classdef ADSBTriggeredCaptureSessionTest < matlab.unittest.TestCase
    %ADSBTRIGGEREDCAPTURESESSIONTEST Regression coverage for the trigger wrapper.

    properties (Access = private)
        TriggerRoot string
    end

    methods (TestClassSetup)
        function addSourcePath(testCase)
            triggerRoot = string(fileparts(mfilename('fullpath')));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(char(triggerRoot)));
            testCase.TriggerRoot = triggerRoot;
            helperTriggerAddProjectPaths();
        end
    end

    methods (TestMethodSetup)
        function resetRandomState(testCase)
            original_rng = rng;
            testCase.addTeardown(@() rng(original_rng));
            rng(29, 'twister');
        end
    end

    methods (Test)
        function testNoTriggerTimeoutWritesArtifacts(testCase)
            [session_root, stage_dir, session_id] = localTempSession(testCase);

            result = runADSBTriggeredCaptureSession( ...
                'SessionID', session_id, ...
                'SessionRoot', session_root, ...
                'ADSBStageDir', stage_dir, ...
                'ShowTriggerPreviewMap', false, ...
                'SaveTriggerPreviewMap', false, ...
                'WatchTimeout_s', 0.05, ...
                'PollPeriod_s', 0.01, ...
                'TailSeconds_s', 0, ...
                'Verbose', false);

            testCase.verifyEqual(result.final_status, "timeout");
            testCase.verifyFalse(result.trigger_fired);
            testCase.verifyEqual(result.capture_info.status, "not_run");
            testCase.verifyTrue(isfile(char(result.artifacts.trigger_summary_txt)));
            testCase.verifyTrue(isfile(char(result.artifacts.trigger_decisions_csv)));
            testCase.verifyTrue(isfile(char(result.artifacts.trigger_context_mat)));
            testCase.verifyEqual(strlength(result.artifacts.session_manifest), 0);
        end

        function testDefaultSessionGeometryResolvesWestFacingAzimuths(testCase)
            [session_root, stage_dir, session_id] = localTempSession(testCase);

            result = runADSBTriggeredCaptureSession( ...
                'SessionID', session_id, ...
                'SessionRoot', session_root, ...
                'ADSBStageDir', stage_dir, ...
                'ShowTriggerPreviewMap', false, ...
                'SaveTriggerPreviewMap', false, ...
                'WatchTimeout_s', 0.05, ...
                'PollPeriod_s', 0.01, ...
                'TailSeconds_s', 0, ...
                'Verbose', false);

            context = localLoadTriggerContext(result);

            testCase.verifyEqual(context.config.CorridorAzimuthCenter_deg, 270.0, 'AbsTol', 1e-12);
            testCase.verifyEqual(context.config.SurveillanceBoresightAzimuth_deg, 270.0, 'AbsTol', 1e-12);
        end

        function testShadowRecommendationRanksWestTargetAndRejectsEastDecoy(testCase)
            [session_root, stage_dir, session_id] = localTempSession(testCase);
            localWriteScenario(stage_dir, session_id, 'include_decoy', true);

            result = runADSBTriggeredCaptureSession( ...
                'SessionID', session_id, ...
                'SessionRoot', session_root, ...
                'ADSBStageDir', stage_dir, ...
                'Mode', 'shadow', ...
                'ShowTriggerPreviewMap', false, ...
                'SaveTriggerPreviewMap', false, ...
                'MinConsecutiveQualifiedPolls', 1, ...
                'WatchTimeout_s', 0.05, ...
                'PollPeriod_s', 0.01, ...
                'TailSeconds_s', 0, ...
                'Verbose', false);

            testCase.verifyEqual(result.final_status, "shadow_recommendation");
            testCase.verifyFalse(result.trigger_fired);
            testCase.verifyGreaterThanOrEqual(height(result.candidate_table), 1);
            testCase.verifyEqual(result.candidate_table.hex(1), "ABC123");
            testCase.verifyTrue(contains(result.trigger_reason, "Shadow recommendation"));
            testCase.verifyLessThan(abs(result.candidate_table.azimuth_deg(1) - 270.0), 10.0);
            testCase.verifyTrue(result.candidate_table.qualified(1));

            decoy_row = result.candidate_table(result.candidate_table.hex == "DEF456", :);

            testCase.verifyEqual(height(decoy_row), 1);
            testCase.verifyFalse(decoy_row.qualified(1));
            testCase.verifyFalse(decoy_row.corridor_gate_pass(1));
            testCase.verifyGreaterThan(result.candidate_table.trigger_score(1), decoy_row.trigger_score(1));
        end

        function testLiveSingleOpportunityCallsCaptureOnceAndWritesManifest(testCase)
            [session_root, stage_dir, session_id] = localTempSession(testCase);
            localWriteScenario(stage_dir, session_id, 'include_decoy', true);

            capture_root = string(tempname(char(testCase.TriggerRoot)));
            mkdir(capture_root);
            testCase.addTeardown(@() localSafeRemoveFolder(capture_root));

            capture_stub = @(varargin) localCaptureStub(capture_root, varargin{:});

            result = runADSBTriggeredCaptureSession( ...
                'SessionID', session_id, ...
                'SessionRoot', session_root, ...
                'ADSBStageDir', stage_dir, ...
                'Mode', 'live', ...
                'ShowTriggerPreviewMap', false, ...
                'SaveTriggerPreviewMap', false, ...
                'MinConsecutiveQualifiedPolls', 1, ...
                'PredictedStartOffsetBounds_s', [0 0], ...
                'WatchTimeout_s', 0.05, ...
                'PollPeriod_s', 0.01, ...
                'TailSeconds_s', 0, ...
                'CaptureFunction', capture_stub, ...
                'Verbose', false);

            testCase.verifyEqual(result.final_status, "captured");
            testCase.verifyTrue(result.trigger_fired);
            testCase.verifyEqual(result.capture_info.status, "captured");
            testCase.verifyTrue(isfile(char(result.artifacts.session_manifest)));
            testCase.verifyNumElements(result.artifacts.packaged_radar_files, 1);

            analysis_setup = helperResolveSessionAnalysisSetup( ...
                session_id, ...
                'DatasetRoot', session_root, ...
                'Verbose', false);
            testCase.verifyEqual(string(analysis_setup.session_id), session_id);
            testCase.verifyNumElements(analysis_setup.adsb_files, numel(result.artifacts.packaged_adsb_files));
        end

        function testCaptureFailurePreservesReadableSummary(testCase)
            [session_root, stage_dir, session_id] = localTempSession(testCase);
            localWriteScenario(stage_dir, session_id, 'include_decoy', false);

            capture_stub = @(varargin) localCaptureFailureStub(varargin{:});

            result = runADSBTriggeredCaptureSession( ...
                'SessionID', session_id, ...
                'SessionRoot', session_root, ...
                'ADSBStageDir', stage_dir, ...
                'Mode', 'live', ...
                'ShowTriggerPreviewMap', false, ...
                'SaveTriggerPreviewMap', false, ...
                'MinConsecutiveQualifiedPolls', 1, ...
                'PredictedStartOffsetBounds_s', [0 0], ...
                'WatchTimeout_s', 0.05, ...
                'PollPeriod_s', 0.01, ...
                'TailSeconds_s', 0, ...
                'CaptureFunction', capture_stub, ...
                'Verbose', false);

            summary_text = string(fileread(char(result.artifacts.trigger_summary_txt)));

            testCase.verifyEqual(result.final_status, "capture_error");
            testCase.verifyTrue(result.trigger_fired);
            testCase.verifyEqual(result.capture_info.status, "error");
            testCase.verifyTrue(contains(summary_text, "capture_error"));
            testCase.verifyTrue(contains(summary_text, "Capture failed"));
        end

        function testSessionPreviewWritesCandidateMapPNG(testCase)
            [session_root, stage_dir, session_id] = localTempSession(testCase);

            result = runADSBTriggeredCaptureSession( ...
                'SessionID', session_id, ...
                'SessionRoot', session_root, ...
                'ADSBStageDir', stage_dir, ...
                'ShowTriggerPreviewMap', false, ...
                'SaveTriggerPreviewMap', true, ...
                'TriggerPreviewGridStep_m', 2000, ...
                'WatchTimeout_s', 0.01, ...
                'PollPeriod_s', 0.01, ...
                'TailSeconds_s', 0, ...
                'Verbose', false);

            summary_text = string(fileread(char(result.artifacts.trigger_summary_txt)));

            testCase.verifyTrue(isfile(char(result.artifacts.trigger_candidate_map_png)));
            testCase.verifyTrue(contains(summary_text, "Preview Map:"));
            testCase.verifyTrue(any(endsWith(result.artifacts.packaged_log_files, "trigger_candidate_map.png")));
        end

        function testSharedGeometryHelperMatchesRuntimeScore(testCase)
            [session_root, stage_dir, session_id] = localTempSession(testCase);
            localWriteScenario(stage_dir, session_id, 'include_decoy', true);

            result = runADSBTriggeredCaptureSession( ...
                'SessionID', session_id, ...
                'SessionRoot', session_root, ...
                'ADSBStageDir', stage_dir, ...
                'Mode', 'shadow', ...
                'ShowTriggerPreviewMap', false, ...
                'SaveTriggerPreviewMap', false, ...
                'MinConsecutiveQualifiedPolls', 1, ...
                'WatchTimeout_s', 0.05, ...
                'PollPeriod_s', 0.01, ...
                'TailSeconds_s', 0, ...
                'Verbose', false);

            loaded = load(char(result.artifacts.trigger_context_mat), 'context');
            context = loaded.context;
            scoring_context = context.score_bundle.scoring_context(1);
            candidate_row = result.candidate_table(1, :);

            evaluation = helperTriggerEvaluateGeometryField( ...
                scoring_context.latest_position_enu_m, ...
                scoring_context.velocity_enu_mps, ...
                context.config, ...
                context.assets, ...
                'FixAge_s', candidate_row.fix_age_s, ...
                'FixCount', candidate_row.n_fixes, ...
                'ApplyFreshnessGate', true);

            testCase.verifyEqual(evaluation.trigger_score(1), candidate_row.trigger_score, 'AbsTol', 1e-12);
            testCase.verifyEqual(evaluation.geometry_score(1), candidate_row.geometry_score, 'AbsTol', 1e-12);
            testCase.verifyEqual(evaluation.rf_proxy_score(1), candidate_row.rf_proxy_score, 'AbsTol', 1e-12);
            testCase.verifyEqual(evaluation.hard_gate_pass(1), candidate_row.hard_gate_pass);
            testCase.verifyEqual(evaluation.qualified(1), candidate_row.qualified);
        end

        function testStandalonePreviewWritesPNGAndReturnsWestFacingQualifiedRegion(testCase)
            output_root = string(tempname(char(testCase.TriggerRoot)));
            mkdir(output_root);
            testCase.addTeardown(@() localSafeRemoveFolder(output_root));

            output_path = fullfile(output_root, 'trigger_candidate_map.png');
            preview = plotADSBTriggerCandidateMap( ...
                'ShowFigure', false, ...
                'SavePNG', true, ...
                'OutputPath', output_path, ...
                'PreviewGridStep_m', 2000, ...
                'Verbose', false);

            testCase.verifyTrue(isfile(char(output_path)));
            testCase.verifyTrue(preview.saved_png);
            testCase.verifyEmpty(preview.figure_handle);
            testCase.verifyGreaterThan(preview.qualified_area_km2, 0);
            testCase.verifyTrue(preview.qualified_region_exists);
            testCase.verifyGreaterThan(preview.max_trigger_score, 0.5);
            testCase.verifyEqual(preview.config_summary.corridor_azimuth_center_deg, 270.0, 'AbsTol', 1e-12);
            testCase.verifyEqual(preview.config_summary.boresight_azimuth_deg, 270.0, 'AbsTol', 1e-12);
            testCase.verifyTrue(any(preview.legend_entries == "Boresight gates"));
            testCase.verifyEqual(preview.overlay_styles.boresight_line_style, ":");
            testCase.verifyEqual(preview.overlay_styles.boresight_color_rgb, [0.85 0.10 0.10], 'AbsTol', 1e-12);
            testCase.verifyLessThan(max(localQualifiedEastSupport(preview)), 0.0);
        end

        function testExplicitAzimuthOverridesCorridorReference(testCase)
            preview = plotADSBTriggerCandidateMap( ...
                'ShowFigure', false, ...
                'SavePNG', false, ...
                'CorridorAzimuthCenter_deg', 270.0, ...
                'SurveillanceBoresightAzimuth_deg', 255.0, ...
                'CorridorReferenceLLA', [42.3656, -71.0096, 10.0], ...
                'PreviewGridStep_m', 2000, ...
                'Verbose', false);

            testCase.verifyEqual(preview.config_summary.corridor_azimuth_center_deg, 270.0, 'AbsTol', 1e-12);
            testCase.verifyEqual(preview.config_summary.boresight_azimuth_deg, 255.0, 'AbsTol', 1e-12);
        end

        function testPreviewHandlesEmptyQualifiedRegionWithoutWarnings(testCase)
            lastwarn('');

            preview = plotADSBTriggerCandidateMap( ...
                'ShowFigure', false, ...
                'SavePNG', false, ...
                'AltitudeBand_m', [1000, 2000], ...
                'PreviewAltitude_m', 5000, ...
                'PreviewGridStep_m', 2000, ...
                'Verbose', false);

            [warning_message, warning_id] = lastwarn;

            testCase.verifyFalse(preview.qualified_region_exists);
            testCase.verifyEqual(preview.qualified_area_km2, 0);
            testCase.verifyEqual(string(warning_message), "");
            testCase.verifyEqual(string(warning_id), "");
            testCase.verifyTrue(contains(preview.qualified_region_message, "No qualified trigger region"));
        end

        function testFrozenBaselineShadowReplayMatchesCurrentBehavior(testCase)
            baseline = helperTriggerPhase1FrozenBaseline();
            [session_root, stage_dir, session_id] = localTempSession(testCase);

            helperTriggerWriteValidationScenario( ...
                stage_dir, ...
                session_id, ...
                'Scenario', baseline.shadow_positive.scenario_name, ...
                'Verbose', false);

            result = runADSBTriggeredCaptureSession( ...
                'SessionID', session_id, ...
                'SessionRoot', session_root, ...
                'ADSBStageDir', stage_dir, ...
                'Mode', 'shadow', ...
                'ShowTriggerPreviewMap', false, ...
                'SaveTriggerPreviewMap', false, ...
                'MinConsecutiveQualifiedPolls', 1, ...
                'WatchTimeout_s', 0.05, ...
                'PollPeriod_s', 0.01, ...
                'TailSeconds_s', 0, ...
                'Verbose', false);

            localVerifyReplayAgainstBaseline(testCase, result, baseline.shadow_positive, baseline.score_tolerance);
        end

        function testFrozenBaselineEastDecoyReplayMatchesCurrentBehavior(testCase)
            baseline = helperTriggerPhase1FrozenBaseline();
            [session_root, stage_dir, session_id] = localTempSession(testCase);

            helperTriggerWriteValidationScenario( ...
                stage_dir, ...
                session_id, ...
                'Scenario', baseline.shadow_negative.scenario_name, ...
                'Verbose', false);

            result = runADSBTriggeredCaptureSession( ...
                'SessionID', session_id, ...
                'SessionRoot', session_root, ...
                'ADSBStageDir', stage_dir, ...
                'Mode', 'shadow', ...
                'ShowTriggerPreviewMap', false, ...
                'SaveTriggerPreviewMap', false, ...
                'MinConsecutiveQualifiedPolls', 1, ...
                'WatchTimeout_s', 0.05, ...
                'PollPeriod_s', 0.01, ...
                'TailSeconds_s', 0, ...
                'Verbose', false);

            localVerifyReplayAgainstBaseline(testCase, result, baseline.shadow_negative, baseline.score_tolerance);
        end

        function testFrozenBaselinePreviewFootprintMatchesCurrentBehavior(testCase)
            baseline = helperTriggerPhase1FrozenBaseline();

            preview = plotADSBTriggerCandidateMap( ...
                'ShowFigure', false, ...
                'SavePNG', false, ...
                'PreviewGridStep_m', baseline.default_preview.preview_grid_step_m, ...
                'Verbose', false);

            testCase.verifyEqual(preview.qualified_region_exists, ...
                baseline.default_preview.expected_qualified_region_exists);
            testCase.verifyEqual(preview.qualified_area_km2, ...
                baseline.default_preview.expected_qualified_area_km2, ...
                'AbsTol', baseline.preview_tolerance);
            testCase.verifyEqual(preview.max_trigger_score, ...
                baseline.default_preview.expected_max_trigger_score, ...
                'AbsTol', baseline.preview_tolerance);
            testCase.verifyEqual(nnz(preview.qualified_grid), ...
                baseline.default_preview.expected_qualified_count);

            qualified_east_axis = preview.east_axis_m(any(preview.qualified_grid, 1));
            testCase.verifyEqual(max(qualified_east_axis), ...
                baseline.default_preview.expected_max_qualified_east_m, ...
                'AbsTol', baseline.preview_tolerance);
            testCase.verifyEqual(find(preview.qualified_grid(:)), ...
                localExpandLinearRuns(baseline.default_preview.expected_qualified_linear_runs));
            testCase.verifyEqual(preview.config_summary.corridor_azimuth_center_deg, ...
                baseline.default_preview.expected_corridor_azimuth_center_deg, ...
                'AbsTol', baseline.preview_tolerance);
            testCase.verifyEqual(preview.config_summary.boresight_azimuth_deg, ...
                baseline.default_preview.expected_boresight_azimuth_deg, ...
                'AbsTol', baseline.preview_tolerance);
        end

        function testOfflineValidationRunnerPassesFrozenPhase1Checks(testCase)
            output_root = string(tempname(char(testCase.TriggerRoot)));
            mkdir(output_root);
            testCase.addTeardown(@() localSafeRemoveFolder(output_root));

            validation = runADSBTriggerOfflineValidation( ...
                'OutputRoot', output_root, ...
                'Verbose', false);

            testCase.verifyTrue(validation.overall_passed);
            testCase.verifyEqual(height(validation.summary_table), 6);
            testCase.verifyTrue(all(validation.summary_table.passed));
            testCase.verifyTrue(isfile(char(validation.artifacts.validation_summary_txt)));
            testCase.verifyTrue(isfile(char(validation.artifacts.validation_summary_csv)));
            testCase.verifyTrue(isfile(char(validation.artifacts.validation_result_mat)));
        end

        function testShellWrapperPassesExplicitWestFacingAzimuthOptions(testCase)
            script_path = fullfile(char(testCase.TriggerRoot), 'run_adsb_triggered_hdtv_capture.sh');
            script_text = string(fileread(script_path));

            testCase.verifyTrue(contains(script_text, "--preflight-only"));
            testCase.verifyTrue(contains(script_text, "runADSBTriggerPreflight"));
            testCase.verifyTrue(contains(script_text, "--surveillance-boresight-azimuth"));
            testCase.verifyTrue(contains(script_text, "--corridor-azimuth-center"));
            testCase.verifyTrue(contains(script_text, "SURVEILLANCE_BORESIGHT_AZIMUTH_DEG=""270"""));
            testCase.verifyTrue(contains(script_text, "CORRIDOR_AZIMUTH_CENTER_DEG=""270"""));
            testCase.verifyTrue(contains(script_text, "'CorridorAzimuthCenter_deg', $CORRIDOR_AZIMUTH_CENTER_DEG"));
            testCase.verifyTrue(contains(script_text, "'SurveillanceBoresightAzimuth_deg', $SURVEILLANCE_BORESIGHT_AZIMUTH_DEG"));
        end
    end
end

function [session_root, stage_dir, session_id] = localTempSession(testCase)
session_root = string(tempname(char(testCase.TriggerRoot)));
stage_dir = string(tempname(char(testCase.TriggerRoot)));
mkdir(session_root);
mkdir(stage_dir);
session_id = "trigger_test_" + string(datetime('now', 'Format', 'yyyyMMddHHmmssSSS')) + "_" + string(randi([1 1e6]));

testCase.addTeardown(@() localSafeRemoveFolder(session_root));
testCase.addTeardown(@() localSafeRemoveFolder(stage_dir));
end

function localWriteScenario(stage_dir, session_id, varargin)
p = inputParser;
addParameter(p, 'include_decoy', true, @islogical);
parse(p, varargin{:});
opts = p.Results;

scenario_name = "west_positive";
if opts.include_decoy
    scenario_name = "west_with_east_decoy";
end

helperTriggerWriteValidationScenario( ...
    stage_dir, ...
    session_id, ...
    'Scenario', scenario_name, ...
    'ReferenceTimeUTC', datetime('now', 'TimeZone', 'UTC'), ...
    'Verbose', false);
end

function capture_info = localCaptureStub(capture_root, varargin)
p = inputParser;
addParameter(p, 'SessionID', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'CaptureDuration_s', 30, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'CaptureFile', "n320_hdtv_capture", @(x) ischar(x) || isstring(x));
addParameter(p, 'RadioName', "Stub", @(x) ischar(x) || isstring(x));
addParameter(p, 'CenterFrequency_Hz', 540e6, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'SampleRate_Hz', 6.144e6, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'LOOffset_Hz', 200e3, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'Gain', [30 50], @isnumeric);
addParameter(p, 'Repetitions', 1, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'RepetitionSpacing_s', 1.0, @(x) isnumeric(x) && isscalar(x));
parse(p, varargin{:});
opts = p.Results;

capture_path = fullfile(capture_root, string(opts.CaptureFile) + "_" + string(opts.SessionID) + ".bb");
file_id = fopen(capture_path, 'w');
if file_id == -1
    error('ADSBTriggeredCaptureSessionTest:captureCreateFailed', ...
        'Could not create %s.', capture_path);
end
fclose(file_id);

capture_info = struct( ...
    'session_id', string(opts.SessionID), ...
    'capture_duration_s', double(opts.CaptureDuration_s), ...
    'capture_repetitions', double(opts.Repetitions), ...
    'capture_repetition_spacing_s', double(opts.RepetitionSpacing_s), ...
    'radar_active_window_s', double(opts.CaptureDuration_s) .* double(opts.Repetitions), ...
    'radar_recorded_iq_seconds_s', double(opts.CaptureDuration_s) .* double(opts.Repetitions), ...
    'capture_file_base', string(opts.CaptureFile), ...
    'radio_name', string(opts.RadioName), ...
    'center_frequency_hz', double(opts.CenterFrequency_Hz), ...
    'sample_rate_hz', double(opts.SampleRate_Hz), ...
    'lo_offset_hz', double(opts.LOOffset_Hz), ...
    'header_center_frequency_hz', double(opts.CenterFrequency_Hz), ...
    'header_lo_offset_hz', double(opts.LOOffset_Hz), ...
    'header_tune_frequency_hz', double(opts.CenterFrequency_Hz + opts.LOOffset_Hz), ...
    'header_sample_rate_hz', double(opts.SampleRate_Hz), ...
    'gain', double(opts.Gain(:).'), ...
    'recording_utc', posixtime(datetime('now', 'TimeZone', 'UTC')), ...
    'local_capture_files', string(capture_path));
end

function capture_info = localCaptureFailureStub(varargin)
capture_info = struct(); %#ok<NASGU>
error('ADSBTriggeredCaptureSessionTest:stubFailure', ...
    'Capture failed in the injected stub.');
end

function context = localLoadTriggerContext(result)
loaded = load(char(result.artifacts.trigger_context_mat), 'context');
context = loaded.context;
end

function east_support_m = localQualifiedEastSupport(preview)
[~, east_idx] = find(preview.qualified_grid);
east_support_m = double(preview.east_axis_m(east_idx));
east_support_m = east_support_m(:);
end

function localVerifyReplayAgainstBaseline(testCase, result, replay_baseline, tolerance)
testCase.verifyEqual(result.final_status, string(replay_baseline.expected_final_status));
testCase.verifyEqual(result.trigger_fired, replay_baseline.expected_trigger_fired);
testCase.verifyEqual(string(result.candidate_table.hex), string(replay_baseline.expected_candidate_hex));
testCase.verifyEqual(logical(result.candidate_table.qualified), logical(replay_baseline.expected_qualified));
testCase.verifyEqual(logical(result.candidate_table.hard_gate_pass), logical(replay_baseline.expected_hard_gate_pass));
testCase.verifyEqual(logical(result.candidate_table.corridor_gate_pass), logical(replay_baseline.expected_corridor_gate_pass));
testCase.verifyEqual(logical(result.candidate_table.boresight_gate_pass), logical(replay_baseline.expected_boresight_gate_pass));
testCase.verifyEqual(double(result.candidate_table.trigger_score), double(replay_baseline.expected_trigger_score), ...
    'AbsTol', tolerance);
testCase.verifyEqual(double(result.candidate_table.geometry_score), double(replay_baseline.expected_geometry_score), ...
    'AbsTol', tolerance);
testCase.verifyEqual(double(result.candidate_table.rf_proxy_score), double(replay_baseline.expected_rf_proxy_score), ...
    'AbsTol', tolerance);
testCase.verifyEqual(double(result.candidate_table.predicted_start_offset_s), ...
    double(replay_baseline.expected_predicted_start_offset_s), ...
    'AbsTol', tolerance);
end

function expanded_idx = localExpandLinearRuns(run_pairs)
expanded_idx = zeros(0, 1);
for idx = 1:size(run_pairs, 1)
    expanded_idx = [expanded_idx; (run_pairs(idx, 1):run_pairs(idx, 2)).']; %#ok<AGROW>
end
end

function localSafeRemoveFolder(folder_path)
folder_path = char(string(folder_path));
if isfolder(folder_path)
    rmdir(folder_path, 's');
end
end
