classdef ADSBTriggeredCaptureSessionTest < matlab.unittest.TestCase
    %ADSBTRIGGEREDCAPTURESESSIONTEST Regression coverage for the trigger wrapper.

    properties (Access = private)
        TriggerRoot string
    end

    methods (TestClassSetup)
        function addSourcePath(testCase)
            triggerRoot = string(fileparts(mfilename('fullpath')));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(char(triggerRoot)));
            testCase.TriggerRoot = triggerRoot;
            helperTriggerAddProjectPaths();
        end
    end

    methods (TestMethodSetup)
        function resetRandomState(testCase)
            original_rng = rng;
            testCase.addTeardown(@() rng(original_rng));
            rng(29, 'twister');
        end
    end

    methods (Test)
        function testNoTriggerTimeoutWritesArtifacts(testCase)
            [session_root, stage_dir, session_id] = localTempSession(testCase);

            result = runADSBTriggeredCaptureSession( ...
                'SessionID', session_id, ...
                'SessionRoot', session_root, ...
                'ADSBStageDir', stage_dir, ...
                'ShowTriggerPreviewMap', false, ...
                'SaveTriggerPreviewMap', false, ...
                'WatchTimeout_s', 0.05, ...
                'PollPeriod_s', 0.01, ...
                'TailSeconds_s', 0, ...
                'Verbose', false);

            testCase.verifyEqual(result.final_status, "timeout");
            testCase.verifyFalse(result.trigger_fired);
            testCase.verifyEqual(result.capture_info.status, "not_run");
            testCase.verifyTrue(isfile(char(result.artifacts.trigger_summary_txt)));
            testCase.verifyTrue(isfile(char(result.artifacts.trigger_decisions_csv)));
            testCase.verifyTrue(isfile(char(result.artifacts.trigger_context_mat)));
            testCase.verifyEqual(strlength(result.artifacts.session_manifest), 0);
        end

        function testDefaultSessionGeometryResolvesWestFacingAzimuths(testCase)
            [session_root, stage_dir, session_id] = localTempSession(testCase);

            result = runADSBTriggeredCaptureSession( ...
                'SessionID', session_id, ...
                'SessionRoot', session_root, ...
                'ADSBStageDir', stage_dir, ...
                'ShowTriggerPreviewMap', false, ...
                'SaveTriggerPreviewMap', false, ...
                'WatchTimeout_s', 0.05, ...
                'PollPeriod_s', 0.01, ...
                'TailSeconds_s', 0, ...
                'Verbose', false);

            context = localLoadTriggerContext(result);

            testCase.verifyEqual(context.config.CorridorAzimuthCenter_deg, 270.0, 'AbsTol', 1e-12);
            testCase.verifyEqual(context.config.SurveillanceBoresightAzimuth_deg, 270.0, 'AbsTol', 1e-12);
        end

        function testShadowRecommendationRanksWestTargetAndRejectsEastDecoy(testCase)
            [session_root, stage_dir, session_id] = localTempSession(testCase);
            localWriteScenario(stage_dir, session_id, 'include_decoy', true);

            result = runADSBTriggeredCaptureSession( ...
                'SessionID', session_id, ...
                'SessionRoot', session_root, ...
                'ADSBStageDir', stage_dir, ...
                'Mode', 'shadow', ...
                'ShowTriggerPreviewMap', false, ...
                'SaveTriggerPreviewMap', false, ...
                'MinConsecutiveQualifiedPolls', 1, ...
                'WatchTimeout_s', 0.05, ...
                'PollPeriod_s', 0.01, ...
                'TailSeconds_s', 0, ...
                'Verbose', false);

            testCase.verifyEqual(result.final_status, "shadow_recommendation");
            testCase.verifyFalse(result.trigger_fired);
            testCase.verifyGreaterThanOrEqual(height(result.candidate_table), 1);
            testCase.verifyEqual(result.candidate_table.hex(1), "ABC123");
            testCase.verifyTrue(contains(result.trigger_reason, "Shadow recommendation"));
            testCase.verifyLessThan(abs(result.candidate_table.azimuth_deg(1) - 270.0), 10.0);
            testCase.verifyTrue(result.candidate_table.qualified(1));

            decoy_row = result.candidate_table(result.candidate_table.hex == "DEF456", :);

            testCase.verifyEqual(height(decoy_row), 1);
            testCase.verifyFalse(decoy_row.qualified(1));
            testCase.verifyFalse(decoy_row.corridor_gate_pass(1));
            testCase.verifyGreaterThan(result.candidate_table.trigger_score(1), decoy_row.trigger_score(1));
        end

        function testLiveSingleOpportunityCallsCaptureOnceAndWritesManifest(testCase)
            [session_root, stage_dir, session_id] = localTempSession(testCase);
            localWriteScenario(stage_dir, session_id, 'include_decoy', true);

            capture_root = string(tempname(char(testCase.TriggerRoot)));
            mkdir(capture_root);
            testCase.addTeardown(@() localSafeRemoveFolder(capture_root));

            capture_stub = @(varargin) localCaptureStub(capture_root, varargin{:});

            result = runADSBTriggeredCaptureSession( ...
                'SessionID', session_id, ...
                'SessionRoot', session_root, ...
                'ADSBStageDir', stage_dir, ...
                'Mode', 'live', ...
                'ShowTriggerPreviewMap', false, ...
                'SaveTriggerPreviewMap', false, ...
                'MinConsecutiveQualifiedPolls', 1, ...
                'PredictedStartOffsetBounds_s', [0 0], ...
                'WatchTimeout_s', 0.05, ...
                'PollPeriod_s', 0.01, ...
                'TailSeconds_s', 0, ...
                'CaptureFunction', capture_stub, ...
                'Verbose', false);

            testCase.verifyEqual(result.final_status, "captured");
            testCase.verifyTrue(result.trigger_fired);
            testCase.verifyEqual(result.capture_info.status, "captured");
            testCase.verifyTrue(isfile(char(result.artifacts.session_manifest)));
            testCase.verifyNumElements(result.artifacts.packaged_radar_files, 1);

            analysis_setup = helperResolveSessionAnalysisSetup( ...
                session_id, ...
                'DatasetRoot', session_root, ...
                'Verbose', false);
            testCase.verifyEqual(string(analysis_setup.session_id), session_id);
            testCase.verifyNumElements(analysis_setup.adsb_files, numel(result.artifacts.packaged_adsb_files));
        end

        function testCaptureFailurePreservesReadableSummary(testCase)
            [session_root, stage_dir, session_id] = localTempSession(testCase);
            localWriteScenario(stage_dir, session_id, 'include_decoy', false);

            capture_stub = @(varargin) localCaptureFailureStub(varargin{:});

            result = runADSBTriggeredCaptureSession( ...
                'SessionID', session_id, ...
                'SessionRoot', session_root, ...
                'ADSBStageDir', stage_dir, ...
                'Mode', 'live', ...
                'ShowTriggerPreviewMap', false, ...
                'SaveTriggerPreviewMap', false, ...
                'MinConsecutiveQualifiedPolls', 1, ...
                'PredictedStartOffsetBounds_s', [0 0], ...
                'WatchTimeout_s', 0.05, ...
                'PollPeriod_s', 0.01, ...
                'TailSeconds_s', 0, ...
                'CaptureFunction', capture_stub, ...
                'Verbose', false);

            summary_text = string(fileread(char(result.artifacts.trigger_summary_txt)));

            testCase.verifyEqual(result.final_status, "capture_error");
            testCase.verifyTrue(result.trigger_fired);
            testCase.verifyEqual(result.capture_info.status, "error");
            testCase.verifyTrue(contains(summary_text, "capture_error"));
            testCase.verifyTrue(contains(summary_text, "Capture failed"));
        end

        function testSessionPreviewWritesCandidateMapPNG(testCase)
            [session_root, stage_dir, session_id] = localTempSession(testCase);

            result = runADSBTriggeredCaptureSession( ...
                'SessionID', session_id, ...
                'SessionRoot', session_root, ...
                'ADSBStageDir', stage_dir, ...
                'ShowTriggerPreviewMap', false, ...
                'SaveTriggerPreviewMap', true, ...
                'TriggerPreviewGridStep_m', 2000, ...
                'WatchTimeout_s', 0.01, ...
                'PollPeriod_s', 0.01, ...
                'TailSeconds_s', 0, ...
                'Verbose', false);

            summary_text = string(fileread(char(result.artifacts.trigger_summary_txt)));

            testCase.verifyTrue(isfile(char(result.artifacts.trigger_candidate_map_png)));
            testCase.verifyTrue(contains(summary_text, "Preview Map:"));
            testCase.verifyTrue(any(endsWith(result.artifacts.packaged_log_files, "trigger_candidate_map.png")));
        end

        function testSharedGeometryHelperMatchesRuntimeScore(testCase)
            [session_root, stage_dir, session_id] = localTempSession(testCase);
            localWriteScenario(stage_dir, session_id, 'include_decoy', true);

            result = runADSBTriggeredCaptureSession( ...
                'SessionID', session_id, ...
                'SessionRoot', session_root, ...
                'ADSBStageDir', stage_dir, ...
                'Mode', 'shadow', ...
                'ShowTriggerPreviewMap', false, ...
                'SaveTriggerPreviewMap', false, ...
                'MinConsecutiveQualifiedPolls', 1, ...
                'WatchTimeout_s', 0.05, ...
                'PollPeriod_s', 0.01, ...
                'TailSeconds_s', 0, ...
                'Verbose', false);

            loaded = load(char(result.artifacts.trigger_context_mat), 'context');
            context = loaded.context;
            scoring_context = context.score_bundle.scoring_context(1);
            candidate_row = result.candidate_table(1, :);

            evaluation = helperTriggerEvaluateGeometryField( ...
                scoring_context.latest_position_enu_m, ...
                scoring_context.velocity_enu_mps, ...
                context.config, ...
                context.assets, ...
                'FixAge_s', candidate_row.fix_age_s, ...
                'FixCount', candidate_row.n_fixes, ...
                'ApplyFreshnessGate', true);

            testCase.verifyEqual(evaluation.trigger_score(1), candidate_row.trigger_score, 'AbsTol', 1e-12);
            testCase.verifyEqual(evaluation.geometry_score(1), candidate_row.geometry_score, 'AbsTol', 1e-12);
            testCase.verifyEqual(evaluation.rf_proxy_score(1), candidate_row.rf_proxy_score, 'AbsTol', 1e-12);
            testCase.verifyEqual(evaluation.hard_gate_pass(1), candidate_row.hard_gate_pass);
            testCase.verifyEqual(evaluation.qualified(1), candidate_row.qualified);
        end

        function testStandalonePreviewWritesPNGAndReturnsWestFacingQualifiedRegion(testCase)
            output_root = string(tempname(char(testCase.TriggerRoot)));
            mkdir(output_root);
            testCase.addTeardown(@() localSafeRemoveFolder(output_root));

            output_path = fullfile(output_root, 'trigger_candidate_map.png');
            preview = plotADSBTriggerCandidateMap( ...
                'ShowFigure', false, ...
                'SavePNG', true, ...
                'OutputPath', output_path, ...
                'PreviewGridStep_m', 2000, ...
                'Verbose', false);

            testCase.verifyTrue(isfile(char(output_path)));
            testCase.verifyTrue(preview.saved_png);
            testCase.verifyEmpty(preview.figure_handle);
            testCase.verifyGreaterThan(preview.qualified_area_km2, 0);
            testCase.verifyTrue(preview.qualified_region_exists);
            testCase.verifyGreaterThan(preview.max_trigger_score, 0.5);
            testCase.verifyEqual(preview.config_summary.corridor_azimuth_center_deg, 270.0, 'AbsTol', 1e-12);
            testCase.verifyEqual(preview.config_summary.boresight_azimuth_deg, 270.0, 'AbsTol', 1e-12);
            testCase.verifyTrue(any(preview.legend_entries == "Boresight gates"));
            testCase.verifyEqual(preview.overlay_styles.boresight_line_style, ":");
            testCase.verifyEqual(preview.overlay_styles.boresight_color_rgb, [0.85 0.10 0.10], 'AbsTol', 1e-12);
            testCase.verifyLessThan(max(localQualifiedEastSupport(preview)), 0.0);
        end

        function testExplicitAzimuthOverridesCorridorReference(testCase)
            preview = plotADSBTriggerCandidateMap( ...
                'ShowFigure', false, ...
                'SavePNG', false, ...
                'CorridorAzimuthCenter_deg', 270.0, ...
                'SurveillanceBoresightAzimuth_deg', 255.0, ...
                'CorridorReferenceLLA', [42.3656, -71.0096, 10.0], ...
                'PreviewGridStep_m', 2000, ...
                'Verbose', false);

            testCase.verifyEqual(preview.config_summary.corridor_azimuth_center_deg, 270.0, 'AbsTol', 1e-12);
            testCase.verifyEqual(preview.config_summary.boresight_azimuth_deg, 255.0, 'AbsTol', 1e-12);
        end

        function testPreviewHandlesEmptyQualifiedRegionWithoutWarnings(testCase)
            lastwarn('');

            preview = plotADSBTriggerCandidateMap( ...
                'ShowFigure', false, ...
                'SavePNG', false, ...
                'AltitudeBand_m', [1000, 2000], ...
                'PreviewAltitude_m', 5000, ...
                'PreviewGridStep_m', 2000, ...
                'Verbose', false);

            [warning_message, warning_id] = lastwarn;

            testCase.verifyFalse(preview.qualified_region_exists);
            testCase.verifyEqual(preview.qualified_area_km2, 0);
            testCase.verifyEqual(string(warning_message), "");
            testCase.verifyEqual(string(warning_id), "");
            testCase.verifyTrue(contains(preview.qualified_region_message, "No qualified trigger region"));
        end

        function testShellWrapperPassesExplicitWestFacingAzimuthOptions(testCase)
            script_path = fullfile(char(testCase.TriggerRoot), 'run_adsb_triggered_hdtv_capture.sh');
            script_text = string(fileread(script_path));

            testCase.verifyTrue(contains(script_text, "--surveillance-boresight-azimuth"));
            testCase.verifyTrue(contains(script_text, "--corridor-azimuth-center"));
            testCase.verifyTrue(contains(script_text, "SURVEILLANCE_BORESIGHT_AZIMUTH_DEG=""270"""));
            testCase.verifyTrue(contains(script_text, "CORRIDOR_AZIMUTH_CENTER_DEG=""270"""));
            testCase.verifyTrue(contains(script_text, "'CorridorAzimuthCenter_deg', $CORRIDOR_AZIMUTH_CENTER_DEG"));
            testCase.verifyTrue(contains(script_text, "'SurveillanceBoresightAzimuth_deg', $SURVEILLANCE_BORESIGHT_AZIMUTH_DEG"));
        end
    end
end

function [session_root, stage_dir, session_id] = localTempSession(testCase)
session_root = string(tempname(char(testCase.TriggerRoot)));
stage_dir = string(tempname(char(testCase.TriggerRoot)));
mkdir(session_root);
mkdir(stage_dir);
session_id = "trigger_test_" + string(datetime('now', 'Format', 'yyyyMMddHHmmssSSS')) + "_" + string(randi([1 1e6]));

testCase.addTeardown(@() localSafeRemoveFolder(session_root));
testCase.addTeardown(@() localSafeRemoveFolder(stage_dir));
end

function localWriteScenario(stage_dir, session_id, varargin)
p = inputParser;
addParameter(p, 'include_decoy', true, @islogical);
parse(p, varargin{:});
opts = p.Results;

rx_lla = [42.2999333, -71.349333, 15.0];
spheroid = wgs84Ellipsoid('meter');
now_utc = datetime('now', 'TimeZone', 'UTC');

aircraft = struct( ...
    'hex', {'ABC123'}, ...
    'callsign', {'WEST1'}, ...
    'ranges_m', {[26e3, 27e3, 28e3]}, ...
    'azimuth_deg', {270.0}, ...
    'altitude_m', {2500}, ...
    'groundspeed_mps', {180}, ...
    'track_deg', {270}, ...
    'vertical_rate_mps', {0});

if opts.include_decoy
    aircraft(2) = struct( ...
        'hex', 'DEF456', ...
        'callsign', 'EASTDEC', ...
        'ranges_m', {[24e3, 24.5e3, 25e3]}, ...
        'azimuth_deg', 75.0, ...
        'altitude_m', 2500, ...
        'groundspeed_mps', 160, ...
        'track_deg', 75, ...
        'vertical_rate_mps', 0);
end

file_name = fullfile(stage_dir, "000_" + string(datetime('now', 'Format', 'yyyyMMdd_HHmmss')) + "_adsb_" + session_id + ".txt");
file_id = fopen(file_name, 'w');
if file_id == -1
    error('ADSBTriggeredCaptureSessionTest:fileOpenFailed', ...
        'Could not create %s.', file_name);
end
cleanup_file = onCleanup(@() fclose(file_id));

for idx = 1:numel(aircraft)
    ac = aircraft(idx);
    timestamps = now_utc + seconds([-10, -5, 0]);
    fprintf(file_id, 'MSG,1,1,1,%s,1,%s,%s,%s,%s,%s,,,,,,,,,,\n', ...
        ac.hex, ...
        localDateString(timestamps(1)), localTimeString(timestamps(1)), ...
        localDateString(timestamps(1)), localTimeString(timestamps(1)), ...
        ac.callsign);

    for fix_idx = 1:numel(timestamps)
        range_m = ac.ranges_m(fix_idx);
        east_m = range_m .* sind(ac.azimuth_deg);
        north_m = range_m .* cosd(ac.azimuth_deg);
        up_m = ac.altitude_m - rx_lla(3);
        [lat_deg, lon_deg, alt_m] = enu2geodetic( ...
            east_m, north_m, up_m, ...
            rx_lla(1), rx_lla(2), rx_lla(3), spheroid);

        fprintf(file_id, 'MSG,3,1,1,%s,1,%s,%s,%s,%s,,%d,,,%s,%s,,,,0\n', ...
            ac.hex, ...
            localDateString(timestamps(fix_idx)), localTimeString(timestamps(fix_idx)), ...
            localDateString(timestamps(fix_idx)), localTimeString(timestamps(fix_idx)), ...
            round(alt_m ./ 0.3048), ...
            sprintf('%.6f', lat_deg), ...
            sprintf('%.6f', lon_deg));

        fprintf(file_id, 'MSG,4,1,1,%s,1,%s,%s,%s,%s,,,%d,%d,,0,,%d\n', ...
            ac.hex, ...
            localDateString(timestamps(fix_idx)), localTimeString(timestamps(fix_idx)), ...
            localDateString(timestamps(fix_idx)), localTimeString(timestamps(fix_idx)), ...
            round(ac.groundspeed_mps ./ 0.5144444), ...
            round(ac.track_deg), ...
            round(ac.vertical_rate_mps ./ 0.00508));
    end
end
end

function capture_info = localCaptureStub(capture_root, varargin)
p = inputParser;
addParameter(p, 'SessionID', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'CaptureDuration_s', 30, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'CaptureFile', "n320_hdtv_capture", @(x) ischar(x) || isstring(x));
addParameter(p, 'RadioName', "Stub", @(x) ischar(x) || isstring(x));
addParameter(p, 'CenterFrequency_Hz', 540e6, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'SampleRate_Hz', 6.144e6, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'LOOffset_Hz', 200e3, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'Gain', [30 50], @isnumeric);
addParameter(p, 'Repetitions', 1, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'RepetitionSpacing_s', 1.0, @(x) isnumeric(x) && isscalar(x));
parse(p, varargin{:});
opts = p.Results;

capture_path = fullfile(capture_root, string(opts.CaptureFile) + "_" + string(opts.SessionID) + ".bb");
file_id = fopen(capture_path, 'w');
if file_id == -1
    error('ADSBTriggeredCaptureSessionTest:captureCreateFailed', ...
        'Could not create %s.', capture_path);
end
fclose(file_id);

capture_info = struct( ...
    'session_id', string(opts.SessionID), ...
    'capture_duration_s', double(opts.CaptureDuration_s), ...
    'capture_repetitions', double(opts.Repetitions), ...
    'capture_repetition_spacing_s', double(opts.RepetitionSpacing_s), ...
    'radar_active_window_s', double(opts.CaptureDuration_s) .* double(opts.Repetitions), ...
    'radar_recorded_iq_seconds_s', double(opts.CaptureDuration_s) .* double(opts.Repetitions), ...
    'capture_file_base', string(opts.CaptureFile), ...
    'radio_name', string(opts.RadioName), ...
    'center_frequency_hz', double(opts.CenterFrequency_Hz), ...
    'sample_rate_hz', double(opts.SampleRate_Hz), ...
    'lo_offset_hz', double(opts.LOOffset_Hz), ...
    'header_center_frequency_hz', double(opts.CenterFrequency_Hz), ...
    'header_lo_offset_hz', double(opts.LOOffset_Hz), ...
    'header_tune_frequency_hz', double(opts.CenterFrequency_Hz + opts.LOOffset_Hz), ...
    'header_sample_rate_hz', double(opts.SampleRate_Hz), ...
    'gain', double(opts.Gain(:).'), ...
    'recording_utc', posixtime(datetime('now', 'TimeZone', 'UTC')), ...
    'local_capture_files', string(capture_path));
end

function capture_info = localCaptureFailureStub(varargin)
capture_info = struct(); %#ok<NASGU>
error('ADSBTriggeredCaptureSessionTest:stubFailure', ...
    'Capture failed in the injected stub.');
end

function context = localLoadTriggerContext(result)
loaded = load(char(result.artifacts.trigger_context_mat), 'context');
context = loaded.context;
end

function east_support_m = localQualifiedEastSupport(preview)
[~, east_idx] = find(preview.qualified_grid);
east_support_m = double(preview.east_axis_m(east_idx));
east_support_m = east_support_m(:);
end

function value = localDateString(time_value)
value = sprintf('%04d/%02d/%02d', year(time_value), month(time_value), day(time_value));
end

function value = localTimeString(time_value)
value = sprintf('%02d:%02d:%06.3f', hour(time_value), minute(time_value), second(time_value));
end

function localSafeRemoveFolder(folder_path)
folder_path = char(string(folder_path));
if isfolder(folder_path)
    rmdir(folder_path, 's');
end
end
