function baseline = helperTriggerPhase1FrozenBaseline()
%HELPERTRIGGERPHASE1FROZENBASELINE Return the frozen Phase 1 trigger baseline.
%
% Plain-language goal:
%   Future trigger-gating experiments need one checked-in comparison target
%   so ranking, qualification, trigger, and preview-footprint deltas are
%   explicit before anyone updates the baseline or runs hardware.

baseline = struct( ...
    'baseline_id', "adsb_trigger_phase1_frozen_20260730", ...
    'approval_rule', "Any intentional delta requires explicit approval before this baseline is updated or used for hardware decisions.", ...
    'shadow_positive', localPositiveReplayBaseline(), ...
    'shadow_negative', localNegativeReplayBaseline(), ...
    'default_preview', localDefaultPreviewBaseline(), ...
    'empty_preview', localEmptyPreviewBaseline(), ...
    'explicit_azimuth_override', localExplicitOverrideBaseline(), ...
    'shell_wrapper', localShellWrapperBaseline(), ...
    'score_tolerance', 1e-12, ...
    'preview_tolerance', 1e-12);

end

function baseline = localPositiveReplayBaseline()
baseline = struct( ...
    'scenario_name', "west_with_east_decoy", ...
    'expected_final_status', "shadow_recommendation", ...
    'expected_trigger_fired', false, ...
    'expected_candidate_hex', ["ABC123"; "DEF456"], ...
    'expected_qualified', logical([true; false]), ...
    'expected_hard_gate_pass', logical([true; false]), ...
    'expected_corridor_gate_pass', logical([true; false]), ...
    'expected_boresight_gate_pass', logical([true; false]), ...
    'expected_trigger_score', [0.607586160470972; 0.305178087284974], ...
    'expected_geometry_score', [0.909611524466940; 0.451111494262590], ...
    'expected_rf_proxy_score', [0.667962249958339; 0.676502574566037], ...
    'expected_predicted_start_offset_s', [0.0; 0.0]);
end

function baseline = localNegativeReplayBaseline()
baseline = struct( ...
    'scenario_name', "east_only_decoy", ...
    'expected_final_status', "timeout", ...
    'expected_trigger_fired', false, ...
    'expected_candidate_hex', "DEF456", ...
    'expected_qualified', false, ...
    'expected_hard_gate_pass', false, ...
    'expected_corridor_gate_pass', false, ...
    'expected_boresight_gate_pass', false, ...
    'expected_trigger_score', 0.305178087284974, ...
    'expected_geometry_score', 0.451111494262590, ...
    'expected_rf_proxy_score', 0.676502574566037, ...
    'expected_predicted_start_offset_s', 0.0);
end

function baseline = localDefaultPreviewBaseline()
baseline = struct( ...
    'preview_grid_step_m', 2000.0, ...
    'expected_qualified_region_exists', true, ...
    'expected_qualified_area_km2', 1152.0, ...
    'expected_max_trigger_score', 0.644498036221326, ...
    'expected_qualified_count', 288, ...
    'expected_max_qualified_east_m', -15639.253181817621, ...
    'expected_corridor_azimuth_center_deg', 270.0, ...
    'expected_boresight_azimuth_deg', 270.0, ...
    'expected_qualified_linear_runs', [ ...
        304 309; ...
        369 380; ...
        437 449; ...
        504 517; ...
        572 586; ...
        640 654; ...
        707 722; ...
        775 791; ...
        843 859; ...
        911 927; ...
        979 995; ...
        1047 1063; ...
        1115 1131; ...
        1183 1199; ...
        1251 1266; ...
        1321 1333; ...
        1390 1400; ...
        1458 1467; ...
        1527 1534; ...
        1596 1602; ...
        1665 1669; ...
        1733 1737; ...
        1802 1804]);
end

function baseline = localEmptyPreviewBaseline()
baseline = struct( ...
    'expected_qualified_region_exists', false, ...
    'expected_qualified_area_km2', 0.0, ...
    'expected_qualified_region_message', "No qualified trigger region exists for the current settings.");
end

function baseline = localExplicitOverrideBaseline()
baseline = struct( ...
    'expected_corridor_azimuth_center_deg', 270.0, ...
    'expected_boresight_azimuth_deg', 255.0);
end

function baseline = localShellWrapperBaseline()
baseline = struct( ...
    'required_snippets', [ ...
        "--preflight-only"; ...
        "runADSBTriggerPreflight"; ...
        "--surveillance-boresight-azimuth"; ...
        "--corridor-azimuth-center"; ...
        "SURVEILLANCE_BORESIGHT_AZIMUTH_DEG=""270"""; ...
        "CORRIDOR_AZIMUTH_CENTER_DEG=""270"""; ...
        "'CorridorAzimuthCenter_deg', $CORRIDOR_AZIMUTH_CENTER_DEG"; ...
        "'SurveillanceBoresightAzimuth_deg', $SURVEILLANCE_BORESIGHT_AZIMUTH_DEG"]);
end
