function scenario_info = helperTriggerWriteValidationScenario(stage_dir, session_id, varargin)
%HELPERTRIGGERWRITEVALIDATIONSCENARIO Write staged ADS-B truth for validation.
%
% Plain-language goal:
%   The frozen Phase 1 trigger baseline needs repeatable staged ADS-B
%   files so future gating changes can be compared offline before anyone
%   spends time on the testing machine.

p = inputParser;
p.FunctionName = mfilename;
addRequired(p, 'stage_dir', @(x) ischar(x) || isstring(x));
addRequired(p, 'session_id', @(x) ischar(x) || isstring(x));
addParameter(p, 'Scenario', "west_with_east_decoy", @localIsScenarioName);
addParameter(p, 'ReferenceTimeUTC', datetime('now', 'TimeZone', 'UTC'), ...
    @(x) isdatetime(x) && isscalar(x));
addParameter(p, 'Verbose', false, @islogical);
parse(p, stage_dir, session_id, varargin{:});
opts = p.Results;

stage_dir = string(stage_dir);
session_id = string(session_id);
scenario_name = string(lower(string(opts.Scenario)));
reference_time_utc = opts.ReferenceTimeUTC;

if strlength(stage_dir) == 0
    error('helperTriggerWriteValidationScenario:missingStageDir', ...
        'Stage directory must not be empty.');
end
if strlength(session_id) == 0
    error('helperTriggerWriteValidationScenario:missingSessionID', ...
        'Session ID must not be empty.');
end

if exist(stage_dir, 'dir') ~= 7
    mkdir(stage_dir);
end

rx_lla = [42.2999333, -71.349333, 15.0];
aircraft = localScenarioAircraft(scenario_name);
file_name = fullfile(stage_dir, ...
    "000_" + string(datetime(reference_time_utc, 'Format', 'yyyyMMdd_HHmmss')) + ...
    "_adsb_" + session_id + ".txt");

file_id = -1;
try
    file_id = fopen(file_name, 'w');
    if file_id == -1
        error('helperTriggerWriteValidationScenario:fileOpenFailed', ...
            'Could not create %s.', file_name);
    end

    spheroid = wgs84Ellipsoid('meter');
    for idx = 1:numel(aircraft)
        ac = aircraft(idx);
        timestamps = reference_time_utc + seconds([-10, -5, 0]);
        fprintf(file_id, 'MSG,1,1,1,%s,1,%s,%s,%s,%s,%s,,,,,,,,,,\n', ...
            ac.hex, ...
            localDateString(timestamps(1)), localTimeString(timestamps(1)), ...
            localDateString(timestamps(1)), localTimeString(timestamps(1)), ...
            ac.callsign);

        for fix_idx = 1:numel(timestamps)
            range_m = ac.ranges_m(fix_idx);
            east_m = range_m .* sind(ac.azimuth_deg);
            north_m = range_m .* cosd(ac.azimuth_deg);
            up_m = ac.altitude_m - rx_lla(3);
            [lat_deg, lon_deg, alt_m] = enu2geodetic( ...
                east_m, north_m, up_m, ...
                rx_lla(1), rx_lla(2), rx_lla(3), spheroid);

            fprintf(file_id, 'MSG,3,1,1,%s,1,%s,%s,%s,%s,,%d,,,%s,%s,,,,0\n', ...
                ac.hex, ...
                localDateString(timestamps(fix_idx)), localTimeString(timestamps(fix_idx)), ...
                localDateString(timestamps(fix_idx)), localTimeString(timestamps(fix_idx)), ...
                round(alt_m ./ 0.3048), ...
                sprintf('%.6f', lat_deg), ...
                sprintf('%.6f', lon_deg));

            fprintf(file_id, 'MSG,4,1,1,%s,1,%s,%s,%s,%s,,,%d,%d,,0,,%d\n', ...
                ac.hex, ...
                localDateString(timestamps(fix_idx)), localTimeString(timestamps(fix_idx)), ...
                localDateString(timestamps(fix_idx)), localTimeString(timestamps(fix_idx)), ...
                round(ac.groundspeed_mps ./ 0.5144444), ...
                round(ac.track_deg), ...
                round(ac.vertical_rate_mps ./ 0.00508));
        end
    end

    fclose(file_id);
    file_id = -1;
catch me_write
    if file_id ~= -1
        fclose(file_id);
    end
    error('helperTriggerWriteValidationScenario:writeFailed', ...
        'Could not write the %s scenario: %s', scenario_name, me_write.message);
end

scenario_info = struct( ...
    'scenario_name', scenario_name, ...
    'session_id', session_id, ...
    'stage_dir', stage_dir, ...
    'stage_file', string(file_name), ...
    'reference_time_utc', reference_time_utc, ...
    'aircraft_hex', string({aircraft.hex}).');

if opts.Verbose
    fprintf('[helperTriggerWriteValidationScenario] Scenario .... %s\n', char(scenario_name));
    fprintf('[helperTriggerWriteValidationScenario] Stage file .. %s\n', char(scenario_info.stage_file));
    fprintf('[helperTriggerWriteValidationScenario] Aircraft .... %s\n', ...
        char(strjoin(scenario_info.aircraft_hex, ", ")));
end

end

function tf = localIsScenarioName(value)
tf = any(strcmpi(string(value), [ ...
    "west_positive", ...
    "west_with_east_decoy", ...
    "east_only_decoy"]));
end

function aircraft = localScenarioAircraft(scenario_name)
west_aircraft = struct( ...
    'hex', 'ABC123', ...
    'callsign', 'WEST1', ...
    'ranges_m', [26e3, 27e3, 28e3], ...
    'azimuth_deg', 270.0, ...
    'altitude_m', 2500, ...
    'groundspeed_mps', 180, ...
    'track_deg', 270, ...
    'vertical_rate_mps', 0);

east_decoy = struct( ...
    'hex', 'DEF456', ...
    'callsign', 'EASTDEC', ...
    'ranges_m', [24e3, 24.5e3, 25e3], ...
    'azimuth_deg', 75.0, ...
    'altitude_m', 2500, ...
    'groundspeed_mps', 160, ...
    'track_deg', 75, ...
    'vertical_rate_mps', 0);

switch scenario_name
    case "west_positive"
        aircraft = west_aircraft;
    case "west_with_east_decoy"
        aircraft = [west_aircraft, east_decoy];
    case "east_only_decoy"
        aircraft = east_decoy;
    otherwise
        error('helperTriggerWriteValidationScenario:unsupportedScenario', ...
            'Unsupported scenario %s.', scenario_name);
end
end

function value = localDateString(time_value)
value = sprintf('%04d/%02d/%02d', year(time_value), month(time_value), day(time_value));
end

function value = localTimeString(time_value)
value = sprintf('%02d:%02d:%06.3f', hour(time_value), minute(time_value), second(time_value));
end
