function score_bundle = helperTriggerScoreCandidates(adsb_tracks, config, assets)
%HELPERTRIGGERSCORECANDIDATES Rank ADS-B aircraft for one trigger poll.
%
% Plain-language goal:
%   The wrapper does not claim calibrated probability of detection in
%   Phase 1. Instead it scores each aircraft with three layers:
%   1) hard corridor gates,
%   2) geometry and time-to-window ranking,
%   3) a coarse RF prior seeded from the saved mission summary and RF budget.

candidate_table = localEmptyCandidateTable();
score_bundle = struct( ...
    'candidate_table', candidate_table, ...
    'adsb_bistatic', struct([]), ...
    'geometry', helperDeriveTxRxGeometry(config.TxLLA, config.RxLLA), ...
    'scoring_notes', "No ADS-B tracks were available.");

if isempty(adsb_tracks)
    return
end

score_bundle.geometry = helperDeriveTxRxGeometry(config.TxLLA, config.RxLLA);
score_bundle.scoring_notes = "Proxy scoring is active.";
spheroid = score_bundle.geometry.spheroid;

adsb_bistatic = struct([]);
evalc('adsb_bistatic = adsbToBistatic(adsb_tracks, config.TxLLA, config.RxLLA, config.CenterFrequency_Hz);');
score_bundle.adsb_bistatic = adsb_bistatic;

if isempty(adsb_bistatic)
    return
end

now_unix = posixtime(config.NowUTC);
for idx = 1:numel(adsb_bistatic)
    bist_track = adsb_bistatic(idx);
    src_idx = find(strcmpi(string({adsb_tracks.hex}), string(bist_track.hex)), 1, 'first');
    if isempty(src_idx)
        continue
    end
    src_track = adsb_tracks(src_idx);

    [track_row, scoring_context] = localScoreOneTrack( ...
        bist_track, src_track, spheroid, now_unix, config, assets);

    candidate_table = [candidate_table; track_row]; %#ok<AGROW>
    score_bundle.scoring_context(idx, 1) = scoring_context;
end

if isempty(candidate_table)
    return
end

candidate_table = sortrows(candidate_table, {'trigger_score', 'geometry_score', 'receiver_range_m'}, ...
    {'descend', 'descend', 'ascend'});
candidate_table.rank = (1:height(candidate_table)).';

score_bundle.candidate_table = candidate_table;

end

function [track_row, scoring_context] = localScoreOneTrack( ...
    bist_track, src_track, spheroid, now_unix, config, assets)

[enu_e, enu_n, enu_u] = geodetic2enu( ...
    bist_track.lat_deg, bist_track.lon_deg, bist_track.alt_m, ...
    config.RxLLA(1), config.RxLLA(2), config.RxLLA(3), spheroid);

latest_pos_enu_m = [enu_e(end); enu_n(end); enu_u(end)];
latest_fix_utc = double(bist_track.t_utc(end));
fix_age_s = max(now_unix - latest_fix_utc, 0.0);
n_fixes = numel(bist_track.t_utc);

velocity_enu_mps = localEstimateVelocity(src_track, bist_track, enu_e, enu_n, enu_u);
evaluation = helperTriggerEvaluateGeometryField( ...
    latest_pos_enu_m, velocity_enu_mps, config, assets, ...
    'FixAge_s', fix_age_s, ...
    'FixCount', n_fixes, ...
    'ApplyFreshnessGate', true);

rationale = localBuildRationale( ...
    bist_track, ...
    evaluation.latest_receiver_range_m(1), ...
    bist_track.alt_m(end), ...
    evaluation.latest_azimuth_deg(1), ...
    evaluation.geometry_score(1), ...
    evaluation.rf_proxy_score(1), ...
    evaluation.trigger_score(1), ...
    evaluation.predicted_start_offset_s(1), ...
    evaluation.hard_gate_pass(1), ...
    evaluation.qualified(1), ...
    config);

track_row = table( ...
    0, ...
    string(bist_track.hex), ...
    string(bist_track.callsign), ...
    latest_fix_utc, ...
    fix_age_s, ...
    n_fixes, ...
    evaluation.latest_receiver_range_m(1), ...
    bist_track.alt_m(end), ...
    evaluation.latest_azimuth_deg(1), ...
    evaluation.latest_elevation_deg(1), ...
    bist_track.R_excess_m(end), ...
    evaluation.best_bistatic_angle_deg(1), ...
    evaluation.hard_gate_pass(1), ...
    evaluation.altitude_gate_pass(1), ...
    evaluation.range_gate_pass(1), ...
    evaluation.corridor_gate_pass(1), ...
    evaluation.boresight_gate_pass(1), ...
    evaluation.freshness_gate_pass(1), ...
    evaluation.geometry_score(1), ...
    evaluation.rf_proxy_score(1), ...
    evaluation.trigger_score(1), ...
    evaluation.predicted_start_offset_s(1), ...
    evaluation.proxy_pd(1), ...
    evaluation.proxy_only, ...
    evaluation.qualified(1), ...
    string(rationale), ...
    'VariableNames', localCandidateVariableNames());

scoring_context = struct( ...
    'hex', string(bist_track.hex), ...
    'latest_position_enu_m', latest_pos_enu_m(:).', ...
    'velocity_enu_mps', velocity_enu_mps(:).', ...
    'window_offsets_s', evaluation.window_offsets_s, ...
    'geometry_sequence', evaluation.geometry_sequence, ...
    'corridor_score', evaluation.corridor_score, ...
    'boresight_score', evaluation.boresight_score, ...
    'range_score', evaluation.range_score, ...
    'bistatic_score', evaluation.bistatic_score, ...
    'predicted_ranges_m', evaluation.predicted_ranges_m, ...
    'predicted_altitudes_m', evaluation.predicted_altitudes_m, ...
    'predicted_bistatic_angle_deg', evaluation.predicted_bistatic_angle_deg, ...
    'predicted_bistatic_excess_m', evaluation.predicted_bistatic_excess_m);

end

function velocity_enu_mps = localEstimateVelocity(src_track, bist_track, enu_e, enu_n, enu_u)
velocity_enu_mps = zeros(3, 1);

finite_speed_idx = find(isfinite(src_track.speed_mps) & isfinite(src_track.track_deg), 1, 'last');
if ~isempty(finite_speed_idx)
    groundspeed_mps = double(src_track.speed_mps(finite_speed_idx));
    track_deg = double(src_track.track_deg(finite_speed_idx));
    vertical_rate_mps = localLatestFinite(src_track.vrate_mps, 0.0);

    velocity_enu_mps(1) = groundspeed_mps .* sind(track_deg);
    velocity_enu_mps(2) = groundspeed_mps .* cosd(track_deg);
    velocity_enu_mps(3) = vertical_rate_mps;
    return
end

if numel(bist_track.t_utc) < 2
    return
end

fit_count = min(numel(bist_track.t_utc), 4);
fit_idx = (numel(bist_track.t_utc) - fit_count + 1):numel(bist_track.t_utc);
t_fit = double(bist_track.t_utc(fit_idx));
t_fit = t_fit - t_fit(1);
t_fit = max(t_fit, 1e-3 .* (0:(numel(t_fit) - 1)).');

coeff_e = polyfit(t_fit, enu_e(fit_idx), 1);
coeff_n = polyfit(t_fit, enu_n(fit_idx), 1);
coeff_u = polyfit(t_fit, enu_u(fit_idx), 1);

velocity_enu_mps(1) = coeff_e(1);
velocity_enu_mps(2) = coeff_n(1);
velocity_enu_mps(3) = coeff_u(1);
end

function rationale = localBuildRationale( ...
    bist_track, receiver_range_m, altitude_m, azimuth_deg, ...
    geometry_score, rf_proxy_score, trigger_score, predicted_start_offset_s, ...
    hard_gate_pass, qualified, config)

state_word = "watch_only";
if qualified
    state_word = "qualified";
elseif hard_gate_pass
    state_word = "scored_below_threshold";
end

proxy_text = "proxy_only";
if isfinite(config.ReferenceChainPenalty_dB)
    proxy_text = "proxy_with_penalty";
end

rationale = sprintf([ ...
    '%s %s range=%.1f km alt=%.0f m az=%.1f deg ' ...
    'geometry=%.3f rf=%.3f trigger=%.3f bestOffset=%.1f s %s'], ...
    char(state_word), ...
    char(string(bist_track.hex)), ...
    receiver_range_m ./ 1e3, ...
    altitude_m, ...
    azimuth_deg, ...
    geometry_score, ...
    rf_proxy_score, ...
    trigger_score, ...
    predicted_start_offset_s, ...
    char(proxy_text));
end

function names = localCandidateVariableNames()
names = { ...
    'rank', ...
    'hex', ...
    'callsign', ...
    'latest_fix_utc', ...
    'fix_age_s', ...
    'n_fixes', ...
    'receiver_range_m', ...
    'altitude_m', ...
    'azimuth_deg', ...
    'elevation_deg', ...
    'bistatic_range_excess_m', ...
    'bistatic_angle_deg', ...
    'hard_gate_pass', ...
    'altitude_gate_pass', ...
    'range_gate_pass', ...
    'corridor_gate_pass', ...
    'boresight_gate_pass', ...
    'freshness_gate_pass', ...
    'geometry_score', ...
    'rf_proxy_score', ...
    'trigger_score', ...
    'predicted_start_offset_s', ...
    'proxy_pd', ...
    'proxy_only', ...
    'qualified', ...
    'rationale'};
end

function candidate_table = localEmptyCandidateTable()
candidate_table = table( ...
    zeros(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    false(0, 1), ...
    false(0, 1), ...
    false(0, 1), ...
    false(0, 1), ...
    false(0, 1), ...
    false(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    false(0, 1), ...
    false(0, 1), ...
    strings(0, 1), ...
    'VariableNames', localCandidateVariableNames());
end

function value_out = localLatestFinite(values, default_value)
value_out = default_value;
finite_idx = find(isfinite(values), 1, 'last');
if ~isempty(finite_idx)
    value_out = double(values(finite_idx));
end
end
