function manifest_path = helperTriggerWriteManifest(session_result, package_info, config)
%HELPERTRIGGERWRITEMANIFEST Write session_manifest.json for triggered runs.
%
% Plain-language goal:
%   When radar data exists, the trigger wrapper should hand off a packaged
%   session that looks like the current manual-capture artifact plus one
%   extra `triggering` block.

manifest_path = "";
if ~isfield(package_info, 'packaged_radar_rel') || isempty(package_info.packaged_radar_rel)
    return
end

manifest_path = fullfile(package_info.session_dir, 'session_manifest.json');

capture_info = session_result.capture_info;
triggering = struct( ...
    'mode', session_result.mode, ...
    'opportunity_policy', session_result.opportunity_policy, ...
    'trigger_fired', session_result.trigger_fired, ...
    'trigger_reason', session_result.trigger_reason, ...
    'proxy_label', session_result.proxy_label, ...
    'reference_chain_penalty_db', config.ReferenceChainPenalty_dB, ...
    'watch_started_utc', session_result.watch_started_utc, ...
    'watch_stopped_utc', session_result.watch_stopped_utc, ...
    'candidate_table', session_result.candidate_table);

manifest = struct( ...
    'manifest_version', 2, ...
    'session_id', session_result.session_id, ...
    'session_folder', session_result.session_id, ...
    'session_created_utc', datetime('now', 'TimeZone', 'UTC', ...
        'Format', 'yyyy-MM-dd''T''HH:mm:ss''Z'''), ...
    'capture_duration_s', config.CaptureDuration_s, ...
    'capture_repetitions', config.Repetitions, ...
    'capture_repetition_spacing_s', config.RepetitionSpacing_s, ...
    'radar_active_window_s', config.Repetitions .* config.CaptureDuration_s + ...
        max(config.Repetitions - 1, 0) .* config.RepetitionSpacing_s, ...
    'radar_recorded_iq_seconds_s', config.Repetitions .* config.CaptureDuration_s, ...
    'tail_seconds_s', config.TailSeconds_s, ...
    'adsb_rotation_s', config.ADSBRotation_s, ...
    'poll_period_s', config.PollPeriod_s, ...
    'capture_file_base', config.CaptureFile, ...
    'gain_spec', localGainSpec(config.Gain), ...
    'pi_host', config.PiHost, ...
    'pi_user', config.PiUser, ...
    'remote_log_file', config.RemoteLogFile, ...
    'radar_epoch_utc', localNumericField(capture_info, 'recording_utc', NaN), ...
    'sdr_defaults', struct( ...
        'radio_name', config.RadioName, ...
        'center_frequency_hz', config.CenterFrequency_Hz, ...
        'sample_rate_hz', config.SampleRate_Hz, ...
        'lo_offset_hz', config.LOOffset_Hz), ...
    'header_readback', struct( ...
        'center_frequency_hz', localNumericField(capture_info, 'header_center_frequency_hz', NaN), ...
        'sample_rate_hz', localNumericField(capture_info, 'header_sample_rate_hz', NaN), ...
        'lo_offset_hz', localNumericField(capture_info, 'header_lo_offset_hz', NaN), ...
        'tune_frequency_hz', localNumericField(capture_info, 'header_tune_frequency_hz', NaN)), ...
    'triggering', triggering, ...
    'radar_files', package_info.packaged_radar_rel, ...
    'adsb_files', package_info.packaged_adsb_rel, ...
    'log_files', package_info.packaged_log_rel);

json_text = jsonencode(helperTriggerPrepareForJSON(manifest));
file_id = fopen(manifest_path, 'w');
if file_id == -1
    error('helperTriggerWriteManifest:fileOpenFailed', ...
        'Could not open %s for writing.', manifest_path);
end
cleanup_file = onCleanup(@() fclose(file_id));
fprintf(file_id, '%s', json_text);
clear cleanup_file

end

function gain_spec = localGainSpec(gain_value)
gain_value = double(gain_value(:).');
gain_spec = strjoin(arrayfun(@(x) sprintf('%.12g', x), gain_value, ...
    'UniformOutput', false), ',');
end

function value = localNumericField(source_struct, field_name, default_value)
value = default_value;
if isstruct(source_struct) && isfield(source_struct, field_name)
    field_value = double(source_struct.(field_name));
    if ~isempty(field_value)
        value = field_value(1);
    end
end
end
