function preview_result = plotADSBTriggerCandidateMap(varargin)
%PLOTADSBTRIGGERCANDIDATEMAP Plot the trigger candidate region on a map.
%
% Example:
%   preview = plotADSBTriggerCandidateMap( ...
%       'ShowFigure', false, ...
%       'SavePNG', true, ...
%       'OutputPath', fullfile(tempdir, 'trigger_candidate_map.png'));
%
% Public name-value groups:
%   Geometry settings:
%       'TxLLA', 'RxLLA', 'CorridorAzimuthCenter_deg',
%       'CorridorReferenceLLA',
%       'SurveillanceBoresightAzimuth_deg'
%   Scoring thresholds:
%       'QualifiedTriggerScore', 'ReferenceChainPenalty_dB',
%       'PredictedStartOffsetBounds_s'
%   Preview settings:
%       'PreviewAltitude_m', 'PreviewGridStep_m',
%       'PreviewRangeMargin_m', 'ShowFigure', 'SavePNG', 'OutputPath'

repo_info = helperTriggerAddProjectPaths();
default_mission_report = fullfile(repo_info.repo_root, 'TestSetupTesting', ...
    'MissionReport_LoganCorridor.mat');
default_rf_budget = fullfile(repo_info.repo_root, 'SystemPrechecks', ...
    'RFBudget', 'DTV_RFBudgetAnalysis.mat');

p = inputParser;
p.FunctionName = mfilename;

addParameter(p, 'TxLLA', [42.310278, -71.236667, 431.9], @(x) isnumeric(x) && numel(x) == 3);
addParameter(p, 'RxLLA', [42.2999333, -71.349333, 15.0], @(x) isnumeric(x) && numel(x) == 3);
addParameter(p, 'CorridorAzimuthCenter_deg', NaN, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'CorridorReferenceLLA', [NaN NaN NaN], @(x) isnumeric(x) && numel(x) == 3);
addParameter(p, 'SurveillanceBoresightAzimuth_deg', NaN, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'SurveillanceBoresightElevation_deg', 0, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'CorridorAzimuthHalfWidth_deg', 35, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'BoresightAzimuthHalfWidth_deg', 50, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'BoresightElevationHalfWidth_deg', 20, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'AltitudeBand_m', [1000 5000], @(x) isnumeric(x) && numel(x) == 2 && x(2) > x(1));
addParameter(p, 'ReceiverRangeBand_m', [15e3 60e3], @(x) isnumeric(x) && numel(x) == 2 && x(2) > x(1));

addParameter(p, 'QualifiedTriggerScore', 0.45, @(x) isnumeric(x) && isscalar(x) && x >= 0 && x <= 1);
addParameter(p, 'PredictedStartOffsetBounds_s', [0 15], ...
    @(x) isnumeric(x) && numel(x) == 2 && all(isfinite(x)) && x(1) >= 0 && x(2) >= x(1));
addParameter(p, 'ReferenceChainPenalty_dB', NaN, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'MaxFixAge_s', 30, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'MinimumTrackFixCount', 2, @(x) isnumeric(x) && isscalar(x) && x >= 1);

addParameter(p, 'CenterFrequency_Hz', 540e6, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'MissionReportPath', default_mission_report, @(x) ischar(x) || isstring(x));
addParameter(p, 'RFBudgetPath', default_rf_budget, @(x) ischar(x) || isstring(x));

addParameter(p, 'PreviewAltitude_m', NaN, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'PreviewGridStep_m', 500, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'PreviewRangeMargin_m', 5000, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'ShowFigure', true, @islogical);
addParameter(p, 'SavePNG', true, @islogical);
addParameter(p, 'OutputPath', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'Basemap', "streets-light", @(x) ischar(x) || isstring(x));
addParameter(p, 'Verbose', true, @islogical);

parse(p, varargin{:});
opts = p.Results;

[corridor_azimuth_deg, boresight_azimuth_deg] = helperTriggerResolveBoresightAzimuth( ...
    opts.RxLLA, ...
    opts.CorridorReferenceLLA, ...
    opts.CorridorAzimuthCenter_deg, ...
    opts.SurveillanceBoresightAzimuth_deg);

config = struct( ...
    'TxLLA', double(opts.TxLLA(:).'), ...
    'RxLLA', double(opts.RxLLA(:).'), ...
    'CorridorReferenceLLA', double(opts.CorridorReferenceLLA(:).'), ...
    'CorridorAzimuthCenter_deg', corridor_azimuth_deg, ...
    'SurveillanceBoresightAzimuth_deg', boresight_azimuth_deg, ...
    'SurveillanceBoresightElevation_deg', double(opts.SurveillanceBoresightElevation_deg), ...
    'CorridorAzimuthHalfWidth_deg', double(opts.CorridorAzimuthHalfWidth_deg), ...
    'BoresightAzimuthHalfWidth_deg', double(opts.BoresightAzimuthHalfWidth_deg), ...
    'BoresightElevationHalfWidth_deg', double(opts.BoresightElevationHalfWidth_deg), ...
    'AltitudeBand_m', double(opts.AltitudeBand_m(:).'), ...
    'ReceiverRangeBand_m', double(opts.ReceiverRangeBand_m(:).'), ...
    'WindowOffsetGrid_s', double(helperTriggerBuildWindowOffsetGrid(opts.PredictedStartOffsetBounds_s)), ...
    'QualifiedTriggerScore', double(opts.QualifiedTriggerScore), ...
    'ReferenceChainPenalty_dB', double(opts.ReferenceChainPenalty_dB), ...
    'CenterFrequency_Hz', double(opts.CenterFrequency_Hz), ...
    'MaxFixAge_s', double(opts.MaxFixAge_s), ...
    'MinimumTrackFixCount', double(opts.MinimumTrackFixCount));

assets = helperTriggerResolveAssets( ...
    'MissionReportPath', opts.MissionReportPath, ...
    'RFBudgetPath', opts.RFBudgetPath);

preview_result = helperTriggerRenderCandidateMap( ...
    config, assets, ...
    'OutputPath', opts.OutputPath, ...
    'ShowFigure', opts.ShowFigure, ...
    'SavePNG', opts.SavePNG, ...
    'Altitude_m', opts.PreviewAltitude_m, ...
    'GridStep_m', opts.PreviewGridStep_m, ...
    'RangeMargin_m', opts.PreviewRangeMargin_m, ...
    'Basemap', opts.Basemap, ...
    'Verbose', opts.Verbose);

end
