function session_result = runADSBTriggeredCaptureSession(varargin)
%RUNADSBTRIGGEREDCAPTURESESSION Phase-1 ADS-B-triggered capture supervisor.
%
% Example:
%   result = runADSBTriggeredCaptureSession( ...
%       'Mode', 'shadow', ...
%       'SessionID', '20260728T153000');
%
% Public name-value groups:
%   Pi/logger settings:
%       'PiUser', 'PiHost', 'PiWorkingDir', 'PiLoggerScript',
%       'RemoteLogFile', 'ADSBStageDir', 'CoordinatorControlDir'
%   Geometry settings:
%       'TxLLA', 'RxLLA', 'CorridorAzimuthCenter_deg',
%       'CorridorReferenceLLA',
%       'SurveillanceBoresightAzimuth_deg'
%   Scoring thresholds:
%       'QualifiedTriggerScore', 'MaxFixAge_s',
%       'MinConsecutiveQualifiedPolls', 'ReferenceChainPenalty_dB'
%   Capture settings:
%       'CaptureDuration_s', 'CaptureFile', 'RadioName',
%       'CenterFrequency_Hz', 'SampleRate_Hz', 'LOOffset_Hz', 'Gain'
%   Session limits and mode flags:
%       'Mode', 'OpportunityPolicy', 'WatchTimeout_s',
%       'PollPeriod_s', 'ADSBRotation_s', 'TailSeconds_s'
%
% Phase-1 note:
%   The returned trigger score is a proxy likelihood ranking. Unless
%   ReferenceChainPenalty_dB is supplied, the wrapper does not report Pd.

repo_info = helperTriggerAddProjectPaths();
default_session_root = fullfile(repo_info.repo_root, 'captures');
default_mission_report = fullfile(repo_info.repo_root, 'TestSetupTesting', ...
    'MissionReport_LoganCorridor.mat');
default_rf_budget = fullfile(repo_info.repo_root, 'SystemPrechecks', ...
    'RFBudget', 'DTV_RFBudgetAnalysis.mat');

p = inputParser;
p.FunctionName = mfilename;

addParameter(p, 'SessionID', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'Mode', "shadow", @localIsMode);
addParameter(p, 'OpportunityPolicy', "single", @localIsOpportunityPolicy);
addParameter(p, 'WatchTimeout_s', 600, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'PollPeriod_s', 5, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'ADSBRotation_s', 5, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'TailSeconds_s', 5, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'WaitForCoordinatorFinalization_s', 45, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'MinConsecutiveQualifiedPolls', 2, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1);
addParameter(p, 'QualifiedTriggerScore', 0.45, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 0 && x <= 1);
addParameter(p, 'MaxFixAge_s', 30, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'MinimumTrackFixCount', 2, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1);
addParameter(p, 'PredictedStartOffsetBounds_s', [0 15], ...
    @(x) isnumeric(x) && numel(x) == 2 && all(isfinite(x)) && x(1) >= 0 && x(2) >= x(1));
addParameter(p, 'ReferenceChainPenalty_dB', NaN, ...
    @(x) isnumeric(x) && isscalar(x));

addParameter(p, 'SessionRoot', default_session_root, @(x) ischar(x) || isstring(x));
addParameter(p, 'ADSBStageDir', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'CoordinatorControlDir', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'CoordinatorStatusFile', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'RemoteLogLocalPath', "", @(x) ischar(x) || isstring(x));

addParameter(p, 'PiUser', "pi2", @(x) ischar(x) || isstring(x));
addParameter(p, 'PiHost', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'PiWorkingDir', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'PiLoggerScript', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'RemoteLogFile', "", @(x) ischar(x) || isstring(x));

addParameter(p, 'TxLLA', [42.310278, -71.236667, 431.9], ...
    @(x) isnumeric(x) && numel(x) == 3);
addParameter(p, 'RxLLA', [42.2999333, -71.349333, 15.0], ...
    @(x) isnumeric(x) && numel(x) == 3);
addParameter(p, 'CorridorAzimuthCenter_deg', NaN, ...
    @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'CorridorReferenceLLA', [NaN NaN NaN], ...
    @(x) isnumeric(x) && numel(x) == 3);
addParameter(p, 'SurveillanceBoresightAzimuth_deg', NaN, ...
    @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'SurveillanceBoresightElevation_deg', 0, ...
    @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'CorridorAzimuthHalfWidth_deg', 35, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'BoresightAzimuthHalfWidth_deg', 50, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'BoresightElevationHalfWidth_deg', 20, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'AltitudeBand_m', [1000 5000], ...
    @(x) isnumeric(x) && numel(x) == 2 && x(2) > x(1));
addParameter(p, 'ReceiverRangeBand_m', [15e3 60e3], ...
    @(x) isnumeric(x) && numel(x) == 2 && x(2) > x(1));

addParameter(p, 'CaptureDuration_s', 30, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'CaptureFile', "n320_hdtv_capture", @(x) ischar(x) || isstring(x));
addParameter(p, 'RadioName', "My USRP N320", @(x) ischar(x) || isstring(x));
addParameter(p, 'CenterFrequency_Hz', 540e6, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'SampleRate_Hz', 6.144e6, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'LOOffset_Hz', 200e3, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'Gain', [30 50], @(x) isnumeric(x) && (isscalar(x) || numel(x) == 2));
addParameter(p, 'Repetitions', 1, @(x) isnumeric(x) && isscalar(x) && x >= 1);
addParameter(p, 'RepetitionSpacing_s', 1.0, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'CaptureFunction', @runLocalHDTVCapture, @(x) isa(x, 'function_handle'));

addParameter(p, 'MissionReportPath', default_mission_report, @(x) ischar(x) || isstring(x));
addParameter(p, 'RFBudgetPath', default_rf_budget, @(x) ischar(x) || isstring(x));
addParameter(p, 'ShowTriggerPreviewMap', true, @(x) islogical(x) && isscalar(x));
addParameter(p, 'SaveTriggerPreviewMap', true, @(x) islogical(x) && isscalar(x));
addParameter(p, 'TriggerPreviewOutputPath', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'TriggerPreviewAltitude_m', NaN, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'TriggerPreviewGridStep_m', 500, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'TriggerPreviewRangeMargin_m', 5000, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'TriggerPreviewBasemap', "streets-light", @(x) ischar(x) || isstring(x));
addParameter(p, 'Verbose', true, @(x) islogical(x) && isscalar(x));

parse(p, varargin{:});
opts = p.Results;

session_id = localResolveSessionID(opts.SessionID);
session_root = char(string(opts.SessionRoot));
stage_dir = localResolveStageDir(repo_info.repo_root, session_id, opts.ADSBStageDir);
control_dir = char(string(opts.CoordinatorControlDir));
status_file = localResolveStatusFile(control_dir, opts.CoordinatorStatusFile);
watch_started_utc = datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss''Z''');

[corridor_azimuth_deg, boresight_azimuth_deg] = helperTriggerResolveBoresightAzimuth( ...
    opts.RxLLA, ...
    opts.CorridorReferenceLLA, ...
    opts.CorridorAzimuthCenter_deg, ...
    opts.SurveillanceBoresightAzimuth_deg);
window_offset_grid_s = helperTriggerBuildWindowOffsetGrid(opts.PredictedStartOffsetBounds_s);

if exist(stage_dir, 'dir') ~= 7
    mkdir(stage_dir);
end

config = struct( ...
    'SessionID', session_id, ...
    'Mode', string(lower(string(opts.Mode))), ...
    'OpportunityPolicy', string(lower(string(opts.OpportunityPolicy))), ...
    'WatchTimeout_s', double(opts.WatchTimeout_s), ...
    'PollPeriod_s', double(opts.PollPeriod_s), ...
    'ADSBRotation_s', double(opts.ADSBRotation_s), ...
    'TailSeconds_s', double(opts.TailSeconds_s), ...
    'WaitForCoordinatorFinalization_s', double(opts.WaitForCoordinatorFinalization_s), ...
    'MinConsecutiveQualifiedPolls', double(opts.MinConsecutiveQualifiedPolls), ...
    'QualifiedTriggerScore', double(opts.QualifiedTriggerScore), ...
    'MaxFixAge_s', double(opts.MaxFixAge_s), ...
    'MinimumTrackFixCount', double(opts.MinimumTrackFixCount), ...
    'PredictedStartOffsetBounds_s', double(opts.PredictedStartOffsetBounds_s(:).'), ...
    'WindowOffsetGrid_s', double(window_offset_grid_s(:).'), ...
    'ReferenceChainPenalty_dB', double(opts.ReferenceChainPenalty_dB), ...
    'TxLLA', double(opts.TxLLA(:).'), ...
    'RxLLA', double(opts.RxLLA(:).'), ...
    'CorridorReferenceLLA', double(opts.CorridorReferenceLLA(:).'), ...
    'CorridorAzimuthCenter_deg', corridor_azimuth_deg, ...
    'SurveillanceBoresightAzimuth_deg', boresight_azimuth_deg, ...
    'SurveillanceBoresightElevation_deg', double(opts.SurveillanceBoresightElevation_deg), ...
    'CorridorAzimuthHalfWidth_deg', double(opts.CorridorAzimuthHalfWidth_deg), ...
    'BoresightAzimuthHalfWidth_deg', double(opts.BoresightAzimuthHalfWidth_deg), ...
    'BoresightElevationHalfWidth_deg', double(opts.BoresightElevationHalfWidth_deg), ...
    'AltitudeBand_m', double(opts.AltitudeBand_m(:).'), ...
    'ReceiverRangeBand_m', double(opts.ReceiverRangeBand_m(:).'), ...
    'SessionRoot', string(session_root), ...
    'ADSBStageDir', string(stage_dir), ...
    'CoordinatorControlDir', string(control_dir), ...
    'CoordinatorStatusFile', string(status_file), ...
    'RemoteLogLocalPath', string(opts.RemoteLogLocalPath), ...
    'PiUser', string(opts.PiUser), ...
    'PiHost', string(opts.PiHost), ...
    'PiWorkingDir', string(opts.PiWorkingDir), ...
    'PiLoggerScript', string(opts.PiLoggerScript), ...
    'RemoteLogFile', string(opts.RemoteLogFile), ...
    'CaptureDuration_s', double(opts.CaptureDuration_s), ...
    'CaptureFile', string(opts.CaptureFile), ...
    'RadioName', string(opts.RadioName), ...
    'CenterFrequency_Hz', double(opts.CenterFrequency_Hz), ...
    'SampleRate_Hz', double(opts.SampleRate_Hz), ...
    'LOOffset_Hz', double(opts.LOOffset_Hz), ...
    'Gain', double(opts.Gain(:).'), ...
    'Repetitions', double(opts.Repetitions), ...
    'RepetitionSpacing_s', double(opts.RepetitionSpacing_s), ...
    'CaptureFunction', opts.CaptureFunction, ...
    'MissionReportPath', string(opts.MissionReportPath), ...
    'RFBudgetPath', string(opts.RFBudgetPath), ...
    'ShowTriggerPreviewMap', logical(opts.ShowTriggerPreviewMap), ...
    'SaveTriggerPreviewMap', logical(opts.SaveTriggerPreviewMap), ...
    'TriggerPreviewOutputPath', string(opts.TriggerPreviewOutputPath), ...
    'TriggerPreviewAltitude_m', double(opts.TriggerPreviewAltitude_m), ...
    'TriggerPreviewGridStep_m', double(opts.TriggerPreviewGridStep_m), ...
    'TriggerPreviewRangeMargin_m', double(opts.TriggerPreviewRangeMargin_m), ...
    'TriggerPreviewBasemap', string(opts.TriggerPreviewBasemap), ...
    'Verbose', logical(opts.Verbose), ...
    'NowUTC', watch_started_utc);

if config.OpportunityPolicy ~= "single" && config.Verbose
    warning('runADSBTriggeredCaptureSession:phase1SingleOnly', ...
        'Phase 1 only supports single-opportunity operation. Using single.');
end
config.OpportunityPolicy = "single";

assets = helperTriggerResolveAssets( ...
    'MissionReportPath', config.MissionReportPath, ...
    'RFBudgetPath', config.RFBudgetPath);

preview_result = localMaybeRenderPreviewMap(config, assets);

score_bundle = helperTriggerScoreCandidates(struct([]), config, assets);
latest_candidate_table = score_bundle.candidate_table;
decision_log = localEmptyDecisionLog(latest_candidate_table);
coordinator_status = helperTriggerReadCoordinatorStatus(status_file);
track_cache = struct();
capture_info = localEmptyCaptureInfo();
shadow_recommendation = false;
trigger_snapshot = struct();
final_status = "timeout";
trigger_fired = false;
trigger_reason = "No qualifying aircraft reached the trigger threshold within the watch window.";

if localCoordinatorStatusIsError(coordinator_status.status)
    final_status = "coordinator_error";
    trigger_reason = "Shell coordinator failure before watch: " + coordinator_status.message;
end

poll_index = 0;
qualified_hex = "";
qualified_count = 0;
watch_deadline_utc = watch_started_utc + seconds(config.WatchTimeout_s);
run_loop = final_status ~= "coordinator_error";
first_poll = true;

while run_loop && (first_poll || datetime('now', 'TimeZone', 'UTC') <= watch_deadline_utc)
    first_poll = false;
    poll_index = poll_index + 1;
    poll_utc = datetime('now', 'TimeZone', 'UTC', ...
        'Format', 'yyyy-MM-dd''T''HH:mm:ss''Z''');

    coordinator_status = helperTriggerReadCoordinatorStatus(status_file);
    if localCoordinatorStatusIsError(coordinator_status.status)
        final_status = "coordinator_error";
        trigger_reason = "Shell coordinator failure during watch: " + coordinator_status.message;
        break
    end

    track_cache = helperTriggerUpdateTrackCache(track_cache, stage_dir, 'Verbose', false);

    config.NowUTC = poll_utc;
    score_bundle = helperTriggerScoreCandidates(track_cache.adsb_tracks, config, assets);
    latest_candidate_table = score_bundle.candidate_table;
    decision_log = localAppendDecisionRows(decision_log, latest_candidate_table, poll_index, poll_utc, "watch");

    if isempty(latest_candidate_table) || ~latest_candidate_table.qualified(1)
        qualified_hex = "";
        qualified_count = 0;
    else
        current_hex = string(latest_candidate_table.hex(1));
        if current_hex == qualified_hex
            qualified_count = qualified_count + 1;
        else
            qualified_hex = current_hex;
            qualified_count = 1;
        end

        if qualified_count >= config.MinConsecutiveQualifiedPolls
            trigger_snapshot = table2struct(latest_candidate_table(1, :));
            predicted_offset_s = max(min( ...
                latest_candidate_table.predicted_start_offset_s(1), ...
                config.PredictedStartOffsetBounds_s(2)), ...
                config.PredictedStartOffsetBounds_s(1));

            if config.Mode == "shadow"
                shadow_recommendation = true;
                final_status = "shadow_recommendation";
                trigger_reason = "Shadow recommendation: " + string(latest_candidate_table.rationale(1));
                break
            end

            if predicted_offset_s > 0
                pause(predicted_offset_s);
            end

            trigger_fired = true;
            trigger_reason = string(latest_candidate_table.rationale(1));
            try
                capture_info = localInvokeCapture(config);
                final_status = "captured";
            catch me_capture
                capture_info = localCaptureErrorInfo(config.SessionID, me_capture);
                final_status = "capture_error";
                trigger_reason = "Capture failed after trigger authorization: " + string(me_capture.message);
            end
            break
        end
    end

    if datetime('now', 'TimeZone', 'UTC') >= watch_deadline_utc
        break
    end

    pause(min(config.PollPeriod_s, max(seconds(watch_deadline_utc - datetime('now', 'TimeZone', 'UTC')), 0)));
end

watch_stopped_utc = datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss''Z''');

if (trigger_fired || shadow_recommendation) && config.TailSeconds_s > 0
    pause(config.TailSeconds_s);
end

finalize_info = helperTriggerFinalizeCoordinator(control_dir, ...
    'StatusFile', status_file, ...
    'WaitTimeout_s', config.WaitForCoordinatorFinalization_s);
coordinator_status = finalize_info.status;

track_cache = helperTriggerUpdateTrackCache(track_cache, stage_dir, 'Verbose', false);

if isempty(latest_candidate_table)
    config.NowUTC = datetime('now', 'TimeZone', 'UTC');
    score_bundle = helperTriggerScoreCandidates(track_cache.adsb_tracks, config, assets);
    latest_candidate_table = score_bundle.candidate_table;
end

session_result = struct( ...
    'session_id', string(config.SessionID), ...
    'mode', string(config.Mode), ...
    'opportunity_policy', string(config.OpportunityPolicy), ...
    'watch_started_utc', watch_started_utc, ...
    'watch_stopped_utc', watch_stopped_utc, ...
    'trigger_fired', logical(trigger_fired), ...
    'trigger_reason', string(trigger_reason), ...
    'candidate_table', latest_candidate_table, ...
    'capture_info', capture_info, ...
    'artifacts', struct(), ...
    'final_status', string(final_status), ...
    'proxy_label', string(assets.proxy_prior.proxy_label));

[package_info, capture_info] = helperTriggerPackageSession( ...
    config.SessionID, config.SessionRoot, config.ADSBStageDir, capture_info, ...
    'RemoteLogLocalPath', localResolveRemoteLogPath(config, coordinator_status), ...
    'ExtraLogPaths', string(status_file), ...
    'Verbose', config.Verbose);
session_result.capture_info = capture_info;

context = struct( ...
    'config', config, ...
    'assets', assets, ...
    'preview_map', localPreviewContext(preview_result), ...
    'score_bundle', score_bundle, ...
    'decision_log', decision_log, ...
    'track_cache', track_cache, ...
    'coordinator_status', coordinator_status, ...
    'finalize_info', finalize_info, ...
    'shadow_recommendation', shadow_recommendation, ...
    'trigger_snapshot', trigger_snapshot);

artifacts = helperTriggerWriteArtifacts(session_result, context, package_info.log_dir, ...
    'Verbose', config.Verbose);
package_info.packaged_log_rel = [ ...
    package_info.packaged_log_rel; ...
    artifacts.trigger_summary_rel; ...
    artifacts.trigger_decisions_rel; ...
    artifacts.trigger_context_rel];

[preview_log_rel, preview_log_abs] = localPreviewLogArtifact(preview_result, package_info.log_dir);
if strlength(preview_log_rel) > 0
    package_info.packaged_log_rel(end + 1, 1) = preview_log_rel;
    package_info.packaged_log_abs(end + 1, 1) = preview_log_abs;
end

manifest_path = helperTriggerWriteManifest(session_result, package_info, config);

session_result.artifacts = struct( ...
    'session_dir', string(package_info.session_dir), ...
    'radar_dir', string(package_info.radar_dir), ...
    'truth_dir', string(package_info.truth_dir), ...
    'log_dir', string(package_info.log_dir), ...
    'trigger_summary_txt', artifacts.trigger_summary_txt, ...
    'trigger_decisions_csv', artifacts.trigger_decisions_csv, ...
    'trigger_context_mat', artifacts.trigger_context_mat, ...
    'trigger_candidate_map_png', string(preview_result.image_path), ...
    'session_manifest', string(manifest_path), ...
    'packaged_radar_files', package_info.packaged_radar_abs, ...
    'packaged_adsb_files', package_info.packaged_adsb_abs, ...
    'packaged_log_files', package_info.packaged_log_abs);

if config.Verbose
    fprintf('TRIGGER_SESSION_ID=%s\n', config.SessionID);
    fprintf('TRIGGER_FINAL_STATUS=%s\n', session_result.final_status);
    fprintf('TRIGGER_SESSION_DIR=%s\n', package_info.session_dir);
    if strlength(manifest_path) > 0
        fprintf('TRIGGER_SESSION_MANIFEST=%s\n', manifest_path);
    end
end

end

function tf = localIsMode(value)
tf = any(strcmpi(string(value), ["shadow", "live"]));
end

function tf = localIsOpportunityPolicy(value)
tf = any(strcmpi(string(value), ["single", "continuous"]));
end

function session_id = localResolveSessionID(value)
session_id = string(value);
if strlength(session_id) == 0
    session_id = string(datetime('now', 'TimeZone', 'UTC', ...
        'Format', 'yyyyMMdd''T''HHmmss'));
end
end

function stage_dir = localResolveStageDir(repo_root, session_id, value)
if strlength(string(value)) == 0
    stage_dir = fullfile(repo_root, 'adsb_capture', session_id);
else
    stage_dir = char(string(value));
end
end

function status_file = localResolveStatusFile(control_dir, value)
if strlength(string(value)) > 0
    status_file = char(string(value));
elseif strlength(string(control_dir)) > 0
    status_file = fullfile(char(string(control_dir)), 'coordinator_status.txt');
else
    status_file = "";
end
end

function tf = localCoordinatorStatusIsError(status_value)
status_value = lower(string(status_value));
tf = status_value == "error" || status_value == "start_failed";
end

function decision_log = localEmptyDecisionLog(candidate_template)
decision_log = candidate_template;
decision_log = addvars(decision_log, ...
    zeros(0, 1), strings(0, 1), strings(0, 1), ...
    'Before', 1, ...
    'NewVariableNames', {'poll_index', 'poll_utc', 'state'});
end

function decision_log = localAppendDecisionRows(decision_log, candidate_rows, poll_index, poll_utc, state_name)
if isempty(candidate_rows)
    return
end

poll_rows = candidate_rows;
poll_rows = addvars(poll_rows, ...
    repmat(double(poll_index), height(poll_rows), 1), ...
    repmat(string(poll_utc), height(poll_rows), 1), ...
    repmat(string(state_name), height(poll_rows), 1), ...
    'Before', 1, ...
    'NewVariableNames', {'poll_index', 'poll_utc', 'state'});
decision_log = [decision_log; poll_rows];
end

function capture_info = localInvokeCapture(config)
capture_info = config.CaptureFunction( ...
    'SessionID', config.SessionID, ...
    'CaptureDuration_s', config.CaptureDuration_s, ...
    'CaptureFile', config.CaptureFile, ...
    'RadioName', config.RadioName, ...
    'CenterFrequency_Hz', config.CenterFrequency_Hz, ...
    'SampleRate_Hz', config.SampleRate_Hz, ...
    'LOOffset_Hz', config.LOOffset_Hz, ...
    'Gain', config.Gain, ...
    'Repetitions', config.Repetitions, ...
    'RepetitionSpacing_s', config.RepetitionSpacing_s);
capture_info.status = "captured";
capture_info.capture_attempted = true;
capture_info.error_message = "";
if ~isfield(capture_info, 'capture_file_path')
    if isfield(capture_info, 'local_capture_files') && ~isempty(capture_info.local_capture_files)
        capture_info.capture_file_path = string(capture_info.local_capture_files(1));
    else
        capture_info.capture_file_path = "";
    end
end
end

function capture_info = localEmptyCaptureInfo()
capture_info = struct( ...
    'session_id', "", ...
    'capture_duration_s', NaN, ...
    'capture_repetitions', NaN, ...
    'capture_repetition_spacing_s', NaN, ...
    'radar_active_window_s', NaN, ...
    'radar_recorded_iq_seconds_s', NaN, ...
    'capture_file_base', "", ...
    'radio_name', "", ...
    'center_frequency_hz', NaN, ...
    'sample_rate_hz', NaN, ...
    'lo_offset_hz', NaN, ...
    'header_center_frequency_hz', NaN, ...
    'header_lo_offset_hz', NaN, ...
    'header_tune_frequency_hz', NaN, ...
    'header_sample_rate_hz', NaN, ...
    'gain', NaN, ...
    'recording_utc', NaN, ...
    'local_capture_files', strings(0, 1), ...
    'capture_file_path', "", ...
    'capture_attempted', false, ...
    'status', "not_run", ...
    'error_message', "");
end

function capture_info = localCaptureErrorInfo(session_id, me_capture)
capture_info = localEmptyCaptureInfo();
capture_info.session_id = string(session_id);
capture_info.capture_attempted = true;
capture_info.status = "error";
capture_info.error_message = string(me_capture.message);
end

function remote_log_path = localResolveRemoteLogPath(config, coordinator_status)
remote_log_path = string(config.RemoteLogLocalPath);
if strlength(remote_log_path) == 0 && isstruct(coordinator_status) && ...
        isfield(coordinator_status, 'remote_log_local_path')
    remote_log_path = string(coordinator_status.remote_log_local_path);
end
end

function preview_result = localMaybeRenderPreviewMap(config, assets)
preview_result = localEmptyPreviewResult();
if ~config.ShowTriggerPreviewMap && ~config.SaveTriggerPreviewMap
    return
end

preview_output_path = localResolvePreviewOutputPath(config);
try
    preview_result = helperTriggerRenderCandidateMap( ...
        config, assets, ...
        'OutputPath', preview_output_path, ...
        'ShowFigure', config.ShowTriggerPreviewMap, ...
        'SavePNG', config.SaveTriggerPreviewMap, ...
        'Altitude_m', config.TriggerPreviewAltitude_m, ...
        'GridStep_m', config.TriggerPreviewGridStep_m, ...
        'RangeMargin_m', config.TriggerPreviewRangeMargin_m, ...
        'Basemap', config.TriggerPreviewBasemap, ...
        'Verbose', config.Verbose);
catch me_preview
    preview_result = localEmptyPreviewResult();
    preview_result.image_path = string(preview_output_path);
    preview_result.warning_message = string(me_preview.message);
    if config.Verbose
        warning('runADSBTriggeredCaptureSession:previewMapFailed', ...
            'Trigger preview map generation failed: %s', me_preview.message);
    end
end
end

function preview_output_path = localResolvePreviewOutputPath(config)
if strlength(config.TriggerPreviewOutputPath) > 0
    preview_output_path = string(config.TriggerPreviewOutputPath);
    return
end

preview_log_dir = fullfile(config.SessionRoot, config.SessionID, 'logs');
if exist(preview_log_dir, 'dir') ~= 7
    mkdir(preview_log_dir);
end
preview_output_path = fullfile(preview_log_dir, 'trigger_candidate_map.png');
end

function preview_context = localPreviewContext(preview_result)
preview_context = preview_result;
preview_context.figure_handle = [];
preview_context.geoaxes_handle = [];
preview_context.enu_axes_handle = [];
end

function [preview_log_rel, preview_log_abs] = localPreviewLogArtifact(preview_result, log_dir)
preview_log_rel = "";
preview_log_abs = "";
image_path = string(preview_result.image_path);
if ~preview_result.saved_png || strlength(image_path) == 0 || exist(image_path, 'file') ~= 2
    return
end

log_dir = string(log_dir);
if startsWith(lower(image_path), lower(log_dir + filesep))
    preview_log_rel = "logs/" + string(extractAfter(image_path, log_dir + filesep));
    preview_log_abs = image_path;
end
end

function preview_result = localEmptyPreviewResult()
preview_result = struct( ...
    'figure_handle', [], ...
    'geoaxes_handle', [], ...
    'enu_axes_handle', [], ...
    'legend_handle', [], ...
    'image_path', "", ...
    'saved_png', false, ...
    'show_figure', false, ...
    'save_png', false, ...
    'altitude_slice_m', NaN, ...
    'grid_step_m', NaN, ...
    'range_margin_m', NaN, ...
    'preview_extent_m', NaN, ...
    'preview_extent_km', NaN, ...
    'qualified_area_km2', NaN, ...
    'qualified_region_exists', false, ...
    'qualified_region_message', "", ...
    'max_trigger_score', NaN, ...
    'east_axis_m', zeros(0, 1), ...
    'north_axis_m', zeros(0, 1), ...
    'trigger_score_grid', zeros(0, 0), ...
    'geometry_gate_grid', false(0, 0), ...
    'qualified_grid', false(0, 0), ...
    'legend_entries', strings(0, 1), ...
    'overlay_styles', struct(), ...
    'config_summary', struct(), ...
    'warning_message', "");
end
