classdef CaptureProvenanceTest < matlab.unittest.TestCase
    %CAPTUREPROVENANCETEST Offline tests for capture setup provenance.

    properties (Access = private)
        TestSetupRoot string
        RepositoryRoot string
    end

    methods (TestClassSetup)
        function addProjectPaths(testCase)
            testCase.TestSetupRoot = string(fileparts(mfilename('fullpath')));
            testCase.RepositoryRoot = string(fileparts(testCase.TestSetupRoot));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                char(testCase.TestSetupRoot)));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                char(fullfile(testCase.RepositoryRoot, 'TriggerAcquisition'))));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                char(fullfile(testCase.RepositoryRoot, 'BistaticDataAnalysis'))));
        end
    end

    methods (Test)
        function testProvidedSetupNotesArePreservedVerbatim(testCase)
            provided_notes = "CH1 RF0:RX2 surveillance Yagi; CH2 RF1:RX2 reference dipole.";

            notes = helperResolveOperatorSetupNotes(provided_notes, ...
                'Interactive', false);

            testCase.verifyEqual(notes, provided_notes);
        end

        function testEmptyInteractiveSetupNotesPromptOnce(testCase)
            prompted_notes = "CH1 proof: disconnect; CH2 proof: pilot stimulus.";

            notes = helperResolveOperatorSetupNotes("", ...
                'Interactive', true, ...
                'PromptFunction', @(~) prompted_notes);

            testCase.verifyEqual(notes, prompted_notes);
        end

        function testHeadlessMissingSetupNotesRefusesCapture(testCase)
            testCase.verifyError( ...
                @() helperResolveOperatorSetupNotes("", 'Interactive', false), ...
                'helperResolveOperatorSetupNotes:missingOperatorSetupNotes');
        end

        function testLocalWrapperCarriesProvidedNotesAndMapping(testCase)
            provided_notes = "CH1 RF0:RX2 surveillance Yagi; CH2 RF1:RX2 reference dipole.";

            capture_info = runLocalHDTVCapture( ...
                'SessionID', "provenance_local_test", ...
                'OperatorSetupNotes', provided_notes, ...
                'Gain', [12 18], ...
                'AntennaPorts', ["RF0:RX2", "RF1:RX2"], ...
                'ChannelRoles', ["surveillance", "reference"], ...
                'CaptureFunction', @localLoggerStub);

            testCase.verifyEqual(capture_info.operator_setup_notes, provided_notes);
            testCase.verifyEqual(capture_info.manifest_version, 3);
            testCase.verifyEqual(capture_info.channel_mapping(1).stored_channel_index, 1);
            testCase.verifyEqual(capture_info.channel_mapping(1).n320_port, "RF0:RX2");
            testCase.verifyEqual(capture_info.channel_mapping(1).semantic_role, "surveillance");
            testCase.verifyEqual(capture_info.channel_mapping(1).gain_db, 12);
            testCase.verifyEqual(capture_info.channel_mapping(2).stored_channel_index, 2);
            testCase.verifyEqual(capture_info.channel_mapping(2).n320_port, "RF1:RX2");
            testCase.verifyEqual(capture_info.channel_mapping(2).semantic_role, "reference");
            testCase.verifyEqual(capture_info.channel_mapping(2).gain_db, 18);
        end

        function testManifestV3RoundTripPreservesSetupAndMapping(testCase)
            [session_result, package_info, config] = localManifestInputs(testCase);

            manifest_path = helperTriggerWriteManifest(session_result, package_info, config);
            manifest = helperLoadSessionManifest(manifest_path);

            testCase.verifyEqual(manifest.manifest_version, 3);
            testCase.verifyEqual(string(manifest.operator_setup_notes), ...
                config.OperatorSetupNotes);
            testCase.verifyEqual(manifest.channel_mapping(1).stored_channel_index, 1);
            testCase.verifyEqual(string(manifest.channel_mapping(1).n320_port), "RF0:RX2");
            testCase.verifyEqual(string(manifest.channel_mapping(1).semantic_role), ...
                "surveillance");
            testCase.verifyEqual(manifest.channel_mapping(1).gain_db, 12);
            testCase.verifyEqual(manifest.channel_mapping(2).stored_channel_index, 2);
            testCase.verifyEqual(string(manifest.channel_mapping(2).n320_port), "RF1:RX2");
            testCase.verifyEqual(string(manifest.channel_mapping(2).semantic_role), ...
                "reference");
            testCase.verifyEqual(manifest.channel_mapping(2).gain_db, 18);
        end

        function testLegacyManifestRemainsReadable(testCase)
            manifest_path = localWriteLegacyManifest(testCase);

            manifest = helperLoadSessionManifest(manifest_path);

            testCase.verifyEqual(manifest.manifest_version, 1);
            testCase.verifyEqual(manifest.session_id, 'legacy_session');
            testCase.verifyEqual(manifest.radar_files, {'radar/legacy.bb'});
            testCase.verifyEmpty(manifest.adsb_files);
            testCase.verifyEmpty(manifest.log_files);
        end
    end
end

function [session_id, written_files] = localLoggerStub(varargin)
arguments_struct = localNameValueStruct(varargin);
session_id = string(arguments_struct.session_id);
written_files = strings(0, 1);
end

function values = localNameValueStruct(arguments_in)
values = struct;
for index = 1:2:numel(arguments_in)
    field_name = char(string(arguments_in{index}));
    values.(field_name) = arguments_in{index + 1};
end
end

function [session_result, package_info, config] = localManifestInputs(testCase)
session_dir = string(tempname(char(testCase.TestSetupRoot)));
mkdir(session_dir);
testCase.addTeardown(@() localSafeRemoveFolder(session_dir));

channel_mapping = helperBuildChannelMapping( ...
    ["RF0:RX2", "RF1:RX2"], ...
    ["surveillance", "reference"], ...
    [12, 18]);

capture_info = struct( ...
    'recording_utc', 1.0, ...
    'header_center_frequency_hz', 599e6, ...
    'header_sample_rate_hz', 6.144e6, ...
    'header_lo_offset_hz', 0, ...
    'header_tune_frequency_hz', 599e6, ...
    'channel_mapping', channel_mapping);
session_result = struct( ...
    'session_id', "provenance_manifest_test", ...
    'capture_info', capture_info, ...
    'mode', "live", ...
    'opportunity_policy', "single", ...
    'trigger_fired', true, ...
    'trigger_reason', "offline manifest test", ...
    'proxy_label', "test", ...
    'watch_started_utc', datetime('now', 'TimeZone', 'UTC'), ...
    'watch_stopped_utc', datetime('now', 'TimeZone', 'UTC'), ...
    'candidate_table', table);
package_info = struct( ...
    'session_dir', session_dir, ...
    'packaged_radar_rel', "radar/capture.bb", ...
    'packaged_adsb_rel', strings(0, 1), ...
    'packaged_log_rel', strings(0, 1));
config = struct( ...
    'CaptureDuration_s', 30, ...
    'Repetitions', 1, ...
    'RepetitionSpacing_s', 0, ...
    'TailSeconds_s', 5, ...
    'ADSBRotation_s', 5, ...
    'PollPeriod_s', 5, ...
    'CaptureFile', "capture", ...
    'Gain', [12, 18], ...
    'OperatorSetupNotes', "CH1 proven; CH2 proven.", ...
    'ChannelMapping', channel_mapping, ...
    'PiHost', "pi.example", ...
    'PiUser', "pi", ...
    'RemoteLogFile', "adsb.log", ...
    'RadioName', "test radio", ...
    'CenterFrequency_Hz', 599e6, ...
    'SampleRate_Hz', 6.144e6, ...
    'LOOffset_Hz', 0, ...
    'ReferenceChainPenalty_dB', NaN);
end

function manifest_path = localWriteLegacyManifest(testCase)
session_dir = string(tempname(char(testCase.TestSetupRoot)));
mkdir(session_dir);
testCase.addTeardown(@() localSafeRemoveFolder(session_dir));
manifest_path = fullfile(session_dir, 'session_manifest.json');

file_id = fopen(manifest_path, 'w');
cleanup_file = onCleanup(@() fclose(file_id));
fprintf(file_id, ['{"manifest_version":1,"session_id":"legacy_session",' ...
    '"radar_files":["radar/legacy.bb"]}']);
clear cleanup_file
end

function localSafeRemoveFolder(folder_path)
folder_path = char(string(folder_path));
if isfolder(folder_path)
    rmdir(folder_path, 's');
end
end
