function [waveform, waveform_info] = helperPlutoMultitoneBuildWaveform(sample_rate_hz, tone_offsets_hz, target_rms_amplitude, varargin)
%HELPERPLUTOMULTITONEBUILDWAVEFORM Build a deterministic complex multitone pilot.
%
% Plain-language concept:
%   A single CW pilot asks one frequency bin to carry all of the evidence.
%   A multitone pilot spreads that evidence across several known frequency
%   bins inside the same coherent processing interval. On receive, each tone
%   can be detected like the existing Phase 1 tone, then the evidence can be
%   integrated across tones. That gives a processing-gain path without
%   jumping immediately to a fully wideband chirp experiment.
%
% Toolbox-first implementation:
%   Each tone component is generated by dsp.SineWave, matching the style of
%   helperPlutoToneBuildWaveform. The final summed waveform is normalized to
%   a requested aggregate RMS and clipped by a peak limit so the Pluto DAC is
%   not driven near full scale.

p = inputParser;
p.FunctionName = mfilename;
addRequired(p, 'sample_rate_hz', @(x) isnumeric(x) && isscalar(x) && x > 0);
addRequired(p, 'tone_offsets_hz', @(x) isnumeric(x) && isvector(x) && ~isempty(x));
addRequired(p, 'target_rms_amplitude', @(x) isnumeric(x) && isscalar(x) && x > 0 && x < 1);
addParameter(p, 'PeakLimit', 0.80, @(x) isnumeric(x) && isscalar(x) && x > 0 && x <= 1);
addParameter(p, 'MinSamples', 65536, @(x) isnumeric(x) && isscalar(x) && x >= 1024);
addParameter(p, 'TonePhases_rad', [], @(x) isempty(x) || (isnumeric(x) && isvector(x)));
addParameter(p, 'Verbose', false, @(x) islogical(x) && isscalar(x));
parse(p, sample_rate_hz, tone_offsets_hz, target_rms_amplitude, varargin{:});
opts = p.Results;

tone_offsets_hz = double(tone_offsets_hz(:));
sample_rate_hz = double(sample_rate_hz);
target_rms_amplitude = double(target_rms_amplitude);

nyquist_hz = sample_rate_hz / 2;
if any(abs(tone_offsets_hz) >= nyquist_hz)
    error('helperPlutoMultitoneBuildWaveform:toneOutOfRange', ...
        'Every tone offset must remain inside the baseband Nyquist span %.3f MHz.', ...
        nyquist_hz / 1e6);
end

tone_phases_rad = localResolveTonePhases(tone_offsets_hz, opts.TonePhases_rad);
n_samples = localResolveWaveformLength(sample_rate_hz, tone_offsets_hz, opts.MinSamples);
waveform = complex(zeros(n_samples, 1));

for idx = 1:numel(tone_offsets_hz)
    sine_wave = dsp.SineWave( ...
        'Amplitude', 1, ...
        'ComplexOutput', true, ...
        'Frequency', tone_offsets_hz(idx), ...
        'SampleRate', sample_rate_hz, ...
        'SamplesPerFrame', n_samples);
    tone = double(sine_wave()) .* exp(1j * tone_phases_rad(idx));
    release(sine_wave);
    waveform = waveform + tone(:);
end

% Average the tone sum before RMS normalization. This keeps the raw waveform
% bounded enough that the final peak limiter behaves predictably.
waveform = waveform ./ numel(tone_offsets_hz);
[waveform, scale_info] = localNormalizeWaveform(waveform, target_rms_amplitude, double(opts.PeakLimit));
waveform = single(waveform(:));

waveform_info = struct( ...
    'waveform_type', 'multitone_comb', ...
    'sample_rate_hz', sample_rate_hz, ...
    'tone_offsets_hz', tone_offsets_hz, ...
    'tone_phases_rad', tone_phases_rad, ...
    'target_rms_amplitude', target_rms_amplitude, ...
    'peak_limit', double(opts.PeakLimit), ...
    'n_samples', double(n_samples), ...
    'duration_s', double(n_samples / sample_rate_hz), ...
    'rms_amplitude', double(sqrt(mean(abs(double(waveform)).^2))), ...
    'peak_amplitude', double(max(abs(double(waveform)))), ...
    'papr_db', 20 * log10(double(max(abs(waveform))) / double(sqrt(mean(abs(waveform).^2))) + eps), ...
    'occupied_bandwidth_hz', double(max(tone_offsets_hz) - min(tone_offsets_hz)), ...
    'tone_spacing_hz', localMedianToneSpacing(tone_offsets_hz), ...
    'ideal_noncoherent_integration_gain_db', 10 * log10(numel(tone_offsets_hz)), ...
    'scale_info', scale_info);

if opts.Verbose
    fprintf(['[helperPlutoMultitoneBuildWaveform] fs %.3f MSps | tones %d | ' ...
        'span %.3f MHz | RMS %.3f | peak %.3f | PAPR %.1f dB\n'], ...
        sample_rate_hz / 1e6, ...
        numel(tone_offsets_hz), ...
        waveform_info.occupied_bandwidth_hz / 1e6, ...
        waveform_info.rms_amplitude, ...
        waveform_info.peak_amplitude, ...
        waveform_info.papr_db);
end
end

function tone_phases_rad = localResolveTonePhases(tone_offsets_hz, requested_phases)
n_tones = numel(tone_offsets_hz);
if isempty(requested_phases)
    tone_phases_rad = zeros(n_tones, 1);
else
    tone_phases_rad = double(requested_phases(:));
    if numel(tone_phases_rad) ~= n_tones
        error('helperPlutoMultitoneBuildWaveform:phaseCountMismatch', ...
            'TonePhases_rad must contain one phase per tone offset.');
    end
end
end

function n_samples = localResolveWaveformLength(sample_rate_hz, tone_offsets_hz, min_samples)
% Prefer an integer number of cycles for every tone when the requested tones
% are rational with respect to the sample rate. If the exact common period
% is too long, fall back to MinSamples; transmitRepeat can still loop it,
% but a tiny wrap discontinuity may appear at the buffer boundary.
period_samples = ones(numel(tone_offsets_hz), 1);
for idx = 1:numel(tone_offsets_hz)
    if tone_offsets_hz(idx) == 0
        period_samples(idx) = 1;
    else
        [~, period_candidate] = rat(abs(tone_offsets_hz(idx)) / sample_rate_hz, 1e-12);
        period_samples(idx) = max(1, double(period_candidate));
    end
end

common_period = 1;
for idx = 1:numel(period_samples)
    common_period = lcm(round(common_period), round(period_samples(idx)));
    if common_period > min_samples
        common_period = min_samples;
        break
    end
end

n_samples = ceil(double(min_samples) / double(common_period)) * double(common_period);
end

function [waveform, scale_info] = localNormalizeWaveform(waveform, target_rms_amplitude, peak_limit)
raw_rms = sqrt(mean(abs(waveform(:)).^2));
if raw_rms == 0
    error('helperPlutoMultitoneBuildWaveform:zeroWaveform', ...
        'Cannot normalize a zero-valued waveform.');
end

scale_factor = target_rms_amplitude / raw_rms;
scaled_peak = max(abs(waveform * scale_factor));
peak_limited = scaled_peak > peak_limit;
if peak_limited
    scale_factor = peak_limit / max(abs(waveform));
end

waveform = waveform * scale_factor;
scale_info = struct( ...
    'raw_rms', raw_rms, ...
    'target_rms_amplitude', target_rms_amplitude, ...
    'peak_limit', peak_limit, ...
    'scale_factor', scale_factor, ...
    'peak_limited', peak_limited);
end

function spacing_hz = localMedianToneSpacing(tone_offsets_hz)
if numel(tone_offsets_hz) < 2
    spacing_hz = NaN;
else
    spacing_hz = median(diff(sort(tone_offsets_hz)));
end
end
