function thresholds = helperPlutoToneDefaultThresholds()
%HELPERPLUTOTONEDEFAULTTHRESHOLDS Return default Phase 1 commissioning thresholds.
%
% Plain-language goal:
%   The sweep and later baseline commissioning need one default threshold
%   pack that matches the current Phase 1 unit-test expectations. Keeping
%   these values in one helper avoids scattering commissioning policy
%   numbers across multiple scripts.

channel_thresholds = struct( ...
    'detect_margin_warn_db', 10, ...
    'detect_margin_min_db', 6, ...
    'frequency_error_warn_hz', 1.5e3, ...
    'frequency_error_max_hz', 3e3, ...
    'level_max_dbfs', -3, ...
    'baseline_level_drift_warn_db', 1.0, ...
    'baseline_level_drift_max_db', 2.0);

joint_thresholds = struct( ...
    'channel_frequency_delta_warn_hz', 1e3, ...
    'channel_frequency_delta_max_hz', 2e3, ...
    'xcorr_peak_advisory_min_db', -20, ...
    'xcorr_lag_advisory_max_samples', 64);

thresholds = struct( ...
    'reference', channel_thresholds, ...
    'surveillance', channel_thresholds, ...
    'joint', joint_thresholds);
end
