%[text] # Pluto Phase 1 Validation Notebook
%[text] This plain-text Live Editor notebook runs the current standalone Phase 1 Pluto validation steps in the same order used during bring-up and records concise summaries so it can be shared later as the artifact describing what was tried.
%[text] - MATLAB unit tests for the standalone Phase 1 slice
%[text] - Stage 6 smoke test at the branch-default |540 MHz / 6.144 MSps / 250 kHz|
%[text] - Stage 6 smoke test at |599 MHz / 8 MSps / 250 kHz|
%[text] - Stage 6 smoke test at |599 MHz / 8 MSps / 3.2 MHz|
%[text] - recorded prior Stage 6 placement and amplitude trials at |599 MHz / 8 MSps / 1.5 MHz|
%[text] - optional full wrapper run once a commissioned baseline path is available \
scriptRoot = fileparts(mfilename('fullpath'));
projectRoot = fileparts(scriptRoot);
cd(scriptRoot);
%%
%[text] ## Current Agreed Context
%[text] This notebook follows the current agreed Phase 1 direction rather than replacing it with the newer Phase 2 archived-capture analysis plan.
agreedContext = table( ...
    ["Phase 1 intent"; "Phase 2 role"; "Surveillance mapping"; "Reference mapping"; "Preferred smoke-test band"; "Current readiness gate"; "Integration stance"], ...
    ["Standalone tone-based readiness gate"; "Secondary standalone analysis over archived Phase 1 captures"; "RF0:RX2 -> CH1 / RX1 = SURV"; "RF1:RX2 -> CH2 / RX2 = REF"; "599 MHz"; "Tone-based now, wideband source later"; "Remain standalone for now"], ...
    'VariableNames', ["Topic", "CurrentDecision"]);
disp(agreedContext);
%%
%[text] ## Native Function Audit For Workflow
%[text:table]
%[text] | Proposed Workflow | Native MATLAB Documentation Example Analogue | Updates needed to fit current goal |
%[text] | --- | --- | --- |
%[text] | Run MATLAB unit tests for the standalone Pluto slice | |runtests| and |matlab.unittest.TestResult| | Keep the tests read-only and summarize pass, fail, and incomplete outcomes clearly |
%[text] | Run the combined Pluto-to-USRP smoke test | Existing repo runner |runPlutoToneStage6Smoke| | Reuse the checked-in runner instead of long shell one-liners |
%[text] | Run the full baseline-backed Phase 1 wrapper | Existing repo wrapper |runPlutoTonePrecheck| | Keep it optional because it requires a commissioned baseline |
%[text] | Summarize notebook output for handoff | built-in |table|, |struct2table|, strings, and Live Editor sections | Convert each run into short notes so the notebook explains what happened without manual editing |
%[text:table]
workflowAudit = table( ...
    ["Run MATLAB unit tests for the standalone Pluto slice"; "Run the combined Pluto-to-USRP smoke test"; "Run the full baseline-backed Phase 1 wrapper"; "Summarize notebook output for handoff"], ...
    ["runtests and matlab.unittest.TestResult"; "runPlutoToneStage6Smoke"; "runPlutoTonePrecheck"; "table, struct2table, strings, and Live Editor sections"], ...
    ["Keep the tests read-only and summarize pass, fail, and incomplete outcomes clearly"; "Reuse the checked-in runner instead of long shell one-liners"; "Keep it optional because it requires a commissioned baseline"; "Convert each run into short notes so the notebook explains what happened without manual editing"], ...
    'VariableNames', ["ProposedWorkflow", "NativeMATLABDocumentationExampleAnalogue", "UpdatesNeededToFitCurrentGoal"]);
disp(workflowAudit);
%%
%[text] ## Native Function Audit For Functions
%[text:table]
%[text] | Proposed Feature / Algorithm | Native MATLAB Function/Toolbox Equivalent | Documentation Syntax Template Used |
%[text] | --- | --- | --- |
%[text] | Unit-test execution | |runtests| | |results = runtests(""PlutoTonePrecheckHelperTest.m"")| |
%[text] | Structured result summaries | |table| and |struct2table| | |T = table(var1,var2,...);| |
%[text] | Failure capture for hardware steps | |try/catch| with |getReport| | |try; step(); catch me; report = getReport(me); end| |
%[text] | Notebook narrative assembly | string arrays and |join| | |lines = strings(0,1); lines(end+1) = ""text"";| |
%[text:table]
functionAudit = table( ...
    ["Unit-test execution"; "Structured result summaries"; "Failure capture for hardware steps"; "Notebook narrative assembly"], ...
    ["runtests"; "table and struct2table"; "try/catch with getReport"; "string arrays and join"], ...
    ["results = runtests(""PlutoTonePrecheckHelperTest.m"")"; "T = table(var1,var2,...);"; "try; step(); catch me; report = getReport(me); end"; "lines = strings(0,1); lines(end+1) = ""text"";"], ...
    'VariableNames', ["ProposedFeatureOrAlgorithm", "NativeMATLABFunctionOrToolboxEquivalent", "DocumentationSyntaxTemplateUsed"]);
disp(functionAudit);
%%
%[text] ## Prior Observed Bring-Up Results
%[text] The table below captures the remote results already observed before this notebook was finalized so later runs can be compared against them without re-reading chat logs.
priorObservedResults = table( ...
    ["Stage 6A: 540 MHz / 250 kHz"; "Stage 6B: 599 MHz / 250 kHz"; "Stage 6C: 599 MHz / 3.2 MHz"; "Stage 6D1: 599 MHz / 1.5 MHz"; "Stage 6D2: 599 MHz / 1.5 MHz"; "Stage 6D3: 599 MHz / 1.5 MHz"; "Stage 6D4: 599 MHz / 1.5 MHz"; "Stage 6D5: 599 MHz / 1.5 MHz / amp 0.8"], ...
    ["Branch-default smoke run"; "HDTV-band comparison run"; "Higher-offset comparison run"; "First 1.5 MHz comparison run before placement study"; "Pluto on top of computer box inside stairwell with 6.75 in telescoping antenna"; "Short USB plus 10 ft Nooelec mount with 4.9 in antenna held outside stairwell"; "Same 10 ft Nooelec mount with 4.9 in antenna taped outside stairwell ledge"; "Same outside-mounted 10 ft Nooelec mount and 4.9 in antenna as Stage 6D4, but ToneAmplitude = 0.8"], ...
    [true; true; true; true; true; true; true; true], ...
    [true; true; true; true; true; true; true; true], ...
    [0.8189; 3.8760; 1.5789; -0.6732; -1.2627; 0.3467; 1.1428; 1.7067], ...
    [-2.4643; -2.0907; -1.1572; -2.8809; -9.3541; 1.5753; -0.3017; 3.7273], ...
    [-16843.8; -10376.0; 22900.4; -18920.9; -13000.5; 7080.1; 6958.0; -4455.6], ...
    [-22609.4; -8483.9; 18383.8; -17211.9; -12268.1; 20874.0; 21301.3; -12390.1], ...
    [5765.6; 1892.1; 4516.6; 1709.0; 732.4219; 13793.9; 14343.3; 7934.6], ...
    [-36.7368; -5.8812; -5.4117; -5.9941; -6.0588; -5.9300; -4.0574; -4.2754], ...
    ["End-to-end path worked, but tone prominence and inter-channel agreement were weak."; "Best overall combined result so far. The end-to-end path worked at the HDTV band and inter-channel agreement improved materially versus the 540 MHz run."; "The higher-offset run still passed, but it did not materially improve tone prominence and joint agreement regressed versus Stage 6B."; "First 1.5 MHz comparison run. The joint delta improved relative to Stage 6C, but both detect margins remained weak."; "Moving the Pluto to the top of the computer box gave the best 1.5 MHz joint delta so far, but the surveillance detect margin collapsed and the setup is not baseline-worthy."; "Moving the radiator just outside the stairwell improved tone visibility on both channels, but the joint frequency delta collapsed and the setup is not baseline-worthy."; "Taping the radiator outside the stairwell kept visibility reasonable and improved advisory xcorr, but the joint frequency delta remained poor and the setup is not baseline-worthy."; "Raising ToneAmplitude to 0.8 on the outside-mounted setup materially improved both detect margins and reduced the joint delta versus Stage 6D4, but the combined result still trails Stage 6B and is not baseline-worthy."], ...
    'VariableNames', ["RunLabel", "PhysicalSetup", "RefToneFound", "SurvToneFound", "RefDetectMargin_dB", "SurvDetectMargin_dB", "RefFreqErr_Hz", "SurvFreqErr_Hz", "ChannelFreqDelta_Hz", "XcorrPeak_dB", "Interpretation"]);
disp(priorObservedResults);
priorObservedNotes = [ ...
    "Earlier smoke testing already showed that the Pluto-to-USRP Stage 6 path is working end-to-end."; ...
    "All recorded Stage 6 runs use the fixed mapping RF0:RX2 -> CH1/RX1 -> SURV and RF1:RX2 -> CH2/RX2 -> REF."; ...
    "Stage 6B at 599 MHz with a 250 kHz tone remains the best overall combined result seen so far and is still the best single comparison point for later tuning changes."; ...
    "The 599 MHz / 3.2 MHz run remained a pass, but it did not improve over Stage 6B and both channel frequency errors moved positive together, which is more consistent with shared TX/RX offset than with one broken channel."; ...
    "The 1.5 MHz placement and amplitude study showed that physical placement and Pluto tone level both change single-channel detect margins, but none of those runs beat Stage 6B on combined joint agreement."; ...
    "Pluto on top of the computer box produced the best 1.5 MHz channel-frequency delta at 732.4 Hz, but the surveillance detect margin dropped to -9.35 dB and the run is not baseline-worthy."; ...
    "On the outside-mounted setup, raising ToneAmplitude from 0.5 to 0.8 improved REF detect from +1.14 dB to +1.71 dB and SURV detect from -0.30 dB to +3.73 dB while reducing the channel-frequency delta from 14.34 kHz to 7.93 kHz."; ...
    "Even with the stronger tone, the outside-mounted 1.5 MHz run still lagged Stage 6B materially on joint agreement, so higher tone level alone does not appear to solve the remaining calibration-readiness gap."; ...
    "The 10 ft micro-USB extension made Pluto undiscoverable, so later physical experiments should keep the Pluto on the short USB cable and move only the antenna/feed when possible."; ...
    "Phase 1 remains the authoritative standalone tone gate. Phase 2 archived-capture analysis stays separate."];
disp(priorObservedNotes);
%%
%[text] ## Run Controls
%[text] Set any of these variables in the workspace before pressing |Run All| if you want to override the defaults on the test machine.
if ~exist('runUnitTests', 'var')
    runUnitTests = true;
end
if ~exist('runSmoke540', 'var')
    runSmoke540 = true;
end
if ~exist('runSmoke599', 'var')
    runSmoke599 = true;
end
if ~exist('runSmoke599Offset32', 'var')
    runSmoke599Offset32 = true;
end
if ~exist('runWrapper', 'var')
    runWrapper = false;
end
if ~exist('baselinePath', 'var')
    baselinePath = "";
end
if ~exist('wrapperToneAmplitude', 'var')
    wrapperToneAmplitude = 0.5;
end
if ~exist('wrapperCaptureDuration_s', 'var')
    wrapperCaptureDuration_s = 1;
end
if ~exist('wrapperPlotFigures', 'var')
    wrapperPlotFigures = false;
end
controls = table( ...
    runUnitTests, ...
    runSmoke540, ...
    runSmoke599, ...
    runSmoke599Offset32, ...
    runWrapper, ...
    string(baselinePath), ...
    wrapperToneAmplitude, ...
    wrapperCaptureDuration_s, ...
    wrapperPlotFigures, ...
    'VariableNames', ["RunUnitTests", "RunSmoke540", "RunSmoke599", "RunSmoke599Offset32", "RunWrapper", "BaselinePath", "WrapperToneAmplitude", "WrapperCaptureDuration_s", "WrapperPlotFigures"]);
disp(controls);
%[text] The executable smoke stages below cover the stable branch-default and HDTV-band comparison runs. The additional |1.5 MHz| placement and amplitude experiments are documented in the prior-results table above instead of being rerun automatically because they depended on temporary physical setups.
smokeConfigurations = table( ...
    ["Stage 6A"; "Stage 6B"; "Stage 6C"], ...
    [540e6; 599e6; 599e6], ...
    [6.144e6; 8e6; 8e6], ...
    [200e3; 0; 0], ...
    [250e3; 250e3; 3.2e6], ...
    [0.25; 0.5; 0.5], ...
    ["30,50"; "30,50"; "30,50"], ...
    ["Branch-default comparison run"; "HDTV-band comparison run"; "Higher-offset comparison run away from the strongest occupied ATSC content"], ...
    'VariableNames', ["Stage", "CenterFrequency_Hz", "SampleRate_Hz", "LOOffset_Hz", "ToneOffset_Hz", "ToneAmplitude", "Gain", "Intent"]);
disp(smokeConfigurations);
%%
%[text] ## Unit Tests
%[text] The Phase 1 unit-test pass tells us whether the standalone wrapper, helpers, and baseline commissioning logic are internally consistent before any hardware step is treated as authoritative.
unitBlock = localRunUnitTestBlock(runUnitTests);
localDisplayRunBlock(unitBlock);
%%
%[text] ## Stage 6A Smoke Test: Branch Default |540 MHz / 6.144 MSps / 250 kHz|
%[text] This run reproduces the branch-default Stage 6 settings so later |599 MHz| runs can be compared directly against the original implementation baseline.
smoke540Block = localRunSmokeBlock( ...
    runSmoke540, ...
    "Stage 6A: 540 MHz / 250 kHz", ...
    'SessionID', "pluto_usrp_smoke_540_live", ...
    'CaptureFileBase', "pluto_usrp_smoke_540_live", ...
    'CenterFrequency_Hz', 540e6, ...
    'SampleRate_Hz', 6.144e6, ...
    'LOOffset_Hz', 200e3, ...
    'ToneOffset_Hz', 250e3, ...
    'ToneAmplitude', 0.25, ...
    'CaptureDuration_s', 1, ...
    'Verbose', true);
localDisplayRunBlock(smoke540Block);
%%
%[text] ## Stage 6B Smoke Test: |599 MHz / 8 MSps / 250 kHz|
%[text] This run aligns the smoke test to the current HDTV collection band while keeping the injected tone at |250 kHz| so it can be compared directly with the branch-default settings.
smoke599Block = localRunSmokeBlock( ...
    runSmoke599, ...
    "Stage 6B: 599 MHz / 250 kHz", ...
    'SessionID', "pluto_usrp_smoke_599_live", ...
    'CaptureFileBase', "pluto_usrp_smoke_599_live", ...
    'CenterFrequency_Hz', 599e6, ...
    'SampleRate_Hz', 8e6, ...
    'LOOffset_Hz', 0, ...
    'ToneOffset_Hz', 250e3, ...
    'ToneAmplitude', 0.5, ...
    'CaptureDuration_s', 1, ...
    'Verbose', true);
localDisplayRunBlock(smoke599Block);
%%
%[text] ## Stage 6C Smoke Test: |599 MHz / 8 MSps / 3.2 MHz|
%[text] This run keeps the |599 MHz| tuning but moves the Pluto tone away from the strongest occupied ATSC content so the tone detect margin is easier to interpret.
smoke599Offset32Block = localRunSmokeBlock( ...
    runSmoke599Offset32, ...
    "Stage 6C: 599 MHz / 3.2 MHz", ...
    'SessionID', "pluto_usrp_smoke_599_offset32_live", ...
    'CaptureFileBase', "pluto_usrp_smoke_599_offset32_live", ...
    'CenterFrequency_Hz', 599e6, ...
    'SampleRate_Hz', 8e6, ...
    'LOOffset_Hz', 0, ...
    'ToneOffset_Hz', 3.2e6, ...
    'ToneAmplitude', 0.5, ...
    'CaptureDuration_s', 1, ...
    'Verbose', true);
localDisplayRunBlock(smoke599Offset32Block);
%%
%[text] ## Optional Full Phase 1 Wrapper
%[text] Leave this disabled until a commissioned baseline exists and the preferred smoke configuration looks physically reasonable.
wrapperBlock = localRunWrapperBlock( ...
    runWrapper, ...
    projectRoot, ...
    baselinePath, ...
    wrapperToneAmplitude, ...
    wrapperCaptureDuration_s, ...
    wrapperPlotFigures);
localDisplayRunBlock(wrapperBlock);
%%
%[text] ## Consolidated Smoke-Test Comparison
%[text] This table puts the current smoke-test metrics next to each other so the notebook can be shared without scrolling through every raw struct dump.
smokeComparison = localBuildSmokeComparisonTable({smoke540Block, smoke599Block, smoke599Offset32Block});
if height(smokeComparison) > 0
    disp(smokeComparison);
else
    disp("No smoke-test comparison rows were available.");
end
%%
%[text] ## Notebook Summary
%[text] Use this last section as the short narrative when explaining the session later.
summaryLines = localBuildNotebookSummaryLines(unitBlock, {smoke540Block, smoke599Block, smoke599Offset32Block}, wrapperBlock);
disp(summaryLines);
%%
%[text] ## Saved Workspace Snapshot
%[text] The struct below is convenient to save manually after review if you want a secondary machine-readable artifact alongside the notebook itself.
validationResults = struct( ...
    'agreedContext', agreedContext, ...
    'workflowAudit', workflowAudit, ...
    'functionAudit', functionAudit, ...
    'priorObservedResults', priorObservedResults, ...
    'priorObservedNotes', priorObservedNotes, ...
    'controls', controls, ...
    'smokeConfigurations', smokeConfigurations, ...
    'unitBlock', unitBlock, ...
    'smoke540Block', smoke540Block, ...
    'smoke599Block', smoke599Block, ...
    'smoke599Offset32Block', smoke599Offset32Block, ...
    'wrapperBlock', wrapperBlock, ...
    'smokeComparison', smokeComparison, ...
    'summaryLines', summaryLines);
disp("Use save('phase1ValidationResults.mat','validationResults') if you want a MAT-file copy of this session.");
function block = localRunUnitTestBlock(enabled)
block = struct( ...
    'label', "Unit Tests", ...
    'status', "SKIPPED", ...
    'summary_table', table(), ...
    'notes', "Unit tests were skipped by run control.", ...
    'error_report', "", ...
    'result', matlab.unittest.TestResult.empty(0, 1));
if ~enabled
    return
end
try
    helperResults = runtests("PlutoTonePrecheckHelperTest.m");
    wrapperResults = runtests("PlutoToneWrapperTest.m");
    baselineResults = runtests("PlutoToneBaselineCommissionTest.m");
    results = [helperResults(:); wrapperResults(:); baselineResults(:)];
    [summaryTable, notes] = localSummarizeUnitResults(results);
    block.status = "COMPLETED";
    block.summary_table = summaryTable;
    block.notes = notes;
    block.result = results;
catch me
    block.status = "ERROR";
    block.summary_table = table();
    block.notes = [ ...
        "The unit-test block stopped on an execution error."; ...
        "Review the error details below before treating later stages as trustworthy."];
    block.error_report = string(getReport(me, 'extended', 'hyperlinks', 'off'));
    block.result = matlab.unittest.TestResult.empty(0, 1);
end
end
function block = localRunSmokeBlock(enabled, label, varargin)
block = struct( ...
    'label', string(label), ...
    'status', "SKIPPED", ...
    'summary_table', table(), ...
    'notes', string(label) + " was skipped by run control.", ...
    'error_report', "", ...
    'result', struct());
if ~enabled
    return
end
try
    result = runPlutoToneStage6Smoke(varargin{:});
    [summaryTable, notes] = localSummarizeSmokeResult(string(label), result);
    block.status = "COMPLETED";
    block.summary_table = summaryTable;
    block.notes = notes;
    block.result = result;
catch me
    block.status = "ERROR";
    block.summary_table = table();
    block.notes = [ ...
        string(label) + " stopped on an execution error."; ...
        "Review the error details below before drawing RF conclusions."];
    block.error_report = string(getReport(me, 'extended', 'hyperlinks', 'off'));
    block.result = struct();
end
end
function block = localRunWrapperBlock(enabled, projectRoot, baselinePath, toneAmplitude, captureDuration_s, plotFigures)
block = struct( ...
    'label', "Full Phase 1 Wrapper", ...
    'status', "SKIPPED", ...
    'summary_table', table(), ...
    'notes', "Full wrapper run was skipped by run control.", ...
    'error_report', "", ...
    'result', struct());
if ~enabled
    return
end
if strlength(string(baselinePath)) == 0
    block.status = "ERROR";
    block.notes = [ ...
        "The full wrapper was requested, but |baselinePath| is empty."; ...
        "Set |baselinePath| to a commissioned baseline before enabling |runWrapper|."];
    return
end
try
    result = runPlutoTonePrecheck( ...
        'BaselinePath', baselinePath, ...
        'CaptureRoot', fullfile(projectRoot, 'captures', 'plutoPrecheck'), ...
        'RadioName', "My USRP N320", ...
        'CaptureFileBase', "pluto_tone_precheck_live", ...
        'CenterFrequency_Hz', 599e6, ...
        'SampleRate_Hz', 8e6, ...
        'LOOffset_Hz', 0, ...
        'Gain', [30 50], ...
        'ToneOffset_Hz', 3.2e6, ...
        'ToneAmplitude', toneAmplitude, ...
        'CaptureDuration_s', captureDuration_s, ...
        'PlotFigures', plotFigures, ...
        'Verbose', true);
    [summaryTable, notes] = localSummarizeWrapperResult(result);
    block.status = "COMPLETED";
    block.summary_table = summaryTable;
    block.notes = notes;
    block.result = result;
catch me
    block.status = "ERROR";
    block.summary_table = table();
    block.notes = [ ...
        "The full wrapper stopped on an execution error."; ...
        "Review the error details below and confirm the baseline plus Pluto runtime are valid on this machine."];
    block.error_report = string(getReport(me, 'extended', 'hyperlinks', 'off'));
    block.result = struct();
end
end
function localDisplayRunBlock(block)
disp("Status: " + string(block.status));
if istable(block.summary_table) && height(block.summary_table) > 0
    disp(block.summary_table);
end
if ~isempty(block.notes)
    disp(string(block.notes));
end
if strlength(string(block.error_report)) > 0
    disp("Error details:");
    disp(string(block.error_report));
end
end
function [summaryTable, notes] = localSummarizeUnitResults(results)
if isempty(results)
    summaryTable = table();
    notes = "No unit-test results were available.";
    return
end
summaryTable = table( ...
    string({results.Name})', ...
    [results.Passed]', ...
    [results.Failed]', ...
    [results.Incomplete]', ...
    [results.Duration]', ...
    'VariableNames', ["Name", "Passed", "Failed", "Incomplete", "Duration_s"]);
failedNames = string({results([results.Failed]).Name})';
incompleteNames = string({results([results.Incomplete]).Name})';
notes = strings(0, 1);
notes(end + 1) = "Unit-test summary:";
notes(end + 1) = "Passed: " + string(nnz([results.Passed]));
notes(end + 1) = "Failed: " + string(nnz([results.Failed]));
notes(end + 1) = "Incomplete: " + string(nnz([results.Incomplete]));
if ~isempty(failedNames)
    notes(end + 1) = "Failed cases: " + join(failedNames, ", ");
else
    notes(end + 1) = "No hard unit-test failures were reported.";
end
if ~isempty(incompleteNames)
    notes(end + 1) = "Incomplete cases: " + join(incompleteNames, ", ");
end
missingRuntimeTest = contains(incompleteNames, "testWrapperFailsGracefullyWhenPlutoRuntimeMissing");
if any(missingRuntimeTest)
    notes(end + 1) = "The missing-runtime wrapper case is expected to be incomplete on machines where the Pluto support package is already installed.";
end
end
function [summaryTable, notes] = localSummarizeSmokeResult(label, result)
summaryTable = table( ...
    string(label), ...
    logical(localFieldOrDefault(result, {'reference_metrics', 'tone_found'}, false)), ...
    logical(localFieldOrDefault(result, {'surveillance_metrics', 'tone_found'}, false)), ...
    double(localFieldOrDefault(result, {'reference_metrics', 'detect_margin_db'}, NaN)), ...
    double(localFieldOrDefault(result, {'surveillance_metrics', 'detect_margin_db'}, NaN)), ...
    double(localFieldOrDefault(result, {'reference_metrics', 'frequency_error_hz'}, NaN)), ...
    double(localFieldOrDefault(result, {'surveillance_metrics', 'frequency_error_hz'}, NaN)), ...
    double(localFieldOrDefault(result, {'joint_metrics', 'channel_frequency_delta_hz'}, NaN)), ...
    double(localFieldOrDefault(result, {'joint_metrics', 'xcorr_peak_db'}, NaN)), ...
    'VariableNames', ["RunLabel", "RefToneFound", "SurvToneFound", "RefDetectMargin_dB", "SurvDetectMargin_dB", "RefFreqErr_Hz", "SurvFreqErr_Hz", "ChannelFreqDelta_Hz", "XcorrPeak_dB"]);
refToneFound = summaryTable.RefToneFound;
survToneFound = summaryTable.SurvToneFound;
refDetect = summaryTable.RefDetectMargin_dB;
survDetect = summaryTable.SurvDetectMargin_dB;
jointDelta = summaryTable.ChannelFreqDelta_Hz;
xcorrPeak = summaryTable.XcorrPeak_dB;
notes = strings(0, 1);
notes(end + 1) = string(label) + " summary:";
if refToneFound && survToneFound
    notes(end + 1) = "Both channels found the injected tone.";
else
    notes(end + 1) = "At least one channel did not find the injected tone.";
end
if isfinite(refDetect) && isfinite(survDetect) && refDetect > 6 && survDetect > 6
    notes(end + 1) = "The tone stands clearly above the local floor on both channels.";
elseif isfinite(refDetect) && isfinite(survDetect) && refDetect > 0 && survDetect > 0
    notes(end + 1) = "The tone is visible on both channels, but the margin is still modest.";
else
    notes(end + 1) = "At least one channel has weak or negative detect margin, so this is not yet a strong commissioning candidate.";
end
if isfinite(jointDelta) && jointDelta < 1e3
    notes(end + 1) = "Inter-channel frequency agreement is strong.";
elseif isfinite(jointDelta) && jointDelta < 3e3
    notes(end + 1) = "Inter-channel frequency agreement is usable but still worth watching.";
else
    notes(end + 1) = "Inter-channel frequency agreement is weak; common RF offset or poor tone prominence is likely.";
end
if isfinite(xcorrPeak) && xcorrPeak > -10
    notes(end + 1) = "Advisory cross-correlation looks reasonably coherent.";
else
    notes(end + 1) = "Advisory cross-correlation is weak.";
end
if contains(string(label), "250 kHz") && (refDetect <= 0 || survDetect <= 0)
    notes(end + 1) = "Because this run uses a 250 kHz offset inside the broadcast band, weak detect margin can reflect occupied ATSC content rather than a broken capture path.";
end
if contains(string(label), "3.2 MHz") && refToneFound && survToneFound
    notes(end + 1) = "The wider tone offset separates the injected tone from the strongest broadcast energy and should be easier to interpret than the 250 kHz runs.";
end
end
function [summaryTable, notes] = localSummarizeWrapperResult(result)
summaryTable = table( ...
    string(localFieldOrDefault(result, {'status'}, "")), ...
    logical(localFieldOrDefault(result, {'overall_pass'}, false)), ...
    string(strjoin(localFieldOrDefault(result, {'fail_codes'}, cell(0, 1)), ", ")), ...
    string(strjoin(localFieldOrDefault(result, {'warn_codes'}, cell(0, 1)), ", ")), ...
    'VariableNames', ["Status", "OverallPass", "FailCodes", "WarnCodes"]);
notes = strings(0, 1);
notes(end + 1) = "Full wrapper summary:";
notes(end + 1) = "Status: " + string(localFieldOrDefault(result, {'status'}, ""));
if summaryTable.OverallPass
    notes(end + 1) = "The baseline-backed wrapper completed without fail codes.";
else
    notes(end + 1) = "Review the wrapper fail or warn codes before treating this run as commissionable.";
end
if isfield(result, 'precheck_summary') && isstruct(result.precheck_summary) && isfield(result.precheck_summary, 'reason_line')
    notes(end + 1) = "Wrapper reason line: " + string(result.precheck_summary.reason_line);
end
end
function smokeComparison = localBuildSmokeComparisonTable(smokeBlocks)
rows = struct( ...
    'RunLabel', {}, ...
    'RefToneFound', {}, ...
    'SurvToneFound', {}, ...
    'RefDetectMargin_dB', {}, ...
    'SurvDetectMargin_dB', {}, ...
    'RefFreqErr_Hz', {}, ...
    'SurvFreqErr_Hz', {}, ...
    'ChannelFreqDelta_Hz', {}, ...
    'XcorrPeak_dB', {});
for idx = 1:numel(smokeBlocks)
    block = smokeBlocks{idx};
    if ~isstruct(block.result) || isempty(fieldnames(block.result))
        continue
    end
    rows(end + 1).RunLabel = char(block.label); %#ok<AGROW>
    rows(end).RefToneFound = logical(localFieldOrDefault(block.result, {'reference_metrics', 'tone_found'}, false));
    rows(end).SurvToneFound = logical(localFieldOrDefault(block.result, {'surveillance_metrics', 'tone_found'}, false));
    rows(end).RefDetectMargin_dB = double(localFieldOrDefault(block.result, {'reference_metrics', 'detect_margin_db'}, NaN));
    rows(end).SurvDetectMargin_dB = double(localFieldOrDefault(block.result, {'surveillance_metrics', 'detect_margin_db'}, NaN));
    rows(end).RefFreqErr_Hz = double(localFieldOrDefault(block.result, {'reference_metrics', 'frequency_error_hz'}, NaN));
    rows(end).SurvFreqErr_Hz = double(localFieldOrDefault(block.result, {'surveillance_metrics', 'frequency_error_hz'}, NaN));
    rows(end).ChannelFreqDelta_Hz = double(localFieldOrDefault(block.result, {'joint_metrics', 'channel_frequency_delta_hz'}, NaN));
    rows(end).XcorrPeak_dB = double(localFieldOrDefault(block.result, {'joint_metrics', 'xcorr_peak_db'}, NaN));
end
if isempty(rows)
    smokeComparison = table();
else
    smokeComparison = struct2table(rows);
end
end
function summaryLines = localBuildNotebookSummaryLines(unitBlock, smokeBlocks, wrapperBlock)
summaryLines = strings(numel(smokeBlocks) + 4, 1);
summaryLines(1) = "Phase 1 validation notebook completed.";
summaryLines(2) = localUnitSummaryLine(unitBlock);
writeIdx = 3;
for idx = 1:numel(smokeBlocks)
    summaryLines(writeIdx) = localSmokeSummaryLine(smokeBlocks{idx});
    writeIdx = writeIdx + 1;
end
summaryLines(writeIdx) = localWrapperSummaryLine(wrapperBlock);
summaryLines(writeIdx + 1) = "Phase 1 remains the authoritative standalone tone gate. Phase 2 archived-capture analysis stays separate.";
end
function line = localUnitSummaryLine(unitBlock)
if unitBlock.status == "SKIPPED"
    line = "Unit tests were skipped.";
    return
end
if unitBlock.status == "ERROR"
    line = "Unit tests stopped on an execution error.";
    return
end
results = unitBlock.result;
line = "Unit tests: " + string(nnz([results.Passed])) + " passed, " + string(nnz([results.Failed])) + " failed, " + string(nnz([results.Incomplete])) + " incomplete.";
end
function line = localSmokeSummaryLine(block)
if block.status == "SKIPPED"
    line = block.label + ": skipped.";
    return
end
if block.status == "ERROR"
    line = block.label + ": execution error.";
    return
end
refToneFound = logical(localFieldOrDefault(block.result, {'reference_metrics', 'tone_found'}, false));
survToneFound = logical(localFieldOrDefault(block.result, {'surveillance_metrics', 'tone_found'}, false));
refDetect = double(localFieldOrDefault(block.result, {'reference_metrics', 'detect_margin_db'}, NaN));
survDetect = double(localFieldOrDefault(block.result, {'surveillance_metrics', 'detect_margin_db'}, NaN));
jointDelta = double(localFieldOrDefault(block.result, {'joint_metrics', 'channel_frequency_delta_hz'}, NaN));
line = block.label + ": REF=" + string(refToneFound) + ", SURV=" + string(survToneFound) + ", margins " + compose("%.1f", refDetect) + "/" + compose("%.1f", survDetect) + " dB, channel delta " + compose("%.1f", jointDelta) + " Hz.";
end
function line = localWrapperSummaryLine(block)
if block.status == "SKIPPED"
    line = "Full wrapper run was skipped.";
    return
end
if block.status == "ERROR"
    line = "Full wrapper run stopped on an execution or configuration error.";
    return
end
line = "Full wrapper status: " + string(localFieldOrDefault(block.result, {'status'}, ""));
end
function value = localFieldOrDefault(source, fieldPath, defaultValue)
value = defaultValue;
current = source;
for idx = 1:numel(fieldPath)
    fieldName = fieldPath{idx};
    if ~(isstruct(current) && isfield(current, fieldName))
        return
    end
    current = current.(fieldName);
end
value = current;
end
%[appendix]{"version":"1.0"}
%---
%[metadata:view]
%   data: {"layout":"inline"}
%---
