classdef PlutoToneCommissioningSweepSupportTest < matlab.unittest.TestCase
    %PLUTOTONECOMMISSIONINGSWEEPSUPPORTTEST Regression coverage for sweep-support helpers.

    properties (Access = private)
        SourceRoot string
    end

    methods (TestClassSetup)
        function addSourcePath(testCase)
            sourceRoot = string(fileparts(mfilename('fullpath')));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(char(sourceRoot)));
            testCase.SourceRoot = sourceRoot;
        end
    end

    methods (Test)
        function testDefaultThresholdsMatchExpectedSchema(testCase)
            thresholds = helperPlutoToneDefaultThresholds();

            testCase.verifyEqual(thresholds.reference.detect_margin_min_db, 6);
            testCase.verifyEqual(thresholds.reference.frequency_error_max_hz, 3e3);
            testCase.verifyEqual(thresholds.joint.channel_frequency_delta_max_hz, 2e3);
            testCase.verifyEqual(thresholds.joint.xcorr_lag_advisory_max_samples, 64);
        end

        function testPromotedSmokeResultCanBeSavedAndReloaded(testCase)
            smoke_result = localBuildSmokeResult();
            result = helperPlutoToneBuildStandaloneResultFromSmoke( ...
                smoke_result, ...
                'RunID', 'commissioning_smoke_demo', ...
                'PlotFigures', false, ...
                'Verbose', false);

            run_folder = string(tempname(char(testCase.SourceRoot)));
            testCase.addTeardown(@() localSafeRemoveFolder(run_folder));

            [artifact_paths, result_out] = helperPlutoToneWriteArtifacts( ...
                result, ...
                'RunFolder', run_folder, ...
                'CopyCaptureFile', false, ...
                'FigureVisibility', 'off', ...
                'Verbose', false);

            reloaded = helperPlutoToneLoadResult(char(artifact_paths.result_mat));

            testCase.verifyEqual(string(result_out.run_id), "commissioning_smoke_demo");
            testCase.verifyEqual(result_out.status, 'WARN');
            testCase.verifyTrue(any(strcmp(result_out.warn_codes, 'CHANNEL_FREQUENCY_DELTA_NEAR_LIMIT')));
            testCase.verifyEqual(string(reloaded.run_id), string(result_out.run_id));
            testCase.verifyEqual(reloaded.joint_metrics.channel_frequency_delta_hz, ...
                result_out.joint_metrics.channel_frequency_delta_hz, AbsTol = 1e-9);
        end

        function testReviewRebuildsSweepSummaryFromSavedRunArtifacts(testCase)
            sweep_folder = string(tempname(char(testCase.SourceRoot)));
            run_root = fullfile(sweep_folder, 'runs');
            mkdir(run_root);
            testCase.addTeardown(@() localSafeRemoveFolder(sweep_folder));

            smoke_result_1 = localBuildSmokeResult();
            result_1 = helperPlutoToneBuildStandaloneResultFromSmoke( ...
                smoke_result_1, ...
                'RunID', 'pluto_tone_commissioning_demo_offset_250kHz_amp_0p50_r01', ...
                'PlotFigures', false, ...
                'Verbose', false);
            helperPlutoToneWriteArtifacts( ...
                result_1, ...
                'RunFolder', fullfile(run_root, 'pluto_tone_commissioning_demo_offset_250kHz_amp_0p50_r01'), ...
                'CopyCaptureFile', false, ...
                'FigureVisibility', 'off', ...
                'Verbose', false);

            smoke_result_2 = localBuildSmokeResult();
            smoke_result_2.reference_metrics.detect_margin_db = 8.5;
            smoke_result_2.surveillance_metrics.detect_margin_db = 8.0;
            smoke_result_2.joint_metrics.channel_frequency_delta_hz = 800;
            smoke_result_2.joint_metrics.status = 'PASS';
            smoke_result_2.joint_metrics.warn_codes = {cell(0, 1)};
            result_2 = helperPlutoToneBuildStandaloneResultFromSmoke( ...
                smoke_result_2, ...
                'RunID', 'pluto_tone_commissioning_demo_offset_250kHz_amp_0p50_r02', ...
                'PlotFigures', false, ...
                'Verbose', false);
            helperPlutoToneWriteArtifacts( ...
                result_2, ...
                'RunFolder', fullfile(run_root, 'pluto_tone_commissioning_demo_offset_250kHz_amp_0p50_r02'), ...
                'CopyCaptureFile', false, ...
                'FigureVisibility', 'off', ...
                'Verbose', false);

            review = reviewPlutoToneCommissioningSweep(sweep_folder, ...
                'PlacementID', 'unit_test_fixed_setup', ...
                'Verbose', false);

            testCase.verifyEqual(height(review.run_table), 2);
            testCase.verifyEqual(height(review.configuration_summary), 1);
            testCase.verifyEqual(review.configuration_summary.NumCompleted(1), 2);
            testCase.verifyTrue(isfile(char(review.artifact_paths.summary_txt)));
            testCase.verifyTrue(isfile(char(review.artifact_paths.configuration_summary_csv)));
            testCase.verifyTrue(contains(string(review.summary_text), "Recommended candidate"));
        end
    end
end

function smoke_result = localBuildSmokeResult()
reference_metrics = struct( ...
    'channel_label', 'REF', ...
    'channel_index', 2, ...
    'rx_label', 'CH2/RX2', ...
    'tone_found', true, ...
    'expected_frequency_hz', 250e3, ...
    'measured_frequency_hz', 249500, ...
    'frequency_error_hz', -500, ...
    'level_dbfs', -14.5, ...
    'tone_peak_dbfs', -55.0, ...
    'local_floor_dbfs', -62.0, ...
    'detect_margin_db', 7.0, ...
    'level_delta_vs_baseline_db', NaN, ...
    'status', 'PASS', ...
    'fail_codes', {cell(0, 1)}, ...
    'warn_codes', {cell(0, 1)});

surveillance_metrics = struct( ...
    'channel_label', 'SURV', ...
    'channel_index', 1, ...
    'rx_label', 'CH1/RX1', ...
    'tone_found', true, ...
    'expected_frequency_hz', 250e3, ...
    'measured_frequency_hz', 250900, ...
    'frequency_error_hz', 900, ...
    'level_dbfs', -18.0, ...
    'tone_peak_dbfs', -57.0, ...
    'local_floor_dbfs', -63.5, ...
    'detect_margin_db', 6.5, ...
    'level_delta_vs_baseline_db', NaN, ...
    'status', 'PASS', ...
    'fail_codes', {cell(0, 1)}, ...
    'warn_codes', {cell(0, 1)});

joint_metrics = struct( ...
    'channel_frequency_delta_hz', 1400, ...
    'xcorr_lag_samples', 1, ...
    'xcorr_lag_seconds', 1e-6, ...
    'xcorr_peak_db', -8.5, ...
    'xcorr_note', 'demo', ...
    'status', 'WARN', ...
    'fail_codes', {cell(0, 1)}, ...
    'warn_codes', {{'CHANNEL_FREQUENCY_DELTA_NEAR_LIMIT'}});

smoke_result = struct( ...
    'settings', struct( ...
        'session_id', 'smoke_demo', ...
        'capture_root', 'demo_capture_root', ...
        'radio_name', 'Unit Test Radio', ...
        'capture_file_base', 'smoke_demo', ...
        'center_frequency_hz', 599e6, ...
        'sample_rate_hz', 8e6, ...
        'lo_offset_hz', 0, ...
        'capture_tune_frequency_hz', 599e6, ...
        'gain', [30 50], ...
        'tone_offset_hz', 250e3, ...
        'tone_rf_frequency_hz', 599.25e6, ...
        'tone_amplitude', 0.5, ...
        'capture_duration_s', 1), ...
    'capture_info', struct( ...
        'capture_session_id', 'smoke_demo', ...
        'capture_file_path', '', ...
        'local_capture_files', strings(0, 1), ...
        'recording_utc', posixtime(datetime('now', 'TimeZone', 'UTC')), ...
        'header_center_frequency_hz', 599e6, ...
        'header_lo_offset_hz', 0, ...
        'header_tune_frequency_hz', 599e6, ...
        'header_sample_rate_hz', 8e6, ...
        'samples_per_channel', 8e6, ...
        'samples_scored', 8e6, ...
        'slice_duration_s', 1, ...
        'reader_metadata', struct()), ...
    'reference_metrics', reference_metrics, ...
    'surveillance_metrics', surveillance_metrics, ...
    'joint_metrics', joint_metrics);
end

function localSafeRemoveFolder(folder_path)
folder_path = char(string(folder_path));
if isfolder(folder_path)
    rmdir(folder_path, 's');
end
end
