classdef PlutoToneWrapperTest < matlab.unittest.TestCase
    %PLUTOTONEWRAPPERTEST Regression coverage for the live wrapper's safe paths.

    properties (Access = private)
        SourceRoot string
    end

    methods (TestClassSetup)
        function addSourcePath(testCase)
            sourceRoot = string(fileparts(mfilename('fullpath')));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(char(sourceRoot)));
            testCase.SourceRoot = sourceRoot;
        end
    end

    methods (TestMethodSetup)
        function resetRandomState(testCase)
            original_rng = rng;
            testCase.addTeardown(@() rng(original_rng));
            rng(11, 'twister');
        end
    end

    methods (Test)
        function testWrapperFailsBeforeHardwareOnBaselineSettingsMismatch(testCase)
            [baseline_path, wrapper_settings] = localCreateBaseline(testCase);
            capture_root = string(tempname(char(testCase.SourceRoot)));
            testCase.addTeardown(@() localSafeRemoveFolder(capture_root));

            result = runPlutoTonePrecheck( ...
                'BaselinePath', baseline_path, ...
                'CaptureRoot', capture_root, ...
                'RadioName', wrapper_settings.RadioName, ...
                'CaptureFileBase', wrapper_settings.CaptureFileBase, ...
                'CenterFrequency_Hz', wrapper_settings.CenterFrequency_Hz, ...
                'SampleRate_Hz', wrapper_settings.SampleRate_Hz, ...
                'LOOffset_Hz', wrapper_settings.LOOffset_Hz, ...
                'Gain', wrapper_settings.Gain, ...
                'ToneOffset_Hz', wrapper_settings.ToneOffset_Hz + 10e3, ...
                'ToneAmplitude', wrapper_settings.ToneAmplitude, ...
                'CaptureDuration_s', wrapper_settings.CaptureDuration_s, ...
                'PlotFigures', false, ...
                'Verbose', false);
            testCase.addTeardown(@() localSafeRemoveFolder(string(result.artifact_paths.run_folder)));

            testCase.verifyEqual(result.status, 'FAIL');
            testCase.verifyTrue(any(strcmp(result.fail_codes, 'BASELINE_SETTINGS_MISMATCH')));
            testCase.verifyFalse(any(strcmp(result.fail_codes, 'PLUTO_CONNECT_FAILED')));
            testCase.verifyFalse(result.baseline_comparison.settings_match);
            testCase.verifyTrue(any(strcmp(result.baseline_comparison.settings_mismatch_fields, 'tone_offset_hz')));
            testCase.verifyTrue(isfile(char(result.artifact_paths.result_mat)));
            testCase.verifyTrue(contains(string(result.precheck_summary.reason_line), "BASELINE_SETTINGS_MISMATCH"));
        end

        function testWrapperFailsGracefullyWhenPlutoRuntimeMissing(testCase)
            testCase.assumeTrue(localPlutoRuntimeMissing(), ...
                'Pluto support-package runtime is installed; missing-runtime regression is not applicable.');

            [baseline_path, wrapper_settings] = localCreateBaseline(testCase);
            capture_root = string(tempname(char(testCase.SourceRoot)));
            testCase.addTeardown(@() localSafeRemoveFolder(capture_root));

            result = runPlutoTonePrecheck( ...
                'BaselinePath', baseline_path, ...
                'CaptureRoot', capture_root, ...
                'RadioName', wrapper_settings.RadioName, ...
                'CaptureFileBase', wrapper_settings.CaptureFileBase, ...
                'CenterFrequency_Hz', wrapper_settings.CenterFrequency_Hz, ...
                'SampleRate_Hz', wrapper_settings.SampleRate_Hz, ...
                'LOOffset_Hz', wrapper_settings.LOOffset_Hz, ...
                'Gain', wrapper_settings.Gain, ...
                'ToneOffset_Hz', wrapper_settings.ToneOffset_Hz, ...
                'ToneAmplitude', wrapper_settings.ToneAmplitude, ...
                'CaptureDuration_s', wrapper_settings.CaptureDuration_s, ...
                'PlotFigures', false, ...
                'Verbose', false);
            testCase.addTeardown(@() localSafeRemoveFolder(string(result.artifact_paths.run_folder)));

            testCase.verifyEqual(result.status, 'FAIL');
            testCase.verifyTrue(any(strcmp(result.fail_codes, 'PLUTO_CONNECT_FAILED')));
            testCase.verifyTrue(result.baseline_comparison.settings_match);
            testCase.verifyFalse(result.overall_pass);
            testCase.verifyEmpty(result.capture_info.capture_file_path);
            testCase.verifyTrue(isfile(char(result.artifact_paths.result_mat)));
            testCase.verifyTrue(isfile(char(result.artifact_paths.result_json)));
            testCase.verifyTrue(isfile(char(result.artifact_paths.summary_txt)));
            testCase.verifyTrue(isfile(char(result.artifact_paths.summary_png)));
            testCase.verifyTrue(contains(string(result.precheck_summary.reason_line), "PLUTO_CONNECT_FAILED"));
        end
    end
end

function [baseline_path, wrapper_settings] = localCreateBaseline(testCase)
wrapper_settings = localWrapperSettings();
result = localBuildStandaloneResult(wrapper_settings);

run_folder = string(tempname(char(testCase.SourceRoot)));
baseline_root = string(tempname(char(testCase.SourceRoot)));
testCase.addTeardown(@() localSafeRemoveFolder(run_folder));
testCase.addTeardown(@() localSafeRemoveFolder(baseline_root));

helperPlutoToneWriteArtifacts( ...
    result, ...
    'RunFolder', run_folder, ...
    'CopyCaptureFile', false, ...
    'FigureVisibility', 'off', ...
    'Verbose', false);

baseline = commissionPlutoToneBaseline( ...
    'BaselineRoot', baseline_root, ...
    'BaselineID', 'wrapper_test_baseline', ...
    'SiteID', 'test_site', ...
    'PlacementID', 'bench_1', ...
    'PlacementNotes', 'wrapper test baseline', ...
    'Thresholds', localThresholds(), ...
    'RadioName', wrapper_settings.RadioName, ...
    'CaptureFileBase', wrapper_settings.CaptureFileBase, ...
    'CenterFrequency_Hz', wrapper_settings.CenterFrequency_Hz, ...
    'SampleRate_Hz', wrapper_settings.SampleRate_Hz, ...
    'LOOffset_Hz', wrapper_settings.LOOffset_Hz, ...
    'Gain', wrapper_settings.Gain, ...
    'ToneOffset_Hz', wrapper_settings.ToneOffset_Hz, ...
    'ToneAmplitude', wrapper_settings.ToneAmplitude, ...
    'CaptureDuration_s', wrapper_settings.CaptureDuration_s, ...
    'RunSources', {char(run_folder)}, ...
    'PlotFigures', false, ...
    'Verbose', false);

baseline_path = string(baseline.provenance.baseline_mat_path);
end

function wrapper_settings = localWrapperSettings()
wrapper_settings = struct( ...
    'RadioName', 'Unit Test Radio', ...
    'CaptureFileBase', 'wrapper_capture', ...
    'CenterFrequency_Hz', 540e6, ...
    'SampleRate_Hz', 1e6, ...
    'LOOffset_Hz', 200e3, ...
    'Gain', [30 50], ...
    'ToneOffset_Hz', 250e3, ...
    'ToneAmplitude', 0.5, ...
    'CaptureDuration_s', 0.065536);
end

function result = localBuildStandaloneResult(wrapper_settings)
scenario = struct( ...
    'sample_rate_hz', wrapper_settings.SampleRate_Hz, ...
    'n_samples', round(wrapper_settings.CaptureDuration_s * wrapper_settings.SampleRate_Hz), ...
    'tone_frequency_hz', wrapper_settings.ToneOffset_Hz);

reference_signal = localSynthesizeTone( ...
    scenario.sample_rate_hz, scenario.n_samples, scenario.tone_frequency_hz, 0.14, 0.01);
surveillance_signal = localSynthesizeTone( ...
    scenario.sample_rate_hz, scenario.n_samples, scenario.tone_frequency_hz, 0.09, 0.01);

reference_baseline = helperPlutoToneScoreChannel( ...
    reference_signal, ...
    scenario.sample_rate_hz, ...
    'ChannelLabel', 'REF', ...
    'ExpectedFrequencyHz', scenario.tone_frequency_hz, ...
    'Verbose', false);

surveillance_baseline = helperPlutoToneScoreChannel( ...
    surveillance_signal, ...
    scenario.sample_rate_hz, ...
    'ChannelLabel', 'SURV', ...
    'ExpectedFrequencyHz', scenario.tone_frequency_hz, ...
    'Verbose', false);

thresholds = localThresholds();
reference_metrics = helperPlutoToneScoreChannel( ...
    reference_signal, ...
    scenario.sample_rate_hz, ...
    'ChannelLabel', 'REF', ...
    'ExpectedFrequencyHz', scenario.tone_frequency_hz, ...
    'BaselineMetrics', reference_baseline, ...
    'Thresholds', thresholds.reference, ...
    'Verbose', false);

surveillance_metrics = helperPlutoToneScoreChannel( ...
    surveillance_signal, ...
    scenario.sample_rate_hz, ...
    'ChannelLabel', 'SURV', ...
    'ExpectedFrequencyHz', scenario.tone_frequency_hz, ...
    'BaselineMetrics', surveillance_baseline, ...
    'Thresholds', thresholds.surveillance, ...
    'Verbose', false);

joint_metrics = helperPlutoToneScoreJointMetrics( ...
    reference_signal, ...
    surveillance_signal, ...
    scenario.sample_rate_hz, ...
    'ReferenceMetrics', reference_metrics, ...
    'SurveillanceMetrics', surveillance_metrics, ...
    'Thresholds', thresholds.joint, ...
    'Verbose', false);

result = struct( ...
    'schema_version', 1, ...
    'run_id', char("wrapper_seed_" + string(tempname)), ...
    'created_utc', char(string(datetime('now', 'TimeZone', 'UTC', 'Format', 'yyyy-MM-dd''T''HH:mm:ss''Z'''))), ...
    'overall_pass', true, ...
    'status', 'PASS', ...
    'fail_codes', {cell(0, 1)}, ...
    'warn_codes', {cell(0, 1)}, ...
    'settings', struct( ...
        'baseline_path', 'baseline_seed.mat', ...
        'capture_root', 'seed_capture_root', ...
        'radio_name', wrapper_settings.RadioName, ...
        'capture_file_base', wrapper_settings.CaptureFileBase, ...
        'center_frequency_hz', wrapper_settings.CenterFrequency_Hz, ...
        'sample_rate_hz', wrapper_settings.SampleRate_Hz, ...
        'lo_offset_hz', wrapper_settings.LOOffset_Hz, ...
        'capture_tune_frequency_hz', wrapper_settings.CenterFrequency_Hz + wrapper_settings.LOOffset_Hz, ...
        'gain', wrapper_settings.Gain, ...
        'tone_offset_hz', wrapper_settings.ToneOffset_Hz, ...
        'tone_rf_frequency_hz', wrapper_settings.CenterFrequency_Hz + wrapper_settings.LOOffset_Hz + wrapper_settings.ToneOffset_Hz, ...
        'tone_amplitude', wrapper_settings.ToneAmplitude, ...
        'capture_duration_s', wrapper_settings.CaptureDuration_s, ...
        'plot_figures', false, ...
        'verbose', false), ...
    'capture_info', struct( ...
        'capture_session_id', 'seed_capture', ...
        'capture_file_path', '', ...
        'local_capture_files', strings(0, 1), ...
        'recording_utc', posixtime(datetime('now', 'TimeZone', 'UTC')), ...
        'header_center_frequency_hz', wrapper_settings.CenterFrequency_Hz, ...
        'header_lo_offset_hz', wrapper_settings.LOOffset_Hz, ...
        'header_tune_frequency_hz', wrapper_settings.CenterFrequency_Hz + wrapper_settings.LOOffset_Hz, ...
        'header_sample_rate_hz', wrapper_settings.SampleRate_Hz, ...
        'samples_per_channel', scenario.n_samples, ...
        'samples_scored', scenario.n_samples, ...
        'slice_duration_s', wrapper_settings.CaptureDuration_s, ...
        'reader_metadata', struct()), ...
    'channel_map', struct( ...
        'reference_label', 'REF', ...
        'reference_channel_index', 2, ...
        'reference_rx_label', 'CH2/RX2', ...
        'surveillance_label', 'SURV', ...
        'surveillance_channel_index', 1, ...
        'surveillance_rx_label', 'CH1/RX1'), ...
    'reference_metrics', reference_metrics, ...
    'surveillance_metrics', surveillance_metrics, ...
    'joint_metrics', joint_metrics, ...
    'baseline_comparison', struct( ...
        'baseline_id', 'seed_baseline', ...
        'settings_match', true, ...
        'settings_mismatch_fields', {cell(0, 1)}, ...
        'reference_level_delta_db', reference_metrics.level_delta_vs_baseline_db, ...
        'surveillance_level_delta_db', surveillance_metrics.level_delta_vs_baseline_db, ...
        'comparison_applied', true), ...
    'precheck_summary', struct(), ...
    'artifact_paths', struct());
end

function signal = localSynthesizeTone(sample_rate_hz, n_samples, tone_frequency_hz, amplitude, noise_sigma)
n = (0:n_samples - 1).';
tone = amplitude .* exp(1j * 2 * pi * tone_frequency_hz .* n ./ sample_rate_hz);
noise = noise_sigma .* (randn(n_samples, 1) + 1j * randn(n_samples, 1)) ./ sqrt(2);
signal = tone + noise;
end

function thresholds = localThresholds()
channel_thresholds = struct( ...
    'detect_margin_warn_db', 10, ...
    'detect_margin_min_db', 6, ...
    'frequency_error_warn_hz', 1.5e3, ...
    'frequency_error_max_hz', 3e3, ...
    'level_max_dbfs', -3, ...
    'baseline_level_drift_warn_db', 1.0, ...
    'baseline_level_drift_max_db', 2.0);

joint_thresholds = struct( ...
    'channel_frequency_delta_warn_hz', 1e3, ...
    'channel_frequency_delta_max_hz', 2e3, ...
    'xcorr_peak_advisory_min_db', -20, ...
    'xcorr_lag_advisory_max_samples', 64);

thresholds = struct( ...
    'reference', channel_thresholds, ...
    'surveillance', channel_thresholds, ...
    'joint', joint_thresholds);
end

function tf = localPlutoRuntimeMissing()
tf = exist('sdrtx', 'file') ~= 2 && exist('sdrtx', 'builtin') ~= 5;
end

function localSafeRemoveFolder(folder_path)
folder_path = char(string(folder_path));
if isfolder(folder_path)
    rmdir(folder_path, 's');
end
end
