classdef PlutoTonePrecheckHelperTest < matlab.unittest.TestCase
    %PLUTOTONEPRECHECKHELPERTEST Unit coverage for the first standalone helpers.

    properties (Access = private)
        SourceRoot string
    end

    methods (TestClassSetup)
        function addSourcePath(testCase)
            sourceRoot = string(fileparts(mfilename('fullpath')));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(char(sourceRoot)));
            testCase.SourceRoot = sourceRoot;
        end
    end

    methods (TestMethodSetup)
        function resetRandomState(testCase)
            original_rng = rng;
            testCase.addTeardown(@() rng(original_rng));
            rng(42, 'twister');
        end
    end

    methods (Test)
        function testChannelScorerFindsToneAndPassesThresholds(testCase)
            scenario = localMakeScenario();
            ref_signal = localSynthesizeTone(scenario.sample_rate_hz, scenario.n_samples, scenario.ref_frequency_hz, 0.14, 0.01);

            baseline_metrics = helperPlutoToneScoreChannel( ...
                ref_signal, ...
                scenario.sample_rate_hz, ...
                'ChannelLabel', 'REF', ...
                'ExpectedFrequencyHz', scenario.expected_frequency_hz, ...
                'Verbose', false);

            thresholds = struct( ...
                'detect_margin_warn_db', 10, ...
                'detect_margin_min_db', 6, ...
                'frequency_error_warn_hz', 1.5e3, ...
                'frequency_error_max_hz', 3e3, ...
                'level_max_dbfs', -3, ...
                'baseline_level_drift_warn_db', 1.0, ...
                'baseline_level_drift_max_db', 2.0);

            [metrics, diagnostics] = helperPlutoToneScoreChannel( ...
                ref_signal, ...
                scenario.sample_rate_hz, ...
                'ChannelLabel', 'REF', ...
                'ExpectedFrequencyHz', scenario.expected_frequency_hz, ...
                'BaselineMetrics', baseline_metrics, ...
                'Thresholds', thresholds, ...
                'Verbose', false);

            testCase.verifyTrue(metrics.tone_found);
            testCase.verifyEqual(metrics.status, 'PASS');
            testCase.verifyLessThanOrEqual(abs(metrics.frequency_error_hz), thresholds.frequency_error_max_hz);
            testCase.verifyGreaterThan(metrics.detect_margin_db, thresholds.detect_margin_min_db);
            testCase.verifyTrue(isfinite(metrics.level_dbfs));
            testCase.verifyTrue(isfinite(diagnostics.goertzel_bin_index));
        end

        function testJointScorerFlagsFrequencyMismatch(testCase)
            scenario = localMakeScenario();
            ref_signal = localSynthesizeTone(scenario.sample_rate_hz, scenario.n_samples, scenario.expected_frequency_hz, 0.14, 0.01);
            surv_signal = localSynthesizeTone(scenario.sample_rate_hz, scenario.n_samples, scenario.expected_frequency_hz + 4e3, 0.10, 0.01);

            ref_metrics = helperPlutoToneScoreChannel( ...
                ref_signal, ...
                scenario.sample_rate_hz, ...
                'ChannelLabel', 'REF', ...
                'ExpectedFrequencyHz', scenario.expected_frequency_hz, ...
                'Verbose', false);

            surv_metrics = helperPlutoToneScoreChannel( ...
                surv_signal, ...
                scenario.sample_rate_hz, ...
                'ChannelLabel', 'SURV', ...
                'ExpectedFrequencyHz', scenario.expected_frequency_hz, ...
                'Verbose', false);

            thresholds = struct( ...
                'channel_frequency_delta_warn_hz', 1e3, ...
                'channel_frequency_delta_max_hz', 2e3, ...
                'xcorr_peak_advisory_min_db', -15, ...
                'xcorr_lag_advisory_max_samples', 64);

            [joint_metrics, diagnostics] = helperPlutoToneScoreJointMetrics( ...
                ref_signal, ...
                surv_signal, ...
                scenario.sample_rate_hz, ...
                'ReferenceMetrics', ref_metrics, ...
                'SurveillanceMetrics', surv_metrics, ...
                'Thresholds', thresholds, ...
                'Verbose', false);

            testCase.verifyEqual(joint_metrics.status, 'FAIL');
            testCase.verifyTrue(any(strcmp(joint_metrics.fail_codes, 'CHANNEL_FREQUENCY_MISMATCH')));
            testCase.verifyGreaterThan(joint_metrics.channel_frequency_delta_hz, thresholds.channel_frequency_delta_max_hz);
            testCase.verifyTrue(isfield(diagnostics, 'correlation_abs'));
        end

        function testArtifactWriterCreatesExpectedFiles(testCase)
            scenario = localMakeScenario();
            ref_signal = localSynthesizeTone(scenario.sample_rate_hz, scenario.n_samples, scenario.expected_frequency_hz, 0.14, 0.01);
            surv_signal = localSynthesizeTone(scenario.sample_rate_hz, scenario.n_samples, scenario.expected_frequency_hz, 0.09, 0.01);

            baseline_ref = helperPlutoToneScoreChannel( ...
                ref_signal, ...
                scenario.sample_rate_hz, ...
                'ChannelLabel', 'REF', ...
                'ExpectedFrequencyHz', scenario.expected_frequency_hz, ...
                'Verbose', false);

            baseline_surv = helperPlutoToneScoreChannel( ...
                surv_signal, ...
                scenario.sample_rate_hz, ...
                'ChannelLabel', 'SURV', ...
                'ExpectedFrequencyHz', scenario.expected_frequency_hz, ...
                'Verbose', false);

            ref_metrics = helperPlutoToneScoreChannel( ...
                ref_signal, ...
                scenario.sample_rate_hz, ...
                'ChannelLabel', 'REF', ...
                'ExpectedFrequencyHz', scenario.expected_frequency_hz, ...
                'BaselineMetrics', baseline_ref, ...
                'Thresholds', localChannelThresholds(), ...
                'Verbose', false);

            surv_metrics = helperPlutoToneScoreChannel( ...
                surv_signal, ...
                scenario.sample_rate_hz, ...
                'ChannelLabel', 'SURV', ...
                'ExpectedFrequencyHz', scenario.expected_frequency_hz, ...
                'BaselineMetrics', baseline_surv, ...
                'Thresholds', localChannelThresholds(), ...
                'Verbose', false);

            joint_metrics = helperPlutoToneScoreJointMetrics( ...
                ref_signal, ...
                surv_signal, ...
                scenario.sample_rate_hz, ...
                'ReferenceMetrics', ref_metrics, ...
                'SurveillanceMetrics', surv_metrics, ...
                'Thresholds', localJointThresholds(), ...
                'Verbose', false);

            run_folder = string(tempname(char(testCase.SourceRoot)));
            testCase.addTeardown(@() localSafeRemoveFolder(run_folder));

            result = localBuildMinimalResult(ref_metrics, surv_metrics, joint_metrics, run_folder);

            [artifact_paths, result_out] = helperPlutoToneWriteArtifacts( ...
                result, ...
                'RunFolder', run_folder, ...
                'CopyCaptureFile', false, ...
                'FigureVisibility', 'off', ...
                'Verbose', false);

            testCase.verifyTrue(isfolder(char(artifact_paths.run_folder)));
            testCase.verifyTrue(isfile(char(artifact_paths.result_mat)));
            testCase.verifyTrue(isfile(char(artifact_paths.result_json)));
            testCase.verifyTrue(isfile(char(artifact_paths.summary_txt)));
            testCase.verifyTrue(isfile(char(artifact_paths.summary_png)));
            testCase.verifyEqual(string(result_out.artifact_paths.result_mat), artifact_paths.result_mat);
            testCase.verifyTrue(contains(string(result_out.precheck_summary.headline), "PLUTO PRECHECK: PASS"));
        end
    end
end

function scenario = localMakeScenario()
scenario = struct( ...
    'sample_rate_hz', 1e6, ...
    'n_samples', 65536, ...
    'expected_frequency_hz', 250e3, ...
    'ref_frequency_hz', 250.4e3);
end

function signal = localSynthesizeTone(sample_rate_hz, n_samples, tone_frequency_hz, amplitude, noise_sigma)
n = (0:n_samples - 1).';
tone = amplitude .* exp(1j * 2 * pi * tone_frequency_hz .* n ./ sample_rate_hz);
noise = noise_sigma .* (randn(n_samples, 1) + 1j * randn(n_samples, 1)) ./ sqrt(2);
signal = tone + noise;
end

function thresholds = localChannelThresholds()
thresholds = struct( ...
    'detect_margin_warn_db', 10, ...
    'detect_margin_min_db', 6, ...
    'frequency_error_warn_hz', 1.5e3, ...
    'frequency_error_max_hz', 3e3, ...
    'level_max_dbfs', -3, ...
    'baseline_level_drift_warn_db', 1.0, ...
    'baseline_level_drift_max_db', 2.0);
end

function thresholds = localJointThresholds()
thresholds = struct( ...
    'channel_frequency_delta_warn_hz', 1e3, ...
    'channel_frequency_delta_max_hz', 2e3, ...
    'xcorr_peak_advisory_min_db', -20, ...
    'xcorr_lag_advisory_max_samples', 64);
end

function result = localBuildMinimalResult(ref_metrics, surv_metrics, joint_metrics, run_folder)
status = localResolveStatus(ref_metrics, surv_metrics, joint_metrics);
fail_codes = [ref_metrics.fail_codes(:); surv_metrics.fail_codes(:); joint_metrics.fail_codes(:)];
warn_codes = [ref_metrics.warn_codes(:); surv_metrics.warn_codes(:); joint_metrics.warn_codes(:)];

result = struct( ...
    'schema_version', 1, ...
    'run_id', 'unit_test_run', ...
    'created_utc', char(string(datetime('now', 'TimeZone', 'UTC', 'Format', 'yyyy-MM-dd''T''HH:mm:ss''Z'''))), ...
    'overall_pass', strcmp(status, 'PASS'), ...
    'status', status, ...
    'fail_codes', {fail_codes}, ...
    'warn_codes', {warn_codes}, ...
    'settings', struct( ...
        'baseline_path', fullfile(char(run_folder), 'baseline.mat'), ...
        'capture_root', char(run_folder), ...
        'radio_name', 'Unit Test Radio', ...
        'capture_file_base', 'unit_test_capture', ...
        'center_frequency_hz', 540e6, ...
        'sample_rate_hz', 1e6, ...
        'lo_offset_hz', 200e3, ...
        'capture_tune_frequency_hz', 540.2e6, ...
        'gain', [30, 50], ...
        'tone_offset_hz', 250e3, ...
        'tone_rf_frequency_hz', 540.45e6, ...
        'tone_amplitude', 0.14, ...
        'capture_duration_s', 0.065, ...
        'plot_figures', false, ...
        'verbose', false), ...
    'capture_info', struct( ...
        'capture_session_id', 'unit_test_capture', ...
        'capture_file_path', '', ...
        'local_capture_files', strings(0, 1), ...
        'recording_utc', posixtime(datetime('now', 'TimeZone', 'UTC')), ...
        'header_center_frequency_hz', 540e6, ...
        'header_lo_offset_hz', 200e3, ...
        'header_tune_frequency_hz', 540.2e6, ...
        'header_sample_rate_hz', 1e6, ...
        'samples_per_channel', 65536, ...
        'samples_scored', 65536, ...
        'slice_duration_s', 0.065536, ...
        'reader_metadata', struct()), ...
    'channel_map', struct( ...
        'reference_label', 'REF', ...
        'reference_channel_index', 2, ...
        'reference_rx_label', 'CH2/RX2', ...
        'surveillance_label', 'SURV', ...
        'surveillance_channel_index', 1, ...
        'surveillance_rx_label', 'CH1/RX1'), ...
    'reference_metrics', ref_metrics, ...
    'surveillance_metrics', surv_metrics, ...
    'joint_metrics', joint_metrics, ...
    'baseline_comparison', struct( ...
        'baseline_id', 'unit_test_baseline', ...
        'settings_match', true, ...
        'settings_mismatch_fields', {cell(0, 1)}, ...
        'reference_level_delta_db', ref_metrics.level_delta_vs_baseline_db, ...
        'surveillance_level_delta_db', surv_metrics.level_delta_vs_baseline_db, ...
        'comparison_applied', true), ...
    'precheck_summary', struct(), ...
    'artifact_paths', struct());
end

function status = localResolveStatus(ref_metrics, surv_metrics, joint_metrics)
statuses = {ref_metrics.status, surv_metrics.status, joint_metrics.status};
if any(strcmp(statuses, 'FAIL'))
    status = 'FAIL';
elseif any(strcmp(statuses, 'WARN'))
    status = 'WARN';
else
    status = 'PASS';
end
end

function localSafeRemoveFolder(folder_path)
folder_path = char(string(folder_path));
if isfolder(folder_path)
    rmdir(folder_path, 's');
end
end
