classdef PlutoToneBaselineCommissionTest < matlab.unittest.TestCase
    %PLUTOTONEBASELINECOMMISSIONTEST Unit coverage for review and baseline commissioning.

    properties (Access = private)
        SourceRoot string
    end

    methods (TestClassSetup)
        function addSourcePath(testCase)
            sourceRoot = string(fileparts(mfilename('fullpath')));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(char(sourceRoot)));
            testCase.SourceRoot = sourceRoot;
        end
    end

    methods (TestMethodSetup)
        function resetRandomState(testCase)
            original_rng = rng;
            testCase.addTeardown(@() rng(original_rng));
            rng(7, 'twister');
        end
    end

    methods (Test)
        function testReviewReloadsSavedResultFromRunFolder(testCase)
            [result, run_folder] = localBuildAndSaveResult(testCase, 0, 0);
            reviewed = reviewPlutoTonePrecheckResult(run_folder, ...
                'PlotFigures', false, ...
                'Verbose', false);

            testCase.verifyEqual(string(reviewed.run_id), string(result.run_id));
            testCase.verifyEqual(reviewed.reference_metrics.measured_frequency_hz, ...
                result.reference_metrics.measured_frequency_hz, AbsTol = 1e-9);
            testCase.verifyTrue(contains(string(reviewed.precheck_summary.headline), "PLUTO PRECHECK: PASS"));
        end

        function testCommissionAggregatesMedianStatisticsFromRunSources(testCase)
            [~, run_folder_1] = localBuildAndSaveResult(testCase, 0, 0);
            [~, run_folder_2] = localBuildAndSaveResult(testCase, 120, -0.5);
            [~, run_folder_3] = localBuildAndSaveResult(testCase, -80, 0.25);

            baseline_root = string(tempname(char(testCase.SourceRoot)));
            testCase.addTeardown(@() localSafeRemoveFolder(baseline_root));

            thresholds = localThresholds();
            baseline = commissionPlutoToneBaseline( ...
                'BaselineRoot', baseline_root, ...
                'BaselineID', 'unit_test_baseline', ...
                'SiteID', 'test_site', ...
                'PlacementID', 'bench_1', ...
                'PlacementNotes', 'unit-test placement', ...
                'Thresholds', thresholds, ...
                'RadioName', 'Unit Test Radio', ...
                'CaptureFileBase', 'demo_capture', ...
                'CenterFrequency_Hz', 540e6, ...
                'SampleRate_Hz', 1e6, ...
                'LOOffset_Hz', 200e3, ...
                'Gain', [30 50], ...
                'ToneOffset_Hz', 250e3, ...
                'ToneAmplitude', 0.14, ...
                'CaptureDuration_s', 0.065536, ...
                'RunSources', {char(run_folder_1), char(run_folder_2), char(run_folder_3)}, ...
                'PlotFigures', false, ...
                'Verbose', false);

            testCase.verifyEqual(string(baseline.baseline_id), "unit_test_baseline");
            testCase.verifyEqual(baseline.commissioning.num_runs, 3);
            testCase.verifyEqual(baseline.commissioning.aggregation_method, 'median');
            testCase.verifyTrue(isfile(char(baseline.provenance.baseline_mat_path)));
            testCase.verifyTrue(isfile(char(baseline.provenance.baseline_json_path)));
            testCase.verifyTrue(isfile(fullfile(char(baseline_root), 'unit_test_baseline', 'summary.txt')));
            testCase.verifyTrue(isfile(fullfile(char(baseline_root), 'unit_test_baseline', 'summary.png')));
            testCase.verifyEqual(baseline.statistics.reference.measured_frequency_hz, 250000, AbsTol = 200);
            testCase.verifyEqual(baseline.statistics.reference.level_dbfs, -17.0528 - 0.5 + 0.25, RelTol = 0.1);
        end
    end
end

function [result, run_folder] = localBuildAndSaveResult(testCase, frequency_offset_hz, level_delta_db)
scenario = localMakeScenario();
ref_amplitude = 0.14 .* 10 .^ (level_delta_db ./ 20);
surv_amplitude = 0.09 .* 10 .^ (level_delta_db ./ 20);

ref_signal = localSynthesizeTone( ...
    scenario.sample_rate_hz, scenario.n_samples, scenario.expected_frequency_hz + frequency_offset_hz, ref_amplitude, 0.01);
surv_signal = localSynthesizeTone( ...
    scenario.sample_rate_hz, scenario.n_samples, scenario.expected_frequency_hz + frequency_offset_hz, surv_amplitude, 0.01);

thresholds_channel = localThresholds().reference;
thresholds_joint = localThresholds().joint;

baseline_ref = helperPlutoToneScoreChannel( ...
    ref_signal, ...
    scenario.sample_rate_hz, ...
    'ChannelLabel', 'REF', ...
    'ExpectedFrequencyHz', scenario.expected_frequency_hz, ...
    'Verbose', false);

baseline_surv = helperPlutoToneScoreChannel( ...
    surv_signal, ...
    scenario.sample_rate_hz, ...
    'ChannelLabel', 'SURV', ...
    'ExpectedFrequencyHz', scenario.expected_frequency_hz, ...
    'Verbose', false);

ref_metrics = helperPlutoToneScoreChannel( ...
    ref_signal, ...
    scenario.sample_rate_hz, ...
    'ChannelLabel', 'REF', ...
    'ExpectedFrequencyHz', scenario.expected_frequency_hz, ...
    'BaselineMetrics', baseline_ref, ...
    'Thresholds', thresholds_channel, ...
    'Verbose', false);

surv_metrics = helperPlutoToneScoreChannel( ...
    surv_signal, ...
    scenario.sample_rate_hz, ...
    'ChannelLabel', 'SURV', ...
    'ExpectedFrequencyHz', scenario.expected_frequency_hz, ...
    'BaselineMetrics', baseline_surv, ...
    'Thresholds', thresholds_channel, ...
    'Verbose', false);

joint_metrics = helperPlutoToneScoreJointMetrics( ...
    ref_signal, ...
    surv_signal, ...
    scenario.sample_rate_hz, ...
    'ReferenceMetrics', ref_metrics, ...
    'SurveillanceMetrics', surv_metrics, ...
    'Thresholds', thresholds_joint, ...
    'Verbose', false);

result = localBuildMinimalResult(ref_metrics, surv_metrics, joint_metrics);
run_folder = string(tempname(char(testCase.SourceRoot)));
testCase.addTeardown(@() localSafeRemoveFolder(run_folder));
helperPlutoToneWriteArtifacts(result, ...
    'RunFolder', run_folder, ...
    'CopyCaptureFile', false, ...
    'FigureVisibility', 'off', ...
    'Verbose', false);
end

function scenario = localMakeScenario()
scenario = struct( ...
    'sample_rate_hz', 1e6, ...
    'n_samples', 65536, ...
    'expected_frequency_hz', 250e3);
end

function signal = localSynthesizeTone(sample_rate_hz, n_samples, tone_frequency_hz, amplitude, noise_sigma)
n = (0:n_samples - 1).';
tone = amplitude .* exp(1j * 2 * pi * tone_frequency_hz .* n ./ sample_rate_hz);
noise = noise_sigma .* (randn(n_samples, 1) + 1j * randn(n_samples, 1)) ./ sqrt(2);
signal = tone + noise;
end

function thresholds = localThresholds()
channel_thresholds = struct( ...
    'detect_margin_warn_db', 10, ...
    'detect_margin_min_db', 6, ...
    'frequency_error_warn_hz', 1.5e3, ...
    'frequency_error_max_hz', 3e3, ...
    'level_max_dbfs', -3, ...
    'baseline_level_drift_warn_db', 1.0, ...
    'baseline_level_drift_max_db', 2.0);

joint_thresholds = struct( ...
    'channel_frequency_delta_warn_hz', 1e3, ...
    'channel_frequency_delta_max_hz', 2e3, ...
    'xcorr_peak_advisory_min_db', -20, ...
    'xcorr_lag_advisory_max_samples', 64);

thresholds = struct( ...
    'reference', channel_thresholds, ...
    'surveillance', channel_thresholds, ...
    'joint', joint_thresholds);
end

function result = localBuildMinimalResult(ref_metrics, surv_metrics, joint_metrics)
status = localResolveStatus(ref_metrics, surv_metrics, joint_metrics);
fail_codes = [ref_metrics.fail_codes(:); surv_metrics.fail_codes(:); joint_metrics.fail_codes(:)];
warn_codes = [ref_metrics.warn_codes(:); surv_metrics.warn_codes(:); joint_metrics.warn_codes(:)];

result = struct( ...
    'schema_version', 1, ...
    'run_id', char("run_" + string(tempname)), ...
    'created_utc', char(string(datetime('now', 'TimeZone', 'UTC', 'Format', 'yyyy-MM-dd''T''HH:mm:ss''Z'''))), ...
    'overall_pass', strcmp(status, 'PASS'), ...
    'status', status, ...
    'fail_codes', {fail_codes}, ...
    'warn_codes', {warn_codes}, ...
    'settings', struct( ...
        'baseline_path', 'demo_baseline.mat', ...
        'capture_root', 'demo_capture_root', ...
        'radio_name', 'Unit Test Radio', ...
        'capture_file_base', 'demo_capture', ...
        'center_frequency_hz', 540e6, ...
        'sample_rate_hz', 1e6, ...
        'lo_offset_hz', 200e3, ...
        'capture_tune_frequency_hz', 540.2e6, ...
        'gain', [30, 50], ...
        'tone_offset_hz', 250e3, ...
        'tone_rf_frequency_hz', 540.45e6, ...
        'tone_amplitude', 0.14, ...
        'capture_duration_s', 0.065536, ...
        'plot_figures', false, ...
        'verbose', false), ...
    'capture_info', struct( ...
        'capture_session_id', 'demo_capture', ...
        'capture_file_path', '', ...
        'local_capture_files', strings(0, 1), ...
        'recording_utc', posixtime(datetime('now', 'TimeZone', 'UTC')), ...
        'header_center_frequency_hz', 540e6, ...
        'header_lo_offset_hz', 200e3, ...
        'header_tune_frequency_hz', 540.2e6, ...
        'header_sample_rate_hz', 1e6, ...
        'samples_per_channel', 65536, ...
        'samples_scored', 65536, ...
        'slice_duration_s', 0.065536, ...
        'reader_metadata', struct()), ...
    'channel_map', struct( ...
        'reference_label', 'REF', ...
        'reference_channel_index', 2, ...
        'reference_rx_label', 'CH2/RX2', ...
        'surveillance_label', 'SURV', ...
        'surveillance_channel_index', 1, ...
        'surveillance_rx_label', 'CH1/RX1'), ...
    'reference_metrics', ref_metrics, ...
    'surveillance_metrics', surv_metrics, ...
    'joint_metrics', joint_metrics, ...
    'baseline_comparison', struct( ...
        'baseline_id', 'demo_baseline', ...
        'settings_match', true, ...
        'settings_mismatch_fields', {cell(0, 1)}, ...
        'reference_level_delta_db', ref_metrics.level_delta_vs_baseline_db, ...
        'surveillance_level_delta_db', surv_metrics.level_delta_vs_baseline_db, ...
        'comparison_applied', true), ...
    'precheck_summary', struct(), ...
    'artifact_paths', struct());
end

function status = localResolveStatus(ref_metrics, surv_metrics, joint_metrics)
statuses = {ref_metrics.status, surv_metrics.status, joint_metrics.status};
if any(strcmp(statuses, 'FAIL'))
    status = 'FAIL';
elseif any(strcmp(statuses, 'WARN'))
    status = 'WARN';
else
    status = 'PASS';
end
end

function localSafeRemoveFolder(folder_path)
folder_path = char(string(folder_path));
if isfolder(folder_path)
    rmdir(folder_path, 's');
end
end
