function result = runPlutoToneStage6Smoke(varargin)
%RUNPLUTOTONESTAGE6SMOKE Combined Pluto-to-USRP smoke test without baseline.
%
% Plain-language goal:
%   This runner executes the documented Stage 6 Pluto smoke test from the
%   current Phase 1 implementation. It starts the Pluto tone, captures one
%   short dual-channel N320 file, reads the capture back through the
%   project's proven loadIQData path, and scores the received tone on both
%   channels.
%
% Syntax:
%   result = runPlutoToneStage6Smoke
%   result = runPlutoToneStage6Smoke('CaptureDuration_s', 1, 'Verbose', true)
%
% Notes:
%   - This runner intentionally uses the current Phase 1 branch defaults:
%     540 MHz center, 6.144 MSps, 200 kHz LO offset, and 250 kHz tone.
%   - It is a smoke test only. It does not require a commissioned baseline.

p = inputParser;
p.FunctionName = mfilename;
addParameter(p, 'SessionID', "pluto_usrp_smoke", @(x) ischar(x) || isstring(x));
addParameter(p, 'CaptureRoot', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'RadioName', "My USRP N320", @(x) ischar(x) || isstring(x));
addParameter(p, 'CaptureFileBase', "pluto_usrp_smoke", @(x) ischar(x) || isstring(x));
addParameter(p, 'CenterFrequency_Hz', 540e6, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'SampleRate_Hz', 6.144e6, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'LOOffset_Hz', 200e3, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'Gain', [30 50], @(x) isnumeric(x) && (isscalar(x) || numel(x) == 2));
addParameter(p, 'ToneOffset_Hz', 250e3, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'ToneAmplitude', 0.25, @(x) isnumeric(x) && isscalar(x) && x > 0 && x <= 1);
addParameter(p, 'CaptureDuration_s', 1, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'Verbose', true, @(x) islogical(x) && isscalar(x));
parse(p, varargin{:});
opts = p.Results;

test_root = fileparts(mfilename('fullpath'));
project_root = fileparts(test_root);
analysis_root = fullfile(project_root, 'BistaticDataAnalysis');

capture_root = string(opts.CaptureRoot);
if strlength(capture_root) == 0
    capture_root = fullfile(project_root, 'captures', 'plutoSmoke');
end

original_folder = pwd;
original_path = path;
cleanup_folder = onCleanup(@() cd(original_folder));
cleanup_path = onCleanup(@() path(original_path));

cd(test_root);
addpath(analysis_root, '-begin');

if opts.Verbose
    fprintf('[runPlutoToneStage6Smoke] Project root .. %s\n', project_root);
    fprintf('[runPlutoToneStage6Smoke] Test root ..... %s\n', test_root);
    fprintf('[runPlutoToneStage6Smoke] loadIQData ..... %s\n', which('loadIQData'));
end

tx_context = struct();

try
    waveform = helperPlutoToneBuildWaveform( ...
        opts.SampleRate_Hz, ...
        opts.ToneOffset_Hz, ...
        opts.ToneAmplitude, ...
        'Verbose', opts.Verbose);

    tx_context = helperPlutoToneStartTx( ...
        'CenterFrequencyHz', double(opts.CenterFrequency_Hz + opts.LOOffset_Hz), ...
        'SampleRateHz', double(opts.SampleRate_Hz), ...
        'Waveform', waveform, ...
        'Verbose', opts.Verbose);

    capture_info = helperPlutoToneCaptureN320( ...
        'SessionID', string(opts.SessionID), ...
        'CaptureRoot', char(capture_root), ...
        'CaptureFileBase', string(opts.CaptureFileBase), ...
        'RadioName', string(opts.RadioName), ...
        'CenterFrequencyHz', double(opts.CenterFrequency_Hz), ...
        'SampleRateHz', double(opts.SampleRate_Hz), ...
        'LOOffsetHz', double(opts.LOOffset_Hz), ...
        'Gain', double(opts.Gain(:).'), ...
        'CaptureDurationSeconds', double(opts.CaptureDuration_s), ...
        'Verbose', opts.Verbose);

    [reference_signal, surveillance_signal, capture_info_out] = helperPlutoToneReadCapture( ...
        capture_info, ...
        'ExpectedSampleRateHz', double(opts.SampleRate_Hz), ...
        'CaptureDurationSeconds', double(opts.CaptureDuration_s), ...
        'Verbose', opts.Verbose);

    localReleaseTransmitter(tx_context);
    tx_context = struct();

    reference_metrics = helperPlutoToneScoreChannel( ...
        reference_signal, ...
        double(opts.SampleRate_Hz), ...
        'ChannelLabel', 'REF', ...
        'ExpectedFrequencyHz', double(opts.ToneOffset_Hz), ...
        'Verbose', opts.Verbose);

    surveillance_metrics = helperPlutoToneScoreChannel( ...
        surveillance_signal, ...
        double(opts.SampleRate_Hz), ...
        'ChannelLabel', 'SURV', ...
        'ExpectedFrequencyHz', double(opts.ToneOffset_Hz), ...
        'Verbose', opts.Verbose);

    joint_metrics = helperPlutoToneScoreJointMetrics( ...
        reference_signal, ...
        surveillance_signal, ...
        double(opts.SampleRate_Hz), ...
        'ReferenceMetrics', reference_metrics, ...
        'SurveillanceMetrics', surveillance_metrics, ...
        'Verbose', opts.Verbose);

    result = struct( ...
        'settings', struct( ...
            'session_id', char(string(opts.SessionID)), ...
            'capture_root', char(capture_root), ...
            'radio_name', char(string(opts.RadioName)), ...
            'capture_file_base', char(string(opts.CaptureFileBase)), ...
            'center_frequency_hz', double(opts.CenterFrequency_Hz), ...
            'sample_rate_hz', double(opts.SampleRate_Hz), ...
            'lo_offset_hz', double(opts.LOOffset_Hz), ...
            'capture_tune_frequency_hz', double(opts.CenterFrequency_Hz + opts.LOOffset_Hz), ...
            'gain', double(opts.Gain(:).'), ...
            'tone_offset_hz', double(opts.ToneOffset_Hz), ...
            'tone_rf_frequency_hz', double(opts.CenterFrequency_Hz + opts.LOOffset_Hz + opts.ToneOffset_Hz), ...
            'tone_amplitude', double(opts.ToneAmplitude), ...
            'capture_duration_s', double(opts.CaptureDuration_s)), ...
        'capture_info', capture_info_out, ...
        'reference_metrics', reference_metrics, ...
        'surveillance_metrics', surveillance_metrics, ...
        'joint_metrics', joint_metrics);

    if opts.Verbose
        fprintf('[runPlutoToneStage6Smoke] REF tone found ... %d\n', reference_metrics.tone_found);
        fprintf('[runPlutoToneStage6Smoke] SURV tone found .. %d\n', surveillance_metrics.tone_found);
        fprintf('[runPlutoToneStage6Smoke] Joint freq delta  %.3f Hz\n', joint_metrics.channel_frequency_delta_hz);
        disp(capture_info_out);
        disp(reference_metrics);
        disp(surveillance_metrics);
        disp(joint_metrics);
    end
catch me
    localReleaseTransmitter(tx_context);
    rethrow(me)
end
end

function localReleaseTransmitter(tx_context)
if isstruct(tx_context) && isfield(tx_context, 'transmitter') && ~isempty(tx_context.transmitter)
    try
        release(tx_context.transmitter);
    catch
    end
end
end
