function result = runPlutoTonePrecheck(varargin)
%RUNPLUTOTONEPRECHECK Run the standalone Pluto-driven tone precheck.
%
% Plain-language goal:
%   This wrapper is the one-call hardware-readiness gate that will sit in
%   front of the broader acquisition pipeline once the standalone behavior
%   is proven. It loads the commissioned baseline, starts a deterministic
%   Pluto tone, reuses the existing N320 capture path for one short
%   dual-channel recording, scores both channels against the baseline, and
%   writes a self-contained review folder.
%
% Syntax
%   result = runPlutoTonePrecheck('BaselinePath', baselinePath)
%
% Name-value options
%   'BaselinePath'        Required baseline.mat, baseline.json, or baseline folder
%   'CaptureRoot'         Root folder for standalone capture files
%   'RadioName'           N320 radio name
%   'CaptureFileBase'     Capture stem passed into runLocalHDTVCapture
%   'CenterFrequency_Hz'  N320 capture center frequency
%   'SampleRate_Hz'       N320 and Pluto sample rate
%   'LOOffset_Hz'         N320 LO offset
%   'Gain'                N320 gain scalar or [surv ref]
%   'ToneOffset_Hz'       Expected tone offset in captured complex baseband
%   'ToneAmplitude'       Digital Pluto tone amplitude
%   'CaptureDuration_s'   N320 capture duration
%   'PlotFigures'         Show figures while writing artifacts. Default: true
%   'Verbose'             Print status and summary text. Default: true
%
% See also: helperPlutoToneLoadBaseline, helperPlutoToneBuildWaveform,
%           helperPlutoToneStartTx, helperPlutoToneCaptureN320,
%           helperPlutoToneReadCapture, helperPlutoToneScoreChannel,
%           helperPlutoToneScoreJointMetrics, helperPlutoToneWriteArtifacts.

p = inputParser;
p.FunctionName = mfilename;
addParameter(p, 'BaselinePath', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'CaptureRoot', fullfile(pwd, 'TestSetupTesting', 'plutoPrecheckCaptures'), @(x) ischar(x) || isstring(x));
addParameter(p, 'RadioName', "My USRP N320", @(x) ischar(x) || isstring(x));
addParameter(p, 'CaptureFileBase', "pluto_tone_precheck", @(x) ischar(x) || isstring(x));
addParameter(p, 'CenterFrequency_Hz', 540e6, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'SampleRate_Hz', 6.144e6, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'LOOffset_Hz', 200e3, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'Gain', [30 50], @(x) isnumeric(x) && (isscalar(x) || numel(x) == 2));
addParameter(p, 'ToneOffset_Hz', 250e3, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'ToneAmplitude', 0.5, @(x) isnumeric(x) && isscalar(x) && x > 0 && x <= 1);
addParameter(p, 'CaptureDuration_s', 0.25, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'PlotFigures', true, @(x) islogical(x) && isscalar(x));
addParameter(p, 'Verbose', true, @(x) islogical(x) && isscalar(x));
parse(p, varargin{:});
opts = p.Results;

baseline_path = string(opts.BaselinePath);
if strlength(baseline_path) == 0
    error('runPlutoTonePrecheck:missingBaselinePath', ...
        'BaselinePath is required.');
end

settings = localBuildSettingsStruct(opts);
run_id = localBuildRunID();
run_folder = fullfile(pwd, 'TestSetupTesting', 'plutoPrecheckRuns', run_id);
figure_visibility = localFigureVisibility(opts.PlotFigures);

result = localBuildInitialResult(run_id, settings);
capture_runtime_info = struct();

try
    baseline = helperPlutoToneLoadBaseline(baseline_path);
    result.baseline_comparison = helperPlutoToneCompareBaseline(baseline, result.settings);
catch me_baseline
    result = localRegisterFailure(result, localBaselineFailCode(me_baseline));
    localPrintFailure(opts.Verbose, result.fail_codes{end}, me_baseline.message);
    result = localWriteArtifacts(result, run_folder, false, figure_visibility, opts.Verbose);
    return
end

if ~result.baseline_comparison.settings_match
    mismatch_text = strjoin(result.baseline_comparison.settings_mismatch_fields, ', ');
    result = localRegisterFailure(result, 'BASELINE_SETTINGS_MISMATCH');
    localPrintFailure(opts.Verbose, 'BASELINE_SETTINGS_MISMATCH', ...
        sprintf('Baseline %s does not match the requested settings: %s', ...
        result.baseline_comparison.baseline_id, mismatch_text));
    result = localWriteArtifacts(result, run_folder, false, figure_visibility, opts.Verbose);
    return
end

try
    waveform = helperPlutoToneBuildWaveform( ...
        result.settings.sample_rate_hz, ...
        result.settings.tone_offset_hz, ...
        result.settings.tone_amplitude, ...
        'Verbose', opts.Verbose);

    tx_context = helperPlutoToneStartTx( ...
        'CenterFrequencyHz', result.settings.capture_tune_frequency_hz, ...
        'SampleRateHz', result.settings.sample_rate_hz, ...
        'Waveform', waveform, ...
        'Verbose', opts.Verbose);
    cleanup_tx = onCleanup(@() localReleaseTransmitter(tx_context));
catch me_pluto
    result = localRegisterFailure(result, localPlutoFailCode(me_pluto));
    localPrintFailure(opts.Verbose, result.fail_codes{end}, me_pluto.message);
    result = localWriteArtifacts(result, run_folder, false, figure_visibility, opts.Verbose);
    return
end

try
    capture_runtime_info = helperPlutoToneCaptureN320( ...
        'SessionID', run_id, ...
        'CaptureRoot', result.settings.capture_root, ...
        'CaptureFileBase', result.settings.capture_file_base, ...
        'RadioName', result.settings.radio_name, ...
        'CenterFrequencyHz', result.settings.center_frequency_hz, ...
        'SampleRateHz', result.settings.sample_rate_hz, ...
        'LOOffsetHz', result.settings.lo_offset_hz, ...
        'Gain', result.settings.gain, ...
        'CaptureDurationSeconds', result.settings.capture_duration_s, ...
        'Verbose', opts.Verbose);
    result.capture_info = localCaptureInfoFromRuntime(capture_runtime_info);
catch me_capture
    result.capture_info = localCaptureInfoFromRuntime(capture_runtime_info);
    result = localRegisterFailure(result, 'N320_CAPTURE_FAILED');
    localPrintFailure(opts.Verbose, 'N320_CAPTURE_FAILED', me_capture.message);
    result = localWriteArtifacts(result, run_folder, false, figure_visibility, opts.Verbose);
    return
end

localReleaseTransmitter(tx_context);
clear cleanup_tx

try
    [reference_signal, surveillance_signal, capture_info_out] = helperPlutoToneReadCapture( ...
        capture_runtime_info, ...
        'ExpectedSampleRateHz', result.settings.sample_rate_hz, ...
        'CaptureDurationSeconds', result.settings.capture_duration_s, ...
        'Verbose', opts.Verbose);
    result.capture_info = capture_info_out;
catch me_read
    result.capture_info = localCaptureInfoFromRuntime(capture_runtime_info);
    result = localRegisterFailure(result, localCaptureReadFailCode(me_read));
    localPrintFailure(opts.Verbose, result.fail_codes{end}, me_read.message);
    result = localWriteArtifacts(result, run_folder, false, figure_visibility, opts.Verbose);
    return
end

reference_metrics = helperPlutoToneScoreChannel( ...
    reference_signal, ...
    result.settings.sample_rate_hz, ...
    'ChannelLabel', 'REF', ...
    'ChannelIndex', 2, ...
    'RXLabel', 'CH2/RX2', ...
    'ExpectedFrequencyHz', result.settings.tone_offset_hz, ...
    'BaselineMetrics', baseline.statistics.reference, ...
    'Thresholds', baseline.thresholds.reference, ...
    'Verbose', false);

surveillance_metrics = helperPlutoToneScoreChannel( ...
    surveillance_signal, ...
    result.settings.sample_rate_hz, ...
    'ChannelLabel', 'SURV', ...
    'ChannelIndex', 1, ...
    'RXLabel', 'CH1/RX1', ...
    'ExpectedFrequencyHz', result.settings.tone_offset_hz, ...
    'BaselineMetrics', baseline.statistics.surveillance, ...
    'Thresholds', baseline.thresholds.surveillance, ...
    'Verbose', false);

joint_metrics = helperPlutoToneScoreJointMetrics( ...
    reference_signal, ...
    surveillance_signal, ...
    result.settings.sample_rate_hz, ...
    'ReferenceMetrics', reference_metrics, ...
    'SurveillanceMetrics', surveillance_metrics, ...
    'Thresholds', baseline.thresholds.joint, ...
    'Verbose', false);

result.reference_metrics = reference_metrics;
result.surveillance_metrics = surveillance_metrics;
result.joint_metrics = joint_metrics;
result.baseline_comparison = helperPlutoToneCompareBaseline( ...
    baseline, ...
    result.settings, ...
    'ReferenceMetrics', reference_metrics, ...
    'SurveillanceMetrics', surveillance_metrics);
result.fail_codes = localUniqueCodes([ ...
    reference_metrics.fail_codes(:); ...
    surveillance_metrics.fail_codes(:); ...
    joint_metrics.fail_codes(:)]);
result.warn_codes = localUniqueCodes([ ...
    reference_metrics.warn_codes(:); ...
    surveillance_metrics.warn_codes(:); ...
    joint_metrics.warn_codes(:)]);
result.status = localResolveStatus(result.fail_codes, result.warn_codes);
result.overall_pass = strcmp(result.status, 'PASS');

result = localWriteArtifacts(result, run_folder, true, figure_visibility, opts.Verbose);
if opts.Verbose
    fprintf('%s\n', char(string(result.precheck_summary.text_block)));
end
end

function settings = localBuildSettingsStruct(opts)
settings = struct( ...
    'baseline_path', char(string(opts.BaselinePath)), ...
    'capture_root', char(string(opts.CaptureRoot)), ...
    'radio_name', char(string(opts.RadioName)), ...
    'capture_file_base', char(string(opts.CaptureFileBase)), ...
    'center_frequency_hz', double(opts.CenterFrequency_Hz), ...
    'sample_rate_hz', double(opts.SampleRate_Hz), ...
    'lo_offset_hz', double(opts.LOOffset_Hz), ...
    'capture_tune_frequency_hz', double(opts.CenterFrequency_Hz + opts.LOOffset_Hz), ...
    'gain', double(opts.Gain(:).'), ...
    'tone_offset_hz', double(opts.ToneOffset_Hz), ...
    'tone_rf_frequency_hz', double(opts.CenterFrequency_Hz + opts.LOOffset_Hz + opts.ToneOffset_Hz), ...
    'tone_amplitude', double(opts.ToneAmplitude), ...
    'capture_duration_s', double(opts.CaptureDuration_s), ...
    'plot_figures', logical(opts.PlotFigures), ...
    'verbose', logical(opts.Verbose));
end

function run_id = localBuildRunID()
run_id = char("pluto_tone_precheck_" + string(datetime( ...
    'now', 'TimeZone', 'UTC', 'Format', 'yyyyMMdd''T''HHmmssSSS')));
end

function result = localBuildInitialResult(run_id, settings)
result = struct( ...
    'schema_version', 1, ...
    'run_id', run_id, ...
    'created_utc', char(string(datetime('now', 'TimeZone', 'UTC', ...
        'Format', 'yyyy-MM-dd''T''HH:mm:ss''Z'''))), ...
    'overall_pass', false, ...
    'status', 'FAIL', ...
    'fail_codes', {cell(0, 1)}, ...
    'warn_codes', {cell(0, 1)}, ...
    'settings', settings, ...
    'capture_info', localEmptyCaptureInfo(), ...
    'channel_map', localChannelMap(), ...
    'reference_metrics', localEmptyChannelMetrics('REF', 2, 'CH2/RX2', settings.tone_offset_hz), ...
    'surveillance_metrics', localEmptyChannelMetrics('SURV', 1, 'CH1/RX1', settings.tone_offset_hz), ...
    'joint_metrics', localEmptyJointMetrics(), ...
    'baseline_comparison', localEmptyBaselineComparison(), ...
    'precheck_summary', struct(), ...
    'artifact_paths', struct());
end

function capture_info = localEmptyCaptureInfo()
capture_info = struct( ...
    'capture_session_id', '', ...
    'capture_file_path', '', ...
    'local_capture_files', strings(0, 1), ...
    'recording_utc', NaN, ...
    'header_center_frequency_hz', NaN, ...
    'header_lo_offset_hz', NaN, ...
    'header_tune_frequency_hz', NaN, ...
    'header_sample_rate_hz', NaN, ...
    'samples_per_channel', NaN, ...
    'samples_scored', NaN, ...
    'slice_duration_s', NaN, ...
    'reader_metadata', struct());
end

function channel_map = localChannelMap()
channel_map = struct( ...
    'reference_label', 'REF', ...
    'reference_channel_index', 2, ...
    'reference_rx_label', 'CH2/RX2', ...
    'surveillance_label', 'SURV', ...
    'surveillance_channel_index', 1, ...
    'surveillance_rx_label', 'CH1/RX1');
end

function metrics = localEmptyChannelMetrics(channel_label, channel_index, rx_label, expected_frequency_hz)
metrics = struct( ...
    'channel_label', channel_label, ...
    'channel_index', channel_index, ...
    'rx_label', rx_label, ...
    'tone_found', false, ...
    'expected_frequency_hz', double(expected_frequency_hz), ...
    'measured_frequency_hz', NaN, ...
    'frequency_error_hz', NaN, ...
    'level_dbfs', NaN, ...
    'tone_peak_dbfs', NaN, ...
    'local_floor_dbfs', NaN, ...
    'detect_margin_db', NaN, ...
    'level_delta_vs_baseline_db', NaN, ...
    'status', 'FAIL', ...
    'fail_codes', {cell(0, 1)}, ...
    'warn_codes', {cell(0, 1)});
end

function joint_metrics = localEmptyJointMetrics()
joint_metrics = struct( ...
    'channel_frequency_delta_hz', NaN, ...
    'xcorr_lag_samples', NaN, ...
    'xcorr_lag_seconds', NaN, ...
    'xcorr_peak_db', NaN, ...
    'xcorr_note', 'Not run.', ...
    'status', 'FAIL', ...
    'fail_codes', {cell(0, 1)}, ...
    'warn_codes', {cell(0, 1)});
end

function comparison = localEmptyBaselineComparison()
comparison = struct( ...
    'baseline_id', '(none)', ...
    'settings_match', false, ...
    'settings_mismatch_fields', {cell(0, 1)}, ...
    'reference_level_delta_db', NaN, ...
    'surveillance_level_delta_db', NaN, ...
    'comparison_applied', false);
end

function result = localRegisterFailure(result, fail_code)
result.fail_codes = localUniqueCodes([result.fail_codes(:); {fail_code}]);
result.warn_codes = localUniqueCodes(result.warn_codes);
result.status = 'FAIL';
result.overall_pass = false;
end

function result = localWriteArtifacts(result, run_folder, copy_capture_file, figure_visibility, verbose)
[~, result] = helperPlutoToneWriteArtifacts( ...
    result, ...
    'RunFolder', run_folder, ...
    'CopyCaptureFile', copy_capture_file, ...
    'FigureVisibility', figure_visibility, ...
    'Verbose', verbose);
end

function capture_info = localCaptureInfoFromRuntime(capture_runtime_info)
capture_info = localEmptyCaptureInfo();
if isempty(fieldnames(capture_runtime_info))
    return
end

capture_info.capture_session_id = char(string(localFieldOrDefault(capture_runtime_info, 'session_id', "")));
capture_info.capture_file_path = char(string(localFirstCaptureFile(capture_runtime_info)));
capture_info.local_capture_files = string(localFieldOrDefault(capture_runtime_info, 'local_capture_files', strings(0, 1)));
capture_info.recording_utc = localFiniteOrNaN(localFieldOrDefault(capture_runtime_info, 'recording_utc', NaN));
capture_info.header_center_frequency_hz = localFiniteOrNaN(localFieldOrDefault(capture_runtime_info, 'header_center_frequency_hz', NaN));
capture_info.header_lo_offset_hz = localFiniteOrNaN(localFieldOrDefault(capture_runtime_info, 'header_lo_offset_hz', NaN));
capture_info.header_tune_frequency_hz = localFiniteOrNaN(localFieldOrDefault(capture_runtime_info, 'header_tune_frequency_hz', NaN));
capture_info.header_sample_rate_hz = localFiniteOrNaN(localFieldOrDefault(capture_runtime_info, 'header_sample_rate_hz', NaN));
capture_info.reader_metadata = struct();
end

function value = localFirstCaptureFile(capture_runtime_info)
value = "";
if isfield(capture_runtime_info, 'local_capture_files') && ~isempty(capture_runtime_info.local_capture_files)
    value = string(capture_runtime_info.local_capture_files(1));
end
end

function value = localFieldOrDefault(source_struct, field_name, default_value)
value = default_value;
if isstruct(source_struct) && isfield(source_struct, field_name)
    value = source_struct.(field_name);
end
end

function value = localFiniteOrNaN(value_in)
value = NaN;
numeric_value = double(value_in);
if isscalar(numeric_value) && isfinite(numeric_value)
    value = numeric_value;
end
end

function fail_code = localBaselineFailCode(me)
if strcmp(me.identifier, 'helperPlutoToneLoadBaseline:unsupportedSchema')
    fail_code = 'BASELINE_SCHEMA_UNSUPPORTED';
else
    fail_code = 'BASELINE_LOAD_FAILED';
end
end

function fail_code = localPlutoFailCode(me)
switch me.identifier
    case {'helperPlutoToneStartTx:missingDependency', 'helperPlutoToneStartTx:connectFailed'}
        fail_code = 'PLUTO_CONNECT_FAILED';
    otherwise
        fail_code = 'PLUTO_TX_START_FAILED';
end
end

function fail_code = localCaptureReadFailCode(me)
if strcmp(me.identifier, 'helperPlutoToneReadCapture:captureFileMissing')
    fail_code = 'CAPTURE_FILE_MISSING';
else
    fail_code = 'CAPTURE_READ_FAILED';
end
end

function figure_visibility = localFigureVisibility(plot_figures)
figure_visibility = 'off';
if plot_figures
    figure_visibility = 'on';
end
end

function status = localResolveStatus(fail_codes, warn_codes)
if ~isempty(fail_codes)
    status = 'FAIL';
elseif ~isempty(warn_codes)
    status = 'WARN';
else
    status = 'PASS';
end
end

function codes = localUniqueCodes(codes_in)
codes = cell(0, 1);
if isempty(codes_in)
    return
end

raw_codes = cellfun(@(x) char(string(x)), codes_in(:), 'UniformOutput', false);
[~, keep_idx] = unique(raw_codes, 'stable');
codes = raw_codes(sort(keep_idx));
codes = codes(:);
end

function localPrintFailure(verbose, fail_code, message_text)
if verbose
    fprintf('[runPlutoTonePrecheck] %s: %s\n', fail_code, message_text);
end
end

function localReleaseTransmitter(tx_context)
if ~isstruct(tx_context) || ~isfield(tx_context, 'transmitter')
    return
end

try
    release(tx_context.transmitter);
catch
end
end
