function featureData = helperBuildStage4CFeatures( ...
        previousState, previousCovarianceDiag, dtSeconds, constvelPredictedState)
%HELPERBUILDSTAGE4CFEATURES Build the frozen 20-feature MLP input contract.
% The network remains memoryless: each row contains one previous state,
% the diagonal of its covariance, and the elapsed time. Physics-derived
% terms expose the native constant-velocity prediction without adding
% trajectory history, aircraft identity, or absolute horizontal position.

previousState = double(previousState);
previousCovarianceDiag = double(previousCovarianceDiag);
dtSeconds = double(dtSeconds(:));
constvelPredictedState = double(constvelPredictedState);

localValidateInputs( ...
    previousState, ...
    previousCovarianceDiag, ...
    dtSeconds, ...
    constvelPredictedState);

vx = previousState(:, 2);
vy = previousState(:, 4);
z = previousState(:, 5);
vz = previousState(:, 6);
constvelDelta = constvelPredictedState - previousState;

featureNames = [ ...
    "vx"; ...
    "vy"; ...
    "z"; ...
    "vz"; ...
    "dtSeconds"; ...
    "previousCovarianceDiag_x"; ...
    "previousCovarianceDiag_vx"; ...
    "previousCovarianceDiag_y"; ...
    "previousCovarianceDiag_vy"; ...
    "previousCovarianceDiag_z"; ...
    "previousCovarianceDiag_vz"; ...
    "vxTimesDt"; ...
    "vyTimesDt"; ...
    "vzTimesDt"; ...
    "constvelDelta_x"; ...
    "constvelDelta_vx"; ...
    "constvelDelta_y"; ...
    "constvelDelta_vy"; ...
    "constvelDelta_z"; ...
    "constvelDelta_vz"];

features = [ ...
    vx, ...
    vy, ...
    z, ...
    vz, ...
    dtSeconds, ...
    previousCovarianceDiag, ...
    vx .* dtSeconds, ...
    vy .* dtSeconds, ...
    vz .* dtSeconds, ...
    constvelDelta];

if any(~isfinite(features), "all")
    error("Stage4C:NonfiniteFeatures", ...
        "The Stage 4C feature matrix must contain only finite values.");
end

featureData = struct();
featureData.features = features;
featureData.featureNames = featureNames;
featureData.featureCount = numel(featureNames);
featureData.stateOrder = ["x", "vx", "y", "vy", "z", "vz"];
featureData.excludedIdentityFeatures = [ ...
    "icao24", ...
    "hex", ...
    "callsign", ...
    "sessionID"];
featureData.excludedHistoryFeatures = "trajectory_history";
featureData.absoluteHorizontalPositionExcluded = true;

end

function localValidateInputs( ...
        previousState, previousCovarianceDiag, dtSeconds, constvelPredictedState)
%LOCALVALIDATEINPUTS Enforce the one-row-per-state-pair feature contract.

sampleCount = size(previousState, 1);

validateattributes(previousState, ...
    {'numeric'}, {'2d', 'real', 'finite'}, mfilename, "previousState");
validateattributes(previousCovarianceDiag, ...
    {'numeric'}, {'2d', 'real', 'finite'}, mfilename, "previousCovarianceDiag");
validateattributes(dtSeconds, ...
    {'numeric'}, {'column', 'real', 'finite', 'positive'}, mfilename, "dtSeconds");
validateattributes(constvelPredictedState, ...
    {'numeric'}, {'2d', 'real', 'finite'}, mfilename, "constvelPredictedState");

if size(previousState, 2) ~= 6 || ...
        size(previousCovarianceDiag, 2) ~= 6 || ...
        size(constvelPredictedState, 2) ~= 6
    error("Stage4C:BadFeatureStateWidth", ...
        "State and covariance inputs must have six columns.");
end

if size(previousCovarianceDiag, 1) ~= sampleCount || ...
        size(constvelPredictedState, 1) ~= sampleCount || ...
        numel(dtSeconds) ~= sampleCount
    error("Stage4C:FeatureInputSizeMismatch", ...
        "All feature inputs must contain one row per state pair.");
end

end
