function metrics = helperScoreStage3APredictions(nextState, predictedNextState, metadata, maneuverPairTable, methodName)
%HELPERSCORESTAGE3APREDICTIONS Score one prediction method by Stage 3A groups.

nextState = double(nextState);
predictedNextState = double(predictedNextState);
methodName = string(methodName);

localValidateInputs(nextState, predictedNextState, metadata, maneuverPairTable);

metrics = struct();
metrics.method = methodName;
metrics.aggregate = localBuildMetricTable( ...
    true(size(nextState, 1), 1), ...
    "all", ...
    "all", ...
    nextState, ...
    predictedNextState, ...
    methodName);
metrics.bySplit = localScoreByGroup( ...
    metadata.split, ...
    "split", ...
    nextState, ...
    predictedNextState, ...
    methodName);
metrics.byManeuverClass = localScoreByGroup( ...
    maneuverPairTable.maneuverClass, ...
    "maneuverClass", ...
    nextState, ...
    predictedNextState, ...
    methodName);
metrics.byVerticalStatus = localScoreByGroup( ...
    maneuverPairTable.verticalStatus, ...
    "verticalStatus", ...
    nextState, ...
    predictedNextState, ...
    methodName);
metrics.byDtRegime = localScoreByGroup( ...
    maneuverPairTable.dtRegime, ...
    "dtRegime", ...
    nextState, ...
    predictedNextState, ...
    methodName);
metrics.positionErrorMeters = localErrorNorm(nextState, predictedNextState, [1, 3, 5]);
metrics.velocityErrorMetersPerSecond = localErrorNorm(nextState, predictedNextState, [2, 4, 6]);

end

function localValidateInputs(nextState, predictedNextState, metadata, maneuverPairTable)
%LOCALVALIDATEINPUTS Verify prediction scoring dimensions.

sampleCount = size(nextState, 1);

if size(nextState, 2) ~= 6 || size(predictedNextState, 2) ~= 6
    error("Stage3A:BadPredictionWidth", ...
        "nextState and predictedNextState must have six columns.");
end

if size(predictedNextState, 1) ~= sampleCount
    error("Stage3A:PredictionSizeMismatch", ...
        "predictedNextState must contain one row per nextState row.");
end

if height(metadata) ~= sampleCount || height(maneuverPairTable) ~= sampleCount
    error("Stage3A:MetricMetadataSizeMismatch", ...
        "metadata and maneuverPairTable must contain one row per state pair.");
end

end

function outputTable = localScoreByGroup(groupValues, groupVariableName, nextState, predictedNextState, methodName)
%LOCALSCOREBYGROUP Build metrics for each observed group value.

groupValues = string(groupValues(:));
groupNames = unique(groupValues, "stable");
outputTable = table();

for groupIdx = 1:numel(groupNames)
    groupName = groupNames(groupIdx);
    groupMask = groupValues == groupName;
    rowTable = localBuildMetricTable( ...
        groupMask, ...
        groupVariableName, ...
        groupName, ...
        nextState, ...
        predictedNextState, ...
        methodName);
    outputTable = [outputTable; rowTable]; %#ok<AGROW>
end

end

function metricTable = localBuildMetricTable(mask, groupVariableName, groupName, nextState, predictedNextState, methodName)
%LOCALBUILDMETRICTABLE Return one row of physical-unit error metrics.

positionErrorMeters = localErrorNorm(nextState(mask, :), predictedNextState(mask, :), [1, 3, 5]);
velocityErrorMetersPerSecond = localErrorNorm(nextState(mask, :), predictedNextState(mask, :), [2, 4, 6]);
sampleCount = numel(positionErrorMeters);

metricTable = table( ...
    methodName, ...
    string(groupVariableName), ...
    string(groupName), ...
    sampleCount, ...
    sqrt(mean(positionErrorMeters .^ 2, "omitnan")), ...
    sqrt(mean(velocityErrorMetersPerSecond .^ 2, "omitnan")), ...
    median(positionErrorMeters, "omitnan"), ...
    median(velocityErrorMetersPerSecond, "omitnan"), ...
    prctile(positionErrorMeters, 95), ...
    prctile(velocityErrorMetersPerSecond, 95), ...
    'VariableNames', [ ...
        "method", ...
        "groupVariable", ...
        "groupName", ...
        "sampleCount", ...
        "positionRMSEMeters", ...
        "velocityRMSEMetersPerSecond", ...
        "positionMedianErrorMeters", ...
        "velocityMedianErrorMetersPerSecond", ...
        "positionP95ErrorMeters", ...
        "velocityP95ErrorMetersPerSecond"]);

end

function errorNorm = localErrorNorm(nextState, predictedNextState, columns)
%LOCALERRORNORM Compute row-wise Euclidean error in selected state columns.

componentError = predictedNextState(:, columns) - nextState(:, columns);
errorNorm = vecnorm(componentError, 2, 2);

end
