function evaluation = helperEvaluateStage4DPredictors( ...
        pairSet, warmModel, varargin)
%HELPEREVALUATESTAGE4DPREDICTORS Compare the frozen warm model and native models.
% Warm and constvel share the current observation and dt. Constacc and
% constturn are reported separately because they also use one predecessor.

parser = inputParser;
parser.FunctionName = mfilename;
addRequired(parser, "pairSet");
addRequired(parser, "warmModel");
addParameter(parser, "PredictionMiniBatchSize", 8192);
addParameter(parser, "ConfidenceLevel", 0.95);
addParameter(parser, "RetainPredictions", false);
parse(parser, pairSet, warmModel, varargin{:});

miniBatchSize = double(parser.Results.PredictionMiniBatchSize);
confidenceLevel = double(parser.Results.ConfidenceLevel);
retainPredictions = localLogicalScalar( ...
    parser.Results.RetainPredictions, ...
    "RetainPredictions");
localValidateInputs(pairSet, warmModel, miniBatchSize, confidenceLevel);

rowCount = size(pairSet.previousState, 1);
constvelTimer = tic;
constvelPrediction = localPredictConstvel( ...
    pairSet.previousState, ...
    pairSet.dtSeconds);
constvelSeconds = toc(constvelTimer);

warmTimer = tic;
warmPrediction = localPredictWarm( ...
    pairSet.previousState, ...
    pairSet.previousCovarianceDiag, ...
    pairSet.dtSeconds, ...
    constvelPrediction, ...
    warmModel, ...
    miniBatchSize);
warmSeconds = toc(warmTimer);

[causalPrediction, causalRuntime] = localPredictCausalNative(pairSet);
models = localBuildModels( ...
    warmPrediction, ...
    constvelPrediction, ...
    causalPrediction);
positionErrors = localStateErrors( ...
    models, ...
    pairSet.targetState, ...
    [1, 3, 5]);
velocityErrors = localStateErrors( ...
    models, ...
    pairSet.targetState, ...
    [2, 4, 6]);

metricTable = localScoreProfiles( ...
    pairSet, ...
    models, ...
    positionErrors, ...
    velocityErrors, ...
    causalPrediction.eligibleMask);
canonicalMetricTable = localScoreCanonicalCases( ...
    pairSet, ...
    models, ...
    positionErrors, ...
    velocityErrors, ...
    causalPrediction.eligibleMask);
[eventWinRateTable, pairedConfidenceIntervalTable] = ...
    localCompareEvents( ...
    pairSet, ...
    positionErrors, ...
    velocityErrors, ...
    causalPrediction.eligibleMask, ...
    confidenceLevel);
transitionMetricTable = localScoreTransitions( ...
    pairSet, ...
    models, ...
    positionErrors, ...
    velocityErrors, ...
    causalPrediction.eligibleMask);

runtimeTable = table( ...
    repmat(string(pairSet.domain), 5, 1), ...
    [ ...
        "expanded_warm_mean_v1"; ...
        "constvel"; ...
        "constacc"; ...
        "constturn"; ...
        "causal_history_initialization"], ...
    [ ...
        rowCount; ...
        rowCount; ...
        sum(causalPrediction.eligibleMask); ...
        sum(causalPrediction.eligibleMask); ...
        rowCount], ...
    [ ...
        warmSeconds; ...
        constvelSeconds; ...
        causalRuntime.constaccSeconds; ...
        causalRuntime.constturnSeconds; ...
        causalRuntime.initializationSeconds], ...
    'VariableNames', [ ...
        "domain", ...
        "modelID", ...
        "pairCount", ...
        "elapsedSeconds"]);
runtimeTable.microsecondsPerPair = ...
    1e6*runtimeTable.elapsedSeconds ./ max(runtimeTable.pairCount, 1);

matchedGroups = groupsummary( ...
    metricTable, ...
    ["domain", "profile", "comparisonFamily", "weighting"], ...
    ["min", "max"], ...
    "sampleCount");
audit = struct();
audit.rowCount = rowCount;
audit.sameInformationRowCount = rowCount;
audit.causalHistoryRowCount = sum(causalPrediction.eligibleMask);
audit.finiteWarmPrediction = all(isfinite(warmPrediction), "all");
audit.finiteConstvelPrediction = all(isfinite(constvelPrediction), "all");
audit.finiteCausalPredictions = all(isfinite( ...
    causalPrediction.constaccPrediction(causalPrediction.eligibleMask, :)), ...
    "all") && all(isfinite( ...
    causalPrediction.constturnPrediction(causalPrediction.eligibleMask, :)), ...
    "all");
audit.matchedComparisonRows = all( ...
    matchedGroups.min_sampleCount == matchedGroups.max_sampleCount);
audit.warmUsesPredecessorHistory = false;
audit.constvelUsesPredecessorHistory = false;
audit.constaccUsesPredecessorHistory = true;
audit.constturnUsesPredecessorHistory = true;
audit.targetStateUsedForPrediction = false;
audit.motionLabelUsedForPrediction = false;
audit.passed = audit.finiteWarmPrediction && ...
    audit.finiteConstvelPrediction && ...
    audit.finiteCausalPredictions && ...
    audit.matchedComparisonRows && ...
    ~audit.targetStateUsedForPrediction && ...
    ~audit.motionLabelUsedForPrediction;

evaluation = struct();
evaluation.domain = string(pairSet.domain);
evaluation.metricTable = metricTable;
evaluation.canonicalMetricTable = canonicalMetricTable;
evaluation.eventWinRateTable = eventWinRateTable;
evaluation.pairedConfidenceIntervalTable = pairedConfidenceIntervalTable;
evaluation.transitionMetricTable = transitionMetricTable;
evaluation.runtimeTable = runtimeTable;
evaluation.audit = audit;
evaluation.causalPolicy = causalPrediction.policy;
evaluation.confidenceIntervalMethod = ...
    "Paired event-RMSE mean difference with a two-sided Student t interval.";
evaluation.errorDifferenceConvention = ...
    "Warm minus comparator; negative values favor the warm model.";

if retainPredictions
    evaluation.predictionReview = struct( ...
        "warm", warmPrediction, ...
        "constvel", constvelPrediction, ...
        "constacc", causalPrediction.constaccPrediction, ...
        "constturn", causalPrediction.constturnPrediction, ...
        "causalEligibleMask", causalPrediction.eligibleMask, ...
        "predecessorRow", causalPrediction.predecessorRow);
end

end

function predictedState = localPredictConstvel(previousState, dtSeconds)
%LOCALPREDICTCONSTVEL Apply native constvel for every distinct interval.

predictedState = NaN(size(previousState));
[uniqueDtSeconds, ~, dtGroup] = unique(dtSeconds);

for groupIdx = 1:numel(uniqueDtSeconds)
    rowMask = dtGroup == groupIdx;
    predicted = constvel( ...
        previousState(rowMask, :).', ...
        uniqueDtSeconds(groupIdx));
    predictedState(rowMask, :) = predicted.';
end

end

function predictedState = localPredictWarm( ...
        previousState, ...
        previousCovarianceDiag, ...
        dtSeconds, ...
        constvelPrediction, ...
        warmModel, ...
        miniBatchSize)
%LOCALPREDICTWARM Run the frozen warm network in physical units.

featureData = helperBuildStage4CFeatures( ...
    previousState, ...
    previousCovarianceDiag, ...
    dtSeconds, ...
    constvelPrediction);
featureNormalization = warmModel.featureNormalization;
targetNormalization = warmModel.targetNormalization;
normalizedFeatures = ...
    (featureData.features - featureNormalization.featureMean) ./ ...
    featureNormalization.featureStd;
normalizedDelta = minibatchpredict( ...
    warmModel.net, ...
    single(normalizedFeatures), ...
    MiniBatchSize=min(miniBatchSize, size(normalizedFeatures, 1)));
normalizedDelta = gather(extractdata(normalizedDelta));

if size(normalizedDelta, 1) ~= size(previousState, 1) && ...
        size(normalizedDelta, 2) == size(previousState, 1)
    normalizedDelta = normalizedDelta.';
end

if ~isequal(size(normalizedDelta), size(previousState))
    error("Stage4D:WarmPredictionShapeMismatch", ...
        "The frozen warm model must return one six-state delta per input row.");
end

physicalDelta = double(normalizedDelta) .* ...
    targetNormalization.targetStd + ...
    targetNormalization.targetMean;
predictedState = previousState + physicalDelta;

end

function [prediction, runtime] = localPredictCausalNative(pairSet)
%LOCALPREDICTCAUSALNATIVE Initialize CA and CT from one predecessor.

initializationTimer = tic;
rowCount = size(pairSet.previousState, 1);
predecessorRow = zeros(rowCount, 1);

if rowCount > 1
    sameEvent = pairSet.eventID(2:end) == pairSet.eventID(1:end - 1);
    adjacentTime = abs( ...
        pairSet.timeKSeconds(2:end) - ...
        pairSet.timeNextSeconds(1:end - 1)) <= 1e-9;
    hasPredecessor = sameEvent & adjacentTime;
    predecessorRow(find(hasPredecessor) + 1) = find(hasPredecessor);
end

eligibleMask = predecessorRow > 0;
eligibleRows = find(eligibleMask);
priorRows = predecessorRow(eligibleRows);
priorDtSeconds = ...
    pairSet.timeKSeconds(eligibleRows) - ...
    pairSet.timeKSeconds(priorRows);
currentVelocity = pairSet.previousState(eligibleRows, [2, 4, 6]);
priorVelocity = pairSet.previousState(priorRows, [2, 4, 6]);
rawAcceleration = ...
    (currentVelocity - priorVelocity) ./ priorDtSeconds;
currentHeadingDegrees = atan2d(currentVelocity(:, 2), currentVelocity(:, 1));
priorHeadingDegrees = atan2d(priorVelocity(:, 2), priorVelocity(:, 1));
rawTurnRateDegreesPerSecond = ...
    wrapTo180(currentHeadingDegrees - priorHeadingDegrees) ./ priorDtSeconds;
finiteInitialization = ...
    all(isfinite(rawAcceleration), 2) & ...
    isfinite(rawTurnRateDegreesPerSecond) & ...
    isfinite(priorDtSeconds) & ...
    priorDtSeconds > 0;
eligibleMask(eligibleRows(~finiteInitialization)) = false;
eligibleRows = find(eligibleMask);
priorRows = predecessorRow(eligibleRows);
priorDtSeconds = ...
    pairSet.timeKSeconds(eligibleRows) - ...
    pairSet.timeKSeconds(priorRows);
currentVelocity = pairSet.previousState(eligibleRows, [2, 4, 6]);
priorVelocity = pairSet.previousState(priorRows, [2, 4, 6]);
rawAcceleration = ...
    (currentVelocity - priorVelocity) ./ priorDtSeconds;
currentHeadingDegrees = atan2d(currentVelocity(:, 2), currentVelocity(:, 1));
priorHeadingDegrees = atan2d(priorVelocity(:, 2), priorVelocity(:, 1));
rawTurnRateDegreesPerSecond = ...
    wrapTo180(currentHeadingDegrees - priorHeadingDegrees) ./ priorDtSeconds;
constaccInitialState = [ ...
    pairSet.previousState(eligibleRows, 1), ...
    pairSet.previousState(eligibleRows, 2), ...
    rawAcceleration(:, 1), ...
    pairSet.previousState(eligibleRows, 3), ...
    pairSet.previousState(eligibleRows, 4), ...
    rawAcceleration(:, 2), ...
    pairSet.previousState(eligibleRows, 5), ...
    pairSet.previousState(eligibleRows, 6), ...
    rawAcceleration(:, 3)];
constturnInitialState = [ ...
    pairSet.previousState(eligibleRows, 1), ...
    pairSet.previousState(eligibleRows, 2), ...
    pairSet.previousState(eligibleRows, 3), ...
    pairSet.previousState(eligibleRows, 4), ...
    rawTurnRateDegreesPerSecond, ...
    pairSet.previousState(eligibleRows, 5), ...
    pairSet.previousState(eligibleRows, 6)];
runtime = struct();
runtime.initializationSeconds = toc(initializationTimer);

constaccTimer = tic;
constaccState = localPropagateByDt( ...
    constaccInitialState, ...
    pairSet.dtSeconds(eligibleRows), ...
    "constacc");
runtime.constaccSeconds = toc(constaccTimer);
constturnTimer = tic;
constturnState = localPropagateByDt( ...
    constturnInitialState, ...
    pairSet.dtSeconds(eligibleRows), ...
    "constturn");
runtime.constturnSeconds = toc(constturnTimer);

constaccPrediction = NaN(rowCount, 6);
constturnPrediction = NaN(rowCount, 6);
constaccPrediction(eligibleRows, :) = ...
    constaccState(:, [1, 2, 4, 5, 7, 8]);
constturnPrediction(eligibleRows, :) = ...
    constturnState(:, [1, 2, 3, 4, 6, 7]);
finitePrediction = ...
    all(isfinite(constaccPrediction), 2) & ...
    all(isfinite(constturnPrediction), 2);
eligibleMask = eligibleMask & finitePrediction;

prediction = struct();
prediction.eligibleMask = eligibleMask;
prediction.constaccPrediction = constaccPrediction;
prediction.constturnPrediction = constturnPrediction;
prediction.predecessorRow = predecessorRow;
prediction.policy = table( ...
    ["constacc"; "constturn"], ...
    ["raw 3-D velocity finite difference"; "wrapped ENU heading finite difference"], ...
    [true; true], ...
    [false; false], ...
    [false; false], ...
    'VariableNames', [ ...
        "modelID", ...
        "causalInitialization", ...
        "usesPredecessorHistory", ...
        "usesTargetState", ...
        "usesMotionLabel"]);

end

function predictedState = localPropagateByDt(initialState, dtSeconds, modelName)
%LOCALPROPAGATEBYDT Apply one native motion function per distinct interval.

predictedState = NaN(size(initialState));
[uniqueDtSeconds, ~, dtGroup] = unique(dtSeconds);

for groupIdx = 1:numel(uniqueDtSeconds)
    rowMask = dtGroup == groupIdx;

    if modelName == "constacc"
        predicted = constacc( ...
            initialState(rowMask, :).', ...
            uniqueDtSeconds(groupIdx));
    elseif modelName == "constturn"
        predicted = constturn( ...
            initialState(rowMask, :).', ...
            uniqueDtSeconds(groupIdx));
    else
        error("Stage4D:UnknownNativeModel", ...
            "Native model must be constacc or constturn.");
    end

    predictedState(rowMask, :) = predicted.';
end

end

function models = localBuildModels( ...
        warmPrediction, constvelPrediction, causalPrediction)
%LOCALBUILDMODELS Preserve the fixed Stage 4D comparison order.

models = repmat(struct( ...
    "modelID", "", ...
    "prediction", []), ...
    4, ...
    1);
models(1).modelID = "expanded_warm_mean_v1";
models(1).prediction = warmPrediction;
models(2).modelID = "constvel";
models(2).prediction = constvelPrediction;
models(3).modelID = "constacc";
models(3).prediction = causalPrediction.constaccPrediction;
models(4).modelID = "constturn";
models(4).prediction = causalPrediction.constturnPrediction;

end

function errors = localStateErrors(models, targetState, stateColumns)
%LOCALSTATEERRORS Compute Euclidean state-subvector errors for each model.

errors = NaN(size(targetState, 1), numel(models));

for modelIdx = 1:numel(models)
    errors(:, modelIdx) = vecnorm( ...
        models(modelIdx).prediction(:, stateColumns) - ...
        targetState(:, stateColumns), ...
        2, ...
        2);
end

end

function metricTable = localScoreProfiles( ...
        pairSet, models, positionErrors, velocityErrors, causalMask)
%LOCALSCOREPROFILES Score pair- and event-weighted profile metrics.

profiles = unique(pairSet.profile, "stable");
metricRows = cell(numel(profiles)*12, 1);
rowIdx = 0;

for profileIdx = 1:numel(profiles)
    profileName = profiles(profileIdx);
    profileMask = pairSet.profile == profileName;
    [metricRows, rowIdx] = localAppendFamilyMetrics( ...
        metricRows, ...
        rowIdx, ...
        pairSet, ...
        models, ...
        positionErrors, ...
        velocityErrors, ...
        profileMask, ...
        "same_information", ...
        [1, 2], ...
        profileName);
    [metricRows, rowIdx] = localAppendFamilyMetrics( ...
        metricRows, ...
        rowIdx, ...
        pairSet, ...
        models, ...
        positionErrors, ...
        velocityErrors, ...
        profileMask & causalMask, ...
        "causal_history", ...
        1:4, ...
        profileName);
end

metricTable = vertcat(metricRows{1:rowIdx});

end

function metricTable = localScoreCanonicalCases( ...
        pairSet, models, positionErrors, velocityErrors, causalMask)
%LOCALSCORECANONICALCASES Retain a model table for each canonical case.

if pairSet.domain ~= "synthetic_canonical"
    metricTable = localEmptyMetricTable();
    return;
end

caseIDs = unique(pairSet.caseID, "stable");
metricRows = cell(numel(caseIDs)*12, 1);
rowIdx = 0;

for caseIdx = 1:numel(caseIDs)
    caseID = caseIDs(caseIdx);
    caseMask = pairSet.caseID == caseID;
    profileName = unique(pairSet.profile(caseMask));
    [metricRows, rowIdx] = localAppendFamilyMetrics( ...
        metricRows, ...
        rowIdx, ...
        pairSet, ...
        models, ...
        positionErrors, ...
        velocityErrors, ...
        caseMask, ...
        "same_information", ...
        [1, 2], ...
        profileName, ...
        caseID);
    [metricRows, rowIdx] = localAppendFamilyMetrics( ...
        metricRows, ...
        rowIdx, ...
        pairSet, ...
        models, ...
        positionErrors, ...
        velocityErrors, ...
        caseMask & causalMask, ...
        "causal_history", ...
        1:4, ...
        profileName, ...
        caseID);
end

metricTable = vertcat(metricRows{1:rowIdx});

end

function [metricRows, rowIdx] = localAppendFamilyMetrics( ...
        metricRows, ...
        rowIdx, ...
        pairSet, ...
        models, ...
        positionErrors, ...
        velocityErrors, ...
        rowMask, ...
        comparisonFamily, ...
        modelIndices, ...
        profileName, ...
        caseID)
%LOCALAPPENDFAMILYMETRICS Add both weighting policies for selected models.

if nargin < 11
    caseID = "all";
end

[eventWeights, eventCount] = localIndependentEventWeights( ...
    pairSet.eventID(rowMask));
pairWeights = ones(sum(rowMask), 1);

for modelIdx = modelIndices
    rowIdx = rowIdx + 1;
    metricRows{rowIdx} = localMetricRow( ...
        pairSet, ...
        models(modelIdx).modelID, ...
        profileName, ...
        comparisonFamily, ...
        "pair_weighted", ...
        caseID, ...
        positionErrors(rowMask, modelIdx), ...
        velocityErrors(rowMask, modelIdx), ...
        pairWeights, ...
        eventCount);
    rowIdx = rowIdx + 1;
    metricRows{rowIdx} = localMetricRow( ...
        pairSet, ...
        models(modelIdx).modelID, ...
        profileName, ...
        comparisonFamily, ...
        "independent_event_weighted", ...
        caseID, ...
        positionErrors(rowMask, modelIdx), ...
        velocityErrors(rowMask, modelIdx), ...
        eventWeights, ...
        eventCount);
end

end

function metricRow = localMetricRow( ...
        pairSet, ...
        modelID, ...
        profileName, ...
        comparisonFamily, ...
        weighting, ...
        caseID, ...
        positionError, ...
        velocityError, ...
        weights, ...
        eventCount)
%LOCALMETRICROW Create one physical-unit summary row.

metricRow = table( ...
    string(pairSet.domain), ...
    string(profileName), ...
    string(comparisonFamily), ...
    string(modelID), ...
    string(weighting), ...
    string(caseID), ...
    unique(pairSet.targetReference), ...
    numel(positionError), ...
    eventCount, ...
    localWeightedRMSE(positionError, weights), ...
    localWeightedQuantile(positionError, weights, 0.50), ...
    localWeightedQuantile(positionError, weights, 0.95), ...
    localWeightedRMSE(velocityError, weights), ...
    localWeightedQuantile(velocityError, weights, 0.50), ...
    localWeightedQuantile(velocityError, weights, 0.95), ...
    'VariableNames', [ ...
        "domain", ...
        "profile", ...
        "comparisonFamily", ...
        "modelID", ...
        "weighting", ...
        "caseID", ...
        "targetReference", ...
        "sampleCount", ...
        "eventCount", ...
        "positionRMSEMeters", ...
        "positionMedianErrorMeters", ...
        "positionP95ErrorMeters", ...
        "velocityRMSEMetersPerSecond", ...
        "velocityMedianErrorMetersPerSecond", ...
        "velocityP95ErrorMetersPerSecond"]);

end

function [winTable, confidenceTable] = localCompareEvents( ...
        pairSet, positionErrors, velocityErrors, causalMask, confidenceLevel)
%LOCALCOMPAREEVENTS Compare paired event RMSE values against the warm model.

profiles = unique(pairSet.profile, "stable");
winRows = cell(numel(profiles)*4, 1);
confidenceRows = cell(numel(profiles)*4, 1);
rowIdx = 0;

for profileIdx = 1:numel(profiles)
    profileName = profiles(profileIdx);
    profileMask = pairSet.profile == profileName;
    [winRows, confidenceRows, rowIdx] = localAppendEventComparisons( ...
        winRows, ...
        confidenceRows, ...
        rowIdx, ...
        pairSet, ...
        positionErrors, ...
        velocityErrors, ...
        profileMask, ...
        profileName, ...
        "same_information", ...
        2, ...
        confidenceLevel);
    [winRows, confidenceRows, rowIdx] = localAppendEventComparisons( ...
        winRows, ...
        confidenceRows, ...
        rowIdx, ...
        pairSet, ...
        positionErrors, ...
        velocityErrors, ...
        profileMask & causalMask, ...
        profileName, ...
        "causal_history", ...
        2:4, ...
        confidenceLevel);
end

winTable = vertcat(winRows{1:rowIdx});
confidenceTable = vertcat(confidenceRows{1:rowIdx});

end

function [winRows, confidenceRows, rowIdx] = localAppendEventComparisons( ...
        winRows, ...
        confidenceRows, ...
        rowIdx, ...
        pairSet, ...
        positionErrors, ...
        velocityErrors, ...
        rowMask, ...
        profileName, ...
        comparisonFamily, ...
        comparatorIndices, ...
        confidenceLevel)
%LOCALAPPENDEVENTCOMPARISONS Add warm-versus-comparator event statistics.

selectedEventID = pairSet.eventID(rowMask);
[eventGroup, eventValues] = findgroups(selectedEventID);
warmPositionRMSE = splitapply( ...
    @(values) sqrt(mean(values .^ 2)), ...
    positionErrors(rowMask, 1), ...
    eventGroup);
warmVelocityRMSE = splitapply( ...
    @(values) sqrt(mean(values .^ 2)), ...
    velocityErrors(rowMask, 1), ...
    eventGroup);

for comparatorIdx = comparatorIndices
    comparatorPositionRMSE = splitapply( ...
        @(values) sqrt(mean(values .^ 2)), ...
        positionErrors(rowMask, comparatorIdx), ...
        eventGroup);
    comparatorVelocityRMSE = splitapply( ...
        @(values) sqrt(mean(values .^ 2)), ...
        velocityErrors(rowMask, comparatorIdx), ...
        eventGroup);
    positionDifference = warmPositionRMSE - comparatorPositionRMSE;
    velocityDifference = warmVelocityRMSE - comparatorVelocityRMSE;
    positionCI = localPairedMeanConfidenceInterval( ...
        positionDifference, ...
        confidenceLevel);
    velocityCI = localPairedMeanConfidenceInterval( ...
        velocityDifference, ...
        confidenceLevel);
    rowIdx = rowIdx + 1;
    comparatorID = localModelID(comparatorIdx);
    winRows{rowIdx} = table( ...
        string(pairSet.domain), ...
        string(profileName), ...
        string(comparisonFamily), ...
        comparatorID, ...
        numel(eventValues), ...
        mean(positionDifference < 0), ...
        mean(abs(positionDifference) <= 1e-12), ...
        mean(velocityDifference < 0), ...
        mean(abs(velocityDifference) <= 1e-12), ...
        'VariableNames', [ ...
            "domain", ...
            "profile", ...
            "comparisonFamily", ...
            "comparatorModelID", ...
            "eventCount", ...
            "warmPositionWinRate", ...
            "positionTieRate", ...
            "warmVelocityWinRate", ...
            "velocityTieRate"]);
    confidenceRows{rowIdx} = table( ...
        string(pairSet.domain), ...
        string(profileName), ...
        string(comparisonFamily), ...
        comparatorID, ...
        numel(eventValues), ...
        confidenceLevel, ...
        mean(positionDifference), ...
        positionCI(1), ...
        positionCI(2), ...
        mean(velocityDifference), ...
        velocityCI(1), ...
        velocityCI(2), ...
        'VariableNames', [ ...
            "domain", ...
            "profile", ...
            "comparisonFamily", ...
            "comparatorModelID", ...
            "eventCount", ...
            "confidenceLevel", ...
            "meanPositionRMSEDifferenceMeters", ...
            "positionDifferenceLower", ...
            "positionDifferenceUpper", ...
            "meanVelocityRMSEDifferenceMetersPerSecond", ...
            "velocityDifferenceLower", ...
            "velocityDifferenceUpper"]);
end

end

function transitionTable = localScoreTransitions( ...
        pairSet, models, positionErrors, velocityErrors, causalMask)
%LOCALSCORETRANSITIONS Summarize error relative to the nearest motion change.

transitionEdges = [-30, -10, 0, 10, 30, 60];
transitionLabels = [ ...
    "minus30_to_minus10"; ...
    "minus10_to_0"; ...
    "0_to_10"; ...
    "10_to_30"; ...
    "30_to_60"];
transitionBin = discretize( ...
    pairSet.transitionOffsetSeconds, ...
    transitionEdges);

if all(isnan(transitionBin))
    transitionTable = localEmptyTransitionTable();
    return;
end

profiles = unique(pairSet.profile, "stable");
transitionRows = cell(numel(profiles)*numel(transitionLabels)*6, 1);
rowIdx = 0;

for profileIdx = 1:numel(profiles)
    profileName = profiles(profileIdx);

    for binIdx = 1:numel(transitionLabels)
        baseMask = pairSet.profile == profileName & transitionBin == binIdx;
        [transitionRows, rowIdx] = localAppendTransitionRows( ...
            transitionRows, ...
            rowIdx, ...
            pairSet, ...
            models, ...
            positionErrors, ...
            velocityErrors, ...
            baseMask, ...
            profileName, ...
            "same_information", ...
            [1, 2], ...
            transitionLabels(binIdx), ...
            mean(transitionEdges(binIdx:(binIdx + 1))));
        [transitionRows, rowIdx] = localAppendTransitionRows( ...
            transitionRows, ...
            rowIdx, ...
            pairSet, ...
            models, ...
            positionErrors, ...
            velocityErrors, ...
            baseMask & causalMask, ...
            profileName, ...
            "causal_history", ...
            1:4, ...
            transitionLabels(binIdx), ...
            mean(transitionEdges(binIdx:(binIdx + 1))));
    end
end

transitionTable = vertcat(transitionRows{1:rowIdx});

end

function [transitionRows, rowIdx] = localAppendTransitionRows( ...
        transitionRows, ...
        rowIdx, ...
        pairSet, ...
        models, ...
        positionErrors, ...
        velocityErrors, ...
        rowMask, ...
        profileName, ...
        comparisonFamily, ...
        modelIndices, ...
        transitionBin, ...
        transitionBinCenterSeconds)
%LOCALAPPENDTRANSITIONROWS Add pair-weighted errors for one time bin.

for modelIdx = modelIndices
    positionError = positionErrors(rowMask, modelIdx);
    velocityError = velocityErrors(rowMask, modelIdx);
    rowIdx = rowIdx + 1;
    transitionRows{rowIdx} = table( ...
        string(pairSet.domain), ...
        string(profileName), ...
        string(comparisonFamily), ...
        string(models(modelIdx).modelID), ...
        string(transitionBin), ...
        transitionBinCenterSeconds, ...
        numel(positionError), ...
        numel(unique(pairSet.eventID(rowMask))), ...
        sqrt(mean(positionError .^ 2)), ...
        median(positionError), ...
        sqrt(mean(velocityError .^ 2)), ...
        median(velocityError), ...
        'VariableNames', [ ...
            "domain", ...
            "profile", ...
            "comparisonFamily", ...
            "modelID", ...
            "transitionBin", ...
            "transitionBinCenterSeconds", ...
            "sampleCount", ...
            "eventCount", ...
            "positionRMSEMeters", ...
            "positionMedianErrorMeters", ...
            "velocityRMSEMetersPerSecond", ...
            "velocityMedianErrorMetersPerSecond"]);
end

end

function [weights, eventCount] = localIndependentEventWeights(eventID)
%LOCALINDEPENDENTEVENTWEIGHTS Give every event equal total pair weight.

if isempty(eventID)
    weights = zeros(0, 1);
    eventCount = 0;
    return;
end

[eventGroup, ~] = findgroups(eventID);
eventLength = accumarray(eventGroup, 1);
weights = 1 ./ eventLength(eventGroup);
eventCount = numel(eventLength);

end

function interval = localPairedMeanConfidenceInterval( ...
        differences, confidenceLevel)
%LOCALPAIREDMEANCONFIDENCEINTERVAL Compute a paired Student t interval.

differences = differences(isfinite(differences));
sampleCount = numel(differences);
meanDifference = mean(differences);

if sampleCount < 2
    interval = [meanDifference, meanDifference];
    return;
end

alpha = 1 - confidenceLevel;
criticalValue = tinv(1 - alpha / 2, sampleCount - 1);
halfWidth = criticalValue*std(differences, 0) / sqrt(sampleCount);
interval = meanDifference + [-halfWidth, halfWidth];

end

function modelID = localModelID(modelIdx)
%LOCALMODELID Map fixed model columns to their public identities.

modelIDs = [ ...
    "expanded_warm_mean_v1"; ...
    "constvel"; ...
    "constacc"; ...
    "constturn"];
modelID = modelIDs(modelIdx);

end

function value = localWeightedRMSE(errors, weights)
%LOCALWEIGHTEDRMSE Compute weighted root mean square error.

value = sqrt(sum(weights .* errors .^ 2) / sum(weights));

end

function value = localWeightedQuantile(values, weights, probability)
%LOCALWEIGHTEDQUANTILE Return a left-continuous weighted quantile.

[values, order] = sort(values);
weights = weights(order);
cumulativeWeight = cumsum(weights);
threshold = probability*cumulativeWeight(end);
quantileIndex = find(cumulativeWeight >= threshold, 1, "first");
value = values(quantileIndex);

end

function metricTable = localEmptyMetricTable()
%LOCALEMPTYMETRICTABLE Return a typed empty metric table.

metricTable = table( ...
    strings(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    'VariableNames', [ ...
        "domain", ...
        "profile", ...
        "comparisonFamily", ...
        "modelID", ...
        "weighting", ...
        "caseID", ...
        "targetReference", ...
        "sampleCount", ...
        "eventCount", ...
        "positionRMSEMeters", ...
        "positionMedianErrorMeters", ...
        "positionP95ErrorMeters", ...
        "velocityRMSEMetersPerSecond", ...
        "velocityMedianErrorMetersPerSecond", ...
        "velocityP95ErrorMetersPerSecond"]);

end

function transitionTable = localEmptyTransitionTable()
%LOCALEMPTYTRANSITIONTABLE Return a typed empty transition table.

transitionTable = table( ...
    strings(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    'VariableNames', [ ...
        "domain", ...
        "profile", ...
        "comparisonFamily", ...
        "modelID", ...
        "transitionBin", ...
        "transitionBinCenterSeconds", ...
        "sampleCount", ...
        "eventCount", ...
        "positionRMSEMeters", ...
        "positionMedianErrorMeters", ...
        "velocityRMSEMetersPerSecond", ...
        "velocityMedianErrorMetersPerSecond"]);

end

function localValidateInputs(pairSet, warmModel, miniBatchSize, confidenceLevel)
%LOCALVALIDATEINPUTS Enforce aligned inputs and frozen warm-model fields.

requiredPairFields = [ ...
    "domain", ...
    "previousState", ...
    "targetState", ...
    "previousCovarianceDiag", ...
    "dtSeconds", ...
    "timeKSeconds", ...
    "timeNextSeconds", ...
    "eventID", ...
    "caseID", ...
    "profile", ...
    "targetReference", ...
    "transitionOffsetSeconds"];
requiredWarmFields = [ ...
    "net", ...
    "featureNormalization", ...
    "targetNormalization"];

if ~isstruct(pairSet) || any(~isfield(pairSet, requiredPairFields))
    error("Stage4D:InvalidPairSet", ...
        "The Stage 4D pair set is missing required aligned fields.");
end

if ~isstruct(warmModel) || any(~isfield(warmModel, requiredWarmFields))
    error("Stage4D:InvalidWarmModel", ...
        "The warm model must contain net and feature/target normalization.");
end

rowCount = size(pairSet.previousState, 1);

if rowCount == 0 || ...
        ~isequal(size(pairSet.previousState), [rowCount, 6]) || ...
        ~isequal(size(pairSet.targetState), [rowCount, 6]) || ...
        ~isequal(size(pairSet.previousCovarianceDiag), [rowCount, 6]) || ...
        numel(pairSet.dtSeconds) ~= rowCount || ...
        numel(pairSet.timeKSeconds) ~= rowCount || ...
        numel(pairSet.timeNextSeconds) ~= rowCount || ...
        numel(pairSet.eventID) ~= rowCount || ...
        numel(pairSet.profile) ~= rowCount
    error("Stage4D:PairSetAlignmentMismatch", ...
        "All Stage 4D pair fields must describe identical N-by-6 rows.");
end

validateattributes(pairSet.previousState, ...
    {'numeric'}, {'2d', 'real', 'finite'}, mfilename, "previousState");
validateattributes(pairSet.targetState, ...
    {'numeric'}, {'2d', 'real', 'finite'}, mfilename, "targetState");
validateattributes(pairSet.previousCovarianceDiag, ...
    {'numeric'}, {'2d', 'real', 'finite', 'positive'}, ...
    mfilename, "previousCovarianceDiag");
validateattributes(pairSet.dtSeconds, ...
    {'numeric'}, {'column', 'real', 'finite', 'positive'}, ...
    mfilename, "dtSeconds");
validateattributes(miniBatchSize, ...
    {'numeric'}, {'scalar', 'integer', 'positive'}, ...
    mfilename, "PredictionMiniBatchSize");
validateattributes(confidenceLevel, ...
    {'numeric'}, {'scalar', 'real', '>', 0, '<', 1}, ...
    mfilename, "ConfidenceLevel");

end

function value = localLogicalScalar(value, argumentName)
%LOCALLOGICALSCALAR Accept scalar logical or numeric zero/one.

isLogicalScalar = islogical(value) && isscalar(value);
isBinaryNumericScalar = isnumeric(value) && isscalar(value) && ...
    isfinite(value) && (value == 0 || value == 1);

if ~isLogicalScalar && ~isBinaryNumericScalar
    error("Stage4D:InvalidLogicalOption", ...
        "%s must be a scalar logical value.", argumentName);
end

value = logical(value);

end
