function context = helperLoadStage4EWarmContext()
%HELPERLOADSTAGE4EWARMCONTEXT Load the frozen Stage 4C transition context.
% The fixed covariance diagonal is the covariance used by every Stage 4C
% training row. It is an input feature to the network, not a covariance
% prediction made by the network.

persistent cachedContext

if ~isempty(cachedContext)
    context = cachedContext;
    return;
end

projectRoot = string(fileparts(mfilename("fullpath")));
warmArtifactPath = fullfile( ...
    projectRoot, ...
    "artifacts", ...
    "stage4CRetrain", ...
    "expandedPost3DayWarmStartMeanMLP_v1.mat");
datasetPath = fullfile( ...
    projectRoot, ...
    "artifacts", ...
    "stage4BPostCampaign", ...
    "expanded_post3day_v2", ...
    "stage3CArchiveStatePairDataset.mat");
loadedWarm = load( ...
    warmArtifactPath, ...
    "net", ...
    "normalization", ...
    "modelArtifact");
loadedDataset = load(datasetPath, "covarianceStdAssumed");

if ~isfield(loadedWarm, "net") || ...
        ~isfield(loadedWarm, "normalization") || ...
        ~isfield(loadedWarm, "modelArtifact") || ...
        string(loadedWarm.modelArtifact.modelID) ~= "expanded_warm_mean_v1"
    error("Stage4E:WarmArtifactContractMismatch", ...
        "The frozen warm model does not match expanded_warm_mean_v1.");
end

if ~isfield(loadedDataset, "covarianceStdAssumed")
    error("Stage4E:MissingTrainingCovariance", ...
        "The frozen dataset does not record covarianceStdAssumed.");
end

fixedCovarianceDiag = double(loadedDataset.covarianceStdAssumed(:).').^2;

if numel(fixedCovarianceDiag) ~= 6 || ...
        any(~isfinite(fixedCovarianceDiag)) || ...
        any(fixedCovarianceDiag <= 0)
    error("Stage4E:InvalidTrainingCovariance", ...
        "The fixed training covariance diagonal must contain six positive values.");
end

cachedContext = struct();
cachedContext.net = loadedWarm.net;
cachedContext.featureNormalization = loadedWarm.normalization.features;
cachedContext.targetNormalization = loadedWarm.normalization.target;
cachedContext.fixedTrainingCovarianceDiag = fixedCovarianceDiag;
cachedContext.modelID = string(loadedWarm.modelArtifact.modelID);
cachedContext.warmArtifactPath = string(warmArtifactPath);
cachedContext.datasetPath = string(datasetPath);
context = cachedContext;

end
