function output = helperPlotStage4DInputPreview(preview, varargin)
%HELPERPLOTSTAGE4DINPUTPREVIEW Plot one input-only degraded trajectory.
% The figure intentionally contains observations and retained sampling
% intervals only. It does not contain latent truth or model predictions.

parser = inputParser;
parser.FunctionName = mfilename;
addRequired(parser, "preview");
addParameter(parser, "SavePath", "");
parse(parser, preview, varargin{:});

savePath = strtrim(string(parser.Results.SavePath));
localValidatePreview(preview);
observedState = double(preview.observationState);
timeSeconds = double(preview.observationTimeSeconds(:));
retainedIntervals = double(preview.retainedIntervalSeconds(:));

figureHandle = figure( ...
    Name="Stage 4D Input Preview", ...
    Color="w", ...
    Position=[100, 100, 1300, 430]);
tiledlayout( ...
    figureHandle, ...
    1, ...
    3, ...
    TileSpacing="compact", ...
    Padding="compact");

axesHandles = gobjects(3, 1);
dataColor = [0.0000, 0.4470, 0.7410];

axesHandles(1) = nexttile;
plot( ...
    axesHandles(1), ...
    observedState(:, 1), ...
    observedState(:, 3), ...
    ".-", ...
    Color=dataColor, ...
    LineWidth=1.1)
axis equal
grid on
xlabel("East (m)", Color="k")
ylabel("North (m)", Color="k")
title("Retained horizontal observations", Color="k")

axesHandles(2) = nexttile;
plot( ...
    axesHandles(2), ...
    timeSeconds, ...
    observedState(:, 5), ...
    ".-", ...
    Color=dataColor, ...
    LineWidth=1.1)
grid on
xlabel("Elapsed time (s)", Color="k")
ylabel("Altitude above ENU origin (m)", Color="k")
title("Retained altitude observations", Color="k")

axesHandles(3) = nexttile;
stem( ...
    axesHandles(3), ...
    timeSeconds(2:end), ...
    retainedIntervals(2:end), ...
    "filled", ...
    Color=dataColor, ...
    MarkerSize=3)
yline( ...
    preview.nominalTruthIntervalSeconds, ...
    "--", ...
    "Latent-grid interval", ...
    Color=[0.35, 0.35, 0.35], ...
    LabelColor="k", ...
    LabelVerticalAlignment="bottom");
grid on
xlabel("Elapsed time (s)", Color="k")
ylabel("Retained interval (s)", Color="k")
title("Irregular sampling and dropout gaps", Color="k")
set( ...
    axesHandles, ...
    Color="w", ...
    XColor="k", ...
    YColor="k", ...
    GridColor=[0.15, 0.15, 0.15], ...
    GridAlpha=0.15);

if strlength(savePath) > 0
    saveFolder = string(fileparts(savePath));

    if strlength(saveFolder) > 0 && ~isfolder(saveFolder)
        mkdir(saveFolder);
    end

    exportgraphics(figureHandle, savePath, Resolution=160);
end

output = struct();
output.figure = figureHandle;
output.savePath = savePath;
output.caseID = string(preview.caseID);
output.observationCount = size(observedState, 1);
output.containsPredictions = false;

end

function localValidatePreview(preview)
%LOCALVALIDATEPREVIEW Enforce the input-only preview contract.

requiredFields = [ ...
    "caseID", ...
    "profile", ...
    "observationTimeSeconds", ...
    "observationState", ...
    "retainedIntervalSeconds", ...
    "nominalTruthIntervalSeconds", ...
    "containsPredictions"];

if ~isstruct(preview) || any(~isfield(preview, requiredFields))
    error("Stage4D:InvalidInputPreview", ...
        "The preview must contain the documented input-only fields.");
end

observationCount = numel(preview.observationTimeSeconds);

if preview.profile ~= "degraded" || ...
        logical(preview.containsPredictions) || ...
        ~isequal(size(preview.observationState), [observationCount, 6]) || ...
        numel(preview.retainedIntervalSeconds) ~= observationCount || ...
        any(diff(preview.observationTimeSeconds) <= 0) || ...
        any(~isfinite(preview.observationState), "all")
    error("Stage4D:InvalidInputPreview", ...
        "The preview must contain finite, monotonic degraded observations only.");
end

end
