function predictedState = helperStage4EWarmTransition( ...
        state, dtSeconds, warmContext)
%HELPERSTAGE4EWARMTRANSITION Apply the frozen network to UKF sigma points.
% The network predicts state only. trackingUKF propagates and maintains the
% recursive covariance independently through its sigma points and Q.

validateattributes(state, ...
    {'numeric'}, {'2d', 'real', 'finite'}, mfilename, "state");
validateattributes(dtSeconds, ...
    {'numeric'}, {'scalar', 'real', 'finite', 'positive'}, ...
    mfilename, "dtSeconds");

isColumnOriented = size(state, 1) == 6;

if isColumnOriented
    stateRows = double(state.');
elseif size(state, 2) == 6
    stateRows = double(state);
else
    error("Stage4E:WarmTransitionStateSize", ...
        "Warm transition states must have six elements per sigma point.");
end

sampleCount = size(stateRows, 1);
dtRows = repmat(double(dtSeconds), sampleCount, 1);
covarianceRows = repmat( ...
    double(warmContext.fixedTrainingCovarianceDiag), ...
    sampleCount, ...
    1);
constvelRows = constvel(stateRows.', double(dtSeconds)).';
featureData = helperBuildStage4CFeatures( ...
    stateRows, ...
    covarianceRows, ...
    dtRows, ...
    constvelRows);
normalizedFeatures = ...
    (featureData.features - ...
    warmContext.featureNormalization.featureMean) ./ ...
    warmContext.featureNormalization.featureStd;
normalizedDelta = predict( ...
    warmContext.net, ...
    single(normalizedFeatures));
normalizedDelta = double(gather(extractdata(normalizedDelta)));

if size(normalizedDelta, 1) ~= sampleCount && ...
        size(normalizedDelta, 2) == sampleCount
    normalizedDelta = normalizedDelta.';
end

if ~isequal(size(normalizedDelta), size(stateRows))
    error("Stage4E:WarmTransitionOutputSize", ...
        "The frozen warm network must return one six-state delta per sigma point.");
end

physicalDelta = normalizedDelta .* ...
    warmContext.targetNormalization.targetStd + ...
    warmContext.targetNormalization.targetMean;
predictedRows = stateRows + physicalDelta;

if isColumnOriented
    predictedState = cast(predictedRows.', "like", state);
else
    predictedState = cast(predictedRows, "like", state);
end

end
