function [pairTable, labelSummary, thresholds] = helperAssignADSBManeuverLabels(previousState, nextState, dtSeconds, varargin)
%HELPERASSIGNADSBMANEUVERLABELS Assign simple model-aligned labels.
% The labels are diagnostic. They describe which native motion-model family
% each adjacent ADS-B state pair most resembles: constvel, constacc, or
% constturn.

parser = inputParser;
parser.FunctionName = mfilename;
addParameter(parser, "Thresholds", struct(), @(value) isstruct(value));
parse(parser, varargin{:});

thresholds = localMergeThresholds(parser.Results.Thresholds);

previousState = double(previousState);
nextState = double(nextState);
dtSeconds = double(dtSeconds(:));

localValidateInputs(previousState, nextState, dtSeconds);

sampleCount = size(previousState, 1);

previousHorizontalVelocity = previousState(:, [2, 4]);
nextHorizontalVelocity = nextState(:, [2, 4]);
previousHorizontalSpeed = vecnorm(previousHorizontalVelocity, 2, 2);
nextHorizontalSpeed = vecnorm(nextHorizontalVelocity, 2, 2);
speedChangeMetersPerSecond = nextHorizontalSpeed - previousHorizontalSpeed;
horizontalAccelerationMetersPerSecondSquared = speedChangeMetersPerSecond ./ dtSeconds;

headingDegreesK = wrapTo180(atan2d(previousState(:, 2), previousState(:, 4)));
headingDegreesNext = wrapTo180(atan2d(nextState(:, 2), nextState(:, 4)));
validHeading = previousHorizontalSpeed >= thresholds.minimumHorizontalSpeedMetersPerSecond & ...
    nextHorizontalSpeed >= thresholds.minimumHorizontalSpeedMetersPerSecond;

headingChangeDegrees = NaN(sampleCount, 1);
headingChangeDegrees(validHeading) = wrapTo180( ...
    headingDegreesNext(validHeading) - headingDegreesK(validHeading));

turnRateDegreesPerSecond = headingChangeDegrees ./ dtSeconds;
absHeadingChangeDegrees = abs(headingChangeDegrees);
absTurnRateDegreesPerSecond = abs(turnRateDegreesPerSecond);

verticalRateMetersPerSecondK = previousState(:, 6);
verticalRateMetersPerSecondNext = nextState(:, 6);
verticalRateChangeMetersPerSecond = verticalRateMetersPerSecondNext - verticalRateMetersPerSecondK;
verticalAccelerationMetersPerSecondSquared = verticalRateChangeMetersPerSecond ./ dtSeconds;

isTurnLike = validHeading & ...
    absHeadingChangeDegrees >= thresholds.headingChangeDegrees & ...
    absTurnRateDegreesPerSecond >= thresholds.turnRateDegreesPerSecond;

isSpeedChangeLike = abs(speedChangeMetersPerSecond) >= thresholds.speedChangeMetersPerSecond;
isHorizontalAccelerationLike = abs(horizontalAccelerationMetersPerSecondSquared) >= ...
    thresholds.horizontalAccelerationMetersPerSecondSquared;
isVerticalRateChangeLike = abs(verticalRateChangeMetersPerSecond) >= ...
    thresholds.verticalRateChangeMetersPerSecond;
isVerticalAccelerationLike = abs(verticalAccelerationMetersPerSecondSquared) >= ...
    thresholds.verticalAccelerationMetersPerSecondSquared;
isAccelerationLike = isSpeedChangeLike | ...
    isHorizontalAccelerationLike | ...
    isVerticalRateChangeLike | ...
    isVerticalAccelerationLike;

isSparseUpdate = dtSeconds >= thresholds.sparseUpdateSeconds;

maneuverClassText = repmat("constvel_like", sampleCount, 1);
maneuverClassText(~isSparseUpdate & ~isTurnLike & isAccelerationLike) = "constacc_like";
maneuverClassText(~isSparseUpdate & isTurnLike & ~isAccelerationLike) = "constturn_like";
maneuverClassText(isSparseUpdate | (isTurnLike & isAccelerationLike)) = "mixed_or_sparse";

maneuverClassOrder = [ ...
    "constvel_like", ...
    "constacc_like", ...
    "constturn_like", ...
    "mixed_or_sparse"];
maneuverClass = categorical( ...
    maneuverClassText, ...
    maneuverClassOrder, ...
    maneuverClassOrder, ...
    "Ordinal", true);

verticalStatusText = repmat("level", sampleCount, 1);
verticalStatusText(verticalRateMetersPerSecondK >= thresholds.climbRateMetersPerSecond) = "climb";
verticalStatusText(verticalRateMetersPerSecondK <= -thresholds.climbRateMetersPerSecond) = "descent";
verticalStatusOrder = ["descent", "level", "climb"];
verticalStatus = categorical( ...
    verticalStatusText, ...
    verticalStatusOrder, ...
    verticalStatusOrder, ...
    "Ordinal", true);

dtRegimeText = repmat("regular_update", sampleCount, 1);
dtRegimeText(isSparseUpdate) = "sparse_update";
dtRegimeOrder = ["regular_update", "sparse_update"];
dtRegime = categorical( ...
    dtRegimeText, ...
    dtRegimeOrder, ...
    dtRegimeOrder, ...
    "Ordinal", true);

pairTable = table( ...
    (1:sampleCount).', ...
    maneuverClass, ...
    previousHorizontalSpeed, ...
    nextHorizontalSpeed, ...
    speedChangeMetersPerSecond, ...
    horizontalAccelerationMetersPerSecondSquared, ...
    headingDegreesK, ...
    headingDegreesNext, ...
    headingChangeDegrees, ...
    turnRateDegreesPerSecond, ...
    absTurnRateDegreesPerSecond, ...
    verticalRateMetersPerSecondK, ...
    verticalRateMetersPerSecondNext, ...
    verticalRateChangeMetersPerSecond, ...
    verticalAccelerationMetersPerSecondSquared, ...
    verticalStatus, ...
    dtSeconds, ...
    dtRegime, ...
    isTurnLike, ...
    isAccelerationLike, ...
    isSparseUpdate, ...
    'VariableNames', [ ...
        "pairIndex", ...
        "maneuverClass", ...
        "horizontalSpeedMetersPerSecondK", ...
        "horizontalSpeedMetersPerSecondNext", ...
        "speedChangeMetersPerSecond", ...
        "horizontalAccelerationMetersPerSecondSquared", ...
        "headingDegreesK", ...
        "headingDegreesNext", ...
        "headingChangeDegrees", ...
        "turnRateDegreesPerSecond", ...
        "absTurnRateDegreesPerSecond", ...
        "verticalRateMetersPerSecondK", ...
        "verticalRateMetersPerSecondNext", ...
        "verticalRateChangeMetersPerSecond", ...
        "verticalAccelerationMetersPerSecondSquared", ...
        "verticalStatus", ...
        "dtSeconds", ...
        "dtRegime", ...
        "isTurnLike", ...
        "isAccelerationLike", ...
        "isSparseUpdate"]);

labelSummary = struct();
labelSummary.thresholds = thresholds;
labelSummary.pairCount = sampleCount;
labelSummary.countsByManeuverClass = localCountCategories(maneuverClass, "maneuverClass");
labelSummary.countsByVerticalStatus = localCountCategories(verticalStatus, "verticalStatus");
labelSummary.countsByDtRegime = localCountCategories(dtRegime, "dtRegime");
labelSummary.indicatorCounts = table( ...
    ["turn_like"; "acceleration_like"; "sparse_update"], ...
    [sum(isTurnLike); sum(isAccelerationLike); sum(isSparseUpdate)], ...
    'VariableNames', ["indicator", "pairCount"]);

end

function thresholds = localMergeThresholds(userThresholds)
%LOCALMERGETHRESHOLDS Merge user thresholds into the Stage 2C defaults.

thresholds = struct();
thresholds.headingChangeDegrees = 0.5;
thresholds.turnRateDegreesPerSecond = 1.0;
thresholds.speedChangeMetersPerSecond = 0.5;
thresholds.horizontalAccelerationMetersPerSecondSquared = 0.5;
thresholds.verticalRateChangeMetersPerSecond = 0.5;
thresholds.verticalAccelerationMetersPerSecondSquared = 0.5;
thresholds.climbRateMetersPerSecond = 1.0;
thresholds.sparseUpdateSeconds = 5.0;
thresholds.minimumHorizontalSpeedMetersPerSecond = 1.0;

if isempty(userThresholds)
    return;
end

userFieldNames = fieldnames(userThresholds);

for fieldIdx = 1:numel(userFieldNames)
    fieldName = userFieldNames{fieldIdx};

    if ~isfield(thresholds, fieldName)
        error("Stage2C:UnknownThreshold", ...
            "Unknown maneuver-label threshold field: %s", fieldName);
    end

    fieldValue = userThresholds.(fieldName);
    validateattributes(fieldValue, {'numeric'}, {'scalar', 'real', 'finite', 'nonnegative'}, ...
        mfilename, fieldName);
    thresholds.(fieldName) = double(fieldValue);
end

validateattributes(thresholds.sparseUpdateSeconds, {'numeric'}, {'scalar', 'positive'}, ...
    mfilename, "sparseUpdateSeconds");

end

function localValidateInputs(previousState, nextState, dtSeconds)
%LOCALVALIDATEINPUTS Validate the state-pair contract from Stage 2B.

validateattributes(previousState, {'numeric'}, {'2d', 'real', 'finite'}, ...
    mfilename, "previousState");
validateattributes(nextState, {'numeric'}, {'2d', 'real', 'finite'}, ...
    mfilename, "nextState");
validateattributes(dtSeconds, {'numeric'}, {'column', 'real', 'finite', 'positive'}, ...
    mfilename, "dtSeconds");

if size(previousState, 2) ~= 6 || size(nextState, 2) ~= 6
    error("Stage2C:InvalidStateWidth", ...
        "previousState and nextState must both use six columns in [x, vx, y, vy, z, vz] order.");
end

if size(previousState, 1) ~= size(nextState, 1) || size(previousState, 1) ~= numel(dtSeconds)
    error("Stage2C:StatePairSizeMismatch", ...
        "previousState, nextState, and dtSeconds must describe the same number of state pairs.");
end

end

function countsTable = localCountCategories(values, variableName)
%LOCALCOUNTCATEGORIES Count every categorical level, including empty levels.

categoryNames = string(categories(values));
pairCount = countcats(values);

if sum(pairCount) == 0
    percent = zeros(size(pairCount));
else
    percent = 100 .* pairCount ./ sum(pairCount);
end

countsTable = table( ...
    categoryNames(:), ...
    pairCount(:), ...
    percent(:), ...
    'VariableNames', [variableName, "pairCount", "percent"]);

end
