function output = helperPlotStage4ERecursiveEvaluation(results, varargin)
%HELPERPLOTSTAGE4ERECURSIVEEVALUATION Plot recursive filter evidence.
% The four panels compare motion-specific synthetic errors, held-out ADS-B
% proxy errors, coasting behavior, and measured execution time.

parser = inputParser;
parser.FunctionName = mfilename;
addRequired(parser, "results");
addParameter(parser, "SavePath", "");
parse(parser, results, varargin{:});

savePath = strtrim(string(parser.Results.SavePath));
localValidateResults(results);
modelOrder = [ ...
    "cv_ekf"; ...
    "ca_ekf"; ...
    "ct_ekf"; ...
    "native_imm"; ...
    "warm_ukf"];
displayNames = [ ...
    "CV EKF"; ...
    "CA EKF"; ...
    "CT EKF"; ...
    "CV/CA/CT IMM"; ...
    "Frozen-warm UKF"];
colors = [ ...
    0.0000, 0.4470, 0.7410; ...
    0.8500, 0.3250, 0.0980; ...
    0.9290, 0.6940, 0.1250; ...
    0.4940, 0.1840, 0.5560; ...
    0.4660, 0.6740, 0.1880];

[canonicalValues, canonicalLabels] = ...
    localCanonicalValues(results.eventMetricTable, modelOrder);
[realValues, realLabels] = ...
    localRealValues(results.metricTable, modelOrder);
[outageValues, outageLabels] = ...
    localOutageValues(results.outageAgeMetricTable, modelOrder);
runtimeValues = localRuntimeValues(results.runtimeTable, modelOrder);

figureHandle = figure( ...
    Name="Stage 4E Recursive Filter Evaluation", ...
    Color="w", ...
    Position=[100, 100, 1450, 820]);
tiledlayout( ...
    figureHandle, ...
    2, ...
    2, ...
    TileSpacing="compact", ...
    Padding="compact");

canonicalAxes = nexttile;
canonicalBars = bar( ...
    categorical(canonicalLabels, canonicalLabels), ...
    canonicalValues);
localApplyModelColors(canonicalBars, colors);
grid on
ylabel("Posterior position RMSE (m)")
title("Synthetic motion cases")
xtickangle(24)
localStyleAxes(canonicalAxes);
motionLegend = legend(displayNames, Location="northwest");
motionLegend.Color = "w";
motionLegend.TextColor = "k";

realAxes = nexttile;
realBars = bar(categorical(realLabels, realLabels), realValues);
localApplyModelColors(realBars, colors);
grid on
ylabel("Posterior position RMSE (m)")
title("Held-out ADS-B scoring proxy")
xtickangle(20)
localStyleAxes(realAxes);

outageAxes = nexttile;
hold on
for modelIdx = 1:numel(modelOrder)
    plot( ...
        1:numel(outageLabels), ...
        outageValues(:, modelIdx), ...
        "-o", ...
        Color=colors(modelIdx, :), ...
        LineWidth=1.4, ...
        MarkerSize=4, ...
        DisplayName=displayNames(modelIdx));
end
hold off
grid on
xticks(1:numel(outageLabels))
xticklabels(outageLabels)
xtickangle(20)
xlabel("Time since last position update")
ylabel("Position RMSE (m)")
title("Burst-outage coasting")
localStyleAxes(outageAxes);

runtimeAxes = nexttile;
bar(categorical(displayNames, displayNames), runtimeValues, ...
    FaceColor="flat")
runtimeAxes.Children.CData = colors;
grid on
ylabel("Runtime per prediction (\mus)")
title("Measured recursive runtime")
xtickangle(22)
localStyleAxes(runtimeAxes);

sgtitle( ...
    "Stage 4E: recursively predicted and position-corrected filters", ...
    Color="k");

if strlength(savePath) > 0
    saveFolder = string(fileparts(savePath));

    if strlength(saveFolder) > 0 && ~isfolder(saveFolder)
        mkdir(saveFolder);
    end

    exportgraphics(figureHandle, savePath, Resolution=160);
end

output = struct();
output.figure = figureHandle;
output.savePath = savePath;
output.modelIDs = modelOrder;
output.canonicalPositionRMSE = canonicalValues;
output.realPositionRMSE = realValues;
output.outagePositionRMSE = outageValues;
output.runtimeMicrosecondsPerPrediction = runtimeValues;

end

function localApplyModelColors(barHandles, colors)
%LOCALAPPLYMODELCOLORS Keep model colors consistent across grouped bars.

for modelIdx = 1:numel(barHandles)
    barHandles(modelIdx).FaceColor = colors(modelIdx, :);
end

end

function localStyleAxes(axesHandle)
%LOCALSTYLEAXES Make exported axes independent of the MATLAB theme.

axesHandle.Color = "w";
axesHandle.XColor = "k";
axesHandle.YColor = "k";
axesHandle.GridColor = [0.75, 0.75, 0.75];
axesHandle.Title.Color = "k";
axesHandle.XLabel.Color = "k";
axesHandle.YLabel.Color = "k";

end

function [values, labels] = localCanonicalValues(eventMetrics, modelOrder)
%LOCALCANONICALVALUES Arrange degraded canonical event metrics.

scenarioOrder = [ ...
    "cv_level"; ...
    "cv_climb"; ...
    "horizontal_acceleration"; ...
    "vertical_acceleration"; ...
    "left_turn"; ...
    "right_turn"; ...
    "motion_transitions"];
labels = [ ...
    "Level CV"; ...
    "Climbing CV"; ...
    "Horizontal accel."; ...
    "Vertical accel."; ...
    "Left turn"; ...
    "Right turn"; ...
    "Transitions"];
rows = eventMetrics( ...
    eventMetrics.domain == "synthetic_canonical" & ...
    eventMetrics.profile == "degraded" & ...
    eventMetrics.estimateStage == "posterior", :);
values = NaN(numel(scenarioOrder), numel(modelOrder));

for scenarioIdx = 1:numel(scenarioOrder)
    for modelIdx = 1:numel(modelOrder)
        rowMask = ...
            rows.motionScenario == scenarioOrder(scenarioIdx) & ...
            rows.modelID == modelOrder(modelIdx);
        values(scenarioIdx, modelIdx) = ...
            mean(rows.positionRMSEMeters(rowMask), "omitnan");
    end
end

end

function [values, labels] = localRealValues(metricTable, modelOrder)
%LOCALREALVALUES Arrange aggregate real-data proxy metrics.

profileOrder = [ ...
    "baseline"; ...
    "random_dropout_10"; ...
    "random_dropout_25"; ...
    "burst_outage"];
labels = [ ...
    "Baseline"; ...
    "10% dropout"; ...
    "25% dropout"; ...
    "Burst outage"];
rows = metricTable( ...
    metricTable.domain == "real_adsb" & ...
    metricTable.estimateStage == "posterior", :);
values = NaN(numel(profileOrder), numel(modelOrder));

for profileIdx = 1:numel(profileOrder)
    for modelIdx = 1:numel(modelOrder)
        rowMask = ...
            rows.profile == profileOrder(profileIdx) & ...
            rows.modelID == modelOrder(modelIdx);
        values(profileIdx, modelIdx) = ...
            mean(rows.positionRMSEMeters(rowMask), "omitnan");
    end
end

end

function [values, labels] = localOutageValues(outageTable, modelOrder)
%LOCALOUTAGEVALUES Pool burst-outage errors by correction age.

binOrder = [ ...
    "corrected_now"; ...
    "0_to_5_s"; ...
    "5_to_15_s"; ...
    "15_to_30_s"; ...
    "over_30_s"];
labels = [ ...
    "Updated"; ...
    "0-5 s"; ...
    "5-15 s"; ...
    "15-30 s"; ...
    ">30 s"];
rows = outageTable( ...
    outageTable.domain == "real_adsb" & ...
    outageTable.profile == "burst_outage" & ...
    outageTable.estimateStage == "posterior", :);
values = NaN(numel(binOrder), numel(modelOrder));

for binIdx = 1:numel(binOrder)
    for modelIdx = 1:numel(modelOrder)
        rowMask = ...
            rows.outageAgeBin == binOrder(binIdx) & ...
            rows.modelID == modelOrder(modelIdx);
        values(binIdx, modelIdx) = localPooledRMSE( ...
            rows.positionRMSEMeters(rowMask), ...
            rows.sampleCount(rowMask));
    end
end

end

function values = localRuntimeValues(runtimeTable, modelOrder)
%LOCALRUNTIMEVALUES Pool elapsed time across every benchmark condition.

values = NaN(numel(modelOrder), 1);

for modelIdx = 1:numel(modelOrder)
    rowMask = runtimeTable.modelID == modelOrder(modelIdx);
    elapsedSeconds = sum(runtimeTable.elapsedSeconds(rowMask), "omitnan");
    predictionCount = sum(runtimeTable.predictionCount(rowMask), "omitnan");
    values(modelIdx) = 1e6*elapsedSeconds/max(1, predictionCount);
end

end

function value = localPooledRMSE(rmseValues, sampleCounts)
%LOCALPOOLEDRMSE Reconstruct a sample-weighted RMSE from grouped rows.

validRows = ...
    isfinite(rmseValues) & ...
    isfinite(sampleCounts) & ...
    sampleCounts > 0;

if any(validRows)
    value = sqrt(sum( ...
        sampleCounts(validRows).*rmseValues(validRows).^2) / ...
        sum(sampleCounts(validRows)));
else
    value = NaN;
end

end

function localValidateResults(results)
%LOCALVALIDATERESULTS Require the recursive result tables used by the plot.

requiredFields = [ ...
    "eventMetricTable"; ...
    "metricTable"; ...
    "outageAgeMetricTable"; ...
    "runtimeTable"];

if ~isstruct(results) || ...
        any(~isfield(results, requiredFields)) || ...
        isempty(results.eventMetricTable) || ...
        isempty(results.metricTable) || ...
        isempty(results.outageAgeMetricTable) || ...
        isempty(results.runtimeTable)
    error("Stage4E:InvalidPlotResults", ...
        "Stage 4E result tables are required to create the summary plot.");
end

end
