function output = helperOpenStage4DGlobe(review)
%HELPEROPENSTAGE4DGLOBE Open one interactive Stage 4D globe collection.

localValidateReview(review);
colors = struct();
colors.input = [0.4000, 0.4000, 0.4000];
colors.reference = [0.0000, 0.6500, 0.2500];
colors.warm = [0.4940, 0.1840, 0.5560];
colors.constvel = [0.0000, 0.3000, 1.0000];
colors.constacc = [0.9290, 0.6940, 0.1250];
colors.constturn = [0.0000, 0.7500, 0.7500];
viewer = trackingGlobeViewer( ...
    ReferenceLocation=review.receiverOriginLLA, ...
    PlatformHistoryDepth=10000, ...
    TrackHistoryDepth=10000);

% Draw inputs first and the scoring reference last. This keeps the
% reference visible where one-step paths overlap.
plotTrajectory( ...
    viewer, ...
    review.trajectories.input, ...
    Color=colors.input, ...
    LineWidth=int32(2));
plotTrajectory( ...
    viewer, ...
    review.trajectories.warm, ...
    Color=colors.warm, ...
    LineWidth=int32(2));
plotTrajectory( ...
    viewer, ...
    review.trajectories.constacc, ...
    Color=colors.constacc, ...
    LineWidth=int32(2));
plotTrajectory( ...
    viewer, ...
    review.trajectories.constturn, ...
    Color=colors.constturn, ...
    LineWidth=int32(2));
plotTrajectory( ...
    viewer, ...
    review.trajectories.constvel, ...
    Color=colors.constvel, ...
    LineWidth=int32(3));
plotTrajectory( ...
    viewer, ...
    review.trajectories.reference, ...
    Color=colors.reference, ...
    LineWidth=int32(4));

output = struct();
output.viewer = viewer;
output.label = review.label;
output.summaryTable = review.summaryTable;
output.legendTable = review.legendTable;
output.validationTable = review.validationTable;
output.colors = colors;
output.trajectoryCount = review.summaryTable.trajectoryCount;
output.trajectoryPathCount = review.summaryTable.trajectoryPathCount;
output.plotCallCount = 6;

end

function localValidateReview(review)
%LOCALVALIDATEREVIEW Require the complete Stage 4D globe contract.

requiredFields = [ ...
    "receiverOriginLLA"; ...
    "trajectories"; ...
    "summaryTable"; ...
    "legendTable"; ...
    "validationTable"; ...
    "label"];

if ~isstruct(review) || any(~isfield(review, requiredFields))
    error("Stage4DGlobe:InvalidReview", ...
        "The Stage 4D globe review is missing required fields.");
end

requiredTrajectoryFields = [ ...
    "input"; ...
    "reference"; ...
    "warm"; ...
    "constvel"; ...
    "constacc"; ...
    "constturn"];

if any(~isfield(review.trajectories, requiredTrajectoryFields))
    error("Stage4DGlobe:InvalidTrajectories", ...
        "The Stage 4D globe review must contain all six path families.");
end

end
