function outputPath = helperWriteStage4CNativeManeuverFigure( ...
        outputPath, metricTable)
%HELPERWRITESTAGE4CNATIVEMANEUVERFIGURE Plot both matched maneuver slices.
% The four tiles keep position and velocity scales separate while showing
% validation and test results for the respective constacc and constturn
% comparisons in one compact artifact.

outputPath = string(outputPath);
outputFolder = fileparts(outputPath);

if strlength(outputFolder) > 0 && ~isfolder(outputFolder)
    mkdir(outputFolder);
end

requiredVariables = [ ...
    "modelID", ...
    "split", ...
    "groupDimension", ...
    "groupName", ...
    "weighting", ...
    "positionRMSEMeters", ...
    "velocityRMSEMetersPerSecond"];

if any(~ismember(requiredVariables, ...
        string(metricTable.Properties.VariableNames)))
    error("Stage4CNative:InvalidFigureMetrics", ...
        "The maneuver figure requires the Stage 4C metric-table schema.");
end

pairMask = ...
    (metricTable.groupDimension == "native_maneuver_baseline") & ...
    (metricTable.weighting == "pair_weighted");
pairMetrics = metricTable(pairMask, :);

if height(pairMetrics) ~= 20
    error("Stage4CNative:IncompleteFigureMetrics", ...
        "Expected 20 pair-weighted rows across two slices and splits.");
end

figureHandle = figure("Visible", "off");
cleanup = onCleanup(@() close(figureHandle));
layout = tiledlayout(figureHandle, 2, 2, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");
title(layout, "Stage 4C native maneuver baselines on matched eligible rows");

localPlotMetric( ...
    nexttile(layout), ...
    pairMetrics, ...
    "constacc_like", ...
    "positionRMSEMeters", ...
    "Constacc-like: position", ...
    "Position RMSE (m)", ...
    true);
localPlotMetric( ...
    nexttile(layout), ...
    pairMetrics, ...
    "constacc_like", ...
    "velocityRMSEMetersPerSecond", ...
    "Constacc-like: velocity", ...
    "Velocity RMSE (m/s)", ...
    false);
localPlotMetric( ...
    nexttile(layout), ...
    pairMetrics, ...
    "constturn_like", ...
    "positionRMSEMeters", ...
    "Constturn-like: position", ...
    "Position RMSE (m)", ...
    false);
localPlotMetric( ...
    nexttile(layout), ...
    pairMetrics, ...
    "constturn_like", ...
    "velocityRMSEMetersPerSecond", ...
    "Constturn-like: velocity", ...
    "Velocity RMSE (m/s)", ...
    false);

exportgraphics(figureHandle, outputPath, "Resolution", 160);

end

function localPlotMetric( ...
        axisHandle, ...
        metricTable, ...
        sliceName, ...
        metricVariable, ...
        plotTitle, ...
        yLabel, ...
        showLegend)
%LOCALPLOTMETRIC Draw validation/test bars in a stable model order.

section = metricTable(metricTable.groupName == sliceName, :);

if sliceName == "constacc_like"
    modelOrder = [ ...
        "constacc"; ...
        "constvel"; ...
        "legacy_stage3a_v1"; ...
        "expanded_scratch_mean_v1"; ...
        "expanded_warm_mean_v1"];
else
    modelOrder = [ ...
        "constturn"; ...
        "constvel"; ...
        "legacy_stage3a_v1"; ...
        "expanded_scratch_mean_v1"; ...
        "expanded_warm_mean_v1"];
end

values = NaN(numel(modelOrder), 2);
splitNames = ["validation", "test"];

for modelIdx = 1:numel(modelOrder)
    for splitIdx = 1:numel(splitNames)
        rowMask = ...
            (section.modelID == modelOrder(modelIdx)) & ...
            (section.split == splitNames(splitIdx));
        values(modelIdx, splitIdx) = section.(metricVariable)(rowMask);
    end
end

hold(axisHandle, "on");
plot( ...
    axisHandle, ...
    1:numel(modelOrder), ...
    values(:, 1), ...
    "o-", ...
    "LineWidth", ...
    1.4, ...
    "MarkerSize", ...
    5, ...
    "DisplayName", ...
    "validation");
plot( ...
    axisHandle, ...
    1:numel(modelOrder), ...
    values(:, 2), ...
    "s-", ...
    "LineWidth", ...
    1.4, ...
    "MarkerSize", ...
    5, ...
    "DisplayName", ...
    "test");
set(axisHandle, "YScale", "log");
grid(axisHandle, "on");
axisHandle.XTick = 1:numel(modelOrder);
axisHandle.XTickLabel = localDisplayNames(modelOrder);
axisHandle.XTickLabelRotation = 22;
ylabel(axisHandle, yLabel);
title(axisHandle, plotTitle);

if showLegend
    legend(axisHandle, splitNames, "Location", "best");
end

hold(axisHandle, "off");

end

function names = localDisplayNames(modelIDs)
%LOCALDISPLAYNAMES Keep long artifact identities readable on one figure.

names = strings(size(modelIDs));
names(modelIDs == "constacc") = "constacc";
names(modelIDs == "constturn") = "constturn";
names(modelIDs == "constvel") = "constvel";
names(modelIDs == "legacy_stage3a_v1") = "legacy";
names(modelIDs == "expanded_scratch_mean_v1") = "scratch";
names(modelIDs == "expanded_warm_mean_v1") = "warm";

end
