function metrics = helperScoreStage4CMeanModels( ...
        nextState, modelPredictions, metadata, maneuverPairTable, split)
%HELPERSCORESTAGE4CMEANMODELS Score identical held-out rows by key regimes.
% Pair-weighted metrics describe the error seen by a randomly selected
% state pair. Independent-event-weighted metrics give every contiguous
% trajectory/regime segment equal total weight so long events cannot
% dominate the result merely because they contain more updates.

nextState = double(nextState);
split = string(split(:));
localValidateInputs( ...
    nextState, ...
    modelPredictions, ...
    metadata, ...
    maneuverPairTable, ...
    split);

splitNames = ["validation", "test"];
groupDefinitions = localBuildGroupDefinitions(maneuverPairTable);
metricTable = table();

for splitIdx = 1:numel(splitNames)
    splitName = splitNames(splitIdx);

    for definitionIdx = 1:numel(groupDefinitions)
        definition = groupDefinitions(definitionIdx);
        groupNames = unique(definition.values(split == splitName), "stable");

        for groupIdx = 1:numel(groupNames)
            groupName = groupNames(groupIdx);
            rowMask = split == splitName & definition.values == groupName;
            [eventWeights, eventCount] = localIndependentEventWeights( ...
                metadata(rowMask, :));
            pairWeights = ones(sum(rowMask), 1);

            for modelIdx = 1:numel(modelPredictions)
                model = modelPredictions(modelIdx);
                predictedState = double(model.predictedNextState(rowMask, :));
                trueState = nextState(rowMask, :);
                positionError = vecnorm( ...
                    predictedState(:, [1, 3, 5]) - ...
                    trueState(:, [1, 3, 5]), ...
                    2, ...
                    2);
                velocityError = vecnorm( ...
                    predictedState(:, [2, 4, 6]) - ...
                    trueState(:, [2, 4, 6]), ...
                    2, ...
                    2);

                pairRow = localMetricRow( ...
                    model.modelID, ...
                    splitName, ...
                    definition.dimension, ...
                    groupName, ...
                    "pair_weighted", ...
                    positionError, ...
                    velocityError, ...
                    pairWeights, ...
                    eventCount);
                eventRow = localMetricRow( ...
                    model.modelID, ...
                    splitName, ...
                    definition.dimension, ...
                    groupName, ...
                    "independent_event_weighted", ...
                    positionError, ...
                    velocityError, ...
                    eventWeights, ...
                    eventCount);
                metricTable = [metricTable; pairRow; eventRow]; %#ok<AGROW>
            end
        end
    end
end

metrics = struct();
metrics.table = metricTable;
metrics.eventDefinition = ...
    "A contiguous run within one session/ICAO track and one reported regime.";
metrics.pairWeightDefinition = "Every held-out state pair has weight one.";
metrics.eventWeightDefinition = ...
    "Each row has reciprocal event-length weight, so every event has total weight one.";
metrics.scoredSplits = splitNames;

end

function definitions = localBuildGroupDefinitions(maneuverPairTable)
%LOCALBUILDGROUPDEFINITIONS Define the required evaluation slices.

sampleCount = height(maneuverPairTable);
definitions = struct( ...
    "dimension", ...
    { ...
        "all", ...
        "maneuver_class", ...
        "vertical_status", ...
        "update_regime"}, ...
    "values", ...
    { ...
        repmat("all", sampleCount, 1), ...
        string(maneuverPairTable.maneuverClass), ...
        string(maneuverPairTable.verticalStatus), ...
        string(maneuverPairTable.dtRegime)});

end

function localValidateInputs( ...
        nextState, modelPredictions, metadata, maneuverPairTable, split)
%LOCALVALIDATEINPUTS Enforce one shared holdout row universe.

sampleCount = size(nextState, 1);

validateattributes(nextState, ...
    {'numeric'}, {'2d', 'real', 'finite'}, mfilename, "nextState");

if size(nextState, 2) ~= 6 || ...
        height(metadata) ~= sampleCount || ...
        height(maneuverPairTable) ~= sampleCount || ...
        numel(split) ~= sampleCount
    error("Stage4C:MetricInputSizeMismatch", ...
        "Metric inputs must describe identical N-by-6 held-out state rows.");
end

requiredMetadata = ["sessionID", "hex", "timeUtcK", "timeUtcNext"];

if any(~ismember(requiredMetadata, string(metadata.Properties.VariableNames)))
    error("Stage4C:MissingMetricMetadata", ...
        "Metadata must include sessionID, hex, timeUtcK, and timeUtcNext.");
end

requiredLabels = ["maneuverClass", "verticalStatus", "dtRegime"];

if any(~ismember(requiredLabels, ...
        string(maneuverPairTable.Properties.VariableNames)))
    error("Stage4C:MissingMetricLabels", ...
        "Maneuver labels must include maneuverClass, verticalStatus, and dtRegime.");
end

if isempty(modelPredictions) || ...
        ~isstruct(modelPredictions) || ...
        any(~isfield(modelPredictions, ["modelID", "predictedNextState"]))
    error("Stage4C:InvalidModelPredictions", ...
        "modelPredictions must contain modelID and predictedNextState.");
end

modelIDs = strings(numel(modelPredictions), 1);

for modelIdx = 1:numel(modelPredictions)
    modelIDs(modelIdx) = string(modelPredictions(modelIdx).modelID);
    prediction = modelPredictions(modelIdx).predictedNextState;

    if ~isnumeric(prediction) || ...
            ~isequal(size(prediction), size(nextState)) || ...
            any(~isfinite(prediction), "all")
        error("Stage4C:InvalidModelPredictionArray", ...
            "Every model prediction must be a finite N-by-6 numeric array.");
    end
end

if numel(unique(modelIDs)) ~= numel(modelIDs)
    error("Stage4C:DuplicateModelIdentity", ...
        "Every scored model must have a distinct identity.");
end

if any(~ismember(split, ["validation", "test"]))
    error("Stage4C:TrainingRowsInMetrics", ...
        "Stage 4C comparison metrics accept validation and test rows only.");
end

end

function [weights, eventCount] = localIndependentEventWeights(metadata)
%LOCALINDEPENDENTEVENTWEIGHTS Give each contiguous track segment unit mass.

rowCount = height(metadata);

if rowCount == 0
    weights = zeros(0, 1);
    eventCount = 0;
    return;
end

rowIndex = (1:rowCount).';
orderingTable = table( ...
    string(metadata.sessionID), ...
    string(metadata.hex), ...
    metadata.timeUtcK, ...
    rowIndex, ...
    'VariableNames', ["sessionID", "hex", "timeUtcK", "rowIndex"]);
orderingTable = sortrows( ...
    orderingTable, ...
    ["sessionID", "hex", "timeUtcK", "rowIndex"]);
orderedRows = orderingTable.rowIndex;
sessionID = string(metadata.sessionID(orderedRows));
hex = string(metadata.hex(orderedRows));
timeUtcK = metadata.timeUtcK(orderedRows);
timeUtcNext = metadata.timeUtcNext(orderedRows);

newEvent = true(rowCount, 1);

if rowCount > 1
    sameTrack = sessionID(2:end) == sessionID(1:end - 1) & ...
        hex(2:end) == hex(1:end - 1);
    adjacentPair = abs(seconds( ...
        timeUtcK(2:end) - timeUtcNext(1:end - 1))) <= 1e-6;
    newEvent(2:end) = ~(sameTrack & adjacentPair);
end

eventID = cumsum(newEvent);
eventCount = eventID(end);
eventLength = accumarray(eventID, 1, [eventCount, 1]);
orderedWeights = 1 ./ eventLength(eventID);
weights = zeros(rowCount, 1);
weights(orderedRows) = orderedWeights;

end

function metricRow = localMetricRow( ...
        modelID, ...
        splitName, ...
        groupDimension, ...
        groupName, ...
        weighting, ...
        positionError, ...
        velocityError, ...
        weights, ...
        eventCount)
%LOCALMETRICROW Build one compact physical-unit metric row.

sampleCount = numel(positionError);
positionRMSEMeters = localWeightedRMSE(positionError, weights);
velocityRMSEMetersPerSecond = localWeightedRMSE(velocityError, weights);
positionMedianErrorMeters = localWeightedQuantile( ...
    positionError, weights, 0.50);
velocityMedianErrorMetersPerSecond = localWeightedQuantile( ...
    velocityError, weights, 0.50);
positionP95ErrorMeters = localWeightedQuantile( ...
    positionError, weights, 0.95);
velocityP95ErrorMetersPerSecond = localWeightedQuantile( ...
    velocityError, weights, 0.95);

metricRow = table( ...
    string(modelID), ...
    string(splitName), ...
    string(groupDimension), ...
    string(groupName), ...
    string(weighting), ...
    sampleCount, ...
    eventCount, ...
    positionRMSEMeters, ...
    velocityRMSEMetersPerSecond, ...
    positionMedianErrorMeters, ...
    velocityMedianErrorMetersPerSecond, ...
    positionP95ErrorMeters, ...
    velocityP95ErrorMetersPerSecond, ...
    'VariableNames', [ ...
        "modelID", ...
        "split", ...
        "groupDimension", ...
        "groupName", ...
        "weighting", ...
        "sampleCount", ...
        "eventCount", ...
        "positionRMSEMeters", ...
        "velocityRMSEMetersPerSecond", ...
        "positionMedianErrorMeters", ...
        "velocityMedianErrorMetersPerSecond", ...
        "positionP95ErrorMeters", ...
        "velocityP95ErrorMetersPerSecond"]);

end

function value = localWeightedRMSE(errors, weights)
%LOCALWEIGHTEDRMSE Compute weighted root mean square error.

finiteMask = isfinite(errors) & isfinite(weights) & weights > 0;
errors = errors(finiteMask);
weights = weights(finiteMask);

if isempty(errors)
    value = NaN;
    return;
end

value = sqrt(sum(weights .* errors .^ 2) / sum(weights));

end

function value = localWeightedQuantile(values, weights, probability)
%LOCALWEIGHTEDQUANTILE Return the left-continuous weighted quantile.

finiteMask = isfinite(values) & isfinite(weights) & weights > 0;
values = values(finiteMask);
weights = weights(finiteMask);

if isempty(values)
    value = NaN;
    return;
end

[values, order] = sort(values);
weights = weights(order);
cumulativeWeight = cumsum(weights);
threshold = probability * cumulativeWeight(end);
quantileIndex = find(cumulativeWeight >= threshold, 1, "first");
value = values(quantileIndex);

end
