function review = helperBuildStage4DGlobeReview(results, varargin)
%HELPERBUILDSTAGE4DGLOBEREVIEW Build interactive Stage 4D trajectory paths.
% Synthetic views use latent kinematic truth as the scoring reference.
% Real views use the next retained ADS-B observation as the reference.

projectRoot = string(fileparts(mfilename("fullpath")));
parser = inputParser;
parser.FunctionName = mfilename;
addRequired(parser, "results", @isstruct);
addParameter(parser, "ProjectRoot", projectRoot);
addParameter(parser, "ViewType", "canonical");
addParameter(parser, "ObservationProfile", "");
addParameter(parser, "MotionScenarios", [ ...
    "cv_level"; ...
    "cv_climb"; ...
    "horizontal_acceleration"; ...
    "vertical_acceleration"; ...
    "left_turn"; ...
    "right_turn"; ...
    "motion_transitions"]);
addParameter(parser, "RealEventRank", 1);
addParameter(parser, "PredictionMiniBatchSize", 8192);
parse(parser, results, varargin{:});

projectRoot = localCanonicalPath(localTextScalar( ...
    parser.Results.ProjectRoot, ...
    "ProjectRoot", ...
    false));
viewType = lower(localTextScalar( ...
    parser.Results.ViewType, ...
    "ViewType", ...
    false));
observationProfile = lower(localTextScalar( ...
    parser.Results.ObservationProfile, ...
    "ObservationProfile", ...
    true));
motionScenarios = string(parser.Results.MotionScenarios(:));
realEventRank = localPositiveInteger( ...
    parser.Results.RealEventRank, ...
    "RealEventRank");
miniBatchSize = localPositiveInteger( ...
    parser.Results.PredictionMiniBatchSize, ...
    "PredictionMiniBatchSize");
localValidateResults(results);

paths = localFrozenPaths(projectRoot);
[dataset, split] = localLoadDatasetAndSplit(paths);
warmModel = localLoadWarmModel(paths.warmArtifact, results);
trainMask = split == "train";
empiricalDtSeconds = dataset.dtSeconds(trainMask);
previousCovarianceDiag = median( ...
    dataset.previousCovarianceDiag(trainMask, :), ...
    1);

if viewType == "canonical"
    if strlength(observationProfile) == 0
        observationProfile = "degraded";
    end

    benchmark = helperGenerateStage4DSyntheticBenchmark( ...
        "canonical", ...
        BenchmarkMode=results.benchmarkMode, ...
        Seed=results.randomSeed, ...
        EmpiricalDtSeconds=empiricalDtSeconds, ...
        PreviousCovarianceDiag=previousCovarianceDiag);
    pairSet = localSelectCanonicalPairs( ...
        benchmark.pairSet, ...
        motionScenarios, ...
        observationProfile);
    receiverOriginLLA = [42.2999333, -71.349333, 15.0];
    referenceDisplayName = "Latent kinematic truth";
    inputDisplayName = "Observed input state";
    viewLabel = "Canonical " + observationProfile + ...
        " motion collection";
else
    if viewType ~= "real_adsb"
        error("Stage4DGlobe:UnknownViewType", ...
            "ViewType must be canonical or real_adsb.");
    end

    if strlength(observationProfile) == 0
        observationProfile = "burst_outage";
    end

    benchmark = helperBuildStage4DRealDropoutBenchmark( ...
        dataset, ...
        split, ...
        BenchmarkMode="smoke", ...
        Seed=results.randomSeed, ...
        PreviousCovarianceDiag=previousCovarianceDiag);
    [pairSet, receiverOriginLLA] = localSelectRealPairs( ...
        benchmark.pairSet, ...
        observationProfile, ...
        realEventRank);
    referenceDisplayName = "Next retained ADS-B observation";
    inputDisplayName = "Retained ADS-B input";
    viewLabel = "Held-out ADS-B event " + realEventRank + ...
        " / " + observationProfile;
end

evaluation = helperEvaluateStage4DPredictors( ...
    pairSet, ...
    warmModel, ...
    PredictionMiniBatchSize=miniBatchSize, ...
    RetainPredictions=true);
review = localBuildTrajectoryReview( ...
    pairSet, ...
    evaluation, ...
    receiverOriginLLA, ...
    viewType, ...
    observationProfile, ...
    referenceDisplayName, ...
    inputDisplayName, ...
    viewLabel);

end

function pairSet = localSelectCanonicalPairs( ...
        pairSet, motionScenarios, observationProfile)
%LOCALSELECTCANONICALPAIRS Keep one requested profile for each motion.

supportedScenarios = unique(pairSet.motionScenario, "stable");
supportedProfiles = unique(pairSet.profile, "stable");

if isempty(motionScenarios) || ...
        any(~ismember(motionScenarios, supportedScenarios))
    error("Stage4DGlobe:UnknownMotionScenario", ...
        "MotionScenarios must be selected from: %s.", ...
        strjoin(supportedScenarios, ", "));
end

if ~ismember(observationProfile, supportedProfiles)
    error("Stage4DGlobe:UnknownObservationProfile", ...
        "Canonical ObservationProfile must be selected from: %s.", ...
        strjoin(supportedProfiles, ", "));
end

rowMask = ...
    pairSet.profile == observationProfile & ...
    ismember(pairSet.motionScenario, motionScenarios);
pairSet = localSubsetPairSet(pairSet, rowMask);
selectedScenarios = unique(pairSet.motionScenario, "stable");

if numel(selectedScenarios) ~= numel(unique(motionScenarios))
    error("Stage4DGlobe:MissingCanonicalScenario", ...
        "Every requested canonical scenario must contribute one event.");
end

end

function [pairSet, receiverOriginLLA] = localSelectRealPairs( ...
        pairSet, observationProfile, realEventRank)
%LOCALSELECTREALPAIRS Select one ranked held-out event and dropout profile.

supportedProfiles = unique(pairSet.profile, "stable");

if ~ismember(observationProfile, supportedProfiles)
    error("Stage4DGlobe:UnknownObservationProfile", ...
        "Real ObservationProfile must be selected from: %s.", ...
        strjoin(supportedProfiles, ", "));
end

caseID = "real_event_" + compose("%05d", realEventRank) + ...
    "__" + observationProfile;
rowMask = pairSet.caseID == caseID;

if ~any(rowMask)
    maximumRank = numel(unique( ...
        pairSet.caseID(pairSet.profile == observationProfile)));
    error("Stage4DGlobe:RealEventRankUnavailable", ...
        "RealEventRank must not exceed %d for profile %s.", ...
        maximumRank, ...
        observationProfile);
end

pairSet = localSubsetPairSet(pairSet, rowMask);
receiverOriginLLA = pairSet.receiverOriginLLA(1, :);

end

function review = localBuildTrajectoryReview( ...
        pairSet, ...
        evaluation, ...
        receiverOriginLLA, ...
        viewType, ...
        observationProfile, ...
        referenceDisplayName, ...
        inputDisplayName, ...
        viewLabel)
%LOCALBUILDTRAJECTORYREVIEW Convert state paths into geoTrajectory objects.

eventIDs = unique(pairSet.eventID, "stable");
trajectoryCount = numel(eventIDs);
trajectoryFields = [ ...
    "input"; ...
    "reference"; ...
    "warm"; ...
    "constvel"; ...
    "constacc"; ...
    "constturn"];
statePaths = localEmptyPathStruct(trajectoryFields, trajectoryCount);
llaPaths = localEmptyPathStruct(trajectoryFields, trajectoryCount);
trajectories = localEmptyPathStruct(trajectoryFields, trajectoryCount);
eventRows = cell(trajectoryCount, 1);
validationRows = cell(trajectoryCount, 1);
prediction = evaluation.predictionReview;

for eventIdx = 1:trajectoryCount
    rowMask = pairSet.eventID == eventIDs(eventIdx);
    eventRows{eventIdx} = find(rowMask);
    eventStartSeconds = min(pairSet.timeKSeconds(rowMask));
    inputTime = pairSet.timeKSeconds(rowMask) - eventStartSeconds;
    targetTime = pairSet.timeNextSeconds(rowMask) - eventStartSeconds;
    causalMask = rowMask & prediction.causalEligibleMask;
    causalTime = pairSet.timeNextSeconds(causalMask) - eventStartSeconds;

    statePaths.input{eventIdx} = pairSet.previousState(rowMask, :);
    statePaths.reference{eventIdx} = pairSet.targetState(rowMask, :);
    statePaths.warm{eventIdx} = prediction.warm(rowMask, :);
    statePaths.constvel{eventIdx} = prediction.constvel(rowMask, :);
    statePaths.constacc{eventIdx} = prediction.constacc(causalMask, :);
    statePaths.constturn{eventIdx} = prediction.constturn(causalMask, :);

    llaPaths.input{eventIdx} = localStateToLLA( ...
        statePaths.input{eventIdx}, ...
        receiverOriginLLA);
    llaPaths.reference{eventIdx} = localStateToLLA( ...
        statePaths.reference{eventIdx}, ...
        receiverOriginLLA);
    llaPaths.warm{eventIdx} = localStateToLLA( ...
        statePaths.warm{eventIdx}, ...
        receiverOriginLLA);
    llaPaths.constvel{eventIdx} = localStateToLLA( ...
        statePaths.constvel{eventIdx}, ...
        receiverOriginLLA);
    llaPaths.constacc{eventIdx} = localStateToLLA( ...
        statePaths.constacc{eventIdx}, ...
        receiverOriginLLA);
    llaPaths.constturn{eventIdx} = localStateToLLA( ...
        statePaths.constturn{eventIdx}, ...
        receiverOriginLLA);

    trajectories.input{eventIdx} = geoTrajectory( ...
        llaPaths.input{eventIdx}, ...
        inputTime, ...
        ReferenceFrame="ENU");
    trajectories.reference{eventIdx} = geoTrajectory( ...
        llaPaths.reference{eventIdx}, ...
        targetTime, ...
        ReferenceFrame="ENU");
    trajectories.warm{eventIdx} = geoTrajectory( ...
        llaPaths.warm{eventIdx}, ...
        targetTime, ...
        ReferenceFrame="ENU");
    trajectories.constvel{eventIdx} = geoTrajectory( ...
        llaPaths.constvel{eventIdx}, ...
        targetTime, ...
        ReferenceFrame="ENU");
    trajectories.constacc{eventIdx} = geoTrajectory( ...
        llaPaths.constacc{eventIdx}, ...
        causalTime, ...
        ReferenceFrame="ENU");
    trajectories.constturn{eventIdx} = geoTrajectory( ...
        llaPaths.constturn{eventIdx}, ...
        causalTime, ...
        ReferenceFrame="ENU");

    finiteLLA = localAllFinite(llaPaths, eventIdx);
    monotonicTime = ...
        all(diff(inputTime) > 0) && ...
        all(diff(targetTime) > 0) && ...
        all(diff(causalTime) > 0);
    predictionCountMatches = ...
        size(statePaths.warm{eventIdx}, 1) == sum(rowMask) && ...
        size(statePaths.constvel{eventIdx}, 1) == sum(rowMask) && ...
        size(statePaths.constacc{eventIdx}, 1) == sum(causalMask) && ...
        size(statePaths.constturn{eventIdx}, 1) == sum(causalMask);
    validationRows{eventIdx} = table( ...
        eventIdx, ...
        string(pairSet.caseID(find(rowMask, 1))), ...
        string(pairSet.motionScenario(find(rowMask, 1))), ...
        sum(rowMask), ...
        sum(causalMask), ...
        finiteLLA, ...
        monotonicTime, ...
        predictionCountMatches, ...
        'VariableNames', [ ...
            "trajectoryRank", ...
            "caseID", ...
            "motionScenario", ...
            "sameInformationPairCount", ...
            "causalPairCount", ...
            "finiteLLA", ...
            "monotonicTime", ...
            "predictionCountMatches"]);
end

validationTable = vertcat(validationRows{:});

if ~all(validationTable{:, ...
        ["finiteLLA", "monotonicTime", "predictionCountMatches"]}, ...
        "all")
    error("Stage4DGlobe:InvalidTrajectoryReview", ...
        "A globe path failed timing, finite-LLA, or prediction-count checks.");
end

legendTable = table( ...
    trajectoryFields, ...
    [ ...
        inputDisplayName; ...
        referenceDisplayName; ...
        "Frozen warm"; ...
        "Native constvel"; ...
        "Causal constacc"; ...
        "Causal constturn"], ...
    ["gray"; "green"; "purple"; "blue"; "orange"; "cyan"], ...
    repmat(trajectoryCount, numel(trajectoryFields), 1), ...
    'VariableNames', ["pathID", "displayName", "color", "pathCount"]);
summaryTable = table( ...
    string(viewType), ...
    string(observationProfile), ...
    trajectoryCount, ...
    sum(validationTable.sameInformationPairCount), ...
    sum(validationTable.causalPairCount), ...
    numel(trajectoryFields)*trajectoryCount, ...
    string(referenceDisplayName), ...
    string(viewLabel), ...
    'VariableNames', [ ...
        "viewType", ...
        "observationProfile", ...
        "trajectoryCount", ...
        "sameInformationPairCount", ...
        "causalPairCount", ...
        "trajectoryPathCount", ...
        "scoringReference", ...
        "viewLabel"]);

review = struct();
review.viewType = string(viewType);
review.observationProfile = string(observationProfile);
review.label = string(viewLabel);
review.referenceDisplayName = string(referenceDisplayName);
review.inputDisplayName = string(inputDisplayName);
review.receiverOriginLLA = receiverOriginLLA;
review.eventRows = eventRows;
review.statePaths = statePaths;
review.llaPaths = llaPaths;
review.trajectories = trajectories;
review.legendTable = legendTable;
review.summaryTable = summaryTable;
review.validationTable = validationTable;
review.metricTable = evaluation.metricTable;
review.trainingPerformed = false;
review.modelPromoted = false;
review.recursiveForecast = false;
review.loadedModelID = "expanded_warm_mean_v1";

end

function pairSet = localSubsetPairSet(pairSet, rowMask)
%LOCALSUBSETPAIRSET Keep aligned pair fields while preserving the domain.

rowCount = size(pairSet.previousState, 1);
fields = string(fieldnames(pairSet));

for fieldIdx = 1:numel(fields)
    fieldName = fields(fieldIdx);
    value = pairSet.(fieldName);

    if ismatrix(value) && size(value, 1) == rowCount
        pairSet.(fieldName) = value(rowMask, :);
    end
end

end

function paths = localFrozenPaths(projectRoot)
%LOCALFROZENPATHS Resolve the only model and data inputs used.

paths = struct();
paths.warmArtifact = fullfile( ...
    projectRoot, ...
    "artifacts", ...
    "stage4CRetrain", ...
    "expandedPost3DayWarmStartMeanMLP_v1.mat");
paths.dataset = fullfile( ...
    projectRoot, ...
    "artifacts", ...
    "stage4BPostCampaign", ...
    "expanded_post3day_v2", ...
    "stage3CArchiveStatePairDataset.mat");
paths.splitManifest = fullfile( ...
    projectRoot, ...
    "adsb_archive", ...
    "datasetVersions", ...
    "expandedPost3DayICAODisjointSplit_v1.csv");

end

function [dataset, split] = localLoadDatasetAndSplit(paths)
%LOCALLOADDATASETANDSPLIT Load the frozen dataset and global ICAO split.

dataset = load( ...
    paths.dataset, ...
    "previousState", ...
    "nextState", ...
    "dtSeconds", ...
    "previousCovarianceDiag", ...
    "metadata");
manifest = readtable(paths.splitManifest, TextType="string");
[found, manifestRow] = ismember( ...
    lower(strtrim(string(dataset.metadata.hex))), ...
    lower(strtrim(string(manifest.icao24))));

if ~all(found)
    error("Stage4DGlobe:SplitMembershipMismatch", ...
        "Every dataset ICAO must occur in the frozen split manifest.");
end

split = lower(strtrim(string(manifest.split(manifestRow))));

end

function warmModel = localLoadWarmModel(warmArtifactPath, results)
%LOCALLOADWARMMODEL Hash-check and load only expanded_warm_mean_v1.

actualHash = helperComputeFileSHA256(warmArtifactPath);
hashRow = results.artifactAudit.check == "warm_model_hash_after";
expectedHash = results.artifactAudit.value(hashRow);

if sum(hashRow) ~= 1 || ~strcmpi(actualHash, expectedHash)
    error("Stage4DGlobe:WarmModelHashMismatch", ...
        "The frozen warm model hash differs from the Stage 4D result.");
end

loaded = load(warmArtifactPath, "net", "normalization", "modelArtifact");

if string(loaded.modelArtifact.modelID) ~= "expanded_warm_mean_v1"
    error("Stage4DGlobe:WarmModelIdentityMismatch", ...
        "The globe review requires expanded_warm_mean_v1.");
end

warmModel = struct();
warmModel.net = loaded.net;
warmModel.featureNormalization = loaded.normalization.features;
warmModel.targetNormalization = loaded.normalization.target;

end

function pathStruct = localEmptyPathStruct(fieldNames, trajectoryCount)
%LOCALEMPTYPATHSTRUCT Allocate one cell array per displayed path.

pathStruct = struct();

for fieldIdx = 1:numel(fieldNames)
    pathStruct.(fieldNames(fieldIdx)) = cell(trajectoryCount, 1);
end

end

function lla = localStateToLLA(state, receiverOriginLLA)
%LOCALSTATETOLLA Convert local ENU positions to WGS-84 geodetic values.

spheroid = wgs84Ellipsoid("meter");
[latitudeDegrees, longitudeDegrees, altitudeMeters] = enu2geodetic( ...
    state(:, 1), ...
    state(:, 3), ...
    state(:, 5), ...
    receiverOriginLLA(1), ...
    receiverOriginLLA(2), ...
    receiverOriginLLA(3), ...
    spheroid);
lla = [latitudeDegrees, longitudeDegrees, altitudeMeters];

end

function finiteLLA = localAllFinite(llaPaths, eventIdx)
%LOCALALLFINITE Check all displayed geodetic paths.

pathNames = string(fieldnames(llaPaths));
finiteLLA = true;

for pathIdx = 1:numel(pathNames)
    finiteLLA = finiteLLA && all(isfinite( ...
        llaPaths.(pathNames(pathIdx)){eventIdx}), ...
        "all");
end

end

function localValidateResults(results)
%LOCALVALIDATERESULTS Require a completed Stage 4D result contract.

requiredFields = [ ...
    "completed", ...
    "benchmarkMode", ...
    "randomSeed", ...
    "artifactAudit"];

if any(~isfield(results, requiredFields)) || ~results.completed
    error("Stage4DGlobe:InvalidResults", ...
        "A completed Stage 4D result is required.");
end

end

function value = localPositiveInteger(value, argumentName)
%LOCALPOSITIVEINTEGER Validate one positive finite integer.

if ~isnumeric(value) || ...
        ~isreal(value) || ...
        ~isscalar(value) || ...
        ~isfinite(value) || ...
        value < 1 || ...
        value ~= fix(value)
    error("Stage4DGlobe:InvalidPositiveInteger", ...
        "%s must be a positive finite integer scalar.", argumentName);
end

value = double(value);

end

function value = localTextScalar(value, argumentName, allowEmpty)
%LOCALTEXTSCALAR Normalize a text option.

isCharacterVector = ischar(value) && (isrow(value) || isempty(value));
isStringScalar = isstring(value) && isscalar(value);

if ~isCharacterVector && ~isStringScalar
    error("Stage4DGlobe:InvalidTextOption", ...
        "%s must be a character vector or string scalar.", argumentName);
end

value = strtrim(string(value));

if ismissing(value) || (~allowEmpty && strlength(value) == 0)
    error("Stage4DGlobe:InvalidTextOption", ...
        "%s must not be empty.", argumentName);
end

end

function canonicalPath = localCanonicalPath(pathValue)
%LOCALCANONICALPATH Normalize a path without requiring it to exist.

try
    canonicalPath = string(java.io.File(char(pathValue)).getCanonicalPath());
catch err
    error("Stage4DGlobe:PathResolutionFailed", ...
        "Unable to resolve path %s: %s", pathValue, err.message);
end

end
