function benchmark = helperGenerateStage4DSyntheticBenchmark(groupName, varargin)
%HELPERGENERATESTAGE4DSYNTHETICBENCHMARK Generate independent Stage 4D truth.
% Truth is generated with kinematicTrajectory on a uniform internal time
% grid. Observation profiles then sample and perturb that latent truth.

parser = inputParser;
parser.FunctionName = mfilename;
addRequired(parser, "groupName");
addParameter(parser, "BenchmarkMode", "smoke");
addParameter(parser, "Seed", 123);
addParameter(parser, "EmpiricalDtSeconds", 1);
addParameter(parser, "PreviousCovarianceDiag", [10000, 100, 10000, 100, 22500, 25]);
addParameter(parser, "TrajectoryCount", []);
addParameter(parser, "DurationSeconds", []);
addParameter(parser, "SampleRateHz", []);
parse(parser, groupName, varargin{:});

groupName = lower(strtrim(string(parser.Results.groupName)));
benchmarkMode = lower(strtrim(string(parser.Results.BenchmarkMode)));
seed = double(parser.Results.Seed);
empiricalDtSeconds = double(parser.Results.EmpiricalDtSeconds(:));
previousCovarianceDiag = double(parser.Results.PreviousCovarianceDiag(:).');
trajectoryCount = parser.Results.TrajectoryCount;
durationSeconds = parser.Results.DurationSeconds;
sampleRateHz = parser.Results.SampleRateHz;
localValidateInputs( ...
    groupName, ...
    benchmarkMode, ...
    seed, ...
    empiricalDtSeconds, ...
    previousCovarianceDiag, ...
    trajectoryCount, ...
    durationSeconds, ...
    sampleRateHz);

config = localBuildConfig( ...
    groupName, ...
    benchmarkMode, ...
    trajectoryCount, ...
    durationSeconds, ...
    sampleRateHz);
stream = RandStream("mt19937ar", "Seed", seed + config.seedOffset);
profileTable = localSyntheticProfileTable();

if groupName == "canonical"
    [pieces, truthAuditTable, caseTable] = localGenerateCanonical( ...
        config, ...
        profileTable, ...
        stream, ...
        empiricalDtSeconds, ...
        previousCovarianceDiag);
else
    [pieces, truthAuditTable, caseTable] = localGenerateMixed( ...
        config, ...
        profileTable, ...
        stream, ...
        empiricalDtSeconds, ...
        previousCovarianceDiag);
end

pairSet = localConcatenatePieces(pieces, groupName);
pairAudit = localAuditPairs(pairSet);

benchmark = struct();
benchmark.groupName = groupName;
benchmark.benchmarkMode = benchmarkMode;
benchmark.seed = seed + config.seedOffset;
benchmark.config = config;
benchmark.profileTable = profileTable;
benchmark.caseTable = caseTable;
benchmark.pairSet = pairSet;
benchmark.sequences = pieces;
benchmark.truthAuditTable = truthAuditTable;
benchmark.pairAudit = pairAudit;
benchmark.truthTrajectoryCount = config.truthTrajectoryCount;
benchmark.observedCaseCount = numel(pieces);

end

function config = localBuildConfig( ...
        groupName, benchmarkMode, trajectoryCount, durationSeconds, sampleRateHz)
%LOCALBUILDCONFIG Define smoke and full benchmark sizes.

config = struct();
config.sampleRateHz = 2;
config.groupName = groupName;

if benchmarkMode == "full"
    config.canonicalDurationSeconds = 240;
    config.mixedDurationSeconds = 600;
    config.inDistributionTrajectoryCount = 100;
    config.outOfDistributionTrajectoryCount = 50;
else
    config.canonicalDurationSeconds = 90;
    config.mixedDurationSeconds = 120;
    config.inDistributionTrajectoryCount = 4;
    config.outOfDistributionTrajectoryCount = 2;
end

switch groupName
    case "canonical"
        config.truthTrajectoryCount = 7;
        config.durationSeconds = config.canonicalDurationSeconds;
        config.seedOffset = 101;
    case "in_distribution"
        config.truthTrajectoryCount = config.inDistributionTrajectoryCount;
        config.durationSeconds = config.mixedDurationSeconds;
        config.seedOffset = 1001;
    case "out_of_distribution"
        config.truthTrajectoryCount = config.outOfDistributionTrajectoryCount;
        config.durationSeconds = config.mixedDurationSeconds;
        config.seedOffset = 2001;
    otherwise
        error("Stage4D:UnknownSyntheticGroup", ...
            "Synthetic group must be canonical, in_distribution, or out_of_distribution.");
end

if ~isempty(trajectoryCount)
    config.truthTrajectoryCount = double(trajectoryCount);
end

if ~isempty(durationSeconds)
    config.durationSeconds = double(durationSeconds);
end

if ~isempty(sampleRateHz)
    config.sampleRateHz = double(sampleRateHz);
end

end

function profileTable = localSyntheticProfileTable()
%LOCALSYNTHETICPROFILETABLE Describe the three synthetic observation paths.

profileTable = table( ...
    ["ideal"; "empirical_timing"; "degraded"], ...
    ["fixed_0p5_second"; "training_empirical"; "training_empirical"], ...
    [0; 0; 0.25], ...
    [0; 0; 30], ...
    [0; 0; 45], ...
    [0; 0; 2], ...
    [0; 0; 1.5], ...
    'VariableNames', [ ...
        "profile", ...
        "samplingPolicy", ...
        "randomObservationDropoutFraction", ...
        "horizontalPositionNoiseStdMeters", ...
        "verticalPositionNoiseStdMeters", ...
        "horizontalVelocityNoiseStdMetersPerSecond", ...
        "verticalVelocityNoiseStdMetersPerSecond"]);

end

function [pieces, truthAuditTable, caseTable] = localGenerateCanonical( ...
        config, profileTable, stream, empiricalDtSeconds, previousCovarianceDiag)
%LOCALGENERATECANONICAL Build seven motions under three observation profiles.

scenarioNames = [ ...
    "cv_level"; ...
    "cv_climb"; ...
    "horizontal_acceleration"; ...
    "vertical_acceleration"; ...
    "left_turn"; ...
    "right_turn"; ...
    "motion_transitions"];
profileCount = height(profileTable);
pieceCount = numel(scenarioNames) * profileCount;
pieces = repmat(localEmptyPiece(), pieceCount, 1);
truthAuditRows = cell(numel(scenarioNames), 1);
caseRows = cell(pieceCount, 1);
pieceIdx = 0;

for scenarioIdx = 1:numel(scenarioNames)
    scenarioName = scenarioNames(scenarioIdx);
    truth = localCreateCanonicalTruth( ...
        scenarioName, ...
        config.durationSeconds, ...
        config.sampleRateHz, ...
        stream);
    truthAuditRows{scenarioIdx} = localTruthAuditRow( ...
        scenarioName, ...
        truth);
    empiricalIndices = localEmpiricalObservationIndices( ...
        truth.timeSeconds, ...
        empiricalDtSeconds, ...
        stream);

    for profileIdx = 1:profileCount
        pieceIdx = pieceIdx + 1;
        profileName = profileTable.profile(profileIdx);
        caseID = scenarioName + "__" + profileName;
        pieces(pieceIdx) = localObserveTruth( ...
            truth, ...
            profileName, ...
            empiricalIndices, ...
            stream, ...
            previousCovarianceDiag, ...
            pieceIdx, ...
            caseID, ...
            scenarioName);
        caseRows{pieceIdx} = table( ...
            caseID, ...
            scenarioName, ...
            profileName, ...
            config.durationSeconds, ...
            height(pieces(pieceIdx).previousState), ...
            "latent_kinematic_truth", ...
            'VariableNames', [ ...
                "caseID", ...
                "motionScenario", ...
                "observationProfile", ...
                "durationSeconds", ...
                "pairCount", ...
                "targetReference"]);
    end
end

truthAuditTable = vertcat(truthAuditRows{:});
caseTable = vertcat(caseRows{:});

end

function [pieces, truthAuditTable, caseTable] = localGenerateMixed( ...
        config, profileTable, stream, empiricalDtSeconds, previousCovarianceDiag)
%LOCALGENERATEMIXED Build randomized piecewise-motion trajectories.

trajectoryCount = config.truthTrajectoryCount;
profileCount = height(profileTable);
pieceCount = trajectoryCount * profileCount;
pieces = repmat(localEmptyPiece(), pieceCount, 1);
truthAuditRows = cell(trajectoryCount, 1);
caseRows = cell(pieceCount, 1);
pieceIdx = 0;

for trajectoryIdx = 1:trajectoryCount
    truth = localCreateMixedTruth( ...
        config.groupName, ...
        config.durationSeconds, ...
        config.sampleRateHz, ...
        stream);
    trajectoryID = config.groupName + "_" + compose("%03d", trajectoryIdx);
    truthAuditRows{trajectoryIdx} = localTruthAuditRow( ...
        trajectoryID, ...
        truth);
    empiricalIndices = localEmpiricalObservationIndices( ...
        truth.timeSeconds, ...
        empiricalDtSeconds, ...
        stream);

    for profileIdx = 1:profileCount
        pieceIdx = pieceIdx + 1;
        profileName = profileTable.profile(profileIdx);
        caseID = trajectoryID + "__" + profileName;
        pieces(pieceIdx) = localObserveTruth( ...
            truth, ...
            profileName, ...
            empiricalIndices, ...
            stream, ...
            previousCovarianceDiag, ...
            pieceIdx, ...
            caseID, ...
            "mixed_motion");
        caseRows{pieceIdx} = table( ...
            caseID, ...
            trajectoryID, ...
            profileName, ...
            config.durationSeconds, ...
            height(pieces(pieceIdx).previousState), ...
            "latent_kinematic_truth", ...
            'VariableNames', [ ...
                "caseID", ...
                "motionScenario", ...
                "observationProfile", ...
                "durationSeconds", ...
                "pairCount", ...
                "targetReference"]);
    end
end

truthAuditTable = vertcat(truthAuditRows{:});
caseTable = vertcat(caseRows{:});

end

function truth = localCreateCanonicalTruth( ...
        scenarioName, durationSeconds, sampleRateHz, stream)
%LOCALCREATECANONICALTRUTH Configure one interpretable motion history.

timeSeconds = (0:(1 / sampleRateHz):durationSeconds).';
sampleCount = numel(timeSeconds);
bodyAcceleration = zeros(sampleCount, 3);
bodyAngularVelocity = zeros(sampleCount, 3);
motionMode = repmat("constant_velocity", sampleCount, 1);
transitionTimesSeconds = zeros(0, 1);
initialSpeed = 130 + 80*rand(stream);
initialHeadingDegrees = 360*rand(stream);
initialVerticalSpeed = 0;

switch scenarioName
    case "cv_level"
        % The default controls already describe level constant velocity.
    case "cv_climb"
        initialVerticalSpeed = 8;
        motionMode(:) = "constant_velocity_climb";
    case "horizontal_acceleration"
        firstInterval = localTimeMask(timeSeconds, 0.20, 0.45);
        secondInterval = localTimeMask(timeSeconds, 0.55, 0.80);
        bodyAcceleration(firstInterval, 1) = 0.8;
        bodyAcceleration(secondInterval, 1) = -0.8;
        motionMode(firstInterval | secondInterval) = "forward_acceleration";
        transitionTimesSeconds = durationSeconds * [0.20; 0.45; 0.55; 0.80];
    case "vertical_acceleration"
        firstInterval = localTimeMask(timeSeconds, 0.20, 0.45);
        secondInterval = localTimeMask(timeSeconds, 0.55, 0.80);
        bodyAcceleration(firstInterval, 3) = 0.15;
        bodyAcceleration(secondInterval, 3) = -0.15;
        motionMode(firstInterval | secondInterval) = "vertical_acceleration";
        transitionTimesSeconds = durationSeconds * [0.20; 0.45; 0.55; 0.80];
    case {"left_turn", "right_turn"}
        turnInterval = localTimeMask(timeSeconds, 0.25, 0.75);
        turnSign = 1;

        if scenarioName == "right_turn"
            turnSign = -1;
        end

        turnRate = turnSign*deg2rad(1.5);
        bodyAngularVelocity(turnInterval, 3) = turnRate;
        bodyAcceleration(turnInterval, 2) = initialSpeed*turnRate;
        motionMode(turnInterval) = scenarioName;
        transitionTimesSeconds = durationSeconds * [0.25; 0.75];
    case "motion_transitions"
        accelerationInterval = localTimeMask(timeSeconds, 0.15, 0.35);
        turnInterval = localTimeMask(timeSeconds, 0.45, 0.70);
        climbInterval = localTimeMask(timeSeconds, 0.78, 0.92);
        bodyAcceleration(accelerationInterval, 1) = 0.9;
        bodyAngularVelocity(turnInterval, 3) = deg2rad(1.8);
        bodyAcceleration(turnInterval, 2) = initialSpeed*deg2rad(1.8);
        bodyAcceleration(climbInterval, 3) = 0.2;
        motionMode(accelerationInterval) = "forward_acceleration";
        motionMode(turnInterval) = "left_turn";
        motionMode(climbInterval) = "vertical_acceleration";
        transitionTimesSeconds = durationSeconds * [0.15; 0.35; 0.45; 0.70; 0.78; 0.92];
    otherwise
        error("Stage4D:UnknownCanonicalScenario", ...
            "Unknown canonical scenario: %s", scenarioName);
end

initialPosition = [ ...
    -20000 + 40000*rand(stream), ...
    -20000 + 40000*rand(stream), ...
    4000 + 7000*rand(stream)];
truth = localRunKinematicTrajectory( ...
    timeSeconds, ...
    initialPosition, ...
    initialSpeed, ...
    initialHeadingDegrees, ...
    initialVerticalSpeed, ...
    bodyAcceleration, ...
    bodyAngularVelocity, ...
    motionMode, ...
    transitionTimesSeconds);

end

function truth = localCreateMixedTruth( ...
        groupName, durationSeconds, sampleRateHz, stream)
%LOCALCREATEMIXEDTRUTH Build bounded piecewise controls for one trajectory.

timeSeconds = (0:(1 / sampleRateHz):durationSeconds).';
sampleCount = numel(timeSeconds);
bodyAcceleration = zeros(sampleCount, 3);
bodyAngularVelocity = zeros(sampleCount, 3);
motionMode = repmat("constant_velocity", sampleCount, 1);

if groupName == "in_distribution"
    initialSpeed = 80 + 180*rand(stream);
    speedBounds = [50, 320];
    verticalSpeedBounds = [-20, 20];
    segmentDurationBounds = [20, 55];
    forwardAccelerationBounds = [0.2, 1.5];
    turnRateBoundsDegrees = [0.4, 3.0];
    verticalAccelerationBounds = [0.05, 0.25];
else
    initialSpeed = 300 + 70*rand(stream);
    speedBounds = [70, 430];
    verticalSpeedBounds = [-45, 45];
    segmentDurationBounds = [8, 22];
    forwardAccelerationBounds = [3.0, 6.0];
    turnRateBoundsDegrees = [5.0, 10.0];
    verticalAccelerationBounds = [0.6, 1.5];
end

initialHeadingDegrees = 360*rand(stream);
initialVerticalSpeed = verticalSpeedBounds(1) + ...
    diff(verticalSpeedBounds)*rand(stream);
nominalSpeed = initialSpeed;
nominalVerticalSpeed = initialVerticalSpeed;
sampleIdx = 1;
transitionTimesSeconds = zeros(0, 1);

while sampleIdx <= sampleCount
    segmentDurationSeconds = randi( ...
        stream, ...
        [segmentDurationBounds(1), segmentDurationBounds(2)]);
    segmentSampleCount = max(1, round(segmentDurationSeconds*sampleRateHz));
    segmentEndIdx = min(sampleCount, sampleIdx + segmentSampleCount - 1);
    segmentRows = sampleIdx:segmentEndIdx;
    actualDurationSeconds = numel(segmentRows) / sampleRateHz;
    modeIndex = randi(stream, 5);
    directionSign = 2*(rand(stream) >= 0.5) - 1;
    forwardAcceleration = 0;
    turnRate = 0;
    verticalAcceleration = 0;

    switch modeIndex
        case 1
            segmentMode = "constant_velocity";
        case 2
            segmentMode = "forward_acceleration";
            forwardAcceleration = directionSign*localUniformDraw( ...
                stream, ...
                forwardAccelerationBounds);
        case 3
            segmentMode = "constant_turn";
            turnRate = directionSign*deg2rad(localUniformDraw( ...
                stream, ...
                turnRateBoundsDegrees));
        case 4
            segmentMode = "vertical_acceleration";
            verticalAcceleration = directionSign*localUniformDraw( ...
                stream, ...
                verticalAccelerationBounds);
        case 5
            segmentMode = "combined_maneuver";
            forwardAcceleration = directionSign*localUniformDraw( ...
                stream, ...
                forwardAccelerationBounds);
            turnRate = -directionSign*deg2rad(localUniformDraw( ...
                stream, ...
                turnRateBoundsDegrees));
            verticalAcceleration = directionSign*localUniformDraw( ...
                stream, ...
                verticalAccelerationBounds);
        otherwise
            error("Stage4D:InvalidMixedMode", ...
                "The mixed-motion mode index is outside its expected range.");
    end

    if nominalSpeed <= speedBounds(1)
        forwardAcceleration = abs(forwardAcceleration);
    elseif nominalSpeed >= speedBounds(2)
        forwardAcceleration = -abs(forwardAcceleration);
    end

    if nominalVerticalSpeed <= verticalSpeedBounds(1)
        verticalAcceleration = abs(verticalAcceleration);
    elseif nominalVerticalSpeed >= verticalSpeedBounds(2)
        verticalAcceleration = -abs(verticalAcceleration);
    end

    meanSegmentSpeed = max(10, ...
        nominalSpeed + 0.5*forwardAcceleration*actualDurationSeconds);
    bodyAcceleration(segmentRows, 1) = forwardAcceleration;
    bodyAcceleration(segmentRows, 2) = meanSegmentSpeed*turnRate;
    bodyAcceleration(segmentRows, 3) = verticalAcceleration;
    bodyAngularVelocity(segmentRows, 3) = turnRate;
    motionMode(segmentRows) = segmentMode;

    nominalSpeed = nominalSpeed + forwardAcceleration*actualDurationSeconds;
    nominalVerticalSpeed = nominalVerticalSpeed + ...
        verticalAcceleration*actualDurationSeconds;

    if sampleIdx > 1
        transitionTimesSeconds(end + 1, 1) = timeSeconds(sampleIdx); %#ok<AGROW>
    end

    sampleIdx = segmentEndIdx + 1;
end

initialPosition = [ ...
    -30000 + 60000*rand(stream), ...
    -30000 + 60000*rand(stream), ...
    3000 + 10000*rand(stream)];
truth = localRunKinematicTrajectory( ...
    timeSeconds, ...
    initialPosition, ...
    initialSpeed, ...
    initialHeadingDegrees, ...
    initialVerticalSpeed, ...
    bodyAcceleration, ...
    bodyAngularVelocity, ...
    motionMode, ...
    transitionTimesSeconds);

end

function truth = localRunKinematicTrajectory( ...
        timeSeconds, ...
        initialPosition, ...
        initialSpeed, ...
        initialHeadingDegrees, ...
        initialVerticalSpeed, ...
        bodyAcceleration, ...
        bodyAngularVelocity, ...
        motionMode, ...
        transitionTimesSeconds)
%LOCALRUNKINEMATICTRAJECTORY Execute the native rate-driven truth model.

sampleRateHz = 1 / median(diff(timeSeconds));
initialVelocity = [ ...
    initialSpeed*cosd(initialHeadingDegrees), ...
    initialSpeed*sind(initialHeadingDegrees), ...
    initialVerticalSpeed];
initialOrientation = quaternion( ...
    [initialHeadingDegrees, 0, 0], ...
    "eulerd", ...
    "ZYX", ...
    "frame");
trajectory = kinematicTrajectory( ...
    SampleRate=sampleRateHz, ...
    Position=initialPosition, ...
    Velocity=initialVelocity, ...
    Orientation=initialOrientation);
cleanup = onCleanup(@() release(trajectory));
[position, ~, velocity, acceleration] = trajectory( ...
    bodyAcceleration, ...
    bodyAngularVelocity);

truth = struct();
truth.timeSeconds = timeSeconds;
truth.position = double(position);
truth.velocity = double(velocity);
truth.acceleration = double(acceleration);
truth.state = [ ...
    truth.position(:, 1), ...
    truth.velocity(:, 1), ...
    truth.position(:, 2), ...
    truth.velocity(:, 2), ...
    truth.position(:, 3), ...
    truth.velocity(:, 3)];
truth.motionMode = motionMode;
truth.transitionTimesSeconds = transitionTimesSeconds;
truth.sampleRateHz = sampleRateHz;

end

function piece = localObserveTruth( ...
        truth, ...
        profileName, ...
        empiricalIndices, ...
        stream, ...
        previousCovarianceDiag, ...
        eventID, ...
        caseID, ...
        motionScenario)
%LOCALOBSERVETRUTH Convert latent truth into one-step observed-state pairs.

switch profileName
    case "ideal"
        retainedIndices = (1:numel(truth.timeSeconds)).';
        noiseStandardDeviation = zeros(1, 6);
    case "empirical_timing"
        retainedIndices = empiricalIndices;
        noiseStandardDeviation = zeros(1, 6);
    case "degraded"
        retainedMask = rand(stream, numel(empiricalIndices), 1) >= 0.25;
        retainedMask([1, end]) = true;
        retainedIndices = empiricalIndices(retainedMask);
        noiseStandardDeviation = [30, 2, 30, 2, 45, 1.5];
    otherwise
        error("Stage4D:UnknownSyntheticProfile", ...
            "Unknown synthetic observation profile: %s", profileName);
end

if numel(retainedIndices) < 3
    retainedIndices = unique([ ...
        1; ...
        max(2, round(numel(truth.timeSeconds) / 2)); ...
        numel(truth.timeSeconds)]);
end

observedState = truth.state(retainedIndices, :);

if any(noiseStandardDeviation > 0)
    observedState = observedState + ...
        randn(stream, size(observedState)) .* noiseStandardDeviation;
end

pairCount = numel(retainedIndices) - 1;
previousIndices = retainedIndices(1:end - 1);
targetIndices = retainedIndices(2:end);
timeK = truth.timeSeconds(previousIndices);
timeNext = truth.timeSeconds(targetIndices);
piece = localEmptyPiece();
piece.previousState = observedState(1:end - 1, :);
piece.targetState = truth.state(targetIndices, :);
piece.previousCovarianceDiag = repmat( ...
    previousCovarianceDiag, ...
    pairCount, ...
    1);
piece.dtSeconds = timeNext - timeK;
piece.timeKSeconds = timeK;
piece.timeNextSeconds = timeNext;
piece.eventID = repmat(eventID, pairCount, 1);
piece.caseID = repmat(caseID, pairCount, 1);
piece.profile = repmat(profileName, pairCount, 1);
piece.motionScenario = repmat(motionScenario, pairCount, 1);
piece.motionMode = truth.motionMode(targetIndices);
piece.targetReference = repmat("latent_kinematic_truth", pairCount, 1);
piece.transitionOffsetSeconds = localNearestTransitionOffset( ...
    timeNext, ...
    truth.transitionTimesSeconds);
piece.truthTimeSeconds = truth.timeSeconds;
piece.truthState = truth.state;
piece.truthMotionMode = truth.motionMode;
piece.observationTimeSeconds = truth.timeSeconds(retainedIndices);
piece.observationState = observedState;
piece.observationTruthIndex = retainedIndices;

end

function retainedIndices = localEmpiricalObservationIndices( ...
        timeSeconds, empiricalDtSeconds, stream)
%LOCALEMPIRICALOBSERVATIONINDICES Sample a uniform truth grid with ADS-B timing.

sampleInterval = median(diff(timeSeconds));
sampleCount = numel(timeSeconds);
retainedIndices = zeros(sampleCount, 1);
retainedIndices(1) = 1;
retainedCount = 1;
currentIndex = 1;
validDt = empiricalDtSeconds( ...
    isfinite(empiricalDtSeconds) & empiricalDtSeconds > 0);
validDt = min(validDt, 15);

while currentIndex < sampleCount
    drawIndex = randi(stream, numel(validDt));
    stepSamples = max(1, round(validDt(drawIndex) / sampleInterval));
    currentIndex = min(sampleCount, currentIndex + stepSamples);
    retainedCount = retainedCount + 1;
    retainedIndices(retainedCount) = currentIndex;
end

retainedIndices = unique(retainedIndices(1:retainedCount), "stable");

end

function transitionOffsetSeconds = localNearestTransitionOffset( ...
        timeSeconds, transitionTimesSeconds)
%LOCALNEARESTTRANSITIONOFFSET Measure signed time from the nearest transition.

if isempty(transitionTimesSeconds)
    transitionOffsetSeconds = NaN(size(timeSeconds));
    return;
end

timeDifference = timeSeconds - transitionTimesSeconds(:).';
[~, nearestTransitionIdx] = min(abs(timeDifference), [], 2);
linearIndex = sub2ind( ...
    size(timeDifference), ...
    (1:numel(timeSeconds)).', ...
    nearestTransitionIdx);
transitionOffsetSeconds = timeDifference(linearIndex);

end

function auditRow = localTruthAuditRow(trajectoryID, truth)
%LOCALTRUTHAUDITROW Check continuity, monotonic time, and finite states.

timeStep = diff(truth.timeSeconds);
positionStep = vecnorm(diff(truth.position, 1, 1), 2, 2);
adjacentSpeed = max( ...
    vecnorm(truth.velocity(1:end - 1, :), 2, 2), ...
    vecnorm(truth.velocity(2:end, :), 2, 2));
adjacentAcceleration = max( ...
    vecnorm(truth.acceleration(1:end - 1, :), 2, 2), ...
    vecnorm(truth.acceleration(2:end, :), 2, 2));
continuityBound = adjacentSpeed .* timeStep + ...
    0.5*adjacentAcceleration .* timeStep .^ 2 + 1e-6;

auditRow = table( ...
    string(trajectoryID), ...
    numel(truth.timeSeconds), ...
    truth.timeSeconds(end) - truth.timeSeconds(1), ...
    all(timeStep > 0), ...
    all(isfinite(truth.state), "all"), ...
    all(positionStep <= continuityBound + 1e-6), ...
    max(positionStep), ...
    'VariableNames', [ ...
        "trajectoryID", ...
        "sampleCount", ...
        "durationSeconds", ...
        "monotonicTime", ...
        "finiteState", ...
        "continuousPosition", ...
        "maximumPositionStepMeters"]);

end

function pairSet = localConcatenatePieces(pieces, groupName)
%LOCALCONCATENATEPIECES Assemble one aligned pair universe.

pairSet = struct();
pairSet.domain = "synthetic_" + groupName;
pairSet.previousState = vertcat(pieces.previousState);
pairSet.targetState = vertcat(pieces.targetState);
pairSet.previousCovarianceDiag = vertcat(pieces.previousCovarianceDiag);
pairSet.dtSeconds = vertcat(pieces.dtSeconds);
pairSet.timeKSeconds = vertcat(pieces.timeKSeconds);
pairSet.timeNextSeconds = vertcat(pieces.timeNextSeconds);
pairSet.eventID = vertcat(pieces.eventID);
pairSet.caseID = vertcat(pieces.caseID);
pairSet.profile = vertcat(pieces.profile);
pairSet.motionScenario = vertcat(pieces.motionScenario);
pairSet.motionMode = vertcat(pieces.motionMode);
pairSet.targetReference = vertcat(pieces.targetReference);
pairSet.transitionOffsetSeconds = vertcat(pieces.transitionOffsetSeconds);

end

function audit = localAuditPairs(pairSet)
%LOCALAUDITPAIRS Verify the observation-to-target pair contract.

rowCount = size(pairSet.previousState, 1);
alignedRowCounts = [ ...
    size(pairSet.targetState, 1), ...
    size(pairSet.previousCovarianceDiag, 1), ...
    numel(pairSet.dtSeconds), ...
    numel(pairSet.timeKSeconds), ...
    numel(pairSet.timeNextSeconds), ...
    numel(pairSet.eventID), ...
    numel(pairSet.profile)];
audit = struct();
audit.rowCount = rowCount;
audit.alignedRows = all(alignedRowCounts == rowCount);
audit.finiteObservedStates = all(isfinite(pairSet.previousState), "all");
audit.finiteTargets = all(isfinite(pairSet.targetState), "all");
audit.positiveDt = all(pairSet.dtSeconds > 0);
audit.monotonicPairs = all(pairSet.timeNextSeconds > pairSet.timeKSeconds);
audit.latentTruthTargets = all( ...
    pairSet.targetReference == "latent_kinematic_truth");
audit.passed = audit.alignedRows && ...
    audit.finiteObservedStates && ...
    audit.finiteTargets && ...
    audit.positiveDt && ...
    audit.monotonicPairs && ...
    audit.latentTruthTargets;

end

function piece = localEmptyPiece()
%LOCALEMPTYPIECE Define a stable observation-piece schema.

piece = struct( ...
    "previousState", zeros(0, 6), ...
    "targetState", zeros(0, 6), ...
    "previousCovarianceDiag", zeros(0, 6), ...
    "dtSeconds", zeros(0, 1), ...
    "timeKSeconds", zeros(0, 1), ...
    "timeNextSeconds", zeros(0, 1), ...
    "eventID", zeros(0, 1), ...
    "caseID", strings(0, 1), ...
    "profile", strings(0, 1), ...
    "motionScenario", strings(0, 1), ...
    "motionMode", strings(0, 1), ...
    "targetReference", strings(0, 1), ...
    "transitionOffsetSeconds", zeros(0, 1), ...
    "truthTimeSeconds", zeros(0, 1), ...
    "truthState", zeros(0, 6), ...
    "truthMotionMode", strings(0, 1), ...
    "observationTimeSeconds", zeros(0, 1), ...
    "observationState", zeros(0, 6), ...
    "observationTruthIndex", zeros(0, 1));

end

function mask = localTimeMask(timeSeconds, startFraction, endFraction)
%LOCALTIMEMASK Select a fractional interval from a trajectory duration.

durationSeconds = timeSeconds(end);
mask = timeSeconds >= startFraction*durationSeconds & ...
    timeSeconds < endFraction*durationSeconds;

end

function value = localUniformDraw(stream, bounds)
%LOCALUNIFORMDRAW Draw one scalar uniformly between two bounds.

value = bounds(1) + diff(bounds)*rand(stream);

end

function localValidateInputs( ...
        groupName, ...
        benchmarkMode, ...
        seed, ...
        empiricalDtSeconds, ...
        previousCovarianceDiag, ...
        trajectoryCount, ...
        durationSeconds, ...
        sampleRateHz)
%LOCALVALIDATEINPUTS Validate public helper arguments.

if ~ismember(groupName, ...
        ["canonical", "in_distribution", "out_of_distribution"])
    error("Stage4D:UnknownSyntheticGroup", ...
        "Synthetic group must be canonical, in_distribution, or out_of_distribution.");
end

if ~ismember(benchmarkMode, ["smoke", "full"])
    error("Stage4D:InvalidBenchmarkMode", ...
        "BenchmarkMode must be smoke or full.");
end

validateattributes(seed, ...
    {'numeric'}, {'scalar', 'integer', 'nonnegative', 'finite'}, ...
    mfilename, "Seed");
validateattributes(empiricalDtSeconds, ...
    {'numeric'}, {'column', 'real', 'finite', 'positive', 'nonempty'}, ...
    mfilename, "EmpiricalDtSeconds");
validateattributes(previousCovarianceDiag, ...
    {'numeric'}, {'row', 'numel', 6, 'real', 'finite', 'positive'}, ...
    mfilename, "PreviousCovarianceDiag");

localValidateOptionalPositiveInteger(trajectoryCount, "TrajectoryCount");
localValidateOptionalPositiveScalar(durationSeconds, "DurationSeconds");
localValidateOptionalPositiveScalar(sampleRateHz, "SampleRateHz");

end

function localValidateOptionalPositiveInteger(value, argumentName)
%LOCALVALIDATEOPTIONALPOSITIVEINTEGER Validate an optional count override.

if isempty(value)
    return;
end

validateattributes(value, ...
    {'numeric'}, ...
    {'scalar', 'integer', 'positive', 'finite'}, ...
    mfilename, ...
    argumentName);

end

function localValidateOptionalPositiveScalar(value, argumentName)
%LOCALVALIDATEOPTIONALPOSITIVESCALAR Validate an optional scalar override.

if isempty(value)
    return;
end

validateattributes(value, ...
    {'numeric'}, ...
    {'scalar', 'real', 'positive', 'finite'}, ...
    mfilename, ...
    argumentName);

end
