function collection = helperBuildStage4CTrajectoryCollection( ...
        dashboard, motionClass, varargin)
%HELPERBUILDSTAGE4CTRAJECTORYCOLLECTION Build Stage 4C globe paths on demand.
% N means the longest N continuous eligible test events in one motion
% class. Each event contributes ADS-B truth, its class-aligned native
% prediction, and predictions from the three frozen neural networks.

parser = inputParser;
parser.FunctionName = mfilename;
addRequired(parser, "dashboard", @isstruct);
addRequired(parser, "motionClass", ...
    @(value) ischar(value) || (isstring(value) && isscalar(value)));
addParameter(parser, "TrajectoryCount", 50);
addParameter(parser, "PredictionMiniBatchSize", []);
parse(parser, dashboard, motionClass, varargin{:});

motionClass = string(parser.Results.motionClass);
requestedCount = localValidateTrajectoryCount( ...
    parser.Results.TrajectoryCount, ...
    "TrajectoryCount");
localValidateDashboardInput(dashboard);
[representative, nativeModelID] = localSelectClass( ...
    dashboard.representatives, motionClass);

eligibleCount = height(representative.eventTable);
plottedCount = min(requestedCount, eligibleCount);
selectedEvents = representative.eventTable(1:plottedCount, :);
selectedEvents = addvars( ...
    selectedEvents, ...
    (1:plottedCount).', ...
    'Before', 1, ...
    'NewVariableNames', "trajectoryRank");
rowCells = selectedEvents.datasetRowIndices;
selectedRows = vertcat(rowCells{:});
eventIndex = repelem((1:plottedCount).', selectedEvents.pairCount);

dataset = localLoadDataset(dashboard.sourcePaths.dataset);
split = localLoadFrozenSplit( ...
    dataset.metadata, ...
    dashboard.sourcePaths.splitManifest);
localValidateSourceHashes(dashboard);
maneuverPairTable = helperAssignADSBManeuverLabels( ...
    dataset.previousState, ...
    dataset.nextState, ...
    dataset.dtSeconds);

testRowsOnly = split(selectedRows) == "test";
motionClassMatches = ...
    string(maneuverPairTable.maneuverClass(selectedRows)) == motionClass;

if ~all(testRowsOnly) || ~all(motionClassMatches)
    error( ...
        "StageReview:Stage4CTrajectoryEligibilityMismatch", ...
        "Selected rows must be eligible test rows in motion class %s.", ...
        motionClass);
end

previousState = double(dataset.previousState(selectedRows, :));
constvelPrediction = double( ...
    dataset.baselineConstVelMetrics.predictedState(selectedRows, :));
featureData = helperBuildStage4CFeatures( ...
    previousState, ...
    dataset.previousCovarianceDiag(selectedRows, :), ...
    dataset.dtSeconds(selectedRows), ...
    constvelPrediction);

miniBatchSize = parser.Results.PredictionMiniBatchSize;

if isempty(miniBatchSize)
    miniBatchSize = dashboard.predictionMiniBatchSize;
else
    miniBatchSize = localValidateTrajectoryCount( ...
        miniBatchSize, ...
        "PredictionMiniBatchSize");
end

% All selected rows are presented to each frozen network together. This
% avoids one inference call per event while preserving event boundaries
% through eventIndex for the subsequent split.
models = localLoadModels(dashboard.modelIdentityTable);
neuralPredictions = cell(3, 1);

for modelIdx = 1:numel(models)
    neuralPredictions{modelIdx} = localPredictState( ...
        models(modelIdx), ...
        featureData.features, ...
        previousState, ...
        miniBatchSize);
end

[nativePrediction, nativeEligible] = localBuildNativePrediction( ...
    nativeModelID, ...
    selectedRows, ...
    dataset, ...
    split);

if ~all(nativeEligible)
    error( ...
        "StageReview:Stage4CTrajectoryEligibilityMismatch", ...
        "A selected %s event is not eligible for native %s prediction.", ...
        motionClass, ...
        nativeModelID);
end

states = localEmptyTrajectoryStruct(plottedCount);
lla = localEmptyTrajectoryStruct(plottedCount);
trajectories = localEmptyTrajectoryStruct(plottedCount);
timeUtc = cell(plottedCount, 1);
timeSeconds = cell(plottedCount, 1);
receiverOriginLLA = zeros(plottedCount, 3);
continuous = false(plottedCount, 1);
monotonicTime = false(plottedCount, 1);
finiteLLA = false(plottedCount, 1);
eventTestRowsOnly = false(plottedCount, 1);
eventMotionClassMatches = false(plottedCount, 1);
eventNativeEligible = false(plottedCount, 1);

for eventIdx = 1:plottedCount
    eventMask = eventIndex == eventIdx;
    eventRows = selectedRows(eventMask);
    eventPreviousState = previousState(eventMask, :);
    eventTimeUtc = [ ...
        dataset.metadata.timeUtcK(eventRows(1)); ...
        dataset.metadata.timeUtcNext(eventRows)];
    eventTimeSeconds = seconds(eventTimeUtc - eventTimeUtc(1));
    eventReceiverOriginLLA = ...
        dataset.metadata.receiverOriginLLA(eventRows(1), :);

    states.truth{eventIdx} = [ ...
        eventPreviousState(1, :); ...
        double(dataset.nextState(eventRows, :))];
    states.native{eventIdx} = [ ...
        eventPreviousState(1, :); ...
        nativePrediction(eventMask, :)];
    states.legacy{eventIdx} = [ ...
        eventPreviousState(1, :); ...
        neuralPredictions{1}(eventMask, :)];
    states.scratch{eventIdx} = [ ...
        eventPreviousState(1, :); ...
        neuralPredictions{2}(eventMask, :)];
    states.warm{eventIdx} = [ ...
        eventPreviousState(1, :); ...
        neuralPredictions{3}(eventMask, :)];

    lla.truth{eventIdx} = localStateToLLA( ...
        states.truth{eventIdx}, eventReceiverOriginLLA);
    lla.native{eventIdx} = localStateToLLA( ...
        states.native{eventIdx}, eventReceiverOriginLLA);
    lla.legacy{eventIdx} = localStateToLLA( ...
        states.legacy{eventIdx}, eventReceiverOriginLLA);
    lla.scratch{eventIdx} = localStateToLLA( ...
        states.scratch{eventIdx}, eventReceiverOriginLLA);
    lla.warm{eventIdx} = localStateToLLA( ...
        states.warm{eventIdx}, eventReceiverOriginLLA);

    trajectories.truth{eventIdx} = geoTrajectory( ...
        lla.truth{eventIdx}, ...
        eventTimeSeconds, ...
        ReferenceFrame="ENU");
    trajectories.native{eventIdx} = geoTrajectory( ...
        lla.native{eventIdx}, ...
        eventTimeSeconds, ...
        ReferenceFrame="ENU");
    trajectories.legacy{eventIdx} = geoTrajectory( ...
        lla.legacy{eventIdx}, ...
        eventTimeSeconds, ...
        ReferenceFrame="ENU");
    trajectories.scratch{eventIdx} = geoTrajectory( ...
        lla.scratch{eventIdx}, ...
        eventTimeSeconds, ...
        ReferenceFrame="ENU");
    trajectories.warm{eventIdx} = geoTrajectory( ...
        lla.warm{eventIdx}, ...
        eventTimeSeconds, ...
        ReferenceFrame="ENU");

    timeUtc{eventIdx} = eventTimeUtc;
    timeSeconds{eventIdx} = eventTimeSeconds;
    receiverOriginLLA(eventIdx, :) = eventReceiverOriginLLA;
    continuous(eventIdx) = localIsContinuousEvent( ...
        eventRows, ...
        dataset.metadata);
    monotonicTime(eventIdx) = all(diff(eventTimeSeconds) > 0);
    finiteLLA(eventIdx) = localAllLLAFinite(lla, eventIdx);
    eventTestRowsOnly(eventIdx) = all(testRowsOnly(eventMask));
    eventMotionClassMatches(eventIdx) = ...
        all(motionClassMatches(eventMask));
    eventNativeEligible(eventIdx) = all(nativeEligible(eventMask));
end

validationTable = table( ...
    (1:plottedCount).', ...
    continuous, ...
    monotonicTime, ...
    finiteLLA, ...
    eventTestRowsOnly, ...
    eventMotionClassMatches, ...
    eventNativeEligible, ...
    'VariableNames', [ ...
        "trajectoryRank", ...
        "continuous", ...
        "monotonicTime", ...
        "finiteLLA", ...
        "testRowsOnly", ...
        "motionClassMatches", ...
        "nativeEligible"]);

if ~all(validationTable{:, 2:end}, "all")
    error( ...
        "StageReview:InvalidStage4CTrajectoryCollection", ...
        "A selected event failed continuity, timing, eligibility, or LLA validation.");
end

pairCount = sum(selectedEvents.pairCount);
sessionCount = numel(unique(selectedEvents.sessionID));
icaoCount = numel(unique(selectedEvents.icao24));
trajectoryPathCount = 5 * plottedCount;
wasCapped = plottedCount < requestedCount;
label = sprintf( ...
    "%s trajectory collection | requested %d | plotted %d of %d eligible events | %d paths | %d pairs | %d sessions | %d ICAOs", ...
    motionClass, ...
    requestedCount, ...
    plottedCount, ...
    eligibleCount, ...
    trajectoryPathCount, ...
    pairCount, ...
    sessionCount, ...
    icaoCount);
summaryTable = table( ...
    motionClass, ...
    nativeModelID, ...
    requestedCount, ...
    plottedCount, ...
    eligibleCount, ...
    trajectoryPathCount, ...
    pairCount, ...
    sessionCount, ...
    icaoCount, ...
    wasCapped, ...
    string(label), ...
    'VariableNames', [ ...
        "motionClass", ...
        "nativeModelID", ...
        "requestedTrajectoryCount", ...
        "plottedTrajectoryCount", ...
        "eligibleTrajectoryCount", ...
        "trajectoryPathCount", ...
        "pairCount", ...
        "sessionCount", ...
        "icaoCount", ...
        "wasCapped", ...
        "collectionLabel"]);

collection = struct();
collection.motionClass = motionClass;
collection.nativeModelID = nativeModelID;
collection.requestedTrajectoryCount = requestedCount;
collection.plottedTrajectoryCount = plottedCount;
collection.eligibleTrajectoryCount = eligibleCount;
collection.trajectoryPathCount = trajectoryPathCount;
collection.plotCallCount = 5;
collection.wasCapped = wasCapped;
collection.label = string(label);
collection.summaryTable = summaryTable;
collection.legendTable = localBuildLegendTable( ...
    nativeModelID, ...
    plottedCount);
collection.eventTable = selectedEvents;
collection.validationTable = validationTable;
collection.datasetRowIndices = rowCells;
collection.allSelectedRows = selectedRows;
collection.receiverOriginLLA = receiverOriginLLA(1, :);
collection.eventReceiverOriginLLA = receiverOriginLLA;
collection.timeUtc = timeUtc;
collection.timeSeconds = timeSeconds;
collection.states = states;
collection.lla = lla;
collection.trajectories = trajectories;
collection.trainingPerformed = false;
collection.clippingApplied = false;
collection.smoothingApplied = false;

end

function value = localValidateTrajectoryCount(value, argumentName)
%LOCALVALIDATETRAJECTORYCOUNT Require a positive finite integer scalar.

if ~isnumeric(value) || ...
        ~isreal(value) || ...
        ~isscalar(value) || ...
        ~isfinite(value) || ...
        value < 1 || ...
        value ~= fix(value)
    error( ...
        "StageReview:InvalidStage4CTrajectoryCount", ...
        "%s must be a positive finite integer scalar.", ...
        argumentName);
end

value = double(value);

end

function localValidateDashboardInput(dashboard)
%LOCALVALIDATEDASHBOARDINPUT Require the on-demand trajectory context.

requiredFields = [ ...
    "representatives"; ...
    "sourcePaths"; ...
    "sourceHashes"; ...
    "modelIdentityTable"; ...
    "predictionMiniBatchSize"];

if any(~isfield(dashboard, requiredFields))
    error( ...
        "StageReview:InvalidStage4CDashboard", ...
        "The Stage 4C dashboard is missing on-demand trajectory context.");
end

end

function [representative, nativeModelID] = localSelectClass( ...
        representatives, motionClass)
%LOCALSELECTCLASS Match one supported motion class.

supportedClasses = string({representatives.motionClass}).';
classMask = supportedClasses == motionClass;

if sum(classMask) ~= 1
    error( ...
        "StageReview:UnknownStage4CMotionClass", ...
        "Motion class must be one of: %s.", ...
        strjoin(supportedClasses, ", "));
end

representative = representatives(classMask);
nativeModelID = representative.nativeModelID;

end

function dataset = localLoadDataset(datasetPath)
%LOCALLOADDATASET Load the fields required for trajectory construction.

try
    dataset = load( ...
        datasetPath, ...
        "previousState", ...
        "nextState", ...
        "dtSeconds", ...
        "previousCovarianceDiag", ...
        "metadata", ...
        "baselineConstVelMetrics");
catch err
    error( ...
        "StageReview:Stage4CDatasetLoadFailed", ...
        "Unable to load the Expanded-3Day dataset: %s", ...
        err.message);
end

requiredFields = [ ...
    "previousState"; ...
    "nextState"; ...
    "dtSeconds"; ...
    "previousCovarianceDiag"; ...
    "metadata"; ...
    "baselineConstVelMetrics"];

if any(~isfield(dataset, requiredFields)) || ...
        ~isfield(dataset.baselineConstVelMetrics, "predictedState")
    error( ...
        "StageReview:InvalidStage4CDataset", ...
        "The Expanded-3Day dataset lacks trajectory construction data.");
end

end

function split = localLoadFrozenSplit(metadata, splitManifestPath)
%LOCALLOADFROZENSPLIT Apply the frozen global ICAO partition.

manifest = readtable(splitManifestPath, TextType="string");
requiredVariables = ["icao24", "split"];

if any(~ismember(requiredVariables, ...
        string(manifest.Properties.VariableNames)))
    error( ...
        "StageReview:InvalidStage4CSplitManifest", ...
        "The frozen split manifest must contain icao24 and split.");
end

manifest.icao24 = lower(strtrim(string(manifest.icao24)));
manifest.split = lower(strtrim(string(manifest.split)));
[found, manifestRow] = ismember( ...
    lower(strtrim(string(metadata.hex))), ...
    manifest.icao24);

if ~all(found)
    error( ...
        "StageReview:Stage4CSplitMembershipMismatch", ...
        "Every selected dataset ICAO must occur in the split manifest.");
end

split = manifest.split(manifestRow);

end

function localValidateSourceHashes(dashboard)
%LOCALVALIDATESOURCEHASHES Detect changes after dashboard construction.

datasetHash = helperComputeFileSHA256(dashboard.sourcePaths.dataset);
splitHash = helperComputeFileSHA256(dashboard.sourcePaths.splitManifest);

if ~strcmpi(datasetHash, dashboard.sourceHashes.dataset) || ...
        ~strcmpi(splitHash, dashboard.sourceHashes.splitManifest)
    error( ...
        "StageReview:Stage4CFrozenInputHashMismatch", ...
        "The dataset or split manifest changed after dashboard construction.");
end

end

function models = localLoadModels(identityTable)
%LOCALLOADMODELS Load and hash-check the three frozen neural models.

modelIDs = [ ...
    "legacy_stage3a_v1"; ...
    "expanded_scratch_mean_v1"; ...
    "expanded_warm_mean_v1"];
models = repmat(struct( ...
    "modelID", "", ...
    "net", [], ...
    "featureNormalization", [], ...
    "targetNormalization", []), ...
    numel(modelIDs), ...
    1);

for modelIdx = 1:numel(modelIDs)
    identityMask = identityTable.modelID == modelIDs(modelIdx);

    if sum(identityMask) ~= 1
        error( ...
            "StageReview:Stage4CModelIdentityMismatch", ...
            "Expected one frozen identity row for %s.", ...
            modelIDs(modelIdx));
    end

    artifactPath = identityTable.artifactPath(identityMask);
    actualHash = helperComputeFileSHA256(artifactPath);

    if ~strcmpi(actualHash, identityTable.sha256(identityMask))
        error( ...
            "StageReview:Stage4CFrozenModelHashMismatch", ...
            "Frozen model %s changed after dashboard construction.", ...
            modelIDs(modelIdx));
    end

    if modelIDs(modelIdx) == "legacy_stage3a_v1"
        featureField = "physicsFeatures";
    else
        featureField = "features";
    end

    loaded = load(artifactPath, "net", "normalization");

    if ~isfield(loaded, "net") || ...
            ~isfield(loaded, "normalization") || ...
            ~isfield(loaded.normalization, featureField) || ...
            ~isfield(loaded.normalization, "target")
        error( ...
            "StageReview:InvalidStage4CModelArtifact", ...
            "Frozen model %s lacks its network or normalization.", ...
            artifactPath);
    end

    models(modelIdx).modelID = modelIDs(modelIdx);
    models(modelIdx).net = loaded.net;
    models(modelIdx).featureNormalization = ...
        loaded.normalization.(featureField);
    models(modelIdx).targetNormalization = ...
        loaded.normalization.target;
end

end

function predictedState = localPredictState( ...
        model, physicalFeatures, previousState, miniBatchSize)
%LOCALPREDICTSTATE Run one frozen neural model in physical units.

normalizedFeatures = ...
    (double(physicalFeatures) - ...
    model.featureNormalization.featureMean) ./ ...
    model.featureNormalization.featureStd;
predictedDeltaNormalized = minibatchpredict( ...
    model.net, ...
    single(normalizedFeatures), ...
    MiniBatchSize=min(miniBatchSize, size(normalizedFeatures, 1)));
predictedDeltaNormalized = gather(extractdata( ...
    predictedDeltaNormalized));

if size(predictedDeltaNormalized, 1) ~= size(normalizedFeatures, 1) && ...
        size(predictedDeltaNormalized, 2) == size(normalizedFeatures, 1)
    predictedDeltaNormalized = predictedDeltaNormalized.';
end

if ~isequal( ...
        size(predictedDeltaNormalized), ...
        [size(normalizedFeatures, 1), 6])
    error( ...
        "StageReview:Stage4CPredictionShapeMismatch", ...
        "Frozen model %s must return an N-by-6 prediction.", ...
        model.modelID);
end

predictedDelta = double(predictedDeltaNormalized) .* ...
    model.targetNormalization.targetStd + ...
    model.targetNormalization.targetMean;
predictedState = double(previousState) + predictedDelta;

if any(~isfinite(predictedState), "all")
    error( ...
        "StageReview:NonfiniteStage4CPrediction", ...
        "Frozen model %s produced a nonfinite prediction.", ...
        model.modelID);
end

end

function [predictedState, eligibleMask] = localBuildNativePrediction( ...
        nativeModelID, selectedRows, dataset, split)
%LOCALBUILDNATIVEPREDICTION Apply the frozen class-aligned native policy.

if nativeModelID == "constvel"
    predictedState = double( ...
        dataset.baselineConstVelMetrics.predictedState(selectedRows, :));
    eligibleMask = all(isfinite(predictedState), 2);
    return;
end

allTrackKeys = table( ...
    string(dataset.metadata.sessionID), ...
    lower(strtrim(string(dataset.metadata.hex))), ...
    'VariableNames', ["sessionID", "icao24"]);
selectedTrackKeys = unique( ...
    allTrackKeys(selectedRows, :), ...
    "rows", ...
    "stable");
trackMask = ismember(allTrackKeys, selectedTrackKeys, "rows");
trackRows = find(trackMask);
trackMetadata = dataset.metadata( ...
    trackRows, ...
    ["sessionID", "hex", "timeUtcK", "timeUtcNext"]);
baseline = helperBuildStage4CNativeManeuverBaselines( ...
    dataset.previousState(trackRows, :), ...
    dataset.dtSeconds(trackRows), ...
    trackMetadata, ...
    split(trackRows));
[found, selectedTrackRows] = ismember(selectedRows, trackRows);

if ~all(found)
    error( ...
        "StageReview:Stage4CTrajectoryRowMismatch", ...
        "A selected event row was not found in its source track.");
end

eligibleMask = baseline.eligibleMask(selectedTrackRows);

if nativeModelID == "constacc"
    predictedState = baseline.constaccPredictedState( ...
        selectedTrackRows, :);
elseif nativeModelID == "constturn"
    predictedState = baseline.constturnPredictedState( ...
        selectedTrackRows, :);
else
    error( ...
        "StageReview:UnknownStage4CNativeModel", ...
        "Unexpected native model identity: %s.", ...
        nativeModelID);
end

end

function trajectoryStruct = localEmptyTrajectoryStruct(trajectoryCount)
%LOCALEMPTYTRAJECTORYSTRUCT Preallocate five model-aligned cell arrays.

trajectoryStruct = struct( ...
    "truth", {cell(trajectoryCount, 1)}, ...
    "native", {cell(trajectoryCount, 1)}, ...
    "legacy", {cell(trajectoryCount, 1)}, ...
    "scratch", {cell(trajectoryCount, 1)}, ...
    "warm", {cell(trajectoryCount, 1)});

end

function lla = localStateToLLA(state, receiverOriginLLA)
%LOCALSTATETOLLA Convert local ENU positions to geodetic coordinates.

spheroid = wgs84Ellipsoid("meter");
[latitudeDegrees, longitudeDegrees, altitudeMeters] = enu2geodetic( ...
    state(:, 1), ...
    state(:, 3), ...
    state(:, 5), ...
    receiverOriginLLA(1), ...
    receiverOriginLLA(2), ...
    receiverOriginLLA(3), ...
    spheroid);
lla = [latitudeDegrees, longitudeDegrees, altitudeMeters];

end

function tf = localIsContinuousEvent(rows, metadata)
%LOCALISCONTINUOUSEVENT Verify one session/ICAO and adjacent pair times.

sameSession = all( ...
    string(metadata.sessionID(rows)) == ...
    string(metadata.sessionID(rows(1))));
sameICAO = all( ...
    lower(strtrim(string(metadata.hex(rows)))) == ...
    lower(strtrim(string(metadata.hex(rows(1))))));

if numel(rows) > 1
    timeGapSeconds = seconds( ...
        metadata.timeUtcK(rows(2:end)) - ...
        metadata.timeUtcNext(rows(1:end - 1)));
    adjacent = all(abs(timeGapSeconds) <= 1e-6);
else
    adjacent = true;
end

tf = sameSession && sameICAO && adjacent;

end

function tf = localAllLLAFinite(lla, eventIdx)
%LOCALALLLLAFINITE Check all five LLA paths for one event.

values = [ ...
    lla.truth{eventIdx}; ...
    lla.native{eventIdx}; ...
    lla.legacy{eventIdx}; ...
    lla.scratch{eventIdx}; ...
    lla.warm{eventIdx}];
tf = all(isfinite(values), "all");

end

function legendTable = localBuildLegendTable(nativeModelID, trajectoryCount)
%LOCALBUILDLEGENDTABLE Describe the five batched model layers.

modelID = [ ...
    "truth"; ...
    nativeModelID; ...
    "legacy_stage3a_v1"; ...
    "expanded_scratch_mean_v1"; ...
    "expanded_warm_mean_v1"];
displayName = [ ...
    "ADS-B truth"; ...
    "Native " + nativeModelID; ...
    "Stage 3A legacy"; ...
    "Expanded scratch"; ...
    "Expanded warm"];
color = ["green"; "blue"; "red"; "orange"; "purple"];
pathCount = repmat(trajectoryCount, 5, 1);
legendTable = table(modelID, displayName, color, pathCount);

end
