function featureSets = helperBuildStage3AFeatures(previousState, previousCovarianceDiag, dtSeconds, constvelPredictedState, split)
%HELPERBUILDSTAGE3AFEATURES Build Stage 3A motion-focused feature sets.
% Absolute horizontal x/y are deliberately excluded. They are only used
% later when reconstructing predictedNextState from predicted state deltas.

previousState = double(previousState);
previousCovarianceDiag = double(previousCovarianceDiag);
dtSeconds = double(dtSeconds(:));
constvelPredictedState = double(constvelPredictedState);
split = string(split(:));

localValidateInputs( ...
    previousState, ...
    previousCovarianceDiag, ...
    dtSeconds, ...
    constvelPredictedState, ...
    split);

vx = previousState(:, 2);
vy = previousState(:, 4);
z = previousState(:, 5);
vz = previousState(:, 6);
constvelDelta = constvelPredictedState - previousState;

rawFeatureNames = [ ...
    "vx"; ...
    "vy"; ...
    "z"; ...
    "vz"; ...
    "dtSeconds"; ...
    "previousCovarianceDiag_x"; ...
    "previousCovarianceDiag_vx"; ...
    "previousCovarianceDiag_y"; ...
    "previousCovarianceDiag_vy"; ...
    "previousCovarianceDiag_z"; ...
    "previousCovarianceDiag_vz"];
rawFeatures = [ ...
    vx, ...
    vy, ...
    z, ...
    vz, ...
    dtSeconds, ...
    previousCovarianceDiag];

physicsFeatureNames = [ ...
    rawFeatureNames; ...
    "vxTimesDt"; ...
    "vyTimesDt"; ...
    "vzTimesDt"; ...
    "constvelDelta_x"; ...
    "constvelDelta_vx"; ...
    "constvelDelta_y"; ...
    "constvelDelta_vy"; ...
    "constvelDelta_z"; ...
    "constvelDelta_vz"];
physicsFeatures = [ ...
    rawFeatures, ...
    vx .* dtSeconds, ...
    vy .* dtSeconds, ...
    vz .* dtSeconds, ...
    constvelDelta];

featureSets = struct();
featureSets.raw = localPackFeatureSet( ...
    rawFeatures, ...
    rawFeatureNames, ...
    split, ...
    "raw_motion");
featureSets.physics = localPackFeatureSet( ...
    physicsFeatures, ...
    physicsFeatureNames, ...
    split, ...
    "physics_derived_delta");
featureSets.defaultFeatureMode = "physics";
featureSets.excludedDefaultFeatures = ["x", "y"];

end

function localValidateInputs(previousState, previousCovarianceDiag, dtSeconds, constvelPredictedState, split)
%LOCALVALIDATEINPUTS Verify feature-builder dimensions.

sampleCount = size(previousState, 1);

if size(previousState, 2) ~= 6 || size(previousCovarianceDiag, 2) ~= 6
    error("Stage3A:BadStateWidth", ...
        "previousState and previousCovarianceDiag must have six columns.");
end

if size(previousCovarianceDiag, 1) ~= sampleCount || ...
        size(constvelPredictedState, 1) ~= sampleCount || ...
        numel(dtSeconds) ~= sampleCount || ...
        numel(split) ~= sampleCount
    error("Stage3A:FeatureInputSizeMismatch", ...
        "All Stage 3A feature inputs must contain one row per state pair.");
end

if size(constvelPredictedState, 2) ~= 6
    error("Stage3A:BadConstvelWidth", ...
        "constvelPredictedState must have six columns.");
end

end

function featureSet = localPackFeatureSet(features, featureNames, split, featureMode)
%LOCALPACKFEATURESET Normalize one feature matrix using train rows only.

normalization = localComputeNormalization(features, featureNames, split);
featuresNormalized = (features - normalization.featureMean) ./ normalization.featureStd;

featureSet = struct();
featureSet.featureMode = featureMode;
featureSet.features = features;
featureSet.featuresNormalized = featuresNormalized;
featureSet.featureNames = featureNames;
featureSet.normalization = normalization;

end

function normalization = localComputeNormalization(features, featureNames, split)
%LOCALCOMPUTENORMALIZATION Compute train-split feature normalization.

trainMask = split == "train";

if ~any(trainMask)
    error("Stage3A:NoTrainingRows", ...
        "At least one training row is required for feature normalization.");
end

featureMean = mean(features(trainMask, :), 1, "omitnan");
rawFeatureStd = std(features(trainMask, :), 0, 1, "omitnan");
featureStd = rawFeatureStd;
badStd = ~isfinite(featureStd) | featureStd <= 0;
featureStd(badStd) = 1;

normalization = struct();
normalization.computedFromSplit = "train";
normalization.trainRowCount = sum(trainMask);
normalization.featureMean = featureMean;
normalization.featureStd = featureStd;
normalization.rawFeatureStd = rawFeatureStd;
normalization.constantFeatureMask = badStd;
normalization.constantFeatureNames = featureNames(badStd);

end
