function errorComparison = helperPlotStageReviewStage3ErrorComparison(review, varargin)
%HELPERPLOTSTAGEREVIEWSTAGE3ERRORCOMPARISON Plot Stage 3A error over time.

parser = inputParser;
parser.FunctionName = mfilename;
addParameter(parser, "TrackHex", review.defaultTrackHex);
addParameter(parser, "MaxPairs", 80);
parse(parser, varargin{:});
opts = parser.Results;

if ~review.hasStage3A
    errorComparison = table( ...
        "Stage 3A artifact missing", ...
        NaN, ...
        NaN, ...
        NaN, ...
        'VariableNames', [ ...
            "method", ...
            "trackPositionRMSEMeters", ...
            "trackMedianPositionErrorMeters", ...
            "trackP95PositionErrorMeters"]);
    fprintf("Stage 3A artifact not found; skipping Stage 3A error comparison plot.\n");
    return;
end

trajectoryData = helperBuildStageReviewTrajectories( ...
    review, ...
    "TrackHex", opts.TrackHex, ...
    "MaxPairs", opts.MaxPairs);

timeSeconds = trajectoryData.timeSeconds;
truthState = trajectoryData.truthState;
constvelState = trajectoryData.constvelState;
stage3State = trajectoryData.stage3State;
positionColumns = [1, 3, 5];

constvelPositionError = vecnorm( ...
    constvelState(:, positionColumns) - truthState(:, positionColumns), ...
    2, ...
    2);
stage3PositionError = vecnorm( ...
    stage3State(:, positionColumns) - truthState(:, positionColumns), ...
    2, ...
    2);
constvelCumulativeRMSE = sqrt(cumsum(constvelPositionError .^ 2) ./ (1:numel(constvelPositionError)).');
stage3CumulativeRMSE = sqrt(cumsum(stage3PositionError .^ 2) ./ (1:numel(stage3PositionError)).');

constvelColor = [0.0000, 0.3000, 1.0000];
stage3Color = [0.9000, 0.0500, 0.0500];

figure("Name", "Stage 3A Constvel Versus Delta MLP Error");
tiledlayout(2, 1, "TileSpacing", "compact", "Padding", "compact");

nexttile;
hold on;
plot(timeSeconds, constvelPositionError, "Color", constvelColor, "LineWidth", 1.5);
plot(timeSeconds, stage3PositionError, "Color", stage3Color, "LineWidth", 1.5);
hold off;
grid on;
xlabel("Elapsed time [s]");
ylabel("One-step position error [m]");
title("Selected Track One-Step Position Error");
legend(["constvel", "Stage 3A delta MLP"], "Location", "best");

nexttile;
hold on;
plot(timeSeconds, constvelCumulativeRMSE, "Color", constvelColor, "LineWidth", 1.5);
plot(timeSeconds, stage3CumulativeRMSE, "Color", stage3Color, "LineWidth", 1.5);
hold off;
grid on;
xlabel("Elapsed time [s]");
ylabel("Cumulative position RMSE [m]");
title("Selected Track Cumulative Position RMSE");
legend(["constvel", "Stage 3A delta MLP"], "Location", "best");

method = ["constvel"; "Stage 3A delta MLP"];
trackPositionRMSEMeters = [ ...
    sqrt(mean(constvelPositionError .^ 2, "omitnan")); ...
    sqrt(mean(stage3PositionError .^ 2, "omitnan"))];
trackMedianPositionErrorMeters = [ ...
    median(constvelPositionError, "omitnan"); ...
    median(stage3PositionError, "omitnan")];
trackP95PositionErrorMeters = [ ...
    prctile(constvelPositionError, 95); ...
    prctile(stage3PositionError, 95)];

errorComparison = table( ...
    method, ...
    trackPositionRMSEMeters, ...
    trackMedianPositionErrorMeters, ...
    trackP95PositionErrorMeters, ...
    'VariableNames', [ ...
        "method", ...
        "trackPositionRMSEMeters", ...
        "trackMedianPositionErrorMeters", ...
        "trackP95PositionErrorMeters"]);

end
