function helperWriteStage4CRetrainReport(reportPath, summary)
%HELPERWRITESTAGE4CRETRAINREPORT Write the exploratory Stage 4C result.
% In plain language, the experiment asks whether a memoryless neural
% one-step predictor learns useful motion corrections from much more ADS-B
% data. It does not promote a model; the held-out metrics decide whether
% either candidate is better than the native constant-velocity baseline.

reportPath = string(reportPath);
reportFolder = fileparts(reportPath);

if strlength(reportFolder) > 0 && ~isfolder(reportFolder)
    mkdir(reportFolder);
end

headline = localHeadlineMetrics(summary.metrics.table);
splitSummary = summary.splitAudit.summary;
nativeAudit = summary.nativeFunctionAudit;
lines = strings(0, 1);
lines(end + 1) = "# Stage 4C-Retrain: Expanded-3Day Exploratory Mean-MLP Training";
lines(end + 1) = "";
lines(end + 1) = "Generated: " + string(summary.generatedAt);
lines(end + 1) = "";
lines(end + 1) = "## Concept";
lines(end + 1) = "";
lines(end + 1) = ...
    "Each network receives only one previous `[x, vx, y, vy, z, vz]` state, " + ...
    "its six covariance-diagonal values, and `dt`. It predicts the six-state " + ...
    "change to the next ADS-B observation. No trajectory history or ICAO " + ...
    "identifier enters the model.";
lines(end + 1) = "";
lines(end + 1) = ...
    "The scratch candidate learns from a new random initialization. The warm " + ...
    "control begins with the frozen Stage 3A weights after an affine weight " + ...
    "rebase that preserves physical predictions under Expanded-3Day " + ...
    "normalization. Both use fresh Adam state and identical rows/options.";
lines(end + 1) = "";
lines(end + 1) = "## Exploratory Verdict";
lines(end + 1) = "";
lines(end + 1) = summary.exploratoryVerdict;
lines(end + 1) = "";
lines(end + 1) = ...
    "No candidate is promoted by this experiment. Broad-generalization, " + ...
    "learned covariance, recurrent history, and deployment remain deferred.";
lines(end + 1) = "";
lines(end + 1) = "## Native Function Audit";
lines(end + 1) = "";
lines = [lines(:); localTableToMarkdown(nativeAudit)];
lines(end + 1) = "";
lines(end + 1) = "## Frozen Dataset And Split";
lines(end + 1) = "";
lines(end + 1) = "- Dataset: `" + summary.datasetProvenance.datasetPath + "`";
lines(end + 1) = "- Dataset SHA-256: `" + ...
    summary.datasetProvenance.datasetSHA256 + "`";
lines(end + 1) = "- Dataset-variant manifest SHA-256: `" + ...
    summary.datasetProvenance.variantManifestSHA256 + "`";
lines(end + 1) = "- Split manifest: `" + ...
    summary.splitProvenance.splitManifestPath + "`";
lines(end + 1) = "- Split manifest SHA-256: `" + ...
    summary.splitProvenance.splitManifestSHA256 + "`";
lines(end + 1) = "- Source files hash-verified: " + ...
    string(summary.datasetProvenance.sourceHashAuditPassed);
lines(end + 1) = "- Inherited smoke-split ICAOs spanning multiple partitions: " + ...
    string(summary.splitAudit.inheritedOverlappingICAOCount) + ...
    " (ignored)";
lines(end + 1) = "";
lines = [lines(:); localTableToMarkdown(splitSummary)];
lines(end + 1) = "";
lines(end + 1) = "## Model And Optimization";
lines(end + 1) = "";
lines(end + 1) = "- Architecture: `20-64-64-6` with ReLU hidden layers.";
lines(end + 1) = "- Objective: normalized six-state delta MSE through MATLAB `trainnet`.";
lines(end + 1) = "- Optimizer: Adam, learning rate " + ...
    string(summary.trainingOptions.InitialLearnRate) + ...
    ", L2 " + string(summary.trainingOptions.L2Regularization) + ".";
lines(end + 1) = "- Batch size: " + ...
    string(summary.trainingOptions.MiniBatchSize) + ...
    "; maximum epochs: " + string(summary.trainingOptions.MaxEpochs) + ".";
lines(end + 1) = "- Validation: once per epoch, patience " + ...
    string(summary.trainingOptions.ValidationPatience) + ...
    ", output network `best-validation`.";
lines(end + 1) = "- Seed and execution: " + ...
    string(summary.trainingOptions.Seed) + ", `" + ...
    summary.trainingOptions.ExecutionEnvironment + "`.";
lines(end + 1) = "";
lines(end + 1) = "## Pre-Training Checks";
lines(end + 1) = "";
lines(end + 1) = "- Tiny-overfit rows: " + ...
    string(summary.tinyOverfit.sampleCount) + ...
    "; first/final loss: " + ...
    compose("%.6g / %.6g", ...
    summary.tinyOverfit.firstTrainingLoss, ...
    summary.tinyOverfit.finalTrainingLoss) + ...
    "; passed: " + string(summary.tinyOverfit.passed) + ".";
lines(end + 1) = "- Warm-start rebase maximum physical-state difference: " + ...
    compose("%.9g m or m/s", ...
    summary.warmStartRebaseAudit.maxAbsPhysicalStateDifference) + ...
    " (tolerance " + compose("%.9g", ...
    summary.warmStartRebaseAudit.tolerance) + "); passed: " + ...
    string(summary.warmStartRebaseAudit.passed) + ".";
lines(end + 1) = "- Frozen Stage 3A artifact unchanged: " + ...
    string(summary.stage3AIntegrity.unchanged) + ...
    " (`" + summary.stage3AIntegrity.beforeSHA256 + "`).";
lines(end + 1) = "";
lines(end + 1) = "## Held-Out Headline Metrics";
lines(end + 1) = "";
lines(end + 1) = ...
    "These are pair-weighted overall metrics. The complete CSV also contains " + ...
    "independent-event-weighted results and all maneuver, vertical, and " + ...
    "update-rate slices.";
lines(end + 1) = "";
lines = [lines(:); localTableToMarkdown(headline)];
lines(end + 1) = "";
lines(end + 1) = "## Weighting Interpretation";
lines(end + 1) = "";
lines(end + 1) = "- Pair-weighted: " + summary.metrics.pairWeightDefinition;
lines(end + 1) = "- Independent-event-weighted: " + ...
    summary.metrics.eventWeightDefinition;
lines(end + 1) = "- Event boundary: " + summary.metrics.eventDefinition;
lines(end + 1) = "";

if isfield(summary, "nativeManeuverBaseline") && ...
        summary.nativeManeuverBaseline.completed
    lines = [ ...
        lines(:); ...
        localNativeManeuverSection(summary.nativeManeuverBaseline)];
end

lines(end + 1) = "## Outputs";
lines(end + 1) = "";
lines(end + 1) = "- Scratch artifact: `" + summary.scratchArtifactPath + "`";
lines(end + 1) = "- Warm artifact: `" + summary.warmArtifactPath + "`";
lines(end + 1) = "- Compact comparison artifact: `" + ...
    summary.comparisonArtifactPath + "`";
lines(end + 1) = "- Complete metric table: `" + summary.metricTablePath + "`";

if isfield(summary, "figurePaths") && ...
        isfield(summary.figurePaths, "trainingCurves")
    lines(end + 1) = "- Training curves: `" + ...
        string(summary.figurePaths.trainingCurves) + "`";
    lines(end + 1) = "- Representative trajectories: `" + ...
        string(summary.figurePaths.representativeTrajectories) + "`";
end

if isfield(summary, "nativeManeuverBaseline") && ...
        strlength(summary.nativeManeuverBaseline.figurePath) > 0
    lines(end + 1) = "- Native maneuver-baseline comparison: `" + ...
        string(summary.nativeManeuverBaseline.figurePath) + "`";
end

try
    writelines(lines, reportPath);
catch err
    error("Stage4C:ReportWriteFailed", ...
        "Unable to write Stage 4C report %s: %s", reportPath, err.message);
end

end

function lines = localNativeManeuverSection(extension)
%LOCALNATIVEMANEUVERSECTION Explain the evaluation-only native extension.

nonzeroExclusions = extension.exclusionTable( ...
    extension.exclusionTable.reason ~= "eligible" & ...
    extension.exclusionTable.rowCount > 0, :);
metricVariables = [ ...
    "modelID", ...
    "split", ...
    "groupName", ...
    "weighting", ...
    "sampleCount", ...
    "eventCount", ...
    "positionRMSEMeters", ...
    "velocityRMSEMetersPerSecond", ...
    "positionMedianErrorMeters", ...
    "velocityMedianErrorMetersPerSecond", ...
    "positionP95ErrorMeters", ...
    "velocityP95ErrorMetersPerSecond"];
lines = strings(0, 1);
lines(end + 1) = "## Native Maneuver-Baseline Extension";
lines(end + 1) = "";
lines(end + 1) = ...
    "This evaluation-only extension compares native `constacc` on matched " + ...
    "`constacc_like` rows and native `constturn` on matched `constturn_like` " + ...
    "rows. The Stage 3A, scratch, and warm networks remain frozen.";
lines(end + 1) = "";
lines(end + 1) = "- Initialization policy: `" + ...
    extension.policy.policyID + "`.";
lines(end + 1) = ...
    "- Acceleration is the raw three-dimensional velocity finite difference " + ...
    "from the immediately preceding adjacent observation.";
lines(end + 1) = ...
    "- Turn rate is the raw wrapped heading finite difference in degrees per " + ...
    "second, matching the native `constturn` omega convention.";
lines(end + 1) = "- Clipping applied: " + ...
    string(extension.policy.clippingApplied) + ...
    "; smoothing applied: " + ...
    string(extension.policy.smoothingApplied) + ".";
lines(end + 1) = ...
    "- Maneuver labels are retrospective truth-derived evaluation slices. " + ...
    "They never initialize or enter a prediction.";
lines(end + 1) = ...
    "- ICAO is used only for frozen split assignment and same-track " + ...
    "predecessor grouping.";
lines(end + 1) = "";
lines(end + 1) = "### Eligibility Coverage";
lines(end + 1) = "";
lines = [lines(:); localTableToMarkdown(extension.coverageTable)];
lines(end + 1) = "";
lines(end + 1) = ...
    "Only temporally adjacent rows with positive prior `dt`, the same split, " + ...
    "finite causal values, and finite native outputs are scored.";
lines(end + 1) = "";
lines(end + 1) = "### Nonzero Exclusion Reasons";
lines(end + 1) = "";
lines = [lines(:); localTableToMarkdown(nonzeroExclusions)];
lines(end + 1) = "";
lines(end + 1) = "### Raw Initialization Diagnostics";
lines(end + 1) = "";
lines(end + 1) = ...
    "Acceleration quantiles use the 3-D magnitude; turn-rate quantiles use " + ...
    "absolute degrees per second. The outlier upper fence is Q3 + 1.5 IQR " + ...
    "and is descriptive only: outliers remain in the native predictions.";
lines(end + 1) = "";
lines = [ ...
    lines(:); ...
    localTableToMarkdown(extension.initializationDiagnostics)];
lines(end + 1) = "";
lines(end + 1) = ...
    "Raw finite differences amplify ADS-B quantization, timing jitter, and " + ...
    "short-interval velocity changes. Turn-rate spikes are therefore an " + ...
    "expected sensitivity of this baseline, not evidence that the aircraft " + ...
    "physically sustained the reported peak rate. Bounded or smoothed " + ...
    "causal initialization is deferred as a separate sensitivity study.";
lines(end + 1) = "";
lines(end + 1) = "### Matched Held-Out Metrics";
lines(end + 1) = "";
lines(end + 1) = ...
    "Every model in a split/slice section uses exactly the same eligible " + ...
    "rows. Both pair-weighted and independent-event-weighted position and " + ...
    "velocity RMSE, median, and P95 are shown.";
lines(end + 1) = "";
lines = [ ...
    lines(:); ...
    localTableToMarkdown(extension.metrics.table(:, metricVariables))];
lines(end + 1) = "";
lines(end + 1) = "### Frozen-Artifact Integrity";
lines(end + 1) = "";
lines = [ ...
    lines(:); ...
    localTableToMarkdown(extension.frozenArtifactIntegrity)];
lines(end + 1) = "";
lines(end + 1) = ...
    "No training occurred, and this exploratory comparison promotes no model.";
lines(end + 1) = "";

end

function headline = localHeadlineMetrics(metricTable)
%LOCALHEADLINEMETRICS Select overall pair-weighted validation/test rows.

mask = metricTable.groupDimension == "all" & ...
    metricTable.groupName == "all" & ...
    metricTable.weighting == "pair_weighted";
variables = [ ...
    "modelID", ...
    "split", ...
    "sampleCount", ...
    "positionRMSEMeters", ...
    "velocityRMSEMetersPerSecond", ...
    "positionMedianErrorMeters", ...
    "positionP95ErrorMeters"];
headline = metricTable(mask, variables);

end

function lines = localTableToMarkdown(inputTable)
%LOCALTABLETOMARKDOWN Format a compact table without report dependencies.

variableNames = string(inputTable.Properties.VariableNames);
lines = strings(height(inputTable) + 2, 1);
lines(1) = "| " + strjoin(variableNames, " | ") + " |";
lines(2) = "| " + strjoin(repmat("---", 1, width(inputTable)), " | ") + " |";

for rowIdx = 1:height(inputTable)
    values = strings(1, width(inputTable));

    for columnIdx = 1:width(inputTable)
        value = inputTable{rowIdx, columnIdx};

        if iscell(value)
            value = value{1};
        end

        values(columnIdx) = localValueToText(value);
    end

    lines(rowIdx + 2) = "| " + strjoin(values, " | ") + " |";
end

end

function text = localValueToText(value)
%LOCALVALUETOTEXT Convert one table cell to readable Markdown text.

if isnumeric(value)
    if isscalar(value)
        text = compose("%.6g", value);
    else
        text = string(mat2str(value));
    end
elseif islogical(value)
    text = string(value);
elseif isdatetime(value)
    text = string(value);
else
    text = string(value);
end

text = replace(text, "|", "\|");

end
