function figurePaths = helperWriteStage4CRetrainFigures( ...
        outputFolder, ...
        scratchTrainingInfo, ...
        warmTrainingInfo, ...
        nextState, ...
        modelPredictions, ...
        metadata, ...
        maneuverPairTable, ...
        split)
%HELPERWRITESTAGE4CRETRAINFIGURES Plot training and held-out trajectories.
% Training curves expose optimization behavior. Trajectory plots show what
% the one-step predictions mean geometrically on representative validation
% and test aircraft tracks.

outputFolder = string(outputFolder);

if ~isfolder(outputFolder)
    mkdir(outputFolder);
end

figurePaths = struct();
figurePaths.trainingCurves = localWriteTrainingCurves( ...
    outputFolder, ...
    scratchTrainingInfo, ...
    warmTrainingInfo);
figurePaths.representativeTrajectories = localWriteTrajectoryComparison( ...
    outputFolder, ...
    double(nextState), ...
    modelPredictions, ...
    metadata, ...
    maneuverPairTable, ...
    string(split(:)));

end

function outputPath = localWriteTrainingCurves( ...
        outputFolder, scratchTrainingInfo, warmTrainingInfo)
%LOCALWRITETRAININGCURVES Plot train and once-per-epoch validation losses.

figureHandle = figure("Visible", "off");
cleanup = onCleanup(@() close(figureHandle));
layout = tiledlayout(figureHandle, 1, 2, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");
title(layout, "Expanded-3Day mean-MLP training curves");

localPlotOneTrainingCurve(nexttile(layout), scratchTrainingInfo, "Scratch");
localPlotOneTrainingCurve(nexttile(layout), warmTrainingInfo, "Warm start");

outputPath = fullfile(outputFolder, "stage4C_training_curves.png");
exportgraphics(figureHandle, outputPath, "Resolution", 160);

end

function localPlotOneTrainingCurve(axisHandle, trainingInfo, plotTitle)
%LOCALPLOTONETRAININGCURVE Plot one trainnet history.

hold(axisHandle, "on");
trainingHistory = trainingInfo.TrainingHistory;
[epochGroup, ~] = findgroups(trainingHistory.Epoch);
epochIteration = splitapply( ...
    @max, ...
    trainingHistory.Iteration, ...
    epochGroup);
epochLoss = splitapply( ...
    @median, ...
    trainingHistory.Loss, ...
    epochGroup);
plot( ...
    axisHandle, ...
    epochIteration, ...
    epochLoss, ...
    "o-", ...
    "LineWidth", ...
    1.2, ...
    "MarkerSize", ...
    3, ...
    "DisplayName", ...
    "Training epoch median");

validationHistory = trainingInfo.ValidationHistory;

if ~isempty(validationHistory)
    plot( ...
        axisHandle, ...
        validationHistory.Iteration, ...
        validationHistory.Loss, ...
        "o-", ...
        "LineWidth", ...
        1.2, ...
        "MarkerSize", ...
        4, ...
        "DisplayName", ...
        "Validation");
end

set(axisHandle, "YScale", "log");
grid(axisHandle, "on");
xlabel(axisHandle, "Iteration");
ylabel(axisHandle, "Normalized delta MSE");
title(axisHandle, plotTitle);
legend(axisHandle, "Location", "best");
hold(axisHandle, "off");

end

function outputPath = localWriteTrajectoryComparison( ...
        outputFolder, ...
        nextState, ...
        modelPredictions, ...
        metadata, ...
        maneuverPairTable, ...
        split)
%LOCALWRITETRAJECTORYCOMPARISON Plot one validation and one test track.

splitNames = ["validation", "test"];
figureHandle = figure("Visible", "off");
cleanup = onCleanup(@() close(figureHandle));
layout = tiledlayout(figureHandle, 1, 2, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");
title(layout, "Representative held-out one-step trajectory predictions");

for splitIdx = 1:numel(splitNames)
    axisHandle = nexttile(layout);
    splitName = splitNames(splitIdx);
    selectedRows = localSelectRepresentativeTrack( ...
        metadata, ...
        maneuverPairTable, ...
        split, ...
        splitName);
    localPlotTrack( ...
        axisHandle, ...
        selectedRows, ...
        splitName, ...
        nextState, ...
        modelPredictions, ...
        metadata);
end

outputPath = fullfile( ...
    outputFolder, ...
    "stage4C_representative_trajectories.png");
exportgraphics(figureHandle, outputPath, "Resolution", 160);

end

function selectedRows = localSelectRepresentativeTrack( ...
        metadata, maneuverPairTable, split, splitName)
%LOCALSELECTREPRESENTATIVETRACK Prefer a long track with maneuver content.

candidateRows = find(split == splitName);

if isempty(candidateRows)
    selectedRows = zeros(0, 1);
    return;
end

trackKey = string(metadata.sessionID(candidateRows)) + "/" + ...
    string(metadata.hex(candidateRows));
[groupID, trackNames] = findgroups(trackKey);
pairCount = splitapply(@numel, trackKey, groupID);
isManeuver = string(maneuverPairTable.maneuverClass(candidateRows)) ~= ...
    "constvel_like";
maneuverCount = splitapply(@sum, isManeuver, groupID);
selectionScore = maneuverCount + 0.05 .* pairCount;
[~, bestGroup] = max(selectionScore);
selectedRows = candidateRows(groupID == bestGroup);
[~, order] = sort(metadata.timeUtcNext(selectedRows));
selectedRows = selectedRows(order);

if numel(selectedRows) > 500
    selection = unique(round(linspace(1, numel(selectedRows), 500)));
    selectedRows = selectedRows(selection);
end

if isempty(trackNames)
    selectedRows = candidateRows(1:min(100, numel(candidateRows)));
end

end

function localPlotTrack( ...
        axisHandle, ...
        rows, ...
        splitName, ...
        nextState, ...
        modelPredictions, ...
        metadata)
%LOCALPLOTTRACK Draw truth and all four model predictions in local ENU.

if isempty(rows)
    text(axisHandle, 0.5, 0.5, "No " + splitName + " rows", ...
        "HorizontalAlignment", "center");
    axis(axisHandle, "off");
    return;
end

hold(axisHandle, "on");
plot( ...
    axisHandle, ...
    nextState(rows, 1), ...
    nextState(rows, 3), ...
    "k-", ...
    "LineWidth", ...
    2.0, ...
    "DisplayName", ...
    "ADS-B truth");

for modelIdx = 1:numel(modelPredictions)
    prediction = modelPredictions(modelIdx).predictedNextState;
    plot( ...
        axisHandle, ...
        prediction(rows, 1), ...
        prediction(rows, 3), ...
        "-", ...
        "LineWidth", ...
        1.0, ...
        "DisplayName", ...
        localDisplayName(modelPredictions(modelIdx).modelID));
end

axis(axisHandle, "equal");
grid(axisHandle, "on");
xlabel(axisHandle, "East, x (m)");
ylabel(axisHandle, "North, y (m)");
trackLabel = string(metadata.hex(rows(1)));

if strlength(strtrim(string(metadata.callsign(rows(1))))) > 0
    trackLabel = strtrim(string(metadata.callsign(rows(1)))) + ...
        " (" + trackLabel + ")";
end

title(axisHandle, splitName + ": " + trackLabel);
legend(axisHandle, "Location", "best");
hold(axisHandle, "off");

end

function displayName = localDisplayName(modelID)
%LOCALDISPLAYNAME Return compact plot legend labels.

switch string(modelID)
    case "constvel"
        displayName = "constvel";
    case "legacy_stage3a_v1"
        displayName = "Legacy Stage 3A";
    case "expanded_scratch_mean_v1"
        displayName = "Expanded scratch";
    case "expanded_warm_mean_v1"
        displayName = "Expanded warm";
    otherwise
        displayName = string(modelID);
end

end
