function filter = helperInitializeStage4EFilter(detection, modelID)
%HELPERINITIALIZESTAGE4EFILTER Initialize one Stage 4E recursive filter.
% Every model receives the same reported position, velocity, and physical
% six-state covariance. Model-specific latent states start at zero.

modelID = lower(strtrim(string(modelID)));
[initialState, initialCovariance, measurementNoise] = ...
    localInitialConditions(detection);

switch modelID
    case "cv_ekf"
        filter = trackingEKF( ...
            @constvel, ...
            @cvmeas, ...
            initialState, ...
            StateTransitionJacobianFcn=@constveljac, ...
            MeasurementJacobianFcn=@cvmeasjac, ...
            StateCovariance=initialCovariance, ...
            HasAdditiveProcessNoise=false, ...
            ProcessNoise=diag([2, 2, 0.8].^2), ...
            HasAdditiveMeasurementNoise=true, ...
            MeasurementNoise=measurementNoise, ...
            HasMeasurementWrapping=false);
    case "ca_ekf"
        caState = [ ...
            initialState(1:2); ...
            0; ...
            initialState(3:4); ...
            0; ...
            initialState(5:6); ...
            0];
        filter = trackingEKF( ...
            @constacc, ...
            @cameas, ...
            caState, ...
            StateTransitionJacobianFcn=@constaccjac, ...
            MeasurementJacobianFcn=@cameasjac, ...
            StateCovariance=localExpandCACovariance(initialCovariance), ...
            HasAdditiveProcessNoise=false, ...
            ProcessNoise=diag([0.5, 0.5, 0.2].^2), ...
            HasAdditiveMeasurementNoise=true, ...
            MeasurementNoise=measurementNoise, ...
            HasMeasurementWrapping=false);
    case "ct_ekf"
        ctState = [initialState(1:4); 0; initialState(5:6)];
        filter = trackingEKF( ...
            @constturn, ...
            @ctmeas, ...
            ctState, ...
            StateTransitionJacobianFcn=@constturnjac, ...
            MeasurementJacobianFcn=@ctmeasjac, ...
            StateCovariance=localExpandCTCovariance(initialCovariance), ...
            HasAdditiveProcessNoise=false, ...
            ProcessNoise=diag([2, 2, deg2rad(0.5), 0.8].^2), ...
            HasAdditiveMeasurementNoise=true, ...
            MeasurementNoise=measurementNoise, ...
            HasMeasurementWrapping=false);
    case "native_imm"
        nativeFilters = { ...
            helperInitializeStage4EFilter(detection, "cv_ekf"); ...
            helperInitializeStage4EFilter(detection, "ca_ekf"); ...
            helperInitializeStage4EFilter(detection, "ct_ekf")};
        filter = trackingIMM( ...
            TrackingFilters=nativeFilters, ...
            ModelConversionFcn=@switchimm, ...
            TransitionProbabilities=0.95, ...
            ModelNames=["constvel", "constacc", "constturn"], ...
            MeasurementNoise=measurementNoise);
    case "warm_ukf"
        warmContext = helperLoadStage4EWarmContext();
        transitionFcn = @(state, dt) helperStage4EWarmTransition( ...
            state, ...
            dt, ...
            warmContext);
        filter = trackingUKF( ...
            transitionFcn, ...
            @cvmeas, ...
            initialState, ...
            StateCovariance=initialCovariance, ...
            HasAdditiveProcessNoise=true, ...
            ProcessNoise=diag([10, 2, 10, 2, 15, 1].^2), ...
            HasAdditiveMeasurementNoise=true, ...
            MeasurementNoise=measurementNoise, ...
            HasMeasurementWrapping=false);
    otherwise
        error("Stage4E:UnknownFilterModel", ...
            "Unknown Stage 4E filter model: %s", modelID);
end

filter.MeasurementNoise = measurementNoise;

end

function [state, covariance, measurementNoise] = localInitialConditions(detection)
%LOCALINITIALCONDITIONS Read the shared six-state initialization record.

attributes = detection.ObjectAttributes;

if iscell(attributes)
    attributes = attributes{1};
end

requiredFields = ["InitialVelocity", "InitialCovarianceDiag"];

if ~isstruct(attributes) || any(~isfield(attributes, requiredFields))
    error("Stage4E:MissingInitializationAttributes", ...
        "The first detection must carry velocity and covariance attributes.");
end

position = double(detection.Measurement(:));
velocity = double(attributes.InitialVelocity(:));
covarianceDiag = double(attributes.InitialCovarianceDiag(:));

if numel(position) ~= 3 || ...
        numel(velocity) ~= 3 || ...
        numel(covarianceDiag) ~= 6
    error("Stage4E:InvalidInitializationAttributes", ...
        "Initialization requires three-position, three-velocity, and six-covariance values.");
end

state = [ ...
    position(1); ...
    velocity(1); ...
    position(2); ...
    velocity(2); ...
    position(3); ...
    velocity(3)];
covariance = diag(covarianceDiag);
measurementNoise = double(detection.MeasurementNoise);

end

function covariance = localExpandCACovariance(commonCovariance)
%LOCALEXPANDCACOVARIANCE Add unobserved acceleration uncertainty.

commonIndices = [1, 2, 4, 5, 7, 8];
covariance = zeros(9);
covariance(commonIndices, commonIndices) = commonCovariance;
covariance([3, 6, 9], [3, 6, 9]) = 4*eye(3);

end

function covariance = localExpandCTCovariance(commonCovariance)
%LOCALEXPANDCTCOVARIANCE Add unobserved turn-rate uncertainty.

commonIndices = [1, 2, 3, 4, 6, 7];
covariance = zeros(7);
covariance(commonIndices, commonIndices) = commonCovariance;
covariance(5, 5) = deg2rad(2)^2;

end
