function baseline = helperBuildStage4CNativeManeuverBaselines( ...
        previousState, dtSeconds, metadata, split)
%HELPERBUILDSTAGE4CNATIVEMANEUVERBASELINES Build causal native predictions.
% Each row is initialized only from the state observed at that row and the
% immediately preceding observation in the same session/ICAO track.
% Retrospective maneuver labels and the current row's next-state target are
% deliberately absent from this interface, so they cannot leak into either
% native prediction.

previousState = double(previousState);
dtSeconds = double(dtSeconds(:));
split = lower(strtrim(string(split(:))));
localValidateInputs(previousState, dtSeconds, metadata, split);

sampleCount = size(previousState, 1);
predecessorRowIndex = localFindPredecessorRows(metadata);
safePredecessor = max(predecessorRowIndex, 1);

sessionID = string(metadata.sessionID);
icao24 = lower(strtrim(string(metadata.hex)));
timeUtcK = metadata.timeUtcK;
timeUtcNext = metadata.timeUtcNext;

hasPredecessor = predecessorRowIndex > 0;
sameTrack = hasPredecessor & ...
    (sessionID == sessionID(safePredecessor)) & ...
    (icao24 == icao24(safePredecessor));
finiteTimes = ~isnat(timeUtcK) & ...
    ~isnat(timeUtcNext(safePredecessor));
timeOffsetSeconds = seconds( ...
    timeUtcK - timeUtcNext(safePredecessor));
temporalAdjacencyToleranceSeconds = 1e-6;
temporallyAdjacent = sameTrack & ...
    finiteTimes & ...
    isfinite(timeOffsetSeconds) & ...
    (abs(timeOffsetSeconds) <= temporalAdjacencyToleranceSeconds);

priorDtSeconds = dtSeconds(safePredecessor);
finitePriorDt = isfinite(priorDtSeconds);
positivePriorDt = finitePriorDt & (priorDtSeconds > 0);
matchingSplit = ~ismissing(split) & ...
    ~ismissing(split(safePredecessor)) & ...
    (split == split(safePredecessor));
finiteStateValues = all(isfinite(previousState), 2) & ...
    all(isfinite(previousState(safePredecessor, :)), 2);
finiteCurrentDt = isfinite(dtSeconds);
positiveCurrentDt = finiteCurrentDt & (dtSeconds > 0);
finiteGroupingValues = ~ismissing(sessionID) & ...
    ~ismissing(icao24) & ...
    (strlength(strtrim(sessionID)) > 0) & ...
    (strlength(icao24) > 0);

eligibleInput = sameTrack & ...
    temporallyAdjacent & ...
    positivePriorDt & ...
    matchingSplit & ...
    finiteStateValues & ...
    positiveCurrentDt & ...
    finiteGroupingValues;

% Sensor Fusion states are interleaved by Cartesian dimension. The raw
% acceleration estimate therefore uses velocity columns [vx, vy, vz] =
% [2, 4, 6], then enters constacc as
% [x, vx, ax, y, vy, ay, z, vz, az].
velocityColumns = [2, 4, 6];
priorVelocity = previousState(safePredecessor, velocityColumns);
currentVelocity = previousState(:, velocityColumns);
rawAcceleration = NaN(sampleCount, 3);
rawAcceleration(eligibleInput, :) = ...
    (currentVelocity(eligibleInput, :) - ...
    priorVelocity(eligibleInput, :)) ./ ...
    priorDtSeconds(eligibleInput);

% constturn uses mathematical heading measured counter-clockwise from the
% positive x/east axis, and its omega state is in degrees per second.
% wrapTo180 prevents a north-crossing heading from becoming an artificial
% nearly-360-degree turn.
priorHeadingDegrees = atan2d( ...
    priorVelocity(:, 2), ...
    priorVelocity(:, 1));
currentHeadingDegrees = atan2d( ...
    currentVelocity(:, 2), ...
    currentVelocity(:, 1));
rawTurnRateDegreesPerSecond = NaN(sampleCount, 1);
rawTurnRateDegreesPerSecond(eligibleInput) = ...
    wrapTo180( ...
    currentHeadingDegrees(eligibleInput) - ...
    priorHeadingDegrees(eligibleInput)) ./ ...
    priorDtSeconds(eligibleInput);

constaccPredictedState = NaN(sampleCount, 6);
constturnPredictedState = NaN(sampleCount, 6);
eligibleRows = find(eligibleInput);

if ~isempty(eligibleRows)
    constaccInitialState = [ ...
        previousState(eligibleRows, 1), ...
        previousState(eligibleRows, 2), ...
        rawAcceleration(eligibleRows, 1), ...
        previousState(eligibleRows, 3), ...
        previousState(eligibleRows, 4), ...
        rawAcceleration(eligibleRows, 2), ...
        previousState(eligibleRows, 5), ...
        previousState(eligibleRows, 6), ...
        rawAcceleration(eligibleRows, 3)];
    constturnInitialState = [ ...
        previousState(eligibleRows, 1), ...
        previousState(eligibleRows, 2), ...
        previousState(eligibleRows, 3), ...
        previousState(eligibleRows, 4), ...
        rawTurnRateDegreesPerSecond(eligibleRows), ...
        previousState(eligibleRows, 5), ...
        previousState(eligibleRows, 6)];

    % The native functions accept many state columns but one scalar dt.
    % Grouping equal intervals retains the toolbox implementation while
    % avoiding one MATLAB function call per ADS-B row.
    [uniqueDtSeconds, ~, dtGroup] = unique(dtSeconds(eligibleRows));

    for groupIdx = 1:numel(uniqueDtSeconds)
        localRows = find(dtGroup == groupIdx);
        datasetRows = eligibleRows(localRows);
        currentDtSeconds = uniqueDtSeconds(groupIdx);

        predictedConstacc = constacc( ...
            constaccInitialState(localRows, :).', ...
            currentDtSeconds);
        predictedConstturn = constturn( ...
            constturnInitialState(localRows, :).', ...
            currentDtSeconds);

        constaccPredictedState(datasetRows, :) = ...
            predictedConstacc([1, 2, 4, 5, 7, 8], :).';
        constturnPredictedState(datasetRows, :) = ...
            predictedConstturn([1, 2, 3, 4, 6, 7], :).';
    end
end

finiteNativePrediction = ...
    all(isfinite(constaccPredictedState), 2) & ...
    all(isfinite(constturnPredictedState), 2);
eligibleMask = eligibleInput & finiteNativePrediction;
exclusionReason = localBuildExclusionReasons( ...
    sameTrack, ...
    finiteTimes, ...
    temporallyAdjacent, ...
    finitePriorDt, ...
    positivePriorDt, ...
    matchingSplit, ...
    finiteStateValues, ...
    finiteCurrentDt, ...
    positiveCurrentDt, ...
    finiteGroupingValues, ...
    finiteNativePrediction);

baseline = struct();
baseline.policyID = "raw_causal_finite_difference_v1";
baseline.previousStateOrder = ["x", "vx", "y", "vy", "z", "vz"];
baseline.constaccStateOrder = ...
    ["x", "vx", "ax", "y", "vy", "ay", "z", "vz", "az"];
baseline.constturnStateOrder = ...
    ["x", "vx", "y", "vy", "omega_deg_per_s", "z", "vz"];
baseline.predecessorRowIndex = predecessorRowIndex;
baseline.eligibleMask = eligibleMask;
baseline.exclusionReason = exclusionReason;
baseline.rawAccelerationMetersPerSecondSquared = rawAcceleration;
baseline.rawTurnRateDegreesPerSecond = rawTurnRateDegreesPerSecond;
baseline.constaccPredictedState = constaccPredictedState;
baseline.constturnPredictedState = constturnPredictedState;
baseline.temporalAdjacencyToleranceSeconds = ...
    temporalAdjacencyToleranceSeconds;
baseline.smoothingApplied = false;
baseline.clippingApplied = false;
baseline.targetStateUsed = false;
baseline.maneuverLabelUsed = false;
baseline.icaoUse = "same-session/ICAO predecessor grouping only";

end

function predecessorRowIndex = localFindPredecessorRows(metadata)
%LOCALFINDPREDECESSORROWS Find the prior row after deterministic sorting.

sampleCount = height(metadata);
rowIndex = (1:sampleCount).';
ordering = table( ...
    string(metadata.sessionID), ...
    lower(strtrim(string(metadata.hex))), ...
    metadata.timeUtcK, ...
    metadata.timeUtcNext, ...
    rowIndex, ...
    'VariableNames', [ ...
        "sessionID", ...
        "icao24", ...
        "timeUtcK", ...
        "timeUtcNext", ...
        "rowIndex"]);
ordering = sortrows( ...
    ordering, ...
    ["sessionID", "icao24", "timeUtcK", "timeUtcNext", "rowIndex"]);
predecessorRowIndex = zeros(sampleCount, 1);

if sampleCount > 1
    predecessorRowIndex(ordering.rowIndex(2:end)) = ...
        ordering.rowIndex(1:end - 1);
end

end

function reason = localBuildExclusionReasons( ...
        sameTrack, ...
        finiteTimes, ...
        temporallyAdjacent, ...
        finitePriorDt, ...
        positivePriorDt, ...
        matchingSplit, ...
        finiteStateValues, ...
        finiteCurrentDt, ...
        positiveCurrentDt, ...
        finiteGroupingValues, ...
        finiteNativePrediction)
%LOCALBUILDEXCLUSIONREASONS Assign one first-failure reason to every row.

sampleCount = numel(sameTrack);
reason = repmat("eligible", sampleCount, 1);
remaining = true(sampleCount, 1);

failed = remaining & ~sameTrack;
reason(failed) = "first_row_in_track";
remaining(failed) = false;

failed = remaining & (~finiteTimes | ~finiteGroupingValues);
reason(failed) = "nonfinite_input";
remaining(failed) = false;

failed = remaining & ~temporallyAdjacent;
reason(failed) = "nonadjacent_predecessor";
remaining(failed) = false;

failed = remaining & ~finitePriorDt;
reason(failed) = "nonfinite_input";
remaining(failed) = false;

failed = remaining & ~positivePriorDt;
reason(failed) = "nonpositive_prior_dt";
remaining(failed) = false;

failed = remaining & ~matchingSplit;
reason(failed) = "split_mismatch";
remaining(failed) = false;

failed = remaining & (~finiteStateValues | ~finiteCurrentDt);
reason(failed) = "nonfinite_input";
remaining(failed) = false;

failed = remaining & ~positiveCurrentDt;
reason(failed) = "nonpositive_current_dt";
remaining(failed) = false;

failed = remaining & ~finiteNativePrediction;
reason(failed) = "nonfinite_native_prediction";

end

function localValidateInputs(previousState, dtSeconds, metadata, split)
%LOCALVALIDATEINPUTS Validate aligned state-pair inputs without hiding NaNs.

sampleCount = size(previousState, 1);

validateattributes(previousState, ...
    {'numeric'}, {'2d', 'real'}, mfilename, "previousState");
validateattributes(dtSeconds, ...
    {'numeric'}, {'column', 'real'}, mfilename, "dtSeconds");

if size(previousState, 2) ~= 6 || ...
        numel(dtSeconds) ~= sampleCount || ...
        height(metadata) ~= sampleCount || ...
        numel(split) ~= sampleCount
    error("Stage4CNative:InputSizeMismatch", ...
        "Inputs must describe the same N rows with six-state values.");
end

requiredMetadata = ["sessionID", "hex", "timeUtcK", "timeUtcNext"];

if any(~ismember(requiredMetadata, ...
        string(metadata.Properties.VariableNames)))
    error("Stage4CNative:MissingMetadata", ...
        "Metadata must contain sessionID, hex, timeUtcK, and timeUtcNext.");
end

if ~isdatetime(metadata.timeUtcK) || ~isdatetime(metadata.timeUtcNext)
    error("Stage4CNative:InvalidTimestampType", ...
        "timeUtcK and timeUtcNext must be datetime values.");
end

end
