function review = helperBuildStage4EGlobeReview(results, varargin)
%HELPERBUILDSTAGE4EGLOBEREVIEW Build one recursive trajectory collection.
% The review converts a retained synthetic or real ADS-B representative
% sequence to geoTrajectory objects for trackingGlobeViewer.

parser = inputParser;
parser.FunctionName = mfilename;
addRequired(parser, "results", @isstruct);
addParameter(parser, "ViewType", "synthetic");
parse(parser, results, varargin{:});

viewType = lower(localTextScalar(parser.Results.ViewType, "ViewType"));
localValidateResults(results);

switch viewType
    case "synthetic"
        path = results.representativePaths.synthetic;
        referenceDisplayName = "Latent kinematic truth";
        viewLabel = "Synthetic motion-transition coasting";
    case "real_adsb"
        path = results.representativePaths.real;
        referenceDisplayName = "ADS-B scoring proxy";
        viewLabel = "Held-out ADS-B burst outage";
    otherwise
        error("Stage4EGlobe:UnknownViewType", ...
            "ViewType must be synthetic or real_adsb.");
end

if isempty(path)
    error("Stage4EGlobe:MissingRepresentativePath", ...
        "The completed Stage 4E result has no %s representative path.", ...
        viewType);
end

modelIDs = [ ...
    "cv_ekf"; ...
    "ca_ekf"; ...
    "ct_ekf"; ...
    "native_imm"; ...
    "warm_ukf"];
pathFields = [ ...
    "measurement"; ...
    "reference"; ...
    modelIDs];
displayNames = [ ...
    "Position updates"; ...
    referenceDisplayName; ...
    "CV EKF"; ...
    "CA EKF"; ...
    "CT EKF"; ...
    "CV/CA/CT IMM"; ...
    "Frozen-warm UKF"];
colorNames = [ ...
    "gray"; ...
    "green"; ...
    "blue"; ...
    "olive"; ...
    "purple"; ...
    "orange"; ...
    "red"];
statePaths = struct();
llaPaths = struct();
trajectories = struct();
timePaths = struct();
timePaths.measurement = path.measurementTimeSeconds(:);
timePaths.reference = path.timeSeconds(:);
statePaths.measurement = path.measurementState;
statePaths.reference = path.referenceState;

for modelIdx = 1:numel(modelIDs)
    modelField = matlab.lang.makeValidName(modelIDs(modelIdx));
    timePaths.(modelField) = path.timeSeconds(:);
    statePaths.(modelField) = path.modelState.(modelField);
end

for pathIdx = 1:numel(pathFields)
    pathField = matlab.lang.makeValidName(pathFields(pathIdx));
    llaPaths.(pathField) = localStateToLLA( ...
        statePaths.(pathField), ...
        path.receiverOriginLLA);
    trajectories.(pathField) = {geoTrajectory( ...
        llaPaths.(pathField), ...
        timePaths.(pathField), ...
        ReferenceFrame="ENU")};
end

finiteLLA = localAllFinite(llaPaths);
monotonicTime = localAllMonotonic(timePaths);
stateCountsMatch = localStateCountsMatch(statePaths, timePaths);

if ~finiteLLA || ~monotonicTime || ~stateCountsMatch
    error("Stage4EGlobe:InvalidTrajectoryReview", ...
        "A globe path failed finite-position, timing, or row-count checks.");
end

legendTable = table( ...
    pathFields, ...
    displayNames, ...
    colorNames, ...
    ones(numel(pathFields), 1), ...
    'VariableNames', ["pathID", "displayName", "color", "pathCount"]);
validationTable = table( ...
    string(path.caseID), ...
    finiteLLA, ...
    monotonicTime, ...
    stateCountsMatch, ...
    'VariableNames', [ ...
        "caseID", ...
        "finiteLLA", ...
        "monotonicTime", ...
        "stateCountsMatch"]);
summaryTable = table( ...
    viewType, ...
    string(path.profile), ...
    string(path.targetReference), ...
    1, ...
    numel(pathFields), ...
    numel(path.timeSeconds), ...
    numel(path.measurementTimeSeconds), ...
    string(referenceDisplayName), ...
    string(viewLabel), ...
    'VariableNames', [ ...
        "viewType", ...
        "profile", ...
        "targetReference", ...
        "trajectoryCount", ...
        "trajectoryPathCount", ...
        "referenceSampleCount", ...
        "measurementSampleCount", ...
        "scoringReference", ...
        "viewLabel"]);

review = struct();
review.viewType = viewType;
review.label = string(viewLabel);
review.receiverOriginLLA = double(path.receiverOriginLLA);
review.statePaths = statePaths;
review.llaPaths = llaPaths;
review.timePaths = timePaths;
review.trajectories = trajectories;
review.legendTable = legendTable;
review.validationTable = validationTable;
review.summaryTable = summaryTable;
review.recursiveEvaluation = true;
review.trainingPerformed = false;
review.associationEvaluated = false;

end

function lla = localStateToLLA(state, receiverOriginLLA)
%LOCALSTATETOLLA Convert local ENU positions to WGS-84 coordinates.

spheroid = wgs84Ellipsoid("meter");
[latitudeDegrees, longitudeDegrees, altitudeMeters] = enu2geodetic( ...
    state(:, 1), ...
    state(:, 3), ...
    state(:, 5), ...
    receiverOriginLLA(1), ...
    receiverOriginLLA(2), ...
    receiverOriginLLA(3), ...
    spheroid);
lla = [latitudeDegrees, longitudeDegrees, altitudeMeters];

end

function finiteLLA = localAllFinite(llaPaths)
%LOCALALLFINITE Confirm every displayed geodetic path is finite.

pathNames = string(fieldnames(llaPaths));
finiteLLA = true;

for pathIdx = 1:numel(pathNames)
    finiteLLA = finiteLLA && ...
        all(isfinite(llaPaths.(pathNames(pathIdx))), "all");
end

end

function monotonicTime = localAllMonotonic(timePaths)
%LOCALALLMONOTONIC Confirm every trajectory uses increasing timestamps.

pathNames = string(fieldnames(timePaths));
monotonicTime = true;

for pathIdx = 1:numel(pathNames)
    monotonicTime = monotonicTime && ...
        all(diff(timePaths.(pathNames(pathIdx))) > 0);
end

end

function countsMatch = localStateCountsMatch(statePaths, timePaths)
%LOCALSTATECOUNTSMATCH Confirm each path has one time per state sample.

pathNames = string(fieldnames(statePaths));
countsMatch = true;

for pathIdx = 1:numel(pathNames)
    pathName = pathNames(pathIdx);
    countsMatch = countsMatch && ...
        size(statePaths.(pathName), 1) == numel(timePaths.(pathName));
end

end

function localValidateResults(results)
%LOCALVALIDATERESULTS Require completed representative Stage 4E paths.

requiredFields = ["completed", "representativePaths"];

if any(~isfield(results, requiredFields)) || ...
        ~results.completed || ...
        ~isfield(results.representativePaths, "synthetic") || ...
        ~isfield(results.representativePaths, "real")
    error("Stage4EGlobe:InvalidResults", ...
        "A completed Stage 4E result with representative paths is required.");
end

end

function value = localTextScalar(value, argumentName)
%LOCALTEXTSCALAR Normalize one nonempty text option.

isCharacterVector = ischar(value) && isrow(value);
isStringScalar = isstring(value) && isscalar(value);

if (~isCharacterVector && ~isStringScalar)
    error("Stage4EGlobe:InvalidTextOption", ...
        "%s must be a character vector or string scalar.", argumentName);
end

value = strtrim(string(value));

if ismissing(value) || strlength(value) == 0
    error("Stage4EGlobe:InvalidTextOption", ...
        "%s must not be empty.", argumentName);
end

end
