function globeOutput = helperOpenStageReviewGlobe(review, varargin)
%HELPEROPENSTAGEREVIEWGLOBE Plot truth, constvel, and NN trajectories.

parser = inputParser;
parser.FunctionName = mfilename;
addParameter(parser, "TrackHex", review.defaultTrackHex);
addParameter(parser, "MaxPairs", 80);
parse(parser, varargin{:});
opts = parser.Results;

trajectoryData = helperBuildStageReviewTrajectories( ...
    review, ...
    "TrackHex", opts.TrackHex, ...
    "MaxPairs", opts.MaxPairs);

truthColor = [0.0000, 0.6500, 0.2500];
constvelColor = [0.0000, 0.3000, 1.0000];
nnSmokeColor = [0.5500, 0.5500, 0.5500];
stage3Color = [0.9000, 0.0500, 0.0500];

viewer = trackingGlobeViewer( ...
    "ReferenceLocation", trajectoryData.receiverOriginLLA, ...
    "PlatformHistoryDepth", 1000, ...
    "TrackHistoryDepth", 1000);

plotTrajectory( ...
    viewer, ...
    trajectoryData.nnSmokeTrajectory, ...
    "Color", nnSmokeColor, ...
    "LineWidth", int32(2));

if review.hasStage3A
    plotTrajectory( ...
        viewer, ...
        trajectoryData.stage3Trajectory, ...
        "Color", stage3Color, ...
        "LineWidth", int32(3));
end

plotTrajectory( ...
    viewer, ...
    trajectoryData.constvelTrajectory, ...
    "Color", constvelColor, ...
    "LineWidth", int32(3));
plotTrajectory( ...
    viewer, ...
    trajectoryData.truthTrajectory, ...
    "Color", truthColor, ...
    "LineWidth", int32(4));

trajectory = [ ...
    "ADS-B next-state truth"; ...
    "constvel prediction"; ...
    "smoke MLP prediction"];
color = ["green"; "blue"; "gray"];
rgb = [ ...
    string(mat2str(truthColor)); ...
    string(mat2str(constvelColor)); ...
    string(mat2str(nnSmokeColor))];
meaning = [ ...
    "Observed ADS-B-derived next state, drawn last so it stays visible."; ...
    "Native Sensor Fusion constant-velocity one-step prediction."; ...
    "Saved Stage 2B NN smoke output; gray excursions are model failure, not truth."];

if review.hasStage3A
    trajectory = [trajectory; "Stage 3A delta MLP prediction"];
    color = [color; "red"];
    rgb = [rgb; string(mat2str(stage3Color))];
    meaning = [meaning; "Saved Stage 3A delta-target prediction reconstructed as previousState + predictedDelta."];
end

legendTable = table(trajectory, color, rgb, meaning, ...
    'VariableNames', ["trajectory", "color", "rgb", "meaning"]);

colors = struct();
colors.truth = truthColor;
colors.constvel = constvelColor;
colors.nnSmoke = nnSmokeColor;
colors.stage3 = stage3Color;

globeOutput = struct();
globeOutput.viewer = viewer;
globeOutput.trajectoryData = trajectoryData;
globeOutput.legendTable = legendTable;
globeOutput.colors = colors;

end