function positionAbsErrorSummary = helperPlotStage3BPositionAbsError(stage3BSummary, varargin)
%HELPERPLOTSTAGE3BPOSITIONABSERROR Plot all Stage 3B position absolute errors.

parser = inputParser;
parser.FunctionName = mfilename;
addParameter(parser, "Visible", "on");
addParameter(parser, "FigurePath", "");
parse(parser, varargin{:});
opts = parser.Results;

visibleMode = string(opts.Visible);
figurePath = string(opts.FigurePath);

pairErrorTable = stage3BSummary.pairErrorTable;
pairIndex = pairErrorTable.pairIndex;
constvelPositionAbsErrorMeters = pairErrorTable.constvelPositionErrorMeters;
frozenMLPPositionAbsErrorMeters = pairErrorTable.frozenStage3APositionErrorMeters;

figureHandle = figure( ...
    "Name", ...
    "Stage 3B Position Absolute Error", ...
    "Visible", ...
    visibleMode);

hold on;
plot( ...
    pairIndex, ...
    constvelPositionAbsErrorMeters, ...
    ".", ...
    "Color", ...
    [0.0000, 0.3000, 1.0000], ...
    "MarkerSize", ...
    9);
plot( ...
    pairIndex, ...
    frozenMLPPositionAbsErrorMeters, ...
    ".", ...
    "Color", ...
    [0.9000, 0.0500, 0.0500], ...
    "MarkerSize", ...
    9);
hold off;

grid on;
xlabel("Stage 3B state-pair row");
ylabel("Position absolute error [m]");
title("Stage 3B Position Absolute Error: Constvel Versus Frozen MLP");
legend(["constvel", "Frozen Stage 3A MLP"], "Location", "best");

if strlength(figurePath) > 0
    try
        exportgraphics(figureHandle, figurePath, "Resolution", 150);
    catch err
        error("Stage3B:PositionAbsErrorFigureExportFailed", ...
            "Failed to export Stage 3B position absolute error figure: %s", err.message);
    end
end

if visibleMode == "off"
    close(figureHandle);
end

positionAbsErrorSummary = localBuildSummaryTable( ...
    constvelPositionAbsErrorMeters, ...
    frozenMLPPositionAbsErrorMeters);

end

function positionAbsErrorSummary = localBuildSummaryTable(constvelPositionAbsErrorMeters, frozenMLPPositionAbsErrorMeters)
%LOCALBUILDSUMMARYTABLE Summarize plotted position absolute error values.

method = [ ...
    "constvel"; ...
    "Frozen Stage 3A MLP"];
sampleCount = [ ...
    numel(constvelPositionAbsErrorMeters); ...
    numel(frozenMLPPositionAbsErrorMeters)];
medianPositionAbsErrorMeters = [ ...
    median(constvelPositionAbsErrorMeters, "omitnan"); ...
    median(frozenMLPPositionAbsErrorMeters, "omitnan")];
p95PositionAbsErrorMeters = [ ...
    prctile(constvelPositionAbsErrorMeters, 95); ...
    prctile(frozenMLPPositionAbsErrorMeters, 95)];
maxPositionAbsErrorMeters = [ ...
    max(constvelPositionAbsErrorMeters, [], "omitnan"); ...
    max(frozenMLPPositionAbsErrorMeters, [], "omitnan")];

positionAbsErrorSummary = table( ...
    method, ...
    sampleCount, ...
    medianPositionAbsErrorMeters, ...
    p95PositionAbsErrorMeters, ...
    maxPositionAbsErrorMeters, ...
    'VariableNames', [ ...
        "method", ...
        "sampleCount", ...
        "medianPositionAbsErrorMeters", ...
        "p95PositionAbsErrorMeters", ...
        "maxPositionAbsErrorMeters"]);

end
