function evaluation = helperEvaluateStage4ESequences( ...
        sequences, tuning, varargin)
%HELPEREVALUATESTAGE4ESEQUENCES Run recursive filters on matched sequences.
% Each estimator receives identical timestamps, position measurements,
% update masks, scoring rows, and physical six-state initialization.

parser = inputParser;
parser.FunctionName = mfilename;
addRequired(parser, "sequences");
addRequired(parser, "tuning");
addParameter(parser, "Verbose", true);
parse(parser, sequences, tuning, varargin{:});

verbose = logical(parser.Results.Verbose);
localValidateInputs(sequences, tuning);
modelIDs = [ ...
    "cv_ekf"; ...
    "ca_ekf"; ...
    "ct_ekf"; ...
    "native_imm"; ...
    "warm_ukf"];
maximumPartCount = numel(sequences)*numel(modelIDs)*2;
scoreParts = cell(maximumPartCount, 1);
runtimeRows = cell(numel(sequences)*numel(modelIDs), 1);
consistencyRows = cell(numel(sequences)*numel(modelIDs), 1);
inputAuditRows = cell(numel(sequences)*numel(modelIDs), 1);
partIndex = 0;
runIndex = 0;
representativePaths = struct("synthetic", [], "real", []);

for sequenceIdx = 1:numel(sequences)
    sequence = sequences(sequenceIdx);
    inputSignature = localSequenceSignature(sequence);

    if verbose
        fprintf( ...
            "Stage 4E sequence %d/%d:\t%s\n", ...
            sequenceIdx, ...
            numel(sequences), ...
            sequence.caseID);
    end

    for modelIdx = 1:numel(modelIDs)
        modelID = modelIDs(modelIdx);
        runIndex = runIndex + 1;
        runOutput = localRunOneFilter(sequence, modelID, tuning);
        partIndex = partIndex + 1;
        scoreParts{partIndex} = runOutput.priorScores;
        partIndex = partIndex + 1;
        scoreParts{partIndex} = runOutput.posteriorScores;
        runtimeRows{runIndex} = runOutput.runtimeRow;
        consistencyRows{runIndex} = runOutput.consistencyRow;
        inputAuditRows{runIndex} = localInputAuditRow( ...
            sequence, ...
            modelID, ...
            inputSignature, ...
            runOutput);
        representativePaths = localCaptureRepresentative( ...
            representativePaths, ...
            sequence, ...
            modelID, ...
            runOutput.posteriorState);
    end
end

scoreParts = scoreParts(1:partIndex);
evaluation = struct();
evaluation.modelIDs = modelIDs;
evaluation.metricTable = localBuildMetricTable(scoreParts);
evaluation.eventMetricTable = localBuildEventMetricTable(scoreParts);
evaluation.motionMetricTable = localBuildMotionMetricTable(scoreParts);
evaluation.outageAgeMetricTable = localBuildOutageMetricTable(scoreParts);
evaluation.eventWinRateTable = localBuildEventWinRateTable( ...
    evaluation.eventMetricTable);
evaluation.consistencyTable = localSummarizeConsistency( ...
    vertcat(consistencyRows{:}));
evaluation.runtimeTable = localSummarizeRuntime(vertcat(runtimeRows{:}));
evaluation.inputAuditTable = vertcat(inputAuditRows{:});
evaluation.representativePaths = representativePaths;
evaluation.audit = localBuildAudit( ...
    sequences, ...
    evaluation.inputAuditTable, ...
    evaluation.eventMetricTable);

end

function output = localRunOneFilter(sequence, modelID, tuning)
%LOCALRUNONEFILTER Execute predict-score-correct recursion for one model.

initialDetection = localInitialDetection(sequence);
filter = localCreateFilter(initialDetection, modelID, tuning);
[initialState, initialCovariance] = localPhysicalDistribution(filter, modelID);
sampleCount = numel(sequence.timeSeconds);
priorState = NaN(sampleCount, 6);
posteriorState = NaN(sampleCount, 6);
priorCovariance = NaN(6, 6, sampleCount);
posteriorCovariance = NaN(6, 6, sampleCount);
priorState(1, :) = initialState;
posteriorState(1, :) = initialState;
priorCovariance(:, :, 1) = initialCovariance;
posteriorCovariance(:, :, 1) = initialCovariance;
priorOutageAge = NaN(sampleCount, 1);
posteriorOutageAge = NaN(sampleCount, 1);
priorOutageAge(1) = 0;
posteriorOutageAge(1) = 0;
nisValues = NaN(sampleCount, 1);
correctionCount = 1;
divergenceCount = 0;
invalidCovarianceCount = 0;
errorIdentifier = "";
errorMessage = "";
lastCorrectionTime = sequence.timeSeconds(1);
runTimer = tic;

for sampleIdx = 2:sampleCount
    dtSeconds = sequence.timeSeconds(sampleIdx) - ...
        sequence.timeSeconds(sampleIdx - 1);

    try
        predict(filter, dtSeconds);
        [priorState(sampleIdx, :), priorCovariance(:, :, sampleIdx)] = ...
            localPhysicalDistribution(filter, modelID);
        priorOutageAge(sampleIdx) = ...
            sequence.timeSeconds(sampleIdx) - lastCorrectionTime;
        invalidCovarianceCount = invalidCovarianceCount + ...
            ~localIsPositiveDefinite(priorCovariance(:, :, sampleIdx));

        if sequence.updateMask(sampleIdx)
            measurement = sequence.measurementState( ...
                sampleIdx, ...
                [1, 3, 5]).';
            innovation = measurement - ...
                priorState(sampleIdx, [1, 3, 5]).';
            measurementCovariance = ...
                priorCovariance([1, 3, 5], [1, 3, 5], sampleIdx) + ...
                sequence.measurementNoise;
            nisValues(sampleIdx) = ...
                innovation.'*(measurementCovariance\innovation);
            filter.MeasurementNoise = sequence.measurementNoise;
            correct(filter, measurement);
            correctionCount = correctionCount + 1;
            lastCorrectionTime = sequence.timeSeconds(sampleIdx);
        end

        [posteriorState(sampleIdx, :), ...
            posteriorCovariance(:, :, sampleIdx)] = ...
            localPhysicalDistribution(filter, modelID);
        posteriorOutageAge(sampleIdx) = ...
            sequence.timeSeconds(sampleIdx) - lastCorrectionTime;
        invalidCovarianceCount = invalidCovarianceCount + ...
            ~localIsPositiveDefinite(posteriorCovariance(:, :, sampleIdx));

        if any(~isfinite(priorState(sampleIdx, :))) || ...
                any(~isfinite(posteriorState(sampleIdx, :))) || ...
                any(~isfinite(priorCovariance(:, :, sampleIdx)), "all") || ...
                any(~isfinite(posteriorCovariance(:, :, sampleIdx)), "all")
            divergenceCount = divergenceCount + 1;
            break;
        end
    catch err
        divergenceCount = divergenceCount + 1;
        errorIdentifier = string(err.identifier);
        errorMessage = string(err.message);
        break;
    end
end

elapsedSeconds = toc(runTimer);
output = struct();
output.priorScores = localBuildScorePart( ...
    sequence, ...
    modelID, ...
    "prior", ...
    priorState, ...
    priorCovariance, ...
    priorOutageAge, ...
    divergenceCount, ...
    invalidCovarianceCount);
output.posteriorScores = localBuildScorePart( ...
    sequence, ...
    modelID, ...
    "posterior", ...
    posteriorState, ...
    posteriorCovariance, ...
    posteriorOutageAge, ...
    divergenceCount, ...
    invalidCovarianceCount);
validNIS = nisValues(isfinite(nisValues));
output.consistencyRow = table( ...
    sequence.domain, ...
    sequence.profile, ...
    sequence.caseID, ...
    sequence.eventID, ...
    modelID, ...
    numel(validNIS), ...
    {validNIS}, ...
    'VariableNames', [ ...
        "domain", ...
        "profile", ...
        "caseID", ...
        "eventID", ...
        "modelID", ...
        "measurementCount", ...
        "nisValues"]);
output.runtimeRow = table( ...
    sequence.domain, ...
    sequence.profile, ...
    modelID, ...
    sampleCount - 1, ...
    correctionCount, ...
    elapsedSeconds, ...
    errorIdentifier, ...
    errorMessage, ...
    'VariableNames', [ ...
        "domain", ...
        "profile", ...
        "modelID", ...
        "predictionCount", ...
        "correctionCount", ...
        "elapsedSeconds", ...
        "errorIdentifier", ...
        "errorMessage"]);
output.posteriorState = posteriorState;
output.initialState = initialState;
output.initialCovariance = initialCovariance;
output.correctionCount = correctionCount;
output.divergenceCount = divergenceCount;
output.invalidCovarianceCount = invalidCovarianceCount;
output.errorIdentifier = errorIdentifier;
output.errorMessage = errorMessage;

end

function detection = localInitialDetection(sequence)
%LOCALINITIALDETECTION Package common position/velocity initialization.

firstState = double(sequence.measurementState(1, :));
attributes = struct( ...
    "InitialVelocity", firstState([2, 4, 6]), ...
    "InitialCovarianceDiag", double(sequence.initialCovarianceDiag));
detection = objectDetection( ...
    double(sequence.timeSeconds(1)), ...
    firstState([1, 3, 5]).', ...
    MeasurementNoise=double(sequence.measurementNoise), ...
    ObjectAttributes={attributes});

end

function filter = localCreateFilter(detection, modelID, tuning)
%LOCALCREATEFILTER Initialize and apply frozen validation-only parameters.

filter = helperInitializeStage4EFilter(detection, modelID);
parameterField = matlab.lang.makeValidName(modelID);

if ~isfield(tuning.parameters, parameterField)
    error("Stage4E:MissingTunedParameters", ...
        "Tuning does not contain parameters for %s.", modelID);
end

setTunedProperties(filter, tuning.parameters.(parameterField));

end

function [state, covariance] = localPhysicalDistribution(filter, modelID)
%LOCALPHYSICALDISTRIBUTION Convert each filter to common six-state output.

switch modelID
    case {"cv_ekf", "native_imm", "warm_ukf"}
        stateIndices = 1:6;
    case "ca_ekf"
        stateIndices = [1, 2, 4, 5, 7, 8];
    case "ct_ekf"
        stateIndices = [1, 2, 3, 4, 6, 7];
    otherwise
        error("Stage4E:UnknownFilterModel", ...
            "Unknown Stage 4E filter model: %s", modelID);
end

state = double(filter.State(stateIndices).');
covariance = double(filter.StateCovariance(stateIndices, stateIndices));
covariance = 0.5*(covariance + covariance.');

end

function scorePart = localBuildScorePart( ...
        sequence, ...
        modelID, ...
        estimateStage, ...
        estimatedState, ...
        covariance, ...
        outageAge, ...
        divergenceCount, ...
        invalidCovarianceCount)
%LOCALBUILDSCOREPART Compute physical errors on reserved scoring rows.

scoreRows = find(sequence.scoringMask);
referenceState = sequence.referenceState(scoreRows, :);
selectedEstimate = estimatedState(scoreRows, :);
positionError = vecnorm( ...
    selectedEstimate(:, [1, 3, 5]) - ...
    referenceState(:, [1, 3, 5]), ...
    2, ...
    2);
velocityError = vecnorm( ...
    selectedEstimate(:, [2, 4, 6]) - ...
    referenceState(:, [2, 4, 6]), ...
    2, ...
    2);
nees = NaN(numel(scoreRows), 1);
stateCoverage95 = NaN(numel(scoreRows), 1);
positionCoverage95 = NaN(numel(scoreRows), 1);

if sequence.targetReference == "latent_kinematic_truth"
    fullThreshold = chi2inv(0.95, 6);
    positionThreshold = chi2inv(0.95, 3);

    for scoreIdx = 1:numel(scoreRows)
        sourceIdx = scoreRows(scoreIdx);
        stateError = ...
            selectedEstimate(scoreIdx, :) - referenceState(scoreIdx, :);
        stateCovariance = covariance(:, :, sourceIdx);
        positionCovariance = ...
            stateCovariance([1, 3, 5], [1, 3, 5]);
        positionDifference = ...
            stateError([1, 3, 5]);

        if localIsPositiveDefinite(stateCovariance)
            nees(scoreIdx) = stateError/stateCovariance*stateError.';
            stateCoverage95(scoreIdx) = nees(scoreIdx) <= fullThreshold;
        end

        if localIsPositiveDefinite(positionCovariance)
            positionNEES = ...
                positionDifference/positionCovariance*positionDifference.';
            positionCoverage95(scoreIdx) = positionNEES <= positionThreshold;
        end
    end
else
    fullThreshold = NaN;
end

scorePart = struct();
scorePart.domain = sequence.domain;
scorePart.profile = sequence.profile;
scorePart.caseID = sequence.caseID;
scorePart.eventID = sequence.eventID;
scorePart.motionScenario = sequence.motionScenario;
scorePart.targetReference = sequence.targetReference;
scorePart.modelID = modelID;
scorePart.estimateStage = estimateStage;
scorePart.positionError = positionError;
scorePart.velocityError = velocityError;
scorePart.nees = nees;
scorePart.nees95Threshold = fullThreshold;
scorePart.stateCoverage95 = stateCoverage95;
scorePart.positionCoverage95 = positionCoverage95;
scorePart.outageAgeSeconds = outageAge(scoreRows);
scorePart.motionMode = sequence.motionMode(scoreRows);
scorePart.sampleCount = numel(scoreRows);
scorePart.divergenceCount = divergenceCount;
scorePart.invalidCovarianceCount = invalidCovarianceCount;

end

function row = localInputAuditRow( ...
        sequence, modelID, inputSignature, runOutput)
%LOCALINPUTAUDITROW Record identical input and initialization evidence.

initializationValues = [ ...
    runOutput.initialState(:); ...
    diag(runOutput.initialCovariance)];
initializationValues = round(initializationValues, 12, "significant");
initializationValues(initializationValues == 0) = 0;
initializationSignature = localNumericSignature(initializationValues);
row = table( ...
    sequence.domain, ...
    sequence.profile, ...
    sequence.caseID, ...
    sequence.eventID, ...
    modelID, ...
    inputSignature, ...
    initializationSignature, ...
    numel(sequence.timeSeconds), ...
    sum(sequence.updateMask), ...
    sum(sequence.scoringMask), ...
    runOutput.correctionCount, ...
    runOutput.divergenceCount, ...
    runOutput.invalidCovarianceCount, ...
    runOutput.errorIdentifier, ...
    runOutput.errorMessage, ...
    'VariableNames', [ ...
        "domain", ...
        "profile", ...
        "caseID", ...
        "eventID", ...
        "modelID", ...
        "inputSignature", ...
        "initializationSignature", ...
        "timestampCount", ...
        "scheduledCorrectionCount", ...
        "scoringCount", ...
        "actualCorrectionCount", ...
        "divergenceCount", ...
        "invalidCovarianceCount", ...
        "errorIdentifier", ...
        "errorMessage"]);

end

function signature = localSequenceSignature(sequence)
%LOCALSEQUENCESIGNATURE Hash timestamps, measurements, and score/update masks.

numericPayload = [ ...
    double(sequence.timeSeconds(:)); ...
    double(sequence.measurementState(:)); ...
    double(sequence.updateMask(:)); ...
    double(sequence.scoringMask(:)); ...
    double(sequence.referenceState(:))];
signature = localNumericSignature(numericPayload);

end

function signature = localNumericSignature(values)
%LOCALNUMERICSIGNATURE Compute a deterministic SHA-256 for numeric values.

digest = java.security.MessageDigest.getInstance("SHA-256");
bytes = typecast(double(values(:)), "int8");
digest.update(bytes);
hashBytes = uint8(mod(double(digest.digest()), 256));
signature = string(reshape(dec2hex(hashBytes, 2).', 1, []));

end

function tableOut = localBuildMetricTable(parts)
%LOCALBUILDMETRICTABLE Aggregate sample errors by benchmark condition.

metadata = localPartMetadata(parts, false);
[groupIndex, groupTable] = findgroups( ...
    metadata(:, [ ...
        "domain", ...
        "profile", ...
        "modelID", ...
        "estimateStage", ...
        "targetReference"]));
rows = cell(height(groupTable), 1);

for groupIdx = 1:height(groupTable)
    selectedParts = [parts{groupIndex == groupIdx}];
    positionError = vertcat(selectedParts.positionError);
    velocityError = vertcat(selectedParts.velocityError);
    nees = vertcat(selectedParts.nees);
    stateCoverage = vertcat(selectedParts.stateCoverage95);
    coverage = vertcat(selectedParts.positionCoverage95);
    rows{groupIdx} = localMetricRow( ...
        groupTable(groupIdx, :), ...
        positionError, ...
        velocityError, ...
        nees, ...
        stateCoverage, ...
        coverage, ...
        numel(selectedParts), ...
        sum([selectedParts.divergenceCount]), ...
        sum([selectedParts.invalidCovarianceCount]));
end

tableOut = vertcat(rows{:});

end

function tableOut = localBuildEventMetricTable(parts)
%LOCALBUILDEVENTMETRICTABLE Report one metric row per event and stage.

rows = cell(numel(parts), 1);

for partIdx = 1:numel(parts)
    part = parts{partIdx};
    metadata = table( ...
        part.domain, ...
        part.profile, ...
        part.modelID, ...
        part.estimateStage, ...
        part.targetReference, ...
        'VariableNames', [ ...
            "domain", ...
            "profile", ...
            "modelID", ...
            "estimateStage", ...
            "targetReference"]);
    rows{partIdx} = localMetricRow( ...
        metadata, ...
        part.positionError, ...
        part.velocityError, ...
        part.nees, ...
        part.stateCoverage95, ...
        part.positionCoverage95, ...
        1, ...
        part.divergenceCount, ...
        part.invalidCovarianceCount);
    rows{partIdx}.caseID = part.caseID;
    rows{partIdx}.eventID = part.eventID;
    rows{partIdx}.motionScenario = part.motionScenario;
end

tableOut = vertcat(rows{:});
tableOut = movevars( ...
    tableOut, ...
    ["caseID", "eventID", "motionScenario"], ...
    After="profile");

end

function tableOut = localBuildMotionMetricTable(parts)
%LOCALBUILDMOTIONMETRICTABLE Summarize synthetic error by truth motion mode.

maximumRowCount = sum(cellfun( ...
    @(part) numel(unique(part.motionMode)), ...
    parts));
rows = cell(maximumRowCount, 1);
rowIndex = 0;

for partIdx = 1:numel(parts)
    part = parts{partIdx};

    if part.targetReference ~= "latent_kinematic_truth"
        continue;
    end

    motionModes = unique(part.motionMode, "stable");

    for modeIdx = 1:numel(motionModes)
        rowMask = part.motionMode == motionModes(modeIdx);
        rowIndex = rowIndex + 1;
        rows{rowIndex} = localDistributionRow( ...
            part, ...
            "motionMode", ...
            motionModes(modeIdx), ...
            rowMask);
    end
end

tableOut = vertcat(rows{1:rowIndex});

end

function tableOut = localBuildOutageMetricTable(parts)
%LOCALBUILDOUTAGEMETRICTABLE Summarize error as correction age increases.

maximumRowCount = numel(parts)*5;
rows = cell(maximumRowCount, 1);
rowIndex = 0;

for partIdx = 1:numel(parts)
    part = parts{partIdx};
    [outageBin, outageOrder] = localOutageBins(part.outageAgeSeconds);

    for binIdx = 1:numel(outageOrder)
        rowMask = outageBin == outageOrder(binIdx);

        if any(rowMask)
            rowIndex = rowIndex + 1;
            rows{rowIndex} = localDistributionRow( ...
                part, ...
                "outageAgeBin", ...
                outageOrder(binIdx), ...
                rowMask);
        end
    end
end

tableOut = vertcat(rows{1:rowIndex});

end

function row = localDistributionRow(part, groupingName, groupingValue, rowMask)
%LOCALDISTRIBUTIONROW Build one event-level conditional error summary.

positionError = part.positionError(rowMask);
velocityError = part.velocityError(rowMask);
row = table( ...
    part.domain, ...
    part.profile, ...
    part.caseID, ...
    part.eventID, ...
    part.modelID, ...
    part.estimateStage, ...
    string(groupingValue), ...
    numel(positionError), ...
    localRMSE(positionError), ...
    median(positionError, "omitnan"), ...
    prctile(positionError, 95), ...
    localRMSE(velocityError), ...
    median(velocityError, "omitnan"), ...
    prctile(velocityError, 95), ...
    'VariableNames', [ ...
        "domain", ...
        "profile", ...
        "caseID", ...
        "eventID", ...
        "modelID", ...
        "estimateStage", ...
        string(groupingName), ...
        "sampleCount", ...
        "positionRMSEMeters", ...
        "positionMedianErrorMeters", ...
        "positionP95ErrorMeters", ...
        "velocityRMSEMetersPerSecond", ...
        "velocityMedianErrorMetersPerSecond", ...
        "velocityP95ErrorMetersPerSecond"]);

end

function row = localMetricRow( ...
        metadata, ...
        positionError, ...
        velocityError, ...
        nees, ...
        stateCoverage, ...
        coverage, ...
        eventCount, ...
        divergenceCount, ...
        invalidCovarianceCount)
%LOCALMETRICROW Build one score summary row.

validNEES = nees(isfinite(nees));
validStateCoverage = stateCoverage(isfinite(stateCoverage));
validCoverage = coverage(isfinite(coverage));
row = [ ...
    metadata, ...
    table( ...
        numel(positionError), ...
        eventCount, ...
        localRMSE(positionError), ...
        median(positionError, "omitnan"), ...
        prctile(positionError, 95), ...
        localRMSE(velocityError), ...
        median(velocityError, "omitnan"), ...
        prctile(velocityError, 95), ...
        mean(validNEES, "omitnan"), ...
        mean(validStateCoverage, "omitnan"), ...
        mean(validCoverage, "omitnan"), ...
        divergenceCount, ...
        invalidCovarianceCount, ...
        'VariableNames', [ ...
            "sampleCount", ...
            "eventCount", ...
            "positionRMSEMeters", ...
            "positionMedianErrorMeters", ...
            "positionP95ErrorMeters", ...
            "velocityRMSEMetersPerSecond", ...
            "velocityMedianErrorMetersPerSecond", ...
            "velocityP95ErrorMetersPerSecond", ...
            "meanNEES", ...
            "stateCoverage95", ...
            "positionCoverage95", ...
            "divergenceCount", ...
            "invalidCovarianceCount"])];

end

function metadata = localPartMetadata(parts, includeEvent)
%LOCALPARTMETADATA Convert score-part labels to a compact table.

partCount = numel(parts);
domain = strings(partCount, 1);
profile = strings(partCount, 1);
modelID = strings(partCount, 1);
estimateStage = strings(partCount, 1);
targetReference = strings(partCount, 1);
caseID = strings(partCount, 1);
eventID = strings(partCount, 1);

for partIdx = 1:partCount
    part = parts{partIdx};
    domain(partIdx) = part.domain;
    profile(partIdx) = part.profile;
    modelID(partIdx) = part.modelID;
    estimateStage(partIdx) = part.estimateStage;
    targetReference(partIdx) = part.targetReference;
    caseID(partIdx) = part.caseID;
    eventID(partIdx) = part.eventID;
end

metadata = table( ...
    domain, ...
    profile, ...
    modelID, ...
    estimateStage, ...
    targetReference);

if includeEvent
    metadata.caseID = caseID;
    metadata.eventID = eventID;
end

end

function tableOut = localBuildEventWinRateTable(eventMetrics)
%LOCALBUILDEVENTWINRATETABLE Count posterior event-level RMSE wins.

posteriorRows = eventMetrics(eventMetrics.estimateStage == "posterior", :);
[conditionIndex, conditions] = findgroups( ...
    posteriorRows(:, ["domain", "profile"]));
maximumModelCount = numel(unique(posteriorRows.modelID));
rows = cell(height(conditions)*maximumModelCount, 1);
rowIndex = 0;

for conditionIdx = 1:height(conditions)
    conditionRows = posteriorRows(conditionIndex == conditionIdx, :);
    eventKeys = unique(conditionRows.caseID, "stable");
    modelIDs = unique(conditionRows.modelID, "stable");
    winCount = zeros(numel(modelIDs), 1);

    for eventIdx = 1:numel(eventKeys)
        eventRows = conditionRows(conditionRows.caseID == eventKeys(eventIdx), :);
        finiteError = eventRows.positionRMSEMeters;
        finiteError = finiteError(isfinite(finiteError));

        if isempty(finiteError)
            continue;
        end

        bestError = min(finiteError);
        winners = eventRows.modelID( ...
            abs(eventRows.positionRMSEMeters - bestError) <= 1e-9);
        winCount(ismember(modelIDs, winners)) = ...
            winCount(ismember(modelIDs, winners)) + 1/numel(winners);
    end

    for modelIdx = 1:numel(modelIDs)
        rowIndex = rowIndex + 1;
        rows{rowIndex} = table( ...
            conditions.domain(conditionIdx), ...
            conditions.profile(conditionIdx), ...
            modelIDs(modelIdx), ...
            numel(eventKeys), ...
            winCount(modelIdx), ...
            winCount(modelIdx)/numel(eventKeys), ...
            'VariableNames', [ ...
                "domain", ...
                "profile", ...
                "modelID", ...
                "eventCount", ...
                "eventWinCount", ...
                "eventWinRate"]);
    end
end

tableOut = vertcat(rows{1:rowIndex});

end

function tableOut = localSummarizeConsistency(eventRows)
%LOCALSUMMARIZECONSISTENCY Aggregate NIS by condition and model.

[groupIndex, groupTable] = findgroups( ...
    eventRows(:, ["domain", "profile", "modelID"]));
rows = cell(height(groupTable), 1);
threshold = chi2inv(0.95, 3);

for groupIdx = 1:height(groupTable)
    values = vertcat(eventRows.nisValues{groupIndex == groupIdx});
    rows{groupIdx} = [ ...
        groupTable(groupIdx, :), ...
        table( ...
            numel(values), ...
            mean(values, "omitnan"), ...
            median(values, "omitnan"), ...
            prctile(values, 95), ...
            mean(values <= threshold, "omitnan"), ...
            threshold, ...
            'VariableNames', [ ...
                "measurementCount", ...
                "meanNIS", ...
                "medianNIS", ...
                "p95NIS", ...
                "nisCoverage95", ...
                "nis95Threshold"])];
end

tableOut = vertcat(rows{:});

end

function tableOut = localSummarizeRuntime(eventRows)
%LOCALSUMMARIZERUNTIME Aggregate elapsed time by condition and model.

[groupIndex, groupTable] = findgroups( ...
    eventRows(:, ["domain", "profile", "modelID"]));
rows = cell(height(groupTable), 1);

for groupIdx = 1:height(groupTable)
    rowMask = groupIndex == groupIdx;
    predictionCount = sum(eventRows.predictionCount(rowMask));
    correctionCount = sum(eventRows.correctionCount(rowMask));
    elapsedSeconds = sum(eventRows.elapsedSeconds(rowMask));
    rows{groupIdx} = [ ...
        groupTable(groupIdx, :), ...
        table( ...
            predictionCount, ...
            correctionCount, ...
            elapsedSeconds, ...
            1e6*elapsedSeconds/max(1, predictionCount), ...
            'VariableNames', [ ...
                "predictionCount", ...
                "correctionCount", ...
                "elapsedSeconds", ...
                "microsecondsPerPrediction"])];
end

tableOut = vertcat(rows{:});

end

function [outageBin, order] = localOutageBins(outageAgeSeconds)
%LOCALOUTAGEBINS Assign correction-age ranges used by coasting plots.

order = [ ...
    "corrected_now"; ...
    "0_to_5_s"; ...
    "5_to_15_s"; ...
    "15_to_30_s"; ...
    "over_30_s"];
outageBin = repmat("over_30_s", numel(outageAgeSeconds), 1);
outageBin(outageAgeSeconds <= 0) = "corrected_now";
outageBin(outageAgeSeconds > 0 & outageAgeSeconds <= 5) = "0_to_5_s";
outageBin(outageAgeSeconds > 5 & outageAgeSeconds <= 15) = "5_to_15_s";
outageBin(outageAgeSeconds > 15 & outageAgeSeconds <= 30) = "15_to_30_s";

end

function value = localRMSE(errorMagnitude)
%LOCALRMSE Compute root-mean-square magnitude while omitting failures.

value = sqrt(mean(errorMagnitude.^2, "omitnan"));

end

function representativePaths = localCaptureRepresentative( ...
        representativePaths, sequence, modelID, posteriorState)
%LOCALCAPTUREREPRESENTATIVE Keep one synthetic and one real path.

isSyntheticRepresentative = ...
    sequence.domain == "synthetic_canonical" && ...
    sequence.profile == "degraded" && ...
    sequence.motionScenario == "motion_transitions";
isRealRepresentative = ...
    sequence.domain == "real_adsb" && ...
    sequence.profile == "burst_outage" && ...
    (isempty(representativePaths.real) || ...
    sequence.caseID == representativePaths.real.caseID);

if isSyntheticRepresentative
    fieldName = "synthetic";
elseif isRealRepresentative
    fieldName = "real";
else
    return;
end

if isempty(representativePaths.(fieldName))
    path = struct();
    path.domain = sequence.domain;
    path.profile = sequence.profile;
    path.caseID = sequence.caseID;
    path.targetReference = sequence.targetReference;
    path.receiverOriginLLA = sequence.receiverOriginLLA;
    path.timeSeconds = sequence.timeSeconds;
    path.referenceState = sequence.referenceState;
    path.measurementTimeSeconds = ...
        sequence.timeSeconds(sequence.updateMask);
    path.measurementState = ...
        sequence.measurementState(sequence.updateMask, :);
    path.modelState = struct();
    representativePaths.(fieldName) = path;
end

modelField = matlab.lang.makeValidName(modelID);
representativePaths.(fieldName).modelState.(modelField) = posteriorState;

end

function audit = localBuildAudit(sequences, inputAuditTable, eventMetricTable)
%LOCALBUILDAUDIT Consolidate recursive execution invariants.

[sequenceGroup, ~] = findgroups( ...
    inputAuditTable(:, ["domain", "profile", "caseID"]));
identicalInputs = splitapply( ...
    @(value) isscalar(unique(value)), ...
    inputAuditTable.inputSignature, ...
    sequenceGroup);
identicalInitialization = splitapply( ...
    @(value) isscalar(unique(value)), ...
    inputAuditTable.initializationSignature, ...
    sequenceGroup);
realMask = string({sequences.domain}).' == "real_adsb";
realSequences = sequences(realMask);
scoringNeverCorrected = true;
sameRealScoringRows = true;

if ~isempty(realSequences)
    for sequenceIdx = 1:numel(realSequences)
        scoringNeverCorrected = scoringNeverCorrected && ...
            ~any(realSequences(sequenceIdx).scoringMask & ...
            realSequences(sequenceIdx).updateMask);
    end

    eventIDs = unique(string({realSequences.eventID}), "stable");

    for eventIdx = 1:numel(eventIDs)
        selected = realSequences( ...
            string({realSequences.eventID}) == eventIDs(eventIdx));
        referenceMask = selected(1).scoringMask;

        for profileIdx = 2:numel(selected)
            sameRealScoringRows = sameRealScoringRows && ...
                isequal(selected(profileIdx).scoringMask, referenceMask);
        end
    end
end

audit = struct();
audit.identicalInputsAcrossFilters = all(identicalInputs);
audit.identicalInitializationAcrossFilters = all(identicalInitialization);
audit.scheduledCorrectionsApplied = all( ...
    inputAuditTable.actualCorrectionCount == ...
    inputAuditTable.scheduledCorrectionCount);
audit.scoringReportsNeverCorrected = scoringNeverCorrected;
audit.sameRealScoringRowsAcrossProfiles = sameRealScoringRows;
audit.monotonicTime = all(arrayfun( ...
    @(sequence) all(diff(sequence.timeSeconds) > 0), ...
    sequences));
audit.finiteStates = ...
    all(eventMetricTable.divergenceCount == 0) && ...
    all(strlength(inputAuditTable.errorIdentifier) == 0) && ...
    all(isfinite(eventMetricTable.positionRMSEMeters)) && ...
    all(isfinite(eventMetricTable.velocityRMSEMetersPerSecond));
audit.positiveDefiniteCovariance = ...
    all(eventMetricTable.invalidCovarianceCount == 0);
audit.coastingOccurred = any(arrayfun( ...
    @(sequence) any(~sequence.updateMask(2:end)), ...
    sequences));

end

function tf = localIsPositiveDefinite(covariance)
%LOCALISPOSITIVEDEFINITE Check finite symmetric positive definiteness.

if any(~isfinite(covariance), "all")
    tf = false;
    return;
end

covariance = 0.5*(covariance + covariance.');
[~, flag] = chol(covariance);
tf = flag == 0;

end

function localValidateInputs(sequences, tuning)
%LOCALVALIDATEINPUTS Enforce the recursive-sequence and tuning contracts.

requiredFields = [ ...
    "domain", ...
    "profile", ...
    "caseID", ...
    "eventID", ...
    "timeSeconds", ...
    "referenceState", ...
    "measurementState", ...
    "updateMask", ...
    "scoringMask", ...
    "measurementNoise", ...
    "initialCovarianceDiag", ...
    "motionMode", ...
    "motionScenario", ...
    "targetReference", ...
    "receiverOriginLLA"];

if ~isstruct(sequences) || ...
        isempty(sequences) || ...
        any(~isfield(sequences, requiredFields))
    error("Stage4E:InvalidSequences", ...
        "Recursive sequences are missing required fields.");
end

if ~isstruct(tuning) || ...
        ~isfield(tuning, "completed") || ...
        ~tuning.completed || ...
        ~isfield(tuning, "parameters")
    error("Stage4E:InvalidTuning", ...
        "Completed frozen Stage 4E tuning parameters are required.");
end

end
