function trackDiagnostics = helperBuildStageReviewTrackDiagnostics(review)
%HELPERBUILDSTAGEREVIEWTRACKDIAGNOSTICS Pick review tracks from metrics.

pairTable = review.pairReviewTable;
[groupID, hex, callsign] = findgroups(pairTable.hex, pairTable.callsign);

pairCount = splitapply(@numel, pairTable.constvelPositionErrorMeters, groupID);
meanConstvelPositionErrorMeters = splitapply(@mean, pairTable.constvelPositionErrorMeters, groupID);
medianConstvelPositionErrorMeters = splitapply(@median, pairTable.constvelPositionErrorMeters, groupID);
meanNNSmokePositionErrorMeters = splitapply(@mean, pairTable.nnSmokePositionErrorMeters, groupID);
medianNNSmokePositionErrorMeters = splitapply(@median, pairTable.nnSmokePositionErrorMeters, groupID);
constvelLikePairCount = splitapply( ...
    @(values) sum(string(values) == "constvel_like"), ...
    pairTable.maneuverClass, ...
    groupID);
constturnLikePairCount = splitapply( ...
    @(values) sum(string(values) == "constturn_like"), ...
    pairTable.maneuverClass, ...
    groupID);
mixedOrSparsePairCount = splitapply( ...
    @(values) sum(string(values) == "mixed_or_sparse"), ...
    pairTable.maneuverClass, ...
    groupID);

trackTable = table( ...
    hex, ...
    callsign, ...
    pairCount, ...
    constvelLikePairCount, ...
    constturnLikePairCount, ...
    mixedOrSparsePairCount, ...
    meanConstvelPositionErrorMeters, ...
    medianConstvelPositionErrorMeters, ...
    meanNNSmokePositionErrorMeters, ...
    medianNNSmokePositionErrorMeters, ...
    'VariableNames', [ ...
        "hex", ...
        "callsign", ...
        "pairCount", ...
        "constvelLikePairCount", ...
        "constturnLikePairCount", ...
        "mixedOrSparsePairCount", ...
        "meanConstvelPositionErrorMeters", ...
        "medianConstvelPositionErrorMeters", ...
        "meanNNSmokePositionErrorMeters", ...
        "medianNNSmokePositionErrorMeters"]);

constvelShare = constvelLikePairCount ./ pairCount;
easyCandidate = pairCount >= 40 & constvelShare >= 0.70;

if any(easyCandidate)
    easyTable = trackTable(easyCandidate, :);
    easyTable = sortrows( ...
        easyTable, ...
        ["medianConstvelPositionErrorMeters", "pairCount"], ...
        ["ascend", "descend"]);
else
    easyTable = sortrows( ...
        trackTable, ...
        ["medianConstvelPositionErrorMeters", "pairCount"], ...
        ["ascend", "descend"]);
end

[~, turnIdx] = max(trackTable.constturnLikePairCount);

trackDiagnostics = struct();
trackDiagnostics.trackTable = sortrows( ...
    trackTable, ...
    ["pairCount", "medianConstvelPositionErrorMeters"], ...
    ["descend", "ascend"]);
trackDiagnostics.easyTrackHex = string(easyTable.hex(1));
trackDiagnostics.turnDiagnosticTrackHex = string(trackTable.hex(turnIdx));
trackDiagnostics.selectionNote = sprintf( ...
    "Easy track %s was selected from tracks with at least 40 pairs and at least 70%% constvel-like labels, using lowest median constvel position error. Turn diagnostic track %s has the most constturn-like pairs.", ...
    trackDiagnostics.easyTrackHex, ...
    trackDiagnostics.turnDiagnosticTrackHex);

end
