function pairData = helperBuildLocalADSBStatePairs(adsbTracks, sourceFile, sessionID, receiverOriginLLA, covarianceStdAssumed, maxDtSeconds)
%HELPERBUILDLOCALADSBSTATEPAIRS Convert ADS-B tracks into one-step ENU pairs.
% Each aircraft track is converted from geodetic coordinates into a local ENU
% frame. The state order is the Sensor Fusion constant-velocity convention:
% [x; vx; y; vy; z; vz].

sourceFile = string(sourceFile);
sessionID = string(sessionID);
receiverOriginLLA = double(receiverOriginLLA);
covarianceStdAssumed = double(covarianceStdAssumed);
maxDtSeconds = double(maxDtSeconds);

validateattributes(receiverOriginLLA, {'numeric'}, {'numel', 3, 'real', 'finite'}, ...
    mfilename, "receiverOriginLLA");
validateattributes(covarianceStdAssumed, {'numeric'}, {'numel', 6, 'real', 'finite', 'positive'}, ...
    mfilename, "covarianceStdAssumed");

if isempty(adsbTracks)
    pairData = localEmptyPairData(covarianceStdAssumed);
    return;
end

sampleTable = localBuildSampleTable(adsbTracks, sourceFile, sessionID, receiverOriginLLA);
pairData = localBuildPairsFromSamples(sampleTable, covarianceStdAssumed, maxDtSeconds);
pairData.aircraftCount = numel(adsbTracks);

end

function sampleTable = localBuildSampleTable(adsbTracks, sourceFile, sessionID, receiverOriginLLA)
%LOCALBUILDSAMPLETABLE Build one row per ADS-B position fix.

sampleCount = 0;

for trackIdx = 1:numel(adsbTracks)
    sampleCount = sampleCount + numel(adsbTracks(trackIdx).t_utc);
end

sessionColumn = strings(sampleCount, 1);
sourceColumn = strings(sampleCount, 1);
hexColumn = strings(sampleCount, 1);
callsignColumn = strings(sampleCount, 1);
timeUtcColumn = NaT(sampleCount, 1, "TimeZone", "UTC");
tUnixColumn = NaN(sampleCount, 1);
receiverOriginColumn = NaN(sampleCount, 3);
latColumn = NaN(sampleCount, 1);
lonColumn = NaN(sampleCount, 1);
altColumn = NaN(sampleCount, 1);
speedColumn = NaN(sampleCount, 1);
trackColumn = NaN(sampleCount, 1);
vrateColumn = NaN(sampleCount, 1);
xColumn = NaN(sampleCount, 1);
yColumn = NaN(sampleCount, 1);
zColumn = NaN(sampleCount, 1);
vxColumn = NaN(sampleCount, 1);
vyColumn = NaN(sampleCount, 1);
vzColumn = NaN(sampleCount, 1);
stateFiniteColumn = false(sampleCount, 1);

spheroid = wgs84Ellipsoid("meter");
nextRow = 1;

for trackIdx = 1:numel(adsbTracks)
    track = adsbTracks(trackIdx);
    trackSampleCount = numel(track.t_utc);

    if trackSampleCount == 0
        continue;
    end

    rowIdx = nextRow:(nextRow + trackSampleCount - 1);
    nextRow = nextRow + trackSampleCount;

    tUnix = double(track.t_utc(:));
    latDeg = double(track.lat_deg(:));
    lonDeg = double(track.lon_deg(:));
    altMeters = double(track.alt_m(:));
    speedMetersPerSecond = double(track.speed_mps(:));
    trackDegrees = double(track.track_deg(:));
    verticalRateMetersPerSecond = double(track.vrate_mps(:));

    eastMeters = NaN(trackSampleCount, 1);
    northMeters = NaN(trackSampleCount, 1);
    upMeters = NaN(trackSampleCount, 1);

    validGeodetic = isfinite(latDeg) & isfinite(lonDeg) & isfinite(altMeters);

    if any(validGeodetic)
        [eastMeters(validGeodetic), northMeters(validGeodetic), upMeters(validGeodetic)] = geodetic2enu( ...
            latDeg(validGeodetic), ...
            lonDeg(validGeodetic), ...
            altMeters(validGeodetic), ...
            receiverOriginLLA(1), ...
            receiverOriginLLA(2), ...
            receiverOriginLLA(3), ...
            spheroid);
    end

    vxMetersPerSecond = speedMetersPerSecond .* sind(trackDegrees);
    vyMetersPerSecond = speedMetersPerSecond .* cosd(trackDegrees);
    vzMetersPerSecond = verticalRateMetersPerSecond;

    requiredFinite = ...
        isfinite(tUnix) & ...
        isfinite(latDeg) & ...
        isfinite(lonDeg) & ...
        isfinite(altMeters) & ...
        isfinite(speedMetersPerSecond) & ...
        isfinite(trackDegrees) & ...
        isfinite(verticalRateMetersPerSecond) & ...
        isfinite(eastMeters) & ...
        isfinite(northMeters) & ...
        isfinite(upMeters) & ...
        isfinite(vxMetersPerSecond) & ...
        isfinite(vyMetersPerSecond) & ...
        isfinite(vzMetersPerSecond);

    sessionColumn(rowIdx) = sessionID;
    sourceColumn(rowIdx) = sourceFile;
    hexColumn(rowIdx) = string(track.hex);
    callsignColumn(rowIdx) = string(track.callsign);
    timeUtcColumn(rowIdx) = datetime(tUnix, "ConvertFrom", "posixtime", "TimeZone", "UTC");
    tUnixColumn(rowIdx) = tUnix;
    receiverOriginColumn(rowIdx, :) = repmat(receiverOriginLLA(:).', trackSampleCount, 1);
    latColumn(rowIdx) = latDeg;
    lonColumn(rowIdx) = lonDeg;
    altColumn(rowIdx) = altMeters;
    speedColumn(rowIdx) = speedMetersPerSecond;
    trackColumn(rowIdx) = trackDegrees;
    vrateColumn(rowIdx) = verticalRateMetersPerSecond;
    xColumn(rowIdx) = eastMeters;
    yColumn(rowIdx) = northMeters;
    zColumn(rowIdx) = upMeters;
    vxColumn(rowIdx) = vxMetersPerSecond;
    vyColumn(rowIdx) = vyMetersPerSecond;
    vzColumn(rowIdx) = vzMetersPerSecond;
    stateFiniteColumn(rowIdx) = requiredFinite;
end

sampleTable = table( ...
    sessionColumn, ...
    sourceColumn, ...
    hexColumn, ...
    callsignColumn, ...
    timeUtcColumn, ...
    tUnixColumn, ...
    receiverOriginColumn, ...
    latColumn, ...
    lonColumn, ...
    altColumn, ...
    speedColumn, ...
    trackColumn, ...
    vrateColumn, ...
    xColumn, ...
    vxColumn, ...
    yColumn, ...
    vyColumn, ...
    zColumn, ...
    vzColumn, ...
    stateFiniteColumn, ...
    'VariableNames', [ ...
        "sessionID", ...
        "sourceFile", ...
        "hex", ...
        "callsign", ...
        "timeUtc", ...
        "tUnix", ...
        "receiverOriginLLA", ...
        "latDeg", ...
        "lonDeg", ...
        "altMeters", ...
        "speedMetersPerSecond", ...
        "trackDegrees", ...
        "verticalRateMetersPerSecond", ...
        "x", ...
        "vx", ...
        "y", ...
        "vy", ...
        "z", ...
        "vz", ...
        "stateFinite"]);

end

function pairData = localBuildPairsFromSamples(sampleTable, covarianceStdAssumed, maxDtSeconds)
%LOCALBUILDPAIRSFROMSAMPLES Sort, de-duplicate, and build adjacent pairs.

sampleTable = sortrows(sampleTable, ["hex", "timeUtc"]);

if height(sampleTable) > 0
    [~, uniqueIdx] = unique(sampleTable(:, ["hex", "tUnix"]), "rows", "stable");
    duplicateTimestampRecordsRemoved = height(sampleTable) - numel(uniqueIdx);
    sampleTable = sampleTable(uniqueIdx, :);
else
    duplicateTimestampRecordsRemoved = 0;
end

previousState = zeros(0, 6);
nextState = zeros(0, 6);
dtSeconds = zeros(0, 1);
metadata = localEmptyMetadataTable();

totalAdjacentPairCount = 0;
rejectedPairCounts = struct();
rejectedPairCounts.nonfiniteEndpoint = 0;
rejectedPairCounts.nonPositiveDt = 0;
rejectedPairCounts.aboveMaxDt = 0;

if height(sampleTable) > 1
    groupId = findgroups(sampleTable.hex);
    groupCount = max(groupId);

    for groupIdx = 1:groupCount
        groupRows = find(groupId == groupIdx);

        if numel(groupRows) < 2
            continue;
        end

        currentRows = groupRows(1:end - 1);
        nextRows = groupRows(2:end);
        groupDtSeconds = sampleTable.tUnix(nextRows) - sampleTable.tUnix(currentRows);
        endpointFinite = sampleTable.stateFinite(currentRows) & sampleTable.stateFinite(nextRows);
        finitePositiveDt = isfinite(groupDtSeconds) & groupDtSeconds > 0;
        withinMaxDt = groupDtSeconds <= maxDtSeconds;
        validPair = endpointFinite & finitePositiveDt & withinMaxDt;

        totalAdjacentPairCount = totalAdjacentPairCount + numel(groupDtSeconds);
        rejectedPairCounts.nonfiniteEndpoint = rejectedPairCounts.nonfiniteEndpoint + sum(~endpointFinite);
        rejectedPairCounts.nonPositiveDt = rejectedPairCounts.nonPositiveDt + ...
            sum(endpointFinite & (~isfinite(groupDtSeconds) | groupDtSeconds <= 0));
        rejectedPairCounts.aboveMaxDt = rejectedPairCounts.aboveMaxDt + ...
            sum(endpointFinite & finitePositiveDt & ~withinMaxDt);

        if ~any(validPair)
            continue;
        end

        currentRows = currentRows(validPair);
        nextRows = nextRows(validPair);
        groupDtSeconds = groupDtSeconds(validPair);

        currentState = [ ...
            sampleTable.x(currentRows), ...
            sampleTable.vx(currentRows), ...
            sampleTable.y(currentRows), ...
            sampleTable.vy(currentRows), ...
            sampleTable.z(currentRows), ...
            sampleTable.vz(currentRows)];

        followingState = [ ...
            sampleTable.x(nextRows), ...
            sampleTable.vx(nextRows), ...
            sampleTable.y(nextRows), ...
            sampleTable.vy(nextRows), ...
            sampleTable.z(nextRows), ...
            sampleTable.vz(nextRows)];

        pairMetadata = table( ...
            sampleTable.sessionID(currentRows), ...
            sampleTable.sourceFile(currentRows), ...
            sampleTable.hex(currentRows), ...
            sampleTable.callsign(currentRows), ...
            sampleTable.timeUtc(currentRows), ...
            sampleTable.timeUtc(nextRows), ...
            sampleTable.receiverOriginLLA(currentRows, :), ...
            strings(numel(groupDtSeconds), 1), ...
            'VariableNames', [ ...
                "sessionID", ...
                "sourceFile", ...
                "hex", ...
                "callsign", ...
                "timeUtcK", ...
                "timeUtcNext", ...
                "receiverOriginLLA", ...
                "split"]);

        previousState = [previousState; currentState]; %#ok<AGROW>
        nextState = [nextState; followingState]; %#ok<AGROW>
        dtSeconds = [dtSeconds; groupDtSeconds]; %#ok<AGROW>
        metadata = [metadata; pairMetadata]; %#ok<AGROW>
    end
end

pairData = struct();
pairData.previousState = previousState;
pairData.nextState = nextState;
pairData.dtSeconds = dtSeconds;
pairData.previousCovarianceDiag = repmat(covarianceStdAssumed(:).'.^2, size(previousState, 1), 1);
pairData.metadata = metadata;
pairData.aircraftCount = 0;
pairData.validSampleCount = sum(sampleTable.stateFinite);
pairData.usablePairCount = size(previousState, 1);
pairData.duplicateTimestampRecordsRemoved = duplicateTimestampRecordsRemoved;
pairData.totalAdjacentPairCount = totalAdjacentPairCount;
pairData.rejectedPairCounts = rejectedPairCounts;

end

function pairData = localEmptyPairData(covarianceStdAssumed)
%LOCALEMPTYPAIRDATA Return a correctly shaped empty output.

pairData = struct();
pairData.previousState = zeros(0, 6);
pairData.nextState = zeros(0, 6);
pairData.dtSeconds = zeros(0, 1);
pairData.previousCovarianceDiag = zeros(0, 6);
pairData.metadata = localEmptyMetadataTable();
pairData.aircraftCount = 0;
pairData.validSampleCount = 0;
pairData.usablePairCount = 0;
pairData.duplicateTimestampRecordsRemoved = 0;
pairData.totalAdjacentPairCount = 0;
pairData.rejectedPairCounts = struct();
pairData.rejectedPairCounts.nonfiniteEndpoint = 0;
pairData.rejectedPairCounts.nonPositiveDt = 0;
pairData.rejectedPairCounts.aboveMaxDt = 0;

if nargin > 0
    pairData.previousCovarianceDiag = zeros(0, numel(covarianceStdAssumed));
end

end

function metadata = localEmptyMetadataTable()
%LOCALEMPTYMETADATATABLE Create the required metadata schema.

metadata = table( ...
    strings(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    NaT(0, 1, "TimeZone", "UTC"), ...
    NaT(0, 1, "TimeZone", "UTC"), ...
    zeros(0, 3), ...
    strings(0, 1), ...
    'VariableNames', [ ...
        "sessionID", ...
        "sourceFile", ...
        "hex", ...
        "callsign", ...
        "timeUtcK", ...
        "timeUtcNext", ...
        "receiverOriginLLA", ...
        "split"]);

end
