function output = helperPlotStage4DMotionComparison(results, varargin)
%HELPERPLOTSTAGE4DMOTIONCOMPARISON Compare canonical motion types.

parser = inputParser;
parser.FunctionName = mfilename;
addRequired(parser, "results");
addParameter(parser, "SavePath", "");
parse(parser, results, varargin{:});

savePath = strtrim(string(parser.Results.SavePath));
localValidateResults(results);
modelOrder = ["expanded_warm_mean_v1", "constvel"];
displayNames = ["Frozen warm", "constvel"];
scenarioOrder = [ ...
    "cv_level"; ...
    "cv_climb"; ...
    "horizontal_acceleration"; ...
    "vertical_acceleration"; ...
    "left_turn"; ...
    "right_turn"; ...
    "motion_transitions"];
displayScenarios = [ ...
    "Level CV"; ...
    "Climbing CV"; ...
    "Horizontal accel."; ...
    "Vertical accel."; ...
    "Left turn"; ...
    "Right turn"; ...
    "Transitions"];
metricRows = results.canonicalMetricTable( ...
    results.canonicalMetricTable.profile == "degraded" & ...
    results.canonicalMetricTable.comparisonFamily == "same_information" & ...
    results.canonicalMetricTable.weighting == "pair_weighted" & ...
    results.canonicalMetricTable.caseID ~= "all", :);
positionRMSE = NaN(numel(scenarioOrder), numel(modelOrder));

for scenarioIdx = 1:numel(scenarioOrder)
    caseID = scenarioOrder(scenarioIdx) + "__degraded";

    for modelIdx = 1:numel(modelOrder)
        rowMask = ...
            metricRows.caseID == caseID & ...
            metricRows.modelID == modelOrder(modelIdx);
        positionRMSE(scenarioIdx, modelIdx) = ...
            metricRows.positionRMSEMeters(rowMask);
    end
end

figureHandle = figure( ...
    Name="Stage 4D Canonical Motion Comparison", ...
    Color="w", ...
    Position=[100, 100, 1050, 560]);
axesHandle = axes(figureHandle);
barHandles = bar( ...
    axesHandle, ...
    categorical(displayScenarios, displayScenarios), ...
    positionRMSE);
barHandles(1).FaceColor = [0.0000, 0.4470, 0.7410];
barHandles(2).FaceColor = [0.8500, 0.3250, 0.0980];
grid on
ylabel("One-step 3-D position RMSE (m)", Color="k")
title( ...
    "Degraded observations expose motion-dependent prediction error", ...
    Color="k")
legendHandle = legend(displayNames, Location="northwest");
legendHandle.Color = "w";
legendHandle.TextColor = "k";
legendHandle.EdgeColor = [0.75, 0.75, 0.75];
xtickangle(22)
set( ...
    axesHandle, ...
    Color="w", ...
    XColor="k", ...
    YColor="k", ...
    GridColor=[0.15, 0.15, 0.15], ...
    GridAlpha=0.15);

if strlength(savePath) > 0
    saveFolder = string(fileparts(savePath));

    if strlength(saveFolder) > 0 && ~isfolder(saveFolder)
        mkdir(saveFolder);
    end

    exportgraphics(figureHandle, savePath, Resolution=160);
end

output = struct();
output.figure = figureHandle;
output.savePath = savePath;
output.motionScenarios = scenarioOrder;
output.modelIDs = modelOrder;
output.positionRMSEMeters = positionRMSE;

end

function localValidateResults(results)
%LOCALVALIDATERESULTS Require canonical Stage 4D metrics.

if ~isstruct(results) || ...
        ~isfield(results, "canonicalMetricTable") || ...
        isempty(results.canonicalMetricTable)
    error("Stage4D:InvalidMotionPlotResults", ...
        "Completed Stage 4D canonical metrics are required.");
end

end
