function eventTable = helperSegmentADSBMotionEvents(pairTable, variantID, varargin)
%HELPERSEGMENTADSBMOTIONEVENTS Convert adjacent qualifying pairs into events.
% Events are segmented within each session/ICAO track. Turn and acceleration
% events require at least three contiguous pairs spanning two seconds;
% climb and descent require ten seconds. Every sparse update is one gap event.

parser = inputParser;
parser.FunctionName = mfilename;
addRequired(parser, "pairTable", @istable);
addRequired(parser, "variantID");
addParameter(parser, "CampaignStartUtc", ...
    datetime(2026, 8, 19, 13, 25, 26, "TimeZone", "UTC"));
parse(parser, pairTable, variantID, varargin{:});

variantID = string(parser.Results.variantID);
campaignStartUtc = parser.Results.CampaignStartUtc;
localValidateInputs(pairTable, variantID, campaignStartUtc);

pairTable = sortrows(pairTable, ["sessionID", "hex", "timeUtcK"]);
eventTable = localEmptyEventTable();

if isempty(pairTable)
    return;
end

eventDefinitions = table( ...
    ["sustained_turn"; "sustained_acceleration"; "sustained_climb"; "sustained_descent"], ...
    [3; 3; 1; 1], ...
    [2; 2; 10; 10], ...
    ["deg/s"; "m/s^2"; "m/s"; "s"], ...
    'VariableNames', ["eventType", "minimumPairCount", "minimumDurationSeconds", "peakUnits"]);

trackKey = pairTable.sessionID + "/" + pairTable.hex;
[trackGroup, ~] = findgroups(trackKey);
trackCount = max(trackGroup, [], "omitmissing");
eventChunks = cell(5 * trackCount, 1);
chunkCount = 0;

for trackIdx = 1:trackCount
    trackPairs = pairTable(trackGroup == trackIdx, :);

    for definitionIdx = 1:height(eventDefinitions)
        definition = eventDefinitions(definitionIdx, :);
        qualifying = localQualifyingMask(trackPairs, definition.eventType);
        peakValues = localPeakValues(trackPairs, definition.eventType);
        segmented = localSegmentOneTrack( ...
            trackPairs, ...
            qualifying, ...
            peakValues, ...
            definition.minimumPairCount, ...
            definition.minimumDurationSeconds, ...
            definition.eventType, ...
            definition.peakUnits, ...
            variantID, ...
            campaignStartUtc);
        if ~isempty(segmented)
            chunkCount = chunkCount + 1;
            eventChunks{chunkCount} = segmented;
        end
    end

    sparseRows = find(trackPairs.isSparseUpdate);

    if ~isempty(sparseRows)
        chunkCount = chunkCount + 1;
        eventChunks{chunkCount} = localBuildSparseEvents( ...
            trackPairs(sparseRows, :), ...
            variantID, ...
            campaignStartUtc);
    end
end

if chunkCount > 0
    eventTable = vertcat(eventChunks{1:chunkCount});
end

if ~isempty(eventTable)
    eventTable = sortrows(eventTable, ["startTimeUtc", "sessionID", "hex", "eventType"]);
    eventTable.eventID = (1:height(eventTable)).';
    eventTable = movevars(eventTable, "eventID", "Before", 1);
end

end

function localValidateInputs(pairTable, variantID, campaignStartUtc)
%LOCALVALIDATEINPUTS Validate the public table contract.

requiredVariables = [ ...
    "sessionID", ...
    "hex", ...
    "timeUtcK", ...
    "timeUtcNext", ...
    "dtSeconds", ...
    "isTurnLike", ...
    "isAccelerationLike", ...
    "verticalStatus", ...
    "isSparseUpdate", ...
    "absTurnRateDegreesPerSecond", ...
    "absHorizontalAccelerationMetersPerSecondSquared", ...
    "absVerticalAccelerationMetersPerSecondSquared", ...
    "verticalRateMetersPerSecond"];
missingVariables = setdiff(requiredVariables, string(pairTable.Properties.VariableNames));

if ~isempty(missingVariables)
    error("Stage4BPost:MissingMotionPairVariable", ...
        "Motion pair table is missing variable %s.", missingVariables(1));
end

if ~isscalar(variantID) || strlength(strtrim(variantID)) == 0
    error("Stage4BPost:InvalidVariantID", ...
        "variantID must be a nonempty string scalar.");
end

if ~isdatetime(campaignStartUtc) || ~isscalar(campaignStartUtc) || isnat(campaignStartUtc)
    error("Stage4BPost:InvalidCampaignStart", ...
        "CampaignStartUtc must be a valid datetime scalar.");
end

end

function qualifying = localQualifyingMask(trackPairs, eventType)
%LOCALQUALIFYINGMASK Return the pair mask for one event definition.

switch eventType
    case "sustained_turn"
        qualifying = trackPairs.isTurnLike;
    case "sustained_acceleration"
        qualifying = trackPairs.isAccelerationLike;
    case "sustained_climb"
        qualifying = string(trackPairs.verticalStatus) == "climb";
    case "sustained_descent"
        qualifying = string(trackPairs.verticalStatus) == "descent";
    otherwise
        error("Stage4BPost:UnknownEventType", ...
            "Unknown event type: %s", eventType);
end

qualifying = logical(qualifying(:));

end

function peakValues = localPeakValues(trackPairs, eventType)
%LOCALPEAKVALUES Select a physically meaningful peak magnitude.

switch eventType
    case "sustained_turn"
        peakValues = trackPairs.absTurnRateDegreesPerSecond;
    case "sustained_acceleration"
        peakValues = max( ...
            trackPairs.absHorizontalAccelerationMetersPerSecondSquared, ...
            trackPairs.absVerticalAccelerationMetersPerSecondSquared);
    case {"sustained_climb", "sustained_descent"}
        peakValues = abs(trackPairs.verticalRateMetersPerSecond);
    otherwise
        peakValues = trackPairs.dtSeconds;
end

end

function events = localSegmentOneTrack(trackPairs, qualifying, peakValues, ...
        minimumPairCount, minimumDurationSeconds, eventType, peakUnits, ...
        variantID, campaignStartUtc)
%LOCALSEGMENTONETRACK Emit sustained contiguous runs for one track.

events = localEmptyEventTable();

if ~any(qualifying)
    return;
end

isContiguous = false(height(trackPairs), 1);

if height(trackPairs) > 1
    gapSeconds = seconds( ...
        trackPairs.timeUtcK(2:end) - trackPairs.timeUtcNext(1:end - 1));
    isContiguous(2:end) = abs(gapSeconds) <= 1e-6;
end

runStart = find(qualifying & ...
    [true; ~qualifying(1:end - 1) | ~isContiguous(2:end)]);
runEnd = find(qualifying & ...
    [~qualifying(2:end) | ~isContiguous(2:end); true]);
eventRows = cell(numel(runStart), 1);
eventCount = 0;

for runIdx = 1:numel(runStart)
    firstRow = runStart(runIdx);
    lastRow = runEnd(runIdx);
    pairCount = lastRow - firstRow + 1;
    durationSeconds = seconds( ...
        trackPairs.timeUtcNext(lastRow) - trackPairs.timeUtcK(firstRow));

    if pairCount < minimumPairCount || durationSeconds < minimumDurationSeconds
        continue;
    end

    firstPair = trackPairs(firstRow, :);
    lastPair = trackPairs(lastRow, :);
    peakMagnitude = max(peakValues(firstRow:lastRow), [], "omitnan");
    eventCount = eventCount + 1;
    eventRows{eventCount} = localBuildEventRow( ...
        firstPair, ...
        lastPair, ...
        pairCount, ...
        peakMagnitude, ...
        eventType, ...
        peakUnits, ...
        variantID, ...
        campaignStartUtc);
end

if eventCount > 0
    events = vertcat(eventRows{1:eventCount});
end

end

function events = localBuildSparseEvents(trackPairs, variantID, campaignStartUtc)
%LOCALBUILDSPARSEEVENTS Vectorize one-event-per-gap construction.

eventCount = height(trackPairs);
eventID = zeros(eventCount, 1);
variantID = repmat(string(variantID), eventCount, 1);
eventType = repmat("sparse_gap", eventCount, 1);
sessionID = string(trackPairs.sessionID);
hex = string(trackPairs.hex);
trackID = sessionID + "/" + hex;
startTimeUtc = trackPairs.timeUtcK;
endTimeUtc = trackPairs.timeUtcNext;
durationSeconds = seconds(endTimeUtc - startTimeUtc);
peakMagnitude = trackPairs.dtSeconds;
peakUnits = repmat("s", eventCount, 1);
pairCount = ones(eventCount, 1);

if ismember("campaignBlock", string(trackPairs.Properties.VariableNames))
    campaignBlock = string(trackPairs.campaignBlock);
else
    campaignBlock = strings(eventCount, 1);

    for eventIdx = 1:eventCount
        campaignBlock(eventIdx) = localCampaignBlock( ...
            startTimeUtc(eventIdx), ...
            campaignStartUtc);
    end
end

events = table( ...
    eventID, ...
    variantID, ...
    eventType, ...
    sessionID, ...
    hex, ...
    trackID, ...
    startTimeUtc, ...
    endTimeUtc, ...
    durationSeconds, ...
    peakMagnitude, ...
    peakUnits, ...
    pairCount, ...
    campaignBlock);

end

function eventRow = localBuildEventRow(firstPair, lastPair, pairCount, ...
        peakMagnitude, eventType, peakUnits, variantID, campaignStartUtc)
%LOCALBUILDEVENTROW Build one independent event record.

startTimeUtc = firstPair.timeUtcK;
endTimeUtc = lastPair.timeUtcNext;
durationSeconds = seconds(endTimeUtc - startTimeUtc);

if ismember("campaignBlock", string(firstPair.Properties.VariableNames))
    campaignBlock = string(firstPair.campaignBlock);
else
    campaignBlock = localCampaignBlock(startTimeUtc, campaignStartUtc);
end

trackID = string(firstPair.sessionID) + "/" + string(firstPair.hex);

eventRow = table( ...
    0, ...
    variantID, ...
    string(eventType), ...
    string(firstPair.sessionID), ...
    string(firstPair.hex), ...
    trackID, ...
    startTimeUtc, ...
    endTimeUtc, ...
    durationSeconds, ...
    double(peakMagnitude), ...
    string(peakUnits), ...
    double(pairCount), ...
    campaignBlock, ...
    'VariableNames', [ ...
        "eventID", ...
        "variantID", ...
        "eventType", ...
        "sessionID", ...
        "hex", ...
        "trackID", ...
        "startTimeUtc", ...
        "endTimeUtc", ...
        "durationSeconds", ...
        "peakMagnitude", ...
        "peakUnits", ...
        "pairCount", ...
        "campaignBlock"]);

end

function campaignBlock = localCampaignBlock(timeUtc, campaignStartUtc)
%LOCALCAMPAIGNBLOCK Label the three 24-hour campaign blocks.

blockNumber = floor(days(timeUtc - campaignStartUtc)) + 1;

if blockNumber >= 1 && blockNumber <= 3
    campaignBlock = "campaign_day_" + string(blockNumber);
else
    campaignBlock = "outside_campaign";
end

end

function eventTable = localEmptyEventTable()
%LOCALEMPTYEVENTTABLE Return the stable public event schema.

eventTable = table( ...
    zeros(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    NaT(0, 1, "TimeZone", "UTC"), ...
    NaT(0, 1, "TimeZone", "UTC"), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    strings(0, 1), ...
    zeros(0, 1), ...
    strings(0, 1), ...
    'VariableNames', [ ...
        "eventID", ...
        "variantID", ...
        "eventType", ...
        "sessionID", ...
        "hex", ...
        "trackID", ...
        "startTimeUtc", ...
        "endTimeUtc", ...
        "durationSeconds", ...
        "peakMagnitude", ...
        "peakUnits", ...
        "pairCount", ...
        "campaignBlock"]);

end
