function output = helperPlotStage4CRMSEDashboard(rmseTable)
%HELPERPLOTSTAGE4CRMSEDASHBOARD Compare native and neural RMSE on test rows.

requiredVariables = [ ...
    "motionClass"; ...
    "modelID"; ...
    "modelDisplayName"; ...
    "split"; ...
    "sampleCount"; ...
    "positionRMSEMeters"; ...
    "velocityRMSEMetersPerSecond"];

if any(~ismember(requiredVariables, ...
        string(rmseTable.Properties.VariableNames)))
    error( ...
        "StageReview:InvalidStage4CRMSETable", ...
        "The RMSE table is missing a required variable.");
end

motionClasses = [ ...
    "constvel_like"; ...
    "constacc_like"; ...
    "constturn_like"];
nativeModelIDs = ["constvel"; "constacc"; "constturn"];
neuralModelIDs = [ ...
    "legacy_stage3a_v1"; ...
    "expanded_scratch_mean_v1"; ...
    "expanded_warm_mean_v1"];
metricVariables = [ ...
    "positionRMSEMeters"; ...
    "velocityRMSEMetersPerSecond"];
metricLabels = [ ...
    "RMSE (m)"; ...
    "RMSE (m/s)"];
modelColors = [ ...
    0.0000, 0.4470, 0.7410; ...
    0.8500, 0.3250, 0.0980; ...
    0.4660, 0.6740, 0.1880; ...
    0.4940, 0.1840, 0.5560];
displayedRows = rmseTable(rmseTable.split == "test", :);

localValidateDisplayedRows( ...
    displayedRows, ...
    motionClasses, ...
    nativeModelIDs, ...
    neuralModelIDs);

figureHandle = figure( ...
    Name="Stage 4C Held-Out Test RMSE Dashboard", ...
    Color="white", ...
    Position=[100, 100, 1200, 850]);
layout = tiledlayout(figureHandle, 3, 2, ...
    TileSpacing="loose", ...
    Padding="loose");
axisHandles = gobjects(3, 2);
legendHandle = gobjects(1);

for classIdx = 1:numel(motionClasses)
    classRows = displayedRows( ...
        displayedRows.motionClass == motionClasses(classIdx), :);
    modelIDs = [nativeModelIDs(classIdx); neuralModelIDs];
    [~, rowOrder] = ismember(modelIDs, classRows.modelID);
    orderedRows = classRows(rowOrder, :);
    modelLabels = localShortModelLabels( ...
        orderedRows.modelDisplayName);

    for metricIdx = 1:numel(metricVariables)
        axisHandles(classIdx, metricIdx) = nexttile(layout);
        values = orderedRows.(metricVariables(metricIdx));
        barHandles = gobjects(numel(modelIDs), 1);
        hold(axisHandles(classIdx, metricIdx), "on");

        for modelIdx = 1:numel(modelIDs)
            barHandles(modelIdx) = bar( ...
                axisHandles(classIdx, metricIdx), ...
                modelIdx, ...
                values(modelIdx), ...
                0.78, ...
                FaceColor=modelColors(modelIdx, :), ...
                EdgeColor="none");
        end

        hold(axisHandles(classIdx, metricIdx), "off");
        grid(axisHandles(classIdx, metricIdx), "on");
        axisHandles(classIdx, metricIdx).Color = "white";
        axisHandles(classIdx, metricIdx).XColor = "black";
        axisHandles(classIdx, metricIdx).YColor = "black";
        axisHandles(classIdx, metricIdx).GridColor = [0.75, 0.75, 0.75];
        axisHandles(classIdx, metricIdx).FontSize = 9;
        axisHandles(classIdx, metricIdx).XTick = 1:numel(modelIDs);
        axisHandles(classIdx, metricIdx).XTickLabel = ...
            modelLabels;
        axisHandles(classIdx, metricIdx).XLim = ...
            [0.5, numel(modelIDs) + 0.5];
        ylabel(axisHandles(classIdx, metricIdx), metricLabels(metricIdx));
        titleHandle = title( ...
            axisHandles(classIdx, metricIdx), ...
            replace(motionClasses(classIdx), "_", "\_"));
        titleHandle.Color = "black";

        if classIdx == 1 && metricIdx == 1
            legendHandle = legend( ...
                axisHandles(classIdx, metricIdx), ...
                barHandles, ...
                [ ...
                    "Class-aligned native"; ...
                    "Stage 3A legacy"; ...
                    "Expanded scratch"; ...
                    "Expanded warm"], ...
                Location="best");
            legendHandle.Color = "white";
            legendHandle.TextColor = "black";
        end
    end
end

layoutTitle = title( ...
    layout, ...
    "Stage 4C pair-weighted 3-D RMSE on matched held-out test rows");
layoutTitle.Color = "black";

output = struct();
output.figure = figureHandle;
output.layout = layout;
output.axes = axisHandles;
output.legend = legendHandle;
output.metricTable = displayedRows;

end

function localValidateDisplayedRows( ...
        displayedRows, motionClasses, nativeModelIDs, neuralModelIDs)
%LOCALVALIDATEDISPLAYEDROWS Enforce test-only matched comparison inputs.

if height(displayedRows) ~= 12 || ...
        any(displayedRows.split ~= "test")
    error( ...
        "StageReview:InvalidStage4CTestRMSETable", ...
        "The held-out comparison requires exactly 12 test rows.");
end

for classIdx = 1:numel(motionClasses)
    classRows = displayedRows( ...
        displayedRows.motionClass == motionClasses(classIdx), :);
    expectedModelIDs = [nativeModelIDs(classIdx); neuralModelIDs];

    if height(classRows) ~= 4 || ...
            ~isequal(sort(classRows.modelID), sort(expectedModelIDs)) || ...
            numel(unique(classRows.sampleCount)) ~= 1
        error( ...
            "StageReview:InvalidStage4CTestRMSESection", ...
            "The %s test section must contain four models on matched rows.", ...
            motionClasses(classIdx));
    end
end

end

function shortLabels = localShortModelLabels(modelOrder)
%LOCALSHORTMODELLABELS Keep six compact panels readable.

shortLabels = strings(size(modelOrder));

for modelIdx = 1:numel(modelOrder)
    if startsWith(modelOrder(modelIdx), "Native ")
        shortLabels(modelIdx) = replace( ...
            modelOrder(modelIdx), ...
            "Native const", ...
            "Native C");
    elseif modelOrder(modelIdx) == "Stage 3A legacy"
        shortLabels(modelIdx) = "Legacy 3A";
    elseif modelOrder(modelIdx) == "Expanded scratch"
        shortLabels(modelIdx) = "Scratch";
    elseif modelOrder(modelIdx) == "Expanded warm"
        shortLabels(modelIdx) = "Warm";
    else
        shortLabels(modelIdx) = modelOrder(modelIdx);
    end
end

end
