function trainingDetails = helperBuildStageReviewTrainingDetails(review)
%HELPERBUILDSTAGEREVIEWTRAININGDETAILS Explain the Stage 2B smoke training.

summary = review.trainingSummary;
trainingScriptPath = fullfile(review.projectRoot, "trainLocalADSBMLPSmoke.m");

trainingDetails = table( ...
    [ ...
        "implementation language"; ...
        "training script"; ...
        "training artifact"; ...
        "network type"; ...
        "input features"; ...
        "target"; ...
        "network output"; ...
        "loss"; ...
        "optimizer"; ...
        "epochs"; ...
        "mini-batch size"; ...
        "learning rate"; ...
        "hidden units per layer"; ...
        "training rows"; ...
        "validation rows"; ...
        "test rows"; ...
        "validation usage"; ...
        "final training loss"; ...
        "end accuracy"; ...
        "all-row position RMSE"; ...
        "all-row velocity RMSE"; ...
        "empirical 1-sigma coverage"; ...
        "empirical 2-sigma coverage"], ...
    [ ...
        "MATLAB Deep Learning Toolbox dlnetwork, not Python"; ...
        trainingScriptPath; ...
        string(summary.outputPath); ...
        sprintf("MLP with two fully connected hidden layers and ReLU activations"); ...
        "13 values: previous [x vx y vy z vz], assumed covariance diagonal, and dtSeconds"; ...
        "Observed ADS-B-derived nextState in [x vx y vy z vz] order"; ...
        "12 values: 6 normalized next-state means and 6 raw diagonal variance parameters"; ...
        "Diagonal Gaussian negative log likelihood in normalized state space"; ...
        sprintf("Adam, rng(123), learn rate %.4g", summary.learnRate); ...
        string(summary.numEpochs); ...
        string(summary.miniBatchSize); ...
        string(summary.learnRate); ...
        string(summary.hiddenUnits); ...
        string(summary.trainCount); ...
        string(summary.validationCount); ...
        string(summary.testCount); ...
        "Held out by aircraft split, but not used for early stopping or model selection in this smoke run"; ...
        sprintf("%.6f", summary.finalLoss); ...
        "Not applicable: this is regression, so report RMSE and coverage instead"; ...
        sprintf("%.3f m", summary.modelPositionRMSEMeters); ...
        sprintf("%.3f m/s", summary.modelVelocityRMSEMetersPerSecond); ...
        sprintf("%.3f", summary.empiricalOneSigmaCoverage); ...
        sprintf("%.3f", summary.empiricalTwoSigmaCoverage)], ...
    'VariableNames', ["item", "value"]);

end
