function output = helperPlotStage4CNNValidationTest(rmseTable)
%HELPERPLOTSTAGE4CNNVALIDATIONTEST Compare neural RMSE across held-out splits.

requiredVariables = [ ...
    "motionClass"; ...
    "modelID"; ...
    "modelDisplayName"; ...
    "split"; ...
    "sampleCount"; ...
    "positionRMSEMeters"; ...
    "velocityRMSEMetersPerSecond"];

if any(~ismember(requiredVariables, ...
        string(rmseTable.Properties.VariableNames)))
    error( ...
        "StageReview:InvalidStage4CRMSETable", ...
        "The RMSE table is missing a required variable.");
end

motionClasses = [ ...
    "constvel_like"; ...
    "constacc_like"; ...
    "constturn_like"];
neuralModelIDs = [ ...
    "legacy_stage3a_v1"; ...
    "expanded_scratch_mean_v1"; ...
    "expanded_warm_mean_v1"];
splitNames = ["validation"; "test"];
metricVariables = [ ...
    "positionRMSEMeters"; ...
    "velocityRMSEMetersPerSecond"];
metricLabels = [ ...
    "RMSE (m)"; ...
    "RMSE (m/s)"];
displayedRows = rmseTable( ...
    ismember(rmseTable.modelID, neuralModelIDs), :);

localValidateDisplayedRows( ...
    displayedRows, ...
    motionClasses, ...
    neuralModelIDs, ...
    splitNames);

figureHandle = figure( ...
    Name="Stage 4C Neural Validation Versus Test RMSE", ...
    Color="white", ...
    Position=[120, 120, 1200, 850]);
layout = tiledlayout(figureHandle, 3, 2, ...
    TileSpacing="loose", ...
    Padding="loose");
axisHandles = gobjects(3, 2);
legendHandle = gobjects(1);

for classIdx = 1:numel(motionClasses)
    classRows = displayedRows( ...
        displayedRows.motionClass == motionClasses(classIdx), :);

    for metricIdx = 1:numel(metricVariables)
        axisHandles(classIdx, metricIdx) = nexttile(layout);
        values = NaN(numel(neuralModelIDs), numel(splitNames));

        for splitIdx = 1:numel(splitNames)
            splitRows = classRows( ...
                classRows.split == splitNames(splitIdx), :);
            [~, rowOrder] = ismember( ...
                neuralModelIDs, ...
                splitRows.modelID);
            values(:, splitIdx) = ...
                splitRows.(metricVariables(metricIdx))(rowOrder);
        end

        bar(axisHandles(classIdx, metricIdx), values, "grouped");
        grid(axisHandles(classIdx, metricIdx), "on");
        axisHandles(classIdx, metricIdx).Color = "white";
        axisHandles(classIdx, metricIdx).XColor = "black";
        axisHandles(classIdx, metricIdx).YColor = "black";
        axisHandles(classIdx, metricIdx).GridColor = [0.75, 0.75, 0.75];
        axisHandles(classIdx, metricIdx).FontSize = 9;
        axisHandles(classIdx, metricIdx).XTick = ...
            1:numel(neuralModelIDs);
        axisHandles(classIdx, metricIdx).XTickLabel = ...
            ["Legacy 3A"; "Scratch"; "Warm"];
        ylabel(axisHandles(classIdx, metricIdx), metricLabels(metricIdx));
        titleHandle = title( ...
            axisHandles(classIdx, metricIdx), ...
            replace(motionClasses(classIdx), "_", "\_"));
        titleHandle.Color = "black";

        if classIdx == 1 && metricIdx == 1
            legendHandle = legend( ...
                axisHandles(classIdx, metricIdx), ...
                ["Validation", "Test"], ...
                Location="best");
            legendHandle.Color = "white";
            legendHandle.TextColor = "black";
        end
    end
end

layoutTitle = title( ...
    layout, ...
    "Stage 4C frozen neural models: validation versus test RMSE");
layoutTitle.Color = "black";

output = struct();
output.figure = figureHandle;
output.layout = layout;
output.axes = axisHandles;
output.legend = legendHandle;
output.metricTable = displayedRows;

end

function localValidateDisplayedRows( ...
        displayedRows, motionClasses, neuralModelIDs, splitNames)
%LOCALVALIDATEDISPLAYEDROWS Enforce the neural split-comparison contract.

if height(displayedRows) ~= 18 || ...
        ~isequal(sort(unique(displayedRows.split)), sort(splitNames))
    error( ...
        "StageReview:InvalidStage4CNNRMSETable", ...
        "The neural comparison requires 18 validation/test rows.");
end

for classIdx = 1:numel(motionClasses)
    for splitIdx = 1:numel(splitNames)
        sectionRows = displayedRows( ...
            displayedRows.motionClass == motionClasses(classIdx) & ...
            displayedRows.split == splitNames(splitIdx), :);

        if height(sectionRows) ~= 3 || ...
                ~isequal( ...
                sort(sectionRows.modelID), ...
                sort(neuralModelIDs)) || ...
                numel(unique(sectionRows.sampleCount)) ~= 1
            error( ...
                "StageReview:InvalidStage4CNNRMSESection", ...
                "The %s/%s section must contain three neural models on matched rows.", ...
                motionClasses(classIdx), ...
                splitNames(splitIdx));
        end
    end
end

end
