function result = helperScoreStage4CNativeManeuverModels( ...
        nextState, ...
        comparatorPredictions, ...
        nativeBaseline, ...
        metadata, ...
        maneuverPairTable, ...
        split)
%HELPERSCORESTAGE4CNATIVEMANEUVERMODELS Score matched maneuver slices.
% constacc and all four comparators share one eligible constacc-like row
% set. constturn and the same comparators share one eligible constturn-like
% row set. Both pair weighting and equal-total-weight event weighting are
% reported from those exact row sets.

nextState = double(nextState);
split = lower(strtrim(string(split(:))));
localValidateInputs( ...
    nextState, ...
    comparatorPredictions, ...
    nativeBaseline, ...
    metadata, ...
    maneuverPairTable, ...
    split);

splitNames = ["validation", "test"];
sliceNames = ["constacc_like", "constturn_like"];
nativeModelIDs = ["constacc", "constturn"];
sectionCount = numel(splitNames) * numel(sliceNames);
modelCountPerSection = numel(comparatorPredictions) + 1;
metricRows = cell(sectionCount * modelCountPerSection * 2, 1);
coverageRows = cell(sectionCount, 1);
exclusionRows = cell(sectionCount, 1);
selectionRows = cell(sectionCount, 1);
metricRowIdx = 0;
sectionIdx = 0;

for splitIdx = 1:numel(splitNames)
    splitName = splitNames(splitIdx);

    for sliceIdx = 1:numel(sliceNames)
        sectionIdx = sectionIdx + 1;
        sliceName = sliceNames(sliceIdx);
        sourceSliceMask = ...
            (split == splitName) & ...
            (string(maneuverPairTable.maneuverClass) == sliceName);
        rowMask = sourceSliceMask & nativeBaseline.eligibleMask;
        selectedRows = find(rowMask);
        [eventWeights, eventCount] = localIndependentEventWeights( ...
            metadata(rowMask, :));
        pairWeights = ones(sum(rowMask), 1);

        models = localBuildSectionModels( ...
            nativeModelIDs(sliceIdx), ...
            nativeBaseline, ...
            comparatorPredictions, ...
            sliceIdx);

        for modelIdx = 1:numel(models)
            predictedState = double( ...
                models(modelIdx).predictedNextState(rowMask, :));
            trueState = nextState(rowMask, :);
            positionError = vecnorm( ...
                predictedState(:, [1, 3, 5]) - ...
                trueState(:, [1, 3, 5]), ...
                2, ...
                2);
            velocityError = vecnorm( ...
                predictedState(:, [2, 4, 6]) - ...
                trueState(:, [2, 4, 6]), ...
                2, ...
                2);

            metricRowIdx = metricRowIdx + 1;
            metricRows{metricRowIdx} = localMetricRow( ...
                models(modelIdx).modelID, ...
                splitName, ...
                sliceName, ...
                "pair_weighted", ...
                positionError, ...
                velocityError, ...
                pairWeights, ...
                eventCount);
            metricRowIdx = metricRowIdx + 1;
            metricRows{metricRowIdx} = localMetricRow( ...
                models(modelIdx).modelID, ...
                splitName, ...
                sliceName, ...
                "independent_event_weighted", ...
                positionError, ...
                velocityError, ...
                eventWeights, ...
                eventCount);
        end

        coverageRows{sectionIdx} = table( ...
            splitName, ...
            sliceName, ...
            sum(sourceSliceMask), ...
            sum(rowMask), ...
            sum(sourceSliceMask & ~nativeBaseline.eligibleMask), ...
            sum(rowMask) ./ sum(sourceSliceMask), ...
            'VariableNames', [ ...
                "split", ...
                "maneuverSlice", ...
                "sourceSliceRowCount", ...
                "eligibleRowCount", ...
                "excludedRowCount", ...
                "coverageFraction"]);
        selectionRows{sectionIdx} = table( ...
            splitName, ...
            sliceName, ...
            {selectedRows}, ...
            'VariableNames', [ ...
                "split", ...
                "maneuverSlice", ...
                "selectedInputRowIndices"]);
        exclusionRows{sectionIdx} = localCountExclusionReasons( ...
            splitName, ...
            sliceName, ...
            nativeBaseline.exclusionReason(sourceSliceMask));
    end
end

metricTable = vertcat(metricRows{:});
coverageTable = vertcat(coverageRows{:});
exclusionTable = vertcat(exclusionRows{:});
selectionTable = vertcat(selectionRows{:});

result = struct();
result.table = metricTable;
result.coverageTable = coverageTable;
result.exclusionTable = exclusionTable;
result.selectionTable = selectionTable;
result.eventDefinition = ...
    "A contiguous run within one session/ICAO track and the scored maneuver slice.";
result.pairWeightDefinition = "Every matched eligible state pair has weight one.";
result.eventWeightDefinition = ...
    "Each row has reciprocal event-length weight, so every event has total weight one.";
result.sharedRowPolicy = ...
    "Every model in one split/slice section uses the exact same selected rows.";

end

function models = localBuildSectionModels( ...
        nativeModelID, nativeBaseline, comparatorPredictions, sliceIdx)
%LOCALBUILDSECTIONMODELS Put the respective native model first.

models = repmat(struct( ...
    "modelID", "", ...
    "predictedNextState", []), ...
    numel(comparatorPredictions) + 1, ...
    1);
models(1).modelID = nativeModelID;

if sliceIdx == 1
    models(1).predictedNextState = ...
        nativeBaseline.constaccPredictedState;
else
    models(1).predictedNextState = ...
        nativeBaseline.constturnPredictedState;
end

models(2:end) = comparatorPredictions(:);

end

function countTable = localCountExclusionReasons( ...
        splitName, sliceName, reasons)
%LOCALCOUNTEXCLUSIONREASONS Retain zero counts for a stable audit schema.

reasonOrder = [ ...
    "eligible"; ...
    "first_row_in_track"; ...
    "nonadjacent_predecessor"; ...
    "nonpositive_prior_dt"; ...
    "split_mismatch"; ...
    "nonfinite_input"; ...
    "nonpositive_current_dt"; ...
    "nonfinite_native_prediction"];
rowCount = zeros(numel(reasonOrder), 1);

for reasonIdx = 1:numel(reasonOrder)
    rowCount(reasonIdx) = sum(reasons == reasonOrder(reasonIdx));
end

countTable = table( ...
    repmat(splitName, numel(reasonOrder), 1), ...
    repmat(sliceName, numel(reasonOrder), 1), ...
    reasonOrder, ...
    rowCount, ...
    'VariableNames', ["split", "maneuverSlice", "reason", "rowCount"]);

end

function [weights, eventCount] = localIndependentEventWeights(metadata)
%LOCALINDEPENDENTEVENTWEIGHTS Give each contiguous event equal total weight.

rowCount = height(metadata);

if rowCount == 0
    weights = zeros(0, 1);
    eventCount = 0;
    return;
end

rowIndex = (1:rowCount).';
ordering = table( ...
    string(metadata.sessionID), ...
    lower(strtrim(string(metadata.hex))), ...
    metadata.timeUtcK, ...
    rowIndex, ...
    'VariableNames', ["sessionID", "icao24", "timeUtcK", "rowIndex"]);
ordering = sortrows( ...
    ordering, ...
    ["sessionID", "icao24", "timeUtcK", "rowIndex"]);
orderedRows = ordering.rowIndex;
sessionID = string(metadata.sessionID(orderedRows));
icao24 = lower(strtrim(string(metadata.hex(orderedRows))));
timeUtcK = metadata.timeUtcK(orderedRows);
timeUtcNext = metadata.timeUtcNext(orderedRows);
newEvent = true(rowCount, 1);

if rowCount > 1
    sameTrack = ...
        (sessionID(2:end) == sessionID(1:end - 1)) & ...
        (icao24(2:end) == icao24(1:end - 1));
    adjacentPair = abs(seconds( ...
        timeUtcK(2:end) - timeUtcNext(1:end - 1))) <= 1e-6;
    newEvent(2:end) = ~(sameTrack & adjacentPair);
end

eventID = cumsum(newEvent);
eventCount = eventID(end);
eventLength = accumarray(eventID, 1, [eventCount, 1]);
orderedWeights = 1 ./ eventLength(eventID);
weights = zeros(rowCount, 1);
weights(orderedRows) = orderedWeights;

end

function metricRow = localMetricRow( ...
        modelID, ...
        splitName, ...
        sliceName, ...
        weighting, ...
        positionError, ...
        velocityError, ...
        weights, ...
        eventCount)
%LOCALMETRICROW Build one row compatible with the Stage 4C metric CSV.

metricRow = table( ...
    string(modelID), ...
    string(splitName), ...
    "native_maneuver_baseline", ...
    string(sliceName), ...
    string(weighting), ...
    numel(positionError), ...
    eventCount, ...
    localWeightedRMSE(positionError, weights), ...
    localWeightedRMSE(velocityError, weights), ...
    localWeightedQuantile(positionError, weights, 0.50), ...
    localWeightedQuantile(velocityError, weights, 0.50), ...
    localWeightedQuantile(positionError, weights, 0.95), ...
    localWeightedQuantile(velocityError, weights, 0.95), ...
    'VariableNames', [ ...
        "modelID", ...
        "split", ...
        "groupDimension", ...
        "groupName", ...
        "weighting", ...
        "sampleCount", ...
        "eventCount", ...
        "positionRMSEMeters", ...
        "velocityRMSEMetersPerSecond", ...
        "positionMedianErrorMeters", ...
        "velocityMedianErrorMetersPerSecond", ...
        "positionP95ErrorMeters", ...
        "velocityP95ErrorMetersPerSecond"]);

end

function value = localWeightedRMSE(errors, weights)
%LOCALWEIGHTEDRMSE Compute weighted root mean square error.

value = sqrt(sum(weights .* errors .^ 2) / sum(weights));

end

function value = localWeightedQuantile(values, weights, probability)
%LOCALWEIGHTEDQUANTILE Return the left-continuous weighted quantile.

[values, order] = sort(values);
weights = weights(order);
cumulativeWeight = cumsum(weights);
threshold = probability * cumulativeWeight(end);
quantileIndex = find(cumulativeWeight >= threshold, 1, "first");
value = values(quantileIndex);

end

function localValidateInputs( ...
        nextState, ...
        comparatorPredictions, ...
        nativeBaseline, ...
        metadata, ...
        maneuverPairTable, ...
        split)
%LOCALVALIDATEINPUTS Enforce aligned finite comparator predictions.

sampleCount = size(nextState, 1);

validateattributes(nextState, ...
    {'numeric'}, {'2d', 'real', 'finite'}, mfilename, "nextState");

if size(nextState, 2) ~= 6 || ...
        height(metadata) ~= sampleCount || ...
        height(maneuverPairTable) ~= sampleCount || ...
        numel(split) ~= sampleCount
    error("Stage4CNative:MetricInputSizeMismatch", ...
        "Metric inputs must describe aligned N-by-6 rows.");
end

requiredBaselineFields = [ ...
    "eligibleMask", ...
    "exclusionReason", ...
    "constaccPredictedState", ...
    "constturnPredictedState"];

if any(~isfield(nativeBaseline, requiredBaselineFields))
    error("Stage4CNative:InvalidNativeBaseline", ...
        "The native baseline struct is missing required fields.");
end

if numel(nativeBaseline.eligibleMask) ~= sampleCount || ...
        numel(nativeBaseline.exclusionReason) ~= sampleCount || ...
        ~isequal(size(nativeBaseline.constaccPredictedState), [sampleCount, 6]) || ...
        ~isequal(size(nativeBaseline.constturnPredictedState), [sampleCount, 6])
    error("Stage4CNative:NativeBaselineSizeMismatch", ...
        "Native baseline fields must align with the scored rows.");
end

if isempty(comparatorPredictions) || ...
        ~isstruct(comparatorPredictions) || ...
        any(~isfield(comparatorPredictions, ...
        ["modelID", "predictedNextState"]))
    error("Stage4CNative:InvalidComparatorPredictions", ...
        "Comparator predictions must contain modelID and predictedNextState.");
end

modelIDs = strings(numel(comparatorPredictions), 1);

for modelIdx = 1:numel(comparatorPredictions)
    modelIDs(modelIdx) = string(comparatorPredictions(modelIdx).modelID);
    prediction = comparatorPredictions(modelIdx).predictedNextState;

    if ~isnumeric(prediction) || ...
            ~isequal(size(prediction), size(nextState)) || ...
            any(~isfinite(prediction), "all")
        error("Stage4CNative:InvalidComparatorPredictionArray", ...
            "Every comparator prediction must be a finite N-by-6 array.");
    end
end

expectedComparatorIDs = [ ...
    "constvel"; ...
    "legacy_stage3a_v1"; ...
    "expanded_scratch_mean_v1"; ...
    "expanded_warm_mean_v1"];

if ~isequal(modelIDs, expectedComparatorIDs)
    error("Stage4CNative:UnexpectedComparatorModels", ...
        "The four frozen Stage 4C comparator identities are required.");
end

if any(~ismember(split, ["validation", "test"]))
    error("Stage4CNative:TrainingRowsInMetrics", ...
        "Native maneuver metrics accept validation and test rows only.");
end

end
