function output = helperOpenStage4EGlobe(review)
%HELPEROPENSTAGE4EGLOBE Open one interactive recursive trajectory view.

localValidateReview(review);
colors = struct();
colors.measurement = [0.4000, 0.4000, 0.4000];
colors.reference = [0.0000, 0.6500, 0.2500];
colors.cv_ekf = [0.0000, 0.4470, 0.7410];
colors.ca_ekf = [0.4660, 0.6740, 0.1880];
colors.ct_ekf = [0.4940, 0.1840, 0.5560];
colors.native_imm = [0.9290, 0.6940, 0.1250];
colors.warm_ukf = [0.8500, 0.3250, 0.0980];
viewer = trackingGlobeViewer( ...
    ReferenceLocation=review.receiverOriginLLA, ...
    PlatformHistoryDepth=10000, ...
    TrackHistoryDepth=10000);

% Draw the reference last so it remains visible where paths overlap.
plotTrajectory( ...
    viewer, ...
    review.trajectories.measurement, ...
    Color=colors.measurement, ...
    LineWidth=int32(2));
plotTrajectory( ...
    viewer, ...
    review.trajectories.cv_ekf, ...
    Color=colors.cv_ekf, ...
    LineWidth=int32(2));
plotTrajectory( ...
    viewer, ...
    review.trajectories.ca_ekf, ...
    Color=colors.ca_ekf, ...
    LineWidth=int32(2));
plotTrajectory( ...
    viewer, ...
    review.trajectories.ct_ekf, ...
    Color=colors.ct_ekf, ...
    LineWidth=int32(2));
plotTrajectory( ...
    viewer, ...
    review.trajectories.native_imm, ...
    Color=colors.native_imm, ...
    LineWidth=int32(3));
plotTrajectory( ...
    viewer, ...
    review.trajectories.warm_ukf, ...
    Color=colors.warm_ukf, ...
    LineWidth=int32(3));
plotTrajectory( ...
    viewer, ...
    review.trajectories.reference, ...
    Color=colors.reference, ...
    LineWidth=int32(4));

output = struct();
output.viewer = viewer;
output.label = review.label;
output.summaryTable = review.summaryTable;
output.legendTable = review.legendTable;
output.validationTable = review.validationTable;
output.colors = colors;
output.trajectoryCount = review.summaryTable.trajectoryCount;
output.trajectoryPathCount = review.summaryTable.trajectoryPathCount;
output.plotCallCount = 7;

end

function localValidateReview(review)
%LOCALVALIDATEREVIEW Require all seven recursive path families.

requiredFields = [ ...
    "receiverOriginLLA"; ...
    "trajectories"; ...
    "summaryTable"; ...
    "legendTable"; ...
    "validationTable"; ...
    "label"];
requiredTrajectoryFields = [ ...
    "measurement"; ...
    "reference"; ...
    "cv_ekf"; ...
    "ca_ekf"; ...
    "ct_ekf"; ...
    "native_imm"; ...
    "warm_ukf"];

if ~isstruct(review) || any(~isfield(review, requiredFields))
    error("Stage4EGlobe:InvalidReview", ...
        "The Stage 4E globe review is missing required fields.");
end

if any(~isfield(review.trajectories, requiredTrajectoryFields))
    error("Stage4EGlobe:InvalidTrajectories", ...
        "The Stage 4E globe review must contain all recursive paths.");
end

end
