function analysis = helperAnalyzeADSBDatasetMotionDiversity(stageSummary, variantID)
%HELPERANALYZEADSBDATASETMOTIONDIVERSITY Measure independent motion coverage.
% Pair-level distributions are retained for compatibility, but readiness is
% based on sustained events, contributor concentration, and leakage-resistant
% prospective splits.

variantID = string(variantID);
stage3BSummary = localResolveStage3BSummary(stageSummary);
localValidateInputs(stage3BSummary, variantID);

pairTable = localBuildMotionPairTable(stage3BSummary, variantID);
continuousSummary = localBuildContinuousSummary(pairTable);
continuousHistogram = localBuildContinuousHistogram(pairTable);
pairRegimeSummary = localBuildPairRegimeSummary(pairTable);
jointRegimeOccupancy = localBuildJointRegimeOccupancy(pairTable);
eventTable = helperSegmentADSBMotionEvents(pairTable, variantID);
eventSummary = localBuildEventSummary(eventTable);
splitAudit = helperAuditADSBProspectiveSplits(pairTable, eventTable);
sourceSummary = localBuildSourceSummary(stageSummary, stage3BSummary);

analysis = struct();
analysis.generatedAt = datetime("now", "TimeZone", "UTC");
analysis.variantID = variantID;
analysis.sourceSummary = sourceSummary;
analysis.pairTable = pairTable;
analysis.continuousSummary = continuousSummary;
analysis.continuousHistogram = continuousHistogram;
analysis.pairRegimeSummary = pairRegimeSummary;
analysis.jointRegimeOccupancy = jointRegimeOccupancy;
analysis.eventTable = eventTable;
analysis.eventSummary = eventSummary;
analysis.splitAudit = splitAudit;
analysis.motionThresholds = stage3BSummary.labelSummary.thresholds;
analysis.retrainingRun = false;

end

function histogramTable = localBuildContinuousHistogram(pairTable)
%LOCALBUILDCONTINUOUSHISTOGRAM Store comparable fixed-bin distributions.

histogramTable = [ ...
    localHistogramRows( ...
        "horizontal_speed_mps", ...
        pairTable.horizontalSpeedMetersPerSecond, ...
        [-Inf, 50, 100, 150, 200, 250, Inf], ...
        ["<50", "50-100", "100-150", "150-200", "200-250", ">=250"]); ...
    localHistogramRows( ...
        "altitude_m", ...
        pairTable.altitudeMeters, ...
        [-Inf, 0, 1000, 3000, 6000, 10000, 15000, Inf], ...
        ["<0", "0-1k", "1k-3k", "3k-6k", "6k-10k", "10k-15k", ">=15k"]); ...
    localHistogramRows( ...
        "abs_turn_rate_degps", ...
        pairTable.absTurnRateDegreesPerSecond, ...
        [-Inf, 0.5, 1, 3, 10, Inf], ...
        ["<0.5", "0.5-1", "1-3", "3-10", ">=10"]); ...
    localHistogramRows( ...
        "abs_horizontal_acceleration_mps2", ...
        pairTable.absHorizontalAccelerationMetersPerSecondSquared, ...
        [-Inf, 0.1, 0.5, 1, 2, 5, Inf], ...
        ["<0.1", "0.1-0.5", "0.5-1", "1-2", "2-5", ">=5"]); ...
    localHistogramRows( ...
        "vertical_rate_mps", ...
        pairTable.verticalRateMetersPerSecond, ...
        [-Inf, -10, -5, -1, 1, 5, 10, Inf], ...
        ["<-10", "-10--5", "-5--1", "-1-1", "1-5", "5-10", ">=10"]); ...
    localHistogramRows( ...
        "dt_seconds", ...
        pairTable.dtSeconds, ...
        [-Inf, 0.75, 2, 5, 15, Inf], ...
        ["<0.75", "0.75-2", "2-5", "5-15", "15-30"])];

end

function rows = localHistogramRows(variableName, values, edges, labels)
%LOCALHISTOGRAMROWS Count finite values in fixed physical bins.

binIndex = discretize(values, edges);
variable = repmat(string(variableName), numel(labels), 1);
bin = labels(:);
binOrder = (1:numel(labels)).';
sampleCount = zeros(numel(labels), 1);
percent = zeros(numel(labels), 1);
finiteCount = sum(isfinite(values));

for binIdx = 1:numel(labels)
    sampleCount(binIdx) = sum(binIndex == binIdx);
    percent(binIdx) = 100 * sampleCount(binIdx) / max(finiteCount, 1);
end

rows = table(variable, bin, binOrder, sampleCount, percent);

end

function stage3BSummary = localResolveStage3BSummary(stageSummary)
%LOCALRESOLVESTAGE3BSUMMARY Accept a Stage 3B or Stage 3C summary.

if isstruct(stageSummary) && isfield(stageSummary, "stage3BSummary")
    stage3BSummary = stageSummary.stage3BSummary;
else
    stage3BSummary = stageSummary;
end

end

function localValidateInputs(stage3BSummary, variantID)
%LOCALVALIDATEINPUTS Validate fields required for motion analysis.

requiredFields = [ ...
    "previousState", ...
    "nextState", ...
    "dtSeconds", ...
    "metadata", ...
    "maneuverPairTable", ...
    "pairErrorTable", ...
    "labelSummary"];

if ~isstruct(stage3BSummary) || ...
        any(~isfield(stage3BSummary, requiredFields))
    error("Stage4BPost:InvalidStageSummary", ...
        "Input must contain the required Stage 3B evaluation fields.");
end

if ~isscalar(variantID) || ismissing(variantID) || ...
        strlength(strtrim(variantID)) == 0
    error("Stage4BPost:InvalidVariantID", ...
        "variantID must be a nonempty string scalar.");
end

pairCount = size(stage3BSummary.previousState, 1);

if size(stage3BSummary.previousState, 2) ~= 6 || ...
        size(stage3BSummary.nextState, 1) ~= pairCount || ...
        size(stage3BSummary.nextState, 2) ~= 6 || ...
        numel(stage3BSummary.dtSeconds) ~= pairCount || ...
        height(stage3BSummary.metadata) ~= pairCount || ...
        height(stage3BSummary.maneuverPairTable) ~= pairCount
    error("Stage4BPost:MotionPairSizeMismatch", ...
        "Stage summary arrays must describe identical N-by-6 state pairs.");
end

end

function pairTable = localBuildMotionPairTable(stage3BSummary, variantID)
%LOCALBUILDMOTIONPAIRTABLE Assemble continuous and categorical diagnostics.

metadata = stage3BSummary.metadata;
maneuver = stage3BSummary.maneuverPairTable;
pairCount = height(metadata);
receiverAltitude = metadata.receiverOriginLLA(:, 3);

pairTable = metadata(:, [ ...
    "sessionID", ...
    "sourceFile", ...
    "hex", ...
    "callsign", ...
    "timeUtcK", ...
    "timeUtcNext"]);
pairTable = addvars( ...
    pairTable, ...
    repmat(variantID, pairCount, 1), ...
    (1:pairCount).', ...
    'Before', ...
    1, ...
    'NewVariableNames', ...
    ["variantID", "pairIndex"]);
pairTable.trackID = pairTable.sessionID + "/" + pairTable.hex;
pairTable.campaignBlock = localCampaignBlocks( ...
    pairTable.sessionID, ...
    pairTable.timeUtcK);
pairTable.previousState = stage3BSummary.previousState;
pairTable.nextState = stage3BSummary.nextState;
pairTable.horizontalSpeedMetersPerSecond = ...
    maneuver.horizontalSpeedMetersPerSecondK;
pairTable.altitudeMeters = stage3BSummary.previousState(:, 5) + receiverAltitude;
pairTable.absTurnRateDegreesPerSecond = ...
    maneuver.absTurnRateDegreesPerSecond;
pairTable.absHorizontalAccelerationMetersPerSecondSquared = abs( ...
    maneuver.horizontalAccelerationMetersPerSecondSquared);
pairTable.verticalRateMetersPerSecond = ...
    maneuver.verticalRateMetersPerSecondK;
pairTable.absVerticalAccelerationMetersPerSecondSquared = abs( ...
    maneuver.verticalAccelerationMetersPerSecondSquared);
pairTable.dtSeconds = stage3BSummary.dtSeconds;
pairTable.maneuverClass = maneuver.maneuverClass;
pairTable.verticalStatus = maneuver.verticalStatus;
pairTable.dtRegime = maneuver.dtRegime;
pairTable.isTurnLike = maneuver.isTurnLike;
pairTable.isAccelerationLike = maneuver.isAccelerationLike;
pairTable.isSparseUpdate = maneuver.isSparseUpdate;
pairTable.turnIntensityBin = localBinValues( ...
    pairTable.absTurnRateDegreesPerSecond, ...
    [-Inf, 0.5, 1, 3, Inf], ...
    ["<0.5", "0.5-1", "1-3", ">=3"]);
pairTable.accelerationIntensityBin = localBinValues( ...
    pairTable.absHorizontalAccelerationMetersPerSecondSquared, ...
    [-Inf, 0.1, 0.5, 1, Inf], ...
    ["<0.1", "0.1-0.5", "0.5-1", ">=1"]);
pairTable.updateIntervalBin = localBinValues( ...
    pairTable.dtSeconds, ...
    [-Inf, 0.75, 2, 5, 15, Inf], ...
    ["<0.75", "0.75-2", "2-5", "5-15", "15-30"]);

end

function bins = localBinValues(values, edges, labels)
%LOCALBINVALUES Apply stable named bins while retaining missing values.

binIndex = discretize(values, edges);
binText = repmat("not_available", numel(values), 1);
validMask = ~isnan(binIndex);
binText(validMask) = labels(binIndex(validMask));
allLabels = [labels, "not_available"];
bins = categorical(binText, allLabels, allLabels, "Ordinal", true);

end

function campaignBlock = localCampaignBlocks(sessionID, fallbackTimeUtc)
%LOCALCAMPAIGNBLOCKS Map session timestamps into three 24-hour blocks.

campaignStartUtc = datetime(2026, 8, 19, 13, 25, 26, "TimeZone", "UTC");
sessionID = string(sessionID);
uniqueSessionIDs = unique(sessionID);
sessionBlock = repmat("outside_campaign", numel(uniqueSessionIDs), 1);

for sessionIdx = 1:numel(uniqueSessionIDs)
    currentSessionID = uniqueSessionIDs(sessionIdx);
    timestampMatch = regexp( ...
        char(currentSessionID), ...
        "\d{8}T\d{6}Z$", ...
        "match", ...
        "once");

    if isempty(timestampMatch) || ~startsWith(currentSessionID, "stage4B_3Day_")
        continue;
    end

    sessionTimeUtc = datetime( ...
        string(timestampMatch), ...
        "InputFormat", ...
        "yyyyMMdd'T'HHmmss'Z'", ...
        "TimeZone", ...
        "UTC");
    blockNumber = floor(days(sessionTimeUtc - campaignStartUtc)) + 1;

    if blockNumber >= 1 && blockNumber <= 3
        sessionBlock(sessionIdx) = "campaign_day_" + string(blockNumber);
    end
end

[isFound, sessionIndex] = ismember(sessionID, uniqueSessionIDs);
campaignBlock = repmat("outside_campaign", numel(sessionID), 1);
campaignBlock(isFound) = sessionBlock(sessionIndex(isFound));
fallbackMask = ~isFound & ~isnat(fallbackTimeUtc);
fallbackBlock = floor(days(fallbackTimeUtc(fallbackMask) - campaignStartUtc)) + 1;

for blockIdx = 1:3
    currentFallback = fallbackMask;
    currentFallback(fallbackMask) = fallbackBlock == blockIdx;
    campaignBlock(currentFallback) = "campaign_day_" + string(blockIdx);
end

end

function summary = localBuildContinuousSummary(pairTable)
%LOCALBUILDCONTINUOUSSUMMARY Report robust distribution statistics.

variable = [ ...
    "horizontal_speed_mps"; ...
    "altitude_m"; ...
    "abs_turn_rate_degps"; ...
    "abs_horizontal_acceleration_mps2"; ...
    "vertical_rate_mps"; ...
    "abs_vertical_acceleration_mps2"; ...
    "dt_seconds"];
units = ["m/s"; "m"; "deg/s"; "m/s^2"; "m/s"; "m/s^2"; "s"];
values = { ...
    pairTable.horizontalSpeedMetersPerSecond; ...
    pairTable.altitudeMeters; ...
    pairTable.absTurnRateDegreesPerSecond; ...
    pairTable.absHorizontalAccelerationMetersPerSecondSquared; ...
    pairTable.verticalRateMetersPerSecond; ...
    pairTable.absVerticalAccelerationMetersPerSecondSquared; ...
    pairTable.dtSeconds};
finiteCount = zeros(numel(variable), 1);
minimum = NaN(numel(variable), 1);
medianValue = NaN(numel(variable), 1);
percentile95 = NaN(numel(variable), 1);
maximum = NaN(numel(variable), 1);

for variableIdx = 1:numel(variable)
    finiteValues = values{variableIdx}(isfinite(values{variableIdx}));
    finiteCount(variableIdx) = numel(finiteValues);

    if isempty(finiteValues)
        continue;
    end

    minimum(variableIdx) = min(finiteValues);
    medianValue(variableIdx) = median(finiteValues);
    percentile95(variableIdx) = prctile(finiteValues, 95);
    maximum(variableIdx) = max(finiteValues);
end

summary = table( ...
    variable, ...
    units, ...
    finiteCount, ...
    minimum, ...
    medianValue, ...
    percentile95, ...
    maximum);

end

function summary = localBuildPairRegimeSummary(pairTable)
%LOCALBUILDPAIRREGIMESUMMARY Count pair and contributor support per bin.

summary = [ ...
    localSummarizeDimension(pairTable, "turn_intensity", "turnIntensityBin"); ...
    localSummarizeDimension(pairTable, "acceleration_intensity", "accelerationIntensityBin"); ...
    localSummarizeDimension(pairTable, "vertical_status", "verticalStatus"); ...
    localSummarizeDimension(pairTable, "update_interval", "updateIntervalBin"); ...
    localSummarizeDimension(pairTable, "legacy_maneuver_class", "maneuverClass")];

end

function summary = localSummarizeDimension(pairTable, dimensionName, variableName)
%LOCALSUMMARIZEDIMENSION Summarize all categories in one variable.

values = string(pairTable.(variableName));
regimes = unique(values, "stable");
dimension = repmat(string(dimensionName), numel(regimes), 1);
regime = regimes(:);
pairCount = zeros(numel(regimes), 1);
percent = zeros(numel(regimes), 1);
aircraftCount = zeros(numel(regimes), 1);
trackCount = zeros(numel(regimes), 1);
sessionCount = zeros(numel(regimes), 1);
campaignBlockCount = zeros(numel(regimes), 1);

for regimeIdx = 1:numel(regimes)
    rowMask = values == regimes(regimeIdx);
    pairCount(regimeIdx) = sum(rowMask);
    percent(regimeIdx) = 100 * pairCount(regimeIdx) / max(height(pairTable), 1);
    aircraftCount(regimeIdx) = numel(unique(pairTable.hex(rowMask)));
    trackCount(regimeIdx) = numel(unique(pairTable.trackID(rowMask)));
    sessionCount(regimeIdx) = numel(unique(pairTable.sessionID(rowMask)));
    campaignBlockCount(regimeIdx) = numel(unique( ...
        pairTable.campaignBlock(rowMask & startsWith( ...
        pairTable.campaignBlock, ...
        "campaign_day_"))));
end

summary = table( ...
    dimension, ...
    regime, ...
    pairCount, ...
    percent, ...
    aircraftCount, ...
    trackCount, ...
    sessionCount, ...
    campaignBlockCount);

end

function occupancy = localBuildJointRegimeOccupancy(pairTable)
%LOCALBUILDJOINTREGIMEOCCUPANCY Build the complete four-dimensional grid.

turnLevels = ["<0.5", "0.5-1", "1-3", ">=3"];
accelerationLevels = ["<0.1", "0.1-0.5", "0.5-1", ">=1"];
verticalLevels = ["descent", "level", "climb"];
updateLevels = ["<0.75", "0.75-2", "2-5", "5-15", "15-30"];
[turnGrid, accelerationGrid, verticalGrid, updateGrid] = ndgrid( ...
    turnLevels, ...
    accelerationLevels, ...
    verticalLevels, ...
    updateLevels);
turnIntensity = turnGrid(:);
accelerationIntensity = accelerationGrid(:);
verticalStatus = verticalGrid(:);
updateInterval = updateGrid(:);
pairCount = zeros(numel(turnIntensity), 1);
trackCount = zeros(numel(turnIntensity), 1);
aircraftCount = zeros(numel(turnIntensity), 1);
sessionCount = zeros(numel(turnIntensity), 1);

for cellIdx = 1:numel(turnIntensity)
    rowMask = string(pairTable.turnIntensityBin) == turnIntensity(cellIdx) & ...
        string(pairTable.accelerationIntensityBin) == accelerationIntensity(cellIdx) & ...
        string(pairTable.verticalStatus) == verticalStatus(cellIdx) & ...
        string(pairTable.updateIntervalBin) == updateInterval(cellIdx);
    pairCount(cellIdx) = sum(rowMask);
    trackCount(cellIdx) = numel(unique(pairTable.trackID(rowMask)));
    aircraftCount(cellIdx) = numel(unique(pairTable.hex(rowMask)));
    sessionCount(cellIdx) = numel(unique(pairTable.sessionID(rowMask)));
end

occupied = pairCount > 0;
occupancy = table( ...
    turnIntensity, ...
    accelerationIntensity, ...
    verticalStatus, ...
    updateInterval, ...
    pairCount, ...
    trackCount, ...
    aircraftCount, ...
    sessionCount, ...
    occupied);

end

function summary = localBuildEventSummary(eventTable)
%LOCALBUILDEVENTSUMMARY Measure event independence and concentration.

eventType = [ ...
    "sustained_turn"; ...
    "sustained_acceleration"; ...
    "sustained_climb"; ...
    "sustained_descent"; ...
    "sparse_gap"];
eventCount = zeros(numel(eventType), 1);
totalDurationSeconds = zeros(numel(eventType), 1);
medianDurationSeconds = NaN(numel(eventType), 1);
peakMagnitude = NaN(numel(eventType), 1);
aircraftCount = zeros(numel(eventType), 1);
trackCount = zeros(numel(eventType), 1);
sessionCount = zeros(numel(eventType), 1);
campaignBlockCount = zeros(numel(eventType), 1);
largestAircraftSharePercent = NaN(numel(eventType), 1);
largestSessionSharePercent = NaN(numel(eventType), 1);
largestCampaignBlockSharePercent = NaN(numel(eventType), 1);

for eventIdx = 1:numel(eventType)
    rowMask = eventTable.eventType == eventType(eventIdx);
    events = eventTable(rowMask, :);
    eventCount(eventIdx) = height(events);

    if isempty(events)
        continue;
    end

    totalDurationSeconds(eventIdx) = sum(events.durationSeconds);
    medianDurationSeconds(eventIdx) = median(events.durationSeconds);
    peakMagnitude(eventIdx) = max(events.peakMagnitude, [], "omitnan");
    aircraftCount(eventIdx) = numel(unique(events.hex));
    trackCount(eventIdx) = numel(unique(events.trackID));
    sessionCount(eventIdx) = numel(unique(events.sessionID));
    campaignMask = startsWith(events.campaignBlock, "campaign_day_");
    campaignBlockCount(eventIdx) = numel(unique(events.campaignBlock(campaignMask)));
    largestAircraftSharePercent(eventIdx) = localLargestShare(events.hex);
    largestSessionSharePercent(eventIdx) = localLargestShare(events.sessionID);
    largestCampaignBlockSharePercent(eventIdx) = ...
        localLargestShare(events.campaignBlock(campaignMask));
end

summary = table( ...
    eventType, ...
    eventCount, ...
    totalDurationSeconds, ...
    medianDurationSeconds, ...
    peakMagnitude, ...
    aircraftCount, ...
    trackCount, ...
    sessionCount, ...
    campaignBlockCount, ...
    largestAircraftSharePercent, ...
    largestSessionSharePercent, ...
    largestCampaignBlockSharePercent);

end

function sharePercent = localLargestShare(values)
%LOCALLARGESTSHARE Return the largest contributor share in percent.

values = string(values);

if isempty(values)
    sharePercent = NaN;
    return;
end

[group, ~] = findgroups(values);
counts = splitapply(@numel, values, group);
sharePercent = 100 * max(counts) / sum(counts);

end

function sourceSummary = localBuildSourceSummary(stageSummary, stage3BSummary)
%LOCALBUILDSOURCESUMMARY Record source parsing and trajectory counts.

sourceManifest = stage3BSummary.sourceManifest;
sourceFileCount = height(sourceManifest);
usableSourceFileCount = sum(sourceManifest.usablePairCount > 0);
parseFailureCount = sum(string(sourceManifest.parseStatus) == "failed");
sessionCount = numel(unique(stage3BSummary.metadata.sessionID));
aircraftCount = numel(unique(stage3BSummary.metadata.hex));
trackCount = numel(unique( ...
    stage3BSummary.metadata.sessionID + "/" + stage3BSummary.metadata.hex));
pairCount = size(stage3BSummary.previousState, 1);

sourceSummary = struct();
sourceSummary.sourceFileCount = sourceFileCount;
sourceSummary.usableSourceFileCount = usableSourceFileCount;
sourceSummary.parseFailureCount = parseFailureCount;
sourceSummary.sessionCount = sessionCount;
sourceSummary.aircraftCount = aircraftCount;
sourceSummary.aircraftTrackCount = trackCount;
sourceSummary.pairCount = pairCount;

if isfield(stageSummary, "archiveInventory")
    inventory = stageSummary.archiveInventory.sourceFileTable;
    sourceSummary.classifiedSourceFileCount = height(inventory);
    sourceSummary.unselectedSourceFileCount = sum(~inventory.selectedForEvaluation);
else
    sourceSummary.classifiedSourceFileCount = sourceFileCount;
    sourceSummary.unselectedSourceFileCount = 0;
end

end
