function benchmark = helperBuildStage4DRealDropoutBenchmark( ...
        dataset, split, varargin)
%HELPERBUILDSTAGE4DREALDROPOUTBENCHMARK Reconstruct held-out ADS-B events.
% Targets are always the next retained ADS-B observation. Dropout changes
% which observations are retained, but never synthesizes a target.

parser = inputParser;
parser.FunctionName = mfilename;
addRequired(parser, "dataset");
addRequired(parser, "split");
addParameter(parser, "BenchmarkMode", "smoke");
addParameter(parser, "Seed", 123);
addParameter(parser, "PreviousCovarianceDiag", [10000, 100, 10000, 100, 22500, 25]);
parse(parser, dataset, split, varargin{:});

benchmarkMode = lower(strtrim(string(parser.Results.BenchmarkMode)));
seed = double(parser.Results.Seed);
previousCovarianceDiag = double(parser.Results.PreviousCovarianceDiag(:).');
split = lower(strtrim(string(split(:))));
localValidateInputs( ...
    dataset, ...
    split, ...
    benchmarkMode, ...
    seed, ...
    previousCovarianceDiag);

stream = RandStream("mt19937ar", "Seed", seed + 3001);
profileTable = localRealProfileTable();
[orderedTestRows, eventID] = localFindTestEvents(dataset.metadata, split);
eventTable = localBuildEventTable(dataset.metadata, orderedTestRows, eventID);

if benchmarkMode == "smoke"
    eventTable = sortrows( ...
        eventTable, ...
        ["pairCount", "sessionID", "icao24", "startTime"], ...
        ["descend", "ascend", "ascend", "ascend"]);
    eventTable = eventTable(1:min(20, height(eventTable)), :);
    selectedEventIDs = eventTable.originalEventID;
    selectedMask = ismember(eventID, selectedEventIDs);
    orderedTestRows = orderedTestRows(selectedMask);
    eventID = eventID(selectedMask);
    [~, ~, eventID] = unique(eventID, "stable");
    eventTable = localBuildEventTable( ...
        dataset.metadata, ...
        orderedTestRows, ...
        eventID);
end

profilePairSets = repmat(localEmptyPairSet(), height(profileTable), 1);

for profileIdx = 1:height(profileTable)
    profilePairSets(profileIdx) = localBuildProfilePairs( ...
        dataset, ...
        orderedTestRows, ...
        eventID, ...
        profileTable.profile(profileIdx), ...
        stream, ...
        previousCovarianceDiag, ...
        (profileIdx - 1)*height(eventTable));
end

pairSet = localConcatenateProfiles(profilePairSets);
baselineRows = pairSet.profile == "baseline";
expectedPreviousState = double(dataset.previousState(orderedTestRows, :));
expectedTargetState = double(dataset.nextState(orderedTestRows, :));
baselineMatchesFrozenRows = ...
    isequal(pairSet.previousState(baselineRows, :), expectedPreviousState) && ...
    isequal(pairSet.targetState(baselineRows, :), expectedTargetState);

audit = struct();
audit.baseTrajectoryCount = height(eventTable);
audit.frozenTestPairCount = numel(orderedTestRows);
audit.baselinePairCount = sum(baselineRows);
audit.baselineMatchesFrozenRows = baselineMatchesFrozenRows;
audit.alignedRows = localAlignedRows(pairSet);
audit.finiteStates = ...
    all(isfinite(pairSet.previousState), "all") && ...
    all(isfinite(pairSet.targetState), "all");
audit.positiveDt = all(pairSet.dtSeconds > 0);
audit.monotonicTime = all( ...
    pairSet.timeNextSeconds > pairSet.timeKSeconds);
audit.retainedADSBTargets = all( ...
    pairSet.targetReference == "next_retained_adsb_observation");
audit.passed = audit.baselineMatchesFrozenRows && ...
    audit.alignedRows && ...
    audit.finiteStates && ...
    audit.positiveDt && ...
    audit.monotonicTime && ...
    audit.retainedADSBTargets;

benchmark = struct();
benchmark.groupName = "real_adsb";
benchmark.benchmarkMode = benchmarkMode;
benchmark.seed = seed + 3001;
benchmark.profileTable = profileTable;
benchmark.eventTable = eventTable;
benchmark.pairSet = pairSet;
benchmark.audit = audit;
benchmark.truthTrajectoryCount = height(eventTable);
benchmark.observedCaseCount = height(eventTable)*height(profileTable);

end

function profileTable = localRealProfileTable()
%LOCALREALPROFILETABLE Describe baseline and three dropout perturbations.

profileTable = table( ...
    ["baseline"; "random_dropout_10"; "random_dropout_25"; "burst_outage"], ...
    ["retain_all"; "independent_random"; "independent_random"; "contiguous_random"], ...
    [0; 0.10; 0.25; 0.20], ...
    [false; false; false; true], ...
    repmat("next_retained_adsb_observation", 4, 1), ...
    'VariableNames', [ ...
        "profile", ...
        "dropoutPolicy", ...
        "nominalDropoutFraction", ...
        "contiguousOutage", ...
        "targetReference"]);

end

function [orderedTestRows, eventID] = localFindTestEvents(metadata, split)
%LOCALFINDTESTEVENTS Sort frozen test rows and identify contiguous events.

testRows = find(split == "test");
ordering = table( ...
    string(metadata.sessionID(testRows)), ...
    lower(strtrim(string(metadata.hex(testRows)))), ...
    metadata.timeUtcK(testRows), ...
    metadata.timeUtcNext(testRows), ...
    testRows, ...
    'VariableNames', [ ...
        "sessionID", ...
        "icao24", ...
        "timeUtcK", ...
        "timeUtcNext", ...
        "datasetRow"]);
ordering = sortrows( ...
    ordering, ...
    ["sessionID", "icao24", "timeUtcK", "timeUtcNext", "datasetRow"]);
orderedTestRows = ordering.datasetRow;
rowCount = height(ordering);
newEvent = true(rowCount, 1);

if rowCount > 1
    sameTrack = ...
        ordering.sessionID(2:end) == ordering.sessionID(1:end - 1) & ...
        ordering.icao24(2:end) == ordering.icao24(1:end - 1);
    adjacentTime = abs(seconds( ...
        ordering.timeUtcK(2:end) - ordering.timeUtcNext(1:end - 1))) <= 1e-6;
    newEvent(2:end) = ~(sameTrack & adjacentTime);
end

eventID = cumsum(newEvent);

end

function eventTable = localBuildEventTable(metadata, orderedRows, eventID)
%LOCALBUILDEVENTTABLE Summarize the selected contiguous held-out events.

eventCount = max(eventID);
firstIndex = accumarray(eventID, (1:numel(eventID)).', [], @min);
lastIndex = accumarray(eventID, (1:numel(eventID)).', [], @max);
firstRows = orderedRows(firstIndex);
lastRows = orderedRows(lastIndex);
eventTable = table( ...
    (1:eventCount).', ...
    string(metadata.sessionID(firstRows)), ...
    lower(strtrim(string(metadata.hex(firstRows)))), ...
    metadata.timeUtcK(firstRows), ...
    metadata.timeUtcNext(lastRows), ...
    accumarray(eventID, 1), ...
    'VariableNames', [ ...
        "originalEventID", ...
        "sessionID", ...
        "icao24", ...
        "startTime", ...
        "endTime", ...
        "pairCount"]);

end

function pairSet = localBuildProfilePairs( ...
        dataset, ...
        orderedRows, ...
        eventID, ...
        profileName, ...
        stream, ...
        previousCovarianceDiag, ...
        eventOffset)
%LOCALBUILDPROFILEPAIRS Apply one dropout profile to all selected events.

eventCount = max(eventID);
previousStateParts = cell(eventCount, 1);
targetStateParts = cell(eventCount, 1);
dtParts = cell(eventCount, 1);
timeKParts = cell(eventCount, 1);
timeNextParts = cell(eventCount, 1);
eventParts = cell(eventCount, 1);
caseParts = cell(eventCount, 1);
receiverOriginParts = cell(eventCount, 1);

for currentEventID = 1:eventCount
    eventRows = orderedRows(eventID == currentEventID);
    observationState = [ ...
        double(dataset.previousState(eventRows, :)); ...
        double(dataset.nextState(eventRows(end), :))];
    eventStart = dataset.metadata.timeUtcK(eventRows(1));
    observationTime = [ ...
        seconds(dataset.metadata.timeUtcK(eventRows) - eventStart); ...
        seconds(dataset.metadata.timeUtcNext(eventRows(end)) - eventStart)];
    retainedMask = localRetainedObservationMask( ...
        numel(observationTime), ...
        profileName, ...
        stream);
    retainedState = observationState(retainedMask, :);
    retainedTime = observationTime(retainedMask);
    pairCount = numel(retainedTime) - 1;
    globalEventID = eventOffset + currentEventID;
    previousStateParts{currentEventID} = retainedState(1:end - 1, :);
    targetStateParts{currentEventID} = retainedState(2:end, :);
    dtParts{currentEventID} = diff(retainedTime);
    timeKParts{currentEventID} = retainedTime(1:end - 1);
    timeNextParts{currentEventID} = retainedTime(2:end);
    eventParts{currentEventID} = repmat(globalEventID, pairCount, 1);
    caseParts{currentEventID} = repmat( ...
        "real_event_" + compose("%05d", currentEventID) + "__" + profileName, ...
        pairCount, ...
        1);
    receiverOriginParts{currentEventID} = repmat( ...
        double(dataset.metadata.receiverOriginLLA(eventRows(1), :)), ...
        pairCount, ...
        1);
end

pairSet = localEmptyPairSet();
pairSet.previousState = vertcat(previousStateParts{:});
pairSet.targetState = vertcat(targetStateParts{:});
pairSet.dtSeconds = vertcat(dtParts{:});
pairSet.timeKSeconds = vertcat(timeKParts{:});
pairSet.timeNextSeconds = vertcat(timeNextParts{:});
pairSet.eventID = vertcat(eventParts{:});
pairSet.caseID = vertcat(caseParts{:});
pairSet.receiverOriginLLA = vertcat(receiverOriginParts{:});
rowCount = size(pairSet.previousState, 1);
pairSet.previousCovarianceDiag = repmat( ...
    previousCovarianceDiag, ...
    rowCount, ...
    1);
pairSet.profile = repmat(profileName, rowCount, 1);
pairSet.motionScenario = repmat("observed_adsb", rowCount, 1);
pairSet.motionMode = repmat("unlabeled_real_adsb", rowCount, 1);
pairSet.targetReference = repmat( ...
    "next_retained_adsb_observation", ...
    rowCount, ...
    1);
pairSet.transitionOffsetSeconds = NaN(rowCount, 1);

end

function retainedMask = localRetainedObservationMask( ...
        observationCount, profileName, stream)
%LOCALRETAINEDOBSERVATIONMASK Keep endpoints and apply the requested outage.

retainedMask = true(observationCount, 1);

switch profileName
    case "baseline"
        % No observations are removed.
    case "random_dropout_10"
        retainedMask = rand(stream, observationCount, 1) >= 0.10;
    case "random_dropout_25"
        retainedMask = rand(stream, observationCount, 1) >= 0.25;
    case "burst_outage"
        interiorCount = max(0, observationCount - 2);
        outageCount = min(interiorCount, max(1, round(0.20*observationCount)));

        if outageCount > 0
            maximumStart = observationCount - outageCount;
            outageStart = randi(stream, [2, maximumStart]);
            retainedMask(outageStart:(outageStart + outageCount - 1)) = false;
        end
    otherwise
        error("Stage4D:UnknownRealProfile", ...
            "Unknown real ADS-B profile: %s", profileName);
end

retainedMask([1, end]) = true;

end

function pairSet = localConcatenateProfiles(profilePairSets)
%LOCALCONCATENATEPROFILES Assemble one aligned real-ADS-B pair universe.

pairSet = localEmptyPairSet();
pairSet.domain = "real_adsb";
fields = [ ...
    "previousState", ...
    "targetState", ...
    "previousCovarianceDiag", ...
    "dtSeconds", ...
    "timeKSeconds", ...
    "timeNextSeconds", ...
    "eventID", ...
    "caseID", ...
    "profile", ...
    "motionScenario", ...
    "motionMode", ...
    "targetReference", ...
    "receiverOriginLLA", ...
    "transitionOffsetSeconds"];

for fieldIdx = 1:numel(fields)
    fieldName = fields(fieldIdx);
    pairSet.(fieldName) = vertcat(profilePairSets.(fieldName));
end

end

function aligned = localAlignedRows(pairSet)
%LOCALALIGNEDROWS Verify every pair metadata field has the same height.

rowCount = size(pairSet.previousState, 1);
fieldCounts = [ ...
    size(pairSet.targetState, 1), ...
    size(pairSet.previousCovarianceDiag, 1), ...
    numel(pairSet.dtSeconds), ...
    numel(pairSet.timeKSeconds), ...
    numel(pairSet.timeNextSeconds), ...
    numel(pairSet.eventID), ...
    numel(pairSet.caseID), ...
    numel(pairSet.profile), ...
    size(pairSet.receiverOriginLLA, 1), ...
    numel(pairSet.targetReference)];
aligned = all(fieldCounts == rowCount);

end

function pairSet = localEmptyPairSet()
%LOCALEMPTYPAIRSET Define the shared Stage 4D pair schema.

pairSet = struct( ...
    "domain", "", ...
    "previousState", zeros(0, 6), ...
    "targetState", zeros(0, 6), ...
    "previousCovarianceDiag", zeros(0, 6), ...
    "dtSeconds", zeros(0, 1), ...
    "timeKSeconds", zeros(0, 1), ...
    "timeNextSeconds", zeros(0, 1), ...
    "eventID", zeros(0, 1), ...
    "caseID", strings(0, 1), ...
    "profile", strings(0, 1), ...
    "motionScenario", strings(0, 1), ...
    "motionMode", strings(0, 1), ...
    "targetReference", strings(0, 1), ...
    "receiverOriginLLA", zeros(0, 3), ...
    "transitionOffsetSeconds", zeros(0, 1));

end

function localValidateInputs( ...
        dataset, ...
        split, ...
        benchmarkMode, ...
        seed, ...
        previousCovarianceDiag)
%LOCALVALIDATEINPUTS Enforce the frozen held-out dataset contract.

requiredFields = [ ...
    "previousState", ...
    "nextState", ...
    "dtSeconds", ...
    "metadata"];

if ~isstruct(dataset) || any(~isfield(dataset, requiredFields))
    error("Stage4D:InvalidRealDataset", ...
        "The real benchmark requires previous/next states, dt, and metadata.");
end

rowCount = size(dataset.previousState, 1);

if ~isequal(size(dataset.previousState), [rowCount, 6]) || ...
        ~isequal(size(dataset.nextState), [rowCount, 6]) || ...
        numel(dataset.dtSeconds) ~= rowCount || ...
        height(dataset.metadata) ~= rowCount || ...
        numel(split) ~= rowCount
    error("Stage4D:RealDatasetAlignmentMismatch", ...
        "Real ADS-B dataset fields and split must describe identical rows.");
end

requiredMetadata = ["sessionID", "hex", "timeUtcK", "timeUtcNext"];
requiredMetadata = [requiredMetadata, "receiverOriginLLA"];

if any(~ismember(requiredMetadata, string(dataset.metadata.Properties.VariableNames)))
    error("Stage4D:MissingRealMetadata", ...
        "Real ADS-B metadata must contain session, ICAO, and pair timestamps.");
end

if ~ismember(benchmarkMode, ["smoke", "full"])
    error("Stage4D:InvalidBenchmarkMode", ...
        "BenchmarkMode must be smoke or full.");
end

validateattributes(seed, ...
    {'numeric'}, {'scalar', 'integer', 'nonnegative', 'finite'}, ...
    mfilename, "Seed");
validateattributes(previousCovarianceDiag, ...
    {'numeric'}, {'row', 'numel', 6, 'real', 'finite', 'positive'}, ...
    mfilename, "PreviousCovarianceDiag");

end
