function tuning = helperTuneStage4EFilters( ...
        detectionLogs, truthTables, varargin)
%HELPERTUNESTAGE4EFILTERS Tune recursive filter parameters on validation.
% trackingFilterTuner adjusts process noise for each estimator and also
% adjusts transition probabilities for the native three-model IMM.

parser = inputParser;
parser.FunctionName = mfilename;
addRequired(parser, "detectionLogs");
addRequired(parser, "truthTables");
addParameter(parser, "OutputPath", "");
addParameter(parser, "Seed", 123);
addParameter(parser, "Verbose", true);
parse(parser, detectionLogs, truthTables, varargin{:});

outputPath = strtrim(string(parser.Results.OutputPath));
seed = double(parser.Results.Seed);
verbose = logical(parser.Results.Verbose);
localValidateInputs(detectionLogs, truthTables, seed);
previousRng = rng;
cleanup = onCleanup(@() rng(previousRng));
rng(seed, "twister");

specifications = table( ...
    [ ...
        "cv_ekf"; ...
        "ca_ekf"; ...
        "ct_ekf"; ...
        "native_imm"; ...
        "warm_ukf"], ...
    [ ...
        "helperInitStage4ECVEKF"; ...
        "helperInitStage4ECAEKF"; ...
        "helperInitStage4ECTEKF"; ...
        "helperInitStage4EIMM"; ...
        "helperInitStage4EWarmUKF"], ...
    'VariableNames', ["modelID", "initializationFunction"]);
parameterStruct = struct();
costRows = cell(height(specifications), 1);
solverOptions = optimoptions( ...
    "fmincon", ...
    Algorithm="sqp", ...
    Display="none", ...
    FiniteDifferenceType="forward", ...
    MaxIterations=3, ...
    MaxFunctionEvaluations=60);

for modelIdx = 1:height(specifications)
    modelID = specifications.modelID(modelIdx);
    initializationFunction = specifications.initializationFunction(modelIdx);

    if verbose
        fprintf("Tuning Stage 4E filter:\t%s\n", modelID);
    end

    initializationHandle = str2func(initializationFunction);
    initialFilter = initializationHandle(detectionLogs{1}{1});
    tunableProperties = localSelectTunableProperties(initialFilter, modelID);
    tuner = trackingFilterTuner( ...
        FilterInitializationFcn=initializationFunction, ...
        TunablePropertiesSource="Custom", ...
        CustomTunableProperties=tunableProperties, ...
        Cost="Custom", ...
        CustomCostFcn=@helperStage4ETuningCost, ...
        Solver="fmincon", ...
        SolverOptions=solverOptions, ...
        UseMex=false, ...
        UseParallel=false, ...
        Display="None");
    tuneTimer = tic;
    [tunedParameters, bestCost] = tune( ...
        tuner, ...
        detectionLogs, ...
        truthTables);
    elapsedSeconds = toc(tuneTimer);
    parameterField = matlab.lang.makeValidName(modelID);
    parameterStruct.(parameterField) = tunedParameters;
    costRows{modelIdx} = table( ...
        modelID, ...
        double(bestCost), ...
        elapsedSeconds, ...
        'VariableNames', ["modelID", "validationCost", "elapsedSeconds"]);
end

tuning = struct();
tuning.generatedAt = datetime("now", "TimeZone", "UTC");
tuning.stage = "4E";
tuning.tuner = "trackingFilterTuner";
tuning.solver = "fmincon";
tuning.solverOptions = struct( ...
    "algorithm", string(solverOptions.Algorithm), ...
    "maximumIterations", solverOptions.MaxIterations, ...
    "maximumFunctionEvaluations", solverOptions.MaxFunctionEvaluations);
tuning.cost = "normalized six-state validation RMSE";
tuning.seed = seed;
tuning.validationEventCount = numel(detectionLogs);
tuning.validationOnly = true;
tuning.networkTrainingPerformed = false;
tuning.specifications = specifications;
tuning.parameters = parameterStruct;
tuning.costTable = vertcat(costRows{:});
tuning.completed = all(isfinite(tuning.costTable.validationCost));

if strlength(outputPath) > 0
    outputFolder = string(fileparts(outputPath));

    if strlength(outputFolder) > 0 && ~isfolder(outputFolder)
        mkdir(outputFolder);
    end

    stage4ETuning = tuning;
    save(outputPath, "stage4ETuning", "-v7.3");
end

end

function properties = localSelectTunableProperties(filter, modelID)
%LOCALSELECTTUNABLEPROPERTIES Limit tuning to process and IMM transition.

properties = tunableProperties(filter);

if modelID == "native_imm"
    setPropertyTunability( ...
        properties, ...
        "ModelProbabilities", ...
        IsTuned=false);
    transitionElements = 1:numel(filter.TransitionProbabilities);
    setPropertyTunability( ...
        properties, ...
        "TransitionProbabilities", ...
        IsTuned=true, ...
        TunableElements=transitionElements, ...
        LowerBound=0.001*ones(size(transitionElements)), ...
        UpperBound=ones(size(transitionElements)));

    for filterIdx = 1:numel(filter.TrackingFilters)
        localConfigureProcessNoise(properties, filter.TrackingFilters{filterIdx}, filterIdx);
    end
else
    setPropertyTunability(properties, "StateCovariance", IsTuned=false);
    localConfigureProcessNoise(properties, filter, []);

    if modelID == "warm_ukf"
        setPropertyTunability(properties, "Alpha", IsTuned=false);
        setPropertyTunability(properties, "Beta", IsTuned=false);
        setPropertyTunability(properties, "Kappa", IsTuned=false);
    end
end

end

function localConfigureProcessNoise(properties, filter, filterIdx)
%LOCALCONFIGUREPROCESSNOISE Tune diagonal square-root noise entries only.

noiseDimension = size(filter.ProcessNoise, 1);
diagonalElements = 1:(noiseDimension + 1):(noiseDimension^2);
initialStandardDeviation = sqrt(diag(filter.ProcessNoise)).';
lowerBound = max(1e-4, 0.05*initialStandardDeviation);
upperBound = max(lowerBound + 1e-4, 20*initialStandardDeviation);

if isempty(filterIdx)
    setPropertyTunability( ...
        properties, ...
        "ProcessNoise", ...
        IsTuned=true, ...
        TunableElements=diagonalElements, ...
        LowerBound=lowerBound, ...
        UpperBound=upperBound);
else
    setPropertyTunability( ...
        properties, ...
        "StateCovariance", ...
        FilterIndex=filterIdx, ...
        IsTuned=false);
    setPropertyTunability( ...
        properties, ...
        "ProcessNoise", ...
        FilterIndex=filterIdx, ...
        IsTuned=true, ...
        TunableElements=diagonalElements, ...
        LowerBound=lowerBound, ...
        UpperBound=upperBound);
end

end

function localValidateInputs(detectionLogs, truthTables, seed)
%LOCALVALIDATEINPUTS Validate the validation-only tuning dataset.

if ~iscell(detectionLogs) || ...
        isempty(detectionLogs) || ...
        ~iscell(truthTables) || ...
        numel(detectionLogs) ~= numel(truthTables)
    error("Stage4E:InvalidTuningData", ...
        "Detection logs and truth tables must be nonempty aligned cell arrays.");
end

validateattributes(seed, ...
    {'numeric'}, {'scalar', 'integer', 'nonnegative', 'finite'}, ...
    mfilename, "Seed");

end
