function output = helperOpenStage4CReviewGlobe(reviewData, motionClass, varargin)
%HELPEROPENSTAGE4CREVIEWGLOBE Open an independent Stage 4C globe viewer.
% Use helperOpenStage4CReviewGlobe(representative) for the original
% single-event interface. For an on-demand collection, pass the dashboard,
% a motion class, and optionally TrajectoryCount=N.

if nargin == 1
    representative = reviewData;
    localValidateRepresentative(representative);
    trajectoryData = representative.trajectories;
    receiverOriginLLA = representative.receiverOriginLLA;
    legendTable = representative.legendTable;
    representativeLabel = representative.label;
    collection = struct();
    collectionLabel = "";
    plottedTrajectoryCount = 1;
else
    collection = helperBuildStage4CTrajectoryCollection( ...
        reviewData, ...
        motionClass, ...
        varargin{:});
    trajectoryData = collection.trajectories;
    receiverOriginLLA = collection.receiverOriginLLA;
    legendTable = collection.legendTable;
    representativeLabel = "";
    collectionLabel = collection.label;
    plottedTrajectoryCount = collection.plottedTrajectoryCount;
end

colors = struct();
colors.truth = [0.0000, 0.6500, 0.2500];
colors.native = [0.0000, 0.3000, 1.0000];
colors.legacy = [0.9000, 0.0500, 0.0500];
colors.scratch = [0.9290, 0.6940, 0.1250];
colors.warm = [0.4940, 0.1840, 0.5560];
viewer = trackingGlobeViewer( ...
    ReferenceLocation=receiverOriginLLA, ...
    PlatformHistoryDepth=10000, ...
    TrackHistoryDepth=10000);

% plotTrajectory accepts a cell array of geoTrajectory objects. One call
% per model therefore draws N event paths while keeping the call count at
% five. Learned predictions are drawn first and truth last so observations
% remain visible where paths overlap.
plotTrajectory( ...
    viewer, ...
    trajectoryData.warm, ...
    Color=colors.warm, ...
    LineWidth=int32(2));
plotTrajectory( ...
    viewer, ...
    trajectoryData.scratch, ...
    Color=colors.scratch, ...
    LineWidth=int32(2));
plotTrajectory( ...
    viewer, ...
    trajectoryData.legacy, ...
    Color=colors.legacy, ...
    LineWidth=int32(2));
plotTrajectory( ...
    viewer, ...
    trajectoryData.native, ...
    Color=colors.native, ...
    LineWidth=int32(3));
plotTrajectory( ...
    viewer, ...
    trajectoryData.truth, ...
    Color=colors.truth, ...
    LineWidth=int32(4));

output = struct();
output.viewer = viewer;
output.legendTable = legendTable;
output.representativeLabel = representativeLabel;
output.collectionLabel = collectionLabel;
output.collection = collection;
output.plottedTrajectoryCount = plottedTrajectoryCount;
output.trajectoryPathCount = 5 * plottedTrajectoryCount;
output.plotCallCount = 5;
output.colors = colors;

end

function localValidateRepresentative(representative)
%LOCALVALIDATEREPRESENTATIVE Preserve the original one-event contract.

requiredFields = [ ...
    "receiverOriginLLA"; ...
    "trajectories"; ...
    "legendTable"; ...
    "label"];

if any(~isfield(representative, requiredFields))
    error( ...
        "StageReview:InvalidStage4CRepresentative", ...
        "The representative trajectory is missing required viewer data.");
end

end
