function dashboard = helperBuildStage4CReviewDashboard(varargin)
%HELPERBUILDSTAGE4CREVIEWDASHBOARD Build the frozen Stage 4C review data.
% The helper loads the Expanded-3Day dataset and completed Stage 4C
% comparison, but it does not train, smooth, clip, or write artifacts.
% Neural inference is limited to the three representative test events.

projectRoot = string(fileparts(mfilename("fullpath")));
parser = inputParser;
parser.FunctionName = mfilename;
addParameter(parser, "ProjectRoot", projectRoot);
addParameter(parser, "DatasetPath", "");
addParameter(parser, "SplitManifestPath", "");
addParameter(parser, "ComparisonArtifactPath", "");
addParameter(parser, "Stage3AArtifactPath", "");
addParameter(parser, "ScratchArtifactPath", "");
addParameter(parser, "WarmArtifactPath", "");
addParameter(parser, "PredictionMiniBatchSize", 8192);
parse(parser, varargin{:});

config = localBuildConfig(parser.Results);
localValidateFiles(config);
dataset = localLoadDataset(config.DatasetPath);
stage4CSummary = localLoadComparison(config.ComparisonArtifactPath);
sourceHashes = localValidateFrozenProvenance(config, stage4CSummary);
split = localLoadFrozenSplit(dataset.metadata, config.SplitManifestPath);
maneuverPairTable = helperAssignADSBManeuverLabels( ...
    dataset.previousState, ...
    dataset.nextState, ...
    dataset.dtSeconds);

splitSummaryTable = localBuildSplitSummary(split);
motionClassSplitTable = localBuildMotionClassSplitTable( ...
    maneuverPairTable.maneuverClass, ...
    split);
rmseTable = localBuildRMSETable(stage4CSummary);

models = localLoadModels(config);
motionClasses = [ ...
    "constvel_like"; ...
    "constacc_like"; ...
    "constturn_like"];
nativeModelIDs = ["constvel"; "constacc"; "constturn"];
representatives = repmat(localEmptyRepresentative(), 3, 1);

for classIdx = 1:numel(motionClasses)
    candidateRows = localEligibleTestRows( ...
        motionClasses(classIdx), ...
        split, ...
        maneuverPairTable, ...
        stage4CSummary.nativeManeuverBaseline.selectionTable);
    eventTable = localBuildEventTable(candidateRows, dataset.metadata);
    representatives(classIdx) = localBuildRepresentative( ...
        motionClasses(classIdx), ...
        nativeModelIDs(classIdx), ...
        eventTable, ...
        dataset, ...
        split, ...
        models, ...
        config.PredictionMiniBatchSize);
end

localValidateDashboard( ...
    dataset, ...
    splitSummaryTable, ...
    motionClassSplitTable, ...
    rmseTable, ...
    representatives);

dashboard = struct();
dashboard.datasetName = "Expanded-3Day";
dashboard.datasetVariantID = "expanded_post3day_v2";
dashboard.datasetPairCount = size(dataset.previousState, 1);
dashboard.stateOrder = string(dataset.stateOrder);
dashboard.splitSummaryTable = splitSummaryTable;
dashboard.motionClassSplitTable = motionClassSplitTable;
dashboard.rmseTable = rmseTable;
dashboard.representatives = representatives;
dashboard.modelIdentityTable = localBuildModelIdentityTable( ...
    config, ...
    stage4CSummary);
dashboard.metricDefinition = ...
    "Pair-weighted aggregate 3-D error, reported separately for position and velocity.";
dashboard.trajectoryDefinition = ...
    "Sequences of one-step predictions from observed previous states; not recursive forecasts or tracker outputs.";
dashboard.trainingPerformed = false;
dashboard.clippingApplied = false;
dashboard.smoothingApplied = false;
dashboard.sourcePaths = struct( ...
    "dataset", config.DatasetPath, ...
    "splitManifest", config.SplitManifestPath, ...
    "comparisonArtifact", config.ComparisonArtifactPath);
dashboard.sourceHashes = sourceHashes;
dashboard.predictionMiniBatchSize = config.PredictionMiniBatchSize;

end

function config = localBuildConfig(opts)
%LOCALBUILDCONFIG Resolve all frozen input paths.

config = struct();
config.ProjectRoot = string(opts.ProjectRoot);
config.DatasetPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.DatasetPath, ...
    fullfile( ...
        "artifacts", ...
        "stage4BPostCampaign", ...
        "expanded_post3day_v2", ...
        "stage3CArchiveStatePairDataset.mat"));
config.SplitManifestPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.SplitManifestPath, ...
    fullfile( ...
        "adsb_archive", ...
        "datasetVersions", ...
        "expandedPost3DayICAODisjointSplit_v1.csv"));
config.ComparisonArtifactPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.ComparisonArtifactPath, ...
    fullfile( ...
        "artifacts", ...
        "stage4CRetrain", ...
        "expandedPost3DayMeanMLPComparison_v1.mat"));
config.Stage3AArtifactPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.Stage3AArtifactPath, ...
    fullfile( ...
        "artifacts", ...
        "stage3", ...
        "localADSBMLPStage3Training.mat"));
config.ScratchArtifactPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.ScratchArtifactPath, ...
    fullfile( ...
        "artifacts", ...
        "stage4CRetrain", ...
        "expandedPost3DayScratchMeanMLP_v1.mat"));
config.WarmArtifactPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.WarmArtifactPath, ...
    fullfile( ...
        "artifacts", ...
        "stage4CRetrain", ...
        "expandedPost3DayWarmStartMeanMLP_v1.mat"));
config.PredictionMiniBatchSize = double(opts.PredictionMiniBatchSize);

validateattributes( ...
    config.PredictionMiniBatchSize, ...
    {'numeric'}, ...
    {'scalar', 'integer', 'positive'}, ...
    mfilename, ...
    "PredictionMiniBatchSize");

end

function resolvedPath = localResolvePath(projectRoot, suppliedPath, defaultPath)
%LOCALRESOLVEPATH Resolve optional paths relative to the project root.

suppliedPath = string(suppliedPath);

if strlength(suppliedPath) == 0
    suppliedPath = string(defaultPath);
end

if localIsAbsolutePath(suppliedPath)
    resolvedPath = suppliedPath;
else
    resolvedPath = string(fullfile(projectRoot, suppliedPath));
end

end

function tf = localIsAbsolutePath(pathValue)
%LOCALISABSOLUTEPATH Recognize Windows, UNC, and rooted paths.

pathValue = char(string(pathValue));
tf = ~isempty(regexp(pathValue, '^[A-Za-z]:[\\/]', 'once')) || ...
    startsWith(pathValue, "\\") || ...
    startsWith(pathValue, "/");

end

function localValidateFiles(config)
%LOCALVALIDATEFILES Fail clearly when a frozen input is unavailable.

paths = [ ...
    config.DatasetPath; ...
    config.SplitManifestPath; ...
    config.ComparisonArtifactPath; ...
    config.Stage3AArtifactPath; ...
    config.ScratchArtifactPath; ...
    config.WarmArtifactPath];
missing = paths(~isfile(paths));

if ~isempty(missing)
    error( ...
        "StageReview:MissingStage4CInput", ...
        "Missing frozen Stage 4C input: %s", ...
        strjoin(missing, ", "));
end

end

function dataset = localLoadDataset(datasetPath)
%LOCALLOADDATASET Load only fields needed by the review dashboard.

try
    dataset = load( ...
        datasetPath, ...
        "previousState", ...
        "nextState", ...
        "dtSeconds", ...
        "previousCovarianceDiag", ...
        "metadata", ...
        "baselineConstVelMetrics", ...
        "stateOrder");
catch err
    error( ...
        "StageReview:Stage4CDatasetLoadFailed", ...
        "Unable to load the Expanded-3Day dataset: %s", ...
        err.message);
end

requiredFields = [ ...
    "previousState"; ...
    "nextState"; ...
    "dtSeconds"; ...
    "previousCovarianceDiag"; ...
    "metadata"; ...
    "baselineConstVelMetrics"; ...
    "stateOrder"];

if any(~isfield(dataset, requiredFields))
    error( ...
        "StageReview:InvalidStage4CDataset", ...
        "The Expanded-3Day dataset is missing a required field.");
end

pairCount = size(dataset.previousState, 1);
expectedStateOrder = ["x", "vx", "y", "vy", "z", "vz"];

if pairCount ~= 457903 || ...
        ~isequal(size(dataset.previousState), [pairCount, 6]) || ...
        ~isequal(size(dataset.nextState), [pairCount, 6]) || ...
        ~isequal(size(dataset.previousCovarianceDiag), [pairCount, 6]) || ...
        numel(dataset.dtSeconds) ~= pairCount || ...
        height(dataset.metadata) ~= pairCount || ...
        any(string(dataset.stateOrder(:).') ~= expectedStateOrder)
    error( ...
        "StageReview:Stage4CDatasetContractMismatch", ...
        "The frozen Expanded-3Day dataset contract has changed.");
end

if ~isfield(dataset.baselineConstVelMetrics, "predictedState") || ...
        ~isequal( ...
        size(dataset.baselineConstVelMetrics.predictedState), ...
        [pairCount, 6])
    error( ...
        "StageReview:MissingStage4CConstvelPrediction", ...
        "The dataset lacks aligned native constvel predictions.");
end

end

function stage4CSummary = localLoadComparison(comparisonPath)
%LOCALLOADCOMPARISON Load compact frozen Stage 4C evaluation evidence.

try
    loaded = load(comparisonPath, "stage4CSummary");
catch err
    error( ...
        "StageReview:Stage4CComparisonLoadFailed", ...
        "Unable to load the Stage 4C comparison artifact: %s", ...
        err.message);
end

if ~isfield(loaded, "stage4CSummary") || ...
        ~isfield(loaded.stage4CSummary, "completed") || ...
        ~loaded.stage4CSummary.completed || ...
        ~isfield(loaded.stage4CSummary, "nativeManeuverBaseline") || ...
        ~loaded.stage4CSummary.nativeManeuverBaseline.completed
    error( ...
        "StageReview:IncompleteStage4CComparison", ...
        "A completed Stage 4C comparison with native baselines is required.");
end

stage4CSummary = loaded.stage4CSummary;

end

function sourceHashes = localValidateFrozenProvenance(config, stage4CSummary)
%LOCALVALIDATEFROZENPROVENANCE Match the completed Stage 4C input hashes.

datasetSHA256 = helperComputeFileSHA256(config.DatasetPath);
splitSHA256 = helperComputeFileSHA256(config.SplitManifestPath);

if ~strcmpi( ...
        datasetSHA256, ...
        stage4CSummary.datasetProvenance.datasetSHA256) || ...
        ~strcmpi( ...
        splitSHA256, ...
        stage4CSummary.splitProvenance.splitManifestSHA256)
    error( ...
        "StageReview:Stage4CFrozenInputHashMismatch", ...
        "The Expanded-3Day dataset or split manifest differs from Stage 4C.");
end

sourceHashes = struct( ...
    "dataset", string(datasetSHA256), ...
    "splitManifest", string(splitSHA256));

end

function split = localLoadFrozenSplit(metadata, splitManifestPath)
%LOCALLOADFROZENSPLIT Apply the global ICAO-disjoint split manifest.

manifest = readtable(splitManifestPath, TextType="string");
requiredVariables = ["icao24", "split"];

if any(~ismember(requiredVariables, ...
        string(manifest.Properties.VariableNames)))
    error( ...
        "StageReview:InvalidStage4CSplitManifest", ...
        "The frozen split manifest must contain icao24 and split.");
end

manifest.icao24 = lower(strtrim(string(manifest.icao24)));
manifest.split = lower(strtrim(string(manifest.split)));

if numel(unique(manifest.icao24)) ~= height(manifest)
    error( ...
        "StageReview:DuplicateStage4CICAO", ...
        "Every ICAO must occur exactly once in the frozen split manifest.");
end

[found, manifestRow] = ismember( ...
    lower(strtrim(string(metadata.hex))), ...
    manifest.icao24);

if ~all(found)
    error( ...
        "StageReview:Stage4CSplitMembershipMismatch", ...
        "Every Expanded-3Day ICAO must occur in the frozen split manifest.");
end

split = manifest.split(manifestRow);
expectedCounts = [277959, 86420, 93524];
actualCounts = [ ...
    sum(split == "train"), ...
    sum(split == "validation"), ...
    sum(split == "test")];

if ~isequal(actualCounts, expectedCounts)
    error( ...
        "StageReview:Stage4CSplitCountMismatch", ...
        "The frozen train/validation/test pair counts have changed.");
end

end

function summaryTable = localBuildSplitSummary(split)
%LOCALBUILDSPLITSUMMARY Summarize frozen pair and aircraft allocation.

splitNames = ["train"; "validation"; "test"];
displayName = ["Train"; "Validation"; "Test"];
pairCount = zeros(3, 1);
pairPercent = zeros(3, 1);

for splitIdx = 1:numel(splitNames)
    pairCount(splitIdx) = sum(split == splitNames(splitIdx));
    pairPercent(splitIdx) = 100 * pairCount(splitIdx) / numel(split);
end

summaryTable = table( ...
    splitNames, ...
    displayName, ...
    pairCount, ...
    pairPercent, ...
    'VariableNames', [ ...
        "split", ...
        "displayName", ...
        "pairCount", ...
        "pairPercent"]);

end

function countTable = localBuildMotionClassSplitTable(maneuverClass, split)
%LOCALBUILDMOTIONCLASSSPLITTABLE Cross-tabulate all frozen rows.

motionClass = [ ...
    "constvel_like"; ...
    "constacc_like"; ...
    "constturn_like"; ...
    "mixed_or_sparse"];
train = zeros(4, 1);
validation = zeros(4, 1);
test = zeros(4, 1);

for classIdx = 1:numel(motionClass)
    classMask = string(maneuverClass) == motionClass(classIdx);
    train(classIdx) = sum(classMask & split == "train");
    validation(classIdx) = sum(classMask & split == "validation");
    test(classIdx) = sum(classMask & split == "test");
end

total = train + validation + test;
countTable = table( ...
    motionClass, ...
    train, ...
    validation, ...
    test, ...
    total);
countTable = [ ...
    countTable; ...
    table( ...
        "all", ...
        sum(train), ...
        sum(validation), ...
        sum(test), ...
        sum(total), ...
        'VariableNames', countTable.Properties.VariableNames)];

end

function rmseTable = localBuildRMSETable(stage4CSummary)
%LOCALBUILDRMSETABLE Select the 3-by-2 dashboard's matched comparisons.

motionClasses = [ ...
    "constvel_like"; ...
    "constacc_like"; ...
    "constturn_like"];
nativeModelIDs = ["constvel"; "constacc"; "constturn"];
neuralModelIDs = [ ...
    "legacy_stage3a_v1"; ...
    "expanded_scratch_mean_v1"; ...
    "expanded_warm_mean_v1"];
splitNames = ["validation"; "test"];
outputRows = cell(24, 1);
outputRow = 0;
baseMetrics = stage4CSummary.metrics.table;
nativeMetrics = stage4CSummary.nativeManeuverBaseline.metrics.table;

for classIdx = 1:numel(motionClasses)
    modelIDs = [nativeModelIDs(classIdx); neuralModelIDs];

    for splitIdx = 1:numel(splitNames)
        if motionClasses(classIdx) == "constvel_like"
            source = baseMetrics( ...
                baseMetrics.groupDimension == "maneuver_class" & ...
                baseMetrics.groupName == motionClasses(classIdx) & ...
                baseMetrics.weighting == "pair_weighted" & ...
                baseMetrics.split == splitNames(splitIdx), :);
        else
            source = nativeMetrics( ...
                nativeMetrics.groupName == motionClasses(classIdx) & ...
                nativeMetrics.weighting == "pair_weighted" & ...
                nativeMetrics.split == splitNames(splitIdx), :);
        end

        for modelIdx = 1:numel(modelIDs)
            selected = source(source.modelID == modelIDs(modelIdx), :);

            if height(selected) ~= 1
                error( ...
                    "StageReview:Stage4CRMSEIdentityMismatch", ...
                    "Expected one %s/%s/%s metric row.", ...
                    motionClasses(classIdx), ...
                    splitNames(splitIdx), ...
                    modelIDs(modelIdx));
            end

            outputRow = outputRow + 1;
            outputRows{outputRow} = table( ...
                motionClasses(classIdx), ...
                nativeModelIDs(classIdx), ...
                selected.modelID, ...
                localModelDisplayName( ...
                selected.modelID, ...
                nativeModelIDs(classIdx)), ...
                selected.split, ...
                selected.sampleCount, ...
                selected.eventCount, ...
                selected.positionRMSEMeters, ...
                selected.velocityRMSEMetersPerSecond, ...
                'VariableNames', [ ...
                    "motionClass", ...
                    "nativeModelID", ...
                    "modelID", ...
                    "modelDisplayName", ...
                    "split", ...
                    "sampleCount", ...
                    "eventCount", ...
                    "positionRMSEMeters", ...
                    "velocityRMSEMetersPerSecond"]);
        end
    end
end

rmseTable = vertcat(outputRows{:});

end

function displayName = localModelDisplayName(modelID, nativeModelID)
%LOCALMODELDISPLAYNAME Give the RMSE chart concise labels.

if modelID == nativeModelID
    displayName = "Native " + modelID;
elseif modelID == "legacy_stage3a_v1"
    displayName = "Stage 3A legacy";
elseif modelID == "expanded_scratch_mean_v1"
    displayName = "Expanded scratch";
elseif modelID == "expanded_warm_mean_v1"
    displayName = "Expanded warm";
else
    error( ...
        "StageReview:UnknownStage4CModel", ...
        "Unexpected Stage 4C model identity: %s", ...
        modelID);
end

end

function models = localLoadModels(config)
%LOCALLOADMODELS Load the three frozen neural predictors once.

models = repmat(struct( ...
    "modelID", "", ...
    "net", [], ...
    "featureNormalization", [], ...
    "targetNormalization", []), ...
    3, ...
    1);
models(1) = localLoadModel( ...
    config.Stage3AArtifactPath, ...
    "legacy_stage3a_v1", ...
    "physicsFeatures");
models(2) = localLoadModel( ...
    config.ScratchArtifactPath, ...
    "expanded_scratch_mean_v1", ...
    "features");
models(3) = localLoadModel( ...
    config.WarmArtifactPath, ...
    "expanded_warm_mean_v1", ...
    "features");

end

function model = localLoadModel(artifactPath, expectedModelID, featureField)
%LOCALLOADMODEL Resolve a frozen network and its normalization.

try
    loaded = load(artifactPath, "net", "normalization");
catch err
    error( ...
        "StageReview:Stage4CModelLoadFailed", ...
        "Unable to load frozen model %s: %s", ...
        artifactPath, ...
        err.message);
end

if ~isfield(loaded, "net") || ...
        ~isfield(loaded, "normalization") || ...
        ~isfield(loaded.normalization, featureField) || ...
        ~isfield(loaded.normalization, "target")
    error( ...
        "StageReview:InvalidStage4CModelArtifact", ...
        "Frozen model %s lacks its network or normalization.", ...
        artifactPath);
end

if ismember("modelArtifact", string(who("-file", artifactPath)))
    identityRecord = load(artifactPath, "modelArtifact");

    if isfield(identityRecord.modelArtifact, "modelID") && ...
            string(identityRecord.modelArtifact.modelID) ~= expectedModelID
        error( ...
            "StageReview:Stage4CModelIdentityMismatch", ...
            "Expected model %s in %s.", ...
            expectedModelID, ...
            artifactPath);
    end
end

model = struct();
model.modelID = expectedModelID;
model.net = loaded.net;
model.featureNormalization = loaded.normalization.(featureField);
model.targetNormalization = loaded.normalization.target;

end

function candidateRows = localEligibleTestRows( ...
        motionClass, split, maneuverPairTable, selectionTable)
%LOCALELIGIBLETESTROWS Resolve each class's exact eligible test rows.

if motionClass == "constvel_like"
    candidateRows = find( ...
        split == "test" & ...
        string(maneuverPairTable.maneuverClass) == motionClass);
    return;
end

selectionMask = ...
    selectionTable.split == "test" & ...
    selectionTable.maneuverSlice == motionClass;

if sum(selectionMask) ~= 1
    error( ...
        "StageReview:Stage4CSelectionMismatch", ...
        "Expected one frozen test selection for %s.", ...
        motionClass);
end

candidateRows = selectionTable.datasetRowIndices{selectionMask};
candidateRows = candidateRows(:);

end

function eventTable = localBuildEventTable(candidateRows, metadata)
%LOCALBUILDEVENTTABLE Segment contiguous rows and rank longest first.

candidateRows = unique(double(candidateRows(:)), "stable");

if isempty(candidateRows)
    error( ...
        "StageReview:NoEligibleStage4CTrajectory", ...
        "No eligible test rows are available for a representative trajectory.");
end

ordering = table( ...
    string(metadata.sessionID(candidateRows)), ...
    lower(strtrim(string(metadata.hex(candidateRows)))), ...
    metadata.timeUtcK(candidateRows), ...
    metadata.timeUtcNext(candidateRows), ...
    candidateRows, ...
    'VariableNames', [ ...
        "sessionID", ...
        "icao24", ...
        "timeUtcK", ...
        "timeUtcNext", ...
        "datasetRow"]);
ordering = sortrows( ...
    ordering, ...
    ["sessionID", "icao24", "timeUtcK", "timeUtcNext", "datasetRow"]);
newEvent = true(height(ordering), 1);

if height(ordering) > 1
    sameTrack = ...
        ordering.sessionID(2:end) == ordering.sessionID(1:end - 1) & ...
        ordering.icao24(2:end) == ordering.icao24(1:end - 1);
    adjacentPair = abs(seconds( ...
        ordering.timeUtcK(2:end) - ...
        ordering.timeUtcNext(1:end - 1))) <= 1e-6;
    newEvent(2:end) = ~(sameTrack & adjacentPair);
end

eventID = cumsum(newEvent);
eventCount = eventID(end);
sessionID = strings(eventCount, 1);
icao24 = strings(eventCount, 1);
callsign = strings(eventCount, 1);
startTimeUtc = NaT(eventCount, 1, "TimeZone", "UTC");
endTimeUtc = NaT(eventCount, 1, "TimeZone", "UTC");
pairCount = zeros(eventCount, 1);
firstDatasetRow = zeros(eventCount, 1);
datasetRowIndices = cell(eventCount, 1);

for eventIdx = 1:eventCount
    rows = ordering.datasetRow(eventID == eventIdx);
    datasetRowIndices{eventIdx} = rows;
    sessionID(eventIdx) = string(metadata.sessionID(rows(1)));
    icao24(eventIdx) = lower(strtrim(string(metadata.hex(rows(1)))));
    callsign(eventIdx) = string(metadata.callsign(rows(1)));
    startTimeUtc(eventIdx) = metadata.timeUtcK(rows(1));
    endTimeUtc(eventIdx) = metadata.timeUtcNext(rows(end));
    pairCount(eventIdx) = numel(rows);
    firstDatasetRow(eventIdx) = rows(1);
end

eventTable = table( ...
    sessionID, ...
    icao24, ...
    callsign, ...
    startTimeUtc, ...
    endTimeUtc, ...
    pairCount, ...
    firstDatasetRow, ...
    datasetRowIndices);
eventTable = sortrows( ...
    eventTable, ...
    [ ...
        "pairCount", ...
        "sessionID", ...
        "icao24", ...
        "startTimeUtc", ...
        "firstDatasetRow"], ...
    [ ...
        "descend", ...
        "ascend", ...
        "ascend", ...
        "ascend", ...
        "ascend"]);

end

function representative = localBuildRepresentative( ...
        motionClass, ...
        nativeModelID, ...
        eventTable, ...
        dataset, ...
        split, ...
        models, ...
        miniBatchSize)
%LOCALBUILDREPRESENTATIVE Build five one-step trajectory sequences.

selectedEvent = eventTable(1, :);
selectedRows = selectedEvent.datasetRowIndices{1};
previousState = double(dataset.previousState(selectedRows, :));
constvelPrediction = double( ...
    dataset.baselineConstVelMetrics.predictedState(selectedRows, :));
featureData = helperBuildStage4CFeatures( ...
    previousState, ...
    dataset.previousCovarianceDiag(selectedRows, :), ...
    dataset.dtSeconds(selectedRows), ...
    constvelPrediction);
neuralPredictions = cell(3, 1);

for modelIdx = 1:numel(models)
    neuralPredictions{modelIdx} = localPredictState( ...
        models(modelIdx), ...
        featureData.features, ...
        previousState, ...
        miniBatchSize);
end

nativePrediction = localBuildNativePrediction( ...
    nativeModelID, ...
    selectedRows, ...
    dataset, ...
    split);
timeUtc = [ ...
    dataset.metadata.timeUtcK(selectedRows(1)); ...
    dataset.metadata.timeUtcNext(selectedRows)];
timeSeconds = seconds(timeUtc - timeUtc(1));
truthState = [ ...
    previousState(1, :); ...
    double(dataset.nextState(selectedRows, :))];
nativeState = [previousState(1, :); nativePrediction];
legacyState = [previousState(1, :); neuralPredictions{1}];
scratchState = [previousState(1, :); neuralPredictions{2}];
warmState = [previousState(1, :); neuralPredictions{3}];
receiverOriginLLA = dataset.metadata.receiverOriginLLA(selectedRows(1), :);

truthLLA = localStateToLLA(truthState, receiverOriginLLA);
nativeLLA = localStateToLLA(nativeState, receiverOriginLLA);
legacyLLA = localStateToLLA(legacyState, receiverOriginLLA);
scratchLLA = localStateToLLA(scratchState, receiverOriginLLA);
warmLLA = localStateToLLA(warmState, receiverOriginLLA);

trajectory = struct();
trajectory.truth = geoTrajectory( ...
    truthLLA, timeSeconds, ReferenceFrame="ENU");
trajectory.native = geoTrajectory( ...
    nativeLLA, timeSeconds, ReferenceFrame="ENU");
trajectory.legacy = geoTrajectory( ...
    legacyLLA, timeSeconds, ReferenceFrame="ENU");
trajectory.scratch = geoTrajectory( ...
    scratchLLA, timeSeconds, ReferenceFrame="ENU");
trajectory.warm = geoTrajectory( ...
    warmLLA, timeSeconds, ReferenceFrame="ENU");

timeSpanUTC = localTimeSpan( ...
    selectedEvent.startTimeUtc, ...
    selectedEvent.endTimeUtc);
label = sprintf( ...
    "Representative trajectory—1 of %d eligible trajectories | session %s | ICAO %s | %s | %d pairs", ...
    height(eventTable), ...
    selectedEvent.sessionID, ...
    selectedEvent.icao24, ...
    timeSpanUTC, ...
    selectedEvent.pairCount);
summaryTable = table( ...
    motionClass, ...
    nativeModelID, ...
    1, ...
    height(eventTable), ...
    selectedEvent.sessionID, ...
    selectedEvent.icao24, ...
    selectedEvent.callsign, ...
    selectedEvent.startTimeUtc, ...
    selectedEvent.endTimeUtc, ...
    selectedEvent.pairCount, ...
    string(label), ...
    'VariableNames', [ ...
        "motionClass", ...
        "nativeModelID", ...
        "selectedTrajectory", ...
        "eligibleTrajectoryCount", ...
        "sessionID", ...
        "icao24", ...
        "callsign", ...
        "startTimeUtc", ...
        "endTimeUtc", ...
        "pairCount", ...
        "representativeLabel"]);
legendTable = localBuildLegendTable( ...
    motionClass, ...
    nativeModelID, ...
    string(label), ...
    selectedEvent, ...
    timeSpanUTC);

representative = struct();
representative.motionClass = motionClass;
representative.nativeModelID = nativeModelID;
representative.selectedTrajectory = 1;
representative.eligibleTrajectoryCount = height(eventTable);
representative.sessionID = selectedEvent.sessionID;
representative.icao24 = selectedEvent.icao24;
representative.callsign = selectedEvent.callsign;
representative.startTimeUtc = selectedEvent.startTimeUtc;
representative.endTimeUtc = selectedEvent.endTimeUtc;
representative.pairCount = selectedEvent.pairCount;
representative.label = string(label);
representative.summaryTable = summaryTable;
representative.legendTable = legendTable;
representative.eventTable = eventTable;
representative.datasetRowIndices = selectedRows;
representative.receiverOriginLLA = receiverOriginLLA;
representative.timeUtc = timeUtc;
representative.timeSeconds = timeSeconds;
representative.truthState = truthState;
representative.nativeState = nativeState;
representative.legacyState = legacyState;
representative.scratchState = scratchState;
representative.warmState = warmState;
representative.truthLLA = truthLLA;
representative.nativeLLA = nativeLLA;
representative.legacyLLA = legacyLLA;
representative.scratchLLA = scratchLLA;
representative.warmLLA = warmLLA;
representative.trajectories = trajectory;

end

function predictedState = localPredictState( ...
        model, physicalFeatures, previousState, miniBatchSize)
%LOCALPREDICTSTATE Run one frozen mean-MLP in physical units.

normalizedFeatures = ...
    (double(physicalFeatures) - ...
    model.featureNormalization.featureMean) ./ ...
    model.featureNormalization.featureStd;
predictedDeltaNormalized = minibatchpredict( ...
    model.net, ...
    single(normalizedFeatures), ...
    MiniBatchSize=min(miniBatchSize, size(normalizedFeatures, 1)));
predictedDeltaNormalized = gather(extractdata( ...
    predictedDeltaNormalized));

if size(predictedDeltaNormalized, 1) ~= size(normalizedFeatures, 1) && ...
        size(predictedDeltaNormalized, 2) == size(normalizedFeatures, 1)
    predictedDeltaNormalized = predictedDeltaNormalized.';
end

if ~isequal( ...
        size(predictedDeltaNormalized), ...
        [size(normalizedFeatures, 1), 6])
    error( ...
        "StageReview:Stage4CPredictionShapeMismatch", ...
        "Frozen model %s must return an N-by-6 prediction.", ...
        model.modelID);
end

predictedDelta = double(predictedDeltaNormalized) .* ...
    model.targetNormalization.targetStd + ...
    model.targetNormalization.targetMean;
predictedState = double(previousState) + predictedDelta;

if any(~isfinite(predictedState), "all")
    error( ...
        "StageReview:NonfiniteStage4CPrediction", ...
        "Frozen model %s produced a nonfinite prediction.", ...
        model.modelID);
end

end

function predictedState = localBuildNativePrediction( ...
        nativeModelID, selectedRows, dataset, split)
%LOCALBUILDNATIVEPREDICTION Reuse the Stage 4C causal native policy.

if nativeModelID == "constvel"
    predictedState = double( ...
        dataset.baselineConstVelMetrics.predictedState(selectedRows, :));
    return;
end

sessionID = string(dataset.metadata.sessionID(selectedRows(1)));
icao24 = lower(strtrim(string(dataset.metadata.hex(selectedRows(1)))));
trackRows = find( ...
    string(dataset.metadata.sessionID) == sessionID & ...
    lower(strtrim(string(dataset.metadata.hex))) == icao24);
trackMetadata = dataset.metadata( ...
    trackRows, ...
    ["sessionID", "hex", "timeUtcK", "timeUtcNext"]);
baseline = helperBuildStage4CNativeManeuverBaselines( ...
    dataset.previousState(trackRows, :), ...
    dataset.dtSeconds(trackRows), ...
    trackMetadata, ...
    split(trackRows));
[found, selectedTrackRows] = ismember(selectedRows, trackRows);

if ~all(found) || ~all(baseline.eligibleMask(selectedTrackRows))
    error( ...
        "StageReview:Stage4CRepresentativeEligibilityMismatch", ...
        "The selected %s event is not eligible under the frozen policy.", ...
        nativeModelID);
end

if nativeModelID == "constacc"
    predictedState = baseline.constaccPredictedState( ...
        selectedTrackRows, :);
elseif nativeModelID == "constturn"
    predictedState = baseline.constturnPredictedState( ...
        selectedTrackRows, :);
else
    error( ...
        "StageReview:UnknownStage4CNativeModel", ...
        "Unexpected native model identity: %s", ...
        nativeModelID);
end

end

function lla = localStateToLLA(state, receiverOriginLLA)
%LOCALSTATETOLLA Convert local ENU positions to geodetic coordinates.

spheroid = wgs84Ellipsoid("meter");
[latitudeDegrees, longitudeDegrees, altitudeMeters] = enu2geodetic( ...
    state(:, 1), ...
    state(:, 3), ...
    state(:, 5), ...
    receiverOriginLLA(1), ...
    receiverOriginLLA(2), ...
    receiverOriginLLA(3), ...
    spheroid);
lla = [latitudeDegrees, longitudeDegrees, altitudeMeters];

end

function timeSpan = localTimeSpan(startTimeUtc, endTimeUtc)
%LOCALTIMESPAN Format one UTC interval for dashboard labels.

startText = string(startTimeUtc, "yyyy-MM-dd HH:mm:ss.SSS 'UTC'");
endText = string(endTimeUtc, "yyyy-MM-dd HH:mm:ss.SSS 'UTC'");
timeSpan = startText + " to " + endText;

end

function legendTable = localBuildLegendTable( ...
        motionClass, nativeModelID, label, selectedEvent, timeSpanUTC)
%LOCALBUILDLEGENDTABLE Describe every trajectory sent to one viewer.

modelID = [ ...
    "truth"; ...
    nativeModelID; ...
    "legacy_stage3a_v1"; ...
    "expanded_scratch_mean_v1"; ...
    "expanded_warm_mean_v1"];
displayName = [ ...
    "ADS-B truth"; ...
    "Native " + nativeModelID; ...
    "Stage 3A legacy"; ...
    "Expanded scratch"; ...
    "Expanded warm"];
color = [ ...
    "green"; ...
    "blue"; ...
    "red"; ...
    "orange"; ...
    "purple"];
representativeLabel = repmat(label, 5, 1);
motionClassColumn = repmat(motionClass, 5, 1);
sessionID = repmat(selectedEvent.sessionID, 5, 1);
icao24 = repmat(selectedEvent.icao24, 5, 1);
timeSpan = repmat(timeSpanUTC, 5, 1);
pairCount = repmat(selectedEvent.pairCount, 5, 1);
legendTable = table( ...
    representativeLabel, ...
    motionClassColumn, ...
    modelID, ...
    displayName, ...
    color, ...
    sessionID, ...
    icao24, ...
    timeSpan, ...
    pairCount, ...
    'VariableNames', [ ...
        "representativeLabel", ...
        "motionClass", ...
        "modelID", ...
        "displayName", ...
        "color", ...
        "sessionID", ...
        "icao24", ...
        "timeSpanUTC", ...
        "pairCount"]);

end

function identityTable = localBuildModelIdentityTable(config, stage4CSummary)
%LOCALBUILDMODELIDENTITYTABLE Record every frozen neural artifact.

modelID = [ ...
    "legacy_stage3a_v1"; ...
    "expanded_scratch_mean_v1"; ...
    "expanded_warm_mean_v1"];
artifactPath = [ ...
    config.Stage3AArtifactPath; ...
    config.ScratchArtifactPath; ...
    config.WarmArtifactPath];
trainingRole = [ ...
    "Stage 3A legacy"; ...
    "Expanded-3Day scratch"; ...
    "Expanded-3Day normalization-rebased warm start"];
frozen = true(3, 1);
sha256 = strings(3, 1);
integrity = ...
    stage4CSummary.nativeManeuverBaseline.frozenArtifactIntegrity;

for modelIdx = 1:numel(modelID)
    expectedRow = integrity.artifactID == modelID(modelIdx);

    if sum(expectedRow) ~= 1
        error( ...
            "StageReview:MissingStage4CModelIntegrity", ...
            "No unique frozen hash is recorded for %s.", ...
            modelID(modelIdx));
    end

    sha256(modelIdx) = helperComputeFileSHA256(artifactPath(modelIdx));

    if ~strcmpi(sha256(modelIdx), integrity.beforeSHA256(expectedRow))
        error( ...
            "StageReview:Stage4CFrozenModelHashMismatch", ...
            "Frozen model %s differs from the evaluated artifact.", ...
            modelID(modelIdx));
    end
end

identityTable = table( ...
    modelID, ...
    artifactPath, ...
    trainingRole, ...
    frozen, ...
    sha256);

end

function representative = localEmptyRepresentative()
%LOCALEMPTYREPRESENTATIVE Preallocate the representative structure.

representative = struct( ...
    "motionClass", "", ...
    "nativeModelID", "", ...
    "selectedTrajectory", 0, ...
    "eligibleTrajectoryCount", 0, ...
    "sessionID", "", ...
    "icao24", "", ...
    "callsign", "", ...
    "startTimeUtc", NaT(1, 1, "TimeZone", "UTC"), ...
    "endTimeUtc", NaT(1, 1, "TimeZone", "UTC"), ...
    "pairCount", 0, ...
    "label", "", ...
    "summaryTable", table(), ...
    "legendTable", table(), ...
    "eventTable", table(), ...
    "datasetRowIndices", zeros(0, 1), ...
    "receiverOriginLLA", NaN(1, 3), ...
    "timeUtc", NaT(0, 1, "TimeZone", "UTC"), ...
    "timeSeconds", zeros(0, 1), ...
    "truthState", zeros(0, 6), ...
    "nativeState", zeros(0, 6), ...
    "legacyState", zeros(0, 6), ...
    "scratchState", zeros(0, 6), ...
    "warmState", zeros(0, 6), ...
    "truthLLA", zeros(0, 3), ...
    "nativeLLA", zeros(0, 3), ...
    "legacyLLA", zeros(0, 3), ...
    "scratchLLA", zeros(0, 3), ...
    "warmLLA", zeros(0, 3), ...
    "trajectories", struct());

end

function localValidateDashboard( ...
        dataset, ...
        splitSummaryTable, ...
        motionClassSplitTable, ...
        rmseTable, ...
        representatives)
%LOCALVALIDATEDASHBOARD Enforce the supplied Stage 4C review contract.

pairCount = size(dataset.previousState, 1);

if sum(splitSummaryTable.pairCount) ~= pairCount || ...
        motionClassSplitTable.total(end) ~= pairCount
    error( ...
        "StageReview:Stage4CCountCoverageMismatch", ...
        "Split and motion-class counts must cover all Expanded-3Day rows.");
end

sectionCounts = groupsummary( ...
    rmseTable, ...
    ["motionClass", "split"], ...
    ["min", "max"], ...
    "sampleCount");

if height(rmseTable) ~= 24 || ...
        any(sectionCounts.min_sampleCount ~= sectionCounts.max_sampleCount)
    error( ...
        "StageReview:Stage4CRMSEMatchingFailed", ...
        "Every RMSE section must compare four models on matched rows.");
end

expectedClasses = [ ...
    "constvel_like"; ...
    "constacc_like"; ...
    "constturn_like"];

if any(string({representatives.motionClass}).' ~= expectedClasses)
    error( ...
        "StageReview:Stage4CRepresentativeOrderMismatch", ...
        "Representative trajectories must follow the three dashboard rows.");
end

for representativeIdx = 1:numel(representatives)
    representative = representatives(representativeIdx);
    llaValues = [ ...
        representative.truthLLA; ...
        representative.nativeLLA; ...
        representative.legacyLLA; ...
        representative.scratchLLA; ...
        representative.warmLLA];

    if representative.selectedTrajectory ~= 1 || ...
            representative.pairCount ~= ...
            max(representative.eventTable.pairCount) || ...
            any(diff(representative.timeSeconds) <= 0) || ...
            any(~isfinite(llaValues), "all") || ...
            height(representative.legendTable) ~= 5
        error( ...
            "StageReview:InvalidStage4CRepresentative", ...
            "A representative trajectory failed continuity or finiteness checks.");
    end
end

end
