function diagnostics = helperBuildStageReviewMLPDiagnostics(review, varargin)
%HELPERBUILDSTAGEREVIEWMLPDIAGNOSTICS Explain the smoke MLP failure mode.

parser = inputParser;
parser.FunctionName = mfilename;
addParameter(parser, "TrackHex", review.defaultTrackHex);
addParameter(parser, "MaxRows", 6);
parse(parser, varargin{:});
opts = parser.Results;

trackHex = string(opts.TrackHex);
maxRows = double(opts.MaxRows);

trackRows = find(string(review.pairReviewTable.hex) == trackHex);

if isempty(trackRows)
    error("StageReview:TrackNotFound", ...
        "Track hex %s was not found in the review artifact.", trackHex);
end

[~, sortIdx] = sort(review.pairReviewTable.timeUtcNext(trackRows));
trackRows = trackRows(sortIdx);
exampleRows = trackRows(1:min(maxRows, numel(trackRows)));

examplePredictionTable = table( ...
    review.pairReviewTable.pairIndex(exampleRows), ...
    review.pairReviewTable.timeUtcNext(exampleRows), ...
    review.dataset.metadata.split(exampleRows), ...
    review.dataset.nextState(exampleRows, 1), ...
    review.dataset.nextState(exampleRows, 3), ...
    review.constvelPredictedState(exampleRows, 1), ...
    review.constvelPredictedState(exampleRows, 3), ...
    review.nnPredictedNextState(exampleRows, 1), ...
    review.nnPredictedNextState(exampleRows, 3), ...
    review.pairReviewTable.constvelPositionErrorMeters(exampleRows), ...
    review.pairReviewTable.nnSmokePositionErrorMeters(exampleRows), ...
    'VariableNames', [ ...
        "pairIndex", ...
        "timeUtcNext", ...
        "split", ...
        "truthEastMeters", ...
        "truthNorthMeters", ...
        "constvelEastMeters", ...
        "constvelNorthMeters", ...
        "nnEastMeters", ...
        "nnNorthMeters", ...
        "constvelPositionErrorMeters", ...
        "nnPositionErrorMeters"]);

splitSummary = groupsummary(review.dataset.metadata(trackRows, :), "split");

componentNames = ["x"; "vx"; "y"; "vy"; "z"; "vz"];
targetsNormalized = (review.dataset.nextState - review.dataset.normalization.targetMean) ./ ...
    review.dataset.normalization.targetStd;
trainMask = review.dataset.metadata.split == "train";
targetTrainNormalizedStd = std(targetsNormalized(trainMask, :), 0, 1).';
predictedNormalizedStd = std(review.nnPredictedNextStateNormalized, 0, 1).';
predictedNormalizedMean = mean(review.nnPredictedNextStateNormalized, 1).';

normalizedSpreadTable = table( ...
    componentNames, ...
    review.dataset.normalization.targetMean(:), ...
    review.dataset.normalization.targetStd(:), ...
    targetTrainNormalizedStd, ...
    predictedNormalizedMean, ...
    predictedNormalizedStd, ...
    'VariableNames', [ ...
        "component", ...
        "targetMeanPhysicalUnits", ...
        "targetStdPhysicalUnits", ...
        "targetTrainNormalizedStd", ...
        "nnPredictedNormalizedMean", ...
        "nnPredictedNormalizedStd"]);

lossHistoryTable = table( ...
    (1:numel(review.trainingSummary.lossHistory)).', ...
    review.trainingSummary.lossHistory(:), ...
    'VariableNames', ["epoch", "trainingLoss"]);

diagnostics = struct();
diagnostics.trackHex = trackHex;
diagnostics.examplePredictionTable = examplePredictionTable;
diagnostics.splitSummary = splitSummary;
diagnostics.normalizedSpreadTable = normalizedSpreadTable;
diagnostics.lossHistoryTable = lossHistoryTable;
diagnostics.diagnosisText = sprintf( ...
    "The Stage 2B smoke MLP path is actual saved model output, not a plotting bug. For track %s, the native constvel prediction stays within meters, but the smoke MLP predicts tens of kilometers away. The MLP only ran %d epochs and its normalized output spread is much smaller than the normalized target spread, which indicates an undertrained model collapsed toward a dataset-level prior instead of learning the one-step aircraft motion.", ...
    trackHex, ...
    review.trainingSummary.numEpochs);

end
