function comparison = runStage4BPostCampaignMotionDiversityGate(varargin)
%RUNSTAGE4BPOSTCAMPAIGNMOTIONDIVERSITYGATE Compare versioned ADS-B datasets.
% The frozen Stage 3A model and native constvel baseline are evaluated on
% Legacy-16, the 3-Day Campaign Increment, and their Expanded-3Day union.
% This gate measures independent motion diversity and never trains a model.

projectRoot = string(fileparts(mfilename("fullpath")));
parser = inputParser;
parser.FunctionName = mfilename;
addParameter(parser, "ProjectRoot", projectRoot);
addParameter(parser, "OutputFolder", "");
addParameter(parser, "RebuildVariantEvaluations", true);
addParameter(parser, "CreateVariantPlots", true);
addParameter(parser, "CreateComparisonPlots", true);
addParameter(parser, "RefreshStage4A", true);
addParameter(parser, "Verbose", true);
parse(parser, varargin{:});

config = localBuildConfig(parser.Results);
localValidateConfig(config);

variantIDs = [ ...
    "legacy_pre3day_v1"; ...
    "campaign_3day_increment_v1"; ...
    "expanded_post3day_v2"];
displayNames = ["Legacy-16"; "3-Day Campaign Increment"; "Expanded-3Day"];
variantSummaries = struct();
analyses = struct();

for variantIdx = 1:numel(variantIDs)
    variantID = variantIDs(variantIdx);
    fullVariantSummary = localResolveVariantSummary(config, variantID);
    analyses.(variantID) = helperAnalyzeADSBDatasetMotionDiversity( ...
        fullVariantSummary, ...
        variantID);
    analyses.(variantID) = localCompactAnalysis(analyses.(variantID));
    variantSummaries.(variantID) = localCompactVariantSummary(fullVariantSummary);
    clear fullVariantSummary
end

localValidateVariantContracts(variantSummaries, analyses);

variantSummaryTable = localBuildVariantSummaryTable( ...
    variantIDs, ...
    displayNames, ...
    variantSummaries, ...
    analyses);
pairRegimeComparison = localCombineAnalysisTables( ...
    variantIDs, ...
    displayNames, ...
    analyses, ...
    "pairRegimeSummary");
eventComparison = localCombineAnalysisTables( ...
    variantIDs, ...
    displayNames, ...
    analyses, ...
    "eventSummary");
continuousComparison = localCombineAnalysisTables( ...
    variantIDs, ...
    displayNames, ...
    analyses, ...
    "continuousSummary");
continuousHistogramComparison = localCombineAnalysisTables( ...
    variantIDs, ...
    displayNames, ...
    analyses, ...
    "continuousHistogram");
jointRegimeComparison = localCombineAnalysisTables( ...
    variantIDs, ...
    displayNames, ...
    analyses, ...
    "jointRegimeOccupancy");
splitCoverageComparison = localCombineSplitCoverage( ...
    variantIDs, ...
    displayNames, ...
    analyses);
modelComparison = localBuildModelComparison( ...
    variantIDs, ...
    displayNames, ...
    variantSummaries);
differenceSummary = localBuildDifferenceSummary( ...
    analyses.legacy_pre3day_v1, ...
    analyses.expanded_post3day_v2);
variantSummaryTable = localAppendVariantDifference( ...
    variantSummaryTable, ...
    differenceSummary);
pairRegimeComparison = localAppendTableDifference( ...
    pairRegimeComparison, ...
    "dimension", ...
    "regime");
eventDifferenceTable = localBuildEventDifferenceTable( ...
    analyses.legacy_pre3day_v1.eventSummary, ...
    analyses.expanded_post3day_v2.eventSummary);
readinessGateTable = localBuildReadinessGateTable( ...
    analyses.campaign_3day_increment_v1, ...
    analyses.expanded_post3day_v2, ...
    analyses.legacy_pre3day_v1, ...
    variantSummaries);
localRetrainingReady = all(readinessGateTable.passed);
broadGeneralizationReady = false;

comparison = struct();
comparison.generatedAt = datetime("now", "TimeZone", "UTC");
comparison.projectRoot = config.ProjectRoot;
comparison.outputFolder = config.OutputFolder;
comparison.variantOrder = variantIDs;
comparison.variantDisplayNames = displayNames;
comparison.variantSummaries = variantSummaries;
comparison.analyses = analyses;
comparison.variantSummaryTable = variantSummaryTable;
comparison.pairRegimeComparison = pairRegimeComparison;
comparison.eventComparison = eventComparison;
comparison.eventDifferenceTable = eventDifferenceTable;
comparison.continuousComparison = continuousComparison;
comparison.continuousHistogramComparison = continuousHistogramComparison;
comparison.jointRegimeComparison = jointRegimeComparison;
comparison.splitCoverageComparison = splitCoverageComparison;
comparison.modelComparison = modelComparison;
comparison.differenceSummary = differenceSummary;
comparison.readinessGateTable = readinessGateTable;
comparison.localRetrainingReady = localRetrainingReady;
comparison.broadGeneralizationReady = broadGeneralizationReady;
comparison.broadGeneralizationReason = ...
    "The evaluated data use one receiver location and one local ADS-B collection domain; three campaign days cannot establish cross-location or cross-source generalization.";
comparison.retrainingRun = false;
comparison.artifactPath = fullfile( ...
    config.OutputFolder, ...
    "stage4BPostCampaignMotionDiversity.mat");
comparison.reportPath = fullfile( ...
    config.OutputFolder, ...
    "stage4BPostCampaignMotionDiversityReport.md");
comparison.figurePaths = struct();
comparison.stage4ARefresh = struct();

localWriteComparisonTables(config.OutputFolder, comparison);

if config.CreateComparisonPlots
    comparison.figurePaths = helperWriteStage4BPostCampaignFigures( ...
        config.OutputFolder, ...
        comparison);
end

function differenceTable = localBuildEventDifferenceTable(legacy, expanded)
%LOCALBUILDEVENTDIFFERENCETABLE Report additive event gains by type.

differenceTable = table();
differenceTable.eventType = expanded.eventType;
differenceTable.eventCount = expanded.eventCount - legacy.eventCount;
differenceTable.totalDurationSeconds = ...
    expanded.totalDurationSeconds - legacy.totalDurationSeconds;
differenceTable.displayName = repmat( ...
    "Expanded-3Day minus Legacy-16", ...
    height(differenceTable), ...
    1);
differenceTable = movevars(differenceTable, "displayName", "Before", 1);

end

if config.RefreshStage4A
    comparison.stage4ARefresh = localRefreshStage4A( ...
        config, ...
        variantSummaries.expanded_post3day_v2);
end

helperWriteStage4BPostCampaignReport(comparison.reportPath, comparison);
localSaveComparison(comparison);

if config.Verbose
    localPrintSummary(comparison);
end

end

function summary = localCompactVariantSummary(fullSummary)
%LOCALCOMPACTVARIANTSUMMARY Retain only comparison and artifact references.

summary = struct();
summary.datasetVariantID = fullSummary.datasetVariantID;
summary.artifactPath = fullSummary.artifactPath;
summary.reportPath = fullSummary.reportPath;
summary.aggregateDatasetPath = fullSummary.aggregateDatasetPath;
summary.stage3AArtifactPath = fullSummary.stage3BSummary.stage3AArtifactPath;
summary.archiveSummary = fullSummary.archiveSummary;
summary.metricComparisonTable = fullSummary.metricComparisonTable;
summary.datasetVariantManifestRows = fullSummary.datasetVariantManifestRows;
summary.stage3BSummary = struct();
summary.stage3BSummary.metrics = struct();
summary.stage3BSummary.metrics.byManeuverClass = ...
    fullSummary.stage3BSummary.metrics.byManeuverClass;
summary.retrainingRun = fullSummary.retrainingRun;

end

function localValidateVariantContracts(variantSummaries, analyses)
%LOCALVALIDATEVARIANTCONTRACTS Verify union and frozen evaluation settings.

legacyFiles = string( ...
    variantSummaries.legacy_pre3day_v1.datasetVariantManifestRows.relativeSourceFile);
incrementFiles = string( ...
    variantSummaries.campaign_3day_increment_v1.datasetVariantManifestRows.relativeSourceFile);
expandedFiles = string( ...
    variantSummaries.expanded_post3day_v2.datasetVariantManifestRows.relativeSourceFile);

if ~isempty(intersect(legacyFiles, incrementFiles))
    error("Stage4BPost:VariantOverlap", ...
        "Legacy-16 and the 3-Day Campaign Increment overlap.");
end

expectedUnion = sort(unique([legacyFiles; incrementFiles]));

if ~isequal(sort(expandedFiles), expectedUnion)
    error("Stage4BPost:InvalidVariantUnion", ...
        "Expanded-3Day is not the exact union of Legacy-16 and the campaign increment.");
end

legacyThresholds = analyses.legacy_pre3day_v1.motionThresholds;
incrementThresholds = analyses.campaign_3day_increment_v1.motionThresholds;
expandedThresholds = analyses.expanded_post3day_v2.motionThresholds;

if ~isequaln(legacyThresholds, incrementThresholds) || ...
        ~isequaln(legacyThresholds, expandedThresholds)
    error("Stage4BPost:ThresholdMismatch", ...
        "All variants must use identical motion thresholds.");
end

stage3APaths = [ ...
    string(variantSummaries.legacy_pre3day_v1.stage3AArtifactPath); ...
    string(variantSummaries.campaign_3day_increment_v1.stage3AArtifactPath); ...
    string(variantSummaries.expanded_post3day_v2.stage3AArtifactPath)];

if numel(unique(stage3APaths)) ~= 1
    error("Stage4BPost:FrozenModelMismatch", ...
        "All variants must use the same frozen Stage 3A artifact.");
end

retrainingFlags = [ ...
    variantSummaries.legacy_pre3day_v1.archiveSummary.retrainingRun; ...
    variantSummaries.campaign_3day_increment_v1.archiveSummary.retrainingRun; ...
    variantSummaries.expanded_post3day_v2.archiveSummary.retrainingRun];

if any(retrainingFlags)
    error("Stage4BPost:UnexpectedRetraining", ...
        "A variant indicates that retraining occurred.");
end

end

function analysis = localCompactAnalysis(analysis)
%LOCALCOMPACTANALYSIS Drop redundant pair-sized arrays after summarization.

analysis = rmfield(analysis, "pairTable");
analysis.splitAudit = rmfield( ...
    analysis.splitAudit, ...
    [ ...
        "aircraftPairSplit", ...
        "chronologicalPairSplit", ...
        "aircraftEventSplit", ...
        "chronologicalEventSplit"]);

end

function summaryTable = localAppendVariantDifference(summaryTable, difference)
%LOCALAPPENDVARIANTDIFFERENCE Add the named expanded-minus-legacy row.

differenceRow = summaryTable(1, :);
differenceRow.variantID = "expanded_minus_legacy";
differenceRow.displayName = difference.name;
differenceRow.sourceFileCount = ...
    summaryTable.sourceFileCount(summaryTable.variantID == "expanded_post3day_v2") - ...
    summaryTable.sourceFileCount(summaryTable.variantID == "legacy_pre3day_v1");
differenceRow.usableSourceFileCount = ...
    summaryTable.usableSourceFileCount(summaryTable.variantID == "expanded_post3day_v2") - ...
    summaryTable.usableSourceFileCount(summaryTable.variantID == "legacy_pre3day_v1");
differenceRow.sessionCount = ...
    summaryTable.sessionCount(summaryTable.variantID == "expanded_post3day_v2") - ...
    summaryTable.sessionCount(summaryTable.variantID == "legacy_pre3day_v1");
differenceRow.aircraftCount = difference.aircraftCount;
differenceRow.aircraftTrackCount = difference.aircraftTrackCount;
differenceRow.pairCount = difference.pairCount;
differenceRow.eventCount = difference.eventCount;
differenceRow.occupiedJointRegimeCellCount = difference.occupiedJointRegimeCellCount;
differenceRow.constvelPositionRMSEMeters = NaN;
differenceRow.frozenMLPPositionRMSEMeters = NaN;
summaryTable = [summaryTable; differenceRow];

end

function combined = localAppendTableDifference( ...
        combined, dimensionVariable, keyVariable)
%LOCALAPPENDTABLEDIFFERENCE Add expanded-minus-legacy rows to count tables.

legacy = combined(combined.variantID == "legacy_pre3day_v1", :);
expanded = combined(combined.variantID == "expanded_post3day_v2", :);
keyVariables = string(keyVariable);

if strlength(dimensionVariable) > 0
    keyVariables = [string(dimensionVariable), keyVariables];
end

differenceRows = expanded;
differenceRows.variantID(:) = "expanded_minus_legacy";
differenceRows.displayName(:) = "Expanded-3Day minus Legacy-16";
variableNames = string(differenceRows.Properties.VariableNames);

for rowIdx = 1:height(differenceRows)
    legacyMask = true(height(legacy), 1);

    for keyIdx = 1:numel(keyVariables)
        variableName = keyVariables(keyIdx);
        legacyMask = legacyMask & ...
            string(legacy.(variableName)) == string(differenceRows.(variableName)(rowIdx));
    end

    if any(legacyMask)
        for variableIdx = 1:numel(variableNames)
            variableName = variableNames(variableIdx);

            if isnumeric(differenceRows.(variableName))
                differenceRows.(variableName)(rowIdx, :) = ...
                    differenceRows.(variableName)(rowIdx, :) - ...
                    legacy.(variableName)(legacyMask, :);
            end
        end
    end
end

combined = [combined; differenceRows];

end

function combined = localCombineSplitCoverage( ...
        variantIDs, displayNames, analyses)
%LOCALCOMBINESPLITCOVERAGE Stack prospective split evidence.

combined = table();

for variantIdx = 1:numel(variantIDs)
    variantID = variantIDs(variantIdx);
    current = analyses.(variantID).splitAudit.eventCoverage;
    current = addvars( ...
        current, ...
        repmat(variantID, height(current), 1), ...
        repmat(displayNames(variantIdx), height(current), 1), ...
        'Before', ...
        1, ...
        'NewVariableNames', ...
        ["variantID", "displayName"]);
    combined = [combined; current]; %#ok<AGROW>
end

end

function config = localBuildConfig(opts)
%LOCALBUILDCONFIG Normalize gate options.

config = struct();
config.ProjectRoot = string(opts.ProjectRoot);
config.OutputFolder = string(opts.OutputFolder);

if strlength(config.OutputFolder) == 0
    config.OutputFolder = fullfile( ...
        config.ProjectRoot, ...
        "artifacts", ...
        "stage4BPostCampaign", ...
        "comparison");
end

config.RebuildVariantEvaluations = logical(opts.RebuildVariantEvaluations);
config.CreateVariantPlots = logical(opts.CreateVariantPlots);
config.CreateComparisonPlots = logical(opts.CreateComparisonPlots);
config.RefreshStage4A = logical(opts.RefreshStage4A);
config.Verbose = logical(opts.Verbose);

end

function localValidateConfig(config)
%LOCALVALIDATECONFIG Validate the version manifest and output path.

if ~isfolder(config.ProjectRoot)
    error("Stage4BPost:MissingProjectRoot", ...
        "Project root was not found: %s", config.ProjectRoot);
end

manifestPath = fullfile( ...
    config.ProjectRoot, ...
    "adsb_archive", ...
    "datasetVersions", ...
    "adsbDatasetVariants.csv");

if exist(manifestPath, "file") ~= 2
    error("Stage4BPost:MissingVariantManifest", ...
        "Run integrateStage4BThreeDayArchive before the diversity gate.");
end

if strlength(config.OutputFolder) == 0
    error("Stage4BPost:MissingOutputFolder", ...
        "OutputFolder must be nonempty.");
end

end

function summary = localResolveVariantSummary(config, variantID)
%LOCALRESOLVEVARIANTSUMMARY Rebuild or load one versioned Stage 3C result.

outputFolder = fullfile( ...
    config.ProjectRoot, ...
    "artifacts", ...
    "stage4BPostCampaign", ...
    variantID);
artifactPath = fullfile(outputFolder, "stage3CArchiveADSBEvaluation.mat");

if config.RebuildVariantEvaluations || exist(artifactPath, "file") ~= 2
    summary = runADSBDatasetVariantEvaluation( ...
        variantID, ...
        "ProjectRoot", ...
        config.ProjectRoot, ...
        "OutputFolder", ...
        outputFolder, ...
        "CreatePlots", ...
        config.CreateVariantPlots, ...
        "Verbose", ...
        config.Verbose);
    return;
end

loaded = load(artifactPath, "stage3CSummary");

if ~isfield(loaded, "stage3CSummary") || ...
        string(loaded.stage3CSummary.datasetVariantID) ~= variantID
    error("Stage4BPost:InvalidVariantArtifact", ...
        "Saved artifact does not match variant %s: %s", ...
        variantID, ...
        artifactPath);
end

summary = loaded.stage3CSummary;

end

function summaryTable = localBuildVariantSummaryTable( ...
        variantIDs, displayNames, variantSummaries, analyses)
%LOCALBUILDVARIANTSUMMARYTABLE Put source, motion, and model counts together.

variantCount = numel(variantIDs);
sourceFileCount = zeros(variantCount, 1);
usableSourceFileCount = zeros(variantCount, 1);
sessionCount = zeros(variantCount, 1);
aircraftCount = zeros(variantCount, 1);
aircraftTrackCount = zeros(variantCount, 1);
pairCount = zeros(variantCount, 1);
eventCount = zeros(variantCount, 1);
occupiedJointRegimeCellCount = zeros(variantCount, 1);
constvelPositionRMSEMeters = NaN(variantCount, 1);
frozenMLPPositionRMSEMeters = NaN(variantCount, 1);

for variantIdx = 1:variantCount
    variantID = variantIDs(variantIdx);
    source = analyses.(variantID).sourceSummary;
    metrics = variantSummaries.(variantID).metricComparisonTable;
    sourceFileCount(variantIdx) = source.sourceFileCount;
    usableSourceFileCount(variantIdx) = source.usableSourceFileCount;
    sessionCount(variantIdx) = source.sessionCount;
    aircraftCount(variantIdx) = source.aircraftCount;
    aircraftTrackCount(variantIdx) = source.aircraftTrackCount;
    pairCount(variantIdx) = source.pairCount;
    eventCount(variantIdx) = height(analyses.(variantID).eventTable);
    occupiedJointRegimeCellCount(variantIdx) = sum( ...
        analyses.(variantID).jointRegimeOccupancy.occupied);
    constvelPositionRMSEMeters(variantIdx) = metrics.positionRMSEMeters( ...
        metrics.method == "constvel baseline");
    frozenMLPPositionRMSEMeters(variantIdx) = metrics.positionRMSEMeters( ...
        metrics.method == "Frozen Stage 3A delta MLP");
end

summaryTable = table( ...
    variantIDs, ...
    displayNames, ...
    sourceFileCount, ...
    usableSourceFileCount, ...
    sessionCount, ...
    aircraftCount, ...
    aircraftTrackCount, ...
    pairCount, ...
    eventCount, ...
    occupiedJointRegimeCellCount, ...
    constvelPositionRMSEMeters, ...
    frozenMLPPositionRMSEMeters, ...
    'VariableNames', [ ...
        "variantID", ...
        "displayName", ...
        "sourceFileCount", ...
        "usableSourceFileCount", ...
        "sessionCount", ...
        "aircraftCount", ...
        "aircraftTrackCount", ...
        "pairCount", ...
        "eventCount", ...
        "occupiedJointRegimeCellCount", ...
        "constvelPositionRMSEMeters", ...
        "frozenMLPPositionRMSEMeters"]);

end

function combined = localCombineAnalysisTables( ...
        variantIDs, displayNames, analyses, fieldName)
%LOCALCOMBINEANALYSISTABLES Stack one analysis table across variants.

combined = table();

for variantIdx = 1:numel(variantIDs)
    variantID = variantIDs(variantIdx);
    current = analyses.(variantID).(fieldName);
    current = addvars( ...
        current, ...
        repmat(variantID, height(current), 1), ...
        repmat(displayNames(variantIdx), height(current), 1), ...
        'Before', ...
        1, ...
        'NewVariableNames', ...
        ["variantID", "displayName"]);
    combined = [combined; current]; %#ok<AGROW>
end

end

function comparisonTable = localBuildModelComparison( ...
        variantIDs, displayNames, variantSummaries)
%LOCALBUILDMODELCOMPARISON Stack frozen-model metrics across variants.

comparisonTable = table();

for variantIdx = 1:numel(variantIDs)
    variantID = variantIDs(variantIdx);
    current = variantSummaries.(variantID).metricComparisonTable;
    current = addvars( ...
        current, ...
        repmat(variantID, height(current), 1), ...
        repmat(displayNames(variantIdx), height(current), 1), ...
        'Before', ...
        1, ...
        'NewVariableNames', ...
        ["variantID", "displayName"]);
    comparisonTable = [comparisonTable; current]; %#ok<AGROW>
end

end

function difference = localBuildDifferenceSummary(legacy, expanded)
%LOCALBUILDDIFFERENCESUMMARY Name the incremental evidence explicitly.

legacyEvents = sum(legacy.eventSummary.eventCount);
expandedEvents = sum(expanded.eventSummary.eventCount);
difference = struct();
difference.name = "Expanded-3Day minus Legacy-16";
difference.pairCount = expanded.sourceSummary.pairCount - ...
    legacy.sourceSummary.pairCount;
difference.aircraftCount = expanded.sourceSummary.aircraftCount - ...
    legacy.sourceSummary.aircraftCount;
difference.aircraftTrackCount = expanded.sourceSummary.aircraftTrackCount - ...
    legacy.sourceSummary.aircraftTrackCount;
difference.eventCount = expandedEvents - legacyEvents;
difference.occupiedJointRegimeCellCount = ...
    sum(expanded.jointRegimeOccupancy.occupied) - ...
    sum(legacy.jointRegimeOccupancy.occupied);

end

function gateTable = localBuildReadinessGateTable( ...
        increment, expanded, legacy, variantSummaries)
%LOCALBUILDREADINESSGATETABLE Apply the approved local retraining gate.

gate = [ ...
    "all source files classified"; ...
    "campaign files with usable pairs"; ...
    "sustained turn diversity"; ...
    "sustained acceleration diversity"; ...
    "sustained climb diversity"; ...
    "sustained descent diversity"; ...
    "sparse-update diversity"; ...
    "contributor concentration"; ...
    "aircraft-disjoint split support"; ...
    "chronological split support"; ...
    "expanded independent coverage"; ...
    "no neural retraining"];
observed = strings(numel(gate), 1);
required = strings(numel(gate), 1);
passed = false(numel(gate), 1);

source = increment.sourceSummary;
passed(1) = source.classifiedSourceFileCount == source.sourceFileCount && ...
    source.parseFailureCount == 0 && ...
    source.unselectedSourceFileCount == 0;
observed(1) = sprintf( ...
    "%d/%d classified; %d parse failures", ...
    source.classifiedSourceFileCount, ...
    source.sourceFileCount, ...
    source.parseFailureCount);
required(1) = "all classified; zero failures";

usablePercent = 100 * source.usableSourceFileCount / max(source.sourceFileCount, 1);
passed(2) = usablePercent >= 95;
observed(2) = sprintf( ...
    "%d/%d (%.1f%%)", ...
    source.usableSourceFileCount, ...
    source.sourceFileCount, ...
    usablePercent);
required(2) = ">=95%";

[passed(3), observed(3)] = localEventDiversityGate( ...
    expanded.eventSummary, "sustained_turn", 30, 10, 3);
required(3) = ">=30 events, >=10 ICAO, 3 campaign days";
[passed(4), observed(4)] = localEventDiversityGate( ...
    expanded.eventSummary, "sustained_acceleration", 30, 10, 3);
required(4) = ">=30 events, >=10 ICAO, 3 campaign days";
[passed(5), observed(5)] = localEventDiversityGate( ...
    expanded.eventSummary, "sustained_climb", 50, 15, 3);
required(5) = ">=50 events, >=15 ICAO, 3 campaign days";
[passed(6), observed(6)] = localEventDiversityGate( ...
    expanded.eventSummary, "sustained_descent", 50, 15, 3);
required(6) = ">=50 events, >=15 ICAO, 3 campaign days";
[passed(7), observed(7)] = localSparseDiversityGate(expanded.eventSummary);
required(7) = ">=100 events, >=20 tracks, 3 campaign days";

[passed(8), observed(8)] = localConcentrationGate(expanded.eventSummary);
required(8) = "each critical regime: ICAO <=20%, campaign day <=60%";

eventCoverage = expanded.splitAudit.eventCoverage;
passed(9) = localSplitStrategyPass(eventCoverage, "aircraft_disjoint");
observed(9) = localSplitObservation(eventCoverage, "aircraft_disjoint");
required(9) = "all regimes in train; >=5 each in validation/test";
passed(10) = localSplitStrategyPass(eventCoverage, "chronological_blocked");
observed(10) = localSplitObservation(eventCoverage, "chronological_blocked");
required(10) = "all regimes in train; >=5 each in validation/test";

addedEvents = sum(expanded.eventSummary.eventCount) - ...
    sum(legacy.eventSummary.eventCount);
addedCells = sum(expanded.jointRegimeOccupancy.occupied) - ...
    sum(legacy.jointRegimeOccupancy.occupied);
passed(11) = addedEvents > 0 && addedCells > 0;
observed(11) = sprintf("+%d events; %+d occupied cells", addedEvents, addedCells);
required(11) = "positive events and occupied cells";

retrainingFlags = [ ...
    variantSummaries.legacy_pre3day_v1.retrainingRun; ...
    variantSummaries.campaign_3day_increment_v1.retrainingRun; ...
    variantSummaries.expanded_post3day_v2.retrainingRun];
passed(12) = ~any(retrainingFlags);
observed(12) = sprintf("%d retraining run(s)", sum(retrainingFlags));
required(12) = "0";

gateTable = table(gate, observed, required, passed);

end

function [passed, observation] = localEventDiversityGate( ...
        eventSummary, eventType, minimumEvents, minimumAircraft, minimumBlocks)
%LOCALEVENTDIVERSITYGATE Evaluate one sustained-event threshold.

row = eventSummary(eventSummary.eventType == eventType, :);
passed = row.eventCount >= minimumEvents && ...
    row.aircraftCount >= minimumAircraft && ...
    row.campaignBlockCount >= minimumBlocks;
observation = sprintf( ...
    "%d events, %d ICAO, %d campaign days", ...
    row.eventCount, ...
    row.aircraftCount, ...
    row.campaignBlockCount);

end

function [passed, observation] = localSparseDiversityGate(eventSummary)
%LOCALSPARSEDIVERSITYGATE Evaluate independent sparse-gap support.

row = eventSummary(eventSummary.eventType == "sparse_gap", :);
passed = row.eventCount >= 100 && ...
    row.trackCount >= 20 && ...
    row.campaignBlockCount >= 3;
observation = sprintf( ...
    "%d events, %d tracks, %d campaign days", ...
    row.eventCount, ...
    row.trackCount, ...
    row.campaignBlockCount);

end

function [passed, observation] = localConcentrationGate(eventSummary)
%LOCALCONCENTRATIONGATE Reject dominance by one aircraft or campaign day.

criticalRows = ismember(eventSummary.eventType, [ ...
    "sustained_turn", ...
    "sustained_acceleration", ...
    "sustained_climb", ...
    "sustained_descent", ...
    "sparse_gap"]);
critical = eventSummary(criticalRows, :);
passed = all(critical.largestAircraftSharePercent <= 20) && ...
    all(critical.largestCampaignBlockSharePercent <= 60);
observation = sprintf( ...
    "max ICAO %.1f%%; max campaign day %.1f%%", ...
    max(critical.largestAircraftSharePercent, [], "omitnan"), ...
    max(critical.largestCampaignBlockSharePercent, [], "omitnan"));

end

function passed = localSplitStrategyPass(eventCoverage, strategy)
%LOCALSPLITSTRATEGYPASS Apply train/validation/test event-count minima.

rows = eventCoverage(eventCoverage.splitStrategy == strategy, :);
trainRows = rows.split == "train";
holdoutRows = rows.split == "validation" | rows.split == "test";
passed = all(rows.eventCount(trainRows) >= 1) && ...
    all(rows.eventCount(holdoutRows) >= 5);

end

function observation = localSplitObservation(eventCoverage, strategy)
%LOCALSPLITOBSERVATION Report the weakest train and holdout cells.

rows = eventCoverage(eventCoverage.splitStrategy == strategy, :);
trainMinimum = min(rows.eventCount(rows.split == "train"));
validationMinimum = min(rows.eventCount(rows.split == "validation"));
testMinimum = min(rows.eventCount(rows.split == "test"));
observation = sprintf( ...
    "minimum train/validation/test = %d/%d/%d events", ...
    trainMinimum, ...
    validationMinimum, ...
    testMinimum);

end

function localWriteComparisonTables(outputFolder, comparison)
%LOCALWRITECOMPARISONTABLES Write compact CSV evidence.

if ~isfolder(outputFolder)
    mkdir(outputFolder);
end

writetable( ...
    comparison.variantSummaryTable, ...
    fullfile(outputFolder, "variantSummary.csv"));
writetable( ...
    comparison.pairRegimeComparison, ...
    fullfile(outputFolder, "pairRegimeComparison.csv"));
writetable( ...
    comparison.eventComparison, ...
    fullfile(outputFolder, "eventComparison.csv"));
writetable( ...
    comparison.eventDifferenceTable, ...
    fullfile(outputFolder, "eventDifference.csv"));
writetable( ...
    comparison.continuousComparison, ...
    fullfile(outputFolder, "continuousMotionSummary.csv"));
writetable( ...
    comparison.continuousHistogramComparison, ...
    fullfile(outputFolder, "continuousMotionHistogram.csv"));
writetable( ...
    comparison.jointRegimeComparison, ...
    fullfile(outputFolder, "jointRegimeOccupancy.csv"));
writetable( ...
    comparison.splitCoverageComparison, ...
    fullfile(outputFolder, "prospectiveSplitEventCoverage.csv"));
writetable( ...
    comparison.modelComparison, ...
    fullfile(outputFolder, "modelComparison.csv"));
writetable( ...
    comparison.readinessGateTable, ...
    fullfile(outputFolder, "localRetrainingReadinessGates.csv"));

end

function stage4ARefresh = localRefreshStage4A(config, expandedSummary)
%LOCALREFRESHSTAGE4A Rebuild Stage 4A from the explicit expanded artifact.

stage4AOutputFolder = fullfile( ...
    config.ProjectRoot, ...
    "artifacts", ...
    "stage4BPostCampaign", ...
    "expanded_post3day_v2", ...
    "stage4A");
capturePlan = helperBuildStage4ADSBTruthCapturePlan( ...
    "ProjectRoot", ...
    config.ProjectRoot, ...
    "Stage3CArtifactPath", ...
    expandedSummary.artifactPath);
plotNames = [ ...
    "readinessGates", ...
    "motionCoverage", ...
    "modelDataProblem", ...
    "splitCoverage", ...
    "captureCampaign"];
figurePaths = struct();

for plotIdx = 1:numel(plotNames)
    plotName = plotNames(plotIdx);
    plotOutput = helperPlotStage4ADSBTruthCapturePlan( ...
        capturePlan, ...
        "PlotName", ...
        plotName, ...
        "OutputFolder", ...
        stage4AOutputFolder, ...
        "Visible", ...
        "off", ...
        "SaveFigures", ...
        true, ...
        "CloseFigures", ...
        true);
    figurePaths.(plotName) = plotOutput.figurePaths.(plotName);
end

artifactPath = fullfile(stage4AOutputFolder, "stage4AExpandedCapturePlan.mat");

if ~isfolder(stage4AOutputFolder)
    mkdir(stage4AOutputFolder);
end

capturePlan = rmfield(capturePlan, ["stage3BSummary", "stage3CSummary"]);
save(artifactPath, "capturePlan", "-v7.3");
stage4ARefresh = struct();
stage4ARefresh.outputFolder = stage4AOutputFolder;
stage4ARefresh.artifactPath = artifactPath;
stage4ARefresh.figurePaths = figurePaths;
stage4ARefresh.sourceStage3CArtifactPath = expandedSummary.artifactPath;

end

function localSaveComparison(comparison)
%LOCALSAVECOMPARISON Save the complete reproducible gate result.

if ~isfolder(comparison.outputFolder)
    mkdir(comparison.outputFolder);
end

save(comparison.artifactPath, "comparison", "-v7.3");

end

function localPrintSummary(comparison)
%LOCALPRINTSUMMARY Print the two required readiness verdicts.

fprintf("Stage 4B-Post motion-diversity gate complete\n");
fprintf("Local gated retraining ready:\t%d\n", comparison.localRetrainingReady);
fprintf("Broad generalization ready:\t%d\n", comparison.broadGeneralizationReady);
fprintf("Report written:\t%s\n", comparison.reportPath);
fprintf("Artifact written:\t%s\n", comparison.artifactPath);

end
