function summary = runStage4CNativeManeuverBaselineEvaluation(varargin)
%RUNSTAGE4CNATIVEMANEUVERBASELINEEVALUATION Extend Stage 4C evaluation.
% This function does not train or modify a network. It builds causal raw
% finite-difference initialization values, propagates native constacc and
% constturn states, and compares them with the four frozen Stage 4C models
% on matched untouched validation/test maneuver slices.

projectRoot = string(fileparts(mfilename("fullpath")));
parser = inputParser;
parser.FunctionName = mfilename;
addParameter(parser, "ProjectRoot", projectRoot);
addParameter(parser, "DatasetPath", "");
addParameter(parser, "SplitManifestPath", "");
addParameter(parser, "Stage3AArtifactPath", "");
addParameter(parser, "ScratchArtifactPath", "");
addParameter(parser, "WarmArtifactPath", "");
addParameter(parser, "ComparisonArtifactPath", "");
addParameter(parser, "MetricTablePath", "");
addParameter(parser, "ReportPath", "");
addParameter(parser, "FigurePath", "");
addParameter(parser, "PredictionMiniBatchSize", 8192);
addParameter(parser, "CreatePlots", true);
addParameter(parser, "Verbose", true);
parse(parser, varargin{:});

config = localBuildConfig(parser.Results);
localValidateConfig(config);

if config.Verbose
    fprintf("Stage 4C native maneuver-baseline evaluation\n");
    fprintf("Policy:\traw_causal_finite_difference_v1\n");
    fprintf("Dataset:\t%s\n", config.DatasetPath);
end

frozenIntegrity = localHashFrozenArtifacts(config, "before");
dataset = localLoadDataset(config.DatasetPath);
split = localLoadSplit(dataset.metadata, config.SplitManifestPath);
stage4CSummary = localLoadComparisonSummary(config.ComparisonArtifactPath);
localAuditFrozenInputs(dataset, split, stage4CSummary, config);

% Keep only grouping and timing metadata after loading. The source-file
% string column is large and is not needed for causal predecessor matching.
metadata = dataset.metadata(:, ...
    ["sessionID", "hex", "timeUtcK", "timeUtcNext"]);
nativeBaseline = helperBuildStage4CNativeManeuverBaselines( ...
    dataset.previousState, ...
    dataset.dtSeconds, ...
    metadata, ...
    split);

% Maneuver labels are truth-derived retrospective slices. They are created
% only after native predictions exist and are never passed into the causal
% initialization helper.
maneuverPairTable = helperAssignADSBManeuverLabels( ...
    dataset.previousState, ...
    dataset.nextState, ...
    dataset.dtSeconds);
holdoutMask = (split == "validation") | (split == "test");
holdoutDatasetRows = find(holdoutMask);
holdoutMetadata = metadata(holdoutMask, :);
holdoutSplit = split(holdoutMask);
holdoutLabels = maneuverPairTable(holdoutMask, :);
holdoutNativeBaseline = localSubsetNativeBaseline( ...
    nativeBaseline, ...
    holdoutMask);

featureData = helperBuildStage4CFeatures( ...
    dataset.previousState, ...
    dataset.previousCovarianceDiag, ...
    dataset.dtSeconds, ...
    dataset.baselineConstVelMetrics.predictedState);
holdoutFeatures = featureData.features(holdoutMask, :);
holdoutPreviousState = dataset.previousState(holdoutMask, :);

legacy = localLoadFrozenModel( ...
    config.Stage3AArtifactPath, ...
    "physicsFeatures", ...
    "legacy_stage3a_v1");
scratch = localLoadFrozenModel( ...
    config.ScratchArtifactPath, ...
    "features", ...
    "expanded_scratch_mean_v1");
warm = localLoadFrozenModel( ...
    config.WarmArtifactPath, ...
    "features", ...
    "expanded_warm_mean_v1");

comparatorPredictions = localBuildComparatorPredictions( ...
    double(dataset.baselineConstVelMetrics.predictedState(holdoutMask, :)), ...
    localPredictPhysicalState( ...
        legacy.net, ...
        holdoutFeatures, ...
        holdoutPreviousState, ...
        legacy.featureNormalization, ...
        legacy.targetNormalization, ...
        config.PredictionMiniBatchSize), ...
    localPredictPhysicalState( ...
        scratch.net, ...
        holdoutFeatures, ...
        holdoutPreviousState, ...
        scratch.featureNormalization, ...
        scratch.targetNormalization, ...
        config.PredictionMiniBatchSize), ...
    localPredictPhysicalState( ...
        warm.net, ...
        holdoutFeatures, ...
        holdoutPreviousState, ...
        warm.featureNormalization, ...
        warm.targetNormalization, ...
        config.PredictionMiniBatchSize));

nativeMetrics = helperScoreStage4CNativeManeuverModels( ...
    dataset.nextState(holdoutMask, :), ...
    comparatorPredictions, ...
    holdoutNativeBaseline, ...
    holdoutMetadata, ...
    holdoutLabels, ...
    holdoutSplit);
localAuditExpectedCoverage(nativeMetrics.coverageTable);
nativeMetrics.selectionTable = localMapSelectionToDatasetRows( ...
    nativeMetrics.selectionTable, ...
    holdoutDatasetRows);
initializationDiagnostics = localBuildInitializationDiagnostics( ...
    holdoutNativeBaseline, ...
    holdoutLabels, ...
    holdoutSplit);

baseMetricTable = stage4CSummary.metrics.table( ...
    stage4CSummary.metrics.table.groupDimension ~= ...
    "native_maneuver_baseline", :);
stage4CSummary.metrics.table = [ ...
    baseMetricTable; ...
    nativeMetrics.table];

if config.CreatePlots
    figurePath = helperWriteStage4CNativeManeuverFigure( ...
        config.FigurePath, ...
        nativeMetrics.table);
else
    figurePath = "";
end

frozenIntegrity = localHashFrozenArtifacts( ...
    config, ...
    "after", ...
    frozenIntegrity);

extension = struct();
extension.generatedAt = datetime("now", "TimeZone", "UTC");
extension.completed = true;
extension.evaluationOnly = true;
extension.policy = localBuildPolicyRecord(nativeBaseline);
extension.nativeFunctionAudit = localBuildNativeFunctionAudit();
extension.coverageTable = nativeMetrics.coverageTable;
extension.exclusionTable = nativeMetrics.exclusionTable;
extension.selectionTable = nativeMetrics.selectionTable;
extension.initializationDiagnostics = initializationDiagnostics;
extension.metrics = rmfield(nativeMetrics, ...
    ["coverageTable", "exclusionTable", "selectionTable"]);
extension.figurePath = figurePath;
extension.frozenArtifactIntegrity = frozenIntegrity;
extension.trainingPerformed = false;
extension.modelPromoted = false;
extension.retrospectiveLabelPolicy = ...
    "Truth-derived maneuver labels select evaluation rows only; they do not initialize or enter predictions.";
extension.icaoPolicy = ...
    "ICAO is used only for split assignment and same-track predecessor grouping.";
extension.deferredSensitivityStudy = ...
    "Bounded or smoothed causal acceleration/turn-rate initialization.";

stage4CSummary.nativeManeuverBaseline = extension;

if ~isfield(stage4CSummary, "figurePaths") || ...
        ~isstruct(stage4CSummary.figurePaths)
    stage4CSummary.figurePaths = struct();
end

stage4CSummary.figurePaths.nativeManeuverBaseline = figurePath;
stage4CSummary.metricTablePath = config.MetricTablePath;
stage4CSummary.reportPath = config.ReportPath;
stage4CSummary.comparisonArtifactPath = config.ComparisonArtifactPath;

writetable(stage4CSummary.metrics.table, config.MetricTablePath);
localSaveComparisonSummary(config.ComparisonArtifactPath, stage4CSummary);
helperWriteStage4CRetrainReport(config.ReportPath, stage4CSummary);

summary = stage4CSummary;

if config.Verbose
    localPrintCompletion(extension, config);
end

end

function config = localBuildConfig(opts)
%LOCALBUILDCONFIG Resolve the frozen Stage 4C paths.

config = struct();
config.ProjectRoot = localCanonicalPath(localTextScalar( ...
    opts.ProjectRoot, "ProjectRoot"));
config.DatasetPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.DatasetPath, ...
    fullfile( ...
        "artifacts", ...
        "stage4BPostCampaign", ...
        "expanded_post3day_v2", ...
        "stage3CArchiveStatePairDataset.mat"));
config.SplitManifestPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.SplitManifestPath, ...
    fullfile( ...
        "adsb_archive", ...
        "datasetVersions", ...
        "expandedPost3DayICAODisjointSplit_v1.csv"));
config.Stage3AArtifactPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.Stage3AArtifactPath, ...
    fullfile("artifacts", "stage3", "localADSBMLPStage3Training.mat"));
config.ScratchArtifactPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.ScratchArtifactPath, ...
    fullfile( ...
        "artifacts", ...
        "stage4CRetrain", ...
        "expandedPost3DayScratchMeanMLP_v1.mat"));
config.WarmArtifactPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.WarmArtifactPath, ...
    fullfile( ...
        "artifacts", ...
        "stage4CRetrain", ...
        "expandedPost3DayWarmStartMeanMLP_v1.mat"));
config.ComparisonArtifactPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.ComparisonArtifactPath, ...
    fullfile( ...
        "artifacts", ...
        "stage4CRetrain", ...
        "expandedPost3DayMeanMLPComparison_v1.mat"));
config.MetricTablePath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.MetricTablePath, ...
    fullfile( ...
        "artifacts", ...
        "stage4CRetrain", ...
        "stage4CRetrainMetricComparison.csv"));
config.ReportPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.ReportPath, ...
    fullfile( ...
        "artifacts", ...
        "stage4CRetrain", ...
        "stage4CRetrainExpandedADSBMLPReport.md"));
config.FigurePath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.FigurePath, ...
    fullfile( ...
        "artifacts", ...
        "stage4CRetrain", ...
        "stage4C_native_maneuver_baseline_comparison.png"));
config.PredictionMiniBatchSize = double(opts.PredictionMiniBatchSize);
config.CreatePlots = localLogicalScalar(opts.CreatePlots, "CreatePlots");
config.Verbose = localLogicalScalar(opts.Verbose, "Verbose");

end

function localValidateConfig(config)
%LOCALVALIDATECONFIG Guard inputs and frozen artifact paths.

requiredFiles = [ ...
    config.DatasetPath, ...
    config.SplitManifestPath, ...
    config.Stage3AArtifactPath, ...
    config.ScratchArtifactPath, ...
    config.WarmArtifactPath, ...
    config.ComparisonArtifactPath, ...
    config.MetricTablePath, ...
    config.ReportPath];

for pathIdx = 1:numel(requiredFiles)
    if exist(requiredFiles(pathIdx), "file") ~= 2
        error("Stage4CNative:MissingInputFile", ...
            "Required Stage 4C file was not found: %s", ...
            requiredFiles(pathIdx));
    end
end

validateattributes(config.PredictionMiniBatchSize, ...
    {'numeric'}, {'scalar', 'integer', 'positive'}, ...
    mfilename, "PredictionMiniBatchSize");

modelPaths = [ ...
    config.Stage3AArtifactPath, ...
    config.ScratchArtifactPath, ...
    config.WarmArtifactPath];
outputPaths = [ ...
    config.ComparisonArtifactPath, ...
    config.MetricTablePath, ...
    config.ReportPath, ...
    config.FigurePath];

if any(ismember(lower(outputPaths), lower(modelPaths)))
    error("Stage4CNative:FrozenArtifactCollision", ...
        "Evaluation outputs cannot overwrite a frozen model artifact.");
end

end

function dataset = localLoadDataset(datasetPath)
%LOCALLOADDATASET Load only fields needed for evaluation.

try
    dataset = load( ...
        datasetPath, ...
        "previousState", ...
        "nextState", ...
        "dtSeconds", ...
        "previousCovarianceDiag", ...
        "metadata", ...
        "stateOrder", ...
        "baselineConstVelMetrics");
catch err
    error("Stage4CNative:DatasetLoadFailed", ...
        "Unable to load the Expanded-3Day dataset: %s", err.message);
end

requiredFields = [ ...
    "previousState", ...
    "nextState", ...
    "dtSeconds", ...
    "previousCovarianceDiag", ...
    "metadata", ...
    "stateOrder", ...
    "baselineConstVelMetrics"];

if any(~isfield(dataset, requiredFields))
    error("Stage4CNative:InvalidDataset", ...
        "The Expanded-3Day dataset is missing required fields.");
end

pairCount = size(dataset.previousState, 1);
expectedStateOrder = ["x", "vx", "y", "vy", "z", "vz"];

if pairCount ~= 457903 || ...
        ~isequal(size(dataset.previousState), [pairCount, 6]) || ...
        ~isequal(size(dataset.nextState), [pairCount, 6]) || ...
        ~isequal(size(dataset.previousCovarianceDiag), [pairCount, 6]) || ...
        numel(dataset.dtSeconds) ~= pairCount || ...
        height(dataset.metadata) ~= pairCount || ...
        any(string(dataset.stateOrder(:).') ~= expectedStateOrder)
    error("Stage4CNative:DatasetContractMismatch", ...
        "The frozen Expanded-3Day dataset contract has changed.");
end

if ~isfield(dataset.baselineConstVelMetrics, "predictedState") || ...
        ~isequal(size(dataset.baselineConstVelMetrics.predictedState), ...
        [pairCount, 6])
    error("Stage4CNative:MissingConstvelPrediction", ...
        "The dataset lacks aligned native constvel predictions.");
end

end

function split = localLoadSplit(metadata, splitManifestPath)
%LOCALLOADSPLIT Apply the frozen global ICAO-disjoint split.

manifest = readtable(splitManifestPath, "TextType", "string");
manifest.icao24 = lower(strtrim(string(manifest.icao24)));
manifest.split = lower(strtrim(string(manifest.split)));
[found, manifestRow] = ismember( ...
    lower(strtrim(string(metadata.hex))), ...
    manifest.icao24);

if ~all(found)
    error("Stage4CNative:SplitMembershipMismatch", ...
        "Every dataset ICAO must occur in the frozen split manifest.");
end

split = manifest.split(manifestRow);

if ~isequal( ...
        [sum(split == "train"), ...
        sum(split == "validation"), ...
        sum(split == "test")], ...
        [277959, 86420, 93524])
    error("Stage4CNative:SplitCountMismatch", ...
        "The frozen train/validation/test pair counts have changed.");
end

end

function stage4CSummary = localLoadComparisonSummary(comparisonArtifactPath)
%LOCALLOADCOMPARISONSUMMARY Load the completed compact Stage 4C artifact.

try
    loaded = load(comparisonArtifactPath, "stage4CSummary");
catch err
    error("Stage4CNative:ComparisonLoadFailed", ...
        "Unable to load the Stage 4C comparison artifact: %s", err.message);
end

if ~isfield(loaded, "stage4CSummary") || ...
        ~isfield(loaded.stage4CSummary, "completed") || ...
        ~loaded.stage4CSummary.completed || ...
        ~isfield(loaded.stage4CSummary, "metrics") || ...
        ~isfield(loaded.stage4CSummary.metrics, "table")
    error("Stage4CNative:InvalidComparisonArtifact", ...
        "A completed Stage 4C comparison artifact is required.");
end

stage4CSummary = loaded.stage4CSummary;

end

function localAuditFrozenInputs(dataset, split, stage4CSummary, config)
%LOCALAUDITFROZENINPUTS Confirm the extension matches the training run.

datasetSHA256 = helperComputeFileSHA256(config.DatasetPath);
splitSHA256 = helperComputeFileSHA256(config.SplitManifestPath);

if ~strcmpi( ...
        datasetSHA256, ...
        stage4CSummary.datasetProvenance.datasetSHA256) || ...
        ~strcmpi( ...
        splitSHA256, ...
        stage4CSummary.splitProvenance.splitManifestSHA256)
    error("Stage4CNative:FrozenInputHashMismatch", ...
        "Dataset or split hash differs from the completed Stage 4C run.");
end

if size(dataset.previousState, 1) ~= ...
        stage4CSummary.datasetPairCount || ...
        any(~ismember(unique(split), ["train", "validation", "test"]))
    error("Stage4CNative:FrozenInputAlignmentMismatch", ...
        "Dataset rows or split names no longer match Stage 4C.");
end

end

function model = localLoadFrozenModel( ...
        artifactPath, featureNormalizationField, expectedModelID)
%LOCALLOADFROZENMODEL Resolve network and normalization without mutation.

try
    loaded = load(artifactPath, "net", "normalization");
catch err
    error("Stage4CNative:ModelLoadFailed", ...
        "Unable to load frozen model %s: %s", artifactPath, err.message);
end

if ~isfield(loaded, "net") || ...
        ~isfield(loaded, "normalization") || ...
        isempty(loaded.net)
    error("Stage4CNative:InvalidModelArtifact", ...
        "Frozen model artifact lacks its network or normalization: %s", ...
        artifactPath);
end

availableVariables = string(who("-file", artifactPath));

if ismember("modelArtifact", availableVariables)
    identityRecord = load(artifactPath, "modelArtifact");

    if isfield(identityRecord.modelArtifact, "modelID") && ...
            string(identityRecord.modelArtifact.modelID) ~= expectedModelID
        error("Stage4CNative:ModelIdentityMismatch", ...
            "Expected %s in %s.", expectedModelID, artifactPath);
    end
end

if ~isfield(loaded.normalization, featureNormalizationField) || ...
        ~isfield(loaded.normalization, "target")
    error("Stage4CNative:MissingModelNormalization", ...
        "Frozen model normalization is incomplete: %s", artifactPath);
end

model = struct();
model.modelID = string(expectedModelID);
model.net = loaded.net;
model.featureNormalization = ...
    loaded.normalization.(featureNormalizationField);
model.targetNormalization = loaded.normalization.target;

end

function predictedState = localPredictPhysicalState( ...
        net, ...
        physicalFeatures, ...
        previousState, ...
        featureNormalization, ...
        targetNormalization, ...
        miniBatchSize)
%LOCALPREDICTPHYSICALSTATE Run one frozen mean model in physical units.

featuresNormalized = ...
    (double(physicalFeatures) - featureNormalization.featureMean) ./ ...
    featureNormalization.featureStd;
predictedDeltaNormalized = minibatchpredict( ...
    net, ...
    single(featuresNormalized), ...
    "MiniBatchSize", ...
    min(miniBatchSize, size(featuresNormalized, 1)));
predictedDeltaNormalized = gather(extractdata( ...
    predictedDeltaNormalized));

if size(predictedDeltaNormalized, 1) ~= size(featuresNormalized, 1) && ...
        size(predictedDeltaNormalized, 2) == size(featuresNormalized, 1)
    predictedDeltaNormalized = predictedDeltaNormalized.';
end

if ~isequal(size(predictedDeltaNormalized), ...
        [size(featuresNormalized, 1), 6])
    error("Stage4CNative:PredictionShapeMismatch", ...
        "Every frozen mean model must return an N-by-6 prediction.");
end

predictedDelta = double(predictedDeltaNormalized) .* ...
    targetNormalization.targetStd + ...
    targetNormalization.targetMean;
predictedState = double(previousState) + predictedDelta;

if any(~isfinite(predictedState), "all")
    error("Stage4CNative:NonfiniteFrozenPrediction", ...
        "A frozen Stage 4C model produced nonfinite predictions.");
end

end

function models = localBuildComparatorPredictions( ...
        constvelPrediction, ...
        legacyPrediction, ...
        scratchPrediction, ...
        warmPrediction)
%LOCALBUILDCOMPARATORPREDICTIONS Preserve the frozen comparison order.

models = repmat(struct( ...
    "modelID", "", ...
    "predictedNextState", []), ...
    4, ...
    1);
models(1).modelID = "constvel";
models(1).predictedNextState = constvelPrediction;
models(2).modelID = "legacy_stage3a_v1";
models(2).predictedNextState = legacyPrediction;
models(3).modelID = "expanded_scratch_mean_v1";
models(3).predictedNextState = scratchPrediction;
models(4).modelID = "expanded_warm_mean_v1";
models(4).predictedNextState = warmPrediction;

end

function subset = localSubsetNativeBaseline(nativeBaseline, rowMask)
%LOCALSUBSETNATIVEBASELINE Keep only holdout-sized arrays for scoring.

subset = nativeBaseline;
subset.predecessorRowIndex = ...
    nativeBaseline.predecessorRowIndex(rowMask);
subset.eligibleMask = nativeBaseline.eligibleMask(rowMask);
subset.exclusionReason = nativeBaseline.exclusionReason(rowMask);
subset.rawAccelerationMetersPerSecondSquared = ...
    nativeBaseline.rawAccelerationMetersPerSecondSquared(rowMask, :);
subset.rawTurnRateDegreesPerSecond = ...
    nativeBaseline.rawTurnRateDegreesPerSecond(rowMask);
subset.constaccPredictedState = ...
    nativeBaseline.constaccPredictedState(rowMask, :);
subset.constturnPredictedState = ...
    nativeBaseline.constturnPredictedState(rowMask, :);

end

function selectionTable = localMapSelectionToDatasetRows( ...
        selectionTable, holdoutDatasetRows)
%LOCALMAPSELECTIONTODATASETROWS Store exact frozen-dataset row identities.

datasetRowIndices = cell(height(selectionTable), 1);

for rowIdx = 1:height(selectionTable)
    inputRows = selectionTable.selectedInputRowIndices{rowIdx};
    datasetRowIndices{rowIdx} = holdoutDatasetRows(inputRows);
end

selectionTable.datasetRowIndices = datasetRowIndices;
selectionTable = removevars(selectionTable, "selectedInputRowIndices");

end

function diagnostics = localBuildInitializationDiagnostics( ...
        nativeBaseline, maneuverPairTable, split)
%LOCALBUILDINITIALIZATIONDIAGNOSTICS Quantify raw finite-difference tails.

splitNames = ["validation", "test"];
sliceNames = ["constacc_like", "constturn_like"];
quantityNames = [ ...
    "acceleration_magnitude"; ...
    "absolute_turn_rate"];
units = ["m/s^2"; "deg/s"];
rowCount = numel(splitNames) * numel(sliceNames);
splitColumn = strings(rowCount, 1);
sliceColumn = strings(rowCount, 1);
quantityColumn = strings(rowCount, 1);
unitsColumn = strings(rowCount, 1);
sampleCount = zeros(rowCount, 1);
p50 = NaN(rowCount, 1);
p90 = NaN(rowCount, 1);
p95 = NaN(rowCount, 1);
p99 = NaN(rowCount, 1);
p999 = NaN(rowCount, 1);
maximum = NaN(rowCount, 1);
signedMinimum = NaN(rowCount, 1);
signedMaximum = NaN(rowCount, 1);
outlierUpperFence = NaN(rowCount, 1);
outlierCount = zeros(rowCount, 1);
outlierFraction = NaN(rowCount, 1);
outputRow = 0;

for splitIdx = 1:numel(splitNames)
    for sliceIdx = 1:numel(sliceNames)
        outputRow = outputRow + 1;
        rowMask = ...
            (split == splitNames(splitIdx)) & ...
            (string(maneuverPairTable.maneuverClass) == ...
            sliceNames(sliceIdx)) & ...
            nativeBaseline.eligibleMask;

        if sliceIdx == 1
            rawSignedValues = NaN(sum(rowMask), 1);
            values = vecnorm( ...
                nativeBaseline.rawAccelerationMetersPerSecondSquared( ...
                rowMask, :), ...
                2, ...
                2);
        else
            rawSignedValues = ...
                nativeBaseline.rawTurnRateDegreesPerSecond(rowMask);
            values = abs(rawSignedValues);
        end

        probability = [0.50, 0.90, 0.95, 0.99, 0.999];
        quantiles = quantile(values, probability);
        quartiles = quantile(values, [0.25, 0.75]);
        upperFence = quartiles(2) + 1.5 * ...
            (quartiles(2) - quartiles(1));
        highOutlierMask = values > upperFence;

        if sliceIdx == 2
            signedMinimum(outputRow) = min(rawSignedValues);
            signedMaximum(outputRow) = max(rawSignedValues);
        end

        splitColumn(outputRow) = splitNames(splitIdx);
        sliceColumn(outputRow) = sliceNames(sliceIdx);
        quantityColumn(outputRow) = quantityNames(sliceIdx);
        unitsColumn(outputRow) = units(sliceIdx);
        sampleCount(outputRow) = numel(values);
        p50(outputRow) = quantiles(1);
        p90(outputRow) = quantiles(2);
        p95(outputRow) = quantiles(3);
        p99(outputRow) = quantiles(4);
        p999(outputRow) = quantiles(5);
        maximum(outputRow) = max(values);
        outlierUpperFence(outputRow) = upperFence;
        outlierCount(outputRow) = sum(highOutlierMask);
        outlierFraction(outputRow) = mean(highOutlierMask);
    end
end

diagnostics = table( ...
    splitColumn, ...
    sliceColumn, ...
    quantityColumn, ...
    unitsColumn, ...
    sampleCount, ...
    p50, ...
    p90, ...
    p95, ...
    p99, ...
    p999, ...
    maximum, ...
    signedMinimum, ...
    signedMaximum, ...
    outlierUpperFence, ...
    outlierCount, ...
    outlierFraction, ...
    'VariableNames', [ ...
        "split", ...
        "maneuverSlice", ...
        "quantity", ...
        "units", ...
        "sampleCount", ...
        "p50", ...
        "p90", ...
        "p95", ...
        "p99", ...
        "p999", ...
        "maximum", ...
        "signedMinimum", ...
        "signedMaximum", ...
        "outlierUpperFence", ...
        "outlierCount", ...
        "outlierFraction"]);

end

function localAuditExpectedCoverage(coverageTable)
%LOCALAUDITEXPECTEDCOVERAGE Enforce the approved frozen-data counts.

expected = table( ...
    ["validation"; "validation"; "test"; "test"], ...
    ["constacc_like"; "constturn_like"; ...
    "constacc_like"; "constturn_like"], ...
    [17030; 2084; 18028; 2186], ...
    [16896; 2075; 17890; 2164], ...
    'VariableNames', [ ...
        "split", ...
        "maneuverSlice", ...
        "sourceSliceRowCount", ...
        "eligibleRowCount"]);
observed = sortrows( ...
    coverageTable(:, expected.Properties.VariableNames), ...
    ["split", "maneuverSlice"]);
expected = sortrows(expected, ["split", "maneuverSlice"]);

if ~isequal(observed, expected)
    error("Stage4CNative:CoverageMismatch", ...
        "Frozen maneuver eligibility coverage differs from the approved counts.");
end

end

function policy = localBuildPolicyRecord(nativeBaseline)
%LOCALBUILDPOLICYRECORD Save the causal initialization contract.

policy = struct();
policy.policyID = nativeBaseline.policyID;
policy.accelerationEstimate = ...
    "(velocity_k - velocity_k_minus_1) / prior_dt in ENU";
policy.turnRateEstimate = ...
    "wrapTo180(atan2d(vy_k,vx_k) - atan2d(vy_k_minus_1,vx_k_minus_1)) / prior_dt";
policy.previousStateOrder = nativeBaseline.previousStateOrder;
policy.constaccStateOrder = nativeBaseline.constaccStateOrder;
policy.constturnStateOrder = nativeBaseline.constturnStateOrder;
policy.temporalAdjacencyToleranceSeconds = ...
    nativeBaseline.temporalAdjacencyToleranceSeconds;
policy.smoothingApplied = nativeBaseline.smoothingApplied;
policy.clippingApplied = nativeBaseline.clippingApplied;
policy.targetStateUsed = nativeBaseline.targetStateUsed;
policy.maneuverLabelUsed = nativeBaseline.maneuverLabelUsed;
policy.icaoUse = nativeBaseline.icaoUse;

end

function audit = localBuildNativeFunctionAudit()
%LOCALBUILDNATIVEFUNCTIONAUDIT Record toolbox-first implementation choices.

workflow = [ ...
    "Constant-acceleration propagation"; ...
    "Constant-turn propagation"; ...
    "Wrapped heading difference"; ...
    "Error norms"; ...
    "Distribution summaries"];
nativeMATLABFunction = [ ...
    "constacc"; ...
    "constturn"; ...
    "atan2d and wrapTo180"; ...
    "vecnorm"; ...
    "quantile"];
stage4CUse = [ ...
    "Propagate [x,vx,ax,y,vy,ay,z,vz,az] with row-specific dt"; ...
    "Propagate [x,vx,y,vy,omega,z,vz] with omega in deg/s"; ...
    "Estimate causal native turn rate across the +/-180 degree boundary"; ...
    "Compute 3-D position, velocity, and acceleration magnitudes"; ...
    "Report raw initialization tails without clipping or smoothing"];
verified = true(5, 1);
audit = table( ...
    workflow, ...
    nativeMATLABFunction, ...
    stage4CUse, ...
    verified);

end

function integrity = localHashFrozenArtifacts(config, phase, integrity)
%LOCALHASHFROZENARTIFACTS Hash all model artifacts before and after.

artifactID = [ ...
    "legacy_stage3a_v1"; ...
    "expanded_scratch_mean_v1"; ...
    "expanded_warm_mean_v1"];
path = [ ...
    config.Stage3AArtifactPath; ...
    config.ScratchArtifactPath; ...
    config.WarmArtifactPath];
hashValue = strings(numel(path), 1);

for artifactIdx = 1:numel(path)
    hashValue(artifactIdx) = helperComputeFileSHA256(path(artifactIdx));
end

if phase == "before"
    integrity = table( ...
        artifactID, ...
        path, ...
        hashValue, ...
        repmat("", numel(path), 1), ...
        false(numel(path), 1), ...
        'VariableNames', [ ...
            "artifactID", ...
            "path", ...
            "beforeSHA256", ...
            "afterSHA256", ...
            "unchanged"]);
    return;
end

integrity.afterSHA256 = hashValue;
integrity.unchanged = strcmpi( ...
    integrity.beforeSHA256, ...
    integrity.afterSHA256);

if ~all(integrity.unchanged)
    error("Stage4CNative:FrozenArtifactChanged", ...
        "A frozen Stage 3A, scratch, or warm artifact changed.");
end

end

function localSaveComparisonSummary(artifactPath, stage4CSummary)
%LOCALSAVECOMPARISONSUMMARY Replace only the compact comparison artifact.

try
    save(artifactPath, "stage4CSummary", "-v7.3");
catch err
    error("Stage4CNative:ComparisonSaveFailed", ...
        "Unable to extend the Stage 4C comparison artifact: %s", ...
        err.message);
end

end

function localPrintCompletion(extension, config)
%LOCALPRINTCOMPLETION Print concise evaluation-only evidence.

fprintf("Native maneuver evaluation complete; no training was run.\n");
disp(extension.coverageTable);
fprintf("Comparison artifact:\t%s\n", config.ComparisonArtifactPath);
fprintf("Metric table:\t%s\n", config.MetricTablePath);
fprintf("Report:\t%s\n", config.ReportPath);

if strlength(extension.figurePath) > 0
    fprintf("Figure:\t%s\n", extension.figurePath);
end

end

function value = localTextScalar(value, argumentName)
%LOCALTEXTSCALAR Validate one nonempty text scalar.

if ~(ischar(value) || (isstring(value) && isscalar(value)))
    error("Stage4CNative:InvalidTextArgument", ...
        "%s must be a text scalar.", argumentName);
end

value = string(value);

if strlength(strtrim(value)) == 0
    error("Stage4CNative:EmptyTextArgument", ...
        "%s must not be empty.", argumentName);
end

end

function value = localLogicalScalar(value, argumentName)
%LOCALLOGICALSCALAR Validate one scalar logical setting.

if ~(islogical(value) && isscalar(value))
    error("Stage4CNative:InvalidLogicalArgument", ...
        "%s must be a logical scalar.", argumentName);
end

end

function resolvedPath = localResolvePath(projectRoot, value, defaultValue)
%LOCALRESOLVEPATH Resolve relative paths against the project root.

if isempty(value) || (isstring(value) && isscalar(value) && ...
        strlength(value) == 0)
    value = defaultValue;
end

value = localTextScalar(value, "path");

if localIsAbsolutePath(value)
    resolvedPath = localCanonicalPath(value);
else
    resolvedPath = localCanonicalPath(fullfile(projectRoot, value));
end

end

function canonicalPath = localCanonicalPath(pathValue)
%LOCALCANONICALPATH Normalize one path without requiring it to exist.

pathValue = string(pathValue);
fileObject = java.io.File(char(pathValue));
canonicalPath = string(fileObject.getCanonicalPath());

end

function tf = localIsAbsolutePath(pathValue)
%LOCALISABSOLUTEPATH Recognize Windows and UNC absolute paths.

pathValue = char(string(pathValue));
tf = ~isempty(regexp(pathValue, '^[A-Za-z]:[\\/]', 'once')) || ...
    startsWith(pathValue, "\\") || ...
    startsWith(pathValue, "/");

end
