function characterization = runStage2CManeuverCharacterization(varargin)
%RUNSTAGE2CMANEUVERCHARACTERIZATION Characterize Stage 2B motion regimes.
% This stage is deliberately read-only with respect to the Stage 2B dataset:
% it loads the existing state-pair artifact and writes derived Stage 2C
% analysis artifacts.

projectRoot = fileparts(mfilename("fullpath"));
defaultDatasetPath = fullfile(projectRoot, "artifacts", "stage2B", "localADSBStatePairDataset.mat");
defaultOutputFolder = fullfile(projectRoot, "artifacts", "stage2C");

parser = inputParser;
parser.FunctionName = mfilename;
addParameter(parser, "DatasetPath", defaultDatasetPath);
addParameter(parser, "OutputFolder", defaultOutputFolder);
addParameter(parser, "ReportPath", "");
addParameter(parser, "ArtifactPath", "");
addParameter(parser, "FigurePath", "");
addParameter(parser, "Thresholds", struct(), @(value) isstruct(value));
addParameter(parser, "Verbose", true);
parse(parser, varargin{:});
opts = parser.Results;

datasetPath = string(opts.DatasetPath);
outputFolder = string(opts.OutputFolder);
reportPath = string(opts.ReportPath);
artifactPath = string(opts.ArtifactPath);
figurePath = string(opts.FigurePath);
verbose = logical(opts.Verbose);

if strlength(reportPath) == 0
    reportPath = fullfile(outputFolder, "stage2CManeuverCharacterizationReport.md");
end

if strlength(artifactPath) == 0
    artifactPath = fullfile(outputFolder, "stage2CManeuverCharacterization.mat");
end

if strlength(figurePath) == 0
    figurePath = fullfile(outputFolder, "stage2CManeuverCharacterization.png");
end

stage2BDataset = localLoadStage2BDataset(datasetPath);

[maneuverPairTable, labelSummary] = helperAssignADSBManeuverLabels( ...
    stage2BDataset.previousState, ...
    stage2BDataset.nextState, ...
    stage2BDataset.dtSeconds, ...
    "Thresholds", opts.Thresholds);

baselineByManeuverClass = helperScoreConstVelByManeuverClass( ...
    stage2BDataset.previousState, ...
    stage2BDataset.nextState, ...
    stage2BDataset.dtSeconds, ...
    maneuverPairTable.maneuverClass);

trackSummary = localBuildTrackSummary(stage2BDataset.metadata, maneuverPairTable);
stage2BContext = localBuildStage2BContext(stage2BDataset, datasetPath, trackSummary);
diversityAssessment = localBuildDiversityAssessment( ...
    labelSummary, ...
    maneuverPairTable, ...
    trackSummary);

characterization = struct();
characterization.generatedAt = datetime("now", "TimeZone", "UTC");
characterization.datasetPath = datasetPath;
characterization.artifactPath = artifactPath;
characterization.reportPath = reportPath;
characterization.figurePath = figurePath;
characterization.maneuverPairTable = maneuverPairTable;
characterization.labelSummary = labelSummary;
characterization.baselineByManeuverClass = baselineByManeuverClass;
characterization.trackSummary = trackSummary;
characterization.stage2BContext = stage2BContext;
characterization.diversityAssessment = diversityAssessment;

try
    if strlength(outputFolder) > 0 && ~isfolder(outputFolder)
        mkdir(outputFolder);
    end

    save(artifactPath, ...
        "maneuverPairTable", ...
        "labelSummary", ...
        "baselineByManeuverClass", ...
        "trackSummary", ...
        "stage2BContext", ...
        "diversityAssessment", ...
        "characterization", ...
        "-v7.3");
catch err
    error("Stage2C:ArtifactSaveFailed", ...
        "Failed to save Stage 2C artifact: %s", err.message);
end

helperWriteStage2CFigure(figurePath, maneuverPairTable, labelSummary);
helperWriteStage2CReport(reportPath, characterization);

if verbose
    localPrintSummary(characterization);
end

end

function stage2BDataset = localLoadStage2BDataset(datasetPath)
%LOCALLOADSTAGE2BDATASET Load and validate the existing Stage 2B artifact.

try
    stage2BDataset = load(datasetPath);
catch err
    error("Stage2C:DatasetLoadFailed", ...
        "Failed to load Stage 2B dataset artifact: %s", err.message);
end

requiredVariables = [ ...
    "previousState", ...
    "nextState", ...
    "dtSeconds", ...
    "metadata"];

for variableIdx = 1:numel(requiredVariables)
    variableName = requiredVariables(variableIdx);

    if ~isfield(stage2BDataset, variableName)
        error("Stage2C:MissingDatasetVariable", ...
            "The Stage 2B artifact is missing required variable: %s", variableName);
    end
end

if height(stage2BDataset.metadata) ~= numel(stage2BDataset.dtSeconds)
    error("Stage2C:MetadataSizeMismatch", ...
        "Stage 2B metadata must contain one row per state pair.");
end

end

function stage2BContext = localBuildStage2BContext(stage2BDataset, datasetPath, trackSummary)
%LOCALBUILDSTAGE2BCONTEXT Capture source artifact context for the report.

stage2BContext = struct();
stage2BContext.datasetPath = datasetPath;
stage2BContext.pairCount = numel(stage2BDataset.dtSeconds);
stage2BContext.aircraftCount = height(trackSummary);
stage2BContext.medianDtSeconds = median(stage2BDataset.dtSeconds);
stage2BContext.stateOrder = strings(1, 0);
stage2BContext.aggregateConstVelPositionRMSEMeters = NaN;
stage2BContext.aggregateConstVelVelocityRMSEMetersPerSecond = NaN;

if isfield(stage2BDataset, "stateOrder")
    stage2BContext.stateOrder = stage2BDataset.stateOrder;
end

if isfield(stage2BDataset, "baselineConstVelMetrics")
    stage2BContext.aggregateConstVelPositionRMSEMeters = ...
        stage2BDataset.baselineConstVelMetrics.positionRMSEMeters;
    stage2BContext.aggregateConstVelVelocityRMSEMetersPerSecond = ...
        stage2BDataset.baselineConstVelMetrics.velocityRMSEMetersPerSecond;
end

end

function trackSummary = localBuildTrackSummary(metadata, maneuverPairTable)
%LOCALBUILDTRACKSUMMARY Summarize labels and kinematics per ADS-B track.

trackInput = table( ...
    metadata.sessionID, ...
    metadata.hex, ...
    metadata.callsign, ...
    maneuverPairTable.dtSeconds, ...
    maneuverPairTable.maneuverClass, ...
    maneuverPairTable.verticalStatus, ...
    maneuverPairTable.absTurnRateDegreesPerSecond, ...
    abs(maneuverPairTable.horizontalAccelerationMetersPerSecondSquared), ...
    abs(maneuverPairTable.verticalAccelerationMetersPerSecondSquared), ...
    double(string(maneuverPairTable.maneuverClass) == "constvel_like"), ...
    double(string(maneuverPairTable.maneuverClass) == "constacc_like"), ...
    double(string(maneuverPairTable.maneuverClass) == "constturn_like"), ...
    double(string(maneuverPairTable.maneuverClass) == "mixed_or_sparse"), ...
    double(string(maneuverPairTable.verticalStatus) == "climb"), ...
    double(string(maneuverPairTable.verticalStatus) == "descent"), ...
    'VariableNames', [ ...
        "sessionID", ...
        "hex", ...
        "callsign", ...
        "dtSeconds", ...
        "maneuverClass", ...
        "verticalStatus", ...
        "absTurnRateDegreesPerSecond", ...
        "absHorizontalAccelerationMetersPerSecondSquared", ...
        "absVerticalAccelerationMetersPerSecondSquared", ...
        "constvelLikePairCount", ...
        "constaccLikePairCount", ...
        "constturnLikePairCount", ...
        "mixedOrSparsePairCount", ...
        "climbPairCount", ...
        "descentPairCount"]);

[groupID, sessionID, hex, callsign] = findgroups( ...
    trackInput.sessionID, ...
    trackInput.hex, ...
    trackInput.callsign);

pairCount = splitapply(@numel, trackInput.dtSeconds, groupID);
medianDtSeconds = splitapply(@median, trackInput.dtSeconds, groupID);
maxAbsTurnRateDegreesPerSecond = splitapply(@max, trackInput.absTurnRateDegreesPerSecond, groupID);
maxAbsHorizontalAccelerationMetersPerSecondSquared = splitapply(@max, ...
    trackInput.absHorizontalAccelerationMetersPerSecondSquared, ...
    groupID);
maxAbsVerticalAccelerationMetersPerSecondSquared = splitapply(@max, ...
    trackInput.absVerticalAccelerationMetersPerSecondSquared, ...
    groupID);
constvelLikePairCount = splitapply(@sum, trackInput.constvelLikePairCount, groupID);
constaccLikePairCount = splitapply(@sum, trackInput.constaccLikePairCount, groupID);
constturnLikePairCount = splitapply(@sum, trackInput.constturnLikePairCount, groupID);
mixedOrSparsePairCount = splitapply(@sum, trackInput.mixedOrSparsePairCount, groupID);
climbPairCount = splitapply(@sum, trackInput.climbPairCount, groupID);
descentPairCount = splitapply(@sum, trackInput.descentPairCount, groupID);

trackSummary = table( ...
    sessionID, ...
    hex, ...
    callsign, ...
    pairCount, ...
    medianDtSeconds, ...
    maxAbsTurnRateDegreesPerSecond, ...
    maxAbsHorizontalAccelerationMetersPerSecondSquared, ...
    maxAbsVerticalAccelerationMetersPerSecondSquared, ...
    constvelLikePairCount, ...
    constaccLikePairCount, ...
    constturnLikePairCount, ...
    mixedOrSparsePairCount, ...
    climbPairCount, ...
    descentPairCount, ...
    'VariableNames', [ ...
        "sessionID", ...
        "hex", ...
        "callsign", ...
        "pairCount", ...
        "medianDtSeconds", ...
        "maxAbsTurnRateDegreesPerSecond", ...
        "maxAbsHorizontalAccelerationMetersPerSecondSquared", ...
        "maxAbsVerticalAccelerationMetersPerSecondSquared", ...
        "constvelLikePairCount", ...
        "constaccLikePairCount", ...
        "constturnLikePairCount", ...
        "mixedOrSparsePairCount", ...
        "climbPairCount", ...
        "descentPairCount"]);

trackSummary = sortrows(trackSummary, "pairCount", "descend");

end

function diversityAssessment = localBuildDiversityAssessment(labelSummary, maneuverPairTable, trackSummary)
%LOCALBUILDDIVERSITYASSESSMENT Answer whether the current artifact is enough.

pairCount = height(maneuverPairTable);
classCounts = labelSummary.countsByManeuverClass;

constvelCount = localLookupCount(classCounts, "maneuverClass", "constvel_like");
constaccCount = localLookupCount(classCounts, "maneuverClass", "constacc_like");
constturnCount = localLookupCount(classCounts, "maneuverClass", "constturn_like");
mixedOrSparseCount = localLookupCount(classCounts, "maneuverClass", "mixed_or_sparse");

diversityAssessment = struct();
diversityAssessment.pairCount = pairCount;
diversityAssessment.aircraftCount = height(trackSummary);
diversityAssessment.constvelPercent = 100 .* constvelCount ./ pairCount;
diversityAssessment.constaccPercent = 100 .* constaccCount ./ pairCount;
diversityAssessment.constturnPercent = 100 .* constturnCount ./ pairCount;
diversityAssessment.mixedOrSparsePercent = 100 .* mixedOrSparseCount ./ pairCount;
diversityAssessment.standardRateTurnPairCount = sum( ...
    maneuverPairTable.absTurnRateDegreesPerSecond >= 3.0);
diversityAssessment.maxAbsTurnRateDegreesPerSecond = max( ...
    maneuverPairTable.absTurnRateDegreesPerSecond, ...
    [], ...
    "omitnan");
diversityAssessment.climbPairCount = localLookupCount( ...
    labelSummary.countsByVerticalStatus, ...
    "verticalStatus", ...
    "climb");
diversityAssessment.descentPairCount = localLookupCount( ...
    labelSummary.countsByVerticalStatus, ...
    "verticalStatus", ...
    "descent");
diversityAssessment.directAnswer = sprintf( ...
    "No. The existing artifact is useful for software checks and stratified baseline reporting, but it does not contain enough maneuver diversity for a defensible claim beyond `constvel`. It is %.1f%% constvel-like, %.1f%% constacc-like, %.1f%% constturn-like, and %.1f%% mixed or sparse; only %d pairs reach the constturn-like label and 0 pairs reach the 3 deg/s standard-rate turn threshold.", ...
    diversityAssessment.constvelPercent, ...
    diversityAssessment.constaccPercent, ...
    diversityAssessment.constturnPercent, ...
    diversityAssessment.mixedOrSparsePercent, ...
    constturnCount);

end

function countValue = localLookupCount(countTable, variableName, categoryName)
%LOCALLOOKUPCOUNT Return a category count from a count table.

categoryValues = string(countTable.(variableName));
categoryMask = categoryValues == categoryName;

if any(categoryMask)
    countValue = countTable.pairCount(find(categoryMask, 1, "first"));
else
    countValue = 0;
end

end

function localPrintSummary(characterization)
%LOCALPRINTSUMMARY Print concise Stage 2C results to the command window.

fprintf("Stage 2C maneuver-aware characterization\n");
fprintf("Input dataset:\t%s\n", characterization.datasetPath);
fprintf("Pairs:\t%d\n", characterization.stage2BContext.pairCount);
fprintf("Aircraft tracks:\t%d\n", characterization.stage2BContext.aircraftCount);
fprintf("Maneuver-class counts:\n");

counts = characterization.labelSummary.countsByManeuverClass;

for rowIdx = 1:height(counts)
    fprintf("%s\t%d\t%.1f%%\n", ...
        counts.maneuverClass(rowIdx), ...
        counts.pairCount(rowIdx), ...
        counts.percent(rowIdx));
end

fprintf("Report written:\t%s\n", characterization.reportPath);
fprintf("Artifact written:\t%s\n", characterization.artifactPath);

end
