function outputs = runStage2BLocalADSBSmoke()
%RUNSTAGE2BLOCALADSBSMOKE Build the Stage 2B dataset and run smoke training.

projectRoot = fileparts(mfilename("fullpath"));
truthFile = fullfile( ...
    fileparts(projectRoot), ...
    "BistaticDataAnalysis", ...
    "captures", ...
    "20260622T102123", ...
    "truth", ...
    "0_20260622_102124_adsb_20260622T102123.txt.gz");

dataset = buildLocalADSBStatePairDataset( ...
    "SourceFiles", truthFile, ...
    "SmokeTest", true, ...
    "Verbose", true);

trainingSummary = trainLocalADSBMLPSmoke( ...
    dataset.buildSummary.outputPath, ...
    "NumEpochs", 3, ...
    "Verbose", true);

outputs = struct();
outputs.dataset = dataset;
outputs.trainingSummary = trainingSummary;

end
