function stage3BSummary = runStage3BAggregateADSBEvaluation(varargin)
%RUNSTAGE3BAGGREGATEADSBEVALUATION Compare frozen Stage 3A MLP and constvel.
% Stage 3B aggregates the local ADS-B truth currently available, rebuilds a
% derived state-pair dataset under artifacts/stage3B, and evaluates the
% frozen Stage 3A network without retraining.

projectRoot = fileparts(mfilename("fullpath"));
flightTestRoot = fileparts(projectRoot);
defaultSearchRoot = fullfile(flightTestRoot, "BistaticDataAnalysis", "captures");
defaultParserFolder = fullfile(flightTestRoot, "BistaticDataAnalysis");
defaultOutputFolder = fullfile(projectRoot, "artifacts", "stage3B");
defaultAggregateDatasetPath = fullfile(defaultOutputFolder, "localADSBAggregateStatePairDataset.mat");
defaultAggregateDatasetReportPath = fullfile(defaultOutputFolder, "stage3BAggregateStatePairDatasetSummary.md");
defaultStage3AArtifactPath = fullfile(projectRoot, "artifacts", "stage3", "localADSBMLPStage3Training.mat");
defaultArtifactPath = fullfile(defaultOutputFolder, "localADSBAggregateStage3BEvaluation.mat");
defaultReportPath = fullfile(defaultOutputFolder, "stage3BAggregateADSBEvaluationReport.md");

parser = inputParser;
parser.FunctionName = mfilename;
addParameter(parser, "ProjectRoot", projectRoot);
addParameter(parser, "SourceFiles", strings(0, 1));
addParameter(parser, "SearchRoot", defaultSearchRoot);
addParameter(parser, "ParserFolder", defaultParserFolder);
addParameter(parser, "OutputFolder", defaultOutputFolder);
addParameter(parser, "AggregateDatasetPath", defaultAggregateDatasetPath);
addParameter(parser, "AggregateDatasetReportPath", defaultAggregateDatasetReportPath);
addParameter(parser, "Stage3AArtifactPath", defaultStage3AArtifactPath);
addParameter(parser, "ArtifactPath", defaultArtifactPath);
addParameter(parser, "ReportPath", defaultReportPath);
addParameter(parser, "RebuildAggregateDataset", true);
addParameter(parser, "CreatePlots", true);
addParameter(parser, "CreateGlobeSnapshot", false);
addParameter(parser, "MinimumSessionsForRetraining", 3);
addParameter(parser, "MinimumSourceFilesForRetraining", 3);
addParameter(parser, "MinimumAircraftForRetraining", 20);
addParameter(parser, "MinimumNonConstvelManeuverClasses", 2);
addParameter(parser, "MinimumConstaccPairs", 100);
addParameter(parser, "MinimumConstturnPairs", 100);
addParameter(parser, "MinimumSparseUpdatePairs", 100);
addParameter(parser, "MinimumClimbPairs", 100);
addParameter(parser, "MinimumDescentPairs", 100);
addParameter(parser, "Verbose", true);
parse(parser, varargin{:});

config = localBuildConfig(parser.Results);
localValidateConfig(config);

if config.Verbose
    fprintf("Stage 3B aggregate ADS-B evaluation\n");
    fprintf("Search root:\t%s\n", config.SearchRoot);
    fprintf("Stage 3A artifact:\t%s\n", config.Stage3AArtifactPath);
end

sourceFiles = localResolveSourceFiles(config);
dataset = localBuildOrLoadAggregateDataset(config, sourceFiles);
inventoryTable = localBuildInventoryTable(sourceFiles, dataset.sourceManifest);

stage3A = localLoadStage3AArtifact(config.Stage3AArtifactPath);

constvelBaseline = helperScoreConstVelBaseline( ...
    dataset.previousState, ...
    dataset.nextState, ...
    dataset.dtSeconds);
constvelPredictedNextState = constvelBaseline.predictedState;

[maneuverPairTable, labelSummary] = helperAssignADSBManeuverLabels( ...
    dataset.previousState, ...
    dataset.nextState, ...
    dataset.dtSeconds);

featureData = localBuildFrozenFeatureData( ...
    dataset, ...
    constvelPredictedNextState, ...
    stage3A.normalization);
frozenPrediction = localPredictFrozenStage3A( ...
    stage3A.net, ...
    featureData.featuresNormalized, ...
    dataset.previousState, ...
    stage3A.normalization.target);
frozenStage3APredictedNextState = frozenPrediction.predictedNextState;

constvelMetrics = helperScoreStage3APredictions( ...
    dataset.nextState, ...
    constvelPredictedNextState, ...
    dataset.metadata, ...
    maneuverPairTable, ...
    "constvel baseline");
frozenStage3AMetrics = helperScoreStage3APredictions( ...
    dataset.nextState, ...
    frozenStage3APredictedNextState, ...
    dataset.metadata, ...
    maneuverPairTable, ...
    "Frozen Stage 3A delta MLP");

pairErrorTable = localBuildPairErrorTable( ...
    dataset, ...
    maneuverPairTable, ...
    constvelPredictedNextState, ...
    frozenStage3APredictedNextState);
metrics = localBuildMetricsStruct( ...
    dataset, ...
    pairErrorTable, ...
    constvelMetrics, ...
    frozenStage3AMetrics);
metricComparisonTable = localBuildMetricComparisonTable(metrics.aggregate);
trackSummary = localBuildTrackSummary(pairErrorTable);
selectedTrack = localSelectRepresentativeTrack(dataset.metadata, trackSummary);
dataReadiness = localBuildDataReadinessAssessment( ...
    config, ...
    dataset, ...
    inventoryTable, ...
    labelSummary, ...
    trackSummary);
verificationTable = localBuildVerificationTable( ...
    dataset, ...
    frozenPrediction, ...
    metrics);

predictions = struct();
predictions.constvelPredictedNextState = constvelPredictedNextState;
predictions.frozenStage3APredictedNextState = frozenStage3APredictedNextState;
predictions.frozenStage3APredictedDeltaNormalized = frozenPrediction.predictedDeltaNormalized;
predictions.frozenStage3APredictedDelta = frozenPrediction.predictedDelta;
predictions.reconstructedNextState = frozenPrediction.reconstructedNextState;

stage3BSummary = struct();
stage3BSummary.generatedAt = datetime("now", "TimeZone", "UTC");
stage3BSummary.projectRoot = config.ProjectRoot;
stage3BSummary.outputFolder = config.OutputFolder;
stage3BSummary.aggregateDatasetPath = config.AggregateDatasetPath;
stage3BSummary.aggregateDatasetReportPath = config.AggregateDatasetReportPath;
stage3BSummary.stage3AArtifactPath = config.Stage3AArtifactPath;
stage3BSummary.artifactPath = config.ArtifactPath;
stage3BSummary.reportPath = config.ReportPath;
stage3BSummary.config = config;
stage3BSummary.configTable = localBuildConfigTable(config);
stage3BSummary.inventoryTable = inventoryTable;
stage3BSummary.sourceManifest = dataset.sourceManifest;
stage3BSummary.buildSummary = dataset.buildSummary;
stage3BSummary.stateOrder = dataset.stateOrder;
stage3BSummary.previousState = dataset.previousState;
stage3BSummary.nextState = dataset.nextState;
stage3BSummary.dtSeconds = dataset.dtSeconds;
stage3BSummary.previousCovarianceDiag = dataset.previousCovarianceDiag;
stage3BSummary.metadata = dataset.metadata;
stage3BSummary.maneuverPairTable = maneuverPairTable;
stage3BSummary.labelSummary = labelSummary;
stage3BSummary.featureData = featureData;
stage3BSummary.predictions = predictions;
stage3BSummary.metrics = metrics;
stage3BSummary.metricComparisonTable = metricComparisonTable;
stage3BSummary.pairErrorTable = pairErrorTable;
stage3BSummary.trackSummary = trackSummary;
stage3BSummary.selectedTrack = selectedTrack;
stage3BSummary.dataReadiness = dataReadiness;
stage3BSummary.verificationTable = verificationTable;
stage3BSummary.figurePaths = struct();

if config.CreatePlots
    stage3BSummary.figurePaths = helperWriteStage3BFigures( ...
        config.OutputFolder, ...
        stage3BSummary);
end

if config.CreateGlobeSnapshot
    stage3BSummary = localTryWriteGlobeSnapshot(stage3BSummary);
end

helperWriteStage3BReport(config.ReportPath, stage3BSummary);
localSaveArtifact(stage3BSummary);

if config.Verbose
    localPrintSummary(stage3BSummary);
end

end

function config = localBuildConfig(opts)
%LOCALBUILDCONFIG Normalize parser output.

config = struct();
config.ProjectRoot = string(opts.ProjectRoot);
config.SourceFiles = string(opts.SourceFiles);
config.SourceFiles = config.SourceFiles(strlength(strtrim(config.SourceFiles)) > 0);
config.SearchRoot = string(opts.SearchRoot);
config.ParserFolder = string(opts.ParserFolder);
config.OutputFolder = string(opts.OutputFolder);
config.AggregateDatasetPath = string(opts.AggregateDatasetPath);
config.AggregateDatasetReportPath = string(opts.AggregateDatasetReportPath);
config.Stage3AArtifactPath = string(opts.Stage3AArtifactPath);
config.ArtifactPath = string(opts.ArtifactPath);
config.ReportPath = string(opts.ReportPath);
config.RebuildAggregateDataset = logical(opts.RebuildAggregateDataset);
config.CreatePlots = logical(opts.CreatePlots);
config.CreateGlobeSnapshot = logical(opts.CreateGlobeSnapshot);
config.MinimumSessionsForRetraining = double(opts.MinimumSessionsForRetraining);
config.MinimumSourceFilesForRetraining = double(opts.MinimumSourceFilesForRetraining);
config.MinimumAircraftForRetraining = double(opts.MinimumAircraftForRetraining);
config.MinimumNonConstvelManeuverClasses = double(opts.MinimumNonConstvelManeuverClasses);
config.MinimumConstaccPairs = double(opts.MinimumConstaccPairs);
config.MinimumConstturnPairs = double(opts.MinimumConstturnPairs);
config.MinimumSparseUpdatePairs = double(opts.MinimumSparseUpdatePairs);
config.MinimumClimbPairs = double(opts.MinimumClimbPairs);
config.MinimumDescentPairs = double(opts.MinimumDescentPairs);
config.Verbose = logical(opts.Verbose);

end

function localValidateConfig(config)
%LOCALVALIDATECONFIG Validate Stage 3B scalar options.

if strlength(config.OutputFolder) == 0
    error("Stage3B:MissingOutputFolder", ...
        "OutputFolder must not be empty.");
end

if exist(config.Stage3AArtifactPath, "file") ~= 2
    error("Stage3B:MissingStage3AArtifact", ...
        "Stage 3A artifact was not found: %s", config.Stage3AArtifactPath);
end

numericFields = [ ...
    "MinimumSessionsForRetraining", ...
    "MinimumSourceFilesForRetraining", ...
    "MinimumAircraftForRetraining", ...
    "MinimumNonConstvelManeuverClasses", ...
    "MinimumConstaccPairs", ...
    "MinimumConstturnPairs", ...
    "MinimumSparseUpdatePairs", ...
    "MinimumClimbPairs", ...
    "MinimumDescentPairs"];

for fieldIdx = 1:numel(numericFields)
    fieldName = numericFields(fieldIdx);
    validateattributes(config.(fieldName), {'numeric'}, {'scalar', 'real', 'finite', 'nonnegative'}, ...
        mfilename, fieldName);
end

end

function sourceFiles = localResolveSourceFiles(config)
%LOCALRESOLVESOURCEFILES Discover or normalize local ADS-B source files.

sourceFiles = config.SourceFiles;

if isempty(sourceFiles)
    sourceFiles = helperDiscoverLocalADSBTruthFiles(config.SearchRoot);
end

sourceFiles = unique(sourceFiles(:), "stable");

if isempty(sourceFiles)
    error("Stage3B:NoSourceFiles", ...
        "No local ADS-B truth files were found for Stage 3B aggregation.");
end

end

function dataset = localBuildOrLoadAggregateDataset(config, sourceFiles)
%LOCALBUILDORLOADAGGREGATEDATASET Build the Stage 3B derived dataset.

if ~config.RebuildAggregateDataset && exist(config.AggregateDatasetPath, "file") == 2
    dataset = localLoadAggregateDataset(config.AggregateDatasetPath);
    return;
end

try
    dataset = buildLocalADSBStatePairDataset( ...
        "SourceFiles", sourceFiles, ...
        "SearchRoot", config.SearchRoot, ...
        "ParserFolder", config.ParserFolder, ...
        "OutputPath", config.AggregateDatasetPath, ...
        "ReportPath", config.AggregateDatasetReportPath, ...
        "SmokeTest", false, ...
        "Verbose", config.Verbose);
catch err
    error("Stage3B:AggregateDatasetBuildFailed", ...
        "Failed to build Stage 3B aggregate dataset: %s", err.message);
end

end

function dataset = localLoadAggregateDataset(datasetPath)
%LOCALLOADAGGREGATEDATASET Load a saved Stage 2B-compatible dataset.

try
    loaded = load(datasetPath, "dataset");
catch err
    error("Stage3B:AggregateDatasetLoadFailed", ...
        "Failed to load Stage 3B aggregate dataset: %s", err.message);
end

if ~isfield(loaded, "dataset")
    error("Stage3B:MissingAggregateDataset", ...
        "The aggregate dataset artifact does not contain the variable dataset.");
end

dataset = loaded.dataset;

end

function inventoryTable = localBuildInventoryTable(sourceFiles, sourceManifest)
%LOCALBUILDINVENTORYTABLE Record every discovered source file.

sourceFiles = string(sourceFiles(:));
fileExists = false(numel(sourceFiles), 1);
fileSizeBytes = NaN(numel(sourceFiles), 1);
modifiedTime = NaT(numel(sourceFiles), 1);

for fileIdx = 1:numel(sourceFiles)
    fileInfo = dir(sourceFiles(fileIdx));

    if ~isempty(fileInfo)
        fileExists(fileIdx) = true;
        fileSizeBytes(fileIdx) = fileInfo.bytes;
        modifiedTime(fileIdx) = datetime(fileInfo.datenum, "ConvertFrom", "datenum");
    end
end

manifestSourceFiles = string(sourceManifest.sourceFile);
usedInDataset = ismember(sourceFiles, manifestSourceFiles(sourceManifest.parseStatus == "parsed"));
usablePairCount = zeros(numel(sourceFiles), 1);
parseStatus = strings(numel(sourceFiles), 1);
sessionID = strings(numel(sourceFiles), 1);

for fileIdx = 1:numel(sourceFiles)
    manifestIdx = find(manifestSourceFiles == sourceFiles(fileIdx), 1, "first");

    if isempty(manifestIdx)
        parseStatus(fileIdx) = "not_in_manifest";
        continue;
    end

    parseStatus(fileIdx) = string(sourceManifest.parseStatus(manifestIdx));
    usablePairCount(fileIdx) = sourceManifest.usablePairCount(manifestIdx);
    sessionID(fileIdx) = string(sourceManifest.sessionID(manifestIdx));
end

inventoryTable = table( ...
    sourceFiles, ...
    fileExists, ...
    fileSizeBytes, ...
    modifiedTime, ...
    parseStatus, ...
    usedInDataset, ...
    usablePairCount, ...
    sessionID, ...
    'VariableNames', [ ...
        "sourceFile", ...
        "fileExists", ...
        "fileSizeBytes", ...
        "modifiedTime", ...
        "parseStatus", ...
        "usedInDataset", ...
        "usablePairCount", ...
        "sessionID"]);

end

function stage3A = localLoadStage3AArtifact(stage3AArtifactPath)
%LOCALLOADSTAGE3AARTIFACT Load the frozen Stage 3A network and transforms.

try
    loaded = load(stage3AArtifactPath, ...
        "net", ...
        "normalization", ...
        "stage3Summary");
catch err
    error("Stage3B:Stage3ALoadFailed", ...
        "Failed to load Stage 3A artifact: %s", err.message);
end

requiredFields = ["net", "normalization", "stage3Summary"];

for fieldIdx = 1:numel(requiredFields)
    fieldName = requiredFields(fieldIdx);

    if ~isfield(loaded, fieldName)
        error("Stage3B:MissingStage3AField", ...
            "The Stage 3A artifact is missing required variable: %s", fieldName);
    end
end

if isempty(loaded.net)
    error("Stage3B:EmptyStage3ANetwork", ...
        "The Stage 3A artifact does not contain a trained network.");
end

stage3A = loaded;

end

function featureData = localBuildFrozenFeatureData(dataset, constvelPredictedNextState, normalization)
%LOCALBUILDFROZENFEATUREDATA Build Stage 3A features using saved scaling.

featureSets = helperBuildStage3AFeatures( ...
    dataset.previousState, ...
    dataset.previousCovarianceDiag, ...
    dataset.dtSeconds, ...
    constvelPredictedNextState, ...
    string(dataset.metadata.split));
featureSet = featureSets.physics;
savedNormalization = normalization.physicsFeatures;
featureNames = string(featureSet.featureNames(:));
savedFeatureNames = localSavedFeatureNames(savedNormalization, featureNames);

if numel(featureNames) ~= numel(savedFeatureNames) || any(featureNames ~= savedFeatureNames)
    error("Stage3B:FeatureContractMismatch", ...
        "Stage 3B physics feature names do not match the saved Stage 3A normalization.");
end

featureMean = double(savedNormalization.featureMean);
featureStd = double(savedNormalization.featureStd);
featuresNormalized = (featureSet.features - featureMean) ./ featureStd;

featureData = struct();
featureData.featureMode = featureSet.featureMode;
featureData.featureNames = featureNames;
featureData.features = featureSet.features;
featureData.featuresNormalized = featuresNormalized;
featureData.savedNormalization = savedNormalization;
featureData.recomputedNormalization = featureSet.normalization;
featureData.excludedDefaultFeatures = featureSets.excludedDefaultFeatures;

end

function featureNames = localSavedFeatureNames(savedNormalization, fallbackFeatureNames)
%LOCALSAVEDFEATURENAMES Recover saved feature names if present.

if isfield(savedNormalization, "featureNames")
    featureNames = string(savedNormalization.featureNames(:));
else
    featureNames = string(fallbackFeatureNames(:));
end

end

function prediction = localPredictFrozenStage3A(net, featuresNormalized, previousState, targetNormalization)
%LOCALPREDICTFROZENSTAGE3A Run frozen MLP inference and reconstruct state.

predictedDeltaNormalized = minibatchpredict(net, featuresNormalized);
predictedDeltaNormalized = double(gather(extractdata(predictedDeltaNormalized)));

if size(predictedDeltaNormalized, 1) ~= size(featuresNormalized, 1) && ...
        size(predictedDeltaNormalized, 2) == size(featuresNormalized, 1)
    predictedDeltaNormalized = predictedDeltaNormalized.';
end

if size(predictedDeltaNormalized, 2) > 6
    predictedDeltaNormalized = predictedDeltaNormalized(:, 1:6);
end

if size(predictedDeltaNormalized, 1) ~= size(featuresNormalized, 1) || ...
        size(predictedDeltaNormalized, 2) ~= 6
    error("Stage3B:PredictionShapeMismatch", ...
        "Frozen Stage 3A predictions must be N-by-6 after inference.");
end

predictedDelta = predictedDeltaNormalized .* targetNormalization.targetStd + ...
    targetNormalization.targetMean;
predictedNextState = previousState + predictedDelta;

prediction = struct();
prediction.predictedDeltaNormalized = predictedDeltaNormalized;
prediction.predictedDelta = predictedDelta;
prediction.predictedNextState = predictedNextState;
prediction.reconstructedNextState = previousState + predictedDelta;

end

function metrics = localBuildMetricsStruct(dataset, pairErrorTable, constvelMetrics, frozenStage3AMetrics)
%LOCALBUILDMETRICSSTRUCT Combine aggregate and Stage 3B group metrics.

metrics = struct();
metrics.constvel = constvelMetrics;
metrics.frozenStage3A = frozenStage3AMetrics;
metrics.aggregate = [constvelMetrics.aggregate; frozenStage3AMetrics.aggregate];
metrics.bySplit = [constvelMetrics.bySplit; frozenStage3AMetrics.bySplit];
metrics.byManeuverClass = [constvelMetrics.byManeuverClass; frozenStage3AMetrics.byManeuverClass];
metrics.byVerticalStatus = [constvelMetrics.byVerticalStatus; frozenStage3AMetrics.byVerticalStatus];
metrics.byDtRegime = [constvelMetrics.byDtRegime; frozenStage3AMetrics.byDtRegime];
metrics.bySession = localScoreBothByGroup( ...
    string(dataset.metadata.sessionID), ...
    "sessionID", ...
    pairErrorTable);
metrics.bySourceFile = localScoreBothByGroup( ...
    string(dataset.metadata.sourceFile), ...
    "sourceFile", ...
    pairErrorTable);
metrics.byAircraftTrack = localScoreBothByGroup( ...
    string(dataset.metadata.sessionID) + "/" + string(dataset.metadata.hex), ...
    "aircraftTrack", ...
    pairErrorTable);

end

function metricTable = localScoreBothByGroup(groupValues, groupVariableName, pairErrorTable)
%LOCALSCOREBOTHBYGROUP Score constvel and frozen MLP for group values.

groupValues = string(groupValues(:));
groupNames = unique(groupValues, "stable");
metricTable = table();

for groupIdx = 1:numel(groupNames)
    groupName = groupNames(groupIdx);
    groupMask = groupValues == groupName;
    constvelRow = localBuildMetricRow( ...
        groupMask, ...
        groupVariableName, ...
        groupName, ...
        "constvel baseline", ...
        pairErrorTable.constvelPositionErrorMeters, ...
        pairErrorTable.constvelVelocityErrorMetersPerSecond);
    mlpRow = localBuildMetricRow( ...
        groupMask, ...
        groupVariableName, ...
        groupName, ...
        "Frozen Stage 3A delta MLP", ...
        pairErrorTable.frozenStage3APositionErrorMeters, ...
        pairErrorTable.frozenStage3AVelocityErrorMetersPerSecond);
    metricTable = [metricTable; constvelRow; mlpRow]; %#ok<AGROW>
end

end

function metricRow = localBuildMetricRow(mask, groupVariableName, groupName, methodName, positionErrorMeters, velocityErrorMetersPerSecond)
%LOCALBUILDMETRICROW Return one physical-unit metric row.

positionError = positionErrorMeters(mask);
velocityError = velocityErrorMetersPerSecond(mask);
sampleCount = numel(positionError);

metricRow = table( ...
    string(methodName), ...
    string(groupVariableName), ...
    string(groupName), ...
    sampleCount, ...
    sqrt(mean(positionError .^ 2, "omitnan")), ...
    sqrt(mean(velocityError .^ 2, "omitnan")), ...
    median(positionError, "omitnan"), ...
    median(velocityError, "omitnan"), ...
    prctile(positionError, 95), ...
    prctile(velocityError, 95), ...
    'VariableNames', [ ...
        "method", ...
        "groupVariable", ...
        "groupName", ...
        "sampleCount", ...
        "positionRMSEMeters", ...
        "velocityRMSEMetersPerSecond", ...
        "positionMedianErrorMeters", ...
        "velocityMedianErrorMetersPerSecond", ...
        "positionP95ErrorMeters", ...
        "velocityP95ErrorMetersPerSecond"]);

end

function pairErrorTable = localBuildPairErrorTable(dataset, maneuverPairTable, constvelPredictedNextState, frozenPredictedNextState)
%LOCALBUILDPAIRERRORTABLE Store row-wise scoring diagnostics.

positionColumns = [1, 3, 5];
velocityColumns = [2, 4, 6];
pairCount = size(dataset.nextState, 1);

constvelPositionError = constvelPredictedNextState(:, positionColumns) - dataset.nextState(:, positionColumns);
constvelVelocityError = constvelPredictedNextState(:, velocityColumns) - dataset.nextState(:, velocityColumns);
frozenPositionError = frozenPredictedNextState(:, positionColumns) - dataset.nextState(:, positionColumns);
frozenVelocityError = frozenPredictedNextState(:, velocityColumns) - dataset.nextState(:, velocityColumns);

pairErrorTable = table( ...
    (1:pairCount).', ...
    dataset.metadata.sessionID, ...
    dataset.metadata.sourceFile, ...
    dataset.metadata.hex, ...
    dataset.metadata.callsign, ...
    dataset.metadata.split, ...
    dataset.metadata.timeUtcK, ...
    dataset.metadata.timeUtcNext, ...
    dataset.dtSeconds, ...
    maneuverPairTable.maneuverClass, ...
    maneuverPairTable.verticalStatus, ...
    maneuverPairTable.dtRegime, ...
    vecnorm(constvelPositionError, 2, 2), ...
    vecnorm(constvelVelocityError, 2, 2), ...
    vecnorm(frozenPositionError, 2, 2), ...
    vecnorm(frozenVelocityError, 2, 2), ...
    'VariableNames', [ ...
        "pairIndex", ...
        "sessionID", ...
        "sourceFile", ...
        "hex", ...
        "callsign", ...
        "split", ...
        "timeUtcK", ...
        "timeUtcNext", ...
        "dtSeconds", ...
        "maneuverClass", ...
        "verticalStatus", ...
        "dtRegime", ...
        "constvelPositionErrorMeters", ...
        "constvelVelocityErrorMetersPerSecond", ...
        "frozenStage3APositionErrorMeters", ...
        "frozenStage3AVelocityErrorMetersPerSecond"]);

end

function metricComparisonTable = localBuildMetricComparisonTable(aggregate)
%LOCALBUILDMETRICCOMPARISONTABLE Add interpretation to aggregate metrics.

interpretation = strings(height(aggregate), 1);

for rowIdx = 1:height(aggregate)
    methodName = string(aggregate.method(rowIdx));

    if methodName == "constvel baseline"
        interpretation(rowIdx) = "Native Sensor Fusion constant-velocity prediction on the exact Stage 3B samples.";
    else
        interpretation(rowIdx) = "Frozen Stage 3A delta-target MLP reconstructed as previousState + predictedDelta.";
    end
end

metricComparisonTable = table( ...
    aggregate.method, ...
    aggregate.sampleCount, ...
    aggregate.positionRMSEMeters, ...
    aggregate.velocityRMSEMetersPerSecond, ...
    aggregate.positionMedianErrorMeters, ...
    aggregate.positionP95ErrorMeters, ...
    interpretation, ...
    'VariableNames', [ ...
        "method", ...
        "sampleCount", ...
        "positionRMSEMeters", ...
        "velocityRMSEMetersPerSecond", ...
        "positionMedianErrorMeters", ...
        "positionP95ErrorMeters", ...
        "interpretation"]);

end

function trackSummary = localBuildTrackSummary(pairErrorTable)
%LOCALBUILDTRACKSUMMARY Summarize coverage and error by aircraft track.

trackInput = table( ...
    pairErrorTable.sessionID, ...
    pairErrorTable.hex, ...
    pairErrorTable.callsign, ...
    pairErrorTable.dtSeconds, ...
    double(string(pairErrorTable.maneuverClass) == "constvel_like"), ...
    double(string(pairErrorTable.maneuverClass) == "constacc_like"), ...
    double(string(pairErrorTable.maneuverClass) == "constturn_like"), ...
    double(string(pairErrorTable.maneuverClass) == "mixed_or_sparse"), ...
    double(string(pairErrorTable.verticalStatus) == "climb"), ...
    double(string(pairErrorTable.verticalStatus) == "descent"), ...
    double(string(pairErrorTable.dtRegime) == "sparse_update"), ...
    pairErrorTable.constvelPositionErrorMeters, ...
    pairErrorTable.frozenStage3APositionErrorMeters, ...
    'VariableNames', [ ...
        "sessionID", ...
        "hex", ...
        "callsign", ...
        "dtSeconds", ...
        "constvelLikePairCount", ...
        "constaccLikePairCount", ...
        "constturnLikePairCount", ...
        "mixedOrSparsePairCount", ...
        "climbPairCount", ...
        "descentPairCount", ...
        "sparseUpdatePairCount", ...
        "constvelPositionErrorMeters", ...
        "frozenStage3APositionErrorMeters"]);

[groupID, sessionID, hex, callsign] = findgroups( ...
    trackInput.sessionID, ...
    trackInput.hex, ...
    trackInput.callsign);

pairCount = splitapply(@numel, trackInput.dtSeconds, groupID);
medianDtSeconds = splitapply(@median, trackInput.dtSeconds, groupID);
constvelLikePairCount = splitapply(@sum, trackInput.constvelLikePairCount, groupID);
constaccLikePairCount = splitapply(@sum, trackInput.constaccLikePairCount, groupID);
constturnLikePairCount = splitapply(@sum, trackInput.constturnLikePairCount, groupID);
mixedOrSparsePairCount = splitapply(@sum, trackInput.mixedOrSparsePairCount, groupID);
climbPairCount = splitapply(@sum, trackInput.climbPairCount, groupID);
descentPairCount = splitapply(@sum, trackInput.descentPairCount, groupID);
sparseUpdatePairCount = splitapply(@sum, trackInput.sparseUpdatePairCount, groupID);
constvelPositionRMSEMeters = splitapply(@localRmse, trackInput.constvelPositionErrorMeters, groupID);
frozenStage3APositionRMSEMeters = splitapply(@localRmse, trackInput.frozenStage3APositionErrorMeters, groupID);

trackSummary = table( ...
    sessionID, ...
    hex, ...
    callsign, ...
    pairCount, ...
    medianDtSeconds, ...
    constvelLikePairCount, ...
    constaccLikePairCount, ...
    constturnLikePairCount, ...
    mixedOrSparsePairCount, ...
    climbPairCount, ...
    descentPairCount, ...
    sparseUpdatePairCount, ...
    constvelPositionRMSEMeters, ...
    frozenStage3APositionRMSEMeters, ...
    'VariableNames', [ ...
        "sessionID", ...
        "hex", ...
        "callsign", ...
        "pairCount", ...
        "medianDtSeconds", ...
        "constvelLikePairCount", ...
        "constaccLikePairCount", ...
        "constturnLikePairCount", ...
        "mixedOrSparsePairCount", ...
        "climbPairCount", ...
        "descentPairCount", ...
        "sparseUpdatePairCount", ...
        "constvelPositionRMSEMeters", ...
        "frozenStage3APositionRMSEMeters"]);

trackSummary = sortrows(trackSummary, "pairCount", "descend");

end

function value = localRmse(values)
%LOCALRMSE Compute scalar RMSE.

value = sqrt(mean(values .^ 2, "omitnan"));

end

function selectedTrack = localSelectRepresentativeTrack(metadata, trackSummary)
%LOCALSELECTREPRESENTATIVETRACK Pick one readable trajectory for plots.

if isempty(trackSummary) || height(trackSummary) == 0
    rows = (1:min(80, height(metadata))).';
    selectedTrack = struct("sessionID", "", "hex", "", "rows", rows);
    return;
end

constvelShare = trackSummary.constvelLikePairCount ./ trackSummary.pairCount;
candidateMask = trackSummary.pairCount >= 40 & constvelShare >= 0.70;

if any(candidateMask)
    candidateTable = trackSummary(candidateMask, :);
else
    candidateTable = trackSummary;
end

[~, bestIdx] = min(candidateTable.constvelPositionRMSEMeters);
sessionID = string(candidateTable.sessionID(bestIdx));
trackHex = string(candidateTable.hex(bestIdx));
rows = find(string(metadata.sessionID) == sessionID & string(metadata.hex) == trackHex);

if isempty(rows)
    rows = (1:min(80, height(metadata))).';
else
    [~, sortIdx] = sort(metadata.timeUtcNext(rows));
    rows = rows(sortIdx);
    rows = rows(1:min(80, numel(rows)));
end

selectedTrack = struct();
selectedTrack.sessionID = sessionID;
selectedTrack.hex = trackHex;
selectedTrack.rows = rows(:);

end

function dataReadiness = localBuildDataReadinessAssessment(config, dataset, inventoryTable, labelSummary, trackSummary)
%LOCALBUILDDATAREADINESSASSESSMENT Gate future training on data diversity.

sessionCount = numel(unique(string(dataset.metadata.sessionID)));
sourceFileCount = sum(inventoryTable.usedInDataset);
aircraftCount = height(trackSummary);
constaccCount = localLookupCount(labelSummary.countsByManeuverClass, "maneuverClass", "constacc_like");
constturnCount = localLookupCount(labelSummary.countsByManeuverClass, "maneuverClass", "constturn_like");
sparseUpdateCount = localLookupCount(labelSummary.countsByDtRegime, "dtRegime", "sparse_update");
climbCount = localLookupCount(labelSummary.countsByVerticalStatus, "verticalStatus", "climb");
descentCount = localLookupCount(labelSummary.countsByVerticalStatus, "verticalStatus", "descent");
nonConstvelClassCount = localCountNonConstvelManeuverClasses(labelSummary.countsByManeuverClass);

gateName = [ ...
    "distinct ADS-B sessions"; ...
    "local truth files used"; ...
    "distinct aircraft tracks"; ...
    "non-constvel maneuver classes"; ...
    "constacc-like pairs"; ...
    "constturn-like pairs"; ...
    "sparse-update pairs"; ...
    "climb pairs"; ...
    "descent pairs"];
observedValue = [ ...
    sessionCount; ...
    sourceFileCount; ...
    aircraftCount; ...
    nonConstvelClassCount; ...
    constaccCount; ...
    constturnCount; ...
    sparseUpdateCount; ...
    climbCount; ...
    descentCount];
requiredValue = [ ...
    config.MinimumSessionsForRetraining; ...
    config.MinimumSourceFilesForRetraining; ...
    config.MinimumAircraftForRetraining; ...
    config.MinimumNonConstvelManeuverClasses; ...
    config.MinimumConstaccPairs; ...
    config.MinimumConstturnPairs; ...
    config.MinimumSparseUpdatePairs; ...
    config.MinimumClimbPairs; ...
    config.MinimumDescentPairs];
passed = observedValue >= requiredValue;
details = localBuildGateDetails(observedValue, requiredValue, passed);

gateTable = table( ...
    gateName, ...
    observedValue, ...
    requiredValue, ...
    passed, ...
    details, ...
    'VariableNames', [ ...
        "gate", ...
        "observedValue", ...
        "requiredValue", ...
        "passed", ...
        "details"]);

isReadyForRetraining = all(passed);
recommendation = localBuildReadinessRecommendation( ...
    isReadyForRetraining, ...
    sessionCount, ...
    sourceFileCount, ...
    aircraftCount, ...
    constturnCount, ...
    sparseUpdateCount);

dataReadiness = struct();
dataReadiness.isReadyForRetraining = isReadyForRetraining;
dataReadiness.gateTable = gateTable;
dataReadiness.recommendation = recommendation;
dataReadiness.sessionCount = sessionCount;
dataReadiness.sourceFileCount = sourceFileCount;
dataReadiness.aircraftCount = aircraftCount;
dataReadiness.nonConstvelManeuverClassCount = nonConstvelClassCount;
dataReadiness.constaccLikePairCount = constaccCount;
dataReadiness.constturnLikePairCount = constturnCount;
dataReadiness.sparseUpdatePairCount = sparseUpdateCount;
dataReadiness.climbPairCount = climbCount;
dataReadiness.descentPairCount = descentCount;

end

function details = localBuildGateDetails(observedValue, requiredValue, passed)
%LOCALBUILDGATEDETAILS Format readiness gate table details.

details = strings(numel(observedValue), 1);

for rowIdx = 1:numel(observedValue)
    if passed(rowIdx)
        details(rowIdx) = sprintf("Observed %d; requirement met.", observedValue(rowIdx));
    else
        details(rowIdx) = sprintf( ...
            "Observed %d; need at least %d before retraining.", ...
            observedValue(rowIdx), ...
            requiredValue(rowIdx));
    end
end

end

function recommendation = localBuildReadinessRecommendation(isReadyForRetraining, sessionCount, sourceFileCount, aircraftCount, constturnCount, sparseUpdateCount)
%LOCALBUILDREADINESSRECOMMENDATION Convert gate result into a direct answer.

if isReadyForRetraining
    recommendation = "Ready for a future gated retraining experiment. Keep Stage 3A frozen for this report and start retraining as a new stage.";
    return;
end

if sessionCount < 3 || sourceFileCount < 3
    recommendation = sprintf( ...
        "Not ready for retraining. Stage 3B found %d ADS-B session(s) and %d usable truth file(s); collect more local SBS-1 ADS-B sessions first.", ...
        sessionCount, ...
        sourceFileCount);
    return;
end

if aircraftCount < 20
    recommendation = sprintf( ...
        "Not ready for retraining. Only %d aircraft tracks are present after filtering; add more local ADS-B tracks first.", ...
        aircraftCount);
    return;
end

if constturnCount < 100 || sparseUpdateCount < 100
    recommendation = sprintf( ...
        "Not ready for retraining. Maneuver coverage is weak, with %d constturn-like pairs and %d sparse-update pairs.", ...
        constturnCount, ...
        sparseUpdateCount);
    return;
end

recommendation = "Not ready for retraining. At least one configured Stage 3B diversity gate failed.";

end

function countValue = localLookupCount(countTable, variableName, categoryName)
%LOCALLOOKUPCOUNT Return a category count from a count table.

categoryValues = string(countTable.(variableName));
categoryMask = categoryValues == categoryName;

if any(categoryMask)
    countValue = countTable.pairCount(find(categoryMask, 1, "first"));
else
    countValue = 0;
end

end

function nonConstvelClassCount = localCountNonConstvelManeuverClasses(countTable)
%LOCALCOUNTNONCONSTVELMANEUVERCLASSES Count observed non-constvel labels.

classNames = string(countTable.maneuverClass);
classCounts = countTable.pairCount;
nonConstvelMask = classNames ~= "constvel_like";
nonConstvelClassCount = sum(nonConstvelMask & classCounts > 0);

end

function verificationTable = localBuildVerificationTable(dataset, frozenPrediction, metrics)
%LOCALBUILDVERIFICATIONTABLE Verify frozen-evaluation invariants.

reconstructionMaxAbsError = max( ...
    abs(frozenPrediction.reconstructedNextState - frozenPrediction.predictedNextState), ...
    [], ...
    "all");
sameSampleCount = all(metrics.aggregate.sampleCount == size(dataset.nextState, 1));
finitePrediction = all(isfinite(frozenPrediction.predictedNextState), "all");
sameRowsScored = metrics.constvel.aggregate.sampleCount(1) == ...
    metrics.frozenStage3A.aggregate.sampleCount(1);

checkName = [ ...
    "frozen delta reconstruction"; ...
    "same sample count for constvel and MLP"; ...
    "finite frozen MLP predictions"; ...
    "all aggregate metrics use dataset row count"];
passed = [ ...
    reconstructionMaxAbsError <= 1e-10; ...
    sameRowsScored; ...
    finitePrediction; ...
    sameSampleCount];
details = [ ...
    sprintf("max abs reconstruction error = %.3g", reconstructionMaxAbsError); ...
    sprintf("constvel rows = %d, MLP rows = %d", metrics.constvel.aggregate.sampleCount(1), metrics.frozenStage3A.aggregate.sampleCount(1)); ...
    sprintf("finite prediction rows = %d", sum(all(isfinite(frozenPrediction.predictedNextState), 2))); ...
    sprintf("dataset rows = %d", size(dataset.nextState, 1))];

verificationTable = table( ...
    checkName, ...
    passed, ...
    details, ...
    'VariableNames', [ ...
        "check", ...
        "passed", ...
        "details"]);

end

function configTable = localBuildConfigTable(config)
%LOCALBUILDCONFIGTABLE Convert config struct to a report table.

fieldNames = string(fieldnames(config));
values = strings(numel(fieldNames), 1);

for fieldIdx = 1:numel(fieldNames)
    fieldName = fieldNames(fieldIdx);
    values(fieldIdx) = localConfigValueToString(config.(fieldName));
end

configTable = table(fieldNames, values, ...
    'VariableNames', ["setting", "value"]);

end

function valueText = localConfigValueToString(value)
%LOCALCONFIGVALUETOSTRING Format config values.

if isstring(value)
    valueText = strjoin(value, ", ");
elseif ischar(value)
    valueText = string(value);
elseif isnumeric(value) || islogical(value)
    valueText = string(mat2str(value));
else
    valueText = string(value);
end

end

function stage3BSummary = localTryWriteGlobeSnapshot(stage3BSummary)
%LOCALTRYWRITEGLOBESNAPSHOT Optionally save a trackingGlobeViewer snapshot.

try
    globeOutput = helperOpenStage3BGlobe( ...
        stage3BSummary, ...
        "TrackHex", stage3BSummary.selectedTrack.hex, ...
        "MaxPairs", 80);
    snapshotImage = snapshot(globeOutput.viewer);
    globeFigure = figure("Name", "Stage 3B trackingGlobeViewer Snapshot", "Visible", "off");
    cleanup = onCleanup(@() close(globeFigure));
    imagesc(snapshotImage);
    axis image;
    xlabel("Snapshot image column");
    ylabel("Snapshot image row");
    title("Stage 3B trackingGlobeViewer Snapshot");
    globePath = fullfile(stage3BSummary.outputFolder, "stage3B_tracking_globe_snapshot.png");
    exportgraphics(globeFigure, globePath, "Resolution", 150);
    stage3BSummary.figurePaths.trackingGlobeSnapshot = globePath;
catch err
    stage3BSummary.figurePaths.trackingGlobeSnapshot = "not generated: " + string(err.message);
end

end

function localSaveArtifact(stage3BSummary)
%LOCALSAVEARTIFACT Save Stage 3B MATLAB artifacts.

predictions = stage3BSummary.predictions;
metrics = stage3BSummary.metrics;
dataReadiness = stage3BSummary.dataReadiness;
inventoryTable = stage3BSummary.inventoryTable;
metricComparisonTable = stage3BSummary.metricComparisonTable;
pairErrorTable = stage3BSummary.pairErrorTable;
trackSummary = stage3BSummary.trackSummary;
featureData = stage3BSummary.featureData;
constvelPredictedNextState = predictions.constvelPredictedNextState;
frozenStage3APredictedNextState = predictions.frozenStage3APredictedNextState;
reconstructedNextState = predictions.reconstructedNextState;

try
    outputFolder = fileparts(stage3BSummary.artifactPath);

    if strlength(outputFolder) > 0 && ~isfolder(outputFolder)
        mkdir(outputFolder);
    end

    save(stage3BSummary.artifactPath, ...
        "stage3BSummary", ...
        "predictions", ...
        "metrics", ...
        "dataReadiness", ...
        "inventoryTable", ...
        "metricComparisonTable", ...
        "pairErrorTable", ...
        "trackSummary", ...
        "featureData", ...
        "constvelPredictedNextState", ...
        "frozenStage3APredictedNextState", ...
        "reconstructedNextState", ...
        "-v7.3");
catch err
    error("Stage3B:ArtifactSaveFailed", ...
        "Failed to save Stage 3B evaluation artifact: %s", err.message);
end

end

function localPrintSummary(stage3BSummary)
%LOCALPRINTSUMMARY Print concise Stage 3B results.

aggregate = stage3BSummary.metricComparisonTable;
constvelRow = aggregate.method == "constvel baseline";
mlpRow = aggregate.method == "Frozen Stage 3A delta MLP";

fprintf("Stage 3B aggregate evaluation complete\n");
fprintf("Pairs evaluated:\t%d\n", size(stage3BSummary.nextState, 1));
fprintf("Sessions:\t%d\n", stage3BSummary.dataReadiness.sessionCount);
fprintf("Source files:\t%d\n", stage3BSummary.dataReadiness.sourceFileCount);
fprintf("Aircraft tracks:\t%d\n", stage3BSummary.dataReadiness.aircraftCount);
fprintf("Constvel position RMSE [m]:\t%.3f\n", aggregate.positionRMSEMeters(constvelRow));
fprintf("Frozen Stage 3A position RMSE [m]:\t%.3f\n", aggregate.positionRMSEMeters(mlpRow));
fprintf("Ready for retraining:\t%d\n", stage3BSummary.dataReadiness.isReadyForRetraining);
fprintf("Report written:\t%s\n", stage3BSummary.reportPath);
fprintf("Artifact written:\t%s\n", stage3BSummary.artifactPath);

end
