function summary = runStage4CRetrainExpandedADSBMLP(varargin)
%RUNSTAGE4CRETRAINEXPANDEDADSBMLP Train two Expanded-3Day mean MLPs.
% The scratch model tests what the unchanged 20-64-64-6 architecture can
% learn from the expanded data. The warm control starts from Stage 3A
% weights after normalization rebasing. Both remain memoryless and predict
% only the six-component state delta with normalized MSE.

projectRoot = string(fileparts(mfilename("fullpath")));
parser = inputParser;
parser.FunctionName = mfilename;
addParameter(parser, "ProjectRoot", projectRoot);
addParameter(parser, "DatasetPath", "");
addParameter(parser, "DatasetVariantManifestPath", "");
addParameter(parser, "SplitManifestPath", "");
addParameter(parser, "Stage3AArtifactPath", "");
addParameter(parser, "OutputFolder", "");
addParameter(parser, "ScratchArtifactPath", "");
addParameter(parser, "WarmArtifactPath", "");
addParameter(parser, "ComparisonArtifactPath", "");
addParameter(parser, "ReportPath", "");
addParameter(parser, "MetricTablePath", "");
addParameter(parser, "Seed", 123);
addParameter(parser, "HiddenUnits", 64);
addParameter(parser, "MiniBatchSize", 1024);
addParameter(parser, "MaxEpochs", 50);
addParameter(parser, "InitialLearnRate", 1e-3);
addParameter(parser, "L2Regularization", 1e-4);
addParameter(parser, "ValidationPatience", 8);
addParameter(parser, "TinySampleCount", 128);
addParameter(parser, "TinyEpochs", 100);
addParameter(parser, "PredictionMiniBatchSize", 8192);
addParameter(parser, "ExecutionEnvironment", "cpu");
addParameter(parser, "VerifySourceHashes", true);
addParameter(parser, "CreatePlots", true);
addParameter(parser, "PreflightOnly", false);
addParameter(parser, "Verbose", true);
parse(parser, varargin{:});

config = localBuildConfig(parser.Results);
localValidateConfig(config);

if config.Verbose
    fprintf("Stage 4C-Retrain Expanded-3Day exploratory mean MLP\n");
    fprintf("Dataset:\t%s\n", config.DatasetPath);
    fprintf("Split manifest:\t%s\n", config.SplitManifestPath);
end

stage3AHashBefore = helperComputeFileSHA256(config.Stage3AArtifactPath);
dataset = localLoadDataset(config.DatasetPath);
stage3A = localLoadStage3A(config.Stage3AArtifactPath);
datasetProvenance = localAuditDatasetProvenance(dataset, config);
[split, splitAudit, splitProvenance] = localLoadAndAuditSplit( ...
    dataset.metadata, ...
    config);

constvelPredictedState = localResolveConstvelPrediction(dataset);
constvelAudit = localAuditConstvelPrediction( ...
    dataset.previousState, ...
    dataset.dtSeconds, ...
    constvelPredictedState);
featureData = helperBuildStage4CFeatures( ...
    dataset.previousState, ...
    dataset.previousCovarianceDiag, ...
    dataset.dtSeconds, ...
    constvelPredictedState);
architectureAudit = localAuditArchitecture( ...
    stage3A.net, ...
    featureData.featureNames, ...
    config.HiddenUnits);

targetDelta = dataset.nextState - dataset.previousState;
normalization = localComputeNormalization( ...
    featureData.features, ...
    featureData.featureNames, ...
    targetDelta, ...
    split);
featuresNormalized = ...
    (featureData.features - normalization.features.featureMean) ./ ...
    normalization.features.featureStd;
targetNormalized = ...
    (targetDelta - normalization.target.targetMean) ./ ...
    normalization.target.targetStd;
localValidateNormalizedData(featuresNormalized, targetNormalized);

trainMask = split == "train";
validationMask = split == "validation";
rebaseRows = localSelectRebaseRows(find(trainMask), 512);
[warmInitialNet, warmStartRebaseAudit] = ...
    helperRebaseStage3ANetworkNormalization( ...
    stage3A.net, ...
    stage3A.normalization.physicsFeatures, ...
    stage3A.normalization.target, ...
    normalization.features, ...
    normalization.target, ...
    featureData.features(rebaseRows, :), ...
    dataset.previousState(rebaseRows, :));

nativeFunctionAudit = localBuildNativeFunctionAudit(constvelAudit);
stage3AIntegrity = struct();
stage3AIntegrity.path = config.Stage3AArtifactPath;
stage3AIntegrity.beforeSHA256 = stage3AHashBefore;
stage3AIntegrity.afterSHA256 = stage3AHashBefore;
stage3AIntegrity.unchanged = true;

summary = localBuildPreflightSummary( ...
    config, ...
    dataset, ...
    datasetProvenance, ...
    splitAudit, ...
    splitProvenance, ...
    normalization, ...
    featureData, ...
    architectureAudit, ...
    warmStartRebaseAudit, ...
    nativeFunctionAudit, ...
    stage3AIntegrity);

if config.PreflightOnly
    if config.Verbose
        fprintf("Preflight complete; neural training was not run.\n");
    end

    return;
end

% The tiny check is deliberately completed before either full-data run.
% Its single batch should become easier to fit, proving that data flow,
% target orientation, gradients, and the six-output reconstruction agree.
tinyOverfit = localRunTinyOverfit( ...
    single(featuresNormalized(trainMask, :)), ...
    single(targetNormalized(trainMask, :)), ...
    config);

if ~tinyOverfit.passed
    error("Stage4C:TinyOverfitFailed", ...
        "The 128-row tiny-overfit check did not produce finite decreasing loss.");
end

XTrain = single(featuresNormalized(trainMask, :));
YTrain = single(targetNormalized(trainMask, :));
XValidation = single(featuresNormalized(validationMask, :));
YValidation = single(targetNormalized(validationMask, :));

if config.Verbose
    fprintf("Training expanded_scratch_mean_v1...\n");
end

scratchRun = localTrainFullNetwork( ...
    [], ...
    XTrain, ...
    YTrain, ...
    XValidation, ...
    YValidation, ...
    config, ...
    "expanded_scratch_mean_v1");

if config.Verbose
    fprintf("Training expanded_warm_mean_v1...\n");
end

warmRun = localTrainFullNetwork( ...
    warmInitialNet, ...
    XTrain, ...
    YTrain, ...
    XValidation, ...
    YValidation, ...
    config, ...
    "expanded_warm_mean_v1");

holdoutMask = split == "validation" | split == "test";
holdoutPreviousState = dataset.previousState(holdoutMask, :);
holdoutNextState = dataset.nextState(holdoutMask, :);
holdoutMetadata = dataset.metadata(holdoutMask, :);
holdoutLabels = helperAssignADSBManeuverLabels( ...
    holdoutPreviousState, ...
    holdoutNextState, ...
    dataset.dtSeconds(holdoutMask));
holdoutSplit = split(holdoutMask);

legacyPredictedState = localPredictPhysicalState( ...
    stage3A.net, ...
    featureData.features(holdoutMask, :), ...
    holdoutPreviousState, ...
    stage3A.normalization.physicsFeatures, ...
    stage3A.normalization.target, ...
    config.PredictionMiniBatchSize);
scratchPredictedState = localPredictPhysicalState( ...
    scratchRun.net, ...
    featureData.features(holdoutMask, :), ...
    holdoutPreviousState, ...
    normalization.features, ...
    normalization.target, ...
    config.PredictionMiniBatchSize);
warmPredictedState = localPredictPhysicalState( ...
    warmRun.net, ...
    featureData.features(holdoutMask, :), ...
    holdoutPreviousState, ...
    normalization.features, ...
    normalization.target, ...
    config.PredictionMiniBatchSize);

modelPredictions = localPackModelPredictions( ...
    constvelPredictedState(holdoutMask, :), ...
    legacyPredictedState, ...
    scratchPredictedState, ...
    warmPredictedState);
metrics = helperScoreStage4CMeanModels( ...
    holdoutNextState, ...
    modelPredictions, ...
    holdoutMetadata, ...
    holdoutLabels, ...
    holdoutSplit);
candidateComparison = localBuildCandidateComparison(metrics.table);
exploratoryVerdict = localBuildExploratoryVerdict(candidateComparison);

if ~isfolder(config.OutputFolder)
    mkdir(config.OutputFolder);
end

writetable(metrics.table, config.MetricTablePath);
figurePaths = struct();

if config.CreatePlots
    figurePaths = helperWriteStage4CRetrainFigures( ...
        config.OutputFolder, ...
        scratchRun.info, ...
        warmRun.info, ...
        holdoutNextState, ...
        modelPredictions, ...
        holdoutMetadata, ...
        holdoutLabels, ...
        holdoutSplit);
end

stage3AHashAfter = helperComputeFileSHA256(config.Stage3AArtifactPath);
stage3AIntegrity.afterSHA256 = stage3AHashAfter;
stage3AIntegrity.unchanged = strcmpi(stage3AHashBefore, stage3AHashAfter);

if ~stage3AIntegrity.unchanged
    error("Stage4C:Stage3AArtifactChanged", ...
        "The frozen Stage 3A artifact hash changed during Stage 4C.");
end

summary.generatedAt = datetime("now", "TimeZone", "UTC");
summary.completed = true;
summary.tinyOverfit = tinyOverfit;
summary.warmStartRebaseAudit = warmStartRebaseAudit;
summary.scratchTraining = localCompactTrainingRun(scratchRun);
summary.warmTraining = localCompactTrainingRun(warmRun);
summary.trainingOptions = localTrainingOptionRecord(config, sum(trainMask));
summary.metrics = metrics;
summary.candidateComparison = candidateComparison;
summary.exploratoryVerdict = exploratoryVerdict;
summary.stage3AIntegrity = stage3AIntegrity;
summary.figurePaths = figurePaths;
summary.scratchArtifactPath = config.ScratchArtifactPath;
summary.warmArtifactPath = config.WarmArtifactPath;
summary.comparisonArtifactPath = config.ComparisonArtifactPath;
summary.reportPath = config.ReportPath;
summary.metricTablePath = config.MetricTablePath;

localSaveModelArtifact( ...
    config.ScratchArtifactPath, ...
    "expanded_scratch_mean_v1", ...
    scratchRun, ...
    "fresh_glorot_initialization", ...
    struct(), ...
    normalization, ...
    summary);
localSaveModelArtifact( ...
    config.WarmArtifactPath, ...
    "expanded_warm_mean_v1", ...
    warmRun, ...
    "legacy_stage3a_v1_rebased_to_expanded_normalization", ...
    warmStartRebaseAudit, ...
    normalization, ...
    summary);
localSaveComparisonArtifact(config.ComparisonArtifactPath, summary);
helperWriteStage4CRetrainReport(config.ReportPath, summary);

if config.Verbose
    localPrintCompletion(summary);
end

end

function config = localBuildConfig(opts)
%LOCALBUILDCONFIG Resolve all dependent paths from one project root.

config = struct();
config.ProjectRoot = localCanonicalPath(localTextScalar( ...
    opts.ProjectRoot, "ProjectRoot", false));
config.DatasetPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.DatasetPath, ...
    fullfile( ...
    "artifacts", ...
    "stage4BPostCampaign", ...
    "expanded_post3day_v2", ...
    "stage3CArchiveStatePairDataset.mat"), ...
    "DatasetPath");
config.DatasetVariantManifestPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.DatasetVariantManifestPath, ...
    fullfile("adsb_archive", "datasetVersions", "adsbDatasetVariants.csv"), ...
    "DatasetVariantManifestPath");
config.SplitManifestPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.SplitManifestPath, ...
    fullfile( ...
    "adsb_archive", ...
    "datasetVersions", ...
    "expandedPost3DayICAODisjointSplit_v1.csv"), ...
    "SplitManifestPath");
config.Stage3AArtifactPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.Stage3AArtifactPath, ...
    fullfile("artifacts", "stage3", "localADSBMLPStage3Training.mat"), ...
    "Stage3AArtifactPath");
config.OutputFolder = localResolvePath( ...
    config.ProjectRoot, ...
    opts.OutputFolder, ...
    fullfile("artifacts", "stage4CRetrain"), ...
    "OutputFolder");
config.ScratchArtifactPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.ScratchArtifactPath, ...
    fullfile( ...
    config.OutputFolder, ...
    "expandedPost3DayScratchMeanMLP_v1.mat"), ...
    "ScratchArtifactPath");
config.WarmArtifactPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.WarmArtifactPath, ...
    fullfile( ...
    config.OutputFolder, ...
    "expandedPost3DayWarmStartMeanMLP_v1.mat"), ...
    "WarmArtifactPath");
config.ComparisonArtifactPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.ComparisonArtifactPath, ...
    fullfile( ...
    config.OutputFolder, ...
    "expandedPost3DayMeanMLPComparison_v1.mat"), ...
    "ComparisonArtifactPath");
config.ReportPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.ReportPath, ...
    fullfile(config.OutputFolder, "stage4CRetrainExpandedADSBMLPReport.md"), ...
    "ReportPath");
config.MetricTablePath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.MetricTablePath, ...
    fullfile(config.OutputFolder, "stage4CRetrainMetricComparison.csv"), ...
    "MetricTablePath");
config.Seed = double(opts.Seed);
config.HiddenUnits = double(opts.HiddenUnits);
config.MiniBatchSize = double(opts.MiniBatchSize);
config.MaxEpochs = double(opts.MaxEpochs);
config.InitialLearnRate = double(opts.InitialLearnRate);
config.L2Regularization = double(opts.L2Regularization);
config.ValidationPatience = double(opts.ValidationPatience);
config.TinySampleCount = double(opts.TinySampleCount);
config.TinyEpochs = double(opts.TinyEpochs);
config.PredictionMiniBatchSize = double(opts.PredictionMiniBatchSize);
config.ExecutionEnvironment = lower(string(opts.ExecutionEnvironment));
config.VerifySourceHashes = localLogicalScalar( ...
    opts.VerifySourceHashes, "VerifySourceHashes");
config.CreatePlots = localLogicalScalar(opts.CreatePlots, "CreatePlots");
config.PreflightOnly = localLogicalScalar(opts.PreflightOnly, "PreflightOnly");
config.Verbose = localLogicalScalar(opts.Verbose, "Verbose");
config.DatasetVariantID = "expanded_post3day_v2";
config.ExpectedPairCounts = [277959, 86420, 93524];
config.SplitNames = ["train", "validation", "test"];

end

function localValidateConfig(config)
%LOCALVALIDATECONFIG Reject invalid settings and unsafe output collisions.

requiredFiles = [ ...
    config.DatasetPath, ...
    config.DatasetVariantManifestPath, ...
    config.SplitManifestPath, ...
    config.Stage3AArtifactPath];

for pathIdx = 1:numel(requiredFiles)
    if exist(requiredFiles(pathIdx), "file") ~= 2
        error("Stage4C:MissingInputFile", ...
            "Required input file was not found: %s", requiredFiles(pathIdx));
    end
end

validateattributes(config.Seed, ...
    {'numeric'}, {'scalar', 'integer', 'finite'}, mfilename, "Seed");
validateattributes(config.HiddenUnits, ...
    {'numeric'}, {'scalar', 'integer', 'positive'}, mfilename, "HiddenUnits");
validateattributes(config.MiniBatchSize, ...
    {'numeric'}, {'scalar', 'integer', 'positive'}, mfilename, "MiniBatchSize");
validateattributes(config.MaxEpochs, ...
    {'numeric'}, {'scalar', 'integer', 'positive'}, mfilename, "MaxEpochs");
validateattributes(config.InitialLearnRate, ...
    {'numeric'}, {'scalar', 'real', 'finite', 'positive'}, ...
    mfilename, "InitialLearnRate");
validateattributes(config.L2Regularization, ...
    {'numeric'}, {'scalar', 'real', 'finite', 'nonnegative'}, ...
    mfilename, "L2Regularization");
validateattributes(config.ValidationPatience, ...
    {'numeric'}, {'scalar', 'integer', 'positive'}, ...
    mfilename, "ValidationPatience");
validateattributes(config.TinySampleCount, ...
    {'numeric'}, {'scalar', 'integer', 'positive'}, ...
    mfilename, "TinySampleCount");
validateattributes(config.TinyEpochs, ...
    {'numeric'}, {'scalar', 'integer', 'positive'}, ...
    mfilename, "TinyEpochs");
validateattributes(config.PredictionMiniBatchSize, ...
    {'numeric'}, {'scalar', 'integer', 'positive'}, ...
    mfilename, "PredictionMiniBatchSize");

if config.HiddenUnits ~= 64
    error("Stage4C:ArchitectureChanged", ...
        "Stage 4C must retain exactly 64 units in both hidden layers.");
end

if config.ExecutionEnvironment ~= "cpu"
    error("Stage4C:ExecutionEnvironmentChanged", ...
        "Stage 4C defaults and approved runs require CPU execution.");
end

protectedInputPaths = [ ...
    config.DatasetPath, ...
    config.DatasetVariantManifestPath, ...
    config.SplitManifestPath, ...
    config.Stage3AArtifactPath];
outputPaths = [ ...
    config.ScratchArtifactPath, ...
    config.WarmArtifactPath, ...
    config.ComparisonArtifactPath, ...
    config.ReportPath, ...
    config.MetricTablePath];

if numel(unique(lower(outputPaths))) ~= numel(outputPaths)
    error("Stage4C:OutputPathCollision", ...
        "Every Stage 4C output must use a distinct path.");
end

if any(ismember(lower(outputPaths), lower(protectedInputPaths)))
    error("Stage4C:ProtectedArtifactCollision", ...
        "Stage 4C outputs cannot overwrite an input or Stage 3A artifact.");
end

end

function dataset = localLoadDataset(datasetPath)
%LOCALLOADDATASET Load only the fields needed by Stage 4C.

try
    dataset = load( ...
        datasetPath, ...
        "previousState", ...
        "nextState", ...
        "dtSeconds", ...
        "previousCovarianceDiag", ...
        "metadata", ...
        "stateOrder", ...
        "sourceManifest", ...
        "buildSummary", ...
        "baselineConstVelMetrics");
catch err
    error("Stage4C:DatasetLoadFailed", ...
        "Unable to load Expanded-3Day dataset: %s", err.message);
end

requiredFields = [ ...
    "previousState", ...
    "nextState", ...
    "dtSeconds", ...
    "previousCovarianceDiag", ...
    "metadata", ...
    "stateOrder", ...
    "sourceManifest", ...
    "baselineConstVelMetrics"];

if any(~isfield(dataset, requiredFields))
    error("Stage4C:InvalidDatasetArtifact", ...
        "Expanded-3Day dataset is missing a required field.");
end

pairCount = size(dataset.previousState, 1);

if pairCount ~= 457903 || ...
        size(dataset.previousState, 2) ~= 6 || ...
        ~isequal(size(dataset.nextState), [pairCount, 6]) || ...
        ~isequal(size(dataset.previousCovarianceDiag), [pairCount, 6]) || ...
        numel(dataset.dtSeconds) ~= pairCount || ...
        height(dataset.metadata) ~= pairCount
    error("Stage4C:DatasetContractMismatch", ...
        "Expanded-3Day must contain exactly 457,903 aligned N-by-6 pairs.");
end

expectedStateOrder = ["x", "vx", "y", "vy", "z", "vz"];

if any(string(dataset.stateOrder(:).') ~= expectedStateOrder)
    error("Stage4C:StateOrderMismatch", ...
        "Dataset state order must be [x, vx, y, vy, z, vz].");
end

end

function stage3A = localLoadStage3A(stage3AArtifactPath)
%LOCALLOADSTAGE3A Load only the frozen network and normalizations.

try
    stage3A = load( ...
        stage3AArtifactPath, ...
        "net", ...
        "normalization");
catch err
    error("Stage4C:Stage3ALoadFailed", ...
        "Unable to load frozen Stage 3A artifact: %s", err.message);
end

if ~isfield(stage3A, "net") || ...
        ~isfield(stage3A, "normalization") || ...
        isempty(stage3A.net)
    error("Stage4C:InvalidStage3AArtifact", ...
        "Frozen Stage 3A artifact lacks its network or normalization.");
end

end

function provenance = localAuditDatasetProvenance(dataset, config)
%LOCALAUDITDATASETPROVENANCE Verify variant membership and source hashes.

variantManifest = readtable( ...
    config.DatasetVariantManifestPath, ...
    "TextType", ...
    "string");
requiredVariables = [ ...
    "relativeSourceFile", ...
    "sourceFileSHA256", ...
    config.DatasetVariantID];

if any(~ismember(requiredVariables, ...
        string(variantManifest.Properties.VariableNames)))
    error("Stage4C:InvalidVariantManifest", ...
        "Dataset-variant manifest is missing required fields.");
end

membership = localMembershipMask( ...
    variantManifest.(char(config.DatasetVariantID)));
selectedManifest = variantManifest(membership, :);

if height(selectedManifest) ~= 159 || height(dataset.sourceManifest) ~= 159
    error("Stage4C:DatasetMembershipCountMismatch", ...
        "Expanded-3Day must contain exactly 159 source files.");
end

expectedPaths = strings(height(selectedManifest), 1);

for rowIdx = 1:height(selectedManifest)
    expectedPaths(rowIdx) = localCanonicalPath(fullfile( ...
        config.ProjectRoot, ...
        replace( ...
        selectedManifest.relativeSourceFile(rowIdx), ...
        "/", ...
        filesep)));
end

expectedKeys = localSourceMembershipKey(expectedPaths);
datasetKeys = localSourceMembershipKey(dataset.sourceManifest.sourceFile);
membershipPassed = isequal(sort(expectedKeys), sort(datasetKeys));

if ~membershipPassed
    error("Stage4C:DatasetMembershipMismatch", ...
        "Dataset source membership does not match expanded_post3day_v2.");
end

expectedSHA256 = upper(strtrim(string( ...
    selectedManifest.sourceFileSHA256)));
observedSHA256 = repmat("not_verified", height(selectedManifest), 1);
hashPassed = false(height(selectedManifest), 1);

if config.VerifySourceHashes
    for rowIdx = 1:height(selectedManifest)
        observedSHA256(rowIdx) = helperComputeFileSHA256(expectedPaths(rowIdx));
        hashPassed(rowIdx) = strcmpi( ...
            observedSHA256(rowIdx), ...
            expectedSHA256(rowIdx));
    end

    if ~all(hashPassed)
        failedPath = expectedPaths(find(~hashPassed, 1, "first"));
        error("Stage4C:SourceHashMismatch", ...
            "Expanded-3Day source hash mismatch: %s", failedPath);
    end
end

sourceHashTable = table( ...
    selectedManifest.relativeSourceFile, ...
    expectedSHA256, ...
    observedSHA256, ...
    hashPassed, ...
    'VariableNames', [ ...
        "relativeSourceFile", ...
        "expectedSHA256", ...
        "observedSHA256", ...
        "passed"]);

provenance = struct();
provenance.datasetVariantID = config.DatasetVariantID;
provenance.datasetPath = config.DatasetPath;
provenance.datasetSHA256 = helperComputeFileSHA256(config.DatasetPath);
provenance.variantManifestPath = config.DatasetVariantManifestPath;
provenance.variantManifestSHA256 = helperComputeFileSHA256( ...
    config.DatasetVariantManifestPath);
provenance.sourceFileCount = height(selectedManifest);
provenance.datasetMembershipPassed = membershipPassed;
provenance.sourceHashesVerified = config.VerifySourceHashes;
provenance.sourceHashAuditPassed = ...
    config.VerifySourceHashes && all(hashPassed);
provenance.sourceHashTable = sourceHashTable;

end

function [split, audit, provenance] = localLoadAndAuditSplit(metadata, config)
%LOCALLOADANDAUDITSPLIT Apply the frozen global ICAO-disjoint assignment.

manifest = readtable(config.SplitManifestPath, "TextType", "string");
requiredVariables = [ ...
    "icao24", ...
    "split", ...
    "pairCount", ...
    "assignmentOrder", ...
    "datasetVariantID", ...
    "policyVersion"];

if any(~ismember(requiredVariables, string(manifest.Properties.VariableNames)))
    error("Stage4C:InvalidSplitManifest", ...
        "The Stage 4C split manifest is missing required variables.");
end

manifest.icao24 = lower(strtrim(string(manifest.icao24)));
manifest.split = lower(strtrim(string(manifest.split)));
datasetICAO = lower(strtrim(string(metadata.hex)));
uniqueDatasetICAO = sort(unique(datasetICAO));

if height(manifest) ~= numel(uniqueDatasetICAO) || ...
        numel(unique(manifest.icao24)) ~= height(manifest) || ...
        ~isequal(sort(manifest.icao24), uniqueDatasetICAO)
    error("Stage4C:SplitMembershipMismatch", ...
        "Split manifest must assign every Expanded-3Day ICAO exactly once.");
end

if any(~ismember(manifest.split, config.SplitNames)) || ...
        any(manifest.datasetVariantID ~= config.DatasetVariantID) || ...
        numel(unique(manifest.policyVersion)) ~= 1
    error("Stage4C:InvalidSplitAssignment", ...
        "Split assignments, dataset identity, or policy version are invalid.");
end

[found, manifestRow] = ismember(datasetICAO, manifest.icao24);

if ~all(found)
    error("Stage4C:UnassignedDatasetICAO", ...
        "At least one Expanded-3Day ICAO is absent from the split manifest.");
end

split = manifest.split(manifestRow);
actualPairCountByICAO = accumarray( ...
    manifestRow, ...
    1, ...
    [height(manifest), 1]);

if any(actualPairCountByICAO ~= double(manifest.pairCount))
    error("Stage4C:SplitPairCountMismatch", ...
        "Split manifest pair counts do not match the dataset.");
end

pairCount = zeros(numel(config.SplitNames), 1);
aircraftCount = zeros(numel(config.SplitNames), 1);

for splitIdx = 1:numel(config.SplitNames)
    splitName = config.SplitNames(splitIdx);
    pairCount(splitIdx) = sum(split == splitName);
    aircraftCount(splitIdx) = sum(manifest.split == splitName);
end

if any(pairCount(:).' ~= config.ExpectedPairCounts)
    error("Stage4C:UnexpectedSplitCounts", ...
        "Expected train/validation/test pair counts of %s; observed %s.", ...
        mat2str(config.ExpectedPairCounts), ...
        mat2str(pairCount(:).'));
end

[inheritedGroup, ~] = findgroups(datasetICAO);
inheritedSplitCount = splitapply( ...
    @(value) numel(unique(string(value))), ...
    metadata.split, ...
    inheritedGroup);
inheritedOverlappingICAOCount = sum(inheritedSplitCount > 1);

if inheritedOverlappingICAOCount ~= 394
    error("Stage4C:InheritedSplitAuditChanged", ...
        "Expected 394 inherited smoke-split ICAO overlaps; observed %d.", ...
        inheritedOverlappingICAOCount);
end

summaryTable = table( ...
    config.SplitNames(:), ...
    pairCount, ...
    aircraftCount, ...
    'VariableNames', ["split", "pairCount", "aircraftCount"]);
audit = struct();
audit.summary = summaryTable;
audit.everyICAOAssignedOnce = true;
audit.aircraftLeakage = false;
audit.inheritedOverlappingICAOCount = ...
    inheritedOverlappingICAOCount;
audit.inheritedSplitIgnored = true;
audit.icaoUsedOnlyAsPartitionKey = true;

provenance = struct();
provenance.splitManifestPath = config.SplitManifestPath;
provenance.splitManifestSHA256 = helperComputeFileSHA256( ...
    config.SplitManifestPath);
provenance.policyVersion = unique(manifest.policyVersion);
provenance.assignmentCount = height(manifest);
provenance.expectedPairCounts = config.ExpectedPairCounts;

end

function predictedState = localResolveConstvelPrediction(dataset)
%LOCALRESOLVECONSTVELPREDICTION Reuse the saved native baseline predictions.

baseline = dataset.baselineConstVelMetrics;

if ~isfield(baseline, "predictedState") || ...
        ~isequal(size(baseline.predictedState), size(dataset.previousState))
    error("Stage4C:MissingConstvelPrediction", ...
        "Expanded-3Day dataset lacks aligned native constvel predictions.");
end

predictedState = double(baseline.predictedState);

if any(~isfinite(predictedState), "all")
    error("Stage4C:NonfiniteConstvelPrediction", ...
        "Saved constvel predictions contain nonfinite values.");
end

end

function audit = localAuditConstvelPrediction( ...
        previousState, dtSeconds, savedPrediction)
%LOCALAUDITCONSTVELPREDICTION Spot-check saved rows against native constvel.

sampleCount = size(previousState, 1);
checkRows = unique(round(linspace(1, sampleCount, 32))).';
recomputed = zeros(numel(checkRows), 6);

for checkIdx = 1:numel(checkRows)
    row = checkRows(checkIdx);
    prediction = constvel(previousState(row, :).', dtSeconds(row));
    recomputed(checkIdx, :) = prediction(:).';
end

maxAbsDifference = max( ...
    abs(recomputed - savedPrediction(checkRows, :)), [], "all");
passed = isfinite(maxAbsDifference) && maxAbsDifference <= 1e-10;

if ~passed
    error("Stage4C:ConstvelAuditFailed", ...
        "Saved baseline differs from native constvel by %.9g.", ...
        maxAbsDifference);
end

audit = struct();
audit.function = "constvel";
audit.checkedRowCount = numel(checkRows);
audit.maxAbsDifference = maxAbsDifference;
audit.passed = passed;

end

function audit = localAuditArchitecture(net, featureNames, hiddenUnits)
%LOCALAUDITARCHITECTURE Require the unchanged 20-64-64-6 network.

learnables = net.Learnables;
fc1Weights = localLearnableValue(learnables, "fc1", "Weights");
fc2Weights = localLearnableValue(learnables, "fc2", "Weights");
predictionWeights = localLearnableValue( ...
    learnables, "prediction", "Weights");
expectedSizes = { ...
    [hiddenUnits, numel(featureNames)], ...
    [hiddenUnits, hiddenUnits], ...
    [6, hiddenUnits]};
observedSizes = { ...
    size(fc1Weights), ...
    size(fc2Weights), ...
    size(predictionWeights)};
passed = isequal(observedSizes, expectedSizes) && ...
    numel(net.Layers) == 6;

if ~passed
    error("Stage4C:LegacyArchitectureMismatch", ...
        "Frozen Stage 3A network is not the approved 20-64-64-6 MLP.");
end

identityTokens = ["icao", "hex", "callsign", "session"];
lowerFeatureNames = lower(string(featureNames));
identityPresent = false;

for tokenIdx = 1:numel(identityTokens)
    identityPresent = identityPresent || ...
        any(contains(lowerFeatureNames, identityTokens(tokenIdx)));
end

if identityPresent
    error("Stage4C:IdentityFeaturePresent", ...
        "ICAO or another identity field appears in neural features.");
end

audit = struct();
audit.passed = passed;
audit.layerCount = numel(net.Layers);
audit.featureCount = numel(featureNames);
audit.hiddenUnits = hiddenUnits;
audit.outputCount = 6;
audit.featureNames = featureNames;
audit.identityFeaturePresent = identityPresent;
audit.memoryless = true;

end

function normalization = localComputeNormalization( ...
        features, featureNames, targetDelta, split)
%LOCALCOMPUTENORMALIZATION Fit all affine scaling on training rows only.

trainMask = split == "train";
featureMean = mean(features(trainMask, :), 1, "omitnan");
rawFeatureStd = std(features(trainMask, :), 0, 1, "omitnan");
featureStd = localGuardStd(rawFeatureStd);
targetMean = mean(targetDelta(trainMask, :), 1, "omitnan");
rawTargetStd = std(targetDelta(trainMask, :), 0, 1, "omitnan");
targetStd = localGuardStd(rawTargetStd);

normalization = struct();
normalization.computedFromSplit = "train";
normalization.trainRowCount = sum(trainMask);
normalization.features = struct();
normalization.features.computedFromSplit = "train";
normalization.features.trainRowCount = sum(trainMask);
normalization.features.featureNames = featureNames(:);
normalization.features.featureMean = featureMean;
normalization.features.featureStd = featureStd;
normalization.features.rawFeatureStd = rawFeatureStd;
normalization.features.constantFeatureMask = rawFeatureStd <= 0 | ...
    ~isfinite(rawFeatureStd);
normalization.target = struct();
normalization.target.computedFromSplit = "train";
normalization.target.trainRowCount = sum(trainMask);
normalization.target.targetNames = [ ...
    "delta_x"; ...
    "delta_vx"; ...
    "delta_y"; ...
    "delta_vy"; ...
    "delta_z"; ...
    "delta_vz"];
normalization.target.targetMean = targetMean;
normalization.target.targetStd = targetStd;
normalization.target.rawTargetStd = rawTargetStd;

end

function guardedStd = localGuardStd(rawStd)
%LOCALGUARDSTD Replace zero or invalid standard deviations with one.

guardedStd = rawStd;
badStd = ~isfinite(guardedStd) | guardedStd <= 0;
guardedStd(badStd) = 1;

end

function localValidateNormalizedData(featuresNormalized, targetNormalized)
%LOCALVALIDATENORMALIZEDDATA Fail before training on malformed arrays.

if size(featuresNormalized, 2) ~= 20 || ...
        size(targetNormalized, 2) ~= 6 || ...
        size(featuresNormalized, 1) ~= size(targetNormalized, 1) || ...
        any(~isfinite(featuresNormalized), "all") || ...
        any(~isfinite(targetNormalized), "all")
    error("Stage4C:InvalidNormalizedTrainingData", ...
        "Normalized training arrays must be finite N-by-20 and N-by-6.");
end

end

function rows = localSelectRebaseRows(trainRows, maximumCount)
%LOCALSELECTREBASEROWS Select deterministic coverage across training rows.

sampleCount = min(maximumCount, numel(trainRows));
selection = unique(round(linspace(1, numel(trainRows), sampleCount)));
rows = trainRows(selection);

end

function auditTable = localBuildNativeFunctionAudit(constvelAudit)
%LOCALBUILDNATIVEFUNCTIONAUDIT Record native MATLAB choices.

workflow = [ ...
    "Irregular one-step motion baseline"; ...
    "Mean-MLP training"; ...
    "MLP architecture"; ...
    "Held-out error summaries"];
nativeMATLABFunction = [ ...
    "constvel"; ...
    "trainnet with trainingOptions('adam')"; ...
    "featureInputLayer, fullyConnectedLayer, reluLayer"; ...
    "vecnorm, mean, median, weighted quantile"];
stage4CUse = [ ...
    "Reuse saved native predictions and spot-check 32 rows"; ...
    "Normalized delta-MSE, patience, and best-validation output"; ...
    "Unchanged 20-64-64-6 architecture"; ...
    "Position/velocity RMSE, median, and P95"];
verified = [ ...
    constvelAudit.passed; ...
    true; ...
    true; ...
    true];
auditTable = table( ...
    workflow, ...
    nativeMATLABFunction, ...
    stage4CUse, ...
    verified);

end

function summary = localBuildPreflightSummary( ...
        config, ...
        dataset, ...
        datasetProvenance, ...
        splitAudit, ...
        splitProvenance, ...
        normalization, ...
        featureData, ...
        architectureAudit, ...
        warmStartRebaseAudit, ...
        nativeFunctionAudit, ...
        stage3AIntegrity)
%LOCALBUILDPREFLIGHTSUMMARY Build compact state without copying the dataset.

summary = struct();
summary.generatedAt = datetime("now", "TimeZone", "UTC");
summary.completed = false;
summary.config = config;
summary.datasetVariantID = config.DatasetVariantID;
summary.datasetPairCount = size(dataset.previousState, 1);
summary.stateOrder = dataset.stateOrder;
summary.datasetProvenance = datasetProvenance;
summary.splitAudit = splitAudit;
summary.splitProvenance = splitProvenance;
summary.normalization = normalization;
summary.featureContract = rmfield(featureData, "features");
summary.architectureAudit = architectureAudit;
summary.warmStartRebaseAudit = warmStartRebaseAudit;
summary.nativeFunctionAudit = nativeFunctionAudit;
summary.stage3AIntegrity = stage3AIntegrity;
summary.trainingOptions = localTrainingOptionRecord( ...
    config, ...
    normalization.trainRowCount);
summary.tinyOverfit = struct();
summary.metrics = struct();
summary.exploratoryVerdict = "Training not run (preflight only).";

end

function tiny = localRunTinyOverfit(XTrain, YTrain, config)
%LOCALRUNTINYOVERFIT Fit one deterministic 128-row batch before full runs.

sampleCount = min(config.TinySampleCount, size(XTrain, 1));
rng(config.Seed, "twister");
selection = randperm(size(XTrain, 1), sampleCount);
XTiny = XTrain(selection, :);
YTiny = YTrain(selection, :);
rng(config.Seed, "twister");
tinyNet = dlnetwork(localBuildLayers(config.HiddenUnits));
rng(config.Seed, "twister");
options = trainingOptions( ...
    "adam", ...
    "MaxEpochs", ...
    config.TinyEpochs, ...
    "MiniBatchSize", ...
    sampleCount, ...
    "InitialLearnRate", ...
    config.InitialLearnRate, ...
    "L2Regularization", ...
    config.L2Regularization, ...
    "Shuffle", ...
    "every-epoch", ...
    "ExecutionEnvironment", ...
    config.ExecutionEnvironment, ...
    "Verbose", ...
    false, ...
    "Plots", ...
    "none");
[tinyNet, info] = trainnet(XTiny, YTiny, tinyNet, "mse", options);
prediction = localPredictNormalized( ...
    tinyNet, ...
    XTiny, ...
    config.PredictionMiniBatchSize);
history = info.TrainingHistory;
firstTrainingLoss = history.Loss(1);
finalTrainingLoss = history.Loss(end);
predictionMSE = mean((double(prediction) - double(YTiny)) .^ 2, "all");
lossDecreased = finalTrainingLoss < firstTrainingLoss;
passed = all(isfinite(prediction), "all") && ...
    isfinite(firstTrainingLoss) && ...
    isfinite(finalTrainingLoss) && ...
    isfinite(predictionMSE) && ...
    (lossDecreased || config.TinyEpochs == 1);

tiny = struct();
tiny.sampleCount = sampleCount;
tiny.maxEpochs = config.TinyEpochs;
tiny.firstTrainingLoss = firstTrainingLoss;
tiny.finalTrainingLoss = finalTrainingLoss;
tiny.predictionMSE = predictionMSE;
tiny.lossDecreased = lossDecreased;
tiny.stopReason = string(info.StopReason);
tiny.passed = passed;
tiny.trainingHistory = history;

end

function run = localTrainFullNetwork( ...
        initialNet, ...
        XTrain, ...
        YTrain, ...
        XValidation, ...
        YValidation, ...
        config, ...
        modelID)
%LOCALTRAINFULLNETWORK Train scratch or rebased weights with fresh Adam.

if isempty(initialNet)
    rng(config.Seed, "twister");
    initialNet = dlnetwork(localBuildLayers(config.HiddenUnits));
    initialization = "fresh_glorot_initialization";
else
    initialization = "rebased_legacy_stage3a_weights";
end

% Reset before trainnet so scratch and warm use the same epoch shuffling.
rng(config.Seed, "twister");
iterationsPerEpoch = ceil(size(XTrain, 1) / config.MiniBatchSize);
options = trainingOptions( ...
    "adam", ...
    "MaxEpochs", ...
    config.MaxEpochs, ...
    "MiniBatchSize", ...
    config.MiniBatchSize, ...
    "InitialLearnRate", ...
    config.InitialLearnRate, ...
    "L2Regularization", ...
    config.L2Regularization, ...
    "Shuffle", ...
    "every-epoch", ...
    "ValidationData", ...
    {XValidation, YValidation}, ...
    "ValidationFrequency", ...
    iterationsPerEpoch, ...
    "ValidationPatience", ...
    config.ValidationPatience, ...
    "OutputNetwork", ...
    "best-validation", ...
    "ExecutionEnvironment", ...
    config.ExecutionEnvironment, ...
    "Verbose", ...
    config.Verbose, ...
    "VerboseFrequency", ...
    iterationsPerEpoch, ...
    "Plots", ...
    "none");
[net, info] = trainnet(XTrain, YTrain, initialNet, "mse", options);

run = struct();
run.modelID = string(modelID);
run.net = net;
run.info = info;
run.initialization = initialization;
run.optimizerStateInitialization = "fresh";
run.finalTrainingLoss = info.TrainingHistory.Loss(end);
run.bestValidationLoss = min(info.ValidationHistory.Loss);
run.stopReason = string(info.StopReason);

if ~isfinite(run.finalTrainingLoss) || ~isfinite(run.bestValidationLoss)
    error("Stage4C:NonfiniteTrainingLoss", ...
        "Model %s produced a nonfinite training or validation loss.", ...
        modelID);
end

end

function layers = localBuildLayers(hiddenUnits)
%LOCALBUILDLAYERS Return the unchanged 20-64-64-6 ReLU MLP.

layers = [
    featureInputLayer(20, "Normalization", "none", "Name", "features")
    fullyConnectedLayer(hiddenUnits, "Name", "fc1")
    reluLayer("Name", "relu1")
    fullyConnectedLayer(hiddenUnits, "Name", "fc2")
    reluLayer("Name", "relu2")
    fullyConnectedLayer(6, "Name", "prediction")];

end

function predictedState = localPredictPhysicalState( ...
        net, ...
        physicalFeatures, ...
        previousState, ...
        featureNormalization, ...
        targetNormalization, ...
        miniBatchSize)
%LOCALPREDICTPHYSICALSTATE Normalize, infer delta, and reconstruct state.

featuresNormalized = ...
    (double(physicalFeatures) - featureNormalization.featureMean) ./ ...
    featureNormalization.featureStd;
predictedDeltaNormalized = localPredictNormalized( ...
    net, ...
    single(featuresNormalized), ...
    miniBatchSize);
predictedDelta = double(predictedDeltaNormalized) .* ...
    targetNormalization.targetStd + ...
    targetNormalization.targetMean;
predictedState = double(previousState) + predictedDelta;

if any(~isfinite(predictedState), "all")
    error("Stage4C:NonfinitePrediction", ...
        "A Stage 4C model produced nonfinite physical predictions.");
end

end

function output = localPredictNormalized(net, input, miniBatchSize)
%LOCALPREDICTNORMALIZED Return an N-by-6 numeric prediction.

output = minibatchpredict( ...
    net, ...
    input, ...
    "MiniBatchSize", ...
    min(miniBatchSize, size(input, 1)));
output = gather(extractdata(output));

if size(output, 1) ~= size(input, 1) && ...
        size(output, 2) == size(input, 1)
    output = output.';
end

if size(output, 1) ~= size(input, 1) || size(output, 2) ~= 6
    error("Stage4C:PredictionShapeMismatch", ...
        "Mean-MLP predictions must be N-by-6.");
end

end

function models = localPackModelPredictions( ...
        constvelPrediction, ...
        legacyPrediction, ...
        scratchPrediction, ...
        warmPrediction)
%LOCALPACKMODELPREDICTIONS Keep the four required identities explicit.

models = repmat(struct( ...
    "modelID", "", ...
    "predictedNextState", []), ...
    4, ...
    1);
models(1).modelID = "constvel";
models(1).predictedNextState = constvelPrediction;
models(2).modelID = "legacy_stage3a_v1";
models(2).predictedNextState = legacyPrediction;
models(3).modelID = "expanded_scratch_mean_v1";
models(3).predictedNextState = scratchPrediction;
models(4).modelID = "expanded_warm_mean_v1";
models(4).predictedNextState = warmPrediction;

end

function comparison = localBuildCandidateComparison(metricTable)
%LOCALBUILDCANDIDATECOMPARISON Compare candidate headline errors to constvel.

headlineMask = metricTable.split == "test" & ...
    metricTable.groupDimension == "all" & ...
    metricTable.groupName == "all" & ...
    metricTable.weighting == "pair_weighted";
headline = metricTable(headlineMask, :);
baseline = headline(headline.modelID == "constvel", :);
candidateIDs = [ ...
    "expanded_scratch_mean_v1"; ...
    "expanded_warm_mean_v1"];
positionRMSEMeters = NaN(numel(candidateIDs), 1);
velocityRMSEMetersPerSecond = NaN(numel(candidateIDs), 1);
positionDeltaFromConstvelMeters = NaN(numel(candidateIDs), 1);
velocityDeltaFromConstvelMetersPerSecond = NaN(numel(candidateIDs), 1);
beatsConstvelPosition = false(numel(candidateIDs), 1);
beatsConstvelVelocity = false(numel(candidateIDs), 1);

for candidateIdx = 1:numel(candidateIDs)
    row = headline(headline.modelID == candidateIDs(candidateIdx), :);
    positionRMSEMeters(candidateIdx) = row.positionRMSEMeters;
    velocityRMSEMetersPerSecond(candidateIdx) = ...
        row.velocityRMSEMetersPerSecond;
    positionDeltaFromConstvelMeters(candidateIdx) = ...
        row.positionRMSEMeters - baseline.positionRMSEMeters;
    velocityDeltaFromConstvelMetersPerSecond(candidateIdx) = ...
        row.velocityRMSEMetersPerSecond - ...
        baseline.velocityRMSEMetersPerSecond;
    beatsConstvelPosition(candidateIdx) = ...
        positionDeltaFromConstvelMeters(candidateIdx) < 0;
    beatsConstvelVelocity(candidateIdx) = ...
        velocityDeltaFromConstvelMetersPerSecond(candidateIdx) < 0;
end

comparison = table( ...
    candidateIDs, ...
    positionRMSEMeters, ...
    velocityRMSEMetersPerSecond, ...
    positionDeltaFromConstvelMeters, ...
    velocityDeltaFromConstvelMetersPerSecond, ...
    beatsConstvelPosition, ...
    beatsConstvelVelocity, ...
    'VariableNames', [ ...
        "modelID", ...
        "testPositionRMSEMeters", ...
        "testVelocityRMSEMetersPerSecond", ...
        "positionDeltaFromConstvelMeters", ...
        "velocityDeltaFromConstvelMetersPerSecond", ...
        "beatsConstvelPosition", ...
        "beatsConstvelVelocity"]);

end

function verdict = localBuildExploratoryVerdict(comparison)
%LOCALBUILDEXPLORATORYVERDICT State success or failure without promotion.

parts = strings(height(comparison), 1);

for rowIdx = 1:height(comparison)
    if comparison.beatsConstvelPosition(rowIdx)
        positionResult = "beats";
    else
        positionResult = "does not beat";
    end

    if comparison.beatsConstvelVelocity(rowIdx)
        velocityResult = "beats";
    else
        velocityResult = "does not beat";
    end

    parts(rowIdx) = sprintf( ...
        "%s %s constvel on test position RMSE (%.3f m; delta %+.3f m) and %s constvel on velocity RMSE (%.3f m/s; delta %+.3f m/s).", ...
        comparison.modelID(rowIdx), ...
        positionResult, ...
        comparison.testPositionRMSEMeters(rowIdx), ...
        comparison.positionDeltaFromConstvelMeters(rowIdx), ...
        velocityResult, ...
        comparison.testVelocityRMSEMetersPerSecond(rowIdx), ...
        comparison.velocityDeltaFromConstvelMetersPerSecond(rowIdx));
end

verdict = strjoin(parts, " ");

end

function record = localTrainingOptionRecord(config, trainRowCount)
%LOCALTRAININGOPTIONRECORD Save exact approved options as plain data.

record = struct();
record.Architecture = "20-64-64-6_relu";
record.Objective = "normalized_delta_mse";
record.Optimizer = "adam";
record.InitialLearnRate = config.InitialLearnRate;
record.L2Regularization = config.L2Regularization;
record.MiniBatchSize = config.MiniBatchSize;
record.MaxEpochs = config.MaxEpochs;
record.ValidationFrequency = ceil( ...
    trainRowCount / config.MiniBatchSize);
record.ValidationCadence = "once_per_epoch";
record.ValidationPatience = config.ValidationPatience;
record.OutputNetwork = "best-validation";
record.Seed = config.Seed;
record.ExecutionEnvironment = config.ExecutionEnvironment;
record.TrainRowCount = trainRowCount;

end

function compact = localCompactTrainingRun(run)
%LOCALCOMPACTTRAININGRUN Exclude network weights from comparison state.

compact = struct();
compact.modelID = run.modelID;
compact.initialization = run.initialization;
compact.optimizerStateInitialization = run.optimizerStateInitialization;
compact.finalTrainingLoss = run.finalTrainingLoss;
compact.bestValidationLoss = run.bestValidationLoss;
compact.stopReason = run.stopReason;
compact.trainingHistory = run.info.TrainingHistory;
compact.validationHistory = run.info.ValidationHistory;

end

function localSaveModelArtifact( ...
        artifactPath, ...
        modelID, ...
        run, ...
        initializationSource, ...
        rebaseAudit, ...
        normalization, ...
        summary)
%LOCALSAVEMODELARTIFACT Save one network without duplicating row data.

modelArtifact = struct();
modelArtifact.generatedAt = summary.generatedAt;
modelArtifact.modelID = string(modelID);
modelArtifact.network = run.net;
modelArtifact.normalization = normalization;
modelArtifact.datasetProvenance = summary.datasetProvenance;
modelArtifact.splitProvenance = summary.splitProvenance;
modelArtifact.splitAudit = summary.splitAudit;
modelArtifact.initializationProvenance = struct( ...
    "source", ...
    string(initializationSource), ...
    "optimizerState", ...
    "fresh", ...
    "stage3AArtifactPath", ...
    summary.stage3AIntegrity.path, ...
    "stage3AArtifactSHA256", ...
    summary.stage3AIntegrity.beforeSHA256, ...
    "rebaseAudit", ...
    rebaseAudit);
modelArtifact.trainingOptions = summary.trainingOptions;
modelArtifact.trainingHistory = run.info.TrainingHistory;
modelArtifact.validationHistory = run.info.ValidationHistory;
modelArtifact.stopReason = string(run.info.StopReason);
modelArtifact.tinyOverfit = summary.tinyOverfit;
modelArtifact.metrics = summary.metrics.table( ...
    summary.metrics.table.modelID == modelID, :);
modelArtifact.comparisonHeadline = summary.candidateComparison;
modelArtifact.stage3AIntegrity = summary.stage3AIntegrity;
modelArtifact.exploratory = true;
modelArtifact.promoted = false;
net = run.net;
trainingInfo = run.info;

try
    save( ...
        artifactPath, ...
        "modelArtifact", ...
        "net", ...
        "normalization", ...
        "trainingInfo", ...
        "-v7.3");
catch err
    error("Stage4C:ModelArtifactSaveFailed", ...
        "Unable to save model artifact %s: %s", artifactPath, err.message);
end

end

function localSaveComparisonArtifact(artifactPath, summary)
%LOCALSAVECOMPARISONARTIFACT Save compact cross-model evidence only.

stage4CSummary = summary;

try
    save(artifactPath, "stage4CSummary", "-v7.3");
catch err
    error("Stage4C:ComparisonArtifactSaveFailed", ...
        "Unable to save comparison artifact %s: %s", ...
        artifactPath, ...
        err.message);
end

end

function localPrintCompletion(summary)
%LOCALPRINTCOMPLETION Print concise physical-unit headline results.

fprintf("Stage 4C-Retrain complete\n");
fprintf("%s\n", summary.exploratoryVerdict);
fprintf("Scratch artifact:\t%s\n", summary.scratchArtifactPath);
fprintf("Warm artifact:\t%s\n", summary.warmArtifactPath);
fprintf("Report:\t%s\n", summary.reportPath);

end

function value = localLearnableValue(learnables, layerName, parameterName)
%LOCALLEARNABLEVALUE Extract one named dlnetwork parameter.

mask = string(learnables.Layer) == layerName & ...
    string(learnables.Parameter) == parameterName;

if sum(mask) ~= 1
    error("Stage4C:ArchitectureLearnableMissing", ...
        "Expected one %s/%s parameter.", layerName, parameterName);
end

matchingValues = learnables.Value(mask);
value = extractdata(matchingValues{1});

end

function membership = localMembershipMask(values)
%LOCALMEMBERSHIPMASK Validate a dataset-variant membership column.

if islogical(values)
    membership = values;
elseif isnumeric(values)
    if any(~isfinite(values), "all") || ...
            any(values ~= 0 & values ~= 1, "all")
        error("Stage4C:InvalidVariantMembership", ...
            "Variant membership must contain only zero or one.");
    end

    membership = logical(values);
else
    text = lower(strtrim(string(values)));
    valid = text == "true" | text == "false" | ...
        text == "1" | text == "0";

    if any(~valid)
        error("Stage4C:InvalidVariantMembership", ...
            "Variant membership must contain only true/false or one/zero.");
    end

    membership = text == "true" | text == "1";
end

membership = membership(:);

end

function keys = localSourceMembershipKey(paths)
%LOCALSOURCEMEMBERSHIPKEY Compare original gzip and fallback text sources.

paths = lower(replace(string(paths), "\", "/"));
keys = strings(numel(paths), 1);
marker = "testing_machine/captures/";

for pathIdx = 1:numel(paths)
    pathValue = paths(pathIdx);
    markerIndex = strfind(pathValue, marker);

    if isempty(markerIndex)
        key = pathValue;
    else
        key = extractAfter(pathValue, markerIndex(end) - 1);
    end

    if endsWith(key, ".gz")
        key = extractBefore(key, strlength(key) - 2);
    end

    keys(pathIdx) = key;
end

end

function value = localTextScalar(value, argumentName, allowEmpty)
%LOCALTEXTSCALAR Normalize one text option.

isCharacterVector = ischar(value) && (isrow(value) || isempty(value));
isStringScalar = isstring(value) && isscalar(value);

if ~isCharacterVector && ~isStringScalar
    error("Stage4C:InvalidTextOption", ...
        "%s must be a character vector or string scalar.", argumentName);
end

value = strtrim(string(value));

if ismissing(value) || (~allowEmpty && strlength(value) == 0)
    error("Stage4C:InvalidTextOption", ...
        "%s must not be empty.", argumentName);
end

end

function value = localLogicalScalar(value, argumentName)
%LOCALLOGICALSCALAR Accept only scalar logical or numeric zero/one.

isLogicalScalar = islogical(value) && isscalar(value);
isBinaryNumericScalar = isnumeric(value) && isscalar(value) && ...
    isfinite(value) && (value == 0 || value == 1);

if ~isLogicalScalar && ~isBinaryNumericScalar
    error("Stage4C:InvalidLogicalOption", ...
        "%s must be a scalar logical value.", argumentName);
end

value = logical(value);

end

function resolvedPath = localResolvePath( ...
        projectRoot, suppliedPath, defaultPath, argumentName)
%LOCALRESOLVEPATH Resolve empty, relative, and already-rooted paths.

suppliedPath = localTextScalar(suppliedPath, argumentName, true);

if strlength(suppliedPath) == 0
    suppliedPath = string(defaultPath);
end

if localIsAbsolutePath(suppliedPath)
    resolvedPath = suppliedPath;
else
    resolvedPath = fullfile(projectRoot, suppliedPath);
end

resolvedPath = localCanonicalPath(resolvedPath);

end

function canonicalPath = localCanonicalPath(pathValue)
%LOCALCANONICALPATH Normalize a path without requiring it to exist.

try
    canonicalPath = string(java.io.File(char(pathValue)).getCanonicalPath());
catch err
    error("Stage4C:PathResolutionFailed", ...
        "Unable to resolve path %s: %s", pathValue, err.message);
end

end

function tf = localIsAbsolutePath(pathValue)
%LOCALISABSOLUTEPATH Detect Windows and POSIX rooted paths.

normalizedPath = replace(string(pathValue), "\", "/");
tf = startsWith(normalizedPath, "/") || ...
    ~isempty(regexp(char(normalizedPath), "^[A-Za-z]:", "once"));

end
