function results = runStage4ERecursiveFilterEvaluation(varargin)
%RUNSTAGE4ERECURSIVEFILTEREVALUATION Benchmark complete recursive filters.
% Stage 4E compares native CV, CA, CT, and IMM estimators with a trackingUKF
% whose state transition is the frozen Stage 4C warm network.

projectRoot = string(fileparts(mfilename("fullpath")));
parser = inputParser;
parser.FunctionName = mfilename;
addParameter(parser, "BenchmarkMode", "smoke");
addParameter(parser, "Seed", 123);
addParameter(parser, "OutputFolder", "");
addParameter(parser, "ResultsPath", "");
addParameter(parser, "RetuneFilters", false);
addParameter(parser, "CreatePlots", true);
addParameter(parser, "Verbose", true);
parse(parser, varargin{:});

config = localBuildConfig(projectRoot, parser.Results);
localValidateConfig(config);
benchmarkTimer = tic;

if config.Verbose
    fprintf("Stage 4E recursive filter evaluation\n");
    fprintf("Benchmark mode:\t%s\n", config.BenchmarkMode);
    fprintf("Retune filters:\t%s\n", string(config.RetuneFilters));
end

warmHashBefore = helperComputeFileSHA256(config.WarmArtifactPath);
[dataset, split, inputAudit] = localLoadFrozenInputs(config);
warmAudit = localAuditWarmArtifact(config, warmHashBefore);
[validationDetectionLogs, validationTruthTables, validationSummary] = ...
    localBuildValidationTuningData( ...
    dataset, ...
    split, ...
    config);
tuning = localResolveTuning( ...
    validationDetectionLogs, ...
    validationTruthTables, ...
    validationSummary, ...
    config, ...
    warmAudit, ...
    inputAudit);
tuningFrozenBeforeTest = exist(config.TuningPath, "file") == 2;

[syntheticSequences, syntheticSummary] = localBuildSyntheticSequences( ...
    dataset, ...
    split, ...
    config);
[realSequences, realProtocol] = localBuildRealSequences( ...
    dataset, ...
    split, ...
    "test", ...
    config);
[realRepeat, ~] = localBuildRealSequences( ...
    dataset, ...
    split, ...
    "test", ...
    config);
deterministicRealDropout = localSequencesEqual( ...
    realSequences, ...
    realRepeat);
clear realRepeat
allSequences = [syntheticSequences(:); realSequences(:)];
evaluationStartedAt = datetime("now", "TimeZone", "UTC");
evaluation = helperEvaluateStage4ESequences( ...
    allSequences, ...
    tuning, ...
    Verbose=config.Verbose);
clear allSequences syntheticSequences realSequences dataset

warmHashAfter = helperComputeFileSHA256(config.WarmArtifactPath);
artifactAudit = localBuildArtifactAudit( ...
    config, ...
    warmAudit, ...
    inputAudit, ...
    tuning, ...
    warmHashBefore, ...
    warmHashAfter);
verificationTable = localBuildVerificationTable( ...
    evaluation, ...
    realProtocol, ...
    syntheticSummary, ...
    tuning, ...
    config, ...
    tuningFrozenBeforeTest, ...
    evaluationStartedAt, ...
    deterministicRealDropout, ...
    warmHashBefore, ...
    warmHashAfter);

if ~isfolder(config.OutputFolder)
    mkdir(config.OutputFolder);
end

resultsFolder = string(fileparts(config.ResultsPath));

if strlength(resultsFolder) > 0 && ~isfolder(resultsFolder)
    mkdir(resultsFolder);
end

results = struct();
results.generatedAt = datetime("now", "TimeZone", "UTC");
results.stage = "4E";
results.completed = all(verificationTable.passed);
results.benchmarkMode = config.BenchmarkMode;
results.randomSeed = config.Seed;
results.interpretation = ...
    "Recursive filter behavior with position-only updates; real ADS-B is a scoring proxy.";
results.config = localBuildConfigurationTable( ...
    config, ...
    syntheticSummary, ...
    realProtocol, ...
    validationSummary);
results.nativeFunctionAudit = localBuildNativeFunctionAudit();
results.artifactAudit = artifactAudit;
results.verificationTable = verificationTable;
results.tuningSummary = rmfield(tuning, 'parameters');
results.metricTable = evaluation.metricTable;
results.eventMetricTable = evaluation.eventMetricTable;
results.motionMetricTable = evaluation.motionMetricTable;
results.outageAgeMetricTable = evaluation.outageAgeMetricTable;
results.eventWinRateTable = evaluation.eventWinRateTable;
results.consistencyTable = evaluation.consistencyTable;
results.runtimeTable = evaluation.runtimeTable;
results.inputAuditTable = evaluation.inputAuditTable;
results.syntheticSummary = syntheticSummary;
results.realProtocol = realProtocol;
results.representativePaths = evaluation.representativePaths;
results.trainingPerformed = false;
results.networkPredictsCovariance = false;
results.associationEvaluated = false;
results.passiveRadarPerformanceEvaluated = false;
results.paths = localBuildOutputPaths(config);
results.figurePaths = struct("summary", "");
results.elapsedSeconds = toc(benchmarkTimer);

if config.CreatePlots
    plotOutput = helperPlotStage4ERecursiveEvaluation( ...
        results, ...
        SavePath=results.paths.summaryFigure);
    results.figurePaths.summary = plotOutput.savePath;
end

localWriteResults(results);

if config.Verbose
    fprintf("Stage 4E complete:\t%s\n", string(results.completed));
    fprintf("Results:\t%s\n", results.paths.results);
end

end

function config = localBuildConfig(projectRoot, options)
%LOCALBUILDCONFIG Resolve Stage 4E paths and execution options.

config = struct();
config.ProjectRoot = localCanonicalPath(projectRoot);
config.BenchmarkMode = lower(localTextScalar( ...
    options.BenchmarkMode, ...
    "BenchmarkMode", ...
    false));
config.Seed = double(options.Seed);
config.OutputFolder = localResolvePath( ...
    config.ProjectRoot, ...
    options.OutputFolder, ...
    fullfile("artifacts", "stage4ERecursiveFilterEvaluation"));
config.ResultsPath = localResolvePath( ...
    config.ProjectRoot, ...
    options.ResultsPath, ...
    fullfile( ...
        config.OutputFolder, ...
        "stage4ERecursiveFilterEvaluationResults.mat"));
config.TuningPath = fullfile( ...
    config.ProjectRoot, ...
    "artifacts", ...
    "stage4ERecursiveFilterEvaluation", ...
    "stage4EFilterTuning.mat");
config.WarmArtifactPath = fullfile( ...
    config.ProjectRoot, ...
    "artifacts", ...
    "stage4CRetrain", ...
    "expandedPost3DayWarmStartMeanMLP_v1.mat");
config.DatasetPath = fullfile( ...
    config.ProjectRoot, ...
    "artifacts", ...
    "stage4BPostCampaign", ...
    "expanded_post3day_v2", ...
    "stage3CArchiveStatePairDataset.mat");
config.SplitManifestPath = fullfile( ...
    config.ProjectRoot, ...
    "adsb_archive", ...
    "datasetVersions", ...
    "expandedPost3DayICAODisjointSplit_v1.csv");
config.RetuneFilters = localLogicalScalar( ...
    options.RetuneFilters, ...
    "RetuneFilters");
config.CreatePlots = localLogicalScalar( ...
    options.CreatePlots, ...
    "CreatePlots");
config.Verbose = localLogicalScalar(options.Verbose, "Verbose");
config.ExpectedWarmSHA256 = ...
    "1999F972DBDABE67F45953C52CD4CDB1620F1FECF1716C075F391064D3B32FFE";

end

function localValidateConfig(config)
%LOCALVALIDATECONFIG Validate modes, files, and protected outputs.

if ~ismember(config.BenchmarkMode, ["smoke", "full"])
    error("Stage4E:InvalidBenchmarkMode", ...
        "BenchmarkMode must be smoke or full.");
end

validateattributes(config.Seed, ...
    {'numeric'}, {'scalar', 'integer', 'nonnegative', 'finite'}, ...
    mfilename, "Seed");
requiredPaths = [ ...
    config.WarmArtifactPath; ...
    config.DatasetPath; ...
    config.SplitManifestPath];

for pathIdx = 1:numel(requiredPaths)
    if exist(requiredPaths(pathIdx), "file") ~= 2
        error("Stage4E:MissingInputFile", ...
            "Required frozen input was not found: %s", requiredPaths(pathIdx));
    end
end

protectedPaths = lower(requiredPaths);

if ismember(lower(config.ResultsPath), protectedPaths) || ...
        ismember(lower(config.TuningPath), protectedPaths)
    error("Stage4E:ProtectedArtifactCollision", ...
        "Stage 4E outputs cannot overwrite frozen Stage 4C inputs.");
end

end

function [dataset, split, audit] = localLoadFrozenInputs(config)
%LOCALLOADFROZENINPUTS Load the fixed Expanded-3Day data and split.

dataset = load( ...
    config.DatasetPath, ...
    "previousState", ...
    "nextState", ...
    "dtSeconds", ...
    "previousCovarianceDiag", ...
    "covarianceStdAssumed", ...
    "metadata", ...
    "stateOrder");
rowCount = size(dataset.previousState, 1);
expectedStateOrder = ["x", "vx", "y", "vy", "z", "vz"];

if rowCount ~= 457903 || ...
        ~isequal(size(dataset.previousState), [rowCount, 6]) || ...
        ~isequal(size(dataset.nextState), [rowCount, 6]) || ...
        ~isequal(size(dataset.previousCovarianceDiag), [rowCount, 6]) || ...
        height(dataset.metadata) ~= rowCount || ...
        numel(dataset.dtSeconds) ~= rowCount || ...
        any(string(dataset.stateOrder(:).') ~= expectedStateOrder)
    error("Stage4E:DatasetContractMismatch", ...
        "The frozen Expanded-3Day dataset contract has changed.");
end

manifest = readtable(config.SplitManifestPath, TextType="string");
[found, manifestRows] = ismember( ...
    lower(strtrim(string(dataset.metadata.hex))), ...
    lower(strtrim(string(manifest.icao24))));

if ~all(found)
    error("Stage4E:SplitMembershipMismatch", ...
        "Every dataset ICAO must occur in the frozen split manifest.");
end

split = lower(strtrim(string(manifest.split(manifestRows))));
splitCounts = [ ...
    sum(split == "train"), ...
    sum(split == "validation"), ...
    sum(split == "test")];

if ~isequal(splitCounts, [277959, 86420, 93524])
    error("Stage4E:SplitCountMismatch", ...
        "The frozen train/validation/test pair counts have changed.");
end

audit = struct();
audit.datasetSHA256 = helperComputeFileSHA256(config.DatasetPath);
audit.splitSHA256 = helperComputeFileSHA256(config.SplitManifestPath);
audit.splitCounts = splitCounts;
audit.stateOrder = expectedStateOrder;
audit.fixedTrainingCovarianceDiag = ...
    double(dataset.covarianceStdAssumed(:).').^2;

end

function audit = localAuditWarmArtifact(config, warmHash)
%LOCALAUDITWARMARTIFACT Verify the frozen learned transition identity.

loaded = load(config.WarmArtifactPath, "modelArtifact");

if ~isfield(loaded, "modelArtifact") || ...
        string(loaded.modelArtifact.modelID) ~= "expanded_warm_mean_v1"
    error("Stage4E:WarmArtifactContractMismatch", ...
        "Stage 4E requires expanded_warm_mean_v1.");
end

audit = struct();
audit.modelID = string(loaded.modelArtifact.modelID);
audit.exploratory = logical(loaded.modelArtifact.exploratory);
audit.promoted = logical(loaded.modelArtifact.promoted);
audit.datasetSHA256 = string( ...
    loaded.modelArtifact.datasetProvenance.datasetSHA256);
audit.splitSHA256 = string( ...
    loaded.modelArtifact.splitProvenance.splitManifestSHA256);
audit.sha256 = string(warmHash);

end

function [detectionLogs, truthTables, summary] = ...
        localBuildValidationTuningData(dataset, split, config)
%LOCALBUILDVALIDATIONTUNINGDATA Reserve validation events for tuner use.

[orderedRows, eventID, eventTable] = localFindEvents( ...
    dataset, ...
    split, ...
    "validation");
eventTable = sortrows( ...
    eventTable, ...
    ["pairCount", "sessionID", "icao24", "startTime"], ...
    ["descend", "ascend", "ascend", "ascend"]);
tuningEventCount = min(3, height(eventTable));
eventTable = eventTable(1:tuningEventCount, :);
maximumTuningPairsPerEvent = 120;
detectionLogs = cell(tuningEventCount, 1);
truthTables = cell(tuningEventCount, 1);
eventKeys = strings(tuningEventCount, 1);

for selectedIdx = 1:tuningEventCount
    selectedEventID = eventTable.originalEventID(selectedIdx);
    eventRows = orderedRows(eventID == selectedEventID);
    eventRows = eventRows(1:min(maximumTuningPairsPerEvent, numel(eventRows)));
    state = [ ...
        double(dataset.previousState(eventRows, :)); ...
        double(dataset.nextState(eventRows(end), :))];
    eventStart = dataset.metadata.timeUtcK(eventRows(1));
    timeSeconds = [ ...
        seconds(dataset.metadata.timeUtcK(eventRows) - eventStart); ...
        seconds(dataset.metadata.timeUtcNext(eventRows(end)) - eventStart)];
    measurementNoise = diag([30, 30, 45].^2);
    covarianceDiag = double(dataset.previousCovarianceDiag(eventRows(1), :));
    detectionLog = cell(numel(timeSeconds), 1);

    for sampleIdx = 1:numel(timeSeconds)
        attributes = struct( ...
            "InitialVelocity", state(1, [2, 4, 6]), ...
            "InitialCovarianceDiag", covarianceDiag);
        detectionLog{sampleIdx} = objectDetection( ...
            timeSeconds(sampleIdx), ...
            state(sampleIdx, [1, 3, 5]).', ...
            MeasurementNoise=measurementNoise, ...
            ObjectAttributes={attributes});
    end

    detectionLogs{selectedIdx} = detectionLog;
    truthTables{selectedIdx} = timetable( ...
        seconds(timeSeconds), ...
        state, ...
        'VariableNames', {'State'});
    eventKeys(selectedIdx) = ...
        string(eventTable.sessionID(selectedIdx)) + "::" + ...
        string(eventTable.icao24(selectedIdx));
end

summary = struct();
summary.split = "validation";
summary.eventCount = tuningEventCount;
summary.eventKeys = eventKeys;
summary.detectionCount = sum(cellfun(@numel, detectionLogs));
summary.maximumPairsPerEvent = maximumTuningPairsPerEvent;
summary.testRowsUsed = false;
summary.seed = config.Seed;

end

function tuning = localResolveTuning( ...
        detectionLogs, ...
        truthTables, ...
        validationSummary, ...
        config, ...
        warmAudit, ...
        inputAudit)
%LOCALRESOLVETUNING Create or load the frozen validation-only tuning result.

if config.RetuneFilters
    tuning = helperTuneStage4EFilters( ...
        detectionLogs, ...
        truthTables, ...
        Seed=config.Seed + 4001, ...
        Verbose=config.Verbose);
    tuning.validationSummary = validationSummary;
    tuning.datasetSHA256 = inputAudit.datasetSHA256;
    tuning.splitSHA256 = inputAudit.splitSHA256;
    tuning.warmSHA256 = warmAudit.sha256;
    tuning.frozenAt = datetime("now", "TimeZone", "UTC");
    tuningPathFolder = string(fileparts(config.TuningPath));

    if ~isfolder(tuningPathFolder)
        mkdir(tuningPathFolder);
    end

    stage4ETuning = tuning;
    save(config.TuningPath, "stage4ETuning", "-v7.3");
elseif exist(config.TuningPath, "file") == 2
    loaded = load(config.TuningPath, "stage4ETuning");
    tuning = loaded.stage4ETuning;
else
    error("Stage4E:MissingFrozenTuning", ...
        "No frozen Stage 4E tuning exists. Run once with RetuneFilters=true.");
end

requiredFields = [ ...
    "completed", ...
    "validationOnly", ...
    "networkTrainingPerformed", ...
    "parameters", ...
    "datasetSHA256", ...
    "splitSHA256", ...
    "warmSHA256", ...
    "frozenAt", ...
    "validationSummary"];

if any(~isfield(tuning, requiredFields)) || ...
        ~tuning.completed || ...
        ~tuning.validationOnly || ...
        tuning.networkTrainingPerformed || ...
        ~strcmpi(tuning.datasetSHA256, inputAudit.datasetSHA256) || ...
        ~strcmpi(tuning.splitSHA256, inputAudit.splitSHA256) || ...
        ~strcmpi(tuning.warmSHA256, warmAudit.sha256)
    error("Stage4E:InvalidFrozenTuning", ...
        "Frozen tuning must match validation-only data and Stage 4C hashes.");
end

end

function [sequences, summary] = localBuildSyntheticSequences( ...
        dataset, split, config)
%LOCALBUILDSYNTHETICSEQUENCES Generate full-grid recursive test sequences.

trainMask = split == "train";
empiricalDtSeconds = double(dataset.dtSeconds(trainMask));
fixedCovarianceDiag = median( ...
    double(dataset.previousCovarianceDiag(trainMask, :)), ...
    1);

if config.BenchmarkMode == "full"
    canonicalDurationSeconds = 120;
    mixedDurationSeconds = 600;
    inDistributionCount = 6;
    outOfDistributionCount = 3;
else
    canonicalDurationSeconds = 30;
    mixedDurationSeconds = 60;
    inDistributionCount = 2;
    outOfDistributionCount = 1;
end

canonical = helperGenerateStage4DSyntheticBenchmark( ...
    "canonical", ...
    BenchmarkMode=config.BenchmarkMode, ...
    Seed=config.Seed, ...
    EmpiricalDtSeconds=empiricalDtSeconds, ...
    PreviousCovarianceDiag=fixedCovarianceDiag, ...
    DurationSeconds=canonicalDurationSeconds, ...
    SampleRateHz=2);
inDistribution = helperGenerateStage4DSyntheticBenchmark( ...
    "in_distribution", ...
    BenchmarkMode=config.BenchmarkMode, ...
    Seed=config.Seed, ...
    EmpiricalDtSeconds=empiricalDtSeconds, ...
    PreviousCovarianceDiag=fixedCovarianceDiag, ...
    TrajectoryCount=inDistributionCount, ...
    DurationSeconds=mixedDurationSeconds, ...
    SampleRateHz=2);
outOfDistribution = helperGenerateStage4DSyntheticBenchmark( ...
    "out_of_distribution", ...
    BenchmarkMode=config.BenchmarkMode, ...
    Seed=config.Seed, ...
    EmpiricalDtSeconds=empiricalDtSeconds, ...
    PreviousCovarianceDiag=fixedCovarianceDiag, ...
    TrajectoryCount=outOfDistributionCount, ...
    DurationSeconds=mixedDurationSeconds, ...
    SampleRateHz=2);
sequences = [ ...
    localConvertSyntheticBenchmark(canonical, "synthetic_canonical"); ...
    localConvertSyntheticBenchmark( ...
    inDistribution, ...
    "synthetic_in_distribution"); ...
    localConvertSyntheticBenchmark( ...
    outOfDistribution, ...
    "synthetic_out_of_distribution")];
summary = struct();
summary.canonicalTrajectoryCount = 7;
summary.inDistributionTrajectoryCount = inDistributionCount;
summary.outOfDistributionTrajectoryCount = outOfDistributionCount;
summary.profileCount = height(canonical.profileTable);
summary.sequenceCount = numel(sequences);
summary.sampleRateHz = 2;
summary.canonicalDurationSeconds = canonicalDurationSeconds;
summary.mixedDurationSeconds = mixedDurationSeconds;
summary.fullLatentGridScored = all(arrayfun( ...
    @(sequence) all(sequence.scoringMask(2:end)), ...
    sequences));
summary.motionScenarios = unique(string({sequences.motionScenario}));
summary.profiles = unique(string({sequences.profile}));

end

function sequences = localConvertSyntheticBenchmark(benchmark, domain)
%LOCALCONVERTSYNTHETICBENCHMARK Build recursive sequence records.

sourceSequences = benchmark.sequences;
sequences = repmat(localEmptySequence(), numel(sourceSequences), 1);

for sequenceIdx = 1:numel(sourceSequences)
    source = sourceSequences(sequenceIdx);
    sampleCount = numel(source.truthTimeSeconds);
    measurementState = NaN(sampleCount, 6);
    measurementState(source.observationTruthIndex, :) = ...
        source.observationState;
    updateMask = false(sampleCount, 1);
    updateMask(source.observationTruthIndex) = true;
    scoringMask = true(sampleCount, 1);
    scoringMask(1) = false;

    if source.profile(1) == "degraded"
        measurementNoise = diag([30, 30, 45].^2);
    else
        measurementNoise = eye(3);
    end

    sequences(sequenceIdx) = localEmptySequence();
    sequences(sequenceIdx).domain = string(domain);
    sequences(sequenceIdx).profile = source.profile(1);
    sequences(sequenceIdx).caseID = source.caseID(1);
    sequences(sequenceIdx).eventID = ...
        string(domain) + "::" + source.caseID(1);
    sequences(sequenceIdx).motionScenario = source.motionScenario(1);
    sequences(sequenceIdx).timeSeconds = source.truthTimeSeconds;
    sequences(sequenceIdx).referenceState = source.truthState;
    sequences(sequenceIdx).measurementState = measurementState;
    sequences(sequenceIdx).updateMask = updateMask;
    sequences(sequenceIdx).scoringMask = scoringMask;
    sequences(sequenceIdx).measurementNoise = measurementNoise;
    sequences(sequenceIdx).initialCovarianceDiag = ...
        source.previousCovarianceDiag(1, :);
    sequences(sequenceIdx).motionMode = source.truthMotionMode;
    sequences(sequenceIdx).targetReference = "latent_kinematic_truth";
    sequences(sequenceIdx).receiverOriginLLA = ...
        [42.2999333, -71.349333, 15.0];
end

end

function [sequences, protocol] = localBuildRealSequences( ...
        dataset, split, splitName, config)
%LOCALBUILDREALSEQUENCES Reserve score rows before applying update dropout.

[orderedRows, eventID, eventTable] = localFindEvents( ...
    dataset, ...
    split, ...
    splitName);
eventTable = sortrows( ...
    eventTable, ...
    ["pairCount", "sessionID", "icao24", "startTime"], ...
    ["descend", "ascend", "ascend", "ascend"]);

if splitName == "validation"
    eventLimit = 3;
elseif config.BenchmarkMode == "full"
    eventLimit = 40;
else
    eventLimit = 4;
end

if config.BenchmarkMode == "smoke"
    maximumPairsPerEvent = 240;
else
    maximumPairsPerEvent = Inf;
end

eventTable = eventTable(1:min(eventLimit, height(eventTable)), :);
profileNames = [ ...
    "baseline"; ...
    "random_dropout_10"; ...
    "random_dropout_25"; ...
    "burst_outage"];
sequences = repmat( ...
    localEmptySequence(), ...
    height(eventTable)*numel(profileNames), ...
    1);
stream = RandStream("mt19937ar", "Seed", config.Seed + 5001);
sequenceIndex = 0;

for selectedIdx = 1:height(eventTable)
    selectedEventID = eventTable.originalEventID(selectedIdx);
    eventRows = orderedRows(eventID == selectedEventID);

    if isfinite(maximumPairsPerEvent)
        eventRows = eventRows( ...
            1:min(maximumPairsPerEvent, numel(eventRows)));
    end

    state = [ ...
        double(dataset.previousState(eventRows, :)); ...
        double(dataset.nextState(eventRows(end), :))];
    eventStart = dataset.metadata.timeUtcK(eventRows(1));
    timeSeconds = [ ...
        seconds(dataset.metadata.timeUtcK(eventRows) - eventStart); ...
        seconds(dataset.metadata.timeUtcNext(eventRows(end)) - eventStart)];
    scoringMask = false(numel(timeSeconds), 1);
    scoringMask(3:5:end) = true;

    if ~any(scoringMask)
        scoringMask(end) = true;
    end

    updateCandidateMask = ~scoringMask;
    updateCandidateMask(1) = true;
    eventKey = ...
        string(eventTable.sessionID(selectedIdx)) + "::" + ...
        string(eventTable.icao24(selectedIdx)) + "::" + ...
        string(eventTable.startTime(selectedIdx), "yyyyMMdd'T'HHmmss");

    for profileIdx = 1:numel(profileNames)
        profileName = profileNames(profileIdx);
        updateMask = localApplyRealDropout( ...
            updateCandidateMask, ...
            profileName, ...
            stream);
        sequenceIndex = sequenceIndex + 1;
        sequences(sequenceIndex) = localEmptySequence();
        sequences(sequenceIndex).domain = "real_adsb";
        sequences(sequenceIndex).profile = profileName;
        sequences(sequenceIndex).caseID = ...
            eventKey + "__" + profileName;
        sequences(sequenceIndex).eventID = eventKey;
        sequences(sequenceIndex).motionScenario = "observed_adsb";
        sequences(sequenceIndex).timeSeconds = timeSeconds;
        sequences(sequenceIndex).referenceState = state;
        sequences(sequenceIndex).measurementState = state;
        sequences(sequenceIndex).updateMask = updateMask;
        sequences(sequenceIndex).scoringMask = scoringMask;
        sequences(sequenceIndex).measurementNoise = diag([30, 30, 45].^2);
        sequences(sequenceIndex).initialCovarianceDiag = ...
            double(dataset.previousCovarianceDiag(eventRows(1), :));
        sequences(sequenceIndex).motionMode = ...
            repmat("unlabeled_real_adsb", numel(timeSeconds), 1);
        sequences(sequenceIndex).targetReference = "adsb_scoring_proxy";
        sequences(sequenceIndex).receiverOriginLLA = ...
            double(dataset.metadata.receiverOriginLLA(eventRows(1), :));
    end
end

protocol = struct();
protocol.split = string(splitName);
protocol.eventCount = height(eventTable);
protocol.profileNames = profileNames;
protocol.scoringStride = 5;
protocol.scoringRowsReservedBeforeDropout = true;
protocol.scoringReportsUsedForCorrection = any(arrayfun( ...
    @(sequence) any(sequence.scoringMask & sequence.updateMask), ...
    sequences));
protocol.sameScoringRowsAcrossProfiles = ...
    localSameScoringRowsAcrossProfiles(sequences);
protocol.targetReference = "adsb_scoring_proxy";
protocol.maximumPairsPerEvent = maximumPairsPerEvent;

end

function updateMask = localApplyRealDropout( ...
        updateCandidateMask, profileName, stream)
%LOCALAPPLYREALDROPOUT Drop only non-scoring update candidates.

updateMask = updateCandidateMask;
candidateRows = find(updateCandidateMask);
candidateRows(candidateRows == 1) = [];

switch profileName
    case "baseline"
        % Keep every non-scoring update candidate.
    case "random_dropout_10"
        dropped = rand(stream, numel(candidateRows), 1) < 0.10;
        updateMask(candidateRows(dropped)) = false;
    case "random_dropout_25"
        dropped = rand(stream, numel(candidateRows), 1) < 0.25;
        updateMask(candidateRows(dropped)) = false;
    case "burst_outage"
        outageCount = min( ...
            numel(candidateRows), ...
            max(1, round(0.20*numel(candidateRows))));

        if outageCount > 0
            maximumStart = numel(candidateRows) - outageCount + 1;
            outageStart = randi(stream, maximumStart);
            droppedRows = candidateRows( ...
                outageStart:(outageStart + outageCount - 1));
            updateMask(droppedRows) = false;
        end
    otherwise
        error("Stage4E:UnknownRealProfile", ...
            "Unknown real ADS-B profile: %s", profileName);
end

updateMask(1) = true;
updateMask(~updateCandidateMask) = false;

end

function [orderedRows, eventID, eventTable] = ...
        localFindEvents(dataset, split, splitName)
%LOCALFINDEVENTS Identify contiguous events from one frozen split.

selectedRows = find(split == splitName);
ordering = table( ...
    string(dataset.metadata.sessionID(selectedRows)), ...
    lower(strtrim(string(dataset.metadata.hex(selectedRows)))), ...
    dataset.metadata.timeUtcK(selectedRows), ...
    dataset.metadata.timeUtcNext(selectedRows), ...
    selectedRows, ...
    'VariableNames', [ ...
        "sessionID", ...
        "icao24", ...
        "timeUtcK", ...
        "timeUtcNext", ...
        "datasetRow"]);
ordering = sortrows( ...
    ordering, ...
    ["sessionID", "icao24", "timeUtcK", "timeUtcNext", "datasetRow"]);
orderedRows = ordering.datasetRow;
newEvent = true(height(ordering), 1);

if height(ordering) > 1
    sameTrack = ...
        ordering.sessionID(2:end) == ordering.sessionID(1:end - 1) & ...
        ordering.icao24(2:end) == ordering.icao24(1:end - 1);
    adjacentTime = abs(seconds( ...
        ordering.timeUtcK(2:end) - ...
        ordering.timeUtcNext(1:end - 1))) <= 1e-6;
    newEvent(2:end) = ~(sameTrack & adjacentTime);
end

eventID = cumsum(newEvent);
eventCount = max(eventID);
firstIndex = accumarray(eventID, (1:numel(eventID)).', [], @min);
lastIndex = accumarray(eventID, (1:numel(eventID)).', [], @max);
firstRows = orderedRows(firstIndex);
lastRows = orderedRows(lastIndex);
eventTable = table( ...
    (1:eventCount).', ...
    string(dataset.metadata.sessionID(firstRows)), ...
    lower(strtrim(string(dataset.metadata.hex(firstRows)))), ...
    dataset.metadata.timeUtcK(firstRows), ...
    dataset.metadata.timeUtcNext(lastRows), ...
    accumarray(eventID, 1), ...
    'VariableNames', [ ...
        "originalEventID", ...
        "sessionID", ...
        "icao24", ...
        "startTime", ...
        "endTime", ...
        "pairCount"]);

end

function same = localSameScoringRowsAcrossProfiles(sequences)
%LOCALSAMESCORINGROWSACROSSPROFILES Check profile-independent score rows.

same = true;
eventIDs = unique(string({sequences.eventID}), "stable");

for eventIdx = 1:numel(eventIDs)
    selected = sequences( ...
        string({sequences.eventID}) == eventIDs(eventIdx));
    referenceTime = selected(1).timeSeconds(selected(1).scoringMask);

    for profileIdx = 2:numel(selected)
        same = same && isequal( ...
            selected(profileIdx).timeSeconds( ...
            selected(profileIdx).scoringMask), ...
            referenceTime);
    end
end

end

function sequence = localEmptySequence()
%LOCALEMPTYSEQUENCE Define the shared recursive evaluation schema.

sequence = struct( ...
    "domain", "", ...
    "profile", "", ...
    "caseID", "", ...
    "eventID", "", ...
    "motionScenario", "", ...
    "timeSeconds", zeros(0, 1), ...
    "referenceState", zeros(0, 6), ...
    "measurementState", zeros(0, 6), ...
    "updateMask", false(0, 1), ...
    "scoringMask", false(0, 1), ...
    "measurementNoise", eye(3), ...
    "initialCovarianceDiag", zeros(1, 6), ...
    "motionMode", strings(0, 1), ...
    "targetReference", "", ...
    "receiverOriginLLA", zeros(1, 3));

end

function equal = localSequencesEqual(first, second)
%LOCALSEQUENCESEQUAL Compare deterministic real dropout and score masks.

equal = numel(first) == numel(second);

if ~equal
    return;
end

for sequenceIdx = 1:numel(first)
    equal = equal && ...
        first(sequenceIdx).caseID == second(sequenceIdx).caseID && ...
        isequal(first(sequenceIdx).timeSeconds, second(sequenceIdx).timeSeconds) && ...
        isequal(first(sequenceIdx).updateMask, second(sequenceIdx).updateMask) && ...
        isequal(first(sequenceIdx).scoringMask, second(sequenceIdx).scoringMask);
end

end

function artifactAudit = localBuildArtifactAudit( ...
        config, ...
        warmAudit, ...
        inputAudit, ...
        tuning, ...
        warmHashBefore, ...
        warmHashAfter)
%LOCALBUILDARTIFACTAUDIT Record frozen identities and training boundaries.

artifactAudit = table( ...
    [ ...
        "warm_model_identity"; ...
        "warm_hash_before"; ...
        "warm_hash_after"; ...
        "warm_hash_unchanged"; ...
        "warm_hash_matches_expected"; ...
        "dataset_hash_matches_model"; ...
        "split_hash_matches_model"; ...
        "tuning_uses_validation_only"; ...
        "network_training_performed"; ...
        "network_predicts_covariance"], ...
    [ ...
        warmAudit.modelID; ...
        string(warmHashBefore); ...
        string(warmHashAfter); ...
        localBooleanText(strcmpi(warmHashBefore, warmHashAfter)); ...
        localBooleanText(strcmpi(warmHashBefore, config.ExpectedWarmSHA256)); ...
        localBooleanText(strcmpi( ...
        inputAudit.datasetSHA256, ...
        warmAudit.datasetSHA256)); ...
        localBooleanText(strcmpi( ...
        inputAudit.splitSHA256, ...
        warmAudit.splitSHA256)); ...
        localBooleanText(tuning.validationOnly); ...
        localBooleanText(tuning.networkTrainingPerformed); ...
        "false"], ...
    'VariableNames', ["check", "value"]);

end

function verificationTable = localBuildVerificationTable( ...
        evaluation, ...
        realProtocol, ...
        syntheticSummary, ...
        tuning, ...
        config, ...
        tuningFrozenBeforeTest, ...
        evaluationStartedAt, ...
        deterministicRealDropout, ...
        warmHashBefore, ...
        warmHashAfter)
%LOCALBUILDVERIFICATIONTABLE Consolidate executable Stage 4E invariants.

requiredMotions = [ ...
    "cv_level", ...
    "horizontal_acceleration", ...
    "left_turn", ...
    "motion_transitions"];
check = [ ...
    "identical_filter_inputs"; ...
    "identical_filter_initialization"; ...
    "scheduled_corrections_applied"; ...
    "real_scoring_reports_never_corrected"; ...
    "same_real_scoring_rows_across_profiles"; ...
    "deterministic_real_dropout"; ...
    "monotonic_time"; ...
    "finite_recursive_states"; ...
    "positive_definite_covariance"; ...
    "coasting_during_outages"; ...
    "full_synthetic_truth_grid_scored"; ...
    "known_motion_cases_present"; ...
    "tuning_validation_only"; ...
    "tuning_frozen_before_test"; ...
    "no_neural_training"; ...
    "warm_hash_unchanged"; ...
    "warm_hash_matches_expected"];
passed = [ ...
    evaluation.audit.identicalInputsAcrossFilters; ...
    evaluation.audit.identicalInitializationAcrossFilters; ...
    evaluation.audit.scheduledCorrectionsApplied; ...
    ~realProtocol.scoringReportsUsedForCorrection; ...
    realProtocol.sameScoringRowsAcrossProfiles; ...
    deterministicRealDropout; ...
    evaluation.audit.monotonicTime; ...
    evaluation.audit.finiteStates; ...
    evaluation.audit.positiveDefiniteCovariance; ...
    evaluation.audit.coastingOccurred; ...
    syntheticSummary.fullLatentGridScored; ...
    all(ismember(requiredMotions, syntheticSummary.motionScenarios)); ...
    tuning.validationOnly && ~tuning.validationSummary.testRowsUsed; ...
    tuningFrozenBeforeTest && tuning.frozenAt <= evaluationStartedAt; ...
    ~tuning.networkTrainingPerformed; ...
    strcmpi(warmHashBefore, warmHashAfter); ...
    strcmpi(warmHashBefore, config.ExpectedWarmSHA256)];
detail = [ ...
    "All five filters received one signature per sequence"; ...
    "Projected six-state initialization is identical"; ...
    "Every scheduled update was applied, including initialization"; ...
    "Reserved ADS-B score reports have updateMask=false"; ...
    "All dropout profiles reuse the same score timestamps"; ...
    "Seeded dropout masks reproduced exactly"; ...
    "Every recursive sequence has strictly increasing time"; ...
    "All reported states and errors are finite"; ...
    "Every reported state covariance passed Cholesky factorization"; ...
    "At least one interval propagated without correction"; ...
    "Every post-initial synthetic truth sample was scored"; ...
    join(requiredMotions, ", "); ...
    "trackingFilterTuner used validation events only"; ...
    string(tuning.frozenAt); ...
    "The frozen network was used for inference only"; ...
    string(warmHashAfter); ...
    string(config.ExpectedWarmSHA256)];
verificationTable = table(check, passed, detail);

end

function configTable = localBuildConfigurationTable( ...
        config, syntheticSummary, realProtocol, validationSummary)
%LOCALBUILDCONFIGURATIONTABLE Build a compact reproducibility record.

configTable = table( ...
    [ ...
        "benchmark_mode"; ...
        "random_seed"; ...
        "filter_count"; ...
        "synthetic_sample_rate_hz"; ...
        "canonical_truth_trajectories"; ...
        "in_distribution_truth_trajectories"; ...
        "out_of_distribution_truth_trajectories"; ...
        "real_test_events"; ...
        "real_dropout_profiles"; ...
        "validation_tuning_events"; ...
        "real_scoring_stride"], ...
    [ ...
        config.BenchmarkMode; ...
        string(config.Seed); ...
        "5"; ...
        string(syntheticSummary.sampleRateHz); ...
        string(syntheticSummary.canonicalTrajectoryCount); ...
        string(syntheticSummary.inDistributionTrajectoryCount); ...
        string(syntheticSummary.outOfDistributionTrajectoryCount); ...
        string(realProtocol.eventCount); ...
        string(numel(realProtocol.profileNames)); ...
        string(validationSummary.eventCount); ...
        string(realProtocol.scoringStride)], ...
    'VariableNames', ["setting", "value"]);

end

function auditTable = localBuildNativeFunctionAudit()
%LOCALBUILDNATIVEFUNCTIONAUDIT Record toolbox functions used by Stage 4E.

auditTable = table( ...
    [ ...
        "CV recursive estimator"; ...
        "CA recursive estimator"; ...
        "CT recursive estimator"; ...
        "Multiple-model estimator"; ...
        "Learned recursive estimator"; ...
        "Position measurement models"; ...
        "Validation-only tuning"; ...
        "Synthetic truth"; ...
        "Geographic review"], ...
    [ ...
        "trackingEKF, constvel, constveljac"; ...
        "trackingEKF, constacc, constaccjac"; ...
        "trackingEKF, constturn, constturnjac"; ...
        "trackingIMM, switchimm"; ...
        "trackingUKF"; ...
        "cvmeas, cameas, ctmeas"; ...
        "trackingFilterTuner, tunableFilterProperties"; ...
        "kinematicTrajectory"; ...
        "trackingGlobeViewer, geoTrajectory"], ...
    [ ...
        "Position-only recursive CV updates"; ...
        "Position-only recursive CA updates"; ...
        "Position-only recursive CT updates"; ...
        "Native CV/CA/CT mode interaction"; ...
        "Frozen warm state transition with independent UKF covariance"; ...
        "Rectangular ENU position correction"; ...
        "Process noise and IMM transition probabilities"; ...
        "Independent latent state grid"; ...
        "Representative recursive paths"], ...
    'VariableNames', [ ...
        "workflowNeed", ...
        "nativeMATLABFunction", ...
        "stage4EUse"]);

end

function paths = localBuildOutputPaths(config)
%LOCALBUILDOUTPUTPATHS Define Stage 4E result artifacts.

paths = struct();
paths.outputFolder = config.OutputFolder;
paths.results = config.ResultsPath;
paths.tuning = config.TuningPath;
paths.metrics = fullfile(config.OutputFolder, "stage4EMetrics.csv");
paths.eventMetrics = fullfile( ...
    config.OutputFolder, ...
    "stage4EEventMetrics.csv");
paths.motionMetrics = fullfile( ...
    config.OutputFolder, ...
    "stage4EMotionMetrics.csv");
paths.outageMetrics = fullfile( ...
    config.OutputFolder, ...
    "stage4EOutageAgeMetrics.csv");
paths.eventWinRates = fullfile( ...
    config.OutputFolder, ...
    "stage4EEventWinRates.csv");
paths.consistency = fullfile( ...
    config.OutputFolder, ...
    "stage4EConsistencyMetrics.csv");
paths.runtime = fullfile(config.OutputFolder, "stage4ERuntime.csv");
paths.inputAudit = fullfile( ...
    config.OutputFolder, ...
    "stage4EInputAudit.csv");
paths.verification = fullfile( ...
    config.OutputFolder, ...
    "stage4EVerification.csv");
paths.summaryFigure = fullfile( ...
    config.OutputFolder, ...
    "stage4E_recursive_filter_summary.png");

end

function localWriteResults(results)
%LOCALWRITERESULTS Save the MAT artifact and detailed CSV tables.

stage4EResults = results;
save(results.paths.results, "stage4EResults", "-v7.3");
writetable(results.metricTable, results.paths.metrics);
writetable(results.eventMetricTable, results.paths.eventMetrics);
writetable(results.motionMetricTable, results.paths.motionMetrics);
writetable(results.outageAgeMetricTable, results.paths.outageMetrics);
writetable(results.eventWinRateTable, results.paths.eventWinRates);
writetable(results.consistencyTable, results.paths.consistency);
writetable(results.runtimeTable, results.paths.runtime);
writetable(results.inputAuditTable, results.paths.inputAudit);
writetable(results.verificationTable, results.paths.verification);

end

function value = localTextScalar(value, argumentName, allowEmpty)
%LOCALTEXTSCALAR Normalize a text option.

isCharacterVector = ischar(value) && (isrow(value) || isempty(value));
isStringScalar = isstring(value) && isscalar(value);

if ~isCharacterVector && ~isStringScalar
    error("Stage4E:InvalidTextOption", ...
        "%s must be a character vector or string scalar.", argumentName);
end

value = strtrim(string(value));

if ismissing(value) || (~allowEmpty && strlength(value) == 0)
    error("Stage4E:InvalidTextOption", ...
        "%s must not be empty.", argumentName);
end

end

function value = localLogicalScalar(value, argumentName)
%LOCALLOGICALSCALAR Validate a scalar logical-like option.

if ~(islogical(value) || isnumeric(value)) || ...
        ~isscalar(value) || ...
        ~isfinite(double(value))
    error("Stage4E:InvalidLogicalOption", ...
        "%s must be a finite scalar logical value.", argumentName);
end

value = logical(value);

end

function resolvedPath = localResolvePath(projectRoot, value, defaultPath)
%LOCALRESOLVEPATH Resolve optional paths relative to the project.

value = localTextScalar(value, "path", true);

if strlength(value) == 0
    value = string(defaultPath);
end

if localIsAbsolutePath(value)
    resolvedPath = localCanonicalPath(value);
else
    resolvedPath = localCanonicalPath(fullfile(projectRoot, value));
end

end

function canonicalPath = localCanonicalPath(pathValue)
%LOCALCANONICALPATH Normalize a path without requiring it to exist.

try
    canonicalPath = string(java.io.File(char(pathValue)).getCanonicalPath());
catch err
    error("Stage4E:PathResolutionFailed", ...
        "Unable to resolve path %s: %s", pathValue, err.message);
end

end

function tf = localIsAbsolutePath(pathValue)
%LOCALISABSOLUTEPATH Identify Windows or UNC absolute paths.

pathValue = char(pathValue);
tf = ~isempty(regexp(pathValue, '^[A-Za-z]:[\\/]', 'once')) || ...
    startsWith(pathValue, "\\") || ...
    startsWith(pathValue, "/");

end

function text = localBooleanText(value)
%LOCALBOOLEANTEXT Convert a scalar logical to lowercase text.

if value
    text = "true";
else
    text = "false";
end

end
