function results = runStage4DFrozenWarmCharacterization(varargin)
%RUNSTAGE4DFROZENWARMCHARACTERIZATION Characterize the frozen warm predictor.
% The benchmark compares one-step predictions from the Stage 4C warm
% network with constvel on identical information. Constacc and constturn
% are reported separately because they use one causal predecessor.

projectRoot = string(fileparts(mfilename("fullpath")));
parser = inputParser;
parser.FunctionName = mfilename;
addParameter(parser, "ProjectRoot", projectRoot);
addParameter(parser, "BenchmarkMode", "smoke");
addParameter(parser, "Seed", 123);
addParameter(parser, "WarmArtifactPath", "");
addParameter(parser, "DatasetPath", "");
addParameter(parser, "SplitManifestPath", "");
addParameter(parser, "OutputFolder", "");
addParameter(parser, "ResultsPath", "");
addParameter(parser, "PredictionMiniBatchSize", 8192);
addParameter(parser, "ConfidenceLevel", 0.95);
addParameter(parser, "VerifyInputHashes", true);
addParameter(parser, "CreatePlots", true);
addParameter(parser, "Verbose", true);
parse(parser, varargin{:});

config = localBuildConfig(parser.Results);
localValidateConfig(config);
benchmarkTimer = tic;

if config.Verbose
    fprintf("Stage 4D frozen-warm characterization\n");
    fprintf("Benchmark mode:\t%s\n", config.BenchmarkMode);
    fprintf("Warm artifact:\t%s\n", config.WarmArtifactPath);
end

warmHashBefore = helperComputeFileSHA256(config.WarmArtifactPath);
[warmModel, warmAudit] = localLoadAndAuditWarmModel( ...
    config.WarmArtifactPath, ...
    warmHashBefore);
[dataset, split, inputAudit] = localLoadAndAuditFrozenInputs(config, warmAudit);
trainMask = split == "train";
empiricalDtSeconds = dataset.dtSeconds(trainMask);
previousCovarianceDiag = median( ...
    dataset.previousCovarianceDiag(trainMask, :), ...
    1);

canonicalBenchmark = helperGenerateStage4DSyntheticBenchmark( ...
    "canonical", ...
    BenchmarkMode=config.BenchmarkMode, ...
    Seed=config.Seed, ...
    EmpiricalDtSeconds=empiricalDtSeconds, ...
    PreviousCovarianceDiag=previousCovarianceDiag);
canonicalRepeat = helperGenerateStage4DSyntheticBenchmark( ...
    "canonical", ...
    BenchmarkMode=config.BenchmarkMode, ...
    Seed=config.Seed, ...
    EmpiricalDtSeconds=empiricalDtSeconds, ...
    PreviousCovarianceDiag=previousCovarianceDiag);
deterministicGeneration = localPairSetsEqual( ...
    canonicalBenchmark.pairSet, ...
    canonicalRepeat.pairSet);
clear canonicalRepeat
canonicalEvaluation = helperEvaluateStage4DPredictors( ...
    canonicalBenchmark.pairSet, ...
    warmModel, ...
    PredictionMiniBatchSize=config.PredictionMiniBatchSize, ...
    ConfidenceLevel=config.ConfidenceLevel);
canonicalEvidence = rmfield(canonicalBenchmark, ["pairSet", "sequences"]);
clear canonicalBenchmark

inDistributionBenchmark = helperGenerateStage4DSyntheticBenchmark( ...
    "in_distribution", ...
    BenchmarkMode=config.BenchmarkMode, ...
    Seed=config.Seed, ...
    EmpiricalDtSeconds=empiricalDtSeconds, ...
    PreviousCovarianceDiag=previousCovarianceDiag);
inDistributionEvaluation = helperEvaluateStage4DPredictors( ...
    inDistributionBenchmark.pairSet, ...
    warmModel, ...
    PredictionMiniBatchSize=config.PredictionMiniBatchSize, ...
    ConfidenceLevel=config.ConfidenceLevel);
inputPreview = localBuildInputPreview(inDistributionBenchmark.sequences);
inDistributionEvidence = rmfield( ...
    inDistributionBenchmark, ...
    ["pairSet", "sequences"]);
clear inDistributionBenchmark

outOfDistributionBenchmark = helperGenerateStage4DSyntheticBenchmark( ...
    "out_of_distribution", ...
    BenchmarkMode=config.BenchmarkMode, ...
    Seed=config.Seed, ...
    EmpiricalDtSeconds=empiricalDtSeconds, ...
    PreviousCovarianceDiag=previousCovarianceDiag);
outOfDistributionEvaluation = helperEvaluateStage4DPredictors( ...
    outOfDistributionBenchmark.pairSet, ...
    warmModel, ...
    PredictionMiniBatchSize=config.PredictionMiniBatchSize, ...
    ConfidenceLevel=config.ConfidenceLevel);
outOfDistributionEvidence = rmfield( ...
    outOfDistributionBenchmark, ...
    ["pairSet", "sequences"]);
clear outOfDistributionBenchmark

realBenchmark = helperBuildStage4DRealDropoutBenchmark( ...
    dataset, ...
    split, ...
    BenchmarkMode=config.BenchmarkMode, ...
    Seed=config.Seed, ...
    PreviousCovarianceDiag=previousCovarianceDiag);
realEvaluation = helperEvaluateStage4DPredictors( ...
    realBenchmark.pairSet, ...
    warmModel, ...
    PredictionMiniBatchSize=config.PredictionMiniBatchSize, ...
    ConfidenceLevel=config.ConfidenceLevel);
realEvidence = rmfield(realBenchmark, "pairSet");
clear realBenchmark dataset warmModel

metricTable = vertcat( ...
    canonicalEvaluation.metricTable, ...
    inDistributionEvaluation.metricTable, ...
    outOfDistributionEvaluation.metricTable, ...
    realEvaluation.metricTable);
canonicalMetricTable = canonicalEvaluation.canonicalMetricTable;
eventWinRateTable = vertcat( ...
    canonicalEvaluation.eventWinRateTable, ...
    inDistributionEvaluation.eventWinRateTable, ...
    outOfDistributionEvaluation.eventWinRateTable, ...
    realEvaluation.eventWinRateTable);
pairedConfidenceIntervalTable = vertcat( ...
    canonicalEvaluation.pairedConfidenceIntervalTable, ...
    inDistributionEvaluation.pairedConfidenceIntervalTable, ...
    outOfDistributionEvaluation.pairedConfidenceIntervalTable, ...
    realEvaluation.pairedConfidenceIntervalTable);
transitionMetricTable = vertcat( ...
    canonicalEvaluation.transitionMetricTable, ...
    inDistributionEvaluation.transitionMetricTable, ...
    outOfDistributionEvaluation.transitionMetricTable);
runtimeTable = vertcat( ...
    canonicalEvaluation.runtimeTable, ...
    inDistributionEvaluation.runtimeTable, ...
    outOfDistributionEvaluation.runtimeTable, ...
    realEvaluation.runtimeTable);
robustnessTable = localBuildRobustnessTable(metricTable);
headlineMetricTable = localBuildHeadlineMetricTable(metricTable);
headlineComparisonTable = localBuildHeadlineComparisonTable( ...
    pairedConfidenceIntervalTable, ...
    eventWinRateTable);
mixedMotionTable = localBuildMixedMotionTable(metricTable);
realDropoutTable = localBuildRealDropoutTable(metricTable);
nativeFunctionAudit = localBuildNativeFunctionAudit();

warmHashAfter = helperComputeFileSHA256(config.WarmArtifactPath);
artifactAudit = localBuildArtifactAudit( ...
    config, ...
    warmAudit, ...
    inputAudit, ...
    warmHashBefore, ...
    warmHashAfter);
verificationTable = localBuildVerificationTable( ...
    config, ...
    canonicalEvidence, ...
    inDistributionEvidence, ...
    outOfDistributionEvidence, ...
    realEvidence, ...
    canonicalEvaluation, ...
    inDistributionEvaluation, ...
    outOfDistributionEvaluation, ...
    realEvaluation, ...
    deterministicGeneration, ...
    artifactAudit);
limitationsTable = localBuildLimitationsTable();
nextDecision = localBuildNextDecision(headlineComparisonTable);
benchmarkElapsedSeconds = toc(benchmarkTimer);
runtimeTable = [ ...
    runtimeTable; ...
    table( ...
        "all", ...
        "complete_benchmark", ...
        sum(metricTable( ...
        metricTable.comparisonFamily == "same_information" & ...
        metricTable.weighting == "pair_weighted" & ...
        metricTable.modelID == "expanded_warm_mean_v1", ...
        :).sampleCount), ...
        benchmarkElapsedSeconds, ...
        1e6*benchmarkElapsedSeconds / max(1, sum(metricTable( ...
        metricTable.comparisonFamily == "same_information" & ...
        metricTable.weighting == "pair_weighted" & ...
        metricTable.modelID == "expanded_warm_mean_v1", ...
        :).sampleCount)), ...
        'VariableNames', runtimeTable.Properties.VariableNames)];

if ~isfolder(config.OutputFolder)
    mkdir(config.OutputFolder);
end

results = struct();
results.generatedAt = datetime("now", "TimeZone", "UTC");
results.stage = "4D";
results.completed = all(verificationTable.passed);
results.benchmarkMode = config.BenchmarkMode;
results.randomSeed = config.Seed;
results.interpretation = ...
    "Frozen one-step warm-model characterization; not a deployed tracker replacement.";
results.config = localBuildConfigurationTable( ...
    config, ...
    canonicalEvidence, ...
    inDistributionEvidence, ...
    outOfDistributionEvidence, ...
    realEvidence);
results.syntheticObservationProfiles = canonicalEvidence.profileTable;
results.realObservationProfiles = realEvidence.profileTable;
results.inputPreview = inputPreview;
results.nativeFunctionAudit = nativeFunctionAudit;
results.artifactAudit = artifactAudit;
results.verificationTable = verificationTable;
results.canonicalCaseTable = canonicalEvidence.caseTable;
results.canonicalMetricTable = canonicalMetricTable;
results.metricTable = metricTable;
results.headlineMetricTable = headlineMetricTable;
results.headlineComparisonTable = headlineComparisonTable;
results.mixedMotionTable = mixedMotionTable;
results.realDropoutTable = realDropoutTable;
results.eventWinRateTable = eventWinRateTable;
results.pairedConfidenceIntervalTable = pairedConfidenceIntervalTable;
results.transitionMetricTable = transitionMetricTable;
results.robustnessTable = robustnessTable;
results.runtimeTable = runtimeTable;
results.confidenceIntervalMethod = ...
    canonicalEvaluation.confidenceIntervalMethod;
results.errorDifferenceConvention = ...
    canonicalEvaluation.errorDifferenceConvention;
results.causalPolicy = canonicalEvaluation.causalPolicy;
results.syntheticEvidence = struct( ...
    "canonical", canonicalEvidence, ...
    "inDistribution", inDistributionEvidence, ...
    "outOfDistribution", outOfDistributionEvidence);
results.realEvidence = realEvidence;
results.limitationsTable = limitationsTable;
results.nextDecision = nextDecision;
results.trainingPerformed = false;
results.modelPromoted = false;
results.recursiveTrackingEvaluated = false;
results.paths = localBuildOutputPaths(config);
results.figurePaths = struct( ...
    "inputPreview", "", ...
    "motionComparison", "", ...
    "characterization", "");

if config.CreatePlots
    inputPlotOutput = helperPlotStage4DInputPreview( ...
        results.inputPreview, ...
        SavePath=results.paths.inputPreviewFigure);
    motionPlotOutput = helperPlotStage4DMotionComparison( ...
        results, ...
        SavePath=results.paths.motionComparisonFigure);
    plotOutput = helperPlotStage4DCharacterization( ...
        results, ...
        SavePath=results.paths.characterizationFigure);
    results.figurePaths.inputPreview = inputPlotOutput.savePath;
    results.figurePaths.motionComparison = motionPlotOutput.savePath;
    results.figurePaths.characterization = plotOutput.savePath;
end

localWriteResults(results);

if config.Verbose
    fprintf("Stage 4D complete:\t%s\n", string(results.completed));
    fprintf("Results:\t%s\n", results.paths.results);
    fprintf("Decision:\t%s\n", results.nextDecision);
end

end

function preview = localBuildInputPreview(sequences)
%LOCALBUILDINPUTPREVIEW Select one deterministic input-only trajectory.

profileNames = strings(numel(sequences), 1);

for sequenceIdx = 1:numel(sequences)
    profileNames(sequenceIdx) = sequences(sequenceIdx).profile(1);
end
selectedIndex = find(profileNames == "degraded", 1, "first");

if isempty(selectedIndex)
    error("Stage4D:MissingInputPreview", ...
        "The in-distribution benchmark does not contain a degraded sequence.");
end

selected = sequences(selectedIndex);
preview = struct();
preview.caseID = selected.caseID(1);
preview.profile = selected.profile(1);
preview.motionScenario = selected.motionScenario(1);
preview.observationTimeSeconds = selected.observationTimeSeconds;
preview.observationState = selected.observationState;
preview.retainedIntervalSeconds = [ ...
    NaN; ...
    diff(selected.observationTimeSeconds)];
preview.nominalTruthIntervalSeconds = median(diff(selected.truthTimeSeconds));
preview.nominalDropoutFraction = 0.25;
preview.containsPredictions = false;
preview.source = "seeded degraded in-distribution synthetic observations";

end

function config = localBuildConfig(opts)
%LOCALBUILDCONFIG Resolve input and output paths.

config = struct();
config.ProjectRoot = localCanonicalPath(localTextScalar( ...
    opts.ProjectRoot, "ProjectRoot", false));
config.BenchmarkMode = lower(localTextScalar( ...
    opts.BenchmarkMode, "BenchmarkMode", false));
config.Seed = double(opts.Seed);
config.WarmArtifactPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.WarmArtifactPath, ...
    fullfile( ...
        "artifacts", ...
        "stage4CRetrain", ...
        "expandedPost3DayWarmStartMeanMLP_v1.mat"));
config.DatasetPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.DatasetPath, ...
    fullfile( ...
        "artifacts", ...
        "stage4BPostCampaign", ...
        "expanded_post3day_v2", ...
        "stage3CArchiveStatePairDataset.mat"));
config.SplitManifestPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.SplitManifestPath, ...
    fullfile( ...
        "adsb_archive", ...
        "datasetVersions", ...
        "expandedPost3DayICAODisjointSplit_v1.csv"));
config.OutputFolder = localResolvePath( ...
    config.ProjectRoot, ...
    opts.OutputFolder, ...
    fullfile("artifacts", "stage4DFrozenWarmCharacterization"));
config.ResultsPath = localResolvePath( ...
    config.ProjectRoot, ...
    opts.ResultsPath, ...
    fullfile( ...
        config.OutputFolder, ...
        "stage4DFrozenWarmCharacterizationResults.mat"));
config.PredictionMiniBatchSize = double(opts.PredictionMiniBatchSize);
config.ConfidenceLevel = double(opts.ConfidenceLevel);
config.VerifyInputHashes = localLogicalScalar( ...
    opts.VerifyInputHashes, ...
    "VerifyInputHashes");
config.CreatePlots = localLogicalScalar(opts.CreatePlots, "CreatePlots");
config.Verbose = localLogicalScalar(opts.Verbose, "Verbose");
config.ExpectedWarmSHA256 = ...
    "1999F972DBDABE67F45953C52CD4CDB1620F1FECF1716C075F391064D3B32FFE";

end

function localValidateConfig(config)
%LOCALVALIDATECONFIG Reject missing inputs and Stage 4C output collisions.

if ~ismember(config.BenchmarkMode, ["smoke", "full"])
    error("Stage4D:InvalidBenchmarkMode", ...
        "BenchmarkMode must be smoke or full.");
end

requiredFiles = [ ...
    config.WarmArtifactPath, ...
    config.DatasetPath, ...
    config.SplitManifestPath];

for pathIdx = 1:numel(requiredFiles)
    if exist(requiredFiles(pathIdx), "file") ~= 2
        error("Stage4D:MissingInputFile", ...
            "Required frozen input was not found: %s", requiredFiles(pathIdx));
    end
end

validateattributes(config.Seed, ...
    {'numeric'}, {'scalar', 'integer', 'nonnegative', 'finite'}, ...
    mfilename, "Seed");
validateattributes(config.PredictionMiniBatchSize, ...
    {'numeric'}, {'scalar', 'integer', 'positive'}, ...
    mfilename, "PredictionMiniBatchSize");
validateattributes(config.ConfidenceLevel, ...
    {'numeric'}, {'scalar', 'real', '>', 0, '<', 1}, ...
    mfilename, "ConfidenceLevel");

protectedPaths = lower([ ...
    config.WarmArtifactPath, ...
    config.DatasetPath, ...
    config.SplitManifestPath]);

if ismember(lower(config.ResultsPath), protectedPaths)
    error("Stage4D:ProtectedArtifactCollision", ...
        "Stage 4D results cannot overwrite a frozen input.");
end

stage4CFolder = lower(localCanonicalPath(fullfile( ...
    config.ProjectRoot, ...
    "artifacts", ...
    "stage4CRetrain")));

if startsWith(lower(config.OutputFolder), stage4CFolder)
    error("Stage4D:Stage4COutputCollision", ...
        "Stage 4D outputs must not be written beneath the Stage 4C folder.");
end

end

function [warmModel, audit] = localLoadAndAuditWarmModel(artifactPath, artifactHash)
%LOCALLOADANDAUDITWARMMODEL Load only the frozen warm Stage 4C artifact.

try
    loaded = load(artifactPath, "net", "normalization", "modelArtifact");
catch err
    error("Stage4D:WarmArtifactLoadFailed", ...
        "Unable to load the frozen warm artifact: %s", err.message);
end

if ~isfield(loaded, "net") || ...
        ~isfield(loaded, "normalization") || ...
        ~isfield(loaded, "modelArtifact") || ...
        isempty(loaded.net)
    error("Stage4D:InvalidWarmArtifact", ...
        "The warm artifact lacks its network, normalization, or identity record.");
end

modelID = string(loaded.modelArtifact.modelID);

if modelID ~= "expanded_warm_mean_v1"
    error("Stage4D:WrongModelIdentity", ...
        "Stage 4D requires expanded_warm_mean_v1, not %s.", modelID);
end

expectedFeatureNames = [ ...
    "vx"; ...
    "vy"; ...
    "z"; ...
    "vz"; ...
    "dtSeconds"; ...
    "previousCovarianceDiag_x"; ...
    "previousCovarianceDiag_vx"; ...
    "previousCovarianceDiag_y"; ...
    "previousCovarianceDiag_vy"; ...
    "previousCovarianceDiag_z"; ...
    "previousCovarianceDiag_vz"; ...
    "vxTimesDt"; ...
    "vyTimesDt"; ...
    "vzTimesDt"; ...
    "constvelDelta_x"; ...
    "constvelDelta_vx"; ...
    "constvelDelta_y"; ...
    "constvelDelta_vy"; ...
    "constvelDelta_z"; ...
    "constvelDelta_vz"];
featureNames = string(loaded.normalization.features.featureNames(:));
layers = loaded.net.Layers;
fullyConnectedMask = arrayfun( ...
    @(layer) isa(layer, "nnet.cnn.layer.FullyConnectedLayer"), ...
    layers);
fullyConnectedLayers = layers(fullyConnectedMask);
fullyConnectedSizes = arrayfun( ...
    @(layer) layer.OutputSize, ...
    fullyConnectedLayers);
architecturePassed = ...
    layers(1).InputSize == 20 && ...
    isequal(fullyConnectedSizes(:).', [64, 64, 6]);
identityPassed = ...
    modelID == "expanded_warm_mean_v1" && ...
    logical(loaded.modelArtifact.exploratory) && ...
    ~logical(loaded.modelArtifact.promoted);
featureContractPassed = isequal(featureNames, expectedFeatureNames);

if ~identityPassed || ~architecturePassed || ~featureContractPassed
    error("Stage4D:WarmArtifactContractMismatch", ...
        "The frozen warm artifact no longer matches the 20-64-64-6 Stage 4C contract.");
end

warmModel = struct();
warmModel.net = loaded.net;
warmModel.featureNormalization = loaded.normalization.features;
warmModel.targetNormalization = loaded.normalization.target;

audit = struct();
audit.path = string(artifactPath);
audit.sha256 = string(artifactHash);
audit.modelID = modelID;
audit.exploratory = logical(loaded.modelArtifact.exploratory);
audit.promoted = logical(loaded.modelArtifact.promoted);
audit.identityPassed = identityPassed;
audit.architecturePassed = architecturePassed;
audit.featureContractPassed = featureContractPassed;
audit.datasetProvenance = loaded.modelArtifact.datasetProvenance;
audit.splitProvenance = loaded.modelArtifact.splitProvenance;
audit.loadedModelArtifactPaths = string(artifactPath);
audit.loadedScratchArtifact = false;
audit.loadedStage3AArtifact = false;

end

function [dataset, split, audit] = localLoadAndAuditFrozenInputs(config, warmAudit)
%LOCALLOADANDAUDITFROZENINPUTS Verify dataset and global split provenance.

try
    dataset = load( ...
        config.DatasetPath, ...
        "previousState", ...
        "nextState", ...
        "dtSeconds", ...
        "previousCovarianceDiag", ...
        "metadata", ...
        "stateOrder");
catch err
    error("Stage4D:DatasetLoadFailed", ...
        "Unable to load the frozen Expanded-3Day dataset: %s", err.message);
end

rowCount = size(dataset.previousState, 1);
expectedStateOrder = ["x", "vx", "y", "vy", "z", "vz"];

if rowCount ~= 457903 || ...
        ~isequal(size(dataset.previousState), [rowCount, 6]) || ...
        ~isequal(size(dataset.nextState), [rowCount, 6]) || ...
        ~isequal(size(dataset.previousCovarianceDiag), [rowCount, 6]) || ...
        numel(dataset.dtSeconds) ~= rowCount || ...
        height(dataset.metadata) ~= rowCount || ...
        any(string(dataset.stateOrder(:).') ~= expectedStateOrder)
    error("Stage4D:DatasetContractMismatch", ...
        "The frozen Expanded-3Day dataset contract has changed.");
end

manifest = readtable(config.SplitManifestPath, TextType="string");
[found, manifestRow] = ismember( ...
    lower(strtrim(string(dataset.metadata.hex))), ...
    lower(strtrim(string(manifest.icao24))));

if ~all(found)
    error("Stage4D:SplitMembershipMismatch", ...
        "Every dataset ICAO must occur in the frozen split manifest.");
end

split = lower(strtrim(string(manifest.split(manifestRow))));
splitCounts = [ ...
    sum(split == "train"), ...
    sum(split == "validation"), ...
    sum(split == "test")];

if ~isequal(splitCounts, [277959, 86420, 93524])
    error("Stage4D:SplitCountMismatch", ...
        "The frozen train/validation/test pair counts have changed.");
end

datasetHash = helperComputeFileSHA256(config.DatasetPath);
splitHash = helperComputeFileSHA256(config.SplitManifestPath);
recordedDatasetHash = string(warmAudit.datasetProvenance.datasetSHA256);
recordedSplitHash = string(warmAudit.splitProvenance.splitManifestSHA256);
hashesMatch = ...
    strcmpi(datasetHash, recordedDatasetHash) && ...
    strcmpi(splitHash, recordedSplitHash);

if config.VerifyInputHashes && ~hashesMatch
    error("Stage4D:FrozenInputHashMismatch", ...
        "Dataset or split hash differs from the warm model's Stage 4C provenance.");
end

audit = struct();
audit.datasetPath = config.DatasetPath;
audit.datasetSHA256 = datasetHash;
audit.recordedDatasetSHA256 = recordedDatasetHash;
audit.splitManifestPath = config.SplitManifestPath;
audit.splitManifestSHA256 = splitHash;
audit.recordedSplitManifestSHA256 = recordedSplitHash;
audit.hashesMatchWarmProvenance = hashesMatch;
audit.splitCounts = splitCounts;
audit.stateOrder = expectedStateOrder;
audit.finiteStates = ...
    all(isfinite(dataset.previousState), "all") && ...
    all(isfinite(dataset.nextState), "all");
audit.positiveDt = all(dataset.dtSeconds > 0);

end

function equal = localPairSetsEqual(firstPairSet, secondPairSet)
%LOCALPAIRSETSEQUAL Verify exact seeded canonical regeneration.

numericFields = [ ...
    "previousState", ...
    "targetState", ...
    "previousCovarianceDiag", ...
    "dtSeconds", ...
    "timeKSeconds", ...
    "timeNextSeconds", ...
    "eventID", ...
    "transitionOffsetSeconds"];
textFields = [ ...
    "caseID", ...
    "profile", ...
    "motionScenario", ...
    "motionMode", ...
    "targetReference"];
equal = true;

for fieldIdx = 1:numel(numericFields)
    fieldName = numericFields(fieldIdx);
    equal = equal && isequaln( ...
        firstPairSet.(fieldName), ...
        secondPairSet.(fieldName));
end

for fieldIdx = 1:numel(textFields)
    fieldName = textFields(fieldIdx);
    equal = equal && isequal( ...
        firstPairSet.(fieldName), ...
        secondPairSet.(fieldName));
end

end

function robustnessTable = localBuildRobustnessTable(metricTable)
%LOCALBUILDROBUSTNESSTABLE Express profile degradation relative to baseline.

robustnessTable = metricTable( ...
    metricTable.weighting == "pair_weighted" & ...
    metricTable.caseID == "all", :);
rowCount = height(robustnessTable);
positionReference = NaN(rowCount, 1);
velocityReference = NaN(rowCount, 1);

for rowIdx = 1:rowCount
    if robustnessTable.domain(rowIdx) == "real_adsb"
        referenceProfile = "baseline";
    else
        referenceProfile = "ideal";
    end

    referenceMask = ...
        robustnessTable.domain == robustnessTable.domain(rowIdx) & ...
        robustnessTable.profile == referenceProfile & ...
        robustnessTable.comparisonFamily == ...
        robustnessTable.comparisonFamily(rowIdx) & ...
        robustnessTable.modelID == robustnessTable.modelID(rowIdx);
    positionReference(rowIdx) = ...
        robustnessTable.positionRMSEMeters(referenceMask);
    velocityReference(rowIdx) = ...
        robustnessTable.velocityRMSEMetersPerSecond(referenceMask);
end

robustnessTable.referencePositionRMSEMeters = positionReference;
robustnessTable.positionRMSEChangePercent = ...
    100*(robustnessTable.positionRMSEMeters - positionReference) ./ ...
    positionReference;
robustnessTable.referenceVelocityRMSEMetersPerSecond = velocityReference;
robustnessTable.velocityRMSEChangePercent = ...
    100*(robustnessTable.velocityRMSEMetersPerSecond - velocityReference) ./ ...
    velocityReference;

end

function headlineTable = localBuildHeadlineMetricTable(metricTable)
%LOCALBUILDHEADLINEMETRICTABLE Select the same-information benchmark rows.

headlineTable = metricTable( ...
    metricTable.comparisonFamily == "same_information" & ...
    metricTable.caseID == "all", :);

end

function comparisonTable = localBuildHeadlineComparisonTable( ...
        confidenceTable, eventWinRateTable)
%LOCALBUILDHEADLINECOMPARISONTABLE Join paired intervals and event win rates.

comparisonTable = confidenceTable( ...
    confidenceTable.comparisonFamily == "same_information" & ...
    confidenceTable.comparatorModelID == "constvel", :);
winRows = eventWinRateTable( ...
    eventWinRateTable.comparisonFamily == "same_information" & ...
    eventWinRateTable.comparatorModelID == "constvel", :);
joinKeys = [ ...
    "domain", ...
    "profile", ...
    "comparisonFamily", ...
    "comparatorModelID", ...
    "eventCount"];
comparisonTable = innerjoin( ...
    comparisonTable, ...
    winRows, ...
    Keys=joinKeys);

end

function mixedTable = localBuildMixedMotionTable(metricTable)
%LOCALBUILDMIXEDMOTIONTABLE Select compact ID and OOD pair metrics.

mixedTable = metricTable( ...
    ismember(metricTable.domain, [ ...
    "synthetic_in_distribution", ...
    "synthetic_out_of_distribution"]) & ...
    metricTable.weighting == "pair_weighted" & ...
    metricTable.caseID == "all", :);

end

function realTable = localBuildRealDropoutTable(metricTable)
%LOCALBUILDREALDROPOUTTABLE Select held-out real ADS-B pair metrics.

realTable = metricTable( ...
    metricTable.domain == "real_adsb" & ...
    metricTable.weighting == "pair_weighted" & ...
    metricTable.caseID == "all", :);

end

function auditTable = localBuildNativeFunctionAudit()
%LOCALBUILDNATIVEFUNCTIONAUDIT Record native MATLAB analogues used.

auditTable = table( ...
    [ ...
        "Independent synthetic truth"; ...
        "Same-information propagation"; ...
        "Causal acceleration propagation"; ...
        "Causal turn propagation"; ...
        "Frozen network inference"; ...
        "Paired confidence interval"; ...
        "Review visualization"], ...
    [ ...
        "kinematicTrajectory"; ...
        "constvel"; ...
        "constacc"; ...
        "constturn"; ...
        "minibatchpredict"; ...
        "tinv"; ...
        "tiledlayout, nexttile"], ...
    [ ...
        "Rate-driven ENU position and velocity truth"; ...
        "Current observed state and dt only"; ...
        "Raw predecessor-derived 3-D acceleration"; ...
        "Raw predecessor-derived wrapped heading rate"; ...
        "Frozen Stage 4C warm dlnetwork"; ...
        "Two-sided paired event-RMSE mean interval"; ...
        "Transition and robustness panels"], ...
    'VariableNames', [ ...
        "workflowNeed", ...
        "nativeMATLABFunction", ...
        "stage4DUse"]);

end

function artifactAudit = localBuildArtifactAudit( ...
        config, warmAudit, inputAudit, warmHashBefore, warmHashAfter)
%LOCALBUILDARTIFACTAUDIT Summarize frozen-input identity and integrity.

artifactAudit = table( ...
    [ ...
        "warm_model_identity"; ...
        "warm_model_hash_before"; ...
        "warm_model_hash_after"; ...
        "warm_model_hash_unchanged"; ...
        "expected_warm_hash"; ...
        "dataset_hash_matches_model"; ...
        "split_hash_matches_model"; ...
        "loaded_scratch_model"; ...
        "loaded_stage3a_model"; ...
        "stage4d_output_is_separate"], ...
    [ ...
        string(warmAudit.modelID); ...
        string(warmHashBefore); ...
        string(warmHashAfter); ...
        localBooleanText(strcmpi(warmHashBefore, warmHashAfter)); ...
        localBooleanText(strcmpi(warmHashBefore, config.ExpectedWarmSHA256)); ...
        localBooleanText(strcmpi( ...
        inputAudit.datasetSHA256, ...
        inputAudit.recordedDatasetSHA256)); ...
        localBooleanText(strcmpi( ...
        inputAudit.splitManifestSHA256, ...
        inputAudit.recordedSplitManifestSHA256)); ...
        localBooleanText(warmAudit.loadedScratchArtifact); ...
        localBooleanText(warmAudit.loadedStage3AArtifact); ...
        localBooleanText(~startsWith( ...
        lower(config.OutputFolder), ...
        lower(fullfile(config.ProjectRoot, "artifacts", "stage4CRetrain"))))], ...
    'VariableNames', ["check", "value"]);

end

function verificationTable = localBuildVerificationTable( ...
        config, ...
        canonicalEvidence, ...
        inDistributionEvidence, ...
        outOfDistributionEvidence, ...
        realEvidence, ...
        canonicalEvaluation, ...
        inDistributionEvaluation, ...
        outOfDistributionEvaluation, ...
        realEvaluation, ...
        deterministicGeneration, ...
        artifactAudit)
%LOCALBUILDVERIFICATIONTABLE Consolidate executable benchmark invariants.

truthAudit = vertcat( ...
    canonicalEvidence.truthAuditTable, ...
    inDistributionEvidence.truthAuditTable, ...
    outOfDistributionEvidence.truthAuditTable);
evaluationAudits = [ ...
    canonicalEvaluation.audit, ...
    inDistributionEvaluation.audit, ...
    outOfDistributionEvaluation.audit, ...
    realEvaluation.audit];
artifactValue = @(name) artifactAudit.value(artifactAudit.check == name);

if config.BenchmarkMode == "full"
    expectedInDistributionCount = 100;
    expectedOutOfDistributionCount = 50;
    expectedMixedDurationSeconds = 600;
    expectedRealBaselinePairs = 93524;
else
    expectedInDistributionCount = 4;
    expectedOutOfDistributionCount = 2;
    expectedMixedDurationSeconds = 120;
    expectedRealBaselinePairs = realEvidence.audit.frozenTestPairCount;
end

check = [ ...
    "canonical_case_count"; ...
    "in_distribution_trajectory_count"; ...
    "out_of_distribution_trajectory_count"; ...
    "mixed_trajectory_duration"; ...
    "deterministic_generation"; ...
    "continuous_synthetic_trajectories"; ...
    "monotonic_synthetic_time"; ...
    "finite_synthetic_states"; ...
    "finite_real_states"; ...
    "monotonic_real_time"; ...
    "real_baseline_matches_frozen_test_rows"; ...
    "matched_model_rows"; ...
    "no_target_leakage"; ...
    "no_motion_label_leakage"; ...
    "no_scratch_model_loaded"; ...
    "no_stage3a_model_loaded"; ...
    "warm_hash_unchanged"; ...
    "warm_hash_matches_expected"; ...
    "separate_stage4d_output"; ...
    "real_baseline_pair_count"];
passed = [ ...
    height(canonicalEvidence.caseTable) == 21; ...
    inDistributionEvidence.truthTrajectoryCount == expectedInDistributionCount; ...
    outOfDistributionEvidence.truthTrajectoryCount == expectedOutOfDistributionCount; ...
    all(inDistributionEvidence.truthAuditTable.durationSeconds == ...
    expectedMixedDurationSeconds) && ...
    all(outOfDistributionEvidence.truthAuditTable.durationSeconds == ...
    expectedMixedDurationSeconds); ...
    deterministicGeneration; ...
    all(truthAudit.continuousPosition); ...
    all(truthAudit.monotonicTime); ...
    all(truthAudit.finiteState); ...
    realEvidence.audit.finiteStates; ...
    realEvidence.audit.monotonicTime; ...
    realEvidence.audit.baselineMatchesFrozenRows; ...
    all([evaluationAudits.matchedComparisonRows]); ...
    ~any([evaluationAudits.targetStateUsedForPrediction]); ...
    ~any([evaluationAudits.motionLabelUsedForPrediction]); ...
    artifactValue("loaded_scratch_model") == "false"; ...
    artifactValue("loaded_stage3a_model") == "false"; ...
    artifactValue("warm_model_hash_unchanged") == "true"; ...
    artifactValue("expected_warm_hash") == "true"; ...
    artifactValue("stage4d_output_is_separate") == "true"; ...
    realEvidence.audit.baselinePairCount == expectedRealBaselinePairs];
detail = [ ...
    string(height(canonicalEvidence.caseTable)); ...
    string(inDistributionEvidence.truthTrajectoryCount); ...
    string(outOfDistributionEvidence.truthTrajectoryCount); ...
    string(expectedMixedDurationSeconds) + " s"; ...
    "Seeded canonical generation reproduced exactly"; ...
    "Position increments satisfy velocity/acceleration continuity bounds"; ...
    "All synthetic time vectors and pairs are increasing"; ...
    "All synthetic truth and observed states are finite"; ...
    "All real retained-observation states are finite"; ...
    "All real retained-observation pairs have increasing time"; ...
    "Baseline reconstruction equals sorted frozen test pairs"; ...
    "Every model within each comparison family uses identical rows"; ...
    "Prediction interfaces exclude targetState"; ...
    "Prediction interfaces exclude retrospective motion labels"; ...
    "Only expanded_warm_mean_v1 was loaded"; ...
    "Only expanded_warm_mean_v1 was loaded"; ...
    artifactValue("warm_model_hash_after"); ...
    config.ExpectedWarmSHA256; ...
    config.OutputFolder; ...
    string(realEvidence.audit.baselinePairCount)];
verificationTable = table(check, passed, detail);

end

function limitationsTable = localBuildLimitationsTable()
%LOCALBUILDLIMITATIONSTABLE Keep conclusions inside the approved boundary.

limitationsTable = table( ...
    [ ...
        "One-step scope"; ...
        "Synthetic evidence"; ...
        "ADS-B target"; ...
        "Causal native information"; ...
        "Deferred integration"], ...
    [ ...
        "No recursive state or covariance rollout is evaluated."; ...
        "Synthetic performance cannot establish real-world generalization."; ...
        "Real perturbations score against the next retained ADS-B observation, not latent truth."; ...
        "Constacc and constturn receive one predecessor that warm and constvel do not."; ...
        "trackingIMM and neural filter integration remain deferred."], ...
    'VariableNames', ["limitation", "interpretation"]);

end

function nextDecision = localBuildNextDecision(headlineComparisonTable)
%LOCALBUILDNEXTDECISION Gate any follow-on recursive evaluation.

requiredMask = ...
    ((headlineComparisonTable.domain == "synthetic_in_distribution") & ...
    (headlineComparisonTable.profile == "empirical_timing")) | ...
    ((headlineComparisonTable.domain == "real_adsb") & ...
    (headlineComparisonTable.profile == "baseline"));
requiredRows = headlineComparisonTable(requiredMask, :);
warmWinsWithConfidence = ...
    height(requiredRows) == 2 && ...
    all(requiredRows.positionDifferenceUpper < 0);

if warmWinsWithConfidence
    nextDecision = ...
        "The warm predictor clears the narrow same-information gate; consider a separately approved recursive tracker experiment without promoting this model.";
else
    nextDecision = ...
        "Retain constvel as the deployed prediction reference; do not begin recursive warm-model or trackingIMM integration from Stage 4D evidence.";
end

end

function configTable = localBuildConfigurationTable( ...
        config, ...
        canonicalEvidence, ...
        inDistributionEvidence, ...
        outOfDistributionEvidence, ...
        realEvidence)
%LOCALBUILDCONFIGURATIONTABLE Provide a compact reproducibility record.

configTable = table( ...
    [ ...
        "benchmark_mode"; ...
        "random_seed"; ...
        "synthetic_sample_rate_hz"; ...
        "canonical_cases"; ...
        "in_distribution_truth_trajectories"; ...
        "out_of_distribution_truth_trajectories"; ...
        "mixed_motion_duration_seconds"; ...
        "real_test_trajectories"; ...
        "confidence_level"; ...
        "prediction_minibatch_size"], ...
    [ ...
        string(config.BenchmarkMode); ...
        string(config.Seed); ...
        string(canonicalEvidence.config.sampleRateHz); ...
        string(height(canonicalEvidence.caseTable)); ...
        string(inDistributionEvidence.truthTrajectoryCount); ...
        string(outOfDistributionEvidence.truthTrajectoryCount); ...
        string(inDistributionEvidence.config.durationSeconds); ...
        string(realEvidence.truthTrajectoryCount); ...
        string(config.ConfidenceLevel); ...
        string(config.PredictionMiniBatchSize)], ...
    'VariableNames', ["setting", "value"]);

end

function paths = localBuildOutputPaths(config)
%LOCALBUILDOUTPUTPATHS Define the separate Stage 4D artifact set.

paths = struct();
paths.outputFolder = config.OutputFolder;
paths.results = config.ResultsPath;
paths.metricSummary = fullfile( ...
    config.OutputFolder, ...
    "stage4DMetricSummary.csv");
paths.canonicalMetrics = fullfile( ...
    config.OutputFolder, ...
    "stage4DCanonicalMetrics.csv");
paths.eventWinRates = fullfile( ...
    config.OutputFolder, ...
    "stage4DEventWinRates.csv");
paths.pairedConfidenceIntervals = fullfile( ...
    config.OutputFolder, ...
    "stage4DPairedConfidenceIntervals.csv");
paths.transitionMetrics = fullfile( ...
    config.OutputFolder, ...
    "stage4DTransitionMetrics.csv");
paths.robustnessMetrics = fullfile( ...
    config.OutputFolder, ...
    "stage4DRobustnessMetrics.csv");
paths.runtime = fullfile( ...
    config.OutputFolder, ...
    "stage4DRuntime.csv");
paths.verification = fullfile( ...
    config.OutputFolder, ...
    "stage4DVerification.csv");
paths.characterizationFigure = fullfile( ...
    config.OutputFolder, ...
    "stage4D_transition_and_robustness.png");
paths.inputPreviewFigure = fullfile( ...
    config.OutputFolder, ...
    "stage4D_input_preview.png");
paths.motionComparisonFigure = fullfile( ...
    config.OutputFolder, ...
    "stage4D_motion_type_comparison.png");

end

function localWriteResults(results)
%LOCALWRITERESULTS Save the MAT artifact and review-oriented CSV tables.

stage4DResults = results;
save(results.paths.results, "stage4DResults", "-v7.3");
writetable(results.metricTable, results.paths.metricSummary);
writetable(results.canonicalMetricTable, results.paths.canonicalMetrics);
writetable(results.eventWinRateTable, results.paths.eventWinRates);
writetable( ...
    results.pairedConfidenceIntervalTable, ...
    results.paths.pairedConfidenceIntervals);
writetable(results.transitionMetricTable, results.paths.transitionMetrics);
writetable(results.robustnessTable, results.paths.robustnessMetrics);
writetable(results.runtimeTable, results.paths.runtime);
writetable(results.verificationTable, results.paths.verification);

end

function value = localTextScalar(value, argumentName, allowEmpty)
%LOCALTEXTSCALAR Normalize a text option.

isCharacterVector = ischar(value) && (isrow(value) || isempty(value));
isStringScalar = isstring(value) && isscalar(value);

if ~isCharacterVector && ~isStringScalar
    error("Stage4D:InvalidTextOption", ...
        "%s must be a character vector or string scalar.", argumentName);
end

value = strtrim(string(value));

if ismissing(value) || (~allowEmpty && strlength(value) == 0)
    error("Stage4D:InvalidTextOption", ...
        "%s must not be empty.", argumentName);
end

end

function value = localLogicalScalar(value, argumentName)
%LOCALLOGICALSCALAR Accept scalar logical or numeric zero/one.

isLogicalScalar = islogical(value) && isscalar(value);
isBinaryNumericScalar = isnumeric(value) && isscalar(value) && ...
    isfinite(value) && (value == 0 || value == 1);

if ~isLogicalScalar && ~isBinaryNumericScalar
    error("Stage4D:InvalidLogicalOption", ...
        "%s must be a scalar logical value.", argumentName);
end

value = logical(value);

end

function resolvedPath = localResolvePath( ...
        projectRoot, suppliedPath, defaultPath)
%LOCALRESOLVEPATH Resolve empty, relative, and rooted paths.

suppliedPath = localTextScalar(suppliedPath, "path", true);

if strlength(suppliedPath) == 0
    suppliedPath = string(defaultPath);
end

if localIsAbsolutePath(suppliedPath)
    resolvedPath = suppliedPath;
else
    resolvedPath = fullfile(projectRoot, suppliedPath);
end

resolvedPath = localCanonicalPath(resolvedPath);

end

function canonicalPath = localCanonicalPath(pathValue)
%LOCALCANONICALPATH Normalize a path without requiring it to exist.

try
    canonicalPath = string(java.io.File(char(pathValue)).getCanonicalPath());
catch err
    error("Stage4D:PathResolutionFailed", ...
        "Unable to resolve path %s: %s", pathValue, err.message);
end

end

function tf = localIsAbsolutePath(pathValue)
%LOCALISABSOLUTEPATH Detect Windows and POSIX rooted paths.

normalizedPath = replace(string(pathValue), "\", "/");
tf = startsWith(normalizedPath, "/") || ...
    ~isempty(regexp(char(normalizedPath), "^[A-Za-z]:", "once"));

end

function text = localBooleanText(value)
%LOCALBOOLEANTEXT Render a logical scalar without numeric coercion.

if value
    text = "true";
else
    text = "false";
end

end
