% Generated by MATLAB(R) 24.2 (R2024b) and Radar Toolbox 24.2 (R2024b).
% Generated on: 07-Aug-2025 14:02:43

%% Define system design parameters, target, and environment for the currently selected radar
radar = designRadar('ExampleRadar');
env = radarEnvironment();
rangeLimits = [1.00000e-02 5.00000e+05]; % m
target = radarTarget(radar,env,rangeLimits);
refPd = .9; % Arbitrary value but should match the value chosen when computing the ReferenceRange

% Predict SNR available at the receiving antenna and system processing gain
[availableSNR,processingGain,refRCS,refRange,constraint,detThreshold] = predictSNR(radar,target, refPd);

%% Instantiate radarDataGenerator
radarSensorModel = radarDataGenerator(1, 'No scanning', ...
    'UpdateRate', 1, ...                                      % (Hz)
    'HasNoise', false, ...                                    % Target position noise
    'HasFalseAlarms', false, ...
    'FalseAlarmRate', radar.Pfa, ...
    'HasOcclusion', false, ...
    'RangeResolution', bw2rangeres(radar.PulseBandwidth), ... % (m)
    'HasRangeAmbiguities', false, ...
    'RangeLimits', [0 rangeLimits(2)], ...                    % (m) Can also change to radar.UnambiguousRange
    'HasRangeRate', true, ...
    'RangeRateResolution', radar.RangeRateRes, ...            % (m/s) HasRangeRate must be true
    'RangeRateLimits',1e6*[-1,1], ...                         % (m/s) HasRangeRate must be true
    'HasRangeRateAmbiguities', true, ...                      % HasRangeRate must be true
    'MaxUnambiguousRadialSpeed', radar.MaxSpeed, ...          % HasRangeRateAmbiguities must be true
    'FieldOfView', [180,180], ...                             % (deg) Change to the transmitter beamwidths to limit detections to the half-power beamwidths
    'AzimuthResolution', radar.EffectiveAzRes, ...            % (deg)
    'HasElevation', true, ...
    'ElevationResolution', radar.EffectiveElRes, ...          % (deg) HasElevation must be true
    'Bandwidth', radar.PulseBandwidth, ...                    % (Hz)
    'CenterFrequency',radar.Frequency, ...                    % (Hz) Useful for converting this to a radarTransceiver
    'ReferenceRCS', refRCS ,...                               % (dBsm)
    'ReferenceRange', refRange ,...                           % (m)
    'DetectionProbability', refPd, ...
    'MountingAngles', [0 -radar.TiltAngle 0], ...             % (deg) East-North-Up Cartesian Coordinates
    'MountingLocation', [0 0 0], ...                          % Consider using the platform position instead
    'TargetReportFormat', 'Detections', ...
    'DetectionCoordinates', 'Body'); % Coordinates are relative to the body center, ignoring mounting position and angle

%%
% ------------------------------------------------------------------------
% Local Functions
% ------------------------------------------------------------------------

% Radar design parameters
function radar = designRadar(radarName)
radar.Name = radarName;
radar.AzimuthBeamwidth = [2.2661;2.2661];
radar.ElevationBeamwidth = [2.2661;2.2661];
radar.Frequency = 10000000000; % Hz
radar.Gain = [38,38];
radar.Height = 10; % m
radar.MaxSpeed = 3.18529e+01;
radar.NoiseTemperature = 290;
radar.NumCPIs = 1;
radar.NumCoherentPulses = 1;
radar.NumNonCoherentPulses = 10;
radar.PRF = 4250; % Hz
radar.PeakPower = 315211; % W
radar.Pfa = 1.00000e-06;
radar.Polarization = 'H';
radar.PulseBandwidth = 2.99792e+07; % Hz
radar.Pulsewidth = 3.33550e-08; % s
radar.RangeRateRes = 6.37059e+00;
radar.ReferenceNoiseTemperature = 290;
radar.TiltAngle = 0; % deg
radar.UnambiguousRange = 3.52697e+04;

% Convert frequency to wavelength
radar.Wavelength = freq2wavelen(radar.Frequency); % m

% Calculate system noise
radar.SystemTemperature = radar.NoiseTemperature; % Kelvin

% Calculate angular resolution
radar.EffectiveAzRes = effbeamwidth(radar.AzimuthBeamwidth(1),radar.AzimuthBeamwidth(2));     % deg
radar.EffectiveElRes = effbeamwidth(radar.ElevationBeamwidth(1),radar.ElevationBeamwidth(2)); % deg
end

%%
% Radar environment
function env = radarEnvironment()
env.EarthModel = 'Flat';
env.EffectiveEarthRadius = Inf; % m
env.RefractionExponent = 0;
env.RefractiveIndex = 1;
env.SurfaceHeightStandardDeviation = 0; % m
env.SurfaceRefractivity = 0;
end

%%
% Radar target
function target = radarTarget(radar,env,rangeLimits)
target.ElevationAngle = 0;
target.RCS = 1.00000e-01; % m²
target.SwerlingCase = 'Swerling0';

% Calculate target position ranges
numTargetPositions = 1000;
target.ranges = linspace(rangeLimits(1),rangeLimits(2),numTargetPositions).'; % m
target.validRngIdxs = getValidRangeIdxs(radar,target,env);

% Calculate target height
target.Height = el2height(target.ElevationAngle,radar.Height,target.ranges, ...
    env.EarthModel,env.EffectiveEarthRadius); % m
end

%%
% Calculate propagation factor
function Fprop = propagationFactor(radar,target)
freqRange = [0.95*radar.Frequency 1.05*radar.Frequency];
patternAnglesEl = linspace(-90,90,361);
hTxRx = phased.SincAntennaElement('FrequencyRange',freqRange, ...
    'Beamwidth',[radar.AzimuthBeamwidth(1) radar.ElevationBeamwidth(1)]);
patternTxRxdB = pattern(hTxRx,radar.Frequency,0,patternAnglesEl,'Type','powerdb');
idxs = target.validRngIdxs;
elevationAngles = target.ElevationAngle*ones(size(idxs));
thetaDiff = mod(((elevationAngles - radar.TiltAngle) + 90),180) - 90;
apatternTxRx2 = interp1(patternAnglesEl,patternTxRxdB,thetaDiff).';
apatternTxRx1 = interp1(patternAnglesEl,patternTxRxdB,0).';
Fpattern = -Inf(numel(target.ranges),2);
Fpattern(idxs,:) = (apatternTxRx2.' - apatternTxRx1)*ones(1,2);
Fprop = Fpattern; % dB
end

%%
% Calculate range-dependent factors
function Fcustom = rangeDependentLosses()
Fcustom = 0; % dB
end

%%
% Calculate environmental losses
function [Lgas,Llens,Lprecipitation] = atmosphericLosses(target)
% Calculate atmospheric gas loss
Lgas = zeros(numel(target.ranges),1);
% Calculate lens effect loss
Llens = zeros(numel(target.ranges),1);
% Calculate precipitation loss
Lprecipitation = zeros(numel(target.ranges),1);
end

%%
% Predict SNR available at the receiving antenna and system processing gain
function [availableSNR,processingGain,refRCS,refRange,constraint,detThreshold] = predictSNR(radar,target, refPd)
% Calculate propagation factor
Fprop = propagationFactor(radar,target);

% Calculate environmental losses
[Lgas,Llens,Lprecipitation] = atmosphericLosses(target);
Latmos = sum([Lgas Llens Lprecipitation], 2);

% Calculate range-dependent factors
Fcustom = rangeDependentLosses();


% Calculate signal-to-noise ratio (SNR)
availableSNR = radareqsnr(radar.Wavelength,target.ranges,radar.PeakPower, ...
    radar.Pulsewidth,'Gain',radar.Gain,'RCS',target.RCS,'Ts',radar.SystemTemperature, ...
    'PropagationFactor',Fprop,'AtmosphericLoss',Latmos,'CustomFactor',Fcustom); % dB

% Set design requirements
% Just used for plotting purposes
% constraint.Pd = 7.5000e-01; % Decimal, Threshold
constraint.Pd = 9.0000e-01; % Decimal, Objective
constraint.Range = 3.5000e+04; % m

% Calculate detectability
[detThreshold,DetComponents,componentNames,processingGain] = effectiveDetectability(refPd,radar);
fluctuationLossIdx = contains(componentNames,'Fluctuation loss','IgnoreCase',true);
if any(fluctuationLossIdx)
    fluctuationLoss = DetComponents(fluctuationLossIdx);
else
    fluctuationLoss = 0;
end

% Reference target and range
% Choose RCS to prevent extrapolation in interp1()
refTargetRCS = 10; % (m^2)
refAvailableSNR = radareqsnr(radar.Wavelength,target.ranges,radar.PeakPower, ...
    radar.Pulsewidth,'Gain',radar.Gain,'RCS',refTargetRCS,'Ts',radar.SystemTemperature, ...
    'PropagationFactor',0,'AtmosphericLoss',0,'CustomFactor',0); % dB

% The radarDataGenerator accounts for target fluctuation (if any) during detection and not during its setup
refRange = interp1(refAvailableSNR,target.ranges,detThreshold-fluctuationLoss,'spline','extrap');
refRCS = pow2db(refTargetRCS); % (dBsm)
end

%%
% Animated Plot
function [radarPlotter,FOVPlotter,targetPlotter,targetDetPlotter,falseAlarmDetPlotter] = createTP(waypoints, trajectory, radarPlat, targetPlat)
radarSensorModel = radarPlat.Sensors{1};
figure('Name','Animated Plot');
ax = gca;
tp = theaterPlot('XLimits',[min(waypoints(:,1))*.1 max(waypoints(:,1))],...
    'ZLimits',max(waypoints(:,1))*[-1 1],'YLimits',max(waypoints(:,1))*[-1 1],...
    'AxesUnits',["km","km","km"],'Parent',ax);
view(40,15);grid on;
legend('Location','northwest','BackgroundAlpha',.6)
title('Live Radar Simulation')

trajPlotter = trajectoryPlotter(tp,'DisplayName','Trajectory','LineWidth',2);
plotTrajectory(trajPlotter,{trajectory.Waypoints})

targetPlotter = platformPlotter(tp,'DisplayName','Target', ...
    'Marker','s','MarkerSize',10);
plotPlatform(targetPlotter,targetPlat.Position, ...
    targetPlat.Dimensions,quaternion(targetPlat.Orientation,'rotvecd'))

radarPlotter = platformPlotter(tp,'DisplayName','Radar','Marker','^','MarkerSize',10);
plotPlatform(radarPlotter,radarPlat.Position)
targetDetPlotter = detectionPlotter(tp,'DisplayName','Target Detection','Marker','x','MarkerSize',15);
falseAlarmDetPlotter = detectionPlotter(tp,'DisplayName','False Alarms','MarkerSize',5);

FOVPlotter = coveragePlotter(tp,'DisplayName','Sensor Coverage');
config = coverageConfig(radarSensorModel);
config.Position = radarPlat.Position + radarSensorModel.MountingLocation;
plotCoverage(FOVPlotter,config)
end

%%
% Static Plot
function staticPlot(simSNR,simRanges,target,radar,availableSNR,processingGain,...
    targetDetectionCoords,allFalseAlarmDetectionCoords,targetGTPoses,radarGTPoses,...
    detThreshold,constraint)
plotSNRError(simSNR,simRanges,target,radar,availableSNR,processingGain,detThreshold,constraint);
plotScenario(simSNR,targetDetectionCoords,allFalseAlarmDetectionCoords,targetGTPoses,radarGTPoses);
end

% Compare Expected and Simulated SNR
function plotSNRError(simSNR,simRanges,target,radar,availableSNR,processingGain,detThreshold,constraint)
f = figure('Name', 'SNR vs Range');
f.Position(3:4) = [1000 500];
ax = subplot(2,2,[1,3]);
metricPlot = radarmetricplot(target.ranges*1.0000e-03,availableSNR,detThreshold, ...
    'RadarName',{'Available SNR (expected)'}, ...
    'MetricName','SNR', ...
    'MaxRangeRequirement',constraint.Range*1.0000e-03,...
    'RequirementName','Detectability (Available SNR)', ...
    'RangeUnit','km', ...
    'MetricUnit','dB', ...
    'ShowStoplight',true,...
    'Parent',ax);
hold on

plot(target.ranges/1e3,availableSNR+processingGain,'DisplayName','Radar SNR (expected)','LineWidth',1.5)
scatter(simRanges/1e3,simSNR,'filled','o','DisplayName','Radar SNR (simulated)','LineWidth',1,'MarkerFaceAlpha',.4)
if radar.UnambiguousRange < max(target.ranges)
    xline(radar.UnambiguousRange/1e3,'--','DisplayName','Max Unambiguous Range')
end

subplot(2,2,2)
predSNR = interp1(target.ranges,availableSNR+processingGain,simRanges);
SNRerror = abs(simSNR-predSNR);
SNRerror(1) = NaN; % Close ranges have numerical instability
plot(simRanges/1e3,SNRerror,'.','LineWidth',1)
title('SNR Error')
xlabel('Target Range (km)')
ylabel('SNR (dB)')
grid
if max(SNRerror) - min(SNRerror) < 2
    ylim([min(SNRerror)-1,max(SNRerror)+1])
else
    axis padded
end
xlim(metricPlot.XLim)
end

% Scenario Geometry
function plotScenario(simSNR,targetDetectionCoords,falseAlarmDetectionCoords,targetGTPoses,radarGTPoses)
subplot(2,2,4)
hold on
grid on
colormap parula
c = colorbar;
c.Label.String = 'SNR (dB)';
title('Scenario Geometry')
xlabel('X (km)')
ylabel('Z (km)')
legend('BackgroundAlpha',.6)

if ~isempty(falseAlarmDetectionCoords)
    scatter(falseAlarmDetectionCoords(:,1)/1e3,falseAlarmDetectionCoords(:,3)/1e3,50,'o','DisplayName','False Alarms');
end
scatter(targetDetectionCoords(:,1)/1e3,targetDetectionCoords(:,3)/1e3,50,simSNR,'o','filled','DisplayName','Target Detections');
plot(targetGTPoses(:,1)/1e3,targetGTPoses(:,3)/1e3,'.','DisplayName','Target Platform Truth');
plot(radarGTPoses(:,1)/1e3,radarGTPoses(:,3)/1e3,'^','DisplayName','Radar Platform Truth','LineWidth',2);
axis padded
end

% Find the detection indices for the target and the false alarms
function [targetDetIdx, falseAlarmDetIdx] = findDetIdx(dets)
% The TargetIdx property is nonnegative for detections from true targets
targetDetIdx = cellfun(@(x) x.ObjectAttributes{1,1}.TargetIndex >=0, dets, 'UniformOutput', 1);
targetDetIdx = find(targetDetIdx, 1); % Assumes only one target detection
falseAlarmDetIdx = 1:numel(dets);
falseAlarmDetIdx(targetDetIdx) = [];
end

%%
% Get indices of geometrically valid ranges
function idxs = getValidRangeIdxs(radar,target,env)
anht = radar.Height + 2*env.SurfaceHeightStandardDeviation;
tgtht = inf;
minRng = 0;
maxRng = 2*env.EffectiveEarthRadius + tgtht + anht;
idxs = (target.ranges >= minRng & target.ranges <= maxRng);
end

%%
% Effective detectability factor for the selected radar
function [Dx,Dc,componentNames,processingGain] = effectiveDetectability(Pd,radar)
Pfa = radar.Pfa;
[Dc,componentNames] = detectabilityComponents(Pd,Pfa,radar.NumNonCoherentPulses);
Dx = sum(Dc,2);
processingGain = -sum(Dc(:,2:end),2);
end

%%
% Losses and gains included in the detectability factor
function [Dc,names] = detectabilityComponents(Pd,Pfa,N)
% Single-pulse steady target
D01 = detectability(Pd,Pfa,1,'Swerling0');
% Noncoherent integration gain
D0N = detectability(Pd,Pfa,N);
Gni = D0N - D01;

Dc = [D01 Gni];
names = {'Single-pulse steady target' 'Noncoherent integration gain'};
end
