clear
clc
close all

projectRoot = fileparts(mfilename("fullpath"));
tablesDir = fullfile(projectRoot, "Artifacts", "Tables");
summariesDir = fullfile(projectRoot, "Artifacts", "Summaries");
figuresDir = fullfile(projectRoot, "Artifacts", "Figures");
decksDir = fullfile(projectRoot, "Artifacts", "Decks");

ensureFolder(tablesDir);
ensureFolder(summariesDir);
ensureFolder(figuresDir);
ensureFolder(decksDir);

[assumptionTable, stationSummary, targetPathSummary, coverageResults] = helperBuildSystemPrecheckAssumptions();
decisionMatrix = helperBuildLinkBudgetDecisionMatrix();
westCorridorTargetPathSummary = coverageResults.ByName.WestCorridor.TargetPathSummary;

writeTableArtifact(assumptionTable, ...
    fullfile(tablesDir, "SystemPrecheckAssumptions.csv"), ...
    fullfile(tablesDir, "SystemPrecheckAssumptions.md"), ...
    "# System Precheck Assumptions Table");
writeCsvArtifact(stationSummary, fullfile(tablesDir, "SystemPrecheckAssumptionsSummary.csv"));
writeTableArtifact(targetPathSummary, ...
    fullfile(tablesDir, "BistaticTargetPathSummary.csv"), ...
    fullfile(tablesDir, "BistaticTargetPathSummary.md"), ...
    "# Bistatic Target Path Summary (Recovered-ROI Baseline)");
writeTableArtifact(westCorridorTargetPathSummary, ...
    fullfile(tablesDir, "BistaticTargetPathSummary_WestCorridor.csv"), ...
    fullfile(tablesDir, "BistaticTargetPathSummary_WestCorridor.md"), ...
    "# Bistatic Target Path Summary (West Corridor)");
writeTableArtifact(decisionMatrix, ...
    fullfile(tablesDir, "LinkBudgetDecisionMatrix.csv"), ...
    fullfile(tablesDir, "LinkBudgetDecisionMatrix.md"), ...
    "# Link Budget Decision Matrix");

wgs84 = wgs84Ellipsoid("meter");
lightSpeed = physconst("LightSpeed");
centerFrequency_Hz = stationSummary.CenterFrequency_MHz * 1e6;
wavelength_m = lightSpeed ./ centerFrequency_Hz;
distance_m = distance( ...
    stationSummary.TowerLatitude_deg, ...
    stationSummary.TowerLongitude_deg, ...
    stationSummary.ReceiverLatitude_deg, ...
    stationSummary.ReceiverLongitude_deg, ...
    wgs84);
distance_km = distance_m / 1e3;
freeSpacePathLoss_dB = arrayfun(@fspl, distance_m, wavelength_m);
eirp_dBm = 10 * log10(stationSummary.ERPHorizontal_kW * 1e6) + 2.15;
directPathPowerAfterAntenna_dBm = ...
    eirp_dBm + stationSummary.ReceiverAntennaGain_dBi - freeSpacePathLoss_dB;

sourceLinkTable = table;
sourceLinkTable.Path = stationSummary.Path;
sourceLinkTable.CallSign = stationSummary.CallSign;
sourceLinkTable.CurrentOperationalStatus = stationSummary.CurrentOperationalStatus;
sourceLinkTable.Distance_km = distance_km;
sourceLinkTable.ERPHorizontal_kW = stationSummary.ERPHorizontal_kW;
sourceLinkTable.EIRP_dBm = eirp_dBm;
sourceLinkTable.FreeSpacePathLoss_dB = freeSpacePathLoss_dB;
sourceLinkTable.DirectPathPowerAfterAntenna_dBm = directPathPowerAfterAntenna_dBm;

writeTableArtifact(sourceLinkTable, ...
    fullfile(tablesDir, "SourceViabilitySummary.csv"), ...
    fullfile(tablesDir, "SourceViabilitySummary.md"), ...
    "# Source Viability Summary");

rfResults = buildRfResults(stationSummary, directPathPowerAfterAntenna_dBm);

rfSummaryTable = table;
rfSummaryTable.Path = string({rfResults.Path}).';
rfSummaryTable.CenterFrequency_MHz = [rfResults.CenterFrequency_MHz].';
rfSummaryTable.FilterLoss_dB = [rfResults.FilterLoss_dB].';
rfSummaryTable.CableLoss_dB = [rfResults.CableLoss_dB].';
rfSummaryTable.TargetInputAfterAntenna_dBm = [rfResults.TargetInputAfterAntenna_dBm].';
rfSummaryTable.DirectInputAfterAntenna_dBm = [rfResults.DirectInputAfterAntenna_dBm].';
rfSummaryTable.TargetOutputPower_dBm = [rfResults.TargetOutputPower_dBm].';
rfSummaryTable.DirectOutputPower_dBm = [rfResults.DirectOutputPower_dBm].';
rfSummaryTable.TargetPreProcessingSNR_dB = [rfResults.TargetPreProcessingSNR_dB].';
rfSummaryTable.TargetPostProcessing1sSNR_dB = [rfResults.TargetPostProcessing1sSNR_dB].';
rfSummaryTable.SystemNF_dB = [rfResults.SystemNF_dB].';
rfSummaryTable.TotalGain_dB = [rfResults.TotalGain_dB].';
rfSummaryTable.HeadroomToRecommendedInput_dB = [rfResults.HeadroomToRecommendedInput_dB].';
rfSummaryTable.RecommendedReferenceAttenuation_dB = [rfResults.RecommendedReferenceAttenuation_dB].';

writeTableArtifact(rfSummaryTable, ...
    fullfile(tablesDir, "RFBudgetSummary.csv"), ...
    fullfile(tablesDir, "RFBudgetSummary.md"), ...
    "# RF Budget Summary");

integrationTimes_s = [0.1; 0.5; 1.0; 2.0];
detectabilityTable = helperBuildDetectabilitySummary( ...
    stationSummary, ...
    rfResults, ...
    integrationTimes_s, ...
    "RecoveredRoi", ...
    "recovered-ROI baseline");
writeTableArtifact(detectabilityTable, ...
    fullfile(tablesDir, "DetectabilitySummary.csv"), ...
    fullfile(tablesDir, "DetectabilitySummary.md"), ...
    "# Detectability Summary (Recovered-ROI Baseline)");

westCorridorStationSummary = stationSummary;
westCorridorStationSummary.TargetPathPower_dBm = westCorridorTargetPathSummary.MeanTargetPathPower_dBm;
westCorridorStationSummary.TargetPathBasis = westCorridorTargetPathSummary.TargetPathBasis;
westCorridorRfResults = buildRfResults(westCorridorStationSummary, directPathPowerAfterAntenna_dBm);
westCorridorDetectabilityTable = helperBuildDetectabilitySummary( ...
    westCorridorStationSummary, ...
    westCorridorRfResults, ...
    integrationTimes_s, ...
    "WestCorridor", ...
    "due-west surveillance corridor");
writeTableArtifact(westCorridorDetectabilityTable, ...
    fullfile(tablesDir, "DetectabilitySummary_WestCorridor.csv"), ...
    fullfile(tablesDir, "DetectabilitySummary_WestCorridor.md"), ...
    "# Detectability Summary (West Corridor)");

riskTable = helperBuildRFRiskTable(stationSummary, sourceLinkTable, rfSummaryTable);
writeTableArtifact(riskTable, ...
    fullfile(tablesDir, "RFRiskTable.csv"), ...
    fullfile(tablesDir, "RFRiskTable.md"), ...
    "# RF Risk Table");

summarySpecs = helperBuildSystemPrecheckTextSummaries( ...
    stationSummary, ...
    coverageResults, ...
    decisionMatrix, ...
    riskTable);

for summaryIndex = 1:numel(summarySpecs)
    helperWriteTextSummary( ...
        summarySpecs(summaryIndex).Title, ...
        summarySpecs(summaryIndex).Lines, ...
        fullfile(summariesDir, summarySpecs(summaryIndex).FileName));
end

staleFigurePaths = { ...
    fullfile(figuresDir, "SystemPrecheck_AssumptionsSummary.png"), ...
    fullfile(figuresDir, "SystemPrecheck_DecisionMatrixSummary.png"), ...
    fullfile(figuresDir, "SystemPrecheck_RFRiskSummary.png"), ...
    fullfile(figuresDir, "SystemPrecheck_Boundaries.png"), ...
    fullfile(figuresDir, "SystemPrecheck_RFCaptureChain.png")};

for figureIndex = 1:numel(staleFigurePaths)
    deleteStaleFigure(staleFigurePaths{figureIndex});
end

figurePaths = helperExportSystemPrecheckVisuals( ...
    stationSummary, ...
    sourceLinkTable, ...
    rfSummaryTable, ...
    rfResults, ...
    coverageResults, ...
    westCorridorRfResults, ...
    integrationTimes_s, ...
    figuresDir);

slideSpecs = helperBuildSystemPrecheckSlideSpecs(figurePaths);
generatedDeckPath = helperGenerateSystemPrecheckDeck( ...
    fullfile(decksDir, "SystemPrecheck_TechnicalStory.pptx"), ...
    slideSpecs);

if ~isfile(figurePaths.RFBudgetAnalyzerScreenshot)
    fprintf("Manual RF Budget Analyzer screenshot pending at %s\n", figurePaths.RFBudgetAnalyzerScreenshot);
end

fprintf("Generated tables in %s\n", tablesDir);
fprintf("Generated summaries in %s\n", summariesDir);
fprintf("Generated figures in %s\n", figuresDir);
fprintf("Generated deck at %s\n", generatedDeckPath);

function ensureFolder(folderPath)
if ~isfolder(folderPath)
    mkdir(folderPath);
end
end

function rfResults = buildRfResults(stationSummary, directPathPowerAfterAntenna_dBm)
rfResults = cell(height(stationSummary), 1);

for stationIndex = 1:height(stationSummary)
    stationStruct = table2struct(stationSummary(stationIndex, :));
    rfResults{stationIndex} = helperBuildRfBudgetCase( ...
        stationStruct, ...
        directPathPowerAfterAntenna_dBm(stationIndex));
end

rfResults = vertcat(rfResults{:});
end

function writeCsvArtifact(dataTable, outputPath)
try
    writetable(dataTable, outputPath);
catch writeException
    error( ...
        "generateSystemPrecheckArtifacts:CsvWriteFailed", ...
        "Could not write %s: %s", ...
        outputPath, ...
        writeException.message);
end
end

function writeTableArtifact(dataTable, csvPath, markdownPath, markdownTitle)
writeCsvArtifact(dataTable, csvPath);

try
    helperWriteMarkdownTable(dataTable, markdownPath, markdownTitle);
catch markdownException
    error( ...
        "generateSystemPrecheckArtifacts:MarkdownWriteFailed", ...
        "Could not write %s: %s", ...
        markdownPath, ...
        markdownException.message);
end
end

function deleteStaleFigure(staleFigurePath)
if ~isfile(staleFigurePath)
    return
end

try
    delete(staleFigurePath);
catch deleteException
    warning( ...
        "generateSystemPrecheckArtifacts:DeleteFailed", ...
        "Could not delete stale figure %s: %s", ...
        staleFigurePath, ...
        deleteException.message);
end
end
