function detectabilityTable = helperBuildDetectabilitySummary( ...
    stationSummary, ...
    rfResults, ...
    integrationTimes_s, ...
    analysisName, ...
    analysisDisplayName)
%helperBuildDetectabilitySummary Build a named detectability summary table.
%
% Plain-language concept:
% Detectability should stay tied to the mean target-path power from the
% specific deterministic geometry branch that produced it. This helper turns
% one named coverage analysis plus the shared RF-chain result into a flat
% table of pre-processing and post-processing SNR values across coherent
% integration times.

pathCount = height(stationSummary);
integrationCount = numel(integrationTimes_s);
rowCount = pathCount * integrationCount;

analysisNames = strings(rowCount, 1);
analysisDisplayNames = strings(rowCount, 1);
pathNames = strings(rowCount, 1);
integrationTimeValues_s = zeros(rowCount, 1);
meanTargetPathPowerValues_dBm = zeros(rowCount, 1);
preProcessingSNRValues_dB = zeros(rowCount, 1);
postProcessingSNRValues_dB = zeros(rowCount, 1);
aboveThreshold = false(rowCount, 1);
basisTexts = strings(rowCount, 1);

rowIndex = 1;

for stationIndex = 1:pathCount
    signalBandwidth_Hz = stationSummary.SignalBandwidth_MHz(stationIndex) * 1e6;

    for timeIndex = 1:integrationCount
        integrationGain_dB = 10 * log10(integrationTimes_s(timeIndex) * signalBandwidth_Hz);
        postProcessingSNR_dB = rfResults(stationIndex).TargetPreProcessingSNR_dB + integrationGain_dB;

        analysisNames(rowIndex) = string(analysisName);
        analysisDisplayNames(rowIndex) = string(analysisDisplayName);
        pathNames(rowIndex) = stationSummary.Path(stationIndex);
        integrationTimeValues_s(rowIndex) = integrationTimes_s(timeIndex);
        meanTargetPathPowerValues_dBm(rowIndex) = stationSummary.TargetPathPower_dBm(stationIndex);
        preProcessingSNRValues_dB(rowIndex) = rfResults(stationIndex).TargetPreProcessingSNR_dB;
        postProcessingSNRValues_dB(rowIndex) = postProcessingSNR_dB;
        aboveThreshold(rowIndex) = postProcessingSNR_dB > 13;
        basisTexts(rowIndex) = compose( ...
            "%s detectability uses the %s mean target-path power through the shared RF-chain model.", ...
            stationSummary.Path(stationIndex), ...
            analysisDisplayName);
        rowIndex = rowIndex + 1;
    end
end

detectabilityTable = table( ...
    analysisNames, ...
    analysisDisplayNames, ...
    pathNames, ...
    integrationTimeValues_s, ...
    meanTargetPathPowerValues_dBm, ...
    preProcessingSNRValues_dB, ...
    postProcessingSNRValues_dB, ...
    aboveThreshold, ...
    basisTexts, ...
    'VariableNames', { ...
        'AnalysisName' ...
        'AnalysisDisplayName' ...
        'Path' ...
        'IntegrationTime_s' ...
        'MeanTargetPathPower_dBm' ...
        'PreProcessingSNR_dB' ...
        'PostProcessingSNR_dB' ...
        'Above13dBThreshold' ...
        'DetectabilityBasis'});
end
