function summarySpecs = helperBuildSystemPrecheckTextSummaries(stationSummary, coverageResults, decisionMatrix, riskTable)
%helperBuildSystemPrecheckTextSummaries Build text-backed summaries for files and slides.

newtonIndex = strcmp(stationSummary.Path, "Newton");
hudsonIndex = strcmp(stationSummary.Path, "Hudson");
baselineSummary = coverageResults.ByName.RecoveredRoi.TargetPathSummary;
westCorridorSummary = coverageResults.ByName.WestCorridor.TargetPathSummary;

supportingCount = sum(decisionMatrix.Classification == "supporting");
referenceCount = sum(decisionMatrix.Classification == "reference");
archiveCount = sum(decisionMatrix.Classification == "archive");

retainedLiveScripts = decisionMatrix.Artifact( ...
    decisionMatrix.Classification == "supporting" & endsWith(decisionMatrix.Artifact, ".mlx"));

assumptionLines = [ ...
    compose( ...
        "Newton (%s): %s on RF%d (%s MHz, center %.0f MHz), %.0f kW horizontal ERP, %.0f kW vertical ERP, status %s.", ...
        stationSummary.Role(newtonIndex), ...
        stationSummary.CallSign(newtonIndex), ...
        stationSummary.RFChannel(newtonIndex), ...
        stationSummary.RFRange_MHz(newtonIndex), ...
        stationSummary.CenterFrequency_MHz(newtonIndex), ...
        stationSummary.ERPHorizontal_kW(newtonIndex), ...
        stationSummary.ERPVertical_kW(newtonIndex), ...
        stationSummary.CurrentOperationalStatus(newtonIndex)); ...
    compose( ...
        "Hudson (%s): %s on RF%d (%s MHz, center %.0f MHz), %.0f kW horizontal ERP, %.0f kW vertical ERP, status %s.", ...
        stationSummary.Role(hudsonIndex), ...
        stationSummary.CallSign(hudsonIndex), ...
        stationSummary.RFChannel(hudsonIndex), ...
        stationSummary.RFRange_MHz(hudsonIndex), ...
        stationSummary.CenterFrequency_MHz(hudsonIndex), ...
        stationSummary.ERPHorizontal_kW(hudsonIndex), ...
        stationSummary.ERPVertical_kW(hudsonIndex), ...
        stationSummary.CurrentOperationalStatus(hudsonIndex)); ...
    compose( ...
        "Common receiver assumption: %s at %.6f deg latitude and %.6f deg longitude with a %.1f dBi receive-antenna gain assumption.", ...
        stationSummary.ReceiverName(1), ...
        stationSummary.ReceiverLatitude_deg(1), ...
        stationSummary.ReceiverLongitude_deg(1), ...
        stationSummary.ReceiverAntennaGain_dBi(1)); ...
    compose( ...
        "Recovered-ROI baseline: %.4f to %.4f deg latitude and %.4f to %.4f deg longitude on a %.2f deg grid.", ...
        baselineSummary.RoiMinLatitude_deg(1), ...
        baselineSummary.RoiMaxLatitude_deg(1), ...
        baselineSummary.RoiMinLongitude_deg(1), ...
        baselineSummary.RoiMaxLongitude_deg(1), ...
        baselineSummary.TargetGridSpacing_deg(1)); ...
    compose( ...
        "Recovered-ROI mean target-path power closes at %.2f dBm for Newton and %.2f dBm for Hudson, with horizontal ERP treated as effective transmitted power for consistency with the retained supporting workflow.", ...
        baselineSummary.MeanTargetPathPower_dBm(newtonIndex), ...
        baselineSummary.MeanTargetPathPower_dBm(hudsonIndex)); ...
    compose( ...
        "Due-west surveillance corridor: %.6f to %.6f deg latitude and %.6f to %.6f deg longitude, centered on the receiver latitude and extending 0.50 deg west from the receiver longitude.", ...
        westCorridorSummary.RoiMinLatitude_deg(1), ...
        westCorridorSummary.RoiMaxLatitude_deg(1), ...
        westCorridorSummary.RoiMinLongitude_deg(1), ...
        westCorridorSummary.RoiMaxLongitude_deg(1)); ...
    compose( ...
        "Due-west corridor mean target-path power closes at %.2f dBm for Newton and %.2f dBm for Hudson; the due-west boresight marker is visual only and is not applied as antenna pattern gain.", ...
        westCorridorSummary.MeanTargetPathPower_dBm(newtonIndex), ...
        westCorridorSummary.MeanTargetPathPower_dBm(hudsonIndex))];

decisionLines = [ ...
    "Final evidence path: generated assumptions tables, shared geometry and RF figures, recovered-ROI baseline coverage figures, due-west corridor coverage figures, paired detectability summaries, and the RF risk table."; ...
    compose( ...
        "Decision-matrix triage: %d supporting artifact(s), %d reference artifact(s), and %d archived artifact(s).", ...
        supportingCount, ...
        referenceCount, ...
        archiveCount); ...
    "Retained supporting live scripts remain useful background, but they are not final evidence because they still depend on interactive geometry selection and are not frozen to the cleaned assumptions table."; ...
    "The native RF Budget Analyzer component view is treated as a manual screenshot artifact on a fixed path, not as an automatically captured image."; ...
    compose( ...
        "Supporting live scripts retained for background only: %s.", ...
        join(retainedLiveScripts, ", ")); ...
    "Historical progress decks, predecessors, and autosaves remain available for traceability but stay outside the review-room claim chain."];

selectedRiskTopics = [ ...
    "Direct path"; ...
    "Target path"; ...
    "Headroom"; ...
    "Selectivity"; ...
    "Adjacent channel and interference"; ...
    "Model boundary"];
selectedRiskTable = riskTable(ismember(riskTable.Topic, selectedRiskTopics), :);
riskLines = strings(height(selectedRiskTable), 1);

for riskIndex = 1:height(selectedRiskTable)
    riskLines(riskIndex) = compose( ...
        "%s: %s", ...
        selectedRiskTable.Topic(riskIndex), ...
        selectedRiskTable.CurrentAssessment(riskIndex));
end

boundaryLines = [ ...
    "This package is a system precheck, not end-to-end passive-radar validation."; ...
    "It does not claim measured field detectability or measured target-path validation."; ...
    "It does not claim adjacent-channel robustness without a field spectrum survey."; ...
    "It does not claim synchronization, calibration, DSI cancellation, or clutter-rejection performance."; ...
    "It does claim illuminator viability, RF front-end capturability, and bounded detectability plausibility within those stated limits."];

summarySpecs(1) = struct( ...
    "FileName", "SystemPrecheckAssumptionsSummary.txt", ...
    "Title", "System Precheck Assumptions Summary", ...
    "Lines", assumptionLines);
summarySpecs(2) = struct( ...
    "FileName", "SystemPrecheckDecisionSummary.txt", ...
    "Title", "Link Budget Decision Summary", ...
    "Lines", decisionLines);
summarySpecs(3) = struct( ...
    "FileName", "SystemPrecheckRFRiskSummary.txt", ...
    "Title", "RF Risk Summary", ...
    "Lines", riskLines);
summarySpecs(4) = struct( ...
    "FileName", "SystemPrecheckBoundaries.txt", ...
    "Title", "What This Analysis Does Not Claim", ...
    "Lines", boundaryLines);
end
