function slideSpecs = helperBuildSystemPrecheckSlideSpecs(figurePaths)
%helperBuildSystemPrecheckSlideSpecs Build the fixed slide order for the deck.

manualCaptureLines = [ ...
    "Manual RF Budget Analyzer screenshot pending."; ...
    compose("Expected artifact path: %s", figurePaths.RFBudgetAnalyzerScreenshot); ...
    "Run helperOpenSystemPrecheckRfAnalyzer(""Newton"") in desktop MATLAB."; ...
    "Capture the native show(budget) component view and save it to the fixed path."; ...
    "Regenerate the deck after the screenshot is in place."];

if isfile(figurePaths.RFBudgetAnalyzerScreenshot)
    rfAnalyzerImagePath = figurePaths.RFBudgetAnalyzerScreenshot;
    rfAnalyzerBodyLines = strings(0, 1);
else
    rfAnalyzerImagePath = "";
    rfAnalyzerBodyLines = manualCaptureLines;
end

finalRiskLines = [ ...
    "Direct-path power remains the dominant RF risk and still implies a heavily attenuated reference branch."; ...
    "Target-path strength is deterministic model output, not field-validated aircraft data."; ...
    "Adjacent-channel environment, assembled-chain headroom, and interference tolerance still need bench or field checks."; ...
    "This deck supports pre-hardware plausibility only; it does not claim calibration, DSI cancellation, clutter rejection, or measured detection performance."];

slideSpecs(1) = struct( ...
    "Title", "Assumptions and Geometry Context", ...
    "ImagePath", figurePaths.GeometryOverview, ...
    "BodyLines", strings(0, 1));
slideSpecs(2) = struct( ...
    "Title", "Direct-Path Source Viability", ...
    "ImagePath", figurePaths.SourceViability, ...
    "BodyLines", strings(0, 1));
slideSpecs(3) = struct( ...
    "Title", "RF Chain Gain and Noise Figure", ...
    "ImagePath", figurePaths.RFChainOverview, ...
    "BodyLines", strings(0, 1));
slideSpecs(4) = struct( ...
    "Title", "RF Levels, Headroom, and Reference Attenuation", ...
    "ImagePath", figurePaths.RFLevelsAndHeadroom, ...
    "BodyLines", strings(0, 1));
slideSpecs(5) = struct( ...
    "Title", "RF Budget Analyzer Component View", ...
    "ImagePath", rfAnalyzerImagePath, ...
    "BodyLines", rfAnalyzerBodyLines);
slideSpecs(6) = struct( ...
    "Title", "Recovered-ROI Baseline Target-Grid Setup", ...
    "ImagePath", figurePaths.RecoveredRoiSetup, ...
    "BodyLines", strings(0, 1));
slideSpecs(7) = struct( ...
    "Title", "Recovered-ROI Baseline Newton Bistatic SNR Coverage", ...
    "ImagePath", figurePaths.RecoveredRoiNewtonCoverage, ...
    "BodyLines", strings(0, 1));
slideSpecs(8) = struct( ...
    "Title", "Recovered-ROI Baseline Hudson Bistatic SNR Coverage", ...
    "ImagePath", figurePaths.RecoveredRoiHudsonCoverage, ...
    "BodyLines", strings(0, 1));
slideSpecs(9) = struct( ...
    "Title", "Recovered-ROI Baseline Combined Max-SNR Coverage", ...
    "ImagePath", figurePaths.RecoveredRoiCombinedCoverage, ...
    "BodyLines", strings(0, 1));
slideSpecs(10) = struct( ...
    "Title", "Recovered-ROI Baseline Regional SNR View", ...
    "ImagePath", figurePaths.RecoveredRoiRegionalCoverage, ...
    "BodyLines", strings(0, 1));
slideSpecs(11) = struct( ...
    "Title", "Recovered-ROI Baseline Detectability Summary", ...
    "ImagePath", figurePaths.RecoveredRoiDetectability, ...
    "BodyLines", strings(0, 1));
slideSpecs(12) = struct( ...
    "Title", "West Corridor Due-West Setup", ...
    "ImagePath", figurePaths.WestCorridorSetup, ...
    "BodyLines", strings(0, 1));
slideSpecs(13) = struct( ...
    "Title", "West Corridor Newton Bistatic SNR Coverage", ...
    "ImagePath", figurePaths.WestCorridorNewtonCoverage, ...
    "BodyLines", strings(0, 1));
slideSpecs(14) = struct( ...
    "Title", "West Corridor Hudson Bistatic SNR Coverage", ...
    "ImagePath", figurePaths.WestCorridorHudsonCoverage, ...
    "BodyLines", strings(0, 1));
slideSpecs(15) = struct( ...
    "Title", "West Corridor Combined Max-SNR Coverage", ...
    "ImagePath", figurePaths.WestCorridorCombinedCoverage, ...
    "BodyLines", strings(0, 1));
slideSpecs(16) = struct( ...
    "Title", "West Corridor Regional SNR View", ...
    "ImagePath", figurePaths.WestCorridorRegionalCoverage, ...
    "BodyLines", strings(0, 1));
slideSpecs(17) = struct( ...
    "Title", "West Corridor Detectability Summary", ...
    "ImagePath", figurePaths.WestCorridorDetectability, ...
    "BodyLines", strings(0, 1));
slideSpecs(18) = struct( ...
    "Title", "Risks and Scope Boundaries", ...
    "ImagePath", "", ...
    "BodyLines", finalRiskLines);
end
