function figurePaths = helperExportSystemPrecheckVisuals( ...
    stationSummary, ...
    sourceLinkTable, ...
    rfSummaryTable, ...
    rfResults, ...
    coverageResults, ...
    westCorridorRfResults, ...
    integrationTimes_s, ...
    figuresDir)
%helperExportSystemPrecheckVisuals Export slide-ready visuals for the technical deck.
%
% Plain-language concept:
% The PowerPoint should now show two deterministic geometry branches without
% duplicating the shared direct-path and RF-chain story. This helper exports
% one shared geometry/RF section, the recovered-ROI baseline coverage set,
% and the additive due-west corridor coverage set with explicit naming.

figurePaths = struct;
figurePaths.GeometryOverview = fullfile(figuresDir, "SystemPrecheck_GeometryOverview.png");
figurePaths.SourceViability = fullfile(figuresDir, "SystemPrecheck_SourceViability.png");
figurePaths.RFChainOverview = fullfile(figuresDir, "SystemPrecheck_RFChainOverview.png");
figurePaths.RFLevelsAndHeadroom = fullfile(figuresDir, "SystemPrecheck_RFLevelsAndHeadroom.png");
figurePaths.RecoveredRoiSetup = fullfile(figuresDir, "SystemPrecheck_RoiTargetGridContext.png");
figurePaths.RecoveredRoiNewtonCoverage = fullfile(figuresDir, "SystemPrecheck_NewtonDeterministicSNRCoverage.png");
figurePaths.RecoveredRoiHudsonCoverage = fullfile(figuresDir, "SystemPrecheck_HudsonDeterministicSNRCoverage.png");
figurePaths.RecoveredRoiCombinedCoverage = fullfile(figuresDir, "SystemPrecheck_CombinedDeterministicSNRCoverage.png");
figurePaths.RecoveredRoiRegionalCoverage = fullfile(figuresDir, "SystemPrecheck_RegionalSNRCoverage.png");
figurePaths.RecoveredRoiDetectability = fullfile(figuresDir, "SystemPrecheck_DetectabilityPlausibility.png");
figurePaths.WestCorridorSetup = fullfile(figuresDir, "SystemPrecheck_WestCorridorSetup.png");
figurePaths.WestCorridorNewtonCoverage = fullfile(figuresDir, "SystemPrecheck_WestCorridor_NewtonSNRCoverage.png");
figurePaths.WestCorridorHudsonCoverage = fullfile(figuresDir, "SystemPrecheck_WestCorridor_HudsonSNRCoverage.png");
figurePaths.WestCorridorCombinedCoverage = fullfile(figuresDir, "SystemPrecheck_WestCorridor_CombinedSNRCoverage.png");
figurePaths.WestCorridorRegionalCoverage = fullfile(figuresDir, "SystemPrecheck_WestCorridor_RegionalSNRCoverage.png");
figurePaths.WestCorridorDetectability = fullfile(figuresDir, "SystemPrecheck_WestCorridor_Detectability.png");
figurePaths.RFBudgetAnalyzerScreenshot = fullfile(figuresDir, "SystemPrecheck_RFBudgetAnalyzer_Newton.png");

% Legacy aliases retained for downstream consumers that still expect the
% original recovered-ROI baseline field names.
figurePaths.RoiTargetGridContext = figurePaths.RecoveredRoiSetup;
figurePaths.NewtonCoverage = figurePaths.RecoveredRoiNewtonCoverage;
figurePaths.HudsonCoverage = figurePaths.RecoveredRoiHudsonCoverage;
figurePaths.CombinedCoverage = figurePaths.RecoveredRoiCombinedCoverage;
figurePaths.RegionalCoverage = figurePaths.RecoveredRoiRegionalCoverage;
figurePaths.Detectability = figurePaths.RecoveredRoiDetectability;

coverageLevels_dB = buildCoverageLevels(coverageResults);

createGeometryOverviewFigure(stationSummary, coverageResults, figurePaths.GeometryOverview);
createSourceViabilityFigure(sourceLinkTable, figurePaths.SourceViability);
createRFChainOverviewFigure(rfResults, figurePaths.RFChainOverview);
createRFLevelsFigure(rfSummaryTable, figurePaths.RFLevelsAndHeadroom);

createAnalysisSetupFigure(stationSummary, coverageResults, "RecoveredRoi", figurePaths.RecoveredRoiSetup);
createCoverageFigure( ...
    stationSummary, ...
    coverageResults, ...
    "RecoveredRoi", ...
    "Newton", ...
    coverageLevels_dB, ...
    figurePaths.RecoveredRoiNewtonCoverage);
createCoverageFigure( ...
    stationSummary, ...
    coverageResults, ...
    "RecoveredRoi", ...
    "Hudson", ...
    coverageLevels_dB, ...
    figurePaths.RecoveredRoiHudsonCoverage);
createCombinedCoverageFigure( ...
    stationSummary, ...
    coverageResults, ...
    "RecoveredRoi", ...
    coverageLevels_dB, ...
    figurePaths.RecoveredRoiCombinedCoverage);
createRegionalCoverageFigure( ...
    stationSummary, ...
    coverageResults, ...
    "RecoveredRoi", ...
    coverageLevels_dB, ...
    figurePaths.RecoveredRoiRegionalCoverage);
createDetectabilityFigure( ...
    stationSummary, ...
    rfResults, ...
    integrationTimes_s, ...
    "Recovered-ROI Baseline", ...
    figurePaths.RecoveredRoiDetectability);

createAnalysisSetupFigure(stationSummary, coverageResults, "WestCorridor", figurePaths.WestCorridorSetup);
createCoverageFigure( ...
    stationSummary, ...
    coverageResults, ...
    "WestCorridor", ...
    "Newton", ...
    coverageLevels_dB, ...
    figurePaths.WestCorridorNewtonCoverage);
createCoverageFigure( ...
    stationSummary, ...
    coverageResults, ...
    "WestCorridor", ...
    "Hudson", ...
    coverageLevels_dB, ...
    figurePaths.WestCorridorHudsonCoverage);
createCombinedCoverageFigure( ...
    stationSummary, ...
    coverageResults, ...
    "WestCorridor", ...
    coverageLevels_dB, ...
    figurePaths.WestCorridorCombinedCoverage);
createRegionalCoverageFigure( ...
    stationSummary, ...
    coverageResults, ...
    "WestCorridor", ...
    coverageLevels_dB, ...
    figurePaths.WestCorridorRegionalCoverage);
createDetectabilityFigure( ...
    stationSummary, ...
    westCorridorRfResults, ...
    integrationTimes_s, ...
    "West Corridor Due-West Check", ...
    figurePaths.WestCorridorDetectability);
end

function createGeometryOverviewFigure(stationSummary, coverageResults, outputPath)
recoveredAnalysis = getCoverageAnalysis(coverageResults, "RecoveredRoi");
westCorridorAnalysis = getCoverageAnalysis(coverageResults, "WestCorridor");

figureHandle = createSlideFigure();
tiledlayout(1, 2, "TileSpacing", "compact", "Padding", "compact");

mapAxes = nexttile;
plotGeometryContext( ...
    mapAxes, ...
    stationSummary, ...
    coverageResults, ...
    coverageResults.AnalysisOrder, ...
    true, ...
    true);
title(mapAxes, ...
    "Receiver, candidate transmitters, recovered ROI, and due-west corridor", ...
    "FontSize", 18, ...
    "FontWeight", "bold");
geometryLegend = legend(mapAxes, "Location", "southoutside", "Orientation", "horizontal");
geometryLegend.NumColumns = 2;
styleLegend(geometryLegend);

detailAxes = nexttile;
axis(detailAxes, "off");
summaryLines = [ ...
    "ASSUMPTIONS SNAPSHOT"; ...
    compose("Receiver: %s", recoveredAnalysis.ReceiverName); ...
    compose("Newton RF35: %.0f MHz, %.0f kW horizontal ERP, status %s.", ...
        stationSummary.CenterFrequency_MHz(1), ...
        stationSummary.ERPHorizontal_kW(1), ...
        stationSummary.CurrentOperationalStatus(1)); ...
    compose("Hudson RF27: %.0f MHz, %.0f kW horizontal ERP, status %s.", ...
        stationSummary.CenterFrequency_MHz(2), ...
        stationSummary.ERPHorizontal_kW(2), ...
        stationSummary.CurrentOperationalStatus(2)); ...
    compose("Recovered-ROI baseline: %.4f to %.4f deg lat and %.4f to %.4f deg lon.", ...
        recoveredAnalysis.RoiMinLatitude_deg, ...
        recoveredAnalysis.RoiMaxLatitude_deg, ...
        recoveredAnalysis.RoiMinLongitude_deg, ...
        recoveredAnalysis.RoiMaxLongitude_deg); ...
    compose("Due-west corridor: %.6f to %.6f deg lat and %.6f to %.6f deg lon.", ...
        westCorridorAnalysis.RoiMinLatitude_deg, ...
        westCorridorAnalysis.RoiMaxLatitude_deg, ...
        westCorridorAnalysis.RoiMinLongitude_deg, ...
        westCorridorAnalysis.RoiMaxLongitude_deg); ...
    compose("West corridor east edge is fixed at receiver longitude %.6f deg.", ...
        westCorridorAnalysis.ReceiverLongitude_deg); ...
    "Due-west boresight marker is visual only; no directional receive gain is applied."; ...
    "These figures are regenerated from the cleaned deterministic rerun workflow."];
text( ...
    detailAxes, ...
    0, ...
    1, ...
    cellstr(summaryLines), ...
    "Color", "k", ...
    "FontSize", 15, ...
    "VerticalAlignment", "top", ...
    "Interpreter", "none");

exportFigure(figureHandle, outputPath);
end

function createSourceViabilityFigure(sourceLinkTable, outputPath)
figureHandle = createSlideFigure();
tiledlayout(1, 2, "TileSpacing", "compact", "Padding", "compact");
pathNames = categorical(sourceLinkTable.Path, sourceLinkTable.Path, sourceLinkTable.Path);

powerAxes = nexttile;
bar(powerAxes, pathNames, sourceLinkTable.DirectPathPowerAfterAntenna_dBm);
hold(powerAxes, "on");
yline(powerAxes, -25, "--", "Preferred low edge", "LineWidth", 1.25);
yline(powerAxes, -15, "--", "Recommended max input", "LineWidth", 1.25);
hold(powerAxes, "off");
grid(powerAxes, "on");
xlabel(powerAxes, "Candidate source path", "FontSize", 15);
ylabel(powerAxes, "Direct-path power after antenna [dBm]", "FontSize", 15);
title(powerAxes, "Direct-path input level versus TwinRX guidance", "FontSize", 18, "FontWeight", "bold");
styleAxes(powerAxes);

contextAxes = nexttile;
yyaxis(contextAxes, "left");
bar(contextAxes, pathNames, sourceLinkTable.Distance_km);
ylabel(contextAxes, "Range to receiver [km]", "FontSize", 15);
yyaxis(contextAxes, "right");
plot( ...
    contextAxes, ...
    pathNames, ...
    sourceLinkTable.ERPHorizontal_kW, ...
    "o-", ...
    "LineWidth", 2, ...
    "MarkerSize", 8);
ylabel(contextAxes, "Horizontal ERP [kW]", "FontSize", 15);
grid(contextAxes, "on");
xlabel(contextAxes, "Candidate source path", "FontSize", 15);
title(contextAxes, "Range and ERP context for the direct-path check", "FontSize", 18, "FontWeight", "bold");
styleAxes(contextAxes);

exportFigure(figureHandle, outputPath);
end

function createRFChainOverviewFigure(rfResults, outputPath)
figureHandle = createSlideFigure();
tiledlayout(1, 2, "TileSpacing", "compact", "Padding", "compact");

stageLabels = formatStageLabels(rfResults(1).StageNames);
colors = lines(numel(rfResults));
stageIndex = 1:numel(stageLabels);

gainAxes = nexttile;
hold(gainAxes, "on");

for resultIndex = 1:numel(rfResults)
    plot( ...
        gainAxes, ...
        stageIndex, ...
        rfResults(resultIndex).TargetBudget.TransducerGain, ...
        "-o", ...
        "Color", colors(resultIndex, :), ...
        "LineWidth", 2, ...
        "MarkerSize", 7, ...
        "DisplayName", rfResults(resultIndex).Path);
end

hold(gainAxes, "off");
grid(gainAxes, "on");
xlabel(gainAxes, "RF chain stage", "FontSize", 15);
ylabel(gainAxes, "Cumulative transducer gain [dB]", "FontSize", 15);
title(gainAxes, "Gain accumulation through the cleaned capture chain", "FontSize", 18, "FontWeight", "bold");
set(gainAxes, "XTick", stageIndex, "XTickLabel", stageLabels, "XTickLabelRotation", 25);
gainLegend = legend(gainAxes, "Location", "northwest");
styleLegend(gainLegend);
styleAxes(gainAxes);

nfAxes = nexttile;
hold(nfAxes, "on");

for resultIndex = 1:numel(rfResults)
    plot( ...
        nfAxes, ...
        stageIndex, ...
        rfResults(resultIndex).TargetBudget.NF, ...
        "-o", ...
        "Color", colors(resultIndex, :), ...
        "LineWidth", 2, ...
        "MarkerSize", 7, ...
        "DisplayName", rfResults(resultIndex).Path);
end

hold(nfAxes, "off");
grid(nfAxes, "on");
xlabel(nfAxes, "RF chain stage", "FontSize", 15);
ylabel(nfAxes, "Cumulative noise figure [dB]", "FontSize", 15);
title(nfAxes, "Noise-figure growth through the same chain", "FontSize", 18, "FontWeight", "bold");
set(nfAxes, "XTick", stageIndex, "XTickLabel", stageLabels, "XTickLabelRotation", 25);
nfLegend = legend(nfAxes, "Location", "northwest");
styleLegend(nfLegend);
styleAxes(nfAxes);

exportFigure(figureHandle, outputPath);
end

function createRFLevelsFigure(rfSummaryTable, outputPath)
figureHandle = createSlideFigure();
tiledlayout(2, 2, "TileSpacing", "compact", "Padding", "compact");
pathNames = categorical(rfSummaryTable.Path, rfSummaryTable.Path, rfSummaryTable.Path);

inputAxes = nexttile;
inputBars = bar( ...
    inputAxes, ...
    pathNames, ...
    [rfSummaryTable.TargetInputAfterAntenna_dBm rfSummaryTable.DirectInputAfterAntenna_dBm], ...
    "grouped");
grid(inputAxes, "on");
xlabel(inputAxes, "Source path", "FontSize", 15);
ylabel(inputAxes, "Power after receive antenna [dBm]", "FontSize", 15);
title(inputAxes, "Target-path and direct-path levels at the antenna", "FontSize", 18, "FontWeight", "bold");
inputLegend = legend(inputAxes, ["Target path" "Direct path"], "Location", "northwest");
styleLegend(inputLegend);
styleAxes(inputAxes);
annotateGroupedBars(inputBars);

outputAxes = nexttile;
outputBars = bar( ...
    outputAxes, ...
    pathNames, ...
    [rfSummaryTable.TargetOutputPower_dBm rfSummaryTable.DirectOutputPower_dBm], ...
    "grouped");
hold(outputAxes, "on");
yline(outputAxes, -25, "--", "Preferred low edge", "LineWidth", 1.25);
yline(outputAxes, -15, "--", "Recommended max input", "LineWidth", 1.25);
hold(outputAxes, "off");
grid(outputAxes, "on");
xlabel(outputAxes, "Source path", "FontSize", 15);
ylabel(outputAxes, "TwinRX input power [dBm]", "FontSize", 15);
title(outputAxes, "Output levels at the TwinRX input", "FontSize", 18, "FontWeight", "bold");
outputLegend = legend(outputAxes, ["Target path" "Direct path"], "Location", "northwest");
styleLegend(outputLegend);
styleAxes(outputAxes);
annotateGroupedBars(outputBars);

headroomAxes = nexttile;
headroomBars = bar(headroomAxes, pathNames, rfSummaryTable.HeadroomToRecommendedInput_dB);
hold(headroomAxes, "on");
yline(headroomAxes, 0, "--", "No headroom remaining", "LineWidth", 1.25);
hold(headroomAxes, "off");
grid(headroomAxes, "on");
xlabel(headroomAxes, "Source path", "FontSize", 15);
ylabel(headroomAxes, "Headroom to -15 dBm recommendation [dB]", "FontSize", 15);
title(headroomAxes, "Direct-path overload margin", "FontSize", 18, "FontWeight", "bold");
styleAxes(headroomAxes);
annotateSingleBars(headroomBars);

attenuationAxes = nexttile;
attenuationBars = bar(attenuationAxes, pathNames, rfSummaryTable.RecommendedReferenceAttenuation_dB);
grid(attenuationAxes, "on");
xlabel(attenuationAxes, "Source path", "FontSize", 15);
ylabel(attenuationAxes, "Recommended reference attenuation [dB]", "FontSize", 15);
title(attenuationAxes, "Reference-path attenuation implied by the modeled direct path", "FontSize", 18, "FontWeight", "bold");
styleAxes(attenuationAxes);
annotateSingleBars(attenuationBars);

exportFigure(figureHandle, outputPath);
end

function createAnalysisSetupFigure(stationSummary, coverageResults, analysisName, outputPath)
analysis = getCoverageAnalysis(coverageResults, analysisName);
analysisTitleText = formatAnalysisTitle(analysis.Name);

figureHandle = createSlideFigure();
tiledlayout(1, 2, "TileSpacing", "compact", "Padding", "compact");

gridAxes = nexttile;
plot(gridAxes, analysis.TargetLongitude_deg, analysis.TargetLatitude_deg, ".", ...
    "Color", [0.70 0.70 0.70], ...
    "MarkerSize", 10, ...
    "DisplayName", "Target grid");
hold(gridAxes, "on");
plotGeometryContext( ...
    gridAxes, ...
    stationSummary, ...
    coverageResults, ...
    analysis.Name, ...
    false, ...
    analysis.ShowBoresight);
hold(gridAxes, "off");
title(gridAxes, analysisTitleText + " target grid and ROI", "FontSize", 18, "FontWeight", "bold");
gridLegend = legend(gridAxes, "Location", "southoutside", "Orientation", "horizontal");
gridLegend.NumColumns = 2;
styleLegend(gridLegend);
styleAxes(gridAxes);

detailAxes = nexttile;
axis(detailAxes, "off");
detailLines = [ ...
    upper(analysisTitleText + " SETUP"); ...
    compose("Grid spacing: %.2f deg", analysis.TargetGridSpacing_deg); ...
    compose("Target count: %.0f cells inside the selected ROI", analysis.TargetCount); ...
    compose("Latitude window: %.6f to %.6f deg", ...
        analysis.RoiMinLatitude_deg, ...
        analysis.RoiMaxLatitude_deg); ...
    compose("Longitude window: %.6f to %.6f deg", ...
        analysis.RoiMinLongitude_deg, ...
        analysis.RoiMaxLongitude_deg); ...
    compose("Target altitude: %.0f ft AGL", convlength(analysis.TargetHeightAGL_m, "m", "ft")); ...
    compose("Target RCS: %.1f m^2", analysis.TargetRCS_m2); ...
    compose("Bistatic interval: %.1f us", analysis.BistaticInterval_s * 1e6); ...
    compose("Noise figure used for dBm conversion: %.1f dB", analysis.NoiseFigure_dB)];

if analysis.ShowBoresight
    detailLines = [ ...
        detailLines; ...
        compose("Due-west boresight follows receiver latitude %.6f deg.", analysis.ReceiverLatitude_deg); ...
        "The due-west boresight marker is visual only and does not alter the RF math."];
else
    detailLines = [ ...
        detailLines; ...
        "This recovered-ROI branch stays unchanged and remains the baseline evidence path."];
end

text( ...
    detailAxes, ...
    0, ...
    1, ...
    cellstr(detailLines), ...
    "Color", "k", ...
    "FontSize", 15, ...
    "VerticalAlignment", "top", ...
    "Interpreter", "none");

exportFigure(figureHandle, outputPath);
end

function createCoverageFigure(stationSummary, coverageResults, analysisName, pathName, coverageLevels_dB, outputPath)
analysis = getCoverageAnalysis(coverageResults, analysisName);
analysisTitleText = formatAnalysisTitle(analysis.Name);
pathIndex = find(stationSummary.Path == pathName, 1, "first");
pathData = analysis.PathData(pathIndex);
summaryRow = analysis.TargetPathSummary(pathIndex, :);

figureHandle = createSlideFigure();
tiledlayout(1, 2, "TileSpacing", "compact", "Padding", "compact");

mapAxes = nexttile;
drawCoverageMap( ...
    mapAxes, ...
    stationSummary, ...
    coverageResults, ...
    analysis.Name, ...
    pathData.BistaticSNRGrid_dB, ...
    coverageLevels_dB, ...
    pathName + " " + analysisTitleText + " bistatic SNR coverage", ...
    false);

detailAxes = nexttile;
axis(detailAxes, "off");
detailLines = [ ...
    compose("%s | %s", upper(pathName), upper(analysisTitleText)); ...
    compose("Center frequency: %.0f MHz", stationSummary.CenterFrequency_MHz(pathIndex)); ...
    compose("Effective transmit power: %.0f kW horizontal ERP", stationSummary.ERPHorizontal_kW(pathIndex)); ...
    compose("Mean bistatic SNR: %.2f dB", summaryRow.MeanBistaticSNR_dB); ...
    compose("Median bistatic SNR: %.2f dB", summaryRow.MedianBistaticSNR_dB); ...
    compose("Mean target-path power: %.2f dBm", summaryRow.MeanTargetPathPower_dBm); ...
    compose("Min / max target-path power: %.2f / %.2f dBm", ...
        summaryRow.MinTargetPathPower_dBm, ...
        summaryRow.MaxTargetPathPower_dBm); ...
    compose("Map source: cleaned deterministic Longley-Rice rerun over the %s.", analysis.DisplayName); ...
    "These values are model-based precheck evidence, not field measurements."];

if analysis.ShowBoresight
    detailLines = [ ...
        detailLines; ...
        "The due-west boresight marker is shown on the setup and regional west-corridor views only."];
end

text( ...
    detailAxes, ...
    0, ...
    1, ...
    cellstr(detailLines), ...
    "Color", "k", ...
    "FontSize", 15, ...
    "VerticalAlignment", "top", ...
    "Interpreter", "none");

exportFigure(figureHandle, outputPath);
end

function createCombinedCoverageFigure(stationSummary, coverageResults, analysisName, coverageLevels_dB, outputPath)
analysis = getCoverageAnalysis(coverageResults, analysisName);
analysisTitleText = formatAnalysisTitle(analysis.Name);

figureHandle = createSlideFigure();
tiledlayout(1, 2, "TileSpacing", "compact", "Padding", "compact");

mapAxes = nexttile;
drawCoverageMap( ...
    mapAxes, ...
    stationSummary, ...
    coverageResults, ...
    analysis.Name, ...
    analysis.CombinedMaxSNRGrid_dB, ...
    coverageLevels_dB, ...
    analysisTitleText + " pointwise max-SNR coverage", ...
    false);

dominanceAxes = nexttile;
dominanceCounts = zeros(height(stationSummary), 1);

for pathIndex = 1:height(stationSummary)
    dominanceCounts(pathIndex) = nnz(analysis.CombinedBestPathIndex == pathIndex);
end

dominanceBars = bar( ...
    dominanceAxes, ...
    categorical(stationSummary.Path, stationSummary.Path, stationSummary.Path), ...
    dominanceCounts);
grid(dominanceAxes, "on");
xlabel(dominanceAxes, "Source path", "FontSize", 15);
ylabel(dominanceAxes, "ROI cells with local max SNR [count]", "FontSize", 15);
title(dominanceAxes, analysisTitleText + " path dominance", "FontSize", 18, "FontWeight", "bold");
styleAxes(dominanceAxes);
annotateSingleBars(dominanceBars);

exportFigure(figureHandle, outputPath);
end

function createRegionalCoverageFigure(stationSummary, coverageResults, analysisName, coverageLevels_dB, outputPath)
analysis = getCoverageAnalysis(coverageResults, analysisName);
analysisTitleText = formatAnalysisTitle(analysis.Name);
[latitudeLimits_deg, longitudeLimits_deg] = getRegionalLimits(stationSummary, coverageResults, analysis.Name);
inRegionalWindow = ...
    analysis.TargetLatitude_deg >= latitudeLimits_deg(1) & ...
    analysis.TargetLatitude_deg <= latitudeLimits_deg(2) & ...
    analysis.TargetLongitude_deg >= longitudeLimits_deg(1) & ...
    analysis.TargetLongitude_deg <= longitudeLimits_deg(2);

figureHandle = createSlideFigure();
tiledlayout(1, 2, "TileSpacing", "compact", "Padding", "compact");

geometryAxes = nexttile;
plot(geometryAxes, ...
    analysis.TargetLongitude_deg(inRegionalWindow), ...
    analysis.TargetLatitude_deg(inRegionalWindow), ...
    ".", ...
    "Color", [0.70 0.70 0.70], ...
    "MarkerSize", 12, ...
    "DisplayName", "Regional target grid");
hold(geometryAxes, "on");
plotGeometryContext( ...
    geometryAxes, ...
    stationSummary, ...
    coverageResults, ...
    analysis.Name, ...
    false, ...
    true);
hold(geometryAxes, "off");
xlim(geometryAxes, longitudeLimits_deg);
ylim(geometryAxes, latitudeLimits_deg);
title(geometryAxes, analysisTitleText + " regional geometry view", "FontSize", 18, "FontWeight", "bold");
regionalLegend = legend(geometryAxes, "Location", "southoutside", "Orientation", "horizontal");
regionalLegend.NumColumns = 2;
styleLegend(regionalLegend);
styleAxes(geometryAxes);

regionalCoverageAxes = nexttile;
drawCoverageMap( ...
    regionalCoverageAxes, ...
    stationSummary, ...
    coverageResults, ...
    analysis.Name, ...
    analysis.CombinedMaxSNRGrid_dB, ...
    coverageLevels_dB, ...
    analysisTitleText + " combined max-SNR regional view", ...
    true);
xlim(regionalCoverageAxes, longitudeLimits_deg);
ylim(regionalCoverageAxes, latitudeLimits_deg);

exportFigure(figureHandle, outputPath);
end

function createDetectabilityFigure(stationSummary, rfResults, integrationTimes_s, analysisTitleText, outputPath)
figureHandle = createSlideFigure();
tiledlayout(1, 2, "TileSpacing", "compact", "Padding", "compact");
colors = lines(numel(rfResults));

curveAxes = nexttile;
hold(curveAxes, "on");

for resultIndex = 1:numel(rfResults)
    signalBandwidth_Hz = stationSummary.SignalBandwidth_MHz(resultIndex) * 1e6;
    integrationGain_dB = 10 * log10(integrationTimes_s * signalBandwidth_Hz);
    postProcessingSNR_dB = rfResults(resultIndex).TargetPreProcessingSNR_dB + integrationGain_dB;
    plot( ...
        curveAxes, ...
        integrationTimes_s, ...
        postProcessingSNR_dB, ...
        "-o", ...
        "Color", colors(resultIndex, :), ...
        "LineWidth", 2, ...
        "MarkerSize", 7, ...
        "DisplayName", stationSummary.Path(resultIndex));
end

yline(curveAxes, 13, "--", "Illustrative detection threshold", "LineWidth", 1.25);
hold(curveAxes, "off");
grid(curveAxes, "on");
xlabel(curveAxes, "Integration time [s]", "FontSize", 15);
ylabel(curveAxes, "Post-processing SNR [dB]", "FontSize", 15);
title(curveAxes, analysisTitleText + " detectability versus coherent integration time", "FontSize", 18, "FontWeight", "bold");
curveLegend = legend(curveAxes, "Location", "southeast");
styleLegend(curveLegend);
styleAxes(curveAxes);

barAxes = nexttile;
pathNames = categorical(string({rfResults.Path}), string({rfResults.Path}), string({rfResults.Path}));
barSeries = bar( ...
    barAxes, ...
    pathNames, ...
    [[rfResults.TargetPreProcessingSNR_dB].' [rfResults.TargetPostProcessing1sSNR_dB].'], ...
    "grouped");
hold(barAxes, "on");
yline(barAxes, 13, "--", "Illustrative detection threshold", "LineWidth", 1.25);
hold(barAxes, "off");
grid(barAxes, "on");
xlabel(barAxes, "Source path", "FontSize", 15);
ylabel(barAxes, "SNR [dB]", "FontSize", 15);
title(barAxes, analysisTitleText + " pre-processing and 1 s post-processing SNR", "FontSize", 18, "FontWeight", "bold");
barLegend = legend(barAxes, ["Pre-processing" "1 s post-processing"], "Location", "northwest");
styleLegend(barLegend);
styleAxes(barAxes);
annotateGroupedBars(barSeries);

exportFigure(figureHandle, outputPath);
end

function figureHandle = createSlideFigure()
figureHandle = figure( ...
    "Visible", "off", ...
    "Color", "w", ...
    "Position", [100 100 1600 900]);
set(figureHandle, "DefaultAxesColor", "w");
set(figureHandle, "DefaultAxesXColor", "k");
set(figureHandle, "DefaultAxesYColor", "k");
set(figureHandle, "DefaultAxesGridColor", [0.20 0.20 0.20]);
set(figureHandle, "DefaultTextColor", "k");
set(figureHandle, "DefaultLegendColor", "w");
set(figureHandle, "DefaultLegendTextColor", "k");
set(figureHandle, "DefaultLegendEdgeColor", "k");
end

function drawCoverageMap(ax, stationSummary, coverageResults, analysisName, gridValues, coverageLevels_dB, titleText, showBoresight)
analysis = getCoverageAnalysis(coverageResults, analysisName);

contourf( ...
    ax, ...
    analysis.LongitudeGrid_deg, ...
    analysis.LatitudeGrid_deg, ...
    gridValues, ...
    coverageLevels_dB, ...
    "LineColor", "none");
hold(ax, "on");
plotGeometryContext( ...
    ax, ...
    stationSummary, ...
    coverageResults, ...
    analysis.Name, ...
    false, ...
    showBoresight);
hold(ax, "off");
title(ax, titleText, "FontSize", 18, "FontWeight", "bold");
styleAxes(ax);
colorbarHandle = colorbar(ax);
colorbarHandle.Color = "k";
colorbarHandle.Label.String = "Bistatic SNR [dB]";
colorbarHandle.Label.FontSize = 15;
colorbarHandle.Label.Color = "k";
colorbarHandle.FontSize = 13;
clim(ax, coverageLevels_dB([1 end]));
end

function plotGeometryContext(ax, stationSummary, coverageResults, analysisNames, includePathLines, showBoresight)
analysisNames = string(analysisNames);
analysisMask = ismember(string({coverageResults.Analyses.Name}).', analysisNames);
selectedAnalyses = coverageResults.Analyses(analysisMask);
colors = lines(height(stationSummary));

hold(ax, "on");

for analysisIndex = 1:numel(selectedAnalyses)
    roiLongitude_deg = [selectedAnalyses(analysisIndex).RoiLongitude_deg; selectedAnalyses(analysisIndex).RoiLongitude_deg(1)];
    roiLatitude_deg = [selectedAnalyses(analysisIndex).RoiLatitude_deg; selectedAnalyses(analysisIndex).RoiLatitude_deg(1)];
    plot( ...
        ax, ...
        roiLongitude_deg, ...
        roiLatitude_deg, ...
        "LineStyle", getAnalysisLineStyle(selectedAnalyses(analysisIndex).Name), ...
        "Color", getAnalysisColor(selectedAnalyses(analysisIndex).Name), ...
        "LineWidth", 1.8, ...
        "DisplayName", formatAnalysisLegendLabel(selectedAnalyses(analysisIndex).Name));
end

if includePathLines
    for pathIndex = 1:height(stationSummary)
        plot( ...
            ax, ...
            [stationSummary.TowerLongitude_deg(pathIndex) coverageResults.Analyses(1).ReceiverLongitude_deg], ...
            [stationSummary.TowerLatitude_deg(pathIndex) coverageResults.Analyses(1).ReceiverLatitude_deg], ...
            "--", ...
            "Color", colors(pathIndex, :), ...
            "LineWidth", 1.5, ...
            "DisplayName", stationSummary.Path(pathIndex) + " direct path");
    end
end

for pathIndex = 1:height(stationSummary)
    plot( ...
        ax, ...
        stationSummary.TowerLongitude_deg(pathIndex), ...
        stationSummary.TowerLatitude_deg(pathIndex), ...
        "^", ...
        "MarkerSize", 10, ...
        "MarkerFaceColor", colors(pathIndex, :), ...
        "MarkerEdgeColor", "k", ...
        "LineWidth", 1.0, ...
        "DisplayName", stationSummary.Path(pathIndex) + " transmitter");
end

plot( ...
    ax, ...
    coverageResults.Analyses(1).ReceiverLongitude_deg, ...
    coverageResults.Analyses(1).ReceiverLatitude_deg, ...
    "s", ...
    "MarkerSize", 10, ...
    "MarkerFaceColor", "k", ...
    "MarkerEdgeColor", "k", ...
    "LineWidth", 1.0, ...
    "DisplayName", "Receiver");

if showBoresight
    boresightAnalyses = coverageResults.Analyses([coverageResults.Analyses.ShowBoresight]);

    for analysisIndex = 1:numel(boresightAnalyses)
        drawDueWestBoresight(ax, boresightAnalyses(analysisIndex));
    end
end

[latitudeLimits_deg, longitudeLimits_deg] = getFullGeometryLimits( ...
    stationSummary, ...
    coverageResults, ...
    analysisNames, ...
    showBoresight);
xlim(ax, longitudeLimits_deg);
ylim(ax, latitudeLimits_deg);
xlabel(ax, "Longitude [deg]", "FontSize", 15);
ylabel(ax, "Latitude [deg]", "FontSize", 15);
grid(ax, "on");
hold(ax, "off");
end

function drawDueWestBoresight(ax, analysis)
boresightColor = [0.85 0.10 0.10];
plot( ...
    ax, ...
    analysis.BoresightLongitude_deg, ...
    analysis.BoresightLatitude_deg, ...
    "-.", ...
    "Color", boresightColor, ...
    "LineWidth", 2.0, ...
    "DisplayName", analysis.BoresightLabel);
plot( ...
    ax, ...
    analysis.BoresightLongitude_deg(end), ...
    analysis.BoresightLatitude_deg(end), ...
    "<", ...
    "MarkerSize", 9, ...
    "MarkerFaceColor", boresightColor, ...
    "MarkerEdgeColor", boresightColor, ...
    "HandleVisibility", "off");
text( ...
    mean(analysis.BoresightLongitude_deg), ...
    analysis.BoresightLatitude_deg(1) + 0.008, ...
    analysis.BoresightLabel, ...
    "Color", boresightColor, ...
    "FontSize", 12, ...
    "HorizontalAlignment", "center", ...
    "VerticalAlignment", "bottom", ...
    "Interpreter", "none", ...
    "Parent", ax);
end

function analysis = getCoverageAnalysis(coverageResults, analysisName)
analysisField = matlab.lang.makeValidName(string(analysisName));
analysis = coverageResults.ByName.(analysisField);
end

function [latitudeLimits_deg, longitudeLimits_deg] = getFullGeometryLimits( ...
    stationSummary, ...
    coverageResults, ...
    analysisNames, ...
    showBoresight)
analysisNames = string(analysisNames);
analysisMask = ismember(string({coverageResults.Analyses.Name}).', analysisNames);
selectedAnalyses = coverageResults.Analyses(analysisMask);

latitudeValues_deg = [stationSummary.TowerLatitude_deg; coverageResults.Analyses(1).ReceiverLatitude_deg];
longitudeValues_deg = [stationSummary.TowerLongitude_deg; coverageResults.Analyses(1).ReceiverLongitude_deg];

if ~isempty(selectedAnalyses)
    roiLatitudeCells = {selectedAnalyses.RoiLatitude_deg}.';
    roiLongitudeCells = {selectedAnalyses.RoiLongitude_deg}.';
    latitudeValues_deg = [latitudeValues_deg; vertcat(roiLatitudeCells{:})];
    longitudeValues_deg = [longitudeValues_deg; vertcat(roiLongitudeCells{:})];
end

if showBoresight
    boresightAnalyses = coverageResults.Analyses([coverageResults.Analyses.ShowBoresight]);

    if ~isempty(boresightAnalyses)
        boresightLatitudeCells = {boresightAnalyses.BoresightLatitude_deg}.';
        boresightLongitudeCells = {boresightAnalyses.BoresightLongitude_deg}.';
        latitudeValues_deg = [latitudeValues_deg; vertcat(boresightLatitudeCells{:})];
        longitudeValues_deg = [longitudeValues_deg; vertcat(boresightLongitudeCells{:})];
    end
end

latitudePadding_deg = 0.025;
longitudePadding_deg = 0.03;
latitudeLimits_deg = [min(latitudeValues_deg) - latitudePadding_deg max(latitudeValues_deg) + latitudePadding_deg];
longitudeLimits_deg = [min(longitudeValues_deg) - longitudePadding_deg max(longitudeValues_deg) + longitudePadding_deg];
end

function [latitudeLimits_deg, longitudeLimits_deg] = getRegionalLimits(stationSummary, coverageResults, analysisName)
switch string(analysisName)
    case "RecoveredRoi"
        analysis = getCoverageAnalysis(coverageResults, analysisName);
        southernLatitude_deg = min([analysis.ReceiverLatitude_deg; stationSummary.TowerLatitude_deg]);
        northernLatitude_deg = min(analysis.RoiMaxLatitude_deg, max(stationSummary.TowerLatitude_deg) + 0.08);
        westernLongitude_deg = min([analysis.ReceiverLongitude_deg; stationSummary.TowerLongitude_deg]) - 0.08;
        easternLongitude_deg = max([analysis.ReceiverLongitude_deg; stationSummary.TowerLongitude_deg]) + 0.08;
        latitudeLimits_deg = [southernLatitude_deg - 0.02 northernLatitude_deg];
        longitudeLimits_deg = [westernLongitude_deg easternLongitude_deg];
    case "WestCorridor"
        analysis = getCoverageAnalysis(coverageResults, analysisName);
        latitudeLimits_deg = [analysis.RoiMinLatitude_deg - 0.02 analysis.RoiMaxLatitude_deg + 0.02];
        longitudeLimits_deg = [analysis.RoiMinLongitude_deg - 0.03 analysis.ReceiverLongitude_deg + 0.05];
    otherwise
        error("Unsupported analysis name '%s' for regional limits.", analysisName);
end
end

function stageLabels = formatStageLabels(stageNames)
stageLabels = replace(stageNames, "_", " ");
stageLabels = replace(stageLabels, "75 to 50", "75->50");
stageLabels = replace(stageLabels, "TwinRX", "TwinRX");
end

function coverageLevels_dB = buildCoverageLevels(coverageResults)
allSNR_dB = [];

for analysisIndex = 1:numel(coverageResults.Analyses)
    allSNR_dB = [allSNR_dB; vertcat(coverageResults.Analyses(analysisIndex).PathData.BistaticSNR_dB)]; %#ok<AGROW>
end

lowerLevel_dB = 5 * floor(min(allSNR_dB) / 5);
upperLevel_dB = 5 * ceil(max(allSNR_dB) / 5);
coverageLevels_dB = lowerLevel_dB:5:upperLevel_dB;

if numel(coverageLevels_dB) < 5
    coverageLevels_dB = linspace(lowerLevel_dB, upperLevel_dB, 6);
end
end

function colorValue = getAnalysisColor(analysisName)
switch string(analysisName)
    case "RecoveredRoi"
        colorValue = [0.10 0.10 0.10];
    case "WestCorridor"
        colorValue = [0.00 0.45 0.74];
    otherwise
        colorValue = [0.25 0.25 0.25];
end
end

function lineStyle = getAnalysisLineStyle(analysisName)
switch string(analysisName)
    case "RecoveredRoi"
        lineStyle = "-";
    case "WestCorridor"
        lineStyle = "--";
    otherwise
        lineStyle = "-.";
end
end

function labelText = formatAnalysisTitle(analysisName)
switch string(analysisName)
    case "RecoveredRoi"
        labelText = "Recovered-ROI Baseline";
    case "WestCorridor"
        labelText = "West Corridor Due-West Check";
    otherwise
        labelText = replace(string(analysisName), "_", " ");
end
end

function labelText = formatAnalysisLegendLabel(analysisName)
switch string(analysisName)
    case "RecoveredRoi"
        labelText = "Recovered-ROI baseline";
    case "WestCorridor"
        labelText = "West corridor ROI";
    otherwise
        labelText = replace(string(analysisName), "_", " ");
end
end

function styleAxes(ax)
ax.FontSize = 13;
ax.LineWidth = 1;
ax.Box = "on";
ax.Layer = "top";
ax.Color = "w";
ax.XColor = "k";
ax.YColor = "k";
ax.GridColor = [0.20 0.20 0.20];
ax.MinorGridColor = [0.40 0.40 0.40];
ax.Title.Color = "k";
ax.XLabel.Color = "k";
ax.YLabel.Color = "k";

if numel(ax.YAxis) > 1
    ax.YAxis(1).Color = "k";
    ax.YAxis(2).Color = "k";
end
end

function styleLegend(legendHandle)
legendHandle.Color = "w";
legendHandle.EdgeColor = "k";
legendHandle.TextColor = "k";
end

function annotateGroupedBars(barSeries)
for seriesIndex = 1:numel(barSeries)
    xValues = barSeries(seriesIndex).XEndPoints;
    yValues = barSeries(seriesIndex).YEndPoints;
    labels = compose("%.1f", yValues);
    text( ...
        xValues, ...
        yValues, ...
        labels, ...
        "HorizontalAlignment", "center", ...
        "VerticalAlignment", "bottom", ...
        "Color", "k", ...
        "FontSize", 11);
end
end

function annotateSingleBars(barSeries)
xValues = barSeries.XEndPoints;
yValues = barSeries.YEndPoints;
labels = compose("%.1f", yValues);
verticalAlignment = repmat("bottom", size(yValues));
verticalAlignment(yValues < 0) = "top";

for labelIndex = 1:numel(labels)
    text( ...
        xValues(labelIndex), ...
        yValues(labelIndex), ...
        labels(labelIndex), ...
        "HorizontalAlignment", "center", ...
        "VerticalAlignment", verticalAlignment(labelIndex), ...
        "Color", "k", ...
        "FontSize", 11);
end
end

function exportFigure(figureHandle, outputPath)
try
    exportgraphics(figureHandle, outputPath, "Resolution", 300, "BackgroundColor", "white");
catch exportException
    close(figureHandle);
    rethrow(exportException);
end

close(figureHandle);
end
