function coverageResults = helperBuildDeterministicCoverageData(stationSummary, roiSpecs)
%helperBuildDeterministicCoverageData Build named deterministic coverage bundles.
%
% Plain-language concept:
% The system precheck now needs two deterministic geometry branches that use
% the same RF and propagation math. This helper keeps the recovered-ROI
% baseline intact, adds the due-west surveillance corridor as a second
% branch, and returns both analyses in one named result so downstream tables,
% figures, and deck slides stay synchronized.
%
% Native MATLAB workflow:
% 1. Represent the receiver, candidate transmitters, and target grid with
%    txsite/rxsite objects.
% 2. Use propagationModel("longley-rice") and pathloss to compute the
%    terrain-driven excess loss for each bistatic leg.
% 3. Use radareqsnr to compute the bistatic SNR on each deterministic target
%    grid.
% 4. Convert the grid SNR to received target-path power in dBm so the same
%    data supports the tabular summaries and the slide-ready coverage maps.

if nargin < 2 || isempty(roiSpecs)
    roiSpecs = buildDefaultRoiSpecs( ...
        stationSummary.ReceiverLatitude_deg(1), ...
        stationSummary.ReceiverLongitude_deg(1));
end

roiSpecs = normalizeRoiSpecs( ...
    roiSpecs, ...
    stationSummary.ReceiverLatitude_deg(1), ...
    stationSummary.ReceiverLongitude_deg(1));

pathCount = height(stationSummary);

targetGridSpacing_deg = 0.04;
targetHeightAGL_m = convlength(6000, "ft", "m");
receiverSiteHeight_m = 25;
targetRCS_m2 = 0.5;
bistaticInterval_s = 1 / (200e3);
noiseFigure_dB = 2.5;

transmitterSiteHeight_m = getTransmitterSiteHeight_m(stationSummary.Path);
transmitterSite = buildTransmitterSites(stationSummary, transmitterSiteHeight_m);

receiverSite = rxsite( ...
    "Name", stationSummary.ReceiverName(1), ...
    "Latitude", stationSummary.ReceiverLatitude_deg(1), ...
    "Longitude", stationSummary.ReceiverLongitude_deg(1), ...
    "AntennaHeight", receiverSiteHeight_m);

longleyRiceModel = propagationModel("longley-rice");
freeSpaceModel = propagationModel("freespace");

pathTemplate = struct( ...
    "Path", "", ...
    "TransmitterLatitude_deg", [], ...
    "TransmitterLongitude_deg", [], ...
    "TransmitterSiteHeight_m", [], ...
    "CenterFrequency_MHz", [], ...
    "EffectiveTransmitPower_kW", [], ...
    "BistaticSNR_dB", [], ...
    "TargetPathPower_dBm", [], ...
    "BistaticSNRGrid_dB", [], ...
    "TargetPathPowerGrid_dBm", [], ...
    "TransmitterToTargetRange_m", [], ...
    "TwoWayExcessLoss_dB", []);

analysisTemplate = struct( ...
    "Name", "", ...
    "DisplayName", "", ...
    "Description", "", ...
    "OutputSuffix", "", ...
    "PropagationModel", "", ...
    "RoiLatitude_deg", [], ...
    "RoiLongitude_deg", [], ...
    "RoiMinLatitude_deg", [], ...
    "RoiMaxLatitude_deg", [], ...
    "RoiMinLongitude_deg", [], ...
    "RoiMaxLongitude_deg", [], ...
    "RoiCenterLatitude_deg", [], ...
    "RoiCenterLongitude_deg", [], ...
    "LatitudeGrid_deg", [], ...
    "LongitudeGrid_deg", [], ...
    "IsInsideRoi", [], ...
    "TargetLatitude_deg", [], ...
    "TargetLongitude_deg", [], ...
    "TargetGridSpacing_deg", [], ...
    "TargetHeightAGL_m", [], ...
    "TargetRCS_m2", [], ...
    "TargetCount", [], ...
    "BistaticInterval_s", [], ...
    "NoiseFigure_dB", [], ...
    "ReceiverName", "", ...
    "ReceiverLatitude_deg", [], ...
    "ReceiverLongitude_deg", [], ...
    "ReceiverSiteHeight_m", [], ...
    "ReceiverToTargetRange_m", [], ...
    "ShowBoresight", false, ...
    "BoresightLabel", "", ...
    "BoresightLatitude_deg", [], ...
    "BoresightLongitude_deg", [], ...
    "TargetPathSummary", table(), ...
    "PathData", pathTemplate, ...
    "CombinedMaxSNRGrid_dB", [], ...
    "CombinedBestPathIndex", []);
analyses = repmat(analysisTemplate, numel(roiSpecs), 1);

noisePower_W = buildNoisePower_W(noiseFigure_dB, stationSummary.SignalBandwidth_MHz(1) * 1e6);

for analysisIndex = 1:numel(roiSpecs)
    currentSpec = roiSpecs(analysisIndex);
    [latitudeGrid_deg, longitudeGrid_deg, isInsideRoi] = buildTargetGrid( ...
        currentSpec.Latitude_deg, ...
        currentSpec.Longitude_deg, ...
        targetGridSpacing_deg);

    targetLatitude_deg = latitudeGrid_deg(isInsideRoi);
    targetLongitude_deg = longitudeGrid_deg(isInsideRoi);
    targetCount = numel(targetLatitude_deg);

    [targetTxSite, targetRxSite] = buildTargetSites( ...
        targetLatitude_deg, ...
        targetLongitude_deg, ...
        targetHeightAGL_m);

    forwardExcessLoss_dB = ...
        pathloss(longleyRiceModel, targetRxSite, transmitterSite) - ...
        pathloss(freeSpaceModel, targetRxSite, transmitterSite);
    reverseExcessLoss_dB = ...
        pathloss(longleyRiceModel, receiverSite, targetTxSite) - ...
        pathloss(freeSpaceModel, receiverSite, targetTxSite);
    twoWayExcessLoss_dB = forwardExcessLoss_dB.' + reverseExcessLoss_dB;

    receiverToTargetRange_m = distance(receiverSite, targetRxSite);
    receiverToTargetRange_m = receiverToTargetRange_m(:);
    transmitterToTargetRange_m = distance(transmitterSite, targetRxSite);

    targetPathSummary = buildTargetPathSummaryTable( ...
        stationSummary, ...
        currentSpec, ...
        targetGridSpacing_deg, ...
        targetHeightAGL_m, ...
        receiverSiteHeight_m, ...
        transmitterSiteHeight_m, ...
        targetRCS_m2, ...
        bistaticInterval_s, ...
        noiseFigure_dB, ...
        targetCount);

    pathData = repmat(pathTemplate, pathCount, 1);

    for pathIndex = 1:pathCount
        wavelength_m = physconst("LightSpeed") / (stationSummary.CenterFrequency_MHz(pathIndex) * 1e6);
        bistaticSNR_dB = radareqsnr( ...
            wavelength_m, ...
            [receiverToTargetRange_m, transmitterToTargetRange_m(:, pathIndex)], ...
            stationSummary.ERPHorizontal_kW(pathIndex) * 1e3, ...
            bistaticInterval_s, ...
            RCS=targetRCS_m2, ...
            Loss=twoWayExcessLoss_dB(:, pathIndex));

        targetPathPower_dBm = pow2db(db2pow(bistaticSNR_dB) * noisePower_W) + 30;

        snrGrid_dB = nan(size(latitudeGrid_deg));
        snrGrid_dB(isInsideRoi) = bistaticSNR_dB;

        powerGrid_dBm = nan(size(latitudeGrid_deg));
        powerGrid_dBm(isInsideRoi) = targetPathPower_dBm;

        targetPathSummary.MeanBistaticSNR_dB(pathIndex) = mean(bistaticSNR_dB);
        targetPathSummary.MedianBistaticSNR_dB(pathIndex) = median(bistaticSNR_dB);
        targetPathSummary.MeanTargetPathPower_dBm(pathIndex) = mean(targetPathPower_dBm);
        targetPathSummary.MedianTargetPathPower_dBm(pathIndex) = median(targetPathPower_dBm);
        targetPathSummary.MinTargetPathPower_dBm(pathIndex) = min(targetPathPower_dBm);
        targetPathSummary.MaxTargetPathPower_dBm(pathIndex) = max(targetPathPower_dBm);
        targetPathSummary.TargetPathBasis(pathIndex) = compose( ...
            "Deterministic Longley-Rice rerun over the %s; %.0f targets on a %.2f deg grid at %.1f m AGL, %.1f m^2 RCS, %.1f m receiver site height, and horizontal ERP treated as effective transmitted power for consistency with the retained supporting workflow.", ...
            currentSpec.DisplayName, ...
            targetCount, ...
            targetGridSpacing_deg, ...
            targetHeightAGL_m, ...
            targetRCS_m2, ...
            receiverSiteHeight_m);

        if currentSpec.ShowBoresight
            targetPathSummary.TargetPathBasis(pathIndex) = compose( ...
                "%s The due-west boresight marker is visual only and is not used as a directional gain term.", ...
                targetPathSummary.TargetPathBasis(pathIndex));
        end

        pathData(pathIndex).Path = stationSummary.Path(pathIndex);
        pathData(pathIndex).TransmitterLatitude_deg = stationSummary.TowerLatitude_deg(pathIndex);
        pathData(pathIndex).TransmitterLongitude_deg = stationSummary.TowerLongitude_deg(pathIndex);
        pathData(pathIndex).TransmitterSiteHeight_m = transmitterSiteHeight_m(pathIndex);
        pathData(pathIndex).CenterFrequency_MHz = stationSummary.CenterFrequency_MHz(pathIndex);
        pathData(pathIndex).EffectiveTransmitPower_kW = stationSummary.ERPHorizontal_kW(pathIndex);
        pathData(pathIndex).BistaticSNR_dB = bistaticSNR_dB;
        pathData(pathIndex).TargetPathPower_dBm = targetPathPower_dBm;
        pathData(pathIndex).BistaticSNRGrid_dB = snrGrid_dB;
        pathData(pathIndex).TargetPathPowerGrid_dBm = powerGrid_dBm;
        pathData(pathIndex).TransmitterToTargetRange_m = transmitterToTargetRange_m(:, pathIndex);
        pathData(pathIndex).TwoWayExcessLoss_dB = twoWayExcessLoss_dB(:, pathIndex);
    end

    allSNRGrids_dB = cat(3, pathData.BistaticSNRGrid_dB);
    [combinedMaxSNRGrid_dB, combinedBestPathIndex] = max(allSNRGrids_dB, [], 3);
    allOutsideRoi = all(isnan(allSNRGrids_dB), 3);
    combinedMaxSNRGrid_dB(allOutsideRoi) = nan;
    combinedBestPathIndex(allOutsideRoi) = nan;

    analyses(analysisIndex).Name = currentSpec.Name;
    analyses(analysisIndex).DisplayName = currentSpec.DisplayName;
    analyses(analysisIndex).Description = currentSpec.Description;
    analyses(analysisIndex).OutputSuffix = currentSpec.OutputSuffix;
    analyses(analysisIndex).PropagationModel = "longley-rice";
    analyses(analysisIndex).RoiLatitude_deg = currentSpec.Latitude_deg;
    analyses(analysisIndex).RoiLongitude_deg = currentSpec.Longitude_deg;
    analyses(analysisIndex).RoiMinLatitude_deg = min(currentSpec.Latitude_deg);
    analyses(analysisIndex).RoiMaxLatitude_deg = max(currentSpec.Latitude_deg);
    analyses(analysisIndex).RoiMinLongitude_deg = min(currentSpec.Longitude_deg);
    analyses(analysisIndex).RoiMaxLongitude_deg = max(currentSpec.Longitude_deg);
    analyses(analysisIndex).RoiCenterLatitude_deg = mean([ ...
        min(currentSpec.Latitude_deg) ...
        max(currentSpec.Latitude_deg)]);
    analyses(analysisIndex).RoiCenterLongitude_deg = mean([ ...
        min(currentSpec.Longitude_deg) ...
        max(currentSpec.Longitude_deg)]);
    analyses(analysisIndex).LatitudeGrid_deg = latitudeGrid_deg;
    analyses(analysisIndex).LongitudeGrid_deg = longitudeGrid_deg;
    analyses(analysisIndex).IsInsideRoi = isInsideRoi;
    analyses(analysisIndex).TargetLatitude_deg = targetLatitude_deg;
    analyses(analysisIndex).TargetLongitude_deg = targetLongitude_deg;
    analyses(analysisIndex).TargetGridSpacing_deg = targetGridSpacing_deg;
    analyses(analysisIndex).TargetHeightAGL_m = targetHeightAGL_m;
    analyses(analysisIndex).TargetRCS_m2 = targetRCS_m2;
    analyses(analysisIndex).TargetCount = targetCount;
    analyses(analysisIndex).BistaticInterval_s = bistaticInterval_s;
    analyses(analysisIndex).NoiseFigure_dB = noiseFigure_dB;
    analyses(analysisIndex).ReceiverName = stationSummary.ReceiverName(1);
    analyses(analysisIndex).ReceiverLatitude_deg = stationSummary.ReceiverLatitude_deg(1);
    analyses(analysisIndex).ReceiverLongitude_deg = stationSummary.ReceiverLongitude_deg(1);
    analyses(analysisIndex).ReceiverSiteHeight_m = receiverSiteHeight_m;
    analyses(analysisIndex).ReceiverToTargetRange_m = receiverToTargetRange_m;
    analyses(analysisIndex).ShowBoresight = currentSpec.ShowBoresight;
    analyses(analysisIndex).BoresightLabel = currentSpec.BoresightLabel;
    analyses(analysisIndex).BoresightLatitude_deg = currentSpec.BoresightLatitude_deg;
    analyses(analysisIndex).BoresightLongitude_deg = currentSpec.BoresightLongitude_deg;
    analyses(analysisIndex).TargetPathSummary = targetPathSummary;
    analyses(analysisIndex).PathData = pathData;
    analyses(analysisIndex).CombinedMaxSNRGrid_dB = combinedMaxSNRGrid_dB;
    analyses(analysisIndex).CombinedBestPathIndex = combinedBestPathIndex;
end

coverageResults = struct;
coverageResults.DefaultAnalysisName = "RecoveredRoi";
coverageResults.AnalysisOrder = string({analyses.Name}).';
coverageResults.Analyses = analyses;
coverageResults.ByName = buildAnalysisLookup(analyses);
end

function noisePower_W = buildNoisePower_W(noiseFigure_dB, signalBandwidth_Hz)
noiseFactor = 10 ^ (noiseFigure_dB / 10);
referenceTemperature_K = 290;
noisePower_W = physconst("Boltzmann") * (noiseFactor - 1) * referenceTemperature_K * signalBandwidth_Hz;
end

function [latitudeGrid_deg, longitudeGrid_deg, isInsideRoi] = buildTargetGrid(roiLatitude_deg, roiLongitude_deg, targetGridSpacing_deg)
latitudeValues_deg = ...
    floor(min(roiLatitude_deg) / targetGridSpacing_deg) * targetGridSpacing_deg : ...
    targetGridSpacing_deg : ...
    ceil(max(roiLatitude_deg) / targetGridSpacing_deg) * targetGridSpacing_deg;
longitudeValues_deg = ...
    floor(min(roiLongitude_deg) / targetGridSpacing_deg) * targetGridSpacing_deg : ...
    targetGridSpacing_deg : ...
    ceil(max(roiLongitude_deg) / targetGridSpacing_deg) * targetGridSpacing_deg;

[latitudeGrid_deg, longitudeGrid_deg] = meshgrid(latitudeValues_deg, longitudeValues_deg);
isInsideRoi = inpolygon( ...
    latitudeGrid_deg, ...
    longitudeGrid_deg, ...
    roiLatitude_deg, ...
    roiLongitude_deg);
end

function transmitterSiteHeight_m = getTransmitterSiteHeight_m(pathNames)
transmitterSiteHeight_m = zeros(numel(pathNames), 1);

for pathIndex = 1:numel(pathNames)
    switch string(pathNames(pathIndex))
        case "Newton"
            transmitterSiteHeight_m(pathIndex) = convlength(1035, "ft", "m");
        case "Hudson"
            transmitterSiteHeight_m(pathIndex) = convlength(1226, "ft", "m");
        otherwise
            error("Unsupported path name '%s' for deterministic target-path rerun.", pathNames(pathIndex));
    end
end
end

function transmitterSite = buildTransmitterSites(stationSummary, transmitterSiteHeight_m)
pathCount = height(stationSummary);

for pathIndex = 1:pathCount
    transmitterSite(pathIndex) = txsite( ...
        "Name", stationSummary.Path(pathIndex), ...
        "Latitude", stationSummary.TowerLatitude_deg(pathIndex), ...
        "Longitude", stationSummary.TowerLongitude_deg(pathIndex), ...
        "AntennaHeight", transmitterSiteHeight_m(pathIndex), ...
        "TransmitterFrequency", stationSummary.CenterFrequency_MHz(pathIndex) * 1e6, ...
        "TransmitterPower", stationSummary.ERPHorizontal_kW(pathIndex) * 1e3); %#ok<AGROW>
end
end

function [targetTxSite, targetRxSite] = buildTargetSites(targetLatitude_deg, targetLongitude_deg, targetHeightAGL_m)
targetCount = numel(targetLatitude_deg);

for targetIndex = 1:targetCount
    targetTxSite(targetIndex) = txsite( ...
        "Latitude", targetLatitude_deg(targetIndex), ...
        "Longitude", targetLongitude_deg(targetIndex), ...
        "AntennaHeight", targetHeightAGL_m); %#ok<AGROW>
    targetRxSite(targetIndex) = rxsite( ...
        "Latitude", targetLatitude_deg(targetIndex), ...
        "Longitude", targetLongitude_deg(targetIndex), ...
        "AntennaHeight", targetHeightAGL_m); %#ok<AGROW>
end
end

function targetPathSummary = buildTargetPathSummaryTable( ...
    stationSummary, ...
    roiSpec, ...
    targetGridSpacing_deg, ...
    targetHeightAGL_m, ...
    receiverSiteHeight_m, ...
    transmitterSiteHeight_m, ...
    targetRCS_m2, ...
    bistaticInterval_s, ...
    noiseFigure_dB, ...
    targetCount)
pathCount = height(stationSummary);

targetPathSummary = table;
targetPathSummary.Path = stationSummary.Path;
targetPathSummary.AnalysisName = repmat(roiSpec.Name, pathCount, 1);
targetPathSummary.AnalysisDisplayName = repmat(roiSpec.DisplayName, pathCount, 1);
targetPathSummary.PropagationModel = repmat("longley-rice", pathCount, 1);
targetPathSummary.RoiMinLatitude_deg = repmat(min(roiSpec.Latitude_deg), pathCount, 1);
targetPathSummary.RoiMaxLatitude_deg = repmat(max(roiSpec.Latitude_deg), pathCount, 1);
targetPathSummary.RoiMinLongitude_deg = repmat(min(roiSpec.Longitude_deg), pathCount, 1);
targetPathSummary.RoiMaxLongitude_deg = repmat(max(roiSpec.Longitude_deg), pathCount, 1);
targetPathSummary.RoiCenterLatitude_deg = repmat(mean([ ...
    min(roiSpec.Latitude_deg) ...
    max(roiSpec.Latitude_deg)]), pathCount, 1);
targetPathSummary.RoiCenterLongitude_deg = repmat(mean([ ...
    min(roiSpec.Longitude_deg) ...
    max(roiSpec.Longitude_deg)]), pathCount, 1);
targetPathSummary.TargetGridSpacing_deg = repmat(targetGridSpacing_deg, pathCount, 1);
targetPathSummary.TargetHeightAGL_m = repmat(targetHeightAGL_m, pathCount, 1);
targetPathSummary.ReceiverSiteHeight_m = repmat(receiverSiteHeight_m, pathCount, 1);
targetPathSummary.TransmitterSiteHeight_m = transmitterSiteHeight_m;
targetPathSummary.TargetRCS_m2 = repmat(targetRCS_m2, pathCount, 1);
targetPathSummary.BistaticInterval_s = repmat(bistaticInterval_s, pathCount, 1);
targetPathSummary.NoiseFigure_dB = repmat(noiseFigure_dB, pathCount, 1);
targetPathSummary.EffectiveTransmitPower_kW = stationSummary.ERPHorizontal_kW;
targetPathSummary.TargetCount = repmat(targetCount, pathCount, 1);
targetPathSummary.MeanBistaticSNR_dB = zeros(pathCount, 1);
targetPathSummary.MedianBistaticSNR_dB = zeros(pathCount, 1);
targetPathSummary.MeanTargetPathPower_dBm = zeros(pathCount, 1);
targetPathSummary.MedianTargetPathPower_dBm = zeros(pathCount, 1);
targetPathSummary.MinTargetPathPower_dBm = zeros(pathCount, 1);
targetPathSummary.MaxTargetPathPower_dBm = zeros(pathCount, 1);
targetPathSummary.TargetPathBasis = strings(pathCount, 1);
end

function roiSpecs = buildDefaultRoiSpecs(receiverLatitude_deg, receiverLongitude_deg)
recoveredLatitude_deg = [42.5425; 42.5425; 42.3082; 42.3082];
recoveredLongitude_deg = [-71.5908; -71.0049; -71.0049; -71.5908];

roiLatitudeSpan_deg = max(recoveredLatitude_deg) - min(recoveredLatitude_deg);
halfLatitudeSpan_deg = roiLatitudeSpan_deg / 2;
westCorridorMinLatitude_deg = receiverLatitude_deg - halfLatitudeSpan_deg;
westCorridorMaxLatitude_deg = receiverLatitude_deg + halfLatitudeSpan_deg;
westCorridorWestEdge_deg = receiverLongitude_deg - 0.50;

roiSpecs(1) = struct( ...
    "Name", "RecoveredRoi", ...
    "DisplayName", "recovered-ROI baseline", ...
    "Description", "Recovered rectangular ROI from the saved live-script figure.", ...
    "OutputSuffix", "", ...
    "Latitude_deg", recoveredLatitude_deg, ...
    "Longitude_deg", recoveredLongitude_deg, ...
    "ShowBoresight", false, ...
    "BoresightLabel", "", ...
    "BoresightLatitude_deg", [receiverLatitude_deg; receiverLatitude_deg], ...
    "BoresightLongitude_deg", [receiverLongitude_deg; receiverLongitude_deg]);

    % The due-west corridor is additive and reuses the same RF math. The
    % boresight line is visual only and follows the receiver latitude.
    roiSpecs(2) = struct( ...
    "Name", "WestCorridor", ...
    "DisplayName", "due-west surveillance corridor", ...
    "Description", "Additive west-looking corridor for the antenna due-west check.", ...
    "OutputSuffix", "WestCorridor", ...
    "Latitude_deg", [ ...
        westCorridorMaxLatitude_deg; ...
        westCorridorMaxLatitude_deg; ...
        westCorridorMinLatitude_deg; ...
        westCorridorMinLatitude_deg], ...
    "Longitude_deg", [ ...
        westCorridorWestEdge_deg; ...
        receiverLongitude_deg; ...
        receiverLongitude_deg; ...
        westCorridorWestEdge_deg], ...
    "ShowBoresight", true, ...
    "BoresightLabel", "Due-west boresight", ...
    "BoresightLatitude_deg", [receiverLatitude_deg; receiverLatitude_deg], ...
    "BoresightLongitude_deg", [receiverLongitude_deg; westCorridorWestEdge_deg]);
end

function normalizedSpecs = normalizeRoiSpecs(roiSpecs, receiverLatitude_deg, receiverLongitude_deg)
requiredFields = ["Name" "DisplayName" "Latitude_deg" "Longitude_deg"];
normalizedSpecs = roiSpecs;

for specIndex = 1:numel(roiSpecs)
    currentFieldNames = string(fieldnames(roiSpecs(specIndex))).';
    missingFields = requiredFields(~ismember(requiredFields, currentFieldNames));

    if ~isempty(missingFields)
        error( ...
            "helperBuildDeterministicCoverageData:MissingRoiField", ...
            "ROI spec %d is missing required field(s): %s", ...
            specIndex, ...
            strjoin(missingFields, ", "));
    end

    normalizedSpecs(specIndex).Name = string(roiSpecs(specIndex).Name);
    normalizedSpecs(specIndex).DisplayName = string(roiSpecs(specIndex).DisplayName);
    normalizedSpecs(specIndex).Latitude_deg = roiSpecs(specIndex).Latitude_deg(:);
    normalizedSpecs(specIndex).Longitude_deg = roiSpecs(specIndex).Longitude_deg(:);

    if numel(normalizedSpecs(specIndex).Latitude_deg) ~= numel(normalizedSpecs(specIndex).Longitude_deg)
        error( ...
            "helperBuildDeterministicCoverageData:InvalidRoiPolygon", ...
            "ROI '%s' must provide matching latitude and longitude vectors.", ...
            normalizedSpecs(specIndex).Name);
    end

    if isfield(roiSpecs(specIndex), "Description")
        normalizedSpecs(specIndex).Description = string(roiSpecs(specIndex).Description);
    else
        normalizedSpecs(specIndex).Description = normalizedSpecs(specIndex).DisplayName;
    end

    if isfield(roiSpecs(specIndex), "OutputSuffix")
        normalizedSpecs(specIndex).OutputSuffix = string(roiSpecs(specIndex).OutputSuffix);
    else
        normalizedSpecs(specIndex).OutputSuffix = normalizedSpecs(specIndex).Name;
    end

    if isfield(roiSpecs(specIndex), "ShowBoresight")
        normalizedSpecs(specIndex).ShowBoresight = logical(roiSpecs(specIndex).ShowBoresight);
    else
        normalizedSpecs(specIndex).ShowBoresight = false;
    end

    if isfield(roiSpecs(specIndex), "BoresightLabel")
        normalizedSpecs(specIndex).BoresightLabel = string(roiSpecs(specIndex).BoresightLabel);
    else
        normalizedSpecs(specIndex).BoresightLabel = "Due-west boresight";
    end

    if isfield(roiSpecs(specIndex), "BoresightLatitude_deg") && ...
            isfield(roiSpecs(specIndex), "BoresightLongitude_deg")
        normalizedSpecs(specIndex).BoresightLatitude_deg = roiSpecs(specIndex).BoresightLatitude_deg(:);
        normalizedSpecs(specIndex).BoresightLongitude_deg = roiSpecs(specIndex).BoresightLongitude_deg(:);
    else
        normalizedSpecs(specIndex).BoresightLatitude_deg = [receiverLatitude_deg; receiverLatitude_deg];
        normalizedSpecs(specIndex).BoresightLongitude_deg = [ ...
            receiverLongitude_deg; ...
            min(normalizedSpecs(specIndex).Longitude_deg)];
    end
end
end

function analysisLookup = buildAnalysisLookup(analyses)
analysisLookup = struct;

for analysisIndex = 1:numel(analyses)
    analysisLookup.(matlab.lang.makeValidName(analyses(analysisIndex).Name)) = analyses(analysisIndex);
end
end
