function [assumptionTable, stationSummary] = helperBuildSystemPrecheckAssumptions()
%helperBuildSystemPrecheckAssumptions Build the sourced and assumed precheck baseline.

receiverName = "MathWorks Apple Hill Garage";
receiverLatitude = 42.299293;
receiverLongitude = -71.349500;

stationSummary = table;
stationSummary.Path = ["Newton"; "Hudson"];
stationSummary.Role = ["Primary"; "Alternate"];
stationSummary.StationName = ["WHDH/WLVI shared RF35 source"; "Univision Boston source"];
stationSummary.CallSign = ["WHDH-TV / WLVI-TV"; "WUNI"];
stationSummary.RFChannel = [35; 27];
stationSummary.RFRange_MHz = ["596-602"; "548-554"];
stationSummary.CenterFrequency_MHz = [599; 551];
stationSummary.ERPHorizontal_kW = [1000; 400];
stationSummary.ERPVertical_kW = [316; 100];
stationSummary.Polarization = ["Inferred mixed H/V"; "Inferred mixed H/V"];
stationSummary.TowerLatitude_deg = [42.310280; 42.384083];
stationSummary.TowerLongitude_deg = [-71.236670; -71.493139];
stationSummary.ReceiverName = repmat(receiverName, 2, 1);
stationSummary.ReceiverLatitude_deg = repmat(receiverLatitude, 2, 1);
stationSummary.ReceiverLongitude_deg = repmat(receiverLongitude, 2, 1);
stationSummary.ReceiverAntennaGain_dBi = [12; 12];
stationSummary.CableLength_ft = [75; 75];
stationSummary.CableLossPer100ft_dB = [1.6; 1.5];
stationSummary.MismatchLoss_dB = [0.4; 0.4];
stationSummary.HighPassLoss_dB = [0.3; 0.3];
stationSummary.LNA_Gain_dB = [20; 20];
stationSummary.LNA_NF_dB = [1.5; 1.4];
stationSummary.LNA_OIP3_dBm = [28; 28];
stationSummary.USRP_Gain_dB = [30; 30];
stationSummary.USRP_NF_dB = [6; 6];
stationSummary.USRP_OIP3_dBm = [30; 30];
stationSummary.SignalBandwidth_MHz = [6; 6];
stationSummary.TargetPathPower_dBm = [-67.37; -67.37];
stationSummary.TargetPathBasis = [ ...
    "Carried from Hudson supporting link-budget result until Newton-specific rerun"; ...
    "Supporting link-budget result reused by current RF scripts"];
stationSummary.CurrentOperationalStatus = ["Licensed"; "Licensed"];
stationSummary.StatusAsOf = ["2026-07-17"; "2026-07-17"];

rows = strings(0, 6);

rows = addAssumptionRow(rows, "Newton", "StationName_CallSign", ...
    "WHDH-TV / WLVI-TV shared RF35 source", "sourced", ...
    "RabbitEars main listing and FCC TV profile, queried 2026-07-17", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Newton", "RFChannel", ...
    "35", "sourced", ...
    "RabbitEars main listing, queried 2026-07-17", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Newton", "RFRange_MHz", ...
    "596-602", "sourced", ...
    "RabbitEars main listing, queried 2026-07-17", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Newton", "CenterFrequency_MHz", ...
    "599", "inferred", ...
    "Midpoint of the RF35 allocation; required by this cleanup plan for RF models", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Newton", "ERPHorizontal_kW", ...
    "1000", "sourced", ...
    "RabbitEars main listing, queried 2026-07-17", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Newton", "ERPVertical_kW", ...
    "316", "sourced", ...
    "RabbitEars main listing, queried 2026-07-17", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Newton", "Polarization", ...
    "Inferred mixed H/V from separate ERP values", "inferred", ...
    "RabbitEars reports separate horizontal and vertical ERP values", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Newton", "TowerLatitude_deg", ...
    "42.310280", "sourced", ...
    "RabbitEars main listing, queried 2026-07-17", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Newton", "TowerLongitude_deg", ...
    "-71.236670", "sourced", ...
    "RabbitEars main listing, queried 2026-07-17", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Newton", "ReceiverLocation", ...
    receiverName, "local-analysis", ...
    "FlightTest_Bistatic_RadarAndCommsAnalysis.mlx and RFBudgetInputCalcs.m", ...
    "all claims");
rows = addAssumptionRow(rows, "Newton", "ReceiverLatitude_deg", ...
    num2str(receiverLatitude, "%.6f"), "local-analysis", ...
    "FlightTest_Bistatic_RadarAndCommsAnalysis.mlx and RFBudgetInputCalcs.m", ...
    "all claims");
rows = addAssumptionRow(rows, "Newton", "ReceiverLongitude_deg", ...
    num2str(receiverLongitude, "%.6f"), "local-analysis", ...
    "FlightTest_Bistatic_RadarAndCommsAnalysis.mlx and RFBudgetInputCalcs.m", ...
    "all claims");
rows = addAssumptionRow(rows, "Newton", "CurrentOperationalStatus", ...
    "Licensed", "sourced", ...
    "FCC TV profile, queried 2026-07-17", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Newton", "TargetPathPower_dBm", ...
    "-67.37", "assumed", ...
    "Carried from the Hudson supporting link-budget output until the Newton path is rerun", ...
    "bistatic detectability plausibility");
rows = addAssumptionRow(rows, "Newton", "ReceiverAntennaGain_dBi", ...
    "12", "assumed", ...
    "Current RF budget scripts use a typical TV Yagi gain assumption", ...
    "capturability");
rows = addAssumptionRow(rows, "Newton", "CableLossPer100ft_dB", ...
    "1.6", "assumed", ...
    "RFBudget_Newton.m", ...
    "capturability");
rows = addAssumptionRow(rows, "Newton", "USRP_Gain_dB", ...
    "30", "assumed", ...
    "RFBudget_Newton.m nominal TwinRX gain setting", ...
    "capturability");

rows = addAssumptionRow(rows, "Hudson", "StationName_CallSign", ...
    "WUNI alternate source path", "sourced", ...
    "RabbitEars main listing and FCC TV profile, queried 2026-07-17", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Hudson", "RFChannel", ...
    "27", "sourced", ...
    "RabbitEars main listing, queried 2026-07-17", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Hudson", "RFRange_MHz", ...
    "548-554", "sourced", ...
    "RabbitEars main listing, queried 2026-07-17", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Hudson", "CenterFrequency_MHz", ...
    "551", "inferred", ...
    "Midpoint of the RF27 allocation; required by this cleanup plan for RF models", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Hudson", "ERPHorizontal_kW", ...
    "400", "sourced", ...
    "RabbitEars main listing, queried 2026-07-17", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Hudson", "ERPVertical_kW", ...
    "100", "sourced", ...
    "RabbitEars main listing, queried 2026-07-17", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Hudson", "Polarization", ...
    "Inferred mixed H/V from separate ERP values", "inferred", ...
    "RabbitEars reports separate horizontal and vertical ERP values", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Hudson", "TowerLatitude_deg", ...
    "42.384083", "sourced", ...
    "RabbitEars main listing, queried 2026-07-17", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Hudson", "TowerLongitude_deg", ...
    "-71.493139", "sourced", ...
    "RabbitEars main listing, queried 2026-07-17", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Hudson", "ReceiverLocation", ...
    receiverName, "local-analysis", ...
    "FlightTest_Bistatic_RadarAndCommsAnalysis.mlx and RFBudgetInputCalcs.m", ...
    "all claims");
rows = addAssumptionRow(rows, "Hudson", "ReceiverLatitude_deg", ...
    num2str(receiverLatitude, "%.6f"), "local-analysis", ...
    "FlightTest_Bistatic_RadarAndCommsAnalysis.mlx and RFBudgetInputCalcs.m", ...
    "all claims");
rows = addAssumptionRow(rows, "Hudson", "ReceiverLongitude_deg", ...
    num2str(receiverLongitude, "%.6f"), "local-analysis", ...
    "FlightTest_Bistatic_RadarAndCommsAnalysis.mlx and RFBudgetInputCalcs.m", ...
    "all claims");
rows = addAssumptionRow(rows, "Hudson", "CurrentOperationalStatus", ...
    "Licensed", "sourced", ...
    "FCC TV profile, queried 2026-07-17", ...
    "illuminator viability");
rows = addAssumptionRow(rows, "Hudson", "TargetPathPower_dBm", ...
    "-67.37", "local-analysis", ...
    "Current RF budget scripts and supporting link-budget workflow", ...
    "bistatic detectability plausibility");
rows = addAssumptionRow(rows, "Hudson", "ReceiverAntennaGain_dBi", ...
    "12", "assumed", ...
    "Current RF budget scripts use a typical TV Yagi gain assumption", ...
    "capturability");
rows = addAssumptionRow(rows, "Hudson", "CableLossPer100ft_dB", ...
    "1.5", "assumed", ...
    "RFBudget_Ch27_Corrected 1.m", ...
    "capturability");
rows = addAssumptionRow(rows, "Hudson", "USRP_Gain_dB", ...
    "30", "assumed", ...
    "RFBudget_Ch27_Corrected 1.m nominal TwinRX gain setting", ...
    "capturability");

assumptionTable = array2table(rows, ...
    "VariableNames", ...
    ["Path", "Field", "Value", "Basis", "SourceNote", "ClaimRelevance"]);
end

function rows = addAssumptionRow(rows, pathName, fieldName, valueText, basisText, sourceText, claimText)
newRow = string({pathName, fieldName, valueText, basisText, sourceText, claimText});
rows(end + 1, :) = newRow;
end
