function riskTable = helperBuildRFRiskTable(stationSummary, sourceLinkTable, rfSummaryTable)
%helperBuildRFRiskTable Build the final RF risk summary used in the write-up.

newtonIndex = strcmp(stationSummary.Path, "Newton");
hudsonIndex = strcmp(stationSummary.Path, "Hudson");

directPathAssessment = compose( ...
    "Newton %.1f dBm after antenna and Hudson %.1f dBm after antenna are both strong enough to justify a reference-channel attenuation plan.", ...
    sourceLinkTable.DirectPathPowerAfterAntenna_dBm(newtonIndex), ...
    sourceLinkTable.DirectPathPowerAfterAntenna_dBm(hudsonIndex));

targetPathAssessment = compose( ...
    "Hudson target path %.2f dBm is carried into the RF budget; Newton currently reuses the same %.2f dBm placeholder until the Newton-specific path is rerun.", ...
    stationSummary.TargetPathPower_dBm(hudsonIndex), ...
    stationSummary.TargetPathPower_dBm(newtonIndex));

nfAssessment = compose( ...
    "System NF closes at %.2f dB for Newton and %.2f dB for Hudson with the current LNA plus TwinRX assumptions.", ...
    rfSummaryTable.SystemNF_dB(newtonIndex), ...
    rfSummaryTable.SystemNF_dB(hudsonIndex));

headroomAssessment = compose( ...
    "Direct-path outputs exceed the recommended TwinRX input window by %.1f dB (Newton) and %.1f dB (Hudson) without attenuation.", ...
    -rfSummaryTable.HeadroomToRecommendedInput_dB(newtonIndex), ...
    -rfSummaryTable.HeadroomToRecommendedInput_dB(hudsonIndex));

selectivityAssessment = compose( ...
    "The 25 C S-parameter file shows insertion loss near %.2f dB at 599 MHz and %.2f dB at 551 MHz, but adjacent-channel rejection still lacks field verification.", ...
    rfSummaryTable.FilterLoss_dB(newtonIndex), ...
    rfSummaryTable.FilterLoss_dB(hudsonIndex));

gainAssessment = compose( ...
    "Current cascade gain closes near %.1f dB for Newton and %.1f dB for Hudson; gain can be trimmed in software before capture if needed.", ...
    rfSummaryTable.TotalGain_dB(newtonIndex), ...
    rfSummaryTable.TotalGain_dB(hudsonIndex));

riskTable = table;
riskTable.Topic = [ ...
    "Direct path"; ...
    "Target path"; ...
    "Noise figure"; ...
    "Gain allocation"; ...
    "Headroom"; ...
    "Selectivity"; ...
    "IF rationale"; ...
    "Adjacent channel and interference"; ...
    "Model boundary"];
riskTable.CurrentAssessment = [ ...
    directPathAssessment; ...
    targetPathAssessment; ...
    nfAssessment; ...
    gainAssessment; ...
    headroomAssessment; ...
    selectivityAssessment; ...
    "The active working set uses a direct-sampling TwinRX chain. Legacy IF and external-mixer scripts are retained only as quick-look history, not as final evidence."; ...
    "No field spectrum survey or measured interference data is present in the repo, so adjacent-channel exposure remains an open risk rather than a closed claim."; ...
    "This pass is a system precheck only. It does not validate clutter rejection, DSI cancellation, synchronization, calibration, or measured field detectability."];
riskTable.Basis = [ ...
    "Sourced plus inferred"; ...
    "Assumed/local-analysis"; ...
    "Assumed RF chain"; ...
    "Assumed RF chain"; ...
    "Assumed RF chain"; ...
    "Measured filter S-parameters plus missing field survey"; ...
    "Working-set decision"; ...
    "Gap in local evidence"; ...
    "Deliberate scope boundary"];
riskTable.ImpactOnClaims = [ ...
    "illuminator viability; capturability"; ...
    "bistatic detectability plausibility"; ...
    "capturability; detectability plausibility"; ...
    "capturability"; ...
    "capturability"; ...
    "capturability"; ...
    "capturability"; ...
    "capturability; detectability plausibility"; ...
    "all claims"];
riskTable.RecommendedFollowOn = [ ...
    "Use a dedicated attenuated reference path during capture."; ...
    "Rerun the Newton link budget with the missing source files restored."; ...
    "Measure the assembled chain NF if confidence needs to increase."; ...
    "Retune USRP gain during bench verification before field use."; ...
    "Bench-check ADC headroom with the actual direct-path signal present."; ...
    "Run a spectrum analyzer survey and verify adjacent-channel suppression in situ."; ...
    "Do not route final decisions through the archived IF scripts."; ...
    "Add a field survey step before claiming deployed robustness."; ...
    "Keep the final story framed as plausibility, not validation."];
riskTable.Status = [ ...
    "monitor"; ...
    "open"; ...
    "monitor"; ...
    "monitor"; ...
    "open"; ...
    "open"; ...
    "closed for this pass"; ...
    "open"; ...
    "closed for this pass"];
end
