function result = helperBuildRfBudgetCase(station, directPathPowerAfterAntenna_dBm)
%helperBuildRfBudgetCase Build the RF budget for one precheck station path.

frequencyHz = station.CenterFrequency_MHz * 1e6;
signalBandwidthHz = station.SignalBandwidth_MHz * 1e6;
cableLoss_dB = station.CableLossPer100ft_dB * (station.CableLength_ft / 100);
bandpassLoss_dB = helperGetBandpassInsertionLoss(frequencyHz);

targetInputAfterAntenna_dBm = station.TargetPathPower_dBm + station.ReceiverAntennaGain_dBi;

targetBudget = rfbudget( ...
    "Elements", buildElements(station, cableLoss_dB, bandpassLoss_dB), ...
    "InputFrequency", frequencyHz, ...
    "AvailableInputPower", targetInputAfterAntenna_dBm, ...
    "SignalBandwidth", signalBandwidthHz, ...
    "Solver", "Friis", ...
    "AutoUpdate", true);

directBudget = rfbudget( ...
    "Elements", buildElements(station, cableLoss_dB, bandpassLoss_dB), ...
    "InputFrequency", frequencyHz, ...
    "AvailableInputPower", directPathPowerAfterAntenna_dBm, ...
    "SignalBandwidth", signalBandwidthHz, ...
    "Solver", "Friis", ...
    "AutoUpdate", true);

targetMetrics = extractMetrics(targetBudget, signalBandwidthHz);
directMetrics = extractMetrics(directBudget, signalBandwidthHz);

result = struct;
result.Path = station.Path;
result.CenterFrequency_MHz = station.CenterFrequency_MHz;
result.FilterLoss_dB = bandpassLoss_dB;
result.CableLoss_dB = cableLoss_dB;
result.TargetInputAfterAntenna_dBm = targetInputAfterAntenna_dBm;
result.DirectInputAfterAntenna_dBm = directPathPowerAfterAntenna_dBm;
result.TargetOutputPower_dBm = targetMetrics.OutputPower_dBm;
result.DirectOutputPower_dBm = directMetrics.OutputPower_dBm;
result.TargetPreProcessingSNR_dB = targetMetrics.SNR_dB;
result.DirectPreProcessingSNR_dB = directMetrics.SNR_dB;
result.TargetPostProcessing1sSNR_dB = targetMetrics.SNR_dB + 10 * log10(signalBandwidthHz);
result.SystemNF_dB = targetMetrics.SystemNF_dB;
result.TotalGain_dB = targetMetrics.TotalGain_dB;
result.HeadroomToRecommendedInput_dB = -15 - directMetrics.OutputPower_dBm;
result.RecommendedReferenceAttenuation_dB = max(0, ceil(directMetrics.OutputPower_dBm + 20));
result.TargetStagePowers_dBm = targetBudget.OutputPower;
result.DirectStagePowers_dBm = directBudget.OutputPower;
result.StageNames = string({targetBudget.Elements.Name});
result.TargetBudget = targetBudget;
result.DirectBudget = directBudget;
end

function elements = buildElements(station, cableLoss_dB, bandpassLoss_dB)
idx = 1;
elements(idx) = amplifier( ...
    "Name", "Cable_RG6_75ft", ...
    "Gain", -cableLoss_dB, ...
    "NF", cableLoss_dB, ...
    "Zin", 75, ...
    "Zout", 75);
idx = idx + 1;

elements(idx) = amplifier( ...
    "Name", "Impedance_Mismatch_75_to_50", ...
    "Gain", -station.MismatchLoss_dB, ...
    "NF", station.MismatchLoss_dB, ...
    "Zin", 75, ...
    "Zout", 50);
idx = idx + 1;

elements(idx) = amplifier( ...
    "Name", "HighPass_VHF580", ...
    "Gain", -station.HighPassLoss_dB, ...
    "NF", station.HighPassLoss_dB, ...
    "Zin", 50, ...
    "Zout", 50);
idx = idx + 1;

elements(idx) = rffilter( ...
    "FilterType", "Butterworth", ...
    "ResponseType", "Bandpass", ...
    "Implementation", "LC Tee", ...
    "FilterOrder", 3, ...
    "PassbandFrequency", [540 634] * 1e6, ...
    "PassbandAttenuation", bandpassLoss_dB, ...
    "Zin", 50, ...
    "Zout", 50, ...
    "Name", "BPF_ZABP587");
idx = idx + 1;

elements(idx) = amplifier( ...
    "Name", "LNA_Nooelec_LANA", ...
    "Gain", station.LNA_Gain_dB, ...
    "NF", station.LNA_NF_dB, ...
    "OIP3", station.LNA_OIP3_dBm, ...
    "Zin", 50, ...
    "Zout", 50, ...
    "Model", "poly");
idx = idx + 1;

elements(idx) = amplifier( ...
    "Name", "USRP_N320_TwinRX", ...
    "Gain", station.USRP_Gain_dB, ...
    "NF", station.USRP_NF_dB, ...
    "OIP3", station.USRP_OIP3_dBm, ...
    "Zin", 50, ...
    "Zout", 50, ...
    "Model", "poly");
end

function metrics = extractMetrics(budget, signalBandwidthHz)
kT_dBmPerHz = -174;
metrics = struct;
metrics.OutputPower_dBm = budget.OutputPower(end);
metrics.TotalGain_dB = budget.TransducerGain(end);
metrics.SystemNF_dB = budget.NF(end);
metrics.NoisePower_dBm = kT_dBmPerHz + 10 * log10(signalBandwidthHz) + metrics.SystemNF_dB;
metrics.SNR_dB = metrics.OutputPower_dBm - metrics.NoisePower_dBm;
end
