classdef bistaticTruthConventionTest < matlab.unittest.TestCase
    %BISTATICTRUTHCONVENTIONTEST Focused regression coverage for shared conventions.

    properties (Constant)
        TxLLA = [42.310278, -71.236667, 431.9];
        RxLLA = [42.2999333, -71.349333, 15.0];
        Fc = 599e6;
        Fs = 8e6;
    end

    properties (TestParameter)
        rangeRateCase = struct( ...
            'approaching', struct('rdot_mps', -120), ...
            'receding', struct('rdot_mps', 95));
    end

    methods (Test)
        function testSharedConstantsMatchCAFAxes(testCase)
            cfg = struct( ...
                'fc', testCase.Fc, ...
                'fs', testCase.Fs, ...
                'N_slow_cpi', 200, ...
                'cpi_duration_s', 0.5e-3);

            consts = helperDeriveBistaticConstants(cfg);
            ref_cube = repmat(localReferenceWaveform(64), 1, cfg.N_slow_cpi);
            surv_cube = ref_cube;
            [~, doppler_axis, range_axis, ~] = createRDM( ...
                surv_cube, ref_cube, cfg.fs, 1 / cfg.cpi_duration_s, 0, false);

            testCase.verifyEqual(consts.alpha, testCase.Fc / physconst('LightSpeed'), ...
                AbsTol=1e-12);
            testCase.verifyEqual(consts.range_cell_m, median(diff(range_axis)), ...
                AbsTol=1e-9);
            testCase.verifyEqual(consts.doppler_bin_hz, median(diff(doppler_axis)), ...
                AbsTol=1e-12);
            testCase.verifyEqual(consts.doppler_bin_hz, 10, AbsTol=1e-12);
        end

        function testCreateRDMMatchesPassiveCAFDopplerConvention(testCase, rangeRateCase)
            fs = 1e6;
            prf = 1000;
            n_fast = 64;
            n_slow = 128;
            delay_samp = 5;
            c_light = physconst('LightSpeed');

            ref_wave = localReferenceWaveform(n_fast);
            ref_cube = repmat(ref_wave, 1, n_slow);
            t_slow = (0:n_slow-1) / prf;
            phase_ramp = exp(-1j * 2 * pi * (testCase.Fc / c_light) * ...
                rangeRateCase.rdot_mps * t_slow);
            delayed = [zeros(delay_samp, 1); ref_wave(1:end-delay_samp)];
            surv_cube = delayed .* phase_ramp;

            [rdm, doppler_axis, range_axis, ~] = createRDM( ...
                surv_cube, ref_cube, fs, prf, 0, false);
            [~, r_idx] = min(abs(range_axis - delay_samp * c_light / fs));
            [~, d_idx] = max(rdm(r_idx, :));

            expected_fd = helperBistaticDopplerFromRangeRate( ...
                rangeRateCase.rdot_mps, testCase.Fc);
            testCase.verifyEqual(doppler_axis(d_idx), expected_fd, ...
                AbsTol=median(abs(diff(doppler_axis))));
        end

        function testTruthProjectionUsesThreeDimensionalBaseline(testCase)
            testCase.assumeNotEmpty(which('geodetic2enu'));

            t0 = posixtime(datetime(2026, 6, 16, 16, 7, 2, 'TimeZone', 'UTC'));
            ac_track = struct( ...
                'hex', "ABC123", ...
                'callsign', "TEST123", ...
                't_utc', [t0; t0 + 2], ...
                'lat_deg', [42.3600; 42.3600], ...
                'lon_deg', [-71.2800; -71.2800], ...
                'alt_m', [3200; 3200]);

            bist = adsbToBistatic(ac_track, testCase.TxLLA, testCase.RxLLA, testCase.Fc);
            geom = helperDeriveTxRxGeometry(testCase.TxLLA, testCase.RxLLA);

            [ac_e_rx, ac_n_rx, ac_u_rx] = geodetic2enu( ...
                ac_track.lat_deg(1), ac_track.lon_deg(1), ac_track.alt_m(1), ...
                testCase.RxLLA(1), testCase.RxLLA(2), testCase.RxLLA(3), geom.spheroid);
            [ac_e_tx, ac_n_tx, ac_u_tx] = geodetic2enu( ...
                ac_track.lat_deg(1), ac_track.lon_deg(1), ac_track.alt_m(1), ...
                testCase.TxLLA(1), testCase.TxLLA(2), testCase.TxLLA(3), geom.spheroid);

            expected_r = norm([ac_e_rx, ac_n_rx, ac_u_rx]) + ...
                norm([ac_e_tx, ac_n_tx, ac_u_tx]) - geom.baseline_3d_m;

            testCase.verifyEqual(bist.L_m, geom.baseline_3d_m, AbsTol=1e-9);
            testCase.verifyGreaterThan(geom.baseline_3d_m - geom.baseline_horizontal_m, 1);
            testCase.verifyEqual(bist.R_excess_m(1), expected_r, AbsTol=1e-6);
        end

        function testProjectionHelperUsesBaselineConsistentRangeExcess(testCase)
            testCase.assumeNotEmpty(which('geodetic2enu'));

            t0 = posixtime(datetime(2026, 6, 16, 16, 7, 2, 'TimeZone', 'UTC'));
            track = localBuildTrack( ...
                "ABC123", ...
                "BASE123", ...
                [t0; t0 + 2], ...
                [42.3600; 42.3600], ...
                [-71.2800; -71.2800], ...
                [3200; 3200]);
            query_times_s = [0; 1; 2];

            [adsb_bistatic, adsb_aligned, projection_table] = ...
                helperProjectADSBTruthToRangeDoppler( ...
                track, ...
                testCase.TxLLA, ...
                testCase.RxLLA, ...
                testCase.Fc, ...
                t0, ...
                query_times_s);
            projection_rows = localProjectionRows(projection_table, "ABC123");
            geom = helperDeriveTxRxGeometry(testCase.TxLLA, testCase.RxLLA);

            [ac_e_rx, ac_n_rx, ac_u_rx] = geodetic2enu( ...
                track.lat_deg(1), track.lon_deg(1), track.alt_m(1), ...
                testCase.RxLLA(1), testCase.RxLLA(2), testCase.RxLLA(3), geom.spheroid);
            [ac_e_tx, ac_n_tx, ac_u_tx] = geodetic2enu( ...
                track.lat_deg(1), track.lon_deg(1), track.alt_m(1), ...
                testCase.TxLLA(1), testCase.TxLLA(2), testCase.TxLLA(3), geom.spheroid);
            expected_r = norm([ac_e_rx, ac_n_rx, ac_u_rx]) + ...
                norm([ac_e_tx, ac_n_tx, ac_u_tx]) - geom.baseline_3d_m;

            testCase.verifyEqual(adsb_bistatic(1).R_excess_m(1), expected_r, AbsTol=1e-6);
            testCase.verifyEqual(adsb_aligned(1).R_excess_m(1), expected_r, AbsTol=1e-6);
            testCase.verifyEqual(projection_rows.R_excess_m(1), expected_r, AbsTol=1e-6);
            testCase.verifyTrue(projection_rows.valid(1));
        end

        function testProjectionHelperKeepsApproachingAndRecedingDopplerSigns(testCase)
            t0 = posixtime(datetime(2026, 6, 16, 16, 7, 2, 'TimeZone', 'UTC'));
            query_times_s = [0; 1; 2];
            track_a = localBuildTrack( ...
                "ABC201", ...
                "SIGN201", ...
                t0 + query_times_s, ...
                [42.3650; 42.3600; 42.3550], ...
                [-71.3300; -71.3200; -71.3100], ...
                [3300; 3300; 3300]);
            track_b = localBuildTrack( ...
                "ABC202", ...
                "SIGN202", ...
                t0 + query_times_s, ...
                flipud(track_a.lat_deg), ...
                flipud(track_a.lon_deg), ...
                flipud(track_a.alt_m));

            [adsb_bistatic, ~, projection_table] = helperProjectADSBTruthToRangeDoppler( ...
                [track_a, track_b], ...
                testCase.TxLLA, ...
                testCase.RxLLA, ...
                testCase.Fc, ...
                t0, ...
                query_times_s);
            rows_a = localProjectionRows(projection_table, "ABC201");
            rows_b = localProjectionRows(projection_table, "ABC202");
            delta_r_a = adsb_bistatic(1).R_excess_m(end) - adsb_bistatic(1).R_excess_m(1);
            delta_r_b = adsb_bistatic(2).R_excess_m(end) - adsb_bistatic(2).R_excess_m(1);
            mean_fd_a = mean(rows_a.f_D_hz(rows_a.valid), 'omitnan');
            mean_fd_b = mean(rows_b.f_D_hz(rows_b.valid), 'omitnan');

            testCase.verifyTrue(sign(delta_r_a) ~= 0);
            testCase.verifyEqual(sign(delta_r_a), -sign(delta_r_b));
            testCase.verifyEqual(sign(mean_fd_a), -sign(delta_r_a));
            testCase.verifyEqual(sign(mean_fd_b), -sign(delta_r_b));
            testCase.verifyEqual(sign(mean_fd_a), -sign(mean_fd_b));
        end

        function testProjectionHelperMarksOutsideWindowQueriesInvalid(testCase)
            t0 = posixtime(datetime(2026, 6, 16, 16, 7, 2, 'TimeZone', 'UTC'));
            track = localBuildTrack( ...
                "ABC301", ...
                "WIND301", ...
                [t0 + 10; t0 + 12], ...
                [42.3500; 42.3510], ...
                [-71.3100; -71.3090], ...
                [3000; 3000]);
            query_times_s = [0; 10; 11; 12; 13];

            [~, adsb_aligned, projection_table] = helperProjectADSBTruthToRangeDoppler( ...
                track, ...
                testCase.TxLLA, ...
                testCase.RxLLA, ...
                testCase.Fc, ...
                t0, ...
                query_times_s);
            projection_rows = localProjectionRows(projection_table, "ABC301");

            testCase.verifyFalse(projection_rows.valid(1));
            testCase.verifyFalse(projection_rows.valid(end));
            testCase.verifyTrue(all(projection_rows.valid(2:4)));
            testCase.verifyTrue(isnan(adsb_aligned(1).R_excess_m(1)));
            testCase.verifyTrue(isnan(adsb_aligned(1).f_D_hz(end)));
        end

        function testProjectionHelperLeavesSingleFixTrackNonInterpolable(testCase)
            t0 = posixtime(datetime(2026, 6, 16, 16, 7, 2, 'TimeZone', 'UTC'));
            track = localBuildTrack( ...
                "ABC401", ...
                "ONE401", ...
                t0 + 10, ...
                42.3550, ...
                -71.3050, ...
                3100);
            query_times_s = [10; 11];

            [adsb_bistatic, adsb_aligned, projection_table] = ...
                helperProjectADSBTruthToRangeDoppler( ...
                track, ...
                testCase.TxLLA, ...
                testCase.RxLLA, ...
                testCase.Fc, ...
                t0, ...
                query_times_s);
            projection_rows = localProjectionRows(projection_table, "ABC401");

            testCase.verifyNumElements(adsb_bistatic, 1);
            testCase.verifyEqual(numel(adsb_bistatic(1).R_excess_m), 1);
            testCase.verifyTrue(all(~projection_rows.valid));
            testCase.verifyTrue(all(isnan(adsb_aligned(1).R_excess_m)));
            testCase.verifyTrue(all(isnan(adsb_aligned(1).f_D_hz)));
        end

        function testProjectionHelperHandlesDuplicateTimestampsWithoutFailure(testCase)
            t0 = posixtime(datetime(2026, 6, 16, 16, 7, 2, 'TimeZone', 'UTC'));
            track = localBuildTrack( ...
                "ABC501", ...
                "DUP501", ...
                [t0; t0; t0 + 2], ...
                [42.3480; 42.3485; 42.3490], ...
                [-71.3250; -71.3230; -71.3210], ...
                [2900; 2900; 2900]);
            query_times_s = [0; 1; 2];

            [adsb_bistatic, adsb_aligned, projection_table] = ...
                helperProjectADSBTruthToRangeDoppler( ...
                track, ...
                testCase.TxLLA, ...
                testCase.RxLLA, ...
                testCase.Fc, ...
                t0, ...
                query_times_s);
            projection_rows = localProjectionRows(projection_table, "ABC501");

            testCase.verifyTrue(all(isfinite(adsb_bistatic(1).f_D_hz)));
            testCase.verifyTrue(all(isfinite(adsb_aligned(1).R_excess_m)));
            testCase.verifyTrue(all(projection_rows.valid));
        end

        function testRangeRateRoundTripAndTrackHistoryShareTheSameConvention(testCase)
            rdot_mps = -87.5;
            fd_hz = helperBistaticDopplerFromRangeRate(rdot_mps, testCase.Fc);
            rdot_roundtrip = helperBistaticRangeRateFromDoppler(fd_hz, testCase.Fc);

            snapshot = struct( ...
                'time', 12.5, ...
                'tracks', struct( ...
                    'TrackID', 42, ...
                    'State', [15000; rdot_mps], ...
                    'StateCovariance', eye(2)), ...
                'n_confirmed', 1);

            history = helperTracksLogToHistories(snapshot, testCase.Fc);

            testCase.verifyEqual(rdot_roundtrip, rdot_mps, AbsTol=1e-12);
            testCase.verifyEqual(history.f_D_hz, fd_hz, AbsTol=1e-12);
            testCase.verifyEqual(history.Rdot_mps, rdot_mps, AbsTol=1e-12);
        end

        function testInitMeasurementSpaceKFUsesSharedConversions(testCase)
            testCase.assumeNotEmpty(which('objectDetection'));
            testCase.assumeNotEmpty(which('trackingKF'));

            rdot_mps = -95;
            fd_hz = helperBistaticDopplerFromRangeRate(rdot_mps, testCase.Fc);
            det = objectDetection(0, [12000; fd_hz], 'MeasurementNoise', eye(2));

            filter = initMeasurementSpaceKF(det, testCase.Fc, testCase.Fs, 10);
            alpha = helperBistaticDopplerCoupling(testCase.Fc);

            testCase.verifyEqual(filter.State(2), rdot_mps, AbsTol=1e-12);
            testCase.verifyEqual(filter.MeasurementModel(2, 2), -alpha, AbsTol=1e-12);
            testCase.verifyEqual(filter.MeasurementNoise(1, 1), ...
                (3 * physconst('LightSpeed') / testCase.Fs)^2, AbsTol=1e-6);
        end
    end
end

function ref_wave = localReferenceWaveform(n_fast)
t = (0:n_fast-1).';
ref_wave = exp(1j * 2 * pi * (0.17 * t + 0.013 * t.^2 / max(n_fast, 1)));
end

function track = localBuildTrack(hex, callsign, t_utc, lat_deg, lon_deg, alt_m)
t_utc = double(t_utc(:));
lat_deg = double(lat_deg(:));
lon_deg = double(lon_deg(:));
alt_m = double(alt_m(:));
n_points = numel(t_utc);

track = struct( ...
    'hex', char(string(hex)), ...
    'callsign', char(string(callsign)), ...
    't_utc', t_utc, ...
    'lat_deg', lat_deg, ...
    'lon_deg', lon_deg, ...
    'alt_m', alt_m, ...
    'speed_mps', zeros(n_points, 1), ...
    'track_deg', zeros(n_points, 1), ...
    'vrate_mps', zeros(n_points, 1));
end

function projection_rows = localProjectionRows(projection_table, hex)
projection_rows = projection_table(projection_table.hex == string(hex), :);
end
