function opportunity_table = buildManualADSBOpportunityTable(adsb_tracks, config)
%BUILDMANUALADSBOPPORTUNITYTABLE Rank archived ADS-B tracks for manual capture.
%
%   table_out = buildManualADSBOpportunityTable(adsb_tracks)
%   table_out = buildManualADSBOpportunityTable(adsb_tracks, config)
%
%   Each row describes one aircraft at its closest observed ADS-B position
%   to the receiver. Bistatic range and Doppler come from adsbToBistatic so
%   this table shares the project's three-dimensional geometry and passive
%   CAF sign convention (positive Doppler means decreasing excess range).
%
%   BiSNR_dB is an assumption-based bistatic radar-equation estimate. Its
%   assumptions and source are carried in every row. It is useful for
%   relative manual ranking, but it is not a calibrated probability of
%   detection and does not initiate acquisition.

if nargin < 2 || isempty(config)
    config = helperADSBRemoter599MHzConfig();
end

localValidateTracks(adsb_tracks);
localValidateConfig(config);

if isempty(adsb_tracks)
    opportunity_table = localEmptyOpportunityTable();
    return
end

geometry = helperDeriveTxRxGeometry(config.TxLLA, config.RxLLA);
adsb_bistatic = adsbToBistatic( ...
    adsb_tracks, config.TxLLA, config.RxLLA, config.CenterFrequency_Hz);

row_count = numel(adsb_bistatic);
aircraft_id = strings(row_count, 1);
callsign = strings(row_count, 1);
cpa_time_utc = NaT(row_count, 1, 'TimeZone', 'UTC');
cpa_distance_m = NaN(row_count, 1);
transmitter_range_m = NaN(row_count, 1);
excess_range_m = NaN(row_count, 1);
doppler_hz = NaN(row_count, 1);
bisnr_db = NaN(row_count, 1);
position_fix_count = zeros(row_count, 1);
cpa_is_track_endpoint = false(row_count, 1);

for track_idx = 1:row_count
    track = adsb_bistatic(track_idx);
    [east_m, north_m, up_m] = geodetic2enu( ...
        track.lat_deg, track.lon_deg, track.alt_m, ...
        config.RxLLA(1), config.RxLLA(2), config.RxLLA(3), ...
        geometry.spheroid);
    receiver_ranges_m = sqrt(east_m.^2 + north_m.^2 + up_m.^2);
    [cpa_distance_m(track_idx), cpa_idx] = min(receiver_ranges_m);

    aircraft_id(track_idx) = upper(string(track.hex));
    callsign(track_idx) = strtrim(string(track.callsign));
    cpa_time_utc(track_idx) = datetime( ...
        track.t_utc(cpa_idx), 'ConvertFrom', 'posixtime', 'TimeZone', 'UTC');
    excess_range_m(track_idx) = track.R_excess_m(cpa_idx);
    doppler_hz(track_idx) = track.f_D_hz(cpa_idx);
    transmitter_range_m(track_idx) = ...
        excess_range_m(track_idx) + geometry.baseline_3d_m - ...
        cpa_distance_m(track_idx);
    bisnr_db(track_idx) = localAssumedBiSNR( ...
        transmitter_range_m(track_idx), cpa_distance_m(track_idx), config);
    position_fix_count(track_idx) = numel(track.t_utc);
    cpa_is_track_endpoint(track_idx) = ...
        cpa_idx == 1 || cpa_idx == numel(track.t_utc);
end

source_id = repmat(string(config.SourceID), row_count, 1);
assumption_id = repmat(string(config.AssumptionID), row_count, 1);
cpa_method = repmat(string(config.CPAMethod), row_count, 1);
emitter_id = repmat(string(config.EmitterID), row_count, 1);
bisnr_assumption_based = true(row_count, 1);
bisnr_rank = zeros(row_count, 1);

opportunity_table = table( ...
    aircraft_id, callsign, cpa_time_utc, cpa_distance_m, ...
    transmitter_range_m, excess_range_m, doppler_hz, bisnr_db, ...
    bisnr_rank, bisnr_assumption_based, position_fix_count, ...
    cpa_is_track_endpoint, emitter_id, source_id, assumption_id, cpa_method, ...
    'VariableNames', localVariableNames());

opportunity_table = sortrows( ...
    opportunity_table, {'BiSNR_dB', 'AircraftID'}, {'descend', 'ascend'});
opportunity_table.BiSNRRank = (1:height(opportunity_table)).';

end

function snr_db = localAssumedBiSNR( ...
        transmitter_range_m, receiver_range_m, config)
% Mirror ADSB-remoter's itemized bistatic radar equation. EIRP already
% includes transmitter antenna gain, while receive gain remains explicit.
c = physconst('LightSpeed');
boltzmann_j_per_k = 1.380649e-23;
wavelength_m = c ./ config.CenterFrequency_Hz;

eirp_dbw = 10 .* log10(config.EmitterEIRP_kW .* 1000);
wavelength_gain_db = 20 .* log10(wavelength_m);
spreading_loss_db = -30 .* log10(4 .* pi);
transmitter_range_loss_db = -20 .* log10(transmitter_range_m);
receiver_range_loss_db = -20 .* log10(receiver_range_m);
thermal_noise_dbw = 10 .* log10( ...
    boltzmann_j_per_k .* config.NoiseTemperature_K .* ...
    config.ReceiverBandwidth_Hz);

snr_db = ...
    eirp_dbw + ...
    config.ReceiverGain_dBi + ...
    wavelength_gain_db + ...
    config.BistaticRCS_dBsm + ...
    spreading_loss_db + ...
    transmitter_range_loss_db + ...
    receiver_range_loss_db - ...
    thermal_noise_dbw - ...
    config.NoiseFigure_dB - ...
    config.PolarizationLoss_dB - ...
    config.SystemLoss_dB;
end

function localValidateTracks(adsb_tracks)
if ~isstruct(adsb_tracks)
    error('buildManualADSBOpportunityTable:badTracks', ...
        'adsb_tracks must be the struct returned by loadADSBTruth.');
end

required_fields = { ...
    'hex', 'callsign', 't_utc', 'lat_deg', 'lon_deg', 'alt_m'};
if ~all(isfield(adsb_tracks, required_fields))
    error('buildManualADSBOpportunityTable:badTracks', ...
        'adsb_tracks does not match the loadADSBTruth trajectory schema.');
end
end

function localValidateConfig(config)
required_fields = { ...
    'TxLLA', 'RxLLA', 'CenterFrequency_Hz', 'EmitterEIRP_kW', ...
    'EmitterID', 'ReceiverGain_dBi', 'NoiseFigure_dB', ...
    'ReceiverBandwidth_Hz', 'BistaticRCS_dBsm', ...
    'PolarizationLoss_dB', 'SystemLoss_dB', 'NoiseTemperature_K', ...
    'CPAMethod', 'SourceID', 'AssumptionID'};
if ~isstruct(config) || ~all(isfield(config, required_fields))
    error('buildManualADSBOpportunityTable:badConfig', ...
        'config must come from helperADSBRemoter599MHzConfig.');
end

validateattributes(config.TxLLA, {'numeric'}, ...
    {'row', 'numel', 3, 'real', 'finite'}, mfilename, 'config.TxLLA');
validateattributes(config.RxLLA, {'numeric'}, ...
    {'row', 'numel', 3, 'real', 'finite'}, mfilename, 'config.RxLLA');
validateattributes(config.CenterFrequency_Hz, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'}, ...
    mfilename, 'config.CenterFrequency_Hz');
validateattributes(config.EmitterEIRP_kW, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'}, ...
    mfilename, 'config.EmitterEIRP_kW');
validateattributes(config.ReceiverBandwidth_Hz, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'}, ...
    mfilename, 'config.ReceiverBandwidth_Hz');
validateattributes(config.NoiseTemperature_K, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'}, ...
    mfilename, 'config.NoiseTemperature_K');
end

function names = localVariableNames()
names = { ...
    'AircraftID', ...
    'Callsign', ...
    'CPATimeUTC', ...
    'CPADistance_m', ...
    'TransmitterRange_m', ...
    'ExcessRange_m', ...
    'Doppler_Hz', ...
    'BiSNR_dB', ...
    'BiSNRRank', ...
    'BiSNRAssumptionBased', ...
    'PositionFixCount', ...
    'CPAIsTrackEndpoint', ...
    'EmitterID', ...
    'SourceID', ...
    'AssumptionID', ...
    'CPAMethod'};
end

function opportunity_table = localEmptyOpportunityTable()
opportunity_table = table( ...
    strings(0, 1), ...
    strings(0, 1), ...
    NaT(0, 1, 'TimeZone', 'UTC'), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    false(0, 1), ...
    zeros(0, 1), ...
    false(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    'VariableNames', localVariableNames());
end
