function source_info = helperResolveDirectPathPrecheckSource(source, varargin)
%HELPERRESOLVEDIRECTPATHPRECHECKSOURCE Resolve a session ID or radar file path.
%
%  source_info = helperResolveDirectPathPrecheckSource(source)
%
%  This helper keeps the pre-analysis diagnostic lightweight:
%  - If SOURCE is an existing `.bb` file, use it directly.
%  - Otherwise treat SOURCE as a packaged session ID and resolve the radar
%    files through the existing session-manifest helper.

p = inputParser;
p.FunctionName = mfilename;
addRequired(p, 'source', @(x) ischar(x) || isstring(x));
addParameter(p, 'DatasetRoot', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'SessionFolder', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'ManifestPath', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'PartIndex', 1, @(x) isnumeric(x) && isscalar(x) && x >= 1 && mod(x, 1) == 0);
addParameter(p, 'Verbose', false, @(x) islogical(x) && isscalar(x));
parse(p, source, varargin{:});
opts = p.Results;

source_str = char(string(opts.source));

if isempty(source_str)
    error('helperResolveDirectPathPrecheckSource:emptySource', ...
        'Provide either a packaged session ID or a .bb radar file path.');
end

if exist(source_str, 'file') == 2
    [~, file_name, file_ext] = fileparts(source_str);
    source_info = struct( ...
        'source_kind',      "radar_file", ...
        'source_label',     string([file_name, file_ext]), ...
        'session_id',       "", ...
        'manifest_path',    "", ...
        'session_folder',   "", ...
        'data_folder',      string(fileparts(source_str)), ...
        'radar_file',       string(source_str), ...
        'part_index',       1);
    return
end

if endsWith(source_str, '.bb', 'IgnoreCase', true)
    error('helperResolveDirectPathPrecheckSource:fileNotFound', ...
        'Radar file not found: %s', source_str);
end

analysis_setup = helperResolveSessionAnalysisSetup( ...
    source_str, ...
    'DatasetRoot', opts.DatasetRoot, ...
    'SessionFolder', opts.SessionFolder, ...
    'ManifestPath', opts.ManifestPath, ...
    'Verbose', opts.Verbose);

if opts.PartIndex > numel(analysis_setup.data_parts)
    error('helperResolveDirectPathPrecheckSource:partIndexOutOfRange', ...
        'PartIndex %d exceeds the %d radar file(s) in session %s.', ...
        opts.PartIndex, numel(analysis_setup.data_parts), analysis_setup.session_id);
end

radar_file = analysis_setup.data_parts{opts.PartIndex};
[~, file_name, file_ext] = fileparts(radar_file);

source_info = struct( ...
    'source_kind',      "session", ...
    'source_label',     string([file_name, file_ext]), ...
    'session_id',       string(analysis_setup.session_id), ...
    'manifest_path',    string(analysis_setup.manifest_path), ...
    'session_folder',   string(analysis_setup.session_folder), ...
    'data_folder',      string(analysis_setup.data_folder), ...
    'radar_file',       string(radar_file), ...
    'part_index',       opts.PartIndex);
end
