function visualization = helperResolveVisualizationProfile(varargin)
%HELPERRESOLVEVISUALIZATIONPROFILE Normalize graphics settings for one run.
%
% Plain-language goal:
%   The full passive-radar session can open many figure windows. This
%   helper groups the graphics switches into three stable profiles so the
%   session wrapper and the manual script stay in sync:
%     full     - enable every supported plotting path
%     core     - keep the highest-value views, disable globe rendering and
%                companion figures
%     headless - run the analysis without opening interactive figures
%
% Syntax
%   visualization = helperResolveVisualizationProfile()
%   visualization = helperResolveVisualizationProfile( ...
%       'VisualizationProfile', 'core', ...
%       'PlotPerPartRDM', true, ...
%       'ExpectedPartCount', 15)
%
% Name-value options
%   'VisualizationProfile'       'full', 'core', or 'headless'
%   'PlotAssessmentFigures'      Override profile default
%   'PlotPerPartRDM'             Override profile default
%   'PlotEllipseGlobe'           Override profile default
%   'PlotTrackerGlobe'           Override profile default
%   'PlotTrackLegend'            Override profile default
%   'PlotInteractiveRDViewer'    Override profile default
%   'PlotTruthDiagnostics'       Override profile default
%   'Force2DGeographicFallback'  Force geoaxes instead of geoglobe
%   'ExpectedPartCount'          Number of radar parts for audit text
%
% Output
%   visualization  Struct containing the resolved booleans plus:
%     .figure_inventory
%     .ranked_crash_causes
%     .max_expected_open_figure_count
%
% See also: analyzeBistaticData, runBistaticAnalysisSession.

p = inputParser;
p.FunctionName = mfilename;
p.PartialMatching = false;
addParameter(p, 'VisualizationProfile', "core", @localIsVisualizationProfile);
addParameter(p, 'PlotAssessmentFigures', [], @localIsOptionalLogicalScalar);
addParameter(p, 'PlotPerPartRDM', [], @localIsOptionalLogicalScalar);
addParameter(p, 'PlotEllipseGlobe', [], @localIsOptionalLogicalScalar);
addParameter(p, 'PlotTrackerGlobe', [], @localIsOptionalLogicalScalar);
addParameter(p, 'PlotTrackLegend', [], @localIsOptionalLogicalScalar);
addParameter(p, 'PlotInteractiveRDViewer', [], @localIsOptionalLogicalScalar);
addParameter(p, 'PlotTruthDiagnostics', [], @localIsOptionalLogicalScalar);
addParameter(p, 'Force2DGeographicFallback', [], @localIsOptionalLogicalScalar);
addParameter(p, 'ExpectedPartCount', NaN, @(x) isnumeric(x) && isscalar(x));
parse(p, varargin{:});
opts = p.Results;

profile = string(opts.VisualizationProfile);
profile = lower(strtrim(profile));
if strlength(profile) == 0
    profile = "core";
end

defaults = localProfileDefaults(profile);

visualization = defaults;
visualization.profile = profile;
visualization.expected_part_count = double(opts.ExpectedPartCount);

visualization.plot_assessment_figures = localResolveOverride( ...
    opts.PlotAssessmentFigures, defaults.plot_assessment_figures);
visualization.plot_per_part_rdm = localResolveOverride( ...
    opts.PlotPerPartRDM, defaults.plot_per_part_rdm);
visualization.plot_ellipse_globe = localResolveOverride( ...
    opts.PlotEllipseGlobe, defaults.plot_ellipse_globe);
visualization.plot_tracker_globe = localResolveOverride( ...
    opts.PlotTrackerGlobe, defaults.plot_tracker_globe);
visualization.plot_track_legend = localResolveOverride( ...
    opts.PlotTrackLegend, defaults.plot_track_legend);
visualization.plot_interactive_rdm_viewer = localResolveOverride( ...
    opts.PlotInteractiveRDViewer, defaults.plot_interactive_rdm_viewer);
visualization.plot_truth_diagnostics = localResolveOverride( ...
    opts.PlotTruthDiagnostics, defaults.plot_truth_diagnostics);
visualization.force_2d_geographic_fallback = localResolveOverride( ...
    opts.Force2DGeographicFallback, defaults.force_2d_geographic_fallback);

visualization.plot_truth_detection_time_series = ...
    visualization.plot_truth_diagnostics;
visualization.plot_truth_track_comparison = ...
    visualization.plot_truth_diagnostics;
visualization.plot_truth_rdm_overlays = false;

if ~visualization.plot_tracker_globe
    visualization.plot_track_legend = false;
end

if visualization.profile == "headless"
    visualization.plot_assessment_figures = false;
    visualization.plot_per_part_rdm = false;
    visualization.plot_ellipse_globe = false;
    visualization.plot_tracker_globe = false;
    visualization.plot_track_legend = false;
    visualization.plot_interactive_rdm_viewer = false;
    visualization.plot_truth_diagnostics = false;
    visualization.plot_truth_detection_time_series = false;
    visualization.plot_truth_track_comparison = false;
    visualization.plot_truth_rdm_overlays = false;
end

visualization.figure_inventory = localBuildFigureInventory(visualization);
visualization.max_expected_open_figure_count = sum( ...
    visualization.figure_inventory.figure_count_when_enabled( ...
    visualization.figure_inventory.enabled));
visualization.ranked_crash_causes = localBuildCrashCauseTable(visualization);
visualization.recommended_profile = "core";

end

function defaults = localProfileDefaults(profile)
switch profile
    case "full"
        defaults = struct( ...
            'plot_assessment_figures', true, ...
            'plot_per_part_rdm', true, ...
            'plot_ellipse_globe', true, ...
            'plot_tracker_globe', true, ...
            'plot_track_legend', true, ...
            'plot_interactive_rdm_viewer', true, ...
            'plot_truth_diagnostics', true, ...
            'force_2d_geographic_fallback', false);

    case "headless"
        defaults = struct( ...
            'plot_assessment_figures', false, ...
            'plot_per_part_rdm', false, ...
            'plot_ellipse_globe', false, ...
            'plot_tracker_globe', false, ...
            'plot_track_legend', false, ...
            'plot_interactive_rdm_viewer', false, ...
            'plot_truth_diagnostics', false, ...
            'force_2d_geographic_fallback', false);

    otherwise
        defaults = struct( ...
            'plot_assessment_figures', false, ...
            'plot_per_part_rdm', false, ...
            'plot_ellipse_globe', false, ...
            'plot_tracker_globe', false, ...
            'plot_track_legend', false, ...
            'plot_interactive_rdm_viewer', true, ...
            'plot_truth_diagnostics', true, ...
            'force_2d_geographic_fallback', false);
end
end

function value = localResolveOverride(override_value, default_value)
if isempty(override_value)
    value = logical(default_value);
else
    value = logical(override_value);
end
end

function inventory = localBuildFigureInventory(visualization)
per_part_note = localPerPartRDMNote(visualization.expected_part_count);
ellipse_renderer = localGeographicRendererLabel( ...
    visualization.force_2d_geographic_fallback, true);
tracker_renderer = localGeographicRendererLabel( ...
    visualization.force_2d_geographic_fallback, false);

inventory = table( ...
    [ ...
        "assessDetections"; ...
        "analyzeBistaticData"; ...
        "plotBistaticEllipses3D"; ...
        "analyzeBistaticData"; ...
        "analyzeBistaticData"; ...
        "analyzeBistaticData"; ...
        "runDetectionTruthDiagnostics"; ...
        "runDetectionTruthDiagnostics"], ...
    [ ...
        "Assessment figures"; ...
        "Per-part RDM viewer"; ...
        "Ellipse geographic view"; ...
        "Tracker geographic view"; ...
        "Track legend figure"; ...
        "Interactive RD viewer"; ...
        "Detection-vs-truth time series"; ...
        "Track comparison figure"], ...
    [ ...
        visualization.plot_assessment_figures; ...
        visualization.plot_per_part_rdm; ...
        visualization.plot_ellipse_globe; ...
        visualization.plot_tracker_globe; ...
        visualization.plot_track_legend; ...
        visualization.plot_interactive_rdm_viewer; ...
        visualization.plot_truth_detection_time_series; ...
        visualization.plot_truth_track_comparison], ...
    [4; 1; 2; 1; 1; 1; 1; 1], ...
    [ ...
        "classic figure"; ...
        "classic figure + uicontrol"; ...
        ellipse_renderer; ...
        tracker_renderer; ...
        "classic figure"; ...
        "classic figure + uicontrol"; ...
        "classic figure"; ...
        "classic figure"], ...
    [ ...
        "medium"; ...
        "medium"; ...
        "medium"; ...
        "high"; ...
        "low"; ...
        "high"; ...
        "high"; ...
        "high"], ...
    [ ...
        "detections required"; ...
        "parts required"; ...
        "detections required"; ...
        "detections required"; ...
        "detections required"; ...
        "detections required"; ...
        "ADS-B truth required"; ...
        "ADS-B truth required"], ...
    [ ...
        "Representative assessment figures for Part 1."; ...
        per_part_note; ...
        "Globe/map plus a Doppler color-scale companion figure."; ...
        "Shows last-known track ellipses on the map or globe."; ...
        "Lowest-value companion window; console mapping remains available."; ...
        "Highest-value interactive radar view for stepping through tracker time."; ...
        "Primary truth-vs-detection diagnostic view."; ...
        "Legacy track-vs-truth validation view."; ...
        ], ...
    'VariableNames', { ...
        'callsite', ...
        'figure_group', ...
        'enabled', ...
        'figure_count_when_enabled', ...
        'renderer_type', ...
        'utility_rank', ...
        'data_dependency', ...
        'notes'});
end

function cause_table = localBuildCrashCauseTable(visualization)
geographic_enabled = visualization.plot_ellipse_globe || ...
    visualization.plot_tracker_globe;
graphics_pressure_enabled = geographic_enabled || ...
    visualization.max_expected_open_figure_count >= 6;

cause_table = table( ...
    [1; 2; 3; 4], ...
    [ ...
        "geoglobe / uifigure / WebGL rendering"; ...
        "Per-part RDM figure fan-out"; ...
        "Combined graphics memory and GPU pressure"; ...
        "Figure export / file-save path"], ...
    [ ...
        "high"; ...
        "medium"; ...
        "medium"; ...
        "low"], ...
    [ ...
        geographic_enabled && ~visualization.force_2d_geographic_fallback; ...
        visualization.plot_per_part_rdm; ...
        graphics_pressure_enabled; ...
        false], ...
    [ ...
        "Highest-risk path when 3-D globe rendering is enabled."; ...
        "Mitigated by the single-window part viewer, but still worth gating on burst sessions."; ...
        "Multiple figures and UI controls can still compound RAM and GPU load in one run."; ...
        "Low-priority suspect; exportgraphics is not on the main-session default path."; ...
        ], ...
    'VariableNames', { ...
        'rank', ...
        'cause', ...
        'confidence', ...
        'active_in_profile', ...
        'notes'});
end

function note = localPerPartRDMNote(expected_part_count)
if isfinite(expected_part_count) && expected_part_count >= 1
    note = sprintf([ ...
        'Single-window slider viewer replaces the legacy %d-window ' ...
        'per-part fan-out.'], round(expected_part_count));
else
    note = 'Single-window slider viewer replaces the legacy per-part fan-out.';
end
end

function label = localGeographicRendererLabel(force_2d, include_color_scale)
if force_2d
    label = "figure + geoaxes";
else
    label = "uifigure + geoglobe";
end

if include_color_scale
    label = label + " + classic color-scale figure";
end
end

function tf = localIsVisualizationProfile(value)
value = string(value);
value = lower(strtrim(value));
if strlength(value) == 0
    tf = true;
    return
end

tf = any(strcmp(value, ["full", "core", "headless"]));
end

function tf = localIsOptionalLogicalScalar(value)
tf = isempty(value) || ...
    (islogical(value) && isscalar(value)) || ...
    (isnumeric(value) && isscalar(value) && any(value == [0, 1]));
end
