function profile = helperMeasurePilotCoherenceProfile(reference_cube, reference_channel, fs, varargin)
%HELPERMEASUREPILOTCOHERENCEPROFILE Build spectrum and pilot-coherence traces.
%
%  A healthy ATSC reference has two distinct signatures:
%  1. Broadband occupied spectrum across the HDTV channel.
%  2. A single highly coherent pilot tone that rises above the incoherent
%     data carriers when we average the FFT across many CPIs.
%
%  This helper returns both traces so the precheck can plot them and
%  quantify how "ATSC-like" the reference looks before running ECA-C.

p = inputParser;
p.FunctionName = mfilename;
addRequired(p, 'reference_cube', @(x) isnumeric(x));
addRequired(p, 'reference_channel', @(x) isnumeric(x));
addRequired(p, 'fs', @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'CaptureCenterFrequencyHz', [], @(x) isempty(x) || (isnumeric(x) && isscalar(x)));
addParameter(p, 'CaptureTuneFrequencyHz', [], @(x) isempty(x) || (isnumeric(x) && isscalar(x)));
addParameter(p, 'LOOffsetHz', 0, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'SessionManifestCenterFrequencyHz', [], @(x) isempty(x) || (isnumeric(x) && isscalar(x)));
addParameter(p, 'SessionManifestLOOffsetHz', [], @(x) isempty(x) || (isnumeric(x) && isscalar(x)));
addParameter(p, 'IlluminatorCenterFrequencyHz', [], @(x) isempty(x) || isnumeric(x));
addParameter(p, 'PilotSearchHalfWidthHz', 300e3, @(x) isnumeric(x) && isscalar(x) && x > 0);
parse(p, reference_cube, reference_channel, fs, varargin{:});
opts = p.Results;

reference_cube = double(reference_cube);
reference_channel = double(reference_channel(:));

n_fast = size(reference_cube, 1);
n_slow = size(reference_cube, 2);

% Coherent pilot profile: compare coherent and incoherent FFT averages
% across the CPI columns. A true pilot remains phase-stable across slow
% time, so it stands out strongly in this ratio.
n_fft_coh = 2^nextpow2(max(n_fast, 2));
fft_cube = fft(reference_cube, n_fft_coh, 1);
mean_coh_fft = mean(fft_cube, 2);
mean_incoh_power = mean(abs(fft_cube).^2, 2);
coherence_ratio = abs(mean_coh_fft).^2 ./ max(mean_incoh_power, eps);
coherence_snr_db = 10 * log10(coherence_ratio * max(n_slow, 1) + eps);
spectral_power_db = fftshift(10 * log10(mean_incoh_power + eps));

coherence_freq_axis_hz = (-n_fft_coh/2 : n_fft_coh/2 - 1).' * (fs / n_fft_coh);
coherence_snr_db = fftshift(coherence_snr_db);

frequency_context = helperResolveCaptureFrequencyContext( ...
    'RequestedIlluminatorCenterHz', opts.IlluminatorCenterFrequencyHz, ...
    'HeaderCenterFrequencyHz', opts.CaptureCenterFrequencyHz, ...
    'HeaderLOOffsetHz', opts.LOOffsetHz, ...
    'SessionManifestCenterFrequencyHz', opts.SessionManifestCenterFrequencyHz, ...
    'SessionManifestLOOffsetHz', opts.SessionManifestLOOffsetHz);

pilot_selection = helperSelectATSCPilotCandidate( ...
    coherence_freq_axis_hz, coherence_snr_db, ...
    'SampleRateHz', fs, ...
    'CaptureCenterFrequencyHz', opts.CaptureCenterFrequencyHz, ...
    'CaptureTuneFrequencyHz', localResolvedTune(opts.CaptureTuneFrequencyHz, frequency_context), ...
    'LOOffsetHz', frequency_context.capture_lo_offset_hz, ...
    'IlluminatorCenterFrequencyHz', frequency_context.illuminator_center_frequency_hz, ...
    'SpectralPowerDB', spectral_power_db, ...
    'SearchHalfWidthHz', opts.PilotSearchHalfWidthHz);

pilot_coherence_snr_db = pilot_selection.selected_snr_db;
pilot_freq_hz = pilot_selection.selected_freq_hz;

% PSD trace for the same slice. Welch averaging gives a readable spectrum
% without requiring the entire file to be loaded into one FFT.
n_channel = numel(reference_channel);
nfft_psd = 2^nextpow2(max(256, min(n_channel, 8192)));
win_len = min(nfft_psd, max(64, min(n_channel, 4096)));
if n_channel < win_len
    win_len = n_channel;
end
overlap = floor(0.5 * win_len);
[psd_linear, psd_freq_axis_hz] = pwelch( ...
    reference_channel, ...
    hamming(win_len), ...
    overlap, ...
    nfft_psd, ...
    fs, ...
    'centered');

profile = struct( ...
    'psd_freq_axis_hz',          psd_freq_axis_hz(:), ...
    'psd_db_hz',                 10 * log10(psd_linear(:) + realmin), ...
    'coherence_freq_axis_hz',    coherence_freq_axis_hz(:), ...
    'coherence_snr_db',          coherence_snr_db(:), ...
    'spectral_power_db',         spectral_power_db(:), ...
    'pilot_freq_hz',             pilot_freq_hz, ...
    'pilot_coherence_snr_db',    pilot_coherence_snr_db, ...
    'pilot_selection',           pilot_selection, ...
    'frequency_context',         frequency_context, ...
    'strongest_coherent_freq_hz', pilot_selection.global_peak_freq_hz, ...
    'strongest_coherent_snr_db', pilot_selection.global_peak_snr_db, ...
    'n_fast',                    n_fast, ...
    'n_slow',                    n_slow);
end

function capture_tune_hz = localResolvedTune(requested_capture_tune_hz, frequency_context)
capture_tune_hz = requested_capture_tune_hz;
if isempty(capture_tune_hz) || ~isfinite(capture_tune_hz)
    capture_tune_hz = frequency_context.capture_tune_frequency_hz;
end
end
