function profile = helperMeasurePilotCoherenceProfile(reference_cube, reference_channel, fs, varargin)
%HELPERMEASUREPILOTCOHERENCEPROFILE Backward-compatible wrapper for pilot evidence.
%
% Plain-language goal:
% Older callers asked for a "pilot coherence profile", but the current
% audit is PSD-first. This wrapper keeps the legacy entrypoint working
% while routing everything through helperMeasureATSCPilotEvidence so there
% is only one pilot-audit truth source in the project.

evidence = helperMeasureATSCPilotEvidence(reference_cube, reference_channel, fs, varargin{:});

profile = struct( ...
    'psd_freq_axis_hz', evidence.psd_freq_axis_hz, ...
    'psd_db_hz', evidence.psd_db_hz, ...
    'coherence_freq_axis_hz', evidence.legacy_coherence_freq_axis_hz, ...
    'coherence_snr_db', evidence.legacy_coherence_trace_db, ...
    'spectral_power_db', evidence.legacy_power_db, ...
    'pilot_freq_hz', evidence.selected_pilot_freq_hz, ...
    'pilot_coherence_snr_db', evidence.legacy_coherence_snr_db, ...
    'pilot_selection', evidence, ...
    'pilot_comparison', evidence.pilot_comparison, ...
    'pilot_candidate_table', evidence.diagnostic_table, ...
    'expected_normal_frequency_hz', evidence.expected_normal_freq_hz, ...
    'expected_mirrored_frequency_hz', evidence.expected_mirrored_freq_hz, ...
    'frequency_context', evidence.frequency_context, ...
    'strongest_coherent_freq_hz', evidence.legacy_global_peak_freq_hz, ...
    'strongest_coherent_snr_db', evidence.legacy_global_peak_snr_db, ...
    'selected_peak_prominence_db', evidence.selected_peak_prominence_db, ...
    'pilot_freq_error_hz', evidence.pilot_freq_error_hz, ...
    'residual_offset_mean_hz', evidence.residual_offset_mean_hz, ...
    'residual_offset_std_hz', evidence.residual_offset_std_hz, ...
    'corrected_concentration_db', evidence.corrected_concentration_db, ...
    'residual_offset_time_s', evidence.residual_offset_time_s, ...
    'residual_offset_hz', evidence.residual_offset_hz, ...
    'stability_message', evidence.stability_message);
end
