function config = helperADSBRemoter599MHzConfig(varargin)
%HELPERADSBREMOTER599MHZCONFIG Fixed geometry and explicit BiSNR assumptions.
%
%   config = helperADSBRemoter599MHzConfig()
%   config = helperADSBRemoter599MHzConfig(Name, Value)
%
%   This configuration describes the 599 MHz WHDH/WLVI illuminator and the
%   Apple Hill receiver used for manual opportunity planning. The RF values
%   mirror the defaults in ADSB-remoter commit 63ff668. They are assumptions
%   for ranking opportunities, not calibrated receiver-performance claims.

p = inputParser;
p.FunctionName = mfilename;
addParameter(p, 'ReceiverGain_dBi', 10.0, @localPositiveOrZeroScalar);
addParameter(p, 'NoiseFigure_dB', 3.0, @localPositiveOrZeroScalar);
addParameter(p, 'ReceiverBandwidth_Hz', 8e6, @localPositiveScalar);
addParameter(p, 'BistaticRCS_dBsm', 10.0, @localFiniteScalar);
addParameter(p, 'PolarizationLoss_dB', 1.0, @localPositiveOrZeroScalar);
addParameter(p, 'SystemLoss_dB', 2.0, @localPositiveOrZeroScalar);
addParameter(p, 'NoiseTemperature_K', 290.0, @localPositiveScalar);
addParameter(p, 'AssumptionID', ...
    "adsb-remoter-63ff668-599MHz-defaults-v1", @localTextScalar);
parse(p, varargin{:});
opts = p.Results;

config = struct( ...
    'TxLLA', [42.311389, -71.216111, 348.386404], ...
    'RxLLA', [42.2999333, -71.349333, 15.0], ...
    'CenterFrequency_Hz', 599e6, ...
    'EmitterEIRP_kW', 1640.5897731995394, ...
    'EmitterID', "ASRN:1005862", ...
    'EmitterCallsign', "WHDH/WLVI", ...
    'ReceiverGain_dBi', double(opts.ReceiverGain_dBi), ...
    'NoiseFigure_dB', double(opts.NoiseFigure_dB), ...
    'ReceiverBandwidth_Hz', double(opts.ReceiverBandwidth_Hz), ...
    'BistaticRCS_dBsm', double(opts.BistaticRCS_dBsm), ...
    'PolarizationLoss_dB', double(opts.PolarizationLoss_dB), ...
    'SystemLoss_dB', double(opts.SystemLoss_dB), ...
    'NoiseTemperature_K', double(opts.NoiseTemperature_K), ...
    'CPAMethod', "minimum_observed_3d_receiver_slant_range", ...
    'SourceID', ...
        "ADSB-remoter@63ff6688628c2813e4287c5ecdc0df67883c3f93", ...
    'AssumptionID', string(opts.AssumptionID));

end

function tf = localPositiveScalar(value)
tf = isnumeric(value) && isscalar(value) && isreal(value) && ...
    isfinite(value) && value > 0;
end

function tf = localPositiveOrZeroScalar(value)
tf = isnumeric(value) && isscalar(value) && isreal(value) && ...
    isfinite(value) && value >= 0;
end

function tf = localFiniteScalar(value)
tf = isnumeric(value) && isscalar(value) && isreal(value) && isfinite(value);
end

function tf = localTextScalar(value)
tf = (ischar(value) && isrow(value)) || ...
    (isstring(value) && isscalar(value) && ~ismissing(value));
end
