function validation = runATSCPilotAuditValidation(session_id, varargin)
%RUNATSCPILOTAUDITVALIDATION Multi-part engineering check for pilot selection.
%
% Plain-language goal:
% A single good-looking precheck plot is not enough to trust a capture
% session. This helper samples multiple parts from the same session and
% checks whether the selected ATSC pilot, orientation decision, and
% continuation recommendation stay coherent across time.

if nargin < 1 || strlength(string(session_id)) == 0
    session_id = "20260622T102123";
end

p = inputParser;
p.FunctionName = mfilename;
addRequired(p, 'session_id', @(x) ischar(x) || isstring(x));
addParameter(p, 'DatasetRoot', helperResolvePackagedCaptureRoot(), @(x) ischar(x) || isstring(x));
addParameter(p, 'PartIndices', [1 5 10 15], @(x) isnumeric(x) && isvector(x) && all(x >= 1));
addParameter(p, 'PlotFigures', false, @(x) islogical(x) && isscalar(x));
addParameter(p, 'FigureVisibility', 'off', @(x) any(strcmpi(string(x), ["on", "off"])));
addParameter(p, 'Verbose', true, @(x) islogical(x) && isscalar(x));
parse(p, session_id, varargin{:});
opts = p.Results;

part_indices = unique(double(opts.PartIndices(:).'));
per_part_results = cell(1, numel(part_indices));

for idxPart = 1 : numel(part_indices)
    part_index = part_indices(idxPart);
    try
        per_part_results{idxPart} = runDirectPathPrecheck( ...
            opts.session_id, ...
            'DatasetRoot', opts.DatasetRoot, ...
            'PartIndex', part_index, ...
            'PlotFigures', opts.PlotFigures, ...
            'FigureVisibility', opts.FigureVisibility, ...
            'Verbose', false);
    catch ME
        error('runATSCPilotAuditValidation:precheckFailed', ...
            'Precheck failed for session %s part %d: %s', opts.session_id, part_index, ME.message);
    end
end

selected_freq_hz = NaN(numel(part_indices), 1);
expected_freq_hz = NaN(numel(part_indices), 1);
pilot_prominence_db = NaN(numel(part_indices), 1);
pilot_freq_error_hz = NaN(numel(part_indices), 1);
legacy_fft_bin_coherence_db = NaN(numel(part_indices), 1);
residual_offset_std_hz = NaN(numel(part_indices), 1);
corrected_concentration_db = NaN(numel(part_indices), 1);
pilot_presence_pass = false(numel(part_indices), 1);
overall_pass = false(numel(part_indices), 1);
selection_mode = strings(numel(part_indices), 1);
continuation_recommendation = strings(numel(part_indices), 1);

for idxPart = 1 : numel(part_indices)
    result = per_part_results{idxPart};
    selected_freq_hz(idxPart) = result.reference_profile.selected_pilot_freq_hz;
    expected_freq_hz(idxPart) = result.reference_profile.expected_normal_freq_hz;
    pilot_prominence_db(idxPart) = result.reference_quality.pilot_prominence_db;
    pilot_freq_error_hz(idxPart) = result.reference_quality.pilot_freq_error_hz;
    legacy_fft_bin_coherence_db(idxPart) = result.reference_quality.legacy_fft_bin_coherence_db;
    residual_offset_std_hz(idxPart) = result.reference_quality.residual_offset_std_hz;
    corrected_concentration_db(idxPart) = result.reference_quality.corrected_concentration_db;
    pilot_presence_pass(idxPart) = result.reference_quality.pilot_pass;
    overall_pass(idxPart) = result.overall_pass;
    selection_mode(idxPart) = string(result.precheck_summary.selection_mode);
    continuation_recommendation(idxPart) = string(result.precheck_summary.continuation_recommendation);
end

part_table = table( ...
    part_indices(:), ...
    selected_freq_hz, ...
    expected_freq_hz, ...
    selected_freq_hz - expected_freq_hz, ...
    pilot_prominence_db, ...
    pilot_freq_error_hz, ...
    legacy_fft_bin_coherence_db, ...
    residual_offset_std_hz, ...
    corrected_concentration_db, ...
    pilot_presence_pass, ...
    selection_mode, ...
    overall_pass, ...
    continuation_recommendation, ...
    'VariableNames', { ...
        'part_index', ...
        'selected_freq_hz', ...
        'expected_freq_hz', ...
        'selected_minus_expected_hz', ...
        'pilot_prominence_db', ...
        'pilot_freq_error_hz', ...
        'legacy_fft_bin_coherence_db', ...
        'residual_offset_std_hz', ...
        'corrected_concentration_db', ...
        'pilot_presence_pass', ...
        'selection_mode', ...
        'overall_pass', ...
        'continuation_recommendation'});

summary = struct( ...
    'session_id', string(opts.session_id), ...
    'part_indices', part_indices(:), ...
    'selected_freq_span_hz', max(selected_freq_hz) - min(selected_freq_hz), ...
    'pilot_prominence_span_db', max(pilot_prominence_db) - min(pilot_prominence_db), ...
    'pilot_presence_pass_fraction', mean(pilot_presence_pass), ...
    'median_residual_offset_std_hz', median(residual_offset_std_hz, 'omitnan'), ...
    'n_pass', nnz(overall_pass), ...
    'n_parts', numel(part_indices), ...
    'continuation_pass_fraction', mean(overall_pass), ...
    'instability_note', localBuildInstabilityNote(selected_freq_hz, residual_offset_std_hz));

validation = struct( ...
    'session_id', string(opts.session_id), ...
    'part_table', part_table, ...
    'summary', summary, ...
    'per_part_results', {per_part_results});

if opts.Verbose
    fprintf('\n[runATSCPilotAuditValidation] Session ......... %s\n', char(validation.session_id));
    fprintf('[runATSCPilotAuditValidation] Parts ........... %s\n', mat2str(part_indices));
    fprintf('[runATSCPilotAuditValidation] Selected span ... %.1f kHz\n', summary.selected_freq_span_hz / 1e3);
    fprintf('[runATSCPilotAuditValidation] Prominence span . %.1f dB\n', summary.pilot_prominence_span_db);
    fprintf('[runATSCPilotAuditValidation] Overall pass .... %d / %d parts\n', summary.n_pass, summary.n_parts);
    fprintf('[runATSCPilotAuditValidation] Stability note . %s\n', char(summary.instability_note));
    disp(part_table);
end
end

function note = localBuildInstabilityNote(selected_freq_hz, residual_offset_std_hz)
selected_freq_hz = selected_freq_hz(:);
selected_freq_span_hz = max(selected_freq_hz) - min(selected_freq_hz);
median_residual_std_hz = median(residual_offset_std_hz, 'omitnan');

if selected_freq_span_hz <= 150e3 && (~isfinite(median_residual_std_hz) || median_residual_std_hz <= 20)
    note = "Selection stays broadly coherent across the sampled parts.";
elseif isfinite(median_residual_std_hz) && median_residual_std_hz > 20
    note = "Selected pilot stays in band, but the advisory residual-frequency spread is broad across the sampled parts.";
else
    note = "Selected pilot frequency moves materially across sampled parts; inspect the candidate tables before trusting downstream analysis.";
end
end
