classdef runDetectorReplaySweepTest < matlab.unittest.TestCase
    %RUNDETECTORREPLAYSWEEPTEST Regression coverage for replay parsing.

    methods (Test)
        function testLowerCamelCaseAliasIsAccepted(testCase)
            warning_state = warning('off', 'runDetectorReplaySweep:caseFieldAlias');
            testCase.addTeardown(@() warning(warning_state));

            replay_input = localBuildMinimalReplayInput();
            cases = struct( ...
                'Name', {'baseline', 'alias_case'}, ...
                'minSNRDB', {0, 10});

            replay_output = runDetectorReplaySweep( ...
                replay_input, ...
                'Cases', cases, ...
                'Verbose', false);

            testCase.verifyEqual(height(replay_output.summary_table), 2);
            testCase.verifyEqual(replay_output.summary_table.min_snr_db(2), 10);
            testCase.verifyEqual(replay_output.case_results(2).parameters.min_snr_db, 10);
        end

        function testLowerCamelCaseAliasWarns(testCase)
            replay_input = localBuildMinimalReplayInput();
            cases = struct('Name', {'alias_case'}, 'minSNRDB', {10});

            testCase.verifyWarning( ...
                @() runDetectorReplaySweep(replay_input, 'Cases', cases, 'Verbose', false), ...
                'runDetectorReplaySweep:caseFieldAlias');
        end

        function testUnknownTopLevelOptionThrowsHelpfulError(testCase)
            replay_input = localBuildMinimalReplayInput();

            testCase.verifyError( ...
                @() runDetectorReplaySweep(replay_input, 'PloatDetectionoTimeSeries', true), ...
                'runDetectorReplaySweep:unknownOption');
        end
    end
end

function replay_input = localBuildMinimalReplayInput()
cfar_defaults = struct( ...
    'cfar_type', 'OS', ...
    'os_rank_fraction', 0.75, ...
    'local_maxima', true, ...
    'lm_range_bins', 1, ...
    'lm_dopp_bins', 1, ...
    'min_snr_db', 0, ...
    'atsc_guard_penalty_db', 0, ...
    'atsc_guard_width_bins', 0, ...
    'notch_guard_dopp_bins', 0);

replay_input = struct( ...
    'session_id', "unit_test_session", ...
    'analysis_label', "Unit Test Replay", ...
    'verbose', false, ...
    'detector_defaults', struct( ...
        'pfa', 1e-4, ...
        'guard_cells', [1, 1], ...
        'train_cells', [2, 2], ...
        'min_range_m', 0, ...
        'cfar_options', cfar_defaults), ...
    'detector_parts', struct([]));
end
