%% test_truthMeasurementOffset.m
% Synthetic coverage for the measurement-offset diagnostic.

clear; clc;

t_vec = (0 : 4).';

adsb_aligned(1) = struct( ...
    'hex', 'A1B2C3', ...
    'callsign', 'UAL123', ...
    't_abs_s', t_vec, ...
    'R_excess_m', 6000 + 40 * t_vec, ...
    'f_D_hz', 120 - 5 * t_vec);

adsb_aligned(2) = struct( ...
    'hex', 'D4E5F6', ...
    'callsign', 'DAL456', ...
    't_abs_s', t_vec, ...
    'R_excess_m', 13500 - 55 * t_vec, ...
    'f_D_hz', -180 + 7 * t_vec);

true_range_offset_m = 18500;
true_doppler_offset_hz = -220;

det_t = [t_vec; t_vec];
det_R = [adsb_aligned(1).R_excess_m + true_range_offset_m + [20; -10; 30; -15; 5]; ...
         adsb_aligned(2).R_excess_m + true_range_offset_m + [-25; 15; -20; 10; 0]];
det_f = [adsb_aligned(1).f_D_hz + true_doppler_offset_hz + [3; -2; 1; 0; -1]; ...
         adsb_aligned(2).f_D_hz + true_doppler_offset_hz + [-4; 2; -3; 1; 0]];

diag_output = struct( ...
    'analysis_label', 'Synthetic offset case', ...
    'adsb_aligned', adsb_aligned, ...
    'truth_metrics', struct( ...
        'det_table', table(det_t, det_R, det_f, ...
            'VariableNames', {'t_abs_s', 'R_excess_m', 'f_D_hz'}), ...
        'gate_range_m', 400, ...
        'gate_doppler_hz', 20, ...
        'time_gate_s', 0.25), ...
    'truth_diag_input', struct( ...
        'range_cell_m', 100, ...
        'doppler_bin_hz', 10));

offset_diag = estimateTruthMeasurementOffset(diag_output, ...
    'RangeBinWidthM', 250, ...
    'DopplerBinWidthHz', 10, ...
    'MaxRangeOffsetM', 25e3, ...
    'MaxDopplerOffsetHz', 400, ...
    'Plot', false, ...
    'Verbose', false);

assert(abs(offset_diag.summary.estimated_range_offset_m - true_range_offset_m) < 150);
assert(abs(offset_diag.summary.estimated_doppler_offset_hz - true_doppler_offset_hz) < 10);
assert(offset_diag.zero_offset_metrics.n_tp == 0);
assert(offset_diag.compensated_metrics.n_tp == numel(det_t));
assert(offset_diag.compensated_metrics.n_fa == 0);

fprintf('test_truthMeasurementOffset passed.\n');
