%% test_truthFixTimingComparison.m
% Synthetic coverage for the timing A/B comparison helpers.

clear; clc;

metadata_output = struct( ...
    'part_start_offsets_s', [0; 7.75; 12.026], ...
    'part_duration_s', 1.0, ...
    'part_timing_info', struct( ...
        'requested_source', 'metadata', ...
        'source', 'file_metadata', ...
        'used_metadata', [true; true; true]), ...
    'truth_diag_summary', struct('n_detections', 95), ...
    'truth_metrics', struct( ...
        'n_tp', 3, ...
        'n_fa', 92, ...
        'n_miss', 40, ...
        'trk_table', table( ...
            [11; 12], {'A1'; 'B2'}, {'AC1'; 'AC2'}, [10; 20], [100; 120], ...
            [2; 4], [10; 12], [5; 5], ...
            'VariableNames', {'track_id', 'assoc_hex', 'assoc_callsign', ...
                              'range_bias_m', 'range_rmse_m', ...
                              'doppler_bias_hz', 'doppler_rmse_hz', 'n_pts'})));

fallback_output = struct( ...
    'part_start_offsets_s', [0; 3; 6], ...
    'part_duration_s', 1.0, ...
    'part_timing_info', struct( ...
        'requested_source', 'fallback', ...
        'source', 'forced_fallback_gap', ...
        'used_metadata', [false; false; false]), ...
    'truth_diag_summary', struct('n_detections', 90), ...
    'truth_metrics', struct( ...
        'n_tp', 0, ...
        'n_fa', 90, ...
        'n_miss', 410, ...
        'trk_table', table( ...
            21, {'C3'}, {'AC3'}, 15, 180, 8, 18, 4, ...
            'VariableNames', {'track_id', 'assoc_hex', 'assoc_callsign', ...
                              'range_bias_m', 'range_rmse_m', ...
                              'doppler_bias_hz', 'doppler_rmse_hz', 'n_pts'})));

ref_log_path = [tempname, '.txt'];
ref_lines = { ...
    '[helperGetPartStartOffsets] Timing source: file_metadata', ...
    '  Part 1 start offset: 0.000 s (part1)', ...
    '  Part 2 start offset: 7.750 s (header)', ...
    '  Part 3 start offset: 12.026 s (header)', ...
    '[assessTruthVsDetections] Gate: |dR| < 146 m,  |df| < 30.2 Hz', ...
    '[assessTruthVsDetections] Time gate: |dt| < 0.200 s', ...
    '  Total detections: 83  |  TP: 0  |  FA: 83  |  Missed: 410'};
fid = fopen(ref_log_path, 'w');
assert(fid > 0, 'Could not create temporary reference log.');
cleanup = onCleanup(@() delete(ref_log_path));
fprintf(fid, '%s\n', ref_lines{:});
fclose(fid);

comparison = compareBistaticTimingModes(metadata_output, fallback_output, ...
    'ReferenceLogPath', ref_log_path, ...
    'Verbose', false);

assert(height(comparison.summary_table) == 2);
assert(strcmp(comparison.summary_table.mode(1), "metadata"));
assert(strcmp(comparison.summary_table.mode(2), "fallback"));
assert(comparison.summary_table.n_tp(1) == 3);
assert(comparison.summary_table.n_tp(2) == 0);
assert(abs(comparison.summary_table.median_gap_s(1) - 5.013) < 1e-3);
assert(abs(comparison.summary_table.median_gap_s(2) - 2.0) < 1e-12);

assert(comparison.delta_table.n_tp_delta == 3);
assert(comparison.delta_table.n_fa_delta == 2);
assert(strcmp(comparison.assessment.preferred_mode, "metadata"));
assert(comparison.assessment.timing_sensitive);
assert(comparison.assessment.metadata_improved_vs_reference);
assert(~comparison.assessment.fallback_improved_vs_reference);

assert(comparison.reference_summary.available);
assert(strcmp(comparison.reference_summary.timing_source, "file_metadata"));
assert(comparison.reference_summary.n_tp == 0);
assert(comparison.reference_summary.n_fa == 83);
assert(comparison.reference_summary.n_miss == 410);
assert(abs(comparison.reference_summary.gate_range_m - 146) < 1e-12);
assert(abs(comparison.reference_summary.gate_doppler_hz - 30.2) < 1e-12);
assert(abs(comparison.reference_summary.time_gate_s - 0.2) < 1e-12);

fprintf('test_truthFixTimingComparison passed.\n');
