function result = buildTechnicalSummaryFamily(reportRoot)
% buildTechnicalSummaryFamily Audit and package the technical-summary family.
%
% This builder never edits the nine source reports or their source assets. It
% writes audit outputs and release copies to TechnicalSummaryFamily_Releases,
% then promotes a validated immutable release to TechnicalSummaryFamily.

arguments
    reportRoot (1,1) string = string(fileparts(mfilename("fullpath")))
end

reportRoot = string(char(reportRoot));
flightTestRoot = string(fileparts(reportRoot));
agenticRoot = "C:\Users\pwilliam\agenticProjects";
releaseRoot = fullfile(reportRoot,"TechnicalSummaryFamily");
releaseHistoryRoot = fullfile(reportRoot,"TechnicalSummaryFamily_Releases");
releaseId = string(datetime("now","Format","yyyyMMdd_HHmmss"));
stageRoot = fullfile(releaseHistoryRoot,releaseId + "_staging");
immutableRoot = fullfile(releaseHistoryRoot,releaseId);

reports = localReportDefinitions(flightTestRoot,agenticRoot);
result = struct( ...
    "ReleaseId",releaseId, ...
    "StageRoot",stageRoot, ...
    "ReleaseRoot",releaseRoot, ...
    "Status","FAILED", ...
    "Message","Build did not start.");

localEnsureFolder(releaseHistoryRoot);
priorReleaseId = localPriorReleaseId(releaseHistoryRoot);
if isfolder(stageRoot)
    error("TechnicalSummaryFamily:StageExists", ...
        "Staging folder already exists: %s",stageRoot);
end

mkdir(stageRoot);
cleanupStage = onCleanup(@()localWriteFailureMarker(stageRoot,result)); %#ok<NASGU>

try
    localValidateSourceInputs(reportRoot,reports);
    sourceHashes = localSourceHashTable(reportRoot,reports);
    sourceIntegrity = localSourceIntegrityBaseline(reportRoot,reports);

    folders = localReleaseFolders(stageRoot);
    localCreateReleaseFolders(folders);

    audit = localBuildPhaseZeroAudit( ...
        folders.Metadata,reportRoot,flightTestRoot,agenticRoot,reports,sourceHashes);

    if any(audit.Priority == "P0" & ...
            audit.RecommendedDisposition == "Blocked from Canonical Release")
        error("TechnicalSummaryFamily:BlockedByAudit", ...
            "The Phase 0 audit contains unresolved P0 blockers.");
    end

    copyInfo = localCreateReleaseCopies( ...
        folders,reportRoot,flightTestRoot,reports,sourceHashes,audit);
    localWriteCanonicalMetadata(folders,reportRoot,releaseRoot,releaseId, ...
        immutableRoot,priorReleaseId,reports,sourceHashes,sourceIntegrity,audit,copyInfo);
    localWriteReleaseReadme(folders.Root,releaseId);

    verification = verifyTechnicalSummaryFamily(folders.Root);
    if ~verification.Passed
        error("TechnicalSummaryFamily:ValidationFailed", ...
            "Release validation failed. See %s", ...
            fullfile(folders.Validation,"release_validation.md"));
    end

    localAssertSourceIntegrity(sourceIntegrity);
    movefile(stageRoot,immutableRoot,"f");
    result.StageRoot = immutableRoot;

    localRecordPromotion(immutableRoot,stageRoot,releaseRoot,priorReleaseId);
    localPromoteImmutableRelease(immutableRoot,releaseRoot,releaseHistoryRoot);
    localAssertSourceIntegrity(sourceIntegrity);

    result.Status = verification.Status;
    result.Message = "Phase 0 audit, release-local stabilization, and promotion completed.";
    result.CurrentRelease = releaseRoot;
    result.ImmutableRelease = immutableRoot;
    result.Validation = verification;
catch exception
    result.Status = "FAILED";
    result.Message = string(getReport(exception,"extended","hyperlinks","off"));
    localWriteBuildFailure(stageRoot,result,exception);
    rethrow(exception);
end
end

function reports = localReportDefinitions(flightTestRoot,agenticRoot)
reports = struct( ...
    "Id",{"01","01A","01B","02","02A","03","04","05","06"}, ...
    "Filename",{ ...
        "01_NorthStarAndMotivation_V2.html", ...
        "01A_IlluminatorSelection_V4.html", ...
        "01B_ReceiveChainDesign_V2.html", ...
        "02_HardwareAndCollection_V5.html", ...
        "02A_SyntheticEchoGeneration_V1.html", ...
        "03_AnalysisPipelineAndGateRebuild.html", ...
        "04_MitigationAndMapRateRecovery_V2.html", ...
        "05_StrongestEvidence_G4RRecoveryStudy.html", ...
        "06_StatusAndFutureWork_V3.html"}, ...
    "Question",{ ...
        "Why is the project worth pursuing?", ...
        "How were the illuminator, channel, receiver site, and observation geometry investigated?", ...
        "How did predicted signal conditions drive the receive-chain design?", ...
        "What physical hardware and collection infrastructure were built?", ...
        "How are known aircraft-like echoes created inside real recordings, and why is synthetic truth useful?", ...
        "How does the analysis pipeline operate, and what does each gate protect?", ...
        "Why did map-rate and mitigation recovery become necessary, and what was learned?", ...
        "What is the strongest current experimental evidence?", ...
        "Where does the project stand, and what should happen next?"}, ...
    "Ownership",{ ...
        "Project motivation, North Star, and long-term measurement/tracking/localization vision.", ...
        "Candidate-tower provenance, geometry screening, prototype history, and RF-design inputs.", ...
        "RF budget, designed architecture, component reasoning, and qualification questions.", ...
        "Installed hardware, coordinated collection, provenance, replay, and qualification gaps.", ...
        "Declared truth, echo synthesis, real-background injection, paired controls, and boundaries.", ...
        "G1 through G10 contracts, truth separation, and downstream-release requirements.", ...
        "Map-rate defect, mitigation investigation, R1 through R5A, and recovery history.", ...
        "Close-target atlas, support interpretation, paired controls, and bounded conclusions.", ...
        "Status, independent blockers, next evidence requirements, and management actions."}, ...
    "Pattern",{ ...
        "Older-pattern reference report", ...
        "New-pattern aligned", ...
        "New-pattern aligned", ...
        "Older-pattern reference report", ...
        "New-pattern aligned", ...
        "Partially aligned", ...
        "Partially aligned", ...
        "Partially aligned", ...
        "Partially aligned"}, ...
    "StrongestResult",{ ...
        "A disciplined measurement-first North Star prevents unsupported tracking and localization claims.", ...
        "Historical Hudson/Newton target-region comparison: 69.91 dB versus 57.78 dB modeled FOV SNR.", ...
        "Historical RF evidence identifies cable, impedance, filtering, low-noise gain, and N320 headroom as one design problem.", ...
        "Fifteen-part packages at 599 MHz and 6.144 MS/s establish collection/replay infrastructure, not qualification.", ...
        "The 15 km anchor is -76.456 microseconds and +540.5 Hz; declared truth supports bounded paired replay.", ...
        "G1 through G10 prevent diagnostics from becoming formal measurements without evidence gates.", ...
        "The formal R5A matrix failed overall: 59 of 108 rows violated at least one frozen criterion.", ...
        "Native-first frozen NLMS associated 8/8 injected targets; no mitigation associated 0/8 under the fixed diagnostic setup.", ...
        "Map-contract verification and collection/reference qualification remain independent blockers; the ADS-B cue interface is verified as infrastructure only."}, ...
    "Metric",{ ...
        "No operational performance metric; claim boundary is the governing result.", ...
        "69.91 dB Hudson versus 57.78 dB Newton modeled FOV SNR.", ...
        "Vendor S21 is -0.7335926 dB at 599 MHz; historical cascade uses 20 dB LANA context.", ...
        "15 packages; 599 MHz; 6.144 MS/s.", ...
        "-76.456 microseconds; +540.5 Hz; 8/8 diagnostic recovery is owned by Report 05.", ...
        "G1-G10 gate chain; formal downstream gates remain disabled.", ...
        "59/108 R5A rows violated one or more frozen criteria.", ...
        "8/8 native-first frozen-NLMS versus 0/8 no-mitigation target associations.", ...
        "Two independent blockers; four bounded management actions."}, ...
    "Decision",{ ...
        "Pursue a measurement-evidence program before downstream performance claims.", ...
        "Carry historical illumination cases into RF design without claiming current configuration selection.", ...
        "Treat RF architecture as a designed model requiring installed qualification.", ...
        "Use collection packages as reproducible infrastructure while retaining qualification gaps.", ...
        "Use declared truth post hoc only; do not steer detector generation with it.", ...
        "Hold downstream detection, tracking, and localization until prerequisite evidence passes.", ...
        "Retain failed R5A and review only bounded upstream correction behavior.", ...
        "Treat recovery as controlled synthetic diagnostic evidence, not operational performance.", ...
        "Authorize bounded evidence actions before any replacement R5A decision."}, ...
    "Unknown",{ ...
        "No validated aircraft measurement, tracking, or localization performance.", ...
        "Current transmitter configuration, field direct path, and qualified reference path.", ...
        "Installed end-to-end RF response, lock, transport integrity, and reference adequacy.", ...
        "Channel-role proof, lock/drop evidence, collection suitability, GPS/PPS lock of the ADS-B time source (internet NTP accepted with a 0.1 s tolerance), and the Pi clock offset of ADS-B truth before 2026-09-25 21:07 UTC.", ...
        "Calibrated RCS, live-aircraft performance, and operational false-alarm behavior.", ...
        "Passing map, detector, measurement, and tracker contracts.", ...
        "Whether reviewed correction passes controlled R4 verification and a separately authorized replacement matrix.", ...
        "Operational Pd/Pfa, live-aircraft detection, product selection, tracking, and localization.", ...
        "Passing map-contract correction, reviewed collection/reference-path qualification, an accepted truth-separation rule for cued collections, and a first collection scheduled from an ADS-B cue."}, ...
    "Predecessor",{"","01","01A","01B","02","02A","03","04","05"}, ...
    "Successor",{"01A","01B","02","02A","03","04","05","06",""}, ...
    "ClaimBoundary",{ ...
        "Motivation is not a field-performance claim.", ...
        "Historical models do not establish installed transmitter or reference-path adequacy.", ...
        "Modeled RF choices do not establish installed performance or qualification.", ...
        "Infrastructure is not radar performance or collection qualification.", ...
        "Synthetic truth is not a live-aircraft result or operational performance.", ...
        "Pipeline implementation does not satisfy disabled downstream gates.", ...
        "R4 bounded success does not erase formal R5A failure.", ...
        "Controlled synthetic association is not live-aircraft detection or operational Pd/Pfa.", ...
        "Status recommendations do not authorize unreviewed follow-on work."}, ...
    "CodePath",{ ...
        fullfile(flightTestRoot,"LinkBudget","FlightTest_Bistatic_RadarAndCommsAnalysis.mlx"), ...
        fullfile(flightTestRoot,"LinkBudget","FlightTest_Bistatic_RadarAndCommsAnalysis.mlx"), ...
        fullfile(flightTestRoot,"RFBudget","RFBudget_Newton.m"), ...
        fullfile(flightTestRoot,"TestSetupTesting","runCoordinatedHDTVCapture.m"), ...
        fullfile(agenticRoot,"flightTest_SynthDataBranch","SyntheticHDTVSimulation","generateRealBackgroundSyntheticSuite.m"), ...
        fullfile(agenticRoot,"PassiveBistaticRestart","runG4PassiveBaselineMap.m"), ...
        fullfile(agenticRoot,"PassiveBistaticRestart","runG4RMapRateMatrix.m"), ...
        fullfile(agenticRoot,"PassiveBistaticRestart","runG4RCloseTargetAtlasRecoveryStudy.m"), ...
        fullfile(agenticRoot,"PassiveBistaticRestart","G4RMapRateValidityPlan.md")});
end

function localValidateSourceInputs(reportRoot,reports)
for index = 1:numel(reports)
    sourcePath = fullfile(reportRoot,reports(index).Filename);
    if ~isfile(sourcePath)
        error("TechnicalSummaryFamily:MissingReport", ...
            "Accepted canonical report is unavailable: %s",sourcePath);
    end
end
end

function folders = localReleaseFolders(root)
folders = struct( ...
    "Root",string(root), ...
    "Reports",fullfile(root,"reports"), ...
    "Assets",fullfile(root,"assets"), ...
    "Companions",fullfile(root,"companions"), ...
    "Metadata",fullfile(root,"metadata"), ...
    "Validation",fullfile(root,"validation"));
end

function localCreateReleaseFolders(folders)
fieldNames = string(fieldnames(folders));
for index = 1:numel(fieldNames)
    localEnsureFolder(folders.(fieldNames(index)));
end
end

function localEnsureFolder(folder)
if ~isfolder(folder)
    mkdir(folder);
end
end

function hashTable = localSourceHashTable(reportRoot,reports)
count = numel(reports);
ids = strings(count,1);
filenames = strings(count,1);
paths = strings(count,1);
hashes = strings(count,1);
for index = 1:count
    path = fullfile(reportRoot,reports(index).Filename);
    ids(index) = reports(index).Id;
    filenames(index) = reports(index).Filename;
    paths(index) = path;
    hashes(index) = string(localSha256(path));
end
hashTable = table(ids,filenames,paths,hashes, ...
    'VariableNames',{'ReportID','Filename','SourcePath','SourceSHA256'});
end

function integrity = localSourceIntegrityBaseline(reportRoot,reports)
% Record every report-local source image plus all source PowerPoint files.
% The release may read these files but never modifies them.
assetPaths = strings(0,1);
for index = 1:numel(reports)
    content = string(fileread(fullfile(reportRoot,reports(index).Filename)));
    sources = localExtractLinks(content,"src");
    for sourceIndex = 1:numel(sources)
        sourceLink = sources(sourceIndex);
        if localIsExternalOrFragment(sourceLink)
            continue;
        end
        sourcePath = fullfile(reportRoot, ...
            string(urldecode(char(localStripFragment(sourceLink)))));
        if isfile(sourcePath)
            assetPaths(end+1,1) = string(sourcePath); %#ok<AGROW>
        end
    end
end
assetPaths = unique(assetPaths,"stable");

powerPointListing = dir(fullfile(reportRoot,"**","*.pptx"));
powerPointPaths = strings(numel(powerPointListing),1);
for index = 1:numel(powerPointListing)
    powerPointPaths(index) = fullfile(powerPointListing(index).folder, ...
        powerPointListing(index).name);
end

paths = [assetPaths;powerPointPaths];
kind = [repmat("Asset",numel(assetPaths),1); ...
    repmat("PowerPoint",numel(powerPointPaths),1)];
relativePath = strings(numel(paths),1);
hashes = strings(numel(paths),1);
for index = 1:numel(paths)
    relativePath(index) = extractAfter(paths(index),reportRoot + filesep);
    hashes(index) = string(localSha256(paths(index)));
end
integrity = table(kind,relativePath,paths,hashes, ...
    'VariableNames',{'Kind','RelativePath','SourcePath','SourceSHA256'});
end

function audit = localBuildPhaseZeroAudit(metadataRoot,reportRoot,flightTestRoot,agenticRoot,reports,sourceHashes)
gapMatrix = localGapMatrix(reports);
writetable(gapMatrix,fullfile(metadataRoot,"report_family_gap_matrix.csv"));

handoffs = localHandoffCatalog(reports);
writetable(handoffs,fullfile(metadataRoot,"family_handoff_catalog.csv"));

duplication = localDuplicationReview();
writetable(duplication,fullfile(metadataRoot,"report_family_duplication_review.csv"));

visuals = localVisualCatalog(reportRoot,agenticRoot);
writetable(visuals,fullfile(metadataRoot,"family_visual_catalog.csv"));

codeNavigation = localCodeNavigation(reports,flightTestRoot,agenticRoot);
writetable(codeNavigation,fullfile(metadataRoot,"family_code_navigation.csv"));

localWriteStorySpine(fullfile(metadataRoot,"report_family_story_spine.html"),reports);
localWriteGapReview(fullfile(metadataRoot,"report_family_gap_review.md"), ...
    reports,gapMatrix,handoffs,visuals,codeNavigation);
localWriteGapReviewAudit(fullfile(metadataRoot,"report_family_gap_review_audit.md"), ...
    reportRoot,reports,sourceHashes,visuals,codeNavigation);

audit = gapMatrix;
end

function gapMatrix = localGapMatrix(reports)
ids = string({reports.Id})';
filenames = string({reports.Filename})';
latest = filenames;
accepted = filenames;
questions = string({reports.Question})';
ownership = string({reports.Ownership})';
actual = ownership;
pattern = string({reports.Pattern})';
executive = ["Adequate";"Strong";"Strong";"Adequate";"Strong";"Adequate";"Adequate";"Strong";"Strong"];
resultVisibility = ["Adequate";"Strong";"Strong";"Adequate";"Strong";"Adequate";"Strong";"Strong";"Strong"];
metrics = ["Adequate";"Strong";"Adequate";"Strong";"Strong";"Adequate";"Strong";"Strong";"Strong"];
whyMatters = ["Strong";"Strong";"Strong";"Adequate";"Strong";"Adequate";"Strong";"Strong";"Strong"];
decision = ["Adequate";"Strong";"Strong";"Adequate";"Strong";"Adequate";"Strong";"Strong";"Strong"];
uncertainty = ["Strong";"Strong";"Strong";"Strong";"Strong";"Strong";"Strong";"Strong";"Strong"];
evidence = ["Adequate";"Strong";"Strong";"Strong";"Strong";"Adequate";"Strong";"Strong";"Strong"];
code = ["Weak";"Adequate";"Adequate";"Adequate";"Strong";"Adequate";"Adequate";"Adequate";"Adequate"];
predecessor = ["Missing";"Adequate";"Adequate";"Adequate";"Adequate";"Adequate";"Adequate";"Adequate";"Adequate"];
successor = ["Missing";"Adequate";"Adequate";"Adequate";"Adequate";"Adequate";"Adequate";"Adequate";"Missing"];
overlap = repmat("Adequate",9,1);
missingEvidence = [ ...
    "No manager-first handoff to illuminator screening."; ...
    "Original 3-D ray-path image remains unavailable."; ...
    "Later direct-sampling RF Analyzer diagram remains unavailable."; ...
    "No field qualification evidence for roles, lock, drops, or reference adequacy."; ...
    "No recoverable raw paired before/after injection plot."; ...
    "Gate mechanics need a compact manager-first entry layer."; ...
    "No replacement R5A matrix is authorized or available."; ...
    "No live-aircraft detection or operational performance evidence."; ...
    "No resolved map-contract or collection/reference qualification closure."];
missingVisual = [ ...
    "Cross-report motivation-to-geometry glue diagram."; ...
    "Original Apple Hill 3-D ray-path capture."; ...
    "Source-faithful full direct-sampling N320 RF Budget Analyzer diagram."; ...
    "Qualified channel-role/lock/drop evidence visual."; ...
    "Source-faithful raw before/after injection pair."; ...
    "Plain-language passive-map formation glue diagram."; ...
    "No new visual required; retain recovery and failure evidence."; ...
    "No decorative visual required; retain atlas originals."; ...
    "Current integrated family dependency visual."];
provenance = [ ...
    "Existing root index omits 01A, 01B, and 02A."; ...
    "Candidate-list provider and full transformation lineage are unrecovered."; ...
    "Historical 548/596.3 versus 551/599 MHz and target-power discrepancies are retained."; ...
    "Collection package exists but hardware qualification is incomplete."; ...
    "August synthetic package and September atlas use distinct configurations."; ...
    "Source navigation is distributed rather than canonical."; ...
    "R4 bounded pass and R5A formal failure require explicit separation."; ...
    "Atlas evidence is diagnostic and must retain its non-claim boundary."; ...
    "Current status must preserve independent map and collection blockers."];
discrepancy = [ ...
    "Six-report legacy index does not represent the nine-report family."; ...
    "Historical model preference is not prototype configuration selection."; ...
    "Frequency, filter-loss, and target-level model differences are unresolved historical inputs."; ...
    "Infrastructure evidence is not collection readiness."; ...
    "Seed-backed and real-background modes are distinct."; ...
    "Implementation is not a released detector/tracker measurement contract."; ...
    "R4 pilot pass does not override R5A matrix failure."; ...
    "Support exclusion is not a detector miss; configured Pfa is not operational Pfa."; ...
    "No downstream claim is enabled by diagnostic evidence."];
disposition = [ ...
    "Freeze with Cross-Links"; ...
    "Accepted with Known Gaps"; ...
    "Accepted with Known Gaps"; ...
    "Freeze with Cross-Links"; ...
    "Accepted with Known Gaps"; ...
    "Freeze with Cross-Links"; ...
    "Accepted with Known Gaps"; ...
    "Accepted with Known Gaps"; ...
    "Freeze with Cross-Links"];
priority = [ ...
    "P0";"P2";"P2";"P1";"P2";"P1";"P1";"P1";"P1"];
confidence = [ ...
    "High";"High";"High";"High";"High";"High";"High";"High";"High"];
notes = [ ...
    "Release-local handoff block resolves the P0 family navigation gap without editing source content."; ...
    "Use original geometry output; do not fabricate a ray-path figure."; ...
    "Use existing recovered figures and preserve model-to-installation boundary."; ...
    "No field claim may be added; classify qualification as unresolved."; ...
    "Use the declared-truth and placement visuals; keep missing raw pair explicit."; ...
    "Release manager-first block makes the gate purpose available before detail."; ...
    "Use release handoff to Report 05 and retain failed-matrix metrics."; ...
    "Use atlas originals and exact non-conclusions; do not infer operational capability."; ...
    "Release index and dependency view integrate the status without changing recommendations."];

gapMatrix = table(ids,filenames,latest,accepted,questions,ownership,actual,pattern, ...
    executive,resultVisibility,metrics,whyMatters,decision,uncertainty,evidence, ...
    code,predecessor,successor,overlap,missingEvidence,missingVisual,provenance, ...
    discrepancy,disposition,priority,confidence,notes, ...
    'VariableNames',{ ...
    'ReportID','CandidateFilename','LatestAvailableVersion','AcceptedVersion', ...
    'PrimaryQuestion','IntendedTopicOwnership','ActualTopicsCovered', ...
    'PatternClassification','ExecutiveAnswerQuality','ResultVisibility', ...
    'ImportantMetricsVisible','WhyItMattersQuality','EngineeringDecisionVisibility', ...
    'RemainingUncertaintyVisibility','OriginalEvidenceQuality','CodeDiscoverability', ...
    'PredecessorInputClarity','SuccessorHandoffClarity','ScopeOverlap', ...
    'MissingTechnicalEvidence','MissingVisual','SourceProvenanceGap', ...
    'ContradictionOrDiscrepancy','RecommendedDisposition','Priority','Confidence','Notes'});
end

function handoffs = localHandoffCatalog(reports)
from = string({reports(1:8).Id})';
to = string({reports(2:9).Id})';
closed = [ ...
    "Why evidence-led passive HDTV work is worth investigating."; ...
    "Historical candidate geometry and signal inputs for receive-chain reasoning."; ...
    "Designed RF architecture and the questions physical qualification must answer."; ...
    "Recorded dual-channel collection context suitable for controlled-background replay."; ...
    "Declared truth package and paired-control construction for truth-blind processing."; ...
    "Gate contract showing why map validity and mitigation are technical turning points."; ...
    "Map-rate recovery evidence and the R5A boundary that frames the atlas result."; ...
    "Strongest bounded evidence and its exact non-conclusions."];
results = string({reports(1:8).StrongestResult})';
metrics = string({reports(1:8).Metric})';
decisions = string({reports(1:8).Decision})';
artifacts = [ ...
    "North Star, claim boundary, and evidence-first program framing."; ...
    "Historical tower/geometry screening and RF-design input set."; ...
    "RF design rationale, component decisions, and qualification question set."; ...
    "Replayable package, manifests, and infrastructure boundary."; ...
    "Declared truth, injection manifest, and paired control contract."; ...
    "Gate definitions, truth-separation rules, and release requirements."; ...
    "R1-R5A recovery record and bounded correction decision boundary."; ...
    "Atlas outcome table, paired controls, and diagnostic conclusion set."];
inputs = [ ...
    "Motivation and measurement-first constraints."; ...
    "Candidate frequency, bandwidth, geometry, and historical modeled levels."; ...
    "Designed architecture plus unresolved installed-performance questions."; ...
    "Real dual-channel background and collection/provenance context."; ...
    "Declared truth package used only after candidate generation."; ...
    "Truth-blind pipeline and protected gate semantics."; ...
    "Map-rate/cancellation context and R5A limitation."; ...
    "Exact bounded evidence, non-conclusions, and blocker state."];
evidence = [ ...
    "Report 01 V2 North Star and evidence vocabulary."; ...
    "Report 01A V4 historical model, provenance, and audit."; ...
    "Report 01B V2 source inventory and architecture audit."; ...
    "Report 02 V5 package/manifests, qualification criteria, and as-built cueing/time state."; ...
    "Report 02A V1 source inventory, declared truth, and atlas references."; ...
    "Report 03 pipeline/gate evidence and current project-state links."; ...
    "Report 04 V2 R1-R5A evidence and cancellation references."; ...
    "Report 05 atlas/paired-control evidence and Report 06 status."];
missing = [ ...
    "Legacy family navigation did not identify the illuminator bridge."; ...
    "Frequency/configuration discrepancies were not visible to downstream readers."; ...
    "Model-to-installed handoff was not centrally navigable."; ...
    "Collection-to-injection transition was not in the legacy family index."; ...
    "Truth declaration to truth-blind processing transition was distributed."; ...
    "Pipeline-to-recovery connection was not exposed before deep detail."; ...
    "Recovery-to-atlas relationship could be mistaken for formal gate closure."; ...
    "Atlas-to-status relationship needed an explicit independent-blocker reminder."];
status = repmat("Resolved by release-local handoff block",8,1);
action = repmat("Inject canonical release handoff and retain original evidence links.",8,1);
priority = repmat("P0",8,1);
notes = [ ...
    "No source report rewrite."; ...
    "Display historical configuration caveat."; ...
    "Keep design, installed hardware, and qualification separate."; ...
    "Keep infrastructure distinct from qualification."; ...
    "Keep truth post hoc and synthetic boundary visible."; ...
    "Keep detector/tracker gate disables visible."; ...
    "Keep R4 bounded success separate from R5A failure."; ...
    "Keep diagnostic recovery separate from live-aircraft claims."];

handoffs = table("H" + compose("%02d",(1:8)') ,from,to,closed,results,metrics, ...
    decisions,artifacts,inputs,evidence,missing,status,action,priority,notes, ...
    'VariableNames',{ ...
    'HandoffID','FromReport','ToReport','QuestionClosedUpstream', ...
    'ResultProducedUpstream','ImportantMetric','EngineeringDecision', ...
    'ArtifactOrOutputProduced','InputConsumedDownstream','SupportingEvidence', ...
    'MissingHandoffItem','HandoffStatus','RecommendedAction','Priority','Notes'});
end

function duplication = localDuplicationReview()
topic = [ ...
    "Project motivation";"Evidence-level framing";"Modeled feasibility"; ...
    "Physical architecture";"Collection packaging";"Gate definitions"; ...
    "Synthetic-data boundaries";"G4-R activation";"R4 versus R5A"; ...
    "Strongest recovery outcome";"Current blockers";"Status matrices"; ...
    "Management recommendations";"Tracking and localization non-claims"];
containing = [ ...
    "01, 06";"01, 03, 04, 05, 06";"01A, 01B";"01B, 02"; ...
    "02, 02A";"01, 03, 04, 06";"02A, 03, 05, 06";"03, 04, 06"; ...
    "04, 05, 06";"05, 06";"02, 04, 06";"01, 04, 06"; ...
    "01, 06";"01, 03, 05, 06"];
owner = [ ...
    "01";"01";"01A";"02";"02";"03";"02A";"04";"04";"05";"06";"06";"06";"01"];
duplicateType = repmat("Necessary local context",14,1);
necessary = repmat("Yes",14,1);
harmful = repmat("No",14,1);
keep = owner;
crossLink = [ ...
    "06";"03, 04, 05, 06";"01B";"01B";"02A";"01, 04, 06"; ...
    "03, 05, 06";"03, 06";"05, 06";"06";"02, 04, 05"; ...
    "01, 04";"01";"03, 05, 06"];
reduce = repmat("None; retain summary-only contextual references.",14,1);
recommendation = repmat("Preserve ownership and use release-local cross-links.",14,1);
priority = repmat("None",14,1);
notes = repmat("No harmful duplication found; ownership is retained in the canonical release.",14,1);
duplication = table(topic,containing,owner,duplicateType,necessary,harmful,keep, ...
    crossLink,reduce,recommendation,priority,notes, ...
    'VariableNames',{ ...
    'Topic','ReportsContainingTopic','PrimaryOwner','DuplicateType', ...
    'NecessaryLocalContext','HarmfulDuplication','KeepInOwnerReport', ...
    'CrossLinkFrom','ReduceOrRemoveFrom','Recommendation','Priority','Notes'});
end

function visuals = localVisualCatalog(reportRoot,agenticRoot)
visualId = "VIS-" + compose("%02d",(1:19)');
question = [ ...
    "Candidate tower provenance";"Tower and receiver geography"; ...
    "Local Site Viewer geometry";"RF Budget Analyzer model"; ...
    "Designed system architecture";"Modeled versus installed hardware"; ...
    "Physical deployment";"Collection package anatomy"; ...
    "Timing and truth workflow";"Synthetic target declaration"; ...
    "Target geometry";"Before/after injection";"Passive map formation"; ...
    "Direct-path cancellation";"Map-rate mismatch";"Detector support"; ...
    "Bounded recovery";"Current blockers";"Future measurement and localization path"];
owner = [ ...
    "01A";"01A";"01A";"01B";"01B";"01B";"02";"02";"02"; ...
    "02A";"02A";"02A";"03";"04";"04";"05";"05";"06";"01, 03, 06"];
title = [ ...
    "Saved RabbitEars/parser and tower-list provenance"; ...
    "Candidate transmitter and receiver-site maps"; ...
    "Apple Hill building-footprint geometry"; ...
    "Recovered RF Budget Analyzer system model"; ...
    "Recovered parking-lot designed architecture"; ...
    "Cascade and enclosure evidence"; ...
    "Deployment and receiver photographs"; ...
    "Manifest, package, and replay evidence"; ...
    "ADS-B/GPS and truth-separation workflow"; ...
    "Declared-truth construction"; ...
    "Geographic and delay-Doppler placement"; ...
    "Source-derived channel-contract schematic"; ...
    "G1-G10 gate architecture"; ...
    "Cancellation characterization graphic"; ...
    "Corrected map-rate and R5A comparison"; ...
    "Support-policy and CFAR placement"; ...
    "Paired native-first/no-mitigation atlas outcomes"; ...
    "Independent blocker and action view"; ...
    "Measurement-to-tracking-to-localization path"];
path = [ ...
    "01A source inventory and report-local assets"; ...
    "01A_IlluminatorSelection_assets"; ...
    "01A_IlluminatorSelection_assets/apple_hill_building_geometry_aoi.png"; ...
    "01B_ReceiveChainDesign_assets/rf_budget_analyzer_system_model.png"; ...
    "01B_ReceiveChainDesign_assets/parking_lot_designed_architecture.png"; ...
    "01B_ReceiveChainDesign_assets"; ...
    "02_HardwareAndCollection_V5.html and HardwarePhotos"; ...
    "02_HardwareAndCollection_V5.html package/manifests"; ...
    "02_HardwareAndCollection_V5.html"; ...
    "02A_SyntheticEchoGeneration_V1.html"; ...
    "02A_SyntheticEchoGeneration_assets"; ...
    "02A native HTML channel-contract schematic"; ...
    "03_AnalysisPipelineAndGateRebuild.html"; ...
    "04_MitigationAndMapRateRecovery_V2.html"; ...
    "04_MitigationAndMapRateRecovery_V2.html"; ...
    "05_StrongestEvidence_G4RRecoveryStudy.html"; ...
    "G4_R_Close_Target_Atlas_Recovery summary.html"; ...
    "06_StatusAndFutureWork_V3.html"; ...
    "01/03/06 release-local continuity block"];
source = [ ...
    "Saved RabbitEars page and parser";"Original LinkBudget sources"; ...
    "Original embedded Live Script output";"LinkBudgetProgress.pptx slide 30"; ...
    "MountingDiagramParkingLot.pptx slide 4";"Historical RF-budget code and enclosure evidence"; ...
    "Original deployment photographs";"Original manifests and replay artifacts"; ...
    "Collection and project-state sources";"SyntheticHDTVSimulation code and manifests"; ...
    "Accepted atlas and generator evidence";"No recoverable raw matched pair"; ...
    "Report 03 and passive pipeline sources";"Cancellation characterization bundle"; ...
    "G4-R diagnosis/checkpoint/matrix evidence";"Atlas policy and CFAR artifacts"; ...
    fullfile(agenticRoot,"PassiveBistaticRestart","artifacts","20260622T102123", ...
        "G4_R_Close_Target_Atlas_Recovery","20260918T134014380Z","summary.html"); ...
    "Report 06 and hardware/map blocker evidence";"Reports 01, 03, and 06"];
metric = [ ...
    "Tower/channel fields";"Candidate geometry";"No measured power"; ...
    "Stage gain/NF/OIP3";"Component layout";"Loss/headroom values"; ...
    "Physical presence only";"15 packages";"No field qualification"; ...
    "Declared truth fields";"-76.456 microseconds, +540.5 Hz";"Not applicable"; ...
    "G1-G10";"9/9 native-first map controls";"59/108 R5A failures"; ...
    "Configured Pfa context";"8/8 versus 0/8";"Two blockers";"No validated measurement yet"];
decision = [ ...
    "Trace tower screening inputs";"Select historical cases for analysis"; ...
    "Retain geometry limitation";"Explain model origin";"Explain design translation"; ...
    "Separate model from installed qualification";"Document infrastructure"; ...
    "Retain replay provenance";"Keep truth post hoc";"Declare target before replay"; ...
    "Inspect support before interpretation";"Do not fabricate visual"; ...
    "Protect downstream claims";"Review bounded correction only"; ...
    "Retain R5A failure";"Do not call exclusion a miss"; ...
    "Retain bounded diagnostic conclusion";"Keep independent blockers"; ...
    "Do not infer tracking/localization"];
readability = repmat("Strong",19,1);
historical = [ ...
    "Historical";"Historical";"Historical";"Historical";"Historical"; ...
    "Historical";"Current infrastructure";"Current infrastructure"; ...
    "Current infrastructure";"Mixed";"Current accepted diagnostic"; ...
    "Current explanatory";"Current process";"Current diagnostic"; ...
    "Current diagnostic";"Current diagnostic";"Current diagnostic"; ...
    "Current status";"Current boundary"];
mainStory = [ ...
    "Yes";"Yes";"Technical reference";"Yes";"Yes";"Yes";"Yes"; ...
    "Technical reference";"Technical reference";"Yes";"Yes";"No"; ...
    "Yes";"Yes";"Yes";"Yes";"Yes";"Yes";"Yes"];
technicalReference = repmat("Yes",19,1);
missing = [ ...
    "";"";"Original 3-D ray-path capture";"";"";"";"";"";"";"";""; ...
    "Original raw before/after injection pair";"";"";"";"";"";"";""];
candidate = [ ...
    "";"";"Unrecovered original only";"";"";"";"";"";"";"";""; ...
    "Unrecovered original only";"";"";"";"";"";"";""];
action = [ ...
    "Bundle source navigation";"Bundle retained original maps"; ...
    "Record known gap; do not recreate";"Bundle original recovered image"; ...
    "Bundle original recovered image";"Bundle retained originals"; ...
    "Bundle local media";"Bundle inventories and manifests"; ...
    "Cross-link to Report 03";"Bundle retained original/derived evidence"; ...
    "Bundle atlas visuals";"Record known gap; retain labelled schematic"; ...
    "Use original report figure";"Use original report figure"; ...
    "Use original report figure";"Use original atlas figure"; ...
    "Use original atlas figure";"Use original status figure"; ...
    "Use release-local glue block only"];
priority = [ ...
    "P1";"P1";"P2";"P1";"P1";"P2";"P1";"P2";"P2"; ...
    "P1";"P1";"P2";"P1";"P1";"P1";"P1";"P1";"P1";"P2"];
notes = repmat("Original or source-backed only; no decorative replacement recommended.",19,1);
visuals = table(visualId,question,owner,title,path,source,question,metric,decision, ...
    readability,historical,mainStory,technicalReference,missing,candidate,action, ...
    priority,notes, ...
    'VariableNames',{ ...
    'VisualID','EngineeringQuestion','OwnerReport','ExistingVisualTitle', ...
    'ExistingVisualPath','OriginalSource','QuestionAnswered','ImportantMetric', ...
    'DecisionRelevance','Readability','HistoricalOrCurrent','MainStorySuitability', ...
    'TechnicalReferenceSuitability','MissingVisual','CandidateSource', ...
    'RecommendedAction','Priority','Notes'});
% 2026-09-26: System Engineering section visuals (outside the family, recorded for navigation).
extraVisuals = array2table([ ...
    "VIS-20", "System architecture and as-built status", "System section", "Functional architecture with as-built status", "system/03_ArchitectureAndAllocation.html (inline SVG)", "docs/system System_Architecture.md, ICD_Messages.md, As_Built.md", "System architecture and as-built status", "One verified link", "Separate designed from built", "Strong", "Current", "Yes", "Yes", "", "", "Keep inline and update with As_Built", "P1", "Source-backed schematic; no performance content."; ...
    "VIS-21", "Message size before and after CR-5", "System section", "Median bytes per message", "system/SDR_CT_CueTasking_assets/fig_message_size.svg", "docs/system/evidence captures 20260926T1234Z and T1523Z", "Message size before and after CR-5", "7,962 B to 681 B per cue", "Justify the encoding decision", "Strong", "Current", "Yes", "Yes", "", "", "Regenerate with summarize_cue_capture.py", "P1", "Measured message sizes."; ...
    "VIS-22", "One-frame fit of every cue", "System section", "track_cue bytes against opportunities", "system/SDR_CT_CueTasking_assets/fig_cue_size_vs_opportunities.svg", "docs/system/evidence capture 20260926T1523Z", "One-frame fit of every cue", "0 of 223 over 1472 B; max 747 B", "Accept the interface", "Strong", "Current", "Technical reference", "Yes", "", "", "Regenerate with summarize_cue_capture.py", "P2", "Measured message interface; not radar evidence."; ...
    "VIS-23", "Live capture timeline", "System section", "What arrived, and when", "system/SDR_CT_CueTasking_assets/fig_capture_timeline.svg", "docs/system/evidence capture 20260926T1523Z", "Live capture timeline", "15 snapshots consistent", "Accept the interface", "Strong", "Current", "Technical reference", "Yes", "", "", "Regenerate with summarize_cue_capture.py", "P2", "Measured message interface; not radar evidence."], ...
    'VariableNames',visuals.Properties.VariableNames);
visuals = [visuals;extraVisuals];
end

function codeNavigation = localCodeNavigation(reports,flightTestRoot,agenticRoot)
topic = [ ...
    "Illuminator selection";"Link budget";"Site Viewer analysis";"RF budget"; ...
    "Hardware characterization";"Coordinated collection";"Synthetic target generation"; ...
    "Package generation";"Pipeline entry point";"R1 through R5A"; ...
    "G4-R atlas generation";"Detector replay";"Truth association"; ...
    "Field-qualification scripts and plans"];
owner = [ ...
    "01A";"01A";"01A";"01B";"02";"02";"02A";"02A";"03"; ...
    "04";"05";"05";"05";"06"];
purpose = [ ...
    "Screen candidate tower/channel and geometry assumptions."; ...
    "Model historical target/direct-path conditions."; ...
    "Inspect local buildings and terrain context."; ...
    "Reason about cascade losses, headroom, and component choices."; ...
    "Inspect installed-chain and qualification context."; ...
    "Coordinate collection and package creation."; ...
    "Create declared synthetic truth and real-background echo cases."; ...
    "Build reviewable synthetic packages and manifests."; ...
    "Form passive maps under gate controls."; ...
    "Diagnose and evaluate map-rate/cancellation remediation."; ...
    "Run the close-target atlas/recovery study."; ...
    "Replay diagnostic detector conditions."; ...
    "Associate truth only after candidate generation."; ...
    "Plan and execute reference-chain/collection qualification."];
entry = [ ...
    fullfile(flightTestRoot,"LinkBudget","FlightTest_Bistatic_RadarAndCommsAnalysis.mlx"); ...
    fullfile(flightTestRoot,"LinkBudget","FlightTest_Bistatic_RadarAndCommsAnalysis.mlx"); ...
    fullfile(flightTestRoot,"LinkBudget","AppleHill_CustomizeBuildingsForRayTracingAnalysisExample.mlx"); ...
    fullfile(flightTestRoot,"RFBudget","RFBudget_Newton.m"); ...
    fullfile(flightTestRoot,"SystemPrechecks","RFBudget","RFBudgetModel_Newton.m"); ...
    fullfile(flightTestRoot,"TestSetupTesting","runCoordinatedHDTVCapture.m"); ...
    fullfile(agenticRoot,"flightTest_SynthDataBranch","SyntheticHDTVSimulation","generateRealBackgroundSyntheticSuite.m"); ...
    fullfile(agenticRoot,"flightTest_SynthDataBranch","SyntheticHDTVSimulation","generateSyntheticHDTVSession.m"); ...
    fullfile(agenticRoot,"PassiveBistaticRestart","runG4PassiveBaselineMap.m"); ...
    fullfile(agenticRoot,"PassiveBistaticRestart","runG4RMapRateMatrix.m"); ...
    fullfile(agenticRoot,"PassiveBistaticRestart","runG4RCloseTargetAtlasRecoveryStudy.m"); ...
    fullfile(agenticRoot,"PassiveBistaticRestart","helperReplayG6DDetector.m"); ...
    fullfile(agenticRoot,"PassiveBistaticRestart","helperClassifyTruthEvaluation.m"); ...
    fullfile(flightTestRoot,"hardwareCheck.md")];
support = [ ...
    "Radio_Tower_List.txt and saved RabbitEars parser"; ...
    "helperPathlossOverTerrain.m and helperRadarCoverageTargetGrid.m"; ...
    "applehill.osm"; ...
    "RFBudget_Comparative_Analysis.m and vendor S2P"; ...
    "Hardware photos, hardwareCheck.md, and manifests"; ...
    "runLocalHDTVCapture.m and synchronization helpers"; ...
    "helperSyntheticGenerateTruth.m and echo helpers"; ...
    "seedBackedSyntheticHDTVSessionWalkthrough.m"; ...
    "G1-G3 helpers and G4 verification"; ...
    "helperAnalyzeG4MapRateValidity.m and cancellation helpers"; ...
    "helperEvaluateG4RCloseTargetCondition.m and atlas manifest helpers"; ...
    "helperReplayG6DRepresentativeDetection.m"; ...
    "atlas outcome tables and post-hoc association records"; ...
    "projectProvenanceUpdate.md and capture plans"];
inputs = [ ...
    "Tower lists, geography, candidate channels"; ...
    "Historical transmitter/target assumptions"; ...
    "Apple Hill OSM geometry"; ...
    "Historical signal cases and component data"; ...
    "Hardware records and collection metadata"; ...
    "N320, ADS-B, GPS, and capture configuration"; ...
    "Declared trajectory, background, and echo conditions"; ...
    "Seed or real-background configuration"; ...
    "Dual-channel package and gate configuration"; ...
    "Frozen R4 contract and paired conditions"; ...
    "Atlas condition manifest and accepted compact evidence"; ...
    "Stored map/candidate configuration"; ...
    "Candidate list and withheld truth"; ...
    "Hardware mapping, lock/drop, and ADS-B criteria"];
outputs = [ ...
    "Modeled candidate cases";"Link-budget outputs";"Geometry visualization"; ...
    "Cascade comparisons";"Qualification evidence";"Capture package"; ...
    "Synthetic package and truth";"Manifest and validation artifacts"; ...
    "Passive maps and gate records";"R1-R5A metrics and decisions"; ...
    "Atlas outcomes and walkthrough";"Diagnostic candidate view"; ...
    "Post-hoc association";"Field-readiness decision"];
figures = [ ...
    "01A maps";"01A modeled coverage";"01A geometry image";"01B cascade figures"; ...
    "02 hardware figures";"02 package/replay figures";"02A declaration/placement"; ...
    "02A validation figures";"03 gate figure";"04 recovery figures"; ...
    "05 atlas figures";"05 diagnostic views";"05 outcomes";"06 blocker/action figures"];
status = strings(numel(entry),1);
for index = 1:numel(entry)
    if isfile(entry(index))
        status(index) = "Inspected only";
    else
        status(index) = "Referenced only";
    end
end
missing = repmat("",numel(entry),1);
recommendation = repmat("Record release-local code link and execution status; do not claim execution.",numel(entry),1);
priority = [ ...
    "P1";"P1";"P2";"P1";"P1";"P1";"P1";"P2";"P1"; ...
    "P1";"P1";"P2";"P2";"P1"];
notes = repmat("Code was navigated from inventories and project artifacts; no execution is claimed.",numel(entry),1);
branch = repmat("Current local working tree",numel(entry),1);
codeNavigation = table(topic,owner,purpose,entry,branch,support,inputs,outputs,figures, ...
    repmat("Release metadata link",numel(entry),1),repmat("Strong",numel(entry),1), ...
    status,missing,recommendation,priority,notes, ...
    'VariableNames',{ ...
    'EngineeringTopic','OwnerReport','HumanReadablePurpose','TopLevelCodeEntry', ...
    'RepositoryBranch','SupportingFunctions','InputArtifacts','OutputArtifacts', ...
    'FiguresProduced','ReportLinkPresent','LinkQuality','ExecutionStatus', ...
    'MissingNavigation','RecommendedChange','Priority','Notes'});
% 2026-09-26: cue tasking and system documents (code outside this repository or on branches).
extraCode = array2table([ ...
    "ADS-B cue tasking (CT)", "System section (SDR-CT); installed state in 02", "Publish per-aircraft cues with modeled illuminator opportunities.", "https://github.com/lhilleMAT2022/ADSB-remoter/blob/55062fc8a4ccacbcb7cedb5dfe8cdbe7a23c8f21/src/adsb_console/cue.py", "ADSB-remoter feature/passive-radar-cueing @ 55062fc", "prediction.py, bistatic.py, cue_config.py, app.py --headless, deploy/, schemas/ 2.0.0 and dictionaries/", "dump1090 SBS, DTV emitter table, observer INI, cue config", "CT 2.0.0 UDP multicast datagrams", "SDR-CT Figures 2-4", "Release metadata link", "Strong", "Inspected; 81 tests re-run 2026-09-26", "", "Record the commit deployed on the Pi in As_Built.md at each update.", "P1", "Deployed on the ADS-B Pi as systemd adsb-cue."; ...
    "Cue capture and verification", "System section (SDR-CT)", "Decode and validate the cue stream and summarise gaps and sizes.", "https://github.com/lhilleMAT2022/ADSB-remoter/blob/55062fc8a4ccacbcb7cedb5dfe8cdbe7a23c8f21/tools/cue_capture.py", "ADSB-remoter feature/passive-radar-cueing @ 55062fc", "tools/cue_decode.py; tools/build_cue_dictionary.py", "Live multicast stream", "docs/system/evidence/*_wire.jsonl and *_summary.json", "SDR-CT Figures 2-4", "Release metadata link", "Strong", "Inspected only", "", "Keep raw wire bytes for every verification capture.", "P1", "Evidence files live on flightTest main under docs/system/evidence/."; ...
    "Cue reception (RM first piece)", "System section (SDR-CT)", "Receive and rank cues in MATLAB; no tasking.", "https://github.com/pwilliamMAT/flightTest/tree/94bf9247fc9384fd0601e7ef4654f2a1630485c6/CueListener", "flightTest feature/adsb-cue-listener @ 94bf924", "runCueListener.m, plotCueWindows.m, dictionaries/", "CT multicast stream or JSONL log", "Active cues and opportunity windows", "SDR-CT section 8", "Release metadata link", "Strong", "Inspected; 16 tests re-run 2026-09-26", "Code stays on its branch pending review.", "Pat to review feature/adsb-cue-listener; link the branch or pinned commit 94bf924.", "P1", "Java MulticastSocket and java.util.zip; compiled-app probe in docs/system/analysis/deployability/."; ...
    "System documents", "System section; 02; 06", "Architecture, requirements (draft), ICD, as-built, change requests, verification log.", "https://github.com/pwilliamMAT/flightTest/tree/main/docs/system", "flightTest main", "analysis/ scripts and deployability probe", "Owner decisions and captures", "Controlled documents", "System section pages", "Release metadata link", "Strong", "Inspected only", "", "Merge the 2026-09-26 proposals (Requirements.md, CR-9, CR-10) before promoting the section.", "P1", "Master copy since 2026-09-26."; ...
    "Cue-interface figure generation", "System section (SDR-CT)", "Reproduce the CT 2.0.0 acceptance numbers and draw SDR-CT Figures 2-4.", "https://github.com/pwilliamMAT/flightTest/blob/main/docs/system/analysis/summarize_cue_capture.py", "flightTest main (proposed 2026-09-26)", "Python standard library; optional jsonschema", "docs/system/evidence captures and dictionary 1", "SVG figures and cue_capture_summary.json", "SDR-CT Figures 2-4", "Release metadata link", "Strong", "Executed 2026-09-26", "", "Re-run after any new verification capture.", "P1", "Cross-checks the committed capture summary."], ...
    'VariableNames',codeNavigation.Properties.VariableNames);
codeNavigation = [codeNavigation;extraCode];
end

function localWriteStorySpine(path,reports)
cards = strings(numel(reports),1);
for index = 1:numel(reports)
    report = reports(index);
    previousText = "Starts the canonical narrative.";
    if strlength(string(report.Predecessor)) > 0
        previousText = "Consumes the engineering output from Report " + report.Predecessor + ".";
    end
    nextText = "Ends the current canonical narrative.";
    if strlength(string(report.Successor)) > 0
        nextText = "Hands a defined artifact to Report " + report.Successor + ".";
    end
    cards(index) = "<article class=""tsf-card"">" + ...
        "<h2>" + report.Id + " — " + localHtmlEscape(report.Question) + "</h2>" + ...
        "<p><b>Result:</b> " + localHtmlEscape(report.StrongestResult) + "</p>" + ...
        "<p><b>Metric:</b> " + localHtmlEscape(report.Metric) + "</p>" + ...
        "<p><b>Decision:</b> " + localHtmlEscape(report.Decision) + "</p>" + ...
        "<p><b>Still unknown:</b> " + localHtmlEscape(report.Unknown) + "</p>" + ...
        "<p><b>Handoff:</b> " + localHtmlEscape(previousText) + " " + ...
        localHtmlEscape(nextText) + "</p>" + ...
        "<p><a href=""../reports/" + report.Filename + """>Open report</a></p></article>";
end
body = strjoin(cards,newline + "<div class=""tsf-arrow"">↓</div>" + newline);
html = "<!doctype html><html><head><meta charset=""utf-8"">" + ...
    "<title>Technical Summary Family Story Spine</title>" + ...
    "<style>body{max-width:1100px;margin:2rem auto;font:16px/1.5 Segoe UI,Arial;color:#172033}" + ...
    ".tsf-card{border:1px solid #cbd5e1;border-left:6px solid #0f4c81;padding:1rem;margin:1rem 0;background:#fff}" + ...
    ".tsf-arrow{text-align:center;font-size:1.8rem;color:#0f4c81}a{color:#075caa}</style></head><body>" + ...
    "<h1>Report Family Story Spine</h1><p>Review artifact only. It exposes questions, results, decisions, uncertainty, and handoffs without replacing the technical reports.</p>" + ...
    body + "</body></html>";
localWriteText(path,html);
end

function localWriteGapReview(path,reports,gapMatrix,handoffs,visuals,codeNavigation)
p0Count = sum(gapMatrix.Priority == "P0");
p1Count = sum(gapMatrix.Priority == "P1");
text = "# Technical Summary Family Gap Review" + newline + newline + ...
    "## 1. Executive verdict" + newline + newline + ...
    "The family is technically coherent and human-readable when read through the nine-report sequence, but the legacy six-report navigation prevented the newer engineering-decision explainers from acting as canonical handoffs. The family is **Ready after P0 fixes**: the required P0 work is release-local continuity, canonical version mapping, and dependency validation. No source technical conclusion requires revision." + newline + newline + ...
    "The strongest content is the 01A/01B/02A outcome-first chain and the 04/05/06 evidence-to-decision chain. The main gaps are preserved historical-model discrepancies, missing original visual recoveries, incomplete field qualification, and disabled downstream measurement/tracking work. Those are visible known gaps, not grounds to invent evidence." + newline + newline + ...
    "## 2. Strongest reports and handoffs" + newline + newline + ...
    "- 01A to 01B turns historical illumination cases into explicit RF-design inputs." + newline + ...
    "- 01B to 02 separates modeled design from installed hardware and qualification." + newline + ...
    "- 02A to 03 preserves declared truth while keeping pipeline candidate generation truth-blind." + newline + ...
    "- 04 to 05 separates R5A formal failure from bounded controlled atlas evidence." + newline + ...
    "- 05 to 06 preserves exact diagnostic conclusions and independent blockers." + newline + newline + ...
    "## 3. Critical content gaps" + newline + newline + ...
    "- P0: canonical family navigation and handoff visibility were incomplete. The release-only navigation block and handoff catalog resolve this without editing report content." + newline + ...
    "- P1: field qualification evidence for channel role, lock/drop, and reference adequacy is absent; it remains a project evidence gap." + newline + ...
    "- P1: older reports 01, 02, 03, 04, and 06 are less consistently manager-first. The release adds an executive continuity layer rather than rewriting accepted evidence." + newline + ...
    "- P2: original Apple Hill 3-D ray-path and raw matched injection-pair visuals are unrecovered. Their absence remains explicit." + newline + newline + ...
    "## 4. Weak handoffs" + newline + newline + ...
    "All eight handoffs are retained in `family_handoff_catalog.csv`. Release-local cards make the upstream output and downstream input explicit; navigation alone is not used as the handoff evidence." + newline + newline + ...
    "## 5. Technical evidence gaps" + newline + newline + ...
    "- Historical 01A/01B frequency, ERP, filter-loss, and target-power assumptions differ and must not be silently reconciled." + newline + ...
    "- Collection infrastructure is not field-qualified reference-path evidence." + newline + ...
    "- Synthetic recovery does not establish live-aircraft detection, operational Pd/Pfa, tracking, or localization." + newline + newline + ...
    "## 6. Human communication gaps" + newline + newline + ...
    "The release provides manager-readable question/result/decision/unknown blocks before deep detail. It does not alter original captions, metrics, evidence IDs, or technical wording." + newline + newline + ...
    "## 7. Duplication" + newline + newline + ...
    "The duplication review found necessary local context but no harmful duplication requiring removal. Each topic retains one primary owner." + newline + newline + ...
    "## 8. Report-specific disposition" + newline + newline + ...
    localMarkdownTable(gapMatrix(:,{'ReportID','PatternClassification','RecommendedDisposition','Priority','Notes'})) + newline + newline + ...
    "## 9. Recommended family order" + newline + newline + ...
    "01 → 01A → 01B → 02 → 02A → 03 → 04 → 05 → 06" + newline + newline + ...
    "## 10. End-to-end story readiness" + newline + newline + ...
    "Ready after P0 fixes. The required fix is canonical continuity, not a new technical result." + newline + newline + ...
    "## 11. Canonical release readiness" + newline + newline + ...
    "Ready after P0 fixes. Promotion requires successful source, dependency, handoff, asset, and link validation." + newline + newline + ...
    "## 12. Skill implications" + newline + newline + ...
    "- Observed behavior: evidence-first reports become manager-readable when an explicit question/result/decision/unknown layer precedes detail." + newline + ...
    "- Generalizable lesson: canonical report families need a version manifest, explicit handoff contract, and dependency classes before downstream storyboard generation." + newline + ...
    "- Proposed skill change: future evidence-to-manager workflows should require a family manifest and handoff audit before presentation generation." + newline + ...
    "- Validation still needed: apply the method to another independent technical-report family before skill adoption." + newline + newline + ...
    "## 13. Prioritized action plan" + newline + newline + ...
    "- P0: generate and validate the canonical nine-report release with explicit handoffs." + newline + ...
    "- P1: obtain field qualification evidence; use the release as source for any future storyboard re-audit." + newline + ...
    "- P2: recover unavailable original visuals only if they become decision-relevant." + newline + ...
    "- P3: apply source-report manager-first augmentations only when separately authorized." + newline + newline + ...
    "Audit counts: " + string(height(gapMatrix)) + " reports, " + string(height(handoffs)) + ...
    " handoffs, " + string(height(visuals)) + " visual decisions, and " + ...
    string(height(codeNavigation)) + " code-navigation records.";
localWriteText(path,text);
end

function localWriteGapReviewAudit(path,reportRoot,reports,sourceHashes,visuals,codeNavigation)
reportList = "- `" + string({reports.Filename}) + "`" + newline;
missingVisuals = visuals.MissingVisual(visuals.MissingVisual ~= "");
missingText = "- " + missingVisuals + newline;
missingCode = codeNavigation.EngineeringTopic(codeNavigation.ExecutionStatus ~= "Inspected only");
codeText = "- " + missingCode + " — referenced only" + newline;
text = "# Report Family Gap Review Audit" + newline + newline + ...
    "## Files reviewed" + newline + newline + strjoin(reportList,"") + newline + ...
    "## Versions and source baseline" + newline + newline + ...
    localMarkdownTable(sourceHashes) + newline + newline + ...
    "## Primary sources inspected" + newline + newline + ...
    "- Existing source/figure inventories, report audits, cross-report audit, cross-explainer review, human-story audit, storyboard audit, and report HTML source." + newline + ...
    "- Linked code/navigation targets were existence-checked; code execution was not performed." + newline + newline + ...
    "## Inaccessible or unrecovered assets" + newline + newline + strjoin(missingText,"") + newline + ...
    "## Code-execution limitations" + newline + newline + strjoin(codeText,"") + newline + ...
    "## Confidence" + newline + newline + ...
    "All P0/P1 recommendations are high confidence because they concern report-family continuity, source mapping, retained report boundaries, and existence-checked dependencies. No P0 recommendation relies on a new technical inference." + newline + newline + ...
    "## Final status" + newline + newline + ...
    "READY WITH KNOWN GAPS" + newline + newline + ...
    "The audit supports release-local stabilization. It does not authorize changes to source reports, technical conclusions, MATLAB analysis, PowerPoint, or field operation.";
localWriteText(path,text);
end

function copyInfo = localCreateReleaseCopies(folders,reportRoot,flightTestRoot,reports,sourceHashes,audit)
copyInfo = struct();
copyInfo.Companions = strings(0,1);
copyInfo.Assets = strings(0,1);
copyInfo.ExternalDependencies = strings(0,1);

for index = 1:numel(reports)
    report = reports(index);
    sourcePath = fullfile(reportRoot,report.Filename);
    content = string(fileread(sourcePath));

    [content,copyInfo] = localCopyCompanionDependencies( ...
        content,reportRoot,folders,copyInfo);
    [content,copyInfo] = localCopyAssetDependencies( ...
        content,reportRoot,folders,copyInfo);
    [content,copyInfo] = localNormalizeRelativeEvidenceLinks( ...
        content,reportRoot,copyInfo,reports);
    content = localRewriteCanonicalReportLinks(content,reports);
    content = localRewriteSiteSectionLinks(content);
    content = localInjectReleaseBlock(content,report,reports,sourcePath);

    destination = fullfile(folders.Reports,report.Filename);
    localWriteText(destination,content);
end

localCopyKnownHandoffCompanions(reportRoot,folders.Companions);
localWriteContentStabilizationLog(folders.Metadata,reports,audit);

copyInfo.Companions = unique(copyInfo.Companions);
copyInfo.Assets = unique(copyInfo.Assets);
copyInfo.ExternalDependencies = unique(copyInfo.ExternalDependencies);
copyInfo.SourceHashes = sourceHashes;
copyInfo.FlightTestRoot = flightTestRoot;
end

function [content,copyInfo] = localCopyCompanionDependencies(content,reportRoot,folders,copyInfo)
links = localExtractLinks(content,"href");
for index = 1:numel(links)
    link = links(index);
    if localIsExternalOrFragment(link) || endsWith(lower(link),".html")
        continue;
    end
    decoded = string(urldecode(char(localStripFragment(link))));
    sourcePath = fullfile(reportRoot,decoded);
    [~,name,extension] = fileparts(sourcePath);
    if ~isfile(sourcePath) || ~ismember(lower(extension), ...
            [".csv",".md",".yaml",".yml",".json",".txt"])
        continue;
    end
    destinationName = string(name) + string(extension);
    destinationPath = fullfile(folders.Companions,destinationName);
    if ~isfile(destinationPath)
        copyfile(sourcePath,destinationPath);
    end
    content = replace(content,link,"../companions/" + destinationName);
    copyInfo.Companions(end+1,1) = destinationName; %#ok<AGROW>
end
end

function [content,copyInfo] = localCopyAssetDependencies(content,reportRoot,folders,copyInfo)
sources = localExtractLinks(content,"src");
for index = 1:numel(sources)
    sourceLink = sources(index);
    if startsWith(sourceLink,"data:") || startsWith(sourceLink,"http") || startsWith(sourceLink,"file:")
        if startsWith(sourceLink,"file:")
            copyInfo.ExternalDependencies(end+1,1) = sourceLink; %#ok<AGROW>
        end
        continue;
    end
    decoded = string(urldecode(char(localStripFragment(sourceLink))));
    sourcePath = fullfile(reportRoot,decoded);
    if ~isfile(sourcePath)
        continue;
    end

    if startsWith(sourceLink,"../HardwarePhotos/")
        destinationFolder = fullfile(folders.Assets,"HardwarePhotos");
        localEnsureFolder(destinationFolder);
        [~,name,extension] = fileparts(sourcePath);
        destinationName = string(name) + string(extension);
        copyfile(sourcePath,fullfile(destinationFolder,destinationName));
        content = replace(content,sourceLink, ...
            "../assets/HardwarePhotos/" + localUrlEncodeFilename(destinationName));
        copyInfo.Assets(end+1,1) = "HardwarePhotos/" + destinationName; %#ok<AGROW>
    elseif contains(sourceLink,"_assets/")
        sourceFolderName = extractBefore(sourceLink,"/");
        sourceFolder = fullfile(reportRoot,string(urldecode(char(sourceFolderName))));
        destinationFolder = fullfile(folders.Assets,sourceFolderName);
        if ~isfolder(destinationFolder)
            copyfile(sourceFolder,destinationFolder);
        end
        content = replace(content,sourceFolderName + "/", ...
            "../assets/" + sourceFolderName + "/");
        copyInfo.Assets(end+1,1) = sourceFolderName; %#ok<AGROW>
    else
        destinationFolder = fullfile(folders.Assets,"misc");
        localEnsureFolder(destinationFolder);
        [~,name,extension] = fileparts(sourcePath);
        destinationName = string(name) + string(extension);
        copyfile(sourcePath,fullfile(destinationFolder,destinationName));
        content = replace(content,sourceLink, ...
            "../assets/misc/" + localUrlEncodeFilename(destinationName));
        copyInfo.Assets(end+1,1) = "misc/" + destinationName; %#ok<AGROW>
    end
end
end

function [content,copyInfo] = localNormalizeRelativeEvidenceLinks(content,reportRoot,copyInfo,reports)
links = localExtractLinks(content,"href");
for index = 1:numel(links)
    link = links(index);
    if localIsExternalOrFragment(link) || startsWith(link,"../companions/") || ...
            localIsFamilyReportReference(link,reports)
        continue;
    end
    decoded = string(urldecode(char(localStripFragment(link))));
    sourcePath = fullfile(reportRoot,decoded);
    if isfile(sourcePath) || isfolder(sourcePath)
        externalUri = localFileUri(sourcePath);
        fragment = extractAfter(link,"#");
        if strlength(fragment) > 0
            externalUri = externalUri + "#" + fragment;
        end
        content = replace(content,link,externalUri);
        copyInfo.ExternalDependencies(end+1,1) = externalUri; %#ok<AGROW>
    end
end
end

function tf = localIsFamilyReportReference(link,reports)
filename = string(localStripFragment(link));
canonical = string({reports.Filename});
legacy = [ ...
    "01_NorthStarAndMotivation.html", ...
    "02_HardwareAndCollection.html", ...
    "02_HardwareAndCollection_V2.html", ...
    "02_HardwareAndCollection_V3.html", ...
    "02_HardwareAndCollection_V4.html", ...
    "04_MitigationAndMapRateRecovery.html", ...
    "06_StatusAndFutureWork.html", ...
    "06_StatusAndFutureWork_V2.html"];
tf = ismember(filename,[canonical,legacy]);
end

function content = localRewriteCanonicalReportLinks(content,reports)
legacy = [ ...
    "01_NorthStarAndMotivation.html", ...
    "02_HardwareAndCollection.html", ...
    "02_HardwareAndCollection_V2.html", ...
    "02_HardwareAndCollection_V3.html", ...
    "02_HardwareAndCollection_V4.html", ...
    "04_MitigationAndMapRateRecovery.html", ...
    "06_StatusAndFutureWork.html", ...
    "06_StatusAndFutureWork_V2.html"];
canonical = [ ...
    reports(1).Filename, ...
    reports(4).Filename, ...
    reports(4).Filename, ...
    reports(4).Filename, ...
    reports(4).Filename, ...
    reports(7).Filename, ...
    reports(9).Filename, ...
    reports(9).Filename];
for index = 1:numel(legacy)
    content = replace(content,legacy(index),canonical(index));
end
end

function content = localRewriteSiteSectionLinks(content)
% Family reports may link to site sections outside the family. Those pages are not part
% of a release package, so release copies link to them on the public reporting site.
siteRoot = "https://pwilliammat.github.io/flightTest/";
sections = ["system","diagnostics","explainers","audits","storyboards"];
for index = 1:numel(sections)
    content = replace(content,"href=""../" + sections(index) + "/", ...
        "href=""" + siteRoot + sections(index) + "/");
end
end

function content = localInjectReleaseBlock(content,report,reports,sourcePath)
if contains(content,"data-tsf-release-navigation")
    error("TechnicalSummaryFamily:DuplicateNavigation", ...
        "Source report unexpectedly contains release navigation: %s",report.Filename);
end

previousLink = "—";
if strlength(string(report.Predecessor)) > 0
    previousLink = localReportFilename(reports,report.Predecessor);
end
nextLink = "—";
if strlength(string(report.Successor)) > 0
    nextLink = localReportFilename(reports,report.Successor);
end
sourceUri = localFileUri(sourcePath);
position = find(string({reports.Id}) == string(report.Id),1);
nav = "<style id=""tsf-release-style"">" + ...
    ".tsf-nav{box-sizing:border-box;width:100%;max-width:100%;overflow-x:hidden;overflow-wrap:anywhere;white-space:normal;font:14px/1.4 Segoe UI,Arial,sans-serif;margin:0 0 1rem;padding:.75rem 1rem;border:1px solid #8fb7d8;background:#edf6fc;color:#102a43}" + ...
    ".tsf-nav *{box-sizing:border-box;max-width:100%;white-space:normal}.tsf-nav a{color:#075caa;font-weight:700}.tsf-nav__row{display:flex;gap:.75rem;flex-wrap:wrap;align-items:center;min-width:0}.tsf-nav__position{flex:0 1 auto}.tsf-nav__question{flex:1 1 18rem;min-width:0;overflow-wrap:anywhere}.tsf-nav__links{display:flex;gap:.45rem;flex:1 1 13rem;flex-wrap:wrap;align-items:center;min-width:0}.tsf-nav__source-row{display:block;margin-top:.4rem;overflow-wrap:anywhere}.tsf-nav__meta{margin-top:.55rem;color:#334e68;overflow-wrap:anywhere}.tsf-nav__boundary{margin-top:.55rem;padding:.45rem .65rem;border-left:4px solid #9a5b00;background:#fff7e6}.tsf-nav__sequence{font-size:.9em;color:#526176;overflow-wrap:anywhere}</style>" + ...
    "<nav class=""tsf-nav"" id=""tsf-navigation-" + report.Id + """ data-tsf-release-navigation aria-label=""Technical Summary Family navigation"">" + ...
    "<div class=""tsf-nav__row""><strong class=""tsf-nav__position"">Technical Summary Family " + string(position) + " of " + string(numel(reports)) + ":</strong>" + ...
    "<span class=""tsf-nav__question"">" + localHtmlEscape(report.Id + " — " + report.Question) + "</span>" + ...
    "<span class=""tsf-nav__links""><a href=""../index.html"">Family index</a>" + ...
    localNavLink(previousLink,"Previous") + localNavLink(nextLink,"Next") + ...
    "</span></div><div class=""tsf-nav__source-row""><a href=""" + sourceUri + """>Unchanged source report</a></div>" + ...
    "<div class=""tsf-nav__meta""><b>Upstream handoff:</b> " + ...
    localHtmlEscape(localHandoffDescription(report,reports,true)) + "<br><b>Downstream handoff:</b> " + ...
    localHtmlEscape(localHandoffDescription(report,reports,false)) + "</div>" + ...
    "<div class=""tsf-nav__boundary""><b>Scope boundary:</b> " + ...
    localHtmlEscape(report.ClaimBoundary) + "</div>" + ...
    "<div class=""tsf-nav__sequence"">Canonical sequence: 01 → 01A → 01B → 02 → 02A → 03 → 04 → 05 → 06</div></nav>";
bodyMatch = regexp(content,'(?i)<body[^>]*>','match','once');
if isempty(bodyMatch)
    error("TechnicalSummaryFamily:MissingBody", ...
        "Cannot inject release navigation without body tag: %s",report.Filename);
end
content = replace(content,string(bodyMatch),string(bodyMatch) + nav);
end

function link = localNavLink(filename,label)
if filename == "—"
    link = "<span>" + label + ": —</span>";
else
    link = "<a href=""" + filename + """>" + label + "</a>";
end
end

function description = localHandoffDescription(report,reports,isUpstream)
if isUpstream
    if strlength(string(report.Predecessor)) == 0
        description = "Starts the program narrative with a measurement-first North Star.";
    else
        predecessor = reports(string({reports.Id}) == string(report.Predecessor));
        description = "Consumes " + predecessor.Id + " output: " + predecessor.Decision;
    end
else
    if strlength(string(report.Successor)) == 0
        description = "Ends the current family with decision-controlled next evidence actions.";
    else
        successor = reports(string({reports.Id}) == string(report.Successor));
        description = "Provides " + report.Id + " output to " + successor.Id + ": " + report.Decision;
    end
end
end

function filename = localReportFilename(reports,id)
filename = string(reports(string({reports.Id}) == string(id)).Filename);
end

function localCopyKnownHandoffCompanions(reportRoot,companionRoot)
names = [ ...
    "cross_explainer_review.md", ...
    "report_family_upgrade_audit.md", ...
    "cross_report_audit.md", ...
    "human_story_audit.md", ...
    "final_polish_audit.md", ...
    "01_NorthStarAndMotivation_source_inventory.csv", ...
    "01_NorthStarAndMotivation_figure_inventory.csv", ...
    "01A_IlluminatorSelection_V4_source_inventory.csv", ...
    "01A_IlluminatorSelection_V4_figure_inventory.csv", ...
    "01A_IlluminatorSelection_V4_audit.md", ...
    "01B_ReceiveChainDesign_V2_source_inventory.csv", ...
    "01B_ReceiveChainDesign_V2_figure_inventory.csv", ...
    "01B_ReceiveChainDesign_V2_audit.md", ...
    "02_HardwareAndCollection_source_inventory.csv", ...
    "02_HardwareAndCollection_figure_inventory.csv", ...
    "02_HardwareAndCollection_V4_evidence_register.csv", ...
    "02A_source_inventory.csv", ...
    "02A_figure_inventory.csv", ...
    "02A_audit.md", ...
    "04_MitigationAndMapRateRecovery_source_inventory.csv", ...
    "04_MitigationAndMapRateRecovery_figure_inventory.csv", ...
    "06_StatusAndFutureWork_source_inventory.csv", ...
    "06_StatusAndFutureWork_figure_inventory.csv", ...
    "human_story_source_inventory.csv"];
for index = 1:numel(names)
    sourcePath = fullfile(reportRoot,names(index));
    if isfile(sourcePath)
        copyfile(sourcePath,fullfile(companionRoot,names(index)));
    end
end
end

function localWriteContentStabilizationLog(metadataRoot,reports,audit)
count = numel(reports);
reportId = string({reports.Id})';
sourceVersion = string({reports.Filename})';
newVersion = repmat("Release-local copy only",count,1);
gapId = repmat("P0-FAMILY-CONTINUITY",count,1);
priority = repmat("P0",count,1);
changeType = repmat("Canonical cross-links and manager-first handoff block",count,1);
description = repmat("Injected release-only previous/next/index navigation, upstream/downstream handoff, and scope boundary.",count,1);
sourceEvidence = repmat("Phase 0 handoff catalog and existing report evidence.",count,1);
valueChanged = repmat("No",count,1);
textChanged = repmat("Release-only navigation text; source report unchanged.",count,1);
figureAdded = repmat("No",count,1);
linkAdded = repmat("Yes",count,1);
boundary = repmat("Yes",count,1);
auditResult = repmat("Safe targeted augmentation",count,1);
accepted = repmat("Yes",count,1);
notes = string(audit.RecommendedDisposition);
log = table(reportId,sourceVersion,newVersion,gapId,priority,changeType,description, ...
    sourceEvidence,valueChanged,textChanged,figureAdded,linkAdded,boundary, ...
    auditResult,accepted,notes, ...
    'VariableNames',{ ...
    'ReportID','SourceVersion','NewVersion','GapID','Priority','ChangeType', ...
    'ChangeDescription','SourceEvidence','ValueChanged','TextChanged', ...
    'FigureAdded','LinkAdded','BoundaryPreserved','AuditResult', ...
    'AcceptedForRelease','Notes'});
writetable(log,fullfile(metadataRoot,"content_stabilization_log.csv"));
end

function localWriteCanonicalMetadata(folders,reportRoot,releaseRoot,releaseId,immutableRoot,priorReleaseId,reports,sourceHashes,sourceIntegrity,audit,copyInfo)
reportCount = numel(reports);
catalogId = "CAT-" + string({reports.Id})';
reportId = string({reports.Id})';
question = string({reports.Question})';
result = string({reports.StrongestResult})';
metric = string({reports.Metric})';
why = repmat( ...
    "The result provides the engineering input or boundary required by the next report.", ...
    reportCount,1);
decision = string({reports.Decision})';
unknown = string({reports.Unknown})';
evidenceId = repmat("Report-level evidence; see bundled source inventory.", ...
    reportCount,1);
evidenceClass = ["Conceptual boundary";"Historical model";"Historical model"; ...
    "Infrastructure";"Controlled synthetic";"Process/gate";"Diagnostic recovery"; ...
    "Controlled diagnostic";"Status/decision"];
currentHistorical = ["Current framing";"Historical";"Historical";"Current infrastructure"; ...
    "Mixed";"Current process";"Current diagnostic";"Current diagnostic";"Current status"];
source = sourceHashes.SourcePath;
figure = ["Report 01 executive/gate visuals";"01A retained maps";"01B retained RF visuals"; ...
    "02 deployment/package visuals";"02A truth/placement visuals";"03 gate visual"; ...
    "04 recovery visuals";"05 atlas visuals";"06 blocker/action visuals"];
releaseAsset = "../reports/" + string({reports.Filename})';
code = string({reports.CodePath})';
mainStory = ["Yes";"Yes";"Yes";"Yes";"Yes";"Yes";"Yes";"Yes";"Yes"];
technical = repmat("Yes",reportCount,1);
boundary = string({reports.ClaimBoundary})';
discrepancy = audit.ContradictionOrDiscrepancy;
notes = repmat("Canonical release summary row; detailed evidence remains report-owned.", ...
    reportCount,1);
catalog = table(catalogId,reportId,question,result,metric,why,decision,unknown, ...
    evidenceId,evidenceClass,currentHistorical,source,figure,releaseAsset,code, ...
    mainStory,technical,boundary,discrepancy,notes, ...
    'VariableNames',{ ...
    'CatalogID','ReportID','EngineeringQuestion','Result','ImportantMetric', ...
    'WhyItMatters','EngineeringDecision','StillUnknown','EvidenceID', ...
    'EvidenceClass','CurrentOrHistorical','OriginalSource','OriginalFigure', ...
    'ReleaseAsset','CodeEntryPoint','MainStorySuitability', ...
    'TechnicalReferenceSuitability','ClaimBoundary','KnownDiscrepancy','Notes'});
writetable(catalog,fullfile(folders.Metadata,"family_evidence_catalog.csv"));
writetable(sourceIntegrity,fullfile(folders.Metadata,"source_integrity_baseline.csv"));

knownGaps = "# Family Known Gaps" + newline + newline + ...
    "## Accepted P1 through P3 gaps" + newline + newline + ...
    "- Field channel-role, lock/drop, reference-path, and collection-suitability qualification remains unavailable." + newline + ...
    "- Historical 01A/01B frequency, ERP, filter-loss, and target-level differences remain visible and unreconciled." + newline + ...
    "- The original Apple Hill 3-D ray-path capture and raw paired before/after injection visual were not recovered." + newline + ...
    "- The family contains controlled synthetic evidence, not live-aircraft detection, operational Pd/Pfa, tracking, or localization validation." + newline + newline + ...
    "## Added 2026-09-26 (cue-tasking update)" + newline + ...
    "" + newline + ...
    "- The ADS-B Pi keeps time from internet NTP, which is accepted, with a proposed 0.1 s host-to-host tolerance; GPS/PPS lock is a hardware to-do. Before 2026-09-25 21:07 UTC the Pi was measured 14.9 s slow, so Pi-timed ADS-B truth from earlier collections carries an unknown offset until it is re-checked (Report 02 V5 TIME-001; Report 06 V3 STAT-010)." + newline + ...
    "- The ADS-B cue interface is verified as a message interface only. The Resource Manager does not schedule collections, and no collection has been made from a cue (Report 06 V3 STAT-009, STAT-012)." + newline + ...
    "- Cues choose when and with which tower to collect, and the Tracker may use cues to help association. The truth-separation rule that labels cued collections and cue-aided products is proposed (CR-9, System Engineering section) and not yet accepted; until it is, no cued result counts as independent detection evidence (Report 06 V3 STAT-013)." + newline + ...
    "- Predicted SNR in cues is a modeled, pre-integration ranking estimate and has not been reconciled with the Report 01A/01B models." + newline + ...
    "- CueListener and the DTV level-check scripts stay on branch `feature/adsb-cue-listener` pending review; the Cue Tasker code is on an ADSB-remoter feature branch." + newline + ...
    "- The system requirements baseline is a draft (CR-10); no requirement is accepted." + newline + newline + ...
    "## Workstation dependencies" + newline + newline + ...
    "- Local file evidence links were existence-checked at build time and are nonportable by design." + newline + ...
    "- External web links are preserved but not network-validated." + newline + newline + ...
    "## Release policy" + newline + newline + ...
    "No unresolved P0 item is hidden. The former P0 family-navigation gap is resolved by release-local navigation, explicit handoffs, canonical version mapping, and validation. Reports 02 V5 and 06 V3 replace 02 V4 and 06 V2 as the current versions; the superseded files stay in `reports/` unchanged because accepted reports link to them.";
localWriteText(fullfile(folders.Metadata,"family_known_gaps.md"),knownGaps);

manifest = struct();
manifest.schema_version = "1.0";
manifest.release_id = char(releaseId);
manifest.release_timestamp = char(datetime("now","Format","yyyy-MM-dd'T'HH:mm:ssXXX"));
manifest.prior_release_id = char(priorReleaseId);
manifest.source_root = char(reportRoot);
manifest.release_root = char(releaseRoot);
manifest.immutable_release_root = char(immutableRoot);
manifest.promotion_status = "VALIDATED_STAGING_CANDIDATE";
manifest.canonical_order = {reports.Id};
manifest.content_audit_status = "READY WITH KNOWN GAPS";
manifest.canonical_release_status = "READY AFTER P0 RELEASE-LOCAL FIXES";
manifest.reports = localManifestReports(reports,sourceHashes,folders.Reports);
manifest.source_report_hashes = table2struct(sourceHashes);
manifest.source_asset_hashes = table2struct(sourceIntegrity( ...
    sourceIntegrity.Kind == "Asset",:));
manifest.source_powerpoint_hashes = table2struct(sourceIntegrity( ...
    sourceIntegrity.Kind == "PowerPoint",:));
manifest.bundled_dependencies = cellstr(copyInfo.Companions);
manifest.bundled_assets = cellstr(copyInfo.Assets);
manifest.local_workstation_dependencies = cellstr(copyInfo.ExternalDependencies);
manifest.known_gaps = { ...
    "Field qualification remains unresolved.", ...
    "Historical configuration discrepancies are retained.", ...
    "Two original visual recoveries remain unavailable.", ...
    "No operational detection, tracking, or localization claim is established.", ...
    "The ADS-B Pi time source is NTP-disciplined (accepted); GPS/PPS lock is a hardware to-do, and Pi-timed ADS-B truth before 2026-09-25 21:07 UTC carries an unknown clock offset.", ...
    "ADS-B cues are verified as a message interface only; no collection has been scheduled from a cue.", ...
    "The truth-separation rule for cued collections and cue-aided association is proposed (CR-9), not accepted."};
localWriteText(fullfile(folders.Metadata,"family_manifest.json"), ...
    jsonencode(manifest,"PrettyPrint",true));
localWriteReleaseIndex(folders.Root,releaseId,reports);
end

function localWriteReleaseIndex(root,releaseId,reports)
cards = strings(numel(reports),1);
for index = 1:numel(reports)
    report = reports(index);
    cards(index) = "<article class=""tsf-index-card"">" + ...
        "<p class=""tsf-index-kicker"">Report " + report.Id + "</p>" + ...
        "<h2><a href=""reports/" + report.Filename + """>" + ...
        localHtmlEscape(report.Question) + "</a></h2>" + ...
        "<p><b>Result:</b> " + localHtmlEscape(report.StrongestResult) + "</p>" + ...
        "<p><b>Metric:</b> " + localHtmlEscape(report.Metric) + "</p>" + ...
        "<p><b>Decision:</b> " + localHtmlEscape(report.Decision) + "</p>" + ...
        "<p><b>Boundary:</b> " + localHtmlEscape(report.ClaimBoundary) + "</p></article>";
end
html = "<!doctype html><html lang=""en""><head><meta charset=""utf-8"">" + ...
    "<meta name=""viewport"" content=""width=device-width, initial-scale=1"">" + ...
    "<title>Passive HDTV Aircraft Localization — Technical Summary Family</title>" + ...
    "<style>body{max-width:1200px;margin:2rem auto;padding:0 1rem;font:16px/1.5 Segoe UI,Arial,sans-serif;color:#172033;background:#f8fafc}" + ...
    "h1,h2{line-height:1.2}.tsf-index-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:1rem}.tsf-index-card{background:#fff;border:1px solid #cbd5e1;border-top:5px solid #0f4c81;padding:1rem}.tsf-index-card p{margin:.65rem 0}.tsf-index-kicker{font-weight:700;color:#0f4c81;margin:0}.tsf-index-links{display:flex;flex-wrap:wrap;gap:.8rem;padding:1rem;background:#e6f2fb;border-left:5px solid #0f4c81}a{color:#075caa;font-weight:650}@media(max-width:640px){body{margin:1rem auto}.tsf-index-links{display:block}.tsf-index-links a{display:block;margin:.4rem 0}}</style></head><body>" + ...
    "<h1>Passive HDTV Aircraft Localization — Technical Summary Family</h1>" + ...
    "<p>Generated canonical release <b>" + releaseId + "</b>. Read the evidence-led nine-report family in order; reports retain their original technical detail and receive release-only continuity navigation.</p>" + ...
    "<div class=""tsf-index-links""><a href=""metadata/report_family_story_spine.html"">Engineering story spine</a><a href=""metadata/family_manifest.json"">Release manifest</a><a href=""metadata/report_family_gap_review.md"">Content audit</a><a href=""metadata/family_known_gaps.md"">Known gaps</a><a href=""validation/release_validation.md"">Validation</a></div>" + ...
    "<h2>Recommended reading paths</h2><p><b>Manager:</b> 01 → 01A → 01B → 02 → 02A → 03 → 04 → 05 → 06. <b>Hardware and collection:</b> 01A → 01B → 02. <b>Synthetic validation:</b> 02 → 02A → 03 → 05. <b>Map recovery:</b> 03 → 04 → 05. <b>Current status:</b> 05 → 06.</p>" + ...
    "<h2>Engineering story map</h2><div class=""tsf-index-grid"">" + strjoin(cards,newline) + ...
    "</div><h2>Cross-report qualifications</h2><p>Historical illuminator/RF configuration differences remain unreconciled; collection infrastructure is not field qualification; controlled synthetic recovery is not live-aircraft detection, tracking, or localization; R4 bounded success remains distinct from formal R5A failure.</p></body></html>";
localWriteText(fullfile(root,"index.html"),html);
end

function manifestReports = localManifestReports(reports,sourceHashes,reportsRoot)
manifestReports = repmat(struct(),numel(reports),1);
for index = 1:numel(reports)
    manifestReports(index).report_id = char(reports(index).Id);
    manifestReports(index).latest_version = char(reports(index).Filename);
    manifestReports(index).accepted_version = char(reports(index).Filename);
    manifestReports(index).canonical_filename = char(reports(index).Filename);
    manifestReports(index).source_hash = char(sourceHashes.SourceSHA256(index));
    manifestReports(index).release_hash = localSha256(fullfile(reportsRoot,reports(index).Filename));
    manifestReports(index).content_status = char(reports(index).Pattern);
    manifestReports(index).primary_question = char(reports(index).Question);
    manifestReports(index).strongest_result = char(reports(index).StrongestResult);
    manifestReports(index).engineering_decision = char(reports(index).Decision);
    manifestReports(index).upstream_report = char(reports(index).Predecessor);
    manifestReports(index).downstream_report = char(reports(index).Successor);
    manifestReports(index).claim_boundary = char(reports(index).ClaimBoundary);
end
end

function priorId = localPriorReleaseId(releaseHistoryRoot)
priorId = "";
if ~isfolder(releaseHistoryRoot)
    return;
end
listing = dir(releaseHistoryRoot);
names = string({listing([listing.isdir]).name});
names = names(~ismember(names,[".",".."]));
isImmutableRelease = ~cellfun(@isempty, ...
    regexp(cellstr(names),'^\d{8}_\d{6}$','once'));
names = names(isImmutableRelease);
if ~isempty(names)
    names = sort(names);
    priorId = names(end);
end
end

function localWriteReleaseReadme(root,releaseId)
text = "# Technical Summary Family Canonical Release" + newline + newline + ...
    "Release ID: `" + releaseId + "`" + newline + newline + ...
    "This is a generated, validated canonical release. It is the required input for future end-to-end human-story generation, storyboard generation, manager-presentation generation, and evidence-to-manager skill work." + newline + newline + ...
    "## Rules" + newline + newline + ...
    "- Do not edit report copies in this release directly." + newline + ...
    "- Update an accepted source report outside this folder, then rerun `buildTechnicalSummaryFamily`." + newline + ...
    "- Use `metadata/family_manifest.json` for the canonical version mapping and ownership contract." + newline + ...
    "- Start navigation at `index.html`; report copies live in `reports/`." + newline + ...
    "- Local `file:///` evidence links were validated on the originating workstation and may be nonportable." + newline + ...
    "- Source reports, source assets, source catalogs, storyboards, and PowerPoint files remain outside this generated release." + newline + newline + ...
    "Validation records are in `validation/`; known limitations are in `metadata/family_known_gaps.md`.";
localWriteText(fullfile(root,"README.md"),text);
end

function localPromoteImmutableRelease(immutableRoot,releaseRoot,releaseHistoryRoot)
nextRoot = releaseRoot + "_next";
if isfolder(nextRoot)
    error("TechnicalSummaryFamily:PendingPromotionExists", ...
        "Refusing to replace a retained pending promotion folder: %s",nextRoot);
end
copyfile(immutableRoot,nextRoot);
if isfolder(releaseRoot)
    legacyId = "superseded_current_" + string(datetime("now","Format","yyyyMMdd_HHmmss"));
    legacyRoot = fullfile(releaseHistoryRoot,legacyId);
    movefile(releaseRoot,legacyRoot,"f");
end
movefile(nextRoot,releaseRoot,"f");
end

function localRecordPromotion(immutableRoot,stageRoot,releaseRoot,priorReleaseId)
manifestPath = fullfile(immutableRoot,"metadata","family_manifest.json");
manifest = jsondecode(fileread(manifestPath));
manifest.prior_release_id = char(priorReleaseId);
manifest.immutable_release_root = char(immutableRoot);
manifest.mutable_current_release_root = char(releaseRoot);
manifest.promotion_status = "PROMOTED_AFTER_VALIDATION";
manifest.promotion_timestamp = char(datetime("now","Format","yyyy-MM-dd'T'HH:mm:ssXXX"));
localWriteText(manifestPath,jsonencode(manifest,"PrettyPrint",true));

validationPath = fullfile(immutableRoot,"validation","release_validation.md");
validationText = string(fileread(validationPath));
validationText = replace(validationText, ...
    "Release root: `" + stageRoot + "`", ...
    "Release root: `" + immutableRoot + "`");
promotion = newline + "## Promotion" + newline + newline + ...
    "- Immutable release: `" + immutableRoot + "`" + newline + ...
    "- Mutable current release: `" + releaseRoot + "`" + newline + ...
    "- Prior immutable release ID: `" + priorReleaseId + "`" + newline + ...
    "- Promotion occurred only after the staged validation passed; source hashes were rechecked after promotion." + newline;
localWriteText(validationPath,validationText + promotion);
end

function localAssertSourceIntegrity(sourceIntegrity)
for index = 1:height(sourceIntegrity)
    sourcePath = sourceIntegrity.SourcePath(index);
    if ~isfile(sourcePath)
        error("TechnicalSummaryFamily:SourceMissing", ...
            "Source file disappeared during build: %s",sourcePath);
    end
    actualHash = string(localSha256(sourcePath));
    if actualHash ~= sourceIntegrity.SourceSHA256(index)
        error("TechnicalSummaryFamily:SourceChanged", ...
            "Source report changed during build: %s",sourcePath);
    end
end
end

function links = localExtractLinks(content,attribute)
expression = "(?i)" + attribute + "\s*=\s*[""']([^""']+)[""']";
matches = regexp(content,expression,"tokens");
if isempty(matches)
    links = strings(0,1);
else
    links = string(cellfun(@(item)item{1},matches,'UniformOutput',false));
end
end

function value = localStripFragment(link)
hashIndex = strfind(link,"#");
if isempty(hashIndex)
    value = link;
else
    value = extractBefore(link,hashIndex(1));
end
end

function tf = localIsExternalOrFragment(link)
tf = startsWith(link,"#") || startsWith(link,"http:") || startsWith(link,"https:") || ...
    startsWith(link,"file:") || startsWith(link,"mailto:") || startsWith(link,"javascript:") || ...
    startsWith(link,"data:");
end

function uri = localFileUri(path)
path = string(path);
path = replace(path,"\","/");
path = replace(path," ","%20");
path = replace(path,"+","%2B");
uri = "file:///" + path;
end

function encoded = localUrlEncodeFilename(filename)
encoded = replace(string(filename)," ","%20");
encoded = replace(encoded,"+","%2B");
end

function hash = localSha256(path)
fileId = fopen(path,"r");
if fileId < 0
    error("TechnicalSummaryFamily:HashReadFailure","Cannot read %s",path);
end
cleanup = onCleanup(@()fclose(fileId)); %#ok<NASGU>
digest = java.security.MessageDigest.getInstance("SHA-256");
while true
    [bytes,count] = fread(fileId,1024 * 1024,"*int8");
    if count == 0
        break;
    end
    digest.update(bytes);
end
raw = typecast(digest.digest(),"uint8");
hash = lower(reshape(dec2hex(raw,2).',1,[]));
end

function escaped = localHtmlEscape(text)
escaped = string(text);
escaped = replace(escaped,"&","&amp;");
escaped = replace(escaped,"<","&lt;");
escaped = replace(escaped,">","&gt;");
escaped = replace(escaped,"""","&quot;");
end

function localWriteText(path,text)
fileId = fopen(path,"w","n","UTF-8");
if fileId < 0
    error("TechnicalSummaryFamily:WriteFailure","Cannot write %s",path);
end
cleanup = onCleanup(@()fclose(fileId)); %#ok<NASGU>
fwrite(fileId,char(text),"char");
end

function markdown = localMarkdownTable(tableData)
variables = string(tableData.Properties.VariableNames);
markdown = "| " + strjoin(variables," | ") + " |" + newline;
markdown = markdown + "| " + strjoin(repmat("---",1,numel(variables))," | ") + " |" + newline;
for row = 1:height(tableData)
    values = strings(1,numel(variables));
    for column = 1:numel(variables)
        value = tableData{row,column};
        if iscell(value)
            value = value{1};
        end
        values(column) = replace(string(value),"|","/");
    end
    markdown = markdown + "| " + strjoin(values," | ") + " |" + newline;
end
end

function localWriteFailureMarker(stageRoot,result)
if isfolder(stageRoot) && result.Status == "FAILED"
    marker = fullfile(stageRoot,"BUILD_FAILED.txt");
    if ~isfile(marker)
        localWriteText(marker,"Build failed or was interrupted before promotion." + newline);
    end
end
end

function localWriteBuildFailure(stageRoot,result,exception)
if ~isfolder(stageRoot)
    return;
end
text = "# Technical Summary Family Build Failure" + newline + newline + ...
    "Status: FAILED" + newline + ...
    "Release ID: " + result.ReleaseId + newline + newline + ...
    "## Exception" + newline + newline + ...
    "```text" + newline + string(getReport(exception,"extended","hyperlinks","off")) + newline + "```" + newline + newline + ...
    "The mutable current release was not promoted. The staged output was retained for diagnosis.";
localWriteText(fullfile(stageRoot,"BUILD_FAILED.md"),text);
end
