classdef AugustPassiveRadarPrecheckReplayTest < matlab.unittest.TestCase
    %AUGUSTPASSIVERADARPRECHECKREPLAYTEST Slow replay of August Yagi data.

    properties (SetAccess = private)
        DataRoot
        ProjectRoot
    end

    properties (TestParameter)
        YagiSession = struct( ...
            "session140613", struct( ...
                "Id", "20260827T140613", ...
                "RailRepetitions", 13), ...
            "session141020", struct( ...
                "Id", "20260827T141020", ...
                "RailRepetitions", []), ...
            "session141524", struct( ...
                "Id", "20260827T141524", ...
                "RailRepetitions", []), ...
            "session141921", struct( ...
                "Id", "20260827T141921", ...
                "RailRepetitions", []));
    end

    methods (TestClassSetup)
        function addProjectPaths(testCase)
            testFolder = fileparts(mfilename("fullpath"));
            acquisitionFolder = fileparts(testFolder);
            testCase.ProjectRoot = string(fileparts(acquisitionFolder));
            testCase.DataRoot = string(fullfile( ...
                fileparts(fileparts(testCase.ProjectRoot)), ...
                "yagi-august-data", "SurvYagiCaptures"));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                testCase.ProjectRoot));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                acquisitionFolder));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(testCase.ProjectRoot, "BistaticDataAnalysis")));
        end
    end

    methods (Test, TestTags = {'Integration', 'Slow'})
        function replayYagiSessionPreservesHoldEvidence( ...
                testCase, YagiSession)
            testCase.assumeTrue(isfolder(testCase.DataRoot), ...
                "August capture data are not available.");
            config = localAugustConfig( ...
                fullfile(testCase.DataRoot, YagiSession.Id));

            result = runPassiveRadarHardwarePrecheck(config);
            [minimumSurveillanceHeadroomDB, railRepetitions] = ...
                localHeadroomEvidence(result);
            metadataPass = arrayfun( ...
                @(capture) capture.Checks.Metadata.Pass, result.Captures);

            testCase.verifyEqual(numel(result.Captures), 15);
            testCase.verifyFalse(any(metadataPass));
            testCase.verifyEqual(result.Status, "hold");
            testCase.verifyLessThan(minimumSurveillanceHeadroomDB, 1);
            testCase.verifyEqual( ...
                railRepetitions, YagiSession.RailRepetitions);
        end
    end
end

function config = localAugustConfig(sessionFolder)
config = struct( ...
    "Mode", "offline", ...
    "Source", string(sessionFolder), ...
    "CenterFrequencyHz", 599e6, ...
    "SampleRateHz", 6.144e6, ...
    "LOOffsetHz", 0, ...
    "IlluminatorCenterFrequencyHz", 599e6, ...
    "AntennaPorts", ["RF0:RX2", "RF1:RX2"], ...
    "ChannelRoles", ["surveillance", "reference"], ...
    "GainDB", [28, 28], ...
    "AnalysisDurationS", 1, ...
    "CPIDurationS", 0.5e-3, ...
    "CreatePlots", false);
end

function [minimumHeadroomDB, railRepetitions] = ...
        localHeadroomEvidence(result)
nCaptures = numel(result.Captures);
surveillanceHeadroomDB = nan(nCaptures, 1);
hasSurveillanceRail = false(nCaptures, 1);
for captureIndex = 1:nCaptures
    capture = result.Captures(captureIndex);
    surveillanceChannel = capture.ConfiguredSurveillanceChannel;
    surveillanceHeadroomDB(captureIndex) = ...
        capture.Checks.Headroom.PeakHeadroomDB(surveillanceChannel);
    hasSurveillanceRail(captureIndex) = ...
        capture.Checks.Headroom.ExactRailSampleCount( ...
        surveillanceChannel) > 0;
end

minimumHeadroomDB = min(surveillanceHeadroomDB);
railRepetitions = [result.Captures(hasSurveillanceRail).PartIndex];
end
