InputFreq = 785e6; % Hudson - WUNI
FreqRange = [782 788];
IFBandPass = [50 90]*10^6;
LOVal = InputFreq + mean(IFBandPass);


% Build a cascade (row vector) of RF elements
elements(1) = rfantenna( ...
    'Name','Antenna_DirectHudson', ...
    'Type','Receiver', ...
    'Gain',34, ...
    'Z',75);%, ...
    %'TxEIRP',92.16, ...
    %'PathLoss',226.7
elements(2) = rffilter( ...
    'FilterType','Butterworth', ...
    'ResponseType','Bandpass', ...
    'Implementation','LC Tee', ...
    'FilterOrder',3, ...
    'PassbandFrequency',FreqRange*1e6, ...
    'PassbandAttenuation',1, ...
    'Zin',75, ...
    'Zout',75, ...
    'Name','RFFilter');
elements(3) = amplifier( ...
    Name='RFAmplifier', ...
    Gain=32, ...
    NF=2.5, ...
    OIP3=45, ...
    Zin=75, ...
    Zout=75, ...
    Model='cubic');

elements(4) = modulator( ...
    Name='Demodulator', ...
    Zin=75, ...
    Zout=75, ...
    Model='demod', ...
    LO=LOVal);
elements(5) = rffilter( ...
    'FilterType','Butterworth', ...
    'ResponseType','Bandpass', ...
    'Implementation','LC Tee', ...
    'FilterOrder',3, ...
    'PassbandFrequency',IFBandPass, ...
    'PassbandAttenuation',2.9, ...
    'Zin',75, ...
    'Zout',75, ...
    'Name','IFFilter');
elements(6) = amplifier( ...
    Name='IFAmplifier', ...
    Gain=25, ...
    NF=3, ...
    OIP3=40, ...
    Zin=75, ...
    Zout=75, ...
    Model='cubic');

% Construct an rfbudget object
DirectPathPower = -39.84;
TargetPathPower = -67.37;
b = rfbudget( ...
    Elements=elements, ...
    InputFrequency=InputFreq, ...
    AvailableInputPower=TargetPathPower, ... % Based on Direct Path Calc: "FlightTest_Bistatic_RadarAndCommsAnalysis.mlx"
    SignalBandwidth=6e6, ...
    Solver='Friis', ...
    AutoUpdate=true);
