
%% Revised RF Budget Analysis
% This version adds realistic losses and USRP front-end characteristics
% so you can compare against your original model.

% Assumptions:
% - Antenna gain reduced to 12 dBi (typical Yagi for DTV)
% - Cable loss added (3 dB for ~50 ft RG-6 at 785 MHz)
% - Bias Tee loss added (0.5 dB)
% - USRP front-end gain and NF added (Gain = 20 dB, NF = 6 dB)
% - Bandpass filter and IF stages remain as in original model

%% Input Parameters
InputFreq = 785e6; % Hudson - WUNI
FreqRange = [782 788]; % Passband for RF filter
IFBandPass = [50 90]*1e6; % IF filter range
LOVal = InputFreq + mean(IFBandPass);

% Available input power from target path (same as original)
TargetPathPower = -67.37; % dBm

%% Build revised cascade
elements_rev(1) = rfantenna( ...
    'Name','Antenna_Yagi', ...
    'Type','Receiver', ...
    'Gain',12, ... % Realistic Yagi gain
    'Z',75);

elements_rev(2) = rfdevice( ...
    'Name','CableLoss', ...
    'Gain',-3, ... % Cable loss for ~50 ft RG-6
    'Zin',75, ...
    'Zout',75);

elements_rev(3) = rfdevice( ...
    'Name','BiasTee', ...
    'Gain',-0.5, ... % Bias tee insertion loss
    'Zin',75, ...
    'Zout',75);

elements_rev(4) = rffilter( ...
    'FilterType','Butterworth', ...
    'ResponseType','Bandpass', ...
    'Implementation','LC Tee', ...
    'FilterOrder',3, ...
    'PassbandFrequency',FreqRange*1e6, ...
    'PassbandAttenuation',1, ...
    'Zin',75, ...
    'Zout',75, ...
    'Name','RFFilter');

elements_rev(5) = amplifier( ...
    'Name','LNA', ...
    'Gain',32, ...
    'NF',2.5, ...
    'OIP3',45, ...
    'Zin',75, ...
    'Zout',75, ...
    'Model','cubic');

elements_rev(6) = amplifier( ...
    'Name','USRP_FrontEnd', ...
    'Gain',20, ... % USRP gain
    'NF',6, ...    % USRP NF
    'OIP3',40, ...
    'Zin',75, ...
    'Zout',75, ...
    'Model','cubic');

elements_rev(7) = modulator( ...
    'Name','Demodulator', ...
    'Zin',75, ...
    'Zout',75, ...
    'Model','demod', ...
    'LO',LOVal);

elements_rev(8) = rffilter( ...
    'FilterType','Butterworth', ...
    'ResponseType','Bandpass', ...
    'Implementation','LC Tee', ...
    'FilterOrder',3, ...
    'PassbandFrequency',IFBandPass, ...
    'PassbandAttenuation',2.9, ...
    'Zin',75, ...
    'Zout',75, ...
    'Name','IFFilter');

elements_rev(9) = amplifier( ...
    'Name','IFAmplifier', ...
    'Gain',25, ...
    'NF',3, ...
    'OIP3',40, ...
    'Zin',75, ...
    'Zout',75, ...
    'Model','cubic');

%% Construct RF budget object for revised analysis
b_rev = rfbudget( ...
    Elements=elements_rev, ...
    InputFrequency=InputFreq, ...
    AvailableInputPower=TargetPathPower, ...
    SignalBandwidth=6e6, ...
    Solver='Friis', ...
    AutoUpdate=true);

%% Display results
disp('Revised RF Budget Analysis:');
disp(b_rev);
