function result = helperAssessPrecheckMetadata(capture, sourceInfo, expected)
%HELPERASSESSPRECHECKMETADATA Validate capture identity and RF settings.
%
% File-header values are treated as measured evidence. Expected values are
% supplied by the collection configuration and are checked independently.

arguments
    capture (1, 1) struct
    sourceInfo (1, 1) struct
    expected (1, 1) struct
end

metadata = capture.Metadata;
requiredFields = ["LOOffset", "RecordingUTC", "SessionID", ...
    "Repetition", "Antenna1", "Antenna2", ...
    "Channel1Role", "Channel2Role", "GainDB"];
missingFields = requiredFields(~arrayfun(@(name) ...
    localHasValue(metadata, name), requiredFields));

actualLOOffsetHz = localNumericField(metadata, "LOOffset");
actualRecordingUTC = localNumericField(metadata, "RecordingUTC");
actualSessionID = localTextField(metadata, "SessionID");
actualRepetition = localNumericField(metadata, "Repetition");
sampleRateErrorHz = abs(capture.SampleRateHz - expected.SampleRateHz);
centerFrequencyErrorHz = abs(capture.CenterFrequencyHz - ...
    expected.CenterFrequencyHz);
loOffsetErrorHz = abs(actualLOOffsetHz - expected.LOOffsetHz);

sampleRatePass = isfinite(capture.SampleRateHz) && ...
    sampleRateErrorHz <= expected.FrequencyToleranceHz;
centerFrequencyPass = isfinite(capture.CenterFrequencyHz) && ...
    centerFrequencyErrorHz <= expected.FrequencyToleranceHz;
loOffsetPass = isfinite(actualLOOffsetHz) && ...
    loOffsetErrorHz <= expected.FrequencyToleranceHz;
channelHeaderPass = capture.NumberOfChannels == 2;
requiredFieldsPass = isempty(missingFields);
fieldValuesPass = isfinite(actualRecordingUTC) && ...
    strlength(actualSessionID) > 0 && ...
    isfinite(actualRepetition) && actualRepetition >= 1 && ...
    mod(actualRepetition, 1) == 0;

actualAntennaPorts = [ ...
    localTextField(metadata, "Antenna1"), ...
    localTextField(metadata, "Antenna2")];
actualChannelRoles = lower([ ...
    localTextField(metadata, "Channel1Role"), ...
    localTextField(metadata, "Channel2Role")]);
actualGainDB = localNumericVectorField(metadata, "GainDB", 2);
antennaPortsPass = all(actualAntennaPorts == expected.AntennaPorts);
channelRolesPass = all(actualChannelRoles == expected.ChannelRoles);
gainPass = all(isfinite(actualGainDB)) && ...
    all(abs(actualGainDB - expected.GainDB) <= 1e-9);

sessionMatchPass = true;
if strlength(sourceInfo.SessionID) > 0
    sessionMatchPass = actualSessionID == sourceInfo.SessionID;
end

repetitionMatchPass = true;
if sourceInfo.PartIndex > 0
    repetitionMatchPass = actualRepetition == sourceInfo.PartIndex;
end

[manifestPass, manifestFailures] = localAssessManifest( ...
    sourceInfo, capture, expected);

pass = requiredFieldsPass && fieldValuesPass && ...
    sampleRatePass && centerFrequencyPass && ...
    loOffsetPass && channelHeaderPass && sessionMatchPass && ...
    repetitionMatchPass && antennaPortsPass && channelRolesPass && ...
    gainPass && manifestPass;

failures = strings(0, 1);
if ~requiredFieldsPass
    failures(end + 1) = "Missing baseband metadata: " + ...
        strjoin(missingFields, ", ") + ".";
end
if requiredFieldsPass && ~fieldValuesPass
    failures(end + 1) = ...
        "RecordingUTC, SessionID, or Repetition metadata is malformed.";
end
if ~sampleRatePass
    failures(end + 1) = sprintf( ...
        "Sample rate %.12g Hz does not match expected %.12g Hz.", ...
        capture.SampleRateHz, expected.SampleRateHz);
end
if ~centerFrequencyPass
    failures(end + 1) = sprintf( ...
        "Center frequency %.12g Hz does not match expected %.12g Hz.", ...
        capture.CenterFrequencyHz, expected.CenterFrequencyHz);
end
if ~loOffsetPass
    failures(end + 1) = sprintf( ...
        "LO offset %.12g Hz does not match expected %.12g Hz.", ...
        actualLOOffsetHz, expected.LOOffsetHz);
end
if ~channelHeaderPass
    failures(end + 1) = sprintf( ...
        "Baseband header reports %d channel(s); exactly two are required.", ...
        capture.NumberOfChannels);
end
if ~antennaPortsPass
    failures(end + 1) = sprintf( ...
        "Header antenna ports [%s] do not match expected [%s].", ...
        strjoin(actualAntennaPorts, ", "), ...
        strjoin(expected.AntennaPorts, ", "));
end
if ~channelRolesPass
    failures(end + 1) = sprintf( ...
        "Header channel roles [%s] do not match expected [%s].", ...
        strjoin(actualChannelRoles, ", "), ...
        strjoin(expected.ChannelRoles, ", "));
end
if ~gainPass
    failures(end + 1) = sprintf( ...
        "Header gains %s dB do not match expected %s dB.", ...
        mat2str(actualGainDB), mat2str(expected.GainDB));
end
if ~sessionMatchPass
    failures(end + 1) = "Header SessionID does not match the packaged session.";
end
if ~repetitionMatchPass
    failures(end + 1) = ...
        "Header Repetition does not match the expected capture part.";
end
failures = [failures; manifestFailures];

result = struct( ...
    "Pass", pass, ...
    "RequiredFields", requiredFields, ...
    "MissingFields", missingFields, ...
    "RequiredFieldsPass", requiredFieldsPass, ...
    "FieldValuesPass", fieldValuesPass, ...
    "SampleRatePass", sampleRatePass, ...
    "CenterFrequencyPass", centerFrequencyPass, ...
    "LOOffsetPass", loOffsetPass, ...
    "ChannelHeaderPass", channelHeaderPass, ...
    "AntennaPortsPass", antennaPortsPass, ...
    "ChannelRolesPass", channelRolesPass, ...
    "GainPass", gainPass, ...
    "SessionMatchPass", sessionMatchPass, ...
    "RepetitionMatchPass", repetitionMatchPass, ...
    "ManifestPass", manifestPass, ...
    "ManifestFailures", manifestFailures, ...
    "ActualSampleRateHz", capture.SampleRateHz, ...
    "ActualCenterFrequencyHz", capture.CenterFrequencyHz, ...
    "ActualLOOffsetHz", actualLOOffsetHz, ...
    "ActualRecordingUTC", actualRecordingUTC, ...
    "ActualSessionID", actualSessionID, ...
    "ActualRepetition", actualRepetition, ...
    "ActualAntennaPorts", actualAntennaPorts, ...
    "ActualChannelRoles", actualChannelRoles, ...
    "ActualGainDB", actualGainDB, ...
    "ExpectedSampleRateHz", expected.SampleRateHz, ...
    "ExpectedCenterFrequencyHz", expected.CenterFrequencyHz, ...
    "ExpectedLOOffsetHz", expected.LOOffsetHz, ...
    "ExpectedAntennaPorts", expected.AntennaPorts, ...
    "ExpectedChannelRoles", expected.ChannelRoles, ...
    "ExpectedGainDB", expected.GainDB, ...
    "Failures", failures);
end

function [pass, failures] = localAssessManifest(sourceInfo, capture, expected)
pass = true;
failures = strings(0, 1);
if sourceInfo.SourceKind ~= "packaged_session"
    return
end

manifest = sourceInfo.Manifest;
requiredFields = [ ...
    "gain_db", "channel_mapping", "sdr_defaults", "header_readback"];
missingFields = requiredFields(~arrayfun(@(name) ...
    localHasValue(manifest, name), requiredFields));
if ~isempty(missingFields)
    pass = false;
    failures(end + 1) = "Manifest is missing acquisition provenance: " + ...
        strjoin(missingFields, ", ") + ".";
end

manifestGainDB = localNumericVectorField(manifest, "gain_db", 2);
gainPass = all(isfinite(manifestGainDB)) && ...
    all(abs(manifestGainDB - expected.GainDB) <= 1e-9);
if ~gainPass
    pass = false;
    failures(end + 1) = ...
        "Manifest gain_db does not match the requested channel gains.";
end

[mappingPass, ~, ~] = ...
    localAssessManifestChannelMapping(manifest, expected);
if ~mappingPass
    pass = false;
    failures(end + 1) = ...
        "Manifest channel_mapping does not match the requested ports and roles.";
end

[requestedRFPass, readbackPass] = ...
    localAssessManifestFrequencies(manifest, capture, expected);
if ~requestedRFPass
    pass = false;
    failures(end + 1) = ...
        "Manifest sdr_defaults do not match the requested RF settings.";
end
if ~readbackPass
    pass = false;
    failures(end + 1) = ...
        "Manifest header_readback does not match the baseband header.";
end

end

function [pass, ports, roles] = ...
        localAssessManifestChannelMapping(manifest, expected)
ports = strings(1, 2);
roles = strings(1, 2);
pass = false;
if ~localHasValue(manifest, "channel_mapping")
    return
end

mapping = manifest.channel_mapping;
if ~isstruct(mapping) || numel(mapping) ~= 2
    return
end

indices = arrayfun(@(entry) ...
    localNumericField(entry, "channel_index"), mapping);
for mappingIndex = 1:2
    channelIndex = indices(mappingIndex);
    if ~isfinite(channelIndex) || channelIndex < 1 || ...
            channelIndex > 2 || mod(channelIndex, 1) ~= 0
        return
    end
    ports(channelIndex) = localTextField( ...
        mapping(mappingIndex), "antenna_port");
    roles(channelIndex) = lower(localTextField( ...
        mapping(mappingIndex), "role"));
end

pass = isequal(indices(:).', [1, 2]) && ...
    isequal(ports, expected.AntennaPorts) && ...
    isequal(roles, expected.ChannelRoles);
end

function [requestedPass, readbackPass] = ...
        localAssessManifestFrequencies(manifest, capture, expected)
requestedPass = false;
readbackPass = false;
if ~localHasValue(manifest, "sdr_defaults") || ...
        ~isstruct(manifest.sdr_defaults) || ...
        ~localHasValue(manifest, "header_readback") || ...
        ~isstruct(manifest.header_readback)
    return
end

requested = manifest.sdr_defaults;
requestedValues = [ ...
    localNumericField(requested, "center_frequency_hz"), ...
    localNumericField(requested, "sample_rate_hz"), ...
    localNumericField(requested, "lo_offset_hz")];
expectedValues = [ ...
    expected.CenterFrequencyHz, ...
    expected.SampleRateHz, ...
    expected.LOOffsetHz];
requestedPass = all(isfinite(requestedValues)) && ...
    all(abs(requestedValues - expectedValues) <= ...
    expected.FrequencyToleranceHz);

readback = manifest.header_readback;
readbackValues = [ ...
    localNumericField(readback, "center_frequency_hz"), ...
    localNumericField(readback, "sample_rate_hz"), ...
    localNumericField(readback, "lo_offset_hz")];
captureValues = [ ...
    capture.CenterFrequencyHz, capture.SampleRateHz, ...
    localNumericField(capture.Metadata, "LOOffset")];
readbackPass = all(isfinite(readbackValues)) && ...
    all(abs(readbackValues - captureValues) <= ...
    expected.FrequencyToleranceHz);
end

function tf = localHasValue(metadata, fieldName)
tf = isstruct(metadata) && isfield(metadata, fieldName) && ...
    ~isempty(metadata.(fieldName));
end

function value = localNumericField(metadata, fieldName)
value = NaN;
if ~localHasValue(metadata, fieldName)
    return
end
if ~(isnumeric(metadata.(fieldName)) || islogical(metadata.(fieldName)))
    return
end
candidate = double(metadata.(fieldName));
if isscalar(candidate) && isfinite(candidate)
    value = candidate;
end
end

function value = localNumericVectorField(metadata, fieldName, expectedCount)
value = nan(1, expectedCount);
if ~localHasValue(metadata, fieldName)
    return
end
if ~(isnumeric(metadata.(fieldName)) || islogical(metadata.(fieldName)))
    return
end
candidate = reshape(double(metadata.(fieldName)), 1, []);
if numel(candidate) == expectedCount
    value = candidate;
end
end

function value = localTextField(metadata, fieldName)
value = "";
if ~localHasValue(metadata, fieldName)
    return
end
candidate = string(metadata.(fieldName));
if isscalar(candidate) && ~ismissing(candidate)
    value = candidate;
end
end
