function result = helperEvaluatePassiveRadarPrecheckCapture(capture, sourceInfo, config)
%HELPEREVALUATEPASSIVERADARPRECHECKCAPTURE Run checks on one capture.
%
% Both channel-role assignments are inspected for diagnostic purposes. The
% configured ChannelRoles remain authoritative: this helper can recommend
% reviewing the mapping, but it never swaps channels automatically.

arguments
    capture (1, 1) struct
    sourceInfo (1, 1) struct
    config (1, 1) struct
end

thresholds = config.Thresholds;
expectedMetadata = struct( ...
    "SampleRateHz", config.SampleRateHz, ...
    "CenterFrequencyHz", config.CenterFrequencyHz, ...
    "LOOffsetHz", config.LOOffsetHz, ...
    "FrequencyToleranceHz", config.FrequencyToleranceHz, ...
    "AntennaPorts", config.AntennaPorts, ...
    "ChannelRoles", config.ChannelRoles, ...
    "GainDB", config.GainDB);
metadataCheck = helperAssessPrecheckMetadata( ...
    capture, sourceInfo, expectedMetadata);

cpiSamples = max(1, round(capture.SampleRateHz * config.CPIDurationS));
expectedSamples = cpiSamples * config.MinimumCPIs;
integrityCheck = helperAssessPrecheckChannelIntegrity( ...
    capture.Samples, expectedSamples, ...
    MaximumZeroFraction=thresholds.MaximumZeroFraction, ...
    MaximumZeroRunSamples=thresholds.MaximumZeroRunSamples);
headroomCheck = helperMeasureChannelHeadroom( ...
    capture.Samples, ...
    FullScale=thresholds.FullScale, ...
    Percentile=thresholds.HeadroomPercentile, ...
    NearRailFraction=thresholds.NearRailFraction, ...
    MaximumNearRailFraction=thresholds.MaximumNearRailFraction, ...
    MinimumPeakHeadroomDB=thresholds.MinimumPeakHeadroomDB, ...
    MinimumPercentileHeadroomDB=thresholds.MinimumPercentileHeadroomDB);

surveillanceChannel = find(config.ChannelRoles == "surveillance");
referenceChannel = find(config.ChannelRoles == "reference");
completeCPIs = floor(size(capture.Samples, 1) / cpiSamples);

if integrityCheck.Pass && completeCPIs >= config.MinimumCPIs
    samplesUsed = cpiSamples * completeCPIs;
    surveillanceCube = reshape( ...
        capture.Samples(1:samplesUsed, surveillanceChannel), ...
        cpiSamples, completeCPIs);
    referenceCube = reshape( ...
        capture.Samples(1:samplesUsed, referenceChannel), ...
        cpiSamples, completeCPIs);

    configuredReference = localAssessReference( ...
        referenceCube, capture, metadataCheck, config);
    alternateReference = localAssessReference( ...
        surveillanceCube, capture, metadataCheck, config);
    correlationCheck = localAssessCorrelation( ...
        surveillanceCube, referenceCube, capture.SampleRateHz, thresholds);
    ecaCheck = localAssessECA( ...
        surveillanceCube, referenceCube, capture.SampleRateHz, ...
        config.CPIDurationS, thresholds);
else
    configuredReference = localSkippedCheck( ...
        "Reference check skipped because channel integrity or CPI length failed.");
    alternateReference = localSkippedCheck( ...
        "Alternate-role check skipped because channel integrity or CPI length failed.");
    correlationCheck = localSkippedCheck( ...
        "Correlation skipped because channel integrity or CPI length failed.");
    ecaCheck = localSkippedCheck( ...
        "ECA skipped because channel integrity or CPI length failed.");
end

roleAdvisory = localBuildRoleAdvisory( ...
    configuredReference, alternateReference, headroomCheck, ...
    surveillanceChannel, referenceChannel, thresholds);

checks = struct( ...
    "Metadata", metadataCheck, ...
    "Integrity", integrityCheck, ...
    "Headroom", headroomCheck, ...
    "Pilot", configuredReference, ...
    "AlternatePilot", alternateReference, ...
    "Correlation", correlationCheck, ...
    "ECA", ecaCheck);
requiredPass = metadataCheck.Pass && integrityCheck.Pass && ...
    headroomCheck.Pass && configuredReference.Pass && ...
    correlationCheck.Pass && ecaCheck.Pass;

failures = localCollectFailures(checks);
status = "hold";
if requiredPass
    status = "pass";
end

result = helperEmptyPassiveRadarCaptureResult();
result.File = capture.File;
result.SourceKind = sourceInfo.SourceKind;
result.PartIndex = sourceInfo.PartIndex;
result.SampleRateHz = capture.SampleRateHz;
result.CenterFrequencyHz = capture.CenterFrequencyHz;
result.SamplesRead = capture.SamplesRead;
result.CPISamples = cpiSamples;
result.CPICount = completeCPIs;
result.ConfiguredSurveillanceChannel = surveillanceChannel;
result.ConfiguredReferenceChannel = referenceChannel;
result.Checks = checks;
result.Advisory = roleAdvisory;
result.Pass = requiredPass;
result.Status = status;
result.Failures = failures;
end

function check = localAssessReference(referenceCube, capture, metadataCheck, config)
thresholds = config.Thresholds;
qualityConfig = struct( ...
    "fs", capture.SampleRateHz, ...
    "ref_level_min_dbfs", thresholds.ReferenceLevelMinDBFS, ...
    "ref_level_max_dbfs", thresholds.ReferenceLevelMaxDBFS, ...
    "ref_pilot_snr_threshold", thresholds.PilotSNRMinDB, ...
    "ref_sfm_threshold_db", thresholds.SpectralFlatnessMinDB, ...
    "pilot_search_half_width_hz", thresholds.PilotSearchHalfWidthHz, ...
    "capture_center_frequency_hz", capture.CenterFrequencyHz, ...
    "capture_tune_frequency_hz", capture.CenterFrequencyHz + ...
        metadataCheck.ActualLOOffsetHz, ...
    "capture_lo_offset_hz", metadataCheck.ActualLOOffsetHz, ...
    "illuminator_center_frequency_hz", ...
        config.IlluminatorCenterFrequencyHz, ...
    "verbose", false);

try
    details = checkRefQuality(referenceCube, qualityConfig);
    check = struct( ...
        "Pass", logical(details.pilot_pass), ...
        "Skipped", false, ...
        "PilotSNRDB", details.pilot_snr_db, ...
        "PilotFrequencyHz", details.pilot_freq_hz, ...
        "SpectralFlatnessDB", details.sfm_db, ...
        "LevelDBFS", details.level_dbfs, ...
        "QualityPass", logical(details.pass), ...
        "Details", details, ...
        "Message", string(details.message), ...
        "ErrorIdentifier", "");
catch exception
    check = localFailedCheck( ...
        "ATSC reference analysis failed: " + string(exception.message), ...
        string(exception.identifier));
    check.PilotSNRDB = NaN;
    check.PilotFrequencyHz = NaN;
    check.SpectralFlatnessDB = NaN;
    check.LevelDBFS = NaN;
    check.QualityPass = false;
    check.Details = struct();
end
end

function check = localAssessCorrelation(surveillanceCube, referenceCube, sampleRateHz, thresholds)
try
    details = helperMeasureCrossCorrelationPeak( ...
        surveillanceCube, referenceCube, sampleRateHz, ...
        "MaxLagSamples", thresholds.CorrelationMaximumLagSamples, ...
        "MaxCPIs", thresholds.CorrelationMaximumCPIs, ...
        "PeakMinDB", thresholds.CorrelationPeakMinDB, ...
        "IsolationMinDB", thresholds.CorrelationIsolationMinDB);
    check = struct( ...
        "Pass", logical(details.pass), ...
        "Skipped", false, ...
        "Details", details, ...
        "Message", string(details.message), ...
        "ErrorIdentifier", "");
catch exception
    check = localFailedCheck( ...
        "Cross-correlation analysis failed: " + string(exception.message), ...
        string(exception.identifier));
    check.Details = struct();
end
end

function check = localAssessECA(surveillanceCube, referenceCube, sampleRateHz, cpiDurationS, thresholds)
try
    details = helperMeasureZeroDopplerSuppression( ...
        surveillanceCube, referenceCube, sampleRateHz, 1 / cpiDurationS, ...
        "NearRangeLimitM", thresholds.ECANearRangeLimitM, ...
        "BeforeMarginMinDB", thresholds.ECABeforeMarginMinDB, ...
        "SuppressionMinDB", thresholds.ECASuppressionMinDB, ...
        "AfterMarginMaxDB", thresholds.ECAAfterMarginMaxDB, ...
        "Verbose", false);
    check = struct( ...
        "Pass", logical(details.pass), ...
        "Skipped", false, ...
        "Details", details, ...
        "Message", string(details.message), ...
        "ErrorIdentifier", "");
catch exception
    check = localFailedCheck( ...
        "ECA analysis failed: " + string(exception.message), ...
        string(exception.identifier));
    check.Details = struct();
end
end

function advisory = localBuildRoleAdvisory(configured, alternate, headroom, surveillanceChannel, referenceChannel, thresholds)
referenceRMSDBFS = localChannelValue(headroom.RMSDBFS, referenceChannel);
surveillanceRMSDBFS = localChannelValue( ...
    headroom.RMSDBFS, surveillanceChannel);
powerDifferenceDB = referenceRMSDBFS - surveillanceRMSDBFS;

configuredPilotSNRDB = localStructNumber(configured, "PilotSNRDB");
alternatePilotSNRDB = localStructNumber(alternate, "PilotSNRDB");
pilotAdvantageDB = alternatePilotSNRDB - configuredPilotSNRDB;
reviewMapping = ~alternate.Skipped && alternate.Pass && ...
    isfinite(pilotAdvantageDB) && ...
    pilotAdvantageDB >= thresholds.RoleSwapPilotMarginDB;

recommendation = "configured_roles_supported";
if reviewMapping
    recommendation = "review_channel_mapping";
elseif configured.Skipped || ~isfinite(pilotAdvantageDB)
    recommendation = "inconclusive";
end

advisory = struct( ...
    "Pass", true, ...
    "IsRequired", false, ...
    "ReferencePowerMinusSurveillanceDB", powerDifferenceDB, ...
    "ConfiguredReferencePilotSNRDB", configuredPilotSNRDB, ...
    "AlternateReferencePilotSNRDB", alternatePilotSNRDB, ...
    "AlternatePilotAdvantageDB", pilotAdvantageDB, ...
    "ReviewChannelMapping", reviewMapping, ...
    "Recommendation", recommendation, ...
    "Message", sprintf( ...
        "REF-SURV power is %.1f dB (advisory only). " + ...
        "Alternate-minus-configured pilot SNR is %.1f dB; %s.", ...
        powerDifferenceDB, pilotAdvantageDB, ...
        strrep(recommendation, "_", " ")));
end

function failures = localCollectFailures(checks)
failures = strings(0, 1);
names = ["Metadata", "Integrity", "Headroom", ...
    "Pilot", "Correlation", "ECA"];
for index = 1:numel(names)
    name = names(index);
    check = checks.(name);
    if ~check.Pass
        if isfield(check, "Failures") && ~isempty(check.Failures)
            messages = string(check.Failures(:));
        elseif isfield(check, "Message")
            messages = string(check.Message);
        else
            messages = "Check failed.";
        end
        failures = [failures; name + ": " + messages]; %#ok<AGROW>
    end
end
end

function value = localChannelValue(values, channelIndex)
value = NaN;
if channelIndex <= numel(values)
    value = values(channelIndex);
end
end

function value = localStructNumber(input, fieldName)
value = NaN;
if isfield(input, fieldName)
    value = double(input.(fieldName));
end
end

function check = localSkippedCheck(message)
check = struct( ...
    "Pass", false, ...
    "Skipped", true, ...
    "Message", string(message), ...
    "ErrorIdentifier", "");
end

function check = localFailedCheck(message, identifier)
check = struct( ...
    "Pass", false, ...
    "Skipped", false, ...
    "Message", string(message), ...
    "ErrorIdentifier", string(identifier));
end
