function result = helperEmptyPassiveRadarCaptureResult()
%HELPEREMPTYPASSIVERADARCAPTURERESULT Create a stable result template.

result = struct( ...
    "File", "", ...
    "SourceKind", "", ...
    "PartIndex", 0, ...
    "SampleRateHz", NaN, ...
    "CenterFrequencyHz", NaN, ...
    "SamplesRead", 0, ...
    "CPISamples", 0, ...
    "CPICount", 0, ...
    "ConfiguredSurveillanceChannel", NaN, ...
    "ConfiguredReferenceChannel", NaN, ...
    "Checks", struct(), ...
    "Advisory", struct(), ...
    "Pass", false, ...
    "Status", "hold", ...
    "Failures", strings(0, 1));
end
