function normalized = helperNormalizePassiveRadarPrecheckConfig(config)
%HELPERNORMALIZEPASSIVERADARPRECHECKCONFIG Apply and validate defaults.

arguments
    config (1, 1) struct
end

normalized = struct();
normalized.Mode = lower(string(config.Mode));
normalized.Source = localField(config, "Source", strings(0, 1));
normalized.DatasetRoot = string(localField(config, "DatasetRoot", ""));
normalized.PartIndices = double(localField(config, "PartIndices", []));
normalized.CenterFrequencyHz = double(localField( ...
    config, "CenterFrequencyHz", 599e6));
normalized.SampleRateHz = double(localField( ...
    config, "SampleRateHz", 6.144e6));
normalized.LOOffsetHz = double(localField(config, "LOOffsetHz", 0));
normalized.AntennaPorts = reshape(string(localField( ...
    config, "AntennaPorts", ["RF0:RX2", "RF1:RX2"])), 1, []);
normalized.ChannelRoles = lower(reshape(string(localField( ...
    config, "ChannelRoles", ["surveillance", "reference"])), 1, []));
normalized.GainDB = reshape(double(localField(config, "GainDB", [16, 16])), 1, []);
normalized.AnalysisDurationS = double(localField( ...
    config, "AnalysisDurationS", 1));
normalized.CPIDurationS = double(localField(config, "CPIDurationS", 0.5e-3));
normalized.MinimumCPIs = double(localField(config, "MinimumCPIs", 16));
normalized.MinimumStableCaptures = double(localField( ...
    config, "MinimumStableCaptures", 3));
normalized.FrequencyToleranceHz = double(localField( ...
    config, "FrequencyToleranceHz", 1));
normalized.IlluminatorCenterFrequencyHz = double(localField( ...
    config, "IlluminatorCenterFrequencyHz", normalized.CenterFrequencyHz));
normalized.CreatePlots = logical(localField(config, "CreatePlots", false));

localValidateScalarPositive(normalized.CenterFrequencyHz, "CenterFrequencyHz");
localValidateScalarPositive(normalized.SampleRateHz, "SampleRateHz");
localValidateScalarFinite(normalized.LOOffsetHz, "LOOffsetHz");
localValidateScalarPositive(normalized.AnalysisDurationS, "AnalysisDurationS");
localValidateScalarPositive(normalized.CPIDurationS, "CPIDurationS");
localValidatePositiveInteger(normalized.MinimumCPIs, "MinimumCPIs");
localValidatePositiveInteger( ...
    normalized.MinimumStableCaptures, "MinimumStableCaptures");
if normalized.MinimumStableCaptures < 3
    localInvalid( ...
        "MinimumStableCaptures cannot be less than three for a " + ...
        "production-safe precheck.");
end
localValidateScalarNonnegative( ...
    normalized.FrequencyToleranceHz, "FrequencyToleranceHz");
if ~isscalar(normalized.CreatePlots)
    localInvalid("CreatePlots must be a logical scalar.");
end
if numel(normalized.AntennaPorts) ~= 2 || ...
        any(strlength(normalized.AntennaPorts) == 0)
    localInvalid("AntennaPorts must contain exactly two nonempty names.");
end
if numel(normalized.ChannelRoles) ~= 2 || ...
        ~isequal(sort(normalized.ChannelRoles), ...
        sort(["reference", "surveillance"]))
    localInvalid( ...
        "ChannelRoles must contain exactly one ""surveillance"" and one " + ...
        """reference"" role.");
end
if numel(normalized.GainDB) ~= 2 || any(~isfinite(normalized.GainDB))
    localInvalid("GainDB must contain two finite channel gains.");
end
if any(normalized.PartIndices < 1) || ...
        any(mod(normalized.PartIndices, 1) ~= 0)
    localInvalid("PartIndices must contain positive integers.");
end

thresholds = localField(config, "Thresholds", struct());
if ~isstruct(thresholds) || ~isscalar(thresholds)
    localInvalid("Thresholds must be a scalar structure.");
end
normalized.Thresholds = localNormalizeThresholds(thresholds);

live = localField(config, "Live", struct());
if ~isstruct(live) || ~isscalar(live)
    localInvalid("Live must be a scalar structure.");
end
normalized.Live = localNormalizeLive(live);
end

function thresholds = localNormalizeThresholds(input)
thresholds = struct( ...
    "MaximumZeroFraction", double(localField(input, "MaximumZeroFraction", 1e-3)), ...
    "MaximumZeroRunSamples", double(localField(input, "MaximumZeroRunSamples", 64)), ...
    "FullScale", double(localField(input, "FullScale", NaN)), ...
    "HeadroomPercentile", double(localField(input, "HeadroomPercentile", 99.99)), ...
    "NearRailFraction", double(localField(input, "NearRailFraction", 0.98)), ...
    "MaximumNearRailFraction", double(localField(input, "MaximumNearRailFraction", 1e-5)), ...
    "MinimumPeakHeadroomDB", double(localField(input, "MinimumPeakHeadroomDB", 0.25)), ...
    "MinimumPercentileHeadroomDB", double(localField(input, "MinimumPercentileHeadroomDB", 3)), ...
    "ReferenceLevelMinDBFS", double(localField(input, "ReferenceLevelMinDBFS", -30)), ...
    "ReferenceLevelMaxDBFS", double(localField(input, "ReferenceLevelMaxDBFS", -3)), ...
    "PilotSNRMinDB", double(localField(input, "PilotSNRMinDB", 10)), ...
    "SpectralFlatnessMinDB", double(localField(input, "SpectralFlatnessMinDB", -15)), ...
    "PilotSearchHalfWidthHz", double(localField(input, "PilotSearchHalfWidthHz", 300e3)), ...
    "CorrelationMaximumLagSamples", double(localField(input, "CorrelationMaximumLagSamples", 500)), ...
    "CorrelationMaximumCPIs", double(localField(input, "CorrelationMaximumCPIs", 32)), ...
    "CorrelationPeakMinDB", double(localField(input, "CorrelationPeakMinDB", 15)), ...
    "CorrelationIsolationMinDB", double(localField(input, "CorrelationIsolationMinDB", 6)), ...
    "ECANearRangeLimitM", double(localField(input, "ECANearRangeLimitM", 5e3)), ...
    "ECABeforeMarginMinDB", double(localField(input, "ECABeforeMarginMinDB", 15)), ...
    "ECASuppressionMinDB", double(localField(input, "ECASuppressionMinDB", 30)), ...
    "ECAAfterMarginMaxDB", double(localField(input, "ECAAfterMarginMaxDB", 15)), ...
    "ControlLevelSpanMaxDB", double(localField(input, "ControlLevelSpanMaxDB", 6)), ...
    "RoleSwapPilotMarginDB", double(localField(input, "RoleSwapPilotMarginDB", 3)));

unitFractions = [thresholds.MaximumZeroFraction, ...
    thresholds.NearRailFraction, thresholds.MaximumNearRailFraction];
if any(~isfinite(unitFractions)) || any(unitFractions < 0) || ...
        any(unitFractions > 1)
    localInvalid("Zero and rail fractions must be finite values from 0 through 1.");
end
if ~isscalar(thresholds.FullScale) || ...
        ~(isnan(thresholds.FullScale) || ...
        (isfinite(thresholds.FullScale) && thresholds.FullScale > 0))
    localInvalid( ...
        "Thresholds.FullScale must be NaN for automatic detection " + ...
        "or a finite positive scalar.");
end
if thresholds.HeadroomPercentile <= 0 || ...
        thresholds.HeadroomPercentile > 100
    localInvalid("Thresholds.HeadroomPercentile must be in (0, 100].");
end
localValidatePositiveInteger( ...
    thresholds.MaximumZeroRunSamples, "Thresholds.MaximumZeroRunSamples");
localValidatePositiveInteger( ...
    thresholds.CorrelationMaximumLagSamples, ...
    "Thresholds.CorrelationMaximumLagSamples");
localValidatePositiveInteger( ...
    thresholds.CorrelationMaximumCPIs, "Thresholds.CorrelationMaximumCPIs");
localValidateScalarNonnegative( ...
    thresholds.MinimumPeakHeadroomDB, ...
    "Thresholds.MinimumPeakHeadroomDB");
localValidateScalarNonnegative( ...
    thresholds.MinimumPercentileHeadroomDB, ...
    "Thresholds.MinimumPercentileHeadroomDB");
localValidateScalarPositive( ...
    thresholds.PilotSearchHalfWidthHz, ...
    "Thresholds.PilotSearchHalfWidthHz");
localValidateScalarPositive( ...
    thresholds.ECANearRangeLimitM, "Thresholds.ECANearRangeLimitM");
localValidateScalarNonnegative( ...
    thresholds.ControlLevelSpanMaxDB, ...
    "Thresholds.ControlLevelSpanMaxDB");
localValidateScalarNonnegative( ...
    thresholds.RoleSwapPilotMarginDB, ...
    "Thresholds.RoleSwapPilotMarginDB");
end

function live = localNormalizeLive(input)
enableHardwareAccess = localField(input, "EnableHardwareAccess", false);
if ~islogical(enableHardwareAccess) || ~isscalar(enableHardwareAccess)
    localInvalid( ...
        "Live.EnableHardwareAccess must be the logical scalar true or false.");
end

live = struct( ...
    "EnableHardwareAccess", enableHardwareAccess, ...
    "SessionID", string(localField(input, "SessionID", "")), ...
    "CaptureDurationS", double(localField(input, "CaptureDurationS", 2)), ...
    "CaptureFile", string(localField( ...
        input, "CaptureFile", "passive_radar_precheck")), ...
    "RadioName", string(localField(input, "RadioName", "My USRP N320")), ...
    "Repetitions", double(localField(input, "Repetitions", 3)), ...
    "RepetitionSpacingS", double(localField( ...
        input, "RepetitionSpacingS", 1)));

if ~isscalar(live.SessionID) || ~isscalar(live.CaptureFile) || ...
        strlength(live.CaptureFile) == 0 || ...
        ~isscalar(live.RadioName) || strlength(live.RadioName) == 0
    localInvalid("Live text settings must be nonempty scalar text where required.");
end
localValidateScalarPositive(live.CaptureDurationS, "Live.CaptureDurationS");
localValidatePositiveInteger(live.Repetitions, "Live.Repetitions");
localValidateScalarNonnegative( ...
    live.RepetitionSpacingS, "Live.RepetitionSpacingS");
end

function value = localField(input, fieldName, defaultValue)
fieldName = char(fieldName);
if isfield(input, fieldName)
    value = input.(fieldName);
else
    value = defaultValue;
end
end

function localValidateScalarPositive(value, fieldName)
if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || value <= 0
    localInvalid(fieldName + " must be a finite positive scalar.");
end
end

function localValidateScalarNonnegative(value, fieldName)
if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || value < 0
    localInvalid(fieldName + " must be a finite nonnegative scalar.");
end
end

function localValidateScalarFinite(value, fieldName)
if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value)
    localInvalid(fieldName + " must be a finite scalar.");
end
end

function localValidatePositiveInteger(value, fieldName)
localValidateScalarPositive(value, fieldName);
if mod(value, 1) ~= 0
    localInvalid(fieldName + " must be an integer.");
end
end

function localInvalid(message)
error("runPassiveRadarHardwarePrecheck:invalidConfiguration", "%s", message);
end
