classdef ADSBRemoterIntegrationTest < matlab.unittest.TestCase
    %ADSBREMOTERINTEGRATIONTEST Offline adapter and opportunity-table parity.

    properties (SetAccess = private)
        ProjectRoot
    end

    methods (TestClassSetup)
        function addAnalysisPath(testCase)
            analysis_folder = fileparts(fileparts(mfilename('fullpath')));
            testCase.ProjectRoot = string(fileparts(analysis_folder));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                analysis_folder));
        end
    end

    methods (Test)
        function testAdapterMatchesCanonicalLoader(testCase)
            fixture_path = fullfile(testCase.ProjectRoot, ...
                "external", "ADSB-remoter", "tests", "fixtures", ...
                "basestation_sample.csv");

            expected_tracks = loadADSBTruth(fixture_path, 'Verbose', false);
            [actual_tracks, import_info] = loadADSBRemoterArchive( ...
                fixture_path, 'Verbose', false);

            testCase.verifyEqual(actual_tracks, expected_tracks);
            testCase.verifyEqual(import_info.parser, "loadADSBTruth");
            testCase.verifyEqual(import_info.source_file_count, 1);
        end

        function testAdapterNormalizesCombinedDatetimeGzip(testCase)
            fixture_path = fullfile(testCase.ProjectRoot, ...
                "external", "ADSB-remoter", "tests", "fixtures", ...
                "sbs_clean", "15_adsb_20220413_060850.csv.gz");

            [actual_tracks, import_info] = loadADSBRemoterArchive( ...
                fixture_path, 'Verbose', false);

            testCase.verifyNotEmpty(actual_tracks);
            testCase.verifyGreaterThan( ...
                import_info.normalized_timestamp_line_count, 0);
            testCase.verifyGreaterThan(import_info.position_fix_count, 0);
            testCase.verifyEqual(import_info.track_count, numel(actual_tracks));

            aircraft_ids = string({actual_tracks.hex});
            track_index = find(aircraft_ids == "C01DDE", 1);
            testCase.assertNotEmpty(track_index);
            imported_track = actual_tracks(track_index);
            expected_time = posixtime(datetime( ...
                2025, 5, 1, 7, 55, 23.778, 'TimeZone', 'UTC'));
            fix_index = find(abs(imported_track.t_utc - expected_time) < ...
                1e-3, 1);
            testCase.assertNotEmpty(fix_index);
            testCase.verifyEqual( ...
                imported_track.lat_deg(fix_index), 41.65481, ...
                AbsTol=1e-10);
            testCase.verifyEqual( ...
                imported_track.lon_deg(fix_index), -73.82331, ...
                AbsTol=1e-10);
            testCase.verifyEqual( ...
                imported_track.alt_m(fix_index), 40000 * 0.3048, ...
                AbsTol=1e-9);
        end

        function testConfigurationPinsGeometryAndAssumptions(testCase)
            config = helperADSBRemoter599MHzConfig();

            testCase.verifyEqual(config.TxLLA, ...
                [42.311389, -71.216111, 348.386404], AbsTol=0);
            testCase.verifyEqual(config.RxLLA, ...
                [42.2999333, -71.349333, 15], AbsTol=0);
            testCase.verifyEqual(config.CenterFrequency_Hz, 599e6, AbsTol=0);
            testCase.verifyEqual( ...
                config.EmitterEIRP_kW, 1640.5897731995394, AbsTol=0);
            testCase.verifyEqual(config.ReceiverGain_dBi, 10, AbsTol=0);
            testCase.verifyEqual(config.NoiseFigure_dB, 3, AbsTol=0);
            testCase.verifyEqual(config.ReceiverBandwidth_Hz, 8e6, AbsTol=0);
            testCase.verifyEqual(config.BistaticRCS_dBsm, 10, AbsTol=0);
            testCase.verifyEqual(config.PolarizationLoss_dB, 1, AbsTol=0);
            testCase.verifyEqual(config.SystemLoss_dB, 2, AbsTol=0);
            testCase.verifyEqual(config.NoiseTemperature_K, 290, AbsTol=0);
            testCase.verifyEqual(config.EmitterID, "ASRN:1005862");
            testCase.verifyEqual(config.SourceID, ...
                "ADSB-remoter@63ff6688628c2813e4287c5ecdc0df67883c3f93");
            testCase.verifyEqual(config.AssumptionID, ...
                "adsb-remoter-63ff668-599MHz-defaults-v1");
            testCase.verifyEqual(config.CPAMethod, ...
                "minimum_observed_3d_receiver_slant_range");
        end

        function testLiveConsoleFilesMatchMATLABConfiguration(testCase)
            config = helperADSBRemoter599MHzConfig();
            emitter_path = fullfile(testCase.ProjectRoot, ...
                "BistaticDataAnalysis", ...
                "adsb_remoter_599mhz_emitter.csv");
            observer_path = fullfile(testCase.ProjectRoot, ...
                "BistaticDataAnalysis", ...
                "adsb_remoter_599mhz_observer.ini");

            emitter = readtable(emitter_path, ...
                TextType="string", VariableNamingRule="preserve");
            observer_text = string(fileread(observer_path));

            testCase.verifyEqual(height(emitter), 1);
            testCase.verifyEqual( ...
                emitter.center_frequency_mhz, ...
                config.CenterFrequency_Hz / 1e6, AbsTol=0);
            testCase.verifyEqual( ...
                emitter.tx_latitude_deg, config.TxLLA(1), AbsTol=0);
            testCase.verifyEqual( ...
                emitter.tx_longitude_deg, config.TxLLA(2), AbsTol=0);
            testCase.verifyEqual( ...
                emitter.tx_altitude_m, config.TxLLA(3), AbsTol=0);
            testCase.verifyEqual( ...
                emitter.eirp_kw, config.EmitterEIRP_kW, AbsTol=0);
            testCase.verifySubstring(observer_text, ...
                "locLat_locLon_locAlt: 42.2999333,-71.349333,15");
            testCase.verifySubstring(observer_text, ...
                "receiverGainDbi: 10");
            testCase.verifySubstring(observer_text, ...
                "noiseFigureDb: 3");
            testCase.verifySubstring(observer_text, ...
                "bandwidthMhz: 8");
        end

        function testOpportunityGeometryAndDopplerMatchProjectHelper(testCase)
            config = helperADSBRemoter599MHzConfig();
            t0 = posixtime(datetime( ...
                2026, 8, 12, 12, 0, 0, 'TimeZone', 'UTC'));
            track = localTrack( ...
                'ABC123', 'TEST123', t0 + [0; 2; 4], ...
                [42.370; 42.350; 42.330], ...
                [-71.310; -71.300; -71.290], ...
                [3200; 3200; 3200]);

            direct = adsbToBistatic( ...
                track, config.TxLLA, config.RxLLA, ...
                config.CenterFrequency_Hz);
            opportunities = buildManualADSBOpportunityTable(track, config);
            geometry = helperDeriveTxRxGeometry( ...
                config.TxLLA, config.RxLLA);
            [east_m, north_m, up_m] = geodetic2enu( ...
                direct.lat_deg, direct.lon_deg, direct.alt_m, ...
                config.RxLLA(1), config.RxLLA(2), config.RxLLA(3), ...
                geometry.spheroid);
            receiver_range_m = sqrt(east_m.^2 + north_m.^2 + up_m.^2);
            [expected_cpa_m, cpa_idx] = min(receiver_range_m);
            expected_cpa_utc = datetime( ...
                direct.t_utc(cpa_idx), ...
                'ConvertFrom', 'posixtime', 'TimeZone', 'UTC');

            testCase.verifyEqual( ...
                opportunities.CPADistance_m, expected_cpa_m, AbsTol=1e-9);
            testCase.verifyEqual( ...
                opportunities.CPATimeUTC, expected_cpa_utc);
            testCase.verifyEqual( ...
                opportunities.ExcessRange_m, ...
                direct.R_excess_m(cpa_idx), AbsTol=1e-9);
            testCase.verifyEqual( ...
                opportunities.Doppler_Hz, ...
                direct.f_D_hz(cpa_idx), AbsTol=1e-12);
            testCase.verifyEqual( ...
                opportunities.TransmitterRange_m, ...
                direct.R_excess_m(cpa_idx) + direct.L_m - expected_cpa_m, ...
                AbsTol=1e-9);
        end

        function testBiSNRAndRankMatchPinnedEquation(testCase)
            config = helperADSBRemoter599MHzConfig();
            t0 = posixtime(datetime( ...
                2026, 8, 12, 12, 0, 0, 'TimeZone', 'UTC'));
            near_lla = [42.36, -71.28, 3000];
            far_lla = [43.00, -72.00, 3000];
            tracks = [ ...
                localSingleFixTrack('ZZZ999', 'TIEZ', t0, near_lla), ...
                localSingleFixTrack('AAA111', 'TIEA', t0, near_lla), ...
                localSingleFixTrack('FFF222', 'FAR', t0, far_lla)];

            opportunities = buildManualADSBOpportunityTable(tracks, config);
            expected_bisnr_db = localPinnedBiSNR( ...
                opportunities.TransmitterRange_m, ...
                opportunities.CPADistance_m, config);

            testCase.verifyEqual( ...
                opportunities.BiSNR_dB, expected_bisnr_db, AbsTol=1e-10);
            testCase.verifyLessThanOrEqual( ...
                diff(opportunities.BiSNR_dB), zeros(2, 1));
            testCase.verifyEqual( ...
                opportunities.AircraftID, ["AAA111"; "ZZZ999"; "FFF222"]);
            testCase.verifyEqual(opportunities.BiSNRRank, (1:3).');
            testCase.verifyTrue(all(opportunities.BiSNRAssumptionBased));
            testCase.verifyEqual(opportunities.SourceID, ...
                repmat(config.SourceID, 3, 1));
            testCase.verifyEqual(opportunities.AssumptionID, ...
                repmat(config.AssumptionID, 3, 1));
        end
    end
end

function track = localTrack(hex_id, callsign, times, latitudes, longitudes, altitudes)
track = struct( ...
    'hex', hex_id, ...
    'callsign', callsign, ...
    't_utc', times(:), ...
    'lat_deg', latitudes(:), ...
    'lon_deg', longitudes(:), ...
    'alt_m', altitudes(:), ...
    'speed_mps', NaN(numel(times), 1), ...
    'track_deg', NaN(numel(times), 1), ...
    'vrate_mps', NaN(numel(times), 1));
end

function track = localSingleFixTrack(hex_id, callsign, time, lla)
track = localTrack( ...
    hex_id, callsign, time, lla(1), lla(2), lla(3));
end

function snr_db = localPinnedBiSNR(tx_range_m, rx_range_m, config)
c = physconst('LightSpeed');
k = 1.380649e-23;
wavelength_m = c ./ config.CenterFrequency_Hz;

snr_db = ...
    10 .* log10(config.EmitterEIRP_kW .* 1000) + ...
    config.ReceiverGain_dBi + ...
    20 .* log10(wavelength_m) + ...
    config.BistaticRCS_dBsm - ...
    30 .* log10(4 .* pi) - ...
    20 .* log10(tx_range_m) - ...
    20 .* log10(rx_range_m) - ...
    10 .* log10(k .* config.NoiseTemperature_K .* ...
        config.ReceiverBandwidth_Hz) - ...
    config.NoiseFigure_dB - ...
    config.PolarizationLoss_dB - ...
    config.SystemLoss_dB;
end
