classdef OfflineToolboxBenchmarkTest < matlab.unittest.TestCase
    %OFFLINETOOLBOXBENCHMARKTEST Tests for the offline toolbox benchmark path.

    methods (TestClassSetup)
        function addSourceFolder(testCase)
            srcFolder = fileparts(fileparts(mfilename('fullpath')));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(srcFolder));
        end
    end

    methods (TestMethodSetup)
        function resetRandomSeed(testCase)
            originalRng = rng;
            testCase.addTeardown(@() rng(originalRng));
            rng(42, 'twister');
        end
    end

    methods (Test)
        function testToolboxTDOARangeMatchesSyntheticDelay(testCase)
            fixture = testCase.buildSignalFixture();

            [range_est_m, estimate_info] = helperEstimateToolboxTDOARange( ...
                fixture.reference_block, fixture.surveillance_block, ...
                fixture.fs, fixture.prf, fixture.detection_doppler_hz, ...
                fixture.direct_path_delay_s, fixture.range_guess_m, ...
                'SearchWindowSamples', 4, ...
                'ApplyClutterMitigation', true, ...
                'Verbose', false);

            testCase.verifyEqual(range_est_m, fixture.expected_range_m, ...
                AbsTol=fixture.range_cell_m);
            testCase.verifyGreaterThan(estimate_info.peak_response, 0);
        end

        function testToolboxTDOAAllowsSeparateClutterAlignmentLag(testCase)
            fixture = testCase.buildSignalFixture();
            c = physconst('LightSpeed');
            signed_direct_delay_samp = -1;

            [range_est_m, estimate_info] = helperEstimateToolboxTDOARange( ...
                fixture.reference_block, fixture.surveillance_block, ...
                fixture.fs, fixture.prf, fixture.detection_doppler_hz, ...
                signed_direct_delay_samp / fixture.fs, ...
                c * (fixture.target_delay_samples - signed_direct_delay_samp + 1) / fixture.fs, ...
                'SearchWindowSamples', 4, ...
                'ApplyClutterMitigation', true, ...
                'ClutterAlignmentLagSamples', fixture.direct_delay_samples, ...
                'Verbose', false);

            testCase.verifyEqual(range_est_m, ...
                c * (fixture.target_delay_samples - signed_direct_delay_samp) / fixture.fs, ...
                AbsTol=fixture.range_cell_m);
            testCase.verifyEqual(estimate_info.clutter_alignment_lag_samples, ...
                fixture.direct_delay_samples);
        end

        function testToolboxTDOASupportsMultiEstimateEstimatorWithoutResponseGrid(testCase)
            fixture = testCase.buildSignalFixture();
            estimator = phased.TDOAEstimator( ...
                'SampleRate', fixture.fs, ...
                'NumEstimates', 4);
            testCase.addTeardown(@() release(estimator));

            [range_est_m, estimate_info] = helperEstimateToolboxTDOARange( ...
                fixture.reference_block, fixture.surveillance_block, ...
                fixture.fs, fixture.prf, fixture.detection_doppler_hz, ...
                fixture.direct_path_delay_s, fixture.range_guess_m, ...
                'SearchWindowSamples', 4, ...
                'ApplyClutterMitigation', true, ...
                'TDOAEstimator', estimator, ...
                'Verbose', false);

            testCase.verifyEqual(range_est_m, fixture.expected_range_m, ...
                AbsTol=fixture.range_cell_m);
            testCase.verifyGreaterThanOrEqual(numel(estimate_info.tau_candidates_s), 1);
            testCase.verifyEqual(estimate_info.tau_candidates_s(1), estimate_info.tau_primary_s, ...
                AbsTol=1e-12);
        end

        function testToolboxCFARReplayMatchesSimpleCustomReplay(testCase)
            fixture = testCase.buildReplayFixture();

            [~, custom_dets] = helperRunDetectorReplayVariant( ...
                fixture.detector_replay_input, 'custom', 'Verbose', false);
            [~, toolbox_dets] = helperRunDetectorReplayVariant( ...
                fixture.detector_replay_input, 'toolbox', 'Verbose', false);

            testCase.verifyEqual(size(custom_dets), [1 6]);
            testCase.verifyEqual(size(toolbox_dets), [1 6]);
            testCase.verifyEqual(toolbox_dets(:, [1, 2, 4, 5, 6]), ...
                custom_dets(:, [1, 2, 4, 5, 6]), AbsTol=1e-9);
        end

        function testBenchmarkHarnessEmitsRequiredSchemaAndBaselineDeltas(testCase)
            fixture = testCase.buildReplayFixture();

            benchmark_output = runOfflineToolboxBenchmark( ...
                fixture.detector_replay_input, ...
                'RunTruthDiagnostics', false, ...
                'PlotSummary', false, ...
                'Verbose', false);

            required_columns = [ ...
                "variant_name", "status", "detector_backend", "tdoa_backend", ...
                "detector_runtime_s", "tdoa_runtime_s", "truth_runtime_s", "total_runtime_s", ...
                "detection_count", "n_tp", "n_fa", "n_miss", "mean_pd", ...
                "delta_detector_runtime_s", "delta_tdoa_runtime_s", "delta_truth_runtime_s", "delta_total_runtime_s", ...
                "delta_detection_count", "delta_n_tp", "delta_n_fa", "delta_n_miss", "delta_mean_pd"];

            testCase.verifyEqual(benchmark_output.summary_table.variant_name, ...
                ["custom_baseline"; "toolbox_tdoa"; "toolbox_cfar"; "toolbox_tdoa_cfar"]);
            testCase.verifyTrue(all(ismember(required_columns, ...
                string(benchmark_output.summary_table.Properties.VariableNames))));
            testCase.verifyTrue(all(benchmark_output.summary_table.status == "completed"));
            testCase.verifyEqual(benchmark_output.summary_table.delta_total_runtime_s(1), 0, AbsTol=1e-12);
            testCase.verifyEqual(benchmark_output.summary_table.delta_detection_count(1), 0, AbsTol=1e-12);
            testCase.verifyEqual(benchmark_output.variant_results(2).all_track_dets(1, 1), ...
                fixture.expected_range_m, AbsTol=fixture.range_cell_m);
        end

        function testBenchmarkHarnessSupportsScopedIterationRuns(testCase)
            fixture = testCase.buildScopedReplayFixture();

            benchmark_output = runOfflineToolboxBenchmark( ...
                fixture.detector_replay_input, ...
                'Variants', {'toolbox_cfar'}, ...
                'PartIndices', 2, ...
                'MaxBlocksPerPart', 1, ...
                'RunTruthDiagnostics', true, ...
                'PlotSummary', false, ...
                'Verbose', false);

            testCase.verifyTrue(benchmark_output.scope_info.is_limited);
            testCase.verifyEqual(benchmark_output.scope_info.selected_part_indices, 2);
            testCase.verifyEqual(benchmark_output.scope_info.max_blocks_per_part, 1);
            testCase.verifyEqual(numel(benchmark_output.variant_results(1).part_detections), 1);
            testCase.verifyEqual(size(benchmark_output.variant_results(1).part_detections{1}, 1), 1);
            testCase.verifyTrue(all(isnan(benchmark_output.summary_table.n_tp)));
        end
    end

    methods (Access = private)
        function fixture = buildReplayFixture(testCase)
            signal_fixture = testCase.buildSignalFixture();
            tmpDir = tempname;
            mkdir(tmpDir);
            testCase.addTeardown(@() rmdir(tmpDir, 's'));

            bbPath = fullfile(tmpDir, 'synthetic_toolbox_benchmark.bb');
            testCase.writeSyntheticBasebandFile( ...
                bbPath, signal_fixture.fs, signal_fixture.fc, ...
                signal_fixture.surveillance_vector, signal_fixture.reference_vector);

            c = physconst('LightSpeed');
            range_axis = (0 : signal_fixture.N_fast - 1).' / signal_fixture.fs * c;
            doppler_axis = ((0 : signal_fixture.N_slow_cpi - 1) - floor(signal_fixture.N_slow_cpi / 2)) * ...
                (signal_fixture.prf / signal_fixture.N_slow_cpi);
            [~, range_idx] = min(abs(range_axis - signal_fixture.expected_range_m));
            [~, dopp_idx] = min(abs(doppler_axis - signal_fixture.detection_doppler_hz));

            rdm_whitened_db = -8 + 0.1 * randn(numel(range_axis), numel(doppler_axis));
            rdm_whitened_db(range_idx, dopp_idx) = 22;

            part_duration_s = signal_fixture.num_samples / signal_fixture.fs;
            block_center_s = part_duration_s / 2;
            det_row = [range_axis(range_idx), doppler_axis(dopp_idx), 22, 1, block_center_s];

            detector_block = struct( ...
                'block_num', 1, ...
                'look_count', 1, ...
                't_part_center_s', block_center_s, ...
                't_abs_center_s', block_center_s, ...
                'rdm_whitened_db', rdm_whitened_db, ...
                'row_nf_db', zeros(numel(range_axis), 1), ...
                'abs_nf_db', 0);

            detector_part = struct( ...
                'part_index', 1, ...
                'data_part', string(bbPath), ...
                'time_window_s', [0, part_duration_s], ...
                'range_axis', range_axis, ...
                'doppler_axis', doppler_axis, ...
                'cfar_nf_db', 0, ...
                'original_detections', det_row, ...
                'blocks', detector_block);

            detector_defaults = struct( ...
                'pfa', 1e-4, ...
                'guard_cells', [2, 1], ...
                'train_cells', [6, 2], ...
                'min_range_m', 2e3, ...
                'cfar_options', struct( ...
                    'cfar_type', 'OS', ...
                    'os_rank_fraction', 0.75, ...
                    'local_maxima', true, ...
                    'lm_range_bins', 1, ...
                    'lm_dopp_bins', 1, ...
                    'min_snr_db', 0, ...
                    'atsc_guard_ranges_m', [], ...
                    'atsc_guard_penalty_db', 10, ...
                    'atsc_guard_width_bins', 1, ...
                    'notch_guard_dopp_bins', 0, ...
                    'nci_looks', 1, ...
                    'verbose', false));

            signal_config = struct( ...
                'fs', signal_fixture.fs, ...
                'fc', signal_fixture.fc, ...
                'num_samples', signal_fixture.num_samples, ...
                'cpi_duration_s', signal_fixture.cpi_duration_s, ...
                'prf', signal_fixture.prf, ...
                'N_slow_cpi', signal_fixture.N_slow_cpi, ...
                'max_nci_looks', 1, ...
                'chunk_dur_s', part_duration_s, ...
                'swap_channels', false);

            fixture = signal_fixture;
            fixture.detector_replay_input = struct( ...
                'schema_version', 1, ...
                'created_posix_utc', posixtime(datetime('now', 'TimeZone', 'UTC')), ...
                'session_id', 'synthetic_toolbox_benchmark', ...
                'analysis_label', 'Synthetic Toolbox Benchmark', ...
                'verbose', false, ...
                'data_parts', {{bbPath}}, ...
                'part_start_offsets_s', 0, ...
                'part_end_offsets_s', part_duration_s, ...
                'part_dur_s', part_duration_s, ...
                'detector_defaults', detector_defaults, ...
                'signal_config', signal_config, ...
                'detector_parts', detector_part, ...
                'original_all_track_dets', [det_row, 1], ...
                'truth_diag_template', struct( ...
                    'adsb_files', {{}}, ...
                    'analysis_label', 'Synthetic Toolbox Benchmark', ...
                    'data_parts', {{bbPath}}, ...
                    'fs', signal_fixture.fs, ...
                    'fc', signal_fixture.fc));
        end

        function fixture = buildScopedReplayFixture(testCase)
            fixture = testCase.buildReplayFixture();
            replay_input = fixture.detector_replay_input;
            detector_part = replay_input.detector_parts;
            detector_block = detector_part.blocks;
            det_row = detector_part.original_detections;
            part_duration_s = replay_input.part_dur_s;

            block2 = detector_block;
            block2.block_num = 2;
            block2.t_part_center_s = 0.75 * part_duration_s;
            block2.t_abs_center_s = block2.t_part_center_s;

            det_row2 = det_row;
            det_row2(4) = 2;
            det_row2(5) = block2.t_part_center_s;

            part1 = detector_part;
            part1.original_detections = [det_row; det_row2];
            part1.blocks = [detector_block, block2];

            part2 = part1;
            part2.part_index = 2;
            part2.time_window_s = [part_duration_s, 2 * part_duration_s];
            for ib = 1 : numel(part2.blocks)
                part2.blocks(ib).t_abs_center_s = part2.blocks(ib).t_part_center_s + part_duration_s;
            end

            replay_input.data_parts = {replay_input.data_parts{1}, replay_input.data_parts{1}};
            replay_input.part_start_offsets_s = [0; part_duration_s];
            replay_input.part_end_offsets_s = [part_duration_s; 2 * part_duration_s];
            replay_input.detector_parts = [part1, part2];
            replay_input.original_all_track_dets = [ ...
                [part1.original_detections, ones(size(part1.original_detections, 1), 1)]; ...
                [part2.original_detections, 2 * ones(size(part2.original_detections, 1), 1)]];

            fixture.detector_replay_input = replay_input;
        end

        function fixture = buildSignalFixture(~)
            fs = 1e6;
            fc = 600e6;
            cpi_duration_s = 250e-6;
            prf = 1 / cpi_duration_s;
            N_fast = round(fs * cpi_duration_s);
            N_slow_cpi = 16;
            num_samples = N_fast * N_slow_cpi;
            detection_doppler_hz = 250;
            direct_delay_samp = 3;
            target_delay_samp = 17;

            reference_block = complex(randn(N_fast, N_slow_cpi), randn(N_fast, N_slow_cpi));
            direct_block = OfflineToolboxBenchmarkTest.delayColumns(reference_block, direct_delay_samp);
            target_block = OfflineToolboxBenchmarkTest.delayColumns(reference_block, target_delay_samp);
            slow_phase = exp(1j * 2 * pi * detection_doppler_hz * (0 : N_slow_cpi - 1) / prf);
            target_block = target_block .* slow_phase;

            surveillance_block = direct_block + 0.65 * target_block + ...
                0.02 * complex(randn(N_fast, N_slow_cpi), randn(N_fast, N_slow_cpi));

            c = physconst('LightSpeed');
            fixture = struct( ...
                'fs', fs, ...
                'fc', fc, ...
                'prf', prf, ...
                'cpi_duration_s', cpi_duration_s, ...
                'N_fast', N_fast, ...
                'N_slow_cpi', N_slow_cpi, ...
                'num_samples', num_samples, ...
                'reference_block', reference_block, ...
                'surveillance_block', surveillance_block, ...
                'reference_vector', reference_block(:), ...
                'surveillance_vector', surveillance_block(:), ...
                'direct_delay_samples', direct_delay_samp, ...
                'target_delay_samples', target_delay_samp, ...
                'detection_doppler_hz', detection_doppler_hz, ...
                'direct_path_delay_s', direct_delay_samp / fs, ...
                'range_guess_m', c * (target_delay_samp - direct_delay_samp + 1) / fs, ...
                'expected_range_m', c * (target_delay_samp - direct_delay_samp) / fs, ...
                'range_cell_m', c / fs);
        end

        function writeSyntheticBasebandFile(~, file_path, fs, fc, surv_vec, ref_vec)
            bbw = comm.BasebandFileWriter(file_path, ...
                'SampleRate', fs, ...
                'CenterFrequency', fc, ...
                'Metadata', struct('Label', 'OfflineToolboxBenchmarkTest'));
            raw_frame = complex(zeros(numel(surv_vec), 2, 'single'));
            raw_frame(:, 1) = single(surv_vec);
            raw_frame(:, 2) = single(ref_vec);
            bbw(raw_frame);
            release(bbw);
        end
    end

    methods (Static, Access = private)
        function delayed = delayColumns(signal_in, delay_samp)
            delayed = zeros(size(signal_in), 'like', signal_in);
            if delay_samp < size(signal_in, 1)
                delayed(delay_samp + 1 : end, :) = signal_in(1 : end - delay_samp, :);
            end
        end
    end
end
