classdef Stage4CNativeManeuverBaselineEvaluationTest < matlab.unittest.TestCase
    %STAGE4CNATIVEMANEUVERBASELINEEVALUATIONTEST Verify the native extension.

    properties
        ProjectRoot
        OutputFolder
        Summary
        FrozenHashesBefore
        FrozenArtifactPaths
    end

    methods (TestClassSetup)
        function runEvaluationFixture(testCase)
            testFolder = fileparts(mfilename("fullpath"));
            testCase.ProjectRoot = fileparts(testFolder);
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(testCase.ProjectRoot));
            tempFixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            testCase.OutputFolder = tempFixture.Folder;

            sourceFolder = fullfile( ...
                testCase.ProjectRoot, ...
                "artifacts", ...
                "stage4CRetrain");
            comparisonPath = fullfile( ...
                testCase.OutputFolder, ...
                "comparison.mat");
            metricPath = fullfile(testCase.OutputFolder, "metrics.csv");
            reportPath = fullfile(testCase.OutputFolder, "report.md");
            copyfile( ...
                fullfile( ...
                    sourceFolder, ...
                    "expandedPost3DayMeanMLPComparison_v1.mat"), ...
                comparisonPath);
            copyfile( ...
                fullfile( ...
                    sourceFolder, ...
                    "stage4CRetrainMetricComparison.csv"), ...
                metricPath);
            copyfile( ...
                fullfile( ...
                    sourceFolder, ...
                    "stage4CRetrainExpandedADSBMLPReport.md"), ...
                reportPath);

            testCase.FrozenArtifactPaths = [ ...
                fullfile( ...
                    testCase.ProjectRoot, ...
                    "artifacts", ...
                    "stage3", ...
                    "localADSBMLPStage3Training.mat"); ...
                fullfile( ...
                    sourceFolder, ...
                    "expandedPost3DayScratchMeanMLP_v1.mat"); ...
                fullfile( ...
                    sourceFolder, ...
                    "expandedPost3DayWarmStartMeanMLP_v1.mat")];
            testCase.FrozenHashesBefore = [ ...
                helperComputeFileSHA256( ...
                    testCase.FrozenArtifactPaths(1)); ...
                helperComputeFileSHA256( ...
                    testCase.FrozenArtifactPaths(2)); ...
                helperComputeFileSHA256( ...
                    testCase.FrozenArtifactPaths(3))];
            testCase.Summary = ...
                runStage4CNativeManeuverBaselineEvaluation( ...
                "ComparisonArtifactPath", ...
                comparisonPath, ...
                "MetricTablePath", ...
                metricPath, ...
                "ReportPath", ...
                reportPath, ...
                "FigurePath", ...
                fullfile(testCase.OutputFolder, "comparison.png"), ...
                "CreatePlots", ...
                false, ...
                "Verbose", ...
                false);
        end
    end

    methods (Test)
        function testConstaccStateOrderingAndExactPropagation(testCase)
            [previousState, dtSeconds, metadata, split, expected] = ...
                localConstantAccelerationFixture();

            actual = helperBuildStage4CNativeManeuverBaselines( ...
                previousState, ...
                dtSeconds, ...
                metadata, ...
                split);

            testCase.verifyEqual( ...
                actual.constaccStateOrder, ...
                ["x", "vx", "ax", "y", "vy", "ay", "z", "vz", "az"]);
            testCase.verifyEqual( ...
                actual.rawAccelerationMetersPerSecondSquared(2, :), ...
                [2, 4, 6], ...
                "AbsTol", ...
                1e-12);
            testCase.verifyEqual( ...
                actual.constaccPredictedState(2, :), ...
                expected, ...
                "AbsTol", ...
                1e-12);
        end

        function testConstturnStateOrderingAndExactPropagation(testCase)
            [previousState, dtSeconds, metadata, split, expected] = ...
                localConstantTurnFixture();

            actual = helperBuildStage4CNativeManeuverBaselines( ...
                previousState, ...
                dtSeconds, ...
                metadata, ...
                split);

            testCase.verifyEqual( ...
                actual.constturnStateOrder, ...
                ["x", "vx", "y", "vy", "omega_deg_per_s", "z", "vz"]);
            testCase.verifyEqual( ...
                actual.rawTurnRateDegreesPerSecond(2), ...
                90, ...
                "AbsTol", ...
                1e-12);
            testCase.verifyEqual( ...
                actual.constturnPredictedState(2, :), ...
                expected, ...
                "AbsTol", ...
                1e-12);
        end

        function testPredecessorEligibilityAndExclusionReasons(testCase)
            [previousState, dtSeconds, metadata, split, expectedReasons] = ...
                localEligibilityFixture();

            actual = helperBuildStage4CNativeManeuverBaselines( ...
                previousState, ...
                dtSeconds, ...
                metadata, ...
                split);

            testCase.verifyEqual(actual.exclusionReason, expectedReasons);
            testCase.verifyEqual( ...
                find(actual.eligibleMask), ...
                2);
            testCase.verifyEqual( ...
                actual.predecessorRowIndex([2, 4, 6, 8, 10]), ...
                [1; 3; 5; 7; 9]);
            testCase.verifyTrue(all(isfinite( ...
                actual.constaccPredictedState(actual.eligibleMask, :)), ...
                "all"));
            testCase.verifyTrue(all(isfinite( ...
                actual.constturnPredictedState(actual.eligibleMask, :)), ...
                "all"));
        end

        function testPredictionInterfaceCannotUseCurrentTarget(testCase)
            baseline = testCase.Summary.nativeManeuverBaseline;

            testCase.verifyEqual( ...
                nargin("helperBuildStage4CNativeManeuverBaselines"), ...
                4);
            testCase.verifyFalse(baseline.policy.targetStateUsed);
            testCase.verifyFalse(baseline.policy.maneuverLabelUsed);
            testCase.verifyEqual( ...
                baseline.policy.icaoUse, ...
                "same-session/ICAO predecessor grouping only");
        end

        function testFrozenValidationAndTestCoverage(testCase)
            coverage = sortrows( ...
                testCase.Summary.nativeManeuverBaseline.coverageTable, ...
                ["split", "maneuverSlice"]);
            expected = sortrows(table( ...
                ["validation"; "validation"; "test"; "test"], ...
                ["constacc_like"; "constturn_like"; ...
                "constacc_like"; "constturn_like"], ...
                [17030; 2084; 18028; 2186], ...
                [16896; 2075; 17890; 2164], ...
                [134; 9; 138; 22], ...
                'VariableNames', [ ...
                    "split", ...
                    "maneuverSlice", ...
                    "sourceSliceRowCount", ...
                    "eligibleRowCount", ...
                    "excludedRowCount"]), ...
                ["split", "maneuverSlice"]);

            testCase.verifyEqual( ...
                coverage(:, expected.Properties.VariableNames), ...
                expected);
        end

        function testEveryModelUsesMatchedRowsAndBothWeightings(testCase)
            extension = testCase.Summary.nativeManeuverBaseline;
            metrics = extension.metrics.table;
            groupedCounts = groupsummary( ...
                metrics, ...
                ["split", "groupName", "weighting"], ...
                ["min", "max"], ...
                "sampleCount");
            modelCounts = groupsummary( ...
                metrics, ...
                ["split", "groupName", "weighting"]);
            selectedCounts = cellfun( ...
                @numel, ...
                extension.selectionTable.datasetRowIndices);

            testCase.verifyEqual(height(metrics), 40);
            testCase.verifyEqual(unique(modelCounts.GroupCount), 5);
            testCase.verifyEqual( ...
                groupedCounts.min_sampleCount, ...
                groupedCounts.max_sampleCount);
            testCase.verifyEqual( ...
                selectedCounts, ...
                extension.coverageTable.eligibleRowCount);
            testCase.verifyEqual( ...
                sort(unique(metrics.weighting)), ...
                ["independent_event_weighted"; "pair_weighted"]);
            testCase.verifyFalse(any( ...
                (metrics.modelID == "constacc") & ...
                (metrics.groupName == "constturn_like")));
            testCase.verifyFalse(any( ...
                (metrics.modelID == "constturn") & ...
                (metrics.groupName == "constacc_like")));
            testCase.verifyTrue(all(isfinite( ...
                metrics.positionRMSEMeters)));
            testCase.verifyTrue(all(isfinite( ...
                metrics.velocityRMSEMetersPerSecond)));
        end

        function testNoTrainingAndFrozenArtifactsRemainUnchanged(testCase)
            integrity = ...
                testCase.Summary.nativeManeuverBaseline.frozenArtifactIntegrity;
            hashesAfter = [ ...
                helperComputeFileSHA256( ...
                    testCase.FrozenArtifactPaths(1)); ...
                helperComputeFileSHA256( ...
                    testCase.FrozenArtifactPaths(2)); ...
                helperComputeFileSHA256( ...
                    testCase.FrozenArtifactPaths(3))];
            sourceText = fileread(fullfile( ...
                testCase.ProjectRoot, ...
                "runStage4CNativeManeuverBaselineEvaluation.m"));

            testCase.verifyTrue(all(integrity.unchanged));
            testCase.verifyEqual( ...
                testCase.FrozenHashesBefore, ...
                hashesAfter);
            testCase.verifyFalse( ...
                testCase.Summary.nativeManeuverBaseline.trainingPerformed);
            testCase.verifyFalse(contains(sourceText, "trainnet("));
            testCase.verifyFalse(contains(sourceText, "trainingOptions("));
        end

        function testComparisonCsvAndReportAreExtended(testCase)
            comparisonPath = fullfile( ...
                testCase.OutputFolder, ...
                "comparison.mat");
            metricPath = fullfile(testCase.OutputFolder, "metrics.csv");
            reportPath = fullfile(testCase.OutputFolder, "report.md");
            loaded = load(comparisonPath, "stage4CSummary");
            metricTable = readtable(metricPath, "TextType", "string");
            reportText = string(fileread(reportPath));
            extensionRows = metricTable.groupDimension == ...
                "native_maneuver_baseline";

            testCase.verifyTrue( ...
                loaded.stage4CSummary.nativeManeuverBaseline.completed);
            testCase.verifyEqual(sum(extensionRows), 40);
            testCase.verifyTrue(contains( ...
                reportText, ...
                "raw_causal_finite_difference_v1"));
            testCase.verifyTrue(contains( ...
                reportText, ...
                "Turn-rate spikes"));
        end
    end
end

function [previousState, dtSeconds, metadata, split, expected] = ...
        localConstantAccelerationFixture()
%LOCALCONSTANTACCELERATIONFIXTURE Build one exact 3-D CA transition.

t0 = datetime(2026, 1, 1, 0, 0, 0, "TimeZone", "UTC");
previousState = [ ...
    0, 1, 10, 3, 20, 5; ...
    2, 3, 15, 7, 28, 11];
dtSeconds = [1; 2];
metadata = table( ...
    ["session"; "session"], ...
    ["icao"; "icao"], ...
    [t0; t0 + seconds(1)], ...
    [t0 + seconds(1); t0 + seconds(3)], ...
    'VariableNames', ["sessionID", "hex", "timeUtcK", "timeUtcNext"]);
split = ["validation"; "validation"];
expected = [12, 7, 37, 15, 62, 23];

end

function [previousState, dtSeconds, metadata, split, expected] = ...
        localConstantTurnFixture()
%LOCALCONSTANTTURNFIXTURE Build one exact +90-degree native turn.

t0 = datetime(2026, 1, 1, 0, 0, 0, "TimeZone", "UTC");
previousState = [ ...
    0, 1, 0, 0, 100, 2; ...
    2 / pi, 0, 2 / pi, 1, 102, 2];
dtSeconds = [1; 1];
metadata = table( ...
    ["session"; "session"], ...
    ["icao"; "icao"], ...
    [t0; t0 + seconds(1)], ...
    [t0 + seconds(1); t0 + seconds(2)], ...
    'VariableNames', ["sessionID", "hex", "timeUtcK", "timeUtcNext"]);
split = ["test"; "test"];
expected = [0, -1, 4 / pi, 0, 104, 2];

end

function [previousState, dtSeconds, metadata, split, expectedReasons] = ...
        localEligibilityFixture()
%LOCALELIGIBILITYFIXTURE Exercise each causal exclusion path.

t0 = datetime(2026, 1, 1, 0, 0, 0, "TimeZone", "UTC");
sessionID = [ ...
    "A"; "A"; "B"; "B"; "C"; ...
    "C"; "D"; "D"; "E"; "E"];
icao24 = [ ...
    "a"; "a"; "b"; "b"; "c"; ...
    "c"; "d"; "d"; "e"; "e"];
timeUtcK = t0 + seconds([0; 1; 0; 1; 0; 3; 0; 0; 0; 1]);
timeUtcNext = t0 + seconds([1; 2; 1; 2; 1; 4; 0; 1; 1; 2]);
metadata = table( ...
    sessionID, ...
    icao24, ...
    timeUtcK, ...
    timeUtcNext, ...
    'VariableNames', ["sessionID", "hex", "timeUtcK", "timeUtcNext"]);
previousState = repmat([0, 1, 0, 0, 100, 0], 10, 1);
previousState(9, 2) = NaN;
dtSeconds = [1; 1; 1; 1; 1; 1; 0; 1; 1; 1];
split = [ ...
    "validation"; "validation"; ...
    "validation"; "test"; ...
    "validation"; "validation"; ...
    "validation"; "validation"; ...
    "validation"; "validation"];
expectedReasons = [ ...
    "first_row_in_track"; ...
    "eligible"; ...
    "first_row_in_track"; ...
    "split_mismatch"; ...
    "first_row_in_track"; ...
    "nonadjacent_predecessor"; ...
    "first_row_in_track"; ...
    "nonpositive_prior_dt"; ...
    "first_row_in_track"; ...
    "nonfinite_input"];

end
