classdef Stage4BPostDatasetTest < matlab.unittest.TestCase
    %STAGE4BPOSTDATASETTEST Verify versioning, integration, and motion gates.

    properties
        ProjectRoot
    end

    methods (TestClassSetup)
        function addProjectPath(testCase)
            testFolder = fileparts(mfilename("fullpath"));
            testCase.ProjectRoot = fileparts(testFolder);
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(testCase.ProjectRoot));
        end
    end

    methods (Test)
        function testIntegratedVariantMembershipIsExact(testCase)
            manifestPath = fullfile( ...
                testCase.ProjectRoot, ...
                "adsb_archive", ...
                "datasetVersions", ...
                "adsbDatasetVariants.csv");
            manifest = readtable(manifestPath, "TextType", "string");

            legacy = logical(manifest.legacy_pre3day_v1);
            increment = logical(manifest.campaign_3day_increment_v1);
            expanded = logical(manifest.expanded_post3day_v2);

            testCase.verifyEqual(sum(legacy), 16);
            testCase.verifyEqual(sum(increment), 143);
            testCase.verifyEqual(sum(expanded), 159);
            testCase.verifyFalse(any(legacy & increment));
            testCase.verifyEqual(expanded, legacy | increment);
            testCase.verifyEqual( ...
                numel(unique(manifest.relativeSourceFile)), ...
                height(manifest));
            testCase.verifyEqual( ...
                numel(unique(manifest.sourceFileSHA256)), ...
                height(manifest));
        end

        function testIntegratedManifestHashesMatchSources(testCase)
            manifestPath = fullfile( ...
                testCase.ProjectRoot, ...
                "adsb_archive", ...
                "datasetVersions", ...
                "adsbDatasetVariants.csv");
            manifest = readtable(manifestPath, "TextType", "string");
            hashesMatch = localManifestHashesMatch( ...
                testCase.ProjectRoot, ...
                manifest);

            testCase.verifyTrue(hashesMatch);
        end

        function testIntegrationArtifactRecordsValidatedCampaign(testCase)
            artifactPath = fullfile( ...
                testCase.ProjectRoot, ...
                "artifacts", ...
                "stage4BPostCampaign", ...
                "integration", ...
                "stage4BThreeDayIntegration.mat");
            loaded = load(artifactPath, "integrationSummary");
            summary = loaded.integrationSummary;

            testCase.verifyTrue(summary.truthImportValidated);
            testCase.verifyEqual(summary.sessionCount, 144);
            testCase.verifyEqual(summary.truthFileCount, 143);
            testCase.verifyEqual(sum(summary.sessionTable.logFileCount), 288);
            testCase.verifyEqual( ...
                summary.noTruthSessionIDs, ...
                "stage4B_3Day_nohup_20260819T132526Z_w133_20260822T072740Z");
        end

        function testVariantRunnerRejectsUnknownID(testCase)
            testCase.verifyError( ...
                @() runADSBDatasetVariantEvaluation("unknown_variant"), ...
                "ADSBDataVersion:InvalidVariantID");
        end

        function testIntegrationIsIdempotent(testCase)
            fixture = localCreateIntegrationFixture();
            testCase.addTeardown(@() localRemoveFolder(fixture.root));
            firstSummary = integrateStage4BThreeDayArchive(fixture.arguments{:});
            secondSummary = integrateStage4BThreeDayArchive(fixture.arguments{:});

            testCase.verifyEqual(firstSummary.copiedSessionCount, 1);
            testCase.verifyEqual(secondSummary.copiedSessionCount, 0);
            testCase.verifyEqual(secondSummary.identicalSessionCount, 1);
            testCase.verifyEqual(secondSummary.truthFileCount, 1);
            testCase.verifyEqual(sum(secondSummary.sessionTable.logFileCount), 2);
        end

        function testIntegrationRefusesDifferingSession(testCase)
            fixture = localCreateIntegrationFixture();
            testCase.addTeardown(@() localRemoveFolder(fixture.root));
            integrateStage4BThreeDayArchive(fixture.arguments{:});
            writelines( ...
                "changed after integration", ...
                fixture.destinationTruthPath);

            testCase.verifyError( ...
                @() integrateStage4BThreeDayArchive(fixture.arguments{:}), ...
                "Stage4BPost:SessionCollision");
        end

        function testSustainedEventSegmentation(testCase)
            pairTable = localSyntheticMotionPairTable();
            events = helperSegmentADSBMotionEvents( ...
                pairTable, ...
                "synthetic_variant");

            testCase.verifyEqual( ...
                sum(events.eventType == "sustained_turn"), ...
                1);
            testCase.verifyEqual( ...
                sum(events.eventType == "sustained_acceleration"), ...
                0);
            testCase.verifyEqual( ...
                sum(events.eventType == "sustained_climb"), ...
                1);
            testCase.verifyEqual( ...
                sum(events.eventType == "sparse_gap"), ...
                2);
        end

        function testProspectiveSplitsDoNotLeak(testCase)
            [pairTable, eventTable] = localSyntheticSplitTables();
            audit = helperAuditADSBProspectiveSplits(pairTable, eventTable);

            testCase.verifyFalse(audit.aircraftLeakage);
            testCase.verifyFalse(audit.chronologicalSessionLeakage);
            testCase.verifyEqual( ...
                height(audit.aircraftAssignment), ...
                numel(unique(audit.aircraftAssignment.hex)));
            testCase.verifyEqual( ...
                height(audit.chronologicalSessionAssignment), ...
                numel(unique(audit.chronologicalSessionAssignment.sessionID)));
            testCase.verifyTrue(all( ...
                audit.normalizationAudit.normalizationSource == "train_only"));
        end

        function testLegacyRegressionArtifact(testCase)
            artifactPath = fullfile( ...
                testCase.ProjectRoot, ...
                "artifacts", ...
                "stage4BPostCampaign", ...
                "legacy_pre3day_v1", ...
                "stage3CArchiveADSBEvaluation.mat");
            loaded = load(artifactPath, "stage3CSummary");
            summary = loaded.stage3CSummary;
            metrics = summary.metricComparisonTable;

            testCase.verifyEqual(summary.archiveSummary.sourceFileCount, 16);
            testCase.verifyEqual(summary.archiveSummary.usableSessionCount, 16);
            testCase.verifyEqual(summary.archiveSummary.usablePairCount, 15013);
            testCase.verifyEqual(summary.archiveSummary.aircraftTrackCount, 222);
            testCase.verifyEqual( ...
                summary.stage3BSummary.dataReadiness.constturnLikePairCount, ...
                350);
            testCase.verifyEqual( ...
                summary.stage3BSummary.dataReadiness.sparseUpdatePairCount, ...
                336);
            testCase.verifyEqual( ...
                metrics.positionRMSEMeters(metrics.method == "constvel baseline"), ...
                23.870442, ...
                "AbsTol", ...
                1e-3);
            testCase.verifyEqual( ...
                metrics.positionRMSEMeters( ...
                metrics.method == "Frozen Stage 3A delta MLP"), ...
                151.260496, ...
                "AbsTol", ...
                1e-3);
            testCase.verifyFalse(summary.retrainingRun);
        end

        function testComparisonArtifactKeepsVerdictsSeparate(testCase)
            artifactPath = fullfile( ...
                testCase.ProjectRoot, ...
                "artifacts", ...
                "stage4BPostCampaign", ...
                "comparison", ...
                "stage4BPostCampaignMotionDiversity.mat");
            loaded = load(artifactPath, "comparison");
            comparison = loaded.comparison;

            testCase.verifyFalse(comparison.retrainingRun);
            testCase.verifyFalse(comparison.broadGeneralizationReady);
            testCase.verifyTrue(ismember( ...
                "expanded_minus_legacy", ...
                comparison.variantSummaryTable.variantID));
            testCase.verifyEqual(height(comparison.readinessGateTable), 12);
        end
    end
end

function hashesMatch = localManifestHashesMatch(projectRoot, manifest)
%LOCALMANIFESTHASHESMATCH Check every frozen source digest.

hashesMatch = true;

for rowIdx = 1:height(manifest)
    sourcePath = fullfile( ...
        projectRoot, ...
        replace(manifest.relativeSourceFile(rowIdx), "/", filesep));
    hashesMatch = hashesMatch && ...
        strcmpi( ...
        helperComputeFileSHA256(sourcePath), ...
        manifest.sourceFileSHA256(rowIdx));
end

end

function fixture = localCreateIntegrationFixture()
%LOCALCREATEINTEGRATIONFIXTURE Build a one-session ZIP and empty archive.

root = string(tempname) + "_stage4BPostTest";
sourceRoot = fullfile(root, "source");
captureRoot = fullfile(sourceRoot, "captures");
sessionID = "test_campaign_w001_20260819T132526Z";
sessionRoot = fullfile(captureRoot, sessionID);
truthFolder = fullfile(sessionRoot, "truth");
logFolder = fullfile(sessionRoot, "logs");
mkdir(truthFolder);
mkdir(logFolder);
truthName = "test_adsb.txt.gz";
coordinatorLog = "coordinator.log";
captureLog = "capture.log";
writelines("dummy gzip fixture", fullfile(truthFolder, truthName));
writelines("coordinator", fullfile(logFolder, coordinatorLog));
writelines("capture", fullfile(logFolder, captureLog));

manifest = struct();
manifest.session_id = sessionID;
manifest.campaign_id = "test_campaign";
manifest.window_id = "w001";
manifest.actual_start_utc = "2026-08-19T13:25:26Z";
manifest.capture_type = "adsb_only_holdout";
manifest.receiver_origin_lla = [42.2999333, -71.349333, 15.0];
% Preserve the production manifest contract: file lists are JSON arrays,
% including when a session contains only one truth file.
manifest.adsb_files = cellstr("truth/" + truthName);
manifest.log_files = ["logs/" + coordinatorLog, "logs/" + captureLog];
manifest.status = "complete";
writelines(jsonencode(manifest, PrettyPrint=true), ...
    fullfile(sessionRoot, "session_manifest.json"));

zipPath = fullfile(root, "campaign.zip");
zip(zipPath, "captures", sourceRoot);
archiveRoot = fullfile(root, "archive");
mkdir(archiveRoot);

arguments = { ...
    "ProjectRoot", root, ...
    "ZipPath", zipPath, ...
    "ArchiveRoot", archiveRoot, ...
    "VariantManifestPath", fullfile(root, "versions.csv"), ...
    "VariantSummaryPath", fullfile(root, "versions.md"), ...
    "ArtifactPath", fullfile(root, "integration.mat"), ...
    "CampaignID", "test_campaign", ...
    "ExpectedZipSHA256", "", ...
    "ExpectedSessionCount", 1, ...
    "ExpectedTruthFileCount", 1, ...
    "ExpectedLogFileCount", 2, ...
    "ExpectedNoTruthSessionCount", 0, ...
    "ExpectedNoTruthSessionID", "", ...
    "ExpectedLegacyTruthFileCount", 0, ...
    "ValidateTruthImport", false, ...
    "Verbose", false};

fixture = struct();
fixture.root = root;
fixture.arguments = arguments;
fixture.destinationTruthPath = fullfile( ...
    archiveRoot, ...
    "testing_machine", ...
    "captures", ...
    sessionID, ...
    "truth", ...
    truthName);

end

function pairTable = localSyntheticMotionPairTable()
%LOCALSYNTHETICMOTIONPAIRTABLE Build deterministic event boundaries.

pairCount = 12;
timeUtcK = datetime(2026, 8, 19, 14, 0, 0, "TimeZone", "UTC") + ...
    seconds((0:pairCount - 1).');
timeUtcNext = timeUtcK + seconds(1);
pairTable = table();
pairTable.sessionID = repmat("session_1", pairCount, 1);
pairTable.hex = repmat("abc123", pairCount, 1);
pairTable.timeUtcK = timeUtcK;
pairTable.timeUtcNext = timeUtcNext;
pairTable.dtSeconds = ones(pairCount, 1);
pairTable.isTurnLike = [true(3, 1); false(pairCount - 3, 1)];
pairTable.isAccelerationLike = [false(3, 1); true(2, 1); false(pairCount - 5, 1)];
pairTable.verticalStatus = categorical( ...
    repmat("climb", pairCount, 1), ...
    ["descent", "level", "climb"], ...
    ["descent", "level", "climb"]);
pairTable.isSparseUpdate = [false(pairCount - 2, 1); true(2, 1)];
pairTable.absTurnRateDegreesPerSecond = ...
    [2 * ones(3, 1); zeros(pairCount - 3, 1)];
pairTable.absHorizontalAccelerationMetersPerSecondSquared = ...
    [zeros(3, 1); ones(2, 1); zeros(pairCount - 5, 1)];
pairTable.absVerticalAccelerationMetersPerSecondSquared = zeros(pairCount, 1);
pairTable.verticalRateMetersPerSecond = 3 * ones(pairCount, 1);

end

function [pairTable, eventTable] = localSyntheticSplitTables()
%LOCALSYNTHETICSPLITTABLES Build three sessions and five aircraft.

pairCount = 15;
pairTable = table();
pairTable.sessionID = repelem(["session_1"; "session_2"; "session_3"], 5);
pairTable.hex = repmat(["a"; "b"; "c"; "d"; "e"], 3, 1);
pairTable.timeUtcK = datetime(2026, 8, 19, 13, 0, 0, "TimeZone", "UTC") + ...
    hours(repelem((0:2).', 5));
pairTable.maneuverClass = categorical( ...
    repmat("constvel_like", pairCount, 1), ...
    ["constvel_like", "constacc_like", "constturn_like", "mixed_or_sparse"]);
pairTable.verticalStatus = categorical( ...
    repmat("level", pairCount, 1), ...
    ["descent", "level", "climb"]);
pairTable.dtRegime = categorical( ...
    repmat("regular_update", pairCount, 1), ...
    ["regular_update", "sparse_update"]);
pairTable.previousState = zeros(pairCount, 6);

eventTable = table();
eventTable.eventType = repmat("sustained_turn", pairCount, 1);
eventTable.sessionID = pairTable.sessionID;
eventTable.hex = pairTable.hex;

end

function localRemoveFolder(folderPath)
%LOCALREMOVEFOLDER Remove one explicitly scoped test folder.

if isfolder(folderPath)
    rmdir(folderPath, "s");
end

end
