classdef Stage4DFrozenWarmCharacterizationTest < matlab.unittest.TestCase
    %STAGE4DFROZENWARMCHARACTERIZATIONTEST Verify the standalone Stage 4D workflow.

    properties
        ProjectRoot
        OutputFolder
        Results
        WarmHashBefore
        CanonicalGlobeReview
        RealGlobeReview
    end

    methods (TestClassSetup)
        function runSmokeBenchmark(testCase)
            testFolder = fileparts(mfilename("fullpath"));
            testCase.ProjectRoot = fileparts(testFolder);
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(testCase.ProjectRoot));
            tempFixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            testCase.OutputFolder = tempFixture.Folder;
            warmPath = fullfile( ...
                testCase.ProjectRoot, ...
                "artifacts", ...
                "stage4CRetrain", ...
                "expandedPost3DayWarmStartMeanMLP_v1.mat");
            testCase.WarmHashBefore = helperComputeFileSHA256(warmPath);
            testCase.Results = runStage4DFrozenWarmCharacterization( ...
                BenchmarkMode="smoke", ...
                Seed=123, ...
                OutputFolder=testCase.OutputFolder, ...
                CreatePlots=false, ...
                Verbose=false);
            testCase.CanonicalGlobeReview = helperBuildStage4DGlobeReview( ...
                testCase.Results, ...
                ViewType="canonical", ...
                ObservationProfile="degraded");
            testCase.RealGlobeReview = helperBuildStage4DGlobeReview( ...
                testCase.Results, ...
                ViewType="real_adsb", ...
                ObservationProfile="burst_outage", ...
                RealEventRank=1);
        end
    end

    methods (Test)
        function testScenarioCountsAndConfiguration(testCase)
            results = testCase.Results;

            testCase.verifyEqual(height(results.canonicalCaseTable), 21);
            testCase.verifyEqual( ...
                results.syntheticEvidence.canonical.truthTrajectoryCount, ...
                7);
            testCase.verifyEqual( ...
                results.syntheticEvidence.inDistribution.truthTrajectoryCount, ...
                4);
            testCase.verifyEqual( ...
                results.syntheticEvidence.outOfDistribution.truthTrajectoryCount, ...
                2);
            testCase.verifyEqual( ...
                unique(results.syntheticEvidence.inDistribution. ...
                truthAuditTable.durationSeconds), ...
                120);
            testCase.verifyEqual( ...
                sort(results.syntheticObservationProfiles.profile), ...
                sort(["ideal"; "empirical_timing"; "degraded"]));
            testCase.verifyEqual( ...
                sort(results.realObservationProfiles.profile), ...
                sort([ ...
                    "baseline"; ...
                    "random_dropout_10"; ...
                    "random_dropout_25"; ...
                    "burst_outage"]));
        end

        function testDeterminismContinuityAndFiniteStates(testCase)
            verification = testCase.Results.verificationTable;
            requiredChecks = [ ...
                "deterministic_generation"; ...
                "continuous_synthetic_trajectories"; ...
                "monotonic_synthetic_time"; ...
                "finite_synthetic_states"; ...
                "finite_real_states"; ...
                "monotonic_real_time"];
            selected = verification( ...
                ismember(verification.check, requiredChecks), :);

            testCase.verifyEqual(height(selected), numel(requiredChecks));
            testCase.verifyTrue(all(selected.passed));
        end

        function testFrozenWarmArtifactIntegrity(testCase)
            results = testCase.Results;
            warmPath = fullfile( ...
                testCase.ProjectRoot, ...
                "artifacts", ...
                "stage4CRetrain", ...
                "expandedPost3DayWarmStartMeanMLP_v1.mat");
            warmHashAfter = helperComputeFileSHA256(warmPath);

            testCase.verifyEqual( ...
                testCase.WarmHashBefore, ...
                "1999F972DBDABE67F45953C52CD4CDB1620F1FECF1716C075F391064D3B32FFE");
            testCase.verifyEqual(warmHashAfter, testCase.WarmHashBefore);
            testCase.verifyEqual( ...
                results.artifactAudit.value( ...
                results.artifactAudit.check == "warm_model_identity"), ...
                "expanded_warm_mean_v1");
            testCase.verifyEqual( ...
                results.artifactAudit.value( ...
                results.artifactAudit.check == "loaded_scratch_model"), ...
                "false");
            testCase.verifyEqual( ...
                results.artifactAudit.value( ...
                results.artifactAudit.check == "loaded_stage3a_model"), ...
                "false");
        end

        function testTargetsAndInformationBoundaries(testCase)
            results = testCase.Results;
            syntheticTargets = unique(results.metricTable.targetReference( ...
                startsWith(results.metricTable.domain, "synthetic_")));
            realTargets = unique(results.metricTable.targetReference( ...
                results.metricTable.domain == "real_adsb"));
            sameInformationModels = sort(unique(results.metricTable.modelID( ...
                results.metricTable.comparisonFamily == "same_information")));
            causalModels = sort(unique(results.metricTable.modelID( ...
                results.metricTable.comparisonFamily == "causal_history")));

            testCase.verifyEqual( ...
                syntheticTargets, ...
                "latent_kinematic_truth");
            testCase.verifyEqual( ...
                realTargets, ...
                "next_retained_adsb_observation");
            testCase.verifyEqual( ...
                sameInformationModels, ...
                sort(["expanded_warm_mean_v1"; "constvel"]));
            testCase.verifyEqual( ...
                causalModels, ...
                sort([ ...
                    "expanded_warm_mean_v1"; ...
                    "constvel"; ...
                    "constacc"; ...
                    "constturn"]));
            testCase.verifyFalse(any( ...
                results.causalPolicy.usesTargetState));
            testCase.verifyFalse(any( ...
                results.causalPolicy.usesMotionLabel));
            testCase.verifyTrue(all( ...
                results.causalPolicy.usesPredecessorHistory));
        end

        function testMetricsConfidenceIntervalsAndMatchedRows(testCase)
            results = testCase.Results;
            requiredMetricVariables = [ ...
                "positionRMSEMeters"; ...
                "positionMedianErrorMeters"; ...
                "positionP95ErrorMeters"; ...
                "velocityRMSEMetersPerSecond"; ...
                "velocityMedianErrorMetersPerSecond"; ...
                "velocityP95ErrorMetersPerSecond"];
            metricValues = results.metricTable{ ...
                :, ...
                cellstr(requiredMetricVariables)};
            matchedCheck = results.verificationTable( ...
                results.verificationTable.check == "matched_model_rows", :);

            testCase.verifyTrue(all(isfinite(metricValues), "all"));
            testCase.verifyEqual( ...
                sort(unique(results.metricTable.weighting)), ...
                sort(["pair_weighted"; "independent_event_weighted"]));
            testCase.verifyTrue(all(matchedCheck.passed));
            testCase.verifyGreaterThan( ...
                height(results.eventWinRateTable), ...
                0);
            testCase.verifyGreaterThan( ...
                height(results.pairedConfidenceIntervalTable), ...
                0);
            testCase.verifyTrue(all(isfinite( ...
                results.pairedConfidenceIntervalTable. ...
                meanPositionRMSEDifferenceMeters)));
            testCase.verifyGreaterThan( ...
                height(results.transitionMetricTable), ...
                0);
            testCase.verifyGreaterThan( ...
                height(results.robustnessTable), ...
                0);
        end

        function testRealDropoutReconstruction(testCase)
            results = testCase.Results;
            realAudit = results.realEvidence.audit;
            realProfiles = unique(results.realDropoutTable.profile);

            testCase.verifyTrue(realAudit.baselineMatchesFrozenRows);
            testCase.verifyEqual( ...
                realAudit.baselinePairCount, ...
                realAudit.frozenTestPairCount);
            testCase.verifyEqual( ...
                sort(realProfiles), ...
                sort([ ...
                    "baseline"; ...
                    "random_dropout_10"; ...
                    "random_dropout_25"; ...
                    "burst_outage"]));
        end

        function testCanonicalGlobeReview(testCase)
            review = testCase.CanonicalGlobeReview;
            validationVariables = [ ...
                "finiteLLA", ...
                "monotonicTime", ...
                "predictionCountMatches"];

            testCase.verifyEqual( ...
                review.summaryTable.trajectoryCount, ...
                7);
            testCase.verifyEqual( ...
                review.summaryTable.trajectoryPathCount, ...
                42);
            testCase.verifyEqual(height(review.legendTable), 6);
            testCase.verifyEqual( ...
                review.summaryTable.scoringReference, ...
                "Latent kinematic truth");
            testCase.verifyTrue(all( ...
                review.validationTable{:, cellstr(validationVariables)}, ...
                "all"));
            testCase.verifyEqual( ...
                review.loadedModelID, ...
                "expanded_warm_mean_v1");
            testCase.verifyFalse(review.trainingPerformed);
            testCase.verifyFalse(review.modelPromoted);
            testCase.verifyFalse(review.recursiveForecast);
        end

        function testRealGlobeReview(testCase)
            review = testCase.RealGlobeReview;
            validationVariables = [ ...
                "finiteLLA", ...
                "monotonicTime", ...
                "predictionCountMatches"];

            testCase.verifyEqual( ...
                review.summaryTable.trajectoryCount, ...
                1);
            testCase.verifyEqual( ...
                review.summaryTable.trajectoryPathCount, ...
                6);
            testCase.verifyEqual(height(review.legendTable), 6);
            testCase.verifyEqual( ...
                review.summaryTable.scoringReference, ...
                "Next retained ADS-B observation");
            testCase.verifyTrue(all( ...
                review.validationTable{:, cellstr(validationVariables)}, ...
                "all"));
            testCase.verifyEqual( ...
                review.loadedModelID, ...
                "expanded_warm_mean_v1");
        end

        function testGlobeReviewRejectsInvalidSelections(testCase)
            testCase.verifyError( ...
                @() helperBuildStage4DGlobeReview( ...
                    testCase.Results, ...
                    ViewType="canonical", ...
                    ObservationProfile="unknown"), ...
                "Stage4DGlobe:UnknownObservationProfile");
            testCase.verifyError( ...
                @() helperBuildStage4DGlobeReview( ...
                    testCase.Results, ...
                    ViewType="real_adsb", ...
                    ObservationProfile="burst_outage", ...
                    RealEventRank=1000000), ...
                "Stage4DGlobe:RealEventRankUnavailable");
        end

        function testSavedArtifactsAndPlot(testCase)
            results = testCase.Results;
            testCase.addTeardown(@() close("all"));
            inputPlotOutput = helperPlotStage4DInputPreview( ...
                results.inputPreview, ...
                SavePath=results.paths.inputPreviewFigure);
            motionPlotOutput = helperPlotStage4DMotionComparison( ...
                results, ...
                SavePath=results.paths.motionComparisonFigure);
            plotOutput = helperPlotStage4DCharacterization( ...
                results, ...
                SavePath=results.paths.characterizationFigure);
            loaded = load(results.paths.results, "stage4DResults");

            testCase.verifyEqual(exist(results.paths.results, "file"), 2);
            testCase.verifyEqual(exist(results.paths.metricSummary, "file"), 2);
            testCase.verifyEqual(exist(results.paths.canonicalMetrics, "file"), 2);
            testCase.verifyEqual(exist(results.paths.eventWinRates, "file"), 2);
            testCase.verifyEqual( ...
                exist(results.paths.pairedConfidenceIntervals, "file"), ...
                2);
            testCase.verifyEqual(exist(results.paths.transitionMetrics, "file"), 2);
            testCase.verifyEqual(exist(results.paths.robustnessMetrics, "file"), 2);
            testCase.verifyEqual(exist(results.paths.runtime, "file"), 2);
            testCase.verifyEqual(exist(results.paths.verification, "file"), 2);
            testCase.verifyEqual(exist(inputPlotOutput.savePath, "file"), 2);
            testCase.verifyEqual(exist(motionPlotOutput.savePath, "file"), 2);
            testCase.verifyEqual(exist(plotOutput.savePath, "file"), 2);
            testCase.verifyTrue(loaded.stage4DResults.completed);
        end

        function testInputPreviewIsDeterministicAndPredictionFree(testCase)
            preview = testCase.Results.inputPreview;
            rerun = runStage4DFrozenWarmCharacterization( ...
                BenchmarkMode="smoke", ...
                Seed=123, ...
                OutputFolder=testCase.OutputFolder, ...
                CreatePlots=false, ...
                Verbose=false);

            testCase.verifyEqual( ...
                rerun.inputPreview.observationTimeSeconds, ...
                preview.observationTimeSeconds, ...
                AbsTol=0);
            testCase.verifyEqual( ...
                rerun.inputPreview.observationState, ...
                preview.observationState, ...
                AbsTol=0);
            testCase.verifyFalse(preview.containsPredictions);
            testCase.verifyEqual(preview.profile, "degraded");
            previewFields = setdiff( ...
                string(fieldnames(preview)), ...
                "containsPredictions");
            testCase.verifyFalse(any(contains( ...
                previewFields, ...
                ["prediction", "predicted"], ...
                IgnoreCase=true), ...
                "all"));
        end

        function testLiveScriptLoadsSavedResultsHeadlessly(testCase)
            scriptPath = fullfile( ...
                testCase.ProjectRoot, ...
                "stage4DFrozenWarmCharacterizationLiveScript.m"); %#ok<NASGU>
            previousFigureVisibility = get(groot, "defaultFigureVisible");
            testCase.addTeardown(@() close("all"));
            testCase.addTeardown(@() set( ...
                groot, ...
                "defaultFigureVisible", ...
                previousFigureVisibility));
            set(groot, "defaultFigureVisible", "off");
            stage4DBenchmarkMode = "smoke"; %#ok<NASGU>
            regenerateStage4DResults = false; %#ok<NASGU>
            stage4DRandomSeed = 123; %#ok<NASGU>
            generateStage4DPlots = false; %#ok<NASGU>
            enableStage4DInteractiveGlobe = false; %#ok<NASGU>
            stage4DCanonicalGlobeProfile = "degraded"; %#ok<NASGU>
            stage4DRealGlobeProfile = "burst_outage"; %#ok<NASGU>
            stage4DRealGlobeEventRank = 1; %#ok<NASGU>
            stage4DOutputFolder = testCase.OutputFolder; %#ok<NASGU>
            commandWindowOutput = evalc("run(scriptPath);"); %#ok<NASGU>

            testCase.verifyTrue(exist("stage4DResults", "var") == 1);
            testCase.verifyTrue(exist("stage4DArtifactAudit", "var") == 1);
            testCase.verifyTrue(exist("stage4DCanonicalMetrics", "var") == 1);
            testCase.verifyTrue(exist("stage4DMixedMotionMetrics", "var") == 1);
            testCase.verifyTrue(exist("stage4DRealDropoutMetrics", "var") == 1);
            testCase.verifyTrue(exist("stage4DCanonicalGlobeReview", "var") == 1);
            testCase.verifyTrue(exist("stage4DRealGlobeReview", "var") == 1);
            testCase.verifyTrue(exist("stage4DCanonicalGlobeStatus", "var") == 1);
            testCase.verifyTrue(exist("stage4DRealGlobeStatus", "var") == 1);
            testCase.verifyEqual( ...
                stage4DCanonicalGlobeReview.summaryTable.trajectoryCount, ...
                7);
            testCase.verifyEqual( ...
                stage4DRealGlobeReview.summaryTable.trajectoryCount, ...
                1);
            testCase.verifyTrue(exist("stage4DNextDecision", "var") == 1);
            testCase.verifyTrue(stage4DResults.completed);
        end

        function testPlainTextLiveScriptContract(testCase)
            scriptPath = fullfile( ...
                testCase.ProjectRoot, ...
                "stage4DFrozenWarmCharacterizationLiveScript.m");
            sourceText = string(fileread(scriptPath));
            lines = splitlines(sourceText);
            requiredSections = [ ...
                "## 1. Purpose And Result Source"; ...
                "## 2. What The Degraded Input Looks Like"; ...
                "## 3. Frozen Model And Integrity Checks"; ...
                "## 4. Synthetic Conditions"; ...
                "## 5. Motion Type Changes The One-Step Error"; ...
                "## 6. Mixed Motion And Held-Out ADS-B"; ...
                "## 7. Headline Metrics And Robustness"; ...
                "## 8. Canonical Globe Review"; ...
                "## 9. Held-Out ADS-B Globe Review"; ...
                "## 10. Conclusion"];

            testCase.verifyTrue(contains(sourceText, "%[text:tableOfContents]"));
            testCase.verifyTrue(all(contains(sourceText, requiredSections)));
            testCase.verifyTrue(contains(sourceText, "helperOpenStage4DGlobe"));
            testCase.verifyTrue(contains(sourceText, ...
                "enableStage4DInteractiveGlobe"));
            testCase.verifyTrue(contains( ...
                sourceText, ...
                "%[appendix]{""version"":""1.0""}"));
            testCase.verifyFalse(contains(sourceText, "mfilename"));
            testCase.verifyFalse(contains(sourceText, "figure("));
            testCase.verifyFalse(contains(sourceText, "%[output:"));
            testCase.verifyFalse(any(strlength(lines(1:end - 1)) == 0));
        end
    end
end
