classdef Stage4ERecursiveFilterEvaluationTest < matlab.unittest.TestCase
    %STAGE4ERECURSIVEFILTEREVALUATIONTEST Verify recursive filter evaluation.

    properties
        ProjectRoot
        OutputFolder
        Results
        WarmHashBefore
        SyntheticGlobeReview
        RealGlobeReview
    end

    methods (TestClassSetup)
        function runSmokeBenchmark(testCase)
            testFolder = fileparts(mfilename("fullpath"));
            testCase.ProjectRoot = fileparts(testFolder);
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(testCase.ProjectRoot));
            tempFixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            testCase.OutputFolder = tempFixture.Folder;
            tuningPath = fullfile( ...
                testCase.ProjectRoot, ...
                "artifacts", ...
                "stage4ERecursiveFilterEvaluation", ...
                "stage4EFilterTuning.mat");
            testCase.assertEqual(exist(tuningPath, "file"), 2, ...
                "Generate the frozen validation-only Stage 4E tuning artifact first.");
            warmPath = fullfile( ...
                testCase.ProjectRoot, ...
                "artifacts", ...
                "stage4CRetrain", ...
                "expandedPost3DayWarmStartMeanMLP_v1.mat");
            testCase.WarmHashBefore = helperComputeFileSHA256(warmPath);
            testCase.Results = runStage4ERecursiveFilterEvaluation( ...
                BenchmarkMode="smoke", ...
                Seed=123, ...
                OutputFolder=testCase.OutputFolder, ...
                CreatePlots=false, ...
                Verbose=false);
            testCase.SyntheticGlobeReview = helperBuildStage4EGlobeReview( ...
                testCase.Results, ...
                ViewType="synthetic");
            testCase.RealGlobeReview = helperBuildStage4EGlobeReview( ...
                testCase.Results, ...
                ViewType="real_adsb");
        end
    end

    methods (Test)
        function testFilterTypesAndCommonInitialization(testCase)
            initialState = [100; 21; -40; 7; 1800; -2];
            covarianceDiag = [900; 25; 900; 25; 1600; 9];
            attributes = struct( ...
                "InitialVelocity", initialState([2, 4, 6]).', ...
                "InitialCovarianceDiag", covarianceDiag.');
            detection = objectDetection( ...
                0, ...
                initialState([1, 3, 5]), ...
                MeasurementNoise=diag([30, 30, 45].^2), ...
                ObjectAttributes={attributes});

            cvFilter = helperInitializeStage4EFilter(detection, "cv_ekf");
            caFilter = helperInitializeStage4EFilter(detection, "ca_ekf");
            ctFilter = helperInitializeStage4EFilter(detection, "ct_ekf");
            immFilter = helperInitializeStage4EFilter(detection, "native_imm");
            warmFilter = helperInitializeStage4EFilter(detection, "warm_ukf");

            testCase.verifyClass(cvFilter, "trackingEKF");
            testCase.verifyClass(caFilter, "trackingEKF");
            testCase.verifyClass(ctFilter, "trackingEKF");
            testCase.verifyClass(immFilter, "trackingIMM");
            testCase.verifyClass(warmFilter, "trackingUKF");
            testCase.verifyEqual(cvFilter.State, initialState, AbsTol=0);
            testCase.verifyEqual( ...
                caFilter.State([1, 2, 4, 5, 7, 8]), ...
                initialState, ...
                AbsTol=0);
            testCase.verifyEqual( ...
                ctFilter.State([1, 2, 3, 4, 6, 7]), ...
                initialState, ...
                AbsTol=0);
            testCase.verifyEqual( ...
                immFilter.State, ...
                initialState, ...
                AbsTol=1e-10);
            testCase.verifyEqual(warmFilter.State, initialState, AbsTol=0);
            testCase.verifyEqual( ...
                diag(cvFilter.StateCovariance), ...
                covarianceDiag, ...
                AbsTol=0);
            testCase.verifyEqual(string(func2str(cvFilter.MeasurementFcn)), "cvmeas");
            testCase.verifyEqual(string(func2str(caFilter.MeasurementFcn)), "cameas");
            testCase.verifyEqual(string(func2str(ctFilter.MeasurementFcn)), "ctmeas");
            testCase.verifyEqual(string(func2str(warmFilter.MeasurementFcn)), "cvmeas");
        end

        function testMatchedInputsAndCorrectionProtocol(testCase)
            results = testCase.Results;
            requiredChecks = [ ...
                "identical_filter_inputs"; ...
                "identical_filter_initialization"; ...
                "scheduled_corrections_applied"; ...
                "real_scoring_reports_never_corrected"; ...
                "same_real_scoring_rows_across_profiles"; ...
                "deterministic_real_dropout"; ...
                "monotonic_time"; ...
                "coasting_during_outages"];
            selected = results.verificationTable( ...
                ismember(results.verificationTable.check, requiredChecks), :);

            testCase.verifyEqual(height(selected), numel(requiredChecks));
            testCase.verifyTrue(all(selected.passed));
            testCase.verifyFalse(results.realProtocol.scoringReportsUsedForCorrection);
            testCase.verifyTrue(results.realProtocol.sameScoringRowsAcrossProfiles);
            testCase.verifyTrue(all( ...
                results.inputAuditTable.actualCorrectionCount == ...
                results.inputAuditTable.scheduledCorrectionCount));
        end

        function testSyntheticMotionAndConsistencyMetrics(testCase)
            results = testCase.Results;
            syntheticRows = startsWith( ...
                results.metricTable.domain, ...
                "synthetic_");
            syntheticMetrics = results.metricTable(syntheticRows, :);
            requiredMotions = [ ...
                "cv_level"; ...
                "cv_climb"; ...
                "horizontal_acceleration"; ...
                "vertical_acceleration"; ...
                "left_turn"; ...
                "right_turn"; ...
                "motion_transitions"];
            canonicalRows = results.eventMetricTable.domain == ...
                "synthetic_canonical";
            canonicalMotions = unique( ...
                results.eventMetricTable.motionScenario(canonicalRows));

            testCase.verifyTrue(all(ismember(requiredMotions, canonicalMotions)));
            testCase.verifyTrue(all(isfinite( ...
                syntheticMetrics.positionRMSEMeters)));
            testCase.verifyTrue(all(isfinite( ...
                syntheticMetrics.velocityRMSEMetersPerSecond)));
            testCase.verifyTrue(all(isfinite(syntheticMetrics.meanNEES)));
            testCase.verifyTrue(all(isfinite(syntheticMetrics.stateCoverage95)));
            testCase.verifyTrue(all(isfinite( ...
                syntheticMetrics.positionCoverage95)));
            testCase.verifyGreaterThanOrEqual( ...
                syntheticMetrics.stateCoverage95, ...
                zeros(height(syntheticMetrics), 1));
            testCase.verifyLessThanOrEqual( ...
                syntheticMetrics.stateCoverage95, ...
                ones(height(syntheticMetrics), 1));
        end

        function testRealADSBProxyMetrics(testCase)
            results = testCase.Results;
            realRows = results.metricTable.domain == "real_adsb";
            realMetrics = results.metricTable(realRows, :);
            profileNames = unique(realMetrics.profile);

            testCase.verifyEqual( ...
                sort(profileNames), ...
                sort([ ...
                    "baseline"; ...
                    "random_dropout_10"; ...
                    "random_dropout_25"; ...
                    "burst_outage"]));
            testCase.verifyTrue(all( ...
                realMetrics.targetReference == "adsb_scoring_proxy"));
            testCase.verifyTrue(all(isfinite( ...
                realMetrics.positionRMSEMeters)));
            testCase.verifyTrue(all(isfinite( ...
                realMetrics.velocityRMSEMetersPerSecond)));
            testCase.verifyTrue(all(isnan(realMetrics.meanNEES)));
            testCase.verifyTrue(all(isnan(realMetrics.stateCoverage95)));
            testCase.verifyGreaterThan( ...
                height(results.eventWinRateTable), ...
                0);
        end

        function testFiniteStatesCovarianceAndNIS(testCase)
            results = testCase.Results;
            requiredChecks = [ ...
                "finite_recursive_states"; ...
                "positive_definite_covariance"];
            selected = results.verificationTable( ...
                ismember(results.verificationTable.check, requiredChecks), :);

            testCase.verifyTrue(all(selected.passed));
            testCase.verifyEqual( ...
                sum(results.eventMetricTable.divergenceCount), ...
                0);
            testCase.verifyEqual( ...
                sum(results.eventMetricTable.invalidCovarianceCount), ...
                0);
            testCase.verifyTrue(all(strlength( ...
                results.inputAuditTable.errorIdentifier) == 0));
            testCase.verifyTrue(all(isfinite( ...
                results.consistencyTable.meanNIS)));
            testCase.verifyTrue(all(isfinite( ...
                results.consistencyTable.nisCoverage95)));
        end

        function testFrozenWarmArtifactAndTuningBoundary(testCase)
            results = testCase.Results;
            warmPath = fullfile( ...
                testCase.ProjectRoot, ...
                "artifacts", ...
                "stage4CRetrain", ...
                "expandedPost3DayWarmStartMeanMLP_v1.mat");
            warmHashAfter = helperComputeFileSHA256(warmPath);
            requiredChecks = [ ...
                "tuning_validation_only"; ...
                "tuning_frozen_before_test"; ...
                "no_neural_training"; ...
                "warm_hash_unchanged"; ...
                "warm_hash_matches_expected"];
            selected = results.verificationTable( ...
                ismember(results.verificationTable.check, requiredChecks), :);

            testCase.verifyEqual( ...
                testCase.WarmHashBefore, ...
                "1999F972DBDABE67F45953C52CD4CDB1620F1FECF1716C075F391064D3B32FFE");
            testCase.verifyEqual(warmHashAfter, testCase.WarmHashBefore);
            testCase.verifyTrue(all(selected.passed));
            testCase.verifyFalse(results.trainingPerformed);
            testCase.verifyFalse(results.networkPredictsCovariance);
            testCase.verifyFalse(results.associationEvaluated);
            testCase.verifyFalse(results.passiveRadarPerformanceEvaluated);
            testCase.verifyLessThanOrEqual( ...
                results.tuningSummary.validationSummary.maximumPairsPerEvent, ...
                120);
        end

        function testSavedArtifactsAndSummaryPlot(testCase)
            results = testCase.Results;
            testCase.addTeardown(@() close("all"));
            plotOutput = helperPlotStage4ERecursiveEvaluation( ...
                results, ...
                SavePath=results.paths.summaryFigure);
            loaded = load(results.paths.results, "stage4EResults");

            testCase.verifyEqual(exist(results.paths.results, "file"), 2);
            testCase.verifyEqual(exist(results.paths.metrics, "file"), 2);
            testCase.verifyEqual(exist(results.paths.eventMetrics, "file"), 2);
            testCase.verifyEqual(exist(results.paths.motionMetrics, "file"), 2);
            testCase.verifyEqual(exist(results.paths.outageMetrics, "file"), 2);
            testCase.verifyEqual(exist(results.paths.eventWinRates, "file"), 2);
            testCase.verifyEqual(exist(results.paths.consistency, "file"), 2);
            testCase.verifyEqual(exist(results.paths.runtime, "file"), 2);
            testCase.verifyEqual(exist(results.paths.inputAudit, "file"), 2);
            testCase.verifyEqual(exist(results.paths.verification, "file"), 2);
            testCase.verifyEqual(exist(plotOutput.savePath, "file"), 2);
            testCase.verifyTrue(loaded.stage4EResults.completed);
        end

        function testRepresentativeGlobeReviews(testCase)
            syntheticReview = testCase.SyntheticGlobeReview;
            realReview = testCase.RealGlobeReview;

            testCase.verifyEqual( ...
                syntheticReview.summaryTable.trajectoryPathCount, ...
                7);
            testCase.verifyEqual( ...
                realReview.summaryTable.trajectoryPathCount, ...
                7);
            testCase.verifyEqual( ...
                syntheticReview.summaryTable.scoringReference, ...
                "Latent kinematic truth");
            testCase.verifyEqual( ...
                realReview.summaryTable.scoringReference, ...
                "ADS-B scoring proxy");
            testCase.verifyTrue(all( ...
                syntheticReview.validationTable{:, 2:end}, ...
                "all"));
            testCase.verifyTrue(all( ...
                realReview.validationTable{:, 2:end}, ...
                "all"));
            testCase.verifyTrue(syntheticReview.recursiveEvaluation);
            testCase.verifyFalse(realReview.trainingPerformed);
        end

        function testGlobeReviewRejectsUnknownView(testCase)
            testCase.verifyError( ...
                @() helperBuildStage4EGlobeReview( ...
                    testCase.Results, ...
                    ViewType="unknown"), ...
                "Stage4EGlobe:UnknownViewType");
        end

        function testLiveScriptRunsHeadlessly(testCase)
            scriptPath = fullfile( ...
                testCase.ProjectRoot, ...
                "stage4ERecursiveFilterEvaluationLiveScript.m"); %#ok<NASGU>
            previousFigureVisibility = get(groot, "defaultFigureVisible");
            testCase.addTeardown(@() close("all"));
            testCase.addTeardown(@() set( ...
                groot, ...
                "defaultFigureVisible", ...
                previousFigureVisibility));
            set(groot, "defaultFigureVisible", "off");
            stage4EBenchmarkMode = "smoke"; %#ok<NASGU>
            regenerateStage4EResults = false; %#ok<NASGU>
            retuneStage4EFilters = false; %#ok<NASGU>
            stage4ERandomSeed = 123; %#ok<NASGU>
            generateStage4EPlots = false; %#ok<NASGU>
            enableStage4EInteractiveGlobe = false; %#ok<NASGU>
            stage4EOutputFolder = testCase.OutputFolder; %#ok<NASGU>
            commandWindowOutput = evalc("run(scriptPath);"); %#ok<NASGU>

            testCase.verifyTrue(exist("stage4EResults", "var") == 1);
            testCase.verifyTrue(exist("stage4EMetrics", "var") == 1);
            testCase.verifyTrue(exist("stage4EEventMetrics", "var") == 1);
            testCase.verifyTrue(exist("stage4EConsistency", "var") == 1);
            testCase.verifyTrue(exist("stage4ESyntheticGlobeReview", "var") == 1);
            testCase.verifyTrue(exist("stage4ERealGlobeReview", "var") == 1);
            testCase.verifyTrue(exist("stage4ESyntheticGlobeStatus", "var") == 1);
            testCase.verifyTrue(exist("stage4ERealGlobeStatus", "var") == 1);
            testCase.verifyTrue(stage4EResults.completed);
        end

        function testPlainTextLiveScriptAndScopeBoundary(testCase)
            scriptPath = fullfile( ...
                testCase.ProjectRoot, ...
                "stage4ERecursiveFilterEvaluationLiveScript.m");
            runnerPath = fullfile( ...
                testCase.ProjectRoot, ...
                "runStage4ERecursiveFilterEvaluation.m");
            evaluatorPath = fullfile( ...
                testCase.ProjectRoot, ...
                "helperEvaluateStage4ESequences.m");
            scriptText = string(fileread(scriptPath));
            implementationText = ...
                string(fileread(runnerPath)) + ...
                string(fileread(evaluatorPath));
            lines = splitlines(scriptText);

            testCase.verifyTrue(contains(scriptText, "%[text:tableOfContents]"));
            testCase.verifyTrue(contains( ...
                scriptText, ...
                "%[appendix]{""version"":""1.0""}"));
            testCase.verifyFalse(contains(scriptText, "mfilename"));
            testCase.verifyFalse(contains(scriptText, "figure("));
            testCase.verifyFalse(contains(scriptText, "%[output:"));
            testCase.verifyFalse(any(strlength(lines(1:end - 1)) == 0));
            testCase.verifyFalse(contains(implementationText, "trainnet("));
            testCase.verifyFalse(contains(implementationText, "trainingOptions("));
            testCase.verifyFalse(contains(implementationText, "trackerGNN("));
            testCase.verifyFalse(contains(implementationText, "trackerJPDA("));
            testCase.verifyFalse(contains(implementationText, "trackerTOMHT("));
        end
    end
end
