classdef Stage4CRetrainExpandedADSBMLPTest < matlab.unittest.TestCase
    %STAGE4CRETRAINEXPANDEDADSBMLPTEST Verify Stage 4C contracts and smoke run.

    properties
        ProjectRoot
        OutputFolder
        Summary
        Stage3AHashBefore
        ExpectedFeatureMean
        ExpectedTargetMean
    end

    methods (TestClassSetup)
        function runOneEpochFixture(testCase)
            testFolder = fileparts(mfilename("fullpath"));
            testCase.ProjectRoot = fileparts(testFolder);
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(testCase.ProjectRoot));
            tempFixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            testCase.OutputFolder = tempFixture.Folder;
            stage3APath = fullfile( ...
                testCase.ProjectRoot, ...
                "artifacts", ...
                "stage3", ...
                "localADSBMLPStage3Training.mat");
            testCase.Stage3AHashBefore = helperComputeFileSHA256(stage3APath);
            testCase.Summary = runStage4CRetrainExpandedADSBMLP( ...
                "OutputFolder", ...
                testCase.OutputFolder, ...
                "ScratchArtifactPath", ...
                fullfile(testCase.OutputFolder, "scratch.mat"), ...
                "WarmArtifactPath", ...
                fullfile(testCase.OutputFolder, "warm.mat"), ...
                "ComparisonArtifactPath", ...
                fullfile(testCase.OutputFolder, "comparison.mat"), ...
                "ReportPath", ...
                fullfile(testCase.OutputFolder, "report.md"), ...
                "MetricTablePath", ...
                fullfile(testCase.OutputFolder, "metrics.csv"), ...
                "MaxEpochs", ...
                1, ...
                "TinyEpochs", ...
                10, ...
                "CreatePlots", ...
                false, ...
                "ExecutionEnvironment", ...
                "cpu", ...
                "Verbose", ...
                false);
            [testCase.ExpectedFeatureMean, testCase.ExpectedTargetMean] = ...
                localIndependentTrainingMeans(testCase.ProjectRoot);
        end
    end

    methods (Test)
        function testFrozenDatasetAndGlobalICAOSplit(testCase)
            summary = testCase.Summary;

            testCase.verifyEqual(summary.datasetPairCount, 457903);
            testCase.verifyEqual( ...
                summary.splitAudit.summary.pairCount.', ...
                [277959, 86420, 93524]);
            testCase.verifyEqual( ...
                summary.splitAudit.summary.aircraftCount.', ...
                [1188, 395, 395]);
            testCase.verifyTrue(summary.splitAudit.everyICAOAssignedOnce);
            testCase.verifyFalse(summary.splitAudit.aircraftLeakage);
            testCase.verifyEqual( ...
                summary.splitAudit.inheritedOverlappingICAOCount, ...
                394);
            testCase.verifyTrue(summary.splitAudit.inheritedSplitIgnored);
            testCase.verifyTrue(summary.splitAudit.icaoUsedOnlyAsPartitionKey);
        end

        function testDatasetMembershipAndSourceHashes(testCase)
            provenance = testCase.Summary.datasetProvenance;

            testCase.verifyEqual( ...
                provenance.datasetVariantID, ...
                "expanded_post3day_v2");
            testCase.verifyEqual(provenance.sourceFileCount, 159);
            testCase.verifyTrue(provenance.datasetMembershipPassed);
            testCase.verifyTrue(provenance.sourceHashesVerified);
            testCase.verifyTrue(provenance.sourceHashAuditPassed);
            testCase.verifyTrue(all(provenance.sourceHashTable.passed));
            testCase.verifyEqual( ...
                provenance.datasetSHA256, ...
                "9B757A85A58DA6663F79524E6B287B06420DB0BF3480A7AA661E96792212EBDD");
            testCase.verifyEqual( ...
                provenance.variantManifestSHA256, ...
                "87B6D5C73046BC3EEC63CE17531EBC7B6E1D7E824D7254CD1C0D753BEB6221E4");
            testCase.verifyEqual( ...
                testCase.Summary.splitProvenance.splitManifestSHA256, ...
                "74CA2A3BC5E583C6C03E06395CA5D50C772F13C67B73148CA9FEB459322900DB");
        end

        function testNormalizationUsesTrainingRowsOnly(testCase)
            normalization = testCase.Summary.normalization;

            testCase.verifyEqual(normalization.computedFromSplit, "train");
            testCase.verifyEqual(normalization.trainRowCount, 277959);
            testCase.verifyEqual( ...
                normalization.features.featureMean, ...
                testCase.ExpectedFeatureMean, ...
                "AbsTol", ...
                1e-12);
            testCase.verifyEqual( ...
                normalization.target.targetMean, ...
                testCase.ExpectedTargetMean, ...
                "AbsTol", ...
                1e-12);
        end

        function testArchitectureAndWarmRebase(testCase)
            summary = testCase.Summary;

            testCase.verifyTrue(summary.architectureAudit.passed);
            testCase.verifyEqual(summary.architectureAudit.featureCount, 20);
            testCase.verifyEqual(summary.architectureAudit.hiddenUnits, 64);
            testCase.verifyEqual(summary.architectureAudit.outputCount, 6);
            testCase.verifyFalse( ...
                summary.architectureAudit.identityFeaturePresent);
            testCase.verifyTrue(summary.architectureAudit.memoryless);
            testCase.verifyTrue(summary.warmStartRebaseAudit.passed);
            testCase.verifyLessThanOrEqual( ...
                summary.warmStartRebaseAudit.maxAbsPhysicalStateDifference, ...
                summary.warmStartRebaseAudit.tolerance);
        end

        function testTinyOverfitAndOneEpochAreFinite(testCase)
            summary = testCase.Summary;

            testCase.verifyTrue(summary.completed);
            testCase.verifyEqual(summary.tinyOverfit.sampleCount, 128);
            testCase.verifyTrue(summary.tinyOverfit.passed);
            testCase.verifyTrue(isfinite( ...
                summary.scratchTraining.finalTrainingLoss));
            testCase.verifyTrue(isfinite( ...
                summary.scratchTraining.bestValidationLoss));
            testCase.verifyTrue(isfinite( ...
                summary.warmTraining.finalTrainingLoss));
            testCase.verifyTrue(isfinite( ...
                summary.warmTraining.bestValidationLoss));
            testCase.verifyTrue(all(isfinite( ...
                summary.metrics.table.positionRMSEMeters)));
            testCase.verifyTrue(all(isfinite( ...
                summary.metrics.table.velocityRMSEMetersPerSecond)));
        end

        function testArtifactsAreDistinctAndStage3ARemainsFrozen(testCase)
            summary = testCase.Summary;
            scratch = load(summary.scratchArtifactPath, "modelArtifact");
            warm = load(summary.warmArtifactPath, "modelArtifact");
            stage3AHashAfter = helperComputeFileSHA256( ...
                summary.stage3AIntegrity.path);

            testCase.verifyNotEqual( ...
                summary.scratchArtifactPath, ...
                summary.warmArtifactPath);
            testCase.verifyNotEqual( ...
                summary.scratchArtifactPath, ...
                summary.stage3AIntegrity.path);
            testCase.verifyNotEqual( ...
                summary.warmArtifactPath, ...
                summary.stage3AIntegrity.path);
            testCase.verifyEqual( ...
                scratch.modelArtifact.modelID, ...
                "expanded_scratch_mean_v1");
            testCase.verifyEqual( ...
                warm.modelArtifact.modelID, ...
                "expanded_warm_mean_v1");
            testCase.verifyEqual( ...
                testCase.Stage3AHashBefore, ...
                stage3AHashAfter);
            testCase.verifyEqual( ...
                stage3AHashAfter, ...
                "2459D134B9352E10EBC803419AD110784411515FE28ACCB4A1D88606A319B906");
            testCase.verifyTrue(summary.stage3AIntegrity.unchanged);
            testCase.verifyFalse(isfield( ...
                scratch.modelArtifact, ...
                "previousState"));
            testCase.verifyFalse(isfield( ...
                warm.modelArtifact, ...
                "nextState"));
        end

        function testAllModelsShareHoldoutMetricRows(testCase)
            metricTable = testCase.Summary.metrics.table;
            modelCounts = groupsummary(metricTable, "modelID");

            testCase.verifyEqual(height(modelCounts), 4);
            testCase.verifyEqual( ...
                numel(unique(modelCounts.GroupCount)), ...
                1);
            testCase.verifyEqual( ...
                sort(unique(metricTable.split)), ...
                ["test"; "validation"]);
            testCase.verifyEqual( ...
                sort(unique(metricTable.weighting)), ...
                ["independent_event_weighted"; "pair_weighted"]);
            testCase.verifyTrue(all(ismember( ...
                ["constvel_like"; ...
                "constacc_like"; ...
                "constturn_like"; ...
                "mixed_or_sparse"], ...
                metricTable.groupName)));
            testCase.verifyTrue(all(ismember( ...
                ["climb"; "descent"; "level"], ...
                metricTable.groupName)));
            testCase.verifyTrue(all(ismember( ...
                ["regular_update"; "sparse_update"], ...
                metricTable.groupName)));
        end

        function testTrainerUsesTrainnetWithoutCustomOptimizer(testCase)
            sourceText = fileread(fullfile( ...
                testCase.ProjectRoot, ...
                "runStage4CRetrainExpandedADSBMLP.m"));

            testCase.verifyTrue(contains(sourceText, "trainnet"));
            testCase.verifyTrue(contains(sourceText, "trainingOptions"));
            testCase.verifyTrue(contains(sourceText, "best-validation"));
            testCase.verifyFalse(contains(sourceText, "adamupdate"));
            testCase.verifyFalse(contains(sourceText, "dlfeval"));
        end
    end
end

function [featureMean, targetMean] = localIndependentTrainingMeans(projectRoot)
%LOCALINDEPENDENTTRAININGMEANS Recompute train-only means from frozen inputs.

datasetPath = fullfile( ...
    projectRoot, ...
    "artifacts", ...
    "stage4BPostCampaign", ...
    "expanded_post3day_v2", ...
    "stage3CArchiveStatePairDataset.mat");
splitPath = fullfile( ...
    projectRoot, ...
    "adsb_archive", ...
    "datasetVersions", ...
    "expandedPost3DayICAODisjointSplit_v1.csv");
dataset = load( ...
    datasetPath, ...
    "previousState", ...
    "nextState", ...
    "dtSeconds", ...
    "previousCovarianceDiag", ...
    "metadata", ...
    "baselineConstVelMetrics");
manifest = readtable(splitPath, "TextType", "string");
[found, manifestRow] = ismember( ...
    lower(string(dataset.metadata.hex)), ...
    lower(manifest.icao24));
assert(all(found));
split = manifest.split(manifestRow);
trainMask = split == "train";
features = helperBuildStage4CFeatures( ...
    dataset.previousState, ...
    dataset.previousCovarianceDiag, ...
    dataset.dtSeconds, ...
    dataset.baselineConstVelMetrics.predictedState);
targetDelta = dataset.nextState - dataset.previousState;
featureMean = mean(features.features(trainMask, :), 1, "omitnan");
targetMean = mean(targetDelta(trainMask, :), 1, "omitnan");

end
