classdef StageReviewLiveScriptTest < matlab.unittest.TestCase
    %STAGEREVIEWLIVESCRIPTTEST Verify the educational review artifact.

    properties
        ProjectRoot
        Stage4CDashboard
    end

    properties (TestParameter)
        stage4CTrajectoryCount = struct( ...
            "one", 1, ...
            "fifty", 50, ...
            "oneHundred", 100, ...
            "fiveHundred", 500, ...
            "oneThousand", 1000)
        invalidStage4CTrajectoryCount = struct( ...
            "zero", 0, ...
            "negative", -1, ...
            "fractional", 1.5, ...
            "infinite", Inf, ...
            "notANumber", NaN, ...
            "nonscalar", [1, 2], ...
            "text", "50")
    end

    methods (TestClassSetup)
        function buildReviewFixture(testCase)
            testFolder = fileparts(mfilename("fullpath"));
            testCase.ProjectRoot = fileparts(testFolder);
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(testCase.ProjectRoot));
            testCase.Stage4CDashboard = ...
                helperBuildStage4CReviewDashboard( ...
                "ProjectRoot", ...
                testCase.ProjectRoot);
        end
    end

    methods (Test)
        function testReviewArtifactsAlign(testCase)
            projectRoot = localProjectRoot();
            review = helperBuildStageReviewArtifacts("ProjectRoot", projectRoot);

            pairCount = size(review.dataset.nextState, 1);
            testCase.verifyEqual(height(review.pairReviewTable), pairCount);
            testCase.verifySize(review.constvelPredictedState, [pairCount, 6]);
            testCase.verifySize(review.nnPredictedNextState, [pairCount, 6]);
            testCase.verifyTrue(all(isfinite(review.constvelPredictedState), "all"));
            testCase.verifyTrue(all(isfinite(review.nnPredictedNextState), "all"));
            testCase.verifySize(review.stage3PredictedNextState, [pairCount, 6]);
            testCase.verifyTrue(isfield(review, "hasStage3B"));
            testCase.verifyTrue(review.hasStage4C);
            testCase.verifyTrue(review.hasStage4CNativeManeuverBaseline);
            testCase.verifyEqual( ...
                height(review.stage4CNativeMetricTable), ...
                40);
            testCase.verifyEqual( ...
                review.stage4CNativeManeuverBaseline.policy.policyID, ...
                "raw_causal_finite_difference_v1");
            if review.hasStage3B
                testCase.verifyGreaterThan(height(review.stage3BMetricComparisonTable), 0);
                testCase.verifyGreaterThan(height(review.stage3BPairErrorTable), 0);
            end
            testCase.verifyEqual(review.metricComparisonTable.method(1), "constvel baseline");
            testCase.verifyEqual(review.metricComparisonTable.method(2), "smoke MLP");
            testCase.verifyGreaterThan( ...
                review.metricComparisonTable.positionRMSEMeters(2), ...
                review.metricComparisonTable.positionRMSEMeters(1));
        end

        function testTrajectoryConversionIsFinite(testCase)
            review = helperBuildStageReviewArtifacts("ProjectRoot", localProjectRoot());
            trajectoryData = helperBuildStageReviewTrajectories( ...
                review, ...
                "TrackHex", review.defaultTrackHex, ...
                "MaxPairs", 20);

            testCase.verifyGreaterThan(numel(trajectoryData.timeSeconds), 2);
            testCase.verifyTrue(all(diff(trajectoryData.timeSeconds) > 0));
            testCase.verifyTrue(all(isfinite(trajectoryData.truthLLA), "all"));
            testCase.verifyTrue(all(isfinite(trajectoryData.constvelLLA), "all"));
            testCase.verifyTrue(all(isfinite(trajectoryData.nnSmokeLLA), "all"));
        end


        function testStage3AErrorComparisonHelper(testCase)
            review = helperBuildStageReviewArtifacts("ProjectRoot", localProjectRoot());
            cleanup = onCleanup(@() close("all"));

            errorComparison = helperPlotStageReviewStage3ErrorComparison( ...
                review, ...
                "TrackHex", review.defaultTrackHex, ...
                "MaxPairs", 20);

            if review.hasStage3A
                testCase.verifyEqual(height(errorComparison), 2);
                testCase.verifyEqual(errorComparison.method(1), "constvel");
                testCase.verifyEqual(errorComparison.method(2), "Stage 3A delta MLP");
                testCase.verifyTrue(all(isfinite(errorComparison.trackPositionRMSEMeters)));
            else
                testCase.verifyEqual(height(errorComparison), 1);
                testCase.verifyTrue(isnan(errorComparison.trackPositionRMSEMeters));
            end
        end

        function testExpandedDatasetPartitionsAndMatchedRMSE(testCase)
            dashboard = testCase.Stage4CDashboard;
            motionCounts = dashboard.motionClassSplitTable;
            rmseTable = dashboard.rmseTable;
            sectionCounts = groupsummary( ...
                rmseTable, ...
                ["motionClass", "split"], ...
                ["min", "max"], ...
                "sampleCount");
            nativeMapping = sortrows(unique(rmseTable( ...
                rmseTable.modelID == rmseTable.nativeModelID, ...
                ["motionClass", "nativeModelID"])), ...
                "motionClass");

            testCase.verifyEqual(dashboard.datasetPairCount, 457903);
            testCase.verifyEqual( ...
                dashboard.splitSummaryTable.pairCount.', ...
                [277959, 86420, 93524]);
            testCase.verifyEqual( ...
                motionCounts.total(1:4).', ...
                [330676, 88488, 10767, 27972]);
            testCase.verifyEqual(motionCounts.total(end), 457903);
            testCase.verifyEqual(height(rmseTable), 24);
            testCase.verifyEqual(sectionCounts.GroupCount, repmat(4, 6, 1));
            testCase.verifyEqual( ...
                sectionCounts.min_sampleCount, ...
                sectionCounts.max_sampleCount);
            testCase.verifyEqual( ...
                nativeMapping.motionClass, ...
                ["constacc_like"; "constturn_like"; "constvel_like"]);
            testCase.verifyEqual( ...
                nativeMapping.nativeModelID, ...
                ["constacc"; "constturn"; "constvel"]);
            testCase.verifyTrue(all( ...
                dashboard.modelIdentityTable.frozen));
            testCase.verifyEqual( ...
                dashboard.modelIdentityTable.sha256, ...
                [ ...
                    "2459D134B9352E10EBC803419AD110784411515FE28ACCB4A1D88606A319B906"; ...
                    "941AFD716E75BC6D75AA4799BDCF38BC8294F8850A3876EEB2D83B0B8883F81F"; ...
                    "1999F972DBDABE67F45953C52CD4CDB1620F1FECF1716C075F391064D3B32FFE"]);
            testCase.verifyFalse(dashboard.trainingPerformed);
            testCase.verifyFalse(dashboard.clippingApplied);
            testCase.verifyFalse(dashboard.smoothingApplied);
        end

        function testHeldOutTestRMSEPresentation(testCase)
            cleanup = onCleanup(@() close("all"));
            output = helperPlotStage4CRMSEDashboard( ...
                testCase.Stage4CDashboard.rmseTable);
            metricTable = output.metricTable;
            sectionCounts = groupsummary( ...
                metricTable, ...
                "motionClass", ...
                ["min", "max"], ...
                "sampleCount");
            nativeMapping = sortrows(unique(metricTable( ...
                metricTable.modelID == metricTable.nativeModelID, ...
                ["motionClass", "nativeModelID"])), ...
                "motionClass");
            neuralCounts = sortrows(groupsummary( ...
                metricTable( ...
                metricTable.modelID ~= metricTable.nativeModelID, :), ...
                "modelID"), ...
                "modelID");

            testCase.verifyEqual(height(metricTable), 12);
            testCase.verifyEqual(unique(metricTable.split), "test");
            testCase.verifyEqual(sectionCounts.GroupCount, repmat(4, 3, 1));
            testCase.verifyEqual( ...
                sectionCounts.min_sampleCount, ...
                sectionCounts.max_sampleCount);
            testCase.verifyEqual( ...
                nativeMapping.motionClass, ...
                ["constacc_like"; "constturn_like"; "constvel_like"]);
            testCase.verifyEqual( ...
                nativeMapping.nativeModelID, ...
                ["constacc"; "constturn"; "constvel"]);
            testCase.verifyEqual( ...
                neuralCounts.modelID, ...
                [ ...
                    "expanded_scratch_mean_v1"; ...
                    "expanded_warm_mean_v1"; ...
                    "legacy_stage3a_v1"]);
            testCase.verifyEqual(neuralCounts.GroupCount, repmat(3, 3, 1));
        end

        function testNeuralValidationTestRMSEPresentation(testCase)
            cleanup = onCleanup(@() close("all"));
            output = helperPlotStage4CNNValidationTest( ...
                testCase.Stage4CDashboard.rmseTable);
            metricTable = output.metricTable;
            sectionCounts = groupsummary( ...
                metricTable, ...
                ["motionClass", "split"], ...
                ["min", "max"], ...
                "sampleCount");
            modelCounts = sortrows( ...
                groupsummary(metricTable, "modelID"), ...
                "modelID");

            testCase.verifyEqual(height(metricTable), 18);
            testCase.verifyEqual( ...
                sort(unique(metricTable.split)), ...
                ["test"; "validation"]);
            testCase.verifyEqual(sectionCounts.GroupCount, repmat(3, 6, 1));
            testCase.verifyEqual( ...
                sectionCounts.min_sampleCount, ...
                sectionCounts.max_sampleCount);
            testCase.verifyEqual( ...
                modelCounts.modelID, ...
                [ ...
                    "expanded_scratch_mean_v1"; ...
                    "expanded_warm_mean_v1"; ...
                    "legacy_stage3a_v1"]);
            testCase.verifyEqual(modelCounts.GroupCount, repmat(6, 3, 1));
            testCase.verifyFalse(any( ...
                metricTable.modelID == metricTable.nativeModelID));
        end

        function testRepresentativeSelectionAndTrajectoryContracts(testCase)
            representatives = testCase.Stage4CDashboard.representatives;
            selectedPairCounts = [representatives.pairCount].';
            maximumEventCounts = arrayfun( ...
                @(value) max(value.eventTable.pairCount), ...
                representatives);
            monotonicTime = arrayfun( ...
                @(value) all(diff(value.timeSeconds) > 0), ...
                representatives);
            finiteLLA = arrayfun( ...
                @(value) all(isfinite([ ...
                value.truthLLA; ...
                value.nativeLLA; ...
                value.legacyLLA; ...
                value.scratchLLA; ...
                value.warmLLA]), ...
                "all"), ...
                representatives);
            expectedNeuralIDs = [ ...
                "expanded_scratch_mean_v1"; ...
                "expanded_warm_mean_v1"; ...
                "legacy_stage3a_v1"; ...
                "truth"];

            testCase.verifyEqual( ...
                string({representatives.motionClass}).', ...
                ["constvel_like"; "constacc_like"; "constturn_like"]);
            testCase.verifyEqual( ...
                [representatives.selectedTrajectory].', ...
                ones(3, 1));
            testCase.verifyEqual( ...
                [representatives.eligibleTrajectoryCount].', ...
                [12537; 10340; 1242]);
            testCase.verifyEqual(selectedPairCounts, [176; 40; 25]);
            testCase.verifyEqual( ...
                selectedPairCounts, ...
                maximumEventCounts(:));
            testCase.verifyTrue(all(monotonicTime));
            testCase.verifyTrue(all(finiteLLA));
            testCase.verifyTrue(all(startsWith( ...
                string({representatives.label}).', ...
                "Representative trajectory—1 of ")));
            testCase.verifyEqual( ...
                sort(representatives(1).legendTable.modelID), ...
                sort([expectedNeuralIDs; "constvel"]));
            testCase.verifyEqual( ...
                sort(representatives(2).legendTable.modelID), ...
                sort([expectedNeuralIDs; "constacc"]));
            testCase.verifyEqual( ...
                sort(representatives(3).legendTable.modelID), ...
                sort([expectedNeuralIDs; "constturn"]));
            testCase.verifyEqual( ...
                [ ...
                    height(representatives(1).legendTable); ...
                    height(representatives(2).legendTable); ...
                    height(representatives(3).legendTable)], ...
                repmat(5, 3, 1));
        end

        function testTrajectoryCollectionCountsAndRanking( ...
                testCase, stage4CTrajectoryCount)
            representative = testCase.Stage4CDashboard.representatives(1);
            collection = helperBuildStage4CTrajectoryCollection( ...
                testCase.Stage4CDashboard, ...
                "constvel_like", ...
                TrajectoryCount=stage4CTrajectoryCount);
            expectedEvents = representative.eventTable( ...
                1:stage4CTrajectoryCount, :);
            actualEvents = collection.eventTable( ...
                :, ...
                expectedEvents.Properties.VariableNames);
            trajectoryCounts = cellfun( ...
                @numel, ...
                struct2cell(collection.trajectories));

            testCase.verifyEqual( ...
                collection.requestedTrajectoryCount, ...
                stage4CTrajectoryCount);
            testCase.verifyEqual( ...
                collection.plottedTrajectoryCount, ...
                stage4CTrajectoryCount);
            testCase.verifyEqual( ...
                collection.trajectoryPathCount, ...
                5 * stage4CTrajectoryCount);
            testCase.verifyEqual(collection.plotCallCount, 5);
            testCase.verifyEqual( ...
                trajectoryCounts, ...
                repmat(stage4CTrajectoryCount, 5, 1));
            testCase.verifyEqual(actualEvents, expectedEvents);
            testCase.verifyTrue(all( ...
                collection.validationTable{:, 2:end}, ...
                "all"));
        end

        function testConstaccTrajectoryCollectionEligibility(testCase)
            collection = helperBuildStage4CTrajectoryCollection( ...
                testCase.Stage4CDashboard, ...
                "constacc_like", ...
                TrajectoryCount=50);

            testCase.verifyEqual(collection.nativeModelID, "constacc");
            testCase.verifyEqual(collection.plottedTrajectoryCount, 50);
            testCase.verifyEqual(collection.trajectoryPathCount, 250);
            testCase.verifyTrue(all( ...
                collection.validationTable{:, 2:end}, ...
                "all"));
        end

        function testTrajectoryCountAboveAvailabilityIsCapped(testCase)
            collection = helperBuildStage4CTrajectoryCollection( ...
                testCase.Stage4CDashboard, ...
                "constturn_like", ...
                TrajectoryCount=2000);

            testCase.verifyEqual(collection.requestedTrajectoryCount, 2000);
            testCase.verifyEqual(collection.plottedTrajectoryCount, 1242);
            testCase.verifyEqual(collection.eligibleTrajectoryCount, 1242);
            testCase.verifyEqual(collection.trajectoryPathCount, 6210);
            testCase.verifyTrue(collection.wasCapped);
            testCase.verifyTrue(all( ...
                collection.validationTable{:, 2:end}, ...
                "all"));
        end

        function testInvalidTrajectoryCountErrors( ...
                testCase, invalidStage4CTrajectoryCount)
            testCase.verifyError( ...
                @() helperBuildStage4CTrajectoryCollection( ...
                testCase.Stage4CDashboard, ...
                "constvel_like", ...
                TrajectoryCount=invalidStage4CTrajectoryCount), ...
                "StageReview:InvalidStage4CTrajectoryCount");
        end

        function testUnknownTrajectoryMotionClassErrors(testCase)
            testCase.verifyError( ...
                @() helperBuildStage4CTrajectoryCollection( ...
                testCase.Stage4CDashboard, ...
                "mixed_or_sparse", ...
                TrajectoryCount=1), ...
                "StageReview:UnknownStage4CMotionClass");
        end

        function testLiveScriptRunsWithoutInteractiveGlobe(testCase)
            projectRoot = localProjectRoot();
            scriptPath = fullfile(projectRoot, "stageReviewLiveScript.m");
            previousFigureVisibility = get( ...
                groot, ...
                "defaultFigureVisible");
            testCase.addTeardown(@() close("all"));
            testCase.addTeardown(@() set( ...
                groot, ...
                "defaultFigureVisible", ...
                previousFigureVisibility));
            set(groot, "defaultFigureVisible", "off");

            testCase.assertEqual(exist(scriptPath, "file"), 2);

            enableInteractiveGlobe = false; %#ok<NASGU>
            commandWindowOutput = evalc("run(scriptPath);"); %#ok<NASGU>

            testCase.verifyTrue(exist("review", "var") == 1);
            testCase.verifyTrue(exist("metricComparison", "var") == 1);
            testCase.verifyTrue(exist("maneuverCounts", "var") == 1);
            testCase.verifyTrue(exist("stage4CNativeCoverage", "var") == 1);
            testCase.verifyTrue(exist( ...
                "stage4CNativeInitializationDiagnostics", ...
                "var") == 1);
            testCase.verifyTrue(exist("stage4CNativeMetrics", "var") == 1);
            testCase.verifyEqual(height(stage4CNativeMetrics), 40);
            testCase.verifyTrue(exist("stage4CDashboard", "var") == 1);
            testCase.verifyTrue(exist( ...
                "expandedMotionClassAllocation", ...
                "var") == 1);
            testCase.verifyTrue(exist( ...
                "stage4CTestRMSEComparison", ...
                "var") == 1);
            testCase.verifyEqual(height(stage4CTestRMSEComparison), 12);
            testCase.verifyEqual( ...
                unique(stage4CTestRMSEComparison.split), ...
                "test");
            testCase.verifyTrue(exist( ...
                "stage4CNNGeneralizationComparison", ...
                "var") == 1);
            testCase.verifyEqual( ...
                height(stage4CNNGeneralizationComparison), ...
                18);
            testCase.verifyFalse(any( ...
                stage4CNNGeneralizationComparison.modelID == ...
                stage4CNNGeneralizationComparison.nativeModelID));
            testCase.verifyTrue(exist( ...
                "constvelRepresentativeSummary", ...
                "var") == 1);
            testCase.verifyTrue(exist( ...
                "constaccRepresentativeSummary", ...
                "var") == 1);
            testCase.verifyTrue(exist( ...
                "constturnRepresentativeSummary", ...
                "var") == 1);
            testCase.verifyEqual(height(constvelGlobeLegend), 5);
            testCase.verifyEqual(height(constaccGlobeLegend), 5);
            testCase.verifyEqual(height(constturnGlobeLegend), 5);
            testCase.verifyEqual(stage4CGlobeTrajectoryCount, 50);
            testCase.verifyFalse(exist( ...
                "constvelTrajectoryCollectionSummary", ...
                "var") == 1);
            testCase.verifyFalse(exist( ...
                "constaccTrajectoryCollectionSummary", ...
                "var") == 1);
            testCase.verifyFalse(exist( ...
                "constturnTrajectoryCollectionSummary", ...
                "var") == 1);
            testCase.verifyFalse(exist("constvelViewer", "var") == 1);
            testCase.verifyFalse(exist("constaccViewer", "var") == 1);
            testCase.verifyFalse(exist("constturnViewer", "var") == 1);
            testCase.verifyTrue(exist("stage3TrackErrorComparison", "var") == 1);
            if review.hasStage3B
                testCase.verifyTrue(exist("stage3BAggregateRMSE", "var") == 1);
                testCase.verifyTrue(exist("stage3BDataReadiness", "var") == 1);
                testCase.verifyTrue(exist("stage3BPositionAbsErrorSummary", "var") == 1);
                testCase.verifyGreaterThan(height(stage3BAggregateRMSE), 0);
                testCase.verifyEqual(height(stage3BPositionAbsErrorSummary), 2);
            else
                testCase.verifyTrue(exist("stage3BStatus", "var") == 1);
            end
            testCase.verifyGreaterThanOrEqual(height(metricComparison), 2);
            testCase.verifyGreaterThan(height(maneuverCounts), 0);
            testCase.verifyGreaterThan(height(stage3TrackErrorComparison), 0);
        end
    end
end

function projectRoot = localProjectRoot()
%LOCALPROJECTROOT Return the adsbForTracking project root.

testFolder = fileparts(mfilename("fullpath"));
projectRoot = fileparts(testFolder);

end
