function scenario_config = buildSyntheticHDTVBaselineScenarioConfig(varargin)
%BUILDSYNTHETICHDTVBASELINESCENARIOCONFIG Build the approved v1 baseline.
%
% This config is the single source of truth for the synthetic Apple Hill /
% CBS baseline. It keeps geometry, timing, terrain, truth, and packaging
% settings in one place so the generator does not inherit mixed legacy
% defaults from the capture and analysis code paths.

p = inputParser;
p.FunctionName = mfilename;
addParameter(p, 'ScenarioID', "applehill_cbs_detector_triage_v1", ...
    @(x) ischar(x) || isstring(x));
addParameter(p, 'SessionID', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'OutputRoot', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'DTEDPath', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'CenterFrequencyHz', 599e6, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
addParameter(p, 'SampleRateHz', 8e6, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
addParameter(p, 'LOOffsetHz', 0, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x));
addParameter(p, 'CaptureDurationS', 0.1, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
addParameter(p, 'CaptureRepetitions', 1, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x >= 1 && mod(x, 1) == 0);
addParameter(p, 'CaptureRepetitionSpacingS', 0, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x >= 0);
addParameter(p, 'TruthSamplePeriodS', 0.02, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
addParameter(p, 'RadarEpochUTC', datetime(2026, 7, 10, 16, 0, 0, 'TimeZone', 'UTC'), ...
    @(x) isnumeric(x) || isdatetime(x));
addParameter(p, 'SignalMode', "zero_channels_v1", @(x) ischar(x) || isstring(x));
addParameter(p, 'SeedSourcePath', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'SeedChannelIndex', 2, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x >= 1 && mod(x, 1) == 0);
addParameter(p, 'SeedStartOffsetS', 0, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x >= 0);
addParameter(p, 'SeedLoopMode', "wrap", @(x) ischar(x) || isstring(x));
addParameter(p, 'SeedTargetRMS', 0.25, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
addParameter(p, 'SeedEchoConditioningEnabled', true, @islogical);
addParameter(p, 'ReferenceGainDB', 0, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x));
addParameter(p, 'DirectPathGainDB', -3, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x));
addParameter(p, 'DirectPathDelaySamples', 0, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x >= 0);
addParameter(p, 'UseStochasticNoise', false, @islogical);
addParameter(p, 'NoiseSNRDB', 45, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x));
addParameter(p, 'RandomSeed', [], @(x) isempty(x) || (isnumeric(x) && isscalar(x) && isfinite(x)));
parse(p, varargin{:});
opts = p.Results;

repo_root = fileparts(fileparts(mfilename('fullpath')));
output_root = localResolveOutputRoot(opts.OutputRoot, repo_root);
dted_path = localResolveDTEDPath(opts.DTEDPath, repo_root);
seed_source_path = localResolveSeedPath(opts.SeedSourcePath, repo_root);
scenario_id = char(string(opts.ScenarioID));
session_id = localResolveSessionID(opts.SessionID, scenario_id);
radar_epoch_utc = localNormalizeEpoch(opts.RadarEpochUTC);
signal_mode = localResolveSignalMode(opts.SignalMode, seed_source_path);
seed_echo_conditioning = localBuildSeedEchoConditioning( ...
    signal_mode, ...
    double(opts.SampleRateHz), ...
    logical(opts.SeedEchoConditioningEnabled));
capture_window_s = opts.CaptureDurationS * opts.CaptureRepetitions + ...
    max(opts.CaptureRepetitions - 1, 0) * opts.CaptureRepetitionSpacingS;

% Approved baseline geometry taken from the current passive-radar workflow.
tx_lla_deg_m = [42.310278, -71.236667, 431.9];
rx_lla_deg_m = [42.2999333, -71.349333, 15.0];
targets = localBuildDefaultTargets(tx_lla_deg_m, rx_lla_deg_m, capture_window_s);

scenario_config = struct( ...
    'scenario_id', scenario_id, ...
    'session_id', session_id, ...
    'purpose', 'detector_truth_projection_triage', ...
    'description', ['Minimal terrain-backed packaged-session baseline for ' ...
        'Apple Hill / CBS passive-radar algorithm evaluation.'], ...
    'generator_name', 'generateSyntheticHDTVSession', ...
    'truth_source', 'synthetic_geoTrajectory_sbs1', ...
    'output_root', output_root, ...
    'terrain_dted_path', dted_path, ...
    'seed_source_path', seed_source_path, ...
    'seed_channel_index', double(opts.SeedChannelIndex), ...
    'seed_start_offset_s', double(opts.SeedStartOffsetS), ...
    'seed_loop_mode', char(string(opts.SeedLoopMode)), ...
    'seed_target_rms', double(opts.SeedTargetRMS), ...
    'seed_echo_source_mode', localResolveSeedEchoSourceMode(signal_mode, seed_echo_conditioning), ...
    'seed_echo_conditioning', seed_echo_conditioning, ...
    'tx_lla_deg_m', tx_lla_deg_m, ...
    'rx_lla_deg_m', rx_lla_deg_m, ...
    'center_frequency_hz', double(opts.CenterFrequencyHz), ...
    'sample_rate_hz', double(opts.SampleRateHz), ...
    'lo_offset_hz', double(opts.LOOffsetHz), ...
    'part_duration_s', double(opts.CaptureDurationS), ...
    'capture_repetitions', double(opts.CaptureRepetitions), ...
    'capture_repetition_spacing_s', double(opts.CaptureRepetitionSpacingS), ...
    'radar_epoch_utc', radar_epoch_utc, ...
    'truth_sample_period_s', double(opts.TruthSamplePeriodS), ...
    'signal_mode', signal_mode, ...
    'reference_gain_db', double(opts.ReferenceGainDB), ...
    'direct_path_gain_db', double(opts.DirectPathGainDB), ...
    'direct_path_delay_samples', double(opts.DirectPathDelaySamples), ...
    'use_stochastic_noise', logical(opts.UseStochasticNoise), ...
    'noise_snr_db', double(opts.NoiseSNRDB), ...
    'random_seed', localNormalizeSeed(opts.RandomSeed), ...
    'capture_file_base', 'synthetic_hdtv_capture', ...
    'expected_overlap_window_s', [0, capture_window_s], ...
    'targets', {targets});
end

function output_root = localResolveOutputRoot(output_root_in, repo_root)
if strlength(string(output_root_in)) == 0
    output_root = fullfile(repo_root, 'captures');
else
    output_root = char(string(output_root_in));
    if ~localIsAbsolutePath(output_root)
        output_root = fullfile(repo_root, output_root);
    end
end
end

function dted_path = localResolveDTEDPath(dted_path_in, repo_root)
if strlength(string(dted_path_in)) == 0
    dted_path = fullfile(repo_root, 'n42_w072_1arc_v3.dt2');
else
    dted_path = char(string(dted_path_in));
    if ~localIsAbsolutePath(dted_path)
        dted_path = fullfile(repo_root, dted_path);
    end
end
end

function seed_path = localResolveSeedPath(seed_path_in, repo_root)
if strlength(string(seed_path_in)) == 0
    seed_path = '';
else
    seed_path = char(string(seed_path_in));
    if ~localIsAbsolutePath(seed_path)
        seed_path = fullfile(repo_root, seed_path);
    end
end
end

function radar_epoch_utc = localNormalizeEpoch(epoch_in)
if isdatetime(epoch_in)
    if isempty(epoch_in.TimeZone)
        epoch_in.TimeZone = 'UTC';
    end
    radar_epoch_utc = posixtime(epoch_in);
else
    radar_epoch_utc = double(epoch_in);
end
end

function signal_mode = localResolveSignalMode(signal_mode_in, seed_source_path)
signal_mode = char(string(signal_mode_in));
if ~isempty(seed_source_path) && strcmp(signal_mode, 'zero_channels_v1')
    signal_mode = 'seed_backed_bistatic_v1';
end
end

function session_id = localResolveSessionID(session_id_in, scenario_id)
if strlength(string(session_id_in)) > 0
    session_id = char(string(session_id_in));
else
    session_id = ['synth_' localSanitizeToken(scenario_id)];
end
end

function seed_value = localNormalizeSeed(seed_in)
if isempty(seed_in)
    seed_value = [];
else
    seed_value = double(seed_in);
end
end

function seed_echo_conditioning = localBuildSeedEchoConditioning(signal_mode, sample_rate_hz, enabled_in)
seed_backed_mode = strcmp(char(string(signal_mode)), 'seed_backed_bistatic_v1');
conditioning_enabled = logical(enabled_in) && seed_backed_mode;

seed_echo_conditioning = struct( ...
    'enabled', conditioning_enabled, ...
    'reference_source', 'full_seed', ...
    'direct_path_source', 'full_seed', ...
    'target_echo_source', 'conditioned_seed', ...
    'method', 'dominant_line_notch_then_rms_match_v1', ...
    'minimum_prominence_db', 10, ...
    'notch_half_width_hz', min(50e3, 0.01 * double(sample_rate_hz)), ...
    'dc_highpass_cutoff_hz', min(50e3, 0.01 * double(sample_rate_hz)), ...
    'max_analysis_samples', 65536, ...
    'baseline_span_bins', 129, ...
    'note', ['Reference and direct-path channels keep the full seed. ' ...
        'Synthetic target echoes use a lightly conditioned seed copy so a dominant ' ...
        'pilot-like line does not create full-height Doppler columns.']);

if ~seed_backed_mode
    seed_echo_conditioning.enabled = false;
    seed_echo_conditioning.target_echo_source = 'not_applicable';
    seed_echo_conditioning.note = 'Zero-channel mode does not synthesize seed-backed target echoes.';
end
end

function seed_echo_source_mode = localResolveSeedEchoSourceMode(signal_mode, seed_echo_conditioning)
if strcmp(char(string(signal_mode)), 'seed_backed_bistatic_v1') && seed_echo_conditioning.enabled
    seed_echo_source_mode = 'conditioned_target_echoes_v1';
elseif strcmp(char(string(signal_mode)), 'seed_backed_bistatic_v1')
    seed_echo_source_mode = 'full_seed_target_echoes_v1';
else
    seed_echo_source_mode = 'not_applicable';
end
end

function targets = localBuildDefaultTargets(tx_lla_deg_m, rx_lla_deg_m, capture_window_s)
scene_lat = mean([tx_lla_deg_m(1), rx_lla_deg_m(1)]);
scene_lon = mean([tx_lla_deg_m(2), rx_lla_deg_m(2)]);
time_of_arrival_s = [0; capture_window_s / 2; capture_window_s];

% Keep the default smoke-test targets out of the near-zero bistatic-range
% region so the baseline session still resembles something we would try to
% lift from real data. These offsets put the targets roughly 8.9–10.2 km
% away in range excess for the approved Apple Hill / CBS geometry.
targets(1) = struct( ...
    'target_id', 'TGT001', ...
    'icao_hex', 'A1B2C3', ...
    'callsign', 'SYNTH01', ...
    'echo_gain_db', -22, ...
    'waypoints_lla_deg_m', [ ...
        scene_lat + 0.060000, scene_lon - 0.060000, 3200; ...
        scene_lat + 0.060000, scene_lon - 0.059950, 3200; ...
        scene_lat + 0.060000, scene_lon - 0.059900, 3200], ...
    'time_of_arrival_s', time_of_arrival_s);

targets(2) = struct( ...
    'target_id', 'TGT002', ...
    'icao_hex', 'D4E5F6', ...
    'callsign', 'SYNTH02', ...
    'echo_gain_db', -24, ...
    'waypoints_lla_deg_m', [ ...
        scene_lat + 0.020000, scene_lon + 0.100000, 3000; ...
        scene_lat + 0.020000, scene_lon + 0.100050, 3000; ...
        scene_lat + 0.020000, scene_lon + 0.100100, 3000], ...
    'time_of_arrival_s', time_of_arrival_s);
end

function tf = localIsAbsolutePath(path_value)
if ispc
    tf = ~isempty(regexp(path_value, '^[A-Za-z]:[\\/]', 'once')) || startsWith(path_value, '\\');
else
    tf = startsWith(path_value, filesep);
end
end

function token = localSanitizeToken(token_in)
token = regexprep(lower(char(string(token_in))), '[^a-z0-9]+', '_');
token = regexprep(token, '^_+|_+$', '');
end
