function scenario_config = buildSyntheticHDTVBaselineScenarioConfig(varargin)
%BUILDSYNTHETICHDTVBASELINESCENARIOCONFIG Build the approved v1 baseline.
%
% This config is the single source of truth for the synthetic Apple Hill /
% CBS baseline. It keeps geometry, timing, terrain, truth, and packaging
% settings in one place so the generator does not inherit mixed legacy
% defaults from the capture and analysis code paths.

p = inputParser;
p.FunctionName = mfilename;
addParameter(p, 'ScenarioID', "applehill_cbs_detector_triage_v1", ...
    @(x) ischar(x) || isstring(x));
addParameter(p, 'SessionID', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'OutputRoot', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'DTEDPath', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'CenterFrequencyHz', 599e6, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
addParameter(p, 'SampleRateHz', 8e6, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
addParameter(p, 'LOOffsetHz', 0, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x));
addParameter(p, 'CaptureDurationS', 0.1, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
addParameter(p, 'CaptureRepetitions', 1, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x >= 1 && mod(x, 1) == 0);
addParameter(p, 'CaptureRepetitionSpacingS', 0, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x >= 0);
addParameter(p, 'TruthSamplePeriodS', 0.02, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
addParameter(p, 'RadarEpochUTC', datetime(2026, 7, 10, 16, 0, 0, 'TimeZone', 'UTC'), ...
    @(x) isnumeric(x) || isdatetime(x));
addParameter(p, 'SignalMode', "zero_channels_v1", @(x) ischar(x) || isstring(x));
addParameter(p, 'SeedSourcePath', "", @(x) ischar(x) || isstring(x));
addParameter(p, 'TruthSourceMode', "auto", @(x) ischar(x) || isstring(x));
addParameter(p, 'TruthWindowMaxS', [], ...
    @(x) isempty(x) || (isnumeric(x) && isscalar(x) && isfinite(x) && x > 0));
addParameter(p, 'SeedChannelIndex', 2, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x >= 1 && mod(x, 1) == 0);
addParameter(p, 'SeedStartOffsetS', 0, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x >= 0);
addParameter(p, 'SeedLoopMode', "wrap", @(x) ischar(x) || isstring(x));
addParameter(p, 'SeedTargetRMS', 0.25, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
addParameter(p, 'SeedEchoConditioningEnabled', true, @islogical);
addParameter(p, 'EchoGenerationModel', "toolbox_wideband_free_space_v1", ...
    @(x) ischar(x) || isstring(x));
addParameter(p, 'EnableFullSeedComparison', false, @islogical);
addParameter(p, 'EnableConditionedEchoDiagnostic', [], ...
    @(x) isempty(x) || islogical(x));
addParameter(p, 'ComparisonEchoGenerationModel', "", ...
    @(x) ischar(x) || isstring(x));
addParameter(p, 'DiagnosticEchoGenerationModel', "", ...
    @(x) ischar(x) || isstring(x));
addParameter(p, 'PropagationBlockDurationS', [], ...
    @(x) isempty(x) || (isnumeric(x) && isscalar(x) && isfinite(x) && x > 0));
addParameter(p, 'ReferenceGainDB', 0, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x));
addParameter(p, 'ReferenceGainAt100kmDB', -25, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x));
addParameter(p, 'DirectPathGainDB', -3, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x));
addParameter(p, 'DirectPathDelaySamples', 0, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x >= 0);
addParameter(p, 'CaptureEchoGainPolicy', "range_only_heuristic_v1", ...
    @(x) ischar(x) || isstring(x));
addParameter(p, 'UseStochasticNoise', false, @islogical);
addParameter(p, 'NoiseSNRDB', 45, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x));
addParameter(p, 'RandomSeed', [], @(x) isempty(x) || (isnumeric(x) && isscalar(x) && isfinite(x)));
parse(p, varargin{:});
opts = p.Results;

repo_root = fileparts(fileparts(mfilename('fullpath')));
output_root = localResolveOutputRoot(opts.OutputRoot, repo_root);
dted_path = localResolveDTEDPath(opts.DTEDPath, repo_root);
seed_session_context = localResolveSeedSessionContext(opts.SeedSourcePath, repo_root);
seed_source_path = localResolveSeedPath(seed_session_context, opts.SeedSourcePath, repo_root);
scenario_id = char(string(opts.ScenarioID));
session_id = localResolveSessionID(opts.SessionID, scenario_id);
truth_source_mode = localResolveTruthSourceMode(opts.TruthSourceMode, seed_session_context);
timing_plan = localResolveTimingPlan(opts, truth_source_mode, seed_session_context);
radar_epoch_utc = localResolveRadarEpoch( ...
    opts.RadarEpochUTC, ...
    truth_source_mode, ...
    seed_session_context);
signal_mode = localResolveSignalMode(opts.SignalMode, seed_source_path);
seed_echo_conditioning = localBuildSeedEchoConditioning( ...
    signal_mode, ...
    double(opts.SampleRateHz), ...
    logical(opts.SeedEchoConditioningEnabled), ...
    false);
comparison_seed_echo_conditioning = localBuildSeedEchoConditioning( ...
    signal_mode, ...
    double(opts.SampleRateHz), ...
    false, ...
    true);
echo_generation_model = localResolveEchoGenerationModel(opts.EchoGenerationModel, signal_mode);
comparison_echo_generation_model = localResolveComparisonEchoGenerationModel( ...
    opts.ComparisonEchoGenerationModel, ...
    opts.DiagnosticEchoGenerationModel, ...
    echo_generation_model, ...
    signal_mode);
full_seed_comparison_enabled = localResolveFullSeedComparisonEnabled( ...
    opts.EnableFullSeedComparison, ...
    opts.EnableConditionedEchoDiagnostic, ...
    signal_mode);
propagation_block_duration_s = localResolvePropagationBlockDuration( ...
    opts.PropagationBlockDurationS, ...
    opts.TruthSamplePeriodS);
seed_echo_source_mode = localResolveSeedEchoSourceMode(signal_mode, seed_echo_conditioning);
comparison_seed_echo_source_mode = localResolveSeedEchoSourceMode( ...
    signal_mode, ...
    comparison_seed_echo_conditioning);
target_echo_dataset_mode = helperSyntheticDescribeTargetEchoDatasetMode( ...
    signal_mode, ...
    seed_echo_source_mode);
comparison_target_echo_dataset_mode = helperSyntheticDescribeTargetEchoDatasetMode( ...
    signal_mode, ...
    comparison_seed_echo_source_mode);
capture_window_s = timing_plan.radar_active_window_s;

% Approved baseline geometry taken from the current passive-radar workflow.
tx_lla_deg_m = [42.310278, -71.236667, 431.9];
rx_lla_deg_m = [42.2999333, -71.349333, 15.0];
targets = localBuildDefaultTargets(tx_lla_deg_m, rx_lla_deg_m, capture_window_s);

scenario_config = struct( ...
    'scenario_id', scenario_id, ...
    'session_id', session_id, ...
    'purpose', 'signal_physics_readiness_gate', ...
    'description', ['Terrain-backed packaged-session baseline for Apple Hill / CBS ' ...
        'synthetic HDTV signal-physics readiness evaluation.'], ...
    'generator_name', 'generateSyntheticHDTVSession', ...
    'truth_source', truth_source_mode, ...
    'truth_source_mode', truth_source_mode, ...
    'truth_model_product', localResolveTruthModelProduct(truth_source_mode), ...
    'synthetic_radar_data_product', 'synthetic_hdtv_iq_session_v2', ...
    'output_root', output_root, ...
    'terrain_dted_path', dted_path, ...
    'seed_source_path', seed_source_path, ...
    'seed_source_kind', char(string(seed_session_context.input_kind)), ...
    'seed_session_context', seed_session_context, ...
    'seed_channel_index', double(opts.SeedChannelIndex), ...
    'seed_start_offset_s', double(opts.SeedStartOffsetS), ...
    'seed_loop_mode', char(string(opts.SeedLoopMode)), ...
    'seed_target_rms', double(opts.SeedTargetRMS), ...
    'truth_window_max_s', localNormalizeOptionalScalar(opts.TruthWindowMaxS), ...
    'selected_truth_window_s', timing_plan.selected_truth_window_s, ...
    'source_capture_active_window_s', localNormalizeOptionalScalar(seed_session_context.radar_active_window_s), ...
    'truth_filter_mode', 'overlap_geometry_inclusive_v1', ...
    'capture_echo_gain_policy', char(string(opts.CaptureEchoGainPolicy)), ...
    'reference_gain_at_100km_db', double(opts.ReferenceGainAt100kmDB), ...
    'echo_generation_model', echo_generation_model, ...
    'propagation_block_duration_s', propagation_block_duration_s, ...
    'seed_echo_source_mode', seed_echo_source_mode, ...
    'seed_echo_conditioning', seed_echo_conditioning, ...
    'target_echo_dataset_mode', target_echo_dataset_mode.mode_id, ...
    'target_echo_dataset_label', target_echo_dataset_mode.label, ...
    'recommended_intermediate_algorithm_test_mode', ...
        target_echo_dataset_mode.recommended_intermediate_algorithm_test_mode, ...
    'full_seed_comparison_enabled', full_seed_comparison_enabled, ...
    'comparison_echo_generation_model', comparison_echo_generation_model, ...
    'comparison_seed_echo_source_mode', comparison_seed_echo_source_mode, ...
    'comparison_seed_echo_conditioning', comparison_seed_echo_conditioning, ...
    'comparison_target_echo_dataset_mode', comparison_target_echo_dataset_mode.mode_id, ...
    'comparison_target_echo_dataset_label', comparison_target_echo_dataset_mode.label, ...
    'diagnostic_conditioned_echo_enabled', full_seed_comparison_enabled, ...
    'diagnostic_echo_generation_model', comparison_echo_generation_model, ...
    'diagnostic_seed_echo_source_mode', comparison_seed_echo_source_mode, ...
    'diagnostic_seed_echo_conditioning', comparison_seed_echo_conditioning, ...
    'tx_lla_deg_m', tx_lla_deg_m, ...
    'rx_lla_deg_m', rx_lla_deg_m, ...
    'center_frequency_hz', double(opts.CenterFrequencyHz), ...
    'sample_rate_hz', double(opts.SampleRateHz), ...
    'lo_offset_hz', double(opts.LOOffsetHz), ...
    'part_duration_s', timing_plan.part_duration_s, ...
    'capture_repetitions', timing_plan.capture_repetitions, ...
    'capture_repetition_spacing_s', timing_plan.capture_repetition_spacing_s, ...
    'output_timing_mode', timing_plan.mode_id, ...
    'radar_epoch_utc', radar_epoch_utc, ...
    'truth_sample_period_s', double(opts.TruthSamplePeriodS), ...
    'signal_mode', signal_mode, ...
    'reference_gain_db', double(opts.ReferenceGainDB), ...
    'direct_path_gain_db', double(opts.DirectPathGainDB), ...
    'direct_path_delay_samples', double(opts.DirectPathDelaySamples), ...
    'use_stochastic_noise', logical(opts.UseStochasticNoise), ...
    'noise_snr_db', double(opts.NoiseSNRDB), ...
    'random_seed', localNormalizeSeed(opts.RandomSeed), ...
    'capture_file_base', 'synthetic_hdtv_capture', ...
    'expected_overlap_window_s', [0, capture_window_s], ...
    'capture_manifest_path', char(string(seed_session_context.manifest_path)), ...
    'capture_adsb_files', {seed_session_context.adsb_files_rel}, ...
    'targets', {targets});
end

function output_root = localResolveOutputRoot(output_root_in, repo_root)
if strlength(string(output_root_in)) == 0
    output_root = fullfile(repo_root, 'captures');
else
    output_root = char(string(output_root_in));
    if ~localIsAbsolutePath(output_root)
        output_root = fullfile(repo_root, output_root);
    end
end
end

function dted_path = localResolveDTEDPath(dted_path_in, repo_root)
if strlength(string(dted_path_in)) == 0
    dted_path = fullfile(repo_root, 'n42_w072_1arc_v3.dt2');
else
    dted_path = char(string(dted_path_in));
    if ~localIsAbsolutePath(dted_path)
        dted_path = fullfile(repo_root, dted_path);
    end
end
end

function seed_session_context = localResolveSeedSessionContext(seed_source_input, repo_root)
if strlength(string(seed_source_input)) == 0
    seed_session_context = helperSyntheticResolveSessionContext("", 'RepoRoot', repo_root);
else
    seed_session_context = helperSyntheticResolveSessionContext( ...
        seed_source_input, ...
        'RepoRoot', repo_root);
end
end

function seed_path = localResolveSeedPath(seed_session_context, seed_path_in, repo_root)
if strlength(string(seed_path_in)) == 0
    seed_path = '';
else
    if isfield(seed_session_context, 'source_spec_path') && ...
            strlength(string(seed_session_context.source_spec_path)) > 0
        seed_path = char(string(seed_session_context.source_spec_path));
    else
        seed_path = char(string(seed_path_in));
        if ~localIsAbsolutePath(seed_path)
            seed_path = fullfile(repo_root, seed_path);
        end
    end
end
end

function truth_source_mode = localResolveTruthSourceMode( ...
    truth_source_mode_in, seed_session_context)
requested_mode = lower(char(string(truth_source_mode_in)));
valid_modes = {'auto', 'synthetic_waypoints_v1', 'capture_adsb_v1'};
if ~ismember(requested_mode, valid_modes)
    error('buildSyntheticHDTVBaselineScenarioConfig:badTruthSourceMode', ...
        'TruthSourceMode must be "auto", "synthetic_waypoints_v1", or "capture_adsb_v1".');
end

switch requested_mode
    case 'auto'
        if seed_session_context.is_manifest_backed && ...
                seed_session_context.has_adsb && ...
                seed_session_context.input_kind ~= "baseband_file"
            truth_source_mode = 'capture_adsb_v1';
        else
            truth_source_mode = 'synthetic_waypoints_v1';
        end

    case 'capture_adsb_v1'
        if ~seed_session_context.is_manifest_backed || ~seed_session_context.has_adsb
            error('buildSyntheticHDTVBaselineScenarioConfig:captureTruthRequiresADSB', ...
                ['TruthSourceMode="capture_adsb_v1" requires a packaged session ' ...
                 'with at least one ADS-B truth file.']);
        end
        truth_source_mode = 'capture_adsb_v1';

    otherwise
        truth_source_mode = 'synthetic_waypoints_v1';
end
end

function timing_plan = localResolveTimingPlan(opts, truth_source_mode, seed_session_context)
requested_active_window_s = double(opts.CaptureDurationS) * double(opts.CaptureRepetitions) + ...
    max(double(opts.CaptureRepetitions) - 1, 0) * double(opts.CaptureRepetitionSpacingS);

timing_plan = struct( ...
    'part_duration_s', double(opts.CaptureDurationS), ...
    'capture_repetitions', double(opts.CaptureRepetitions), ...
    'capture_repetition_spacing_s', double(opts.CaptureRepetitionSpacingS), ...
    'radar_active_window_s', requested_active_window_s, ...
    'selected_truth_window_s', requested_active_window_s, ...
    'mode_id', 'synthetic_timing_v1');

if ~strcmp(truth_source_mode, 'capture_adsb_v1')
    return
end

full_capture_window_s = double(seed_session_context.radar_active_window_s);
if ~(isfinite(full_capture_window_s) && full_capture_window_s > 0)
    error('buildSyntheticHDTVBaselineScenarioConfig:missingCaptureWindow', ...
        'The packaged capture session does not expose a finite radar_active_window_s.');
end

selected_window_s = localResolveSelectedWindow( ...
    opts.TruthWindowMaxS, ...
    full_capture_window_s);
timing_plan.selected_truth_window_s = selected_window_s;
timing_plan.radar_active_window_s = selected_window_s;

[use_manifest_timing, included_parts] = localResolveManifestTimingCrop( ...
    selected_window_s, ...
    seed_session_context);

if use_manifest_timing
    timing_plan.part_duration_s = double(seed_session_context.capture_duration_s);
    timing_plan.capture_repetitions = double(numel(included_parts));
    timing_plan.capture_repetition_spacing_s = double(seed_session_context.capture_repetition_spacing_s);
    timing_plan.mode_id = 'capture_manifest_timing_v1';
else
    timing_plan.part_duration_s = selected_window_s;
    timing_plan.capture_repetitions = 1;
    timing_plan.capture_repetition_spacing_s = 0;
    timing_plan.mode_id = 'capture_cropped_single_part_v1';
end
end

function selected_window_s = localResolveSelectedWindow(truth_window_max_s_in, full_capture_window_s)
if isempty(truth_window_max_s_in)
    selected_window_s = full_capture_window_s;
else
    selected_window_s = min(double(truth_window_max_s_in), full_capture_window_s);
end
end

function [use_manifest_timing, included_parts] = localResolveManifestTimingCrop( ...
    selected_window_s, seed_session_context)
use_manifest_timing = false;
included_parts = 1 : max(numel(seed_session_context.radar_files), 0);

capture_duration_s = double(seed_session_context.capture_duration_s);
capture_spacing_s = double(seed_session_context.capture_repetition_spacing_s);
n_parts = numel(seed_session_context.radar_files);
if ~(isfinite(capture_duration_s) && isfinite(capture_spacing_s) && n_parts >= 1)
    return
end

part_start_offsets_s = (0 : n_parts - 1).' .* (capture_duration_s + capture_spacing_s);
part_end_offsets_s = part_start_offsets_s + capture_duration_s;
boundary_tolerance_s = 1e-9;

if abs(selected_window_s - double(seed_session_context.radar_active_window_s)) <= boundary_tolerance_s
    use_manifest_timing = true;
    included_parts = 1 : n_parts;
    return
end

included_mask = part_end_offsets_s <= selected_window_s + boundary_tolerance_s;
included_parts = find(included_mask).';
if isempty(included_parts)
    return
end

if abs(part_end_offsets_s(included_parts(end)) - selected_window_s) <= boundary_tolerance_s
    use_manifest_timing = true;
end
end

function radar_epoch_utc = localResolveRadarEpoch( ...
    requested_epoch_in, truth_source_mode, seed_session_context)
requested_epoch_utc = localNormalizeEpoch(requested_epoch_in);
if strcmp(truth_source_mode, 'capture_adsb_v1') && ...
        isfinite(seed_session_context.radar_epoch_utc)
    radar_epoch_utc = double(seed_session_context.radar_epoch_utc);
else
    radar_epoch_utc = requested_epoch_utc;
end
end

function truth_model_product = localResolveTruthModelProduct(truth_source_mode)
if strcmp(truth_source_mode, 'capture_adsb_v1')
    truth_model_product = 'capture_backed_bistatic_truth_v1';
else
    truth_model_product = 'synthetic_bistatic_truth_v2';
end
end

function value = localNormalizeOptionalScalar(value_in)
if isempty(value_in)
    value = [];
else
    value = double(value_in);
end
end

function radar_epoch_utc = localNormalizeEpoch(epoch_in)
if isdatetime(epoch_in)
    if isempty(epoch_in.TimeZone)
        epoch_in.TimeZone = 'UTC';
    end
    radar_epoch_utc = posixtime(epoch_in);
else
    radar_epoch_utc = double(epoch_in);
end
end

function signal_mode = localResolveSignalMode(signal_mode_in, seed_source_path)
signal_mode = char(string(signal_mode_in));
if ~isempty(seed_source_path) && strcmp(signal_mode, 'zero_channels_v1')
    signal_mode = 'seed_backed_bistatic_v1';
end
end

function session_id = localResolveSessionID(session_id_in, scenario_id)
if strlength(string(session_id_in)) > 0
    session_id = char(string(session_id_in));
else
    session_id = ['synth_' localSanitizeToken(scenario_id)];
end
end

function seed_value = localNormalizeSeed(seed_in)
if isempty(seed_in)
    seed_value = [];
else
    seed_value = double(seed_in);
end
end

function seed_echo_conditioning = localBuildSeedEchoConditioning( ...
    signal_mode, sample_rate_hz, enabled_in, comparison_reference_mode)
seed_backed_mode = strcmp(char(string(signal_mode)), 'seed_backed_bistatic_v1');
conditioning_enabled = logical(enabled_in) && seed_backed_mode;

seed_echo_conditioning = struct( ...
    'enabled', conditioning_enabled, ...
    'reference_source', 'full_seed', ...
    'direct_path_source', 'full_seed', ...
    'target_echo_source', 'full_seed', ...
    'method', 'dominant_line_notch_then_rms_match_v1', ...
    'minimum_prominence_db', 10, ...
    'notch_half_width_hz', min(50e3, 0.01 * double(sample_rate_hz)), ...
    'dc_highpass_cutoff_hz', min(50e3, 0.01 * double(sample_rate_hz)), ...
    'max_analysis_samples', 65536, ...
    'baseline_span_bins', 129, ...
    'note', '');

if conditioning_enabled
    seed_echo_conditioning.target_echo_source = 'conditioned_seed';
    seed_echo_conditioning.note = ['Recommended intermediate algorithm-test output. ' ...
        'Reference and direct-path channels keep the full seed while target ' ...
        'echoes use a lightly conditioned seed copy so the dominant pilot-like ' ...
        'line is less likely to create truth-aligned vertical Doppler columns.'];
elseif seed_backed_mode && comparison_reference_mode
    seed_echo_conditioning.note = ['Full-seed comparison/reference output. ' ...
        'Reference, direct-path, and target echoes all reuse the unmodified ' ...
        'seed so users can study seed preservation and vertical-column artifacts.'];
elseif seed_backed_mode
    seed_echo_conditioning.note = ['Full-seed comparison/reference output. ' ...
        'This mode is retained for A/B comparison and is not the recommended ' ...
        'algorithm-test dataset while the vertical-column artifact persists.'];
end

if ~seed_backed_mode
    seed_echo_conditioning.enabled = false;
    seed_echo_conditioning.target_echo_source = 'not_applicable';
    seed_echo_conditioning.note = 'Zero-channel mode does not synthesize seed-backed target echoes.';
end
end

function echo_generation_model = localResolveEchoGenerationModel(echo_generation_model_in, signal_mode)
if ~strcmp(char(string(signal_mode)), 'seed_backed_bistatic_v1')
    echo_generation_model = 'not_applicable';
    return
end

echo_generation_model = char(string(echo_generation_model_in));
if strlength(string(echo_generation_model)) == 0
    echo_generation_model = 'toolbox_wideband_free_space_v1';
end
end

function comparison_echo_generation_model = localResolveComparisonEchoGenerationModel( ...
    comparison_model_in, legacy_diagnostic_model_in, primary_echo_generation_model, signal_mode)
if ~strcmp(char(string(signal_mode)), 'seed_backed_bistatic_v1')
    comparison_echo_generation_model = 'not_applicable';
    return
end

comparison_model = string(comparison_model_in);
if strlength(comparison_model) == 0
    comparison_model = string(legacy_diagnostic_model_in);
end
if strlength(comparison_model) == 0
    comparison_model = string(primary_echo_generation_model);
end

comparison_echo_generation_model = char(comparison_model);
end

function full_seed_comparison_enabled = localResolveFullSeedComparisonEnabled( ...
    full_seed_comparison_in, legacy_diagnostic_in, signal_mode)
if ~strcmp(char(string(signal_mode)), 'seed_backed_bistatic_v1')
    full_seed_comparison_enabled = false;
    return
end

full_seed_comparison_enabled = logical(full_seed_comparison_in);
if ~full_seed_comparison_enabled && ~isempty(legacy_diagnostic_in)
    full_seed_comparison_enabled = logical(legacy_diagnostic_in);
end
end

function propagation_block_duration_s = localResolvePropagationBlockDuration( ...
    propagation_block_duration_s_in, truth_sample_period_s)
if isempty(propagation_block_duration_s_in)
    propagation_block_duration_s = double(truth_sample_period_s);
else
    propagation_block_duration_s = double(propagation_block_duration_s_in);
end
end

function seed_echo_source_mode = localResolveSeedEchoSourceMode(signal_mode, seed_echo_conditioning)
if strcmp(char(string(signal_mode)), 'seed_backed_bistatic_v1') && seed_echo_conditioning.enabled
    seed_echo_source_mode = 'conditioned_target_echoes_v1';
elseif strcmp(char(string(signal_mode)), 'seed_backed_bistatic_v1')
    seed_echo_source_mode = 'full_seed_target_echoes_v1';
else
    seed_echo_source_mode = 'not_applicable';
end
end

function targets = localBuildDefaultTargets(tx_lla_deg_m, rx_lla_deg_m, capture_window_s)
scene_lat = mean([tx_lla_deg_m(1), rx_lla_deg_m(1)]);
scene_lon = mean([tx_lla_deg_m(2), rx_lla_deg_m(2)]);
time_of_arrival_s = [0; capture_window_s / 2; capture_window_s];

% Keep the default smoke-test targets out of the near-zero bistatic-range
% region so the baseline session still resembles something we would try to
% lift from real data. These offsets put the targets roughly 8.9–10.2 km
% away in range excess for the approved Apple Hill / CBS geometry.
targets(1) = struct( ...
    'target_id', 'TGT001', ...
    'icao_hex', 'A1B2C3', ...
    'callsign', 'SYNTH01', ...
    'echo_gain_db', -22, ...
    'waypoints_lla_deg_m', [ ...
        scene_lat + 0.060000, scene_lon - 0.060000, 3200; ...
        scene_lat + 0.060000, scene_lon - 0.059950, 3200; ...
        scene_lat + 0.060000, scene_lon - 0.059900, 3200], ...
    'time_of_arrival_s', time_of_arrival_s);

targets(2) = struct( ...
    'target_id', 'TGT002', ...
    'icao_hex', 'D4E5F6', ...
    'callsign', 'SYNTH02', ...
    'echo_gain_db', -24, ...
    'waypoints_lla_deg_m', [ ...
        scene_lat + 0.020000, scene_lon + 0.100000, 3000; ...
        scene_lat + 0.020000, scene_lon + 0.100050, 3000; ...
        scene_lat + 0.020000, scene_lon + 0.100100, 3000], ...
    'time_of_arrival_s', time_of_arrival_s);
end

function tf = localIsAbsolutePath(path_value)
if ispc
    tf = ~isempty(regexp(path_value, '^[A-Za-z]:[\\/]', 'once')) || startsWith(path_value, '\\');
else
    tf = startsWith(path_value, filesep);
end
end

function token = localSanitizeToken(token_in)
token = regexprep(lower(char(string(token_in))), '[^a-z0-9]+', '_');
token = regexprep(token, '^_+|_+$', '');
end
