function truth_bundle = helperSyntheticBuildCaptureTruthBundle(scenario_config)
%HELPERSYNTHETICBUILDCAPTURETRUTHBUNDLE Build normalized truth from capture ADS-B.
%
% Plain language:
% A packaged capture session already contains the aircraft motion we want
% to preserve. This helper loads the recorded ADS-B truth, clips it to the
% chosen radar window, projects it into bistatic measurement space, aligns
% it to the synthetic generator timeline, and returns the same
% `truth_bundle` contract that the synthetic waypoint path uses.

validateattributes(scenario_config, {'struct'}, {'scalar'}, mfilename, 'scenario_config');

session_context = localResolveSessionContextFromScenario(scenario_config);
if ~session_context.is_manifest_backed || ~session_context.has_adsb
    error('helperSyntheticBuildCaptureTruthBundle:missingCaptureADSB', ...
        ['Capture-backed truth requires a packaged session context with at ' ...
         'least one ADS-B truth file.']);
end

selected_truth_window_s = localResolveSelectedTruthWindowS( ...
    scenario_config, ...
    session_context);
sample_times_s = localBuildSampleTimes( ...
    selected_truth_window_s, ...
    double(scenario_config.truth_sample_period_s));

loaded_adsb_tracks = loadADSBTruth(session_context.adsb_files, 'Verbose', false);
windowed_adsb_tracks = localClipADSBTracksToWindow( ...
    loaded_adsb_tracks, ...
    double(scenario_config.radar_epoch_utc), ...
    selected_truth_window_s);
windowed_bistatic_tracks = adsbToBistatic( ...
    windowed_adsb_tracks, ...
    scenario_config.tx_lla_deg_m, ...
    scenario_config.rx_lla_deg_m, ...
    double(scenario_config.center_frequency_hz));
aligned_bistatic_tracks = alignTruthToRadar( ...
    windowed_bistatic_tracks, ...
    double(scenario_config.radar_epoch_utc), ...
    sample_times_s);

selection_table = localBuildSelectionTable( ...
    windowed_adsb_tracks, ...
    windowed_bistatic_tracks, ...
    aligned_bistatic_tracks, ...
    selected_truth_window_s);
retained_mask = selection_table.Include(:);
retained_adsb_tracks = windowed_adsb_tracks(retained_mask);
[retained_bistatic_tracks, retained_aligned_tracks] = localSelectProjectedTracks( ...
    retained_adsb_tracks, ...
    windowed_bistatic_tracks, ...
    aligned_bistatic_tracks);

[sampled_targets, sampled_bistatic_tracks, track_metadata] = localBuildRetainedTracks( ...
    retained_adsb_tracks, ...
    retained_bistatic_tracks, ...
    retained_aligned_tracks, ...
    sample_times_s, ...
    scenario_config, ...
    session_context);

truth_bundle = struct( ...
    'scenario_id', scenario_config.scenario_id, ...
    'purpose', scenario_config.purpose, ...
    'radar_epoch_utc', scenario_config.radar_epoch_utc, ...
    'tx_lla_deg_m', scenario_config.tx_lla_deg_m, ...
    'rx_lla_deg_m', scenario_config.rx_lla_deg_m, ...
    'sample_times_s', sample_times_s, ...
    'adsb_tracks', retained_adsb_tracks, ...
    'bistatic_tracks', sampled_bistatic_tracks, ...
    'targets', {sampled_targets}, ...
    'track_metadata', track_metadata, ...
    'selection_table', selection_table, ...
    'truth_source_mode', 'capture_adsb_v1', ...
    'selected_truth_window_s', double(selected_truth_window_s), ...
    'capture_manifest_path', char(string(session_context.manifest_path)), ...
    'capture_adsb_files', {session_context.adsb_files_rel}, ...
    'loaded_aircraft_count', double(numel(windowed_adsb_tracks)), ...
    'retained_aircraft_count', double(sum(retained_mask)));
end

function session_context = localResolveSessionContextFromScenario(scenario_config)
if isfield(scenario_config, 'seed_session_context') && ...
        isstruct(scenario_config.seed_session_context) && ...
        isscalar(scenario_config.seed_session_context) && ...
        isfield(scenario_config.seed_session_context, 'radar_files')
    session_context = scenario_config.seed_session_context;
    return
end

repo_root = fileparts(fileparts(mfilename('fullpath')));
session_context = helperSyntheticResolveSessionContext( ...
    scenario_config.seed_source_path, ...
    'RepoRoot', repo_root);
end

function selected_truth_window_s = localResolveSelectedTruthWindowS( ...
    scenario_config, session_context)
if isfield(scenario_config, 'selected_truth_window_s') && ...
        ~isempty(scenario_config.selected_truth_window_s)
    selected_truth_window_s = double(scenario_config.selected_truth_window_s);
elseif isfield(scenario_config, 'expected_overlap_window_s') && ...
        numel(scenario_config.expected_overlap_window_s) >= 2
    selected_truth_window_s = double(scenario_config.expected_overlap_window_s(2));
else
    selected_truth_window_s = double(session_context.radar_active_window_s);
end
end

function sample_times_s = localBuildSampleTimes(capture_window_s, truth_sample_period_s)
n_steps = floor(capture_window_s / truth_sample_period_s) + 1;
sample_times_s = (0 : n_steps - 1).' * truth_sample_period_s;

if sample_times_s(end) < capture_window_s
    sample_times_s(end + 1, 1) = capture_window_s;
else
    sample_times_s(end, 1) = capture_window_s;
end
end

function clipped_tracks = localClipADSBTracksToWindow( ...
    adsb_tracks, radar_epoch_utc, selected_truth_window_s)
clipped_tracks = adsb_tracks;

for idx = 1 : numel(adsb_tracks)
    t_rel_s = double(adsb_tracks(idx).t_utc(:)) - radar_epoch_utc;
    in_window_mask = t_rel_s >= 0 & t_rel_s <= selected_truth_window_s;

    clipped_tracks(idx).t_utc = adsb_tracks(idx).t_utc(in_window_mask);
    clipped_tracks(idx).lat_deg = adsb_tracks(idx).lat_deg(in_window_mask);
    clipped_tracks(idx).lon_deg = adsb_tracks(idx).lon_deg(in_window_mask);
    clipped_tracks(idx).alt_m = adsb_tracks(idx).alt_m(in_window_mask);
    clipped_tracks(idx).speed_mps = adsb_tracks(idx).speed_mps(in_window_mask);
    clipped_tracks(idx).track_deg = adsb_tracks(idx).track_deg(in_window_mask);
    clipped_tracks(idx).vrate_mps = adsb_tracks(idx).vrate_mps(in_window_mask);
end
end

function selection_table = localBuildSelectionTable( ...
    windowed_adsb_tracks, windowed_bistatic_tracks, aligned_bistatic_tracks, ...
    selected_truth_window_s)
n_tracks = numel(windowed_adsb_tracks);

icao_hex = strings(n_tracks, 1);
callsign = strings(n_tracks, 1);
in_window_fix_count = zeros(n_tracks, 1);
projected_fix_count = zeros(n_tracks, 1);
overlap_s = zeros(n_tracks, 1);
aligned_valid_sample_count = zeros(n_tracks, 1);
aligned_beyond_guard_count = zeros(n_tracks, 1);
minimum_aligned_range_excess_m = NaN(n_tracks, 1);
include = false(n_tracks, 1);
reason = strings(n_tracks, 1);

for idx = 1 : n_tracks
    adsb_track = windowed_adsb_tracks(idx);
    track_key = localTrackKey(adsb_track.hex);
    bistatic_idx = localFindTrackIndex(windowed_bistatic_tracks, track_key);
    aligned_idx = localFindTrackIndex(aligned_bistatic_tracks, track_key);

    icao_hex(idx) = string(adsb_track.hex);
    callsign(idx) = string(adsb_track.callsign);
    in_window_fix_count(idx) = numel(adsb_track.t_utc);

    if in_window_fix_count(idx) < 2
        reason(idx) = "fewer_than_2_in_window_adsb_fixes";
        continue
    end

    if isempty(bistatic_idx)
        reason(idx) = "nonfinite_or_nonphysical_bistatic_projection";
        continue
    end

    projected_fix_count(idx) = numel(windowed_bistatic_tracks(bistatic_idx).t_utc);
    if isempty(aligned_idx)
        reason(idx) = "no_aligned_samples";
        continue
    end

    overlap_s(idx) = double(aligned_bistatic_tracks(aligned_idx).overlap_s);
    valid_mask = isfinite(aligned_bistatic_tracks(aligned_idx).R_excess_m(:)) & ...
        isfinite(aligned_bistatic_tracks(aligned_idx).f_D_hz(:));
    beyond_guard_mask = valid_mask & ...
        aligned_bistatic_tracks(aligned_idx).R_excess_m(:) >= 5e3;
    aligned_valid_sample_count(idx) = sum(valid_mask);
    aligned_beyond_guard_count(idx) = sum(beyond_guard_mask);

    if any(valid_mask)
        minimum_aligned_range_excess_m(idx) = min( ...
            aligned_bistatic_tracks(aligned_idx).R_excess_m(valid_mask), ...
            [], ...
            'omitnan');
    end

    if aligned_valid_sample_count(idx) < 1
        reason(idx) = "no_aligned_samples";
    elseif aligned_beyond_guard_count(idx) < 1
        reason(idx) = "below_5km_near_range_guard";
    else
        include(idx) = true;
        reason(idx) = "retained_overlap_geometry_inclusive_v1";
    end
end

selection_table = table( ...
    icao_hex, ...
    callsign, ...
    repmat(double(selected_truth_window_s), n_tracks, 1), ...
    in_window_fix_count, ...
    projected_fix_count, ...
    overlap_s, ...
    aligned_valid_sample_count, ...
    aligned_beyond_guard_count, ...
    minimum_aligned_range_excess_m, ...
    include, ...
    reason, ...
    'VariableNames', { ...
        'ICAOHex', ...
        'Callsign', ...
        'SelectedWindowS', ...
        'InWindowFixCount', ...
        'ProjectedFixCount', ...
        'OverlapS', ...
        'AlignedValidSampleCount', ...
        'AlignedBeyondGuardSampleCount', ...
        'MinimumAlignedRangeExcessM', ...
        'Include', ...
        'Reason'});
end

function [sampled_targets, sampled_bistatic_tracks, track_metadata] = localBuildRetainedTracks( ...
    retained_adsb_tracks, retained_bistatic_tracks, retained_aligned_tracks, ...
    sample_times_s, scenario_config, session_context)
n_tracks = numel(retained_adsb_tracks);

sampled_targets = repmat(struct( ...
    'target_id', '', ...
    'icao_hex', '', ...
    'callsign', '', ...
    't_rel_s', zeros(0, 1), ...
    't_utc', zeros(0, 1), ...
    'lat_deg', zeros(0, 1), ...
    'lon_deg', zeros(0, 1), ...
    'alt_m', zeros(0, 1), ...
    'north_mps', zeros(0, 1), ...
    'east_mps', zeros(0, 1), ...
    'down_mps', zeros(0, 1), ...
    'speed_mps', zeros(0, 1), ...
    'track_deg', zeros(0, 1), ...
    'vrate_mps', zeros(0, 1)), 1, n_tracks);

sampled_bistatic_tracks = repmat(struct( ...
    'hex', '', ...
    'callsign', '', ...
    't_utc', zeros(0, 1), ...
    'R_excess_m', zeros(0, 1), ...
    'f_D_hz', zeros(0, 1), ...
    'lat_deg', zeros(0, 1), ...
    'lon_deg', zeros(0, 1), ...
    'alt_m', zeros(0, 1), ...
    'L_m', NaN), 1, n_tracks);

track_metadata = repmat(struct( ...
    'target_id', '', ...
    'hex', '', ...
    'callsign', '', ...
    'truth_source_mode', 'capture_adsb_v1', ...
    'echo_gain_db', NaN, ...
    'echo_gain_policy', '', ...
    'selection_reason', 'retained_overlap_geometry_inclusive_v1', ...
    'capture_manifest_path', '', ...
    'in_window_fix_count', 0, ...
    'aligned_valid_sample_count', 0, ...
    'aligned_beyond_guard_sample_count', 0), 1, n_tracks);

for idx = 1 : n_tracks
    adsb_track = retained_adsb_tracks(idx);
    aligned_track = retained_aligned_tracks(idx);
    bistatic_track = retained_bistatic_tracks(idx);
    target_id = localCaptureTargetID(adsb_track.hex, adsb_track.callsign, idx);

    valid_aligned_mask = isfinite(aligned_track.R_excess_m(:)) & ...
        isfinite(aligned_track.f_D_hz(:));
    target_sample_times_s = sample_times_s(valid_aligned_mask);

    trajectory = geoTrajectory( ...
        [adsb_track.lat_deg(:), adsb_track.lon_deg(:), adsb_track.alt_m(:)], ...
        double(adsb_track.t_utc(:)) - double(scenario_config.radar_epoch_utc), ...
        'ReferenceFrame', 'NED');
    [position_lla_deg_m, ~, velocity_ned_mps] = lookupPose(trajectory, target_sample_times_s);
    speed_mps = hypot(velocity_ned_mps(:, 1), velocity_ned_mps(:, 2));
    track_deg = mod(atan2d(velocity_ned_mps(:, 2), velocity_ned_mps(:, 1)), 360);
    vrate_mps = -velocity_ned_mps(:, 3);
    echo_gain_db = localResolveCaptureEchoGainDB(bistatic_track, scenario_config);

    sampled_targets(idx) = struct( ...
        'target_id', target_id, ...
        'icao_hex', char(string(adsb_track.hex)), ...
        'callsign', char(string(adsb_track.callsign)), ...
        't_rel_s', target_sample_times_s, ...
        't_utc', double(scenario_config.radar_epoch_utc) + target_sample_times_s, ...
        'lat_deg', position_lla_deg_m(:, 1), ...
        'lon_deg', position_lla_deg_m(:, 2), ...
        'alt_m', position_lla_deg_m(:, 3), ...
        'north_mps', velocity_ned_mps(:, 1), ...
        'east_mps', velocity_ned_mps(:, 2), ...
        'down_mps', velocity_ned_mps(:, 3), ...
        'speed_mps', speed_mps, ...
        'track_deg', track_deg, ...
        'vrate_mps', vrate_mps);

    sampled_bistatic_tracks(idx) = struct( ...
        'hex', char(string(adsb_track.hex)), ...
        'callsign', char(string(adsb_track.callsign)), ...
        't_utc', double(scenario_config.radar_epoch_utc) + sample_times_s, ...
        'R_excess_m', double(aligned_track.R_excess_m(:)), ...
        'f_D_hz', double(aligned_track.f_D_hz(:)), ...
        'lat_deg', localProjectFullTimeline( ...
            sampled_targets(idx).t_rel_s, ...
            sampled_targets(idx).lat_deg, ...
            sample_times_s), ...
        'lon_deg', localProjectFullTimeline( ...
            sampled_targets(idx).t_rel_s, ...
            sampled_targets(idx).lon_deg, ...
            sample_times_s), ...
        'alt_m', localProjectFullTimeline( ...
            sampled_targets(idx).t_rel_s, ...
            sampled_targets(idx).alt_m, ...
            sample_times_s), ...
        'L_m', double(bistatic_track.L_m));

    track_metadata(idx) = struct( ...
        'target_id', target_id, ...
        'hex', char(string(adsb_track.hex)), ...
        'callsign', char(string(adsb_track.callsign)), ...
        'truth_source_mode', 'capture_adsb_v1', ...
        'echo_gain_db', echo_gain_db, ...
        'echo_gain_policy', char(string(scenario_config.capture_echo_gain_policy)), ...
        'selection_reason', 'retained_overlap_geometry_inclusive_v1', ...
        'capture_manifest_path', char(string(session_context.manifest_path)), ...
        'in_window_fix_count', double(numel(adsb_track.t_utc)), ...
        'aligned_valid_sample_count', double(sum(valid_aligned_mask)), ...
        'aligned_beyond_guard_sample_count', double(sum( ...
            valid_aligned_mask & aligned_track.R_excess_m(:) >= 5e3)));
end
end

function projected_values = localProjectFullTimeline( ...
    source_times_s, source_values, sample_times_s)
projected_values = NaN(numel(sample_times_s), 1);
if isempty(source_times_s)
    return
end

[~, source_idx, sample_idx] = intersect( ...
    double(source_times_s(:)), ...
    double(sample_times_s(:)));
projected_values(sample_idx) = double(source_values(source_idx));
end

function echo_gain_db = localResolveCaptureEchoGainDB(bistatic_track, scenario_config)
gain_policy = char(string(scenario_config.capture_echo_gain_policy));
if ~strcmp(gain_policy, 'range_only_heuristic_v1')
    error('helperSyntheticBuildCaptureTruthBundle:unsupportedEchoGainPolicy', ...
        'Unsupported CaptureEchoGainPolicy: %s', gain_policy);
end

valid_range_mask = isfinite(bistatic_track.R_excess_m(:));
if ~any(valid_range_mask)
    echo_gain_db = NaN;
    return
end

baseline_m = double(bistatic_track.L_m);
total_path_m = baseline_m + double(bistatic_track.R_excess_m(valid_range_mask));
median_total_path_m = median(total_path_m, 'omitnan');
echo_gain_db = double(scenario_config.reference_gain_at_100km_db) - ...
    20 .* log10(median_total_path_m ./ 100e3);
end

function track_idx = localFindTrackIndex(track_struct, track_key)
track_idx = [];
if isempty(track_struct)
    return
end

track_keys = arrayfun(@(track) localTrackKey(track.hex), track_struct, 'UniformOutput', false);
track_idx = find(strcmp(track_keys, track_key), 1, 'first');
end

function [retained_bistatic_tracks, retained_aligned_tracks] = localSelectProjectedTracks( ...
    retained_adsb_tracks, windowed_bistatic_tracks, aligned_bistatic_tracks)
n_tracks = numel(retained_adsb_tracks);
if n_tracks == 0
    retained_bistatic_tracks = struct( ...
        'hex', {}, 'callsign', {}, 't_utc', {}, 'R_excess_m', {}, ...
        'f_D_hz', {}, 'lat_deg', {}, 'lon_deg', {}, 'alt_m', {}, 'L_m', {});
    retained_aligned_tracks = struct( ...
        'hex', {}, 'callsign', {}, 't_abs_s', {}, 'R_excess_m', {}, ...
        'f_D_hz', {}, 't_rel_adsb', {}, 'overlap_s', {});
    return
end

retained_bistatic_tracks = repmat(windowed_bistatic_tracks(1), 1, n_tracks);
retained_aligned_tracks = repmat(aligned_bistatic_tracks(1), 1, n_tracks);

for idx = 1 : n_tracks
    track_key = localTrackKey(retained_adsb_tracks(idx).hex);
    bistatic_idx = localFindTrackIndex(windowed_bistatic_tracks, track_key);
    aligned_idx = localFindTrackIndex(aligned_bistatic_tracks, track_key);
    retained_bistatic_tracks(idx) = windowed_bistatic_tracks(bistatic_idx);
    retained_aligned_tracks(idx) = aligned_bistatic_tracks(aligned_idx);
end
end

function track_key = localTrackKey(hex_value)
track_key = upper(char(string(hex_value)));
end

function target_id = localCaptureTargetID(hex_value, callsign, track_idx)
hex_token = upper(char(string(hex_value)));
if strlength(string(hex_token)) > 0
    target_id = hex_token;
elseif strlength(string(callsign)) > 0
    target_id = char(string(callsign));
else
    target_id = sprintf('CAPTURE_%03d', track_idx);
end
end
