function [echo_source_seed, conditioning_summary] = helperSyntheticBuildConditionedEchoSeed( ...
    seed_waveform, sample_rate_hz, conditioning_config)
%HELPERSYNTHETICBUILDCONDITIONEDECHOSEED Build the target-echo seed source.
%
% Plain language:
% The reference and direct-path channels should preserve the seed capture
% because they model the received illuminator itself. The synthetic target
% echoes are different: replaying the seed's strongest narrowband pilot
% line directly into every moving echo can turn a localized target into a
% full-height Doppler column. This helper builds a second seed copy for
% the echo path only. It uses native MATLAB spectral estimation and
% filtering to suppress the dominant pilot-like line, then matches the
% original RMS so the existing per-target echo gains keep the same meaning.

validateattributes(seed_waveform, {'single', 'double'}, {'column', 'nonempty'}, mfilename, 'seed_waveform');
validateattributes(sample_rate_hz, {'numeric'}, {'scalar', 'real', 'finite', 'positive'}, mfilename, 'sample_rate_hz');

if nargin < 3 || isempty(conditioning_config)
    conditioning_config = struct();
end
validateattributes(conditioning_config, {'struct'}, {'scalar'}, mfilename, 'conditioning_config');

conditioning_config = localResolveConditioningConfig(conditioning_config, double(sample_rate_hz));
seed_waveform = seed_waveform(:);
seed_double = double(seed_waveform);
rms_in = rms(seed_double);

analysis_sample_count = min(numel(seed_double), conditioning_config.max_analysis_samples);
analysis_waveform = seed_double(1:analysis_sample_count);
nfft = max(4096, 2 ^ nextpow2(max(analysis_sample_count, 2)));
[psd_linear, freq_hz] = periodogram( ...
    analysis_waveform, ...
    [], ...
    nfft, ...
    double(sample_rate_hz), ...
    'centered', ...
    'power');
psd_db = 10 * log10(psd_linear + eps);
baseline_db = movmedian( ...
    psd_db, ...
    conditioning_config.baseline_span_bins, ...
    'Endpoints', ...
    'shrink');
[dominant_prominence_db, dominant_idx] = max(psd_db - baseline_db);
dominant_freq_hz = freq_hz(dominant_idx);
dominant_power_db = psd_db(dominant_idx);

conditioned_double = seed_double;
pilot_suppression_applied = false;
filter_kind = 'none';
filter_half_power_hz = [NaN, NaN];

if conditioning_config.enabled && ...
        isfinite(dominant_prominence_db) && ...
        dominant_prominence_db >= conditioning_config.minimum_prominence_db
    [conditioned_double, pilot_suppression_applied, filter_kind, filter_half_power_hz] = ...
        localSuppressDominantLine( ...
            seed_double, ...
            double(sample_rate_hz), ...
            dominant_freq_hz, ...
            conditioning_config);
end

rms_out_raw = rms(conditioned_double);
if pilot_suppression_applied && isfinite(rms_out_raw) && rms_out_raw > 0
    conditioned_double = conditioned_double .* (rms_in / rms_out_raw);
end
rms_out_matched = rms(conditioned_double);

echo_source_seed = complex(single(real(conditioned_double)), single(imag(conditioned_double)));
conditioning_summary = struct( ...
    'enabled', logical(conditioning_config.enabled), ...
    'reference_source', char(string(conditioning_config.reference_source)), ...
    'direct_path_source', char(string(conditioning_config.direct_path_source)), ...
    'target_echo_source', localResolveTargetEchoSource(pilot_suppression_applied, conditioning_config), ...
    'method', char(string(conditioning_config.method)), ...
    'note', char(string(conditioning_config.note)), ...
    'pilot_suppression_applied', logical(pilot_suppression_applied), ...
    'filter_kind', char(string(filter_kind)), ...
    'filter_half_power_hz', double(filter_half_power_hz), ...
    'dominant_line_freq_hz', double(dominant_freq_hz), ...
    'dominant_line_power_db', double(dominant_power_db), ...
    'dominant_line_prominence_db', double(dominant_prominence_db), ...
    'minimum_prominence_db', double(conditioning_config.minimum_prominence_db), ...
    'notch_half_width_hz', double(conditioning_config.notch_half_width_hz), ...
    'dc_highpass_cutoff_hz', double(conditioning_config.dc_highpass_cutoff_hz), ...
    'analysis_sample_count', double(analysis_sample_count), ...
    'baseline_span_bins', double(conditioning_config.baseline_span_bins), ...
    'rms_in', double(rms_in), ...
    'rms_out_raw', double(rms_out_raw), ...
    'rms_out_matched', double(rms_out_matched));
end

function conditioning_config = localResolveConditioningConfig(conditioning_config_in, sample_rate_hz)
conditioning_config = struct( ...
    'enabled', true, ...
    'reference_source', 'full_seed', ...
    'direct_path_source', 'full_seed', ...
    'target_echo_source', 'conditioned_seed', ...
    'method', 'dominant_line_notch_then_rms_match_v1', ...
    'minimum_prominence_db', 10, ...
    'notch_half_width_hz', min(50e3, 0.01 * sample_rate_hz), ...
    'dc_highpass_cutoff_hz', min(50e3, 0.01 * sample_rate_hz), ...
    'max_analysis_samples', 65536, ...
    'baseline_span_bins', 129, ...
    'note', ['Reference and direct-path channels keep the full seed. ' ...
        'Synthetic target echoes use a lightly conditioned seed copy so a dominant ' ...
        'pilot-like line does not create full-height Doppler columns.']);

field_names = fieldnames(conditioning_config_in);
for idx = 1 : numel(field_names)
    conditioning_config.(field_names{idx}) = conditioning_config_in.(field_names{idx});
end

conditioning_config.enabled = logical(conditioning_config.enabled);
conditioning_config.minimum_prominence_db = max(double(conditioning_config.minimum_prominence_db), 0);
conditioning_config.notch_half_width_hz = max(double(conditioning_config.notch_half_width_hz), 1e3);
conditioning_config.dc_highpass_cutoff_hz = max(double(conditioning_config.dc_highpass_cutoff_hz), 1e3);
conditioning_config.max_analysis_samples = max(round(double(conditioning_config.max_analysis_samples)), 1024);
conditioning_config.baseline_span_bins = max(round(double(conditioning_config.baseline_span_bins)), 33);

if mod(conditioning_config.baseline_span_bins, 2) == 0
    conditioning_config.baseline_span_bins = conditioning_config.baseline_span_bins + 1;
end
end

function [conditioned_double, pilot_suppression_applied, filter_kind, filter_half_power_hz] = ...
    localSuppressDominantLine(seed_double, sample_rate_hz, dominant_freq_hz, conditioning_config)
conditioned_double = seed_double;
pilot_suppression_applied = false;
filter_kind = 'none';
filter_half_power_hz = [NaN, NaN];

abs_freq_hz = abs(double(dominant_freq_hz));
nyquist_hz = sample_rate_hz / 2;

if abs_freq_hz <= conditioning_config.dc_highpass_cutoff_hz
    cutoff_hz = min(conditioning_config.dc_highpass_cutoff_hz, nyquist_hz - 1e3);
    if cutoff_hz > 1e3
        filter_object = designfilt( ...
            'highpassiir', ...
            'FilterOrder', 8, ...
            'HalfPowerFrequency', cutoff_hz, ...
            'DesignMethod', 'butter', ...
            'SampleRate', sample_rate_hz);
        conditioned_double = filtfilt(filter_object, seed_double);
        pilot_suppression_applied = true;
        filter_kind = 'highpass';
        filter_half_power_hz = [0, cutoff_hz];
    end
    return
end

lower_half_power_hz = max(1e3, abs_freq_hz - conditioning_config.notch_half_width_hz);
upper_half_power_hz = min(nyquist_hz - 1e3, abs_freq_hz + conditioning_config.notch_half_width_hz);
if upper_half_power_hz <= lower_half_power_hz + 1e3
    return
end

filter_object = designfilt( ...
    'bandstopiir', ...
    'FilterOrder', 8, ...
    'HalfPowerFrequency1', lower_half_power_hz, ...
    'HalfPowerFrequency2', upper_half_power_hz, ...
    'DesignMethod', 'butter', ...
    'SampleRate', sample_rate_hz);
conditioned_double = filtfilt(filter_object, seed_double);
pilot_suppression_applied = true;
filter_kind = 'bandstop';
filter_half_power_hz = [lower_half_power_hz, upper_half_power_hz];
end

function target_echo_source = localResolveTargetEchoSource(pilot_suppression_applied, conditioning_config)
if ~conditioning_config.enabled
    target_echo_source = char(string(conditioning_config.target_echo_source));
elseif pilot_suppression_applied
    target_echo_source = 'conditioned_seed';
else
    target_echo_source = 'full_seed';
end
end
