function targets = helperSyntheticBuildValidationConfidenceTargets(tx_lla_deg_m, rx_lla_deg_m, active_window_s)
%HELPERSYNTHETICBUILDVALIDATIONCONFIDENCETARGETS Build far-from-direct-path validation targets.
%
% Plain language:
% The closed-loop validation scene should be easy to inspect in the RDMs,
% but it also needs to look more like a target we would hope to separate
% from the direct path in real data. These targets are therefore placed
% well outside the current 5 km near-range guard while keeping modest,
% easy-to-read Doppler separation.

validateattributes(tx_lla_deg_m, {'numeric'}, {'numel', 3, 'real', 'finite'}, ...
    mfilename, 'tx_lla_deg_m');
validateattributes(rx_lla_deg_m, {'numeric'}, {'numel', 3, 'real', 'finite'}, ...
    mfilename, 'rx_lla_deg_m');
validateattributes(active_window_s, {'numeric'}, {'scalar', 'real', 'finite', 'positive'}, ...
    mfilename, 'active_window_s');

scene_lat_deg = mean([tx_lla_deg_m(1), rx_lla_deg_m(1)]);
scene_lon_deg = mean([tx_lla_deg_m(2), rx_lla_deg_m(2)]);
confidence_arrival_s = [0; active_window_s];

% These offsets were chosen by inspecting the resulting bistatic geometry
% against the Apple Hill / CBS baseline so the targets sit near
% 8.9–10.2 km range excess instead of hugging the 0 m direct-path region.
targets(1) = struct( ...
    'target_id', 'TGT101', ...
    'icao_hex', 'C0F101', ...
    'callsign', 'CONF101', ...
    'echo_gain_db', -16, ...
    'waypoints_lla_deg_m', [ ...
        scene_lat_deg + 0.060000, scene_lon_deg - 0.060000, 3200; ...
        scene_lat_deg + 0.060000, scene_lon_deg - 0.059800, 3200], ...
    'time_of_arrival_s', confidence_arrival_s);

targets(2) = struct( ...
    'target_id', 'TGT102', ...
    'icao_hex', 'C0F102', ...
    'callsign', 'CONF102', ...
    'echo_gain_db', -18, ...
    'waypoints_lla_deg_m', [ ...
        scene_lat_deg + 0.020000, scene_lon_deg + 0.100000, 3000; ...
        scene_lat_deg + 0.020000, scene_lon_deg + 0.100200, 3000], ...
    'time_of_arrival_s', confidence_arrival_s);
end
