function validation_summary = helperSyntheticValidateGeneratedIQ(session_source, varargin)
%HELPERSYNTHETICVALIDATEGENERATEDIQ Run the session-level signal-physics readiness gate.
%
% Plain language:
% The readiness gate reads one generated synthetic session, checks every
% packaged radar part against the truth that drove synthesis, aggregates
% the per-part results into explicit pass/fail readiness decisions, and
% writes a compact readiness summary back into the session manifest. The
% same entry point accepts either the in-memory artifact returned by
% `generateSyntheticHDTVSession` or an existing session folder or manifest
% path on disk.

helperSyntheticEnsureProjectPaths();

p = inputParser;
p.FunctionName = mfilename;
addRequired(p, 'session_source', @(x) isstruct(x) || ischar(x) || isstring(x));
addParameter(p, 'PartIndex', [], @(x) isempty(x) || (isnumeric(x) && isscalar(x) && x >= 1 && mod(x, 1) == 0));
addParameter(p, 'PlotFigures', true, @(x) islogical(x) && isscalar(x));
addParameter(p, 'PrecheckFigures', false, @(x) islogical(x) && isscalar(x));
addParameter(p, 'FigureVisibility', 'on', @(x) any(strcmpi(string(x), ["on", "off"])));
addParameter(p, 'RangeGateExpansionBins', 3, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'DopplerGateExpansionBins', 2, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'MaxDisplayRangeM', 30e3, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
addParameter(p, 'UpdateManifest', true, @(x) islogical(x) && isscalar(x));
addParameter(p, 'RunEchoModelComparison', false, @(x) islogical(x) && isscalar(x));
addParameter(p, 'Verbose', false, @(x) islogical(x) && isscalar(x));
parse(p, session_source, varargin{:});
opts = p.Results;

session_context = localResolveValidationSource(opts.session_source);
part_indices = localResolvePartIndices(session_context, opts.PartIndex);
part_results = helperSyntheticValidateGeneratedIQPart( ...
    session_context, ...
    'PartIndex', part_indices(1), ...
    'PlotFigures', opts.PlotFigures, ...
    'PrecheckFigures', opts.PrecheckFigures, ...
    'FigureVisibility', char(string(opts.FigureVisibility)), ...
    'RangeGateExpansionBins', opts.RangeGateExpansionBins, ...
    'DopplerGateExpansionBins', opts.DopplerGateExpansionBins, ...
    'MaxDisplayRangeM', opts.MaxDisplayRangeM, ...
    'Verbose', opts.Verbose);
part_results(1).readiness.part_index = part_indices(1);

for idx = 2 : numel(part_indices)
    part_results(idx) = helperSyntheticValidateGeneratedIQPart( ...
        session_context, ...
        'PartIndex', part_indices(idx), ...
        'PlotFigures', opts.PlotFigures, ...
        'PrecheckFigures', opts.PrecheckFigures, ...
        'FigureVisibility', char(string(opts.FigureVisibility)), ...
        'RangeGateExpansionBins', opts.RangeGateExpansionBins, ...
        'DopplerGateExpansionBins', opts.DopplerGateExpansionBins, ...
        'MaxDisplayRangeM', opts.MaxDisplayRangeM, ...
        'Verbose', opts.Verbose);
    part_results(idx).readiness.part_index = part_indices(idx);
end

primary_part = part_results(1);
seed_preservation_summary = localSummarizeSeedPreservationAcrossParts(part_results);
direct_path_summary = localSummarizeDirectPathAcrossParts(part_results);
per_target_summary = localBuildPerTargetSessionSummary(part_results);
target_strength_ordering_summary = localSummarizeStrengthOrderingAcrossParts(part_results);
vertical_column_summary = localSummarizeVerticalColumnsAcrossParts(part_results);
packaging_integrity_pass = all(arrayfun(@(part) part.integrity.overall_pass, part_results));
target_echo_dataset_mode = helperSyntheticDescribeTargetEchoDatasetMode( ...
    char(string(session_context.scenario_config.signal_mode)), ...
    char(string(session_context.scenario_config.seed_echo_source_mode)));
target_placement_pass = ~isempty(per_target_summary) && all([per_target_summary.pass]);

failure_classes = localBuildSessionFailureClasses( ...
    packaging_integrity_pass, ...
    seed_preservation_summary, ...
    direct_path_summary, ...
    target_placement_pass, ...
    target_strength_ordering_summary, ...
    vertical_column_summary);
overall_pass = isempty(failure_classes);

compatibility_smoke = struct( ...
    'status', 'not_requested', ...
    'overall_pass', false, ...
    'note', 'Wrapper replay remains an optional compatibility smoke check for this phase.');

diagnostic_echo_model_comparison = struct( ...
    'status', 'not_requested', ...
    'selected_part_index', NaN);
if opts.RunEchoModelComparison || localFullSeedComparisonEnabled(session_context.scenario_config)
    diagnostic_echo_model_comparison = localRunEchoModelComparison( ...
        session_context, ...
        primary_part, ...
        opts);
end

readiness_summary = struct( ...
    'status', localStatusString(overall_pass), ...
    'overall_pass', overall_pass, ...
    'failure_classes', {failure_classes}, ...
    'n_parts_validated', numel(part_results), ...
    'n_parts_passed', sum(arrayfun(@(part) part.readiness.overall_pass, part_results)), ...
    'packaging_integrity_pass', packaging_integrity_pass, ...
    'seed_preservation', seed_preservation_summary, ...
    'direct_path', direct_path_summary, ...
    'per_target', {per_target_summary}, ...
    'target_placement_pass', target_placement_pass, ...
    'target_strength_ordering', target_strength_ordering_summary, ...
    'vertical_column', vertical_column_summary, ...
    'target_echo_dataset_mode', target_echo_dataset_mode.mode_id, ...
    'target_echo_dataset_label', target_echo_dataset_mode.label, ...
    'recommended_intermediate_algorithm_test_mode', ...
        target_echo_dataset_mode.recommended_intermediate_algorithm_test_mode, ...
    'full_seed_comparison_enabled', localFullSeedComparisonEnabled(session_context.scenario_config), ...
    'compatibility_smoke', compatibility_smoke, ...
    'updated_utc', char(string(datetime('now', 'TimeZone', 'UTC'), 'yyyy-MM-dd''T''HH:mm:ss''Z''')));

validation_summary = struct( ...
    'session_id', string(session_context.session_id), ...
    'session_folder', string(session_context.session_folder), ...
    'manifest_path', string(session_context.manifest_path), ...
    'source_type', string(session_context.source_type), ...
    'echo_generation_model', string(session_context.scenario_config.echo_generation_model), ...
    'target_echo_source_mode', string(session_context.scenario_config.seed_echo_source_mode), ...
    'target_echo_dataset_mode', string(target_echo_dataset_mode.mode_id), ...
    'target_echo_dataset_label', string(target_echo_dataset_mode.label), ...
    'seed_fixture', session_context.seed_fixture_summary, ...
    'evaluated_part_indices', double(part_indices(:).'), ...
    'per_part', {part_results}, ...
    'primary_part', primary_part, ...
    'integrity', primary_part.integrity, ...
    'seed_preservation', primary_part.seed_preservation, ...
    'direct_path', primary_part.direct_path, ...
    'rdm', primary_part.rdm, ...
    'target_summaries', {primary_part.target_summaries}, ...
    'target_prominence_summary', primary_part.target_prominence_summary, ...
    'doppler_column_advisory', primary_part.doppler_column_advisory, ...
    'readiness', readiness_summary, ...
    'compatibility_smoke', compatibility_smoke, ...
    'diagnostic_echo_model_comparison', diagnostic_echo_model_comparison, ...
    'overall_pass', overall_pass, ...
    'failure_classes', {failure_classes});

if opts.UpdateManifest
    localWriteManifestReadinessSummary(session_context.manifest_path, readiness_summary);
end

localPrintSessionSummary(validation_summary);
end

function session_context = localResolveValidationSource(session_source)
if isstruct(session_source)
    session_context = localNormalizeArtifact(session_source);
    session_context.source_type = 'artifact';
    return
end

manifest_path = localResolveManifestPath(session_source);
manifest = helperLoadSessionManifest(manifest_path);
session_folder = fileparts(manifest_path);
traceability_truth_path = fullfile(session_folder, strrep(manifest.traceability_truth_file, '/', filesep));
if exist(traceability_truth_path, 'file') ~= 2
    error('helperSyntheticValidateGeneratedIQ:missingTraceabilityTruth', ...
        'Traceability truth file not found: %s', traceability_truth_path);
end

traceability_context = load(traceability_truth_path);
if ~isfield(traceability_context, 'truth_bundle')
    error('helperSyntheticValidateGeneratedIQ:missingTruthBundle', ...
        'Traceability truth file does not contain truth_bundle: %s', traceability_truth_path);
end
if ~isfield(traceability_context, 'scenario_config')
    error('helperSyntheticValidateGeneratedIQ:missingScenarioConfig', ...
        ['Traceability truth file does not contain scenario_config. ' ...
         'Re-generate the session with the readiness-gate implementation first: %s'], ...
        traceability_truth_path);
end

part_start_offsets_s = localFallbackPartOffsets(traceability_context, manifest);
part_synthesis_summaries = localFallbackPartSummaries(traceability_context, manifest);
seed_fixture_summary = localFallbackSeedFixture(traceability_context, traceability_context.scenario_config);

session_context = struct( ...
    'scenario_config', traceability_context.scenario_config, ...
    'session_id', manifest.session_id, ...
    'session_folder', session_folder, ...
    'manifest_path', manifest_path, ...
    'radar_files', {manifest.radar_files(:).'}, ...
    'truth_bundle', traceability_context.truth_bundle, ...
    'part_start_offsets_s', part_start_offsets_s, ...
    'part_synthesis_summaries', {part_synthesis_summaries(:).'}, ...
    'seed_fixture_summary', seed_fixture_summary, ...
    'source_type', 'manifest');
end

function session_context = localNormalizeArtifact(session_artifact)
required_fields = { ...
    'scenario_config', ...
    'session_id', ...
    'session_folder', ...
    'manifest_path', ...
    'radar_files', ...
    'truth_bundle'};
for idx = 1 : numel(required_fields)
    if ~isfield(session_artifact, required_fields{idx})
        error('helperSyntheticValidateGeneratedIQ:missingArtifactField', ...
            'The artifact struct is missing required field "%s".', required_fields{idx});
    end
end

session_context = session_artifact;
if ~isfield(session_context, 'part_start_offsets_s')
    manifest = helperLoadSessionManifest(session_context.manifest_path);
    session_context.part_start_offsets_s = localFallbackPartOffsets(struct(), manifest);
end
if ~isfield(session_context, 'part_synthesis_summaries')
    session_context.part_synthesis_summaries = cell(numel(session_context.radar_files), 1);
end
if ~isfield(session_context, 'seed_fixture_summary')
    session_context.seed_fixture_summary = helperSyntheticDescribeSeedFixture( ...
        session_context.scenario_config.seed_source_path);
end
end

function manifest_path = localResolveManifestPath(session_source)
session_source = char(string(session_source));
if exist(session_source, 'dir') == 7
    manifest_path = fullfile(session_source, 'session_manifest.json');
elseif exist(session_source, 'file') == 2
    manifest_path = session_source;
else
    error('helperSyntheticValidateGeneratedIQ:missingSource', ...
        'Could not resolve a session folder or manifest path from %s.', session_source);
end
end

function part_indices = localResolvePartIndices(session_context, requested_part_index)
n_parts = numel(session_context.radar_files);
if isempty(requested_part_index)
    part_indices = 1 : n_parts;
else
    if requested_part_index > n_parts
        error('helperSyntheticValidateGeneratedIQ:partIndexOutOfRange', ...
            'PartIndex %d exceeds the %d radar file(s) in this session.', ...
            requested_part_index, n_parts);
    end
    part_indices = requested_part_index;
end
end

function part_start_offsets_s = localFallbackPartOffsets(traceability_context, manifest)
if isfield(traceability_context, 'part_start_offsets_s')
    part_start_offsets_s = double(traceability_context.part_start_offsets_s(:));
    return
end

capture_duration_s = double(manifest.capture_duration_s);
capture_spacing_s = double(manifest.capture_repetition_spacing_s);
n_parts = numel(manifest.radar_files);
part_start_offsets_s = (0 : n_parts - 1).' .* (capture_duration_s + capture_spacing_s);
end

function part_synthesis_summaries = localFallbackPartSummaries(traceability_context, manifest)
n_parts = numel(manifest.radar_files);
if isfield(traceability_context, 'part_synthesis_summaries')
    part_synthesis_summaries = traceability_context.part_synthesis_summaries;
else
    part_synthesis_summaries = cell(n_parts, 1);
end

if numel(part_synthesis_summaries) < n_parts
    part_synthesis_summaries(end + 1 : n_parts) = {[]};
end
end

function seed_fixture_summary = localFallbackSeedFixture(traceability_context, scenario_config)
if isfield(traceability_context, 'seed_fixture_summary')
    seed_fixture_summary = traceability_context.seed_fixture_summary;
else
    seed_fixture_summary = helperSyntheticDescribeSeedFixture(scenario_config.seed_source_path);
end
end

function seed_preservation_summary = localSummarizeSeedPreservationAcrossParts(part_results)
reference_corr = arrayfun(@(part) part.seed_preservation.reference_spectrum_correlation, part_results);
surveillance_corr = arrayfun(@(part) part.seed_preservation.surveillance_spectrum_correlation, part_results);
seed_preservation_summary = struct( ...
    'overall_pass', all(arrayfun(@(part) part.seed_preservation.overall_pass, part_results)), ...
    'minimum_reference_spectrum_correlation', min(reference_corr), ...
    'minimum_surveillance_spectrum_correlation', min(surveillance_corr), ...
    'part_indices_failed', double([part_results(~arrayfun(@(part) part.seed_preservation.overall_pass, part_results)).part_index]));
end

function direct_path_summary = localSummarizeDirectPathAcrossParts(part_results)
abs_residuals = abs(arrayfun(@(part) part.direct_path.residual_samples_fractional, part_results));
direct_path_summary = struct( ...
    'overall_pass', all(arrayfun(@(part) part.direct_path.pass, part_results)), ...
    'median_abs_residual_samples', median(abs_residuals, 'omitnan'), ...
    'worst_abs_residual_samples', max(abs_residuals), ...
    'part_indices_failed', double([part_results(~arrayfun(@(part) part.direct_path.pass, part_results)).part_index]));
end

function per_target_summary = localBuildPerTargetSessionSummary(part_results)
target_ids = strings(0, 1);
target_callsigns = strings(0, 1);
for part_idx = 1 : numel(part_results)
    target_summaries = part_results(part_idx).target_summaries;
    for target_idx = 1 : numel(target_summaries)
        if ~target_summaries(target_idx).present_in_dwell
            continue
        end
        target_ids(end + 1, 1) = string(target_summaries(target_idx).target_id); %#ok<AGROW>
        target_callsigns(end + 1, 1) = string(target_summaries(target_idx).callsign); %#ok<AGROW>
    end
end

unique_target_ids = unique(target_ids, 'stable');
per_target_summary = repmat(struct( ...
    'target_id', '', ...
    'callsign', '', ...
    'n_parts_seen', 0, ...
    'median_abs_range_residual_bins', NaN, ...
    'worst_abs_range_residual_bins', NaN, ...
    'median_abs_doppler_residual_bins', NaN, ...
    'worst_abs_doppler_residual_bins', NaN, ...
    'pass', false), 1, numel(unique_target_ids));

for idx = 1 : numel(unique_target_ids)
    target_id = unique_target_ids(idx);
    range_residual_bins = zeros(0, 1);
    doppler_residual_bins = zeros(0, 1);
    target_callsign = "";

    for part_idx = 1 : numel(part_results)
        target_summaries = part_results(part_idx).target_summaries;
        match_idx = find(strcmp(string({target_summaries.target_id}), target_id), 1, 'first');
        if isempty(match_idx) || ~target_summaries(match_idx).present_in_dwell
            continue
        end

        target_callsign = string(target_summaries(match_idx).callsign);
        if isfinite(target_summaries(match_idx).range_residual_bins)
            range_residual_bins(end + 1, 1) = abs(target_summaries(match_idx).range_residual_bins); %#ok<AGROW>
        end
        if isfinite(target_summaries(match_idx).doppler_residual_bins)
            doppler_residual_bins(end + 1, 1) = abs(target_summaries(match_idx).doppler_residual_bins); %#ok<AGROW>
        end
    end

    per_target_summary(idx).target_id = char(target_id);
    per_target_summary(idx).callsign = char(target_callsign);
    per_target_summary(idx).n_parts_seen = numel(range_residual_bins);
    if ~isempty(range_residual_bins)
        per_target_summary(idx).median_abs_range_residual_bins = median(range_residual_bins, 'omitnan');
        per_target_summary(idx).worst_abs_range_residual_bins = max(range_residual_bins);
    end
    if ~isempty(doppler_residual_bins)
        per_target_summary(idx).median_abs_doppler_residual_bins = median(doppler_residual_bins, 'omitnan');
        per_target_summary(idx).worst_abs_doppler_residual_bins = max(doppler_residual_bins);
    end
    per_target_summary(idx).pass = ...
        isfinite(per_target_summary(idx).median_abs_range_residual_bins) && ...
        isfinite(per_target_summary(idx).worst_abs_range_residual_bins) && ...
        isfinite(per_target_summary(idx).median_abs_doppler_residual_bins) && ...
        isfinite(per_target_summary(idx).worst_abs_doppler_residual_bins) && ...
        per_target_summary(idx).median_abs_range_residual_bins <= 1 && ...
        per_target_summary(idx).worst_abs_range_residual_bins <= 2 && ...
        per_target_summary(idx).median_abs_doppler_residual_bins <= 1 && ...
        per_target_summary(idx).worst_abs_doppler_residual_bins <= 2;
    per_target_summary(idx).n_parts_seen = max(numel(range_residual_bins), numel(doppler_residual_bins));
end
end

function target_strength_ordering_summary = localSummarizeStrengthOrderingAcrossParts(part_results)
part_pass = arrayfun(@(part) part.readiness.target_strength_ordering.pass, part_results);
n_pairs = sum(arrayfun(@(part) part.readiness.target_strength_ordering.n_qualified_pairs, part_results));
target_strength_ordering_summary = struct( ...
    'overall_pass', all(part_pass), ...
    'n_qualified_pairs', n_pairs, ...
    'part_indices_failed', double([part_results(~part_pass).part_index]));
end

function vertical_column_summary = localSummarizeVerticalColumnsAcrossParts(part_results)
part_pass = arrayfun(@(part) part.doppler_column_advisory.all_targets_clear, part_results);
vertical_column_summary = struct( ...
    'overall_pass', all(part_pass), ...
    'n_flagged_parts', sum(~part_pass), ...
    'part_indices_failed', double([part_results(~part_pass).part_index]));
end

function failure_classes = localBuildSessionFailureClasses( ...
    packaging_integrity_pass, seed_preservation_summary, direct_path_summary, ...
    target_placement_pass, target_strength_ordering_summary, ...
    vertical_column_summary)
failure_classes = strings(0, 1);
if ~packaging_integrity_pass
    failure_classes(end + 1, 1) = "packaging_only_compatibility";
end
if ~seed_preservation_summary.overall_pass
    failure_classes(end + 1, 1) = "seed_preservation_failure";
end
if ~direct_path_summary.overall_pass
    failure_classes(end + 1, 1) = "direct_path_failure";
end
if ~target_placement_pass
    failure_classes(end + 1, 1) = "target_placement_failure";
end
if ~target_strength_ordering_summary.overall_pass
    failure_classes(end + 1, 1) = "target_strength_ordering_failure";
end
if ~vertical_column_summary.overall_pass
    failure_classes(end + 1, 1) = "vertical_column_defect";
end

failure_classes = cellstr(unique(failure_classes, 'stable')).';
end

function localWriteManifestReadinessSummary(manifest_path, readiness_summary)
manifest = jsondecode(fileread(manifest_path));
manifest.readiness_check = readiness_summary;

fid = fopen(manifest_path, 'w');
if fid < 0
    error('helperSyntheticValidateGeneratedIQ:manifestWriteFailed', ...
        'Could not open manifest path for readiness update: %s', manifest_path);
end
cleanup_fid = onCleanup(@() fclose(fid));
manifest_text = char(jsonencode(manifest, 'PrettyPrint', true));
fwrite(fid, manifest_text, 'char');
end

function diagnostic_comparison = localRunEchoModelComparison(session_context, primary_part, opts)
diagnostic_comparison = struct( ...
    'status', 'not_applicable', ...
    'selected_part_index', primary_part.part_index);
if ~strcmp(char(string(session_context.scenario_config.signal_mode)), 'seed_backed_bistatic_v1')
    return
end

diagnostic_config = session_context.scenario_config;
diagnostic_config.output_root = fullfile(tempdir, 'synthetic_hdtv_full_seed_compare');
diagnostic_config.session_id = char(string(session_context.session_id) + "_full_seed_compare");
diagnostic_config.echo_generation_model = localComparisonEchoGenerationModel(diagnostic_config);
diagnostic_config.seed_echo_conditioning = localComparisonSeedEchoConditioning(diagnostic_config);
diagnostic_config.seed_echo_source_mode = localComparisonSeedEchoSourceMode(diagnostic_config);
comparison_target_echo_dataset_mode = helperSyntheticDescribeTargetEchoDatasetMode( ...
    char(string(diagnostic_config.signal_mode)), ...
    diagnostic_config.seed_echo_source_mode);
diagnostic_config.target_echo_dataset_mode = comparison_target_echo_dataset_mode.mode_id;
diagnostic_config.target_echo_dataset_label = comparison_target_echo_dataset_mode.label;
diagnostic_config.recommended_intermediate_algorithm_test_mode = ...
    comparison_target_echo_dataset_mode.recommended_intermediate_algorithm_test_mode;
diagnostic_config.full_seed_comparison_enabled = false;
diagnostic_config.diagnostic_conditioned_echo_enabled = false;

if exist(fullfile(diagnostic_config.output_root, diagnostic_config.session_id), 'dir') == 7
    rmdir(fullfile(diagnostic_config.output_root, diagnostic_config.session_id), 's');
end

diagnostic_artifact = generateSyntheticHDTVSession('ScenarioConfig', diagnostic_config);
diagnostic_part = helperSyntheticValidateGeneratedIQPart( ...
    diagnostic_artifact, ...
    'PartIndex', primary_part.part_index, ...
    'PlotFigures', false, ...
    'PrecheckFigures', false, ...
    'FigureVisibility', char(string(opts.FigureVisibility)), ...
    'RangeGateExpansionBins', opts.RangeGateExpansionBins, ...
    'DopplerGateExpansionBins', opts.DopplerGateExpansionBins, ...
    'MaxDisplayRangeM', opts.MaxDisplayRangeM, ...
    'Verbose', opts.Verbose);

diagnostic_comparison = struct( ...
    'status', 'completed', ...
    'selected_part_index', primary_part.part_index, ...
    'primary', localSummarizePartComparison(primary_part), ...
    'diagnostic', localSummarizePartComparison(diagnostic_part), ...
    'diagnostic_session_folder', string(diagnostic_artifact.session_folder));
end

function summary = localSummarizePartComparison(part_result)
summary = struct( ...
    'echo_generation_model', part_result.echo_generation_model, ...
    'seed_echo_source_mode', part_result.seed_echo_source_mode, ...
    'target_echo_dataset_mode', part_result.target_echo_dataset_mode, ...
    'target_echo_dataset_label', part_result.target_echo_dataset_label, ...
    'overall_pass', part_result.readiness.overall_pass, ...
    'failure_classes', {part_result.readiness.failure_classes}, ...
    'seed_preservation_pass', part_result.readiness.seed_preservation.overall_pass, ...
    'direct_path_pass', part_result.direct_path.pass, ...
    'vertical_column_pass', part_result.doppler_column_advisory.all_targets_clear, ...
    'target_strength_ordering_pass', part_result.readiness.target_strength_ordering.pass);
end

function localPrintSessionSummary(validation_summary)
readiness = validation_summary.readiness;

fprintf('\nSynthetic IQ signal-physics readiness\n');
fprintf('\tSession:\t%s\n', validation_summary.session_id);
fprintf('\tParts validated:\t%d\n', readiness.n_parts_validated);
fprintf('\tEcho model:\t%s\n', validation_summary.echo_generation_model);
fprintf('\tTarget echo source:\t%s\n', validation_summary.target_echo_source_mode);
fprintf('\tTarget echo dataset:\t%s\n', validation_summary.target_echo_dataset_label);
fprintf('\tOverall readiness:\t%s\n', localPassString(readiness.overall_pass));
fprintf('\tFailure classes:\t%s\n', strjoin(string(readiness.failure_classes), ', '));
fprintf('\tSeed preservation:\t%s\n', localPassString(readiness.seed_preservation.overall_pass));
fprintf('\tDirect-path gate:\t%s\tmedian %.3f [samples]\tworst %.3f [samples]\n', ...
    localPassString(readiness.direct_path.overall_pass), ...
    readiness.direct_path.median_abs_residual_samples, ...
    readiness.direct_path.worst_abs_residual_samples);
fprintf('\tTarget placement:\t%s\n', localPassString(readiness.target_placement_pass));
fprintf('\tStrength ordering:\t%s\t%d qualified pair(s)\n', ...
    localPassString(readiness.target_strength_ordering.overall_pass), ...
    readiness.target_strength_ordering.n_qualified_pairs);
fprintf('\tVertical columns:\t%s\n', localPassString(readiness.vertical_column.overall_pass));

for idx = 1 : numel(readiness.per_target)
    target = readiness.per_target(idx);
    fprintf('\t%s (%s):\tR median %.2f / worst %.2f bins\tfd median %.2f / worst %.2f bins\t%s\n', ...
        target.target_id, ...
        target.callsign, ...
        target.median_abs_range_residual_bins, ...
        target.worst_abs_range_residual_bins, ...
        target.median_abs_doppler_residual_bins, ...
        target.worst_abs_doppler_residual_bins, ...
        localPassString(target.pass));
end
end

function label = localPassString(tf)
if tf
    label = 'PASS';
else
    label = 'FAIL';
end
end

function label = localStatusString(tf)
if tf
    label = 'pass';
else
    label = 'fail';
end
end

function enabled = localFullSeedComparisonEnabled(scenario_config)
enabled = false;
if isfield(scenario_config, 'full_seed_comparison_enabled') && ...
        ~isempty(scenario_config.full_seed_comparison_enabled)
    enabled = logical(scenario_config.full_seed_comparison_enabled);
elseif isfield(scenario_config, 'diagnostic_conditioned_echo_enabled') && ...
        ~isempty(scenario_config.diagnostic_conditioned_echo_enabled)
    enabled = logical(scenario_config.diagnostic_conditioned_echo_enabled);
end
end

function model = localComparisonEchoGenerationModel(scenario_config)
model = scenario_config.echo_generation_model;
if isfield(scenario_config, 'comparison_echo_generation_model') && ...
        strlength(string(scenario_config.comparison_echo_generation_model)) > 0
    model = char(string(scenario_config.comparison_echo_generation_model));
elseif isfield(scenario_config, 'diagnostic_echo_generation_model') && ...
        strlength(string(scenario_config.diagnostic_echo_generation_model)) > 0
    model = char(string(scenario_config.diagnostic_echo_generation_model));
end
end

function seed_echo_conditioning = localComparisonSeedEchoConditioning(scenario_config)
seed_echo_conditioning = scenario_config.seed_echo_conditioning;
if isfield(scenario_config, 'comparison_seed_echo_conditioning') && ...
        isstruct(scenario_config.comparison_seed_echo_conditioning) && ...
        isscalar(scenario_config.comparison_seed_echo_conditioning)
    seed_echo_conditioning = scenario_config.comparison_seed_echo_conditioning;
elseif isfield(scenario_config, 'diagnostic_seed_echo_conditioning') && ...
        isstruct(scenario_config.diagnostic_seed_echo_conditioning) && ...
        isscalar(scenario_config.diagnostic_seed_echo_conditioning)
    seed_echo_conditioning = scenario_config.diagnostic_seed_echo_conditioning;
end
end

function seed_echo_source_mode = localComparisonSeedEchoSourceMode(scenario_config)
seed_echo_source_mode = char(string(scenario_config.seed_echo_source_mode));
if isfield(scenario_config, 'comparison_seed_echo_source_mode') && ...
        strlength(string(scenario_config.comparison_seed_echo_source_mode)) > 0
    seed_echo_source_mode = char(string(scenario_config.comparison_seed_echo_source_mode));
elseif isfield(scenario_config, 'diagnostic_seed_echo_source_mode') && ...
        strlength(string(scenario_config.diagnostic_seed_echo_source_mode)) > 0
    seed_echo_source_mode = char(string(scenario_config.diagnostic_seed_echo_source_mode));
end
end
