function truth_bundle = helperSyntheticGenerateTruth(scenario_config)
%HELPERSYNTHETICGENERATETRUTH Generate baseline truth from geoTrajectory.
%
% Plain language:
% The synthetic session needs one truth source that drives every downstream
% artifact. This helper samples each declared aircraft trajectory on a
% shared scenario timeline, converts that motion into an ADS-B-like truth
% struct, and derives measurement-space truth with the same bistatic
% conventions already enforced by the current analysis workflow.
%
% The truth chain is explicit:
%   1. user-defined waypoints -> sampled native trajectory truth
%   2. sampled native trajectory truth -> ADS-B-compatible structs
%   3. ADS-B-compatible structs -> bistatic range/Doppler truth
% That same bistatic truth later drives seed-backed echo synthesis, so the
% preview, written truth artifacts, and generated IQ stay tied together.

validateattributes(scenario_config, {'struct'}, {'scalar'}, mfilename, 'scenario_config');

capture_window_s = scenario_config.part_duration_s * scenario_config.capture_repetitions + ...
    max(scenario_config.capture_repetitions - 1, 0) * scenario_config.capture_repetition_spacing_s;
sample_times_s = localBuildSampleTimes(capture_window_s, scenario_config.truth_sample_period_s);
targets = scenario_config.targets;
n_targets = numel(targets);

adsb_tracks = repmat(struct( ...
    'hex', '', ...
    'callsign', '', ...
    't_utc', zeros(0, 1), ...
    'lat_deg', zeros(0, 1), ...
    'lon_deg', zeros(0, 1), ...
    'alt_m', zeros(0, 1), ...
    'speed_mps', zeros(0, 1), ...
    'track_deg', zeros(0, 1), ...
    'vrate_mps', zeros(0, 1)), 1, n_targets);

traceability_targets = repmat(struct( ...
    'target_id', '', ...
    'icao_hex', '', ...
    'callsign', '', ...
    't_rel_s', zeros(0, 1), ...
    't_utc', zeros(0, 1), ...
    'lat_deg', zeros(0, 1), ...
    'lon_deg', zeros(0, 1), ...
    'alt_m', zeros(0, 1), ...
    'north_mps', zeros(0, 1), ...
    'east_mps', zeros(0, 1), ...
    'down_mps', zeros(0, 1), ...
    'speed_mps', zeros(0, 1), ...
    'track_deg', zeros(0, 1), ...
    'vrate_mps', zeros(0, 1)), 1, n_targets);

for idx = 1 : n_targets
    target_def = targets(idx);

    % Step 1: sample the user-declared waypoint motion on the shared
    % scenario timeline so every downstream artifact sees the same motion.
    trajectory = geoTrajectory( ...
        target_def.waypoints_lla_deg_m, ...
        target_def.time_of_arrival_s, ...
        'ReferenceFrame', 'NED');

    [position_lla_deg_m, ~, velocity_ned_mps] = lookupPose(trajectory, sample_times_s);
    speed_mps = hypot(velocity_ned_mps(:, 1), velocity_ned_mps(:, 2));
    track_deg = mod(atan2d(velocity_ned_mps(:, 2), velocity_ned_mps(:, 1)), 360);
    vrate_mps = -velocity_ned_mps(:, 3);
    t_utc = scenario_config.radar_epoch_utc + sample_times_s;

    % Step 2: store the sampled motion in an ADS-B-compatible struct so
    % the existing truth-alignment workflow can consume it without a new
    % file format.
    adsb_tracks(idx) = struct( ...
        'hex', char(string(target_def.icao_hex)), ...
        'callsign', char(string(target_def.callsign)), ...
        't_utc', t_utc, ...
        'lat_deg', position_lla_deg_m(:, 1), ...
        'lon_deg', position_lla_deg_m(:, 2), ...
        'alt_m', position_lla_deg_m(:, 3), ...
        'speed_mps', speed_mps, ...
        'track_deg', track_deg, ...
        'vrate_mps', vrate_mps);

    traceability_targets(idx) = struct( ...
        'target_id', char(string(target_def.target_id)), ...
        'icao_hex', char(string(target_def.icao_hex)), ...
        'callsign', char(string(target_def.callsign)), ...
        't_rel_s', sample_times_s, ...
        't_utc', t_utc, ...
        'lat_deg', position_lla_deg_m(:, 1), ...
        'lon_deg', position_lla_deg_m(:, 2), ...
        'alt_m', position_lla_deg_m(:, 3), ...
        'north_mps', velocity_ned_mps(:, 1), ...
        'east_mps', velocity_ned_mps(:, 2), ...
        'down_mps', velocity_ned_mps(:, 3), ...
        'speed_mps', speed_mps, ...
        'track_deg', track_deg, ...
        'vrate_mps', vrate_mps);
end

% Step 3: convert the ADS-B-compatible truth into bistatic measurement
% truth. These range-excess and Doppler arrays are what later drive the
% synthetic target delays and Doppler shifts in the generated IQ.
adsb_bistatic = adsbToBistatic( ...
    adsb_tracks, ...
    scenario_config.tx_lla_deg_m, ...
    scenario_config.rx_lla_deg_m, ...
    scenario_config.center_frequency_hz);

truth_bundle = struct( ...
    'scenario_id', scenario_config.scenario_id, ...
    'purpose', scenario_config.purpose, ...
    'radar_epoch_utc', scenario_config.radar_epoch_utc, ...
    'tx_lla_deg_m', scenario_config.tx_lla_deg_m, ...
    'rx_lla_deg_m', scenario_config.rx_lla_deg_m, ...
    'sample_times_s', sample_times_s, ...
    'adsb_tracks', adsb_tracks, ...
    'bistatic_tracks', adsb_bistatic, ...
    'targets', {traceability_targets});
end

function sample_times_s = localBuildSampleTimes(capture_window_s, truth_sample_period_s)
n_steps = floor(capture_window_s / truth_sample_period_s) + 1;
sample_times_s = (0 : n_steps - 1).' * truth_sample_period_s;

if sample_times_s(end) < capture_window_s
    sample_times_s(end + 1, 1) = capture_window_s;
else
    sample_times_s(end, 1) = capture_window_s;
end
end
