function [scenario_summary, target_summary_table] = helperSyntheticSummarizeScenarioConfig(scenario_config)
%HELPERSYNTHETICSUMMARIZESCENARIOCONFIG Summarize timing and target edits.
%
% Plain language:
% The walkthrough exposes the scenario knobs directly, so this helper
% gathers the timing and target values into one compact summary before
% generation. It reports both the overall radar timing window and a per-
% target start/end waypoint table so the user can confirm the intended
% geometry without opening the backend generator.

validateattributes(scenario_config, {'struct'}, {'scalar'}, mfilename, 'scenario_config');

radar_active_window_s = scenario_config.part_duration_s * scenario_config.capture_repetitions + ...
    max(scenario_config.capture_repetitions - 1, 0) * scenario_config.capture_repetition_spacing_s;
radar_recorded_iq_seconds_s = scenario_config.part_duration_s * scenario_config.capture_repetitions;

targets = scenario_config.targets;
n_targets = numel(targets);

target_id = strings(n_targets, 1);
icao_hex = strings(n_targets, 1);
callsign = strings(n_targets, 1);
target_labels = strings(n_targets, 1);
echo_gain_db = NaN(n_targets, 1);
first_arrival_s = NaN(n_targets, 1);
last_arrival_s = NaN(n_targets, 1);
start_lat_deg = NaN(n_targets, 1);
start_lon_deg = NaN(n_targets, 1);
start_alt_m = NaN(n_targets, 1);
end_lat_deg = NaN(n_targets, 1);
end_lon_deg = NaN(n_targets, 1);
end_alt_m = NaN(n_targets, 1);

for idx = 1 : n_targets
    target_def = targets(idx);
    waypoints_lla_deg_m = double(target_def.waypoints_lla_deg_m);
    waypoint_times_s = double(target_def.time_of_arrival_s(:));

    target_id(idx) = string(target_def.target_id);
    icao_hex(idx) = string(target_def.icao_hex);
    callsign(idx) = string(target_def.callsign);
    target_labels(idx) = target_id(idx) + " (" + callsign(idx) + ")";
    echo_gain_db(idx) = double(target_def.echo_gain_db);
    first_arrival_s(idx) = waypoint_times_s(1);
    last_arrival_s(idx) = waypoint_times_s(end);
    start_lat_deg(idx) = waypoints_lla_deg_m(1, 1);
    start_lon_deg(idx) = waypoints_lla_deg_m(1, 2);
    start_alt_m(idx) = waypoints_lla_deg_m(1, 3);
    end_lat_deg(idx) = waypoints_lla_deg_m(end, 1);
    end_lon_deg(idx) = waypoints_lla_deg_m(end, 2);
    end_alt_m(idx) = waypoints_lla_deg_m(end, 3);
end

scenario_summary = struct( ...
    'session_id', string(scenario_config.session_id), ...
    'signal_mode', string(scenario_config.signal_mode), ...
    'terrain_dted_path', string(scenario_config.terrain_dted_path), ...
    'seed_source_path', string(scenario_config.seed_source_path), ...
    'sample_rate_hz', double(scenario_config.sample_rate_hz), ...
    'center_frequency_hz', double(scenario_config.center_frequency_hz), ...
    'part_duration_s', double(scenario_config.part_duration_s), ...
    'capture_repetitions', double(scenario_config.capture_repetitions), ...
    'capture_repetition_spacing_s', double(scenario_config.capture_repetition_spacing_s), ...
    'radar_active_window_s', double(radar_active_window_s), ...
    'radar_recorded_iq_seconds_s', double(radar_recorded_iq_seconds_s), ...
    'truth_sample_period_s', double(scenario_config.truth_sample_period_s), ...
    'n_targets', double(n_targets), ...
    'target_labels', target_labels.');

target_summary_table = table( ...
    target_id, ...
    callsign, ...
    icao_hex, ...
    echo_gain_db, ...
    first_arrival_s, ...
    last_arrival_s, ...
    start_lat_deg, ...
    start_lon_deg, ...
    start_alt_m, ...
    end_lat_deg, ...
    end_lon_deg, ...
    end_alt_m, ...
    'VariableNames', { ...
        'TargetID', ...
        'Callsign', ...
        'ICAOHex', ...
        'EchoGainDB', ...
        'FirstArrivalS', ...
        'LastArrivalS', ...
        'StartLatDeg', ...
        'StartLonDeg', ...
        'StartAltM', ...
        'EndLatDeg', ...
        'EndLonDeg', ...
        'EndAltM'});
end
