function manifest = helperSyntheticBuildManifest(scenario_config, radar_files_rel, adsb_files_rel, traceability_truth_rel, header_readback)
%HELPERSYNTHETICBUILDMANIFEST Build the packaged-session manifest struct.

validateattributes(scenario_config, {'struct'}, {'scalar'}, mfilename, 'scenario_config');
validateattributes(radar_files_rel, {'cell'}, {'vector'}, mfilename, 'radar_files_rel');
validateattributes(adsb_files_rel, {'cell'}, {'vector'}, mfilename, 'adsb_files_rel');
validateattributes(traceability_truth_rel, {'char', 'string'}, {'scalartext'}, mfilename, 'traceability_truth_rel');
validateattributes(header_readback, {'struct'}, {'scalar'}, mfilename, 'header_readback');

radar_active_window_s = scenario_config.part_duration_s * scenario_config.capture_repetitions + ...
    max(scenario_config.capture_repetitions - 1, 0) * scenario_config.capture_repetition_spacing_s;
radar_recorded_iq_seconds_s = scenario_config.part_duration_s * scenario_config.capture_repetitions;

manifest = struct( ...
    'manifest_version', 1, ...
    'session_id', scenario_config.session_id, ...
    'session_folder', scenario_config.session_id, ...
    'session_created_utc', localPosixToIso(scenario_config.radar_epoch_utc), ...
    'capture_duration_s', scenario_config.part_duration_s, ...
    'capture_repetitions', scenario_config.capture_repetitions, ...
    'capture_repetition_spacing_s', scenario_config.capture_repetition_spacing_s, ...
    'radar_active_window_s', radar_active_window_s, ...
    'radar_recorded_iq_seconds_s', radar_recorded_iq_seconds_s, ...
    'lead_seconds_s', 0, ...
    'tail_seconds_s', 0, ...
    'adsb_target_window_s', radar_active_window_s, ...
    'adsb_run_seconds_s', radar_active_window_s, ...
    'adsb_stop_mode', 'synthetic_generation', ...
    'capture_file_base', scenario_config.capture_file_base, ...
    'gain_spec', 'synthetic', ...
    'pi_host', 'synthetic', ...
    'pi_user', 'synthetic', ...
    'remote_log_file', '', ...
    'radar_epoch_utc', scenario_config.radar_epoch_utc, ...
    'sdr_defaults', struct( ...
        'radio_name', 'SyntheticHDTVGenerator', ...
        'center_frequency_hz', scenario_config.center_frequency_hz, ...
        'sample_rate_hz', scenario_config.sample_rate_hz, ...
        'lo_offset_hz', scenario_config.lo_offset_hz), ...
    'header_readback', header_readback, ...
    'radar_files', {radar_files_rel(:).'}, ...
    'adsb_files', {adsb_files_rel(:).'}, ...
    'log_files', {{}}, ...
    'traceability_truth_file', char(string(traceability_truth_rel)), ...
    'data_origin', 'synthetic', ...
    'scenario_id', scenario_config.scenario_id, ...
    'generator_name', scenario_config.generator_name, ...
    'generation_time_utc', localNowIsoUTC(), ...
    'truth_source', scenario_config.truth_source, ...
    'random_seed', scenario_config.random_seed, ...
    'signal_mode', scenario_config.signal_mode, ...
    'seed_source_path', char(string(scenario_config.seed_source_path)), ...
    'seed_channel_index', scenario_config.seed_channel_index, ...
    'seed_echo_source_mode', localManifestEchoSeedSourceMode(scenario_config), ...
    'seed_echo_conditioning', localManifestEchoSeedConditioning(scenario_config), ...
    'reference_gain_db', scenario_config.reference_gain_db, ...
    'direct_path_gain_db', scenario_config.direct_path_gain_db, ...
    'direct_path_delay_samples', scenario_config.direct_path_delay_samples, ...
    'terrain_dted_file', char(string(scenario_config.terrain_dted_path)), ...
    'purpose', scenario_config.purpose);
end

function iso_string = localPosixToIso(t_utc)
dt = datetime(t_utc, 'ConvertFrom', 'posixtime', 'TimeZone', 'UTC');
iso_string = char(string(dt, 'yyyy-MM-dd''T''HH:mm:ss''Z'''));
end

function iso_string = localNowIsoUTC()
iso_string = char(string(datetime('now', 'TimeZone', 'UTC'), 'yyyy-MM-dd''T''HH:mm:ss''Z'''));
end

function seed_echo_source_mode = localManifestEchoSeedSourceMode(scenario_config)
seed_echo_source_mode = 'not_applicable';
if isfield(scenario_config, 'seed_echo_source_mode') && ...
        strlength(string(scenario_config.seed_echo_source_mode)) > 0
    seed_echo_source_mode = char(string(scenario_config.seed_echo_source_mode));
end
end

function seed_echo_conditioning = localManifestEchoSeedConditioning(scenario_config)
seed_echo_conditioning = struct( ...
    'enabled', false, ...
    'reference_source', 'not_applicable', ...
    'direct_path_source', 'not_applicable', ...
    'target_echo_source', 'not_applicable', ...
    'method', 'not_applicable', ...
    'note', 'Manifest does not have a seed-backed echo conditioning summary.');

if isfield(scenario_config, 'seed_echo_conditioning') && ...
        isstruct(scenario_config.seed_echo_conditioning) && ...
        isscalar(scenario_config.seed_echo_conditioning)
    seed_echo_conditioning = scenario_config.seed_echo_conditioning;
end
end
