function globe_preview = helperSyntheticPlotTruthGlobePreview(scenario_config, truth_bundle, varargin)
%HELPERSYNTHETICPLOTTRUTHGLOBEPREVIEW Show sampled synthetic truth on a globe.
%
% Plain language:
% The 2-D scenario overview is good for reading timing and bistatic
% numbers, but it does not answer the visual question "where are the
% aircraft in 3-D space relative to the transmitter and receiver?" This
% helper uses trackingGlobeViewer to place the exact sampled truth used by
% synthesis on a globe, then captures a snapshot into a standard MATLAB
% figure so the walkthrough has a stable artifact even when the live globe
% is interactive.

validateattributes(scenario_config, {'struct'}, {'scalar'}, mfilename, 'scenario_config');
validateattributes(truth_bundle, {'struct'}, {'scalar'}, mfilename, 'truth_bundle');

p = inputParser;
p.FunctionName = mfilename;
addParameter(p, 'ShowLiveViewer', true, @(x) islogical(x) && isscalar(x));
addParameter(p, 'CloseViewerOnReturn', false, @(x) islogical(x) && isscalar(x));
addParameter(p, 'ViewerVisibility', 'on', @(x) ischar(x) || isstring(x));
addParameter(p, 'SnapshotFigureVisibility', 'on', @(x) ischar(x) || isstring(x));
addParameter(p, 'Basemap', 'satellite', @(x) ischar(x) || isstring(x));
addParameter(p, 'Terrain', 'gmted2010', @(x) ischar(x) || isstring(x));
parse(p, varargin{:});
opts = p.Results;

truth_targets = truth_bundle.targets;
n_targets = numel(truth_targets);
target_colors = lines(max(n_targets, 1));
reference_location_lla_deg_m = localResolveReferenceLocation(scenario_config, truth_targets);
camera_position_lla_deg_m = localResolveCameraPosition( ...
    scenario_config, ...
    truth_targets, ...
    reference_location_lla_deg_m);
camera_orientation_deg = [38, -32, 0];
viewer_visibility = localResolveViewerVisibility(opts.ShowLiveViewer, opts.ViewerVisibility);
close_viewer_when_done = logical(opts.CloseViewerOnReturn) || ~logical(opts.ShowLiveViewer);

globe_preview = struct( ...
    'status', "unavailable", ...
    'message', "trackingGlobeViewer preview was not attempted.", ...
    'viewer', [], ...
    'viewer_figure', [], ...
    'snapshot_figure', [], ...
    'snapshot_axes', [], ...
    'snapshot_image', zeros(0, 0, 3, 'uint8'), ...
    'reference_location_lla_deg_m', reference_location_lla_deg_m, ...
    'camera_position_lla_deg_m', camera_position_lla_deg_m, ...
    'camera_orientation_deg', camera_orientation_deg, ...
    'n_targets', double(n_targets), ...
    'used_live_viewer', logical(opts.ShowLiveViewer), ...
    'target_colors', target_colors, ...
    'fallback_reason', "");

if exist('trackingGlobeViewer', 'file') ~= 2
    [snapshot_figure, snapshot_axes, snapshot_image] = localCreateDiagnosticFigure( ...
        'Synthetic Truth 3-D Globe Preview Unavailable', ...
        ['trackingGlobeViewer is unavailable. Install Sensor Fusion and ' ...
         'Tracking Toolbox to render the 3-D truth preview.'], ...
        opts.SnapshotFigureVisibility);
    globe_preview.snapshot_figure = snapshot_figure;
    globe_preview.snapshot_axes = snapshot_axes;
    globe_preview.snapshot_image = snapshot_image;
    globe_preview.message = "trackingGlobeViewer is unavailable in this MATLAB session.";
    globe_preview.fallback_reason = globe_preview.message;
    return
end

viewer_figure = [];

try
    viewer_figure = uifigure( ...
        'Name', 'Synthetic Truth 3-D Globe Viewer', ...
        'Visible', viewer_visibility);

    viewer = trackingGlobeViewer( ...
        viewer_figure, ...
        ReferenceLocation=reference_location_lla_deg_m, ...
        Basemap=string(opts.Basemap), ...
        Terrain=string(opts.Terrain));

    sampled_truth_trajectories = localBuildSampledTruthTrajectories(truth_targets);
    if ~isempty(sampled_truth_trajectories)
        plotTrajectory( ...
            viewer, ...
            sampled_truth_trajectories, ...
            Color=target_colors, ...
            LineWidth=2.0);
    end

    [tx_platform, rx_platform] = localBuildSiteMarkerPlatforms( ...
        scenario_config, ...
        reference_location_lla_deg_m);
    plotPlatform( ...
        viewer, ...
        tx_platform, ...
        "ENU", ...
        TrajectoryMode="None", ...
        Marker="^", ...
        MarkerSize=9, ...
        LineWidth=2, ...
        Color=[0.90, 0.15, 0.05], ...
        LabelStyle="None");
    plotPlatform( ...
        viewer, ...
        rx_platform, ...
        "ENU", ...
        TrajectoryMode="None", ...
        Marker="s", ...
        MarkerSize=9, ...
        LineWidth=2, ...
        Color=[0.05, 0.35, 0.85], ...
        LabelStyle="None");

    [start_platforms, end_platforms] = localBuildTargetEndpointPlatforms( ...
        truth_targets, ...
        reference_location_lla_deg_m);
    if ~isempty(start_platforms)
        plotPlatform( ...
            viewer, ...
            start_platforms, ...
            "ENU", ...
            TrajectoryMode="None", ...
            Marker="d", ...
            MarkerSize=7, ...
            LineWidth=1, ...
            Color=target_colors, ...
            LabelStyle="None");
        plotPlatform( ...
            viewer, ...
            end_platforms, ...
            "ENU", ...
            TrajectoryMode="None", ...
            Marker="s", ...
            MarkerSize=7, ...
            LineWidth=1, ...
            Color=target_colors, ...
            LabelStyle="None");
    end

    campos(viewer, camera_position_lla_deg_m);
    camorient(viewer, camera_orientation_deg);
    drawnow;

    snapshot_image = snapshot(viewer);
    [snapshot_figure, snapshot_axes] = localCreateSnapshotFigure( ...
        snapshot_image, ...
        n_targets, ...
        opts.SnapshotFigureVisibility);

    if close_viewer_when_done
        delete(viewer_figure);
        viewer_figure = [];
        viewer = [];
    end

    globe_preview = struct( ...
        'status', "ready", ...
        'message', "Rendered trackingGlobeViewer-based 3-D truth preview.", ...
        'viewer', viewer, ...
        'viewer_figure', viewer_figure, ...
        'snapshot_figure', snapshot_figure, ...
        'snapshot_axes', snapshot_axes, ...
        'snapshot_image', snapshot_image, ...
        'reference_location_lla_deg_m', reference_location_lla_deg_m, ...
        'camera_position_lla_deg_m', camera_position_lla_deg_m, ...
        'camera_orientation_deg', camera_orientation_deg, ...
        'n_targets', double(n_targets), ...
        'used_live_viewer', logical(opts.ShowLiveViewer) && ~close_viewer_when_done, ...
        'target_colors', target_colors, ...
        'fallback_reason', "");
catch ME
    if ~isempty(viewer_figure) && isvalid(viewer_figure)
        delete(viewer_figure);
    end

    [snapshot_figure, snapshot_axes, snapshot_image] = localCreateDiagnosticFigure( ...
        'Synthetic Truth 3-D Globe Preview Unavailable', ...
        "trackingGlobeViewer failed: " + string(ME.message), ...
        opts.SnapshotFigureVisibility);
    globe_preview.status = "failed";
    globe_preview.snapshot_figure = snapshot_figure;
    globe_preview.snapshot_axes = snapshot_axes;
    globe_preview.snapshot_image = snapshot_image;
    globe_preview.message = "trackingGlobeViewer preview failed; returning a diagnostic figure instead.";
    globe_preview.used_live_viewer = false;
    globe_preview.fallback_reason = string(ME.message);
end
end

function sampled_truth_trajectories = localBuildSampledTruthTrajectories(truth_targets)
n_targets = numel(truth_targets);
sampled_truth_trajectories = cell(n_targets, 1);

for idx = 1 : n_targets
    target_truth = truth_targets(idx);
    sampled_truth_trajectories{idx} = geoTrajectory( ...
        [target_truth.lat_deg(:), target_truth.lon_deg(:), target_truth.alt_m(:)], ...
        target_truth.t_rel_s(:), ...
        'ReferenceFrame', 'NED');
end
end

function [tx_platform, rx_platform] = localBuildSiteMarkerPlatforms( ...
    scenario_config, reference_location_lla_deg_m)
spheroid = wgs84Ellipsoid('meter');
[tx_e_m, tx_n_m, tx_u_m] = geodetic2enu( ...
    scenario_config.tx_lla_deg_m(1), ...
    scenario_config.tx_lla_deg_m(2), ...
    scenario_config.tx_lla_deg_m(3), ...
    reference_location_lla_deg_m(1), ...
    reference_location_lla_deg_m(2), ...
    reference_location_lla_deg_m(3), ...
    spheroid);
[rx_e_m, rx_n_m, rx_u_m] = geodetic2enu( ...
    scenario_config.rx_lla_deg_m(1), ...
    scenario_config.rx_lla_deg_m(2), ...
    scenario_config.rx_lla_deg_m(3), ...
    reference_location_lla_deg_m(1), ...
    reference_location_lla_deg_m(2), ...
    reference_location_lla_deg_m(3), ...
    spheroid);

dimensions = localDefaultPlatformDimensions();
orientation = eye(3);

tx_platform = struct( ...
    'PlatformID', 9001, ...
    'Position', [tx_e_m, tx_n_m, tx_u_m], ...
    'Dimensions', dimensions, ...
    'Orientation', orientation);
rx_platform = struct( ...
    'PlatformID', 9002, ...
    'Position', [rx_e_m, rx_n_m, rx_u_m], ...
    'Dimensions', dimensions, ...
    'Orientation', orientation);
end

function [start_platforms, end_platforms] = localBuildTargetEndpointPlatforms( ...
    truth_targets, reference_location_lla_deg_m)
spheroid = wgs84Ellipsoid('meter');
n_targets = numel(truth_targets);
dimensions = localDefaultPlatformDimensions();
orientation = eye(3);

start_platforms = repmat(struct( ...
    'PlatformID', 0, ...
    'Position', zeros(1, 3), ...
    'Dimensions', dimensions, ...
    'Orientation', orientation), n_targets, 1);
end_platforms = start_platforms;

for idx = 1 : n_targets
    target_truth = truth_targets(idx);

    [start_e_m, start_n_m, start_u_m] = geodetic2enu( ...
        target_truth.lat_deg(1), ...
        target_truth.lon_deg(1), ...
        target_truth.alt_m(1), ...
        reference_location_lla_deg_m(1), ...
        reference_location_lla_deg_m(2), ...
        reference_location_lla_deg_m(3), ...
        spheroid);
    [end_e_m, end_n_m, end_u_m] = geodetic2enu( ...
        target_truth.lat_deg(end), ...
        target_truth.lon_deg(end), ...
        target_truth.alt_m(end), ...
        reference_location_lla_deg_m(1), ...
        reference_location_lla_deg_m(2), ...
        reference_location_lla_deg_m(3), ...
        spheroid);

    start_platforms(idx).PlatformID = 1000 + idx;
    start_platforms(idx).Position = [start_e_m, start_n_m, start_u_m];
    end_platforms(idx).PlatformID = 2000 + idx;
    end_platforms(idx).Position = [end_e_m, end_n_m, end_u_m];
end
end

function reference_location_lla_deg_m = localResolveReferenceLocation( ...
    scenario_config, truth_targets)
[lat_all_deg, lon_all_deg, alt_all_m] = localCollectSceneCoordinates( ...
    scenario_config, truth_targets);

reference_location_lla_deg_m = [ ...
    mean([min(lat_all_deg), max(lat_all_deg)]), ...
    mean([min(lon_all_deg), max(lon_all_deg)]), ...
    mean([min(alt_all_m), max(alt_all_m)])];
end

function camera_position_lla_deg_m = localResolveCameraPosition( ...
    scenario_config, truth_targets, reference_location_lla_deg_m)
[lat_all_deg, lon_all_deg, alt_all_m] = localCollectSceneCoordinates( ...
    scenario_config, truth_targets);
spheroid = wgs84Ellipsoid('meter');
[scene_e_m, scene_n_m, ~] = geodetic2enu( ...
    lat_all_deg, ...
    lon_all_deg, ...
    alt_all_m, ...
    reference_location_lla_deg_m(1), ...
    reference_location_lla_deg_m(2), ...
    reference_location_lla_deg_m(3), ...
    spheroid);

horizontal_extent_m = max(hypot(scene_e_m, scene_n_m));
lat_span_deg = max(lat_all_deg) - min(lat_all_deg);
lon_span_deg = max(lon_all_deg) - min(lon_all_deg);
camera_altitude_m = max(alt_all_m) + max(1.2e4, 2.5 * horizontal_extent_m);

camera_position_lla_deg_m = [ ...
    reference_location_lla_deg_m(1) - max(0.015, 0.45 * lat_span_deg), ...
    reference_location_lla_deg_m(2) - max(0.020, 0.65 * lon_span_deg), ...
    camera_altitude_m];
end

function [lat_all_deg, lon_all_deg, alt_all_m] = localCollectSceneCoordinates( ...
    scenario_config, truth_targets)
lat_cells = arrayfun(@(target) target.lat_deg(:), truth_targets, 'UniformOutput', false);
lon_cells = arrayfun(@(target) target.lon_deg(:), truth_targets, 'UniformOutput', false);
alt_cells = arrayfun(@(target) target.alt_m(:), truth_targets, 'UniformOutput', false);

lat_all_deg = [scenario_config.tx_lla_deg_m(1); scenario_config.rx_lla_deg_m(1)];
lon_all_deg = [scenario_config.tx_lla_deg_m(2); scenario_config.rx_lla_deg_m(2)];
alt_all_m = [scenario_config.tx_lla_deg_m(3); scenario_config.rx_lla_deg_m(3)];

if ~isempty(lat_cells)
    lat_all_deg = [lat_all_deg; vertcat(lat_cells{:})]; %#ok<AGROW>
    lon_all_deg = [lon_all_deg; vertcat(lon_cells{:})]; %#ok<AGROW>
    alt_all_m = [alt_all_m; vertcat(alt_cells{:})]; %#ok<AGROW>
end
end

function [snapshot_figure, snapshot_axes] = localCreateSnapshotFigure( ...
    snapshot_image, n_targets, figure_visibility)
snapshot_figure = figure( ...
    'Name', 'Synthetic Truth 3-D Globe Snapshot', ...
    'NumberTitle', 'off', ...
    'Visible', char(string(figure_visibility)));
snapshot_axes = axes('Parent', snapshot_figure);
image(snapshot_axes, snapshot_image)
axis(snapshot_axes, 'image')
set(snapshot_axes, 'XTick', [], 'YTick', [])
xlabel(snapshot_axes, 'Pixel Column')
ylabel(snapshot_axes, 'Pixel Row')
title(snapshot_axes, { ...
    sprintf('Synthetic Truth 3-D Globe Snapshot | %d target(s)', n_targets), ...
    'Tx = red triangle | Rx = blue square | start = diamond | end = square'})
text(snapshot_axes, 0.02, 0.03, ...
    ['trackingGlobeViewer renders the same sampled truth used by the ' ...
     'synthetic generator.'], ...
    'Units', 'normalized', ...
    'Margin', 4, ...
    'FontSize', 9, ...
    'VerticalAlignment', 'bottom')
end

function [diagnostic_figure, diagnostic_axes, diagnostic_image] = localCreateDiagnosticFigure( ...
    figure_name, diagnostic_message, figure_visibility)
diagnostic_figure = figure( ...
    'Name', figure_name, ...
    'NumberTitle', 'off', ...
    'Visible', char(string(figure_visibility)));
diagnostic_axes = axes('Parent', diagnostic_figure);
axis(diagnostic_axes, [0, 1, 0, 1])
set(diagnostic_axes, 'XTick', [], 'YTick', [])
xlabel(diagnostic_axes, 'Diagnostic Axis')
ylabel(diagnostic_axes, 'Diagnostic Axis')
title(diagnostic_axes, figure_name)
text(diagnostic_axes, 0.05, 0.65, char(string(diagnostic_message)), ...
    'Interpreter', 'none', ...
    'FontSize', 10)
text(diagnostic_axes, 0.05, 0.42, ...
    ['The walkthrough still keeps the 2-D scenario overview and ' ...
     'downstream validation steps available.'], ...
    'FontSize', 9)
frame = getframe(diagnostic_axes);
diagnostic_image = frame.cdata;
end

function dimensions = localDefaultPlatformDimensions()
dimensions = struct( ...
    'Length', 35, ...
    'Width', 28, ...
    'Height', 10, ...
    'OriginOffset', [0, 0, 0]);
end

function viewer_visibility = localResolveViewerVisibility(show_live_viewer, viewer_visibility_in)
if show_live_viewer
    viewer_visibility = char(string(viewer_visibility_in));
else
    viewer_visibility = 'off';
end
end
