function truth_bundle = helperSyntheticGenerateTruth(scenario_config)
%HELPERSYNTHETICGENERATETRUTH Generate normalized truth for synthetic sessions.
%
% Plain language:
% The synthetic session needs one truth bundle that drives every
% downstream artifact. Synthetic waypoint mode samples the declared
% `geoTrajectory` targets directly. Capture-backed mode instead loads
% recorded ADS-B truth from a packaged session and normalizes it onto the
% same bundle contract so the preview, written truth artifacts, and
% generated IQ stay tied together.

validateattributes(scenario_config, {'struct'}, {'scalar'}, mfilename, 'scenario_config');

truth_source_mode = localResolveTruthSourceMode(scenario_config);

switch truth_source_mode
    case 'capture_adsb_v1'
        truth_bundle = helperSyntheticBuildCaptureTruthBundle(scenario_config);

    otherwise
        truth_bundle = localBuildSyntheticTruthBundle(scenario_config);
end
end

function truth_source_mode = localResolveTruthSourceMode(scenario_config)
if isfield(scenario_config, 'truth_source_mode') && ...
        strlength(string(scenario_config.truth_source_mode)) > 0
    truth_source_mode = char(string(scenario_config.truth_source_mode));
    return
end

if isfield(scenario_config, 'truth_source') && ...
        strlength(string(scenario_config.truth_source)) > 0
    truth_source_mode = char(string(scenario_config.truth_source));
else
    truth_source_mode = 'synthetic_waypoints_v1';
end
end

function truth_bundle = localBuildSyntheticTruthBundle(scenario_config)
capture_window_s = scenario_config.part_duration_s * scenario_config.capture_repetitions + ...
    max(scenario_config.capture_repetitions - 1, 0) * scenario_config.capture_repetition_spacing_s;
sample_times_s = localBuildSampleTimes(capture_window_s, scenario_config.truth_sample_period_s);
targets = scenario_config.targets;
n_targets = numel(targets);

adsb_tracks = repmat(struct( ...
    'hex', '', ...
    'callsign', '', ...
    't_utc', zeros(0, 1), ...
    'lat_deg', zeros(0, 1), ...
    'lon_deg', zeros(0, 1), ...
    'alt_m', zeros(0, 1), ...
    'speed_mps', zeros(0, 1), ...
    'track_deg', zeros(0, 1), ...
    'vrate_mps', zeros(0, 1)), 1, n_targets);

traceability_targets = repmat(struct( ...
    'target_id', '', ...
    'icao_hex', '', ...
    'callsign', '', ...
    't_rel_s', zeros(0, 1), ...
    't_utc', zeros(0, 1), ...
    'lat_deg', zeros(0, 1), ...
    'lon_deg', zeros(0, 1), ...
    'alt_m', zeros(0, 1), ...
    'north_mps', zeros(0, 1), ...
    'east_mps', zeros(0, 1), ...
    'down_mps', zeros(0, 1), ...
    'speed_mps', zeros(0, 1), ...
    'track_deg', zeros(0, 1), ...
    'vrate_mps', zeros(0, 1)), 1, n_targets);

track_metadata = repmat(struct( ...
    'target_id', '', ...
    'hex', '', ...
    'callsign', '', ...
    'truth_source_mode', 'synthetic_waypoints_v1', ...
    'echo_gain_db', NaN, ...
    'echo_gain_policy', 'scenario_target_gain_v1', ...
    'selection_reason', 'synthetic_target', ...
    'capture_manifest_path', '', ...
    'in_window_fix_count', 0, ...
    'aligned_valid_sample_count', 0, ...
    'aligned_beyond_guard_sample_count', 0), 1, n_targets);

for idx = 1 : n_targets
    target_def = targets(idx);

    trajectory = geoTrajectory( ...
        target_def.waypoints_lla_deg_m, ...
        target_def.time_of_arrival_s, ...
        'ReferenceFrame', 'NED');

    [position_lla_deg_m, ~, velocity_ned_mps] = lookupPose(trajectory, sample_times_s);
    speed_mps = hypot(velocity_ned_mps(:, 1), velocity_ned_mps(:, 2));
    track_deg = mod(atan2d(velocity_ned_mps(:, 2), velocity_ned_mps(:, 1)), 360);
    vrate_mps = -velocity_ned_mps(:, 3);
    t_utc = scenario_config.radar_epoch_utc + sample_times_s;

    adsb_tracks(idx) = struct( ...
        'hex', char(string(target_def.icao_hex)), ...
        'callsign', char(string(target_def.callsign)), ...
        't_utc', t_utc, ...
        'lat_deg', position_lla_deg_m(:, 1), ...
        'lon_deg', position_lla_deg_m(:, 2), ...
        'alt_m', position_lla_deg_m(:, 3), ...
        'speed_mps', speed_mps, ...
        'track_deg', track_deg, ...
        'vrate_mps', vrate_mps);

    traceability_targets(idx) = struct( ...
        'target_id', char(string(target_def.target_id)), ...
        'icao_hex', char(string(target_def.icao_hex)), ...
        'callsign', char(string(target_def.callsign)), ...
        't_rel_s', sample_times_s, ...
        't_utc', t_utc, ...
        'lat_deg', position_lla_deg_m(:, 1), ...
        'lon_deg', position_lla_deg_m(:, 2), ...
        'alt_m', position_lla_deg_m(:, 3), ...
        'north_mps', velocity_ned_mps(:, 1), ...
        'east_mps', velocity_ned_mps(:, 2), ...
        'down_mps', velocity_ned_mps(:, 3), ...
        'speed_mps', speed_mps, ...
        'track_deg', track_deg, ...
        'vrate_mps', vrate_mps);

    track_metadata(idx) = struct( ...
        'target_id', char(string(target_def.target_id)), ...
        'hex', char(string(target_def.icao_hex)), ...
        'callsign', char(string(target_def.callsign)), ...
        'truth_source_mode', 'synthetic_waypoints_v1', ...
        'echo_gain_db', double(target_def.echo_gain_db), ...
        'echo_gain_policy', 'scenario_target_gain_v1', ...
        'selection_reason', 'synthetic_target', ...
        'capture_manifest_path', '', ...
        'in_window_fix_count', double(numel(sample_times_s)), ...
        'aligned_valid_sample_count', double(numel(sample_times_s)), ...
        'aligned_beyond_guard_sample_count', NaN);
end

adsb_bistatic = adsbToBistatic( ...
    adsb_tracks, ...
    scenario_config.tx_lla_deg_m, ...
    scenario_config.rx_lla_deg_m, ...
    scenario_config.center_frequency_hz);

for idx = 1 : n_targets
    track_metadata(idx).aligned_beyond_guard_sample_count = double(sum( ...
        adsb_bistatic(idx).R_excess_m(:) >= 5e3));
end

minimum_range_excess_m = NaN(n_targets, 1);
aligned_beyond_guard_sample_count = NaN(n_targets, 1);
for idx = 1 : n_targets
    minimum_range_excess_m(idx) = min(adsb_bistatic(idx).R_excess_m(:), [], 'omitnan');
    aligned_beyond_guard_sample_count(idx) = track_metadata(idx).aligned_beyond_guard_sample_count;
end

selection_table = table( ...
    string({traceability_targets.icao_hex}).', ...
    string({traceability_targets.callsign}).', ...
    repmat(double(capture_window_s), n_targets, 1), ...
    repmat(double(numel(sample_times_s)), n_targets, 1), ...
    repmat(double(numel(sample_times_s)), n_targets, 1), ...
    repmat(double(capture_window_s), n_targets, 1), ...
    repmat(double(numel(sample_times_s)), n_targets, 1), ...
    aligned_beyond_guard_sample_count, ...
    minimum_range_excess_m, ...
    true(n_targets, 1), ...
    repmat("synthetic_target", n_targets, 1), ...
    'VariableNames', { ...
        'ICAOHex', ...
        'Callsign', ...
        'SelectedWindowS', ...
        'InWindowFixCount', ...
        'ProjectedFixCount', ...
        'OverlapS', ...
        'AlignedValidSampleCount', ...
        'AlignedBeyondGuardSampleCount', ...
        'MinimumAlignedRangeExcessM', ...
        'Include', ...
        'Reason'});

truth_bundle = struct( ...
    'scenario_id', scenario_config.scenario_id, ...
    'purpose', scenario_config.purpose, ...
    'radar_epoch_utc', scenario_config.radar_epoch_utc, ...
    'tx_lla_deg_m', scenario_config.tx_lla_deg_m, ...
    'rx_lla_deg_m', scenario_config.rx_lla_deg_m, ...
    'sample_times_s', sample_times_s, ...
    'adsb_tracks', adsb_tracks, ...
    'bistatic_tracks', adsb_bistatic, ...
    'targets', {traceability_targets}, ...
    'track_metadata', track_metadata, ...
    'selection_table', selection_table, ...
    'truth_source_mode', 'synthetic_waypoints_v1', ...
    'selected_truth_window_s', double(capture_window_s), ...
    'capture_manifest_path', '', ...
    'capture_adsb_files', {{}}, ...
    'loaded_aircraft_count', double(n_targets), ...
    'retained_aircraft_count', double(n_targets));
end

function sample_times_s = localBuildSampleTimes(capture_window_s, truth_sample_period_s)
n_steps = floor(capture_window_s / truth_sample_period_s) + 1;
sample_times_s = (0 : n_steps - 1).' * truth_sample_period_s;

if sample_times_s(end) < capture_window_s
    sample_times_s(end + 1, 1) = capture_window_s;
else
    sample_times_s(end, 1) = capture_window_s;
end
end
