function [scenario_summary, target_summary_table] = helperSyntheticSummarizeScenarioConfig(scenario_config)
%HELPERSYNTHETICSUMMARIZESCENARIOCONFIG Summarize timing and target edits.
%
% Plain language:
% The walkthrough exposes the scenario knobs directly, so this helper
% gathers the timing and target values into one compact summary before
% generation. It reports both the overall radar timing window and a per-
% target start/end waypoint table so the user can confirm the intended
% geometry without opening the backend generator.

validateattributes(scenario_config, {'struct'}, {'scalar'}, mfilename, 'scenario_config');

radar_active_window_s = scenario_config.part_duration_s * scenario_config.capture_repetitions + ...
    max(scenario_config.capture_repetitions - 1, 0) * scenario_config.capture_repetition_spacing_s;
radar_recorded_iq_seconds_s = scenario_config.part_duration_s * scenario_config.capture_repetitions;
truth_source_mode = localTruthSourceMode(scenario_config);
target_echo_dataset_mode = helperSyntheticDescribeTargetEchoDatasetMode( ...
    char(string(scenario_config.signal_mode)), ...
    char(string(scenario_config.seed_echo_source_mode)));
comparison_seed_echo_source_mode = localComparisonSeedEchoSourceMode(scenario_config);
comparison_target_echo_dataset_mode = helperSyntheticDescribeTargetEchoDatasetMode( ...
    char(string(scenario_config.signal_mode)), ...
    comparison_seed_echo_source_mode);

targets = scenario_config.targets;
n_targets = numel(targets);

target_id = strings(n_targets, 1);
icao_hex = strings(n_targets, 1);
callsign = strings(n_targets, 1);
target_labels = strings(n_targets, 1);
echo_gain_db = NaN(n_targets, 1);
first_arrival_s = NaN(n_targets, 1);
last_arrival_s = NaN(n_targets, 1);
start_lat_deg = NaN(n_targets, 1);
start_lon_deg = NaN(n_targets, 1);
start_alt_m = NaN(n_targets, 1);
end_lat_deg = NaN(n_targets, 1);
end_lon_deg = NaN(n_targets, 1);
end_alt_m = NaN(n_targets, 1);

if ~strcmp(truth_source_mode, 'capture_adsb_v1')
    for idx = 1 : n_targets
        target_def = targets(idx);
        waypoints_lla_deg_m = double(target_def.waypoints_lla_deg_m);
        waypoint_times_s = double(target_def.time_of_arrival_s(:));

        target_id(idx) = string(target_def.target_id);
        icao_hex(idx) = string(target_def.icao_hex);
        callsign(idx) = string(target_def.callsign);
        target_labels(idx) = target_id(idx) + " (" + callsign(idx) + ")";
        echo_gain_db(idx) = double(target_def.echo_gain_db);
        first_arrival_s(idx) = waypoint_times_s(1);
        last_arrival_s(idx) = waypoint_times_s(end);
        start_lat_deg(idx) = waypoints_lla_deg_m(1, 1);
        start_lon_deg(idx) = waypoints_lla_deg_m(1, 2);
        start_alt_m(idx) = waypoints_lla_deg_m(1, 3);
        end_lat_deg(idx) = waypoints_lla_deg_m(end, 1);
        end_lon_deg(idx) = waypoints_lla_deg_m(end, 2);
        end_alt_m(idx) = waypoints_lla_deg_m(end, 3);
    end
else
    n_targets = 0;
    target_labels = strings(1, 0);
end

scenario_summary = struct( ...
    'session_id', string(scenario_config.session_id), ...
    'truth_source_mode', string(truth_source_mode), ...
    'signal_mode', string(scenario_config.signal_mode), ...
    'echo_generation_model', string(scenario_config.echo_generation_model), ...
    'seed_echo_source_mode', string(scenario_config.seed_echo_source_mode), ...
    'target_echo_dataset_mode', string(target_echo_dataset_mode.mode_id), ...
    'target_echo_dataset_label', string(target_echo_dataset_mode.label), ...
    'recommended_intermediate_algorithm_test_mode', ...
        logical(target_echo_dataset_mode.recommended_intermediate_algorithm_test_mode), ...
    'full_seed_comparison_enabled', localFullSeedComparisonEnabled(scenario_config), ...
    'comparison_echo_generation_model', string(localComparisonEchoGenerationModel(scenario_config)), ...
    'comparison_seed_echo_source_mode', string(comparison_seed_echo_source_mode), ...
    'comparison_target_echo_dataset_mode', string(comparison_target_echo_dataset_mode.mode_id), ...
    'comparison_target_echo_dataset_label', string(comparison_target_echo_dataset_mode.label), ...
    'terrain_dted_path', string(scenario_config.terrain_dted_path), ...
    'seed_source_path', string(scenario_config.seed_source_path), ...
    'capture_manifest_path', string(localOptionalStringField(scenario_config, 'capture_manifest_path')), ...
    'sample_rate_hz', double(scenario_config.sample_rate_hz), ...
    'center_frequency_hz', double(scenario_config.center_frequency_hz), ...
    'part_duration_s', double(scenario_config.part_duration_s), ...
    'capture_repetitions', double(scenario_config.capture_repetitions), ...
    'capture_repetition_spacing_s', double(scenario_config.capture_repetition_spacing_s), ...
    'radar_active_window_s', double(radar_active_window_s), ...
    'radar_recorded_iq_seconds_s', double(radar_recorded_iq_seconds_s), ...
    'selected_truth_window_s', localOptionalDoubleField(scenario_config, 'selected_truth_window_s', radar_active_window_s), ...
    'truth_filter_mode', string(localOptionalStringField(scenario_config, 'truth_filter_mode')), ...
    'capture_echo_gain_policy', string(localOptionalStringField(scenario_config, 'capture_echo_gain_policy')), ...
    'truth_sample_period_s', double(scenario_config.truth_sample_period_s), ...
    'n_targets', double(n_targets), ...
    'target_labels', target_labels.');

target_summary_table = table( ...
    target_id(1:n_targets), ...
    callsign(1:n_targets), ...
    icao_hex(1:n_targets), ...
    echo_gain_db(1:n_targets), ...
    first_arrival_s(1:n_targets), ...
    last_arrival_s(1:n_targets), ...
    start_lat_deg(1:n_targets), ...
    start_lon_deg(1:n_targets), ...
    start_alt_m(1:n_targets), ...
    end_lat_deg(1:n_targets), ...
    end_lon_deg(1:n_targets), ...
    end_alt_m(1:n_targets), ...
    'VariableNames', { ...
        'TargetID', ...
        'Callsign', ...
        'ICAOHex', ...
        'EchoGainDB', ...
        'FirstArrivalS', ...
        'LastArrivalS', ...
        'StartLatDeg', ...
        'StartLonDeg', ...
        'StartAltM', ...
        'EndLatDeg', ...
        'EndLonDeg', ...
        'EndAltM'});
end

function enabled = localFullSeedComparisonEnabled(scenario_config)
enabled = false;
if isfield(scenario_config, 'full_seed_comparison_enabled') && ...
        ~isempty(scenario_config.full_seed_comparison_enabled)
    enabled = logical(scenario_config.full_seed_comparison_enabled);
elseif isfield(scenario_config, 'diagnostic_conditioned_echo_enabled') && ...
        ~isempty(scenario_config.diagnostic_conditioned_echo_enabled)
    enabled = logical(scenario_config.diagnostic_conditioned_echo_enabled);
end
end

function truth_source_mode = localTruthSourceMode(scenario_config)
truth_source_mode = 'synthetic_waypoints_v1';
if isfield(scenario_config, 'truth_source_mode') && ...
        strlength(string(scenario_config.truth_source_mode)) > 0
    truth_source_mode = char(string(scenario_config.truth_source_mode));
elseif isfield(scenario_config, 'truth_source') && ...
        strlength(string(scenario_config.truth_source)) > 0
    truth_source_mode = char(string(scenario_config.truth_source));
end
end

function value = localOptionalStringField(scenario_config, field_name)
value = "";
if isfield(scenario_config, field_name) && ...
        strlength(string(scenario_config.(field_name))) > 0
    value = string(scenario_config.(field_name));
end
end

function value = localOptionalDoubleField(scenario_config, field_name, default_value)
value = double(default_value);
if isfield(scenario_config, field_name) && ~isempty(scenario_config.(field_name))
    value = double(scenario_config.(field_name));
end
end

function model = localComparisonEchoGenerationModel(scenario_config)
model = "not_applicable";
if isfield(scenario_config, 'comparison_echo_generation_model') && ...
        strlength(string(scenario_config.comparison_echo_generation_model)) > 0
    model = string(scenario_config.comparison_echo_generation_model);
elseif isfield(scenario_config, 'diagnostic_echo_generation_model') && ...
        strlength(string(scenario_config.diagnostic_echo_generation_model)) > 0
    model = string(scenario_config.diagnostic_echo_generation_model);
end
end

function seed_echo_source_mode = localComparisonSeedEchoSourceMode(scenario_config)
seed_echo_source_mode = "not_applicable";
if isfield(scenario_config, 'comparison_seed_echo_source_mode') && ...
        strlength(string(scenario_config.comparison_seed_echo_source_mode)) > 0
    seed_echo_source_mode = string(scenario_config.comparison_seed_echo_source_mode);
elseif isfield(scenario_config, 'diagnostic_seed_echo_source_mode') && ...
        strlength(string(scenario_config.diagnostic_seed_echo_source_mode)) > 0
    seed_echo_source_mode = string(scenario_config.diagnostic_seed_echo_source_mode);
end
end
