function validation_summary = helperSyntheticValidateGeneratedIQPart(session_artifact, varargin)
%HELPERSYNTHETICVALIDATEGENERATEDIQPART Validate one written synthetic IQ part against truth.
%
% Plain language:
% The synthetic workflow intentionally reuses one truth source end to end.
% User-edited waypoints define synthetic aircraft motion. That motion is
% sampled into traceability truth, converted into ADS-B-compatible structs
% for workflow compatibility, converted again into bistatic range/Doppler
% truth, and then used to synthesize delayed and Doppler-shifted echoes.
% This helper closes the loop by reading the written `.bb` file back and
% checking that the recovered measurement-space content still matches the
% same synthetic truth that drove synthesis.
%
helperSyntheticEnsureProjectPaths();
repo_root = fileparts(fileparts(mfilename('fullpath')));
analysis_folder = fullfile(repo_root, 'BistaticDataAnalysis');
original_folder = pwd;
cleanup_folder = onCleanup(@() cd(original_folder));
cd(analysis_folder);

p = inputParser;
p.FunctionName = mfilename;
addRequired(p, 'session_artifact', @(x) isstruct(x) && isscalar(x));
addParameter(p, 'PartIndex', 1, @(x) isnumeric(x) && isscalar(x) && x >= 1 && mod(x, 1) == 0);
addParameter(p, 'PlotFigures', true, @(x) islogical(x) && isscalar(x));
addParameter(p, 'PrecheckFigures', false, @(x) islogical(x) && isscalar(x));
addParameter(p, 'FigureVisibility', 'on', @(x) any(strcmpi(string(x), ["on", "off"])));
addParameter(p, 'RangeGateExpansionBins', 3, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'DopplerGateExpansionBins', 2, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'MaxDisplayRangeM', 30e3, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
addParameter(p, 'ReferenceSpectrumCorrelationMin', 0.98, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0 && x <= 1);
addParameter(p, 'SurveillanceSpectrumCorrelationMin', 0.90, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0 && x <= 1);
addParameter(p, 'DirectPathResidualMaxSamples', 0.50, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
addParameter(p, 'Verbose', false, @(x) islogical(x) && isscalar(x));
parse(p, session_artifact, varargin{:});
opts = p.Results;

localValidateArtifact(session_artifact);

if opts.PartIndex > numel(session_artifact.radar_files)
    error('helperSyntheticValidateGeneratedIQ:partIndexOutOfRange', ...
        'PartIndex %d exceeds the %d radar file(s) in this artifact.', ...
        opts.PartIndex, numel(session_artifact.radar_files));
end

scenario_config = session_artifact.scenario_config;
truth_bundle = session_artifact.truth_bundle;
manifest = helperLoadSessionManifest(session_artifact.manifest_path);
radar_file_path = localResolveRadarFilePath(session_artifact, opts.PartIndex);
part_start_offset_s = localResolvePartStartOffset(session_artifact, opts.PartIndex);
part_synthesis_summary = localResolvePartSynthesisSummary(session_artifact, opts.PartIndex);

integrity = localValidateBasebandIntegrity(radar_file_path, scenario_config, manifest);
validation_config = localBuildValidationConfig(integrity.header.sample_rate_hz);

% Use the same CPI duration and first-chunk dwell that the current passive
% radar processor uses, but stop after one chunk so validation stays cheap.
validation_sample_count = min( ...
    integrity.header.samples_in_file, ...
    round(validation_config.validation_dwell_s * integrity.header.sample_rate_hz));
[reference_channel, surveillance_channel, reference_cube, surveillance_cube] = loadIQData( ...
    radar_file_path, ...
    validation_sample_count, ...
    validation_config.cpi_duration_s, ...
    integrity.header.sample_rate_hz, ...
    struct('swap_channels', false, 'verbose', opts.Verbose));
[seed_waveform, ~] = helperSyntheticLoadSeedWaveform( ...
    scenario_config, ...
    validation_sample_count, ...
    part_start_offset_s);

n_slow_used = size(surveillance_cube, 2);
if n_slow_used < 1
    error('helperSyntheticValidateGeneratedIQ:noValidationCPIs', ...
        'The selected file does not contain enough samples for one validation CPI.');
end

surveillance_cube = surveillance_cube(:, 1:n_slow_used);
reference_cube = reference_cube(:, 1:n_slow_used);
validation_dwell_s = n_slow_used * validation_config.cpi_duration_s;
validation_query_time_s = part_start_offset_s + ...
    (((0 : n_slow_used - 1).' + 0.5) * validation_config.cpi_duration_s);
spot_check_query_time_s = validation_query_time_s(ceil(numel(validation_query_time_s) / 2));

[~, projected_aligned_tracks, projected_truth_table] = ...
    helperProjectADSBTruthToRangeDoppler( ...
    truth_bundle.adsb_tracks, ...
    scenario_config.tx_lla_deg_m, ...
    scenario_config.rx_lla_deg_m, ...
    double(scenario_config.center_frequency_hz), ...
    double(scenario_config.radar_epoch_utc), ...
    validation_query_time_s);

[rdm_before_db, doppler_axis_hz, range_axis_m, measured_direct_path_lag_samples] = createRDM( ...
    surveillance_cube, ...
    reference_cube, ...
    integrity.header.sample_rate_hz, ...
    validation_config.prf_hz, ...
    [], ...
    opts.Verbose);

range_bin_spacing_m = localAxisSpacing(range_axis_m);
doppler_bin_spacing_hz = localAxisSpacing(doppler_axis_hz);
direct_path_delay_samples_expected = double(scenario_config.direct_path_delay_samples);
max_lag_samples = max(500, ceil(direct_path_delay_samples_expected) + 64);
fractional_lag_summary = localMeasureFractionalLag( ...
    surveillance_channel, ...
    reference_channel, ...
    integrity.header.sample_rate_hz, ...
    max_lag_samples);

% Keep the direct-path precheck in the loop, but treat its pilot/coherence
% outputs as advisory only for this synthetic-validation pass.
precheck_summary = localRunAdvisoryPrecheck( ...
    radar_file_path, ...
    validation_config, ...
    integrity.header.part_duration_header_s, ...
    direct_path_delay_samples_expected, ...
    opts);
seed_preservation_summary = localBuildSeedPreservationSummary( ...
    seed_waveform, ...
    reference_channel, ...
    surveillance_channel, ...
    precheck_summary, ...
    opts);

[target_summaries] = localBuildTargetValidationSummaries( ...
    truth_bundle, ...
    scenario_config, ...
    projected_aligned_tracks, ...
    part_synthesis_summary, ...
    validation_query_time_s, ...
    range_axis_m, ...
    doppler_axis_hz, ...
    rdm_before_db, ...
    range_bin_spacing_m, ...
    doppler_bin_spacing_hz, ...
    opts);
[spot_check_targets, spot_check_table] = localBuildRawSpotCheckSummary( ...
    truth_bundle, ...
    projected_truth_table, ...
    target_summaries, ...
    spot_check_query_time_s, ...
    rdm_before_db, ...
    range_axis_m, ...
    doppler_axis_hz, ...
    range_bin_spacing_m, ...
    doppler_bin_spacing_hz, ...
    opts);

readiness_summary = localBuildReadinessSummary( ...
    target_summaries, ...
    validation_config, ...
    range_bin_spacing_m, ...
    doppler_bin_spacing_hz);
strength_ordering_summary = localBuildTargetStrengthOrderingSummary( ...
    target_summaries, ...
    truth_bundle, ...
    scenario_config);

direct_path_summary = struct( ...
    'configured_delay_samples', double(scenario_config.direct_path_delay_samples), ...
    'comparison_delay_samples', double(direct_path_delay_samples_expected), ...
    'measured_lag_samples_integer', double(measured_direct_path_lag_samples), ...
    'measured_lag_samples_fractional', double(fractional_lag_summary.peak_lag_samples), ...
    'residual_samples_fractional', double(fractional_lag_summary.peak_lag_samples - direct_path_delay_samples_expected), ...
    'residual_samples_integer', double(measured_direct_path_lag_samples - direct_path_delay_samples_expected), ...
    'peak_to_median_db', double(fractional_lag_summary.peak_to_median_db), ...
    'peak_to_second_db', double(fractional_lag_summary.peak_to_second_db), ...
    'max_residual_samples', double(opts.DirectPathResidualMaxSamples), ...
    'pass', abs(double(fractional_lag_summary.peak_lag_samples - direct_path_delay_samples_expected)) <= ...
        double(opts.DirectPathResidualMaxSamples), ...
    'comparison_note', 'Configured fractional direct-path delay is compared directly against a sub-sample lag estimate.');

target_echo_dataset_mode = helperSyntheticDescribeTargetEchoDatasetMode( ...
    char(string(scenario_config.signal_mode)), ...
    localResolvePartSeedEchoSourceMode(part_synthesis_summary, scenario_config));
readiness_summary.seed_preservation = seed_preservation_summary;
readiness_summary.direct_path_pass = direct_path_summary.pass;
readiness_summary.target_strength_ordering = strength_ordering_summary;
readiness_summary.target_echo_dataset_mode = target_echo_dataset_mode.mode_id;
readiness_summary.target_echo_dataset_label = target_echo_dataset_mode.label;
readiness_summary.recommended_intermediate_algorithm_test_mode = ...
    target_echo_dataset_mode.recommended_intermediate_algorithm_test_mode;
readiness_summary.comparison_reference_mode = ...
    target_echo_dataset_mode.comparison_reference_mode;
readiness_summary.failure_classes = localBuildPartFailureClasses( ...
    seed_preservation_summary, ...
    direct_path_summary, ...
    target_summaries, ...
    strength_ordering_summary);
readiness_summary.overall_pass = isempty(readiness_summary.failure_classes);

figure_handles = struct('validation', [], 'precheck', [], 'raw_spot_check', []);
if opts.PlotFigures
    figure_handles.validation = localPlotValidationFigure( ...
        session_artifact, ...
        opts.PartIndex, ...
        integrity.header.sample_rate_hz, ...
        surveillance_channel, ...
        reference_channel, ...
        rdm_before_db, ...
        range_axis_m, ...
        doppler_axis_hz, ...
        direct_path_summary, ...
        precheck_summary, ...
        target_summaries, ...
        spot_check_query_time_s, ...
        spot_check_targets, ...
        opts);
    figure_handles.raw_spot_check = figure_handles.validation;
end
if isstruct(precheck_summary) && isfield(precheck_summary, 'figure_handles')
    figure_handles.precheck = precheck_summary.figure_handles;
end

validation_summary = struct( ...
    'session_id', string(session_artifact.session_id), ...
    'part_index', double(opts.PartIndex), ...
    'radar_file_path', string(radar_file_path), ...
    'manifest_path', string(session_artifact.manifest_path), ...
    'echo_generation_model', string(part_synthesis_summary.echo_generation_model), ...
    'seed_echo_source_mode', string(part_synthesis_summary.seed_echo_source_mode), ...
    'target_echo_dataset_mode', string(target_echo_dataset_mode.mode_id), ...
    'target_echo_dataset_label', string(target_echo_dataset_mode.label), ...
    'integrity', integrity, ...
    'validation_config', validation_config, ...
    'seed_preservation', seed_preservation_summary, ...
    'direct_path', direct_path_summary, ...
    'advisory_precheck', precheck_summary, ...
    'rdm', struct( ...
        'before_db', rdm_before_db, ...
        'range_axis_m', range_axis_m, ...
        'doppler_axis_hz', doppler_axis_hz, ...
        'dwell_start_s', double(part_start_offset_s), ...
        'dwell_duration_s', double(validation_dwell_s)), ...
    'target_summaries', {target_summaries(:).'}, ...
    'spot_check_query_time_s', double(spot_check_query_time_s), ...
    'spot_check_targets', {spot_check_targets(:).'}, ...
    'spot_check_table', spot_check_table, ...
    'readiness', readiness_summary, ...
    'assumptions', struct( ...
        'direct_path_fractional_comparison', ...
            'Measured lag is compared against the configured fractional direct-path delay using parabolic interpolation.', ...
        'precheck_policy', ...
            'Pilot/coherence outputs from runDirectPathPrecheck contribute to seed-preservation evidence but are not the only gate.', ...
        'target_observation_policy', ...
            'Target placement and strength-ordering checks use the raw pre-ECA-C read-back RDM, not a clutter-mitigated detector product.', ...
        'spot_check_metric', ...
            'LocalProminenceDB in the midpoint-CPI spot-check table is a raw local-gate prominence metric for read-back consistency, not calibrated RF receive-power SNR.'), ...
    'figure_handles', figure_handles);

localPrintValidationSummary(validation_summary);
end

function localValidateArtifact(session_artifact)
required_fields = { ...
    'scenario_config', ...
    'session_id', ...
    'session_folder', ...
    'manifest_path', ...
    'radar_files', ...
    'truth_bundle'};

for idx = 1 : numel(required_fields)
    if ~isfield(session_artifact, required_fields{idx})
        error('helperSyntheticValidateGeneratedIQ:missingArtifactField', ...
            'The artifact struct is missing required field "%s".', required_fields{idx});
    end
end
end

function radar_file_path = localResolveRadarFilePath(session_artifact, part_index)
radar_rel_path = char(string(session_artifact.radar_files{part_index}));
radar_file_path = fullfile(session_artifact.session_folder, strrep(radar_rel_path, '/', filesep));
if exist(radar_file_path, 'file') ~= 2
    error('helperSyntheticValidateGeneratedIQ:missingRadarFile', ...
        'Radar file not found for validation: %s', radar_file_path);
end
end

function part_start_offset_s = localResolvePartStartOffset(session_artifact, part_index)
part_start_offset_s = 0;
if isfield(session_artifact, 'part_start_offsets_s') && ...
        numel(session_artifact.part_start_offsets_s) >= part_index
    part_start_offset_s = double(session_artifact.part_start_offsets_s(part_index));
end
end

function part_synthesis_summary = localResolvePartSynthesisSummary(session_artifact, part_index)
part_synthesis_summary = struct( ...
    'part_idx', double(part_index), ...
    'part_start_offset_s', NaN, ...
    'signal_mode', '', ...
    'seed_echo_source_mode', '', ...
    'track_summaries', {repmat(struct( ...
        'hex', '', ...
        'callsign', '', ...
        'echo_gain_db', NaN, ...
        'valid_samples', 0, ...
        'delay_samples_range', [NaN, NaN], ...
        'doppler_hz_range', [NaN, NaN]), 1, 0)});

if isfield(session_artifact, 'part_synthesis_summaries') && ...
        numel(session_artifact.part_synthesis_summaries) >= part_index && ...
        ~isempty(session_artifact.part_synthesis_summaries{part_index})
    part_synthesis_summary = session_artifact.part_synthesis_summaries{part_index};
end
end

function seed_echo_source_mode = localResolvePartSeedEchoSourceMode(part_synthesis_summary, scenario_config)
seed_echo_source_mode = "";
if isfield(part_synthesis_summary, 'seed_echo_source_mode') && ...
        strlength(string(part_synthesis_summary.seed_echo_source_mode)) > 0
    seed_echo_source_mode = string(part_synthesis_summary.seed_echo_source_mode);
elseif isfield(scenario_config, 'seed_echo_source_mode') && ...
        strlength(string(scenario_config.seed_echo_source_mode)) > 0
    seed_echo_source_mode = string(scenario_config.seed_echo_source_mode);
end
end

function integrity = localValidateBasebandIntegrity(radar_file_path, scenario_config, manifest)
reader = comm.BasebandFileReader(radar_file_path, 'SamplesPerFrame', 65536);
cleanup_reader = onCleanup(@() release(reader));
header_info = info(reader);
metadata = reader.Metadata;

sample_rate_hz = double(reader.SampleRate);
center_frequency_hz = double(reader.CenterFrequency);
lo_offset_hz = localMetadataScalar(metadata, 'LOOffset', NaN);
part_duration_header_s = localMetadataScalar(metadata, 'Duration_s', NaN);
recording_utc = localMetadataScalar(metadata, 'RecordingUTC', NaN);
samples_in_file = double(header_info.NumSamplesInData);

channel_count_observed = NaN;
total_samples_counted = 0;
all_finite = true;
nonzero_channels = false(1, 2);
sum_abs_sq = zeros(1, 2);
peak_abs = zeros(1, 2);
sum_diff_sq = 0;

while total_samples_counted < samples_in_file
    frame = reader();
    if isempty(frame)
        break
    end

    samples_remaining = samples_in_file - total_samples_counted;
    frame = frame(1:min(size(frame, 1), samples_remaining), :);
    frame = double(frame);
    frame_rows = size(frame, 1);
    frame_channels = size(frame, 2);
    total_samples_counted = total_samples_counted + frame_rows;

    if isnan(channel_count_observed)
        channel_count_observed = frame_channels;
    end

    all_finite = all_finite && all(isfinite(real(frame(:)))) && all(isfinite(imag(frame(:))));
    n_channels_to_check = min(frame_channels, 2);
    for ch_idx = 1 : n_channels_to_check
        channel_data = frame(:, ch_idx);
        sum_abs_sq(ch_idx) = sum_abs_sq(ch_idx) + sum(abs(channel_data) .^ 2);
        peak_abs(ch_idx) = max(peak_abs(ch_idx), max(abs(channel_data)));
        nonzero_channels(ch_idx) = nonzero_channels(ch_idx) || any(channel_data ~= 0);
    end

    if frame_channels >= 2
        sum_diff_sq = sum_diff_sq + sum(abs(frame(:, 1) - frame(:, 2)) .^ 2);
    end
end

surveillance_rms = sqrt(sum_abs_sq(1) / max(total_samples_counted, 1));
reference_rms = sqrt(sum_abs_sq(2) / max(total_samples_counted, 1));
channel_difference_rms = sqrt(sum_diff_sq / max(total_samples_counted, 1));

duration_from_samples_s = total_samples_counted / max(sample_rate_hz, eps);
duration_tolerance_s = max(1 / max(sample_rate_hz, 1), 1e-9);
sample_rate_pass = abs(sample_rate_hz - double(scenario_config.sample_rate_hz)) <= 1e-9;
center_frequency_pass = abs(center_frequency_hz - double(scenario_config.center_frequency_hz)) <= 1e-6;
lo_offset_pass = abs(lo_offset_hz - double(scenario_config.lo_offset_hz)) <= 1e-9;
duration_header_pass = abs(part_duration_header_s - double(scenario_config.part_duration_s)) <= duration_tolerance_s;
duration_samples_pass = abs(duration_from_samples_s - double(scenario_config.part_duration_s)) <= duration_tolerance_s;
channel_count_pass = (channel_count_observed == 2);
finite_pass = all_finite;
nonzero_pass = all(nonzero_channels);
channels_distinct_pass = channel_difference_rms > (1e-6 * max([surveillance_rms, reference_rms, eps]));

manifest_center_hz = localNestedScalar(manifest, {'sdr_defaults', 'center_frequency_hz'}, NaN);
manifest_sample_rate_hz = localNestedScalar(manifest, {'sdr_defaults', 'sample_rate_hz'}, NaN);
manifest_lo_offset_hz = localNestedScalar(manifest, {'sdr_defaults', 'lo_offset_hz'}, NaN);
manifest_header_center_hz = localNestedScalar(manifest, {'header_readback', 'center_frequency_hz'}, NaN);
manifest_header_sample_rate_hz = localNestedScalar(manifest, {'header_readback', 'sample_rate_hz'}, NaN);
manifest_header_lo_offset_hz = localNestedScalar(manifest, {'header_readback', 'lo_offset_hz'}, NaN);

manifest_match_pass = true;
if isfinite(manifest_center_hz)
    manifest_match_pass = manifest_match_pass && abs(manifest_center_hz - center_frequency_hz) <= 1e-6;
end
if isfinite(manifest_sample_rate_hz)
    manifest_match_pass = manifest_match_pass && abs(manifest_sample_rate_hz - sample_rate_hz) <= 1e-9;
end
if isfinite(manifest_lo_offset_hz)
    manifest_match_pass = manifest_match_pass && abs(manifest_lo_offset_hz - lo_offset_hz) <= 1e-9;
end
if isfinite(manifest_header_center_hz)
    manifest_match_pass = manifest_match_pass && abs(manifest_header_center_hz - center_frequency_hz) <= 1e-6;
end
if isfinite(manifest_header_sample_rate_hz)
    manifest_match_pass = manifest_match_pass && abs(manifest_header_sample_rate_hz - sample_rate_hz) <= 1e-9;
end
if isfinite(manifest_header_lo_offset_hz)
    manifest_match_pass = manifest_match_pass && abs(manifest_header_lo_offset_hz - lo_offset_hz) <= 1e-9;
end

overall_pass = sample_rate_pass && center_frequency_pass && lo_offset_pass && ...
    duration_header_pass && duration_samples_pass && channel_count_pass && ...
    finite_pass && nonzero_pass && channels_distinct_pass && manifest_match_pass;

integrity = struct( ...
    'overall_pass', overall_pass, ...
    'checks', struct( ...
        'sample_rate_pass', sample_rate_pass, ...
        'center_frequency_pass', center_frequency_pass, ...
        'lo_offset_pass', lo_offset_pass, ...
        'duration_header_pass', duration_header_pass, ...
        'duration_samples_pass', duration_samples_pass, ...
        'channel_count_pass', channel_count_pass, ...
        'finite_pass', finite_pass, ...
        'nonzero_pass', nonzero_pass, ...
        'channels_distinct_pass', channels_distinct_pass, ...
        'manifest_match_pass', manifest_match_pass), ...
    'header', struct( ...
        'sample_rate_hz', sample_rate_hz, ...
        'center_frequency_hz', center_frequency_hz, ...
        'lo_offset_hz', lo_offset_hz, ...
        'part_duration_header_s', part_duration_header_s, ...
        'recording_utc', recording_utc, ...
        'samples_in_file', total_samples_counted, ...
        'channel_count', channel_count_observed), ...
    'measured_duration_s', duration_from_samples_s, ...
    'surveillance', struct( ...
        'rms', surveillance_rms, ...
        'peak', peak_abs(1), ...
        'rms_dbfs', 20 * log10(surveillance_rms + eps), ...
        'peak_dbfs', 20 * log10(peak_abs(1) + eps)), ...
    'reference', struct( ...
        'rms', reference_rms, ...
        'peak', peak_abs(2), ...
        'rms_dbfs', 20 * log10(reference_rms + eps), ...
        'peak_dbfs', 20 * log10(peak_abs(2) + eps)), ...
    'channel_difference_rms', channel_difference_rms);
end

function validation_config = localBuildValidationConfig(sample_rate_hz)
% Mirror the current downstream processor dwell settings without calling
% the full pipeline. Keep this helper in sync with analyzeBistaticData.
validation_config = struct( ...
    'sample_rate_hz', double(sample_rate_hz), ...
    'cpi_duration_s', 0.5e-3, ...
    'prf_hz', 1 / 0.5e-3, ...
    'n_slow_cpi', 200, ...
    'max_nci_looks', 2, ...
    'cfar_min_range_m', 5e3, ...
    'validation_dwell_s', 200 * 0.5e-3);
end

function precheck_summary = localRunAdvisoryPrecheck( ...
    radar_file_path, validation_config, part_duration_s, expected_delay_samples, opts)
precheck_slice_s = min(double(part_duration_s), max(validation_config.validation_dwell_s, validation_config.cpi_duration_s));
max_lag_samples = max(500, double(expected_delay_samples) + 64);

try
    precheck_summary = runDirectPathPrecheck( ...
        radar_file_path, ...
        'SliceDurationS', precheck_slice_s, ...
        'CPIDurationS', validation_config.cpi_duration_s, ...
        'MaxLagSamples', max_lag_samples, ...
        'PlotFigures', opts.PrecheckFigures, ...
        'FigureVisibility', char(string(opts.FigureVisibility)), ...
        'Verbose', opts.Verbose);
    precheck_summary.policy_note = 'Pilot/coherence outputs are advisory only in this helper.';
catch ME
    precheck_summary = struct( ...
        'policy_note', 'Pilot/coherence outputs are advisory only in this helper.', ...
        'error_message', ME.message, ...
        'figure_handles', struct('reference', [], 'cross_correlation', [], 'zero_doppler', []));
end
end

function lag_summary = localMeasureFractionalLag( ...
    surveillance_channel, reference_channel, sample_rate_hz, max_lag_samples)
surveillance_channel = double(surveillance_channel(:));
reference_channel = double(reference_channel(:));
n_samples = numel(surveillance_channel);
n_fft = 2 ^ nextpow2(2 * n_samples - 1);

surveillance_channel = surveillance_channel - mean(surveillance_channel);
reference_channel = reference_channel - mean(reference_channel);
surveillance_channel = surveillance_channel ./ max(rms(surveillance_channel), eps);
reference_channel = reference_channel ./ max(rms(reference_channel), eps);

cpsd = fft(surveillance_channel, n_fft) .* conj(fft(reference_channel, n_fft));
xc_full = fftshift(ifft(cpsd ./ max(abs(cpsd), eps)));
lags_full = (-n_fft / 2 : n_fft / 2 - 1).';
lag_mask = abs(lags_full) <= max_lag_samples;
lags = double(lags_full(lag_mask));
xc_mag = abs(xc_full(lag_mask));
[peak_value, peak_idx] = max(xc_mag);

if peak_idx > 1 && peak_idx < numel(xc_mag)
    y_left = xc_mag(peak_idx - 1);
    y_mid = xc_mag(peak_idx);
    y_right = xc_mag(peak_idx + 1);
    curvature = y_left - 2 * y_mid + y_right;
    if abs(curvature) > eps
        fractional_offset = 0.5 * (y_left - y_right) / curvature;
    else
        fractional_offset = 0;
    end
else
    fractional_offset = 0;
end

guard_bins = max(2, round(0.01 * numel(lags)));
secondary_mask = true(size(xc_mag));
secondary_mask(max(1, peak_idx - guard_bins) : min(numel(xc_mag), peak_idx + guard_bins)) = false;
if any(secondary_mask)
    second_value = max(xc_mag(secondary_mask));
else
    second_value = median(xc_mag);
end

peak_lag_samples = lags(peak_idx) + fractional_offset;
peak_to_median_db = 20 * log10(peak_value / max(median(xc_mag), eps));
peak_to_second_db = 20 * log10(peak_value / max(second_value, eps));

lag_summary = struct( ...
    'peak_lag_samples', double(peak_lag_samples), ...
    'peak_lag_us', double(peak_lag_samples / sample_rate_hz * 1e6), ...
    'peak_to_median_db', double(peak_to_median_db), ...
    'peak_to_second_db', double(peak_to_second_db), ...
    'max_lag_samples', double(max_lag_samples));
end

function seed_preservation_summary = localBuildSeedPreservationSummary( ...
    seed_waveform, reference_channel, surveillance_channel, precheck_summary, opts)
correlation_sample_count = min([numel(seed_waveform), numel(reference_channel), numel(surveillance_channel), 65536]);
nfft = 4096;
[seed_psd, freq_hz] = periodogram( ...
    double(seed_waveform(1:correlation_sample_count)), [], nfft, 1, 'centered', 'power');
[reference_psd, ~] = periodogram( ...
    double(reference_channel(1:correlation_sample_count)), [], nfft, 1, 'centered', 'power');
[surveillance_psd, ~] = periodogram( ...
    double(surveillance_channel(1:correlation_sample_count)), [], nfft, 1, 'centered', 'power');

seed_psd_db = 10 * log10(seed_psd + eps);
reference_psd_db = 10 * log10(reference_psd + eps);
surveillance_psd_db = 10 * log10(surveillance_psd + eps);

reference_spectrum_correlation = corr(seed_psd_db, reference_psd_db);
surveillance_spectrum_correlation = corr(seed_psd_db, surveillance_psd_db);
reference_spectrum_pass = reference_spectrum_correlation >= opts.ReferenceSpectrumCorrelationMin;
surveillance_spectrum_pass = surveillance_spectrum_correlation >= opts.SurveillanceSpectrumCorrelationMin;
pilot_pass = isstruct(precheck_summary) && isfield(precheck_summary, 'reference_quality') && ...
    precheck_summary.reference_quality.pass;
lag_peak_pass = isstruct(precheck_summary) && isfield(precheck_summary, 'cross_correlation') && ...
    precheck_summary.cross_correlation.pass;

seed_preservation_summary = struct( ...
    'frequency_axis_normalized_hz', freq_hz, ...
    'reference_spectrum_correlation', double(reference_spectrum_correlation), ...
    'surveillance_spectrum_correlation', double(surveillance_spectrum_correlation), ...
    'reference_spectrum_correlation_min', double(opts.ReferenceSpectrumCorrelationMin), ...
    'surveillance_spectrum_correlation_min', double(opts.SurveillanceSpectrumCorrelationMin), ...
    'reference_spectrum_pass', reference_spectrum_pass, ...
    'surveillance_spectrum_pass', surveillance_spectrum_pass, ...
    'pilot_pass', pilot_pass, ...
    'lag_peak_pass', lag_peak_pass, ...
    'overall_pass', reference_spectrum_pass && surveillance_spectrum_pass && pilot_pass && lag_peak_pass);
end

function strength_ordering_summary = localBuildTargetStrengthOrderingSummary( ...
    target_summaries, truth_bundle, scenario_config)
max_pair_count = max(numel(target_summaries) * (numel(target_summaries) - 1) / 2, 0);
pair_details = repmat(struct( ...
    'target_pair', '', ...
    'expected_stronger_target', '', ...
    'expected_delta_gain_db', NaN, ...
    'observed_delta_power_db', NaN, ...
    'pass', true, ...
    'applicable', false), 1, max_pair_count);
pair_write_idx = 0;

expected_gain_map = localResolveExpectedTargetGainMap( ...
    truth_bundle, ...
    scenario_config);

for idx = 1 : numel(target_summaries)
    for jdx = idx + 1 : numel(target_summaries)
        target_a = target_summaries(idx);
        target_b = target_summaries(jdx);
        if ~target_a.present_in_dwell || ~target_b.present_in_dwell
            continue
        end
        if ~isfinite(target_a.observed_peak_power_db) || ~isfinite(target_b.observed_peak_power_db)
            continue
        end

        if ~isKey(expected_gain_map, target_a.target_id) || ...
                ~isKey(expected_gain_map, target_b.target_id)
            continue
        end

        gain_a_db = expected_gain_map(target_a.target_id);
        gain_b_db = expected_gain_map(target_b.target_id);
        gain_delta_db = gain_a_db - gain_b_db;
        if abs(gain_delta_db) < 3
            continue
        end

        expected_stronger_target = target_a.target_id;
        if gain_delta_db < 0
            expected_stronger_target = target_b.target_id;
        end

        observed_delta_power_db = target_a.observed_peak_power_db - target_b.observed_peak_power_db;
        pass = sign(observed_delta_power_db) == sign(gain_delta_db);
        pair_write_idx = pair_write_idx + 1;
        pair_details(pair_write_idx) = struct( ...
            'target_pair', char(string(target_a.target_id) + " vs " + string(target_b.target_id)), ...
            'expected_stronger_target', expected_stronger_target, ...
            'expected_delta_gain_db', double(abs(gain_delta_db)), ...
            'observed_delta_power_db', double(observed_delta_power_db), ...
            'pass', pass, ...
            'applicable', true);
    end
end

pair_details = pair_details(1:pair_write_idx);

strength_ordering_summary = struct( ...
    'n_qualified_pairs', pair_write_idx, ...
    'pass', all([pair_details.pass]) || isempty(pair_details), ...
    'pair_details', {pair_details});
end

function expected_gain_map = localResolveExpectedTargetGainMap( ...
    truth_bundle, scenario_config)
expected_gain_map = containers.Map('KeyType', 'char', 'ValueType', 'double');

if isfield(truth_bundle, 'track_metadata') && ~isempty(truth_bundle.track_metadata)
    for idx = 1 : numel(truth_bundle.track_metadata)
        track_metadata = truth_bundle.track_metadata(idx);
        if ~isfield(track_metadata, 'target_id') || ...
                strlength(string(track_metadata.target_id)) == 0
            continue
        end
        if ~isfield(track_metadata, 'echo_gain_db') || ...
                ~isfinite(double(track_metadata.echo_gain_db))
            continue
        end

        expected_gain_map(char(string(track_metadata.target_id))) = ...
            double(track_metadata.echo_gain_db);
    end
end

if ~isfield(scenario_config, 'targets') || isempty(scenario_config.targets)
    return
end

for idx = 1 : numel(scenario_config.targets)
    target_def = scenario_config.targets(idx);
    target_id = char(string(target_def.target_id));
    if isKey(expected_gain_map, target_id)
        continue
    end
    if ~isfinite(double(target_def.echo_gain_db))
        continue
    end

    expected_gain_map(target_id) = double(target_def.echo_gain_db);
end
end

function failure_classes = localBuildPartFailureClasses( ...
    seed_preservation_summary, direct_path_summary, target_summaries, ...
    strength_ordering_summary)
failure_classes = strings(0, 1);

if ~seed_preservation_summary.overall_pass
    failure_classes(end + 1, 1) = "seed_preservation_failure";
end
if ~direct_path_summary.pass
    failure_classes(end + 1, 1) = "direct_path_failure";
end
if any(arrayfun(@(target) target.present_in_dwell && ...
        (~isfinite(target.range_residual_bins) || abs(target.range_residual_bins) > 2 || ...
        ~isfinite(target.doppler_residual_bins) || abs(target.doppler_residual_bins) > 2), target_summaries))
    failure_classes(end + 1, 1) = "target_placement_failure";
end
if ~strength_ordering_summary.pass
    failure_classes(end + 1, 1) = "target_strength_ordering_failure";
end

failure_classes = unique(failure_classes, 'stable');
failure_classes = cellstr(failure_classes).';
end

function target_summaries = localBuildTargetValidationSummaries( ...
    truth_bundle, ...
    scenario_config, ...
    projected_aligned_tracks, ...
    part_synthesis_summary, ...
    ~, ...
    range_axis_m, ...
    doppler_axis_hz, ...
    rdm_raw_db, ...
    range_bin_spacing_m, ...
    doppler_bin_spacing_hz, ...
    opts)
truth_targets = truth_bundle.targets;
truth_adsb_tracks = truth_bundle.adsb_tracks;
n_targets = numel(truth_targets);
target_summaries = repmat(struct( ...
    'target_id', '', ...
    'callsign', '', ...
    'hex', '', ...
    'display_label', '', ...
    'present_in_dwell', false, ...
    'predicted_trace_time_s', zeros(0, 1), ...
    'predicted_trace_range_m', zeros(0, 1), ...
    'predicted_trace_doppler_hz', zeros(0, 1), ...
    'predicted_mid_range_m', NaN, ...
    'predicted_mid_doppler_hz', NaN, ...
    'expected_delay_samples_range', [NaN, NaN], ...
    'expected_doppler_hz_range', [NaN, NaN], ...
    'observed_peak_range_m', NaN, ...
    'observed_peak_doppler_hz', NaN, ...
    'observed_peak_power_db', NaN, ...
    'search_window_range_m', [NaN, NaN], ...
    'search_window_doppler_hz', [NaN, NaN], ...
    'range_residual_m', NaN, ...
    'doppler_residual_hz', NaN, ...
    'range_residual_bins', NaN, ...
    'doppler_residual_bins', NaN, ...
    'combined_residual_bins', NaN, ...
    'alignment_label', 'not_in_dwell'), 1, n_targets);

for idx = 1 : n_targets
    truth_target = truth_targets(idx);
    truth_adsb_track = truth_adsb_tracks(idx);
    projected_track = localFindProjectedTrack(projected_aligned_tracks, truth_adsb_track.hex);

    target_summaries(idx).target_id = char(string(truth_target.target_id));
    target_summaries(idx).callsign = char(string(truth_target.callsign));
    target_summaries(idx).hex = char(string(truth_adsb_track.hex));
    target_summaries(idx).display_label = char("Synthetic Truth: " + ...
        string(truth_target.target_id) + " (" + string(truth_target.callsign) + ")");

    if isempty(projected_track)
        continue
    end

    predicted_range_m = double(projected_track.R_excess_m(:));
    predicted_doppler_hz = double(projected_track.f_D_hz(:));
    valid_mask = isfinite(predicted_range_m) & isfinite(predicted_doppler_hz);

    if ~any(valid_mask)
        continue
    end

    predicted_trace_time_s = double(projected_track.t_abs_s(valid_mask));
    predicted_trace_range_m = predicted_range_m(valid_mask);
    predicted_trace_doppler_hz = predicted_doppler_hz(valid_mask);
    predicted_mid_idx = ceil(numel(predicted_trace_time_s) / 2);

    target_summaries(idx).present_in_dwell = true;
    target_summaries(idx).predicted_trace_time_s = predicted_trace_time_s;
    target_summaries(idx).predicted_trace_range_m = predicted_trace_range_m;
    target_summaries(idx).predicted_trace_doppler_hz = predicted_trace_doppler_hz;
    target_summaries(idx).predicted_mid_range_m = predicted_trace_range_m(predicted_mid_idx);
    target_summaries(idx).predicted_mid_doppler_hz = predicted_trace_doppler_hz(predicted_mid_idx);

    synthesis_track_summary = localFindTrackSummary(part_synthesis_summary, truth_adsb_track.hex);
    if ~isempty(synthesis_track_summary)
        target_summaries(idx).expected_delay_samples_range = synthesis_track_summary.delay_samples_range;
        target_summaries(idx).expected_doppler_hz_range = synthesis_track_summary.doppler_hz_range;
    else
        target_summaries(idx).expected_delay_samples_range = localRangeToDelayRange( ...
            predicted_trace_range_m, ...
            double(scenario_config.direct_path_delay_samples), ...
            double(scenario_config.sample_rate_hz));
        target_summaries(idx).expected_doppler_hz_range = [ ...
            min(predicted_trace_doppler_hz), ...
            max(predicted_trace_doppler_hz)];
    end

    search_range_m = [ ...
        min(predicted_trace_range_m) - opts.RangeGateExpansionBins * range_bin_spacing_m, ...
        max(predicted_trace_range_m) + opts.RangeGateExpansionBins * range_bin_spacing_m];
    search_doppler_hz = [ ...
        min(predicted_trace_doppler_hz) - opts.DopplerGateExpansionBins * doppler_bin_spacing_hz, ...
        max(predicted_trace_doppler_hz) + opts.DopplerGateExpansionBins * doppler_bin_spacing_hz];
    target_summaries(idx).search_window_range_m = search_range_m;
    target_summaries(idx).search_window_doppler_hz = search_doppler_hz;

    [observed_peak_range_m, observed_peak_doppler_hz, observed_peak_power_db] = localFindObservedPeak( ...
        rdm_raw_db, ...
        range_axis_m, ...
        doppler_axis_hz, ...
        search_range_m, ...
        search_doppler_hz);

    target_summaries(idx).observed_peak_range_m = observed_peak_range_m;
    target_summaries(idx).observed_peak_doppler_hz = observed_peak_doppler_hz;
    target_summaries(idx).observed_peak_power_db = observed_peak_power_db;

    if ~isfinite(observed_peak_range_m) || ~isfinite(observed_peak_doppler_hz)
        target_summaries(idx).alignment_label = 'no_peak_in_gate';
        continue
    end

    range_residual_trace_m = observed_peak_range_m - predicted_trace_range_m;
    doppler_residual_trace_hz = observed_peak_doppler_hz - predicted_trace_doppler_hz;
    combined_residual_trace_bins = hypot( ...
        range_residual_trace_m ./ max(range_bin_spacing_m, eps), ...
        doppler_residual_trace_hz ./ max(doppler_bin_spacing_hz, eps));

    [min_combined_residual_bins, best_match_idx] = min(combined_residual_trace_bins);
    target_summaries(idx).range_residual_m = range_residual_trace_m(best_match_idx);
    target_summaries(idx).doppler_residual_hz = doppler_residual_trace_hz(best_match_idx);
    target_summaries(idx).range_residual_bins = ...
        target_summaries(idx).range_residual_m / max(range_bin_spacing_m, eps);
    target_summaries(idx).doppler_residual_bins = ...
        target_summaries(idx).doppler_residual_hz / max(doppler_bin_spacing_hz, eps);
    target_summaries(idx).combined_residual_bins = min_combined_residual_bins;
    target_summaries(idx).alignment_label = localDescribeAlignment(min_combined_residual_bins);
end
end

function synthesis_track_summary = localFindTrackSummary(part_synthesis_summary, track_hex)
synthesis_track_summary = [];
if ~isfield(part_synthesis_summary, 'track_summaries') || isempty(part_synthesis_summary.track_summaries)
    return
end

for idx = 1 : numel(part_synthesis_summary.track_summaries)
    candidate = part_synthesis_summary.track_summaries(idx);
    if strcmpi(char(string(candidate.hex)), char(string(track_hex)))
        synthesis_track_summary = candidate;
        return
    end
end
end

function projected_track = localFindProjectedTrack(projected_aligned_tracks, track_hex)
projected_track = [];
for idx = 1 : numel(projected_aligned_tracks)
    candidate = projected_aligned_tracks(idx);
    if strcmpi(char(string(candidate.hex)), char(string(track_hex)))
        projected_track = candidate;
        return
    end
end
end

function delay_range = localRangeToDelayRange(range_trace_m, direct_path_delay_samples, sample_rate_hz)
delay_samples = double(direct_path_delay_samples) + ...
    (double(range_trace_m(:)) ./ physconst('LightSpeed')) .* double(sample_rate_hz);
delay_range = [min(delay_samples), max(delay_samples)];
end

function [observed_peak_range_m, observed_peak_doppler_hz, observed_peak_power_db] = localFindObservedPeak( ...
    rdm_db, range_axis_m, doppler_axis_hz, search_range_m, search_doppler_hz)
observed_peak_range_m = NaN;
observed_peak_doppler_hz = NaN;
observed_peak_power_db = NaN;

range_idx = find(range_axis_m >= search_range_m(1) & range_axis_m <= search_range_m(2));
doppler_idx = find(doppler_axis_hz >= search_doppler_hz(1) & doppler_axis_hz <= search_doppler_hz(2));
if isempty(range_idx) || isempty(doppler_idx)
    return
end

rdm_region_db = rdm_db(range_idx, doppler_idx);
[observed_peak_power_db, linear_idx] = max(rdm_region_db(:));
[range_local_idx, doppler_local_idx] = ind2sub(size(rdm_region_db), linear_idx);
observed_peak_range_m = range_axis_m(range_idx(range_local_idx));
observed_peak_doppler_hz = doppler_axis_hz(doppler_idx(doppler_local_idx));
end

function [local_prominence_db, local_background_level_db, local_background_cell_count] = ...
    localEstimateTargetProminence( ...
    rdm_db, ...
    range_axis_m, ...
    doppler_axis_hz, ...
    search_range_m, ...
    search_doppler_hz, ...
    observed_peak_range_m, ...
    observed_peak_doppler_hz, ...
    observed_peak_power_db)
% This is a local raw CAF prominence metric, not a calibrated RF SNR
% estimate. The target gate is excluded from the background estimate so
% the table reports whether a visible local peak exists near the truth.
local_prominence_db = NaN;
local_background_level_db = NaN;
local_background_cell_count = 0;

if ~isfinite(observed_peak_range_m) || ...
        ~isfinite(observed_peak_doppler_hz) || ...
        ~isfinite(observed_peak_power_db)
    return
end

target_range_idx = find(range_axis_m >= search_range_m(1) & range_axis_m <= search_range_m(2));
target_doppler_idx = find(doppler_axis_hz >= search_doppler_hz(1) & doppler_axis_hz <= search_doppler_hz(2));
if isempty(target_range_idx) || isempty(target_doppler_idx)
    return
end

range_pad_bins = max(8, numel(target_range_idx) + 4);
doppler_pad_bins = max(6, numel(target_doppler_idx) + 4);
background_range_idx = max(1, min(target_range_idx) - range_pad_bins) : ...
    min(numel(range_axis_m), max(target_range_idx) + range_pad_bins);
background_doppler_idx = max(1, min(target_doppler_idx) - doppler_pad_bins) : ...
    min(numel(doppler_axis_hz), max(target_doppler_idx) + doppler_pad_bins);

rdm_mag = 10 .^ (rdm_db(background_range_idx, background_doppler_idx) ./ 20);
background_mask = true(size(rdm_mag));
target_range_local_idx = target_range_idx - background_range_idx(1) + 1;
target_doppler_local_idx = target_doppler_idx - background_doppler_idx(1) + 1;
background_mask(target_range_local_idx, target_doppler_local_idx) = false;

background_cells = rdm_mag(background_mask);
background_cells = background_cells(isfinite(background_cells) & background_cells > 0);
if isempty(background_cells)
    return
end

background_level_mag = median(background_cells, 'omitnan');
if ~(isfinite(background_level_mag) && background_level_mag > 0)
    return
end

peak_level_mag = 10 ^ (double(observed_peak_power_db) / 20);
local_prominence_db = 20 * log10(peak_level_mag / max(background_level_mag, eps));
local_background_level_db = 20 * log10(background_level_mag + eps);
local_background_cell_count = numel(background_cells);
end

function readiness_summary = localBuildReadinessSummary( ...
    target_summaries, validation_config, range_bin_spacing_m, doppler_bin_spacing_hz)
present_mask = arrayfun(@(target) target.present_in_dwell, target_summaries);
present_targets = target_summaries(present_mask);
n_present_targets = numel(present_targets);

target_readiness = repmat(struct( ...
    'target_id', '', ...
    'direct_path_min_range_m', NaN, ...
    'direct_path_min_range_bins', NaN, ...
    'inside_detector_near_range_guard', false), 1, n_present_targets);

for idx = 1 : n_present_targets
    min_range_m = min(present_targets(idx).predicted_trace_range_m);
    target_readiness(idx).target_id = present_targets(idx).target_id;
    target_readiness(idx).direct_path_min_range_m = min_range_m;
    target_readiness(idx).direct_path_min_range_bins = min_range_m / max(range_bin_spacing_m, eps);
    target_readiness(idx).inside_detector_near_range_guard = ...
        min_range_m < validation_config.cfar_min_range_m;
end

pair_separation_count = max(n_present_targets * (n_present_targets - 1) / 2, 0);
pair_separation = repmat(struct( ...
    'target_pair', '', ...
    'minimum_range_separation_bins', NaN, ...
    'minimum_doppler_separation_bins', NaN, ...
    'minimum_combined_separation_bins', NaN), 1, pair_separation_count);
pair_write_idx = 0;

for idx = 1 : n_present_targets
    for jdx = idx + 1 : n_present_targets
        [range_delta_bins, doppler_delta_bins, combined_delta_bins] = localMinimumPairSeparation( ...
            present_targets(idx), ...
            present_targets(jdx), ...
            range_bin_spacing_m, ...
            doppler_bin_spacing_hz);

        pair_write_idx = pair_write_idx + 1;
        pair_separation(pair_write_idx) = struct( ...
            'target_pair', char(string(present_targets(idx).target_id) + " vs " + string(present_targets(jdx).target_id)), ...
            'minimum_range_separation_bins', range_delta_bins, ...
            'minimum_doppler_separation_bins', doppler_delta_bins, ...
            'minimum_combined_separation_bins', combined_delta_bins);
    end
end

readiness_summary = struct( ...
    'range_bin_spacing_m', range_bin_spacing_m, ...
    'doppler_bin_spacing_hz', doppler_bin_spacing_hz, ...
    'target_readiness', {target_readiness(:).'}, ...
    'pair_separation', {pair_separation(:).'});
end

function [spot_check_targets, spot_check_table] = localBuildRawSpotCheckSummary( ...
    truth_bundle, ...
    projected_truth_table, ...
    target_summaries, ...
    spot_check_query_time_s, ...
    rdm_before_db, ...
    range_axis_m, ...
    doppler_axis_hz, ...
    range_bin_spacing_m, ...
    doppler_bin_spacing_hz, ...
    opts)
truth_targets = truth_bundle.targets;
truth_adsb_tracks = truth_bundle.adsb_tracks;
n_targets = numel(truth_targets);
time_tolerance_s = max(eps(max(abs(double(spot_check_query_time_s)), 1)), 1e-12);
selected_indices = zeros(0, 1);

for idx = 1 : n_targets
    if idx > numel(target_summaries) || ~target_summaries(idx).present_in_dwell
        continue
    end

    track_hex = string(truth_adsb_tracks(idx).hex);
    row_mask = projected_truth_table.hex == track_hex & ...
        abs(projected_truth_table.query_time_s - double(spot_check_query_time_s)) <= time_tolerance_s;
    if ~any(row_mask)
        continue
    end

    row_idx = find(row_mask, 1, 'first');
    if ~projected_truth_table.valid(row_idx)
        continue
    end

    selected_indices(end + 1, 1) = idx; %#ok<AGROW>
    if numel(selected_indices) >= 5
        break
    end
end

n_selected = numel(selected_indices);
spot_check_targets = repmat(struct( ...
    'target_id', '', ...
    'callsign', '', ...
    'hex', '', ...
    'display_label', '', ...
    'truth_range_m', NaN, ...
    'truth_doppler_hz', NaN, ...
    'observed_range_m', NaN, ...
    'observed_doppler_hz', NaN, ...
    'range_residual_m', NaN, ...
    'doppler_residual_hz', NaN, ...
    'local_prominence_db', NaN, ...
    'pass_within_gate', false, ...
    'search_window_range_m', [NaN, NaN], ...
    'search_window_doppler_hz', [NaN, NaN]), 1, n_selected);

for write_idx = 1 : n_selected
    target_idx = selected_indices(write_idx);
    truth_target = truth_targets(target_idx);
    truth_adsb_track = truth_adsb_tracks(target_idx);
    row_mask = projected_truth_table.hex == string(truth_adsb_track.hex) & ...
        abs(projected_truth_table.query_time_s - double(spot_check_query_time_s)) <= time_tolerance_s;
    row_idx = find(row_mask, 1, 'first');

    truth_range_m = double(projected_truth_table.R_excess_m(row_idx));
    truth_doppler_hz = double(projected_truth_table.f_D_hz(row_idx));
    search_range_m = truth_range_m + [-1, 1] .* opts.RangeGateExpansionBins * range_bin_spacing_m;
    search_doppler_hz = truth_doppler_hz + [-1, 1] .* opts.DopplerGateExpansionBins * doppler_bin_spacing_hz;

    [observed_range_m, observed_doppler_hz, observed_power_db] = localFindObservedPeak( ...
        rdm_before_db, ...
        range_axis_m, ...
        doppler_axis_hz, ...
        search_range_m, ...
        search_doppler_hz);
    [local_prominence_db, ~, ~] = localEstimateTargetProminence( ...
        rdm_before_db, ...
        range_axis_m, ...
        doppler_axis_hz, ...
        search_range_m, ...
        search_doppler_hz, ...
        observed_range_m, ...
        observed_doppler_hz, ...
        observed_power_db);

    spot_check_targets(write_idx) = struct( ...
        'target_id', char(string(truth_target.target_id)), ...
        'callsign', char(string(truth_target.callsign)), ...
        'hex', char(string(truth_adsb_track.hex)), ...
        'display_label', char("Raw Spot Check: " + ...
            string(truth_target.target_id) + " (" + string(truth_target.callsign) + ")"), ...
        'truth_range_m', truth_range_m, ...
        'truth_doppler_hz', truth_doppler_hz, ...
        'observed_range_m', observed_range_m, ...
        'observed_doppler_hz', observed_doppler_hz, ...
        'range_residual_m', observed_range_m - truth_range_m, ...
        'doppler_residual_hz', observed_doppler_hz - truth_doppler_hz, ...
        'local_prominence_db', local_prominence_db, ...
        'pass_within_gate', isfinite(observed_range_m) && isfinite(observed_doppler_hz), ...
        'search_window_range_m', search_range_m, ...
        'search_window_doppler_hz', search_doppler_hz);
end

spot_check_table = localBuildSpotCheckTable(spot_check_targets);
end

function spot_check_table = localBuildSpotCheckTable(spot_check_targets)
n_targets = numel(spot_check_targets);

target_id = strings(n_targets, 1);
callsign = strings(n_targets, 1);
truth_range_m = NaN(n_targets, 1);
truth_doppler_hz = NaN(n_targets, 1);
observed_range_m = NaN(n_targets, 1);
observed_doppler_hz = NaN(n_targets, 1);
range_residual_m = NaN(n_targets, 1);
doppler_residual_hz = NaN(n_targets, 1);
local_prominence_db = NaN(n_targets, 1);
pass_within_gate = false(n_targets, 1);

for idx = 1 : n_targets
    target = spot_check_targets(idx);
    target_id(idx) = string(target.target_id);
    callsign(idx) = string(target.callsign);
    truth_range_m(idx) = double(target.truth_range_m);
    truth_doppler_hz(idx) = double(target.truth_doppler_hz);
    observed_range_m(idx) = double(target.observed_range_m);
    observed_doppler_hz(idx) = double(target.observed_doppler_hz);
    range_residual_m(idx) = double(target.range_residual_m);
    doppler_residual_hz(idx) = double(target.doppler_residual_hz);
    local_prominence_db(idx) = double(target.local_prominence_db);
    pass_within_gate(idx) = logical(target.pass_within_gate);
end

spot_check_table = table( ...
    target_id, ...
    callsign, ...
    truth_range_m, ...
    truth_doppler_hz, ...
    observed_range_m, ...
    observed_doppler_hz, ...
    range_residual_m, ...
    doppler_residual_hz, ...
    local_prominence_db, ...
    pass_within_gate, ...
    'VariableNames', { ...
        'TargetID', ...
        'Callsign', ...
        'TruthRangeM', ...
        'TruthDopplerHz', ...
        'ObservedRangeM', ...
        'ObservedDopplerHz', ...
        'RangeResidualM', ...
        'DopplerResidualHz', ...
        'LocalProminenceDB', ...
        'PassWithinGate'});
end

function [minimum_range_separation_bins, minimum_doppler_separation_bins, minimum_combined_separation_bins] = ...
    localMinimumPairSeparation(target_a, target_b, range_bin_spacing_m, doppler_bin_spacing_hz)
common_time_s = intersect(target_a.predicted_trace_time_s, target_b.predicted_trace_time_s);
if isempty(common_time_s)
    minimum_range_separation_bins = NaN;
    minimum_doppler_separation_bins = NaN;
    minimum_combined_separation_bins = NaN;
    return
end

range_a_m = interp1(target_a.predicted_trace_time_s, target_a.predicted_trace_range_m, common_time_s, 'linear', NaN);
range_b_m = interp1(target_b.predicted_trace_time_s, target_b.predicted_trace_range_m, common_time_s, 'linear', NaN);
doppler_a_hz = interp1(target_a.predicted_trace_time_s, target_a.predicted_trace_doppler_hz, common_time_s, 'linear', NaN);
doppler_b_hz = interp1(target_b.predicted_trace_time_s, target_b.predicted_trace_doppler_hz, common_time_s, 'linear', NaN);

valid_mask = isfinite(range_a_m) & isfinite(range_b_m) & isfinite(doppler_a_hz) & isfinite(doppler_b_hz);
if ~any(valid_mask)
    minimum_range_separation_bins = NaN;
    minimum_doppler_separation_bins = NaN;
    minimum_combined_separation_bins = NaN;
    return
end

range_delta_bins = abs(range_a_m(valid_mask) - range_b_m(valid_mask)) ./ max(range_bin_spacing_m, eps);
doppler_delta_bins = abs(doppler_a_hz(valid_mask) - doppler_b_hz(valid_mask)) ./ max(doppler_bin_spacing_hz, eps);
combined_delta_bins = hypot(range_delta_bins, doppler_delta_bins);

minimum_range_separation_bins = min(range_delta_bins);
minimum_doppler_separation_bins = min(doppler_delta_bins);
minimum_combined_separation_bins = min(combined_delta_bins);
end

function validation_figure = localPlotValidationFigure( ...
    session_artifact, ...
    part_index, ...
    sample_rate_hz, ...
    surveillance_channel, ...
    reference_channel, ...
    rdm_before_db, ...
    range_axis_m, ...
    doppler_axis_hz, ...
    direct_path_summary, ...
    precheck_summary, ...
    target_summaries, ...
    spot_check_query_time_s, ...
    spot_check_targets, ...
    opts)
figure_title_prefix = sprintf( ...
    'Synthetic IQ Validation | %s part %d', ...
    string(session_artifact.session_id), ...
    part_index);

psd_sample_count = min(numel(surveillance_channel), 65536);
nfft = 4096;
[surveillance_psd, freq_hz] = periodogram( ...
    surveillance_channel(1:psd_sample_count), [], nfft, sample_rate_hz, "centered", "power");
[reference_psd, ~] = periodogram( ...
    reference_channel(1:psd_sample_count), [], nfft, sample_rate_hz, "centered", "power");

validation_figure = figure( ...
    'Name', 'Synthetic IQ Validation - Consolidated Readiness', ...
    'NumberTitle', 'off', ...
    'Visible', opts.FigureVisibility, ...
    'Position', [80, 80, 1480, 920]);
t = tiledlayout(validation_figure, 3, 4, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');
localApplyLiteralTitle(t, sprintf( ...
    '%s\nRaw generated-data validation', ...
    figure_title_prefix));

[display_range_min_km, display_range_max_km] = localResolveDisplayRangeLimitsKm( ...
    target_summaries, ...
    spot_check_targets, ...
    range_axis_m, ...
    opts.MaxDisplayRangeM);

ax_raw = nexttile(t, [2, 2]);
localPlotRawRDMPanel( ...
    ax_raw, ...
    rdm_before_db, ...
    range_axis_m, ...
    doppler_axis_hz, ...
    target_summaries, ...
    display_range_min_km, ...
    display_range_max_km);
localApplyLiteralTitle(ax_raw, sprintf( ...
    '%s\nFirst-chunk raw RDM with synthetic truth overlay\nRange window %.1f to %.1f km', ...
    figure_title_prefix, ...
    display_range_min_km, ...
    display_range_max_km));
ax_raw.Tag = 'raw_rdm';

ax_spot = nexttile(t, [2, 2]);
localPlotRawSpotCheckPanel( ...
    ax_spot, ...
    rdm_before_db, ...
    range_axis_m, ...
    doppler_axis_hz, ...
    spot_check_query_time_s, ...
    spot_check_targets, ...
    display_range_min_km, ...
    display_range_max_km);
localApplyLiteralTitle(ax_spot, sprintf( ...
    '%s\nMidpoint-CPI raw spot check\nQuery time %.6f s', ...
    figure_title_prefix, ...
    spot_check_query_time_s));
ax_spot.Tag = 'raw_spot_check';

ax_spectrum = nexttile(t, [1, 2]);
hold(ax_spectrum, 'on')
plot(ax_spectrum, freq_hz ./ 1e6, 10 * log10(surveillance_psd + eps), ...
    'LineWidth', 1.2, ...
    'DisplayName', 'Surveillance')
plot(ax_spectrum, freq_hz ./ 1e6, 10 * log10(reference_psd + eps), ...
    'LineWidth', 1.2, ...
    'DisplayName', 'Reference')
grid(ax_spectrum, 'on')
xlabel(ax_spectrum, 'Baseband Frequency [MHz]')
ylabel(ax_spectrum, 'PSD [dB]')
localApplyLiteralTitle(ax_spectrum, sprintf( ...
    '%s\nReadback spectrum sanity', ...
    figure_title_prefix));
legend(ax_spectrum, 'Location', 'best')
hold(ax_spectrum, 'off')
ax_spectrum.Tag = 'spectrum';

ax_lag = nexttile(t, [1, 2]);
if isfield(precheck_summary, 'cross_correlation')
    plot(ax_lag, precheck_summary.cross_correlation.lags_us, ...
        precheck_summary.cross_correlation.magnitude_db_rel, ...
        'LineWidth', 1.2)
    hold(ax_lag, 'on')
    measured_lag_us = direct_path_summary.measured_lag_samples_fractional * 1e6 / max(sample_rate_hz, eps);
    expected_lag_us = direct_path_summary.comparison_delay_samples * 1e6 / max(sample_rate_hz, eps);
    xline(ax_lag, measured_lag_us, '--', 'Measured lag')
    xline(ax_lag, expected_lag_us, ':', 'Expected lag')
    hold(ax_lag, 'off')
    grid(ax_lag, 'on')
    xlabel(ax_lag, 'Lag [\mus]')
    ylabel(ax_lag, 'Relative Magnitude [dB]')
    localApplyLiteralTitle(ax_lag, sprintf( ...
        '%s\nLag diagnostic\nMeasured %.3f vs expected %.3f samples', ...
        figure_title_prefix, ...
        direct_path_summary.measured_lag_samples_fractional, ...
        direct_path_summary.comparison_delay_samples));
else
    axis(ax_lag, 'off')
    localApplyLiteralTitle(ax_lag, sprintf( ...
        '%s\nLag diagnostic', ...
        figure_title_prefix));
    text(ax_lag, 0.05, 0.6, 'Advisory direct-path precheck did not return lag data.', ...
        'Units', 'normalized')
    text(ax_lag, 0.05, 0.45, char(string(precheck_summary.policy_note)), 'Units', 'normalized')
end
ax_lag.Tag = 'lag';
end

function localPlotRawRDMPanel( ...
    ax_raw, ...
    rdm_before_db, ...
    range_axis_m, ...
    doppler_axis_hz, ...
    target_summaries, ...
    display_range_min_km, ...
    display_range_max_km)
imagesc(ax_raw, doppler_axis_hz, range_axis_m / 1e3, rdm_before_db)
axis(ax_raw, 'xy')
grid(ax_raw, 'on')
hold(ax_raw, 'on')
localOverlayTargetAnnotations(ax_raw, target_summaries)
hold(ax_raw, 'off')
ylim(ax_raw, [display_range_min_km, display_range_max_km])
xlabel(ax_raw, 'Doppler [Hz]')
ylabel(ax_raw, 'Bistatic Range Excess [km]')
cb_raw = colorbar(ax_raw);
cb_raw.Label.String = localGetRDMColorbarLabel();
if any(arrayfun(@(target) target.present_in_dwell, target_summaries))
    legend(ax_raw, 'Location', 'northeastoutside')
end
end

function localPlotRawSpotCheckPanel( ...
    ax_raw, ...
    rdm_before_db, ...
    range_axis_m, ...
    doppler_axis_hz, ...
    spot_check_query_time_s, ...
    spot_check_targets, ...
    display_range_min_km, ...
    display_range_max_km)
imagesc(ax_raw, doppler_axis_hz, range_axis_m / 1e3, rdm_before_db)
axis(ax_raw, 'xy')
grid(ax_raw, 'on')
hold(ax_raw, 'on')

for idx = 1 : numel(spot_check_targets)
    target = spot_check_targets(idx);

    truth_handle = plot(ax_raw, ...
        target.truth_doppler_hz, ...
        target.truth_range_m / 1e3, ...
        'o', ...
        'LineWidth', 1.4, ...
        'DisplayName', target.display_label);
    truth_handle.MarkerFaceColor = truth_handle.Color;
    text(ax_raw, ...
        target.truth_doppler_hz, ...
        target.truth_range_m / 1e3, ...
        sprintf('  %s truth', target.target_id), ...
        'FontSize', 8, ...
        'Clipping', 'on')

    if isfinite(target.observed_doppler_hz) && isfinite(target.observed_range_m)
        plot(ax_raw, ...
            target.observed_doppler_hz, ...
            target.observed_range_m / 1e3, ...
            'x', ...
            'Color', truth_handle.Color, ...
            'LineWidth', 1.8, ...
            'MarkerSize', 8, ...
            'HandleVisibility', 'off')
        text(ax_raw, ...
            target.observed_doppler_hz, ...
            target.observed_range_m / 1e3, ...
            sprintf('  obs | dR %.0f m | df %.1f Hz', ...
                target.range_residual_m, ...
                target.doppler_residual_hz), ...
            'FontSize', 8, ...
            'Clipping', 'on')
    else
        text(ax_raw, ...
            target.truth_doppler_hz, ...
            target.truth_range_m / 1e3, ...
            '  no peak in gate', ...
            'FontSize', 8, ...
            'Clipping', 'on')
    end
end

if isempty(spot_check_targets)
    text(ax_raw, 0.03, 0.95, ...
        'No eligible retained truth targets had finite midpoint-CPI projections.', ...
        'Units', 'normalized', ...
        'VerticalAlignment', 'top');
end

hold(ax_raw, 'off')
ylim(ax_raw, [display_range_min_km, display_range_max_km])
xlabel(ax_raw, 'Doppler [Hz]')
ylabel(ax_raw, 'Bistatic Range Excess [km]')
cb_raw = colorbar(ax_raw);
cb_raw.Label.String = localGetRDMColorbarLabel();
if ~isempty(spot_check_targets)
    legend(ax_raw, 'Location', 'northeastoutside')
end
text(ax_raw, 0.03, 0.03, sprintf('Query time: %.6f s', spot_check_query_time_s), ...
    'Units', 'normalized', ...
    'VerticalAlignment', 'bottom')
end

function localOverlayTargetAnnotations(ax_handle, target_summaries)
for idx = 1 : numel(target_summaries)
    target = target_summaries(idx);
    if ~target.present_in_dwell
        continue
    end

    trace_handle = plot(ax_handle, ...
        target.predicted_trace_doppler_hz, ...
        target.predicted_trace_range_m ./ 1e3, ...
        '-', ...
        'LineWidth', 1.6, ...
        'DisplayName', target.display_label);
    midpoint_handle = plot(ax_handle, ...
        target.predicted_mid_doppler_hz, ...
        target.predicted_mid_range_m ./ 1e3, ...
        'o', ...
        'HandleVisibility', 'off');
    midpoint_handle.Color = trace_handle.Color;
    midpoint_handle.MarkerFaceColor = trace_handle.Color;
    text(ax_handle, ...
        target.predicted_mid_doppler_hz, ...
        target.predicted_mid_range_m ./ 1e3, ...
        sprintf('  %s', target.target_id), ...
        'FontSize', 8, ...
        'Clipping', 'on')
end
end

function [display_range_min_km, display_range_max_km] = localResolveDisplayRangeLimitsKm( ...
    target_summaries, spot_check_targets, range_axis_m, max_display_range_m)
truth_ranges_m = zeros(0, 1);

for idx = 1 : numel(target_summaries)
    if ~target_summaries(idx).present_in_dwell
        continue
    end

    predicted_trace_range_m = double(target_summaries(idx).predicted_trace_range_m(:));
    predicted_trace_range_m = predicted_trace_range_m(isfinite(predicted_trace_range_m));
    truth_ranges_m = [truth_ranges_m; predicted_trace_range_m]; %#ok<AGROW>
end

if isempty(truth_ranges_m) && ~isempty(spot_check_targets)
    spot_check_truth_range_m = double([spot_check_targets.truth_range_m]);
    spot_check_truth_range_m = spot_check_truth_range_m(isfinite(spot_check_truth_range_m));
    truth_ranges_m = spot_check_truth_range_m(:);
end

if isempty(truth_ranges_m)
    display_range_min_km = min(double(range_axis_m)) / 1e3;
    display_range_max_km = min(max(double(range_axis_m)), double(max_display_range_m)) / 1e3;
else
    display_range_min_km = min(truth_ranges_m) / 1e3 - 10;
    display_range_max_km = max(truth_ranges_m) / 1e3 + 10;
end

if ~(isfinite(display_range_min_km) && isfinite(display_range_max_km))
    display_range_min_km = min(double(range_axis_m)) / 1e3;
    display_range_max_km = min(max(double(range_axis_m)), double(max_display_range_m)) / 1e3;
end

if display_range_max_km <= display_range_min_km
    display_range_max_km = display_range_min_km + 1;
end
end

function rdm_colorbar_label = localGetRDMColorbarLabel()
rdm_colorbar_label = 'CAF Magnitude [dB]';
end

function localApplyLiteralTitle(graphics_target, title_text)
title_handle = title(graphics_target, title_text);
title_handle.Interpreter = 'none';
end

function localPrintValidationSummary(validation_summary)
integrity = validation_summary.integrity;
direct_path = validation_summary.direct_path;
readiness = validation_summary.readiness;
target_summaries = validation_summary.target_summaries;
spot_check_table = validation_summary.spot_check_table;

fprintf('\nSynthetic IQ validation\n');
fprintf('\tSession:\t%s\n', validation_summary.session_id);
fprintf('\tPart index:\t%d\n', validation_summary.part_index);
fprintf('\tFormat readable:\t%s\n', localPassString(integrity.overall_pass));
fprintf('\tHeader Fs / Fc:\t%.3f [MSps]\t%.3f [MHz]\n', ...
    integrity.header.sample_rate_hz / 1e6, ...
    integrity.header.center_frequency_hz / 1e6);
fprintf('\tPart duration:\t%.6f [s] header\t%.6f [s] measured\n', ...
    integrity.header.part_duration_header_s, ...
    integrity.measured_duration_s);
fprintf('\tSurv RMS / Peak:\t%.3f\t%.3f\n', ...
    integrity.surveillance.rms, ...
    integrity.surveillance.peak);
fprintf('\tRef RMS / Peak:\t%.3f\t%.3f\n', ...
    integrity.reference.rms, ...
    integrity.reference.peak);
fprintf('\tSeed preservation:\t%s\tref corr %.3f\tsurv corr %.3f\n', ...
    localPassString(readiness.seed_preservation.overall_pass), ...
    readiness.seed_preservation.reference_spectrum_correlation, ...
    readiness.seed_preservation.surveillance_spectrum_correlation);
fprintf('\tTarget echo dataset:\t%s\n', readiness.target_echo_dataset_label);
fprintf('\tDirect-path lag:\t%.3f [samples] measured\t%.3f [samples] expected\t%.3f [samples] residual\n', ...
    direct_path.measured_lag_samples_fractional, ...
    direct_path.comparison_delay_samples, ...
    direct_path.residual_samples_fractional);
fprintf('\tRange bin spacing:\t%.2f [m]\n', readiness.range_bin_spacing_m);
fprintf('\tDoppler bin spacing:\t%.2f [Hz]\n', readiness.doppler_bin_spacing_hz);
fprintf('\tPilot/coherence note:\t%s\n', validation_summary.assumptions.precheck_policy);
fprintf('\tRaw target observation policy:\t%s\n', validation_summary.assumptions.target_observation_policy);
fprintf('\tRaw spot check:\tt = %.6f [s]\t%d selected target(s)\n', ...
    validation_summary.spot_check_query_time_s, ...
    height(spot_check_table));
fprintf('\tSpot-check metric:\t%s\n', validation_summary.assumptions.spot_check_metric);
fprintf('\tTarget-strength ordering:\t%s\t%d qualified pair(s)\n', ...
    localPassString(readiness.target_strength_ordering.pass), ...
    readiness.target_strength_ordering.n_qualified_pairs);
fprintf('\tPart readiness:\t%s\t%s\n', ...
    localPassString(readiness.overall_pass), ...
    strjoin(string(readiness.failure_classes), ', '));

for idx = 1 : numel(target_summaries)
    target = target_summaries(idx);
    if ~target.present_in_dwell
        fprintf('\t%s:\tnot present in validation dwell\n', target.display_label);
        continue
    end

    fprintf('\t%s:\tR %.3f to %.3f [km]\tfd %.1f to %.1f [Hz]\tobs %.3f [km] / %.1f [Hz]\tres %.0f [m] / %.1f [Hz]\tpeak %.1f [dB]\t%s\n', ...
        target.display_label, ...
        min(target.predicted_trace_range_m) / 1e3, ...
        max(target.predicted_trace_range_m) / 1e3, ...
        min(target.predicted_trace_doppler_hz), ...
        max(target.predicted_trace_doppler_hz), ...
        target.observed_peak_range_m / 1e3, ...
        target.observed_peak_doppler_hz, ...
        target.range_residual_m, ...
        target.doppler_residual_hz, ...
        target.observed_peak_power_db, ...
        target.alignment_label);
    fprintf('\t%s synthesis span:\tdelay %.3f to %.3f [samples]\tfd %.1f to %.1f [Hz]\n', ...
        target.target_id, ...
        target.expected_delay_samples_range(1), ...
        target.expected_delay_samples_range(2), ...
        target.expected_doppler_hz_range(1), ...
        target.expected_doppler_hz_range(2));
end

for idx = 1 : numel(readiness.target_readiness)
    target_ready = readiness.target_readiness(idx);
    fprintf('\t%s direct-path separation:\t%.1f [m]\t%.1f [bins]\tinside 5 km guard = %s\n', ...
        target_ready.target_id, ...
        target_ready.direct_path_min_range_m, ...
        target_ready.direct_path_min_range_bins, ...
        localYesNo(target_ready.inside_detector_near_range_guard));
end

for idx = 1 : numel(readiness.pair_separation)
    pair_ready = readiness.pair_separation(idx);
    fprintf('\t%s separation:\t%.1f [range bins]\t%.1f [Doppler bins]\t%.1f [combined bins]\n', ...
        pair_ready.target_pair, ...
        pair_ready.minimum_range_separation_bins, ...
        pair_ready.minimum_doppler_separation_bins, ...
        pair_ready.minimum_combined_separation_bins);
end
end

function label = localDescribeAlignment(combined_residual_bins)
if ~isfinite(combined_residual_bins)
    label = 'no_peak_in_gate';
elseif combined_residual_bins <= 1
    label = 'tight';
elseif combined_residual_bins <= 2
    label = 'close';
else
    label = 'inspect';
end
end

function value = localAxisSpacing(axis_values)
axis_values = double(axis_values(:));
if numel(axis_values) < 2
    value = NaN;
    return
end
value = mean(diff(axis_values));
end

function value = localMetadataScalar(metadata, field_name, default_value)
value = default_value;
if ~isstruct(metadata) || ~isfield(metadata, field_name)
    return
end

raw_value = metadata.(field_name);
if isempty(raw_value)
    return
end

candidate = double(raw_value);
if isscalar(candidate) && isfinite(candidate)
    value = candidate;
end
end

function value = localNestedScalar(data, field_path, default_value)
value = default_value;
cursor = data;

for idx = 1 : numel(field_path)
    if ~isstruct(cursor) || ~isfield(cursor, field_path{idx})
        return
    end
    cursor = cursor.(field_path{idx});
end

if isempty(cursor)
    return
end

candidate = double(cursor);
if isscalar(candidate) && isfinite(candidate)
    value = candidate;
end
end

function txt = localPassString(tf)
if tf
    txt = 'PASS';
else
    txt = 'WARN';
end
end

function txt = localYesNo(tf)
if tf
    txt = 'yes';
else
    txt = 'no';
end
end
