%[text] # Seed-Backed Synthetic HDTV Session Walkthrough
%[text] This plain-text live script generates one synthetic HDTV packaged session, checks whether the generated IQ matches the requested signal physics, and then shows whether the downstream detector recovers the synthetic targets near truth.
%[text] The goal is to answer explicit validation questions with numbers so the reader does not need to infer readiness from helper printouts or from the legacy track-comparison figure alone.
%%
%[text] ## Questions Answered By This Walkthrough
%[text] Question 1: Did we generate the scenario we intended?
%[text] Question 2: Does the generated IQ preserve the expected seed, direct-path, and target-placement behavior?
%[text] Question 3: Does the downstream detector recover the synthetic targets near the truth trajectories?
%[text] Question 4: What level of validation claim does this run support?
%%
%[text] ## User Controls
%[text] Edit this section and rerun the walkthrough from here when you want a different packaged session or a different validation preset.
sessionID = ""; % If you want to name the new synthetic data yourself
% Synthetic Seed:
%seedSourcePath = "/C:/Users/pwilliam/agenticProjects/flightTest_SynthDataBranch/captures/seed_demo_20260717T133832138/session_manifest.json";
% Real Data Seed:
seedSourcePath = "/C:/Users/pwilliam/agenticProjects/flightTest_SynthDataBranch/captures/20260622T102123/session_manifest.json";
useValidationConfidencePreset = true;
useMotionVisiblePreset = false;
runSignalPhysicsReadinessCheck = true;
runWrapperReplay = true;
%%
%[text] ## Optional Advanced Overrides
%[text] Leave the path strings empty to use the repo-relative defaults.
outputRoot = "";
dtedPath = "";
seedChannelIndex = 2;
signalMode = "seed_backed_bistatic_v1";
truthSourceMode = "auto"; % "auto" uses capture ADS-B truth when the seed resolves to a packaged session with ADS-B
echoGenerationModel = "toolbox_wideband_free_space_v1";
useFullSeedComparisonDataset = false;
runFullSeedComparison = false;
captureDurationS = 0.10;
captureRepetitions = 1;
captureRepetitionSpacingS = 0.0;
tMaxS = []; % [] uses the full capture radar window when capture-backed truth is active
truthSamplePeriodS = 0.02;
referenceGainDB = 0;
directPathGainDB = -3;
directPathDelaySamples = 0.75;
useStochasticNoise = false;
showValidationPrecheckFigures = false;
%%
%[text] ## Collect Inputs
%[text] The walkthrough resolves repo-relative paths, assigns a fresh auto-generated session ID when you leave |sessionID| empty, and keeps the user-control section authoritative on every run.
pathInfo = helperSyntheticEnsureProjectPaths();
repoRoot = pathInfo.repo_root;
if strlength(string(outputRoot)) == 0
    outputRoot = fullfile(repoRoot, "captures");
end
currentSessionID = string(sessionID);
if ~exist("lastAutoGeneratedSessionID", "var")
    previousAutoSessionID = "";
else
    previousAutoSessionID = string(lastAutoGeneratedSessionID);
end
preferredAutoSessionID = "seed_demo_" + string(datetime("now", "Format", "yyyyMMdd'T'HHmmssSSS"));
[sessionID, lastAutoGeneratedSessionID, sessionIDResolutionInfo] = helperSyntheticResolveWalkthroughSessionID( ...
    'OutputRoot', outputRoot, ...
    'SessionID', currentSessionID, ...
    'PreviousAutoSessionID', previousAutoSessionID, ...
    'PreferredAutoSessionID', preferredAutoSessionID);
if sessionIDResolutionInfo.refreshed_previous_auto_session_id
    disp(localBuildKeyValueTable("Session ID note", "Refreshed the prior auto-generated ID to " + string(sessionID) + " so this rerun writes a new capture folder."))
end
if strlength(string(dtedPath)) == 0
    dtedPath = fullfile(repoRoot, "n42_w072_1arc_v3.dt2");
end
if strlength(string(signalMode)) == 0
    signalMode = "seed_backed_bistatic_v1";
end
if strlength(string(echoGenerationModel)) == 0
    echoGenerationModel = "toolbox_wideband_free_space_v1";
end
%%
%[text] ## Optional Validation Confidence Preset
%[text] Question: Do we want a short low-noise scene that is easy to inspect numerically and visually?
%[text] Quantification: This preset lengthens the active window slightly, keeps the scene deterministic, and places the validation targets away from the 5 km near-range guard.
%[text] Interpretation: Use this preset when you want the clearest manual check of target placement and detector recovery.
if useValidationConfidencePreset && useMotionVisiblePreset
    error('seedBackedSyntheticHDTVSessionWalkthrough:conflictingPresets', 'Only one walkthrough preset can be active at a time.')
end
if useValidationConfidencePreset
    captureDurationS = 0.20;
    captureRepetitions = 1;
    captureRepetitionSpacingS = 0.0;
    truthSamplePeriodS = 0.01;
    directPathDelaySamples = 1.00;
    useStochasticNoise = false;
end
%%
%[text] ## Optional Motion-Visible Preset
%[text] Question: Do we want a longer multi-part run so target motion is easier to inspect across time?
%[text] Quantification: This preset stretches the active window to 10 contiguous one-second parts while keeping the same packaged-session workflow.
%[text] Interpretation: Use this preset for multi-part truth and timing checks rather than for the fastest confidence run.
if useMotionVisiblePreset
    captureDurationS = 1.00;
    captureRepetitions = 10;
    captureRepetitionSpacingS = 0.0;
    truthSamplePeriodS = 0.10;
    directPathDelaySamples = 1.00;
    useStochasticNoise = false;
end
%%
%[text] ## Resolve The Illuminator Seed
%[text] Question: What waveform is driving the reference channel, the direct path, and the synthetic target echoes?
%[text] Quantification: The walkthrough resolves either a field seed or a deterministic probe seed and records that source in the scenario and generated manifest.
%[text] Interpretation: This seed choice is important because any strong spectral structure in the seed can reappear in the synthetic echoes.
if strlength(string(seedSourcePath)) == 0 %[output:group:567e24e8]
    probeSeedFolder = fullfile(repoRoot, "tmp_probe");
    probeSeedName = "synthetic_probe_seed_" + sessionID + ".bb";
    [seedSourcePath, seedInfo] = helperSyntheticCreateProbeSeed( ...
        'OutputFolder', probeSeedFolder, ...
        'FileName', probeSeedName);
else
    requestedSeedSourcePath = string(seedSourcePath);
    seedSessionContext = helperSyntheticResolveSessionContext( ...
        seedSourcePath, ...
        'RepoRoot', repoRoot);
    seedSourcePath = char(string(seedSessionContext.source_spec_path));
    seedInfo = helperSyntheticDescribeSeedFixture(seedSourcePath);
    seedInfo.source = 'field_capture';
    if string(seedSourcePath) ~= requestedSeedSourcePath || ...
            seedSessionContext.input_kind ~= "baseband_file"
        disp(localBuildKeyValueTable("Seed source note", ...
            "Resolved " + string(seedSessionContext.input_kind) + ...
            " from " + string(seedSourcePath) + ".")) %[output:244015e5]
    end
end %[output:group:567e24e8]
%%
%[text] ## Build And Confirm The Scenario
%[text] Question: Did we define the intended timing window, dataset mode, and target geometry before writing any IQ?
%[text] Quantification: The scenario summary table and target table below are the exact inputs that drive truth generation, echo synthesis, packaging, and later validation.
%[text] Interpretation: If the scenario summary is wrong here, every later readiness result will be answering the wrong question.
baselineScenarioConfig = buildSyntheticHDTVBaselineScenarioConfig( ... %[output:group:91422633] %[output:2c81ffb1]
    'OutputRoot', outputRoot, ... %[output:2c81ffb1]
    'SessionID', sessionID, ... %[output:2c81ffb1]
    'DTEDPath', dtedPath, ... %[output:2c81ffb1]
    'SeedSourcePath', seedSourcePath, ... %[output:2c81ffb1]
    'SeedChannelIndex', seedChannelIndex, ... %[output:2c81ffb1]
    'SignalMode', signalMode, ... %[output:2c81ffb1]
    'TruthSourceMode', truthSourceMode, ... %[output:2c81ffb1]
    'TruthWindowMaxS', tMaxS, ... %[output:2c81ffb1]
    'ReferenceGainDB', referenceGainDB, ... %[output:2c81ffb1]
    'DirectPathGainDB', directPathGainDB, ... %[output:2c81ffb1]
    'DirectPathDelaySamples', directPathDelaySamples, ... %[output:2c81ffb1]
    'UseStochasticNoise', useStochasticNoise, ... %[output:2c81ffb1]
    'SeedEchoConditioningEnabled', ~logical(useFullSeedComparisonDataset), ... %[output:2c81ffb1]
    'EchoGenerationModel', echoGenerationModel, ... %[output:2c81ffb1]
    'EnableFullSeedComparison', runFullSeedComparison, ... %[output:2c81ffb1]
    'CaptureDurationS', captureDurationS, ... %[output:2c81ffb1]
    'CaptureRepetitions', captureRepetitions, ... %[output:2c81ffb1]
    'CaptureRepetitionSpacingS', captureRepetitionSpacingS, ... %[output:2c81ffb1]
    'TruthSamplePeriodS', truthSamplePeriodS); %[output:group:91422633] %[output:2c81ffb1]
activeWindowS = double(baselineScenarioConfig.expected_overlap_window_s(2));
if useFullSeedComparisonDataset && runFullSeedComparison
    runFullSeedComparison = false;
    disp(localBuildKeyValueTable("Comparison note", "The primary dataset already uses full-seed target echoes, so the extra comparison run is disabled."))
end
captureBackedTruth = strcmp(string(baselineScenarioConfig.truth_source_mode), "capture_adsb_v1");
if ~captureBackedTruth && (~exist("targets", "var") || isempty(targets))
    baselineTargets = baselineScenarioConfig.targets;
    if useValidationConfidencePreset || useMotionVisiblePreset
        targets = helperSyntheticBuildValidationConfidenceTargets( ...
            baselineScenarioConfig.tx_lla_deg_m, ...
            baselineScenarioConfig.rx_lla_deg_m, ...
            activeWindowS);
    else
        targets(1) = struct( ...
            'target_id', baselineTargets(1).target_id, ...
            'icao_hex', baselineTargets(1).icao_hex, ...
            'callsign', baselineTargets(1).callsign, ...
            'echo_gain_db', baselineTargets(1).echo_gain_db, ...
            'waypoints_lla_deg_m', baselineTargets(1).waypoints_lla_deg_m, ...
            'time_of_arrival_s', baselineTargets(1).time_of_arrival_s);
        targets(2) = struct( ...
            'target_id', baselineTargets(2).target_id, ...
            'icao_hex', baselineTargets(2).icao_hex, ...
            'callsign', baselineTargets(2).callsign, ...
            'echo_gain_db', baselineTargets(2).echo_gain_db, ...
            'waypoints_lla_deg_m', baselineTargets(2).waypoints_lla_deg_m, ...
            'time_of_arrival_s', baselineTargets(2).time_of_arrival_s);
    end
end
scenarioConfig = baselineScenarioConfig;
scenarioConfig.full_seed_comparison_enabled = logical(runFullSeedComparison);
scenarioConfig.diagnostic_conditioned_echo_enabled = logical(runFullSeedComparison);
if ~captureBackedTruth
    scenarioConfig.targets = targets;
end
[scenarioSummary, targetSummaryTable] = helperSyntheticSummarizeScenarioConfig(scenarioConfig);
disp(localBuildScenarioOverviewTable( ...
    scenarioSummary, ...
    seedSourcePath, ...
    seedInfo, ...
    dtedPath, ...
    runSignalPhysicsReadinessCheck, ...
    runWrapperReplay, ...
    useValidationConfidencePreset, ...
    useMotionVisiblePreset, ...
    useFullSeedComparisonDataset))
disp(targetSummaryTable)
%%
%[text] ## Preview The Sampled Synthetic Truth
%[text] Question: Before we synthesize IQ, do the sampled target paths and bistatic truth traces look like the scene we intended?
%[text] Quantification: The preview uses the same sampled truth that later drives the synthetic delays and Doppler shifts, so this is the earliest place to catch geometry mistakes.
%[text] Interpretation: If the preview plot is wrong, the downstream radar outputs will also be wrong because the generator reuses this truth verbatim.
truthPreview = helperSyntheticGenerateTruth(scenarioConfig);
previewPlotHandles = helperSyntheticPlotScenarioOverview(scenarioConfig, truthPreview); %#ok<NASGU>
if strcmp(string(scenarioConfig.truth_source_mode), "capture_adsb_v1")
    disp(localBuildCaptureTruthOverviewTable(scenarioConfig, truthPreview))
    disp(truthPreview.selection_table(:, {'ICAOHex', 'Callsign', 'InWindowFixCount', 'AlignedBeyondGuardSampleCount', 'Include', 'Reason'}))
end
%%
%[text] ## Preview The Sampled Synthetic Truth In 3-D
%[text] Question: Do the exact sampled aircraft positions sit where we expect in 3-D relative to the transmitter and receiver?
%[text] Quantification: This globe preview uses trackingGlobeViewer to render the same sampled truth bundle and then captures a stable snapshot figure for the walkthrough output.
%[text] Interpretation: If the 3-D target paths or Tx/Rx context look wrong here, the synthetic delay and Doppler inputs are already wrong before IQ generation starts.
truthGlobePreview = helperSyntheticPlotTruthGlobePreview(scenarioConfig, truthPreview); %#ok<NASGU>
%%
%[text] ## Generate The Synthetic Session
%[text] Question: Did the generator write the packaged radar, truth, and manifest artifacts we need for replay and traceability?
%[text] Quantification: The tables below record the written session folder, manifest, radar parts, and truth files.
%[text] Interpretation: This confirms packaging and gives you the exact artifact paths for any manual inspection or replay outside this walkthrough.
artifact = generateSyntheticHDTVSession('ScenarioConfig', scenarioConfig);
disp(localBuildArtifactOverviewTable(artifact))
disp(table(string(artifact.radar_files(:)), 'VariableNames', {'RadarFile'}))
disp(table(string(artifact.adsb_files(:)), 'VariableNames', {'ADSBFile'}))
validationSummary = struct([]);
analysisOutput = struct([]);
truthDiagOutput = struct([]);
%%
%[text] ## Signal-Physics Readiness
%[text] Question: Does the generated IQ preserve the intended seed spectrum, direct-path lag, and target placement?
%[text] Quantification: The readiness gate reads the written files back, measures seed-preservation correlations, measures the direct-path lag residual, compares predicted and observed target peaks in range and Doppler, and checks for truth-aligned vertical Doppler columns.
%[text] Interpretation: A passing readiness table means the dataset is internally consistent enough for intermediate downstream algorithm testing. A failing table tells you which physical assumption broke.
if runSignalPhysicsReadinessCheck
    validationSummary = helperSyntheticValidateGeneratedIQ( ...
        artifact, ...
        'PlotFigures', true, ...
        'PrecheckFigures', showValidationPrecheckFigures, ...
        'FigureVisibility', 'on', ...
        'RunEchoModelComparison', runFullSeedComparison, ...
        'Verbose', false);
    disp(localBuildReadinessOverviewTable(validationSummary))
    disp(localBuildReadinessPartTable(validationSummary))
    disp(localBuildReadinessTargetTable(validationSummary))
else
    disp(localBuildKeyValueTable("Signal-physics readiness", "Skipped because runSignalPhysicsReadinessCheck = false."))
end
%%
%[text] ## Existing Wrapper Replay
%[text] Question: Can the current packaged-session workflow ingest the generated data without changing the downstream pipeline?
%[text] Quantification: The walkthrough replays the packaged session through |runBistaticAnalysisSession| with figures hidden, then reruns only the fast truth-diagnostic stage with the modern detection-vs-truth figure enabled and the legacy track-comparison figure disabled.
%[text] Interpretation: This answers compatibility first, then detector usefulness, without leaning on the older figure that can be visually confusing when track history is sparse.
if runWrapperReplay
    originalVisibility = get(groot, "DefaultFigureVisible");
    set(groot, "DefaultFigureVisible", "off")
    cleanupVisibility = onCleanup(@() set(groot, "DefaultFigureVisible", originalVisibility));
    analysisOutput = runBistaticAnalysisSession( ...
        scenarioConfig.session_id, ...
        'DatasetRoot', scenarioConfig.output_root, ...
        'Verbose', false, ...
        'Use2DGeographicFallback', true, ...
        'SaveTruthDiagnosticSnapshot', false, ...
        'SaveDetectorReplaySnapshot', false, ...
        'PlotLegacyTruthComparison', false, ...
        'PlotDetectionTruthFigure', false);
    clear cleanupVisibility
    disp(localBuildWrapperOverviewTable(analysisOutput))
    if isfield(analysisOutput, 'truth_diag_input') && ~isempty(analysisOutput.truth_diag_input)
        truthDiagOutput = runDetectionTruthDiagnostics( ...
            analysisOutput.truth_diag_input, ...
            'FigureTitle', "Walkthrough " + string(analysisOutput.session_id), ...
            'PlotDetectionTimeSeries', true, ...
            'PlotRDMOverlays', false, ...
            'PlotTrackComparison', false, ...
            'Verbose', false);
        disp(localBuildTruthOverviewTable(truthDiagOutput))
        truthPerPartTable = localBuildTruthPerPartTable(truthDiagOutput);
        if ~isempty(truthPerPartTable)
            disp(truthPerPartTable)
        end
        disp(localBuildDetectionErrorTable(truthDiagOutput.truth_metrics))
        if isfield(truthDiagOutput, 'truth_metrics') && isfield(truthDiagOutput.truth_metrics, 'Pd_per_ac') && ~isempty(truthDiagOutput.truth_metrics.Pd_per_ac)
            pdTable = truthDiagOutput.truth_metrics.Pd_per_ac(:, {'hex', 'callsign', 'n_tp', 'n_hit_cpis', 'n_miss', 'Pd'});
            pdTable.Pd = localRoundFinite(pdTable.Pd, 3);
            disp(pdTable)
        end
        if isfield(truthDiagOutput, 'truth_metrics') && isfield(truthDiagOutput.truth_metrics, 'trk_table') && ~isempty(truthDiagOutput.truth_metrics.trk_table)
            trkTable = truthDiagOutput.truth_metrics.trk_table(:, {'track_id', 'assoc_callsign', 'range_bias_m', 'range_rmse_m', 'doppler_bias_hz', 'doppler_rmse_hz', 'n_pts'});
            trkTable.range_bias_m = localRoundFinite(trkTable.range_bias_m, 1);
            trkTable.range_rmse_m = localRoundFinite(trkTable.range_rmse_m, 1);
            trkTable.doppler_bias_hz = localRoundFinite(trkTable.doppler_bias_hz, 2);
            trkTable.doppler_rmse_hz = localRoundFinite(trkTable.doppler_rmse_hz, 2);
            disp(trkTable)
        end
    else
        disp(localBuildKeyValueTable("Truth-diagnostic bundle", "runBistaticAnalysisSession completed, but no truth_diag_input bundle was returned."))
    end
else
    disp(localBuildKeyValueTable("Wrapper replay", "Skipped because runWrapperReplay = false."))
end
%%
%[text] ## What The Numbers Mean
%[text] Question: Is this synthetic dataset useful for downstream validation, and what claim level does that support?
%[text] Quantification: The summary below combines the signal-physics readiness decision with the downstream truth-match counts and error statistics.
%[text] Interpretation: Treat a readiness pass plus truth-matched detections as evidence that the dataset is useful for intermediate workflow validation. Treat persistent vertical-column failures or missing true positives as a debugging signal rather than as a final benchmark result.
disp(localBuildValidationInterpretationTable(validationSummary, truthDiagOutput, runSignalPhysicsReadinessCheck, runWrapperReplay))
%%
%[text] ## Explain The Pipeline To Someone Else
%[text] Step 1: Start with a real or probe HDTV seed waveform so the reference channel has realistic broadcast structure.
%[text] Step 2: Copy that seed into the surveillance channel as the direct-path signal, then add synthetic target echoes whose delay, Doppler, and gain come from sampled truth trajectories.
%[text] Step 3: Package the generated radar files, truth files, and manifest exactly like a normal capture session so the existing downstream workflow can read them unchanged.
%[text] Step 4: Run the readiness gate to check whether the generated IQ landed where the scenario predicted in range and Doppler and whether the seeded waveform preserved the expected signal structure.
%[text] Step 5: Run the existing detector and compare detections to truth in measurement space so you can decide whether the dataset is useful for intermediate validation.
%[text] The range-error and Doppler-error summaries are the numbers behind the bottom histograms from the legacy figure: mean near zero indicates low bias, and sigma or RMS tells you how tightly the true-positive detections cluster around truth.
%[text] The legacy top track-comparison axis is intentionally not the main figure in this walkthrough because the modern detection-vs-truth figure answers the validation question more directly and avoids the empty-axis confusion that can happen when no track history is plotted there.
function tableOut = localBuildScenarioOverviewTable(scenarioSummary, seedSourcePath, seedInfo, dtedPath, runSignalPhysicsReadinessCheck, runWrapperReplay, useValidationConfidencePreset, useMotionVisiblePreset, useFullSeedComparisonDataset)
presetLabel = "Default smoke test";
if useValidationConfidencePreset
    presetLabel = "Validation confidence preset";
elseif useMotionVisiblePreset
    presetLabel = "Motion-visible preset";
elseif useFullSeedComparisonDataset
    presetLabel = "Full-seed comparison dataset";
end
seedSourceLabel = "unknown";
if isstruct(seedInfo) && isfield(seedInfo, 'source')
    seedSourceLabel = string(seedInfo.source);
end
labels = [ ...
    "Session ID"; ...
    "Preset"; ...
    "Truth source"; ...
    "Signal mode"; ...
    "Echo model"; ...
    "Target echo dataset"; ...
    "Target echo source"; ...
    "Recommended intermediate mode"; ...
    "Readiness gate enabled"; ...
    "Wrapper replay enabled"; ...
    "Sample rate"; ...
    "Center frequency"; ...
    "Part duration"; ...
    "Capture repetitions"; ...
    "Repetition spacing"; ...
    "Active window"; ...
    "Selected truth window"; ...
    "Truth sample period"; ...
    "Target count"; ...
    "Seed file"; ...
    "Seed source"; ...
    "Capture manifest"; ...
    "DTED path"];
values = [ ...
    string(scenarioSummary.session_id); ...
    presetLabel; ...
    string(scenarioSummary.truth_source_mode); ...
    string(scenarioSummary.signal_mode); ...
    string(scenarioSummary.echo_generation_model); ...
    string(scenarioSummary.target_echo_dataset_label); ...
    string(scenarioSummary.seed_echo_source_mode); ...
    localFormatYesNo(scenarioSummary.recommended_intermediate_algorithm_test_mode); ...
    localFormatYesNo(runSignalPhysicsReadinessCheck); ...
    localFormatYesNo(runWrapperReplay); ...
    compose("%.3f [MSps]", scenarioSummary.sample_rate_hz / 1e6); ...
    compose("%.3f [MHz]", scenarioSummary.center_frequency_hz / 1e6); ...
    compose("%.3f [s]", scenarioSummary.part_duration_s); ...
    compose("%d", scenarioSummary.capture_repetitions); ...
    compose("%.3f [s]", scenarioSummary.capture_repetition_spacing_s); ...
    compose("%.3f [s]", scenarioSummary.radar_active_window_s); ...
    compose("%.3f [s]", scenarioSummary.selected_truth_window_s); ...
    compose("%.3f [s]", scenarioSummary.truth_sample_period_s); ...
    compose("%d", scenarioSummary.n_targets); ...
    string(seedSourcePath); ...
    seedSourceLabel; ...
    string(scenarioSummary.capture_manifest_path); ...
    string(dtedPath)];
tableOut = localBuildKeyValueTable(labels, values);
end
function tableOut = localBuildCaptureTruthOverviewTable(scenarioConfig, truthPreview)
labels = [ ...
    "Capture radar window"; ...
    "Selected simulation window"; ...
    "ADS-B aircraft loaded"; ...
    "ADS-B aircraft retained"; ...
    "Truth filter mode"; ...
    "Echo gain policy"];
values = [ ...
    compose("%.3f [s]", scenarioConfig.source_capture_active_window_s); ...
    compose("%.3f [s]", truthPreview.selected_truth_window_s); ...
    compose("%d", truthPreview.loaded_aircraft_count); ...
    compose("%d", truthPreview.retained_aircraft_count); ...
    string(scenarioConfig.truth_filter_mode); ...
    string(scenarioConfig.capture_echo_gain_policy)];
tableOut = localBuildKeyValueTable(labels, values);
end
function tableOut = localBuildArtifactOverviewTable(artifact)
labels = [ ...
    "Session folder"; ...
    "Manifest path"; ...
    "Radar file count"; ...
    "ADSB file count"];
values = [ ...
    string(artifact.session_folder); ...
    string(artifact.manifest_path); ...
    compose("%d", numel(artifact.radar_files)); ...
    compose("%d", numel(artifact.adsb_files))];
tableOut = localBuildKeyValueTable(labels, values);
end
function tableOut = localBuildReadinessOverviewTable(validationSummary)
if isempty(validationSummary) || ~isfield(validationSummary, 'readiness')
    tableOut = localBuildKeyValueTable("Signal-physics readiness", "Not run.");
    return
end
readiness = validationSummary.readiness;
labels = [ ...
    "Overall readiness"; ...
    "Failure classes"; ...
    "Parts validated"; ...
    "Parts passed"; ...
    "Packaging integrity"; ...
    "Seed preservation"; ...
    "Direct-path gate"; ...
    "Median direct-path residual"; ...
    "Worst direct-path residual"; ...
    "Target placement"; ...
    "Strength ordering"; ...
    "Qualified strength-ordering pairs"; ...
    "Vertical columns clear"; ...
    "Target echo dataset"; ...
    "Recommended intermediate mode"];
values = [ ...
    localFormatPassFail(readiness.overall_pass); ...
    localJoinStringArray(readiness.failure_classes); ...
    compose("%d", readiness.n_parts_validated); ...
    compose("%d", readiness.n_parts_passed); ...
    localFormatPassFail(readiness.packaging_integrity_pass); ...
    localFormatPassFail(readiness.seed_preservation.overall_pass); ...
    localFormatPassFail(readiness.direct_path.overall_pass); ...
    compose("%.3f [samples]", readiness.direct_path.median_abs_residual_samples); ...
    compose("%.3f [samples]", readiness.direct_path.worst_abs_residual_samples); ...
    localFormatPassFail(readiness.target_placement_pass); ...
    localFormatPassFail(readiness.target_strength_ordering.overall_pass); ...
    compose("%d", readiness.target_strength_ordering.n_qualified_pairs); ...
    localFormatPassFail(readiness.vertical_column.overall_pass); ...
    string(readiness.target_echo_dataset_label); ...
    localFormatYesNo(readiness.recommended_intermediate_algorithm_test_mode)];
tableOut = localBuildKeyValueTable(labels, values);
end
function tableOut = localBuildReadinessPartTable(validationSummary)
tableOut = table();
if isempty(validationSummary) || ~isfield(validationSummary, 'per_part') || isempty(validationSummary.per_part)
    return
end
partResults = validationSummary.per_part;
nParts = numel(partResults);
partIndex = zeros(nParts, 1);
overallReadiness = strings(nParts, 1);
failureClasses = strings(nParts, 1);
seedPreservation = strings(nParts, 1);
referenceSpectrumCorr = NaN(nParts, 1);
surveillanceSpectrumCorr = NaN(nParts, 1);
directPathResidualSamples = NaN(nParts, 1);
medianProminenceDB = NaN(nParts, 1);
verticalColumnsClear = strings(nParts, 1);
for idx = 1 : nParts
    partResult = partResults(idx);
    partIndex(idx) = partResult.part_index;
    overallReadiness(idx) = localFormatPassFail(partResult.readiness.overall_pass);
    failureClasses(idx) = localJoinStringArray(partResult.readiness.failure_classes);
    seedPreservation(idx) = localFormatPassFail(partResult.seed_preservation.overall_pass);
    referenceSpectrumCorr(idx) = partResult.seed_preservation.reference_spectrum_correlation;
    surveillanceSpectrumCorr(idx) = partResult.seed_preservation.surveillance_spectrum_correlation;
    directPathResidualSamples(idx) = partResult.direct_path.residual_samples_fractional;
    medianProminenceDB(idx) = partResult.target_prominence_summary.median_prominence_db;
    verticalColumnsClear(idx) = localFormatPassFail(partResult.doppler_column_advisory.all_targets_clear);
end
referenceSpectrumCorr = localRoundFinite(referenceSpectrumCorr, 3);
surveillanceSpectrumCorr = localRoundFinite(surveillanceSpectrumCorr, 3);
directPathResidualSamples = localRoundFinite(directPathResidualSamples, 3);
medianProminenceDB = localRoundFinite(medianProminenceDB, 1);
tableOut = table( ...
    partIndex, ...
    overallReadiness, ...
    failureClasses, ...
    seedPreservation, ...
    referenceSpectrumCorr, ...
    surveillanceSpectrumCorr, ...
    directPathResidualSamples, ...
    medianProminenceDB, ...
    verticalColumnsClear, ...
    'VariableNames', { ...
        'PartIndex', ...
        'OverallReadiness', ...
        'FailureClasses', ...
        'SeedPreservation', ...
        'ReferenceSpectrumCorr', ...
        'SurveillanceSpectrumCorr', ...
        'DirectPathResidualSamples', ...
        'MedianProminenceDB', ...
        'VerticalColumnsClear'});
end
function tableOut = localBuildReadinessTargetTable(validationSummary)
tableOut = table();
if isempty(validationSummary) || ~isfield(validationSummary, 'target_summaries') || isempty(validationSummary.target_summaries)
    return
end
targetSummaries = validationSummary.target_summaries;
nTargets = numel(targetSummaries);
targetID = strings(nTargets, 1);
callsign = strings(nTargets, 1);
presentInDisplayedPart = strings(nTargets, 1);
predictedMidRangeKm = NaN(nTargets, 1);
observedPeakRangeKm = NaN(nTargets, 1);
rangeResidualM = NaN(nTargets, 1);
medianAbsRangeResidualBins = NaN(nTargets, 1);
worstAbsRangeResidualBins = NaN(nTargets, 1);
predictedMidDopplerHz = NaN(nTargets, 1);
observedPeakDopplerHz = NaN(nTargets, 1);
dopplerResidualHz = NaN(nTargets, 1);
medianAbsDopplerResidualBins = NaN(nTargets, 1);
worstAbsDopplerResidualBins = NaN(nTargets, 1);
localProminenceDB = NaN(nTargets, 1);
directPathMinRangeKm = NaN(nTargets, 1);
insideNearRangeGuard = repmat("not assessed", nTargets, 1);
verticalColumnClear = repmat("not assessed", nTargets, 1);
alignment = strings(nTargets, 1);
sessionPlacementPass = repmat("not assessed", nTargets, 1);
for idx = 1 : nTargets
    target = targetSummaries(idx);
    targetID(idx) = string(target.target_id);
    callsign(idx) = string(target.callsign);
    presentInDisplayedPart(idx) = localFormatYesNo(target.present_in_dwell);
    alignment(idx) = string(target.alignment_label);
    if target.present_in_dwell
        predictedMidRangeKm(idx) = target.predicted_mid_range_m / 1e3;
        observedPeakRangeKm(idx) = target.observed_peak_range_m / 1e3;
        rangeResidualM(idx) = target.range_residual_m;
        predictedMidDopplerHz(idx) = target.predicted_mid_doppler_hz;
        observedPeakDopplerHz(idx) = target.observed_peak_doppler_hz;
        dopplerResidualHz(idx) = target.doppler_residual_hz;
        localProminenceDB(idx) = target.local_prominence_db;
    end
    if isfield(validationSummary, 'readiness') && isfield(validationSummary.readiness, 'per_target')
        sessionTarget = localFindByTargetId(validationSummary.readiness.per_target, target.target_id);
        if ~isempty(sessionTarget)
            medianAbsRangeResidualBins(idx) = sessionTarget.median_abs_range_residual_bins;
            worstAbsRangeResidualBins(idx) = sessionTarget.worst_abs_range_residual_bins;
            medianAbsDopplerResidualBins(idx) = sessionTarget.median_abs_doppler_residual_bins;
            worstAbsDopplerResidualBins(idx) = sessionTarget.worst_abs_doppler_residual_bins;
            sessionPlacementPass(idx) = localFormatPassFail(sessionTarget.pass);
        end
    end
    if isfield(validationSummary, 'primary_part') && isfield(validationSummary.primary_part, 'readiness') && isfield(validationSummary.primary_part.readiness, 'target_readiness')
        targetReady = localFindByTargetId(validationSummary.primary_part.readiness.target_readiness, target.target_id);
        if ~isempty(targetReady)
            directPathMinRangeKm(idx) = targetReady.direct_path_min_range_m / 1e3;
            insideNearRangeGuard(idx) = localFormatYesNo(targetReady.inside_detector_near_range_guard);
        end
    end
    if isfield(validationSummary, 'doppler_column_advisory') && isfield(validationSummary.doppler_column_advisory, 'per_target')
        targetColumn = localFindByTargetId(validationSummary.doppler_column_advisory.per_target, target.target_id);
        if ~isempty(targetColumn) && targetColumn.present_in_dwell
            verticalColumnClear(idx) = localFormatYesNo(~targetColumn.flagged);
        end
    end
end
predictedMidRangeKm = localRoundFinite(predictedMidRangeKm, 3);
observedPeakRangeKm = localRoundFinite(observedPeakRangeKm, 3);
rangeResidualM = localRoundFinite(rangeResidualM, 1);
medianAbsRangeResidualBins = localRoundFinite(medianAbsRangeResidualBins, 2);
worstAbsRangeResidualBins = localRoundFinite(worstAbsRangeResidualBins, 2);
predictedMidDopplerHz = localRoundFinite(predictedMidDopplerHz, 1);
observedPeakDopplerHz = localRoundFinite(observedPeakDopplerHz, 1);
dopplerResidualHz = localRoundFinite(dopplerResidualHz, 1);
medianAbsDopplerResidualBins = localRoundFinite(medianAbsDopplerResidualBins, 2);
worstAbsDopplerResidualBins = localRoundFinite(worstAbsDopplerResidualBins, 2);
localProminenceDB = localRoundFinite(localProminenceDB, 1);
directPathMinRangeKm = localRoundFinite(directPathMinRangeKm, 3);
tableOut = table( ...
    targetID, ...
    callsign, ...
    presentInDisplayedPart, ...
    predictedMidRangeKm, ...
    observedPeakRangeKm, ...
    rangeResidualM, ...
    medianAbsRangeResidualBins, ...
    worstAbsRangeResidualBins, ...
    predictedMidDopplerHz, ...
    observedPeakDopplerHz, ...
    dopplerResidualHz, ...
    medianAbsDopplerResidualBins, ...
    worstAbsDopplerResidualBins, ...
    localProminenceDB, ...
    directPathMinRangeKm, ...
    insideNearRangeGuard, ...
    verticalColumnClear, ...
    alignment, ...
    sessionPlacementPass, ...
    'VariableNames', { ...
        'TargetID', ...
        'Callsign', ...
        'PresentInDisplayedPart', ...
        'PredictedMidRangeKm', ...
        'ObservedPeakRangeKm', ...
        'RangeResidualM', ...
        'MedianAbsRangeResidualBins', ...
        'WorstAbsRangeResidualBins', ...
        'PredictedMidDopplerHz', ...
        'ObservedPeakDopplerHz', ...
        'DopplerResidualHz', ...
        'MedianAbsDopplerResidualBins', ...
        'WorstAbsDopplerResidualBins', ...
        'LocalProminenceDB', ...
        'DirectPathMinRangeKm', ...
        'InsideNearRangeGuard', ...
        'VerticalColumnClear', ...
        'Alignment', ...
        'SessionPlacementPass'});
end
function tableOut = localBuildWrapperOverviewTable(analysisOutput)
if isempty(analysisOutput)
    tableOut = localBuildKeyValueTable("Wrapper replay", "Not run.");
    return
end
labels = [ ...
    "Session ID"; ...
    "Radar file count"; ...
    "Truth file count"; ...
    "Aligned truth tracks"; ...
    "2-D geographic fallback"; ...
    "Truth-diagnostic bundle available"];
values = [ ...
    string(analysisOutput.session_id); ...
    compose("%d", numel(analysisOutput.radar_files)); ...
    compose("%d", numel(analysisOutput.adsb_files)); ...
    compose("%d", localCountAlignedTruthTracks(analysisOutput)); ...
    localFormatYesNo(analysisOutput.use_2d_geographic_fallback); ...
    localFormatYesNo(isfield(analysisOutput, 'truth_diag_input') && ~isempty(analysisOutput.truth_diag_input))];
tableOut = localBuildKeyValueTable(labels, values);
end
function tableOut = localBuildTruthOverviewTable(truthDiagOutput)
if ~localHasTruthDiagnostics(truthDiagOutput)
    tableOut = localBuildKeyValueTable("Downstream truth diagnostics", "Not run.");
    return
end
checkSummary = truthDiagOutput.check_summary;
metrics = truthDiagOutput.truth_metrics;
labels = [ ...
    "Aircraft with overlap"; ...
    "Visible truth samples"; ...
    "Truth samples inside display"; ...
    "Detections"; ...
    "True positives"; ...
    "False alarms"; ...
    "Missed truth CPIs"; ...
    "Range gate"; ...
    "Doppler gate"; ...
    "Time gate"];
values = [ ...
    compose("%d / %d", checkSummary.n_aircraft_overlap, checkSummary.n_aircraft_total); ...
    compose("%d", checkSummary.n_truth_visible_samples); ...
    compose("%d", checkSummary.n_truth_samples_in_display); ...
    compose("%d", checkSummary.n_detections); ...
    compose("%d", metrics.n_tp); ...
    compose("%d", metrics.n_fa); ...
    compose("%d", metrics.n_miss); ...
    compose("%.0f [m]", metrics.gate_range_m); ...
    compose("%.1f [Hz]", metrics.gate_doppler_hz); ...
    compose("%.3f [s]", metrics.time_gate_s)];
tableOut = localBuildKeyValueTable(labels, values);
end
function tableOut = localBuildTruthPerPartTable(truthDiagOutput)
tableOut = table();
if ~localHasTruthDiagnostics(truthDiagOutput)
    return
end
checkSummary = truthDiagOutput.check_summary;
if isempty(checkSummary.per_part_truth_points)
    return
end
partIndex = (1 : numel(checkSummary.per_part_truth_points)).';
truthPoints = checkSummary.per_part_truth_points(:);
detections = checkSummary.per_part_detection_counts(:);
tableOut = table(partIndex, truthPoints, detections, 'VariableNames', {'PartIndex', 'TruthSamples', 'Detections'});
end
function tableOut = localBuildDetectionErrorTable(metrics)
[rangeCount, rangeMean, rangeSigma, rangeMedian, rangeRMS] = localComputeErrorStats(metrics.det_range_err_m);
[dopplerCount, dopplerMean, dopplerSigma, dopplerMedian, dopplerRMS] = localComputeErrorStats(metrics.det_doppler_err_hz);
quantity = ["Range error [m]"; "Doppler error [Hz]"];
countTP = [rangeCount; dopplerCount];
meanValue = localRoundFinite([rangeMean; dopplerMean], 2);
sigmaValue = localRoundFinite([rangeSigma; dopplerSigma], 2);
medianValue = localRoundFinite([rangeMedian; dopplerMedian], 2);
rmsValue = localRoundFinite([rangeRMS; dopplerRMS], 2);
tableOut = table(quantity, countTP, meanValue, sigmaValue, medianValue, rmsValue, 'VariableNames', {'Quantity', 'CountTP', 'Mean', 'Sigma', 'Median', 'RMS'});
end
function tableOut = localBuildValidationInterpretationTable(validationSummary, truthDiagOutput, runSignalPhysicsReadinessCheck, runWrapperReplay)
questions = [ ...
    "Is the generated IQ internally consistent with the requested scene?"; ...
    "Did the synthetic targets land where truth predicted?"; ...
    "Does the downstream detector recover truth-aligned targets?"; ...
    "What validation claim does this run support?"];
answers = strings(size(questions));
evidence = strings(size(questions));
if ~runSignalPhysicsReadinessCheck || isempty(validationSummary)
    answers(1) = "Not assessed in this run.";
    evidence(1) = "Set runSignalPhysicsReadinessCheck = true to run the session-level readiness gate.";
    answers(2) = "Not assessed in this run.";
    evidence(2) = "Target-placement evidence comes from the readiness gate.";
else
    answers(1) = localTernary(validationSummary.readiness.overall_pass, "Yes.", "No.");
    evidence(1) = "Failure classes: " + localJoinStringArray(validationSummary.readiness.failure_classes) + ".";
    answers(2) = localTernary(validationSummary.readiness.target_placement_pass, "Yes at the current readiness thresholds.", "No, at least one target missed the placement thresholds.");
    evidence(2) = localBuildTargetPlacementEvidence(validationSummary.readiness.per_target);
end
if ~runWrapperReplay
    answers(3) = "Not assessed in this run.";
    evidence(3) = "Set runWrapperReplay = true to run the packaged-session workflow and truth comparison.";
elseif ~localHasTruthDiagnostics(truthDiagOutput)
    answers(3) = "Wrapper replay ran, but no truth-diagnostic bundle was available.";
    evidence(3) = "Check whether runBistaticAnalysisSession returned truth_diag_input.";
else
    metrics = truthDiagOutput.truth_metrics;
    answers(3) = localTernary(metrics.n_tp > 0, "Yes, the detector produced truth-matched hits.", "No true positives under the current gates.");
    evidence(3) = compose("TP=%d, FA=%d, missed truth CPIs=%d.", metrics.n_tp, metrics.n_fa, metrics.n_miss);
end
[answers(4), evidence(4)] = localClassifyValidationUsefulness(validationSummary, truthDiagOutput, runSignalPhysicsReadinessCheck, runWrapperReplay);
tableOut = table(questions, answers, evidence, 'VariableNames', {'Question', 'Answer', 'Evidence'});
end
function [label, evidence] = localClassifyValidationUsefulness(validationSummary, truthDiagOutput, runSignalPhysicsReadinessCheck, runWrapperReplay)
if ~runSignalPhysicsReadinessCheck || isempty(validationSummary)
    if runWrapperReplay && localHasTruthDiagnostics(truthDiagOutput)
        label = "Exploratory only.";
        evidence = "Downstream truth metrics exist, but the signal-physics readiness gate was skipped.";
    else
        label = "Configuration only.";
        evidence = "Neither the readiness gate nor downstream truth replay completed in this run.";
    end
    return
end
failureClasses = string(validationSummary.readiness.failure_classes);
failureClasses = failureClasses(strlength(failureClasses) > 0);
onlyVerticalColumnFailure = numel(failureClasses) == 1 && failureClasses(1) == "vertical_column_defect";
hasTruthDiagnostics = localHasTruthDiagnostics(truthDiagOutput);
nTP = 0;
nFA = 0;
nMiss = 0;
if hasTruthDiagnostics
    nTP = truthDiagOutput.truth_metrics.n_tp;
    nFA = truthDiagOutput.truth_metrics.n_fa;
    nMiss = truthDiagOutput.truth_metrics.n_miss;
end
if validationSummary.readiness.overall_pass
    if hasTruthDiagnostics && nTP > 0
        label = "Useful for intermediate workflow validation.";
        evidence = "Readiness PASS and the downstream detector produced truth-matched hits. This is still not a field-equivalent benchmark.";
    elseif hasTruthDiagnostics
        label = "Internally consistent, but downstream recovery was not demonstrated in this run.";
        evidence = compose("Readiness PASS, but TP=%d, FA=%d, and missed truth CPIs=%d under the current gates.", nTP, nFA, nMiss);
    else
        label = "Internally consistent; downstream usefulness was not checked in this run.";
        evidence = "Readiness PASS and wrapper replay was skipped or did not return truth metrics.";
    end
elseif onlyVerticalColumnFailure
    if hasTruthDiagnostics && nTP > 0
        label = "Useful for debugging and controlled comparisons, but not for benchmark scoring.";
        evidence = "Target placement is usable and truth-matched detections exist, but vertical Doppler-column artifacts remain.";
    else
        label = "Useful only for signal-chain debugging.";
        evidence = "The main remaining failure is vertical_column_defect and downstream evidence is limited.";
    end
else
    label = "Not ready for downstream validation.";
    evidence = "Readiness failed on " + localJoinStringArray(failureClasses) + ".";
end
if ~runWrapperReplay && validationSummary.readiness.overall_pass
    evidence = evidence + " Wrapper replay was skipped in this run.";
end
end
function evidence = localBuildTargetPlacementEvidence(perTargetSummary)
if isempty(perTargetSummary)
    evidence = "No per-target readiness summary was produced.";
    return
end
parts = strings(numel(perTargetSummary), 1);
for idx = 1 : numel(perTargetSummary)
    target = perTargetSummary(idx);
    parts(idx) = string(target.target_id) + " R " + compose("%.2f/%.2f bins", target.median_abs_range_residual_bins, target.worst_abs_range_residual_bins) + ", fd " + compose("%.2f/%.2f bins", target.median_abs_doppler_residual_bins, target.worst_abs_doppler_residual_bins);
end
evidence = strjoin(parts, " | ");
end
function match = localFindByTargetId(items, targetId)
match = struct([]);
if isempty(items)
    return
end
targetIds = string({items.target_id});
matchIdx = find(targetIds == string(targetId), 1, 'first');
if ~isempty(matchIdx)
    match = items(matchIdx);
end
end
function count = localCountAlignedTruthTracks(analysisOutput)
count = 0;
if isempty(analysisOutput) || ~isfield(analysisOutput, 'adsb_aligned') || isempty(analysisOutput.adsb_aligned)
    return
end
count = sum(arrayfun(@(track) any(isfinite(track.R_excess_m)), analysisOutput.adsb_aligned));
end
function tf = localHasTruthDiagnostics(truthDiagOutput)
tf = isstruct(truthDiagOutput) && ~isempty(truthDiagOutput) && isfield(truthDiagOutput, 'truth_metrics') && ~isempty(truthDiagOutput.truth_metrics);
end
function [countValue, meanValue, sigmaValue, medianValue, rmsValue] = localComputeErrorStats(values)
values = double(values(:));
values = values(isfinite(values));
countValue = numel(values);
if isempty(values)
    meanValue = NaN;
    sigmaValue = NaN;
    medianValue = NaN;
    rmsValue = NaN;
    return
end
meanValue = mean(values, 'omitnan');
sigmaValue = std(values, 0, 'omitnan');
medianValue = median(values, 'omitnan');
rmsValue = sqrt(mean(values .^ 2, 'omitnan'));
end
function tableOut = localBuildKeyValueTable(labels, values)
labels = string(labels(:));
values = string(values(:));
tableOut = table(labels, values, 'VariableNames', {'Metric', 'Value'});
end
function values = localRoundFinite(values, digits)
mask = isfinite(values);
values(mask) = round(values(mask), digits);
end
function label = localFormatPassFail(tf)
if tf
    label = "PASS";
else
    label = "FAIL";
end
end
function label = localFormatYesNo(tf)
if tf
    label = "yes";
else
    label = "no";
end
end
function label = localJoinStringArray(values)
if isempty(values)
    label = "none";
    return
end
labelValues = string(values);
labelValues = labelValues(strlength(labelValues) > 0);
if isempty(labelValues)
    label = "none";
else
    label = strjoin(labelValues, ", ");
end
end
function label = localTernary(tf, trueLabel, falseLabel)
if tf
    label = string(trueLabel);
else
    label = string(falseLabel);
end
end
