classdef SyntheticHDTVSessionGeneratorTest < matlab.unittest.TestCase
    %SYNTHETICHDTVSESSIONGENERATORTEST Verification-aligned coverage for v1 increment 1.

    properties (Constant)
        ApprovedTxLLA = [42.310278, -71.236667, 431.9];
        ApprovedRxLLA = [42.2999333, -71.349333, 15.0];
    end

    methods (TestClassSetup)
        function addProjectPaths(testCase)
            tests_folder = fileparts(mfilename('fullpath'));
            src_folder = fileparts(tests_folder);
            repo_root = fileparts(src_folder);

            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(src_folder));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repo_root, 'BistaticDataAnalysis')));
        end
    end

    methods (TestMethodSetup)
        function suppressFigures(testCase)
            original_visibility = get(groot, 'DefaultFigureVisible');
            set(groot, 'DefaultFigureVisible', 'off');
            testCase.addTeardown(@() set(groot, 'DefaultFigureVisible', original_visibility));
        end
    end

    methods (Test)
        function testBaselineScenarioConfigDeclaresApprovedSites(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);

            cfg = buildSyntheticHDTVBaselineScenarioConfig('OutputRoot', fixture.Folder);

            testCase.verifyEqual(cfg.tx_lla_deg_m, testCase.ApprovedTxLLA, AbsTol=1e-12);
            testCase.verifyEqual(cfg.rx_lla_deg_m, testCase.ApprovedRxLLA, AbsTol=1e-12);
            testCase.verifyEqual(cfg.purpose, 'signal_physics_readiness_gate');
            testCase.verifyEqual(cfg.capture_repetitions, 1);
            testCase.verifyGreaterThan(cfg.part_duration_s, 0);
            testCase.verifyEqual(cfg.seed_echo_source_mode, 'not_applicable');
            testCase.verifyEqual(cfg.target_echo_dataset_mode, 'not_applicable');
            testCase.verifyFalse(cfg.seed_echo_conditioning.enabled);
            testCase.verifyEqual(cfg.echo_generation_model, 'not_applicable');
            testCase.verifyFalse(cfg.full_seed_comparison_enabled);
            testCase.verifyFalse(cfg.diagnostic_conditioned_echo_enabled);
        end

        function testTerrainSceneCoversApprovedGeometry(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            cfg = buildSyntheticHDTVBaselineScenarioConfig('OutputRoot', fixture.Folder);

            terrain_info = helperSyntheticBuildSceneTerrain(cfg);

            testCase.verifyTrue(terrain_info.tx_in_coverage);
            testCase.verifyTrue(terrain_info.rx_in_coverage);
            testCase.verifyGreaterThan(terrain_info.raster_size(1), 0);
            testCase.verifyGreaterThan(terrain_info.raster_size(2), 0);
        end

        function testGeneratedTruthIsTraceableAndConventionCompatible(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            cfg = buildSyntheticHDTVBaselineScenarioConfig('OutputRoot', fixture.Folder);
            truth_bundle = helperSyntheticGenerateTruth(cfg);
            truth_path = fullfile(fixture.Folder, 'adsb_test.txt');

            helperSyntheticWriteADSBTruth(truth_path, truth_bundle.adsb_tracks);
            loaded_tracks = loadADSBTruth({truth_path}, 'Verbose', false);
            geometry = helperDeriveTxRxGeometry(cfg.tx_lla_deg_m, cfg.rx_lla_deg_m);

            testCase.verifyEqual(numel(loaded_tracks), numel(truth_bundle.adsb_tracks));
            testCase.verifyEqual( ...
                SyntheticHDTVSessionGeneratorTest.localTrackKeys(loaded_tracks), ...
                SyntheticHDTVSessionGeneratorTest.localTrackKeys(truth_bundle.adsb_tracks));
            testCase.verifyEqual(truth_bundle.bistatic_tracks(1).L_m, ...
                geometry.baseline_3d_m, AbsTol=1e-9);
            testCase.verifyEqual(numel(truth_bundle.targets(1).t_rel_s), ...
                numel(truth_bundle.targets(1).t_utc));
        end

        function testBaselineTargetsStayOutsideNearRangeGuard(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            cfg = buildSyntheticHDTVBaselineScenarioConfig('OutputRoot', fixture.Folder);
            truth_bundle = helperSyntheticGenerateTruth(cfg);

            min_range_excess_m = arrayfun( ...
                @(track) min(track.R_excess_m), ...
                truth_bundle.bistatic_tracks);

            testCase.verifyGreaterThan(min(min_range_excess_m), 5e3);
        end

        function testBasebandArtifactsReadBackAsTwoChannelFiles(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            artifact = SyntheticHDTVSessionGeneratorTest.localGenerateSession( ...
                fixture.Folder, 'bb_readback_session');
            radar_file_path = SyntheticHDTVSessionGeneratorTest.localResolveRelativePath( ...
                artifact.session_folder, artifact.radar_files{1});

            reader = comm.BasebandFileReader(radar_file_path, 'SamplesPerFrame', 32);
            cleanup_reader = onCleanup(@() release(reader));
            samples = reader();
            metadata = reader.Metadata;

            testCase.verifySize(samples, [32, 2]);
            testCase.verifyEqual(double(reader.SampleRate), ...
                artifact.scenario_config.sample_rate_hz, AbsTol=1e-9);
            testCase.verifyEqual(double(reader.CenterFrequency), ...
                artifact.scenario_config.center_frequency_hz, AbsTol=1e-9);
            testCase.verifyEqual(double(metadata.Duration_s), ...
                artifact.scenario_config.part_duration_s, AbsTol=1e-12);
            testCase.verifyEqual(char(string(metadata.SessionID)), artifact.session_id);
        end

        function testProbeSeedHelperCreatesReadableDualChannelFile(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);

            [seed_path, seed_info] = helperSyntheticCreateProbeSeed( ...
                'OutputFolder', fixture.Folder, ...
                'FileName', 'probe_seed.bb');

            reader = comm.BasebandFileReader(seed_path, 'SamplesPerFrame', 64);
            cleanup_reader = onCleanup(@() release(reader));
            samples = reader();
            metadata = reader.Metadata;

            testCase.verifyEqual(seed_info.seed_file_path, seed_path);
            testCase.verifySize(samples, [64, 2]);
            testCase.verifyGreaterThan(rms(double(samples(:, 2))), 0);
            testCase.verifyEqual(char(string(metadata.SignalMode)), 'probe_seed_v1');
        end

        function testSeedWaveformLoadsAndNormalizesToTargetRMS(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            seed_path = SyntheticHDTVSessionGeneratorTest.localCreateProbeSeed(fixture.Folder);
            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'SeedSourcePath', seed_path, ...
                'SeedTargetRMS', 0.2);
            n_output_samples = round(cfg.sample_rate_hz * cfg.part_duration_s);

            [seed_waveform, seed_info] = helperSyntheticLoadSeedWaveform(cfg, n_output_samples, 0);

            testCase.verifySize(seed_waveform, [n_output_samples, 1]);
            testCase.verifyEqual(rms(double(seed_waveform)), cfg.seed_target_rms, RelTol=1e-2);
            testCase.verifyEqual(string(seed_info.seed_path), string(seed_path));
            testCase.verifyEqual(seed_info.seed_channel_index, cfg.seed_channel_index);
        end

        function testSeedSourceResolverAcceptsManifestFolderAndSessionID(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            source_artifact = SyntheticHDTVSessionGeneratorTest.localGenerateSeedBackedSession( ...
                fixture.Folder, 'seed_source_fixture_session');
            expected_seed_path = SyntheticHDTVSessionGeneratorTest.localResolveRelativePath( ...
                source_artifact.session_folder, source_artifact.radar_files{1});

            [seed_from_manifest, manifest_info] = helperSyntheticResolveSeedSourcePath( ...
                source_artifact.manifest_path, ...
                'CapturesRoot', fixture.Folder);
            [seed_from_folder, folder_info] = helperSyntheticResolveSeedSourcePath( ...
                source_artifact.session_folder, ...
                'CapturesRoot', fixture.Folder);
            [seed_from_session_id, session_info] = helperSyntheticResolveSeedSourcePath( ...
                source_artifact.session_id, ...
                'CapturesRoot', fixture.Folder);

            testCase.verifyEqual(char(seed_from_manifest), expected_seed_path);
            testCase.verifyEqual(char(seed_from_folder), expected_seed_path);
            testCase.verifyEqual(char(seed_from_session_id), expected_seed_path);
            testCase.verifyEqual(manifest_info.input_kind, "session_manifest");
            testCase.verifyEqual(folder_info.input_kind, "session_manifest");
            testCase.verifyEqual(session_info.input_kind, "session_manifest");
        end

        function testSeedSourceResolverAcceptsExtensionlessFieldCaptureFiles(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            [manifest_path, session_folder, radar_file_path] = ...
                SyntheticHDTVSessionGeneratorTest.localCreateExtensionlessSeedSession( ...
                    fixture.Folder, 'extensionless_seed_fixture_session');

            [seed_from_manifest, manifest_info] = helperSyntheticResolveSeedSourcePath( ...
                manifest_path, ...
                'CapturesRoot', fixture.Folder);
            [seed_from_folder, folder_info] = helperSyntheticResolveSeedSourcePath( ...
                session_folder, ...
                'CapturesRoot', fixture.Folder);
            [seed_from_session_id, session_info] = helperSyntheticResolveSeedSourcePath( ...
                'extensionless_seed_fixture_session', ...
                'CapturesRoot', fixture.Folder);
            [seed_from_file, file_info] = helperSyntheticResolveSeedSourcePath( ...
                radar_file_path, ...
                'CapturesRoot', fixture.Folder);

            testCase.verifyEqual(char(seed_from_manifest), radar_file_path);
            testCase.verifyEqual(char(seed_from_folder), radar_file_path);
            testCase.verifyEqual(char(seed_from_session_id), radar_file_path);
            testCase.verifyEqual(char(seed_from_file), radar_file_path);
            testCase.verifyEqual(manifest_info.input_kind, "session_manifest");
            testCase.verifyEqual(folder_info.input_kind, "session_manifest");
            testCase.verifyEqual(session_info.input_kind, "session_manifest");
            testCase.verifyEqual(file_info.input_kind, "baseband_file");
        end

        function testSeedWaveformLoadAcceptsManifestShortcutAndNormalizesWindowsDriveSlash(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            source_artifact = SyntheticHDTVSessionGeneratorTest.localGenerateSeedBackedSession( ...
                fixture.Folder, 'seed_manifest_fixture_session');
            expected_seed_path = SyntheticHDTVSessionGeneratorTest.localResolveRelativePath( ...
                source_artifact.session_folder, source_artifact.radar_files{1});
            manifest_path = string(source_artifact.manifest_path);

            if ispc
                manifest_path = "/" + replace(manifest_path, "\", "/");
            end

            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'SessionID', 'manifest_seed_load_session', ...
                'SeedSourcePath', manifest_path, ...
                'SignalMode', 'seed_backed_bistatic_v1');
            n_output_samples = round(cfg.sample_rate_hz * cfg.part_duration_s);

            [seed_waveform, seed_info] = helperSyntheticLoadSeedWaveform(cfg, n_output_samples, 0);

            testCase.verifySize(seed_waveform, [n_output_samples, 1]);
            testCase.verifyEqual(string(seed_info.seed_path), string(expected_seed_path));
            testCase.verifyGreaterThan(rms(double(seed_waveform)), 0);
        end

        function testSeedWaveformLoadAcceptsExtensionlessFieldCaptureManifest(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            [manifest_path, ~, radar_file_path] = ...
                SyntheticHDTVSessionGeneratorTest.localCreateExtensionlessSeedSession( ...
                    fixture.Folder, 'extensionless_seed_load_session');

            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'SessionID', 'extensionless_manifest_seed_load_session', ...
                'SeedSourcePath', manifest_path, ...
                'SignalMode', 'seed_backed_bistatic_v1');
            n_output_samples = round(cfg.sample_rate_hz * cfg.part_duration_s);

            [seed_waveform, seed_info] = helperSyntheticLoadSeedWaveform(cfg, n_output_samples, 0);

            testCase.verifySize(seed_waveform, [n_output_samples, 1]);
            testCase.verifyEqual(string(seed_info.seed_path), string(radar_file_path));
            testCase.verifyGreaterThan(rms(double(seed_waveform)), 0);
        end

        function testEchoSeedConditioningSuppressesProbePilotAndPreservesRMS(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            probe_seed_folder = fullfile(fixture.Folder, 'probe_seed');
            [seed_path, seed_info] = helperSyntheticCreateProbeSeed( ...
                'OutputFolder', probe_seed_folder, ...
                'FileName', 'probe_seed.bb');
            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'SeedSourcePath', seed_path, ...
                'SignalMode', 'seed_backed_bistatic_v1', ...
                'SeedEchoConditioningEnabled', true);
            n_output_samples = round(cfg.sample_rate_hz * cfg.part_duration_s);

            [seed_waveform, ~] = helperSyntheticLoadSeedWaveform(cfg, n_output_samples, 0);
            [conditioned_seed, conditioning_summary] = helperSyntheticBuildConditionedEchoSeed( ...
                seed_waveform, ...
                cfg.sample_rate_hz, ...
                cfg.seed_echo_conditioning);

            raw_tone_power_db = SyntheticHDTVSessionGeneratorTest.localMeasureTonePower( ...
                seed_waveform, ...
                cfg.sample_rate_hz, ...
                seed_info.pilot_offset_hz);
            conditioned_tone_power_db = SyntheticHDTVSessionGeneratorTest.localMeasureTonePower( ...
                conditioned_seed, ...
                cfg.sample_rate_hz, ...
                seed_info.pilot_offset_hz);

            testCase.verifyTrue(conditioning_summary.enabled);
            testCase.verifyTrue(conditioning_summary.pilot_suppression_applied);
            testCase.verifyLessThan(conditioned_tone_power_db, raw_tone_power_db - 10);
            testCase.verifyEqual( ...
                rms(double(conditioned_seed)), ...
                rms(double(seed_waveform)), ...
                RelTol=5e-2);
        end

        function testManifestPreservesWorkflowFieldsAndSyntheticProvenance(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            artifact = SyntheticHDTVSessionGeneratorTest.localGenerateSession( ...
                fixture.Folder, 'manifest_session');

            manifest = helperLoadSessionManifest(artifact.manifest_path);
            raw_manifest = jsondecode(fileread(artifact.manifest_path));

            testCase.verifyEqual(manifest.session_id, artifact.session_id);
            testCase.verifyEqual(numel(manifest.radar_files), 1);
            testCase.verifyEqual(numel(manifest.adsb_files), 1);
            testCase.verifyEqual(raw_manifest.data_origin, 'synthetic');
            testCase.verifyEqual(raw_manifest.scenario_id, artifact.scenario_config.scenario_id);
            testCase.verifyEqual(raw_manifest.generator_name, artifact.scenario_config.generator_name);
            testCase.verifyEqual(raw_manifest.truth_source, artifact.scenario_config.truth_source);
        end

        function testDefaultArchiveMATIsWrittenAndPreservesPerPartChannels(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            cfg = SyntheticHDTVSessionGeneratorTest.localBuildArchiveTestConfig( ...
                fixture.Folder, 'archive_default_session');
            artifact = generateSyntheticHDTVSession('ScenarioConfig', cfg);
            expected_archive_path = fullfile(artifact.session_folder, 'archive', 'synthetic_session_archive.mat');
            archive_bundle = SyntheticHDTVSessionGeneratorTest.localLoadArchiveBundle( ...
                expected_archive_path);
            expected_samples_per_part = round(cfg.sample_rate_hz * cfg.part_duration_s);

            testCase.verifyEqual(artifact.archive_mat_path, expected_archive_path);
            testCase.verifyTrue(exist(expected_archive_path, 'file') == 2);
            testCase.verifyTrue(SyntheticHDTVSessionGeneratorTest.localStructHasFields( ...
                archive_bundle, ...
                SyntheticHDTVSessionGeneratorTest.localArchiveBundleFields()));
            testCase.verifyEqual(archive_bundle.session_id, artifact.session_id);
            testCase.verifyEqual(archive_bundle.channel_contract.channel_1, 'surveillance');
            testCase.verifyEqual(archive_bundle.channel_contract.channel_2, 'reference');
            testCase.verifyEqual(numel(archive_bundle.parts), cfg.capture_repetitions);
            testCase.verifySize( ...
                archive_bundle.parts(1).samples_interleaved, ...
                [expected_samples_per_part, 2]);
            testCase.verifyEqual( ...
                archive_bundle.parts(1).samples_interleaved(:, 1), ...
                archive_bundle.parts(1).surveillance_channel);
            testCase.verifyEqual( ...
                archive_bundle.parts(1).samples_interleaved(:, 2), ...
                archive_bundle.parts(1).reference_channel);
            testCase.verifyEqual(archive_bundle.parts(1).radar_file_rel, artifact.radar_files{1});
            testCase.verifyEqual(archive_bundle.radar_files, artifact.radar_files);
            testCase.verifyTrue(artifact.archive_bundle_summary.saved);
            testCase.verifyEqual(artifact.archive_bundle_summary.num_parts, cfg.capture_repetitions);
            testCase.verifyEqual( ...
                artifact.archive_bundle_summary.num_samples_per_part, ...
                repmat(expected_samples_per_part, 1, cfg.capture_repetitions));
            testCase.verifyEqual( ...
                SyntheticHDTVSessionGeneratorTest.localNormalizeStringArray( ...
                    artifact.archive_bundle_summary.channel_order), ...
                ["surveillance", "reference"]);
        end

        function testManifestIncludesArchiveMetadataWhenEnabled(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            cfg = SyntheticHDTVSessionGeneratorTest.localBuildArchiveTestConfig( ...
                fixture.Folder, 'archive_manifest_session');
            artifact = generateSyntheticHDTVSession('ScenarioConfig', cfg);
            manifest = jsondecode(fileread(artifact.manifest_path));
            expected_samples_per_part = round(cfg.sample_rate_hz * cfg.part_duration_s);

            testCase.verifyTrue(isfield(manifest, 'archive_files'));
            testCase.verifyTrue(isfield(manifest, 'archive_summary'));
            testCase.verifyEqual( ...
                SyntheticHDTVSessionGeneratorTest.localNormalizeStringArray( ...
                    manifest.archive_files), ...
                "archive/synthetic_session_archive.mat");
            testCase.verifyTrue(manifest.archive_summary.saved);
            testCase.verifyEqual(string(manifest.archive_summary.path), ...
                "archive/synthetic_session_archive.mat");
            testCase.verifyEqual(manifest.archive_summary.num_parts, cfg.capture_repetitions);
            testCase.verifyEqual( ...
                reshape(double(manifest.archive_summary.num_samples_per_part), 1, []), ...
                repmat(expected_samples_per_part, 1, cfg.capture_repetitions));
            testCase.verifyEqual( ...
                SyntheticHDTVSessionGeneratorTest.localNormalizeStringArray( ...
                    manifest.archive_summary.channel_order), ...
                ["surveillance", "reference"]);
        end

        function testArchiveMATCanBeDisabled(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            cfg = SyntheticHDTVSessionGeneratorTest.localBuildArchiveTestConfig( ...
                fixture.Folder, 'archive_disabled_session');
            artifact = generateSyntheticHDTVSession( ...
                'ScenarioConfig', cfg, ...
                'SaveArchiveMAT', false);
            manifest = jsondecode(fileread(artifact.manifest_path));
            archive_folder = fullfile(artifact.session_folder, 'archive');

            testCase.verifyFalse(exist(archive_folder, 'dir') == 7);
            testCase.verifyEqual(strlength(string(artifact.archive_mat_path)), 0);
            testCase.verifyFalse(artifact.archive_bundle_summary.saved);
            testCase.verifyEqual(artifact.archive_bundle_summary.num_parts, 0);
            testCase.verifyEmpty(manifest.archive_files);
            testCase.verifyFalse(manifest.archive_summary.saved);
            testCase.verifyEqual(manifest.archive_summary.num_parts, 0);
        end

        function testSeedBackedBasebandChannelsAreNonzeroAndDistinct(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            artifact = SyntheticHDTVSessionGeneratorTest.localGenerateSeedBackedSession( ...
                fixture.Folder, 'seed_backed_readback_session');
            radar_file_path = SyntheticHDTVSessionGeneratorTest.localResolveRelativePath( ...
                artifact.session_folder, artifact.radar_files{1});

            reader = comm.BasebandFileReader(radar_file_path, 'SamplesPerFrame', 8192);
            cleanup_reader = onCleanup(@() release(reader));
            samples = reader();

            testCase.verifyGreaterThan(rms(double(samples(:, 1))), 0);
            testCase.verifyGreaterThan(rms(double(samples(:, 2))), 0);
            testCase.verifyGreaterThan(norm(double(samples(:, 1) - samples(:, 2))), 0);
        end

        function testSeedBackedManifestIncludesSeedProvenance(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            artifact = SyntheticHDTVSessionGeneratorTest.localGenerateSeedBackedSession( ...
                fixture.Folder, 'seed_backed_manifest_session');

            manifest = jsondecode(fileread(artifact.manifest_path));

            testCase.verifyEqual(manifest.signal_mode, 'seed_backed_bistatic_v1');
            testCase.verifyEqual(manifest.echo_generation_model, 'toolbox_wideband_free_space_v1');
            testCase.verifyEqual(manifest.seed_source_path, artifact.scenario_config.seed_source_path);
            testCase.verifyEqual(manifest.seed_channel_index, artifact.scenario_config.seed_channel_index);
            testCase.verifyEqual(manifest.seed_echo_source_mode, artifact.scenario_config.seed_echo_source_mode);
            testCase.verifyEqual(manifest.target_echo_dataset_mode, 'conditioned_target_echo_dataset_v1');
            testCase.verifyEqual( ...
                manifest.target_echo_dataset_label, ...
                'conditioned target-echo dataset (recommended intermediate algorithm-test mode)');
            testCase.verifyTrue(manifest.recommended_intermediate_algorithm_test_mode);
            testCase.verifyTrue(manifest.seed_echo_conditioning.enabled);
            testCase.verifyEqual( ...
                manifest.seed_echo_conditioning.target_echo_source, ...
                artifact.scenario_config.seed_echo_conditioning.target_echo_source);
            testCase.verifyEqual(string(manifest.seed_fixture.kind), "probe_seed");
            testCase.verifyFalse(manifest.full_seed_comparison_enabled);
            testCase.verifyEqual(manifest.readiness_check.status, 'not_run');
            testCase.verifyEqual( ...
                manifest.readiness_check.target_echo_dataset_mode, ...
                manifest.target_echo_dataset_mode);
            testCase.verifyEqual(manifest.reference_gain_db, artifact.scenario_config.reference_gain_db);
            testCase.verifyEqual(manifest.direct_path_gain_db, artifact.scenario_config.direct_path_gain_db);
        end

        function testSeedBackedArtifactKeepsPartSynthesisSummaries(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            artifact = SyntheticHDTVSessionGeneratorTest.localGenerateValidationSeedBackedSession( ...
                fixture.Folder, 'validation_summary_session');

            testCase.verifyTrue(isfield(artifact, 'part_synthesis_summaries'));
            testCase.verifyEqual(numel(artifact.part_synthesis_summaries), 1);
            testCase.verifyEqual(artifact.part_synthesis_summaries{1}.signal_mode, 'seed_backed_bistatic_v1');
            testCase.verifyEqual( ...
                artifact.part_synthesis_summaries{1}.echo_generation_model, ...
                'toolbox_wideband_free_space_v1');
            testCase.verifyEqual( ...
                artifact.part_synthesis_summaries{1}.seed_echo_source_mode, ...
                'conditioned_target_echoes_v1');
            testCase.verifyEqual( ...
                artifact.part_synthesis_summaries{1}.target_echo_dataset_mode, ...
                'conditioned_target_echo_dataset_v1');
            testCase.verifyTrue( ...
                artifact.part_synthesis_summaries{1}.recommended_intermediate_algorithm_test_mode);
            testCase.verifyTrue(artifact.part_synthesis_summaries{1}.echo_seed_conditioning.enabled);
            testCase.verifyEqual( ...
                artifact.part_synthesis_summaries{1}.echo_seed_conditioning.reference_source, ...
                'full_seed');
            testCase.verifyEqual( ...
                artifact.part_synthesis_summaries{1}.echo_seed_conditioning.direct_path_source, ...
                'full_seed');
            testCase.verifyTrue(artifact.part_synthesis_summaries{1}.readiness_eligible_primary_path);
            testCase.verifyEqual( ...
                artifact.part_synthesis_summaries{1}.model_summary.propagation_domain, ...
                'measurement_space_excess_path');
            testCase.verifyEqual( ...
                numel(artifact.part_synthesis_summaries{1}.track_summaries), ...
                numel(artifact.scenario_config.targets));
            testCase.verifyTrue(all(arrayfun( ...
                @(track) all(isfinite(track.delay_samples_range)), ...
                artifact.part_synthesis_summaries{1}.track_summaries)));
        end

        function testTimingOverridesPropagateAcrossTruthAndManifest(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            capture_duration_s = 0.05;
            capture_repetitions = 3;
            capture_spacing_s = 0.10;
            truth_sample_period_s = 0.01;
            expected_active_window_s = capture_duration_s * capture_repetitions + ...
                (capture_repetitions - 1) * capture_spacing_s;

            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'SessionID', 'timing_override_session', ...
                'CaptureDurationS', capture_duration_s, ...
                'CaptureRepetitions', capture_repetitions, ...
                'CaptureRepetitionSpacingS', capture_spacing_s, ...
                'TruthSamplePeriodS', truth_sample_period_s);
            truth_bundle = helperSyntheticGenerateTruth(cfg);
            artifact = generateSyntheticHDTVSession('ScenarioConfig', cfg);
            manifest = helperLoadSessionManifest(artifact.manifest_path);

            testCase.verifyEqual(cfg.expected_overlap_window_s(2), expected_active_window_s, AbsTol=1e-12);
            testCase.verifyEqual(max(truth_bundle.sample_times_s), expected_active_window_s, AbsTol=1e-12);
            testCase.verifyEqual(artifact.part_start_offsets_s, [0; 0.15; 0.30], AbsTol=1e-12);
            testCase.verifyEqual(numel(artifact.radar_files), capture_repetitions);
            testCase.verifyEqual(manifest.capture_duration_s, capture_duration_s, AbsTol=1e-12);
            testCase.verifyEqual(manifest.capture_repetitions, capture_repetitions);
            testCase.verifyEqual(manifest.capture_repetition_spacing_s, capture_spacing_s, AbsTol=1e-12);
            testCase.verifyEqual(manifest.radar_active_window_s, expected_active_window_s, AbsTol=1e-12);
        end

        function testTenSecondMotionVisibleTimingAndTruthSampling(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'SessionID', 'motion_visible_session', ...
                'SampleRateHz', 5e4, ...
                'CaptureDurationS', 1.0, ...
                'CaptureRepetitions', 10, ...
                'CaptureRepetitionSpacingS', 0.0, ...
                'TruthSamplePeriodS', 0.10);

            cfg.targets = helperSyntheticBuildValidationConfidenceTargets( ...
                cfg.tx_lla_deg_m, ...
                cfg.rx_lla_deg_m, ...
                cfg.expected_overlap_window_s(2));

            truth_bundle = helperSyntheticGenerateTruth(cfg);
            artifact = generateSyntheticHDTVSession('ScenarioConfig', cfg);

            testCase.verifyEqual(cfg.expected_overlap_window_s(2), 10.0, AbsTol=1e-12);
            testCase.verifyEqual(truth_bundle.sample_times_s(1), 0.0, AbsTol=1e-12);
            testCase.verifyEqual(max(truth_bundle.sample_times_s), 10.0, AbsTol=1e-12);
            testCase.verifyEqual(artifact.part_start_offsets_s, (0 : 9).', AbsTol=1e-12);
            testCase.verifyEqual(numel(artifact.radar_files), 10);
            testCase.verifyGreaterThan( ...
                max(truth_bundle.bistatic_tracks(1).R_excess_m) - min(truth_bundle.bistatic_tracks(1).R_excess_m), ...
                1.0);
        end

        function testCustomTargetsDriveSavedTruthAndADSBOutput(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'SessionID', 'custom_target_session');
            custom_targets = cfg.targets;
            capture_window_s = cfg.expected_overlap_window_s(2);

            custom_targets(1).target_id = 'TGT901';
            custom_targets(1).icao_hex = 'ABC901';
            custom_targets(1).callsign = 'EDIT901';
            custom_targets(1).echo_gain_db = -18;
            custom_targets(1).waypoints_lla_deg_m = [ ...
                42.314500, -71.332000, 3100; ...
                42.316000, -71.322000, 3200; ...
                42.317500, -71.312000, 3300];
            custom_targets(1).time_of_arrival_s = [0; capture_window_s / 2; capture_window_s];
            cfg.targets = custom_targets;

            artifact = generateSyntheticHDTVSession('ScenarioConfig', cfg);
            traceability_truth = load(artifact.traceability_truth_path, 'truth_bundle');
            adsb_truth_path = SyntheticHDTVSessionGeneratorTest.localResolveRelativePath( ...
                artifact.session_folder, artifact.adsb_files{1});
            loaded_adsb_tracks = loadADSBTruth({adsb_truth_path}, 'Verbose', false);

            adsb_idx = SyntheticHDTVSessionGeneratorTest.localFindTrackIndexByCallsign( ...
                loaded_adsb_tracks, 'EDIT901');

            testCase.verifyEqual(traceability_truth.truth_bundle.targets(1).target_id, 'TGT901');
            testCase.verifyEqual(traceability_truth.truth_bundle.targets(1).callsign, 'EDIT901');
            testCase.verifyEqual( ...
                traceability_truth.truth_bundle.targets(1).lat_deg(1), ...
                custom_targets(1).waypoints_lla_deg_m(1, 1), AbsTol=1e-9);
            testCase.verifyEqual( ...
                traceability_truth.truth_bundle.targets(1).lon_deg(end), ...
                custom_targets(1).waypoints_lla_deg_m(end, 2), AbsTol=1e-9);
            testCase.verifyEqual(loaded_adsb_tracks(adsb_idx).callsign, 'EDIT901');
            testCase.verifyEqual(loaded_adsb_tracks(adsb_idx).hex, 'ABC901');
            testCase.verifyEqual( ...
                loaded_adsb_tracks(adsb_idx).lat_deg(1), ...
                custom_targets(1).waypoints_lla_deg_m(1, 1), AbsTol=1e-6);
            testCase.verifyEqual( ...
                loaded_adsb_tracks(adsb_idx).lon_deg(end), ...
                custom_targets(1).waypoints_lla_deg_m(end, 2), AbsTol=1e-6);
        end

        function testPackagedSessionReplaysThroughCurrentWrapper(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            artifact = SyntheticHDTVSessionGeneratorTest.localGenerateSession( ...
                fixture.Folder, 'wrapper_session');

            out = SyntheticHDTVSessionGeneratorTest.localRunWrapperQuietly( ...
                artifact.session_id, ...
                'DatasetRoot', fixture.Folder, ...
                'Verbose', false, ...
                'Use2DGeographicFallback', true, ...
                'SaveTruthDiagnosticSnapshot', false, ...
                'SaveDetectorReplaySnapshot', false);

            testCase.verifyEqual(char(out.session_id), artifact.session_id);
            testCase.verifyEqual(numel(out.radar_files), 1);
            testCase.verifyEqual(numel(out.adsb_files), 1);
            testCase.verifyTrue(isfield(out, 'adsb_aligned'));
        end

        function testPackagedSessionReplaysThroughCurrentWrapperWithoutArchiveMAT(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            artifact = SyntheticHDTVSessionGeneratorTest.localGenerateSessionWithoutArchive( ...
                fixture.Folder, 'wrapper_no_archive_session');

            out = SyntheticHDTVSessionGeneratorTest.localRunWrapperQuietly( ...
                artifact.session_id, ...
                'DatasetRoot', fixture.Folder, ...
                'Verbose', false, ...
                'Use2DGeographicFallback', true, ...
                'SaveTruthDiagnosticSnapshot', false, ...
                'SaveDetectorReplaySnapshot', false);

            testCase.verifyEqual(char(out.session_id), artifact.session_id);
            testCase.verifyEqual(numel(out.radar_files), 1);
            testCase.verifyEqual(numel(out.adsb_files), 1);
            testCase.verifyTrue(isfield(out, 'adsb_aligned'));
        end

        function testSeedBackedPackagedSessionReplaysThroughCurrentWrapper(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            artifact = SyntheticHDTVSessionGeneratorTest.localGenerateSeedBackedSession( ...
                fixture.Folder, 'seed_backed_wrapper_session');

            out = SyntheticHDTVSessionGeneratorTest.localRunWrapperQuietly( ...
                artifact.session_id, ...
                'DatasetRoot', fixture.Folder, ...
                'Verbose', false, ...
                'Use2DGeographicFallback', true, ...
                'SaveTruthDiagnosticSnapshot', false, ...
                'SaveDetectorReplaySnapshot', false);

            n_aligned_tracks = sum(arrayfun(@(track) any(isfinite(track.R_excess_m)), out.adsb_aligned));

            testCase.verifyEqual(char(out.session_id), artifact.session_id);
            testCase.verifyEqual(numel(out.radar_files), 1);
            testCase.verifyEqual(numel(out.adsb_files), 1);
            testCase.verifyGreaterThanOrEqual(n_aligned_tracks, 1);
        end

        function testScenarioSummaryHelperReportsWaypointEndpoints(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'CaptureDurationS', 0.08, ...
                'CaptureRepetitions', 2, ...
                'CaptureRepetitionSpacingS', 0.12);

            [scenario_summary, target_summary_table] = helperSyntheticSummarizeScenarioConfig(cfg);

            testCase.verifyEqual(scenario_summary.part_duration_s, 0.08, AbsTol=1e-12);
            testCase.verifyEqual(scenario_summary.capture_repetitions, 2);
            testCase.verifyEqual(scenario_summary.capture_repetition_spacing_s, 0.12, AbsTol=1e-12);
            testCase.verifyEqual(scenario_summary.radar_active_window_s, 0.28, AbsTol=1e-12);
            testCase.verifyEqual(scenario_summary.n_targets, numel(cfg.targets));
            testCase.verifyEqual(target_summary_table.TargetID(1), string(cfg.targets(1).target_id));
            testCase.verifyEqual(target_summary_table.Callsign(2), string(cfg.targets(2).callsign));
            testCase.verifyEqual( ...
                target_summary_table.StartLatDeg(1), ...
                cfg.targets(1).waypoints_lla_deg_m(1, 1), AbsTol=1e-12);
            testCase.verifyEqual( ...
                target_summary_table.EndLonDeg(2), ...
                cfg.targets(2).waypoints_lla_deg_m(end, 2), AbsTol=1e-12);
        end

        function testScenarioSummaryDistinguishesRecommendedAndComparisonModes(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            seed_path = SyntheticHDTVSessionGeneratorTest.localCreateProbeSeed(fixture.Folder);

            recommended_cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'SeedSourcePath', seed_path, ...
                'SignalMode', 'seed_backed_bistatic_v1');
            comparison_cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'SeedSourcePath', seed_path, ...
                'SignalMode', 'seed_backed_bistatic_v1', ...
                'SeedEchoConditioningEnabled', false);

            [recommended_summary, ~] = helperSyntheticSummarizeScenarioConfig(recommended_cfg);
            [comparison_summary, ~] = helperSyntheticSummarizeScenarioConfig(comparison_cfg);

            testCase.verifyEqual( ...
                recommended_summary.target_echo_dataset_mode, ...
                "conditioned_target_echo_dataset_v1");
            testCase.verifyEqual( ...
                recommended_summary.target_echo_dataset_label, ...
                "conditioned target-echo dataset (recommended intermediate algorithm-test mode)");
            testCase.verifyTrue(recommended_summary.recommended_intermediate_algorithm_test_mode);
            testCase.verifyEqual( ...
                comparison_summary.target_echo_dataset_mode, ...
                "full_seed_comparison_dataset_v1");
            testCase.verifyEqual( ...
                comparison_summary.target_echo_dataset_label, ...
                "full-seed comparison dataset");
            testCase.verifyFalse(comparison_summary.recommended_intermediate_algorithm_test_mode);
        end

        function testScenarioOverviewPlotHelperRunsForConfiguredTruth(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            cfg = buildSyntheticHDTVBaselineScenarioConfig('OutputRoot', fixture.Folder);
            truth_bundle = helperSyntheticGenerateTruth(cfg);
            plot_handles = helperSyntheticPlotScenarioOverview(cfg, truth_bundle);
            testCase.addTeardown(@() close(plot_handles.figure));

            testCase.verifyTrue(isgraphics(plot_handles.figure));
            testCase.verifyTrue(isgraphics(plot_handles.geometry_axes, 'axes'));
            testCase.verifyTrue(isgraphics(plot_handles.altitude_axes, 'axes'));
            testCase.verifyTrue(isgraphics(plot_handles.range_axes, 'axes'));
            testCase.verifyTrue(isgraphics(plot_handles.doppler_axes, 'axes'));
        end

        function testScenarioOverviewPlotUsesSyntheticTruthLabels(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            cfg = SyntheticHDTVSessionGeneratorTest.localBuildValidationSeedBackedConfig( ...
                fixture.Folder, 'preview_label_session');
            truth_bundle = helperSyntheticGenerateTruth(cfg);
            plot_handles = helperSyntheticPlotScenarioOverview(cfg, truth_bundle);
            testCase.addTeardown(@() close(plot_handles.figure));

            geometry_title = string(plot_handles.geometry_axes.Title.String);
            range_lines = findobj(plot_handles.range_axes, 'Type', 'line');
            range_labels = string(get(range_lines, 'DisplayName'));

            testCase.verifyTrue(any(contains(geometry_title, "Sampled Target Motion")));
            testCase.verifyTrue(any(contains(range_labels, "Synthetic Truth:")));
        end

        function testTruthGlobePreviewHelperRendersSnapshotWhenViewerAvailable(testCase)
            testCase.assumeTrue(exist('trackingGlobeViewer', 'file') == 2);

            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            cfg = buildSyntheticHDTVBaselineScenarioConfig('OutputRoot', fixture.Folder);
            truth_bundle = helperSyntheticGenerateTruth(cfg);
            globe_preview = helperSyntheticPlotTruthGlobePreview( ...
                cfg, ...
                truth_bundle, ...
                'ShowLiveViewer', false, ...
                'CloseViewerOnReturn', true, ...
                'SnapshotFigureVisibility', 'off');
            testCase.addTeardown(@() SyntheticHDTVSessionGeneratorTest.localCloseGraphicsHandles( ...
                [globe_preview.snapshot_figure; globe_preview.viewer_figure]));

            testCase.verifyEqual(globe_preview.status, "ready");
            testCase.verifyTrue(isgraphics(globe_preview.snapshot_figure, 'figure'));
            testCase.verifyTrue(isgraphics(globe_preview.snapshot_axes, 'axes'));
            testCase.verifyClass(globe_preview.snapshot_image, 'uint8');
            testCase.verifyEqual(size(globe_preview.snapshot_image, 3), 3);
            testCase.verifyGreaterThan(size(globe_preview.snapshot_image, 1), 0);
            testCase.verifyGreaterThan(size(globe_preview.snapshot_image, 2), 0);
            testCase.verifyEqual(globe_preview.n_targets, double(numel(cfg.targets)));
            testCase.verifyEqual(strlength(globe_preview.fallback_reason), 0);
            testCase.verifyFalse(globe_preview.used_live_viewer);
        end

        function testTruthGlobePreviewHelperReturnsDiagnosticSnapshotOnViewerFailure(testCase)
            testCase.assumeTrue(exist('trackingGlobeViewer', 'file') == 2);

            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            cfg = buildSyntheticHDTVBaselineScenarioConfig('OutputRoot', fixture.Folder);
            truth_bundle = helperSyntheticGenerateTruth(cfg);
            globe_preview = helperSyntheticPlotTruthGlobePreview( ...
                cfg, ...
                truth_bundle, ...
                'ShowLiveViewer', false, ...
                'CloseViewerOnReturn', true, ...
                'SnapshotFigureVisibility', 'off', ...
                'Basemap', '__invalid_basemap__');
            testCase.addTeardown(@() SyntheticHDTVSessionGeneratorTest.localCloseGraphicsHandles( ...
                [globe_preview.snapshot_figure; globe_preview.viewer_figure]));

            testCase.verifyEqual(globe_preview.status, "failed");
            testCase.verifyTrue(isgraphics(globe_preview.snapshot_figure, 'figure'));
            testCase.verifyTrue(isgraphics(globe_preview.snapshot_axes, 'axes'));
            testCase.verifyClass(globe_preview.snapshot_image, 'uint8');
            testCase.verifyEqual(size(globe_preview.snapshot_image, 3), 3);
            testCase.verifyGreaterThan(size(globe_preview.snapshot_image, 1), 0);
            testCase.verifyGreaterThan(size(globe_preview.snapshot_image, 2), 0);
            testCase.verifyNotEmpty(globe_preview.fallback_reason);
            testCase.verifyTrue(contains(globe_preview.message, "failed"));
            testCase.verifyFalse(globe_preview.used_live_viewer);
        end

        function testValidationFigureConsolidatesRawReadinessPanels(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            artifact = SyntheticHDTVSessionGeneratorTest.localGenerateValidationSeedBackedSession( ...
                fixture.Folder, 'validation_overlay_session');

            validation_summary = SyntheticHDTVSessionGeneratorTest.localRunValidationQuietly( ...
                artifact, ...
                'PlotFigures', true, ...
                'PrecheckFigures', false, ...
                'FigureVisibility', 'off', ...
                'Verbose', false);
            validation_figure = validation_summary.primary_part.figure_handles.validation;
            testCase.addTeardown(@() SyntheticHDTVSessionGeneratorTest.localCloseGraphicsHandles( ...
                validation_figure));

            testCase.verifyTrue(isgraphics(validation_figure, 'figure'));
            testCase.verifyEqual(string(validation_figure.Name), ...
                "Synthetic IQ Validation - Consolidated Readiness");

            raw_axis = findobj(validation_figure, 'Type', 'axes', 'Tag', 'raw_rdm');
            spot_axis = findobj(validation_figure, 'Type', 'axes', 'Tag', 'raw_spot_check');
            spectrum_axis = findobj(validation_figure, 'Type', 'axes', 'Tag', 'spectrum');
            lag_axis = findobj(validation_figure, 'Type', 'axes', 'Tag', 'lag');
            raw_title_text = join(string(raw_axis.Title.String), newline);
            spot_title_text = join(string(spot_axis.Title.String), newline);

            testCase.verifyNumElements(raw_axis, 1);
            testCase.verifyNumElements(spot_axis, 1);
            testCase.verifyNumElements(spectrum_axis, 1);
            testCase.verifyNumElements(lag_axis, 1);
            testCase.verifyTrue(contains(raw_title_text, "raw RDM"));
            testCase.verifyTrue(contains(spot_title_text, "raw spot check"));
            testCase.verifyTrue(contains(raw_title_text, newline));
            testCase.verifyTrue(contains(spot_title_text, newline));
            testCase.verifyEqual(string(raw_axis.Title.Interpreter), "none");
            testCase.verifyEqual(string(spot_axis.Title.Interpreter), "none");
            testCase.verifyEqual(string(spectrum_axis.Title.Interpreter), "none");
            testCase.verifyEqual(string(lag_axis.Title.Interpreter), "none");

            raw_display_names = arrayfun( ...
                @(line_handle) string(line_handle.DisplayName), ...
                findobj(raw_axis, 'Type', 'line'));
            spot_display_names = arrayfun( ...
                @(line_handle) string(line_handle.DisplayName), ...
                findobj(spot_axis, 'Type', 'line'));

            testCase.verifyTrue(any(contains(raw_display_names, "Synthetic Truth:")));
            testCase.verifyTrue(any(contains(spot_display_names, "Raw Spot Check:")));
            [expected_ymin_km, expected_ymax_km] = ...
                SyntheticHDTVSessionGeneratorTest.localExpectedValidationRangeLimitsKm( ...
                    validation_summary.primary_part.target_summaries);
            testCase.verifyEqual(raw_axis.YLim(1), expected_ymin_km, AbsTol=1e-9);
            testCase.verifyEqual(spot_axis.YLim(1), expected_ymin_km, AbsTol=1e-9);
            testCase.verifyEqual(raw_axis.YLim(2), expected_ymax_km, AbsTol=1e-9);
            testCase.verifyEqual(spot_axis.YLim(2), expected_ymax_km, AbsTol=1e-9);

            colorbars = findall(validation_figure, 'Type', 'ColorBar');
            testCase.verifyNumElements(colorbars, 2);
            testCase.verifyTrue(all(arrayfun( ...
                @(colorbar_handle) string(colorbar_handle.Label.String) == "CAF Magnitude [dB]", ...
                colorbars)));
            testCase.verifyFalse(contains(raw_title_text, "After ECA-C"));
        end

        function testValidationHelperReturnsRawSpotCheckOutputs(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            artifact = SyntheticHDTVSessionGeneratorTest.localGenerateValidationSeedBackedSession( ...
                fixture.Folder, 'raw_spot_check_session');

            validation_summary = SyntheticHDTVSessionGeneratorTest.localRunValidationQuietly( ...
                artifact, ...
                'PlotFigures', true, ...
                'PrecheckFigures', false, ...
                'FigureVisibility', 'off', ...
                'Verbose', false);
            raw_spot_check_figure = validation_summary.primary_part.figure_handles.raw_spot_check;
            spot_check_table = validation_summary.spot_check_table;
            spot_check_target_ids = SyntheticHDTVSessionGeneratorTest.localSpotCheckTargetIDs( ...
                validation_summary.spot_check_targets);
            testCase.addTeardown(@() SyntheticHDTVSessionGeneratorTest.localCloseGraphicsHandles( ...
                raw_spot_check_figure));

            testCase.verifyTrue(isgraphics(raw_spot_check_figure, 'figure'));
            testCase.verifyGreaterThan(validation_summary.spot_check_query_time_s, 0);
            testCase.verifyEqual(raw_spot_check_figure, ...
                validation_summary.primary_part.figure_handles.validation);
            testCase.verifyEqual(string(raw_spot_check_figure.Name), ...
                "Synthetic IQ Validation - Consolidated Readiness");
            testCase.verifyEqual(string(spot_check_table.Properties.VariableNames), [ ...
                "TargetID", ...
                "Callsign", ...
                "TruthRangeM", ...
                "TruthDopplerHz", ...
                "ObservedRangeM", ...
                "ObservedDopplerHz", ...
                "RangeResidualM", ...
                "DopplerResidualHz", ...
                "LocalProminenceDB", ...
                "PassWithinGate"]);
            testCase.verifyEqual(height(spot_check_table), numel(artifact.scenario_config.targets));
            testCase.verifyEqual(height(spot_check_table), numel(validation_summary.spot_check_targets));
            testCase.verifyEqual(string(spot_check_table.TargetID), spot_check_target_ids);
            testCase.verifyLessThanOrEqual(height(spot_check_table), 5);
        end

        function testValidationHelperSelectsFirstFiveEligibleSpotCheckTargets(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            artifact = SyntheticHDTVSessionGeneratorTest.localGenerateSpotCheckSelectionSession( ...
                fixture.Folder, 'spot_check_selection_session');

            validation_summary = SyntheticHDTVSessionGeneratorTest.localRunValidationQuietly( ...
                artifact, ...
                'PlotFigures', false, ...
                'PrecheckFigures', false, ...
                'Verbose', false);
            actual_target_ids = SyntheticHDTVSessionGeneratorTest.localSpotCheckTargetIDs( ...
                validation_summary.spot_check_targets);
            expected_target_ids = SyntheticHDTVSessionGeneratorTest.localExpectedSpotCheckTargetIDs( ...
                artifact, ...
                validation_summary.spot_check_query_time_s, ...
                5);

            testCase.verifyEqual(height(validation_summary.spot_check_table), 5);
            testCase.verifyEqual(actual_target_ids, expected_target_ids);
            testCase.verifyEqual(string(validation_summary.spot_check_table.TargetID), expected_target_ids);
        end

        function testValidationHelperRawSpotCheckFindsFinitePeaksInConfidenceFixture(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            artifact = SyntheticHDTVSessionGeneratorTest.localGenerateSpotCheckSelectionSession( ...
                fixture.Folder, 'spot_check_confidence_session');

            validation_summary = SyntheticHDTVSessionGeneratorTest.localRunValidationQuietly( ...
                artifact, ...
                'PlotFigures', false, ...
                'PrecheckFigures', false, ...
                'Verbose', false);
            spot_check_table = validation_summary.spot_check_table;

            testCase.verifyEqual(height(spot_check_table), 5);
            testCase.verifyTrue(all(spot_check_table.PassWithinGate));
            testCase.verifyTrue(all(isfinite(spot_check_table.TruthRangeM)));
            testCase.verifyTrue(all(isfinite(spot_check_table.TruthDopplerHz)));
            testCase.verifyTrue(all(isfinite(spot_check_table.ObservedRangeM)));
            testCase.verifyTrue(all(isfinite(spot_check_table.ObservedDopplerHz)));
            testCase.verifyTrue(all(isfinite(spot_check_table.RangeResidualM)));
            testCase.verifyTrue(all(isfinite(spot_check_table.DopplerResidualHz)));
            testCase.verifyTrue(all(isfinite(spot_check_table.LocalProminenceDB)));
        end

        function testValidationHelperCanRestrictReadinessToPrimaryPart(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            seed_path = SyntheticHDTVSessionGeneratorTest.localCreateProbeSeed(fixture.Folder);
            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'SessionID', 'primary_part_only_validation_session', ...
                'SeedSourcePath', seed_path, ...
                'SignalMode', 'seed_backed_bistatic_v1', ...
                'SampleRateHz', 5e4, ...
                'CaptureDurationS', 1.0, ...
                'CaptureRepetitions', 3, ...
                'CaptureRepetitionSpacingS', 0.0, ...
                'TruthSamplePeriodS', 0.10, ...
                'DirectPathDelaySamples', 1.0, ...
                'UseStochasticNoise', false);
            cfg.targets = helperSyntheticBuildValidationConfidenceTargets( ...
                cfg.tx_lla_deg_m, ...
                cfg.rx_lla_deg_m, ...
                cfg.expected_overlap_window_s(2));
            artifact = generateSyntheticHDTVSession('ScenarioConfig', cfg);

            validation_summary = SyntheticHDTVSessionGeneratorTest.localRunValidationQuietly( ...
                artifact, ...
                'PartIndex', 1, ...
                'PlotFigures', false, ...
                'PrecheckFigures', false, ...
                'Verbose', false);

            testCase.verifyEqual(validation_summary.evaluated_part_indices, 1);
            testCase.verifyEqual(numel(validation_summary.per_part), 1);
            testCase.verifyEqual(validation_summary.primary_part.part_index, 1);
            testCase.verifyEqual(validation_summary.readiness.n_parts_validated, 1);
            testCase.verifyGreaterThan(height(validation_summary.spot_check_table), 0);
        end

        function testWalkthroughSessionIDHelperRefreshesPriorAutoIDOnRerun(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            prior_auto_session_id = 'seed_demo_old';
            mkdir(fullfile(fixture.Folder, prior_auto_session_id));

            [session_id, last_auto_generated_session_id, resolution_info] = ...
                helperSyntheticResolveWalkthroughSessionID( ...
                    'OutputRoot', fixture.Folder, ...
                    'SessionID', prior_auto_session_id, ...
                    'PreviousAutoSessionID', prior_auto_session_id, ...
                    'PreferredAutoSessionID', 'seed_demo_new');

            testCase.verifyEqual(session_id, 'seed_demo_new');
            testCase.verifyEqual(last_auto_generated_session_id, 'seed_demo_new');
            testCase.verifyTrue(resolution_info.used_auto_session_id);
            testCase.verifyTrue(resolution_info.refreshed_previous_auto_session_id);
            testCase.verifyFalse(resolution_info.preserved_requested_session_id);
        end

        function testWalkthroughSessionIDHelperRefreshesLegacyAutoIDWithoutSentinel(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            legacy_auto_session_id = 'seed_demo_20260714T080355';
            mkdir(fullfile(fixture.Folder, legacy_auto_session_id));

            [session_id, last_auto_generated_session_id, resolution_info] = ...
                helperSyntheticResolveWalkthroughSessionID( ...
                    'OutputRoot', fixture.Folder, ...
                    'SessionID', legacy_auto_session_id, ...
                    'PreferredAutoSessionID', 'seed_demo_20260715T100700000');

            testCase.verifyEqual(session_id, 'seed_demo_20260715T100700000');
            testCase.verifyEqual(last_auto_generated_session_id, 'seed_demo_20260715T100700000');
            testCase.verifyTrue(resolution_info.used_auto_session_id);
            testCase.verifyTrue(resolution_info.refreshed_previous_auto_session_id);
            testCase.verifyFalse(resolution_info.preserved_requested_session_id);
        end

        function testWalkthroughSessionIDHelperPreservesPinnedSessionID(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);

            [session_id, last_auto_generated_session_id, resolution_info] = ...
                helperSyntheticResolveWalkthroughSessionID( ...
                    'OutputRoot', fixture.Folder, ...
                    'SessionID', 'manual_session', ...
                    'PreviousAutoSessionID', 'seed_demo_old', ...
                    'PreferredAutoSessionID', 'seed_demo_new');

            testCase.verifyEqual(session_id, 'manual_session');
            testCase.verifyEqual(last_auto_generated_session_id, "");
            testCase.verifyFalse(resolution_info.used_auto_session_id);
            testCase.verifyFalse(resolution_info.refreshed_previous_auto_session_id);
            testCase.verifyTrue(resolution_info.preserved_requested_session_id);
        end

        function testWalkthroughSessionIDHelperAddsSuffixForAutoIDCollision(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            mkdir(fullfile(fixture.Folder, 'seed_demo_candidate'));

            [session_id, last_auto_generated_session_id, resolution_info] = ...
                helperSyntheticResolveWalkthroughSessionID( ...
                    'OutputRoot', fixture.Folder, ...
                    'PreferredAutoSessionID', 'seed_demo_candidate');

            testCase.verifyEqual(session_id, 'seed_demo_candidate_rerun_01');
            testCase.verifyEqual(last_auto_generated_session_id, 'seed_demo_candidate_rerun_01');
            testCase.verifyTrue(resolution_info.used_auto_session_id);
            testCase.verifyFalse(resolution_info.refreshed_previous_auto_session_id);
        end

        function testGenerateSyntheticHDTVSessionReportsSessionCollisionRecovery(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            SyntheticHDTVSessionGeneratorTest.localGenerateSession( ...
                fixture.Folder, 'existing_session');
            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'SessionID', 'existing_session');

            caught_error = [];
            try
                generateSyntheticHDTVSession('ScenarioConfig', cfg);
            catch ME
                caught_error = ME;
            end

            testCase.verifyEqual(caught_error.identifier, ...
                'generateSyntheticHDTVSession:sessionExists');
            testCase.verifyTrue(contains( ...
                caught_error.message, ...
                'clear the walkthrough auto-generated sessionID'));
        end

        function testValidationHelperReturnsClosedLoopSummary(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            artifact = SyntheticHDTVSessionGeneratorTest.localGenerateValidationSeedBackedSession( ...
                fixture.Folder, 'closed_loop_validation_session');

            validation_summary = SyntheticHDTVSessionGeneratorTest.localRunValidationQuietly( ...
                artifact, ...
                'PlotFigures', false, ...
                'PrecheckFigures', false, ...
                'Verbose', false);

            n_finite_observed_targets = sum(arrayfun( ...
                @(target) isfinite(target.observed_peak_range_m) && isfinite(target.observed_peak_doppler_hz), ...
                validation_summary.target_summaries));

            testCase.verifyTrue(validation_summary.integrity.overall_pass);
            testCase.verifyEqual( ...
                validation_summary.direct_path.comparison_delay_samples, ...
                artifact.scenario_config.direct_path_delay_samples, AbsTol=1e-12);
            testCase.verifyEqual( ...
                numel(validation_summary.target_summaries), ...
                numel(artifact.scenario_config.targets));
            testCase.verifyGreaterThanOrEqual(n_finite_observed_targets, 1);
            testCase.verifyEqual(numel(validation_summary.per_part), 1);
            testCase.verifyGreaterThan(validation_summary.primary_part.readiness.range_bin_spacing_m, 0);
            testCase.verifyGreaterThan(validation_summary.primary_part.readiness.doppler_bin_spacing_hz, 0);
            testCase.verifyTrue(validation_summary.readiness.seed_preservation.overall_pass);
            testCase.verifyTrue(validation_summary.readiness.direct_path.overall_pass);
            testCase.verifyTrue(validation_summary.readiness.target_placement_pass);
            testCase.verifyEqual( ...
                validation_summary.target_echo_dataset_mode, ...
                "conditioned_target_echo_dataset_v1");
            testCase.verifyEqual( ...
                validation_summary.readiness.target_echo_dataset_mode, ...
                'conditioned_target_echo_dataset_v1');
            testCase.verifyTrue( ...
                validation_summary.readiness.recommended_intermediate_algorithm_test_mode);
        end

        function testValidationHelperUpdatesManifestAndReloadsFromManifestPath(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            artifact = SyntheticHDTVSessionGeneratorTest.localGenerateValidationSeedBackedSession( ...
                fixture.Folder, 'validation_reload_session');

            validation_summary = SyntheticHDTVSessionGeneratorTest.localRunValidationQuietly( ...
                artifact.manifest_path, ...
                'PlotFigures', false, ...
                'PrecheckFigures', false, ...
                'Verbose', false);

            manifest = jsondecode(fileread(artifact.manifest_path));

            testCase.verifyEqual(validation_summary.source_type, "manifest");
            testCase.verifyEqual( ...
                manifest.readiness_check.target_echo_dataset_mode, ...
                'conditioned_target_echo_dataset_v1');
            testCase.verifyEqual( ...
                manifest.readiness_check.target_echo_dataset_label, ...
                'conditioned target-echo dataset (recommended intermediate algorithm-test mode)');
            testCase.verifyTrue(isfield(manifest, 'seed_fixture'));
        end

        function testValidationHelperReportsRawSpotCheckMetricAssumptions(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            artifact = SyntheticHDTVSessionGeneratorTest.localGenerateValidationSeedBackedSession( ...
                fixture.Folder, 'validation_prominence_session');

            validation_summary = SyntheticHDTVSessionGeneratorTest.localRunValidationQuietly( ...
                artifact, ...
                'PlotFigures', false, ...
                'PrecheckFigures', false, ...
                'Verbose', false);

            testCase.verifyTrue(isfield(validation_summary.assumptions, 'target_observation_policy'));
            testCase.verifyTrue(isfield(validation_summary.assumptions, 'spot_check_metric'));
            testCase.verifyTrue(contains( ...
                string(validation_summary.assumptions.target_observation_policy), ...
                "raw pre-ECA-C"));
            testCase.verifyTrue(contains( ...
                string(validation_summary.assumptions.spot_check_metric), ...
                "LocalProminenceDB"));
            testCase.verifyTrue(all(isfinite(validation_summary.spot_check_table.LocalProminenceDB)));
        end

        function testFullSeedComparisonSeparatesRecommendedAndReferenceModes(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            cfg = SyntheticHDTVSessionGeneratorTest.localBuildValidationSeedBackedConfig( ...
                fixture.Folder, 'validation_compare_session');
            cfg.full_seed_comparison_enabled = true;
            cfg.diagnostic_conditioned_echo_enabled = true;

            artifact = generateSyntheticHDTVSession('ScenarioConfig', cfg);
            validation_summary = SyntheticHDTVSessionGeneratorTest.localRunValidationQuietly( ...
                artifact, ...
                'PlotFigures', false, ...
                'PrecheckFigures', false, ...
                'RunEchoModelComparison', true, ...
                'Verbose', false);
            comparison = validation_summary.diagnostic_echo_model_comparison;

            testCase.verifyEqual(comparison.status, 'completed');
            testCase.verifyEqual( ...
                comparison.primary.target_echo_dataset_mode, ...
                "conditioned_target_echo_dataset_v1");
            testCase.verifyEqual( ...
                comparison.diagnostic.target_echo_dataset_mode, ...
                "full_seed_comparison_dataset_v1");
        end

        function testTruthAndMetadataRepeatAcrossReruns(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            run_a_root = fullfile(fixture.Folder, 'run_a');
            run_b_root = fullfile(fixture.Folder, 'run_b');
            session_id = 'repeatable_session';

            artifact_a = SyntheticHDTVSessionGeneratorTest.localGenerateSession(run_a_root, session_id);
            artifact_b = SyntheticHDTVSessionGeneratorTest.localGenerateSession(run_b_root, session_id);
            truth_text_a = fileread(SyntheticHDTVSessionGeneratorTest.localResolveRelativePath( ...
                artifact_a.session_folder, artifact_a.adsb_files{1}));
            truth_text_b = fileread(SyntheticHDTVSessionGeneratorTest.localResolveRelativePath( ...
                artifact_b.session_folder, artifact_b.adsb_files{1}));
            manifest_a = jsondecode(fileread(artifact_a.manifest_path));
            manifest_b = jsondecode(fileread(artifact_b.manifest_path));

            testCase.verifyEqual(truth_text_a, truth_text_b);
            testCase.verifyEqual( ...
                jsonencode(SyntheticHDTVSessionGeneratorTest.localCanonicalizeManifest(manifest_a)), ...
                jsonencode(SyntheticHDTVSessionGeneratorTest.localCanonicalizeManifest(manifest_b)));
        end

        function testBaselineScenarioIntentAndOverlapRemainExplicit(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            cfg = buildSyntheticHDTVBaselineScenarioConfig('OutputRoot', fixture.Folder);
            truth_bundle = helperSyntheticGenerateTruth(cfg);

            testCase.verifyEqual(cfg.expected_overlap_window_s(1), 0, AbsTol=1e-12);
            testCase.verifyEqual(cfg.expected_overlap_window_s(2), cfg.part_duration_s, AbsTol=1e-12);
            testCase.verifyGreaterThanOrEqual(min(truth_bundle.sample_times_s), 0);
            testCase.verifyLessThanOrEqual(max(truth_bundle.sample_times_s), cfg.expected_overlap_window_s(2));
        end
    end

    methods (Static, Access = private)
        function artifact = localGenerateSession(output_root, session_id)
            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', output_root, ...
                'SessionID', session_id);
            artifact = generateSyntheticHDTVSession('ScenarioConfig', cfg);
        end

        function artifact = localGenerateSessionWithoutArchive(output_root, session_id)
            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', output_root, ...
                'SessionID', session_id);
            artifact = generateSyntheticHDTVSession( ...
                'ScenarioConfig', cfg, ...
                'SaveArchiveMAT', false);
        end

        function artifact = localGenerateSeedBackedSession(output_root, session_id)
            seed_path = SyntheticHDTVSessionGeneratorTest.localCreateProbeSeed(output_root);
            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', output_root, ...
                'SessionID', session_id, ...
                'SeedSourcePath', seed_path, ...
                'SignalMode', 'seed_backed_bistatic_v1');
            artifact = generateSyntheticHDTVSession('ScenarioConfig', cfg);
        end

        function artifact = localGenerateValidationSeedBackedSession(output_root, session_id)
            cfg = SyntheticHDTVSessionGeneratorTest.localBuildValidationSeedBackedConfig( ...
                output_root, session_id);
            artifact = generateSyntheticHDTVSession('ScenarioConfig', cfg);
        end

        function artifact = localGenerateSpotCheckSelectionSession(output_root, session_id)
            cfg = SyntheticHDTVSessionGeneratorTest.localBuildSpotCheckSelectionConfig( ...
                output_root, session_id);
            artifact = generateSyntheticHDTVSession('ScenarioConfig', cfg);
        end

        function cfg = localBuildArchiveTestConfig(output_root, session_id)
            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', output_root, ...
                'SessionID', session_id, ...
                'SampleRateHz', 5e4, ...
                'CaptureDurationS', 0.02, ...
                'CaptureRepetitions', 3, ...
                'CaptureRepetitionSpacingS', 0.01, ...
                'TruthSamplePeriodS', 0.01, ...
                'UseStochasticNoise', false);
        end

        function cfg = localBuildValidationSeedBackedConfig(output_root, session_id)
            seed_path = SyntheticHDTVSessionGeneratorTest.localCreateProbeSeed(output_root);
            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', output_root, ...
                'SessionID', session_id, ...
                'SeedSourcePath', seed_path, ...
                'SignalMode', 'seed_backed_bistatic_v1', ...
                'CaptureDurationS', 0.20, ...
                'TruthSamplePeriodS', 0.01, ...
                'DirectPathDelaySamples', 1.0, ...
                'UseStochasticNoise', false);

            active_window_s = cfg.expected_overlap_window_s(2);
            cfg.targets = helperSyntheticBuildValidationConfidenceTargets( ...
                cfg.tx_lla_deg_m, ...
                cfg.rx_lla_deg_m, ...
                active_window_s);
        end

        function cfg = localBuildSpotCheckSelectionConfig(output_root, session_id)
            cfg = SyntheticHDTVSessionGeneratorTest.localBuildValidationSeedBackedConfig( ...
                output_root, session_id);
            active_window_s = cfg.expected_overlap_window_s(2);
            cfg.targets = SyntheticHDTVSessionGeneratorTest.localBuildSpotCheckSelectionTargets( ...
                cfg.tx_lla_deg_m, ...
                cfg.rx_lla_deg_m, ...
                active_window_s);
        end

        function seed_path = localCreateProbeSeed(output_root)
            seed_folder = fullfile(output_root, 'seed_fixture');
            [seed_path, ~] = helperSyntheticCreateProbeSeed( ...
                'OutputFolder', seed_folder, ...
                'FileName', 'synthetic_probe_seed.bb');
        end

        function targets = localBuildSpotCheckSelectionTargets(tx_lla_deg_m, rx_lla_deg_m, active_window_s)
            scene_lat_deg = mean([tx_lla_deg_m(1), rx_lla_deg_m(1)]);
            scene_lon_deg = mean([tx_lla_deg_m(2), rx_lla_deg_m(2)]);
            confidence_arrival_s = [0; active_window_s];

            targets = helperSyntheticBuildValidationConfidenceTargets( ...
                tx_lla_deg_m, ...
                rx_lla_deg_m, ...
                active_window_s);
            targets(1).echo_gain_db = -12;
            targets(2).echo_gain_db = -13;

            targets(3) = struct( ...
                'target_id', 'TGT103', ...
                'icao_hex', 'C0F103', ...
                'callsign', 'CONF103', ...
                'echo_gain_db', -14, ...
                'waypoints_lla_deg_m', [ ...
                    scene_lat_deg + 0.045000, scene_lon_deg - 0.015000, 3100; ...
                    scene_lat_deg + 0.045200, scene_lon_deg - 0.014700, 3100], ...
                'time_of_arrival_s', confidence_arrival_s);
            targets(4) = struct( ...
                'target_id', 'TGT104', ...
                'icao_hex', 'C0F104', ...
                'callsign', 'CONF104', ...
                'echo_gain_db', -15, ...
                'waypoints_lla_deg_m', [ ...
                    scene_lat_deg - 0.015000, scene_lon_deg + 0.070000, 2950; ...
                    scene_lat_deg - 0.014700, scene_lon_deg + 0.069700, 2950], ...
                'time_of_arrival_s', confidence_arrival_s);
            targets(5) = struct( ...
                'target_id', 'TGT105', ...
                'icao_hex', 'C0F105', ...
                'callsign', 'CONF105', ...
                'echo_gain_db', -16, ...
                'waypoints_lla_deg_m', [ ...
                    scene_lat_deg + 0.075000, scene_lon_deg + 0.015000, 3400; ...
                    scene_lat_deg + 0.074700, scene_lon_deg + 0.015300, 3400], ...
                'time_of_arrival_s', confidence_arrival_s);
            targets(6) = struct( ...
                'target_id', 'TGT106', ...
                'icao_hex', 'C0F106', ...
                'callsign', 'CONF106', ...
                'echo_gain_db', -17, ...
                'waypoints_lla_deg_m', [ ...
                    scene_lat_deg - 0.050000, scene_lon_deg - 0.085000, 3050; ...
                    scene_lat_deg - 0.050300, scene_lon_deg - 0.084700, 3050], ...
                'time_of_arrival_s', confidence_arrival_s);
        end

        function expected_target_ids = localExpectedSpotCheckTargetIDs(artifact, query_time_s, max_count)
            [~, ~, projection_table] = helperProjectADSBTruthToRangeDoppler( ...
                artifact.truth_bundle.adsb_tracks, ...
                artifact.scenario_config.tx_lla_deg_m, ...
                artifact.scenario_config.rx_lla_deg_m, ...
                artifact.scenario_config.center_frequency_hz, ...
                artifact.scenario_config.radar_epoch_utc, ...
                query_time_s);
            expected_target_ids = strings(0, 1);
            query_tolerance_s = max(eps(max(abs(double(query_time_s)), 1)), 1e-12);

            for idx = 1 : numel(artifact.truth_bundle.targets)
                track_hex = string(artifact.truth_bundle.adsb_tracks(idx).hex);
                row_mask = projection_table.hex == track_hex & ...
                    abs(projection_table.query_time_s - double(query_time_s)) <= query_tolerance_s;
                if ~any(row_mask)
                    continue
                end

                row_idx = find(row_mask, 1, 'first');
                if ~projection_table.valid(row_idx)
                    continue
                end

                expected_target_ids(end + 1, 1) = ...
                    string(artifact.truth_bundle.targets(idx).target_id); %#ok<AGROW>
                if numel(expected_target_ids) >= max_count
                    break
                end
            end
        end

        function spot_check_target_ids = localSpotCheckTargetIDs(spot_check_targets)
            n_targets = numel(spot_check_targets);
            spot_check_target_ids = strings(n_targets, 1);
            for idx = 1 : n_targets
                spot_check_target_ids(idx) = string(spot_check_targets(idx).target_id);
            end
        end

        function [display_range_min_km, display_range_max_km] = localExpectedValidationRangeLimitsKm(target_summaries)
            truth_ranges_m = zeros(0, 1);
            for idx = 1 : numel(target_summaries)
                if ~target_summaries(idx).present_in_dwell
                    continue
                end
                predicted_trace_range_m = double(target_summaries(idx).predicted_trace_range_m(:));
                predicted_trace_range_m = predicted_trace_range_m(isfinite(predicted_trace_range_m));
                truth_ranges_m = [truth_ranges_m; predicted_trace_range_m]; %#ok<AGROW>
            end

            display_range_min_km = min(truth_ranges_m) / 1e3 - 10;
            display_range_max_km = max(truth_ranges_m) / 1e3 + 10;
        end

        function validation_summary = localRunValidationQuietly(session_source, varargin)
            evalc('validation_summary = helperSyntheticValidateGeneratedIQ(session_source, varargin{:});');
        end

        function analysis_output = localRunWrapperQuietly(session_id, varargin)
            evalc('analysis_output = runBistaticAnalysisSession(session_id, varargin{:});');
        end

        function [manifest_path, session_folder, radar_file_path] = localCreateExtensionlessSeedSession(output_root, session_id)
            session_folder = fullfile(output_root, session_id);
            radar_folder = fullfile(session_folder, 'radar');
            if exist(radar_folder, 'dir') ~= 7
                mkdir(radar_folder);
            end

            radar_file_path = fullfile(radar_folder, 'extensionless_capture_part1');
            waveform = complex( ...
                single([zeros(256, 1), exp(1j * 2 * pi * (0 : 255).' / 32)]));
            metadata = struct( ...
                'SessionID', session_id, ...
                'SignalMode', 'field_capture_seed_fixture');
            bbw = comm.BasebandFileWriter( ...
                radar_file_path, ...
                'SampleRate', 8e6, ...
                'CenterFrequency', 599e6, ...
                'Metadata', metadata);
            cleanup_writer = onCleanup(@() release(bbw));
            bbw(waveform);
            clear cleanup_writer

            manifest_path = fullfile(session_folder, 'session_manifest.json');
            manifest = struct( ...
                'manifest_version', 1, ...
                'session_id', session_id, ...
                'session_folder', session_id, ...
                'radar_files', {{'radar/extensionless_capture_part1'}}, ...
                'adsb_files', {{}}, ...
                'log_files', {{}});
            SyntheticHDTVSessionGeneratorTest.localWriteTextFile( ...
                manifest_path, jsonencode(manifest));
        end

        function archive_bundle = localLoadArchiveBundle(archive_path)
            loaded_archive = load(archive_path, 'archive_bundle');
            archive_bundle = loaded_archive.archive_bundle;
        end

        function tf = localStructHasFields(input_struct, field_names)
            tf = all(isfield(input_struct, field_names));
        end

        function field_names = localArchiveBundleFields()
            field_names = { ...
                'session_id', ...
                'session_folder', ...
                'scenario_config', ...
                'truth_bundle', ...
                'manifest', ...
                'header_readback', ...
                'part_start_offsets_s', ...
                'part_synthesis_summaries', ...
                'seed_fixture_summary', ...
                'radar_files', ...
                'adsb_files', ...
                'traceability_truth_path', ...
                'channel_contract', ...
                'parts'};
        end

        function values = localNormalizeStringArray(input_value)
            if isempty(input_value)
                values = strings(1, 0);
                return
            end

            if iscell(input_value)
                values = string(input_value(:).');
                return
            end

            if isstring(input_value)
                values = input_value(:).';
                return
            end

            if ischar(input_value)
                values = string({input_value});
                return
            end

            values = string(input_value);
            values = values(:).';
        end

        function keys = localTrackKeys(track_struct)
            n_tracks = numel(track_struct);
            keys = strings(n_tracks, 1);
            for idx = 1 : n_tracks
                keys(idx) = string(track_struct(idx).hex) + "|" + string(track_struct(idx).callsign);
            end
            keys = sort(keys);
        end

        function abs_path = localResolveRelativePath(session_folder, rel_path)
            abs_path = fullfile(session_folder, strrep(rel_path, '/', filesep));
        end

        function manifest = localCanonicalizeManifest(manifest_in)
            manifest = manifest_in;
            if isfield(manifest, 'generation_time_utc')
                manifest = rmfield(manifest, 'generation_time_utc');
            end
        end

        function idx = localFindTrackIndexByCallsign(track_struct, callsign)
            idx = find(arrayfun(@(track) strcmp(track.callsign, callsign), track_struct), 1, 'first');
        end

        function tone_power_db = localMeasureTonePower(waveform, sample_rate_hz, tone_freq_hz)
            waveform = double(waveform(:));
            analysis_sample_count = min(numel(waveform), 65536);
            analysis_waveform = waveform(1:analysis_sample_count);
            nfft = max(4096, 2 ^ nextpow2(max(analysis_sample_count, 2)));
            [psd_linear, freq_hz] = periodogram( ...
                analysis_waveform, ...
                [], ...
                nfft, ...
                sample_rate_hz, ...
                'centered', ...
                'power');
            [~, tone_idx] = min(abs(freq_hz - tone_freq_hz));
            tone_power_db = 10 * log10(psd_linear(tone_idx) + eps);
        end

        function localCloseGraphicsHandles(graphics_handles)
            graphics_handles = graphics_handles(isgraphics(graphics_handles));
            if isempty(graphics_handles)
                return
            end

            close(graphics_handles);
        end

        function localWriteTextFile(file_path, file_text)
            file_id = fopen(file_path, 'w');
            if file_id < 0
                error('SyntheticHDTVSessionGeneratorTest:fileOpenFailed', ...
                    'Could not open %s for writing.', file_path);
            end

            cleanup_file = onCleanup(@() fclose(file_id));
            fwrite(file_id, file_text, 'char');
            clear cleanup_file
        end
    end
end
