classdef SyntheticHDTVCaptureTruthTest < matlab.unittest.TestCase
    %SYNTHETICHDTVCAPTURETRUTHTEST Coverage for capture-backed truth flow.

    methods (TestClassSetup)
        function addProjectPaths(testCase)
            tests_folder = fileparts(mfilename('fullpath'));
            src_folder = fileparts(tests_folder);
            repo_root = fileparts(src_folder);

            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(src_folder));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repo_root, 'BistaticDataAnalysis')));
        end
    end

    methods (TestMethodSetup)
        function suppressFigures(testCase)
            original_visibility = get(groot, 'DefaultFigureVisible');
            set(groot, 'DefaultFigureVisible', 'off');
            testCase.addTeardown(@() set(groot, 'DefaultFigureVisible', original_visibility));
        end
    end

    methods (Test)
        function testAutoTruthModeSelectsCaptureADSBForManifestSeed(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            capture_fixture = SyntheticHDTVCaptureTruthTest.localCreateCaptureTruthFixture( ...
                fixture.Folder, ...
                'capture_truth_auto_fixture');

            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'SeedSourcePath', capture_fixture.manifest_path);

            testCase.verifyEqual(cfg.truth_source_mode, 'capture_adsb_v1');
            testCase.verifyEqual(cfg.seed_source_kind, 'session_manifest');
            testCase.verifyEqual(cfg.capture_manifest_path, capture_fixture.manifest_path);
        end

        function testAutoTruthModeStaysSyntheticForDirectBasebandInput(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            capture_fixture = SyntheticHDTVCaptureTruthTest.localCreateCaptureTruthFixture( ...
                fixture.Folder, ...
                'direct_baseband_fixture');

            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'SeedSourcePath', capture_fixture.radar_file_paths{1});

            testCase.verifyEqual(cfg.truth_source_mode, 'synthetic_waypoints_v1');
            testCase.verifyEqual(cfg.seed_source_kind, 'baseband_file');
            testCase.verifyEqual(cfg.capture_manifest_path, capture_fixture.manifest_path);
        end

        function testCaptureTruthWindowMaxSCropsTimeline(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            capture_fixture = SyntheticHDTVCaptureTruthTest.localCreateCaptureTruthFixture( ...
                fixture.Folder, ...
                'capture_truth_crop_fixture');

            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'SeedSourcePath', capture_fixture.manifest_path, ...
                'TruthWindowMaxS', 1.25, ...
                'TruthSamplePeriodS', 0.25);
            truth_bundle = helperSyntheticGenerateTruth(cfg);

            testCase.verifyEqual(cfg.selected_truth_window_s, 1.25, AbsTol=1e-12);
            testCase.verifyEqual(truth_bundle.selected_truth_window_s, 1.25, AbsTol=1e-12);
            testCase.verifyEqual(truth_bundle.sample_times_s(end), 1.25, AbsTol=1e-12);
            testCase.verifyLessThanOrEqual(max(truth_bundle.targets(1).t_rel_s), 1.25 + 1e-12);
        end

        function testCaptureTruthSelectionTableReportsRetainAndExcludeReasons(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            capture_fixture = SyntheticHDTVCaptureTruthTest.localCreateCaptureTruthFixture( ...
                fixture.Folder, ...
                'capture_truth_filter_fixture');

            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'SeedSourcePath', capture_fixture.manifest_path, ...
                'TruthSamplePeriodS', 0.25);
            truth_bundle = helperSyntheticGenerateTruth(cfg);
            selection_table = truth_bundle.selection_table;

            testCase.verifyEqual(sum(selection_table.Include), 1);
            testCase.verifyTrue(any(selection_table.Reason == "retained_overlap_geometry_inclusive_v1"));
            testCase.verifyTrue(any(selection_table.Reason == "fewer_than_2_in_window_adsb_fixes"));
            testCase.verifyTrue(any(selection_table.Reason == "below_5km_near_range_guard"));
            testCase.verifyEqual(numel(truth_bundle.targets), 1);
            testCase.verifyEqual(numel(truth_bundle.bistatic_tracks), 1);
        end

        function testCaptureTruthRetainedTracksShareGeneratorTimeline(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            capture_fixture = SyntheticHDTVCaptureTruthTest.localCreateCaptureTruthFixture( ...
                fixture.Folder, ...
                'capture_truth_timeline_fixture');

            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'SeedSourcePath', capture_fixture.manifest_path, ...
                'TruthSamplePeriodS', 0.25);
            truth_bundle = helperSyntheticGenerateTruth(cfg);

            retained_target = truth_bundle.targets(1);
            retained_track = truth_bundle.bistatic_tracks(1);
            valid_mask = isfinite(retained_track.R_excess_m(:)) & ...
                isfinite(retained_track.f_D_hz(:));

            testCase.verifyEqual(retained_target.t_rel_s, truth_bundle.sample_times_s(valid_mask), AbsTol=1e-12);
            testCase.verifyEqual(numel(retained_track.t_utc), numel(truth_bundle.sample_times_s));
            testCase.verifyEqual(max(retained_target.t_rel_s), cfg.selected_truth_window_s, AbsTol=1e-12);
        end

        function testCaptureTruthGainHeuristicIsRecordedAndDeterministic(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            capture_fixture = SyntheticHDTVCaptureTruthTest.localCreateCaptureTruthFixture( ...
                fixture.Folder, ...
                'capture_truth_gain_fixture');

            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'SeedSourcePath', capture_fixture.manifest_path, ...
                'TruthSamplePeriodS', 0.25);
            truth_a = helperSyntheticGenerateTruth(cfg);
            truth_b = helperSyntheticGenerateTruth(cfg);

            gains_a = [truth_a.track_metadata.echo_gain_db];
            gains_b = [truth_b.track_metadata.echo_gain_db];
            policies = string({truth_a.track_metadata.echo_gain_policy});

            testCase.verifyEqual(gains_a, gains_b, AbsTol=1e-12);
            testCase.verifyTrue(all(policies == "range_only_heuristic_v1"));
        end

        function testSessionContextPreservesRadarPartOrder(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            capture_fixture = SyntheticHDTVCaptureTruthTest.localCreateCaptureTruthFixture( ...
                fixture.Folder, ...
                'session_context_fixture');

            session_context = helperSyntheticResolveSessionContext(capture_fixture.manifest_path);

            testCase.verifyEqual(numel(session_context.radar_files), numel(capture_fixture.radar_file_paths));
            testCase.verifyEqual(string(session_context.radar_files), string(capture_fixture.radar_file_paths));
            testCase.verifyEqual(session_context.capture_repetitions, 2);
        end

        function testSeedWaveformLoadingSpansPartBoundary(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            capture_fixture = SyntheticHDTVCaptureTruthTest.localCreateCaptureTruthFixture( ...
                fixture.Folder, ...
                'seed_boundary_fixture');

            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'SeedSourcePath', capture_fixture.manifest_path, ...
                'SignalMode', 'seed_backed_bistatic_v1', ...
                'SampleRateHz', capture_fixture.sample_rate_hz, ...
                'CenterFrequencyHz', capture_fixture.center_frequency_hz, ...
                'SeedTargetRMS', 0.5);

            [seed_waveform, seed_info] = helperSyntheticLoadSeedWaveform(cfg, 8, 0.75);

            testCase.verifySize(seed_waveform, [8, 1]);
            testCase.verifyEqual(string(seed_info.seed_path), string(capture_fixture.radar_file_paths{1}));
            testCase.verifyEqual(numel(seed_info.read_segments), 2);
            testCase.verifyEqual([seed_info.read_segments.file_index], [1, 2]);
            testCase.verifyEqual([seed_info.read_segments.samples_read], [4, 12]);
        end

        function testToolboxSynthesisUsesTruthMetadataWithoutScenarioTargets(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', fixture.Folder, ...
                'SignalMode', 'seed_backed_bistatic_v1', ...
                'SampleRateHz', 1e5, ...
                'CaptureDurationS', 0.01, ...
                'TruthSamplePeriodS', 0.005, ...
                'UseStochasticNoise', false);
            truth_bundle = helperSyntheticGenerateTruth(cfg);
            cfg.targets = struct([]);
            seed_waveform = complex(single(ones(64, 1)), single(zeros(64, 1)));

            [target_echo_waveform, track_summaries] = helperSyntheticSynthesizeToolboxTargetEchoes( ...
                seed_waveform, ...
                cfg, ...
                truth_bundle, ...
                0);

            testCase.verifySize(target_echo_waveform, [64, 1]);
            testCase.verifyEqual(numel(track_summaries), numel(truth_bundle.bistatic_tracks));
            testCase.verifyEqual([track_summaries.echo_gain_db], [truth_bundle.track_metadata.echo_gain_db], AbsTol=1e-12);
            testCase.verifyEqual( ...
                string({track_summaries.echo_gain_policy}), ...
                string({truth_bundle.track_metadata.echo_gain_policy}));
        end
    end

    methods (Static, Access = private)
        function capture_fixture = localCreateCaptureTruthFixture(output_root, session_id)
            sample_rate_hz = 16;
            center_frequency_hz = 599e6;
            radar_epoch_utc = posixtime(datetime(2026, 6, 22, 10, 21, 23, 'TimeZone', 'UTC'));
            session_folder = fullfile(output_root, session_id);
            radar_folder = fullfile(session_folder, 'radar');
            truth_folder = fullfile(session_folder, 'truth');

            if exist(radar_folder, 'dir') ~= 7
                mkdir(radar_folder);
            end
            if exist(truth_folder, 'dir') ~= 7
                mkdir(truth_folder);
            end

            radar_file_paths = { ...
                fullfile(radar_folder, 'capture_part1'), ...
                fullfile(radar_folder, 'capture_part2')};
            SyntheticHDTVCaptureTruthTest.localWriteRadarPart( ...
                radar_file_paths{1}, session_id, sample_rate_hz, center_frequency_hz, ...
                radar_epoch_utc, 1);
            SyntheticHDTVCaptureTruthTest.localWriteRadarPart( ...
                radar_file_paths{2}, session_id, sample_rate_hz, center_frequency_hz, ...
                radar_epoch_utc + 1, 101);

            adsb_tracks = SyntheticHDTVCaptureTruthTest.localBuildFixtureADSBTracks( ...
                output_root, ...
                radar_epoch_utc);
            adsb_path = fullfile(truth_folder, 'adsb_truth.txt');
            helperSyntheticWriteADSBTruth(adsb_path, adsb_tracks);

            manifest = struct( ...
                'manifest_version', 1, ...
                'session_id', session_id, ...
                'session_folder', session_id, ...
                'radar_files', {{'radar/capture_part1', 'radar/capture_part2'}}, ...
                'adsb_files', {{'truth/adsb_truth.txt'}}, ...
                'log_files', {{}}, ...
                'capture_duration_s', 1, ...
                'capture_repetitions', 2, ...
                'capture_repetition_spacing_s', 0, ...
                'radar_active_window_s', 2, ...
                'radar_epoch_utc', radar_epoch_utc, ...
                'sdr_defaults', struct( ...
                    'sample_rate_hz', sample_rate_hz, ...
                    'center_frequency_hz', center_frequency_hz, ...
                    'lo_offset_hz', 0));
            manifest_path = fullfile(session_folder, 'session_manifest.json');
            SyntheticHDTVCaptureTruthTest.localWriteTextFile( ...
                manifest_path, jsonencode(manifest));

            capture_fixture = struct( ...
                'manifest_path', manifest_path, ...
                'session_folder', session_folder, ...
                'radar_file_paths', {radar_file_paths}, ...
                'adsb_path', adsb_path, ...
                'sample_rate_hz', sample_rate_hz, ...
                'center_frequency_hz', center_frequency_hz, ...
                'radar_epoch_utc', radar_epoch_utc);
        end

        function adsb_tracks = localBuildFixtureADSBTracks(output_root, radar_epoch_utc)
            cfg = buildSyntheticHDTVBaselineScenarioConfig( ...
                'OutputRoot', output_root, ...
                'CaptureDurationS', 2, ...
                'CaptureRepetitions', 1, ...
                'TruthSamplePeriodS', 0.25, ...
                'RadarEpochUTC', radar_epoch_utc);
            truth_bundle = helperSyntheticGenerateTruth(cfg);

            retained_track = truth_bundle.adsb_tracks(1);
            retained_track.hex = 'ABC001';
            retained_track.callsign = 'RETAIN1';

            single_fix_track = truth_bundle.adsb_tracks(2);
            single_fix_track.hex = 'ABC002';
            single_fix_track.callsign = 'ONEFIX';
            single_fix_track.t_utc = single_fix_track.t_utc(1);
            single_fix_track.lat_deg = single_fix_track.lat_deg(1);
            single_fix_track.lon_deg = single_fix_track.lon_deg(1);
            single_fix_track.alt_m = single_fix_track.alt_m(1);
            single_fix_track.speed_mps = single_fix_track.speed_mps(1);
            single_fix_track.track_deg = single_fix_track.track_deg(1);
            single_fix_track.vrate_mps = single_fix_track.vrate_mps(1);

            near_range_track = retained_track;
            near_range_track.hex = 'ABC003';
            near_range_track.callsign = 'NEARGRD';
            near_range_track.lat_deg = repmat(cfg.rx_lla_deg_m(1), size(retained_track.t_utc));
            near_range_track.lon_deg = repmat(cfg.rx_lla_deg_m(2), size(retained_track.t_utc));
            near_range_track.alt_m = repmat(cfg.rx_lla_deg_m(3), size(retained_track.t_utc));
            near_range_track.speed_mps = zeros(size(retained_track.t_utc));
            near_range_track.track_deg = zeros(size(retained_track.t_utc));
            near_range_track.vrate_mps = zeros(size(retained_track.t_utc));

            adsb_tracks = [retained_track, single_fix_track, near_range_track];
        end

        function localWriteRadarPart( ...
                file_path, session_id, sample_rate_hz, center_frequency_hz, ...
                recording_utc, sample_offset)
            sample_index = (0 : 15).';
            samples = complex(single([ ...
                sample_offset + sample_index, ...
                2 .* (sample_offset + sample_index)]));
            metadata = struct( ...
                'SessionID', session_id, ...
                'SignalMode', 'field_capture_seed_fixture', ...
                'RecordingUTC', recording_utc, ...
                'Duration_s', numel(sample_index) ./ sample_rate_hz, ...
                'LOOffset', 0);
            writer = comm.BasebandFileWriter( ...
                file_path, ...
                'SampleRate', sample_rate_hz, ...
                'CenterFrequency', center_frequency_hz, ...
                'Metadata', metadata);
            cleanup_writer = onCleanup(@() release(writer));
            writer(samples);
            clear cleanup_writer
        end

        function localWriteTextFile(file_path, file_text)
            file_id = fopen(file_path, 'w');
            if file_id < 0
                error('SyntheticHDTVCaptureTruthTest:fileOpenFailed', ...
                    'Could not open %s for writing.', file_path);
            end

            cleanup_file = onCleanup(@() fclose(file_id));
            fwrite(file_id, file_text, 'char');
            clear cleanup_file
        end
    end
end
