function info = buildBistaticAnalysisArchitecture(opts)
%BUILDBISTATICANALYSISARCHITECTURE Build or open the logical analysis model.
% This quick-reference architecture is intentionally non-executable. It
% documents how the current passive bistatic analysis pipeline moves data
% through the main processing path and the replay/diagnostic side paths.

arguments
    opts.ForceRebuild (1,1) logical = false
    opts.OpenModel (1,1) logical = false
    opts.ExportDiagram (1,1) logical = true
end

architectureDir = fileparts(mfilename("fullpath"));
modelName = "bistaticAnalysisQuickReference";
modelFile = fullfile(architectureDir, modelName + ".slx");
diagramFile = fullfile(architectureDir, modelName + ".png");

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end

originalFolder = pwd;
restoreFolder = onCleanup(@() cd(originalFolder));
cd(architectureDir);

if isfile(modelFile) && ~opts.ForceRebuild
    systemcomposer.openModel(modelName);

    exportInfo = struct( ...
        "exported", false, ...
        "status", "skipped", ...
        "image_path", diagramFile, ...
        "message", "" ...
    );

    if opts.ExportDiagram && ~isfile(diagramFile)
        exportInfo = helperExportArchitectureDiagram(modelName, diagramFile);
    end

    validation = struct( ...
        "status", "skipped", ...
        "message", "Existing model opened without rebuild." ...
    );

    if ~opts.OpenModel
        close_system(modelName, 0);
    end

    info = localBuildInfo(modelName, modelFile, diagramFile, false, exportInfo, validation);
    return
end

if isfile(modelFile)
    try
        delete(modelFile);
    catch ME
        error( ...
            "buildBistaticAnalysisArchitecture:DeleteModelFailed", ...
            "Unable to refresh existing architecture model '%s'. %s", ...
            modelFile, ...
            ME.message ...
        );
    end
end

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end

model = systemcomposer.createModel(modelName);
arch = model.Architecture;

open_system(modelName);

% Root ports highlight durable session inputs and the saved replay artifacts.
helperAddArchitecturePort( ...
    arch, ...
    "session inputs", ...
    "in", ...
    [20 205 30 215] ...
);
helperAddArchitecturePort( ...
    arch, ...
    "truth_diag_input", ...
    "in", ...
    [20 475 30 485] ...
);
helperAddArchitecturePort( ...
    arch, ...
    "detector_replay_input", ...
    "in", ...
    [20 565 30 575] ...
);
helperAddArchitecturePort( ...
    arch, ...
    "tracks", ...
    "out", ...
    [2190 205 2200 215] ...
);
helperAddArchitecturePort( ...
    arch, ...
    "truth metrics", ...
    "out", ...
    [2190 245 2200 255] ...
);
helperAddArchitecturePort( ...
    arch, ...
    "truth snapshot", ...
    "out", ...
    [2190 475 2200 485] ...
);
helperAddArchitecturePort( ...
    arch, ...
    "detector replay snapshot", ...
    "out", ...
    [2190 565 2200 575] ...
);

% Components are placed left-to-right for the main path, with replay and
% snapshot builders below and truth alignment above the assessment stage.
components.sessionResolver = helperAddArchitectureComponent( ...
    arch, ...
    "Session and manifest resolver", ...
    "session inputs", ...
    ["manifest metadata" "ADS-B files"], ...
    [100 180 270 260] ...
);
components.radarIngest = helperAddArchitectureComponent( ...
    arch, ...
    "Radar file discovery and IQ ingest", ...
    "manifest metadata", ...
    "radar parts", ...
    [330 180 500 260] ...
);
components.timingResolution = helperAddArchitectureComponent( ...
    arch, ...
    "Timing and metadata resolution", ...
    ["ingested radar parts" "session metadata"], ...
    ["radar parts" "manifest metadata"], ...
    [560 180 730 260] ...
);
components.refValidation = helperAddArchitectureComponent( ...
    arch, ...
    "Reference-quality and direct-path validation", ...
    ["radar parts" "manifest metadata"], ...
    "validated radar parts", ...
    [790 180 980 260] ...
);
components.clutterMitigation = helperAddArchitectureComponent( ...
    arch, ...
    "Clutter mitigation", ...
    "validated radar parts", ...
    "clutter-suppressed IQ", ...
    [1040 180 1210 260] ...
);
components.rangeDoppler = helperAddArchitectureComponent( ...
    arch, ...
    "Range-Doppler generation", ...
    "clutter-suppressed IQ", ...
    "processed RDM blocks", ...
    [1270 180 1440 260] ...
);
components.detector = helperAddArchitectureComponent( ...
    arch, ...
    "Detector", ...
    "processed RDM blocks", ...
    "detections", ...
    [1500 180 1670 260] ...
);
components.assessmentTracking = helperAddArchitectureComponent( ...
    arch, ...
    "Detection assessment and tracking", ...
    ["detections" "aligned truth"], ...
    ["tracks" "truth metrics"], ...
    [1730 180 1900 260] ...
);
components.visualization = helperAddArchitectureComponent( ...
    arch, ...
    "Geographic and diagnostic visualization", ...
    [ ...
        "analysis tracks" ...
        "analysis truth metrics" ...
        "processed RDM blocks" ...
        "replay detections" ...
        "truth replay metrics" ...
        "detector replay metrics" ...
    ], ...
    ["tracks" "truth metrics"], ...
    [1960 170 2140 280] ...
);
components.truthAlignment = helperAddArchitectureComponent( ...
    arch, ...
    "ADS-B truth load, projection, and alignment", ...
    ["ADS-B files" "manifest metadata"], ...
    "aligned truth", ...
    [1730 40 1900 120] ...
);
components.detectorReplaySnapshotBuilder = helperAddArchitectureComponent( ...
    arch, ...
    "Detector replay snapshot builder", ...
    ["processed RDM blocks" "manifest metadata" "aligned truth"], ...
    "detector replay snapshot", ...
    [1270 360 1440 440] ...
);
components.truthSnapshotBuilder = helperAddArchitectureComponent( ...
    arch, ...
    "Truth-diagnostic snapshot builder", ...
    [ ...
        "processed RDM blocks" ...
        "detections" ...
        "tracks" ...
        "truth metrics" ...
        "aligned truth" ...
    ], ...
    "truth snapshot", ...
    [1730 360 1900 440] ...
);
components.detectorReplaySweep = helperAddArchitectureComponent( ...
    arch, ...
    "Detector replay sweep", ...
    "detector_replay_input", ...
    ["replay detections" "detector replay metrics"], ...
    [1270 540 1440 620] ...
);
components.truthReplayDiagnostics = helperAddArchitectureComponent( ...
    arch, ...
    "Truth replay diagnostics", ...
    "truth_diag_input", ...
    "truth replay metrics", ...
    [1730 540 1900 620] ...
);

connect(arch, [], components.sessionResolver);

connect( ...
    getPort(components.sessionResolver, "manifest metadata"), ...
    getPort(components.radarIngest, "manifest metadata") ...
);
connect( ...
    getPort(components.sessionResolver, "manifest metadata"), ...
    getPort(components.timingResolution, "session metadata") ...
);
connect( ...
    getPort(components.sessionResolver, "ADS-B files"), ...
    getPort(components.truthAlignment, "ADS-B files") ...
);

connect( ...
    getPort(components.radarIngest, "radar parts"), ...
    getPort(components.timingResolution, "ingested radar parts") ...
);

connect( ...
    getPort(components.timingResolution, "radar parts"), ...
    getPort(components.refValidation, "radar parts") ...
);
connect( ...
    getPort(components.timingResolution, "manifest metadata"), ...
    getPort(components.refValidation, "manifest metadata") ...
);
connect( ...
    getPort(components.timingResolution, "manifest metadata"), ...
    getPort(components.truthAlignment, "manifest metadata") ...
);
connect( ...
    getPort(components.timingResolution, "manifest metadata"), ...
    getPort(components.detectorReplaySnapshotBuilder, "manifest metadata") ...
);

connect( ...
    getPort(components.refValidation, "validated radar parts"), ...
    getPort(components.clutterMitigation, "validated radar parts") ...
);
connect( ...
    getPort(components.clutterMitigation, "clutter-suppressed IQ"), ...
    getPort(components.rangeDoppler, "clutter-suppressed IQ") ...
);
connect( ...
    getPort(components.rangeDoppler, "processed RDM blocks"), ...
    getPort(components.detector, "processed RDM blocks") ...
);

connect( ...
    getPort(components.detector, "detections"), ...
    getPort(components.assessmentTracking, "detections") ...
);
connect( ...
    getPort(components.truthAlignment, "aligned truth"), ...
    getPort(components.assessmentTracking, "aligned truth") ...
);

connect( ...
    getPort(components.assessmentTracking, "tracks"), ...
    getPort(components.visualization, "analysis tracks") ...
);
connect( ...
    getPort(components.assessmentTracking, "truth metrics"), ...
    getPort(components.visualization, "analysis truth metrics") ...
);
connect( ...
    getPort(components.rangeDoppler, "processed RDM blocks"), ...
    getPort(components.visualization, "processed RDM blocks") ...
);

connect( ...
    getPort(components.rangeDoppler, "processed RDM blocks"), ...
    getPort(components.detectorReplaySnapshotBuilder, "processed RDM blocks") ...
);
connect( ...
    getPort(components.truthAlignment, "aligned truth"), ...
    getPort(components.detectorReplaySnapshotBuilder, "aligned truth") ...
);

connect( ...
    getPort(components.rangeDoppler, "processed RDM blocks"), ...
    getPort(components.truthSnapshotBuilder, "processed RDM blocks") ...
);
connect( ...
    getPort(components.detector, "detections"), ...
    getPort(components.truthSnapshotBuilder, "detections") ...
);
connect( ...
    getPort(components.assessmentTracking, "tracks"), ...
    getPort(components.truthSnapshotBuilder, "tracks") ...
);
connect( ...
    getPort(components.assessmentTracking, "truth metrics"), ...
    getPort(components.truthSnapshotBuilder, "truth metrics") ...
);
connect( ...
    getPort(components.truthAlignment, "aligned truth"), ...
    getPort(components.truthSnapshotBuilder, "aligned truth") ...
);

connect(arch, [], components.truthReplayDiagnostics);
connect( ...
    getPort(components.truthReplayDiagnostics, "truth replay metrics"), ...
    getPort(components.visualization, "truth replay metrics") ...
);

connect(arch, [], components.detectorReplaySweep);
connect( ...
    getPort(components.detectorReplaySweep, "replay detections"), ...
    getPort(components.visualization, "replay detections") ...
);
connect( ...
    getPort(components.detectorReplaySweep, "detector replay metrics"), ...
    getPort(components.visualization, "detector replay metrics") ...
);

connect(arch, components.visualization, []);
connect(arch, components.truthSnapshotBuilder, []);
connect(arch, components.detectorReplaySnapshotBuilder, []);

model.save;

% Save the structure first, then force one update pass so verification tools
% can operate on a consistent on-disk model.
validation = struct( ...
    "status", "updated", ...
    "message", "Diagram update completed without manual repair." ...
);

try
    set_param(modelName, "SimulationCommand", "update");
catch ME
    validation.status = "error";
    validation.message = ME.message;
end

exportInfo = struct( ...
    "exported", false, ...
    "status", "skipped", ...
    "image_path", diagramFile, ...
    "message", "" ...
);

if opts.ExportDiagram
    exportInfo = helperExportArchitectureDiagram(modelName, diagramFile);
end

model.save;

if ~opts.OpenModel
    close_system(modelName, 0);
end

info = localBuildInfo(modelName, modelFile, diagramFile, true, exportInfo, validation);
end

function info = localBuildInfo(modelName, modelFile, diagramFile, wasRebuilt, exportInfo, validation)
info = struct;
info.model_name = modelName;
info.model_path = modelFile;
info.diagram_path = diagramFile;
info.was_rebuilt = wasRebuilt;
info.export = exportInfo;
info.validation = validation;
info.is_executable_model = false;
info.component_names = [ ...
    "Session and manifest resolver" ...
    "Radar file discovery and IQ ingest" ...
    "Timing and metadata resolution" ...
    "Reference-quality and direct-path validation" ...
    "Clutter mitigation" ...
    "Range-Doppler generation" ...
    "Detector" ...
    "Detection assessment and tracking" ...
    "Geographic and diagnostic visualization" ...
    "ADS-B truth load, projection, and alignment" ...
    "Truth-diagnostic snapshot builder" ...
    "Detector replay snapshot builder" ...
    "Truth replay diagnostics" ...
    "Detector replay sweep" ...
];
info.root_inputs = [ ...
    "session inputs" ...
    "truth_diag_input" ...
    "detector_replay_input" ...
];
info.root_outputs = [ ...
    "tracks" ...
    "truth metrics" ...
    "truth snapshot" ...
    "detector replay snapshot" ...
];
end
